### ISSUE TITLE
Rollercoaster Tycoon 3D: Missing Shader Opcodes 0x05 and 0x06

### ISSUE THREAD

**Issue by JMC47** [citra-emu/citra#1021]
You should run into them just booting the game and navigating the menus to get into any of the modes.  I haven't found a way to avoid them.

According to @yuriks Fire Emblem Awakening also uses them and they're log2 and exp2

Dunno what else to list.

**Comment by yuriks** [comment]
Since these aren't implemented in the interpreter either, I'm guessing they're the cause of that awful bloom in FE 3D scenes. (log2/exp2 are often used to implement shading models.)

**Comment by yuriks** [comment]
I just checked and the instructions don't seem to be even executed in Fire Emblem. (They're part of a branch that isn't taken.)

**Comment by shinyquagsire23** [comment]
This also happens with Cubic Ninja as well in the main menu.
