### ISSUE TITLE
Xenoblade

### ISSUE THREAD

**Issue by brimaster20000** [citra-emu/citra#1029]
![bandicam 2015-08-08 01-50-59-844](https://cloud.githubusercontent.com/assets/13445120/9149443/ec28e0ee-3d6f-11e5-82ca-0fa126df7ae2.jpg)
It constantly gives this error. I'm guessing it has something to do with the new 3ds

**Comment by neobrain** [comment]
Please don't use our issue tracker for stuff like this.
