### ISSUE TITLE
Professor Layton and the Miracle Mask - Hangs

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1040]
1. Hangs while skip intro movie:

![prof l mir mask 1](https://cloud.githubusercontent.com/assets/11453507/9294590/6fef7a44-4452-11e5-9be1-1a9dc1d81cb9.PNG)

LOG: http://pastebin.com/8mxD0rm9

2. Hangs at Mysteries (you can go there when you don't stop playing a intro video):

![prof l mir mask 2](https://cloud.githubusercontent.com/assets/11453507/9294593/8f859960-4452-11e5-9136-e5a1bb17e94c.PNG)

LOG: http://pastebin.com/d7phjMLi

**Comment by yuriks** [comment]
Seems like it's (trying to?) playing a video (or at least using y2r) in either case. Might be just that some other bug prevents it from displaying on-screen.

**Comment by Subv** [comment]
@yuriks That part of the log is probably from the intro video

**Comment by JohnGodgames** [comment]
Fixed with https://github.com/MerryMage/citra **audio** branch

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1734
