### ISSUE TITLE
Paper Mario Sticker Star - Graphical Glitches

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1041]
![paper 3](https://cloud.githubusercontent.com/assets/11453507/9294785/f64528dc-4457-11e5-9c48-c1f9e7a6c78f.PNG)

![paper 1](https://cloud.githubusercontent.com/assets/11453507/9294766/66b77418-4457-11e5-9849-d7ad40589831.PNG)

![paper 2](https://cloud.githubusercontent.com/assets/11453507/9294768/6f514e3c-4457-11e5-9390-a164c9bf25f7.PNG)

![paper 4](https://cloud.githubusercontent.com/assets/11453507/9294789/2834c78a-4458-11e5-89fc-fb6bd13ff873.PNG)

CITRACE LOG: https://goo.gl/Tff5vU

**Comment by Subv** [comment]
Could you try with #996 please?

**Comment by JohnGodgames** [comment]
#996 not helping...the same :(

**Comment by yuriks** [comment]
What about the software renderer?

**Comment by JohnGodgames** [comment]
screens are taken at software renderer...

**Comment by JohnGodgames** [comment]
#1049 not helped

**Comment by wwylele** [comment]
Fixed by #1462 , should be closed
