### ISSUE TITLE
Professor Layton vs Phoenix Wright Ace Attorney crash citra and some weird behavior

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#1044]
OBJECTION YOUR HONOR BUT THIS GAME WONT BOOT

ok jokes aside here is the last thing that games go to before crashing citra completely

![lol2](https://cloud.githubusercontent.com/assets/12820322/9308348/2a7cf8b4-450c-11e5-87f1-0ad8bc7dcca4.PNG)

here is a log

http://pastebin.com/ZEUZxCkp

as for the weird behavior the cutscene for the companies that made the game ex capcom end up with a black screen when done and nothing happens after however if i press the bottom screen and skip the cutscene then it works normally not sure if my pc is just a potato to handle the full cutscene or just a strange behavior

also this was done with H.W mode and JIT, without JIT it gets the same result also

**Comment by RavenHome1** [comment]
also the crash is a hard citra crash, completely crashing citra

**Comment by Subv** [comment]
Did you test with the sw renderer?

**Comment by RavenHome1** [comment]
i tried but the boot time is so long :/

**Comment by RavenHome1** [comment]
@Subv ok it boots in sw 

![redefe](https://cloud.githubusercontent.com/assets/12820322/9309115/48dd0552-4510-11e5-8ac3-239b2811153e.PNG)

**Comment by RavenHome1** [comment]
i had this issue before where s.w worked but h.w didnt however it was a driver issue that i already updated and the issue got fixed. i just tested OoT in H.W and JIT and it boots fine

**Comment by RavenHome1** [comment]
ok this game behave weird i let it run in SW mode and it just goes into the title screen when select new game it just goes into a black screen also i don't see anything fun in the console possible bad dump?

![grgrg](https://cloud.githubusercontent.com/assets/12820322/9452540/76d8dc94-4abd-11e5-8dd8-b4bd6ca44bd7.PNG)

![ukkdrhege](https://cloud.githubusercontent.com/assets/12820322/9452554/8fcbd1f2-4abd-11e5-89ba-e2a8d9c2a873.PNG)

**Comment by Subv** [comment]
There were some important changes in the last few days, could you retest with the hw renderer please?

**Comment by RavenHome1** [comment]
@Subv there is no change it is still crashing

**Comment by RavenHome1** [comment]
update; with the new changes the game now fully boots into the main menu in hardware mode but breaks when hitting the new game button (as in the picture above), still the same thing where it ends in a black screen (tested both with and without JIT shader) i am suspecting it is the same issue as in the pokemon games where a save file is needed to bypass the hanging

**Comment by exhalatio** [comment]
Fixed by #1734

**Comment by RavenHome1** [comment]
@MerryMage sorry about the late reply but the game is working fine now.
