### ISSUE TITLE
Race condition in Vertex Shader JIT

### ISSUE THREAD

**Issue by Subv** [citra-emu/citra#1051]
There's a race condition between the UI thread enabling the VS JIT and the Shader::Setup and Shader::Run functions.

Picture this:
JIT is disabled
Game issues draw command and Shader::Setup is called, it doesn't do anything because the jit is disabled.
UI enables the shader JIT
Shader::Run now sees the JIT is enabled and tries to use jit_shader (a null pointer).
Crash

**Comment by Subv** [comment]
Just a reminder that this still happens.

**Comment by yuriks** [comment]
It sure does.
