### ISSUE TITLE
JitCompiler Unhandled instruction: 0x2a/0x2b

### ISSUE THREAD

**Issue by mhvuze** [citra-emu/citra#1053]
I get a plethora of the above errors when booting up Monster Hunter 4 (JP) using the JIT Compiler. The game never showed anything - no textures, no text etc - but that's the first time I see Citra throwing GPU-related errors, so maybe it's related to that? The game is still running btw. I can navigate through the startup dialogues by using the game running on my 3DS as reference for example. 

Here is a log file: http://pastie.org/private/tjdnfo2aore0qmgb4bima

I'm certain it also affects MH4U and MH3U but don't have these handy right now.

**Comment by Subv** [comment]
Those are EMIT and SETEMIT. 
We don't currently implement geometry shaders

**Comment by JayFoxRox** [comment]
I have this WIP in https://github.com/JayFoxRox/citra/tree/gs-debugger
It still needs a massive cleanup. Most of it was stolen from https://github.com/ds84182/citra/tree/geometry-shaders too.

**Comment by mhvuze** [comment]
Cool. Do you happen to have a compiled version ready that I could toy around with? I'm getting a bunch of compilation errors in video_core.

**Comment by Leo626** [comment]
I get errors when compiling it as well. It seems to point to src\video_core/shader/shader.h.

**Comment by JayFoxRox** [comment]
That branch is experimental (hence no PR). Just use issues in my repo instead of spamming the issues.. (My branch works fine for me in gcc, Probably msvc specific problems. You can probably just disable the static_assert its failing at, JIT won't work properly anyway)

**Comment by wwylele** [comment]
Should be fixed by #2865. If there is still issue, feel free to comment here / open a new one.
