### ISSUE TITLE
Error.... Does anyone happen?

### ISSUE THREAD

**Issue by Cod3Mast3r** [citra-emu/citra#1060]
please help !
rom not charged :( 
![BootGame:236: Failed to load ROM!](https://cloud.githubusercontent.com/assets/13925892/9427050/4a5f57aa-4924-11e5-9022-63a6e26a4226.png)

**Comment by archshift** [comment]
Your game dump is encrypted. Please follow the [instructions on the wiki](https://github.com/citra-emu/citra/wiki/Decryption) to decrypt them with your 3DS if it's at a compatible firmware level. If not, sorry, but you're out of luck.
