### ISSUE TITLE
Several games are crashing at vm_manager.cpp:Kernel::VMManager::CarveVMARange

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1066]
Last working build for these games was #996 from yurikstexture-copy for me.It started crashing by 
#1064 from lioncashmatr - d6a5a00c24daa90911d39734baa5283ca3c67f0b for me.I think that it's causing by #1025 from yuriks/heap-management...

Some of logs:

35 Classic Games - http://pastie.org/10371997
50 Classic Games 3D
Ace_Combat_Assault_Horizon_Legacy - http://pastie.org/10372001
Doctor_Lautrec_and_the_Forgotten_Knights - http://pastie.org/10372003
Gem_Smashers - http://pastie.org/10372004
Green_Lantern_Rise_of_the_Manhunters
Chevrolet Camaro Wild - Ride 3D
Island Days
Jewel Link - Legends of Atlantis
Jewel Master - Cradle of Egypt 2 3D
Junior_Classic_Games_3D
Marvel_Super_Hero_Squad_The_Infinity_Gauntlet
Nekketsu Kouha Kunio-Kun Special
Scooby-Doo and Looney Tunes Cartoon Universe - Adventure
Teenage Mutant Ninja Turtles - Danger of the Ooze
Transformers - Rise of the Dark Spark
Travel Adventures with Hello Kitty
Virus Shooter XX
Word Wizard 3D
Wreck-It Ralph
WWE_All_Stars
and more...

**Comment by yuriks** [comment]
#1075 should fix these

**Comment by JohnGodgames** [comment]
Tested and it's fixed by #1075
