### ISSUE TITLE
Dead or Alive: Dimensions - freezing when the gyro is activated

### ISSUE THREAD

**Issue by baltai** [citra-emu/citra#1070]
Well, this game freezes in the menu just at the moment when the gyro is activated.
I tested the demo and retail versions.

![001](https://cloud.githubusercontent.com/assets/13970874/9480437/c0c4f9a4-4b8b-11e5-81a9-bb0fd4ef69fa.jpg)

**Comment by MoochMcGee** [comment]
Holy shit, does this thing actually interface with the DSP? That sort of thing could easily generate a deadlock, after all.

**Comment by purpasmart96** [comment]
@MoochMcGee Ummm you do know all games call the DSP service.

**Comment by hrydgard** [comment]
Yeah, just implementing or stubbing those Gyro functions would likely allow it to progress.

**Comment by JohnGodgames** [comment]
already issued here https://github.com/citra-emu/citra/issues/956

**Comment by Subv** [comment]
Indeed this is a duplicated issue

**Comment by yuriks** [comment]
Should probably add the info about the gyro to the other issue though, since I don't think it's mentioned.
