### ISSUE TITLE
beyond the labyrinth - multiple graphic bugs/ untextured models

### ISSUE THREAD

**Issue by Punk34** [citra-emu/citra#1076]
I just inform you that this game does not have much effect, and all models of characters and monsters have no textures:

![01](https://cloud.githubusercontent.com/assets/13983158/9496535/6390c392-4c19-11e5-807e-8f3881f6dfb5.jpg)

**Comment by Subv** [comment]
Could you please test with #1049 to see if the map bug persists? thanks

**Comment by Punk34** [comment]
Sorry, at the moment I am not able to compile the emulator. I'll wait for a new nightly build.
By the way, the touchscreen doesn't work well.

**Comment by Punk34** [comment]
Nothing changed

![citra-qt 2015-08-27 19-22-49-59](https://cloud.githubusercontent.com/assets/13983158/9526306/3c63f37e-4cf1-11e5-87db-bb408f17d720.jpg)

**Comment by yuriks** [comment]
Has #1261 fixed the missing textures?

**Comment by Punk34** [comment]
no

![01](https://cloud.githubusercontent.com/assets/13983158/11588431/9c3f8c3e-9a91-11e5-8f16-21e9be98e739.jpg)

**Comment by Punk34** [comment]
Oh, the аame freezes after this

![0002](https://cloud.githubusercontent.com/assets/13983158/11588586/c33d4b40-9a92-11e5-84e8-c1b11996c840.jpg)

**Comment by JayFoxRox** [comment]
There have been lots of graphical fixes recently in Citra. Can you retest this game?
The map would probably be fixed by #1263

**Comment by Punk34** [comment]
@JayFoxRox game is broken #1457

**Comment by Subv** [comment]
Is this still an issue?

**Comment by Dragios** [comment]
Please close this. It looks fine to me / fixed based on this [image](https://github.com/citra-emu/citra/issues/1457#issuecomment-214720731)
