### ISSUE TITLE
Ubuntu. libglfw.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by timfayz** [citra-emu/citra#1077]
Hello, Ubuntu 14.10 64bit, citra-20150825-4ad86a6-linux-amd64. First run:
```
$ cd citra-20150825-4ad86a6-linux-amd64
$ ./citra-qt
[   0.000000] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /home/timur/.config/citra-emu/qt-config.ini
X Error: GLXBadFBConfig 178
  Extension:    155 (Uknown extension)
  Minor opcode: 34 (Unknown request)
  Resource id:  0x5800016
```
Then, I've tried to run just `citra`.
```
$ ./citra
./citra: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory
```

What's wrong?(

**Comment by LittleWhite-tb** [comment]
Hello,

For the first one, I would say you don't  have GPU acceleration. If you have embedded Intel chipset and NVIDIA, try to run citra-qt with optirun to force it to run using the GPU.

For the second one, I remember a similar issue, but can't remember. I would suggest to search for libglfw.so.3 in harddrive and try to install it from package manager if not found. But it should be found otherwise the compilation could not have be done.

**Comment by archshift** [comment]
I guess you're running a nightly. To use the GLFW frontend, you need to install glfw with your package manager.

**Comment by kalopsia** [comment]
Thanks for replay.

> For the first one, I would say you don't have GPU acceleration. If you have embedded Intel chipset and NVIDIA, try to run citra-qt with optirun to force it to run using the GPU.

If to be honest switching between Intel and Nvidia graphics it is real headache. I don't know how to do it and where to start.

I've tried to switch, but...

![screenshot from 2015-08-27 10 13 20](https://cloud.githubusercontent.com/assets/6209197/9514681/dbfc1c06-4ca4-11e5-8d5d-d9e52079c093.png)

After log-out and log-in - nothing changed:

![screenshot from 2015-08-27 10 13 03](https://cloud.githubusercontent.com/assets/6209197/9514730/45cb1326-4ca5-11e5-845f-63962654ab26.png)

I've tried using `prime-select` - but it doesn't solve the problem.

![screenshot from 2015-08-27 10 22 36](https://cloud.githubusercontent.com/assets/6209197/9514768/9340c466-4ca5-11e5-8c06-d831bd001fff.png)

> I guess you're running a nightly. To use the GLFW frontend, you need to install glfw with your package manager.

Could you provide some information how to do it? I haven't very much Linux administration skills)

**Comment by LittleWhite-tb** [comment]
For the citra-qt : can you check with the glxinfo command that NVIDIA info is showing up (the ten first line of what the command will return).
To install GLFW, start the package manager (you will find it in the Unity menus), then search for GLFW or libglfw3 and install it. That's all.

**Comment by archshift** [comment]
Closing due to no reply.
