### ISSUE TITLE
SSB demo crashes the vertex shader JIT while in-game due to running out of memory for compiled shaders

### ISSUE THREAD

**Issue by archshift** [citra-emu/citra#1081]
Steps to reproduce:
- Open the SSB demo ~~(you have to create the save_data folder which the console will complain about during your first run, otherwise the demo will refuse to play)~~
- Attempt to play, by choosing your character and stage
- Wait for the countdown to finish

Then, Citra promptly crashes somewhere in the JITted code with a EXC_BAD_ACCESS:
```
->  0x10a40a038: pushq  %rbx
    0x10a40a039: pushq  %rbp
    0x10a40a03a: pushq  %r12
    0x10a40a03c: pushq  %r13
```

As expected, this does not occur when the JIT is disabled.

**Comment by archshift** [comment]
The same error seems to occur in Kirby: Triple Deluxe, after playing for a short time.

**Comment by archshift** [comment]
@yuriks and I found it likely that this is caused by running out of memory for the JIT to compile to. @bunnei, does the JIT not automatically allocate memory?

**Comment by yuriks** [comment]
It doesn't, the allocation size needs to be manually bumped. What we should do is change the allocation so that it does a separate allocation for each JITed shader. That way, we can set a upper bound on the size of a single shader and not have to worry about the number of shaders the game uses.
