### ISSUE TITLE
Breaks caused by missing cfg savedata

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#1094]
There are several files currently which require the extraction of the cfg save file from the 3DS. This is a highly inconvenient process (required dumping and decrypting the NAND and then using a Linux-only tool to unpack the save) and there's currently no easy homebrew tool to use to dump it.

Support for dumping this should be added to [citra-emu/3dsutils](https://github.com/citra-emu/3dsutils) in some way, or Citra should HLE missing blocks required by games to avoid the need to dump the file. (The latter is preferable of course, especially in the long run.)

**Comment by yuriks** [comment]
Related to #1093

**Comment by JohnGodgames** [comment]
Also related to #975

**Comment by Kloen** [comment]
Also related to #902

**Comment by yuriks** [comment]
PR #1097 should provide most of the currently known missing blocks. Let me know if any games request additional ones.

**Comment by JohnGodgames** [comment]
tested #1097 and not helped for tekken or kindom hearts :(

**Comment by yuriks** [comment]
Uh, it should help get past those errors at least. Are you sure you deleted the file first?

**Comment by Kloen** [comment]
#902 Fixed

**Comment by yuriks** [comment]
This issue is too broad, and I think we haven't had issues related to this in a while now. If anything shows up that requires new blocks to be implemented they'll go in as separate issues.
