### ISSUE TITLE
Kingdom Hearts 3D - Dream Drop Distance Crash Citra During Spirit Tutorial

### ISSUE THREAD

**Issue by TheSoraHD** [citra-emu/citra#1098]
Happens when entering Spirit's Ability Link Board. Interesting thing, since I don't remember that the Gyroscope was actually used in that part of the game.

![image](https://cloud.githubusercontent.com/assets/8531824/9619939/6bc4f14a-5115-11e5-85d0-014ddcc497e0.png)

**Comment by archshift** [comment]
We need some more info to even start investigating this crash. Can you get a stack trace?

**Comment by TheSoraHD** [comment]
I hope this can help, tell me if you need something more.

![image](https://cloud.githubusercontent.com/assets/8531824/9634022/02772aac-5190-11e5-8d04-d339eb91bd95.png)
![image](https://cloud.githubusercontent.com/assets/8531824/9634049/2842d088-5190-11e5-8aef-57186e8e7e63.png)


Log:
http://pastebin.com/fnFrCEbN

**Comment by HeroineChan** [comment]
Why I can't open? Got any problem with it? O.o
![untitled 4](https://cloud.githubusercontent.com/assets/16014270/11414927/c28cc75a-9436-11e5-8928-b366fc05f20d.png)

**Comment by HeroineChan** [comment]
Failed to load ROM??? O.O Why? o.o
![untitled 5](https://cloud.githubusercontent.com/assets/16014270/11414946/faea06a8-9436-11e5-9c2e-e73fb753d26c.png)

**Comment by yuriks** [comment]
The issue tracker is not for user support. And don't post on unrelated issues. (Also, you're using an unsupported 3rd party build.)

**Comment by Subv** [comment]
It maaaay be trying to set an invalid buffer (Returned as garbage from one of our unimplemented cam functions) as a texture, and so the hashing crashes when reading from some bad location

**Comment by wwylele** [comment]
As reported the game doesn't crash at this point anymore. Closing
