### ISSUE TITLE
Naruto Powerful Shippuden - Black screen

### ISSUE THREAD

**Issue by Kloen** [citra-emu/citra#1100]
The game it's unable to boot in both HW and SW render. With no error or warning spam, only hangs.

Here's the log: https://gist.github.com/Kloen/56bf10227e2244c95fd6

Any thoughts on what could be happening? I'll try to gather more information once I reach home, can't debug citra atm.

**Comment by RavenHome1** [comment]
same as my issue https://github.com/citra-emu/citra/issues/1044

**Comment by Kloen** [comment]
@RavenHome1 I don't think that it's the same. Because 20 minutes later... still black screen, no more on logs, both HW and SW. Professor Layton at least runs... and even print out some errors.

**Comment by RavenHome1** [comment]
it is printing similar errors, try to boot the game again and keep clicking on the bottom  touch screen , it might be the same issue with my game at boot which is a stuck introductory cut scene ,clicking on the bottom skips it

**Comment by Kloen** [comment]
Update report to last master: 2b00bdec1f83be82acb65bb316086858134e5766

https://gist.github.com/Kloen/56bf10227e2244c95fd6

**Comment by Kloen** [comment]
Surprise :open_mouth: 

![image](https://cloud.githubusercontent.com/assets/9112818/14100924/3216b6c4-f591-11e5-9115-2ab98e854550.png)

Fixed by... (searching between builds...)
