### ISSUE TITLE
blank screen when compiling citra from sources 

### ISSUE THREAD

**Issue by garcher** [citra-emu/citra#1107]
![2015-09-04 23 12 39](https://cloud.githubusercontent.com/assets/10480310/9694606/7945bf1a-535a-11e5-9db2-4849e5e55319.png) I can't run the emulator, all I get is a blank window. In console there is only 1 warning: Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /Users/user/.config/citra-emu/qt-config.ini . What could be the reason for it?

**Comment by OatmealDome** [comment]
I think that's normal. You should be able to run a ROM. (there's an option in the menu bar under FIle)

**Comment by garcher** [comment]
@OatmealDome  okay, thank you. I forgot that on OS X there is a menu at the top
