### ISSUE TITLE
Support Wiimotes (Code Already Written)

### ISSUE THREAD

**Issue by Oalecj** [citra-emu/citra#1120]
Similar to how dolphin works, you could support wiimotes over Bluetooth.
The code is already written at http://bit.ly/1Ftidsg - it just needs to be modified a bit to fit with citra. Using a wii remote would be so much easier than a keyboard, and it has almost the same amount of buttons as the 3ds.

**Comment by neobrain** [comment]
Not taking feature requests, currently.
