### ISSUE TITLE
Allow usage of a subset of boost libraries

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#115]
I've recently made myself more familiar with the boost libraries and figured being able to use them would be helpful in a number of places. In particular, these three boost libraries seem beneficial for Citra:

* Ranges (http://www.boost.org/doc/libs/1_56_0/libs/range/doc/html/index.html) in place of `<algorithm>`: Allows accessing standard library containers via *ranges* rather than *iterators*. This has a number of conceptional advantages, and most importantly it allows for more compact code: a simple find operation would be `boost::find(some_vector, some_element)` rather than `std::find(some_vector.begin(), some_vector.end(), some_element)`. Additionally it provides fancy features like range zipping (cf. http://pastie.org/private/xne0jrgive77aothj8cw)
* Format (http://www.boost.org/doc/libs/1_56_0/libs/format/index.html) in place of Dolphin's StringFromFormat: Provides a type safe replacement for conveniently generating `std::string` objects with a printf-like syntax
* Filesystem (http://www.boost.org/doc/libs/1_56_0/libs/filesystem/doc/reference.html): Provides generic file access functions (file_size, exists, etc) as well as path string handling. This would allow us to throw away a lot of Dolphin code from our code base.

A full list is shown at http://www.boost.org/doc/libs/1_56_0/ . You can tell I'm being conservative about the number of libraries I'm proposing to use :) Luckily, a lot functionality of the boost libraries has been standardized in C++11, otherwise the list would probably have been bigger.

The general idea behind this is a) to give Citra developers more powerful tools to work with b) to throw out code forked from Dolphin (which requires us to synchronize with updates etc). However, there also is a number of disadvantages to using boost:
* Bad documentation: Well, it varies. Basic functionality can usually be grasped quickly, however more advanced things or very special corner features may be hard to understand without writing a small test application.
* Long compile times: This one is indeed annoying, and there's not much we can do about it.
* Horrible compile error messages: some libraries don't have this issue at all, while the more template-heavy ones will spam pages full of error messages.

For now, I'd say let's just give it a shot - each of the above shortcomings needs to be seen in a case-by-case basis. If some library turns out to suffer from one of them heavily, we can just decide not to use that one without dropping boost usage altogether.

If this change gets accepted, we should
* include the relevant Boost headers in externals.
* add an explicit list of allowed dependencies to the coding style guide.
* as a first phase, migrate over relevant common/ interfaces to boost.
* as a second phase, replace common/ usage with direct boost usage.

**Comment by bunnei** [comment]
Done. Closed.
