### ISSUE TITLE
Rollercoaster Tycoon 3D: Zfighting in HW renderer.

### ISSUE THREAD

**Issue by JMC47** [citra-emu/citra#1150]
Happens in latest as of this post.  Look at the grass overpowering the sidewalk stuff on the hardware renderer, vs the clear lines on the SW renderer.  Note that lighting is messed up making it kind of hard to see.

Software Renderer

![zfightingsw](https://cloud.githubusercontent.com/assets/6598209/9828520/96f5f054-58bc-11e5-8b27-7407d53e043f.jpg)

Hardware Renderer

![zfightinghw](https://cloud.githubusercontent.com/assets/6598209/9828524/a3162e4e-58bc-11e5-8b2e-2417c919a0e5.jpg)

**Comment by purpasmart96** [comment]
Zfighting can also  be seen in the OoT using the HW  renderer. but I've only see in one small place though.

**Comment by Subv** [comment]
ALBW has the same issue, it's because we're not using viewport_depth_range nor viewport_depth_far_plane anywhere in the hardware renderer

**Comment by JMC47** [comment]
I think this was merged.
