### ISSUE TITLE
Not a valid Win32 Application

### ISSUE THREAD

**Issue by phase** [citra-emu/citra#1153]
I'm getting this lovely error when trying to run Citra on my Windows XP machine:
![picture of error](http://i.imgur.com/w5rw7qT.png)
Is Citra not compatible with 32 bit OSes/computers?
(This is the latest build, and I got the same error with the latest build from a couple days ago)

**Comment by OatmealDome** [comment]
Citra is not compatible with 32-bit OSes iirc

**Comment by yuriks** [comment]
Official Citra builds are not compatible with 32-bit OSes. (Building 32-bit binaries from source currently works but is also not a supported configuration.)

**Comment by phase** [comment]
@yuriks How would one build for 32 bit?

**Comment by archshift** [comment]
The same way one would build for 64-bit. The instructions are on the wiki.
