### ISSUE TITLE
Shinobi - hangs before ingame

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1155]
![shinobi](https://cloud.githubusercontent.com/assets/11453507/9866376/f29226a6-5b61-11e5-9907-8dba19218e9f.PNG)

http://pastie.org/10420447

**Comment by Subv** [comment]
This will probably not work until we do something about the DSP

**Comment by JohnGodgames** [comment]
Fixed by #1479

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1441
