### ISSUE TITLE
Sonic Lost World - Hangs while Sega Intro video should be played

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1156]
Reference - https://www.youtube.com/watch?v=fPoMeylrFPc

![sonic lost world](https://cloud.githubusercontent.com/assets/11453507/9866619/b0699676-5b64-11e5-9438-c822681ad692.PNG)

http://pastie.org/10420453

**Comment by yuriks** [comment]
Also looks like a dupe of #1139

**Comment by JohnGodgames** [comment]
Fixed with https://github.com/MerryMage/citra **audio** branch

**Comment by JayFoxRox** [comment]
does this work already? (it's the only remaining open audio-tagged issue)

**Comment by JohnGodgames** [comment]
Works ingame on recent master
