### ISSUE TITLE
Lego Batman 3: Beyond Gotham - Preparing save data looping

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1158]
![lego batman](https://cloud.githubusercontent.com/assets/11453507/9866857/314d70f2-5b68-11e5-95a1-e2c01d14c5b3.PNG)

LOG:
http://pastebin.com/rmxFKKrf

**Comment by Subv** [comment]
Could you please test #1302 ?

**Comment by JohnGodgames** [comment]
Yep fixed by #1302 great work!
