### ISSUE TITLE
True Remembrance wont go beyond logo

### ISSUE THREAD

**Issue by Eriz0** [citra-emu/citra#1161]
Hey, guys.
Here is a game (True Remembrance ~Kioku no Kakera~) I´d really want to play, unfotunately it doesn´t go beyond the logo screen, It´s a really simple VN game (just text and pics and music), so it´d be nice if you could fix this.
Thank you.

**Comment by mailwl** [comment]
omg, warez! remove ASAP!

**Comment by Eriz0** [comment]
You mean the game link? Ok, removed, but how will they fix this without the actual game?

**Comment by Kloen** [comment]
Just post the log.

Use this from command prompt on Windows:
´´´citra-qt 1> console.log 2>&1´´´

And pastebin the console.log content.

On other OS's just search a method to redirect the console/terminal output to a file.

**Comment by vitorsilverio** [comment]
Please post log trace and screenshots

**Comment by mailwl** [comment]
@Eriz0, btw, this game exists on PC, in english, and russian ("Истина памяти")

**Comment by Eriz0** [comment]
@mailwl I know, I want 3ds grafics))

**Comment by mailwl** [comment]
ok, i found the problem, now game is fully playable (no sound for sure). can you change sources my yourself?

**Comment by Eriz0** [comment]
Im afraid not, Im a complete noob in programming, Well unless a really thorough step by step instruction is provided.

**Comment by mailwl** [comment]
sorry, no. i am mac user

**Comment by Eriz0** [comment]
Some coding needs changing I presume?

**Comment by mailwl** [comment]
i describe change, maybe someone build it for you.
So, the problem is the game on every screen change call pair "RegisterInterruptRelayQueue/UnregisterInterruptRelayQueue" - second is not implemented.
I make it this way (gsp_gpu.cpp):
```c++
static void UnregisterInterruptRelayQueue(Service::Interface* self) {
    u32* cmd_buff = Kernel::GetCommandBuffer();
    g_shared_memory = nullptr;
    using Kernel::MemoryPermission;
    g_shared_memory = Kernel::SharedMemory::Create(0x1000, MemoryPermission::ReadWrite,
                                                   MemoryPermission::ReadWrite, "GSPSharedMem");
    cmd_buff[1] = 0;
}
```

and do not forget to link to interface:
...
{0x00140000, UnregisterInterruptRelayQueue,   "UnregisterInterruptRelayQueue"},
...

**Comment by Eriz0** [comment]
Spasibo=)

**Comment by RavenHome1** [comment]
is this the same game? http://trueremembrance.insani.org/get.html

**Comment by Eriz0** [comment]
Yes, the graphics is different though, plus it has a couple of bonus scenarios, new movies etc. 17.09.2015, 20:40, "RavenHome1" <notifications@github.com>:is this the same game? http://trueremembrance.insani.org/get.html—Reply to this email directly or view it on GitHub.

**Comment by RavenHome1** [comment]
ok this looks like a windows game that you can pick up instead if you want

**Comment by Eriz0** [comment]
Can someone, please share the edited file? I tried rebuilding the programm, but it still doesn't seem to work...

**Comment by Kloen** [comment]
I ran it on basically the same environment that you.

Win7 x64
Intel HD 4600 (Same drivers)

![image](https://cloud.githubusercontent.com/assets/9112818/9954307/3db833c2-5de8-11e5-9198-4a28e059abc9.png)

If you want, I can mail you a copy of the compiled version. But remember, it's not an official build, and in fact, it's not a build over master branch.

**Comment by Eriz0** [comment]
Could you please？

**Comment by Kloen** [comment]
@Eriz0 done.

**Comment by Eriz0** [comment]
Thank you. But It wont open saying that it didnt find msvcp120.dll which is very strange, because Im sure I have it and C++ libraries installed. Could you send it with all dlls included? Mabe thats the problem?

**Comment by Kloen** [comment]
Oh, that's cause it's builded with Visual Studio 2013, you need to install [Visual Studio C++ Redistributable 2013](http://www.microsoft.com/en-us/download/details.aspx?id=40784)

**Comment by Eriz0** [comment]
I have it installed, but it still wont work. I reinstalled it and reloaded but still no good.

**Comment by Kloen** [comment]
Uh, that's kinda strange... Did you install vcredist_x64.exe? Anyway, this it's kinda offtopic cause the issue it's fixed by the @mailwl code, so if you need further help to run it, come to the [IRC](http://webchat.freenode.net/?channels=citra)

**Comment by Eriz0** [comment]
ok

**Comment by neobrain** [comment]
Please don't abuse our issue tracker for user support. The project is not at a state where we can spend time on providing the latter, sorry. We are not interested in "Game XY doesn't work"-like issue reports currently. There may be some useful information mentioned by @mailwl , but ultimately the information density in this thread is far below the relevance threshold.
