### ISSUE TITLE
New Build, please!

### ISSUE THREAD

**Issue by Eriz0** [citra-emu/citra#1162]
Hello everebody.
Could someone please implement this new build for me？
Original Message:
-------------------------------
i describe change, maybe someone build it for you.
So, the problem is the game on every screen change calls pair "RegisterInterruptRelayQueue/UnregisterInterruptRelayQueue" - second is not implemented.
I make it this way (gsp_gpu.cpp):

static void UnregisterInterruptRelayQueue(Service::Interface* self) {
    u32* cmd_buff = Kernel::GetCommandBuffer();
    g_shared_memory = nullptr;
    using Kernel::MemoryPermission;
    g_shared_memory = Kernel::SharedMemory::Create(0x1000, MemoryPermission::ReadWrite,
                                                   MemoryPermission::ReadWrite, "GSPSharedMem");
    cmd_buff[1] = 0;
}

and do not forget to link to interface (same file):
...
{0x00140000, UnregisterInterruptRelayQueue, "UnregisterInterruptRelayQueue"},
...
----------------------------------
end of message.
Ill be much oblidged.

**Comment by vitorsilverio** [comment]
Related #1161
