### ISSUE TITLE
make error during compiling shader_jit_x64.cpp

### ISSUE THREAD

**Issue by Road-Drum** [citra-emu/citra#1163]
hello. I'm still new to github and also coding. hopefully when I have enough knowledge I will start contributing. I got this error when compiling under Fedora 22. all dependencies are already install and meets the minimum requirements.

/home/hello/citra/src/video_core/shader/shader_jit_x64.cpp: In member function ‘void Pica::Shader::JitCompiler::Compile_SwizzleSrc(nihstro::Instruction, unsigned int, nihstro::SourceRegister, Gen::X64Reg)’:
/home/hello/citra/src/video_core/shader/shader_jit_x64.cpp:200:19: error: ‘union nihstro::SwizzlePattern’ has no member named ‘GetRawSelector’
     u8 sel = swiz.GetRawSelector(src_num);
                   ^
src/video_core/CMakeFiles/video_core.dir/build.make:399: recipe for target 'src/video_core/CMakeFiles/video_core.dir/shader/shader_jit_x64.cpp.o' failed
make[2]: *** [src/video_core/CMakeFiles/video_core.dir/shader/shader_jit_x64.cpp.o] Error 1
CMakeFiles/Makefile2:384: recipe for target 'src/video_core/CMakeFiles/video_core.dir/all' failed
make[1]: *** [src/video_core/CMakeFiles/video_core.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

what am I missing? sorry this is the only place that i can ask. If I can troubleshoot this by myself, it'd been done without this issue request

**Comment by yuriks** [comment]
Have you updated submodules? `git submodule update --init`

**Comment by Road-Drum** [comment]
ah it's working now. forgot that submodules should been updated and git pull doesn't update submodules
thanks for the fast response. i will close this topic
