### ISSUE TITLE
3dsx RomFS support

### ISSUE THREAD

**Issue by Cruel** [citra-emu/citra#1166]
Currently gives error:

    Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFileDirectly:119: failed to get a handle for archive archive_id=0x00000003 archive_path=[Empty]

Presumably from this location in ctrulib: https://github.com/smealum/ctrulib/blob/master/libctru/source/romfs_dev.c#L142

And of course it fails to init romfs and continues loading attempts from sdmc.

**Comment by fincs** [comment]
From IRC today:
```
<fincs> It just takes exposing the embedded layer3 romFS inside it as the RomFS FS archive
<fincs> 3dsx romFS is defined by extended fields in the header that launchers are supposed to ignore
<profi200> I think Citra should follow the 3dsx format and also should provide argc + argv[]. If it only would provide arg[0] apps with RomFS should work.
<fincs> It cannot provide argv[0] if the 3dsx is outside the filesystem folder
<fincs> And in order for it to try using argv[0] it needs to provide the service override list
<fincs> The presence of which is the official way to detect a homebrew loader
<fincs> So, it's simply easier and troublefree to just emulate the RomFS archive
```
[Extended header reference](https://github.com/smealum/ctrulib/blob/master/libctru/source/romfs_dev.c#L97)
[How to detect the presence of 3dsx-romFS](https://github.com/smealum/ctrulib/blob/master/libctru/source/romfs_dev.c#L145)

**Comment by Cruel** [comment]
Okay thanks, think I got it working, but gotta work. I'll test it and do PR tonight.

**Comment by vgturtle127** [comment]
We can close this now right? The PR was merged...

**Comment by Cruel** [comment]
Don't know. May want to keep it for sentimental reasons... :sparkles:
