### ISSUE TITLE
Suggestion: Create a forum to build a community around Citra

### ISSUE THREAD

**Issue by Kiloku** [citra-emu/citra#1168]
The best emulators in the internet owe a large part of their success to the strong community around them (Dolphin being a prime example of that). 

Communities attract and motivate developers, as well as centralizes simpler feedback. I'm aware that Citra has rooms at Freenode, but chats are ephemeral in nature, the conversations last somewhere between seconds and hours, while forums can have months-long debates. A forum would also allow for easy to find announcements, progress reports, patch notes, etc.

**Comment by RavenHome1** [comment]
https://gbatemp.net/threads/citra-new-3ds-emulator.365154/ closest thing to a forum

**Comment by Kiloku** [comment]
I'm aware of subcommunities in general emulation forums and even as "off-topic" in the communities for other emulators, but it'd be very good to have a full (and official) forum for Citra.

**Comment by yuriks** [comment]
I think a forum is expected to launch at the same time as the new website redesign. (No ETA)

> while forums can have months-long debates.

You say that as if it were a good thing. :^)

**Comment by Cruel** [comment]
This would also be nice to minimize all the "these polygons look strange in XX game" issues on github. Maybe discuss them in forums and consolidate them into specific diagnosed issues in the repo.

**Comment by purpasmart96** [comment]
This would also help remove unnecessary invalid issues in the Github issue tracker that continue to clutter it up.

**Comment by neobrain** [comment]
This is not a bug report.
