### ISSUE TITLE
failed to load ROM (homebrew works fine)

### ISSUE THREAD

**Issue by Road-Drum** [citra-emu/citra#1169]
hi again. I'm starting this issue since rom's I've downloaded (sorry my new 3ds is too young to die) aren't working. checking with 3dsexplorer and crappy tiny reader, the partitions seems fine (card serial is present, region is correct, checking doesn't yield any error) so here's the error

==============================================================================

[  11.400090] Frontend <Info> citra_qt/main.cpp:BootGame:233: Citra starting...

[  11.429589] Service.FS <Info> core/file_sys/archive_sdmc.cpp:ArchiveFactory_SDMC:21: Directory /home/hello/.local/share/citra-emu/sdmc/ set as SDMC.
[  11.432163] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /home/hello/.local/share/citra-emu/sdmc/
[  11.432295] Service.FS <Info> core/file_sys/archive_savedata.cpp:ArchiveFactory_SaveData:36: Directory /home/hello/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
[  11.432324] Service.FS <Info> core/file_sys/archive_extsavedata.cpp:ArchiveFactory_ExtSaveData:62: Directory /home/hello/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  11.434287] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /home/hello/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
[  11.434423] Service.FS <Info> core/file_sys/archive_extsavedata.cpp:ArchiveFactory_ExtSaveData:62: Directory /home/hello/.local/share/citra-emu/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  11.435876] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /home/hello/.local/share/citra-emu/nand/data/00000000000000000000000000000000/extdata/
[  11.436696] Service.APT <Warning> core/hle/service/apt/apt.cpp:Init:411: Unable to load shared font: /home/hello/.local/share/citra-emu/sysdata/shared_font.bin
[  11.447940] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:382: GL_VERSION: 3.3 (Core Profile) Mesa 10.6.1 (git-6ff3ae8)
[  11.448030] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:383: GL_VENDOR: X.Org
[  11.448066] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:384: GL_RENDERER: Gallium 0.4 on AMD SUMO
[  14.823690] Loader <Info> core/loader/loader.cpp:LoadFile:113: Loading file /home/hello/Downloads/3DSZ043 - Daigyakuten Saiban - Naruhodou Ryuunosuke no Bouken (Japan).3ds as NCSD...
[  14.823745] Loader <Warning> core/loader/ncch.cpp:Load:235: Only loading the first (bootable) NCCH within the NCSD file!
[  14.823767] Loader <Info> core/loader/ncch.cpp:Load:259: Name:                         �c�c�G�Xk#����3|��	�-�f��m�%�9�/�����Hp��U�5}�9}H�Û2�

[  14.823819] Frontend <Critical> citra_qt/main.cpp:BootGame:244: Failed to load ROM!

=============================================================================

does this relate to unimplemented functions (the rom is JP region)? (tried other roms and all of them aren't working, even in US region) homebrew works fine with slow emulation speed (understandable since this is w.i.p.).
if this is and old issue, feel free to close this.

**Comment by mailwl** [comment]
the rom is ENCRYPTED

**Comment by RavenHome1** [comment]
can the last message be replaced and instead say, error failed to load reason ROM is encrypted

**Comment by Cruel** [comment]
That would be nice, though it may be difficult to differentiate between encryption and garbled nonsense. And if people are merely attempted to run garbage code, you certainly don't want to tell them it's encrypted.

**Comment by Road-Drum** [comment]
oh silly me. well to add the line ROM is encrypted might cause confusion as stated above (unless a checker is implemented) . can't progress much since my new 3ds is constantly updated and don't have any plan to run any gateway flashcarts. as homebrew is working (homebrew launcher still can't detect 3ds folder in sdmc root) then it's ok. thanks for the help though.
