### ISSUE TITLE
Crash - OpenGL

### ISSUE THREAD

**Issue by kholyphoenix1** [citra-emu/citra#1179]
Hello, 

Erro with OpenGL.
GPU: Intel HD Graphics 2000. (Drive - Ok)

----

[root@jr-pc build]# ../build/src/citra_qt/citra-qt
Qt: Session management error: None of the authentication protocols specified are supported
[   0.000000] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /root/.config/citra-emu/qt-config.ini
Error creating proxy: A conexão está fechada (g-io-error-quark, 18)
Error creating proxy: A conexão está fechada (g-io-error-quark, 18)
Error creating proxy: A conexão está fechada (g-io-error-quark, 18)
Error creating proxy: A conexão está fechada (g-io-error-quark, 18)
Error creating proxy: A conexão está fechada (g-io-error-quark, 18)
[  32.178135] Frontend <Info> citra_qt/main.cpp:BootGame:233: Citra starting...

[  32.204834] Service.FS <Info> core/file_sys/archive_sdmc.cpp:ArchiveFactory_SDMC:21: Directory /root/.local/share/citra-emu/sdmc/ set as SDMC.
[  32.218221] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /root/.local/share/citra-emu/sdmc/
[  32.218308] Service.FS <Info> core/file_sys/archive_savedata.cpp:ArchiveFactory_SaveData:36: Directory /root/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
[  32.218380] Service.FS <Info> core/file_sys/archive_extsavedata.cpp:ArchiveFactory_ExtSaveData:62: Directory /root/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  32.219537] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /root/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
[  32.219621] Service.FS <Info> core/file_sys/archive_extsavedata.cpp:ArchiveFactory_ExtSaveData:62: Directory /root/.local/share/citra-emu/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  32.228266] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /root/.local/share/citra-emu/nand/data/00000000000000000000000000000000/extdata/
[  32.228680] Service.APT <Warning> core/hle/service/apt/apt.cpp:Init:411: Unable to load shared font: /root/.local/share/citra-emu/sysdata/shared_font.bin
[  32.243220] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:382: GL_VERSION: 3.2 (Core Profile) Mesa 10.6.3 (git-ccef890)
[  32.243328] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:383: GL_VENDOR: Intel Open Source Technology Center
[  32.243385] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:384: GL_RENDERER: Mesa DRI Intel(R) Sandybridge Desktop 
Mesa 10.6.3 implementation error: Failed to compile fragment shader: FS compile failed: Register spilling not supported with m14 used

Please report at https://bugs.freedesktop.org/enter_bug.cgi?product=Mesa
[  35.338808] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadShaders:80: Error linking shader:
FS compile failed: Register spilling not supported with m14 used

Falha de segmentação (imagem do núcleo gravada)
[root@jr-pc build]#

**Comment by yuriks** [comment]
Update your drivers (your mesa version, in this case.)

**Comment by kholyphoenix1** [comment]
Thanks!!
