### ISSUE TITLE
Introduce a color theme management framework for the Qt GUI

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#1181]
Colors in debug widgets (or within the UI in general) shouldn't be hardcoded, but the UI designer quite often still needs some way to highlight text in some way. Hardcoding colors in this case often works for "standard" system themes, but causes poor readability whenever the program user uses a non-standard color theme (e.g. dark ones). A solution is to have a central code framework to request different types of "highlighting" colors. The concrete values of these colors could either be inferred from the system theme (which will be hard to implement) or could be user-adjustable (which would be easy and flexible enough). 

An example of such a framework is KDE's KColorScheme (cf http://api.kde.org/frameworks-api/frameworks5-apidocs/kconfigwidgets/html/classKColorScheme.html). This need not be the same interface that we would use, but it's a good example of what idea I have in mind.

To get things going, we could start with a dummy implementation which only supports a single (hardcoded) color theme. The "hardcoding" is then localized to a central place rather than needing to fixup the whole source tree later on.

**Comment by BreadFish64** [comment]
This has been implemented
