### ISSUE TITLE
Introduce a tabbed configuration dialog

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#1182]
Tabbed configuration dialogs are great - they allow for bundling all relevant configuration modules into a single dialog so that the user can conveniently inspect and tune all settings without having to step through multiple windows.

There are some issues with traditional tabbed layouts, though: First off, text-only content makes it cognitively less straightforward to find particular functionality quickly. It would be beneficial to additionally have an icon per configuration module (= tab) hence. Secondly, a horizontal tab bar takes away (for configuration dialogs usually precious) vertical screen space. Hence a vertical tab bar should be used instead.

Both of these points (and others) have been addressed by the KDE community:
![KDE page widget](http://www.davidrevoy.com/data/images/blog/2013/01/mint14kde/linux-mint-kde-14-digital-painting_05.jpg)

I think KDE's solution is both very usable and visually pleasing, and hence would be a great candidate for adoption in Citra. The relevant code can be found at http://api.kde.org/4.x-api/kdelibs-apidocs/kdeui/html/dir_1f296a4dd1c9f1f4073f9d2032e2722f.html , and can be stripped down a bit and then included in Citra.

(Note that currently we do not actually have enough configuration dialogs to sensibly introduce such a tabbed configuration dialog - however in the future this will definitely be useful.)

**Comment by Gareth422** [comment]
This is my favourite design for configuration dialogues. I would support this.

**Comment by lioncash** [comment]
Same

**Comment by JayFoxRox** [comment]
Partially implemented by #1368 . Still missing vertical tabs and icons so I'll keep this one opened

**Comment by LittleWhite-tb** [comment]
Is someone having some ideas for the icons we should use for this tabbed configuration dialog ? It would be cool for the person willing to work on that, to have the ressources ready (even if it is a placeholder).

**Comment by Megamouse** [comment]
looks like this can be closed now

**Comment by Subv** [comment]
I'll leave my subjective opinion here, I don't really like how that KDE dialog looks, the vertical bar with the icons is IMO redundant.

**Comment by GPUCode** [comment]
UI is now tabbed will be closing this
