### ISSUE TITLE
Path separation characters issue in Windows

### ISSUE THREAD

**Issue by reconman** [citra-emu/citra#1184]
citra-qt.exe is trying to load the config and gamelist files like this:
D:\Citra/user/config/qt-config.ini

I think you can't currently run the Windows nightly build on Windows.

**Comment by shinyquagsire23** [comment]
I thought Windows took / characters just fine in paths? In any case it's the safest way to go honestly.

**Comment by reconman** [comment]
Nevermind, the error for the game directory disappeared after specifying it in the program and the warnings for isDirectory didn't show up again at the 2nd start.
