### ISSUE TITLE
Kingdom Hearts Dream Drop Distance (Controller) Input Issues

### ISSUE THREAD

**Issue by VIRGINKLM** [citra-emu/citra#1185]
There's that weird input issue in that game that is puzzling me.
It's really easy to reproduce. You start the game and once you reach the main screen that you can either start a new game or load one, if you select to start a new game a menu pops up telling you that "The game supports Circle Pad Pro. Would you like to use it?" and it gives you under two options, "Yes" and "No". If you press on the keyboard <- (Left) so the indicator will go to "Yes", without pressing "A" to select it, if you try to press -> (Right) to go back to the "No" selection, you will realise that the button is non-responsive and you are unable to select it unless you use the mouse to select it from the screen. Now this issue affects pretty like all options in the game, the pause menu(...) everything rendering impossible to return or select some options, especially the ones that are not selectable on the lower screen via touch input. BTW, no options in the emulator seem to affect this issue and nothing weird is going on in the console, so I can't provide anything more to help.
![untitled-3](https://cloud.githubusercontent.com/assets/3772761/10269110/2160f67e-6ad5-11e5-9f02-d09fd7e8fdab.png)

**Comment by TheSoraHD** [comment]
When trying to type the name of the Dream Eaters, also it works like a double press. Maybe the emulator doesn't release correctly the input?
However, it doesn't affect gameplay at all. Combat and movement works good (at least they don't show any problem even if it's also affected), only menus are heavily affected.

**Comment by smartkaartik** [comment]
May this can help
![68747470733a2f2f692e696d6775722e636f6d2f623852775164512e706e67](https://cloud.githubusercontent.com/assets/14974622/10411769/db80a398-6f8e-11e5-8d4c-8477950eb7da.png)

**Comment by VIRGINKLM** [comment]
@smartkaartik Nope, the keys are simply non-responsive when that happens, we know the key bindings and it's not a mistake on our side, the issue is coding related, like the emulator fails to return a button release after a combination of stuff happen.

**Comment by Subv** [comment]
This appears to be the exact same issue as with Majora's Mask, it has something to do with the Circle Pad Pro codepath that the game takes.

**Comment by VIRGINKLM** [comment]
Maybe one of the buttons of the circle pad pro share the same internal commands with the normal pad and maybe the game tried to check for a second if they are actually there, or even, it constantly actively tries to check if they are there.

**Comment by wwylele** [comment]
Is this fixed by #1510 ?

**Comment by Leo626** [comment]
I tried it and it works properly for me.
