### ISSUE TITLE
Pokemon Mystery Dungeon not working in citra 

### ISSUE THREAD

**Issue by smartkaartik** [citra-emu/citra#1186]
![capture](https://cloud.githubusercontent.com/assets/14974622/10276578/f16da428-6b6d-11e5-989c-e01795653bc2.PNG)

Please Help

**Comment by smartkaartik** [comment]
Description on PC I have
1) With Windows 10 64-Bit 8Gb ram
2)With windows 8.1 32-bit 2gb ram

**Comment by mailwl** [comment]
You have to decrypt the rom first

**Comment by Subv** [comment]
You are using an encrypted rom, please refer to https://github.com/citra-emu/citra/wiki/Decryption to decrypt it.

**Comment by SeannyM** [comment]
fjkeghjofi231pq

**Comment by smartkaartik** [comment]
Thanks Subv
