### ISSUE TITLE
Very Slow speed 

### ISSUE THREAD

**Issue by smartkaartik** [citra-emu/citra#1191]
It emulates the decrypted roms very slowly

**Comment by smartkaartik** [comment]
MY PC SPECS
![capture1](https://cloud.githubusercontent.com/assets/14974622/10343765/277edd40-6d3d-11e5-8a11-5796a413c3d7.PNG)

**Comment by bankkopf** [comment]
It doesn't even run full speed on latest high-end CPUs so it will be very slow on your laptop. 
Else this is no noteworthy issue.

**Comment by pauldacheez** [comment]
That CPU probably can't even run any DS games at full speed (besides maybe the first Ace Attorney). How the fuck do you expect it to run a *3*DS emulator at even half-speed, especially this early in the emulator's life where it doesn't even have a JIT for the CPU?
