### ISSUE TITLE
Pokemon neo y elite not working

### ISSUE THREAD

**Issue by smartkaartik** [citra-emu/citra#1197]
The rom is Decrypted.......
CMD PIC
![rom](https://cloud.githubusercontent.com/assets/14974622/10409227/7a00186a-6f34-11e5-8c64-2391daf41965.PNG)
Please help

**Comment by RavenHome1** [comment]
none of the pokemon games boot atm, check again when a major change is made

**Comment by archshift** [comment]
This issue report is pretty unhelpful, and we know the Pokemon games don't work.

**Comment by mailwl** [comment]
i think, problem is other (not ldr::ro, like in pokemon y, for example). something don't let start the main thread
