### ISSUE TITLE
Pokemon Y error

### ISSUE THREAD

**Issue by hiperion99** [citra-emu/citra#1203]
I wanted to run pokemon y and this error code was shown:
![image](https://cloud.githubusercontent.com/assets/15111613/10463378/9a529a04-71e4-11e5-90a8-7080116104d6.png)
If there is a thread where this is explained,please give me a link or try to help me.
Thanks in advance.
P.S. I know basics of c++ so please explain me as good as you can.Sorry for grammar

**Comment by jroweboy** [comment]
Likely the same issue as all the other pokemon games. See https://github.com/citra-emu/citra/issues/1197 for one instance of it.

**Comment by hiperion99** [comment]
So i cant play pokemon y now?

**Comment by jroweboy** [comment]
Nope. Please close this issue as its already documented that Pokemon games don't work yet. :) https://github.com/citra-emu/citra/issues?utf8=%E2%9C%93&q=is%3Aissue+pokemon

**Comment by hiperion99** [comment]
Thank you,one more question,can you tell my roughly when will this problem be fixed?

**Comment by jroweboy** [comment]
No clue. It'll be fixed when a developer takes up the task and implements the needed code for it.

**Comment by hiperion99** [comment]
Thanks :D

**Comment by hiperion99** [comment]
How to close issue?
