### ISSUE TITLE
Jett Rocket II The Wrath of Taikai - multiple graphic bugs/ untextured models

### ISSUE THREAD

**Issue by Punk34** [citra-emu/citra#1206]
The game runs on pretty fast, about 50-60fps. But these bugs

![000](https://cloud.githubusercontent.com/assets/13983158/10522160/6307ebaa-737c-11e5-9147-daa6ed216308.jpg)

**Comment by neobrain** [comment]
Sorry, but this bug report contains virtually no information which would be useful for debugging, and we aren't looking for plain "Game XY doesn't work" reports.
