### ISSUE TITLE
error on starting 

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#1213]
![capture](https://cloud.githubusercontent.com/assets/12820322/10662126/ef25edec-78ba-11e5-9f09-c47265d7550d.PNG)

**Comment by durazell** [comment]
Did you compile it yourself? Looks like linking problem to me

**Comment by RavenHome1** [comment]
Nope. This is a download from the nightly builds, seems like someone made a derp

**Comment by Andrix44** [comment]
Try to download Visual C++ Redistributable (https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by smartkaartik** [comment]
Same prob,i added all of them but another problem refer #1215

**Comment by RavenHome1** [comment]
I already have redist package, the issue is not from it it seems

**Comment by neobrain** [comment]
Please don't abuse our issue tracker for user support.

**Comment by RavenHome1** [comment]
@neobrain i am confused as if this is an issue on citra's end or the use end?
