### ISSUE TITLE
error loading a ROM

### ISSUE THREAD

**Issue by laweacuanticaatomica** [citra-emu/citra#1214]
Im getting this problem everytime that i load a ROM of TloZ OoT 3D, help pls :c
![captura](https://cloud.githubusercontent.com/assets/15258047/10683630/8e0253da-7909-11e5-88df-797c5204e3a1.PNG)

**Comment by archshift** [comment]
There is no issue here; the screenshot you posted isn't even of an error.

**Comment by laweacuanticaatomica** [comment]
what should i do then?

**Comment by smartkaartik** [comment]
Just wait for the screen to come up.After loading it.

**Comment by neobrain** [comment]
Please don't abuse our issue tracker for user support.
