### ISSUE TITLE
Citra not running

### ISSUE THREAD

**Issue by smartkaartik** [citra-emu/citra#1215]
After i inserted all the dlls on my windows 8.1 pc i got the following error : "the produce entry point strncmp could not be located in dynamic link literary C:/Users/             /Desktop/citra/Qt5OpenGl.dll"
Window title is Entry point not found.

Please Help!

It is running well but slow on my another pc as it has 1.20 ghz processor.So i upgraded my another pc form 32 bit to 64 with 3.50 ghz processor but i am not able to run it

**Comment by neobrain** [comment]
Please don't abuse our issue tracker for user support.

**Comment by smartkaartik** [comment]
Hey neobrain if you you have too much of brain then solve this issue

**Comment by smartkaartik** [comment]
It is a latest citra issue
