### ISSUE TITLE
Homebrew causes Citra to freeze while trying to print out double values with printf

### ISSUE THREAD

**Issue by iamevn** [citra-emu/citra#1218]
Not really sure what's going on here but I've been getting freezes seemingly randomly while trying to print out double values with printf and format strings
example code: https://gist.github.com/iamevn/b6163562f03ed9068ac4 ([.3dsx](http://puu.sh/kVcXN/35c6061f40.3dsx))

I haven't managed to reproduce this freeze on the actual hardware so I'm pretty sure it isn't a bug in ctrulib or something like that.

**Comment by archshift** [comment]
By randomly, do you mean that the freeze does not always occur?

**Comment by iamevn** [comment]
Yeah, sometimes works and sometimes freezes.

**Comment by Subv** [comment]
It actually seems to freeze specifically when trying to print 3.8, weird

**Comment by Subv** [comment]
Trying to print 1000.6 http://i.imgur.com/TZNEYZK.png
This looks like a printf bug?

**Comment by Subv** [comment]
The bug only appears when using mfloat-abi=hard. The soft and softfp float implementations do not have this problem. It seems to be a bug in our VFP implementation, it has some differences with what the 3DS actually does.
I'm assigning this one to @lioncash
