### ISSUE TITLE
Citra not running

### ISSUE THREAD

**Issue by smartkaartik** [citra-emu/citra#1219]
After i inserted all the dlls on my windows 8.1 pc i got the following error : "the produce entry point strncmp could not be located in dynamic link literary C:/Users/ /Desktop/citra/Qt5OpenGl.dll"
Window title is Entry point not found.

Please Help!

It is running well but slow on my another pc as it has 1.20 ghz processor.So i upgraded my another pc form 32 bit to 64 with 3.50 ghz processor but i am not able to run it

**Comment by yuriks** [comment]
Argh.

**Comment by smartkaartik** [comment]
What"s that problem

**Comment by smartkaartik** [comment]
????????????????????????????????????????????????

**Comment by smartkaartik** [comment]
How to Solve this.

**Comment by yuriks** [comment]
This is not a Citra issue, it's an issue on your setup, now go ask for support somewhere else. This bug tracker is for development.

**Comment by smartkaartik** [comment]
Is it the problem of windows

**Comment by smartkaartik** [comment]
???

**Comment by smartkaartik** [comment]
If so help

**Comment by Syphurith** [comment]
@smartkaartik I'm very sorry, but this tracker is for development use. You might go to gbatemp to ask for some support (if there is). BTW you could provide more infomation, including the screenshots or system details to who can help. Also the posts on github can be modified, just click the pencil there.

**Comment by smartkaartik** [comment]
I know
But i have changed 2 windows but same problem

**Comment by smartkaartik** [comment]
Currently windows 8.1

**Comment by yuriks** [comment]
A nice way of annoying developers and making them not want to help you is to spam their Inbox with zero-signal GitHub notifications. Now please go elsewhere.
