### ISSUE TITLE
Update Loader to reflect 3dsxdump changes

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#1220]
A recent fix to 3dsxdump [1] fixed support for exception handling in 3dsx applications. The homebrew 3dsx loaders are affected by this too, but no public changes have surfaced yet for this. Either way, Citra's loader is out of date and needs to be adjusted according to the cited 3dsxdump change.

[1] https://github.com/devkitPro/3dstools/commit/47bea18f5cded3437552e3af968aa1356e2d6f3e#diff-8bc872c01cd7836116ee2424e204e9c9

**Comment by JayFoxRox** [comment]
did anybody do this yet?

**Comment by yuriks** [comment]
This was implemented in #2450
