### ISSUE TITLE
Make a downloads page somewhere!

### ISSUE THREAD

**Issue by Jkhemili** [citra-emu/citra#1224]
There is no way that dumping the games is currently the only way to get roms. Make a downloads page somewhere for downloadable 3ds roms.

**Comment by CryZe** [comment]
You can download Hombrew Applications here: http://www.3dbrew.org/wiki/Homebrew_Applications

**Comment by Jkhemili** [comment]
Well, still make a page where I can download the games.

**Comment by archshift** [comment]
We don't encourage piracy here, and homebrew can be very easily found by using Google.
