### ISSUE TITLE
Black screen on the top when I use Config Savegame from FW10.2

### ISSUE THREAD

**Issue by Punk34** [citra-emu/citra#1226]
This happens in every game. Config Savegame from the firmware 4.0 works fine, but it is not suitable for the newest games! When I use Config Savegame from FW10.0 i get this:
![01](https://cloud.githubusercontent.com/assets/13983158/10845665/c9133c3e-7f1a-11e5-95b0-8f0c18b35c2f.jpg)

Even in older games!

**Comment by archshift** [comment]
This happens in every game you've tried?

**Comment by Punk34** [comment]
Yeap. Only with Config Savegame from FW10

**Comment by Jkhemili** [comment]
How is it possible to even play games at all?

**Comment by Subv** [comment]
Maybe it has something to do with the 3D screen calibration data?

**Comment by JayFoxRox** [comment]
What happened to this?

**Comment by B3n30** [comment]
Closing this since it is very old, might be fixed already and the bug report is missing essential info to investigate (e.g. a log)
