### ISSUE TITLE
10 in 1 Arcade Collection and next several games are crashing at command_processor.cpp line 286

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1227]
Tested on latest commit https://github.com/citra-emu/citra/commit/7c12ee9ecc9ccfc6ab051cebfb7d238acc867de3

Next affected games:
- Culdcept
- Fossil Fighters: Frontier
- Horrid Henry: The Good, The Bad & The Bugly
- Inazuma Eleven
- Lego Games
- Rage of the Gladiator
- Vacation Adventures - Park Ranger, Vacation Adventures 2
- Yowamushi Pedal: Ashita e no High Cadence

Pointing to https://github.com/citra-emu/citra/blob/master/src/video_core/command_processor.cpp#L286

![arcade 1](https://cloud.githubusercontent.com/assets/11453507/10866160/a6145e34-8023-11e5-8c5a-ad0247bc3d05.PNG)

LOG: http://pastebin.com/dzmS6ZAX

**Comment by Zaneo** [comment]
@JohnGodgames Is this still the case? There have a number of commits to command_processor.cpp

**Comment by JohnGodgames** [comment]
Ahh forget to close.Most of those crashes fixed by https://github.com/citra-emu/citra/pull/1394 ...

**Comment by Subv** [comment]
#1394 has not been merged

**Comment by JohnGodgames** [comment]
@Subv yes I know, but I think that this issue is bad.
