### ISSUE TITLE
Shin Megami Tensei IV - bottom screen does not work

### ISSUE THREAD

**Issue by Padre-Ramirez** [citra-emu/citra#1231]
I mean nothing is displayed on the bottom screen

the console is non stop spamming the message: HW.GPU <Error> video_core\command_processor.cpp:Pica::CommandProcessor::WritePicaReg:94: Invalid VS default attribute index 16

![citra](https://cloud.githubusercontent.com/assets/15618608/10893632/efc48dea-81ba-11e5-85ea-9209275415ad.jpg)

**Comment by Subv** [comment]
Duplicate of #945
