### ISSUE TITLE
Gateway homebrew not supported?

### ISSUE THREAD

**Issue by Jkhemili** [citra-emu/citra#1232]
For some odd reason, when I try to use most homebrew, it does not work. I need Gateway to make like a storage folder or something like that. Can you please fix this?

**Comment by archshift** [comment]
Could you give an example of homebrew that doesn't work?

**Comment by Jkhemili** [comment]
Umm...like GATEWAY!!!. Please! I need it to make and finish the storage on the emulator.

**Comment by yuriks** [comment]
What the hell are you talking about?

**Comment by Jkhemili** [comment]
Well, then, what do you suggest me using for building the storage because I don't even have a 3ds.

**Comment by yuriks** [comment]
Again, what are you talking about? What "storage" are you talking about? And Gateway isn't even ARM11 software.

**Comment by Jkhemili** [comment]
Oh, then what is? I am talking about stuff like the home menu and stuff that allows you to run a rom properly.
