### ISSUE TITLE
crushes on startup 

### ISSUE THREAD

**Issue by smartkaartik** [citra-emu/citra#1233]
When I open Citra qt then it opens but when I load a rom it says program has stopped working!!! What can I do.

**Comment by smartkaartik** [comment]
Should I reinstall windows

**Comment by smartkaartik** [comment]
Windows is 8.1 should I change it to 10

**Comment by archshift** [comment]
This is a duplicate issue.

**Comment by smartkaartik** [comment]
What duplicate

**Comment by smartkaartik** [comment]
My problem is other.

**Comment by smartkaartik** [comment]
I checked his screenshots they differ from my
