### ISSUE TITLE
Rom loading error

### ISSUE THREAD

**Issue by smartkaartik** [citra-emu/citra#1234]
When I try to load the rom. A message pop up "the program has stopped working"

I have tried it in 3 different versions 

In first one
![screenshot](https://cloud.githubusercontent.com/assets/14974622/10995266/93da46ac-84a1-11e5-8d4f-e136ce727db9.jpg)
In second 
![screenshot001](https://cloud.githubusercontent.com/assets/14974622/10995272/9dd4be4e-84a1-11e5-84af-e252765d0bbb.jpg)
In third
![screenshot002](https://cloud.githubusercontent.com/assets/14974622/10995287/a71ecefe-84a1-11e5-8f86-a93449e0b556.jpg)

When i use windows 8.1 the same error i got so i thought of upgrading it to windows 10 to solve it as in my another windows 10 pc it is working.

**Comment by smartkaartik** [comment]
help

**Comment by smartkaartik** [comment]
help

**Comment by RavenHome1** [comment]
for citra crashing this is caused by the game as some process or function is not emulated/is causing citra to crash, i had this issue runing a game myself. you can try another game if you want and see if it works, if it continue to crash then try updating your graphic driver

**Comment by smartkaartik** [comment]
No I tried 3-4 roms

**Comment by smartkaartik** [comment]
I'll try graphic driver

**Comment by Andrix44** [comment]
@smartkaartik Could you stop spamming, please?

**Comment by Jkhemili** [comment]
Be careful, upgrading can do some damage.

**Comment by smartkaartik** [comment]
OK

**Comment by smartkaartik** [comment]
Doesn't work

**Comment by RavenHome1** [comment]
i am not sure then, just close this for now so we won't kill everyone with notification spam and try at a later time when a major release is made

**Comment by smartkaartik** [comment]
I need help

**Comment by smartkaartik** [comment]
Please

**Comment by OatmealDome** [comment]
I'd recommend you scroll all the way down in the console window and take a screenshot of that so we can see where exactly it's crashing. Also, list what games you are trying to play.

Note that the issue tracker isn't meant as a support forum. If you follow RavenHome1's instructions to join the citra IRC, you may be able to find help there.

**Comment by smartkaartik** [comment]
OK

I am trying to boot:
1)pokemon mystery dungeon
2)legend of zelda ocarina of time
3)cave story
4)RayOrigenes

Please note i an using decrypted roms and all of them are working in my another pc


Secondly I tried https://webchat.freenode.net/ but i didn't understand it.

**Comment by RavenHome1** [comment]
@smartkaartik you said that they all work in another pc. then most likely it's a hardware/software issue on your end, jump into the chat i mentioned before and use #citra as a channel and ask for some support in there.

**Comment by smartkaartik** [comment]
I think it s a software issue

**Comment by yuriks** [comment]
@smartkaartik Stop spamming the issue tracker with support requests or I'll be force to ban you.

**Comment by smartkaartik** [comment]
So where I can go for help

**Comment by yuriks** [comment]
The IRC channel is the only official support channel. Otherwise you can go to some community site like reddit's r/emulation.

**Comment by smartkaartik** [comment]
But I didn't know how to use IRC channel
