### ISSUE TITLE
Relicense to GPLv2+

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#124]
Really, sticking with GPLv2 is just going to cause us more trouble than it's worth. Fwiw, most of the Dolphin contributors that have copyright over code in Dolphin's "Common" library have agreed to relicensing their code to GPLv2+, so I don't think we have any dependencies which are truly GPLv2-only anymore.

Obviously should ask the people who contributed to citra so far about their opinion on this and their green light on relicensing the existing Citra code.

**Comment by bunnei** [comment]
Done. Closed.
