### ISSUE TITLE
Citra crashes whenever I try to emulate any game.

### ISSUE THREAD

**Issue by SalamanderNatsu** [citra-emu/citra#1240]
I have done everything, I checked Use Hardware Renderer, I've tried launching citra-qt as an administrator, I have downloaded the user folders and I have decrypted my .cia files, but no matter what I do citra-qt just keeps on crashing. I've been looking all over the internet for solution, but there's nothing. This is my last option so pls help. The screenshot is down below.
![screenshot_1](https://cloud.githubusercontent.com/assets/15838828/11156993/4aa7cd70-8a4f-11e5-87f7-b11974a92292.png)

**Comment by Punk34** [comment]
update ogl drivers

**Comment by vgturtle127** [comment]
@SalamanderNatsu Can we have your computers specifications and your operating system, please?

**Comment by SalamanderNatsu** [comment]
Here
![screenshot_2](https://cloud.githubusercontent.com/assets/15838828/11162819/dc6f6782-8ab2-11e5-8cce-cb1e60cb2b37.png)

**Comment by RavenHome1** [comment]
your computer is a veteran at this point. you should consider a new machine

**Comment by SalamanderNatsu** [comment]
I don't have that much money

**Comment by RavenHome1** [comment]
@SalamanderNatsu and?...

**Comment by mailwl** [comment]
купи себе 3дс и не парься

oops, sorry. TS, buy 3ds, its cheap, and don't fu.. our minds

**Comment by OatmealDome** [comment]
Are you trying to run games in Citra to play them? like mailwl said, it's best that you buy a 3DS instead.

**Comment by vgturtle127** [comment]
He has a modern 64-bit dual-core and 4GB of RAM. The bottleneck is his graphics, he is running integrated graphics. So, my recommendation would be to buy a cheap graphics card, preferably an Nvidia card since those are way better at emulation.

But if you want to play 3DS games to enjoy them, you would need either an extreme custom PC, or just get a 3DS and run homebrew on it for maximum enjoyment.

**Comment by SalamanderNatsu** [comment]
I figured it out, Citra needs OpenGL 3.3 and I have 3.1

**Comment by vgturtle127** [comment]
OK. That further explains why my point is accurate. You should get a graphics card, you won't regret it.
