### ISSUE TITLE
Disable OpenGL renderer in Citra

### ISSUE THREAD

**Issue by SalamanderNatsu** [citra-emu/citra#1243]
Is there a way to disable OpenGL rendering in Citra?

**Comment by Road-Drum** [comment]
you want to use DirectX? afaik citra is OpenGL only (for now)

**Comment by SalamanderNatsu** [comment]
I want Citra to stop freezing. I have OpenGL 3.1 and that's the highest update for it from Intel for now.

**Comment by mrfuuton** [comment]
Have some patience. These things take time, and a lot of coffee.

**Comment by SalamanderNatsu** [comment]
I'll check back every once in a while to see if there's some progress.

**Comment by bunnei** [comment]
Going to close this one. There are no plans to support versions of OpenGL prior to 3.3. We would basically need to use deprecated functionality to do this, and as time goes on, increasingly fewer people are using pre-3.3 HW. Even if we supported DirectX, we would be using modern features that your GPU likely wouldn't support. And lastly, even if the SW renderer did not require OpenGL 3.3, it would be so slow that it would only be useful for development.

If you really would like to use Citra for development, and can't get a newer GPU, it would be very easy for you to make your own build that uses OpenGL 3.1 for the SW renderer.
