### ISSUE TITLE
Missing Config block 0x170000 in BOXBOY!

### ISSUE THREAD

**Issue by exhalatio** [citra-emu/citra#1258]
Hi!
Missing Config block 0x170000 in BOXBOY!
The following error message.

[  16.957686] Service.CFG <Error> core\hle\service\cfg\cfg.cpp:Service::CFG::GetConfigInfoBlock:236: Config block 0x170000 with flags 2 and size 4 was not found

**Comment by Punk34** [comment]
You need to dump "Config Savegame" from your 3DS

**Comment by Punk34** [comment]
This game probably requires the latest version, that is not working properly on Citra
https://github.com/citra-emu/citra/issues/1226

**Comment by yuriks** [comment]
I'll look into adding support for generating dummy data for this block at some point, thanks.

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1732
