### ISSUE TITLE
Image not found Mac error.

### ISSUE THREAD

**Issue by braydenk0916** [citra-emu/citra#1265]
I use a Mac OS X 10.9.5 and tried to run Citra and it keeps saying this in the terminal.
/Users/??????/Downloads/citra-20151201-644d1e7-osx-amd64/citra ; exit;
dyld: Library not loaded: /usr/local/opt/glfw3/lib/libglfw3.3.dylib
  Referenced from: /Users/??????/Downloads/citra-20151201-644d1e7-osx-amd64/citra
  Reason: image not found
Trace/BPT trap: 5
logout

**Comment by archshift** [comment]
You need to install glfw with homebrew.

**Comment by braydenk0916** [comment]
and how do I install that version?(3.3)

**Comment by mailwl** [comment]
outdated issue, should be closed

**Comment by BarryMode** [comment]
@gamizard was never answered, so I'll post what I found worked for installing 3.3

```
brew install --HEAD glfw
```
