### ISSUE TITLE
Rune Factory 4 SW mode bug and HW mode Black Screen 

### ISSUE THREAD

**Issue by amirlou** [citra-emu/citra#1268]
hello today i tired Rune Factory 4 on last nightly Build on Windows 10 on SW mode i get low frame lots of Glitch on HW mode black Screen only but i noticed some thing when i was switching from SW mode to HW mode for small moment i see game screen on HW mode Before its Go to black i took screenshot of all of them i dont understand problem need some help 

![sw mode](https://cloud.githubusercontent.com/assets/16171668/11613202/da550e98-9c2d-11e5-8b2a-f97011128655.jpg)
![hw mode](https://cloud.githubusercontent.com/assets/16171668/11613204/e428836e-9c2d-11e5-9d11-3cf74ffdd110.jpg)
![switch from sw to hw moment](https://cloud.githubusercontent.com/assets/16171668/11613205/ea4639bc-9c2d-11e5-95ef-764a6ffe5407.jpg)

[New Text Document.txt](https://github.com/citra-emu/citra/files/53140/New.Text.Document.txt)

**Comment by Punk34** [comment]
Hah! This happened to me on a real console too
![mlwa77stoiavom0cl0](https://cloud.githubusercontent.com/assets/13983158/11613469/be4a866a-9c32-11e5-9702-22b7d746dd4b.jpg)
![zlcfzswxphorixqtpv](https://cloud.githubusercontent.com/assets/13983158/11613470/be4b7192-9c32-11e5-9d13-1a3905d5e759.jpg)

**Comment by amirlou** [comment]
how did you fix it on console ?

**Comment by Punk34** [comment]
restart the game

**Comment by amirlou** [comment]
so no one know what is Problem With black Screen on Citra For This Game  ?

**Comment by Subv** [comment]
This is not a valid bug report, there's no revision information and the provided log file is incomplete
