### ISSUE TITLE
Paypal - This recipient is currently unable to receive money.

### ISSUE THREAD

**Issue by TheCherry** [citra-emu/citra#1273]
Paypal says: This recipient is currently unable to receive money.

Do you have a Bitcoin wallet too?

**Comment by mailwl** [comment]
bitcoin is bad idea, at least in Russia it forbitten

**Comment by yuriks** [comment]
For the time being, if you want to donate, contact @bunnei via private message in IRC.

**Comment by bunnei** [comment]
See https://citra-emu.org/page/donate for updated info on how you can donate!
