### ISSUE TITLE
Citra just crashes if OpenGL not found

### ISSUE THREAD

**Issue by thebigsmileXD** [citra-emu/citra#1275]
Just crashes. But no information that OpenGL is missing, maybe add a check if OpenGL is installed?

**Comment by shinyquagsire23** [comment]
Honestly most modern systems should have OpenGL installed by default, if you don't have it installed I'm legitimately wondering how you've gone without it.

**Comment by thebigsmileXD** [comment]
I tried to run it on a Win2012 server. That doesn't have that installed ;)

**Comment by exhalatio** [comment]
I tried to run it on a Win2012 server with VMWare.
I look at the OpenGL error message.

Screenshot here
http://i.imgur.com/COAaQ2A.png

True, VMWare does not meet the minimum requirements.
It is correct that the error message is displayed.

**Comment by thebigsmileXD** [comment]
I ran it without VMWare, but still, its the same error

**Comment by Zaneo** [comment]
Does this need to be in the issue tracker? Perhaps you are requesting that there be some sort of dialog that informs the user that OpenGL was unable to be initialized?

**Comment by LittleWhite-tb** [comment]
This dialog is coming with #1344 :)

**Comment by thebigsmileXD** [comment]
Thx

**Comment by JayFoxRox** [comment]
#1344 has been merged so I'll close this. Please inform me if this is wrong
