### ISSUE TITLE
Citra won't start

### ISSUE THREAD

**Issue by pokemon2112** [citra-emu/citra#1276]
Hi i have problem with emulator, when i click on citra icon it's crash, when I click on citra-qt icon emulator star working but I can't do anything. I tried to run rom and have loader error and fronted critical, what it could be?? how can i fix it?? And one more information i can't configure anything:(

**Comment by bunnei** [comment]
You're probably using an encrypted ROM. You need to use a 3DS to dump/decrypt games. See https://github.com/citra-emu/citra/wiki/Dumping-Game-Cartridges for more information.
