### ISSUE TITLE
Tomodachi Life freezes after resetting save data

### ISSUE THREAD

**Issue by popalous** [citra-emu/citra#1278]
This game starts fine, and says save data is corrupted, after resetting it freezes.

LOG:
http://pastebin.com/KW7DLsuL

**Comment by Subv** [comment]
Could you please test #1302 ?

**Comment by archshift** [comment]
Why did you close this? If it was fixed with the PR, this issue still shouldn't be closed as the PR hasn't been merged yet.

**Comment by popalous** [comment]
my little brother got on my computer, sorry about that. reopened

**Comment by Subv** [comment]
Is this fixed?

**Comment by MattKackles** [comment]
@Subv 
Currently goes ingame but freezes due to software keyboard being unimplemented.
https://github.com/citra-emu/citra/issues/1980

**Comment by JayFoxRox** [comment]
Open a new issue about the keyboard and / or report it in #1980
This original issue looks fixed to me then, according to your description.
