### ISSUE TITLE
Unclear ARM disassembler license status - potential license conflict

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#1280]
https://github.com/citra-emu/citra/blob/402692c08d7abf5e2ac3a9b039ac00670fc45ae1/src/core/arm/disassembler/arm_disasm.cpp says `Copyright 2006 The Android Open Source Project`, which is far from descriptive to say the least. In fact, a quick web search seems to suggest that the AOSP is licensed under Apache 2.0, which is not compatible with GPL v2, which is intended to be a valid licensing option for Citra.

**Comment by mailwl** [comment]
maybe just ask google change the license? i don't think they say no

**Comment by archshift** [comment]
Lol. Google changing the license of a file just for us has literally no chance of happening.

**Comment by mailwl** [comment]
why not? do you think google people is not... ah don't know english word for russian variant
samsung even change the code of tizen for us (russian company), why google can not change license

**Comment by TheDcoder** [comment]
Did you try google translate? :P

**Comment by mailwl** [comment]
@TheDcoder , thanks a lot, the word is "inconversable"

**Comment by TheDcoder** [comment]
Glad to be useful :)

**Comment by neobrain** [comment]
Testing the IRC bot, ignore this comment.

**Comment by JayFoxRox** [comment]
Referencing #1480 as it's a (non-functional) problem with the current debugger

**Comment by yuriks** [comment]
Made obsolete by #2689 (debugger removed)
