### ISSUE TITLE
Can't open application

### ISSUE THREAD

**Issue by Willi8910** [citra-emu/citra#1285]
![capture jpg2123](https://cloud.githubusercontent.com/assets/16332498/11863513/098d91fc-a4c7-11e5-889c-1c3ca8e0938e.JPG)

**Comment by Willi8910** [comment]
i have tried reinstalling the program but it is still same as before

**Comment by tr4nquility** [comment]
You need to install Microsoft Visual C++ Redistributable 2015 ...
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by Willi8910** [comment]
okay thanks a lot it can be started now
