### ISSUE TITLE
Can't open Kingdom hearts 3d

### ISSUE THREAD

**Issue by Willi8910** [citra-emu/citra#1286]
![sac](https://cloud.githubusercontent.com/assets/16332498/11886022/b5a2c116-a557-11e5-9bf2-d7dcc0959953.JPG)
I tried to open the game it has been like this
game size is 1,8gb if you want to know

**Comment by Subv** [comment]
Your rom is encrypted, see the wiki for the decryption guide

**Comment by neobrain** [comment]
This totally is a valid issue!

**Comment by neobrain** [comment]
Nevermind, just testing the bot. This is totally invalid.
