### ISSUE TITLE
unimplemented - GetConnectionStatusEvent

### ISSUE THREAD

**Issue by Punk34** [citra-emu/citra#1292]
Almost all new games doesn't work and gives this error. Maybe it's the new protection to determine who play games without buying them in the eShop?

In any case, the newest games not work on citra for this reason

![01](https://cloud.githubusercontent.com/assets/13983158/11963638/65617f9e-a8f9-11e5-8060-b378d390c2c7.png)

**Comment by Punk34** [comment]
some of them:
steamworld heist
legend of dark witch 2
mario and luigi paper jam

**Comment by Subv** [comment]
This function is related to the Circle Pad Pro

**Comment by mailwl** [comment]
long time ago i umplemented such functions, but don't remember if it helps torun any games, here the code
[ir.zip](https://github.com/citra-emu/citra/files/70541/ir.zip)

**Comment by Punk34** [comment]
mailwl, I'm sorry, but I can not install visual studio and build the emulator with these files. not because I do not know how, but because this is install new updates on my server's os and bring me problems. but if you build a win version of citra for me, i be able to test a lot of games

**Comment by mailwl** [comment]
[citra_ir.zip](https://github.com/citra-emu/citra/files/72225/citra_ir.zip)

here. x64 VS 2015
let Dragon Quest VIII go through GetConnectionStatus panic

**Comment by Punk34** [comment]
Oh, that's great! you should add it on the master!!!

![01](https://cloud.githubusercontent.com/assets/13983158/12003936/3ef94a82-ab45-11e5-90a9-995304d92d29.jpg)
![02](https://cloud.githubusercontent.com/assets/13983158/12003937/3f20ff28-ab45-11e5-8e51-4feaf3e47df0.jpg)
![03](https://cloud.githubusercontent.com/assets/13983158/12003938/3f245e0c-ab45-11e5-905c-da97424d2987.jpg)

**Comment by RavenHome1** [comment]
i managed to get majora's mask up to this point but it won't go past it and i the don't use button does not work if i press it 
![majora](https://cloud.githubusercontent.com/assets/12820322/12006376/be30509c-abdc-11e5-9862-054ae33d1b16.PNG)

**Comment by mailwl** [comment]
is the majora mask works fine without ir-related code?
i know the code is not perfect (i did even know, it's circle pad related :). so it may break compatibility

**Comment by RavenHome1** [comment]
no majoras mask completely breaks without your code see https://github.com/citra-emu/citra/issues/954

**Comment by Punk34** [comment]
Paper Jam is working with mailwl's code

![01](https://cloud.githubusercontent.com/assets/13983158/12009975/c04a4786-aca2-11e5-8835-0accecbe37a8.jpg)

**Comment by JohnGodgames** [comment]
### ir files helps too:
* IronFall Invasion - https://www.youtube.com/watch?v=NdEK57qsjII 
* The Legend of Zelda: Tri Force Heroes  - https://www.youtube.com/watch?v=MixG9O0Wpro

**Comment by mailwl** [comment]
@Subv, may you add the code to citra? as initial support of ir

**Comment by wwylele** [comment]
@mailwl why not just open a pull request

**Comment by mailwl** [comment]
i am too lazy, sorry :( and don't know git enough good

**Comment by bunnei** [comment]
Fixed by #1418
