### ISSUE TITLE
JMP compilation in the Shader JIT is fundamentally broken

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#1293]
The implementation of the JMP family instructions in the vertex shader JIT is broken. For certain programs, the generated control flow will jump to a random branch point in the program, causing certain parts of shaders to be completely skipped.

This happens when a jmp instruction jump over another jmp which itself jumps to a label beyond the target of the original jmp, like so:

```
    jmp label_1
    nop
    jmp label_2
label_1:
    nop
label_2:
    end
```

The first JMP will emit a branch, then initiate a nested loop compiling instructions until label_1. However, when it tries to compile `jmp label_2`, that will initiate another nested loop compiling until `label_2`. When this loop eventually finishes, it will return to the outer jmp compilation loop, which will notice it has passed `label_1` already and set the jump target. The end result is that both jmp instructions will jump to `label_2`.

**Comment by hiperion99** [comment]
When will you implement CROs (CTR Relocatable Objects)?

**Comment by bunnei** [comment]
@hiperion99 that's totally unrelated to this issue.

**Comment by hiperion99** [comment]
I know,but there is no other place i could ask and yuriks is (i think) the best guy to ask that.

**Comment by MoochMcGee** [comment]
There's the citra IRC dude.

**Comment by yuriks** [comment]
I added some more concrete information to this bug after debugging it yesterday. This will require a redesign of the JIT compile so that it does better control flow analysis of the source program.

**Comment by yuriks** [comment]
This likely affects Ironfall, which is missing lighting in the JIT.
