### ISSUE TITLE
Incomplete or improper file stat

### ISSUE THREAD

**Issue by Cruel** [citra-emu/citra#1295]
To recreate, using ctrulib:

```c
char *path = "sdmc:/3ds/";
struct stat s;

if( stat(path, &s) == 0 )
{
	if(S_ISDIR(s.st_mode)) {
		printf("it's a directory");
	}
	else if(S_ISREG(s.st_mode)) {
		printf("it's a file");
	}
	else {
		printf("something else");
	}
}
else {
	printf("error");
}
```

Assuming you have a "3ds" directory in sdmc, it says it's a file. All directories and all files seems to be seen as "regular files" (i.e. return true after a S_ISREG).

**Comment by Subv** [comment]
I'm pretty sure i fixed this exact same issue a while ago

**Comment by Subv** [comment]
Yep, here it is #1067, I wonder why it's broken again, maybe this is the cause for MK7's hang?

**Comment by Subv** [comment]
I just tested this locally with https://gist.github.com/Subv/41a1039fcbd8a9e13a5b and it correctly says that "3ds" is a directory. What operating system are you using?

**Comment by Cruel** [comment]
I'm using Linux with ext4 filesystem.

**Comment by Cruel** [comment]
Well, fopen returns non-null when opening a directory (at least for read-only in Linux). So it seems to be failing with the `IOFile::IsOpen` check you added.

I have fixed this for my particular program by doing a `FileUtil::IsDirectory` check:

```c
if (FileUtil::IsDirectory(path))
    return false;
```

I originally put this in `IOFile::Open` but it seems like it may be more appropriate in `DiskFile::Open` since there is also a check in `DiskDirectory::Open` checking that it *is* a directory, so I guess it would make sense to check that it *isn't* for `DiskFile`.

It works for my program in either function, but I will have to defer to someone who knows more about these classes and their purpose. I don't know is `IOFile` is supposed to manage directories too.

Additionally, it would be nice if another linux user could confirm this issue so we can be sure I just didn't screw something up lol.

**Comment by Subv** [comment]
Could you please test #1302 ?

**Comment by Cruel** [comment]
Yeah, solves this issue.
