### ISSUE TITLE
WaitSynchronizationN should (probably) not acquire Semaphores more than once

### ISSUE THREAD

**Issue by Subv** [citra-emu/citra#1308]
If you call WaitSynchronizationN with N handles all pointing to the same Semaphore object, Citra will currently acquire the semaphore N times, which may result in the Semaphore being locked.

We should verify if this is indeed hardware behavior.

**Comment by wwylele** [comment]
(If I understand this correctly)
Hardware behaviour verified: is the same as citra's behaviour. This can be closed.
[Here is the test](https://github.com/wwylele/ctrhwtest/tree/master/semaphore_acquire_n)

**Comment by Subv** [comment]
You set the semaphore to have 10 free slots, but only acquire it 3 times, the problem manifests when you acquire it more times than are available in the semaphore.

**Comment by wwylele** [comment]
@Subv updated the test ([3ef30a5](https://github.com/wwylele/ctrhwtest/tree/3ef30a59b792122bbfc844f3486ec879c82b5b0e/semaphore_acquire_n)). The last test is acquire the semaphore 3 times when the available count is 2. The behaviour of 3DS and citra is still the same: didn't time out, decrease the count to zero. Citra's code just magically works.

**Comment by Subv** [comment]
Why does it work?

**Comment by wwylele** [comment]
citra's code logic for WaitSynchN-wait-all is like: check all objects, if all of them are available, then acquire *each object that is available* ; otherwise wait the thread. So it works

**Comment by Subv** [comment]
Could you upload a 3dsx of this test please?

**Comment by wwylele** [comment]
@Subv https://www.dropbox.com/s/2blq0qptizagi08/semaphore_acquire_n.3dsx?dl=1

**Comment by Subv** [comment]
I see what happens, for the last Acquire() call, ShouldWait() returns true, thus the call is not performed, leaving the available_count of the semaphore in 0 instead of underflowing.
This does not make much sense, but then again, passing the same semaphore multiple times to WaitSynchN doesn't make much sense either, and this is apparently the same behavior as the hardware.

I'll just close this.
