### ISSUE TITLE
Aqua Moto Racing 3D - (UNIMPLEMENTED) called port=dlp:SRVR

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1311]
Tested on latest commit https://github.com/citra-https://github.com/citra-emu/citra/commit/82087672b7eba5a42e081c29b8e7b79cb4f77a25

* additional merged https://github.com/citra-emu/citra/pull/1302

**Aqua Moto Racing 3D**

[LOG](http://pastebin.com/tDp5MyEZ)

**Sonic & All-Stars Racing Transformed**

[LOG](http://pastebin.com/0Kh9Asmq)

**Comment by Subv** [comment]
Huh, interesting, a game that initializes Download Play on startup

**Comment by purpasmart96** [comment]
The stubbing of ports continues...

**Comment by exhalatio** [comment]
If implement dlp:SRVR service.
Sonic & All-Stars Racing Transformed is work.
Aqua Moto Racing 3D seems stuck on "CRO".

![sonic](https://cloud.githubusercontent.com/assets/7089513/14054628/fdf901fa-f31d-11e5-9402-31da44c55461.jpg)

**Comment by JohnGodgames** [comment]
Sonic & All-Stars Racing Transformed is ingame now and Aqua Moto Racing 3D got intro and stuck for some reason
