### ISSUE TITLE
Several games gets infinite loading

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1314]
Possible candidates?

```
[  12.342804] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::LoadComponent:91: (STUBBED) called size=0xBDCE, unk1=0x505300FF, unk2=0x000E00FF, new_size=0xBDCEA, buffer=0x005C4EC4
[  12.345862] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::RegisterInterruptEvents:157: Registered interrupt=2, channel=2, event_handle=0x000E802A
[  12.363851] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::GetSemaphoreEventHandle:106: (STUBBED) called
[  12.367454] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::SetSemaphoreMask:278: (STUBBED) called mask=0x00002000
[  12.371585] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::SetSemaphore:180: (STUBBED) called
[  12.374290] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::SetSemaphore:180: (STUBBED) called
```

Tested on latest commit https://github.com/citra-https://github.com/citra-emu/citra/commit/82087672b7eba5a42e081c29b8e7b79cb4f77a25
- additional merged https://github.com/citra-emu/citra/pull/1302
### Cars 2

![cars 2](https://cloud.githubusercontent.com/assets/11453507/12055947/49ae565c-af32-11e5-8e57-c57e827e2e4a.PNG)

LOG: http://pastebin.com/R6uKGjJQ
### Splinter Cell 3D

![splinter](https://cloud.githubusercontent.com/assets/11453507/13682723/5f12402c-e703-11e5-981f-d7f6dd3cb412.JPG)

[LOG](http://pastie.org/10755312)
### Nascar Unleashed

![nascar](https://cloud.githubusercontent.com/assets/11453507/13682763/8c168970-e703-11e5-94aa-93267dc491e5.JPG)

[LOG](http://pastie.org/10755316)

**Comment by JayFoxRox** [comment]
Do any of these work with the audio branch?

**Comment by JohnGodgames** [comment]
Nope...tried already

**Comment by Subv** [comment]
Could you please test these again? We've had many changes to the archive handling code.

**Comment by JohnGodgames** [comment]
Updated logs with https://github.com/citra-emu/citra/commit/cf5b8483fc53ca3b4919d231045348625a507d05

[Cars 2](http://pastebin.com/eTgTAct4)
[Splinter Cell 3D](http://pastebin.com/8LBS25SS)
[Nascar Unleashed](http://pastebin.com/Pfcca5gY)

**Comment by Subv** [comment]
Could you please re-test these on the latest master and update the logs?

**Comment by JohnGodgames** [comment]
Updated logs with https://github.com/citra-emu/citra-nightly/commit/b36677daff771d4791f3b13e0d7cb95f4b0b47f6

[Cars 2](http://pastie.org/10989346) 
[Splinter Cell 3D](http://pastie.org/10989348)
[Nascar Unleashed](http://pastie.org/10989347)

**Comment by danzel** [comment]
Still same issue, Splinter Cell 3D on HEAD-e1bb198
https://gist.github.com/danzel/659087d543323bec7d3715267e534af2

**Comment by benderscruffy** [comment]
using HEAD-c810a3f
Still same issue, Splinter Cell 3D
[log.zip](https://github.com/citra-emu/citra/files/1484193/log.zip)

**Comment by benderscruffy** [comment]
using nightly HEAD-b88ed52
cars 2 goes ingame
![cars 2](https://user-images.githubusercontent.com/2696404/33884703-b1ccfcc2-df7b-11e7-8f33-42ac5a63ffae.PNG)

Nascar Unleashed goes ingame
![nascar](https://user-images.githubusercontent.com/2696404/33884714-be612a76-df7b-11e7-9d66-af45907cbc36.PNG)

but Splinter Cell 3D still has the same issue

**Comment by Subv** [comment]
Could you create a separate issue for Splinter Cell 3D please?

**Comment by benderscruffy** [comment]
ok this can be closed then
