### ISSUE TITLE
Fifa 13 - Unknown virtual address @ 0x008C2554

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1319]
Tested on latest commit https://github.com/citra-https://github.com/citra-emu/citra/commit/82087672b7eba5a42e081c29b8e7b79cb4f77a25

* additional merged https://github.com/citra-emu/citra/pull/1302

This game is not showing anything too...

LOG: http://pastebin.com/51H6fe0s

**Comment by JamePeng** [comment]
@yuriks
This addr also belong to the heap Vaddr but can not run VirtualToPhysicalAddress , 
because there are no condition to process the Heap Type Addr!
HEAP_VADDR     = 0x08000000,     HEAP_SIZE      = 0x08000000,
maybe it should be point to linear-heap!

**Comment by yuriks** [comment]
@JamePeng Heap addresses can not be converted to physical addresses. The 3DS also doesn't support this.

**Comment by JamePeng** [comment]
@yuriks
 ? but MMU was supported in ARM11,right?

**Comment by mailwl** [comment]
@JohnGodgames , try https://github.com/citra-emu/citra/pull/1395 - i think this should help

**Comment by mailwl** [comment]
it's really strange. Main thread loop itself with LR=PC. There is something wrong

![fifa13](https://cloud.githubusercontent.com/assets/629437/14395610/5691da7c-fddb-11e5-88f7-988379bc6d93.png)

**Comment by MoochMcGee** [comment]
Sounds like a threading bug to me.

**Comment by mailwl** [comment]
no. it's arm interpreter error in opcode `BLX LR`
it changes LR to PC+4 at first, when set PC to LR (PC become PC+4, and equal LR).
need at first change PC, then LR.

now all 3 fifa games shows intro, but then stuck again

**Comment by lioncash** [comment]
@mailwl Your image only has BX in it, not BLX

**Comment by mailwl** [comment]
yes, `blx lr` right before this function, when i did screenshot, didn't know yet it matters.

**Comment by lioncash** [comment]
Fixed in #1653
