### ISSUE TITLE
Fractured Souls - Failed to accessing save game data

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1320]
Tested on latest commit https://github.com/citra-https://github.com/citra-emu/citra/commit/82087672b7eba5a42e081c29b8e7b79cb4f77a25
- additional merged https://github.com/citra-emu/citra/pull/1302

![fractures souls](https://cloud.githubusercontent.com/assets/11453507/12056659/11c60e2c-af39-11e5-96e8-8da3fdda597a.PNG)

LOG: http://pastie.org/10661690

**Comment by Subv** [comment]
Could you please test this again?

**Comment by JohnGodgames** [comment]
Tested on https://github.com/citra-emu/citra-nightly/commit/b36677daff771d4791f3b13e0d7cb95f4b0b47f6 and still persist

[LOG](http://pastie.org/10989343)

**Comment by benderscruffy** [comment]
still happens in the latest nightly and canary
![fracutred](https://user-images.githubusercontent.com/2696404/33226923-3c9dcaf4-d1d3-11e7-9161-941d0d19a156.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1502787/log.zip)

**Comment by benderscruffy** [comment]
nightly HEAD-a66e458
still happens
[Debug log.zip](https://github.com/citra-emu/citra/files/1605911/Debug.log.zip)

**Comment by benderscruffy** [comment]
still happens in the latest nightly
![souls](https://user-images.githubusercontent.com/2696404/50636401-e7ca1a80-0f90-11e9-9855-786886b83d8a.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2723601/citra_log.zip)

**Comment by Subv** [comment]
Is this still an issue? Could somebody please test with #5213?

**Comment by Dragios** [comment]
For now the workaround to bypass this is to manually create an empty save file named `TSG_FS3DS.file` at
```
C:\Users\[Your user name here]\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/000b0300/data/00000001/
```
Make sure your settings has show file name extension enabled before you rename else it will not work.
