### ISSUE TITLE
Green Lantern: Rise of the Manhunters - loading loop

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1321]
Tested on latest commit https://github.com/citra-https://github.com/citra-emu/citra/commit/82087672b7eba5a42e081c29b8e7b79cb4f77a25

* additional merged https://github.com/citra-emu/citra/pull/1302

![green lantern](https://cloud.githubusercontent.com/assets/11453507/12057209/ce8d3620-af3e-11e5-9516-95a009904a38.PNG)

LOG: http://pastie.org/10662761

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1374

**Comment by Subv** [comment]
Was this fixed by the Source Processing PR?

**Comment by JohnGodgames** [comment]
Not sure, but it works on that master
