### ISSUE TITLE
Happy Feet Two - hangs at language selection screen (regression due to #642 touchpad support bug)

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1323]
Tested on latest commit https://github.com/citra-https://github.com/citra-emu/citra/commit/82087672b7eba5a42e081c29b8e7b79cb4f77a25

* additional merged https://github.com/citra-emu/citra/pull/1302

#### reference video:
https://www.youtube.com/watch?v=LvLeZa__wlo

![happy feet two](https://cloud.githubusercontent.com/assets/11453507/12059708/a3dfd94c-af60-11e5-8dad-1958bbcb76b0.PNG)

LOG: http://pastie.org/10662056

**Comment by Subv** [comment]
If this is a regression, please post the revision where it worked

**Comment by JohnGodgames** [comment]
Ohh last working commit https://github.com/citra-emu/citra/commit/b56829df020a81248dd04688ff2b307f3444a09f

Stopped working after https://github.com/citra-emu/citra/pull/642

**Comment by JohnGodgames** [comment]
![happy 1](https://cloud.githubusercontent.com/assets/11453507/13710185/23931958-e7b8-11e5-975c-c41498736228.JPG)
![happy 2](https://cloud.githubusercontent.com/assets/11453507/13710187/262e15dc-e7b8-11e5-87de-86edd2204709.JPG)

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1510
