### ISSUE TITLE
Hello Kitty to Issho! Block Crash Z - GSPSharedMem: already mapped at 0x10000000!

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1324]
Tested on latest commit https://github.com/citra-https://github.com/citra-emu/citra/commit/82087672b7eba5a42e081c29b8e7b79cb4f77a25

* additional merged https://github.com/citra-emu/citra/pull/1302

LOG: http://pastie.org/10662697

**Comment by Subv** [comment]
Try out #1327

**Comment by JohnGodgames** [comment]
Yeah https://github.com/citra-emu/citra/pull/1327 helped to get past to title screen.
