### ISSUE TITLE
Nascar Unleashed - Loading / save screen looping

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1325]
Tested on latest commit https://github.com/citra-https://github.com/citra-emu/citra/commit/82087672b7eba5a42e081c29b8e7b79cb4f77a25
- additional merged https://github.com/citra-emu/citra/pull/1302

![nascar unl](https://cloud.githubusercontent.com/assets/11453507/12064266/4ad3721e-afbf-11e5-8c0f-291fcb9f5483.PNG)

LOG: http://pastie.org/10662752

**Comment by JohnGodgames** [comment]
Maybe related to https://github.com/citra-emu/citra/issues/1314

**Comment by Subv** [comment]
Could you please test this again? We've had some pretty big changes to the archive code.

**Comment by JohnGodgames** [comment]
It's already in https://github.com/citra-emu/citra/issues/1314
