### ISSUE TITLE
How to train your dragon 2 - shows only solid colors and not textures

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1329]
I hope that it's useful...

![httyd2](https://cloud.githubusercontent.com/assets/11453507/12070825/71b98428-b08b-11e5-974b-4bfd35368b18.PNG)

![httyd2 apitrace 1](https://cloud.githubusercontent.com/assets/11453507/12070826/7aa3731e-b08b-11e5-8d22-129f7f344c17.PNG)

![httyd2 apitrace 2](https://cloud.githubusercontent.com/assets/11453507/12070827/80791294-b08b-11e5-8333-f25e8c5de0a5.PNG)

Video from ingame:
https://www.youtube.com/watch?v=-g0NXjZ1IkQ

LOG http://pastie.org/10663810
[APITRACE SAMPLE](https://mega.nz/#!yB1jiSbJ!uF_RBDVTpbl-E_zYoYtczArCYI4rKyxgEDVKYTS-2zw)

**Comment by Subv** [comment]
It could be using geometry shaders to draw

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1508

![httyd2 1](https://cloud.githubusercontent.com/assets/11453507/13726627/5508ee6c-e8d1-11e5-97e8-1dc3b74032cb.JPG)
