### ISSUE TITLE
Pokemon Y issue

### ISSUE THREAD

**Issue by Armonite** [citra-emu/citra#1331]
Hey today i just loaded the Pokemon Y rom into Citra and it was a decrypted one.
It didn't boot up, this is what happened.
![imp](https://cloud.githubusercontent.com/assets/12455548/12077378/4dd010a0-b206-11e5-881b-684f68046a37.png)

**Comment by shinyquagsire23** [comment]
@Subv has changes which have not been merged yet, so Pokemon Y will still not run from any buildbot-built builds.

**Comment by Armonite** [comment]
Okay thank you very much, I thought Pokemon X was working and so would Pokemon Y

**Comment by Armonite** [comment]
So any idea when will we have the new release in which Pokemon Y would run?

**Comment by shinyquagsire23** [comment]
Just watch for CRO support to get merged in, I don't think there's an ETA for that but it'll probably be within the month, hopefully.
