### ISSUE TITLE
"The ROM is probably encrypted"

### ISSUE THREAD

**Issue by izumi937** [citra-emu/citra#1332]
Hello, I tested Citra with The Legend of Zelda Ocarina of time 3D and Fire Emblem: Awakening. 
And I got the following line in red colour: 

[  18.220264] Loader <Error> core\loader\ncch.cpp:Loader::AppLoader_NCCH::Load:269: ExHeader Program ID mismatch: the ROM is probably encrypted.

And the last line in purple colour: 

[  18.222324] Frontend <Critical> citra_qt\main.cpp:GMainWindow::BootGame:261: Failed to load ROM!

**Comment by mailwl** [comment]
i think, we need the wiki article about decrypting roms

**Comment by Subv** [comment]
https://github.com/citra-emu/citra/wiki/Dumping-Game-Cartridges
