### ISSUE TITLE
Please verify before exiting

### ISSUE THREAD

**Issue by PFCKrutonium** [citra-emu/citra#1335]
I accidentally quit mid fight with Queen Gohma...

**Comment by mailwl** [comment]
WTF?

**Comment by PFCKrutonium** [comment]
Sorry, I should explain more - the emulator should verify you want to close it before it closes while a game is running. If it does already, then I somehow skipped it.

**Comment by mailwl** [comment]
ah, i see "ask before exit"

**Comment by PFCKrutonium** [comment]
Yah, gotta love it when you accidentally do a key combo at the speed of light that kills the game...

**Comment by LittleWhite-tb** [comment]
This is now implemented, and I guess, this issue should be closed.

**Comment by yuriks** [comment]
Fixed by #1352

**Comment by PFCKrutonium** [comment]
Thanks!
