### ISSUE TITLE
Citra not loading decrypted roms and even homebrew :/

### ISSUE THREAD

**Issue by rupansh** [citra-emu/citra#1337]
Hello guys i downloaded citra and installed a 64bit os on ma pc but whenever i try to load a rom on citra a popup comes up saying citra has stopped working. I first tried decrypted Pokemon neo Y and then i tried 3ds craft (homebrew) but it didnt load and stopped working. The screenshot has been attached :) pls help me.
![untitled](https://cloud.githubusercontent.com/assets/3929608/12096796/e252dd56-b33d-11e5-8f53-3a268ce68751.png)

**Comment by Subv** [comment]
Update your graphic drivers.
