### ISSUE TITLE
Allow increasing internal resolution with OpenGL Renderer

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#1338]
any possible support for a high level of anti aliasing?

**Comment by mailwl** [comment]
i think, before dynarec implemented no need antialiasing

**Comment by RHY3756547** [comment]
If this is really bugging you, for now you could always enable FXAA in your GPU settings, though at a resolution this low a ton of graphical artifacts can appear. (and it doesn't work when you scale up the window..)

![image](https://cloud.githubusercontent.com/assets/6294155/12108031/6039c3f2-b36a-11e5-9ea5-b73a5454d9ce.png)
![image](https://cloud.githubusercontent.com/assets/6294155/12108062/ca628de0-b36a-11e5-9e59-9b1cf9e029b1.png)

**Comment by Zetchzie** [comment]
need an internal res upscale.

**Comment by Zaneo** [comment]
Should this be marked as with, graphics, enhancement tag, or just closed?

**Comment by tfarley** [comment]
Note: a version of this is included in #1436.

**Comment by lioncash** [comment]
`[23:33] <tfarley> can someone close #1533 and #1338? both should have been officially solved by merging texfwd`
