### ISSUE TITLE
Doesn't run any rom

### ISSUE THREAD

**Issue by Juanillo62gm** [citra-emu/citra#1340]
I'm using Mac OS X El Capitan, I tried to run several roms and citra don't do anything

**Comment by RavenHome1** [comment]
please post a log so one can help you with the issue. also your issue will most likely be from one of these issues

1- your gpu does not support openGL 3.3
2-you graphic driver needs to be updated
3- your roms are encrypted 
4- you are trying to launch titles that uses CRO, which is not yet implemented in citra

**Comment by Subv** [comment]
This is not a valid bug report.
