### ISSUE TITLE
The Denpa Men: They Came by Wave freezes when Initiating Unimplemented Camera Functionality

### ISSUE THREAD

**Issue by Vectrex33** [citra-emu/citra#1341]
http://pastebin.com/fHGxAudm <- Log

Seems that this game asks to do even more calls then are stubbed so far. (At least, from what I understand from the Log)

**Comment by Subv** [comment]
It crashes due to unimplemented camera functionality.

**Comment by mailwl** [comment]
@Vectrex33, may you try my branch? https://github.com/mailwl/citra/tree/branch-cam
it's outdated, but works for one game (Heavy Fire).
 just to check, if panic disappear

**Comment by mailwl** [comment]
well, i tested it by myself. it's... kind of work (random data as camera picture, and it looks like the game want to move camera). Not playable

**Comment by Vectrex33** [comment]
As of eb43581, the game no longer crashes, and as such, even though the game still isn't playable (Game wants to move camera), it ain't freezing.
