### ISSUE TITLE
Kingdom Hearts 3D Camera Issues

### ISSUE THREAD

**Issue by seanos1998** [citra-emu/citra#1343]
The game is running smoothly, the models are intact (as seen in the first image) and the framerate is pretty good. Only issue is: the camera seems to be placed in the wrong place for some reason and clips through different models, such as the raft in the opening cutscenes and sora while doing the first dive mission.

EDIT. After some testing this appears to happen when the shader JIT is enabled. Without the shader JIT the camera seems to be fine.

![schermafdruk 2016-01-06 22 10 52](https://cloud.githubusercontent.com/assets/16582810/12154968/ef624ec4-b4c2-11e5-86b9-17427d620fb3.png)
![schermafdruk 2016-01-06 22 08 32](https://cloud.githubusercontent.com/assets/16582810/12154969/ef641c86-b4c2-11e5-8c0c-f2cffed9cf0b.png)
![schermafdruk 2016-01-06 22 10 32](https://cloud.githubusercontent.com/assets/16582810/12154971/ef68b25a-b4c2-11e5-884c-55823c5a097f.png)
![schermafdruk 2016-01-06 22 10 35](https://cloud.githubusercontent.com/assets/16582810/12154970/ef673a10-b4c2-11e5-9141-3bf996743ac2.png)

**Comment by yuriks** [comment]
Does this still happen in master? #1367 may have fixed it.

**Comment by JayFoxRox** [comment]
Check if #1546 fixes this

**Comment by JayFoxRox** [comment]
Confirmed fixed by pcmaker (with youtube-video evidence)
