### ISSUE TITLE
Rune Factory 4 JPN - Text bubble behind character image

### ISSUE THREAD

**Issue by JanetMerai** [citra-emu/citra#1345]
![rune factory 4 text issues 2](https://cloud.githubusercontent.com/assets/4703831/12190575/2cbedcc8-b587-11e5-9e4f-86b8925a6746.png)
On this one, the text bubble without the character image is properly rendered.

![rune factory 4 text issues](https://cloud.githubusercontent.com/assets/4703831/12190576/2cd63bde-b587-11e5-84e0-6c2776a5aa03.png)
The text bubble is drawn behind the character, on the actual game the bubble appears in-front of the character and the text is on the front too.

This should be obvious and I took screenshots with the information to the side as well.
Sorry, I am not a programmer and thought this might help :3

Citra build 0144b8e was used for this.

**Comment by yuriks** [comment]
Please test with #1334

**Comment by JanetMerai** [comment]
I use this URL to get builds
https://builds.citra-emu.org/citra/nightly/windows-amd64/?C=M&O=D

1334 is not listed in the builds so I cannot test it.

**Comment by gilatino** [comment]
@JanetMerai Here is a build of #1334
[Citra.zip](https://github.com/citra-emu/citra/files/82482/Citra.zip)

**Comment by JanetMerai** [comment]
@gilatino All I get are missing .dll errors.
I downloaded the necessary .dll files and I still get missing .dll alerts.
As a test, I used a copy of 0144b8e and replaced the exe with your zip file and I got the same errors.

I've never had this issue with Citra before and I couldn't open Citra with your Zip file.
Was there a problem with your build?

**Comment by gilatino** [comment]
@JanetMerai Sorry I built the build as a Debug not Release. Here is the Release build:
[Release.zip](https://github.com/citra-emu/citra/files/82670/Release.zip)

**Comment by JanetMerai** [comment]
![rf4 text works](https://cloud.githubusercontent.com/assets/4703831/12198551/4b0652e6-b5ce-11e5-83c2-515c333fb871.png)

It works, thank you @gilatino :3

**Comment by yuriks** [comment]
#1334 has been merged
