### ISSUE TITLE
Region Switching in the Interface

### ISSUE THREAD

**Issue by JanetMerai** [citra-emu/citra#1347]
For a long time, I have been editing the config file to change the region code when I get a new Citra build.

Would it be possible to change the region within the interface easily?

Typically, I have to edit the text file and close Citra when I make a change.

**Comment by LittleWhite-tb** [comment]
Nice request :+1: 

For latter usage, some info on region stuff : http://3dbrew.org/wiki/Nandrw/sys/SecureInfo_A

**Comment by yuriks** [comment]
You can just keep your configuration files when you get a new build, you only need to replace the .exe file. Either way, this should probably go into some sort of configuration dialog instead of just being thrown in the menu.

**Comment by JanetMerai** [comment]
Thank you @yuriks :3
Still, it would be awesome to just switch it anyway.

**Comment by purpasmart96** [comment]
lol yeah that was my crappy region value changing implementation by me, I didn't even make them string values.

**Comment by mailwl** [comment]
already implemented?

**Comment by LittleWhite-tb** [comment]
Yes :)
