### ISSUE TITLE
Citra-qt has stopped working

### ISSUE THREAD

**Issue by RipDeamon** [citra-emu/citra#1348]
Hi, i need help, every time i load a 3ds game like for a example Rune factory 4 on Citra i get Citra-qt has stopped working here's  a snapshot of my Problem. 

https://cloud.githubusercontent.com/assets/16543346/12196906/a7d9895a-b602-11e5-98e7-5e84cb205f60.JPG

I hope you can help me fix this Problem.
Thanks in advance.

**Comment by neobrain** [comment]
This is not a support forum.

**Comment by RipDeamon** [comment]
Then can you suggest any support forum that can help me
