### ISSUE TITLE
Citra runs, but it's slow

### ISSUE THREAD

**Issue by SalamanderNatsu** [citra-emu/citra#1349]
Ok, so I've turned off HW renderer and this time it actually didn't crash, but it started. I have OGL version 3.1 so whenever, I turn HW rendering on Citra crashes on me. Can I speed up the emulation without HW rendering? Please don't comment something like: "Get a new graphics card" or "Get a new laptop." Intel doesn't support OGL 3.3. so my drivers are as high as they can be.

**Comment by MoochMcGee** [comment]
Well, tough shit. If you want to use HW rendering, you need to get
something newer.

**Comment by neobrain** [comment]
Please don't abuse the issue tracker for help requests.

**Comment by JMC47** [comment]
Emulators aren't developed so individual people can play games full speed.  Emulators have the job of emulating the system; and if you want to use a Hardware Renderer, you need an OpenGL version (currently) capable of emulating the 3DS.  I'm guessing the devs chose OGL 3.3 for a reason.

I wouldn't doubt that there will be optimizations in the future, but, I think it would be best if you were patient and thought of the emulator as a project for preservation.  I wouldn't think of Citra as something that'd run nearly as well as a 3DS for a couple years anyway.  By then you may have a new computer anyway!

**Comment by SalamanderNatsu** [comment]
Thank you and sry for bugging you
