### ISSUE TITLE
Software renderer relies on OpenGL 3.3

### ISSUE THREAD

**Issue by LittleWhite-tb** [citra-emu/citra#1350]
Hello,

While going through the code, I have noticed that it is not possible to use the software renderer without having OpenGL 3.3.

It is natural to think that the software renderer relies only on software, so we (I include myself on this one) have to think a way to render the buffer without OpenGL 3.3.

**Comment by yuriks** [comment]
It should be possible to do this by simply painting the surface using Qt, but there are several issues regarding making OpenGL mode also work (without slowing it down) at the same time. I expect this to require large refactors of the rendering frontend and UI code.

**Comment by benderscruffy** [comment]
can be closed

**Comment by benderscruffy** [comment]
Is this still an issue?.

**Comment by SleepingSnakezzz** [comment]
Fixed in https://github.com/citra-emu/citra/pull/6347
