### ISSUE TITLE
citra crash when i run a game

### ISSUE THREAD

**Issue by rubensaiz2003** [citra-emu/citra#1351]
Crash when I run a game:
(Im spanish, my english are bad and my Windows are in spanish)
Firma con problemas:
Nombre del evento de problema: APPCRASH
Nombre de la aplicación: citra-qt.exe
Versión de la aplicación: 0.0.0.0
Marca de tiempo de la aplicación: 566ddbf6
Nombre del módulo con errores: ig4icd64.dll
Versión del módulo con errores: 8.15.10.1892
Marca de tiempo del módulo con errores: 4a9ebb4b
Código de excepción: c0000005
Desplazamiento de excepción: 000000000003ee1f
Versión del sistema operativo: 6.1.7601.2.1.0.768.3
Id. de configuración regional: 3082
Información adicional 1: 1d4e
Información adicional 2: 1d4e37e611e2ed11c9bd1d26efb809b8
Información adicional 3: 517c
Información adicional 4: 517cf451771344ebce716eb9d12193d1
I think the problem is Intel Graphics Accelerator Drivers for Windows 7(R)

Acer TravelMate 5330
Windows 7 Home Premium x64
Intel® GMA 4500M
Intel Celeron
3GB ram

Video
I cant upload file to Github, sorry: http://www.mediafire.com/watch/2pz1m1838pqd88i/Citra_crash.wmv

**Comment by Subv** [comment]
Your GPU does not support OpenGL 3.3, there is nothing we can do to help you.
