### ISSUE TITLE
Can't get build instructions working for Windows.

### ISSUE THREAD

**Issue by WinterMute** [citra-emu/citra#1353]
Not sure what's going on with this

Output from Cmake is :-

The C compiler identification is unknown
The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:36 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:36 (project):
  No CMAKE_CXX_COMPILER could be found.

Configuring incomplete, errors occurred!
See also "C:/Users/davem_000/projects/3ds/citra/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/davem_000/projects/3ds/citra/build/CMakeFiles/CMakeError.log".

[CMakeError.log.txt](https://github.com/citra-emu/citra/files/84162/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/citra-emu/citra/files/84163/CMakeOutput.log.txt)

**Comment by wwylele** [comment]
`cannot open input file 'kernel32.lib'`
The Windows SDK seems to be missed or damaged.
Have you successfully built a simple windows program on this computer?

**Comment by WinterMute** [comment]
I've successfully built many windows programs on this computer. VS 2015 works fine from the IDE.

**Comment by WinterMute** [comment]
OK. This appears to be an issue with Windows 10 & Cmake 3.4.1. See https://cmake.org/Bug/view.php?id=15831

I uninstalled 3.4.1 and installed 3.3.2 which works and I can build citra now

**Comment by MerryMage** [comment]
For the record the issue is fixed in cmake 3.5.

**Comment by Subv** [comment]
This is a CMake bug, not a Citra bug.

**Comment by yuriks** [comment]
It still affects us though. I think someone should at least add a note on the build instructions about how to fix/workaround it.

**Comment by Subv** [comment]
Do we have a "Requirements" page anywhere? I feel that would be the best way to place this information

**Comment by WinterMute** [comment]
https://github.com/citra-emu/citra/wiki/Common-Issues might be a good place
