### ISSUE TITLE
add full screen mode

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#1354]
please add a full screen mode which will help with variable refresh rate monitors

**Comment by linkmauve** [comment]
3DS games don’t support variable refresh rate.

Also duplicate of #139.

**Comment by RavenHome1** [comment]
no game supports any variable refresh rate technology. this technology only relies on communication between the GPU and the monitor itself,  i don't see why it would not work with citra.

**Comment by yuriks** [comment]
You could set the monitor video mode to whatever you want, but you would still need to display on 30/60 frames per second. It would only lead to stuttering.
