### ISSUE TITLE
Error or unavailability?

### ISSUE THREAD

**Issue by Prussico** [citra-emu/citra#1355]
I'm a Mario RPG's Games fan, and i tried to emulate some games of the gender but they never work. So i don't know if the program is yet not ready for emulating those games or i'm doing something wrong.
I mean because the game didn't even start, no black screen or crashed game, it doesn't even start, it says it might be encrypted but i don't know what that is.
Can somebody help me please?
![citra](https://cloud.githubusercontent.com/assets/16672174/12273097/1567a786-b94b-11e5-8e15-284b98dabe02.jpg)
this is a print screen of the error

**Comment by mailwl** [comment]
ROM is crypted, you need 3DS to decrypt it first
