### ISSUE TITLE
ROM breaking execution

### ISSUE THREAD

**Issue by Naerius** [citra-emu/citra#1356]
Hello there!

While trying to run a ROM I got the following error:

Service.GSP < Warning > core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
Debug.Emulated < Critical > core\hle\svc.cpp:SVC::Break 389: Emulated program broke execution!
Debug.Emulated < Critical > core\hle\svc.cpp:SVC::Break 397: Break reason: PANIC

Hope it helps!
Greetings.

**Comment by archshift** [comment]
Sorry, but this is incredibly unhelpful. Which game is it? What were you doing in the game? Are you using the latest build of Citra? Were you using the shader JIT or not? How exactly can we reproduce this?

**Comment by neobrain** [comment]
^ missing too much info. Please look around common guides (-> web search) and learn about reporting issues properly before using our issue tracker again, thanks.

**Comment by JustJean101** [comment]
ive got this issue on pokemon x eur decrypted
