### ISSUE TITLE
I can't open citra-qt.exe, "stop working"

### ISSUE THREAD

**Issue by Sedhaild** [citra-emu/citra#1357]
One night, I was testing how KH3D runs in the emulator, then I closed it, and now I just can't open citra-qt.exe.
When the emulator worked fine, I didn't change anything in my pc, the next morning I try to open it, I got the error.
I always get the "Stop working" error, doesn't matter if I download another version or where I put the emulator in my pc.
I open the emulator as admin, or changing the compatibility to w7, w8, etc, nothing works.
The cmd shows this:
http://fotos.subefotos.com/6bf4db0d5aee30e42d8da1a8fe693e49o.jpg

My specs:
Windows 10 64 bits.
i5 6400 Base 2.7GHz, Turbo 3.3 GHz 
16GB DDR4 2400MHz Vengeance LPX 
GeForce GTX 750Ti 2Gb GDDR5

**Comment by neobrain** [comment]
This is not a good issue report. Please understand that we have to aggressively filter out issues that do not meet minimal standards to make sure the issue tracker remains useful in the long run. If you want future issue reports to be accepted, I suggest looking around common guides (-> web search) and learning about reporting issues properly before using our issue tracker again.

Thank you.

**Comment by essaic** [comment]
Try removing the file mentioned in the error ?

**Comment by Sedhaild** [comment]
Now the cmd shows nothing, but the "stop working" still.
