### ISSUE TITLE
dsp

### ISSUE THREAD

**Issue by woody2014** [citra-emu/citra#1358]
Please can someone code dsp service to use dspfirm.cdc.

**Comment by neobrain** [comment]
This is not a good issue report. Please understand that we have to aggressively filter out issues that do not meet minimal standards to make sure the issue tracker remains useful in the long run. If you want future issue reports to be accepted, I suggest looking around common guides (-> web search) and learning about reporting issues properly before using our issue tracker again.

Thank you.
