### ISSUE TITLE
crash with .3ds files and other question

### ISSUE THREAD

**Issue by Diablon** [citra-emu/citra#1359]
First time using the emulator
but when i try to use a .3ds file i get a message "citra-qt.exe stopped working"
what i need to get it work??

And where i can configure the controls

(I used Windows 8)

Sorry for the noob question

**Comment by Diablon** [comment]
I tried to play animal crossing: new leaf

**Comment by yuriks** [comment]
Please see the (newly updated) [CONTRIBUTING.md](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) file.
