### ISSUE TITLE
Enable -Wall and -Wpedantic and fix all compiler warnings

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#136]
`-Wall` and `-Wpedantic` are gcc compiler options that specify the amount of warnings to spam during compilation. I think it's beneficial for code quality to catch as many warnings as possible (warnings which turn out to be useless can be disabled explicitly later on).

Additionally, we should make an effort to get the build warning-free. This allows us to enable `-Werror` (warnings are treated as errors) on the travis build bot, so that new code is guaranteed not to introduce new warnings to the code base.

**Comment by GPUCode** [comment]
Impmented in https://github.com/citra-emu/citra/pull/6456 and https://github.com/citra-emu/citra/pull/6602 for msvc and https://github.com/citra-emu/citra/pull/6602 for gcc/clang
