### ISSUE TITLE
Failed to load rom error: Super mario 3d land

### ISSUE THREAD

**Issue by Ninja4562** [citra-emu/citra#1362]
if i try to open citra.exe, it will come up with a cmd for less than half a second, to fast for me to read, then it closes. if i open citra-qt.exe i get 3 errors (the first 9 lines of the text), but it actually opens the emulator. if i load my rom (super mario 3d land) i get this error in the cmd, and the emulator doesnt do anything. 
[citra error.txt](https://github.com/citra-emu/citra/files/95543/citra.error.txt)
FYI: i know that this program isnt stable and is likely to not work, thats why im uploading this error, i hope someone can fix this and make citra better.

**Comment by jroweboy** [comment]
You didn't read the contributing guidelines very well before creating this report :( These are the exact kind of reports that don't help at all. The output of the error says that your rom is still encrypted. Please do not create reports for things that are not real issues. If you aren't sure if you found a real issue or not, then its not a real issue :) Check the wiki for instructions on how to decrypt a rom, and if you can't follow those instructions, then citra isn't for you yet.
