### ISSUE TITLE
Pokemon X Not Loading Error when trying to boot

### ISSUE THREAD

**Issue by RainbowHawk** [citra-emu/citra#1364]
[   0.000001] Config <Info> citra\config.cpp:Config::LoadINI:39: Successfully loaded C:\Users\live2\Desktop\Files\Citra/user/config/glfw-config.ini
[   0.096918] Service.FS <Info> core\file_sys\archive_sdmc.cpp:FileSys::ArchiveFactory_SDMC::ArchiveFactory_SDMC:21: Directory C:\Users\live2\Desktop\Files\Citra/user/sdmc/ set as SDMC.
[   0.100996] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:198: path exists C:\Users\live2\Desktop\Files\Citra/user/sdmc/
[   0.101788] Service.FS <Info> core\file_sys\archive_savedata.cpp:FileSys::ArchiveFactory_SaveData::ArchiveFactory_SaveData:36: Directory C:\Users\live2\Desktop\Files\Citra/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
[   0.102584] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:62: Directory C:\Users\live2\Desktop\Files\Citra/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[   0.103702] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:198: path exists C:\Users\live2\Desktop\Files\Citra/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
[   0.104285] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:62: Directory C:\Users\live2\Desktop\Files\Citra/user/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[   0.105097] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:198: path exists C:\Users\live2\Desktop\Files\Citra/user/nand/data/00000000000000000000000000000000/extdata/
[   0.106019] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Init:411: Unable to load shared font: C:\Users\live2\Desktop\Files\Citra/user/sysdata/shared_font.bin
[   0.107649] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:464: GL_VERSION: 3.3.0 - Build 10.18.10.4252
[   0.108047] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:465: GL_VENDOR: Intel
[   0.108380] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:466: GL_RENDERER: Intel(R) HD Graphics
[   0.119716] Loader <Info> core\loader\loader.cpp:Loader::LoadFile:113: Loading file C:\Users\live2\Desktop\Files\Citra\Pokemon X por Inmortalgames.3ds as NCSD...
[   0.120262] Loader <Warning> core\loader\ncch.cpp:Loader::AppLoader_NCCH::Load:234: Only loading the first (bootable) NCCH within the NCSD file!
[   0.121865] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::Load:258: Name:                         kujira-1
[   0.221569] Loader <Info> core\hle\kernel\process.cpp:Kernel::Process::ParseKernelCaps:99: ExHeader kernel version: 2.35
[   0.313168] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GetLockHandle:118: (STUBBED) called handle=0x00038009 applet_attributes=0x00000000
[   0.317955] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'OverrideDefaultDaemons': port=ndm:u, cmd_buff[1]=0xF
[   0.321231] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'SuspendDaemons': port=ndm:u, cmd_buff[1]=0x6
[   0.324452] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Enable:126: (STUBBED) called attributes=0x00000000
[   0.327630] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GlanceParameter:243: called app_id=0x00000300, buffer_size=0x00001000
[   0.330863] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::NotifyToWait:101: (STUBBED) app_id=768
[   0.332445] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::ReceiveParameter:220: called app_id=0x00000300, buffer_size=0x00001000
[   0.336375] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:305: (STUBBED) called command=0x00000007, buffer1_size=0x00000004, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF40, buffer2_addr=0x0FFFFF0C
[   0.339627] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:305: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF08, buffer2_addr=0x0FFFFF0C
[   0.348297] Service.FS <Warning> core\hle\service\fs\fs_user.cpp:Service::FS::InitializeWithSdkVersion:668: (STUBBED) called unk1=0x050200C8, unk2=0x00000020, unk3=0x0007001A
[   0.355666] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'Subscribe': port=srv:, cmd_buff[1]=0x209
[   0.368208] Kernel.SVC <Error> core\hle\service\apt\apt.cpp:Service::APT::GetSharedFont:93: called, but shared_font.bin has not been loaded!
[   0.371293] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[   0.372630] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[   0.374183] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[   0.375640] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[   0.377209] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[   0.378656] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[   0.435064] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
[   0.439456] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
[   0.442409] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[   0.443915] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[   0.445416] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[   0.447016] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[   0.450358] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
[   0.453605] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!

**Comment by yuriks** [comment]
https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md
