### ISSUE TITLE
 hardware renderer breaking the graphics

### ISSUE THREAD

**Issue by suelo50** [citra-emu/citra#1376]
hardware renderer breaking the graphics but software show normal my gpu  supports OpenGL 3.3 Why is this happening?

**Comment by neobrain** [comment]
Please don't use our issue tracker.

**Comment by LittleWhite-tb** [comment]
Or be more precise.
You can read the doc : https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md#reporting-issues to see what I mean.
