### ISSUE TITLE
unimplemented functions port=ndm:u

### ISSUE THREAD

**Issue by puntywalker** [citra-emu/citra#1378]
NDMU:ResumeDaemons
NDMU:GetSchedulerDisableCount

This likely causes Tomodachi Life to freeze after resetting the SD Card
 
Heres a log someone else had which is the same as mine:
http://pastebin.com/KW7DLsuL

**Comment by purpasmart96** [comment]
ResumeDaemons shouldn't be a problem, although GetSchedulerDisableCount I have seen much less so there could be something that could be done about that.

**Comment by JamePeng** [comment]
please check the #1650 , I am no sure the NDMU:GetSchedulerDisableCount whether work fine?

**Comment by Subv** [comment]
As of #1650 they are now stubbed and the log doesn't appear anymore.
