### ISSUE TITLE
Pokemon Omega Ruby Panic Loop

### ISSUE THREAD

**Issue by Ystro** [citra-emu/citra#1382]
Hello, 
I tried to use citra today for the first time and if i try to start Pokemon Omega Ruby Citra will stay in a loop and i only see two blackscreens :/ 

Does somebody has an idea how to fix that?
Sorry for my bad english and thank you in advance

Ystro

log-File:

`[   0.000000] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:198: path exists D:\citra-latest-windows-amd64/user/config/qt-config.ini
[   0.146376] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:198: path exists D:\citra-latest-windows-amd64/user/config/qt-config.ini
[   0.206614] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:198: path exists D:\citra-latest-windows-amd64/user/config/qt-config.ini
[  11.737624] Frontend <Info> citra_qt\main.cpp:GMainWindow::BootGame:250: Citra starting...
[  11.741331] Service.FS <Info> core\file_sys\archive_sdmc.cpp:FileSys::ArchiveFactory_SDMC::ArchiveFactory_SDMC:21: Directory D:\citra-latest-windows-amd64/user/sdmc/ set as SDMC.
[  11.741457] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:198: path exists D:\citra-latest-windows-amd64/user/sdmc/
[  11.741472] Service.FS <Info> core\file_sys\archive_savedata.cpp:FileSys::ArchiveFactory_SaveData::ArchiveFactory_SaveData:36: Directory D:\citra-latest-windows-amd64/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
[  11.741482] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:62: Directory D:\citra-latest-windows-amd64/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  11.741528] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:198: path exists D:\citra-latest-windows-amd64/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
[  11.741539] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:62: Directory D:\citra-latest-windows-amd64/user/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  11.741578] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:198: path exists D:\citra-latest-windows-amd64/user/nand/data/00000000000000000000000000000000/extdata/
[  11.741742] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Init:411: Unable to load shared font: D:\citra-latest-windows-amd64/user/sysdata/shared_font.bin
[  11.744332] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:464: GL_VERSION: 3.3.0 NVIDIA 361.43
[  11.744362] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:465: GL_VENDOR: NVIDIA Corporation
[  11.744389] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:466: GL_RENDERER: GeForce GTX 770/PCIe/SSE2
[  11.754046] Loader <Info> core\loader\loader.cpp:Loader::LoadFile:113: Loading file D:/Roms/Pokemon Omega Ruby por Inmortalgames.3ds as NCSD...
[  11.754064] Loader <Warning> core\loader\ncch.cpp:Loader::AppLoader_NCCH::Load:234: Only loading the first (bootable) NCCH within the NCSD file!
[  11.754079] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::Load:258: Name:                         sango-1
[  11.781200] Loader <Info> core\hle\kernel\process.cpp:Kernel::Process::ParseKernelCaps:99: ExHeader kernel version: 2.39
[  11.845794] HW.Memory <Error> core\memory.cpp:Memory::GetPointer:148: unknown GetPointer @ 0xfffffffc
[  11.895550] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GetLockHandle:118: (STUBBED) called handle=0x00038009 applet_attributes=0x00000000
[  11.895889] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'WriteInputToNsState?': port=APT:A, cmd_buff[1]=0x0
[  11.895994] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'OverrideDefaultDaemons': port=ndm:u, cmd_buff[1]=0xF
[  11.896015] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'SuspendDaemons': port=ndm:u, cmd_buff[1]=0x6
[  11.896260] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Enable:126: (STUBBED) called attributes=0x00000000
[  11.896406] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GlanceParameter:243: called app_id=0x00000300, buffer_size=0x00001000
[  11.896530] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::NotifyToWait:101: (STUBBED) app_id=768
[  11.896646] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::ReceiveParameter:220: called app_id=0x00000300, buffer_size=0x00001000
[  11.896802] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:305: (STUBBED) called command=0x00000007, buffer1_size=0x00000004, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF40, buffer2_addr=0x0FFFFF0C
[  11.896846] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:305: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF08, buffer2_addr=0x0FFFFF0C
[  11.899136] Service.FS <Warning> core\hle\service\fs\fs_user.cpp:Service::FS::InitializeWithSdkVersion:668: (STUBBED) called unk1=0x070101C8, unk2=0x00000020, unk3=0x0007001B
[  11.901006] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'Subscribe': port=srv:, cmd_buff[1]=0x209
[  11.905255] Kernel.SVC <Error> core\hle\service\apt\apt.cpp:Service::APT::GetSharedFont:93: called, but shared_font.bin has not been loaded!
[  11.905295] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[  11.905302] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[  11.905316] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[  11.905321] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[  11.905342] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[  11.905348] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[  11.907223] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
[  11.907238] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
[  11.907257] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[  11.907264] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[  11.907274] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[  11.907279] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[  11.907865] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:446: API OTHER 131185: Buffer detailed info: Buffer object 1 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
[  11.943421] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
[  11.943445] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
[  11.943481] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[  11.943490] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
[  11.944520] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
[  11.944533] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
[  11.944549] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[  11.944620] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC`

**Comment by RavenHome1** [comment]
pokemon uses CROs which are yet to be implemented in citra 'official" nightly builds, please read the contribution guide before posting an issue as the team is not looking for these sort of issues https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by sachit12123** [comment]
I am encountering the same problem . Is there anyway to fix it .please
