### ISSUE TITLE
Citra crashes when Hardware renderer is on

### ISSUE THREAD

**Issue by SuikaIbuki** [citra-emu/citra#1384]
Anytime i try to open a game with hardware renderer on citra shows [this](http://i.imgur.com/5ekiMrL.png) and crashes, the game i'm trying to run is Kirby Triple Deluxe which i've seen a few people playing, without the hardware renderer on citra doesn't crashes but doesn't display anything either.
Computer info: [1](http://i.imgur.com/HWgmRdG.png)/[2](http://i.imgur.com/U7M6Wxk.png).

**Comment by RavenHome1** [comment]
https://github.com/citra-emu/citra/wiki/FAQ

**Comment by dogtopus** [comment]
Try to update your GPU driver

**Comment by Subv** [comment]
Please read the FAQ
