### ISSUE TITLE
Mii Maker - lambda: Assertion Failed!

### ISSUE THREAD

**Issue by puntywalker** [citra-emu/citra#1393]
iirc, this used to be playable.
Crashes citra with the last error being:
SVC::CreateThread::lambda_3758cb5c4f75f5f350d285b6986e0bdf::operator ():481: Assertion Failed!

Full log:
http://pastebin.com/L0pgbVDF

**Comment by wwylele** [comment]
Citra run mii maker well here. maybe it needs more test to ensure it's not because of different mii make version.

**Comment by JasonSome** [comment]
Is this issue still present?

**Comment by mailwl** [comment]
@wwylele, may you describe, how to get mii maker from 3ds?

**Comment by wwylele** [comment]
@mailwl this should be discussed on IRC or the forum

**Comment by archshift** [comment]
I don't experience this issue with Mii Maker (anymore?). @puntywalker, can you confirm this is fixed?

**Comment by mailwl** [comment]
@wwylele, done

**Comment by JayFoxRox** [comment]
I'll close this due to inactivity. I've seen reports of this working.
If the problem still exists reopen this issue please and remove this post.
