### ISSUE TITLE
f1d1049 test:Time Traver

### ISSUE THREAD

**Issue by JamePeng** [citra-emu/citra#1396]
Nice work ! bunnei ! @bunnei 
2016.2.6:
Today I pull the newest version code to local and i build it!
Then I test the "time traver"  with the f1d1049 , I found that the texture had some changed.

**test by 7497675**
[7497675_log.txt](https://github.com/citra-emu/citra/files/120208/7497675_log.txt)

![qq 20160206171630](https://cloud.githubusercontent.com/assets/17095606/12865961/08de6b56-ccf8-11e5-99fc-e4547320eb66.png)
![qq 20160206171717](https://cloud.githubusercontent.com/assets/17095606/12865962/0e23bf80-ccf8-11e5-9ef0-c5a0f54836bf.png)
![qq 20160206171736](https://cloud.githubusercontent.com/assets/17095606/12865959/08276f5a-ccf8-11e5-81fa-50ca1c81ba75.png)

**test by f1d1049**
[f1d1049_log.txt](https://github.com/citra-emu/citra/files/120210/f1d1049_log.txt)
![qq 20160206174126](https://cloud.githubusercontent.com/assets/17095606/12865995/33bb46d6-ccf9-11e5-8eb4-39fcbeb23ce6.png)
![qq 20160206174215](https://cloud.githubusercontent.com/assets/17095606/12865997/34798d8a-ccf9-11e5-96be-79bfdf7b417b.png)
![qq 20160206174234](https://cloud.githubusercontent.com/assets/17095606/12865996/346b489c-ccf9-11e5-8a30-a746f996dc15.png)

**Comment by JohnGodgames** [comment]
It's not an issue, but progress.Bunnei fixed it with fragment lighting...so you can close this issue
