### ISSUE TITLE
Instant crash when loading the emulator

### ISSUE THREAD

**Issue by BigheadSMZ** [citra-emu/citra#1397]
I haven't really tried this emulator out much, but in the past I was at least able to load it and mess around with it (albeit slow). I'm not sure what has changed, but even builds that used to work no longer work. I can't find anything about this issue so I'm making this report, because maybe the problem is on my end, but nothing else is exhibiting issues so I can only assume the issue is with Citra. As soon as I load citra-qt.exe, I am welcomed with the message....

_citra-qt.exe has stopped working
A problem caused the program to stop working correctly. Please close the program._

This is displayed twice before it closes. I can sometimes bypass the issue by directly dropping my ROM onto citra.exe, but sometimes this also causes an instant crash. Plus, I have no way to access the menu bar options. But, it does work sometimes and spams this error message no matter what game it is...

_Render.OpenGL <Error> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:446: API ERROR 1282: GL_INVALID_OPERATION error generated. Function >**Insert Here**< is deprecated and not available in preview contexts._

For >Insert Here< OpenGL functions, I've seen...
glPopMatrix
glPopAttrib
glVertex2fv

I don't remember this being spammed in the past for every single game I load, so if the problem is on my end, any ideas on why it's crashing or what the problem is? Maybe a graphics card driver update? (I'm far to lazy to roll back at the moment to see, but I will if requested.) I have loaded dozens of emulators and PC games to see if anything else is giving me problems and nope, they all work. Only Citra is giving me a headache for whatever reason...

System info...
Windows 10 x64
Intel Core i5 2500k
Geforce GTX 970
8GB G.Skill DDR3

**Comment by smartkaartik** [comment]
No help is given by github citra,they can only help to close the issue.
https://github.com/citra-emu/citra/issues/1234 you can see that.

**Comment by LittleWhite-tb** [comment]
I guess you have a configuration with two GPUs (Intel one and NVIDIA one). Try to set your computer to start citra on NVIDIA.

**Comment by yuriks** [comment]
I'm not sure what build you're using, but it mustn't be very recent, because we haven't loaded these functions for ages.

**Comment by BigheadSMZ** [comment]
No on-board GPU and just a single graphics card. My motherboard is an ASRock P67 Extreme4 Gen3. I did try some older builds I had laying around, along with the latest nightly found on the main site here. http://citra-emu.org/

On the rare chance the site's link wasn't being updated, against my better judgment I tried the latest I could find on EmuCR. http://www.emucr.com/2016/02/citra-git-20160206.html

The crash is happening on all of them. The problem must be on my end because they worked before, so this issue is most likely invalidated by that alone... I just can't remember if it was before moving to Windows 10 or not. It's really frustrating to say the least because I can usually research and troubleshoot these kinds of issues and eventually come up with a solution, and after hours I'm still stumped.

Upon loading the emulator, the GUI crashes immediately with this: http://i.imgur.com/lXrkJYN.png
No relevant information at all. Just a "Close the program" button. Very useful Microsoft...

If I close the console window before clicking close, then this Timer message comes up before closing, which may not have anything to do with anything. http://i.imgur.com/k3qgHT2.png

@yuriks: Although those functions may not be loaded, for some reason they are being spammed for me (even on the latest build I can find) if I bypass the QT frontend by dragging a ROM directly onto citra.exe. I don't even think this is related to the crash I'm experiencing, but figured it would be worth pointing out anyway. http://i.imgur.com/kpJwapa.png

At this point I've run out of ideas and things to try. Since nobody else seems to be having this issue it's probably a rare issue exclusive to something dumb going on with my computer, so trying to figure it out is most likely a waste of time at this point. I know Citra is still young in development and I enjoy seeing emulators progress, but it's probably not worth an entire OS reinstallation just to hope it will "fix" whatever is going on, so I guess I'll try again in the future. :(

**Comment by Kloen** [comment]
![image](https://cloud.githubusercontent.com/assets/9112818/12875274/b71f165e-cde6-11e5-891d-9df5a9ac68ae.png)

Hapens on last master only. The build 
citra-20160205-69e2453-windows-amd64.7z	10M	05-Feb-2016 22:11 
It's clean.

**Comment by purpasmart96** [comment]
EmuCR builds are not supported, please use the builds from Citra's website.

**Comment by yuriks** [comment]
@BigheadSMZ I'm confused about where exactly you're seeing the issue. Are you getting this on the Qt or GLFW frontends?

**Comment by BigheadSMZ** [comment]
@purpasmart96: I did try the official build from the website, along with older official builds I downloaded in the past. The EmuCR thing was just a test to see if there was a difference and there wasn't.

@yuriks: I guess it depends on which issue you mean. My main issue and why I created this issue report is that I can't get the QT frontend to work at all. If I try to load **citra-qt.exe**, it crashes instantly. And I cannot for the life of me figure out why because it used to work, and I'm not having any other issues with my PC that lead me to believe there's some software/hardware conflict that's responsible for it.

As for the OpenGL error thing, this I stumbled on when trying to bypass the QT executable by dropping a rom directly onto **citra.exe** and loading that way. This allows me to actually "sometimes" load games without citra crashing, but I noticed that error message being spammed so I figured it was worth mentioning. But I'm not sure if this is even related to the instant crash I'm experiencing. I can't find any other info on it so I'm assuming at this point it's specific to me for some reason...

**Comment by yuriks** [comment]
@BigheadSMZ The GLFW frontend (citra.exe) absolutely should not be loading those functions. Do you have any software that hooks into games to display FPS counters, or OSDs? I don't think this is a citra issue at this point.

**Comment by BigheadSMZ** [comment]
Yep that was it, it was EVGA Precision. I almost forgot about it completely because I disabled the OSD a long time ago, but it looks like it's still trying to hook into apps for whatever reason. So now I uninstalled it, I'll find another application to crank up the fan speed. This did stop the errors from spamming, but the crash is still happening.  :(

At least the most important mystery is solved since it raised a red flag, sorry for the false alarm. When I get time to do a full OS reinstallation hopefully the crashing issue will resolve itself.

**Comment by yuriks** [comment]
So, do you still crash? Or just not get the errors in the log?

**Comment by BigheadSMZ** [comment]
Instant crash when loading the QT frontend. Not sure what the problem is, I can only assume something is messed up on my end although I'm not sure what. I'm going to do a fresh OS install sometime in the near future, which will hopefully fix it as a side effect.

**Comment by BigheadSMZ** [comment]
Sorry it took me so long to get back to this issue... it seems the latest versions work well! Not sure what you guys did but the latest nightly does not instantly crash, the GUI loads successfully, and games are once again booting. The older versions are still crashing, although they didn't in the past, but I suppose that's not important. :)
