### ISSUE TITLE
Distorted text in several games

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1398]
There is a list of some games with text distortion.As @yuriks mentioned it's can be caused by geometry shaders propably.

### List of some affected games:

DOOORS
![doors tex](https://cloud.githubusercontent.com/assets/11453507/12872311/a1e6ffae-cda0-11e5-91ac-9323e5ede9ea.PNG)

Dragon Ball Z: Extreme Butoden
![dragon ball z extreme butoden tex](https://cloud.githubusercontent.com/assets/11453507/12872313/b0a6c43e-cda0-11e5-896b-951002fe8c6b.PNG)

Excave II: Wizard Of The Underworld
![excave ii wizard of the underworldtex](https://cloud.githubusercontent.com/assets/11453507/12872321/d9621dc4-cda0-11e5-963f-7b08d6117196.PNG)

Flap Flap
![flap flap tex](https://cloud.githubusercontent.com/assets/11453507/12872324/dd4e4d90-cda0-11e5-90a8-53fbbb18377f.PNG)

Jet Dog
![jet dog tex](https://cloud.githubusercontent.com/assets/11453507/12872326/e06a37e6-cda0-11e5-9aae-7dbd977a1264.PNG)

Langrisser: Re - Incarnation Tensei
![langrisser re - incarnation tensei tex](https://cloud.githubusercontent.com/assets/11453507/12872328/e4736a6a-cda0-11e5-8235-2aef9f4f303e.PNG)

Moco Moco Friends
![moco moco friends tex](https://cloud.githubusercontent.com/assets/11453507/12872330/e78646b4-cda0-11e5-9740-99f5d5baff34.PNG)

Monster Strike (JP)
![monster strike tex](https://cloud.githubusercontent.com/assets/11453507/12872332/ee97b24e-cda0-11e5-8c39-10dc3bb67747.PNG)

Navy Commander
![navy commander tex](https://cloud.githubusercontent.com/assets/11453507/12872333/f4713b86-cda0-11e5-94c1-8a1e894a2693.PNG)

Phoenix Wright: Ace Attorney Trilogy
![phoenix wright ace attorney trilogy tex](https://cloud.githubusercontent.com/assets/11453507/12872335/f852d052-cda0-11e5-8a8e-9d3b82d35dbd.PNG)

Pokemon Link: Battle!
![pokemon link battle tex](https://cloud.githubusercontent.com/assets/11453507/12872337/fd0fbb46-cda0-11e5-9a6e-93dca3117a5a.PNG)

Simple DL Series Vol 38: The Item Sagashi: Joshikousei Tantei Shinjitsu no Jikenbo
![simple dl series vol 38 the item sagashi joshikousei tantei shinjitsu no jikenbo tex](https://cloud.githubusercontent.com/assets/11453507/12872339/011407a6-cda1-11e5-9e87-625d899662ea.PNG)

The Legend of Zelda - A Link Between Worlds DEMO
![the legend of zelda - a link between worlds demo tex](https://cloud.githubusercontent.com/assets/11453507/12872341/05bcf83a-cda1-11e5-8f9d-69a7c2404b6d.PNG)

**Comment by deadair3210** [comment]
This also happens with Nintendo Badge Arcade

**Comment by archshift** [comment]
Yoshi's New Island as well.

**Comment by Subv** [comment]
I'm willing to guess this is because of the lack of geometry shader support

**Comment by mailwl** [comment]
Dragon Quest VIII as well

**Comment by JayFoxRox** [comment]
Should be tested against https://github.com/citra-emu/citra/pull/1479
Multipy-Add is commonly used for 2D sprite scaling / positioning (screen_vertex = sprite_size * sprite_vertex + sprite_pos).

I'll try to get access to some games on this list and look into it if #1479 doesn't fix it.

**Comment by JohnGodgames** [comment]
# Oh my fixed by #1479 too

![doors text](https://cloud.githubusercontent.com/assets/11453507/13641170/c4ecbbb2-e617-11e5-9714-6760d68da9b4.JPG)
![dragon text](https://cloud.githubusercontent.com/assets/11453507/13641172/c8659ade-e617-11e5-9829-2cbc4f0c61a3.JPG)
![excave 2 text](https://cloud.githubusercontent.com/assets/11453507/13641177/cbc49b62-e617-11e5-9757-1f09384f5602.JPG)
![jet text](https://cloud.githubusercontent.com/assets/11453507/13641188/cfbf4780-e617-11e5-9191-172318cd18c2.JPG)
![flap text](https://cloud.githubusercontent.com/assets/11453507/13641191/d3901556-e617-11e5-8bb9-77e289486b73.JPG)
![link btw text](https://cloud.githubusercontent.com/assets/11453507/13641196/d63f2bf2-e617-11e5-9d86-5c901b4c47ee.JPG)

**Comment by Subv** [comment]
fixed by #1479
