### ISSUE TITLE
games

### ISSUE THREAD

**Issue by cagethelonewolf** [citra-emu/citra#1399]
i been getting really attracted to the animal crossing games i loveing them more and more i even whent back and played the game cube one and beat it in 2 or 1 in game night i saw your em was real and not a fake or a scam so i wornding if you know of any animal crossing new leaf roms i dont have a lot of room on my laptop so i dont want to go deleating everything and not be able to even play what i wanted

**Comment by lioncash** [comment]
Sorry, we don't provide ROM links

**Comment by cagethelonewolf** [comment]
well do you know if any works or sud i not hunt at all because there all
bad broken or a scam
