### ISSUE TITLE
Super Pokemon Rumble graphic issues.

### ISSUE THREAD

**Issue by Kloen** [citra-emu/citra#1402]
I think that a picture talks on his own...

![image](https://cloud.githubusercontent.com/assets/9112818/12932323/8cc9e2ba-cf82-11e5-94d0-61d3d25295d9.png)

![image](https://cloud.githubusercontent.com/assets/9112818/12932381/c966dfb6-cf82-11e5-9abf-15587adf9890.png)

![image](https://cloud.githubusercontent.com/assets/9112818/12932431/0ec50e70-cf83-11e5-9e5e-e8e4d02e067b.png)

![image](https://cloud.githubusercontent.com/assets/9112818/12932592/c6038328-cf83-11e5-8299-16af7b6e20db.png)

Specs:
![image](https://cloud.githubusercontent.com/assets/9112818/12932477/3a3a59d4-cf83-11e5-912b-9bc9d5a54535.png)
![image](https://cloud.githubusercontent.com/assets/9112818/12932526/924fea62-cf83-11e5-9237-53b8787175c9.png)

**Comment by yuriks** [comment]
This is #1394 and #1293

**Comment by JohnGodgames** [comment]
#1394 helps with mirrored screen, but there is still some of depth problem similar to tekken https://www.youtube.com/watch?v=_xzWNKxzZ4I

**Comment by Kloen** [comment]
#1394 fixed mirrored screen, now it just:

![image](https://cloud.githubusercontent.com/assets/9112818/13521225/67252796-e1e7-11e5-85d6-853823fbb930.png)

**Comment by yuriks** [comment]
Should go away if you disable the shader JIT. Fixing this needs a re-write of the JIT which is on my plans eventually... (cc @bunnei)

**Comment by bunnei** [comment]
Note: This isn't necessarily #1293, the above screenshots only indicate that the game is using a shader that jumps backwards, which does not work in the shader JIT.
