### ISSUE TITLE
Open dev discussion(before develop)

### ISSUE THREAD

**Issue by JamePeng** [citra-emu/citra#1407]
@bunnei @Subv @lioncash @MerryMage 
Hi , I am newbie of developer JamePeng. Not sure If I can open a discussion here :p ,but request discuss always behind a develop!
3dbrew was a treasure, I read it , update my code , test ,and learn a lot!
Here are my three problem it make me get confused!

1)What is the new definition of citra?Old 3DS or NEW 3DS?
maybe you will say"why do you ask?"
![qq 20160212110115](https://cloud.githubusercontent.com/assets/17095606/12998339/a70c2636-d17d-11e5-971b-190922da4c09.png)

After I have improved and implement a lot of functions ,some function will come out obvious.like this CheckNew3DS. 
That is not only a question of "cmd_buff[1]=0"or"cmd_buff[1]=1",but also a definition of citra.
Because beginning of firmware 8.0.0,  the process detail of 3DS have some different.
e.g.
![qq 20160212105241](https://cloud.githubusercontent.com/assets/17095606/12998452/c2bd9f94-d17e-11e5-9aad-b66c443a49dd.png)

Maybe some small change which will affect the development in the future?

2)Another serious problem is the PIPE.
Yes，In the DSP, the canned_read_pipe array maybe solve early problem on the surface,
But some test display the pipe of amount of usage is 0x20 beyong the canned_read_pipe size 0xF
![qq 20160212115938](https://cloud.githubusercontent.com/assets/17095606/12998578/6929539a-d180-11e5-8f90-0289114a24be.png)
Compare to 0xF and 0x20, I think there are a huge data lost by using canned_read_pipe.
Shall we emulate a pipe operation? The  canned_read_pipe was not enough definitely!!

3)The third problem is the function GetAppletInfo()
With my update the APT functiontable, a lot of function could be implement.
But someone increase the problem scale , the appletID
![qq 20160212121141](https://cloud.githubusercontent.com/assets/17095606/12998705/dc95d05a-d181-11e5-8d48-d0436cdb8f88.png)
More ID means more situation of process! How can we generate a true return value and make it work well especially.
![qq 20160212121331](https://cloud.githubusercontent.com/assets/17095606/12998720/19ca2eda-d182-11e5-9c24-f17e823f68d8.png)
0x401 is mean softkeyboard?What is this?
![image](https://cloud.githubusercontent.com/assets/17095606/12998658/548dc9ce-d181-11e5-9f0c-113533338364.png)

**Comment by lioncash** [comment]
You should likely ask these questions on the IRC channel on Freenode (channel name: #citra).

**Comment by JamePeng** [comment]
@lioncash  OK！
