### ISSUE TITLE
Building citra fails 

### ISSUE THREAD

**Issue by q1w2e3r43** [citra-emu/citra#1410]
Building Citra fails on linux when using GCC 4.8.6  With GCC 4.9.3 works perfect
For error code: http://pastebin.com/FMMBDkuy

**Comment by archshift** [comment]
Sorry, we don't support GCC 4.8.

**Comment by LittleWhite-tb** [comment]
Updated Linux Build wiki page -> https://github.com/citra-emu/citra/wiki/Linux-Build to match what you just said.
