### ISSUE TITLE
Style Savvy: Trendsetters JPN - No graphics displayed

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#1411]
http://pastie.org/pastes/10722175 <- Log

Seems that this game does not display graphics.
I have tested HW / SW Renderer and enable / disable shader jit options, but don't helps it.

This game known in the PAL region as Nintendo presents: New Style Boutique, in Japan as Wagamama Fashion: Girls Mode Yokubari Sengen!

**Comment by mailwl** [comment]
Completely helpless log. SetAxiConfigQoSMode just set priority between cpu and gpu, and i don't think it affects on graphics on emulator

**Comment by yuriks** [comment]
Do those lines repeat infinitely? Maybe we just need to return a valid result there.

**Comment by exhalatio** [comment]
SetAxiConfigQoSMode, this line was repeated.

I've uploaded a Debug info log.
Could you check this?
https://mega.nz/#!YhBXFbzb!h6X19F7-_zDrcLrrRdiM6csqR125KllGlpkCVxuhqeE

**Comment by CakeLancelot** [comment]
Also _seems_ to be a similar issue with 3D Classics: Xevious, except it outputs 'SetAxiConfigQoSMode' and stops. Black lines are on the right side of the screen but otherwise nothing.

Screenshot: https://gyazo.com/fb7e06b915b102c9724c77556683a2e6.png
Log: http://pastebin.com/Kr1Y52h6

**Comment by JohnGodgames** [comment]
Strange, my US backup is working (worked along time ago too) https://www.youtube.com/watch?v=Jc561o30zgc

**Comment by exhalatio** [comment]
I just tested US version. Undoubtedly it working.
It is strange, I re-dumped JPN version still not working...

**Comment by exhalatio** [comment]
Unfortunately, doesn't help #1419

**Comment by purpasmart96** [comment]
change you region value to the one used by the game, see if that helps.

**Comment by exhalatio** [comment]
Thanks in advice.
I change the Console Language value, (https://github.com/citra-emu/citra/blob/master/src/core/hle/service/cfg/cfg.cpp#L66), that worked well.

Can I closed this issue?

**Comment by wwylele** [comment]
Since language selecting is implemented, I think we can close this.
