### ISSUE TITLE
[Nvidia] OpenGL Acceleration doesn't work in Quadro FX1800

### ISSUE THREAD

**Issue by fervi** [citra-emu/citra#1417]
Hello

I have few computers; on Radeon OGL AC works propertly, but in my Quadro FX1800 (nvidia 340 drivers, Linux) it doesn't work

[  20.109285] Render.OpenGL <Error> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:444: API ERROR 1282: GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.

All elements except background isn't showed (with Hardware Acceleration option), but in Software Rendering it works without any problems.

I used this Nyan Cat example:
https://www.dropbox.com/s/e400my3xm0zw74r/nyan_cat.zip?dl=0

**Comment by emmauss** [comment]
your opengl version may be too low for it.nvidia reports your card to support ogl 3.0. citra needs ogl 3.3

**Comment by yuriks** [comment]
You need to paste the entire log.

**Comment by fervi** [comment]
@emmauss
OpenGL version string: 3.3.0 NVIDIA 340.96
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL context flags: (none)
OpenGL profile mask: (none)

@yuriks
http://gmclan.org/uploader/6184/test0269f.txt

**Comment by yuriks** [comment]
Huh, that's pretty strange. I wonder if it's some untested shader combination the game uses or if your compiler acts differently for some reason. I'll try to take a look when I'm able.

**Comment by fervi** [comment]
@yuruiks
Oddly enough, the problem is definitely on the card nvidia, because AMD this example works without any problem.

Ok, stay tuned :)

**Comment by JayFoxRox** [comment]
Does it apply to all games or specifically to said nyan_cat app?
Also, is this fixed in recent versions?

I'll close this if there is no response within the next days.

**Comment by fervi** [comment]
@JayFoxRox 
I didn't test other ROMs, but it is now fixed
