### ISSUE TITLE
(website) bare code website

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#1423]
at the RSS 2.0 in the blog section at the bottom of the page on the website if you click on it, it will lead you to a bare code webpage, not sure if intended or a bug 

![website](https://cloud.githubusercontent.com/assets/12820322/13333058/a83b41d2-dc0d-11e5-9bfd-121c2e1774ac.PNG)

**Comment by bunnei** [comment]
Intended. Thats an rss feed, it's meant to be consumed by an rss reader :)

**Comment by RavenHome1** [comment]
ah alright sorry for the trouble
