### ISSUE TITLE
hello i got that problem can you help plzz?

### ISSUE THREAD

**Issue by sayeem012** [citra-emu/citra#1425]
i dont understand it but that's the screenshot.
![capture d ecran 3](https://cloud.githubusercontent.com/assets/17502658/13363344/c837f382-dcc0-11e5-9e1a-1c1dda0c3bf1.png)

Then when begin the game that's what happens black screen.

![capture d ecran 4](https://cloud.githubusercontent.com/assets/17502658/13363355/d484c106-dcc0-11e5-980c-203380606ced.png)
![capture d ecran 5](https://cloud.githubusercontent.com/assets/17502658/13363356/d485a88c-dcc0-11e5-8a26-91d62149ca83.png)

**Comment by jroweboy** [comment]
Please don't abuse the issue tracker. This is not a support forum for you to find help. Also, that does not appear to be an official build, so the IRC wouldn't be able to help you either.
