### ISSUE TITLE
Project X Zone 2 freeze

### ISSUE THREAD

**Issue by Punk34** [citra-emu/citra#1428]
The game freezes on the first window

![- -1](https://cloud.githubusercontent.com/assets/13983158/13378834/48fd260e-de24-11e5-9aa2-7c43efa2a2fc.jpg)

**Comment by mailwl** [comment]
@Punk34, may u test with latest master?
there is no text shown at all, but in other the game fully playable.

**Comment by Punk34** [comment]
Same thing with "HEAD-b8e9af9"

**Comment by mhvuze** [comment]
Just to add: The same issue is present in b25605e for "MonHun Nikki: Poka Poka Airu Mura DX" when the game tries to write savedata or load savedata.

**Comment by Subv** [comment]
Does this still happen? StoreDataCache is most definitely not the cause of this issue.

**Comment by Dragios** [comment]
This does not happen anymore and can be safely close. It already managed to create save file long time ago.
