### ISSUE TITLE
Rune Factory 4 - corrupted? graphics

### ISSUE THREAD

**Issue by emmauss** [citra-emu/citra#1431]
I notice some graphical bugs when playing rune factory 4. object graphics are being replaced by random graphic artifacts, like the order symbol replacing a wall, or the well replacing a door.it is completely random, and occurs more often when you a play play longer in a session.it can be quickly fixed when you turn of hardware rendering and turn it on.
![screenshot 30](https://cloud.githubusercontent.com/assets/5307160/13388288/9be69494-deb6-11e5-990d-40a686ac7a2b.png)

above screen log
https://justpaste.it/rt5r

fixed screen
![screenshot 31](https://cloud.githubusercontent.com/assets/5307160/13388335/ed371abc-deb6-11e5-80de-0c25b5b3d8d5.png)

the order symbol replaces the wall behind my calendar in the buggy screen

its log
https://justpaste.it/rt5s

other screens
![screenshot 32](https://cloud.githubusercontent.com/assets/5307160/13388354/1200061a-deb7-11e5-8a6e-860b13e1beff.png)
the well replace the door of the house to the right,
![screenshot 33](https://cloud.githubusercontent.com/assets/5307160/13388356/1578f8c4-deb7-11e5-923b-3b11fa9dc706.png)

**Comment by tfarley** [comment]
Very likely due to the HW renderer using an improper way of detecting texture invalidation in master. Reminder to re-check this when I PR texture forwarding which includes an invalidation check on each CPU memory write and should solve the issue.

**Comment by emmauss** [comment]
okay

**Comment by tfarley** [comment]
Can you do a preliminary test with #1436 to see if this is fixed?

**Comment by emmauss** [comment]
i am curently doing it.game is a little bit faster, but there are still bugs.
![screenshot 34](https://cloud.githubusercontent.com/assets/5307160/13453486/6f0bbc04-e048-11e5-9489-d52294e6e0e3.png)
the door aint the right right.

**Comment by tfarley** [comment]
Can you try this again with #1436 since the latest commit?

**Comment by emmauss** [comment]
no bug so far, though i will keep testing it to see if the bugs have just been delayed or they are gone for good.

**Comment by emmauss** [comment]
30 minutes into it and no bugs.i conclude that it has been fixed with pr #1436 .
