### ISSUE TITLE
The legend of legacy - CreateThread AssertionFailed

### ISSUE THREAD

**Issue by Kloen** [citra-emu/citra#1432]
Just found this. Couldn't get the full log to a file so... well, windows power shell in a nutshell.

![image](https://cloud.githubusercontent.com/assets/9112818/13393239/6da231f4-dee0-11e5-9a0a-65d19240aefc.png)

**Comment by mailwl** [comment]
can u compile from source? to fix this, you have to insert string
`case THREADPROCESSORID_ALL:`

at line https://github.com/citra-emu/citra/blob/master/src/core/hle/svc.cpp#L489

**Comment by Kloen** [comment]
That works...
![image](https://cloud.githubusercontent.com/assets/9112818/13425601/4708f910-dfa8-11e5-8e9b-2f6e44965b80.png)

Now on, there are an infinite loop of 
SaveData Corrupted -> Format Save Data -> No -> SaveData Corrupted -> Format Save Data ->...

Or a:
SaveData Corrupted -> Format Save Data -> Yes -> Crash!

**Comment by mailwl** [comment]
#1302 should help, but i'm not sure

**Comment by Kloen** [comment]
The error it's the same that I got with Digimon Re on Intel Cards using Hardware Render...

On Software Render it's booting well (slow as ever):
![image](https://cloud.githubusercontent.com/assets/9112818/13426754/d897bb94-dfaf-11e5-867b-2bcbe9e96527.png)

**Comment by Kloen** [comment]
Fixed by:
#1434 
#1436 

![image](https://cloud.githubusercontent.com/assets/9112818/13454877/41fb371e-e05a-11e5-9181-7a8bf3b70ffc.png)
![image](https://cloud.githubusercontent.com/assets/9112818/13454884/56564384-e05a-11e5-9a49-7065d58223b0.png)
