### ISSUE TITLE
Debug.Emulated <Critical>  core\hle\svc.cpp:SVC::Break:405: Emulated program broken execution

### ISSUE THREAD

**Issue by codelyoko2409** [citra-emu/citra#1438]
![untitled](https://cloud.githubusercontent.com/assets/17511625/13457753/5aab677e-e09c-11e5-9f31-7d3de49cc454.png)
Any game is like this.
Sorry for my bad English

**Comment by Kloen** [comment]
You are using a custom build from immortalgames, which are not oficial builds. Am I wrong?

Try using oficial Nightly builds from: https://citra-emu.org/

And... "any game" it's not even usefull.

**Comment by codelyoko2409** [comment]
But the oficial Nightly builds is like this too
I try it with pokemon x and pokemon omega ruby

**Comment by Kloen** [comment]
Pokemon games are not actually supported by citra. Only a few custom builds can run them, and not even in a full playable state.

**Comment by Subv** [comment]
See https://discuss.citra-emu.org/d/42-how-do-i-play-pokemon/2
