### ISSUE TITLE
Commits question 

### ISSUE THREAD

**Issue by SakataGintokiYT** [citra-emu/citra#1439]
#How to add this commits to git clone ?﻿
-https://github.com/citra-emu/citra/pull/1389
-https://github.com/citra-emu/citra/pull/1421
-https://github.com/citra-emu/citra/pull/1426
-https://github.com/citra-emu/citra/pull/1429
-#1302
-https://github.com/citra-emu/citra/pull/1436
-https://github.com/ds84182/citra/commit/4369c7bde06bf89dbc6ff9295b2603fa26b598fc

**Comment by mailwl** [comment]
git remote add <name> <repository url>
https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes

**Comment by bunnei** [comment]
This isn't an issue with Citra and doesn't belong here. Feel free to try our forum (https://discuss.citra-emu.org/) or IRC.
