### ISSUE TITLE
Why does cmakelists check for glfw3, not libglfw3?

### ISSUE THREAD

**Issue by ProfessorKaos64** [citra-emu/citra#1442]
Debian package:
https://packages.debian.org/source/jessie/glfw3

Exact request (now closed) upstream at glfw:
https://github.com/glfw/glfw/issues/280

`glfw3` is Debian source code that `libglfw3` is built from.
https://packages.debian.org/source/jessie/glfw3

Maybe I am missing something, but that is GLFW 3.x.x. GLFW3 was packaged for sid in 2014. Debian hosts 3.0.4-1

**Comment by jroweboy** [comment]
It won't be an issue for much longer as citra is removing GLFW in favor of SDL 2 

Watch https://github.com/citra-emu/citra/pull/1403 for this to happen

**Comment by ProfessorKaos64** [comment]
Will subscribe, many thanks.
