### ISSUE TITLE
Zelda Triforce Heros Crash

### ISSUE THREAD

**Issue by brimaster2000** [citra-emu/citra#1443]
Citra seems to lock up and freeze after a spin attack is charged.

**Comment by KillzXGaming** [comment]
Issue occurs in Tri-Force Heroes and Kirby Triple deluxe too (and possibly Yoshi New Island). Happens when a particle effect occurs. Disabling shader effect results in no crash however shows buggy particles.

**Comment by ds84182** [comment]
Possibly unimplemented Geometry Shaders. Can you both post logs?

**Comment by bunnei** [comment]
@KillzXGaming what do you mean by "Disabling shader effect results"... Do you mean disabling the shader JIT?

**Comment by KillzXGaming** [comment]
Yes. by disabling Shader JIT.

**Comment by JohnGodgames** [comment]
Yeah there is more games that do the same thing and propably more:

Exstetra
Final Fantasy Explorers
Kirby Fighters Deluxe
Kirby Triple Deluxe
Sayonara Umihara Kawase

dupe of https://github.com/citra-emu/citra/issues/1081
