### ISSUE TITLE
Citra not running in windows 8.1 Pro X64  (citra.exe entry point not found)

### ISSUE THREAD

**Issue by RaoufAdel** [citra-emu/citra#1444]
http://s13.postimg.org/e3w1j4a6v/Screenshot_1.png

After i inserted all the dlls on my windows 8.1 pc i got the following error : "the produce entry point strncmp could not be located in dynamic link literary C:/Users/ /Desktop/citra/Qt5OpenGl.dll"
Window title is Entry point not found.

Please Help!

It is running well but slow on my another pc as it has 1.20 ghz processor.So i upgraded my another pc form 32 bit to 64 with 3.50 ghz processor but i am not able to run it

After i inserted all the dlls on my windows 8.1 pc i got the following error : "the produce entry point strncmp could not be located in dynamic link literary C:/Users/ /Desktop/citra/Qt5OpenGl.dll"
Window title is Entry point not found.

Please Help!

It is running well but slow on my another pc as it has 1.20 ghz processor.So i upgraded my another pc form 32 bit to 64 with 3.50 ghz processor but i am not able to run it

After i inserted all the dlls on my windows 8.1 pc i got the following error : "the produce entry point strncmp could not be located in dynamic link literary C:/Users/ /Desktop/citra/Qt5OpenGl.dll"
Window title is Entry point not found.

Please Help!

It is running well but slow on my Laptop WINDOWS 10 as it has 1.20 ghz processor.S

So i upgraded my another pc form 32 bit to 64 with 3.50 ghz processor but i am not able to run it IN WINDOWS 8.1 Pro X64

**Comment by jroweboy** [comment]
Hello @RaoufAdel 

Please do not ask for help on the issue tracker. This is for developers to log issues with citra and not a place for specific help requests. Please instead make an account on the forum and ask for help on there.
