### ISSUE TITLE
New Love Plus + freezes at warning screen

### ISSUE THREAD

**Issue by internetakias** [citra-emu/citra#1445]
[This](http://i.imgur.com/LcJKGxA.png) one to be exact. (The game has you hold the 3DS like a book mode so that's why the image is on its side)
Build: 699b2a6
Use Hardware Render: On/Off
Use JIT Shader: On/Off
OS: Windows 7 64 bit
Log: http://pastebin.com/ktn3xZ8i

**Comment by exhalatio** [comment]
Fixed by #1641

**Comment by internetakias** [comment]
Can confirm this

**Comment by MerryMage** [comment]
#1963 has been merged. Is this still an issue?
