### ISSUE TITLE
Monster Hunter 4G  crash error :Unsupported thread processor ID: 2

### ISSUE THREAD

**Issue by JamePeng** [citra-emu/citra#1449]
![qq 20160304155141](https://cloud.githubusercontent.com/assets/17095606/13521085/ee9bb620-e220-11e5-8d62-7feb2a256e46.png)

I think we should add the THREADPROCESSORID_MAX into SVC::CreateThread

PTM::CheckNew3DS will return the machine type(u8 output: 0 = Old3DS, 1 = New3DS.) 
so, if you select the New3DS,it will cause a assert failed!

**Comment by JamePeng** [comment]
#1520

**Comment by subzerohurley** [comment]
wait so can someone help me out? explain where i i do what?

**Comment by Andrix44** [comment]
Shouldn't this be closed? Same with #840.

**Comment by JayFoxRox** [comment]
Sounds okay to me, we'll reopen if this is still a problem. Closed.
