### ISSUE TITLE
Frontend. Failed to load ROM!

### ISSUE THREAD

**Issue by deslayer2000** [citra-emu/citra#1451]
The first game i try to load up but i keep getting the same message. Keeps saying it fails to load rom. Please help.

**Comment by RavenHome1** [comment]
rom is encrypted

**Comment by deslayer2000** [comment]
is there a way to get around that?

**Comment by RavenHome1** [comment]
nope, now please close this issue since this is not a valid report

**Comment by deslayer2000** [comment]
before i do, how do i know whether a game is encrypted or not?

**Comment by RavenHome1** [comment]
you will get the same error most of the time for every encrypted rom

**Comment by deslayer2000** [comment]
where can i get non-encrypted roms?

**Comment by RavenHome1** [comment]
no one will give you a pirated rom here, you will have to search for yourself, now please close this issue or leave it since someone will close it eventually

**Comment by deslayer2000** [comment]
alright, how do i close this thread?

**Comment by yuriks** [comment]
Support forum is that way ---> https://discuss.citra-emu.org/
