### ISSUE TITLE
Rune Factory 4 - no colour gate

### ISSUE THREAD

**Issue by emmauss** [citra-emu/citra#1452]
Another Rune Factory 4 bug, though not as annoying as the corrupted textures.All monster gates appear as completely white vortexes.Depending on the type of gate,a gate supposed to have a specific colour,black on it outer edge, the element or type colour in the mid range, and white at center.
![screenshot 38](https://cloud.githubusercontent.com/assets/5307160/13546356/4534f118-e2a3-11e5-98de-6ef9be7dd1c9.png)
  log:
https://justpaste.it/ryq1
this is not fixed by #1436

**Comment by amirlou** [comment]
hi emmauss i tired playing this game with most of citra build but i always get black screen on hw mode and on sw mode bad Texture can i ask you which Region of game you use i'm using (U) thx and sorry for asking unrelated question

**Comment by emmauss** [comment]
i also use the usa release.do you have a dumped shared_font.bin file.if you do put it in user/sysdata.otherwise you wont be able to boot it.

**Comment by amirlou** [comment]
yeah i got Shared_font.bin but my game run like this and its only run on new hw-tex-forwarding on other build all i get is black screen
![rf4black](https://cloud.githubusercontent.com/assets/16171668/13699700/51763fd4-e791-11e5-9591-b3d6ac0df149.jpg)

https://justpaste.it/s56x

**Comment by ds84182** [comment]
Can you retest this with the current master?

**Comment by amirlou** [comment]
hello i test it with current master got black screen on HW mode and buggy screen on SW mode
![fr citra hw](https://cloud.githubusercontent.com/assets/16171668/14220703/f45d04e4-f876-11e5-9ced-a45e39405f17.jpg)
https://justpaste.it/suqy here is note for HW test

![fr citra sw](https://cloud.githubusercontent.com/assets/16171668/14220716/0cdbb934-f877-11e5-9045-692e87678781.jpg)

https://justpaste.it/sur0 here is note for SW test

**Comment by emmauss** [comment]
i think this issue is getting out of topic.

**Comment by ds84182** [comment]
@emmauss I was asking you to retry this in the current master because #1479 probably fixed this

**Comment by emmauss** [comment]
sorry @ds84182  , i thought you where talking to @amirlou. tested the latest master. still completely white for the gates.

**Comment by JayFoxRox** [comment]
Does this work now? Can you provide more screenshots of citra and how it is supposed to look like?

**Comment by emmauss** [comment]
here is a screenshot on a 3ds
![capture1](https://cloud.githubusercontent.com/assets/5307160/15185240/d70e499a-1787-11e6-997a-68d5be332731.PNG)
that is an earth gate

even a neutral gate  should have a black aura.all gates have dark auras
here from citra
![screenshot 48](https://cloud.githubusercontent.com/assets/5307160/15185318/14952630-1788-11e6-80fd-0a473731bbc6.png)
from the latest master.

**Comment by ds84182** [comment]
Maybe it's something in TEV that isn't being emulated correctly? I can dump
the game when I get home and look through it

**Comment by JayFoxRox** [comment]
Unable to reproduce to me sucking at said game. Can you provide a savegame where it's easy to reproduce this bug? I plan to look into it. I've just "played" (just hit a + b to click through all menus, then leveled up in the forrest) for about 1 hour and felt it was the worst game ever designed. In the end was unable to even see the bug :rage:

**Comment by emmauss** [comment]
@JayFoxRox can you post a screenshot, cause it happens everywhere.no gate should be completely white.that is the bug.unless my dump is bad, and i dont think it is,it should happen on yours.please post a screenshot of the nearest gate you can reach,any gate at all.

**Comment by JayFoxRox** [comment]
I'm unable to *FIND* any gate. I don't know the games world and I'm guessing they only appear later in the games story?

**Comment by emmauss** [comment]
gates should be fairly common,when you get out of town, keep going east till you reach a save book and a notice board bordering an entrance to the forest. enter it and scout.you will find one soon.it infinitely generates monsters until it is destroyed.

**Comment by emmauss** [comment]
although when compared to RF3, due to the large world and numerous dungeons, the gates are more sparse.

**Comment by JayFoxRox** [comment]
Looks like a bug in the tev stages. My debugger says RGB is from "Unknown.rgb" I'll update this with infos later.

**Comment by emmauss** [comment]
fixed with #1786 .gate colour, aura and vortex motion looks okay.
