### ISSUE TITLE
Emu citra (error?)

### ISSUE THREAD

**Issue by Noticiero** [citra-emu/citra#1456]
Good boys and girls, I have a question that I don't know if it is a bug or not. I will tell you: 

well, I download the citra, in the file citra-qt and citra in properties add to open as administrator, all goes well. When I open it also it works for me, the problem is on boot I get screen black (the game is Pokemón Omega Ruby or Pokemon X) 

here a picture:  [http://imgur.com/hkJUtX8](url)

Thanks.

(translated)

**Comment by Subv** [comment]
Pokemon does not yet boot in master.
