### ISSUE TITLE
Story of Seasons ··Interaction does not show

### ISSUE THREAD

**Issue by louts** [citra-emu/citra#1464]
Interaction with animal characters does not show

**Comment by Zaneo** [comment]
While I suspect this issue will be closed, in future it would help to provide a relevant log, and more detail describing what issue is occurring, and how to reproduce it. If possible a comparison between how it should work on a physical device, versus how it is working in citra helps as well.

**Comment by bunnei** [comment]
Yes, I have no idea what this means. Please post a log, screenshots. configuration, git revision, etc. as @Zaneo pointed out.
