### ISSUE TITLE
Petit Novel series - Harvest December - unimplemented ControlArchive, recvData

### ISSUE THREAD

**Issue by Punk34** [citra-emu/citra#1470]
Only black screen in the game, the console says: unimplemented function 'ControlArchive', 'recvData'.

![01](https://cloud.githubusercontent.com/assets/13983158/13556969/86bdc920-e3f7-11e5-97f2-332afc9fb302.jpg)

**Comment by mailwl** [comment]
impl of ControlArchive you may take from my branch
https://github.com/mailwl/citra/blob/ctrl_archive/src/core/hle/service/fs/fs_user.cpp#L407
just comment lines 430-431 to avoid errors,
about recvData - Maribel PR https://github.com/citra-emu/citra/pull/1441

**Comment by mailwl** [comment]
i think, this issue may be closed

**Comment by wwylele** [comment]
Is the game playable now?

**Comment by mailwl** [comment]
yes
