### ISSUE TITLE
Shin Megami Tensei IV - ui glich

### ISSUE THREAD

**Issue by Punk34** [citra-emu/citra#1471]
I found a strange glitch, game ui is disappear depending on the camera angle, and during the interaction with npc
console says nothing

![citra-qt 2016-03-07 00-06-43-04](https://cloud.githubusercontent.com/assets/13983158/13557061/9a1b1192-e3f9-11e5-9fcf-1081c29184c5.gif)
![citra-qt 2016-03-027 00-06-43-04](https://cloud.githubusercontent.com/assets/13983158/13557062/9f02790c-e3f9-11e5-8bb5-02975ed86255.gif)

**Comment by JamePeng** [comment]
citra\user\config\qt-config.ini


[Miscellaneous]
log_filter=*:Debug

**Comment by Punk34** [comment]
@JamePeng  no errors or warnings, only something like this

![01](https://cloud.githubusercontent.com/assets/13983158/13568325/9322c7e0-e471-11e5-8474-8a79048edf7c.jpg)

**Comment by mailwl** [comment]
Pica gpu not fully implemented, don't wait a miracle.
The Tales Of The Abyss looks unaligned before crash, so it' moooore work for developers still
![tota](https://cloud.githubusercontent.com/assets/629437/13568801/f47223e4-e474-11e5-9535-cbe5b2f935fd.png)

**Comment by JayFoxRox** [comment]
Is this still an issue?

**Comment by Krusher97** [comment]
Played 10 hours of SMT4, did not encounter this at all.

**Comment by FearlessTobi** [comment]
Closing, as this issue very likely has been resolved. If that's not the case, report it here, and it will be reopened.
