### ISSUE TITLE
Crash Time 3D depth testing issue

### ISSUE THREAD

**Issue by bunnei** [citra-emu/citra#1473]
@JohnGodgames found this issue with #1462, which was still merged. From his post in the PR:

### Crash Time 3D before (imm-mode2):
![crash time 3d imm2 1](https://cloud.githubusercontent.com/assets/11453507/13554185/c8023ff2-e3a1-11e5-9286-cdf1213a4cc6.JPG)
![crash time 3d imm2 2](https://cloud.githubusercontent.com/assets/11453507/13554186/d0990e84-e3a1-11e5-9974-2b5aa175375a.JPG)

### Crash Time 3D after (imm-mode2 + depth-test-write):
![crash time 3d depth](https://cloud.githubusercontent.com/assets/11453507/13554197/f040e752-e3a1-11e5-9475-abeba00cf218.JPG)
![crash time 3d depth 2](https://cloud.githubusercontent.com/assets/11453507/13554199/f50aa2fa-e3a1-11e5-959b-f82e4c3d06b7.JPG)

**Comment by JohnGodgames** [comment]
Also Tappingo 1 or 2 and Thorium Wars have issues (bottom ones are bad):

![tappingo depth issue 1](https://cloud.githubusercontent.com/assets/11453507/13657945/880f3d8a-e673-11e5-9503-ddc8e716746b.JPG)
![tappingo depth issue](https://cloud.githubusercontent.com/assets/11453507/13658159/d99be81e-e674-11e5-8766-51add22c9c74.JPG)



![thorium wars depth 1](https://cloud.githubusercontent.com/assets/11453507/13657955/998802fe-e673-11e5-9bec-4b4ad27a058e.JPG)
![thorium wars depth](https://cloud.githubusercontent.com/assets/11453507/13657959/9e4b534a-e673-11e5-8f85-34c92767720b.JPG)

**Comment by yuriks** [comment]
Wonder if this is related to us not implementing the depth scale register. (Or I might've missed some detail in my PR. There's always that possibility. :))

**Comment by JohnGodgames** [comment]
So there are more issues unfortunately: 

### Brave Tank Hero

With #1462

![brave tank hero depth2](https://cloud.githubusercontent.com/assets/11453507/13882173/9f7f9098-ed24-11e5-90e4-cb821d306154.JPG)

Reverted #1462

![brave tank hero depth1](https://cloud.githubusercontent.com/assets/11453507/13882175/a272a948-ed24-11e5-8257-89419fe8ea66.JPG)


### The Legend of Zelda - A Link Between Worlds DEMO

With #1462

![albw demo depth 1](https://cloud.githubusercontent.com/assets/11453507/13882314/3ef6cd12-ed25-11e5-82e9-8d4c43a9166f.JPG)


Reverted #1462

![albw demo depth 2](https://cloud.githubusercontent.com/assets/11453507/13882318/4131dc52-ed25-11e5-94ec-be6da595ae6b.JPG)

**Comment by JayFoxRox** [comment]
Probably related to https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_DEPTHMAP_ENABLE ?

**Comment by JohnGodgames** [comment]
Some of testing (only sw renderer) https://github.com/JayFoxRox/citra/tree/w-buffer

![crash buffer 1](https://cloud.githubusercontent.com/assets/11453507/14069757/507a74fa-f49e-11e5-884e-e6440f9ea029.JPG)

![crash buffer 2](https://cloud.githubusercontent.com/assets/11453507/14069759/546caaec-f49e-11e5-8c85-e12e71854dca.JPG)

![tap buffer](https://cloud.githubusercontent.com/assets/11453507/14069755/4be5ac8e-f49e-11e5-97c6-545be74cc81b.JPG)

![thorium buffer](https://cloud.githubusercontent.com/assets/11453507/14069766/6695fb56-f49e-11e5-8334-95ed33f60b11.JPG)

![tank buffer](https://cloud.githubusercontent.com/assets/11453507/14069768/6a5f11be-f49e-11e5-86ce-49c431e3796a.JPG)

**Comment by JayFoxRox** [comment]
Crash Time 3D fixed by #1621 

However, **Tappingo and Thorium Wars: NOT FIXED**. They will be fixed by another PR as it is a seperate problem.

**FRIENDLY REMINDER: DO NOT POST DIFFERENT GAMES IN THE SAME ISSUE EVEN IF THEY LOOK SIMILAR**
