### ISSUE TITLE
[Request] Improve Debugger (please :) )

### ISSUE THREAD

**Issue by Romsstar** [citra-emu/citra#1480]
I understand this is probably not on the priority list right now,
and this is a bold request but please, is it somehow possible to improve functions of the debugger?

The disassembly as it currently is, is very limited.
The dissasembly window is not showing all used memory areas and you can't differenciate between read/write breakpoints. Also you can't assemble on the fly and override instructions. This wouldn't be a problem if we at least had a memory viewer/editor to go with :/

It is only opinion but I believe the PPSSPP debugger executed that splendly. Now I understand ARM is not MIPS but would it be possible at all to port the dissasembly functions of ppsspp over to citra? Because those were perfect in my view. 

Sorry for wasting your time.

**Comment by mailwl** [comment]
why? Use IDAPro.
i write a plugin for loading .3ds (https://github.com/mailwl/IDA_plugin_3ds) - mostly citra code used. sorry i forgot to mention it but later i write about it

**Comment by lioncash** [comment]
@mailwl Because not everyone uses IDA, nor can they usually afford it. Having something that works out of the box for basic stuff is a valid concern.

**Comment by mailwl** [comment]
hm... make sense. i forget about ida is very expensive

**Comment by JayFoxRox** [comment]
My 5 cents about this: Ditch the integrated debugger and focus on the gdbstub.

Citra is an emulator project and not a debugger project. We probably won't be able to create a debugger better than gdb (or tools able to communicate with the gdbstub) and the use of an integrated debugger is probably very limited as Citra is not meant as a development platform either (at the moment).

The only portion of the Citra debugger which is actually useful is the Pica debugger which is very important as there is no standard for generic low level graphics debugging yet. Even there something like apitrace or RenderDoc might be acceptable in the future. However, at this point the Pica debugger is much more invasive and features such as stepping through shader assembly wouldn't be possible in external tools.
But even with the texture viewer I think Citra is adding lots of bloat to essentially become a glorified "image viewer" - it's fine as it is but adding more features such as gamma viewing, zoom, blending, color format conversion etc (to emulate what games do) could potentially become a maintenance problem.

**Comment by MerryMage** [comment]
I took at look at the gdbstub code and it's in need of some love.

> So even if we would spend time on a debugger it should probably just be a very simple, lightweight external gdbstub-friendly ARM debugger.

I like this idea.

**Comment by yuriks** [comment]
Made obsoleted by #2689 (debugger removed)
