### ISSUE TITLE
Implement GetArchiveResource for Fire Emblem Fates ingame

### ISSUE THREAD

**Issue by pippo2931** [citra-emu/citra#1481]
Somebody that knows better than me,
should come up with the right values.

static void GetArchiveResource(Service::Interface* self) {
    u32* cmd_buff = Kernel::GetCommandBuffer();
    cmd_buff[1] = RESULT_SUCCESS.raw;
    cmd_buff[2] = 512;
    cmd_buff[3] = 16384;
    cmd_buff[4] = 0xFFFFFFFF;
    cmd_buff[5] = 0xFFFFFFFF;
}

![fef](https://cloud.githubusercontent.com/assets/17737754/13650547/0bf40468-e5f8-11e5-958a-f18592dea567.png)

**Comment by InusualZ** [comment]
I think that you should look at this: https://www.3dbrew.org/wiki/FS:GetArchiveResource

**Comment by pippo2931** [comment]
Disabling JIT, goes to battle.
It gets stuck after the first support battle

![fef2](https://cloud.githubusercontent.com/assets/17737754/13655318/554a3f04-e613-11e5-80f7-edf336528b5b.png)

![fef3](https://cloud.githubusercontent.com/assets/17737754/13655319/5d11862a-e613-11e5-8bd9-104b2739af7d.png)
