### ISSUE TITLE
Youkai Watch and other games hangs

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1484]
Games aren't fully hangs, characters and things are moving, looks like some of sync bug.

Possible candidates:

`core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function '0x00010082': port=boss:U, cmd_buff[1]=0x0, cmd_buff[2]=0x0, cmd_buff[3]=0x20, cmd_buff[4]=0x0`

### Youkai Watch

![youkai watch](https://cloud.githubusercontent.com/assets/11453507/13655105/532c3c0a-e65d-11e5-8d55-f2066d47cd87.JPG)

[LOG](http://pastebin.com/q9qtHZP5)

### Inazuma Eleven GO: Chrono Stones: Thunderflash

![inazuma](https://cloud.githubusercontent.com/assets/11453507/13655311/ba4e758c-e65e-11e5-8412-93e4718248ad.JPG)

[LOG](http://pastebin.com/Ki8c310U)

### Dragon Ball Heroes: Ultimate Mission
![dragon](https://cloud.githubusercontent.com/assets/11453507/13655626/0e47fca6-e661-11e5-95fe-01ae816a38af.JPG)

[LOG](http://pastebin.com/6uxBAY8B)

**Comment by emmauss** [comment]
can you test this and all other similar freezes with #1730  .it may have fixed them

**Comment by hrydgard** [comment]
@emmauss  not likely, #1730 is just a cleanup and performance improvement.

**Comment by JohnGodgames** [comment]
All of these fixed with https://github.com/MerryMage/citra **audio** branch

**Comment by emmauss** [comment]
@MerryMage once speculated that it may be caused by a wait in audio.though at that time he tested and couldn't find what was wrong.

**Comment by MerryMage** [comment]
@emmauss I have a better understanding of how audio works now than I did at the time.

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1734
