### ISSUE TITLE
Chibi-Robo Zip Lash! - Config block 0x170000 with flags 2 and size 4 was not found

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1486]
Also it shows critical error with result **0xD90103FA** (Cfg:GetCountryCodeString)

https://www.3dbrew.org/wiki/Cfg:GetCountryCodeString

[LOG](http://pastebin.com/f7kqE3EH)

**Comment by newretro** [comment]
Works fine with config_savegame from fw10.4

![02](https://cloud.githubusercontent.com/assets/17784684/13704597/c5d6332c-e7ad-11e5-8c1a-1c69847a7c59.jpg)

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1732
