### ISSUE TITLE
Texture issues on several games (gl_rasterizer.cpp Unknown cull mode 3)

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1487]
Affected games with similar symptoms:
### Transformers: Rise of the Dark Spark
![transformers rise](https://cloud.githubusercontent.com/assets/11453507/13555367/1cb2a970-e3bf-11e5-9d29-32804984ea6c.JPG)

### Teenage Mutant Ninja Turtles: Danger of the Ooze
![teenage 1](https://cloud.githubusercontent.com/assets/11453507/13555369/22535f32-e3bf-11e5-8791-3f0818303acd.JPG)

[LOG](http://pastebin.com/1fDcpQGv)

**Comment by JayFoxRox** [comment]
Also fixed by #1496 

![Fixed Turtles](http://i.imgur.com/xk16DDS.jpg)

(Image by @JohnGodgames )

**Comment by JohnGodgames** [comment]
Only in Transformers: Rise of the Dark Spark are missing characters after that.

**Comment by yuriks** [comment]
Note: Turns out this was unrelated to the mentioned "(gl_rasterizer.cpp Unknown cull mode 3)" on the title.
