### ISSUE TITLE
Super Smash Bros. Demo - broken characters (WritePicaReg:467: Invalid VS uniform index 127)

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1488]
With MAD fix I see more stuff than before [THIS VIDEO](https://www.youtube.com/watch?v=gmriJSYnji4)

Tested with https://github.com/citra-emu/citra/commit/3789de6bd9f54e532f290eb11634af27480ab88d

additional merged commits:
- https://github.com/citra-emu/citra/pull/1479
- https://github.com/citra-emu/citra/pull/1302

![smash 1](https://cloud.githubusercontent.com/assets/11453507/13661027/8c6dc59c-e68f-11e5-89da-15b7d5d49234.JPG)
![smash 2](https://cloud.githubusercontent.com/assets/11453507/13661031/8fbe953c-e68f-11e5-9d2e-41ee103f1eda.JPG)
![smash 4](https://cloud.githubusercontent.com/assets/11453507/13661035/95771760-e68f-11e5-82f3-b4db2dded737.JPG)
![smash 5](https://cloud.githubusercontent.com/assets/11453507/13661036/98fd1510-e68f-11e5-896d-07615dfe99b9.JPG)
![smash 6](https://cloud.githubusercontent.com/assets/11453507/13661038/9bed4092-e68f-11e5-934d-8b2a8e945541.JPG)

[LOG](http://pastebin.com/wVPP823y)

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1496

![super smash 2](https://cloud.githubusercontent.com/assets/11453507/13706595/042ddf1a-e7a6-11e5-9517-498f8f69add8.JPG)

**Comment by JayFoxRox** [comment]
@JohnGodgames  Just a little note: the bottom screen is affected by another PR. This only fixes the 3D characters (top screen) which were garbage before (drawing over almost everything making this a game breaking glitch)
