### ISSUE TITLE
Ridge Racer 3D hangs at menu

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1491]
Possible candidate:

`[ 121.820092] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'InvalidateDCache': port=dsp::DSP, cmd_buff[1]=0x478560, cmd_buff[2]=0x4000, cmd_buff[3]=0x0, cmd_buff[4]=0xFFFF8001`

![ridge racer](https://cloud.githubusercontent.com/assets/11453507/13669855/94b37936-e6c6-11e5-9a92-98cd2c08cef3.JPG)

[LOG](http://pastebin.com/dqfhcR0y)

**Comment by mailwl** [comment]
Citra don't use cache, so error in other reason

**Comment by MerryMage** [comment]
I think the 0xD8E007F7 error possibly due to using a "handle" returned from an unimplemented function is more likely.

**Comment by Subv** [comment]
I think command 0x000E0000 from cecd:u returns a handle. In fact, we already have a bug with a similar function from cecd:u (0x000F0000) if i'm not mistaken.

**Comment by JayFoxRox** [comment]
What's the precondition for this? The game works fine for me (except for the remaining bugs # 1661 and # 1693 ). Can this be closed?

**Comment by JohnGodgames** [comment]
Fixed on recent changes...
