### ISSUE TITLE
Missing Text And Characters are green boxes FE:Awakening

### ISSUE THREAD

**Issue by RainbowHawk** [citra-emu/citra#1494]
I get this error on the missing text
[   4.172772] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenArchive:389: failed to get a handle for archive archive_id=0x00000006 archive_path=[Binary: 01000000050a000000000000]

![capture 3](https://cloud.githubusercontent.com/assets/16834734/13696587/6d3d5e30-e7bb-11e5-9e48-a4a08936219e.JPG)

Every character model overworld in the game are green boxes. I keep getting this error in the cmd.

![capture 2](https://cloud.githubusercontent.com/assets/16834734/13696535/16c493fc-e7bb-11e5-8cc0-df72a3459a23.JPG)

![capture](https://cloud.githubusercontent.com/assets/16834734/13696605/9498c4e2-e7bb-11e5-9b76-f0cf68b3e5a2.JPG)

**Comment by Kloen** [comment]
Uh?
![image](https://cloud.githubusercontent.com/assets/9112818/13697042/0cb75390-e76b-11e5-8b7b-1c0b3e7333ec.png)

**Comment by RainbowHawk** [comment]
idk i think its the rom.

**Comment by RainbowHawk** [comment]
Nvm. I fixed the problem it was the rom after all.
