### ISSUE TITLE
7th Dragon III Code: VFD - Japanese text invisible

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra#1497]
Using https://github.com/citra-emu/citra/commit/c6cf075b5169ec40103b59ae170d0a7e369ed09d

This already happens in the menu:
(Compare to japanese near bottom of top screen: https://youtu.be/ardlHbCKrIk?t=33s)

![Broken font](http://i.imgur.com/zZ2jKn2.png)

Here is the same thing with hacked checkerboard texture:

![Checkerboard test font](http://i.imgur.com/HAl4MqW.png)

Seeing how the draw calls get through this is probably related to a missing texture.
The japanese text seems to come from a 128 x 32 A4 texture. The texture seems to be fully transparent in my installation of citra.
I believe this is due to a missing japanese font texture. It might be part of what is dumped as shared_font.bin on japanese systems so that should be tested.

~~Probably also affects "Digimon World ReDigtize Decode" ( #1129 ). I'll rename this issue if this affects nearly all japanese games.~~

[Full log](https://cdn.rawgit.com/JayFoxRox/629de0916c9730d30a5c/raw/f0daac5b8150ef661a4038daf0a5bfce1ca14564/index.html)

**Comment by Romsstar** [comment]
@JayFoxRox : I believe the issue must be something different in #1129 because we hacked the game and inserted English Text and Citra still won't show it. It would display fine on a 3DS though. Shouldn't it display English Text even without the Japanese shared_font.bin?

**Comment by JayFoxRox** [comment]
@Romsstar Note that the first 3 letters of the bottom row in the screenshot above are also supposed to be "RPG". It could simply be a font file for mixed japanese / english letters. However, it should be checked if "RPG" uses a different font texture as 128x32 is pretty small for 2 fontmaps.
The memory source for the textures should also be traced back too to figure out where stuff goes wrong.

However, this is a rather lengthy process probably and I (myself) would rather not do it now. Probably easier to wait until this is fixed "by accident" or a better test case turns up.

**Comment by Romsstar** [comment]
@JayFoxRox : I understand. I'll see that I can get a dump of a japanese shared_font.bin and post the results here. 
While the font thing is a separate issue, could you please look into why the model rendering goes wrong in #1129? I believe that is not connected to the missing font case but it would still be great if it could be fixed.

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1689
