### ISSUE TITLE
Monster Hunter 3: Ultimate and others have a broken menu

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1498]
These games from Capcom runs on the same engine propably.All three games says about "Unknown source op 6"

`[  20.085674] Render.OpenGL <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:GLShader::AppendSource:60: Unknown source op 6`
### Monster Hunter 3 Ultimate

![monster 2](https://cloud.githubusercontent.com/assets/11453507/13719770/27b11f06-e7fb-11e5-9695-510d8ebb95ff.JPG)

![monster 1](https://cloud.githubusercontent.com/assets/11453507/13719772/2c75b66e-e7fb-11e5-9ef6-8fdc57f36d2b.JPG)

[LOG](http://pastebin.com/hnz6FcWR)
### Resident Evil - Revelations

![resi eve 2](https://cloud.githubusercontent.com/assets/11453507/13719825/2175449a-e7fc-11e5-8c25-49ad8f26da86.JPG)

![resi eve 1](https://cloud.githubusercontent.com/assets/11453507/13719826/25fcf526-e7fc-11e5-9e0d-fb6592053b15.JPG)
### Resident Evil The Mercenaries 3D

![resi merc 2](https://cloud.githubusercontent.com/assets/11453507/13719899/3fc62094-e7fd-11e5-8bf9-7158b7b254d2.JPG)

![resi merc 1](https://cloud.githubusercontent.com/assets/11453507/13719901/443d2186-e7fd-11e5-88ed-157175753af2.JPG)

**Comment by JayFoxRox** [comment]
Guesswork: Missing TU3 [which probably is a thing at 0xA1](https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_00A1)).
Will also need extension of  [texconfig](https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_TEXUNIT_CONFIG) which seems to map texcoords to TUs

**Comment by Subv** [comment]
@JayFoxRox Isn't TextureUnit3 the Geoshader unit?

**Comment by mailwl** [comment]
mh3 shows a picture? what a progress for citra, i want to try

**Comment by JohnGodgames** [comment]
Yeah these games needs a geometry shaders...

Taken from WIP https://github.com/JayFoxRox/citra/tree/geometry-shader

![mh3 gs debugger](https://cloud.githubusercontent.com/assets/11453507/14066219/191eab70-f444-11e5-9d2e-7790e367bdd9.JPG)
![resi rev gs debugger](https://cloud.githubusercontent.com/assets/11453507/14066223/25b7256a-f444-11e5-8dcd-a2fc4bb7bb99.JPG)

**Comment by tywald** [comment]
@JohnGodgames How were you merging it? When I try it says later when I build that 3 failed. Master works just fine though.

I'm very intrigued to check it out myself.

**Comment by MWFIAE** [comment]
As this is needed for a few games and already seems to be working on the wip version, when will it be officially available?

**Comment by wwylele** [comment]
Should be fixed by #2865 (heard from forums). If there is still issue, feel free to comment here / open a new one.
