### ISSUE TITLE
Pokemon Picross input issue

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#1507]
(I am not a native English speaker. This issue is a little bit hard for me to describe.)
The issue happens when you choose control method to be "Stylus".
### On real console
During the game, you can use D-Pad or Circle Pad to switch between two pattern (solid or "x") to be drawn. That's saying:
 - when you press and hold "Up" on D-Pad, or push up Circle Pad and hold it, you are in "drawing" state and you can fill in grids on the board with stylus
 - when you press and hold "Down" on D-Pad, or push down Circle Pad and hold it, you are in "cross out" state and you can put "x" in the grids. 
 - if you release D-Pad or Circle Pad, you are now in "idle" state, and you can draw nothing with stylus. 

![pic](https://cloud.githubusercontent.com/assets/4592895/13725742/3f17522e-e8b3-11e5-893a-e4ca5c7e52b3.PNG)

An icon is shown at the left up corner of the bottom screen, indicating which state you are in. For example, if you are in "drawing state", the upper red icon will be shining.

### On Citra
Both D-Pad and Circle Pad seem broken. When you push up Circle Pad and hold it, the game responses as if you are not holding it, but pushing it up and releasing it in a high frequency. You can see the icon is not shining normally, but continuously switching between "filling" state and "idle" state. At the same time you can hardly draw anything with stylus (mouse). Similar thing happens to D-Pad.

I don't know if other Picross games have this issue. I only have this one game.

**Comment by wwylele** [comment]
[Log](http://pastebin.com/xaVfnuiy)

**Comment by yuriks** [comment]
This looks like the same issue as #1408. Can you post your information there instead to keep it in one issue?

**Comment by wwylele** [comment]
@yuriks  Ok I pasted it there.
