### ISSUE TITLE
Shovel Knight - Background appears distorted/broken

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#1516]
Using master as of a2024d7. The entire background appears to be broken. Notice the rock on the right is rendered just like on 3DS.

**3DS**
![shovel knight 3ds](https://cloud.githubusercontent.com/assets/17358613/13732721/6bb56904-e95f-11e5-9283-5b1eaab62af8.PNG)
**Citra**
![shovel knight citra](https://cloud.githubusercontent.com/assets/17358613/13732726/75282080-e95f-11e5-859c-1520ad732474.png)
[LOG](https://gist.github.com/Leo626/8615e3120a6200ca1a92)

**Comment by KillzXGaming** [comment]
I don't have this problem, however did when dumping the game on braindump using the cxi file.

**Comment by Kloen** [comment]
@KillzXGaming could u try with latest master? Looks that what you have isn't the latest one. Atleast not the hash ;)

**Comment by KillzXGaming** [comment]
Same thing
http://i.imgur.com/jTugssH.png

Looking at log, mine says the same thing too.

**Comment by Leo626** [comment]
So it's likely because of bad dump. It's a 3ds file. I don't have the game anymore. Will probably close this if no-one else has this problem.
