### ISSUE TITLE
Ace Attorney Dual Destinies - Missing 2D graphics / 3d models

### ISSUE THREAD

**Issue by Punk34** [citra-emu/citra#1521]
Good news, the game now is playable. Bad: a lot of 2d / 3d graphics is missing. The console says: **shader_jit: unhandled instructuon 0x2a (0xae800000)** and **Unknown source op 6**

![01](https://cloud.githubusercontent.com/assets/13983158/13755966/ba31907e-ea2e-11e5-88c7-c995fc9bb345.jpg)
![02](https://cloud.githubusercontent.com/assets/13983158/13755967/ba32932a-ea2e-11e5-9ca7-f3fe9ded249a.jpg)

**Comment by KillzXGaming** [comment]
May have #1498

**Comment by MoochMcGee** [comment]
Sounds like geo shaders m8.

**Comment by anirudh8860** [comment]
How did it became playable? Can anyone tell me?

**Comment by Subv** [comment]
@bunnei Weren't you looking for a game that used Texture3? Here you have it

**Comment by wwylele** [comment]
The `Unknown source op 6`(Texture3-proctex) part should have been fixed, but the graphics is still broken for other reason.

**Comment by wwylele** [comment]
Fixed by #3281 as reported so closing. Feel free to reopen if it is not the case.
