### ISSUE TITLE
SDL2 frontend selects a RGB565 config on Wayland

### ISSUE THREAD

**Issue by linkmauve** [citra-emu/citra#1525]
I just noticed Majora’s Mask was looking quite weird, and apitrace confirmed this was the reason…

Doesn’t seem to happen on X11.

**Comment by bunnei** [comment]
Can you test if adding the following to SDL initialization resolves the issue:

<pre>
SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);
</pre>

**Comment by linkmauve** [comment]
Indeed, that fixes it.  Do we need more than 0 bits of alpha though?

**Comment by bunnei** [comment]
I don't think so, but as far as I can tell, the default is RGBA8888 on other platforms.
