### ISSUE TITLE
WWE All Stars - Broken 2D graphics in menu

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1529]
Tested on latest master https://github.com/citra-emu/citra/commit/9a627aa30b16542eb64115a83dc075055dbabaf4

Images taken from a SW renderer, HW renderer doesn't showed all of the stuff as at SW.

![wwe alstars 1](https://cloud.githubusercontent.com/assets/11453507/13784162/7c2d4ba6-eace-11e5-9983-dafb478f29ba.JPG)

![wwe alstars 2](https://cloud.githubusercontent.com/assets/11453507/13784170/81762bbe-eace-11e5-8f84-921d854bde59.JPG)

![wwe alstars 4](https://cloud.githubusercontent.com/assets/11453507/13784195/a0b7b63c-eace-11e5-96ec-ee0d915641cc.JPG)

![wwe alstars 3](https://cloud.githubusercontent.com/assets/11453507/13784175/85d45c94-eace-11e5-8b05-075551c0911b.JPG)

[LOG](http://pasted.co/4df9be8d)

**Comment by JayFoxRox** [comment]
This does some weird things with its GS. Me and @ds84182 have been starting to look into it.
I'm starting to believe there is no b15 register or it has dual use (assumption at this point is that its set after the first GS invocation).

**Comment by yuriks** [comment]
Years ago when smea was looking into GS on the GPU, we deduced that shader state persists across invocations. That is, all registers keep it's contents from one vertex to the other and can be used to keep state. This might be relevant if you're seeing weird register usage.

**Comment by JayFoxRox** [comment]
Geometry Shaders, using a custom shader(?).
Fixed in https://github.com/JayFoxRox/citra/tree/gs-debugger (needs cleanup)

Still doesn't go ingame and some graphics missing (Depth related?)

**Comment by wwylele** [comment]
Is this fixed?

**Comment by JohnGodgames** [comment]
Yep 

![wwe 1](https://user-images.githubusercontent.com/11453507/30372481-368a9766-987e-11e7-974a-d6394534dfb6.PNG)
![wwe 2](https://user-images.githubusercontent.com/11453507/30372482-368b418e-987e-11e7-8803-9df766f2a9a2.PNG)
