### ISSUE TITLE
Alien on the run - broken 3d characters

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1531]
Propably dupe of #1530

Tested on master https://github.com/citra-emu/citra/commit/9a627aa30b16542eb64115a83dc075055dbabaf4
### 3DS

![large](https://cloud.githubusercontent.com/assets/11453507/13813193/81167310-eb80-11e5-87c5-f92b6bf74b8e.jpg)
### Citra

![alien on the run 1](https://cloud.githubusercontent.com/assets/11453507/13812836/97ac4cc8-eb7e-11e5-9a3e-d799d4c12af1.JPG)
### more screens from scaled resolution

![alien 1](https://cloud.githubusercontent.com/assets/11453507/13813171/520fa29e-eb80-11e5-9a4e-d6cd67a13d3f.JPG)
![alien 2](https://cloud.githubusercontent.com/assets/11453507/13813172/564e7902-eb80-11e5-97cd-36dd8ba9580a.JPG)
### 3DS

![alien on the run 3](https://cloud.githubusercontent.com/assets/11453507/13812952/279982f6-eb7f-11e5-975e-074c3aeeaca5.JPG)
### Citra

![alien on the run 2](https://cloud.githubusercontent.com/assets/11453507/13812843/9e141578-eb7e-11e5-9424-da98ad392f5e.JPG)

REFERENCE VIDEO [HERE](https://www.youtube.com/watch?v=5j3cQ0-SfQo)

**Comment by JayFoxRox** [comment]
Geometry Shaders, using DMP_silhouette.
Fixed in https://github.com/JayFoxRox/citra/tree/gs-debugger (needs cleanup)

**Comment by wwylele** [comment]
Is this fixed?

**Comment by JohnGodgames** [comment]
Yep

![alien 1](https://user-images.githubusercontent.com/11453507/30372765-23196b5c-987f-11e7-9c09-851fa03cda88.PNG)
![alien 2](https://user-images.githubusercontent.com/11453507/30372764-23169f8a-987f-11e7-8c18-ebbab2a4057e.PNG)
