### ISSUE TITLE
Gummy Bears Magical Medallion - Broken graphics ingame

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1532]
Also bottom screen doesn't show anything.It looks as alpha / depth issue to me.

Tested on master https://github.com/citra-emu/citra/commit/9a627aa30b16542eb64115a83dc075055dbabaf4
### 3DS

![gummy bears 3](https://cloud.githubusercontent.com/assets/11453507/13813539/6b72f2c0-eb82-11e5-92d9-dd21737f8360.JPG)
### Citra

![gummy bears 1](https://cloud.githubusercontent.com/assets/11453507/13813448/f541cfcc-eb81-11e5-9969-57e7de474d70.JPG)
### screen from scaled resolution and all possible fixed that was made recently

![gummy bears 2](https://cloud.githubusercontent.com/assets/11453507/13813451/f8fc4fac-eb81-11e5-8a9c-6eee4fd981d6.JPG)

REFERENCE VIDEO [HERE](https://www.youtube.com/watch?v=xcfUI2_04wE)

**Comment by JayFoxRox** [comment]
Might be an insane case of z-fighting. Does #1621 change it?

**Comment by JohnGodgames** [comment]
with #1621 same

**Comment by JayFoxRox** [comment]
I've tested this (very shortly. so read with grain of salt please).
With #1518 and software rasterizer I get similar issues. Hardware renderer (Mesa 11.2 on Intel HD 4000) doesn't draw anything except for the sky. 

apitrace on hardware shows that the Z-Buffer is 1.0 for nearly all the time.
The game operates way too close to the farplane probably.

Z/W examples for this game (values rounded by the Vertex Shader Debugger):
27.4711/27.6753 = 0.992621579531
26.5925/26.7981 = 0.992327814285
(Uses Z-Buffering and scale = -1.0, offset = 0.0)

I think this needs some rounding / precision changes to work.

**Comment by JayFoxRox** [comment]
Suddenly this looks way better than I remembered (using my swrasterizer-fix branch, but still in HW mode. I didn't test master yet). I'll investigate some more later.

**Comment by Subv** [comment]
Is this still an issue?

**Comment by JohnGodgames** [comment]
Still an issue tested on latest https://github.com/citra-emu/citra/commit/f68f37b520c7acaf2fa4d9c948e08c06b60d3555

**now with a spam:**
```
[ 188.937221] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:483: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched.
[ 188.937342] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:483: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched.
[ 188.938522] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:483: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched.
```



![bear](https://cloud.githubusercontent.com/assets/11453507/20459637/63508d68-aec9-11e6-8b11-e49bf3e2539c.PNG)

**Comment by benderscruffy** [comment]
this works in the latest nightly
this can be closed
![gummy](https://user-images.githubusercontent.com/2696404/32987480-3f8a5e80-cd28-11e7-8aeb-570ffecc0ba1.PNG)
