### ISSUE TITLE
Cave Story Broken graphics

### ISSUE THREAD

**Issue by LFsWang** [citra-emu/citra#1533]
![image](https://cloud.githubusercontent.com/assets/7088579/13822909/743e1d02-ebe2-11e5-883c-805fdcd1d558.png)
![image](https://cloud.githubusercontent.com/assets/7088579/13824619/c988049c-ebe9-11e5-864c-b5137e053ecb.png)

Tested on master 96cafbe 55f24e1

But it's well on previous version
![image](https://cloud.githubusercontent.com/assets/7088579/13823234/973e87f0-ebe3-11e5-8701-f7b7ac8be759.png)

Tested on master 9a627aa

On 3DS
https://youtu.be/MwgcMrcpXt4?t=1m20s

full log  http://pastebin.com/JcAHEz63

**update** 
it's fine if close hw renderer
![image](https://cloud.githubusercontent.com/assets/7088579/13824410/df3ea562-ebe8-11e5-89c9-a4452c5909eb.png)
( test default with jit+hw both on )

**Comment by JohnGodgames** [comment]
Caching issues fixed by https://github.com/citra-emu/citra/pull/1436 (build with hw-text-forwarding on the left)

![cave story fixed](https://cloud.githubusercontent.com/assets/11453507/13826138/471a94c6-ebb6-11e5-82a0-1a634f097958.JPG)

**Comment by lioncash** [comment]
`[23:33] <tfarley> can someone close #1533 and #1338? both should have been officially solved by merging texfwd`
