### ISSUE TITLE
Tales of the Abyss / Pac Man Party 3D - wrong screens offsets

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1542]
These two games have the same problem and it's a pretty old issue...
### Tales of the Abyss

![tales of abyss 5](https://cloud.githubusercontent.com/assets/11453507/13865902/b4a245a2-ecb0-11e5-8183-612038ae55f6.JPG)

![tales of abyss 4](https://cloud.githubusercontent.com/assets/11453507/13865903/b95bbba0-ecb0-11e5-8f83-94d4acd5cb34.JPG)

![tales of abyss 1](https://cloud.githubusercontent.com/assets/11453507/13865908/bedb2dea-ecb0-11e5-9c14-9136c4145156.JPG)

![tales of abyss 2](https://cloud.githubusercontent.com/assets/11453507/13865913/d0dd50d6-ecb0-11e5-90a8-721276ded286.JPG)

![tales of abyss 3](https://cloud.githubusercontent.com/assets/11453507/13865917/d93fabd4-ecb0-11e5-8c56-bad55158cd31.JPG)
### Pac Man Party 3D

![pac man party 1](https://cloud.githubusercontent.com/assets/11453507/13865919/def0efca-ecb0-11e5-96f7-639bec98e475.JPG)

![pac man party 2](https://cloud.githubusercontent.com/assets/11453507/13865923/e3f6d2aa-ecb0-11e5-97d5-fc33451bc871.JPG)

![pac man party 3](https://cloud.githubusercontent.com/assets/11453507/13865927/ebe43246-ecb0-11e5-80ed-21a1a3ed3ede.JPG)

**Comment by JayFoxRox** [comment]
I've only taken a look at Pac-Man Party 3D, but:

We have to [handle flags `(crop_input_lines | flip_vertical)` here](https://github.com/citra-emu/citra/blob/master/src/core/hw/gpu.cpp#L170). We already handle `flip_vertical` but `crop_input_lines` is entirely unimplemented in `master`.
(Not sure if 3DS also supports it for TextureCopy)

```
DisplayTriggerTransfer: 0x00046500 bytes from 0x1801c000(256x512)-> 0x183ce430(240x400), dst format 1, flags 0x00001005
DisplayTriggerTransfer: 0x00038400 bytes from 0x18030000(256x512)-> 0x180b4830(240x320), dst format 1, flags 0x00001005
```

The framebuffer is at VA 0x18000000; 256x512 RGBA8
I tried to understand what the crop mode does but figured it's easier / safer to just write a HW-test. However, I'll leave this to somebody else because I don't have particular interest in these games / knowledge about this part of code.

**Comment by yuriks** [comment]
`crop_input_lines` doesn't matter for emulation. (On hardware it needs to *always* be set when your output width is less than the input, otherwise you get bad/skewed output.) It would also not cause the kinds of mis-alignment we see here. The root cause must be something else.

**Comment by Subv** [comment]
As for Pacman's top screen, the game is properly rendering and doing a display transfer to 0x182FB530 (left fb0), but it tells the LCD to draw from 0x18346500, which is right in between the left fb0 and the left fb1, so we're showing parts of both.
I have no idea why it is doing this.

**Comment by benderscruffy** [comment]
still happens on the latest nightly
![pm0](https://user-images.githubusercontent.com/2696404/32987346-e14a5522-cd23-11e7-8f34-fd78935f310b.PNG)
![pm1](https://user-images.githubusercontent.com/2696404/32987347-f0e8894a-cd23-11e7-8dcc-0d16754a6b7d.PNG)

**Comment by Subv** [comment]
Pacman allocates the output framebuffer at 0x18346500, but during the display transfer call it detects that the output dimensions are smaller than the input dimensions and subtracts some value (that is calculated from the input and output dimensions) from the output pointer, yielding 0x182FB530. It also sets a flag in the display transfer when this happens but i was unable to identify which bit it enabled.

I wonder how the PICA actually handles these cases.

**Comment by benderscruffy** [comment]
still happens in the latest nightly
![party](https://user-images.githubusercontent.com/2696404/50622217-84b39600-0f46-11e9-9189-ddd2190ad19b.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2722670/citra_log.zip)

**Comment by mike13dash** [comment]
any progress for this kind of problem?

**Comment by benderscruffy** [comment]
still happens in the latest nightly

**Comment by tywald** [comment]
Currently the issue changed into a black screen and it appears https://github.com/citra-emu/citra/pull/5170 caused that.

**Comment by benderscruffy** [comment]
still an issue
black screen with sound playing

**Comment by mrcmunir** [comment]
the black screen it's only affected by HW renderer 
the wrong screens offsets it's still are present in software too.

**Comment by abyssfan** [comment]
@GPUCode please look at this if you have some time. 😗

**Comment by GPUCode** [comment]
Decompiling the game has confirmed Subv's statement. The game adjusts the output address when it detects the input width is larger than the output width:

<img src="https://github.com/citra-emu/citra/assets/47210458/2110efe6-014a-49e5-9289-1a1a7768b71f.png" width=75% height=75%>

Adjusting the display transfer to reverse this subtraction does indeed fix this game. @Steveice10 has theorized it's related to a hardware quirk when crop_input_lines and flip_vertical flags are used at the same time and the game is trying to compensate for that. We need to write a hw test to confirm this behaviour

![TALES OF THE ABYSS_06 09 23_14 01 34 293](https://github.com/citra-emu/citra/assets/47210458/ec0e8878-b041-42c8-bfd0-227ae98e3260)

**Comment by GPUCode** [comment]
@abyssfan After running some hwtests I have opened PR you can test

**Comment by abyssfan** [comment]
That was fast! Thank you guys for investigating it! The game shows up perfectly now! ❤️


Sadly, the game crashes during the tutorial battle with some "Assertion Failed!". But I guess that should be a separate issue.

**Comment by GPUCode** [comment]
Upload a log file with the crash

**Comment by GPUCode** [comment]
I played through the game a bit and eventually got the crash. It uses geo shaders to render the battle particles but the configuration is weird:
* It doesn't set gs_unit_exclusive_configuration which is presumably required (the first assertion)
* The geo shader is configured in point mode, and only takes 1 input while the vertex shader has 2 outputs, so it's not a multiple of the vshader output

Both cases need hw testing to see what the correct behaviour is
