### ISSUE TITLE
Mario Golf World Tour / Mario Tennis Open - won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1547]
**All of these doesn't show anything and spams with**

```
[  12.373419] Kernel.SVC <Error> core\hle\kernel\shared_memory.cpp:Kernel::SharedMemory::GetPointer:102: memory block id=33 not mapped!
[  12.478593] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
```

**also:**
`[  34.961312] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'GetStartupArgument': port=APT:U, cmd_buff[1]=0x2, cmd_buff[2]=0x1`

**Mario Golf World Tour**

[LOG](http://pastebin.com/fDNrHEGf)

**Mario Tennis Open**

[LOG](http://pastebin.com/f8d3yRPt)

**Comment by KillzXGaming** [comment]
Same error with Luigi's Mansion 2 Dark Moon

**Comment by JamePeng** [comment]
I append APT::GetStartupArgument in #1577 ,but  I don't think any help for this problem!

**Comment by KillzXGaming** [comment]
I guess it isn't a service issue. Most games with this error won't boot.

[  12.373419] Kernel.SVC <Error> core\hle\kernel\shared_memory.cpp:Kernel::SharedMemory::GetPointer:102: memory block id=33 not mapped!

**Comment by wwylele** [comment]
@KillzXGaming I have some games that show this when booting but didn't crash. I figured out the  'id==33' memory block is typically hid shared memory. Games map this memory block few frames  later after booting, and citra often tries update it before mapping and cause this error. I don't think it's essential.

**Comment by wwylele** [comment]
I suspect the unimplemented `GetStepHistory` cause the problem. I will looking into it.

**Comment by mailwl** [comment]
I look at Mario Tennis Open, it stucks on one thread without switch to another threads, when i add forcibly thread switching after some ticks, it starts.
the game veeeery slow, and in japan language (usa rom CTR-P-AGAE), looks like the stucked thred at start try to get language in strange way, but when i forse switch thread, the game uses not filled value.
anyway, the game unplayable because of using giroscope

**Comment by KillzXGaming** [comment]
@mailwl Is this the same for Mario golf as well?

**Comment by mailwl** [comment]
don't know yet, don't have this game

**Comment by mailwl** [comment]
here: https://github.com/mailwl/citra/tree/preemptive
preemptive multithreading (a kind of), it runs Tennis, but not Golf.
game loading is very long (about 5 minutes on my notebook).

golf starts on my other branch with full of changes, don't know yet which need to run golf

**Comment by Subv** [comment]
The 3DS's appcore threading model is cooperative, there's no preempting of threads.
However I think the syscore does allow thread preemption based on some set of rules, but we don't even implement the syscore.

**Comment by mailwl** [comment]
from 3dbrew:
> ARM11 Processor Core	
> Old3DS: ARM11 2x MPCore & 2x VFPv2 Co-Processor 268MHz(~268123480 Hz).
> New3DS: 4x MPCore, 4x VFPv2, able to run up to 804MHz (see below). It also has an optional 2MB L2 cache.
at least 2 threads should run simultaneously.

in mario tennis code:
```
.text:001003D4                 LDR             R0, =thread_data
.text:001003D8                 STR             R4, [R11,#(dword_4F8CF0 - 0x4F8CB8)]
.text:001003DC                 BL              create_and_run_stuck_thread ; waits while thread_data[0x1c] == 1
.text:001003E0                 ADR             R1, aSjis ; "SJIS"
.text:001003E4                 MOV             R0, #0x1F
.text:001003E8                 BL              sub_316FA0
```
citra never return to .text:001003E0, and thread_data[0x1C] never changes

**Comment by mailwl** [comment]
hmm... adding `HLE::Reschedule(__func__);` to `Thread::SetPriority` switches threads (waiting thread set the lowest priority to itself).
both variants is crutch

**Comment by Subv** [comment]
@mailwl Applications (games) can not be scheduled in the syscore (Core 1) unless they explicitly request it (by calling APT::SetAppCPUTimeLimit) and specifying the THREADPROCESSORID_1 flag in the svcCreateThread call.
However, a thread that can run on the syscore should run on it every now and then (We don't really know what scheduling behavior this thread has, we only know it's preemptive and possibly time-slice based) so that's a bug we currently have.

**Comment by Subv** [comment]
@mailwl Could you (or anybody) please test this commit https://github.com/Subv/citra/commit/9ae5b188b3e8e2136ca9436b812d7ed9a292f653 on this game and see if warns about the processor id? Thanks

**Comment by mailwl** [comment]
no warnings.
where to read about syscore? what for is it? what for arm9 processor?

**Comment by yuriks** [comment]
The "SysCore" is the 2nd core of the ARM11. I'm not sure if there's anywhere to read more details about it, though.

**Comment by JohnGodgames** [comment]
Mario Tennis Open boots with https://github.com/citra-emu/citra/pull/1689

**Comment by benderscruffy** [comment]
can this be reopened up again as these two games won't boot again
nothing but black screens
[Debug log.zip](https://github.com/citra-emu/citra/files/1550589/Debug.log.zip)

**Comment by wwylele** [comment]
@benderscruffy could you open a new issue please? Because it can be a different problem and we need a new log.

**Comment by benderscruffy** [comment]
i did a new log in my post
