### ISSUE TITLE
Add Save Manager to Frontend for Easier Save Importing and Exporting

### ISSUE THREAD

**Issue by KillzXGaming** [citra-emu/citra#1553]
Here is an enhancement I would like added, sorry if this is posted in wrong place
How this would work:

**Option 1:**
Have a window that opens and searches all low title IDs in the saves folder and gives the title according to the title ID, right clicking game would give options to import and export save. 

**Option 2:**
Add the ability to right click a game on the game list by maybe reading the rom's header and import/export the save as the header includes game's title ID. 

When importing/exporting data, you would import/export the data folder as every save is located in one. 

This is just an idea, sorry if I'm putting out any impossible or ignorant solutions.

**Comment by Leo626** [comment]
Should this be closed now that #2322 is merged?
