### ISSUE TITLE
Undead Storm Nightmare / Undead Bowling- Hangs while saving

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1555]
Tested with https://github.com/citra-emu/citra/commit/b83e95727f95fa6fe35d436be3e821605244a6a8

Both of games are related to this issue for sure.It's an older issue and it's also a regression (lazy to search which commit killed it or what's wrong).

**Undead Storm Nightmare**
![undead storm 1](https://cloud.githubusercontent.com/assets/11453507/13909538/7e35ecfa-ef15-11e5-90b4-729305e4e845.JPG)

[LOG](http://pastebin.com/n3s6WjkE)

**UndeadBowling**

![undead bowling 1](https://cloud.githubusercontent.com/assets/11453507/13909609/776f890c-ef16-11e5-8b90-9ba754e6c821.JPG)

[LOG](http://pastebin.com/fMgdCSpv)

**Comment by Subv** [comment]
````
[  55.259661] Service.FS <Info> core\file_sys\archive_sdmc.cpp:FileSys::ArchiveFactory_SDMC::ArchiveFactory_SDMC:21: Directory N:\CITRA VS2015/user/sdmc/ set as SDMC.
[  55.259896] Service.FS <Warning> core\file_sys\archive_sdmc.cpp:FileSys::ArchiveFactory_SDMC::Initialize:26: SDMC disabled by config.
[  55.260124] Service.FS <Error> core\hle\service\fs\archive.cpp:Service::FS::ArchiveInit:528: Can't instantiate SDMC archive with path N:\CITRA VS2015/user/sdmc/
````
Please enable your SDMC archive and try again.

**Comment by JohnGodgames** [comment]
Undead Storm Nightmare: https://github.com/citra-emu/citra/commit/cf5b8483fc53ca3b4919d231045348625a507d05  -  [LOG](http://pastebin.com/hrSnJnec
)
Undead Bowling (Won't boot anymore): https://github.com/citra-emu/citra/commit/cf5b8483fc53ca3b4919d231045348625a507d05  -  [LOG](http://pastebin.com/wbign7jN
)

**Comment by Subv** [comment]
Does this still happen?

**Comment by JohnGodgames** [comment]
Tested on https://github.com/citra-emu/citra-nightly/commit/b36677daff771d4791f3b13e0d7cb95f4b0b47f6 and both games are working
