### ISSUE TITLE
Horribly slow video playback in certain games - y2r 

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1557]
**Known affected games:**
- Teenage Mutant Ninja Turtles [LOG](http://pastebin.com/zrcrhzs6)
- The Smurfs [LOG](http://pasted.co/19a22079)

**Spams with:**

```
[  35.809630] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'IsFinishedSendingV': port=y2r:u
[  35.810294] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'IsFinishedReceiving': port=y2r:u
```

**Comment by archshift** [comment]
Slow video decoding/playback is probably due to relatively slow CPU emulation. A JIT should help with this.

**Comment by yuriks** [comment]
Yeah, this doesn't actually have anything to do with y2r. Videos are decoded using the CPU and that's the slow part right now. I'll close this since it's just a general "CPU is slow" thing.
