### ISSUE TITLE
Thor God of Thunder - Hangs at ingame while saving

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1558]
![thor](https://cloud.githubusercontent.com/assets/11453507/13910177/4aa6c50e-ef1e-11e5-907b-a7c9e979ade1.JPG)

```
[ 188.958488] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::IsDirectory:112: stat failed on N:\CITRA VS2015/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00040500/data/00000001///save1.sav: SystÚm nem¨×e nalÚzt uvedenř soubor.

[ 188.958984] Service.FS <Error> core\file_sys\disk_archive.cpp:FileSys::DiskFile::Open:118: Non-existing file N:\CITRA VS2015/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00040500/data/00000001///save1.sav can't be open without mode create.
[ 188.959551] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFile:75: failed to get a handle for file [Wchar: //save1.sav]
[ 188.960180] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::IsDirectory:112: stat failed on N:\CITRA VS2015/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00040500/data/00000001///save2.sav: SystÚm nem¨×e nalÚzt uvedenř soubor.

[ 188.960558] Service.FS <Error> core\file_sys\disk_archive.cpp:FileSys::DiskFile::Open:118: Non-existing file N:\CITRA VS2015/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00040500/data/00000001///save2.sav can't be open without mode create.
[ 188.961107] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFile:75: failed to get a handle for file [Wchar: //save2.sav]
```

[LOG](http://pasted.co/54cc07c4)

**Comment by Subv** [comment]
There was a big change to how we handle archives recently, could you please re-test this?

**Comment by JohnGodgames** [comment]
I can't pass a title screen for first time boot - https://github.com/citra-emu/citra/commit/cf5b8483fc53ca3b4919d231045348625a507d05  -  [LOG](http://pastebin.com/qetSNSWQ)

Next time boot hangs at ingame while saving...so it's the same [LOG](http://pastebin.com/uwVRGRhC)

**Comment by Subv** [comment]
Does this still happen?

**Comment by JohnGodgames** [comment]
Tested on https://github.com/citra-emu/citra-nightly/commit/b36677daff771d4791f3b13e0d7cb95f4b0b47f6 and still persist

**Comment by benderscruffy** [comment]
still happens on the latest nightly and canary
![thor](https://user-images.githubusercontent.com/2696404/33226776-0bc389bc-d1d0-11e7-8389-db01415503d9.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1502777/log.zip)

**Comment by JohnGodgames** [comment]
Fixed already.

<img width="439" alt="thor" src="https://user-images.githubusercontent.com/11453507/38705338-86e2ad80-3ea9-11e8-8bae-8e380624943a.PNG">
