### ISSUE TITLE
.CIA/DLC Files loading in future?

### ISSUE THREAD

**Issue by bhsupreme** [citra-emu/citra#1565]
Will this ever happen as I am interested in loading dlc/.cia files for fire emblem: awakening. Some games have glitches that are not from the emulator but from the game itself but was patched in an update/.cia file. Thanks if you do add this.

**Comment by Zetchzie** [comment]
this would be nice

**Comment by Punk34** [comment]
Don't think that this is possible in the near future, it requires much more extensive OS emulation.

**Comment by yuriks** [comment]
.cia files are archives, we probably wouldn't support that but would use the unpacked patch title instead. I think the semantics of this aren't that complex, but for it to be usable we would indeed need much more complete OS emulation of the title system. I wouldn't count on this happening for a while.

**Comment by Thealexbarney** [comment]
Assuming the CIA is already decrypted, it seems simple enough in the general case to read the TMD to get the offset and size of the first content, and read that as a CXI

**Comment by mailwl** [comment]
@yuriks btw, ncch has archived code section as well )))
hmm... i don't care about cia at all, but dlc... make sense

**Comment by MWFIAE** [comment]
I really would wish for cia's as most of the games I have backed up are cia's as only that can be installed directly on the 3ds with fbi

**Comment by Demos25** [comment]
@MWFIAE Just decrypt this CIA on your 3DS and extract CXI using ctrtool

**Comment by MWFIAE** [comment]
Yeah I know of this "workaround". 
I may be mistaken, but I always thought that doing this would take really long ( 2h per game) on my o3ds. 
And as there isn't really a reason why cias should not be directly supported by citra I think it should be supported.

**Comment by Thealexbarney** [comment]
@MWFIAE There's currently no way (or at least no public method) to decrypt 3DS content without using an actual 3DS.

**Comment by mailwl** [comment]
xorpads? or they only for .3ds?

**Comment by MWFIAE** [comment]
Any news on that? 
As we have now the bootroms we should be able to decrypt everything, right? :)

**Comment by Demos25** [comment]
decrypting is not the problem here

**Comment by mailwl** [comment]
i remember pr for cia loader. dlc completly nothing

**Comment by MWFIAE** [comment]
> decrypting is not the problem here

Well what exactly is the problem then?

**Comment by Subv** [comment]
Since CIAs can now be installed directly, I'd say this issue is now resolved.

**Comment by candrapersada** [comment]
how to `https://www.3dscia.com` for citra?
