### ISSUE TITLE
Harvest Moon: The Land's Origins```Cannot enter the name

### ISSUE THREAD

**Issue by louts** [citra-emu/citra#1569]
Below the screen stuck

**Comment by wwylele** [comment]
Please paste the log here

**Comment by louts** [comment]
2 @ 0x000FFDAC
[ 114.345278] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDB0
[ 114.345364] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDB4
[ 114.345445] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDB8
[ 114.345522] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDBC
[ 114.345597] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDC0
[ 114.345673] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDC4
[ 114.345749] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDC8
[ 114.345824] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDCC
[ 114.345900] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDD0
[ 114.345975] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDD4
[ 114.346053] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDD8
[ 114.346130] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDDC
[ 114.346206] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDE0
[ 114.346281] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDE4
[ 114.346357] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDE8
[ 114.346432] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDEC
[ 114.346527] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDF0
[ 114.346603] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDF4
[ 114.346678] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDF8
[ 114.346756] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFDFC
[ 114.346832] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE00
[ 114.346907] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE04
[ 114.346983] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE08
[ 114.347058] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE0C
[ 114.347143] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE10
[ 114.347235] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE14
[ 114.347314] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE18
[ 114.347389] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE1C
[ 114.347465] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE20
[ 114.347540] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE24
[ 114.347614] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE28
[ 114.347690] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE2C
[ 114.347764] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE30
[ 114.347840] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE34
[ 114.347915] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE38
[ 114.347990] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE3C
[ 114.348065] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE40
[ 114.348146] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE44
[ 114.348222] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE48
[ 114.348298] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE4C
[ 114.348373] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE50
[ 114.348448] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE54
[ 114.348525] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE58
[ 114.348601] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE5C
[ 114.348676] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE60
[ 114.348751] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE64
[ 114.348826] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE68
[ 114.348901] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE6C
[ 114.348977] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE70
[ 114.349051] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE74
[ 114.349130] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE78
[ 114.349206] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE7C
[ 114.349281] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE80
[ 114.349356] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE84
[ 114.349431] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE88
[ 114.349506] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE8C
[ 114.349581] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE90
[ 114.349656] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE94
[ 114.349733] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE98
[ 114.349809] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFE9C
[ 114.349884] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEA0
[ 114.349959] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEA4
[ 114.350034] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEA8
[ 114.350118] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEAC
[ 114.350195] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEB0
[ 114.350271] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEB4
[ 114.350346] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEB8
[ 114.350422] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEBC
[ 114.350497] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEC0
[ 114.350572] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEC4
[ 114.350647] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEC8
[ 114.350761] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFECC
[ 114.350836] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFED0
[ 114.350912] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFED4
[ 114.350989] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFED8
[ 114.351064] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEDC
[ 114.351153] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEE0
[ 114.351233] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEE4
[ 114.351309] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEE8
[ 114.351384] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEEC
[ 114.351460] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEF0
[ 114.351535] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEF4
[ 114.351610] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEF8
[ 114.351685] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFEFC
[ 114.351761] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF00
[ 114.351836] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF04
[ 114.351911] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF08
[ 114.351986] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF0C
[ 114.352061] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF10
[ 114.352146] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF14
[ 114.352225] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF18
[ 114.352301] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF1C
[ 114.352376] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF20
[ 114.352451] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF24
[ 114.352526] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF28
[ 114.352602] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF2C
[ 114.352677] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF30
[ 114.352752] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF34
[ 114.352827] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF38
[ 114.352902] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF3C
[ 114.352977] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF40
[ 114.353052] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF44
[ 114.353161] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF48
[ 114.353266] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF4C
[ 114.353342] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF50
[ 114.353418] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF54
[ 114.353495] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF58
[ 114.353571] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF5C
[ 114.353646] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF60
[ 114.353721] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF64
[ 114.353796] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF68
[ 114.353871] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF6C
[ 114.353967] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF70
[ 114.354043] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF74
[ 114.354121] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF78
[ 114.354198] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF7C
[ 114.354274] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF80
[ 114.354349] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF84
[ 114.354424] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF88
[ 114.354498] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF8C
[ 114.354574] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF90
[ 114.354649] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF94
[ 114.354726] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF98
[ 114.354801] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFF9C
[ 114.354876] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFA0
[ 114.354951] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFA4
[ 114.355026] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFA8
[ 114.355108] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFAC
[ 114.355220] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFB0
[ 114.355297] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFB4
[ 114.355373] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFB8
[ 114.355448] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFBC
[ 114.355523] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFC0
[ 114.355599] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFC4
[ 114.355674] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFC8
[ 114.355749] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFCC
[ 114.355843] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFD0
[ 114.355918] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFD4
[ 114.355996] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFD8
[ 114.356071] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFDC
[ 114.356178] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFE0
[ 114.356256] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFE4
[ 114.356331] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFE8
[ 114.356406] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFEC
[ 114.356481] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFF0
[ 114.356556] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFF4
[ 114.356630] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFF8
[ 114.356705] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x000FFFFC
[ 114.362946] HW.Memory <Error> core\memory.cpp:Memory::Write:163: unmapped Writ
e32 0x00000000 @ 0x00000000
