### ISSUE TITLE
Majoras Mask Circle Pad Pro Issue

### ISSUE THREAD

**Issue by turkeynaruto** [citra-emu/citra#1574]
How can I bypass the Circle Pad Pro Issue ? 
Can someone give me a Savegame which disabled it or how can I disable it ?
Pls its my favorite game and even when it will run slow I would play/test it.

**Comment by JayFoxRox** [comment]
This is not a support forum. Please ask those kind of questions in https://discuss.citra-emu.org/
That being said: Wait until Citra works better and until "Majoras Mask" is finally fully supported.

**Comment by turkeynaruto** [comment]
Oh sry I didnt knew that.
