### ISSUE TITLE
Cannot load any game

### ISSUE THREAD

**Issue by GTO888** [citra-emu/citra#1575]
my PC is.. windows ( 8.1  64 Bit ).. RAM 8.. i,m sure that it can handle citra emulater
when i press load files in the option..directly it shows to me that the citra emulator stop working  !!!???
anyone can help plz !

**Comment by MoochMcGee** [comment]
Learn English. Then we'll talk, because I can't understand half of what you're saying.

**Comment by archshift** [comment]
Sorry, this issue tracker isn't a help forum.
