### ISSUE TITLE
Professor Layton and the Miracle Mask - Freezing after first cutscenes

### ISSUE THREAD

**Issue by itstake** [citra-emu/citra#1578]
Game is fully working before "Enter your name" Screen.

but if I skip movie. It freezes
![cap 2016-03-27 19-17-53-045](https://cloud.githubusercontent.com/assets/5001353/14064949/d6322352-f450-11e5-9678-a96ff7af2014.jpg)
This screen.

and if I watch movie without skip. It freezes
![cap 2016-03-27 18-57-22-260](https://cloud.githubusercontent.com/assets/5001353/14064953/eecbf370-f450-11e5-9dd5-8ede4c9515f0.jpg)
this. and citra logs
![image](https://cloud.githubusercontent.com/assets/5001353/14064965/51641134-f451-11e5-9b4b-15559aeca1fb.png)
both logs are same.

(so sorry for bad english)

**Comment by JohnGodgames** [comment]
Issue  already posted https://github.com/citra-emu/citra/issues/1040
