### ISSUE TITLE
Girls Mode 3 - Black Screen

### ISSUE THREAD

**Issue by exhalatio** [citra-emu/citra#1579]
Tested with e366f60cff290d76cf0876dcf7d07240dae0d12d

Correct graphics is generated in framebuffer.
However, main screen is always Black.
![gm3](https://cloud.githubusercontent.com/assets/7089513/14065405/9f898b9e-f462-11e5-9a23-ce9de4260a96.jpg)

LOG
https://mega.nz/#!98BDVRBJ!xbbvpGvG1BIO4pnTL7-8Y9jfHgLLRolK5o3O5x3xd-g

**Comment by mailwl** [comment]
hm... same MH3U. Maybe drawing outside window?

**Comment by JayFoxRox** [comment]
Maybe AA using fullscreen blit or what you see is only something like a reflection or refraction map.
Should be tested with GS or depth testing disabled.

**Comment by exhalatio** [comment]
Doesn't help geometry shaders WIP https://github.com/JayFoxRox/citra/tree/geometry-shader
and Reverted #1462

**Comment by exhalatio** [comment]
Fixed in 38f4c9c
![gm3](https://cloud.githubusercontent.com/assets/7089513/14442919/39b2a49c-0077-11e6-8c0e-7e076b1d50b2.jpg)
