### ISSUE TITLE
Games that still hangs while OS Software Keyboard should appear

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1583]
**Zoo Resort 3D**

![zoo 2](https://cloud.githubusercontent.com/assets/11453507/14069269/00e4e4ee-f498-11e5-8628-fd16b34eeba4.JPG)

![zoo](https://cloud.githubusercontent.com/assets/11453507/14069249/c83e600c-f497-11e5-85b5-c9f16c034222.JPG)

[LOG](http://pastebin.com/JdtzJ35y)

**Harvest Moon 3D A New Beginning**

reference [video](https://www.youtube.com/watch?v=i5XbZHzOQxc&list=PLMfPU_BxnPBaiCUeaxyf-r-cQG1auezxv)

![harvest](https://cloud.githubusercontent.com/assets/11453507/14069347/c30006e4-f498-11e5-8bb2-40850e302787.JPG)

[LOG](http://pastebin.com/8XuzqeVb)

**Comment by wwylele** [comment]
#1577 helps？

**Comment by JohnGodgames** [comment]
#1577 not helped

**Comment by KillzXGaming** [comment]
Doesn't monster hunter 3 also use OS software keyboard?

**Comment by tywald** [comment]
@KillzXGaming It does.

![dsc_0463](https://cloud.githubusercontent.com/assets/10337060/14090527/456b6266-f53b-11e5-9500-6a68711a2c35.JPG)
![dsc_0464](https://cloud.githubusercontent.com/assets/10337060/14090528/457000d2-f53b-11e5-9286-125d8890c8e0.JPG)

**Comment by mailwl** [comment]
i think, the reason, why games hangs is wrong id of confirm key (see on first only one button - OK, on the last screenshot - two, Cancel/OK)

**Comment by wwylele** [comment]
@mailwl You've guessed right. **Zoo Resort 3D** passes software keyboard with [return code](https://github.com/citra-emu/citra/blob/master/src/core/hle/applets/swkbd.cpp#L80) changed to 0.
However, this doesn't apply to **Harvest Moon 3D A New Beginning**, which seems to hang by other issue.

**Comment by FunctionsCome** [comment]
I guess no way to fix Harvest Moon?

**Comment by benderscruffy** [comment]
using the latest nightly and canary
Zoo Resort 3D and Harvest Moon 3D A New Beginning both still have the same problems 
cannot pass the name screen
