### ISSUE TITLE
Star Fox 64 - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1590]
```
[   0.386587] HW.Memory <Error> core\memory.cpp:Memory::Write:163: unmapped Write32 0x00000000 @ 0x00000028
[   0.386932] HW.Memory <Error> core\memory.cpp:Memory::Write:163: unmapped Write8 0x00000000 @ 0x00000039
[   0.387206] HW.Memory <Error> core\memory.cpp:Memory::Write:163: unmapped Write8 0x00000000 @ 0x00000038
[   0.387431] HW.Memory <Error> core\memory.cpp:Memory::Write:163: unmapped Write8 0x00000000 @ 0x0000003A
[   0.387659] HW.Memory <Error> core\memory.cpp:Memory::Write:163: unmapped Write32 0x00000000 @ 0x0000003C
```

[LOG](http://pasted.co/4dcdbd77)

**Comment by KillzXGaming** [comment]
This causes the HW errors
[   4.653141] HW.Memory <Error> core\memory.cpp:Memory::GetPointer:182: unknown GetPointer @ 0xfffffffc

Many games seem to get a similar unknown getpointer error like hyrule warriors legends.

**Comment by mailwl** [comment]
[ 4.653141] HW.Memory core\memory.cpp:Memory::GetPointer:182: unknown GetPointer @ 0xfffffffc

this error not related to games, it's bug in first callstack getting
https://github.com/citra-emu/citra/blob/master/src/citra_qt/debugger/callstack.cpp#L41

**Comment by KillzXGaming** [comment]
Latest master now does not give those memory errors, however now shows unimplemented functions. 
http://i.imgur.com/Uv1DM2T.png

[LOG](http://pastebin.com/

**Comment by KillzXGaming** [comment]
Could be labeled as an audio issue. Fails to load DSP although unsure if this causes game not to boot as i haven't seen any other game do this.

**Comment by mailwl** [comment]
UnloadComponent is not a reason, because LoadComponent just stubbed (After Unload - LoadComponent again)

**Comment by JohnGodgames** [comment]
It's booting now, but there is another issue with save data...

**Comment by CubertZ** [comment]
I'm getting the same error : HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write32 0x00000000 @ 0x0000B290
any solution ?

**Comment by Papermanzero** [comment]
Issue is still present
