### ISSUE TITLE
Puzzle & Dragons Z + Puzzle & Dragons Super Mario Bros. Edition - hangs

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1592]
After I've clicked to an A button, black screen appears and spams only:

```
[   2.940975] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:405: Emulated program broke execution!
[   2.941976] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:413: Break reason: PANIC
```

![puzzle dragon](https://cloud.githubusercontent.com/assets/11453507/14077427/a893fbf0-f4eb-11e5-8253-1d50d24ad2e6.JPG)

[LOG](http://pasted.co/829f04fc)

**Comment by exhalatio** [comment]
<CODE>[   1.888002] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'LoadExeCRO_New?': port=ldr:ro, cmd_buff[1]=0x801F000, cmd_buff[2]=0x309000, cmd_buff[3]=0x101000, cmd_buff[4]=0x81206A0, cmd_buff[5]=0x0, cmd_buff[6]=0x327C, cmd_buff[7]=0x812391C, cmd_buff[8]=0xA59F0, cmd_buff[9]=0xFFFFD01, cmd_buff[10]=0x1, cmd_buff[11]=0x0, cmd_buff[12]=0x0, cmd_buff[13]=0xFFFF8001></CODE>
Maybe a CRO issue?

**Comment by JayFoxRox** [comment]
Is this still an issue?

**Comment by wwylele** [comment]
already resolved
