### ISSUE TITLE
Puppies 3D - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1594]
Maybe related to https://github.com/citra-emu/citra/issues/1556

[LOG](http://pasted.co/afa04dd2)

**Comment by mailwl** [comment]
#1647 fix it

**Comment by Subv** [comment]
#1647 was merged, is this still an issue?

**Comment by JohnGodgames** [comment]
It's broken again with something else...break reason panic.I will update issue later

**Comment by mailwl** [comment]
@JohnGodgames check please the game on latest master again, it works for me

**Comment by JohnGodgames** [comment]
It's working...closing
