### ISSUE TITLE
My Pet Puppy 3D - Graphical bug at HW renderer

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1598]
SW:

![my pet 3 sw](https://cloud.githubusercontent.com/assets/11453507/14078106/1e66c5ea-f4f3-11e5-84cd-8d39492c8707.JPG)

![my pet 4 sw](https://cloud.githubusercontent.com/assets/11453507/14078110/2371d0ca-f4f3-11e5-85f8-09ad9be93963.JPG)

HW:

![my pet 1](https://cloud.githubusercontent.com/assets/11453507/14078099/0c8a1322-f4f3-11e5-8c15-6460c73a39d0.JPG)

![my pet 2](https://cloud.githubusercontent.com/assets/11453507/14078103/181d4196-f4f3-11e5-8bcb-aa15b788b3d3.JPG)

**Comment by JayFoxRox** [comment]
Probably depth clipping in HW or lighting affecting the skybox.
We shouldn't worry too much about this for now. My w-buffer branch *might* be able to fix it soon.

**Comment by JayFoxRox** [comment]
Test with #1621 please

**Comment by JohnGodgames** [comment]
Fixed with #1621
