### ISSUE TITLE
Moon Chronicles - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1599]
[LOG](http://pasted.co/9e2b744d)

**Comment by JohnGodgames** [comment]
Game needs a geometry shaders to show stuff so it's related to https://github.com/citra-emu/citra/issues/1498

**with JayFoxRox's GS WIP:**

![moon 1](https://cloud.githubusercontent.com/assets/11453507/20236978/37d3328e-a8c6-11e6-8d0d-8139374dc604.PNG)


![moon](https://cloud.githubusercontent.com/assets/11453507/20236971/0e08c3f6-a8c6-11e6-8fb5-9fe517fc07ea.PNG)

**Comment by wwylele** [comment]
Is this fixed?

**Comment by JohnGodgames** [comment]
Yep

![moon 1](https://user-images.githubusercontent.com/11453507/30372944-eb255cfa-987f-11e7-8183-582094500740.PNG)
![moon 2](https://user-images.githubusercontent.com/11453507/30372943-eb245206-987f-11e7-934b-2e3749d61ea1.PNG)
