### ISSUE TITLE
Lost Heroes 1 and 2 - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1601]
Propably related to https://github.com/citra-emu/citra/issues/1556

**Lost Heroes**
[LOG](http://pasted.co/78c764b4)

**Lost Heroes 2**
[LOG](http://pasted.co/96a18b0f)

**Comment by mailwl** [comment]
to pass endless loop, you have to change 
https://github.com/citra-emu/citra/blob/master/src/core/hle/svc.cpp#L862

with this line:
`*out = (process->heap_used + process->linear_heap_used + process->misc_memory_used) & 0xFFFFFFFFFFFFF000ull;`

(it works at least in LH1). I think, it's aligning stuff or something like that (last 3 bytes must be 0)

**Comment by mailwl** [comment]
to pass second stuck, you hate to implement ac:u::CloseAsync function, for example, in such way:
```c++
static void CloseAsync(Service::Interface* self) {
    u32* cmd_buff = Kernel::GetCommandBuffer();
    auto evt = Kernel::g_handle_table.Get<Kernel::Event>(cmd_buff[4]);
    if (evt) {
        evt->name = "AC_U:close_event";
        evt->Signal();
    }
    cmd_buff[1] = RESULT_SUCCESS.raw; // No error
    LOG_WARNING(Service_AC, "(STUBBED) called");
}
```

**Comment by Subv** [comment]
#1647 was merged, is this still an issue?

**Comment by JohnGodgames** [comment]
It's broken again with something else...break reason panic.I will update issue later

**Comment by JohnGodgames** [comment]
It works on latest master so I'm closing it...
