### ISSUE TITLE
Kid Icarus Uprising - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1603]
`[   2.056845] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function '0x00010082': port=boss:U, cmd_buff[1]=0x0, cmd_buff[2]=0x0, cmd_buff[3]=0x20, cmd_buff[4]=0x0`

[LOG](http://pasted.co/f084e732)

**Comment by deadair3210** [comment]
Unless I'm mistaken, errors with BOSS are caused by SpotPass not being implemented yet. The game probably tries to check if its SpotPass handler is installed and fails because its waiting for a certain reply that it never gets

**Comment by mailwl** [comment]
the reason: game can't load SharedFont.
apt:GetSharedFont try to MapMemoryBlock, but failed, because memory block already allocated (by game?)
in log we can see:
[  11.306515] Kernel.SVC <Debug> core\hle\svc.cpp:SVC::ControlMemory:77: called operation=0x00010003, addr0=0x00000000, addr1=0x00000000, size=0x5F0C000, permissions=0x00000003
[  11.351105] HW.Memory <Debug> core\memory.cpp:Memory::MapPages:83: Mapping 000001E48CFFE080 onto 14000000-19F0C000
[  11.352252] HW.Memory <Debug> core\memory.cpp:Memory::MapPages:83: Mapping 000001E48CFFE080 onto 14000000-19F0C000

shared font starts from 0x18000000

**Comment by mailwl** [comment]
ah, forgot to mention, even if we copy shared font by hand, later game crash:

[ 336.655992] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFileDirectly:119: failed to get a handle for archive archive_id=0x2345678A archive_path=[Binary: 020201009b00040000ffffff02000000]
[ 336.657331] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:108: Fatal error!
[ 336.657902] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:116: PID: 0x00000000_0x00000000
[ 336.659152] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:117: REV: 44677
[ 336.659603] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:118: AID: 0x00000000_0x00000000
[ 336.660029] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:119: ADR: 0x002F3940
[ 336.660420] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:121: RSL: 0xFFFFFFFF
[ 336.662008] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:122:   Level: 31
[ 336.662433] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:123:   Summary: 63
[ 336.662844] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:124:   Module: 255
[ 336.663235] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:125:   Desc: 1023

**Comment by wwylele** [comment]
@mailwl you need some files dumped from 3ds.

**Comment by mailwl** [comment]
@wwylele, thanks, you right, i forgot to copy files.
to quick fix this game, need to change code at lines:
https://github.com/citra-emu/citra/blob/master/src/core/hle/service/apt/apt.cpp#L81-L83

with this:
```
        auto vma = Kernel::g_current_process->vm_manager.MapMemoryBlock(shared_font_mem->fixed_address,
                shared_font, 0, shared_font_mem->size, Kernel::MemoryState::Shared);

        if(vma.Code() == Kernel::ERR_INVALID_ADDRESS_STATE) { // already initialized
            memcpy(Memory::GetPointer(SHARED_FONT_VADDR), &(*shared_font)[0], shared_font->size());
        }
        }
```
it's just hack, need right way to fix this situation
