### ISSUE TITLE
JAWS Ultimate Predator - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1604]
[LOG](http://pasted.co/a4968ba8)

**Comment by mailwl** [comment]
looks like it can't load font romfs:/Fonts/nintendo.bcfnt

**Comment by Subv** [comment]
Does this still happen?

**Comment by mailwl** [comment]
yes, tryed to access about address-zero memory

**Comment by Subv** [comment]
@mailwl Please provide a log

**Comment by Subv** [comment]
Does this still happen?

**Comment by JohnGodgames** [comment]
Tested on https://github.com/citra-emu/citra-nightly/commit/b36677daff771d4791f3b13e0d7cb95f4b0b47f6 and still persist

**Comment by benderscruffy** [comment]
still happens
![jaws](https://user-images.githubusercontent.com/2696404/32705713-f95edd8a-c851-11e7-94fa-7bccd3ddc181.PNG)

**Comment by Hexagon12** [comment]
@benderscruffy Could you upload a new log file, please?

**Comment by benderscruffy** [comment]
ok
[log.zip](https://github.com/citra-emu/citra/files/1466640/log.zip)

**Comment by Hexagon12** [comment]
Does this happen with #3091 merged? (aka that PR is merged in Canary)

**Comment by benderscruffy** [comment]
yes it work in #3091

**Comment by benderscruffy** [comment]
this can be closed now  as it works in the latest nightly
![jaws](https://user-images.githubusercontent.com/2696404/33811673-14f2ae54-de51-11e7-93a4-b5f36272aa69.PNG)
