### ISSUE TITLE
Ice Age: Continental Drift - Arctic Games - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1605]
Propably related too https://github.com/citra-emu/citra/issues/1556

[LOG](http://pasted.co/56b5badd)

**Comment by mailwl** [comment]
#1647 fix it, but then game stuck on team select

**Comment by Subv** [comment]
#1647 was merged, is this still an issue?

**Comment by JohnGodgames** [comment]
It's broken again with something else...break reason panic.I will update issue later

**Comment by JohnGodgames** [comment]
It works on latest master so I'm closing it...
