### ISSUE TITLE
Batman Arkham Origins Blackgate - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1610]
[LOG](http://pasted.co/872a0556)

**Comment by RavenHome1** [comment]
maybe a cro issue?

**Comment by wwylele** [comment]
@RavenHome1 If it were about CRO, the log would say something about 'LoadExeCro'

**Comment by KillzXGaming** [comment]
Isn't this same as #1547? Both have same error where GSP event cannot be created.

**Comment by mailwl** [comment]
@JohnGodgames , try #1613
it shows intro now, but later back screen, maybe geometry shaders, like MH3U and others, don't know...

**Comment by JohnGodgames** [comment]
Yep #1613 helps

![batman](https://cloud.githubusercontent.com/assets/11453507/14126620/97c0e180-f612-11e5-9b32-2b9c85959cd9.JPG)

**Comment by bunnei** [comment]
Should this be closed?
