### ISSUE TITLE
It says that the program can't start because MSVCP140.dll is missing from my computer.... What is MSVCP140.dll and how can I fix this?

### ISSUE THREAD

**Issue by TheHeroJay** [citra-emu/citra#1614]

**Comment by tywald** [comment]
Have you installed runtime?

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by tywald** [comment]
Have you tried with different browsers?

**Comment by MerryMage** [comment]
Needs to be vc_redist.x64.exe fwiw.

**Comment by archshift** [comment]
Sorry, this issue tracker is not a help forum. Try the Citra forums next time (even though you got your answer this time).
