### ISSUE TITLE
cannot load games

### ISSUE THREAD

**Issue by GTO888** [citra-emu/citra#1617]
anyone know what is mean of this ?
i,m sure the ( legend of zelda ) rom is decrypt but when i try harvest moon new beginning it worked but lagging
i don,t now why it is not work ???
anyone can help
![ih](https://cloud.githubusercontent.com/assets/18095162/14132355/b10e3a98-f5e0-11e5-99e2-36d0dc096b61.png)

and if there is video how to dump games..it will be very big help because the steps is very hsrd to understand for normal users

**Comment by archshift** [comment]
Sorry, but this issue tracker is not a help forum. Try our [FAQ](https://citra-emu.org/wikis/faq) or [actual forum](https://discuss.citra-emu.org/) for help using Citra.

**Comment by GTO888** [comment]
so..at least what is the problem here??
