### ISSUE TITLE
101 Dino Pets - Graphical bug

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1626]
It could help https://github.com/citra-emu/citra/pull/1625

**3DS:**

![101 dino pets depth 2](https://cloud.githubusercontent.com/assets/11453507/14210666/502811f8-f82a-11e5-9d69-404b73fd5cde.JPG)

**Citra HW Renderer:**

![101 dino pets depth 1](https://cloud.githubusercontent.com/assets/11453507/14210671/5663a154-f82a-11e5-8c87-efd1d020b161.JPG)

**Citra SW Renderer:**

![101 dino pets depth 3](https://cloud.githubusercontent.com/assets/11453507/14210951/aa9e74aa-f82b-11e5-8f01-0e213b8b0cb3.JPG)

More (hw above / sw below):

![101 dino pets depth 5](https://cloud.githubusercontent.com/assets/11453507/14224428/727edc92-f89c-11e5-9f26-d05be557e3c3.JPG)
![101 dino pets depth 4](https://cloud.githubusercontent.com/assets/11453507/14224429/75c689f4-f89c-11e5-9640-c8df6cf79153.JPG)

![101 dino pets depth 6](https://cloud.githubusercontent.com/assets/11453507/14224426/62a79bd8-f89c-11e5-895b-02d18947f424.JPG)
![101 dino pets depth 7](https://cloud.githubusercontent.com/assets/11453507/14224427/6608f4ca-f89c-11e5-99ff-32c067c655e3.JPG)

![101 dino pets depth 8](https://cloud.githubusercontent.com/assets/11453507/14224430/7c5a8c70-f89c-11e5-92a5-a38957e44c48.JPG)
![101 dino pets depth 9](https://cloud.githubusercontent.com/assets/11453507/14224431/7f50e33e-f89c-11e5-9d32-a172f1070555.JPG)

Also shows:
`[  93.709150] Render.OpenGL <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:GLShader::AppendColorCombiner:203: Unknown color combiner operation: 6`

**Comment by JayFoxRox** [comment]
This seems to be a combination of various small problems.
I'll be looking further into it *probably*.

The algorithm seems to be something like:
* Draw scene from 0x18000000 (D24) and 0x183C8000 (RGBA8 256x800)
* Blur scene in 0x18096000 and 0x18300000 (ping pong, sampled RGBA8 128x256, drawn in 128x512?)
* Draw something at small resolution at 0x18340000 (depth buffer?)
* Clear and draw grayscale god rays in 0x18096000 and 0x18300000 (ping pong, sampled RGBA8 128x256, drawn in 128x512?)
* Merge scene with god rays from 0x18000000 ? (draw buffer = depth buffer = tex 2 = 0x18000000)

I'll edit this post later when I have more time - it probably reads like nonsense at this point.

Point is the HW renderer actually overwrites color with depth (color = depth). Not sure if it can sample the texture either (texture = framebuffer).

**Comment by JayFoxRox** [comment]
Fixed by #1786  I think
When loading a savegame the menu still bugs out, that seems to be a different issue though.

**Comment by JayFoxRox** [comment]
This bug (outdoor scene before the game starts) are fixed in HW renderer by #1768. SW renderer is missing per-pixel-lighthing but otherwise looks good with these scenes too.

The ingame scenes are still broken but that seems to be a memory or cubemap related issue.
The symptoms are also slightly different.
I'll close this and we should probably open a new issue about broken reflections and broken ingame scenes (one issue for each + better reference shots, also from hardware that time please - changes get very subtle now)
