### ISSUE TITLE
Stella Glow - Graphical bug

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1627]
You need a branch https://github.com/tfarley/citra/tree/hw-tex-forwarding or simply merge it to master, it's crashing while attemp to ingame on hw renderer without it.The log isn't showing anything useful.

**3DS:**
![stella glow 3 3ds](https://cloud.githubusercontent.com/assets/11453507/14224592/380d4e44-f8a2-11e5-86a4-7403e9cd71f6.JPG)

**Citra HW:**

![stella glow 1](https://cloud.githubusercontent.com/assets/11453507/14224597/4a6ef146-f8a2-11e5-8733-c22b3f41cfae.JPG)

**Citra SW:**

![stella glow 2 sw](https://cloud.githubusercontent.com/assets/11453507/14224595/42507566-f8a2-11e5-9307-40a5714716f2.JPG)

**Comment by JayFoxRox** [comment]
Did this change recently?

**Comment by Leo626** [comment]
Appears to be fixed with #1786. (N.B. I'm using the demo but since it shares the same issue with the full game, I'm assuming it's fixed as well.

![citra-qt_2016-05-12_17-37-32](https://cloud.githubusercontent.com/assets/17358613/15231366/a7fdaac4-1868-11e6-818a-41f91855a12d.png)
