### ISSUE TITLE
Games that crash when Shader JIT is enabled

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1629]
Tested on recent master and https://github.com/bunnei/citra/tree/refactor-shader-jit

Logs are from https://github.com/bunnei/citra/commit/b7bbc93dff8f7846410d98e16b12a71cc924d5ec

**Exstetra**

[LOG](http://pastebin.com/smB2tfa6)

**Sayonara Umihara Kawase**

[LOG](http://pastebin.com/BVH58Gm7)

and propably more (I will add next if I find them)

**Comment by Subv** [comment]
Does this still happen?

**Comment by JohnGodgames** [comment]
Yeah still with both of these...

**Comment by Dragios** [comment]
#2226 Suffers from the same issue but only when loading the game itself result in crash but not during booting.

**Comment by Subv** [comment]
These games are trying to perform ````movaps xmm1, [7FF66FC3A099h]````, but the manual entry for movaps says that it must operate on 16-byte aligned addresses.

**Comment by yuriks** [comment]
We're not scaling the loop index by 16 before indexing into the register. (How Does Anything Even Work™-worthy for sure) The fix is just to multiply LOOPCOUNT_REG and LOOPINC by 16 when they're assigned like we do with ADDROFFS_REG_0/1.

**Comment by JayFoxRox** [comment]
Proposed solution https://github.com/JayFoxRox/citra/pull/34 (untested still)

**Comment by mailwl** [comment]
Cut the Rope works
