### ISSUE TITLE
Gummy Bears Magical Medallion - Crash with SW-Rasterizer

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra#1633]
Tested using master fc6f898e0bab7446df330bca3b0807e871520d32

Fixed by closed-no-merge #1518 . SW-Rasterizer crashes in logos + menu + ingame at `GetDepth`
Needs further investigation.

HW renderer works fine for logos + menus.
HW Renderer only draws sky for me (Different results for somebody else: #1532 ).

**Comment by JayFoxRox** [comment]
Looked into it.

```
viewport size: 120, 200 viewport offset: 0,   0 framebuffer size: 240, 400 (Top screen)
viewport size: 120, 200 viewport offset: 0, -40 framebuffer size: 240, 320 (Bottom screen)
```

Vertex coords x max are 400.5 / 400.0 so we'll assume those are kind of safe.

Now lets do the math:

```
    vtx.screenpos[1] = (vtx.pos.y * inv_w + float24::FromFloat32(1.0)) * viewport.halfsize_y + viewport.offset_y;
= (-1.0 * 1.0 + 1.0) * 200 + 0 = 0 (Top screen min)
= ( 1.0 * 1.0 + 1.0) * 200 + 0 = 400 (Top screen max)
= (-1.0 * 1.0 + 1.0) * 200 - 40 = -40 (Bottom screen min)
= ( 1.0 * 1.0 + 1.0) * 200 - 40 = 360 (Bottom screen max)
```

This would overflow the framebuffer as the pixel coordinates must be in a \[0, 399\] (or \[0, 319\]) range
So this would underflow in ScreenToRasterizerCoordinates which casts the -40 to unsigned short putting max_y to 64896 => 4056 pixels high bounding box.

**Comment by benderscruffy** [comment]
can be closed 
goes ingame with [SW-Rasterizer]
