### ISSUE TITLE
PICA_DUMP_GEOMETRY doesn't work anymore

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra#1635]
`PICA_DUMP_GEOMETRY` has been broken for some time now. As the vertex cache is hit it won't be informed about all vertices passing through. This will break the output data.

---

The easy fix would be to disable the vertex cache when compiling with `PICA_DUMP_GEOMETRY`.
But that would possibly break some apps which depend on the cache as it actually emulates hardware behaviour (and shader state *could* depend on it) + that's just unclean code.

I think `PICA_DUMP_GEOMETRY` should be removed entirely to remove bloat code. Dumping geometry might be a fun feature for users but it serves no use in emulation or debugging the emulator.
(I personally used the `PICA_DUMP_GEOMETRY` define before to debug an issue but ended up rewriting almost all of it to suit my needs - I'm sure others would do the same. Also I wasn't aware that the VS debugger could show register states at that point)

The alternative would be to push for inclusion of such features in tools like apitrace or use existing tools such as renderdoc.
If users just want an easy way to export models this is probably better suited for a custom fork too.

If there should be a geometry dumper in citra it should probably be implemented elsewhere in the code and work by dumping the vertices independent of the renderer loop / vertex cache. Possibly some "Primitive inspector" which is closely tied to the VS debugger with connection to a GS debugger OR a debug callback for submitted polyons ("Fragment inspector"?). That would make it possible to export all attributes (by mapping them in the UI), making this a much more powerful tool.

**Comment by yuriks** [comment]
@JayFoxRox The shader cache is a pure optimization, I didn't model it based on the hardware (I tuned the size and associativity to maximize performance.)

I'd just remove it. I usually use RenderDoc to dump geometry if I need to.
