### ISSUE TITLE
Resident Evil: Revelations - Hangs at menu 

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1637]
Used a https://github.com/JayFoxRox/citra/tree/gs-new-refactor for showing a menus 

After I've pressed **OK** it hangs and spams with:

```
[  73.273137] Service.APT <Error> core\hle\applets\applet.cpp:HLE::Applets::Applet::Create:56: Could not create applet 1030
[  73.273683] Service.APT <Error> core\hle\applets\applet.cpp:HLE::Applets::Applet::Create:56: Could not create applet 1030
[  73.274723] Service.APT <Error> core\hle\applets\applet.cpp:HLE::Applets::Applet::Create:56: Could not create applet 1030
[  73.275884] Service.APT <Error> core\hle\applets\applet.cpp:HLE::Applets::Applet::Create:56: Could not create applet 1030
[  73.276399] Service.APT <Error> core\hle\applets\applet.cpp:HLE::Applets::Applet::Create:56: Could not create applet 1030
```

![resident evil rev 1](https://cloud.githubusercontent.com/assets/11453507/14233056/b8b96bb0-f9bd-11e5-8061-1b663505bc44.JPG)

[LOG](http://pastebin.com/WNuJUwU9)

**Comment by mailwl** [comment]
try to add my branch https://github.com/mailwl/citra/tree/erreula - it has 1030 applet
maybe it helps

**Comment by JohnGodgames** [comment]
Unfortunately https://github.com/mailwl/citra/tree/erreula not helped

**Comment by JamePeng** [comment]
0x406 is Error Display (error)

**Comment by JohnGodgames** [comment]
I think it's a something with streetpasss function, because on hw I have a dialog where I can choose to use a streetpass **Yes** or **No** .On Citra I can't choose and dialog is only **regarding the use of StreetPass**

**Comment by wwylele** [comment]
iirc, error display and streetpass dialog share the same applet ID.

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1850

**Comment by JohnGodgames** [comment]
#1850 Merged..closing
