### ISSUE TITLE
pokemon y do not load

### ISSUE THREAD

**Issue by Asad011** [citra-emu/citra#1642]
why it doesn't work?
![untitled 2](https://cloud.githubusercontent.com/assets/18265582/14252171/512b4cd6-fab0-11e5-908d-4cc5b723793b.png)
![untitled](https://cloud.githubusercontent.com/assets/18265582/14252172/512ea75a-fab0-11e5-9652-d20793e0361c.png)

**Comment by MerryMage** [comment]
This issue tracker is not a help forum. Please post to [the Citra forums](https://discuss.citra-emu.org/) in the future.

The answer to this question is [also in our FAQ](https://citra-emu.org/wiki/FAQ):

> Can Citra run Pokémon games?
> 
> Not at the moment. While you may have seen screenshots or videos of Citra running Pokemon games, these have been made with non-official builds. Pokemon games do not currently run with our nightly releases.
