### ISSUE TITLE
SDL2 LIbrary Missing problem (Linux)

### ISSUE THREAD

**Issue by NorbertoAlexander** [citra-emu/citra#1649]
Sorry if this is not the place for a Linux report but i think this is the only place where i can get the technical help.

So i have this error while making the installing
I change the subject of this issue because i realize that the instalation was not complete and because of that the room wasn't loading and i didint wanted to make more space creating another one.

<FindSDL2.cmake> </FindSDL2.cmake> CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message): Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR) Call Stack (most recent call first): /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE) externals/cmake-modules/FindSDL2.cmake:230 (FIND_PACKAGE_HANDLE_STANDARD_ARGS) CMakeLists.txt:155 (find_package)

My system is 

Linux Mint Rosa 17.3
4gb Ram
3X AMD Athlon(tm) ii x3 455 processor
GTX 750TI (364.12 Drivers)

**Comment by JamePeng** [comment]
[ 4.877189] Service.APT core/hle/service/apt/apt.cpp:Init:445: Unable to load shared font: /home/norberto/.local/share/citra-emu/sysdata/shared_font.bin

![qq 20160408170042](https://cloud.githubusercontent.com/assets/17095606/14379200/6588c502-fdab-11e5-9db4-13d29c5b5f3f.png)

Your citra couldn't find the shared_font.bin in \citra\user\sysdata

**Comment by JayFoxRox** [comment]
This is not for technical questions / user errors. Use [the forum](https://discuss.citra-emu.org/) for these kind of questions instead.
This issue tracker is used for technical discussions about new features / bugs.

Make sure you have SDL2 installed and always use the latest version from master.
Also cmake 2.8 sounds rather old. I'm using cmake 3.5. Keep your system updated and use a distribution which keeps its software up-to-date.

**Comment by yuriks** [comment]
This is a problem with GL support on your system. Please use the forums for support questions.
