### ISSUE TITLE
unknown / unimplemented function 'Subscribe'

### ISSUE THREAD

**Issue by Aegefel** [citra-emu/citra#1656]
Hi,
I'm trying to play Pokemon X with the lastest Citra's release but I have this issue:
I compiled Citra on linux and I launched citra-qtwith with this command:
cd build/src/citra_qt && ./citra-qt

Then I loaded the Pokemon X ROM and it crashed.
Here is what the terminal says
[Log.txt](https://github.com/citra-emu/citra/files/211923/Log.txt)

One of the lasts lines, it says:
[   6.190287] Service <Error> core/hle/service/service.cpp:SyncRequest:69: unknown / unimplemented function 'Subscribe': port=srv:, cmd_buff[1]=0x209

I had a panic loop then I put the default_font.bin from ctrulib in the appropriate repository, after renaming it in “shared_font.bin”.

However,  I still have this issue.
Thanks for your help
Aegefel

**Comment by JayFoxRox** [comment]
[Pokemon not working is a known issue](https://discuss.citra-emu.org/d/50-can-citra-play-pok-mon-other-game-s-won-t-start-crashes-look-here)

If you really want to play it find out how to make it work and maybe create instructions how to do it in the wiki or the forums (if there aren't any yet).
However, also tell people to not report issues about it if they are using non-offical builds.

**Comment by Aegefel** [comment]
Ok. Sorry and thanks for your help, I'll try to get it work and I'll let you know if I make it

**Comment by dheersusania** [comment]
@Aegefel did it work ??

**Comment by Subv** [comment]
Pokemon is not supported for now.

**Comment by dheersusania** [comment]
so what games are supported ?

**Comment by JayFoxRox** [comment]
[Use the forums for questions](https://discuss.citra-emu.org/)

**Comment by Aegefel** [comment]
I didn't had the time to get it works but during the holydays I will try
Sorry :)

**Comment by JayFoxRox** [comment]
Locked to avoid further spam
