### ISSUE TITLE
Unknown alpha blend factor 3

### ISSUE THREAD

**Issue by JamePeng** [citra-emu/citra#1658]
Use the master version code to test HarvestMoon3D(using the SW-rasterizer )
(note. just create a new branch , there are no new code)

After this  picture display:
![qq 20160411182701](https://cloud.githubusercontent.com/assets/17095606/14424310/f3b4a8dc-0012-11e6-8af5-776a378577ad.png)

`[  36.535983] HW.GPU <Critical> video_core\rasterizer.cpp:Pica::Rasterizer::ProcessTriangleInternal::<lambda_91630ad4b11595351d0bde8f7913cd6c>::operator ():1006: Unknown alpha blend factor 3`

![qq 20160411182559](https://cloud.githubusercontent.com/assets/17095606/14424276/ca08bcbc-0012-11e6-8317-25eb59f1d5c8.png)

**Comment by wwylele** [comment]
#1625 related?

**Comment by JamePeng** [comment]
yes，#1625 can fix it!

**Comment by JayFoxRox** [comment]
#1625 was merged - this can be closed.
