### ISSUE TITLE
SVC::CallSVC:1055: unimplemented SVC function ExitProcess(..)

### ISSUE THREAD

**Issue by JamePeng** [citra-emu/citra#1663]
Exit the homebrew application will cause this error!
![qq 20160413143221](https://cloud.githubusercontent.com/assets/17095606/14484777/3eaf3ab4-0185-11e6-8b78-898a243ac922.png)

I think it should return to homebrew launcher(which launch the homebrew) or this window
![qq 20160413144126](https://cloud.githubusercontent.com/assets/17095606/14484859/d8a28c8e-0185-11e6-8f21-550871be7a2a.png)

**Comment by deadair3210** [comment]
Emulator now crashes with an 'Unreachable Code!' error as of version = HEAD-b3c53b6

**Comment by Subv** [comment]
This function has already been implemented, please create a new issue with a log if the crashing persists.
