### ISSUE TITLE
Kokuga - Graphical bugs

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1664]
Nothing useful in log...

**3DS**

![kokuga 2](https://cloud.githubusercontent.com/assets/11453507/14489497/d908ffe0-016d-11e6-9ed9-68af54682bdb.JPG)

![kokuga 4](https://cloud.githubusercontent.com/assets/11453507/14489502/dd446b3a-016d-11e6-8d8e-fcfd8f600ec7.JPG)

**Citra**

![kokuga 1](https://cloud.githubusercontent.com/assets/11453507/14489509/e2fbc140-016d-11e6-8558-45b797dfc0b1.JPG)

![kokuga 3](https://cloud.githubusercontent.com/assets/11453507/14489513/e8358e0c-016d-11e6-9713-4cdafb9d67db.JPG)

**Comment by JayFoxRox** [comment]
Tex0 type is 3 (Projection). I'll implement this experimentally.
