### ISSUE TITLE
OpenGL state tracking issue in Fire Emblem Fates

### ISSUE THREAD

**Issue by DrewHak** [citra-emu/citra#1670]
So errrrr, I was running Fates on Citra, and it will finish a battle, but never go back to Open World, and when I check the command prompt, it's just continously saying [ 403.392243] Render.OpenGL <Error> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:444: API ERROR 1282: GL error GL_INVALID_OPERATION, what does that mean?

**Comment by yuriks** [comment]
This error spam, while annoying, should be harmless. Sometimes we neglect to unbind a texture before rendering. Should be fixed at some point.

**Comment by KillzXGaming** [comment]
Have you tested the newest audio branch? Seems to fix hanging and heard it fixes the games battle sequence.

**Comment by FearlessTobi** [comment]
I haven't seen this happen. 
This issue is likely outdated. If not it can be reopened.
