### ISSUE TITLE
A-Train: 3D City Simulator - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1674]
Nothing is shown and spams with:

```
[ 188.862354] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read32 @ 0x03371663
[ 188.862483] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read32 @ 0x0337166B
[ 188.862623] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read32 @ 0x03371673
```

[LOG](http://pastebin.com/ECqhQJXT)

**Comment by exhalatio** [comment]
I catch up ba0bfe7 is bootup. 2a19de1 is won't boot.
![a3ds](https://cloud.githubusercontent.com/assets/7089513/14777598/19035740-0b09-11e6-952a-f0294aa9ac99.jpg)

**Comment by wwylele** [comment]
@exhalatio so it is a regression? Also try #1695 ?

**Comment by exhalatio** [comment]
@wwylele That’s true. Also #1695 seems not helps.

**Comment by Subv** [comment]
Does this still happen?

**Comment by JohnGodgames** [comment]
Tested on https://github.com/citra-emu/citra-nightly/commit/b36677daff771d4791f3b13e0d7cb95f4b0b47f6 and game is working
