### ISSUE TITLE
Alien on the Run - Hangs at menu

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1675]
![alien hang](https://cloud.githubusercontent.com/assets/11453507/14569759/f9d3109c-0340-11e6-9498-39048a3c5e2f.JPG)

[LOG](http://pasted.co/721377a3)

**Comment by JayFoxRox** [comment]
Is this a new issue (regression maybe)? I remember having this issue, but about 1-2 weeks ago (might be wrong about the exact period, I'm bad at keeping track of time) I actually was able to go ingame with my GS branch.
(You were also ingame in #1531 )

So we should figure out if this is randomly or always happening.

**Comment by JohnGodgames** [comment]
It's a random.You can go up to ingame (when you quicky press A)  as is showed at #1531

**Comment by Subv** [comment]
Does this still happen?

**Comment by JohnGodgames** [comment]
Tested on https://github.com/citra-emu/citra-nightly/commit/b36677daff771d4791f3b13e0d7cb95f4b0b47f6

![alien on the run ingame](https://cloud.githubusercontent.com/assets/11453507/21860476/0a673256-d831-11e6-98bc-3dc8fea4b0d1.PNG)
