### ISSUE TITLE
The Binding of Isaac: Rebirth - Hangs while formating data

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1676]
![issac 1](https://cloud.githubusercontent.com/assets/11453507/14570107/bd60258a-0342-11e6-8a16-a3d5ada79a33.JPG)

[LOG](http://pasted.co/6eb864fa)

**Comment by Subv** [comment]
Does this still happen?

**Comment by mailwl** [comment]
if i am right, it's New 3DS only game

**Comment by JohnGodgames** [comment]
Yep closing for now...
