### ISSUE TITLE
Slice It! - Won't boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1678]
[LOG](http://pasted.co/07786f92)

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1641

**Comment by wwylele** [comment]
Is this fixed now?

**Comment by JohnGodgames** [comment]
It works on https://github.com/citra-emu/citra/commit/e91327c86a863b9419fd3695b2400a52336ec3b5
