### ISSUE TITLE
New Super Mario Bros 2 - Graphical bugs at HW Renderer (Alpha)

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1681]
It's a regression according to this older [video](https://www.youtube.com/watch?v=HQxsONkm_9c)

bug started with **Immediate-mode improvements #1461**
https://github.com/citra-emu/citra/pull/1461/commits

![nsmb 2 1](https://cloud.githubusercontent.com/assets/11453507/14573068/f08ec1c2-0352-11e6-8616-5e0d4ea974ff.JPG)

![nsmb 2 2](https://cloud.githubusercontent.com/assets/11453507/14573073/f5f481a6-0352-11e6-9068-4bb6f91bd7b0.JPG)

![nsmb 2 3](https://cloud.githubusercontent.com/assets/11453507/14573076/faf37248-0352-11e6-8061-b428c559996f.JPG)

**Comment by KillzXGaming** [comment]
It's kinda odd. Animal crossing also has this issue however in older builds it does not along with this game.
Old build (around January)
http://i.imgur.com/tkf388x.png

http://i.imgur.com/7v9Bc2n.png

**Comment by JayFoxRox** [comment]
I'll self-un-assign this for now because I'm too busy with other stuff at the moment.
I'd be happy if anyone else could look into this.

**Comment by B3n30** [comment]
Solved by #2921
