### ISSUE TITLE
Pokemon Mystery Dungeon Gates to Infinity: Unhandled exception: Integer division by zero.

### ISSUE THREAD

**Issue by Gabrielbeck** [citra-emu/citra#1682]
Hello , sorry for my bad English. I found this exception when I was testing the battles at the end of the first dungeon of the game.

When you start the battle , the value of output_width and output_gap are not getting properly.

![screenbattle](https://cloud.githubusercontent.com/assets/13140288/14578511/4eeb7258-0360-11e6-961a-f9ba3cf5d876.png)

![exceptiondivisionbyzero](https://cloud.githubusercontent.com/assets/13140288/14578512/56b72fb8-0360-11e6-9e1c-ad9342af5372.PNG)

**Comment by HJJ256** [comment]
Same Problem Here!

**Comment by HJJ256** [comment]
Someone please solve this issue!

**Comment by Dragios** [comment]
#1928

**Comment by j-selby** [comment]
Yeah, this seems to be quite a weird issue. It occurs at every boss/random encounter. Here is a very basic fix (hardware confirmation of this behavior is required and it likely doesn't meet Citra formatting requirements):

Replace [src/core/hw/gpu.cpp line 190-194](https://github.com/citra-emu/citra/blob/master/src/core/hw/gpu.cpp#L190) with:

    if (input_width > 0) {
        size_t contiguous_input_size = config.texture_copy.size / input_width * (input_width + input_gap);
        Memory::RasterizerFlushRegion(config.GetPhysicalInputAddress(), static_cast<u32>(contiguous_input_size));
    }

    if (output_width > 0) {
        size_t contiguous_output_size = config.texture_copy.size / output_width * (output_width + output_gap);
        Memory::RasterizerFlushAndInvalidateRegion(config.GetPhysicalOutputAddress(), static_cast<u32>(contiguous_output_size));
    }

That is my best guess for there. If no memory has to be flushed, there is no point in invoking the method (and invoking that invalid division).

This will then cause the following while loop to go into a infinite loop. Adding this will fix that:

Add this at [src/core/hw/gpu.cpp line 201](https://github.com/citra-emu/citra/blob/master/src/core/hw/gpu.cpp#L201):

    if (copy_size == 0) {
        LOG_CRITICAL(HW_GPU, "Invalid copy_size");
        break;
    }

We are now in:

![chrome-07-09-2016_18-34-31](https://cloud.githubusercontent.com/assets/1404334/18305214/d397c836-7529-11e6-86b1-f47f02a57aeb.png)
![chrome-07-09-2016_18-34-21](https://cloud.githubusercontent.com/assets/1404334/18305218/d6b8d028-7529-11e6-8a58-6df508f10ad6.png)


I'll pull request this if it is at all useful (and not just a dirty hack).

**Comment by Dragios** [comment]
Awesome!! I myself also trying to fix it by myself but it seems to be no avail.

**Comment by prshkr07** [comment]
@j-selby , could you please share your compiled citra with above code changes. 
File size of compilation tools are way too big for me to download. Thanks.

**Comment by j-selby** [comment]
@prshkr07, I won't be distributing copies of Citra myself, master or not. Wait until my changes have been tested and merged into master to download a official build.

**Comment by prshkr07** [comment]
@j-selby , ok. thanks.

**Comment by wwylele** [comment]
Should be fixed by #2103. If not please leave a comment and reopen this.
