### ISSUE TITLE
Mario & Sonic at the London 2012 Olympic Games - Hangs at title screen

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1684]
Hangs after pressing **A** or **TOUCH**

![mario sonic olymp](https://cloud.githubusercontent.com/assets/11453507/14578564/6adae0ea-038b-11e6-95ca-4ac49cd2c036.JPG)

[LOG](http://pasted.co/b8ffdd8c)

**Comment by KillzXGaming** [comment]
Guessing ControlArchive crashes the game similar to ALBW. Does a save have the same effect?

**Comment by JohnGodgames** [comment]
Fixed with https://github.com/MerryMage/citra **audio** branch

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/citra-emu/citra/pull/1734
