### ISSUE TITLE
Mario Kart 7 - hang before racing start

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#1687]
This is a regression. The last passing build I found is b393408, and the first failing build is dccadce. 
Now when trying start a race (after selecting everything and the cut scene before start), the game hangs with the following log spammed:
`[  72.865351] HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read3
2 @ 0x00000FE8`
(Seems that PC move to 0x00000000 somehow)

**Comment by mailwl** [comment]
hm... i know, frd:u full of bugs (now i fix it while trying to make work YouTube app), but on latest master Mario Kart 7 works fine for me:
![mariokart7](https://cloud.githubusercontent.com/assets/629437/14586970/88504468-04b1-11e6-99c3-fdfefb7ecb13.png)

**Comment by wwylele** [comment]
hmm... delete everything and put only necessary files there, it works again on current master... It might be some strange things in the save game or config file. I can't reproduce it now, so I will close this issue until I find exactly what the problem is.

**Comment by pippo2931** [comment]
I got the same issue. Sometimes citra crashes after selecting the cart or it hangs before starting the race.
