### ISSUE TITLE
Ridge Racer 3D - Graphical bugs in the tunnel at HW Renderer

### ISSUE THREAD

**Issue by exhalatio** [citra-emu/citra#1693]
Tested in 32dfd4b
When you driving in the tunnel, reflection the bottom screen on the top screen. (HW Renderer)
![rr3d](https://cloud.githubusercontent.com/assets/7089513/14638377/119b403a-0672-11e6-827f-9151cd497ed4.jpg)

**Comment by exhalatio** [comment]
Fixed by 6abc600

**Comment by Subv** [comment]
Huh, are you sure that's the one that fixed it?

**Comment by JayFoxRox** [comment]
I couldn't reproduce it either the other day (on another track), but I'm not sure if it might still exist under some conditions.

I'm very certain that it's just fixed *at* that revision and not fixed *by* it.

**Comment by exhalatio** [comment]
@Subv I think fixed at this revision. and not fixed this one.
I have to ｓａｙ that "Fixed at 6abc600".
I'm sorry.
