### ISSUE TITLE
Theatrhythm Final Fantasy Demo: Text scrolls outside of text border.

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#1694]
Tested with master 32dfd4b. The text is suppose to clip along the border as seen [here](https://gfycat.com/SereneEverlastingApe). I'm not sure if the log provides anything useful.

![2016-04-19_14-36-07](https://cloud.githubusercontent.com/assets/17358613/14657130/aac25dde-0659-11e6-8609-514d8d2c802e.gif)
[LOG](http://clipboard.space/clip/EByr10G6goU69be2adRv)

Something similar occurs in Fire Emblem: Awakening.
![citra-qt_2016-04-19_14-16-27](https://cloud.githubusercontent.com/assets/17358613/14657181/1cc6f066-065a-11e6-92cc-fd60b7e8653c.png)
![ffa](https://cloud.githubusercontent.com/assets/17358613/14657184/232db57a-065a-11e6-8850-009a40356c10.PNG)
[LOG](http://clipboard.space/clip/doDxB9j5J9cGJ1eZ0rqe)

**Comment by Subv** [comment]
I think remember fixing this problem _somehow_, maybe it was related to #1263

**Comment by Leo626** [comment]
@Subv Thanks. I tried your scissor branch and it fixed the issue.

![citra-qt_2016-04-19_19-16-28](https://cloud.githubusercontent.com/assets/17358613/14658909/6e5c02f8-0665-11e6-88b3-260531674e6c.png)
![citra-qt_2016-04-19_19-27-54](https://cloud.githubusercontent.com/assets/17358613/14658914/783b00a8-0665-11e6-8cbe-bc84243cb9c1.png)
