### ISSUE TITLE
Mario Kart 7 - lots of errors - check included screenshots

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#1698]
Lots of errors trying to run Mario Kart 7 on latest nightly build (2016-04-21) of Citra. OS is Windows 8.1 64-bit. CPU is Intel Core i7-3632QM. GPU is Geforce GT 740M with version 364.72 of the driver.

![citra1](https://cloud.githubusercontent.com/assets/18618590/14748204/ac3178ec-08b8-11e6-9bd2-e0968632b05e.png)
![citra2](https://cloud.githubusercontent.com/assets/18618590/14748210/b02a77a0-08b8-11e6-8e5a-f04f0254e87f.png)

**Comment by mailwl** [comment]
you need file user\nand\00000000000000000000000000000000\title\0004009b\00010202\content\00000000.app.romfs
dumped from 3ds

**Comment by JayFoxRox** [comment]
What mailwl said. I'll close this.
Consult the forums at https://discuss.citra-emu.org/ for any further related questions.
(And come back with bug reports if you find any)
