### ISSUE TITLE
Mario & Luigi Paper Jam - memory leak in OS X during battles

### ISSUE THREAD

**Issue by pippo2931** [citra-emu/citra#1701]
As soon as a battle starts, citra is leaking memory.
In top, CMPRS 3392M+ are 3 Gigs of compressed memory allocated but not used anymore by citra.
It grows up to 20 Gb.
Eventually systems runs out of resources.

<img width="982" alt="screen shot 2016-04-22 at 11 57 17 am" src="https://cloud.githubusercontent.com/assets/17737754/14752271/37a6688c-0883-11e6-8945-47d012e2933e.png">
<img width="991" alt="screen shot 2016-04-22 at 12 08 37 pm" src="https://cloud.githubusercontent.com/assets/17737754/14752273/3b3332be-0883-11e6-8145-35534a16b231.png">

**Comment by JayFoxRox** [comment]
Is this still an issue? It might have been fixed by the changes to the shader cache keys in #1704

**Comment by pippo2931** [comment]
Still around in latest master.
Paper Mario Sticker Stars too, my system run out of memory during the intro.
I tried valgrind (does not work well on 10.11.5) and other OS X tools but they could not catch anything.

**Comment by pippo2931** [comment]
Partial workaround is to disable "enable scaled resolution" from graphics preferences.

**Comment by pippo2931** [comment]
No more memory leaks with High Sierra and latest citra.
