### ISSUE TITLE
Tried to run a game, and got some kind of error

### ISSUE THREAD

**Issue by sergito98** [citra-emu/citra#1702]
I tried to run Pokemon Y and I got an error which said something about gsp

![b24ea7686828091c54daf34fdd15880e](https://cloud.githubusercontent.com/assets/18622235/14755667/43850a62-08e4-11e6-9f62-49f5d32db8b9.png)

Anyone can help me?

**Comment by jroweboy** [comment]
Nope. Not here at least. This is not a place to ask for help, this is an issue tracker for developers. You might have better luck asking on the forums https://discuss.citra-emu.org/
