### ISSUE TITLE
Kuroko no Basuke - Mirai e no Kizuna 

### ISSUE THREAD

**Issue by SakataGintokiYT** [citra-emu/citra#1703]
Latest Nightly Build 

<img src="http://www.fotoszok.pl/upload/dd155466.png" alt="Fotoszok.pl" />

**Comment by wwylele** [comment]
Please put full log here

**Comment by SakataGintokiYT** [comment]
https://gist.github.com/SakataGintokiYT/35bfb41136ae56d2a2dce7a920c33dd3

**Comment by mailwl** [comment]
it works for me to main menu, but black screen on New Game.

**Comment by SakataGintokiYT** [comment]
@mailwl 
Thanks :P
<img src="http://www.fotoszok.pl/upload/3bb45c68.jpg" alt="Fotoszok.pl" />

**Comment by JayFoxRox** [comment]
This looks resolved, I'll close this.
