### ISSUE TITLE
Citra does not recognise key pressed in foreign keyboard layout

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#1707]
for example, key 'A' in english looks 'Ф' in russian even if it one physical key.
Maybe change asking ascii-code to scan-codes?

**Comment by valentinvanelslande** [comment]
@MerryMage this is not a swkbd issue, remove the label

**Comment by SleepingSnakezzz** [comment]
Closing in favour of https://github.com/citra-emu/citra/issues/4243
