### ISSUE TITLE
Better utilize the github label system in issues and PRs

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra#1715]
We need some stricter rules and better suited labels for issues and PRs. I've mentioned this earlier on IRC but I'm a little worried it will be lost. Also we should probably decide this together to not make it worse as it is (imho).
(Sorry if you think this is not the proper place to discuss this. I'd rather use a forum software but this is probably as good as it gets because I'm not even sure if all maintainers check the citra forums regularily)

The current labels should be deprecated and replaced
- **proposal / enhancement**: what's the difference between this and enhancement? (I can see some cases, but often those imply each other)
- **bug**: most things which are not an enhancement are most likely a bug. It would be more interesting to know if a bug is in the host (~ SIGSEGV) or guest ("read32() unmapped"). We could probably just use "bug" for host issues and replace each guest bug with a label which already hints the affected subsystem
- **D-easy** / **D-hard** / **D-intermediate**:  Do we really have to tag these? Often times it's easy to figure out if a problem is easy or not but sometimes there are problems you don't expect. If we want to attract new developers we should list these elsewhere
- **duplicate**: Useless because we can just reference the original issue and close the new one
- **frontend**: okay
- **graphics**: okay but I'd rather use "GPU" and "CPU", "APT", "Y2R" etc. tags which are way more meaningful and hint a subsystem..
- **help wanted** / **question**: seem useless to me because if you post an issue you most likely want help / discussion of some sort. We should redirect most questions to the forum anyway
- **invalid**: invalid what? No idea when to use this one
- **performance**: okay
- **regression**: okay
- **savedata**: okay but a more generic "storage" or "fs" is probably better because we also have bugs related to SD card not being detected which might not be directly be "savedata"
- **tests pending**: I'm usually unsure what kind of tests it means - does it mean hw-test for PRs? does it mean more tests to confirm an issue? ..
- **unimplemented**: There aren't too many unimplemented features left so it might be more logical to hint a subsystem again ("shadow-texture", "geometry-shader", "cubemap", "unimplemented-hle")
- **wontfix**: closing these should be enough, if we find them again and the last post is "won't fix because..." that's much more meaningful.

So maybe we can use this issue to discuss the matter by building new policys (for labels) and proposing new labels?

First proposal: label for **administrative** tasks (such as discussing behaviour of maintainers in case a user complains, discussions like this which are not directly related to citra, discussion of licensing etc.)

**Comment by mailwl** [comment]
proposal / enhancement -there is difference, at my point of view.
for example, what i want to ask:
implement controller support - it is proposal
save config settings immediately after changing (don't lose last game when crash) - it's enhancement
because feature already exists, but need, mm... enhancement?

**Comment by JayFoxRox** [comment]
The problem with that terminology is that a proposal probably always implies an enhancement in the long run.

What I've realized the past days is that we definitely need tags for each subsystem. That would put A LOT more meaning to tags such as "unimplemented" or "bug".

If we had a tag for already solved problems which are not merged yet that'd be great.
If we call that tag `implemented` we don't even need the "unimplemented" tag anymore - then we won't need the "unimplemented" tag anymore if combined with a feature tag - example:

* Ridge Racer 3D - Broken reflection `gpu:cubemaps`

  Cubemaps are not in the codebase and nobody has implemented it yet either. As cubemaps are a subtag of GPU we'd also know that we know exactly what's wrong. If we wouldn't know that it is related to cubemaps but somewhere in the GPU we'd have used `gpu`

* Ridge Racer 3D - Car colors wrong `gpu:sw` `bug`

  Problem in the codebase, somewhere in the GPU software rasterizer code. HW renderer is not affected

* Pokemon - Hangs after selecting pokemon `audio` `implemented`

  Some implementation exists for audio, somewhere, but it's not in the codebase yet. So even if nothing is ever merged we have some reference code for this (which should be linked to somewhere in the issues discussion)

* \<Game\> - \<Problem\> `cpu` `bug` `implemented`

  `bug` + `implemented` should not be used in combination, or maybe only if there is a broken reference implementation. The feature tag still shows it's a CPU problem

No tag would mean nobody looked into it or we don't know what's wrong

**Comment by mailwl** [comment]
"implemented" not good tag, better "in testing", or something like this

**Comment by JayFoxRox** [comment]
I also thought about "in testing" or "wip" but I think "in testing" creates an ambiguity because it implies that this is actively being tested. Also it could mean we are testing to find the bug. I'm still open to other suggestions though :)

(I went ahead and added an `audio` tag in gold which hopefully becomes the "feature" color now because too many issues were getting hard to find. I'm tempted to create more tags but I'd rather have a discussion about it first)

**Comment by JayFoxRox** [comment]
I'll create more "component:feature" labels *soon* if there is no veto here soon:

* I'll (probably) start with "administrative", "gpu:cubemap" and "gpu:projection2d", "frontend-qt" but add more as I see fit.
* I'll also get rid of old labels "invalid", "duplicate", "help wanted" and "question".

**Comment by archshift** [comment]
Personally I think "implemented" is unclear, I do really like "wip" though. I'm also fine with more specific labels.

**Comment by MerryMage** [comment]
If one wanted to get rid of "question", it should be lumped together with "invalid" (i.e.: this issue is not a valid issue)

**Comment by JayFoxRox** [comment]
I've done plenty of changes already.

- I did what Merry suggested and replaced the use of 'question' by 'invalid'
- Removed 'help wanted' and 'question'
- I've created a couple new ones:
  - Those in gold are functional features or subsystems which are broken.
    - Namely: 'gpu:shader-jit', 'gpu:gl-renderer', 'gpu:sw-rasterizer', 'gpu:scissor', 'gpu:gs'
  - The light yellow is for non-functional issue labels
    - Namely: 'administrative'
  - I've also recolored some older ones (Make red match for 'regression', 'bug' etc.).
  - I've then added 'crash' for severe cases where the emu does not only fail to emulate but also fails to work entirely which results in it closing. These are probably more important than simple 'bugs'

We should only use one or two of each color at the same time. Just use the most important one and only use them if we have confirmed what the issue is.

I still decided to keep 'duplicate' because I wasn't sure if I should also tag them 'invalid' and we haven't decided wether 'duplicate's should be closed or kept open
I also kept the older 'graphics'-label etc. for now because they are still widely used and give an indicator of what the problem looks like (= before we have pinned it down to something specific), not what the problem actually is.

I'd also like golden labels for the CPU / memory bugs but I'm not sure how to call them yet.

**Comment by JayFoxRox** [comment]
I'll close this for now because the new labels are being used, I'll add/remove more as I see fit.
