### ISSUE TITLE
Dragon Quest VII don't work after selecting new game

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#1716]
```
[ 469.336517] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x4010C0, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.336778] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x4010D0, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.337057] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400400, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.337336] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400404, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.337596] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400408, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.337853] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40040C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.338162] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400410, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.338425] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400414, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.338691] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400418, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.338950] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40041C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.339225] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400420, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.339491] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400424, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.339747] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400428, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.340005] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40042C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.340294] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400430, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.340553] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400434, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.340812] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400438, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.341078] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40043C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.341360] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400440, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.341617] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400444, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.341877] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400448, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.342134] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40045C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.342400] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400460, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.342664] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400464, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.342928] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400470, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.343190] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40049C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.345040] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400500, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.345302] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400504, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.345559] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400508, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.345817] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40050C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.349179] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400510, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.349548] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400514, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.349874] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400518, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.350201] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40051C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.356759] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400520, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.357141] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400524, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.357490] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400528, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.357892] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40052C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.361619] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400530, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.361963] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400534, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.362303] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400538, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.362653] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40053C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.365742] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400540, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.366118] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400544, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.366463] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400548, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.366831] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40055C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.373351] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400560, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.373747] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400564, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.374119] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400570, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.374465] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40059C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.378177] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400468, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.378520] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40046C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.378859] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400568, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.379187] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x40056C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.382348] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400494, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.382800] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400498, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.383266] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400478, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.383697] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400578, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.389959] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegsWithMask': port=gsp::Gpu, cmd_buff[1]=0x400C18, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10, cmd_buff[5]=0x10402, cmd_buff[6]=0xFFFFE14
[ 469.390499] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400004, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.390822] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegsWithMask': port=gsp::Gpu, cmd_buff[1]=0x40001C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10, cmd_buff[5]=0x10402, cmd_buff[6]=0xFFFFE14
[ 469.391147] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegsWithMask': port=gsp::Gpu, cmd_buff[1]=0x40002C, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10, cmd_buff[5]=0x10402, cmd_buff[6]=0xFFFFE14
[ 469.395250] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400050, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.424994] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegsWithMask': port=gsp::Gpu, cmd_buff[1]=0x400054, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10, cmd_buff[5]=0x10402, cmd_buff[6]=0xFFFFE14
[ 469.425727] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400474, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.426352] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'WriteHWRegs': port=gsp::Gpu, cmd_buff[1]=0x400574, cmd_buff[2]=0x4, cmd_buff[3]=0x10002, cmd_buff[4]=0xFFFFE10
[ 469.426787] Service <Trace> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: function 'TriggerCmdReqQueue': port=gsp::Gpu
[ 474.371416] HW.Memory <Error> core\memory.cpp:Memory::GetPointer:259: unknown GetPointer @ 0x5916b139
```
(Edited by JayFoxRox to use markdown styling)

**Comment by gilatino** [comment]
This game crash the emulator while booting with #1689 . I don't know if this is helpful as I know nothing about programming but here are part of the logs that shows a difference.
With #1689 

> [   2.696476] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:69: unknown / unimplemented function 'ReadSavedData': port=cecd:u, cmd_buff[1]=0x60, cmd_buff[2]=0x65E00, cmd_buff[3]=0x2, cmd_buff[4]=0x12, cmd_buff[5]=0x20, cmd_buff[6]=0xA8024, cmd_buff[7]=0x60C, cmd_buff[8]=0xFFFF628
[   2.696981] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::ResumeDaemons:99: (STUBBED) daemon_bit_mask=0x0000000F
[   2.697330] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:298: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF90, buffer2_addr=0x0FFFFF94
[   2.768160] Kernel.SVC <Warning> core\hle\svc.cpp:SVC::CreateThread:500: Newly created thread is allowed to be run in the SysCore, unimplemented.
[   2.770089] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:423: Unknown virtual address @ 0x0FFFFCA0
[   4.728293] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:423: Unknown virtual address @ 0x0FFFFDE0
[   5.358224] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::AcquireRight:645: called
[   5.358846] HW.Memory <Debug> core\memory.cpp:Memory::MapPages:81: Mapping 000001CDA5417B00 onto 10000000-10001000
[   5.359286] HW.Memory <Debug> core\memory.cpp:Memory::MapPages:81: Mapping 000001CDA5419B00 onto 10002000-10003000
[   5.359545] HW.Memory <Debug> core\memory.cpp:Memory::MapPages:81: Mapping 000001CDA5419B00 onto 10002000-10003000 The game crashes the emulator here

> 

![imagess 1](https://cloud.githubusercontent.com/assets/17504785/15100986/03037230-158c-11e6-9bf6-682d0ca9bfc0.png)


Without #1689 

>  [  13.266003] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:69: unknown / unimplemented function 'ReadSavedData': port=cecd:u, cmd_buff[1]=0x60, cmd_buff[2]=0x65E00, cmd_buff[3]=0x2, cmd_buff[4]=0x12, cmd_buff[5]=0x20, cmd_buff[6]=0xA8024, cmd_buff[7]=0x60C, cmd_buff[8]=0xFFFF628
[  13.266492] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::ResumeDaemons:99: (STUBBED) daemon_bit_mask=0x0000000F
[  13.266784] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:304: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF90, buffer2_addr=0x0FFFFF94
[  13.339303] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:423: Unknown virtual address @ 0x0FFFFCA0
[  15.274123] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:423: Unknown virtual address @ 0x0FFFFDE0
                                                                                [  82.873364] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::AcquireRight:644: called
[  82.910393] Kernel.SVC <Error> core\hle\service\apt\apt.cpp:Service::APT::GetSharedFont:92: called, but shared_font.bin has not been loaded!
[  82.910921] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:404: Emulated program broke execution!
[  82.911290] Debug.Emulated <Critical> core\hle\svc.cpp:SVC::Break:412: Break reason: PANIC
[  82.911802] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x00000000
[  82.911922] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x00000000
[  82.912199] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x00000000
[  82.912307] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x00000000

>

**Comment by Subv** [comment]
@gilatino That crash means you do not have the shared_font.bin file, extract it from your 3DS and place it in the correct location, then try again.

**Comment by gilatino** [comment]
@Subv Thanks, that fixed it.
The game is still broken as before although it shows new lines in the log (unmapped Read.Write lines) with #1689 . If this is unhelpful or I am bothering you, just tell me  and I will stop posting.

> 
[ 363.488810] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::AcquireRight:645: called
[ 363.489263] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x10003000
[ 363.489479] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x10003000
[ 363.490035] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read8 @ 0x10003001
[ 363.490186] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x10003000
[ 363.490336] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x1000303C
[ 363.490485] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x10003038
[ 363.490632] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000105 @ 0x10003020
[ 363.490776] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x14DC7B50 @ 0x10003024
[ 363.490920] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00007480 @ 0x10003028
[ 363.491062] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x1000302C
[ 363.491212] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x10003030
[ 363.491364] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x10003034
[ 363.491513] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000100 @ 0x10003000
[ 363.491670] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read8 @ 0x10003001
[ 363.491811] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x10003000
[ 363.492040] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x1000303C
[ 363.492197] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x10003038
[ 363.492345] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x01000101 @ 0x10003020
[ 363.492498] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x14DC7B50 @ 0x10003024
[ 363.492653] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00007480 @ 0x10003028
[ 363.492823] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x1000302C
[ 363.493018] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x10003030
[ 363.493254] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x10003034
[ 363.493403] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000100 @ 0x10003000
[ 363.493567] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read8 @ 0x10003001
[ 363.493724] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x10003000
[ 363.493877] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x1000303C
[ 363.494028] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000000 @ 0x10003038
[ 363.494195] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x01000103 @ 0x10003020
[ 363.494346] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x1F5F8000 @ 0x10003024
[ 363.494495] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x14DD7D20 @ 0x10003028
[ 363.494657] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00800080 @ 0x1000302C
[ 363.494802] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00800080 @ 0x10003030
[ 363.494947] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00004400 @ 0x10003034
[ 363.495115] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Write32 0x00000100 @ 0x10003000
[ 363.531441] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:423: Unknown virtual address @ 0x00DF1D80
[ 363.968091] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:423: Unknown virtual address @ 0x00DF1D80
[ 364.418064] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:423: Unknown virtual address @ 0x00DF1D80
[ 364.866000] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:423: Unknown virtual address @ 0x00DF1D80
[ 365.315656] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:423: Unknown virtual address @ 0x00DF1D80 The game continues to spam this.

>

**Comment by Subv** [comment]
Well that's interesting, it unmapped the GSP shared memory and then tried to read from it.

**Comment by Phanto-m** [comment]
This happens because this game calls UnregisterInterruptRelayQueue then RegisterInterruptRelayQueue everytime it loads a new screen/area, RegisterInterruptRelayQueue increments g_thread_id but unregister doesn't reset it, simply doing that will make the game run flawlessly
However multiple GSP threads are still broken (though i don't know of any game that uses this) because:
1. Shared memory is only 0x1000 sized when command buffers are located at 0x800 + threadid*0x200
2. Unless I'm totally off the mark here I don't think it's supposed to create a new shared memory everytime
3. According to 3dbrew only PDC0 and PDC1 should be sent to all threads, citra does that with every interrupt

**Comment by Subv** [comment]
I think the thread id is just so that multiple applications can use the GSP at the same time (So that they know where to write to in the SharedMemory without conflicting with others), the id seems to refer to a GSP-service thread that handles the requests from that specific session.
