### ISSUE TITLE
Johnny's Payday Panic - text rendering bugs

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1739]
Also crash at sw renderer

![payday 1](https://cloud.githubusercontent.com/assets/11453507/14935472/0e3c6e6e-0ed3-11e6-9bf9-a735f5d141c2.JPG)

![payday 2](https://cloud.githubusercontent.com/assets/11453507/14935474/16d37a4a-0ed3-11e6-8302-2e221a61e63e.JPG)

**Comment by wwylele** [comment]
I remember some games that has similar issue is due to unimplemented geometry shader.

**Comment by JohnGodgames** [comment]
Same with https://github.com/JayFoxRox/citra/tree/gs-new-refactor

**Comment by JayFoxRox** [comment]
How about my batching fix? If it's not that either I'll probably try to get my hands on it.

**Comment by JohnGodgames** [comment]
@JayFoxRox your batching fix branch = Immediate crash with that game

**Comment by JayFoxRox** [comment]
Fixed in #1689, we can close this once merged.
