### ISSUE TITLE
Qt: Rendering area never cleared by GL while games aren't actively rendering.

### ISSUE THREAD

**Issue by archshift** [citra-emu/citra#174]
![example](http://i.imgur.com/25aTA3b.png)

**Comment by neobrain** [comment]
Can you explain more thoroughly what you consider to be the actual problem here, and what you expect to be done differently?

**Comment by yuriks** [comment]
There's somewhat of a mis-description here. The output area isn't simply black,  it is unrenewed, so you get leftover stuff there. On my system it starts white and turns into a trail of window fragments when I resize the window or a debugger pane. It definitely looks bad.

**Comment by archshift** [comment]
The rendering area should be cleared on startup.

**Comment by archshift** [comment]
Should this be closed by #1171?

**Comment by LittleWhite-tb** [comment]
Yes.
