### ISSUE TITLE
Attack on Titan - Rasterizer Resource Cache Overflow 

### ISSUE THREAD

**Issue by KillzXGaming** [citra-emu/citra#1744]
Occurs in Attack on Titan. Causes crash once ingame. 
http://imgur.com/RB8dmGA

[LOG](http://pastebin.com/pBG72ZjX)

**Comment by JamePeng** [comment]
The same question with the 進撃の巨人～人類最後の翼, I output the debug info for check

Rasterizer Resource Cache Overflow(When count_delta=1, res_count=0xFF)
![qq 20160430165636](https://cloud.githubusercontent.com/assets/17095606/14940018/b40947a6-0f94-11e6-90af-a7f508ce4839.jpg)

Rasterizer Resource Cache Underflow(When count_delta=-1, res_count=0)
![2016-04-30_223757](https://cloud.githubusercontent.com/assets/17095606/14940019/b40cfcf2-0f94-11e6-99e8-3525d9cacc75.png)

maybe it is a surface problem?

**Comment by benderscruffy** [comment]
nightly HEAD-a66e458
just comes up with HW Memory errors now
[Debug log.zip](https://github.com/citra-emu/citra/files/1605452/Debug.log.zip)

**Comment by benderscruffy** [comment]
still crashes in the latest nightly 
but goes ingame in the latest canary
![attack](https://user-images.githubusercontent.com/2696404/35798692-8b1b97ac-0a9e-11e8-9c70-554f48e5e579.PNG)

**Comment by Leo626** [comment]
Closed with 4befbdd.
