### ISSUE TITLE
Strange error "Tried to register more than one archive with same id code"

### ISSUE THREAD

**Issue by fanfic65** [citra-emu/citra#1747]
Hello, today i was trying to play Monster high new ghoul at school for 3DS on Citra emulator and after selecting ROM File emulator crashes and in console it gives this error "Tried to register more than one archive with same id code"

I also attached screenshot of console after crash: 
<img width="676" alt="citra error" src="https://cloud.githubusercontent.com/assets/18960686/14943048/1bb1c3d0-0fcf-11e6-9d69-54d409096f42.png">

I am using Windows 10

Please help.

**Comment by wwylele** [comment]
Is this still an issue?

**Comment by Subv** [comment]
I'll close this, if it is still an issue in the latest master please create a new issue report.
