### ISSUE TITLE
Mario Kart 7 - Missing objects / Mii characters using SW-Rasterizer

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra#1749]
Tested on 15d0e982678d6151bb058fbb8ea0f39b7ffa688a

Hardware rendering:

![HW](http://i.imgur.com/UPFCYeH.png)

Software rendering:

![SW](http://i.imgur.com/lPa0lS7.png)

Nothing in log when switching.

**Comment by JayFoxRox** [comment]
I just found the cause for this.
This is related to SecondaryFragmentColor.rgba = 0 and the alpha of the Miis being taken from it.
We could theoreticly use a higher value but it seems to add a lot of specular to other objects.

We should keep this in mind and fix this by implementing per pixel lighting in the software renderer.

**Comment by FearlessTobi** [comment]
Now the Miis are visible on the Software Renderer too, but their heads are completely invisible on both HW and SW Renderer.

Hardware Renderer:

![hr](https://user-images.githubusercontent.com/20753089/32202287-e2ea29c2-bddb-11e7-9042-aa15d0bebbb5.PNG)

Software Renderer:

![sr](https://user-images.githubusercontent.com/20753089/32202291-eb088e3c-bddb-11e7-9eac-e4c71c65836a.PNG)

**Comment by FearlessTobi** [comment]
![unbenannt](https://user-images.githubusercontent.com/20753089/43317236-5df1a4a8-919c-11e8-908f-71d1a0a69b9d.PNG)
Issue is fixed in latest Nightly on both HW and SW Renderer.

Requesting to close.
