### ISSUE TITLE
RasterizerOpenGL::SetShader now creates much more new shader than before

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#1752]
This issue appears since #1745 merged. I can see there is much more "Creating new shader" log, and memory are consumed faster. I am not sure if this is the same padding issue in #1621 (I tried a quick memset/memcpy patch but seems not help). Or maybe `const_color` can vary in a large range in high frequency, so we shouldn't create shader for each value?

Edit: Now I think adding `const_color` in #1745 is a mistake. `const_color` is supposed to be handled as a  shader uniform(see [here](https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/gl_rasterizer.cpp#L1007-1013) and [here](https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/gl_shader_gen.cpp#L536)), not as a parameter to create shader

**Comment by tfarley** [comment]
Indeed, `const_color` is only used as a uniform (due to that high variance) and not actually part of shader code generation like the other TEV config values, so it should not be included in the hash of a shader. That explains why it was left out in the original code.

**Comment by JayFoxRox** [comment]
Oops :( Sorry. I'll create a new commit to remove the `const_color` line but keep the loop.
