### ISSUE TITLE
Pokémon Rumble World Won't boot 

### ISSUE THREAD

**Issue by suelo50** [citra-emu/citra#1758]
log
![log pokemon](https://cloud.githubusercontent.com/assets/16906404/15035638/7bf60fd4-125a-11e6-8ce2-ffdf87f6df34.png)

**Comment by KillzXGaming** [comment]
Boots for me in latest master. Also log isn't very detailed, suggest using this in a text file and save as a .bat.
citra-qt.exe 1> console.log 2>&1

**Comment by suelo50** [comment]
pokemon rumble world how fix it
![pokemon rumble](https://cloud.githubusercontent.com/assets/16906404/15064620/afe5703c-132c-11e6-9cf1-f2068e1897d8.png)

**Comment by suelo50** [comment]
pokemon rumble world how fix it?
![pokemon rumble](https://cloud.githubusercontent.com/assets/16906404/15064666/4b955d58-132d-11e6-962c-5396fabe2f0f.png)

**Comment by wwylele** [comment]
@suelo50 First run the mii maker with citra and make a mii. Then you can go in pokemon rumble world

**Comment by suelo50** [comment]
wwylele how run mii maker in citra?

**Comment by wwylele** [comment]
@suelo50 Dump the mii maker from you 3DS's NAND, decrypt it and run it as a normal game in citra. If you need more help about this please go to our [forum](https://discuss.citra-emu.org/)

**Comment by suelo50** [comment]
@wwylele thank

**Comment by JayFoxRox** [comment]
Can we close this then?

@wwylele we should probably document this on the wiki / faq. It's the first time I'm hearing about that. I only knew I had to dump the shared_font.

**Comment by poutros** [comment]
Pokémon rumble world boots and runs without any apparent issue(except textures).

**Comment by wwylele** [comment]
We can close this I think. Side note: no texture issue for me

**Comment by poutros** [comment]
@wwylele The attack's textures don't appear at all. (maybe those aren't textures but effects?)

**Comment by wwylele** [comment]
@poutros oh sorry I didn't notice that. It can be unimplemented geometry shader, I guess

**Comment by JayFoxRox** [comment]
@poutros please create a new issue with version information, a log and screenshots (citra SW rendering, citra HW rendering, behaviour on Console) for that if necessary. Title would be something like "Pokemon Rumble World - Attack effect not drawn" (or "Attack effect drawn incorrectly" if it somehow draws parts of it).
Also this souds like something that happens later into the game, so you might want to attach a savegame or mention how to reproduce this problem.

---

I'll lock this issue as the original issue has been solved.
