### ISSUE TITLE
Pokémon SMD massive slowdown intro playback and weird green artifact overlay display

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#1759]
I should have reported this issue long time ago.
Regression build 878562c

I noticed this in the log, spams often that causes massive slowdown intro video. It used to play the intro video at acceptable frame rate.
```
[  13.167374] Service.CAM <Warning> core\hle\service\cam\cam.cpp:Service::CAM::GetTransferBytes:133: (STUBBED) called, port=1
[  13.168369] Service.CAM <Warning> core\hle\service\cam\cam.cpp:Service::CAM::SetReceiving:92: (STUBBED) called, addr=0x307BD400, port=1, image_size=393216, trans_unit=5120
```
[[Full log]](http://pasted.co/8c41fed7) is based on the latest master 07411fb

![dc2ee9b](https://cloud.githubusercontent.com/assets/18496868/15036120/481ebd24-12bd-11e6-8af6-57a14bc16ca0.png)
![878562c](https://cloud.githubusercontent.com/assets/18496868/15035983/e6706998-12bb-11e6-929f-8c723c9a8d62.png)

**Comment by wwylele** [comment]
It is because we stubbed camera service (the grean screen should be image captured by camera). You can filter out this kind of log to increase frame rate

**Comment by Dragios** [comment]
It just looks weird to project image captured by camera with green overlay. There must be a better solution for this.
How to filter out the log?

**Comment by wwylele** [comment]
@Dragios [Log Filters](https://github.com/citra-emu/citra/wiki/Log-Filters)

**Comment by Dragios** [comment]
It seems like I need configure both qt-config.ini and sdl2-config.ini only then the log_filter will work. I think you might need to update the documentation.

**Comment by wwylele** [comment]
@Dragios `qt-config` and `sdl2-config` are corresponding to the two frontend (`citra-qt` and `citra`). Only edit the one that matches the frontend you use should work. If you need more support, please go to our [forum](https://discuss.citra-emu.org/)
