### ISSUE TITLE
Online Support feature?

### ISSUE THREAD

**Issue by briannyeko** [citra-emu/citra#1760]
when will you add online support(through LAN/Wi-fi) to the emulator?

**Comment by JayFoxRox** [comment]
"When it's done".
Ask such questions on the forum next time: https://discuss.citra-emu.org/
This is an issue tracker for citra developers.

Also you are being imprecise, do you mean: tunneling for ad-hoc games, netplay, sharing of savegames, connecting to offical servers, ... ?

If you are a developer yourself you can work on it. However, you should probably coordinate that on our IRC channel (freenode, \#citra-dev).

(You could have formulated it as a feature request instead so I would have left it open for development discussions about said feature)
