### ISSUE TITLE
Yo-Kai Sangokushi Won't boot (Crash in GPU)

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#1763]
Crash in <a href="https://github.com/citra-emu/citra/blob/master/src/core/hw/gpu.cpp#L340">GPU.cpp line 340</a>.
![youkai](https://cloud.githubusercontent.com/assets/7089513/15073541/044043ac-13d5-11e6-9b4b-1bf3a3ffa8f6.png)
<a href="http://pastie.org/10827010">LOG</a>

**Comment by Subv** [comment]
Huh, another game that feeds a heap address to the GPU, I've only seen this happen with Metal Gear Solid.

**Comment by KillzXGaming** [comment]
@Subv this also happens on Hyrule Warriors Legends.

**Comment by JohnGodgames** [comment]
It will be great if someone fix that.Next games with that problem:
- Fossil Fighters: Frontier
- Resident Evil The Mercenaries 3D
- Super Street Fighter IV: 3D Edition

**Comment by benderscruffy** [comment]
this goes ingame now using nightly HEAD-a66e458
![yokai](https://user-images.githubusercontent.com/2696404/34594585-ea0ff7e4-f20c-11e7-8aa3-b934d2e06343.PNG)
this can be closed now
