### ISSUE TITLE
Dragon Quest Monsters Joker 3 graphics error

### ISSUE THREAD

**Issue by Salijour** [citra-emu/citra#1769]
Unimplemented? shader/graphics cause missing textures and spiky polygon syndrome.

http://i.imgur.com/pTuEsPD.png
http://i.imgur.com/0BFdZaS.png

Log:
http://pastebin.com/gd1NiDeD

**Comment by JayFoxRox** [comment]
Very likely fixed by geometry shaders (looks like DMP_silhouette gone wrong)

**Comment by JohnGodgames** [comment]
Yeah that game uses a geometry shaders.You can see at this [video](https://www.youtube.com/watch?v=0hicrBzR_ms) (merged geometry shaders from JayFoxRox)

**Comment by wwylele** [comment]
Should be fixed by #2865 (I saw screen shots from others from bleeding edge build). If there is still issue, feel free to comment here / open a new one.
