### ISSUE TITLE
Ridge Racer 3D - Bad reflections

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra#1772]
Missing feature reported for 006fe5f and all versions prior

3DS (Stolen from some [youtube vid by 'Video Game Heaven'](https://www.youtube.com/watch?v=xRsjGj-w2TY), pardon the quality):
![Reflections](http://i.imgur.com/0VFlYNC.png)

Citra (left is default rendering, ignore the image on the right; stolen from pcmaker and too lazy to crop it): 
![Broken reflections](https://cloud.githubusercontent.com/assets/11453507/14625309/35f2c934-05e2-11e6-9d36-3a4483357b7d.JPG)

Note the reflection on the windshield etc.
This issue has been tracked down to cubemaps (if I remember correctly. It must be texture type related at least, so it's very likely)

(The white boxes around the sprites are _not_ related to this issue, they are part of #1661)

**Comment by wwylele** [comment]
Is this fixed by #3497 ?

**Comment by Dragios** [comment]
This can be closed. It is fixed by #3497 
![Nightly-640](https://user-images.githubusercontent.com/18496868/43301534-6652f4a2-9198-11e8-903b-3393acb9e888.png)
Screenshot based on [nightly-640](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-640). No build available for [nightly-639](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-639).

**Comment by legend800** [comment]
The issue has not been fixed. Please reopen. There's been no change to this bug in years. To repro you have to go straight into Single Player > Grand Prix > car screen. 100% repro. 

IF however you go somewhere else first after launching the game, like Quick Race, load the car screen, THEN go to Grand Prix, everything will be fine for the rest of the session. It's just going to Grand Prix first that triggers it - some weird issue loading these assets if you go in this order. 

![2018-07-27 08_43_04-window](https://user-images.githubusercontent.com/20983844/43330960-78a9e1ac-9179-11e8-915c-663baf6289bd.png)

**Comment by wwylele** [comment]
@legend800 #1661 is the one you are looking for
