### ISSUE TITLE
Ridge Racer 3D - Wrong car colors in sw-rasterizer

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra#1776]
Tested at 86ecbdf

**Menu**:

SW Renderer
![SW](http://i.imgur.com/79hl2yD.png)
HW Renderer (intended):
![HW](http://i.imgur.com/8YvxlMf.png)

**Ingame**:

SW Renderer
![SW](http://i.imgur.com/n84o2PJ.png)
HW Renderer (intended):
![HW](http://i.imgur.com/8pUSPVB.png)

Might be related to #1772 but not confirmed yet.
Partially caused by some reflections (which are far worse in sw-rasterizer) but also decals are white.

**Comment by Dragios** [comment]
Fix by #2822. Please close.
![nightly-285](https://user-images.githubusercontent.com/18496868/43303349-f0b6f0ea-91a1-11e8-8168-05a5b5c9f6c4.png)
