### ISSUE TITLE
Etrian Odyssey IV - Title screen BG, dungeons not rendering on HW renderer

### ISSUE THREAD

**Issue by xdanieldzd** [citra-emu/citra#1784]
Etrian Odyssey IV is not rendering its title screen sky background nor the dungeons on the current master using the HW renderer (tested on nightly build f6eb62d). They do work with the SW renderer, and appear to have stopped working on HW at some point after 73624b4 (cannot give an exact build).

(There's also a, probably unrelated, issue with menu backgrounds not rendering on HW since even before 73624b4. I'll try to narrow this down and open another issue for this, if needed.)

Log for f6eb62d: http://pastebin.com/85n8uHPa
Screenshots HW (broken):
![Title on f6eb62d HW](http://i.imgur.com/vG1KMHD.png)![Dungeon on f6eb62d HW](http://i.imgur.com/wjZI3Iv.png)
Screenshots SW (okay):
![Title on f6eb62d SW](http://i.imgur.com/KnSCfrt.png)![Dungeon on f6eb62d SW](http://i.imgur.com/fhTZRDZ.png)

Log for 73624b4: http://pastebin.com/gMZ44Gn3
Screenshots HW (okay):
![Title on 73624b4 HW](http://i.imgur.com/PEyMR5s.png)![Dungeon on 73624b4 HW](http://i.imgur.com/lLUHgdf.png)

**Comment by JayFoxRox** [comment]
The menu looks fine for me with HW in f6eb62d0628d31efc4f93a0057ebd85bb39bc0fe but in SW it has the same bug as your screenshot (stretched garbage polygons accross the tree and one horizontally accross the screen).
I'm on Intel HD 4000, i5, Linux, compiled this myself.

I can't get ingame due not being able to select "no" as an option to wether I want to transfer my demo data (which I don't have + face buttons and arrow keys don't work to select "no").

**Comment by xdanieldzd** [comment]
I'm on an old ATI Radeon HD 4670 - OpenGL 3.3, Shader Model 4.1, I believe -, so I'd _assume_ that maybe some OpenGL- and/or shader-related changes were done in between the mentioned commits, that my card doesn't support? I'll check if there's a driver update available that I missed (tho I'm not hopeful); any other ideas about what I could try on my end?

As for the demo data transfer option, I just tried starting a new game on the f6eb62d Windows nightly and [I can select "no", then select the difficulty and begin the game](http://imgur.com/a/0fbHD). The controls in general appear to work fine for me.

**Comment by JohnGodgames** [comment]
It seems to be a AMD issue only.On NVIDIA it's ok on latest master.

![etrian](https://cloud.githubusercontent.com/assets/11453507/15247490/ee05a1aa-1914-11e6-9524-8adcd78c3042.JPG)

**Comment by JayFoxRox** [comment]
@xdanieldzd can you `git bisect` + apitrace this? (menu should be enough)
[You seem to be quite capable, but if you have any issues feel free to contact me on irc or something - I'd try to guide you through it]

**Comment by xdanieldzd** [comment]
@JayFoxRox I _think_ I've successfully narrowed it down via `git bisect` - fc9cc21024bff71d98e0106c9d0fd0476ab3c17e (i.e. one of the two commits in PR #1621, merged via 86ecbdfa4de5654fb1f3e998921af8db1d5373cf) is the first bad commit according to the bisection result.

The last commit to master prior to that merge, feecc76333c56e42b9de590bef14e9e9872fbc5d, works fine. Traces up to the title screen - one showing the sky properly, the other without it - are attached ([citra-eo4-traces.zip](https://github.com/citra-emu/citra/files/264057/citra-eo4-traces.zip)).

**Comment by JayFoxRox** [comment]
Probably something about accuracy then.
I'll try to get my hands on an AMD machine. Both traces works fine on Intel HD 4000 (mesa)

**Comment by xdanieldzd** [comment]
Sort of an update on this issue from my end: I have recently upgraded to a _slightly_ more modern video card -- Radeon HD 6750, 1 GB GDDR3, OpenGL 4.4, Catalyst drivers 15.7.1 -- and the issues I've been experiencing are gone. The game now renders the title screen's sky background and dungeons correctly using the hardware renderer. That, coupled with the disappearance of some known issues in a few regular PC games, leads me to believe that this was just a case of old hardware and/or drivers not being up to the task.

So, would you count this issue as solved now, or would this still be worth investigating regardless? I still have the old 4670 card and _might_ be able to set up another machine with it, in case more testing would be desired.

**Comment by yuriks** [comment]
Given that updating your card/drivers fixed it, it was probably some sort of driver bug. So I'll close it.
