### ISSUE TITLE
Pokemon Omega Ruby / Alpha Sapphire Crash / Black screen Rustboro City

### ISSUE THREAD

**Issue by kreedz1** [citra-emu/citra#1796]
Black screen when you leave Petalburg to enter Rustboro City

Game runs somewhat well until that crash here's a screenshot and log
![c63bcfbb5bf095a36949a32d66f94cb3](https://cloud.githubusercontent.com/assets/7191061/15271142/1b1b9d4c-1a33-11e6-9ee7-cbec37e5ba27.png)
[log_pertersburg.txt](https://github.com/citra-emu/citra/files/264749/log_pertersburg.txt)

**Comment by JayFoxRox** [comment]
Known issue + we don't support unoffical builds.
Wait until stuff is in master (Can take a couple of months).

Closed as invalid.
