### ISSUE TITLE
Chevrolet Camaro Wild: Ride 3D and others - bad reflections

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1801]
Dupe of https://github.com/citra-emu/citra/issues/1772 ?

[LOG](http://pasted.co/cfb5820a)

![camaro 1](https://cloud.githubusercontent.com/assets/11453507/15274787/6ab24dbe-1abb-11e6-9f91-80e12713d232.JPG)

![camaro 2](https://cloud.githubusercontent.com/assets/11453507/15274788/7485a73c-1abb-11e6-8856-5447226b7034.JPG)
- shadows are fixed with https://github.com/citra-emu/citra/pull/1786

Saw reflections issues also at these games (HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:GLShader::AppendSource:60: Unhandled texture type 1):
- Need for Speed The Run
- AirRace Xeno
- AirRace Speed
- Batman Arkham Origins Blackgate
- Dead or Alive Dimensions
- The Amazing Spider-Man 2

**Comment by wwylele** [comment]
Is this fixed by #3497 ?

**Comment by JohnGodgames** [comment]
looks good too

https://ci.appveyor.com/project/bunnei/citra/build/1.0.7488/job/q3rxjp54xb4jf905/artifacts

<img width="443" alt="camaro 1" src="https://user-images.githubusercontent.com/11453507/37347959-4643ea2a-26d3-11e8-87f5-ab61491663b3.PNG">

**Comment by wwylele** [comment]
Please test this on the latest nightly/master (not canary) and close it if it is fixed, thanks!

**Comment by JohnGodgames** [comment]
I'm closing it as fixed.

<img width="439" alt="camaro" src="https://user-images.githubusercontent.com/11453507/38704833-da265dcc-3ea7-11e8-8da6-0eef43f3ad38.PNG">
