### ISSUE TITLE
Story of Seasons Naming

### ISSUE THREAD

**Issue by sdeborn** [citra-emu/citra#1803]
In the game Story of Seasons. It doesn't let me. A pop-up bubble saying: "Name your character" comes up and when I click to go. Another pop-up appears saying is Citra okay?
Could someone help me?
Thanks in advance!

**Comment by kreedz1** [comment]
people working on citra here don't want you spamming, so ask your questions here [CitraForum](https://discuss.citra-emu.org/)

**Comment by JayFoxRox** [comment]
Closed as invalid because this is a question, not an issue.
Also way too few information provided.

**Comment by sdeborn** [comment]
Sorry, I'll try it there.
