### ISSUE TITLE
Big Hero 6: Battle in the Bay - Unhandled texture type 2 (Shadow2D) / missing shadows

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1804]
Log (critical) says:
`HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:GLShader::AppendSource:60: Unhandled texture type 2`

**3DS:**
![big hero 6 1](https://cloud.githubusercontent.com/assets/11453507/15276637/202d33b6-1aee-11e6-8879-a35b1ad9c30b.JPG)

**Citra:**
![big hero 6 2](https://cloud.githubusercontent.com/assets/11453507/15276638/23e7b94a-1aee-11e6-9940-fe3e90da812b.JPG)

Edit:
updated screen from https://github.com/citra-emu/citra/commit/c4e4fa53d9200bbac34a498d55cde381e3112764

<img width="1920" alt="big 2" src="https://cloud.githubusercontent.com/assets/11453507/20942299/208acda6-bbfb-11e6-8437-dddef24270c4.PNG">

**Comment by benderscruffy** [comment]
LEGO Star Wars III - The Clone Wars (Europe) has an overlay on the top screen during gameplay
HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:GLShader::SampleTexture:206: Unhandled texture type 2
![lego](https://user-images.githubusercontent.com/2696404/32687670-93f02608-c6fc-11e7-897b-97bd34bae2d3.PNG)

**Comment by wwylele** [comment]
What does this look like in software renderer with #3516?

**Comment by JohnGodgames** [comment]
Yeah shadow is there

https://ci.appveyor.com/project/bunnei/citra/build/1.0.7516/job/d5btsuflp1i2xavf/artifacts

<img width="443" alt="big hero" src="https://user-images.githubusercontent.com/11453507/37347272-b9c299e4-26d1-11e8-981c-ae751bc2b3ae.PNG">

**Comment by wwylele** [comment]
Is this fixed on nightly with hardware shader?

**Comment by JohnGodgames** [comment]
@wwylele tested and it's there

![big hero 6](https://user-images.githubusercontent.com/11453507/43076426-82146f8e-8e84-11e8-8f61-20c718ef38c6.JPG)
