### ISSUE TITLE
Error while starting Citra!

### ISSUE THREAD

**Issue by Eirik00** [citra-emu/citra#1805]
I was starting up citra - qt when i got an error that said 

> _Failed to initialize the video core! Please ensure that your GPU supports OpenGL 3.3 and 
 that you have the latest graphics driver_

But this link says (this is my graphics card) [http://delphigl.de/glcapsviewer/gl_generatereport.php?reportID=942](url) that my graphics card supports openGL 4.40!
and i want so badly to play tomodachi life please help

**Comment by JayFoxRox** [comment]
This is an issue-tracker for developers, no user-support here.
Closed as invalid, install proper drivers. Consult [the forum](https://discuss.citra-emu.org/) for more infos.
