### ISSUE TITLE
HW.memory error on KH3D

### ISSUE THREAD

**Issue by nashikun** [citra-emu/citra#1815]
hi everyone
i tried playing kingdom hearts 3d on citra. the rom is decripted and all. when I try to lunch, it shows the following message:
![1](https://cloud.githubusercontent.com/assets/19435889/15370835/9c0e5e80-1d30-11e6-9020-72e01f80b9ea.png)
![2](https://cloud.githubusercontent.com/assets/19435889/15370843/a28c0cd0-1d30-11e6-8eb2-e341a8b0d8c4.png)

any idea on what to do please?

**Comment by jroweboy** [comment]
@nashikun Please don't use the issue tracker for help requests. This is a place for developers and not for users. Visit the forums and ask there instead. https://discuss.citra-emu.org/

**Comment by JayFoxRox** [comment]
Formulated as a question and bad title. (What @jroweboy said)

Closed as invalid.
