### ISSUE TITLE
Fatal error while booting Kirby Triple Deluxe

### ISSUE THREAD

**Issue by SuikaIbuki** [citra-emu/citra#1818]
After updating to the latest version of citra, kirby triple deluxe(which was previously working) is now giving a fatal error.
Other games such as Persona Q and Mario 3D Land works just fine, the only problem is with this game it seems.
Full log: 
Part 1-http://prntscr.com/b5q09u
Part 2- http://prntscr.com/b5q18r
Part 3- [   2.577142] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:125:   Desc: 1023
PC info: http://prntscr.com/b5q1kc

**Comment by wwylele** [comment]
works fine here. it seems you lost the 3ds-dumped file when updating

**Comment by SuikaIbuki** [comment]
Booting the game on a old version of citra still works though.

**Comment by kienhoangtu7** [comment]
Can i have your old "platforms" and "user" because i got the save error but i dont know how to fix

**Comment by JayFoxRox** [comment]
No you can't because those are copyrighted files. Dump your own files.
