### ISSUE TITLE
Style Savvy: Trendsetters - Freezing

### ISSUE THREAD

**Issue by Bobesh8** [citra-emu/citra#1819]
The game freezes in the following areas, strangely only happened once:
Choosing a backdrop in Photo Studio: Unknown virtual address @ 0x00788E60
Turning the tutorial off in Profile Card.

Yes, I assume it will happen in other games as well. The emulator is still in development, after all.

**Comment by JayFoxRox** [comment]
Please provide more info in your first post.
Post a full log and name the exact version (revision) you were using.

**Comment by Bobesh8** [comment]
Where would I find the log?
I'm using an unofficial build, v3 with filtering, by Leo121 (GBATemp member).

**Comment by JayFoxRox** [comment]
We don't support issue reports for those.
We only support offical build (only the most recent nightly to be more precise).

The log is what you see in the terminal / console window which opens with Citra.

Closed as invalid.
