### ISSUE TITLE
Impossible to run the software.

### ISSUE THREAD

**Issue by poile310** [citra-emu/citra#1821]
I do not know if I have it installed. In fact I downloaded the windows version and master citra and I unzipped, but when I execute Citra.exe or Citra-qt.exe, an error message "Citra.exe. - System Error
Unable to start the program because it lacks MSVCP140.dll on your computer. Try reinstalling the program to fix this problem. "And he said he also lacks VCRUNTIME140.dll
I hope you understand me because I'm French. 
![image](https://cloud.githubusercontent.com/assets/19466727/15390036/e9411ec0-1db9-11e6-89aa-2b8d52353942.png) 
![image](https://cloud.githubusercontent.com/assets/19466727/15390043/f5111c5a-1db9-11e6-9453-5ba6066d5f14.png)

**Comment by Kloen** [comment]
https://citra-emu.org/wikis/faq looks for "Citra complains about missing DLLs."

In adittion, this kind of questions goes on: https://discuss.citra-emu.org/

**Comment by JayFoxRox** [comment]
Closed as invalid (what @Kloen said).

**Comment by poile310** [comment]
Thank you for your quick response, I will emulate a game to see if it works in any case the application launches thank you very much.
