### ISSUE TITLE
Qt Config UI Improvements

### ISSUE THREAD

**Issue by MerryMage** [citra-emu/citra#1825]
- Rearrrange items in tabs.
  - Video things should go into a video tab.
- Re-group things in a sensible order.
  - Enhancements like scaled rendering should go in their own group.
- Rearrange config sources into the `config` folder.
- General code cleanup.

**Comment by Subv** [comment]
Is this still relevant?

**Comment by JayFoxRox** [comment]
I guess this is partially done buy also very vaguely defined.

- We have tabs now
- Grouping could be better but probably deserves it's own discussion / issue and more concrete goals
- Config sources [source files?] are named correctly I guess
- Code cleanups in general would be nice, no point in mentioning it

**Comment by MerryMage** [comment]
Closing this because of recent improvements, and also because this is far too vague.
