### ISSUE TITLE
Kingdom Hearts 3D: Shadows look glitched with Scaled Resolution

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#1830]
Tested with af25858. Happens with player, NPCs and enemies in gameplay and cutscenes.

**Scaled Resolution On**
![citra-qt_2016-05-20_08-35-20](https://cloud.githubusercontent.com/assets/17358613/15429514/4368c55a-1e6f-11e6-9336-e704ee8399f0.png)

**Scaled Resolution Off**
![citra-qt_2016-05-20_09-25-26](https://cloud.githubusercontent.com/assets/17358613/15429532/56e6fe76-1e6f-11e6-8899-cc40f8d5bed7.png)

**Comment by wwylele** [comment]
Fixed by #3281 as reported so closing. Feel free to reopen if it is not the case.
