### ISSUE TITLE
Cant Run

### ISSUE THREAD

**Issue by IcyFlameX** [citra-emu/citra#1836]
http://prntscr.com/b6qawf
ROM Pokemon X[Decrypted For Citra Emulator]
Pc Specs
4GB CrossAir Vengance
AMD Radeon HD5450 1GB
AMD A3870 QuadCore Processor

**Comment by MerryMage** [comment]
Pokemon does not run because of an unimplemented feature called cro. This is a known issue.

Please note this issue tracker is not a help forum. Please post to [the Citra forums](https://discuss.citra-emu.org/) in the future.
