### ISSUE TITLE
Yo-Kai Watch: Incorrect Hair Color

### ISSUE THREAD

**Issue by Jobenblue** [citra-emu/citra#1840]
In game you pass a line and your character puts on shoes, when they put on shoes, the hair color becomes pink or really light, when they are supposed to stay brown.  5/21 build. The hair color is supposed to stay brown when the character crosses the line.

**CITRA** (correct hair color, no shoes)
![capture](https://cloud.githubusercontent.com/assets/19492416/15452156/36d1dc0a-1faa-11e6-87e2-ab41eb58f5e8.PNG)

**CITRA** (incorrect color, with shoes on)
![](https://cloud.githubusercontent.com/assets/19492416/15452220/88c2b29e-1fac-11e6-85ba-dd83924abe72.PNG)

**3DS** (Image added by JayFoxRox, taken by JohnGodgames / pcmaker; thanks!)
![capture by JohnGodgames](http://i.imgur.com/joAb49E.jpg)

*Other example:*

**3DS** (left, correct coloring with shoes) vs **CITRA** (right, incorrect, with shoes)
![capture](https://cloud.githubusercontent.com/assets/19492416/15452200/1ba1a922-1fac-11e6-8806-69e36a39f468.PNG)

(Images reordered by JayFoxRox)

---

"Is it the hardware renderer?" It's really dark without HW renderer on, but it looks the hair doesn't change with HW renderer off.
nvidia gtx 970m
But it only happens when you have shoes on, with them off, the color is correct like in the real game.

(Posts moved here by JayFoxRox)

**Comment by Jobenblue** [comment]
![capture](https://cloud.githubusercontent.com/assets/19492416/15452220/88c2b29e-1fac-11e6-85ba-dd83924abe72.PNG)

**Comment by MerryMage** [comment]
I'm assuming the first two pictures are "on hardware" and the lattermost is "in Citra".

**Comment by JayFoxRox** [comment]
Please label what each image shows (3DS / Citra + short info) and wether it's correct or broken. Also mention if you used HW / SW rendering and.
I couldn't work with this

**Comment by Jobenblue** [comment]
"Is it the hardware renderer?" It's really dark without HW renderer on, but it looks the haiir doesn't change with HW renderer off.

**Comment by JohnGodgames** [comment]
I don't think that it's a incorrect color, but just a brighter as on most of other games in citra.

**Comment by Jobenblue** [comment]
But it only happens when you have shoes on, with them off, the color is correct like in the real game.

**Comment by JayFoxRox** [comment]
3e7e8daf5967d30cbef6ed8a3a2459c7caaf8e31 + fix-batching always causes this bug regardless of shoes
master + fix-batching exhibit the shoe problem

I have not yet bisected this or confirmed these tests. Might do that sometime
