### ISSUE TITLE
citra won't open

### ISSUE THREAD

**Issue by boody379** [citra-emu/citra#1841]
everytime i try to open citra it says the procedure entry point_register_onexit_function could not be located in the dyanmic link. what to do?

**Comment by MerryMage** [comment]
This issue tracker is not a help forum. Please post to [the Citra forums](https://discuss.citra-emu.org/) in the future.

That being said:

Take a look at our [FAQ](https://citra-emu.org/wiki/FAQ) under "Citra complains about missing DLLs". Also note that Citra only supports x64 systems (64-bit systems).
