### ISSUE TITLE
Inform user of missing required files & document how to dump them

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#1844]
If a game wants a NAND archive that user didn't place correctly, citra just log some "failed to get a handle for archive" with unreadable IDs. What's worse, if a game wants `shared_font.bin` but it isn't there, citra [just crashes](https://discuss.citra-emu.org/d/253-rune-factory-4-not-starting).
In these cases, citra should inform the user what is missing, and give instructions on dumping those files (or a link to a instruction page, like we did for decrypting). Speak of which, we have 3dsutil, but don't have a clear instruction on using it.

**Comment by JayFoxRox** [comment]
For the time being: https://github.com/citra-emu/citra/wiki/Home-Folder

---

Also keep in mind that this is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead if you have questions regarding this.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

**Comment by FearlessTobi** [comment]
Can we close this? There are now popups to inform the user of missing files.
