### ISSUE TITLE
Paper Mario Sticker Star: interactible graphics prompting to press A does not appear

### ISSUE THREAD

**Issue by aldelaro5** [citra-emu/citra#1847]
This issue that I have is better explained with visuals.

This is what citra display, as you can see, nothing says you can open the door by pressing A near Mario:

![screenshot from 2016-05-23 19 20 56](https://cloud.githubusercontent.com/assets/8932978/15487588/a9a5811e-211c-11e6-953f-723afcb5ba6e.png)

And this is what a real console displays (bear with me with the phone camera, I don;t have a way to capture video directly)

![img_1678](https://cloud.githubusercontent.com/assets/8932978/15487609/dd62b3aa-211c-11e6-82ce-5038d156ad23.JPG)

So the issue here is that this button prompt does not appear on any object it should like being near a sticker for example.

This is the console output:

![screenshot from 2016-05-23 19 26 14](https://cloud.githubusercontent.com/assets/8932978/15487644/1de98ee4-211d-11e6-80e8-de019d4dd4e5.png)

And this is some info about my opengl drivers, I use a build of mesa from some days old:

![screenshot from 2016-05-23 19 26 51](https://cloud.githubusercontent.com/assets/8932978/15487658/3a838122-211d-11e6-8e22-33c0060c0b1b.png)

My OS is Linux Mint 17.3.

**Comment by wwylele** [comment]
this is due to unimplemented geomotry shader.

**Comment by wwylele** [comment]
Should be fixed by #2865. If there is still issue, feel free to comment here / open a new one.
