### ISSUE TITLE
CRO rewriting Pokémon ORAS XY and some games

### ISSUE THREAD

**Issue by gianni9916** [citra-emu/citra#1848]
CRO is need to play without crash in some games like Pokémon ORAS XY , SUPER SMASH BROS 3DS ext ... At that point we are with cro rewriting?

**Comment by JayFoxRox** [comment]
What? No idea what you are trying to say / accomplish.

Closed as invalid because this is not an issue and it's not contributing anything either.
(If you have questions use the forum](https://discuss.citra-emu.org/).
