### ISSUE TITLE
The Denpa Men Series Randomly Freezing

### ISSUE THREAD

**Issue by Vectrex33** [citra-emu/citra#1852]
Since HLE audio was added, The Denpa Men: They Came By Wave no longer works properly in Citra. It randomly freezes, without accepting input, with the music still playing, but sped up. All the log seems to tell me is that Looped Buffers aren't supported by Citra yet, but the game runs fine even with this error appearing. It just happens at random.

Here's a pastebin of the Log: http://pastebin.com/ru5jN2KG

And a Video of said issue: [Video was removed]

Using HEAD-e054e55

**Comment by wwylele** [comment]
Could you please try #1854?

**Comment by Vectrex33** [comment]
I would be willing to test it, but I don't have a build environment set up. Would you mind building for me?

**Comment by legoj15** [comment]
http://www.mediafire.com/download/m6m0y2rikqw69cz/citra-1854-windows-amd64.7z Here's a build of PR 1854 for Windows. I'll remove the link once it has been downloaded to make sure no one uses an outdated version of Citra.

**Comment by Vectrex33** [comment]
This also happens in the Second, and Third games.

**Comment by Vectrex33** [comment]
Pull Request #1854 did NOT help the situation.

**Comment by Vectrex33** [comment]
Just another update, the game still does this on latest nightly as of 06/11/16. No HLE errors in log though.

**Comment by Subv** [comment]
Does this still happen?

**Comment by Vectrex33** [comment]
@Subv Yes, this still occurs as of the latest PR. If it will help (Unlikely, but hey, why not), here's a log from running the first game. http://pastebin.com/gRNFMtaP

**Comment by Subv** [comment]
Does this still happen on the latest master?

**Comment by Vectrex33** [comment]
It seems that the bug, after almost half a year, the bug does no longer occur on the First or second games. I however do not have the ability to test the third right now.

**Comment by Subv** [comment]
I'm closing this then
