### ISSUE TITLE
Mario Kart 7: Crash on first Loading Screen

### ISSUE THREAD

**Issue by Vectrex33** [citra-emu/citra#1853]
Open the game, and it gets stuck at the first Loading Screen. This wasn't an issue in older versions of Citra.

Log: http://pastebin.com/5t4QvSGw

Video: https://www.youtube.com/watch?v=cSxWCXnBrs4

**Comment by wwylele** [comment]
Works fine here on current master c106f71
> [   5.656471] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFileDirectly:119: failed to get a handle for archive archive_id=0x2345678A archive_path=[Binary: 020201009b00040000ffffff02000000]

Seems that you lost your dumped nand file when updating.

**Comment by mailwl** [comment]
may you check #1820 ?
I fix memcopy error in frd:u, which i did in initial implemetation of frd

**Comment by Vectrex33** [comment]
@wwylele What do you mean exactly?

**Comment by wwylele** [comment]
@Vectrex33 find your old version of citra, copy the `user` folder to the new version.

**Comment by Vectrex33** [comment]
I have a user folder already, and I have no backup of said folder.

**Comment by Vectrex33** [comment]
@wwylele I'm guessing I missed a step and need something like a NAND dump?

**Comment by Vectrex33** [comment]
I figured it out. Sorry for the confusion.
