### ISSUE TITLE
Video and Audio Regression

### ISSUE THREAD

**Issue by Jobenblue** [citra-emu/citra#1856]
So I am trying out Yo-Kai Watch (it's the only game I have that works) and as recently as e054e55 (does not happen in 51ee2d2), a few new issues have arisen, seemingly stemming from an intro video/ special scenes. If I let the intro play, all sound cuts off and when I press continue at the title screen (also no audio in menu if cutscene plays), it gets stuck at a black screen. If I skip the intro video quickly enough, sound still works in the menu and I can go into the game, but when I leave the house, triggering a special "welcome to the world of yo-kai" screen (which occurs once per game), the game gets stuck on a black screen and I can't do anything, if "welcome to the world of yo-kai" has already happened, it is possible to leave the house but there is an issue with the audio looping. So basically, e054e55 and newer has issues with the intro video/special scenes/audio, leading to either no audio and cannot get in game, or has audio but cannot leave the house if "welcome to the world of yo-kai" pops up. Also happens the same way if audio is set to null.

Purple log which was not present before during intro video.
![capture](https://cloud.githubusercontent.com/assets/19492416/15591994/fbcb14a4-2365-11e6-9bf7-d8ea6a2050a4.PNG)

Letting intro play, leading to no audio, after hitting continue
![capture](https://cloud.githubusercontent.com/assets/19492416/15592050/4c627fec-2366-11e6-902d-553ec83cd201.PNG)

Ingame with audio
![capture](https://cloud.githubusercontent.com/assets/19492416/15592167/2b7a45ca-2367-11e6-8c9c-224bd6eb8f0d.PNG)

Ingame with audio, causes audio to stop, game still runs.
![capture](https://cloud.githubusercontent.com/assets/19492416/15592206/83766074-2367-11e6-8468-903c671f75ee.PNG)

**Comment by JayFoxRox** [comment]
https://github.com/citra-emu/citra/pull/1854
