### ISSUE TITLE
Finding Nemo: Escape to the Big Blue - Hangs after Story mode is selected

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1859]
[LOG](http://pasted.co/b2e7ded1)

![finding nemo 1](https://cloud.githubusercontent.com/assets/11453507/15625498/bcce0a88-24a8-11e6-8eac-d54e6b78ca39.JPG)

![finding nemo 2](https://cloud.githubusercontent.com/assets/11453507/15625499/c0ed11b8-24a8-11e6-8a35-987919b60ffc.JPG)

**Comment by mailwl** [comment]
log not exists, but looks like https://github.com/citra-emu/citra/issues/1716

**Comment by JohnGodgames** [comment]
Ohh log update.Yeah it has the same blue screen and it can be related...

**Comment by mailwl** [comment]
#1859 fix it

**Comment by JohnGodgames** [comment]
Works on recent master de79b6fc4857fde1df3c8a4a2b38d231f2cc961d
