### ISSUE TITLE
Phineas & Ferb: Quest for Cool Stuff - Hangs at opening screen

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#1861]
[LOG](http://pasted.co/86ffb991)

![phineas](https://cloud.githubusercontent.com/assets/11453507/15625553/a9a64eaa-24aa-11e6-9272-9111a5e83273.JPG)

**Comment by mailwl** [comment]
it second game i saw, which panic after WaitSynchronizationN on GSP::GPU event. I think @wwylele should look at this game
```
.text:001957C4                 LDR             R2, [R4,#0x2C]
.text:001957C8                 MOV             R0, #0xFFFFFFFF
.text:001957CC                 MOV             R1, R0
.text:001957D0                 STMEA           SP, {R0-R2}
.text:001957D4                 MOV             R3, #0
.text:001957D8                 MOV             R2, #1
.text:001957DC                 ADD             R1, SP, #0x30+var_28
.text:001957E0                 ADD             R0, SP, #0x30+var_24
.text:001957E4                 BL              WaitSynchronizationN
.text:001957E8                 MOVS            R1, R0,LSR#31
.text:001957EC                 NOP
.text:001957F0                 BLNE            Panic   ; <<< panic here
```

**Comment by wwylele** [comment]
#1854 doesn't help?

**Comment by mailwl** [comment]
no.
i don't understand why WaitSynchN returns error, if GSP::GPU event for sure exists.
looks like this code is not good:
https://github.com/wwylele/citra/blob/18a5043b7912268f7fd43358e0077ba691fc9d2d/src/core/hle/svc.cpp#L347-L348

**Comment by wwylele** [comment]
@mailwl does it works before #1837 ?

**Comment by mailwl** [comment]
no, the problem not in your PRs. 
I mean, if you look at WaitSynchronizationN now, the game good thing to test

**Comment by wwylele** [comment]
@mailwl got it. Indeed an interesting case

**Comment by wwylele** [comment]
@mailwl @JohnGodgames Try this (I don't have the game so it's just my random guess) : comment out [this two lines](https://github.com/citra-emu/citra/blob/a2c84d5779a80c61adbf07cfce6c37b0952fea84/src/core/hle/kernel/thread.cpp#L546-547) 
```c++
// Don't bother switching to the same thread
if (next == cur)
    return;
```

**Comment by mailwl** [comment]
wow, it's worked!

**Comment by JohnGodgames** [comment]
Yeah, you can get ingame with comment out those 2 lines

![phineas 1](https://cloud.githubusercontent.com/assets/11453507/15627234/a617ba70-24dd-11e6-96d0-9fc04143e7bd.JPG)

![phineas 2](https://cloud.githubusercontent.com/assets/11453507/15627235/abc1c204-24dd-11e6-8b2a-65fa3a9bb4e8.JPG)

**Comment by wwylele** [comment]
Oh really interesting... It is similar to the issue described in #1854. But this happens even with #1854, I don't know why...

**Comment by wwylele** [comment]
By examining the code, I speculate that the following happens:
 - The game runs to a point where all threads are blocked except the GSP thread (the ready queue is empty now)
 - in `RunLoop`- `g_app_core->Run` - `ARM_DynCom::ExecuteInstructions` - `InterpreterMainLoop`, GSP thread calls `WaitSynchronizationN` on GSP event, when GSP event is not signaled yet.
 - the thread sleeps itself and pends a reschedule; `InterpreterMainLoop` exits.
 - in `RunLoop`- `g_app_core->Run` - `ARM_DynCom::ExecuteInstructions` - `AddTicks`, `Advance` is called, and the GSP event is signaled. It wakes up the thread and put it to the ready queue (now the thread is the only item in the queue).
 - `RunLoop` - `Kernel::Reschedule`. Note that the current thread is still the GSP thread (hasn't been scheduled away), and the next ready thread is also the GSP thread (just put by last step), so it `// Don't bother switching to the same thread`, (from now on it is quite similar to that in #1854) which means the thread's PC doesn't get stepped back to call WaitSynchronizationN again.
 - The GSP thread continues to run with `HLE::RESULT_INVALID` as the final return value. When it checks the return value, it `ThrowFatalError`.

**Comment by JohnGodgames** [comment]
Works on recent master de79b6fc4857fde1df3c8a4a2b38d231f2cc961d
