### ISSUE TITLE
三国志 (sangokushi) - Gets stuck after saving game

### ISSUE THREAD

**Issue by fuhuan416** [citra-emu/citra#1872]
> [475.572047] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:69: unknown / unimplemented function 'ControlArchive': port=fs:USER, cmd_buff[1]=0x5, cmd_buff[2]=0x0, cmd_buff[3]=0x0, cmd_buff[4]=0x1, cmd_buff[5]=0x1, cmd_buff[6]=0x1A, cmd_buff[7]=0x8011B10, cmd_buff[8]=0x1C, cmd_buff[9]=0x8011B14

It's 三国志, when i saved in game then i get output information above. Whatever the save/load are both successfully, just after on save/load the emulator will be stuck.

**Comment by mailwl** [comment]
this function does 2 thing: commit the save, and get save timestamp. (This case commit)
Citra does not need to commit the save, so, this function is not a reason of game stuck

**Comment by fuhuan416** [comment]
Thank you for answer of mailwl, at least let me know isn't about save/load issues.
Otherwise after on save/load and output windows nothing happen, no way to know what reason to stuck.

**Comment by Andrix44** [comment]
You could test it with #1748 though.

**Comment by fuhuan416** [comment]
Thanks, i'll test it later.

**Comment by Subv** [comment]
Is this still an issue?

**Comment by mailwl** [comment]
i saw the game, but can not find, how to Save, don't understand japanese :(

**Comment by Subv** [comment]
Could you please re-test this on the latest master?

**Comment by Dragios** [comment]
Please try testing again with the latest nightly. If it does not fix you can try Canary that has PR #5120 and see if this fixes the issue.

**Comment by fuhuan416** [comment]
> Please try testing again with the latest nightly. If it does not fix you can try Canary that has PR #5120 and see if this fixes the issue.

ok, i'll try it later.

**Comment by fuhuan416** [comment]
> Please try testing again with the latest nightly. If it does not fix you can try Canary that has PR #5120 and see if this fixes the issue.

I have lost this game for a long time, but through my netizens, he has this game, feedback to me that this problem has been solved. I think I can close this question. Thank you very much Citra and everyone who has paid for it!
