### ISSUE TITLE
OS X: Logs aren't stored anywhere

### ISSUE THREAD

**Issue by MerryMage** [citra-emu/citra#1876]
Since OS X 10.7, launchd-managed processes no longer have stdout/stderr redirected to the system log. Users are required to open a terminal window to explicitly store logs for error reporting. Perhaps the [`asl`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/asl.3.html) could be used on OS X to make this easier.

**Comment by mailwl** [comment]
sdl2 citra running from terminal show logs.
citraqt running from terminal (not `open citra_qt.app`) shows logs as well

**Comment by MerryMage** [comment]
Closed by #1962.
