### ISSUE TITLE
why doesnt it work?

### ISSUE THREAD

**Issue by jasmineSweetQueen** [citra-emu/citra#1878]
i really wanted to play pokemon X and Y but this keeps happening! 
![image](https://cloud.githubusercontent.com/assets/19741759/15799376/7bd20d9c-2a0f-11e6-8ffe-4ea600754e29.png)

i have all the files here! 
![image](https://cloud.githubusercontent.com/assets/19741759/15799380/8fd5f916-2a0f-11e6-972f-00bfc189fa8e.png)

(please reply back to me)

**Comment by JayFoxRox** [comment]
I'll refer you to #1836 and #1795 and tons of others.
