### ISSUE TITLE
can someone help me

### ISSUE THREAD

**Issue by jasmineSweetQueen** [citra-emu/citra#1880]
Can someone give me a link to a FULL working emulator of a 3ds + with a rom of pokemon Y and alpha sapphire?

**Comment by MerryMage** [comment]
This issue tracker is not a help forum. Please post to [the Citra forums](https://discuss.citra-emu.org/) in the future; or some other user-forum.

**Comment by JayFoxRox** [comment]
Also, you are not allowed to ask for warez, you won't get support when not using legal copies of everything.
Don't bother registering on the forums to ask that - you'll be banned.
