### ISSUE TITLE
Cannot use Nightly Build nor Build with Cmake

### ISSUE THREAD

**Issue by lanessear** [citra-emu/citra#1882]
As soon as I try to read the Nightly Build directory for Windows it tells me the file is corrupted. When I try to build citra with Cmake I hit "configure" and get "error MSB6006: "CL.exe" exited with code 5.".
I have installed everything the readme file said and the windows 8.1 sdk.

**Comment by mailwl** [comment]
btw, citra required 2015 redisriburable?

**Comment by JayFoxRox** [comment]
@mailwl Create a new issue instead or ask on irc.

---

@lanessear: This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid

**Comment by mailwl** [comment]
ah sorry, sorry! i just think, it's nice issue to talk about dependencies on Windows
