### ISSUE TITLE
Broken Build zip archive

### ISSUE THREAD

**Issue by IceLancerSR** [citra-emu/citra#1885]
citra-20160602-8df4283-windows-amd64.7z.filepart
link reads as filepart of 2.4 mb only
its broken archive
link from nightly 3rd june

**Comment by MerryMage** [comment]
Thanks for the issue report! We know about this already.

I'll leave this open until this is fixed, just so that nobody opens another issue.

**Comment by archshift** [comment]
I was going to let the problem fix itself with another commit being pushed to the repo, but since that hasn't happened in two days I just manually removed the faulty build.
