### ISSUE TITLE
Mario Kart 7 - particles are black, or copy HUD elements

### ISSUE THREAD

**Issue by mariohackandglitch** [citra-emu/citra#1887]
![2016-06-06_17-22-29](https://cloud.githubusercontent.com/assets/10946643/15827501/adae1754-2c0b-11e6-9c9d-09afc47f2317.png)
![2016-06-06_17-23-26](https://cloud.githubusercontent.com/assets/10946643/15827503/adafb028-2c0b-11e6-9768-264f9d1484d9.png)
![2016-06-06_17-24-03](https://cloud.githubusercontent.com/assets/10946643/15827504/adb0c58a-2c0b-11e6-8e40-b66f2b3c9311.png)
![2016-06-06_17-21-29](https://cloud.githubusercontent.com/assets/10946643/15827502/adb008fc-2c0b-11e6-9f92-71629a0fa3b1.png)

The photos are taken from CTGP-7 (a romhack), however, this issue also happens with unmodded game.

**Comment by JayFoxRox** [comment]
Known issue #1681 ; known fix #1688 (closed due to incompleteness).

We'll keep this opened because "1 issue per game". Thanks for the bug report. Please include the commit / revision you tested this on; possibly also a log (not applicable this time because this is a known issue).

**Comment by mariohackandglitch** [comment]
Commit: 63557e3

**Comment by Tasosgemah** [comment]
Still same issue in latest Nightly (9b6dbe9)

For some reason i didn't have this problem before updating from an older build (ca0281b)

**Comment by B3n30** [comment]
Is this fixed?

**Comment by FearlessTobi** [comment]
Can confirm the problem to be fixed in latest nightly.
