### ISSUE TITLE
when i open pokemon x in citra it shows citra qt has stopped working. ihave attached screenshot showing error.please help

### ISSUE THREAD

**Issue by ravishankar577** [citra-emu/citra#1888]
![screenshot 1](https://cloud.githubusercontent.com/assets/19783045/15831633/321778ac-2c3c-11e6-8003-4ae876b6fad8.png)

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game, pirated 3DS bios files, unofficial or old builds.

**Also note that we do not support Pokemon. Pokemon is NOT supported [and not working](https://github.com/citra-emu/citra/issues/1795); no version, not X, not Y, not ORAS, nothing. Come back in a couple of months but don't expect anything.**

---

Closed as invalid

**Comment by mailwl** [comment]
Is it possible to stick topics like this on the top?
But, maybe it doesn't help. In Russia is good proverb about this: "Chukchi not the reader, Chukchi - a writer". Sorry this idiom hard to translate to english in right way
