### ISSUE TITLE
Inazuma Eleven Go Shadow - ThrowFatalError

### ISSUE THREAD

**Issue by Hideyuki191** [citra-emu/citra#1889]
Whenever this error shows up, inazuma eleven go shadow's audio stops and the game crashes after a while.

**Comment by wwylele** [comment]
Please provide full log. And probably #1869 can help?

**Comment by Hideyuki191** [comment]
[Fatalerror.txt](https://github.com/citra-emu/citra/files/302249/Fatalerror.txt)

**Comment by Hideyuki191** [comment]
[ 625.563874] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:70: unknown / unimplemented function 'InvalidateDCache': port=dsp::DS
P, cmd_buff[1]=0x608FA0, cmd_buff[2]=0x4000, cmd_buff[3]=0x0, cmd_buff[4]=0xFFFF
8001
[ 627.787180] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:70: unknown / unimplemented function 'InvalidateDCache': port=dsp::DS
P, cmd_buff[1]=0x608FA0, cmd_buff[2]=0x4000, cmd_buff[3]=0x0, cmd_buff[4]=0xFFFF
8001
[ 631.986516] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:70: unknown / unimplemented function 'InvalidateDCache': port=dsp::DS
P, cmd_buff[1]=0x608FA0, cmd_buff[2]=0x4000, cmd_buff[3]=0x0, cmd_buff[4]=0xFFFF
8001
[ 634.169999] Audio.DSP <Error> audio_core\hle\source.cpp:DSP::HLE::Source::Dequ
eueBuffer:249: Looped buffers are unimplemented at the moment
[ 634.997355] Audio.DSP <Error> audio_core\hle\source.cpp:DSP::HLE::Source::Dequ
eueBuffer:249: Looped buffers are unimplemented at the moment
[ 636.318158] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:70: unknown / unimplemented function 'InvalidateDCache': port=dsp::DS
P, cmd_buff[1]=0x608FA0, cmd_buff[2]=0x4000, cmd_buff[3]=0x0, cmd_buff[4]=0xFFFF
8001
[ 638.241266] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFata
lError:108: Fatal error!
[ 638.241859] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFata
lError:116: PID: 0x00000000_0x00000000
[ 638.242228] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFata
lError:117: REV: 41015
[ 638.242783] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFata
lError:118: AID: 0x00000000_0x00000000
[ 638.243188] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFata
lError:119: ADR: 0x0054E804
[ 638.243535] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFata
lError:121: RSL: 0xFFFFFFFF
[ 638.244054] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFata
lError:122:   Level: 31
[ 638.244400] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFata
lError:123:   Summary: 63
[ 638.244763] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFata
lError:124:   Module: 255
[ 638.245124] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFata
lError:125:   Desc: 1023

**Comment by MerryMage** [comment]
> RSL: 0xFFFFFFFF

Try the [following version (master-51ee2d2)](https://builds.citra-emu.org/citra/nightly/windows-amd64/citra-20160521-51ee2d2-windows-amd64.7z) or merge #1869 above. Please report back if that fixes things.

**Comment by Hideyuki191** [comment]
The master-51ee2d2 worked
Thanks, game is still very slow but the sound is at least following the speed

**Comment by Hideyuki191** [comment]
The master-51ee2d2 worked
Thanks, game is still very slow but the sound is at least following the speed

**Comment by Hideyuki191** [comment]
The master-51ee2d2 worked
Thanks, game is still very slow but the sound is at least following the speed

**Comment by Hideyuki191** [comment]
The master-51ee2d2 worked
Thanks, game is still very slow but the sound is at least following the speed

**Comment by Hideyuki191** [comment]
The master-51ee2d2 worked
Thanks, game is still very slow but the sound is at least following the speed

**Comment by Hideyuki191** [comment]
The master-51ee2d2 worked
Thanks, game is still very slow but the sound is at least following the speed

**Comment by Hideyuki191** [comment]
The master-51ee2d2 worked
Thanks, game is still very slow but the sound is at least following the speed

**Comment by Hideyuki191** [comment]
The master-51ee2d2 worked
Thanks, game is still very slow but the sound is at least following the speed

**Comment by Hideyuki191** [comment]
The master-51ee2d2 worked
Thanks, game is still very slow but the sound is at least following the speed

**Comment by MerryMage** [comment]
Reopening issue; to close when #1869 is merged.

**Comment by wwylele** [comment]
#1869 is merged
