### ISSUE TITLE
guys help!!!!!!!!

### ISSUE THREAD

**Issue by Lovebig** [citra-emu/citra#1892]
when i install citra something weird happened!
i wanted to play tomodachi life but no this happened!
![help me](https://cloud.githubusercontent.com/assets/19827692/15913380/4af2316c-2de2-11e6-8b2d-83a0586bd8d1.PNG)
I JUST WANTED TO PLAY TOMODACHI LIFE,I HAVE Microsoft Visual C++ 2010 Redistributable Package (x86)! HOW I AM SUPPOSED TO FIX THE ERROR? WHAT I AM SUPPOSED TO DO? I WANT TO PLAY TOMODACHI LIFE SO BAD!!!!!!!!!!!!!!!

**Comment by kreedz1** [comment]
entitled much ? calm down, man Citra is still under development.

**Comment by Leo626** [comment]
See the [FAQ](https://github.com/citra-emu/citra/wiki/FAQ). This is missing DLLs. You need to install the x64 variant (vc_redist.x64.exe) of Visual C++ Redistributable for Visual Studio 2015 from Microsoft.

Also next time use the forums for support.

**Comment by Lovebig** [comment]
when i install the vc_redistx64.exe this happens.
![help me again](https://cloud.githubusercontent.com/assets/19827692/15913947/f525e0d6-2de5-11e6-8975-dbdd8980bc39.PNG)

**Comment by JayFoxRox** [comment]
You probably have a 32-Bit OS.
Continue this [discussion on the forum](https://discuss.citra-emu.org/) please if it's not the case.
