### ISSUE TITLE
Pokemon oras crashes when i try to cross petalburg woods and also when i use sweet scent

### ISSUE THREAD

**Issue by kirilot** [citra-emu/citra#1901]
Pokemon oras crashes whenever i try to leave petalburg woods to enter rustboro city.....and whenever i use surskits sweet scent move it crashes immediately but when i used a saved game i downloaded from the Internet and flew to the place next to rustboro city it worked fine....so please fix this in your next update...been waiting for a while now.

**Comment by mailwl** [comment]
log of crash?

**Comment by archshift** [comment]
Sorry, but we don't support unmerged branches to master, such as the CRO branch that is required to play Pokemon.

Feel free to post issues for official Citra builds, though!
