### ISSUE TITLE
Hardware renderer issue

### ISSUE THREAD

**Issue by Armonite** [citra-emu/citra#1903]
When I boot Pokemon X using the hardware renderer option checked it works but there are no colors everything is black and blue and the game seems to run at 50% speed but after sometime when I de-select the "Use hardware renderer option" I can see all the colors and everything is fine but when I move my character the game almost seems unplayable it runs at 2-4 FPS.
I'm attaching 2 screens with this post.
Please let me know what the problem is and thanks in advance.
Regards,
Armonite
![untitled](https://cloud.githubusercontent.com/assets/12455548/15990374/4b5db4c2-30ae-11e6-9ab5-bcff06f6bee3.png)
![unti](https://cloud.githubusercontent.com/assets/12455548/15990380/5525012c-30ae-11e6-9549-12a1ca20fc04.png)

**Comment by mailwl** [comment]
not official build, go to citra-emu.org

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game, pirated 3DS bios files, unofficial or old builds.

**Also note that we do not support Pokemon. Pokemon is NOT supported [and not working](https://github.com/citra-emu/citra/issues/1795); no version, not X, not Y, not ORAS, nothing. Come back in a couple of months but don't expect anything.**

---

Closed as invalid
