### ISSUE TITLE
List of Game that Citra support

### ISSUE THREAD

**Issue by Ninnjie** [citra-emu/citra#1908]
Hi. Im new with Citra emu . can i know the list game that citra can support

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid

**Comment by mailwl** [comment]
btw, it's good to know current Citra comparibility.
what do you think about log sending?
