### ISSUE TITLE
Bravely Second End Layer - Stop emulation when leaving status menu

### ISSUE THREAD

**Issue by whymsical210** [citra-emu/citra#1910]
While testing out Bravely Second on Citra, I came across the fact that exiting the status screen seems to just stop the emulation. Not really crash, but just stops, like it's been paused. I have pictures of the console log and the game screen itself for your viewing. 

console log:
![log](http://i.imgur.com/544F1BJ.png)

screenshot of actual game when stuck:
![screenshot](http://i.imgur.com/nNFgGEV.png)

This was on a build that's about 2 days old (The commit used was 63557e3).
I tested on a current nightly (6/14/2016) and as well does it there.

(Markup and style fixes by JayFoxRox)

**Comment by whymsical210** [comment]
The commit used  was 63557e3

**Comment by SteveSsSsS** [comment]
Same problem here, only crashes when i press menu key.
![screenshot_37](https://cloud.githubusercontent.com/assets/21972033/18225443/dc43392e-71f1-11e6-8f67-eb92b14b720e.png)

**Comment by Marborao** [comment]
same here

**Comment by Marborao** [comment]
to bad, becouse the rest of game seems to be working perfectly

**Comment by Marborao** [comment]
Same here. a shame because the rest of the game seems to work perfectly

**Comment by Strange09** [comment]
Been trying on the Bleeding Edge and it wont even open the game.  Shame since it looked like it was going to work perfectly as the Default.

**Comment by JayFoxRox** [comment]
(Removed comments by @Marborao and @Strange09 which didn't contribute anything to the discussion - note that we don't support Bleeding Edge either)

**Comment by wwylele** [comment]
Closed by #2188
