### ISSUE TITLE
Citra freez/ in pokemon Omega ruby 

### ISSUE THREAD

**Issue by Zfrenchguy** [citra-emu/citra#1913]
![citra bug](https://cloud.githubusercontent.com/assets/19976969/16119972/298f8234-33de-11e6-816c-0ce1f95efabf.png)

citra can't work properly each time i try to get out of this forest; can someone help me please? Everything is shown on the picture. When i try to get out the forest the screen become black but the sound continue

**Comment by archshift** [comment]
Sorry, but if you're running a Pokemon game you're using an unofficial and unsupported Citra build. We can't help you there.

Feel free to post issue reports for our nightly builds, though, which are available at [our website](https://citra-emu.org).
