### ISSUE TITLE
crash when try to play Attack on Titan Humanity in Chains USA

### ISSUE THREAD

**Issue by asdaf5678** [citra-emu/citra#1918]
when i try to play this game it shows that error, it's something that i can do?
![sin titulo](https://cloud.githubusercontent.com/assets/19938053/16151195/f7d457ba-349b-11e6-97b6-5135c9fad9d6.png)

**Comment by Leo626** [comment]
Boots for me with 251457b. It looks like you don't have your [Home folder](https://github.com/citra-emu/citra/wiki/Home-Folder) cause I get that error in the log and crash when I removed mine.

**Comment by JayFoxRox** [comment]
I'll close this and link you to #1844
