### ISSUE TITLE
VFP regression

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#1919]
A regression caused by https://github.com/citra-emu/citra/pull/1810/commits/edf30d84cc0e8299d61c98f5bb40a6428d1576bc (PR #1810). This commit was mean to be a clean-up but actually changed the behaviour.
Can be seen in _Kid Icarus: Uprising_ (need stub CECD service to boot), where the regression causes the game freeze.

**Comment by JayFoxRox** [comment]
Context from irc:

```
wwylele: JayFoxRox: gdmk reports me a "regression" caused by https://github.com/citra-emu/citra/pull/1810/commits/edf30d84cc0e8299d61c98f5bb40a6428d1576bc, which causes game freeze/crash. Not sure if it is a regression itself, or just revealed another hidden bug.
wwylele: btw he doesn't speak English well
...
wwylele: https://github.com/JayFoxRox/citra/blob/edf30d84cc0e8299d61c98f5bb40a6428d1576bc/src/core/arm/skyeye_common/vfp/vfpdouble.cpp#L100 this one is suspicious, exceptions is always 0 here
Wright is now known as PhoenixWright
JayFoxRox: it would indeed change behaviour here! https://github.com/citra-emu/citra/pull/1810/commits/edf30d84cc0e8299d61c98f5bb40a6428d1576bc#diff-a161405907efe94bbb9c676954b3d3a4L538
JayFoxRox: there are also more spots, good catch!
JayFoxRox: however, the comment implies that this is supposed to handle inf and NaN - which is not what their check does..
***JayFoxRox wonders if we always have to respect the exception bits or only where it was passed to that function + if we can also ditch the exception thing and check for actual inf / nan instead
JayFoxRox: it looks like they only want to check for vd->significant >= 0
```

I think this is a simple fix but I might be wrong

**Comment by JayFoxRox** [comment]
Does this affect the JIT too @MerryMage ?

**Comment by MerryMage** [comment]
@JayFoxRox No; the JIT has an independent VFP implementation.

**Comment by wwylele** [comment]
Closed this as the issue is detailed documented in #2680 and #2681

**Comment by JayFoxRox** [comment]
I believe this was the better bug report because reverting my faulty changes should make things work again? The new issues sound like there is something fundamentally wrong?

**Comment by wwylele** [comment]
I probably didn't understand these issues and recognized them as the same one... I'll leave this to @Subv to decide whether they are the same (and reopen this if not)

**Comment by Subv** [comment]
At first glance it's hard to know if they're the same issue, somebody should test the changes proposed in #2680 and #2681 (And add them to vfpdouble.cpp too) to verify if Kid Icarus works with them.
