### ISSUE TITLE
Soundtouch missing CMakeLists.txt

### ISSUE THREAD

**Issue by zero17333** [citra-emu/citra#1920]
"The source directory

/home/user/citra/externals/soundtouch

does not contain a CMakeLists.txt file."

Is this a bug found only on Linux? Did someone forget it?

**Comment by legoj15** [comment]
It's on Windows, I can say that much.

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

https://github.com/citra-emu/citra/wiki/Building-For-Linux

You did not use the `--recursive` option.
You can still fix it by doing

```
git submodule init 
git submodule update
```

---

Closed as invalid
