### ISSUE TITLE
Citra Pokemon X Game Start Crash

### ISSUE THREAD

**Issue by thehunter202** [citra-emu/citra#1924]
When attempting to load up Pokemon X 3ds rom I get this error:
I replaced <> with ()

 [   4.083611] Service.APT (Warning) core\hle\service\apt\apt.cpp:Service::APT::GetLockHandle:115: (STUBBED) called handle=0x00038009 applet_attributes=0x00000000
[   4.086686] Service.NDM (Warning) core\hle\service\ndm\ndm.cpp:Service::NDM::OverrideDefaultDaemons:198: (STUBBED) default_daemon_bit_mask=0x0000000F
[   4.091368] Service.NDM (Warning) core\hle\service\ndm\ndm.cpp:Service::NDM::SuspendDaemons:84: (STUBBED) daemon_bit_mask=0x00000009
[   4.094337] Service.APT (Warning) core\hle\service\apt\apt.cpp:Service::APT::Enable:123: (STUBBED) called attributes=0x00000000
[   4.098421] Service.APT (Warning) core\hle\service\apt\apt.cpp:Service::APT::GlanceParameter:238: called app_id=0x00000300, buffer_size=0x00001000
[   4.100759] Service.APT (Warning) core\hle\service\apt\apt.cpp:Service::APT::NotifyToWait:98: (STUBBED) app_id=768
[   4.103096] Service.APT (Warning) core\hle\service\apt\apt.cpp:Service::APT::ReceiveParameter:216: called app_id=0x00000300, buffer_size=0x00001000
[   4.107555] Service.APT (Warning) core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:304: (STUBBED) called command=0x00000007, buffer1_size=0x00000004, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF40, buffer2_addr=0x0FFFFF0C
[   4.111692] Service.APT (Warning) core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:304: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF08, buffer2_addr=0x0FFFFF0C
[   4.118003] Service.FS (Warning) core\hle\service\fs\fs_user.cpp:Service::FS::InitializeWithSdkVersion:694: (STUBBED) called unk1=0x050200C8, unk2=0x00000020, unk3=0x0007001A
[   4.123672] Service (Error) core\hle\service\service.cpp:Service::Interface::SyncRequest:70: unknown / unimplemented function 'Subscribe': port=srv:, cmd_buff[1]=0x209

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game, pirated 3DS bios files, unofficial or old builds.

**Also note that we do not support Pokemon. Pokemon is NOT supported [and not working](https://github.com/citra-emu/citra/issues/1795); no version, not X, not Y, not ORAS, nothing. Come back in a couple of months but don't expect anything.**

---

Closed as invalid
