### ISSUE TITLE
GPL not included with nightly builds

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra#1925]
Why don't we mention the GPL anywhere on https://citra-emu.org/page/download and why isn't the license text included in the nightly builds?

(There were a variety of GPL violations lately with unofficial builds - but really, I can't blame them if we don't set a good example)

**Comment by archshift** [comment]
It's just a master of copying the file into the compressed folder using Travis.

**Comment by JayFoxRox** [comment]
neobrain said:

> as far as I recall, while our source claims to be GPLv2+, our binaries are actually either only GPLv2 or GPLv3. I'm not sure which one it is. ... lol great, https://github.com/citra-emu/citra/issues/1279 implies GPLv2-only, https://github.com/citra-emu/citra/issues/1280 implies GPLv3-only

We should resolve this soon.
For now I've changed the build script in my PR (referenced above) to include license.txt and README.md (whatever those may indicate). In the future we'll have to change those files to reflect the new license information.
But including *anything* about GPL (even if slightly off) is better than not including any license information at all.

**Comment by JayFoxRox** [comment]
license.txt and README.md are included in new nightly builds now as #1926 was merged.
The other issue remains but it's worth another issue.
