### ISSUE TITLE
Unable to build nightly for maybe a week

### ISSUE THREAD

**Issue by John-Gee** [citra-emu/citra#1931]
Hello,

I'm using Arch Linux with GCC6 and I have not been able to build citra git lately without hacking a certain file.

By default I get errors like these:

src/citra/src/citra_qt/configure_audio.cpp: In constructor ‘ConfigureAudio::ConfigureAudio(QWidget*)’:
src/citra/src/citra_qt/configure_audio.cpp:14:12: error: ‘make_unique’ is not a member of ‘std’
         ui(std::make_unique<Ui::ConfigureAudio>();"

Removing -std=gnu++11  in src/citra_qt/CMakeFiles/citra-qt.dir/flags.make fixes that.
I am not sure what generates that file and why there is -std=c++1y and then -std=gnu++11.

relevant line:
"CXX_FLAGS = -march=native -O2 -pipe -fstack-protector-strong -fstack-check -flto=8  -std=c++1y -Wno-attributes -msse4.1 -O3 -DNDEBUG -fPIC -pthread -std=gnu++11"

I'd be happy to test anything you can think of.
In case it helps, my system CXX_FLAGS is:
"-march=native -O2 -pipe -fstack-protector-strong -fstack-check -flto=$(nproc)"

**Comment by Enverex** [comment]
Ditto, the compilation worked a week ago but now fails with that error.

```
/src/citra/src/citra_qt/configure_audio.cpp: In constructor ‘ConfigureAudio::ConfigureAudio(QWidget*)’:
/src/citra/src/citra_qt/configure_audio.cpp:14:12: error: ‘make_unique’ is not a member of ‘std’
         ui(std::make_unique<Ui::ConfigureAudio>())
            ^~~
/src/citra/src/citra_qt/configure_audio.cpp:14:47: error: expected primary-expression before ‘>’ token
         ui(std::make_unique<Ui::ConfigureAudio>())
                                               ^
/src/citra/src/citra_qt/configure_audio.cpp:14:49: error: expected primary-expression before ‘)’ token
         ui(std::make_unique<Ui::ConfigureAudio>())
                                                 ^
make[2]: *** [src/citra_qt/CMakeFiles/citra-qt.dir/build.make:487: src/citra_qt/CMakeFiles/citra-qt.dir/configure_audio.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:724: src/citra_qt/CMakeFiles/citra-qt.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

**Comment by John-Gee** [comment]
I digged a bit more and it seems to be coming from:
src/citra_qt/CMakeLists.txt

removing qhexedit and ${CITRA_QT_LIBS} from their respective target_link_librairies calls removes the extra and wrong -std.

Now looking what these are wrong!

**Comment by John-Gee** [comment]
I am on Qt 5.7.0, how about you @Enverex ?
I updated to it about a week ago, so just wondering if that's why.

**Comment by jroweboy** [comment]
I just got my Arch vm setup, and I'm looking into this as well. I was on cmake 3.5 and didn't have any issues, but I think you are onto something that its a change in QT 5.7's cmake files that broke it.

**Comment by John-Gee** [comment]
Thank you for helping!

**Comment by jroweboy** [comment]
It'd be easier to talk about this in IRC if you are available to hop on for a bit. I think its actually something to do with Cmake by looking at this page https://cmake.org/cmake/help/v3.1/manual/cmake-compile-features.7.html#manual:cmake-compile-features(7) I'm guessing that the OpenGL in QT requests a compiler feature and cmake interprets that to be gnuc++11

**Comment by John-Gee** [comment]
jroweboy found the issue in this Qt commit:
http://code.qt.io/cgit/qt/qtbase.git/commit/src?id=aaf0b72a816ba430442d4ea956db95fa8e286e9f

adding "set_property(TARGET citra-qt PROPERTY CXX_STANDARD 14)" in the citra-qt CMakeLists.txt works, or set(CMAKE_CXX_STANDARD 14) in the first CMakeLists.txt works around the problem.

With both we still have the double (and different) -std definition, but it shouldn't prevent it from compiling anymore.

**Comment by yuriks** [comment]
If we set either of these variables, then we don't need to add `-std=c++14` manually anymore. (Assuming all CMake versions we support can do C++14.)

**Comment by Shuliyey** [comment]
I got this problem when installing citra-git throught yaourt

when you do **cmake** you can pass the **-DCMAKE_CXX_STANDARD_REQUIRED=NO** and **-DCMAKE_CXX_STANDARD=14** flag.

This way citra should compile.

For yaourt/makepkg, this change can be made in the PKGBUILD file
Details on this workaround for yaourt/makepkg
https://github.com/citra-emu/citra/issues/1955#issuecomment-233106336

**Comment by jroweboy** [comment]
@Shuliyey I actually have that fix already in the PR here https://github.com/citra-emu/citra/pull/1936 But thanks for putting in the effort to find that :) I just need to test one more thing to make sure it works in OSX and then its going to be merged to master

**Comment by JayFoxRox** [comment]
#1936 got merged - Is this fixed for you @John-Gee / @Shuliyey ?

**Comment by John-Gee** [comment]
It is!
Thank you.
