### ISSUE TITLE
shin megami tensei IV - freeze

### ISSUE THREAD

**Issue by dorbs35** [citra-emu/citra#1934]
hey
when I try to play the game, my game freeze at the point after choosing the protagonist name
followed by those messages:

![image](https://cloud.githubusercontent.com/assets/20215155/16472555/92ea6a7a-3e6d-11e6-83bf-9af42aaabbfa.png)

![image](https://cloud.githubusercontent.com/assets/20215155/16472565/a9bab304-3e6d-11e6-89ea-28f066d5be30.png)

anyone maybe know a solution for the problem?

**Comment by Leo626** [comment]
That nightly build is outdated. Try the latest one. I believe #1869 which was merged recently fixed it.

**Comment by dorbs35** [comment]
thank you very much :)

**Comment by wwylele** [comment]
It's reopened because the issue was not being fixed?

**Comment by dorbs35** [comment]
hey
#1869 actually did not fix the problem...
I don't know what I'm doing wrong

**Comment by Leo626** [comment]
I tested 9cde5cb and I it freezes after choosing name with that error in the log. With de79b6f, it doesn't.

![citra-qt_2016-06-30_14-17-17](https://cloud.githubusercontent.com/assets/17358613/16499338/f2223008-3ecd-11e6-9a24-04e5b3931bc5.png)

**Comment by dorbs35** [comment]
The problem is solved
thank you so much for the help Leo626 :)
