### ISSUE TITLE
Several games with partial/cut-off rendering on the bottom screen

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#1938]
Affected game: Kung Fu Panda - SLL
Appears to be a regression from #1933. Tested with Nvidia GPU.

![kp1](https://cloud.githubusercontent.com/assets/17358613/16545623/68771174-40fe-11e6-87ba-732290cd632d.png)
![kp2](https://cloud.githubusercontent.com/assets/17358613/16545624/6ad5406c-40fe-11e6-9f7d-d254610502e5.png)
[LOG](http://clipboard.space/clip/ggye8KrWjnHPpg551keq)

**Comment by Subv** [comment]
Ah, I remember having a bug like this in ALBW with the first implementation of scissor i had, it had to do with the viewport offsets not being taken into account / affecting the scissor. Not sure if that's the case here.

**Comment by yuriks** [comment]
I tested ALBW here and it renders correctly, so whatever it is must be a different bug from last time.

**Comment by wwylele** [comment]
![default](https://cloud.githubusercontent.com/assets/4592895/16987433/e596333a-4e94-11e6-99c9-6fc58914f1fc.PNG)
This regression is also seen in mii maker

**Comment by wwylele** [comment]
(Sorry for late test) mii maker shows normally under software renderor.

**Comment by JohnGodgames** [comment]
There are next what I found:

![moco](https://cloud.githubusercontent.com/assets/11453507/18228888/db8ba794-7261-11e6-97ff-3e395ba68056.PNG)
![lang](https://cloud.githubusercontent.com/assets/11453507/18228890/db8c075c-7261-11e6-90da-6f7bb5471b58.PNG)
![farm 2](https://cloud.githubusercontent.com/assets/11453507/18228891/db8ce6cc-7261-11e6-82ec-93053bc43e71.PNG)
![farm](https://cloud.githubusercontent.com/assets/11453507/18228889/db8bd34a-7261-11e6-8891-4ec6b1143919.PNG)
![etr 1](https://cloud.githubusercontent.com/assets/11453507/18228893/db90f226-7261-11e6-996a-ffd7b286b008.PNG)
![kartz](https://cloud.githubusercontent.com/assets/11453507/18228892/db8efa02-7261-11e6-816f-2cef43d85034.PNG)
![doors](https://cloud.githubusercontent.com/assets/11453507/18228895/dba42652-7261-11e6-8c56-41f035e08ac2.PNG)
![castle 2](https://cloud.githubusercontent.com/assets/11453507/18228894/dba1526a-7261-11e6-9a93-4244b0940f66.PNG)
![castle](https://cloud.githubusercontent.com/assets/11453507/18228896/dba543a2-7261-11e6-8117-3edefc528230.PNG)
![bella](https://cloud.githubusercontent.com/assets/11453507/18228899/dba6a4c2-7261-11e6-86a5-1ac0b66c0d03.PNG)
![aqua](https://cloud.githubusercontent.com/assets/11453507/18228897/dba5a554-7261-11e6-96d6-9eda1727caa8.PNG)
![viking](https://cloud.githubusercontent.com/assets/11453507/18228898/dba6164c-7261-11e6-89d0-fad7122af36b.PNG)
![link battle](https://cloud.githubusercontent.com/assets/11453507/18228900/dbbaa490-7261-11e6-9b2c-d2127c55b67e.PNG)
![navy](https://cloud.githubusercontent.com/assets/11453507/18228901/dbbaff80-7261-11e6-901d-a58106c13a42.PNG)

**Comment by yuriks** [comment]
I tested #2083 against Mii Maker. Let me know if it doesn't fix any of the other games.

**Comment by Leo626** [comment]
Fixes Kung Fu Panda - SLL.
