### ISSUE TITLE
citra keeps crashing 

### ISSUE THREAD

**Issue by rudyee** [citra-emu/citra#1941]
my citra keeps crashing as soon as i load pokemoon x .it stops working

**Comment by jroweboy** [comment]
Pokemon X does not work. A simple search of this issue tracker would have shown you that. Here is the 16 other previous issues that people have opened about it https://github.com/citra-emu/citra/issues?utf8=%E2%9C%93&q=is%3Aclosed%20label%3Ainvalid%20pokemon

Watch the official youtube for videos. When pokemon is finally supported, I can almost guarantee that a video will be made about it. Until then, it doesn't work, and asking about it here isn't going to help :)

**Comment by MerryMage** [comment]
Please read the [FAQ](https://citra-emu.org/wiki/FAQ).

Do note this issue tracker is not a help forum. Please post to [the Citra forums](https://discuss.citra-emu.org/) in the future.
