### ISSUE TITLE
Unable to build under MinGW 64

### ISSUE THREAD

**Issue by emmauss** [citra-emu/citra#1943]
i am unable to build under MingGW 64. here is the log
http://pastie.org/10902627

I set cmake to generate with MinGw makefiles, and my PATH to MinGw/bin is set.
Building master

**Comment by sem-nome** [comment]
The log says "Hi, you don't have threading library".

**Comment by jroweboy** [comment]
Citra (currently) doesn't compile with Mingw64, but the changes to get it to compile are pretty small. https://github.com/citra-emu/citra/pull/1906 You can pull that and it should be enough to get it to compile.

**Comment by JayFoxRox** [comment]
This is fixed I believe.
