### ISSUE TITLE
Controls mapped to letters don't work while keyboard language set to Arabic 

### ISSUE THREAD

**Issue by gilatino** [citra-emu/citra#1945]
When I set my keyboard language to Arabic, the controls mapped to letters don't work. Arrow keys and numbers work,  This doesn't happen in Dolphin or Desmume. I wonder if this happens in other languages. This problem also happens in #1900. With #1900 when I map them in the input tab while my keyboard set to Arabic, The letters are in Arabic and then they work.
![image 3s](https://cloud.githubusercontent.com/assets/17504785/16726862/1db41ee2-4767-11e6-9641-2d40ae17467d.png)

**Comment by mailwl** [comment]
related with https://github.com/citra-emu/citra/issues/1707 ?

**Comment by gilatino** [comment]
Yes, I think it is same issue. Maybe I should close this.
