### ISSUE TITLE
ARM: translation cache never actually clears

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#1946]
[trans_cache_buf_top](https://github.com/citra-emu/citra/blob/master/src/core/arm/dyncom/arm_dyncom_trans.cpp#L13) never clears to zero after starting up. It keeps growing when one repeats to start and stop a game (which will eventually crash with "Translation cache is full", I think).

~~Also `trans_cache_buf` and `trans_cache_buf_top` shouldn't be just global. IMO they should belong to a process.~~ Why do we even need `trans_cache_buf`? We can just let each element in `instruction_cache` manage a buffer itself

**Comment by MerryMage** [comment]
> Why do we even need trans_cache_buf? We can just let each element in instruction_cache manage a buffer itself

Having a contiguous block of memory (with the next element to access immediately next in memory) provides [good data locality and faster memory access](http://bitbashing.io/memory-performance.html).

**Comment by yuriks** [comment]
It also makes allocation very fast, because here it's just using a linear allocator. (Incrementing a pointer.)

**Comment by MerryMage** [comment]
Closed by #1948.
