### ISSUE TITLE
(possible regression) hard crash upon booting omega ruby

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#1949]
the game was working a couple of months ago now it it straight out crash citra, i don't see anything fun in the console either.

![capture2](https://cloud.githubusercontent.com/assets/12820322/16822311/2ff0e2ee-4964-11e6-9acf-2622a94f9e0b.PNG)

![capture](https://cloud.githubusercontent.com/assets/12820322/16822314/36dea8c0-4964-11e6-9d7c-f0669a6f4682.PNG)

**Comment by shinyquagsire23** [comment]
AFAIK the game was never working in master and won't work until https://github.com/citra-emu/citra/pull/1948 is merged.

**Comment by Subv** [comment]
Indeed, Pokemon has never worked.

**Comment by RavenHome1** [comment]
oh wait i thought cro was merged and it is just giving a crash instead of complaining about CRO *facepalm*
