### ISSUE TITLE
cannot play kirby triple deluxe 

### ISSUE THREAD

**Issue by kienhoangtu7** [citra-emu/citra#1953]
When ever i try to start kirby triple deluxe. The game has a black screen for like infinity.
here is the picture of it 
![image](https://cloud.githubusercontent.com/assets/20159363/16870844/de81beec-4aad-11e6-8c19-66e09bf699f1.png)

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

This looks very similar to https://github.com/citra-emu/citra/issues/1818
Dump your own games and also make sure to dump shared-font
