### ISSUE TITLE
Crash while launching game [f95d119]

### ISSUE THREAD

**Issue by UltraStars3000** [citra-emu/citra#1954]
![untitled](https://cloud.githubusercontent.com/assets/14246308/16872794/7d2c0ba2-4a8f-11e6-9e3c-d1f584f70ba9.gif)

I don't know why this happening, I've tried around 10 diferrents roms, and I always get this crash message :/

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game, pirated 3DS bios files, unofficial or old builds.

**Also note that we do not support Pokemon. Pokemon is NOT supported [and not working](https://github.com/citra-emu/citra/issues/1795); no version, not X, not Y, not ORAS, nothing. Come back in a couple of months but don't expect anything.**

---

Closed as invalid
