### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by JulioJunior10** [citra-emu/citra#1956]
please help when i open citra and i select  pokemon omega ruby It appears to me "citra-qt.exe It stopped working" and to when i open zelda ocarina of time it dont work to me

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game, pirated 3DS bios files, unofficial or old builds.

**Also note that we do not support Pokemon. Pokemon is NOT supported [and not working](https://github.com/citra-emu/citra/issues/1795); no version, not X, not Y, not ORAS, nothing. Come back in a couple of months but don't expect anything.**

---

Closed as invalid
