### ISSUE TITLE
Skyeye: Incorrect translation of REVSH (thumb)

### ISSUE THREAD

**Issue by MerryMage** [citra-emu/citra#1957]
Skyeye appears to translate thumb REVSH into ANDEQ. 

TODO: More investigation.

**Comment by MerryMage** [comment]
Investigation complete.

In `TranslateThumbInstruction`: When tinstr is REVSH, `BITS(tinstr, 6, 7) == 3`. `subset[3]` reads beyond the end of the `subset` array.

Proposed fix (perhaps with some other way of hand)

            static const u32 subset[3] = {
                0xE6BF0F30, // REV
                0xE6BF0FB0, // REV16
                0, 
                0xE6FF0FB0, // REVSH
            };

            if (BITS(tinstr, 6, 7) == 2) {
                valid = ThumbDecodeStatus::UNDEFINED;
                break;
            }

            // ... as before ...

**Comment by lioncash** [comment]
Fix looks fine
