### ISSUE TITLE
crash when loading rom on osx el Capitain 10.11.5

### ISSUE THREAD

**Issue by danycrup85** [citra-emu/citra#1965]
when I load a rom I get this error:
Debug <Critical> core/hle/service/fs/archive.cpp:operator():310: Assertion Failed!
Tried to register more than one archive with same id code

can I fix it?

**Comment by JayFoxRox** [comment]
(This is a shitty issue title and description, I'm tempted to close this and sent you to the forums instead)

As an effort to rescue this issue: attach a backtrace please?

**Comment by danycrup85** [comment]
sorry for my english, I attach a screenshot. How can I send you a backtrace? 
![screenshot- 2016-07-21 alle 17 50 19](https://cloud.githubusercontent.com/assets/8995116/17029495/b613a3ea-4f6b-11e6-803d-73d68e171255.png)

**Comment by archshift** [comment]
@danycrup85 When it crashes, Xcode should open up the debugger menu that has a list of some text. You'd be able to click on each list item and it would take you to a new location in the code. Use shift to select the entire list and copy/paste here.

**Comment by azoreseuropa** [comment]
What did you do ? I was on 10.11.5 and doesn't have a problem at all. Now, update to 10.11.6 and doesn't have a problem.

**Comment by danycrup85** [comment]
I've updated to 10.11.6, but I have the same problem.

I think this is my backtrace:

#0	0x000000010016d73a in void assert_noinline_call<Service::FS::RegisterArchiveType(std::__1::unique_ptr<FileSys::ArchiveFactory, std::__1::default_delete<FileSys::ArchiveFactory> >&&, Service::FS::ArchiveIdCode)::$_0>(Service::FS::RegisterArchiveType(std::__1::unique_ptr<FileSys::ArchiveFactory, std::__1::default_delete<FileSys::ArchiveFactory> >&&, Service::FS::ArchiveIdCode)::$_0 const&) at /Users/daniele/Downloads/citra/src/common/assert.h:27
#1	0x000000010016d566 in Service::FS::RegisterArchiveType(std::__1::unique_ptr<FileSys::ArchiveFactory, std::__1::default_delete<FileSys::ArchiveFactory> >&&, Service::FS::ArchiveIdCode) at /Users/daniele/Downloads/citra/src/core/hle/service/fs/archive.cpp:310
#2	0x000000010016f7de in Service::FS::RegisterArchiveTypes() at /Users/daniele/Downloads/citra/src/core/hle/service/fs/archive.cpp:531
#3	0x00000001001727bb in Service::FS::ArchiveInit() at /Users/daniele/Downloads/citra/src/core/hle/service/fs/archive.cpp:570
#4	0x0000000100192510 in Service::Init() at /Users/daniele/Downloads/citra/src/core/hle/service/service.cpp:107
#5	0x000000010011eb89 in HLE::Init() at /Users/daniele/Downloads/citra/src/core/hle/hle.cpp:46
#6	0x00000001001da9da in System::Init(EmuWindow*) at /Users/daniele/Downloads/citra/src/core/system.cpp:26
#7	0x0000000100093d16 in GMainWindow::InitializeSystem() at /Users/daniele/Downloads/citra/src/citra_qt/main.cpp:255
#8	0x0000000100092b1f in GMainWindow::BootGame(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /Users/daniele/Downloads/citra/src/citra_qt/main.cpp:320
#9	0x0000000100094eaf in GMainWindow::OnMenuLoadFile() at /Users/daniele/Downloads/citra/src/citra_qt/main.cpp:425
#10	0x0000000100009977 in GMainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) at /Users/daniele/Downloads/citra/build/src/citra_qt/moc_main.cpp:128
#11	0x000000010a219d96 in QMetaObject::activate(QObject*, int, int, void**) ()
#12	0x00000001092d69f7 in QAction::activate(QAction::ActionEvent) ()
#13	0x000000010a219d96 in QMetaObject::activate(QObject*, int, int, void**) ()
#14	0x000000010a212932 in QObject::event(QEvent*) ()
#15	0x00000001092e0096 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
#16	0x00000001092e15f8 in QApplication::notify(QObject*, QEvent*) ()
#17	0x000000010a1e4814 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
#18	0x000000010a1e555b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
#19	0x000000010ae63d5e in QCocoaEventDispatcherPrivate::processPostedEvents() ()
#20	0x000000010ae64621 in QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) ()
#21	0x00007fff914f1881 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#22	0x00007fff914d0fbc in __CFRunLoopDoSources0 ()
#23	0x00007fff914d04df in __CFRunLoopRun ()
#24	0x00007fff914cfed8 in CFRunLoopRunSpecific ()
#25	0x00007fff8a744935 in RunCurrentEventLoopInMode ()
#26	0x00007fff8a744677 in ReceiveNextEventCommon ()
#27	0x00007fff8a7445af in _BlockUntilNextEventMatchingListInModeWithFilter ()
#28	0x00007fff8d103df6 in _DPSNextEvent ()
#29	0x00007fff8d103226 in -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] ()
#30	0x00007fff8d0f7d80 in -[NSApplication run] ()
#31	0x000000010ae6352f in QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#32	0x000000010a1e09d1 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#33	0x000000010a1e4e85 in QCoreApplication::exec() ()
#34	0x0000000100095d0d in main at /Users/daniele/Downloads/citra/src/citra_qt/main.cpp:594
#35	0x00007fff962725ad in start ()

**Comment by mailwl** [comment]
i think, i found problem.
When run citra from Xcode, it add to command line parameter **-NSDocumentRevisionsDebugMode**, which citra try to load as ROM (unsuccessfully).
look at: https://github.com/citra-emu/citra/blob/master/src/citra_qt/main.cpp#L322-L326

```
    if (!InitializeSystem())
        return;
```
Here system is initialized
```
    if (!LoadROM(filename))
        return;
```
Here return with error, BUT! system still initialized, and FS too, with all file systems.
When, we try to open good rom, system initialized again, trying to add same file system to uncleaned list.
