### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by WyRe** [citra-emu/citra#1968]
I'm trying to open Citra after compile from ArchLinux AUR repos [https://aur.archlinux.org/packages/citra-git/](url) and I get a message saying:

Ilegal instruction (core dumped)

I've got to do some modifications to PKGBUILD according to that issue:

[https://github.com/citra-emu/citra/issues/1955#issuecomment-233106336](url)

As you can see in AUR commentaries. I'm running under OpenGL 4.5.0 and NVIDIA 367.35 driver. Thank you so much.

**Comment by JayFoxRox** [comment]
Contact the packager via the AUR comments (or try linkmauve1 on freenode / in \#citra).
This is not officially maintained and also not a problem with Citra itself (We should probably make that more clear).

(A proper title for this issue would have been "AUR Package 'citra-git' broken: Illegal Instruction")

---

Closed as invalid.
