### ISSUE TITLE
Citra crashes during start up pokemon alpha sapphire

### ISSUE THREAD

**Issue by timo40** [citra-emu/citra#1969]
Hello

When I try to use a decrypted rom which I downloaded, the emulator crashes instant.

**Here is the log**:

[   0.000000] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .citra-qt.exe as unknown...
[   0.000280] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .citra-qt.pdb as unknown...
[   0.000501] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .citra.exe as unknown...
[   0.000749] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .citra.pdb as unknown...
[   0.000992] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .license.txt as unknown...
[   0.001245] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .Qt5Core.dll as unknown...
[   0.001487] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .Qt5Gui.dll as unknown...
[   0.001696] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .Qt5OpenGL.dll as unknown...
[   0.001932] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .Qt5Widgets.dll as unknown...
[   0.002182] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .README.md as unknown...
[   0.002445] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .SDL2.dll as unknown...
[   0.002690] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .tests.exe as unknown...
[   0.002920] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file .tests.pdb as unknown...
[   3.771844] Frontend Info citra_qtmain.cppGMainWindowBootGame317 Citra starting...
[   3.777778] Service.FS Info corefile_sysarchive_sdmc.cppFileSysArchiveFactory_SDMCArchiveFactory_SDMC21 Directory CUsersTimoDesktopcitrausersdmc set as SDMC.
[   3.778171] Common.Filesystem Warning commonfile_util.cppFileUtilCreateFullPath207 path exists CUsersTimoDesktopcitrausersdmc
[   3.778444] Service.FS Info corefile_sysarchive_savedata.cppFileSysArchiveFactory_SaveDataArchiveFactory_SaveData42 Directory CUsersTimoDesktopcitrausersdmcNintendo 3DS0000000000000000000000000000000000000000000000000000000000000000title set as SaveData.
[   3.778674] Service.FS Info corefile_sysarchive_extsavedata.cppFileSysArchiveFactory_ExtSaveDataArchiveFactory_ExtSaveData62 Directory CUsersTimoDesktopcitrausersdmcNintendo 3DS0000000000000000000000000000000000000000000000000000000000000000extdata set as base for ExtSaveData.
[   3.778990] Common.Filesystem Warning commonfile_util.cppFileUtilCreateFullPath207 path exists CUsersTimoDesktopcitrausersdmcNintendo 3DS0000000000000000000000000000000000000000000000000000000000000000extdata
[   3.779183] Service.FS Info corefile_sysarchive_extsavedata.cppFileSysArchiveFactory_ExtSaveDataArchiveFactory_ExtSaveData62 Directory CUsersTimoDesktopcitrausernanddata00000000000000000000000000000000extdata set as base for ExtSaveData.
[   3.779426] Common.Filesystem Warning commonfile_util.cppFileUtilCreateFullPath207 path exists CUsersTimoDesktopcitrausernanddata00000000000000000000000000000000extdata
[   3.780350] Service.APT Warning corehleserviceaptapt.cppServiceAPTInit488 Unable to load shared font CUsersTimoDesktopcitrausersysdatashared_font.bin
[   3.781413] Render.OpenGL Info video_corerenderer_openglrenderer_opengl.cppRendererOpenGLInit481 GL_VERSION 3.3.0 NVIDIA 368.81
[   3.782053] Render.OpenGL Info video_corerenderer_openglrenderer_opengl.cppRendererOpenGLInit482 GL_VENDOR NVIDIA Corporation
[   3.782718] Render.OpenGL Info video_corerenderer_openglrenderer_opengl.cppRendererOpenGLInit483 GL_RENDERER GeForce GTX 980PCIeSSE2
[   3.784844] Loader Info coreloaderloader.cppLoaderGetLoader143 Loading file CUsersTimoDesktopcitrarompokemon.3ds as NCSD...
[   3.785504] Loader Warning coreloaderncch.cppLoaderAppLoader_NCCHLoadExeFS242 Only loading the first (bootable) NCCH within the NCSD file!
[   3.786181] Loader Info coreloaderncch.cppLoaderAppLoader_NCCHLoadExeFS266 Name                        sango-2
[   3.786975] Loader Info coreloaderncch.cppLoaderAppLoader_NCCHLoadExeFS267 Program ID                  000400000011C500
[   3.808599] Loader Info corehlekernelprocess.cppKernelProcessParseKernelCaps100 ExHeader kernel version 2.39
[   3.864109] Service.SRV Warning corehleservicesrv.cppSRVRegisterClient38 (STUBBED) called
[   3.886648] Service.SRV Warning corehleservicesrv.cppSRVEnableNotification62 (STUBBED) called
[   3.887286] Service.APT Warning corehleserviceaptapt.cppServiceAPTGetLockHandle115 (STUBBED) called handle=0x00038009 applet_attributes=0x00000000
[   3.888112] Service.APT Warning corehleserviceaptapt.cppServiceAPTSetNSStateField392 (STUBBED) unknown_ns_state_field=0
[   3.888847] Service.NDM Warning corehleservicendmndm.cppServiceNDMOverrideDefaultDaemons198 (STUBBED) default_daemon_bit_mask=0x0000000F
[   3.889437] Service.NDM Warning corehleservicendmndm.cppServiceNDMSuspendDaemons84 (STUBBED) daemon_bit_mask=0x00000009
[   3.889892] Service.APT Warning corehleserviceaptapt.cppServiceAPTEnable123 (STUBBED) called attributes=0x00000000
[   3.890567] Service.APT Warning corehleserviceaptapt.cppServiceAPTGlanceParameter238 called app_id=0x00000300, buffer_size=0x00001000
[   3.891336] Service.APT Warning corehleserviceaptapt.cppServiceAPTNotifyToWait98 (STUBBED) app_id=768
[   3.891758] Service.APT Warning corehleserviceaptapt.cppServiceAPTReceiveParameter216 called app_id=0x00000300, buffer_size=0x00001000
[   3.892487] Service.APT Warning corehleserviceaptapt.cppServiceAPTAppletUtility304 (STUBBED) called command=0x00000007, buffer1_size=0x00000004, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF40, buffer2_addr=0x0FFFFF0C
[   3.893108] Service.APT Warning corehleserviceaptapt.cppServiceAPTAppletUtility304 (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF08, buffer2_addr=0x0FFFFF0C
[   3.895270] Service.FS Warning corehleservicefsfs_user.cppServiceFSInitializeWithSdkVersion725 (STUBBED) called unk1=0x070101C8, unk2=0x00000020, unk3=0x0007001B
[   3.897447] Service.SRV Warning corehleservicesrv.cppSRVSubscribe109 (STUBBED) called, notification_id=0x209

**Pc specifications:**

I7 5820k
GTX 980
16 GB RAM
SSD 256 GB

**Comment by mailwl** [comment]
Pokemon goooo (away)

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game, pirated 3DS bios files, unofficial or old builds.

**Also note that we do not support Pokemon. Pokemon is NOT supported [and not working](https://github.com/citra-emu/citra/issues/1795); no version, not X, not Y, not ORAS, nothing. Come back in a couple of months but don't expect anything.**

---

Closed as invalid
