### ISSUE TITLE
Kirby Planet Robobot First BOSS Battle Glitch

### ISSUE THREAD

**Issue by zaranrapu** [citra-emu/citra#1970]
Video of the bug: https://github.com/citra-emu/citra/files/379506/Citra.zip

(Post restored by JayFoxRox after vandalism)

**Comment by wwylele** [comment]
This looks like a regression. I used to successfully beat that boss on citra, but can confirm this happens today.

**Comment by neobrain** [comment]
This bug report is useless.

**Comment by JayFoxRox** [comment]
@wwylele commented on Jul 23:
This looks like a regression. I used to successfully beat that boss on citra, but can confirm this happens today. Regression caused by edf30d8 (PR #1810) (issue #1919)

**Comment by Subv** [comment]
Closed by #2696
