### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by Tink-Tank** [citra-emu/citra#1976]
![image](https://cloud.githubusercontent.com/assets/20629800/17086478/a5aad55e-51fb-11e6-80d8-1e909cec5f8b.png)

Trying to compile a citra build but stuck at this step.I was told that i am supposed to get CITRA_USE_BUNDLED_SDL2 and CITRA_USE_BUNDLED_QT these errors but yet only those. I updated everything and I'm using git.

**Comment by Tink-Tank** [comment]
To be Clear

-I have downloaded Visual Studio 2015 Community,Cmake and Git Bash
-Cloned files using ''git clone --recursive https://github.com/citra-emu/citra.git'' to documents
-Chose source code and build binaries
-Then tried to configure using Cmake choosing Visual Studio 2015 Win64

Then stuck at this step.

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

This also applies to help understanding code unless you have very specific (and critical) questions about existing code.
We do not use this issue tracker for support of any kind (such as build assistence).

(Also, *who* told you to set the BUNDLED etc.?)

---

Closed as invalid
