### ISSUE TITLE
Citra-qt.exe has stoppped working

### ISSUE THREAD

**Issue by Xpenz** [citra-emu/citra#1977]
Hello,
i have a Problem. Whenever i try to start Omega Ruby with the citra Emulator i get the pop-up window saying "Citra-qt.exe has stopped working". It's the only Rom i have tried so far. It's a .3ds and freshly downloaded. 
Heres the error Code:
http://imgur.com/a/LVybR

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game, pirated 3DS bios files, unofficial or old builds.

**Also note that we do not support Pokemon. Pokemon is NOT supported [and not working](https://github.com/citra-emu/citra/issues/1795); no version, not X, not Y, not ORAS, nothing. Come back in a couple of months but don't expect anything.**

---

Closed as invalid
