### ISSUE TITLE
Game Issue [Monster Hunter 4 Ultimate]

### ISSUE THREAD

**Issue by TamTahiti** [citra-emu/citra#1979]
I noticed a game launch error of Monster Hunter 4 Ultimate with the default settings.
![run issue mh4](https://cloud.githubusercontent.com/assets/20630502/17087968/1abda23c-51b0-11e6-9dd0-c1e96f3a62a2.png)

I hope it will help the development of the emulator.

My setup :
Windows 10
Intel 2.5 GHz CPU
GPU Intel HD graphic
8GB RAM

**Comment by JayFoxRox** [comment]
[That sounds like a shared-font issue](https://discuss.citra-emu.org/d/81-how-to-dump-the-required-files).

Also, please follow the general style of issue naming: "[Game Name] - [Observed Problem]" (without the brackets).
We'll tag your issues according to the current state of the issue.

**Comment by Andrix44** [comment]
It should get further if you spam A.

**Comment by Subv** [comment]
Is this still an issue?

**Comment by JayFoxRox** [comment]
Aside from font issues this also lacks GS. So I'll close this now, you can open it at a later time once GS have been implemented. (This issue had a rough start anyway)
