### ISSUE TITLE
Super Mario 3D Land crashing

### ISSUE THREAD

**Issue by azoreseuropa** [citra-emu/citra#1981]
I am using Mac OS X version: Can you test this? Super Mario 3D Land EUROPE isn't playable and crashing Citra when World 1-1 was brought up to the screen for the first time. The latest version is citra-20160726-f8f6722-osx-amd64.tar.xz at Citra Nightly because it was playable on June 8 the version - citra-20160608-ba4fb41-osx-amd64.tar.xz

**Comment by JayFoxRox** [comment]
This is a known issue with the shader related to lighting. So I'm kind of surprised that you claim that it worked fine in the past.

**Comment by azoreseuropa** [comment]
Yes, it was playable after World 1-1 was brought up to the screen without crashing and I played it for a while in World 1-1 only. And it was not crashing as far as I can go in World 1-1, thats all. I guess I will wait for the next version or so for more testing. :)

**Comment by azoreseuropa** [comment]
Do you need log information of what caused it to crashes ?

**Comment by JayFoxRox** [comment]
Is this resolved?

**Comment by azoreseuropa** [comment]
Yes, it is no longer crashes.

**Comment by gamedropswithpops** [comment]
hi super mario 3d land still crashes in world 8 bowsers castle after your shoot out of the second canon , is there any fix for this btw I am using https://github.com/citra-emu/citra-bleeding-edge/releases build 
thanks

**Comment by freiro** [comment]
@gamedropswithpops please test on current master (bleeding edge is "unsupported") and eventually open a new ticket.
