### ISSUE TITLE
Citra qt has stopped working ...

### ISSUE THREAD

**Issue by Cookigod** [citra-emu/citra#1982]
I just got the newest build 2016/7/27 and when i loaded a game, it said that citra qt has stopped working. When i tried builds with avx, sse3, and sse4, it works but the ones that have been compiled doesn't work. Even the official builds from citra's website doesn't work, but the chinese versions work fine to me. Is there any fix to this????

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.
Note that we also don't support any kind of non-official builds.
There is only support for clean builds of the current master or the prepared official nightly builds.

---

Closed as invalid
