### ISSUE TITLE
VFP: Incorrect FTZ behaviour

### ISSUE THREAD

**Issue by MerryMage** [citra-emu/citra#1990]
Skyeye does not seem to perform FTZ on outputs at all. DAZ on inputs however does occur.

Assembly Code:

```
@ This test program adds two numbers that produces a denormal
.text
.arm
.align 4

.global test1
.type test1, %function
test1:
    ldr r0, =0x01000000
    vmsr fpscr, r0
    ldr r0, =0x81784441
    vmov.f32 s1, r0
    ldr r0, =0x0142e1d7
    vmov.f32 s18, r0
    vadd.f32 s14, s1, s18
    vmov.f32 r0, s14
    bx lr

.global test2
.type test2, %function
test2:
    ldr r0, =0x01000000
    vmsr fpscr, r0
    ldr r0, =0x81784441
    vmov.f32 s1, r0
    ldr r0, =0x0142e1d7
    vmov.f32 s18, r0
    vadd.f32 s14, s1, s18
    vmrs r0, fpscr
    bx lr

.global test3
.type test3, %function
test3:
    ldr r0, =0x01000000
    vmsr fpscr, r0
    ldr r0, =0x806ac4d4
    vmov.f32 s2, r0
    ldr r0, =0x00000000
    vmov.f32 s3, r0
    vadd.f32 s0, s2, s3
    vmov.f32 r0, s0
    bx lr
```

Citra output:

```
test1: 0x806ac4d4 *
test2: 0x01000000 *
test3: 0x00000000
```

Hardware output:

```
test1: 0x00000000 *
test2: 0x01000008 *
test3: 0x00000000
```

**Comment by MerryMage** [comment]
Code: https://github.com/MerryMage/3ds-tests/tree/master/vfp-ftz-add

**Comment by JayFoxRox** [comment]
I'd like to start tagging issues as cpu:jit and cpu:interpreter. Which part's are affected by this?

**Comment by Subv** [comment]
I've taken a look at this for single precision code, it seems vfp_single_normaliseround does not check the FTZ flag at all before rounding and writing the result to the registers.
Apparently none of the vfp instructions do this in the dyncom. I've checked the linux vfp code and it doesn't seem to do it either.

**Comment by MerryMage** [comment]
@Subv The code in vfp_single_normaliseround already checks for `underflow`, so that should be easy-ish to add.
