### ISSUE TITLE
Undub rom still encrypted?

### ISSUE THREAD

**Issue by Senjosei** [citra-emu/citra#1992]
So i tried playing an undub rom of Rune Factory 4 i downloaded (i have the original but too lazy to patch) but it says its still encrypted? Doesnt undub rom means its already decrypted?
Heres the rom info i got from rom tools :

> [+] CCI Image Details
>  Media Type:            CARD1
>  Media Size:            4 GB (32 Gbit)
>  CCI Data Size:         1395 MB (0x573c4000 bytes)
>  CCI File:
>   \> Size                1395 MB
>   \> Status              Trimmed
>  Additional Device:     EEPROM
>  Partition Count:       1
>  Save Crypto:           2.2.0-4 KeyY Method
> [+] CXI Partition
>  Product Code:          code
>  Company Code:          00
>  Unique ID:             07666
>  Build Type:            Release
>  SDK Version:           5.0.0 Release
> [+] CFA Partitions
>  E-Manual:              No
>  DLP Child:             No
>  Update Data:           No

And when i load it i get this :

> [   0.000000] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:207: path exists C:\Users\ASSSS\Desktop\Gamezzz\Citra/user/config/qt-config.ini
> [   0.116317] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./citra-qt.exe as unknown...
> [   0.116518] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./citra-qt.pdb as unknown...
> [   0.116718] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./citra.exe as unknown...
> [   0.116858] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./citra.pdb as unknown...
> [   0.116985] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./license.txt as unknown...
> [   0.117088] Loader <Error> core\loader\loader.cpp:Loader::GetLoader:127: Failed to load file ./log.txt
> [   0.117203] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./msvcp140.dll as unknown...
> [   0.125135] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./Qt5Core.dll as unknown...
> [   0.127668] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./Qt5Gui.dll as unknown...
> [   0.127866] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./Qt5OpenGL.dll as unknown...
> [   0.128228] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./Qt5Widgets.dll as unknown...
> [   0.128464] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./README.md as unknown...
> [   0.128633] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./SDL2.dll as unknown...
> [   0.130433] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./tests.exe as unknown...
> [   0.132800] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./tests.pdb as unknown...
> [   0.133108] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./vcruntime140.dll as unknown...
> [   4.832391] Frontend <Info> citra_qt\main.cpp:GMainWindow::BootGame:317: Citra starting...
> [   4.840725] Service.FS <Info> core\file_sys\archive_sdmc.cpp:FileSys::ArchiveFactory_SDMC::ArchiveFactory_SDMC:21: Directory C:\Users\ASSSS\Desktop\Gamezzz\Citra/user/sdmc/ set as SDMC.
> [   4.840877] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:207: path exists C:\Users\ASSSS\Desktop\Gamezzz\Citra/user/sdmc/
> [   4.840901] Service.FS <Info> core\file_sys\archive_savedata.cpp:FileSys::ArchiveFactory_SaveData::ArchiveFactory_SaveData:42: Directory C:\Users\ASSSS\Desktop\Gamezzz\Citra/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
> [   4.840918] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:62: Directory C:\Users\ASSSS\Desktop\Gamezzz\Citra/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
> [   4.840989] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:207: path exists C:\Users\ASSSS\Desktop\Gamezzz\Citra/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
> [   4.841007] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:62: Directory C:\Users\ASSSS\Desktop\Gamezzz\Citra/user/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
> [   4.841070] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:207: path exists C:\Users\ASSSS\Desktop\Gamezzz\Citra/user/nand/data/00000000000000000000000000000000/extdata/
> [   4.841342] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Init:495: Unable to load shared font: C:\Users\ASSSS\Desktop\Gamezzz\Citra/user/sysdata/shared_font.bin
> [   4.841891] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:481: GL_VERSION: 3.3.0 - Build 20.19.15.4444
> [   4.842043] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:482: GL_VENDOR: Intel
> [   4.842056] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:483: GL_RENDERER: Intel(R) HD Graphics 4400
> [   4.847451] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file E:/Temp/test/rune.3ds as NCSD...
> [   4.847480] Loader <Warning> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:242: Only loading the first (bootable) NCCH within the NCSD file!
> [   4.847502] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:266: Name:                        w˜±ÉzÐ„A˜Ük‡R4ôgL?‹©vé®YJ7>
> Gê¦1Ó|kkÀsDÊ72g=²2´‘ƒ·Çëå“ïžl;©£ÝvP>:ˆk×¢bÿŒÏÏ¦“(×ƒN¤ÇåL¨Œ÷HqÔ#@a<
> }k›˜ñ§¶˜<%Èš
> M×kj”CÖ£CÞ‰@¬ÄèÄ
> [   4.847512] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:267: Program ID:                  0004000000766600
> [   4.847527] Loader <Error> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:278: ExHeader Program ID mismatch: the ROM is probably encrypted.
> [   4.847536] Frontend <Critical> citra_qt\main.cpp:GMainWindow::LoadROM:285: Failed to load ROM!

Im running the latest windows nightly build commit e22b80b

**Comment by wwylele** [comment]
We don't support pirating games.

**Comment by Senjosei** [comment]
so if i dump my own cartridge and patch it myself it'll work ?

**Comment by MerryMage** [comment]
Sure, since you'll have to decrypt it before you can patch it in the first place.

Just don't reencrypt it afterwards.
