### ISSUE TITLE
Pokemon AS Route 104 Forest

### ISSUE THREAD

**Issue by jawad90** [citra-emu/citra#1993]
[  35.135353] Service <Error> core\hle\service\service.cpp:SyncRequest:70: unknown / unimplemented function 'SetProbeResponseParam': port=nwm::UDS, cmd_buff[1]=0x321F00, cmd_buff[2]=0x0
[  35.135772] Service <Error> core\hle\service\service.cpp:SyncRequest:70: unknown / unimplemented function 'BeginHostingNetwork': port=nwm::UDS, cmd_buff[1]=0xD, cmd_buff[2]=0x420402, cmd_buff[3]=0x66E778, cmd_buff[4]=0x34002, cmd_buff[5]=0x5A5BBC 

only changing the language to korean or japanese solves the problem but switching back to english gives the same error again

**Comment by poutros** [comment]
Pokemon is currently not supported on master branch. Close this issue.
