### ISSUE TITLE
Missing ddl files

### ISSUE THREAD

**Issue by erickwilsoneck12** [citra-emu/citra#1994]
I missing a WHOLE bunch of ddl files that I tried downloading. Please fix this error or have a pack of ddl files that come with the emulator

**Comment by yuriks** [comment]
We include all required DLLs (I'm assuming this is what you're talking about) with the nightlies, except for the VC2015 runtime. You'll need to provide more information.

**Comment by MerryMage** [comment]
Please read the [FAQ](https://citra-emu.org/wiki/FAQ).

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid
