### ISSUE TITLE
You guys tested it on win 7 ?

### ISSUE THREAD

**Issue by sfuns** [citra-emu/citra#1997]
You guys tested on win 7 ?
From my experience i'd say it will not run on win 7 32 & x64 , i tested on 3 different computers & all return the same errors that you can not solve on windows 7 since it requires at least win 8 DLL's.

Can you confirm this please?

Thank you.

**Comment by JayFoxRox** [comment]
Was [this](https://github.com/citra-emu/citra/issues/1996#issuecomment-238517685) too hard to understand?

---

This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid
