### ISSUE TITLE
Master built on Ubuntu, but options bar are missing

### ISSUE THREAD

**Issue by Road-Drum** [citra-emu/citra#1998]
so it's what i've said. i can't find any menu to tinker with emulation mode etc. it's been months and i don't keep up much where the options bar went to

![screenshot from 2016-08-09 22-26-15](https://cloud.githubusercontent.com/assets/14361864/17522109/5e993072-5e88-11e6-9795-8e1eed4013bd.png)

**Comment by MerryMage** [comment]
This is entirely a guess, but could you perhaps try running the application like this:

    QT_QPA_PLATFORMTHEME=gtk ./citra-qt

**Comment by Road-Drum** [comment]
awww yishh and the menu is back. wonder why though. incompatible theme?

**Comment by MerryMage** [comment]
If you're not using Unity, sounds like it could be related to this:

https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619

This'll likely affect most Qt5 apps; would recommend uninstalling appmenu-qt5 if none of your apps depend on that.

**Comment by Road-Drum** [comment]
im on unity though, quite weird to have this. at any rate i'll close this for now
