### ISSUE TITLE
Emulating very very slow with GTX 1070 and an i5 6600K

### ISSUE THREAD

**Issue by halixness** [citra-emu/citra#2003]
Hi,
I was trying to troubleshoot Citra because of very slow video rendering while paying a .3ds rom...
I've also tested it on my friend's pc (380x STRIX and i5 6400),worked fine ,not slow at all but as I copied files into my computer and ran the emulator I noticed it was running very slowly...
Are there compatibility issues with Pascal GPUs?
Thanks for being available,sorry if there's an existing topic like this one...

**Comment by jroweboy** [comment]
Hello! This is a issue tracker and not a general discussion forum. Please post this in the citra forums (https://discuss.citra-emu.org/) and close this issue. Note that citra is still early in development and its not at full speeds on most games no matter how powerful your machine is :)

**Comment by JayFoxRox** [comment]
What @jroweboy said.

---

This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid
