### ISSUE TITLE
pokemon mystery dungeon makes citra crush at a point

### ISSUE THREAD

**Issue by smartkaartik** [citra-emu/citra#2005]
When on hazy path we are about to battle with scraggy and gudaurr citra crushes and closes.

![capture](https://cloud.githubusercontent.com/assets/14974622/17656862/4eb8e992-62dc-11e6-888b-c5aca3b8b3c1.PNG)

System specs 
Windows 10 64bit
Intel I3 3.0ghz
Nvidia geforce gt 610 2gb

**Comment by wwylele** [comment]
dupe of #1682 ?

**Comment by smartkaartik** [comment]
Not that as the game player in #1682 is far behind me

**Comment by j-selby** [comment]
Can confirm, is dupe as the same issue has occurred (just without the same visual effect). Working on "solution" in the other thread.

**Comment by wwylele** [comment]
Should be fixed by #2103. If not please leave a comment and reopen this.
