### ISSUE TITLE
Better information: Super Mario 3D Land crashes with pictures

### ISSUE THREAD

**Issue by azoreseuropa** [citra-emu/citra#2009]
I am using Macbook Pro with Retina Mid 2014.

June 8 version of HEAD-ba4fb41 is playable here:

https://s10.postimg.org/uo8slko9l/Screen_Shot_2016_08_11_at_5_34_14_PM.png

The latest version of August 8 of HEAD-3c3a6cb crashes when he jumps into the screen:

https://s9.postimg.org/lmegb4mr3/Screen_Shot_2016_08_11_at_5_39_51_PM.png

Edit: Today on August 17

The latest version still crashes when he jumps into the screen. The June 8 version of HEAD-ba4fb41 remains playable only. @_@

What cause it ? I speak with people at gbatemp and they have the same problem for Windows as well as Mac. That's strange.

**Comment by wwylele** [comment]
You have already opened #1981. Please add information there and don't open another one. This is not a forum.
Close as duplicated.
