### ISSUE TITLE
OPENGL error although i have OPENGL 4.3

### ISSUE THREAD

**Issue by sophanith-github** [citra-emu/citra#2011]
Citra still pop up OPENGL 3.3 error although mine is 4.3.

![image](https://cloud.githubusercontent.com/assets/19278390/17770187/8ed89964-6566-11e6-9a7c-3d6b12fc1d5f.png)

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid
