### ISSUE TITLE
Touch Detective: Nameko Rhythm Bottom Screen Glitch

### ISSUE THREAD

**Issue by zaranrapu** [citra-emu/citra#2012]
![snapcrab_noname_2016-8-19_10-54-2_no-00](https://cloud.githubusercontent.com/assets/11900318/17796546/2dc3f952-65fc-11e6-8921-1f6a2a86aaef.png)
![snapcrab_noname_2016-8-19_10-54-31_no-00](https://cloud.githubusercontent.com/assets/11900318/17796551/33351fce-65fc-11e6-9178-d33383c4e997.png)
Used last night build-7b4dcac.
Old Citra build not screen glitch.

**Comment by wwylele** [comment]
Probably the same cause of #1938

**Comment by poutros** [comment]
Happens with mii maker and pokemon shuffle as well.

**Comment by yuriks** [comment]
Dupe of #1938
