### ISSUE TITLE
Can't play if hardware render isnt disabled.

### ISSUE THREAD

**Issue by sayeem012** [citra-emu/citra#2017]
hey guys this isssue is about the unofficial 7/17/2016.

So i wanted to play pokemon omea ruby and there's just a black screen so i tried a little of everything then finally i dicovered that it only works when i disable hardware render does any one hav a solution because if hardware render's disabled its way too slow and makes it unplayable THANKS for your help.

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game, pirated 3DS bios files, unofficial or old builds.

**Also note that we do not support Pokemon. Pokemon is NOT supported [and not working](https://github.com/citra-emu/citra/issues/1795); no version, not X, not Y, not ORAS, nothing. Come back in a couple of months but don't expect anything.**

---

Closed as invalid
