### ISSUE TITLE
This time with the official i get this error.

### ISSUE THREAD

**Issue by sayeem012** [citra-emu/citra#2018]
so i installed lots of dll and then this error comes up don't know what to do please help
![capture](https://cloud.githubusercontent.com/assets/17502658/17946649/0e511c16-69fe-11e6-94c4-7a3277031676.PNG)

**Comment by LittleWhite-tb** [comment]
Someone has reported similar DLL error on another project. Did you get your citra release on emurc, isn't it ?

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Use something like [dependency walker](http://www.dependencywalker.com/) if you have weird errors and you downloaded strange DLLs from the internet (Hint: Don't do it).
If DLLs are missing you probably haven't installed the Visual C++ Redistributables - check the FAQ for more information.

---

Closed as invalid
