### ISSUE TITLE
[Harvest Moon] Story_Of_Seasons_*removed*.3ds doesn't boot

### ISSUE THREAD

**Issue by conongtt** [citra-emu/citra#2020]
error log:
[7.778788] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read16 @ 0x0000001
Help me!

**Comment by JayFoxRox** [comment]
Stupid github.. Don't use pirated games.

Closed as invalid because the report is horrible in general. Check the wiki / contributing docs on how to submit a proper report.
