### ISSUE TITLE
.tar? 

### ISSUE THREAD

**Issue by morganarrow** [citra-emu/citra#2021]
I opened the newest file for citra on my mac (citra-latest-osx-amd64.tar.xz) and it opens up a .tar file that can only be opened with TextEdit, I really want this emulator to work :(

**Comment by muvor** [comment]
Use a nightly from the official site

**Comment by MerryMage** [comment]
Perhaps try using [The Unarchiver](http://unarchiver.c3.cx/unarchiver).

----

This issue tracker is not a help forum. Please post to [the Citra forums](https://discuss.citra-emu.org/) in the future.
