### ISSUE TITLE
Pokemon Alpha Sapphire-Black screen depending on the save file language

### ISSUE THREAD

**Issue by teslabyte** [citra-emu/citra#2026]
So as i downloaded the latest nightly that has CRO implemented i put a save file for Pokemon Alpha Sapphire in the right folder and started the game.The game starts to the main menu(where i see my save) and when i click to load my game save screen goes black.So i found the fix to change save file language to German and i did.And the crash is fixed i can now play the game.My question is what is the difference between English and German version,i mean that's just the translation,right?And the Log is a little different for both German and English.

German log: http://pastebin.com/0byUsgYC
English log: http://pastebin.com/8PgqhJYG

My specs are:
i5 4200U
4Gb DDr3
GT740M
Windows 10 64-bit

Maybe there is an issue in shared_font.bin or something like that.What do you guys think what is the issue?
P.S. The issue doesn't appear on the Pokemon ROM hacks like star saphhire only on the original game.

[0011c500(eng).zip](https://github.com/citra-emu/citra/files/442277/0011c500.eng.zip)
[0011c500(german).zip](https://github.com/citra-emu/citra/files/442278/0011c500.german.zip)

**Comment by wwylele** [comment]
could you please provide the save so that others can test it?

**Comment by hiperion99** [comment]
Ok here it is in both laguages.Remember the German works but the English doesn,t






[0011c500(eng).zip](https://github.com/citra-emu/citra/files/442183/0011c500.eng.zip)
[0011c500(german).zip](https://github.com/citra-emu/citra/files/442184/0011c500.german.zip)

**Comment by hiperion99** [comment]
Did you manage to find the cause for this issue or not?

**Comment by JayFoxRox** [comment]
Please give this a proper title which makes it easy to find the issue. The title should include the name of the game and what you observe.
"Pokemon AS/OR - Crash depending on selected language" *or something* (not sure if OR is also affected and if that's the full issue, it's just a hint, not the title you should actually use)

Also this is **not a forum** (And even there your behaviour would be wrong).
Don't ask questions unless they contribute to finding the root of the issue.
If people have something to contribute, they'll do so. No reason to poll.
Please add the savegames to the first post (which is where they should have been in the first place).

- I'll remove this post and the other posts which don't contribute once you've resolved those issues.

**Comment by swablueme** [comment]
There's nothing wrong with your save file:
http://i.imgur.com/YUH7GRr.png

Make sure that shared_font.bin is in your user/sysdata

**Comment by hiperion99** [comment]
@swablueme Are you using the ROM hack or the original game?I see that you character has blue clothes(just like in Star Sapphire).

**Comment by swablueme** [comment]
@hiperion99 I took three different screenshots and don't recall the one I uploaded.

**Comment by hiperion99** [comment]
@swablueme But what game were you using?Alpha Sapphire or Star Sapphire?

**Comment by swablueme** [comment]
Ah no I remember. Someone speculated that SS moved data around compared to AS (eg when you create a pokemon hack you move certain things around and edit routines for example) so they thought that AS's messups were relocated somewhere else in SS. Same reason that the girl can't actually get into Oldale's Pokemon Centre or crashes @ firey path whereas the boy doesn't suffer those issues. I have all the ROMs in one folder.

**Comment by emmauss** [comment]
the female crash at pokecenter happens on all pokecenter in the game, on the original AS game.

**Comment by hiperion99** [comment]
@emmauss Can you maybe try both of my save files on the original AS and see if German works and English doesn't.

**Comment by emmauss** [comment]
@hiperion99 i would try the german save.

**Comment by emmauss** [comment]
@hiperion99 tested both saves and yes, english does not work. i would say the your save is corrupted, or you used a hack to bypass a place that citra would freeze at. so until that freeze is fixed, you are stuck on using the german save.
to give the devs more help, please start the game afresh with your trainer in English and play until you reach the place you had to change roms or language to continue. post any information you can get by following the issue guidelines. that would help them.

**Comment by hiperion99** [comment]
@emmauss Well this is how it went.I made a brand new save and started from the begining.Everything was great until the exit from the Petalburg woods,where i needed to change language to pass to Rustboro city.And past Rustboro is Route 116 where i still need German.I found that after that route you go to Mauville City and there you can change back to English and it will work properly.So probably that part in the game(Petalburg woods,Rustboro city,route 115,116,...) has something that Citra can't open and that's why it crashes,but that something is missing from the German version and Citra runs it well.

**Comment by kyox91** [comment]
@hiperion99 i'm having the same issue, black screen the moment i tried to leave Petalburg woods. Can you please tell me how you that by changing the game language? i thought you cannot change the game language after you started the game.

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

If you are not a developer interested in contributing knowledge about the cause of this issue OR have a fix to present, don't say anything.

**Comment by Dragios** [comment]
Fix incoming #2260

**Comment by ShinobiAtlas** [comment]
i.have.faced.a.problem.after.i.beat.champion.steven.in.As.after.went.with.steven.in.hall,fame.screen.comes.black.and.only.background.music.happends.please.help.....

**Comment by RavenHome1** [comment]
@ShinobiAtlas 

please use the forums for support and not poke around issues that have been closed for so long

https://community.citra-emu.org/
