### ISSUE TITLE
Pokemon alpha sapphire pokecenter freeze

### ISSUE THREAD

**Issue by emmauss** [citra-emu/citra#2028]
i have been having this problem with the unofficial build and now that it is official i am posting it here. as i have only experience this freeze at the pokemon center, it may be related to other freezes found this game and omega ruby.
thee freeze occurs anything you try to enter a pokecenter with a female character, ie when playing as May.screen shots here

![screenshot 11](https://cloud.githubusercontent.com/assets/5307160/18063324/0034eb1a-6e1a-11e6-8f6a-9cf8577b0912.png)

for console log 
http://pastebin.com/MUQUUtxN

i am using master build , git commit 3f515c0 

for steps ;
create or load a save with the female trainers.
go to the nearest pokecenter 
try entering.
it would freeze during the blacking out sequence, when the pokeball inner circle almost touches the head of your trainer.
PC specs
Intel core i5 4210u @ 2.4ghz ~ 2.7ghz
nvidia geforce 840m 2gb
6 gb ddr3 ram

i dont know how i can get more info for the issue report, it does not crash so no backtrace.

**Comment by robertosartori** [comment]
Maybe OT:
How do you start Pokemon? I've build yesterday master branch (after the CRO commit) and  i get only 'svc.cpp break' errors. I've downloaded the official nightly today (29\08 build) and same errors. With unofficial build i can start it.

**Comment by zacharisharris** [comment]
I am playing Alpha Sapphire right now and I have the exact same issue. Is there some fix for that?

**Comment by emmauss** [comment]
Confirmed #2260 fixes this.

**Comment by ShinobiAtlas** [comment]
after.i.beat.steven.i.found.a.black.screen.any.solution

**Comment by XXXDragonXXX** [comment]
When I Talk TO Nurse ! It Says "Welcome to pokemon centre and...." And after that game freezes . Only music comes

**Comment by RavenHome1** [comment]
please use the forums for any questions you have and don't revive dead issues on github 

https://community.citra-emu.org/

make sure you have the latest version of citra
