### ISSUE TITLE
Pokemon Y instant crash

### ISSUE THREAD

**Issue by Zock629** [citra-emu/citra#2052]
Command prompt log:

[   0.000000] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:207: path exists D:\Program Files (x86)\Emulators\3DS Emulator/user/config/qt-config.ini
[   0.063545] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./0451 - Pokemon Y (Europe) (En,Ja,Fr,De,Es,It,Ko) Decrypted.3ds as NCSD...
[   0.063808] Loader <Warning> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:242: Only loading the first (bootable) NCCH within the NCSD file!
[   0.064041] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:266: Name:                        kujira-2
[   0.064266] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:267: Program ID:                  0004000000055E00
[   0.064682] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./citra-qt.exe as unknown...
[   0.064915] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./citra-qt.pdb as unknown...
[   0.065141] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./citra.exe as unknown...
[   0.065376] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./citra.pdb as unknown...
[   0.065634] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./license.txt as unknown...
[   0.065975] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./Pokemon Alpha Sapphire.3ds as NCSD...
[   0.066210] Loader <Warning> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:242: Only loading the first (bootable) NCCH within the NCSD file!
[   0.066463] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:266: Name:                        sango-2
[   0.066715] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:267: Program ID:                  000400000011C500
[   0.067097] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./Qt5Core.dll as unknown...
[   0.067343] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./Qt5Gui.dll as unknown...
[   0.067596] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./Qt5OpenGL.dll as unknown...
[   0.067856] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./Qt5Widgets.dll as unknown...
[   0.068119] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./README.md as unknown...
[   0.068366] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./SDL2.dll as unknown...
[   1.139423] Frontend <Info> citra_qt\main.cpp:GMainWindow::BootGame:319: Citra starting...
[   1.272278] Service.FS <Info> core\file_sys\archive_sdmc.cpp:FileSys::ArchiveFactory_SDMC::ArchiveFactory_SDMC:21: Directory D:\Program Files (x86)\Emulators\3DS Emulator/user/sdmc/ set as SDMC.
[   1.273152] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:207: path exists D:\Program Files (x86)\Emulators\3DS Emulator/user/sdmc/
[   1.273973] Service.FS <Info> core\file_sys\archive_savedata.cpp:FileSys::ArchiveFactory_SaveData::ArchiveFactory_SaveData:42: Directory D:\Program Files (x86)\Emulators\3DS Emulator/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
[   1.274690] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:62: Directory D:\Program Files (x86)\Emulators\3DS Emulator/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[   1.275455] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:207: path exists D:\Program Files (x86)\Emulators\3DS Emulator/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
[   1.276146] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:62: Directory D:\Program Files (x86)\Emulators\3DS Emulator/user/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[   1.276896] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:207: path exists D:\Program Files (x86)\Emulators\3DS Emulator/user/nand/data/00000000000000000000000000000000/extdata/
[   1.277625] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:207: path exists D:\Program Files (x86)\Emulators\3DS Emulator/user/sysdata/shared_font.bin
[   1.280357] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:481: GL_VERSION: 3.3.0 NVIDIA 368.81
[   1.281031] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:482: GL_VENDOR: NVIDIA Corporation
[   1.281658] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:483: GL_RENDERER: GeForce GTX 970/PCIe/SSE2
[   1.285927] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:143: Loading file ./0451 - Pokemon Y (Europe) (En,Ja,Fr,De,Es,It,Ko) Decrypted.3ds as NCSD...
[   1.286569] Loader <Warning> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:242: Only loading the first (bootable) NCCH within the NCSD file!
[   1.287175] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:266: Name:                        kujira-2
[   1.287778] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:267: Program ID:                  0004000000055E00
[   1.310587] Loader <Info> core\hle\kernel\process.cpp:Kernel::Process::ParseKernelCaps:100: ExHeader kernel version: 2.35
[   1.406662] Service.SRV <Warning> core\hle\service\srv.cpp:SRV::RegisterClient:38: (STUBBED) called
[   1.407219] Service.SRV <Warning> core\hle\service\srv.cpp:SRV::EnableNotification:62: (STUBBED) called
[   1.407785] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GetLockHandle:119: (STUBBED) called handle=0x00038009 applet_attributes=0x00000000
[   1.408728] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::OverrideDefaultDaemons:198: (STUBBED) default_daemon_bit_mask=0x0000000F
[   1.409328] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::SuspendDaemons:84: (STUBBED) daemon_bit_mask=0x00000009
[   1.410000] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Enable:127: (STUBBED) called attributes=0x00000000
[   1.410957] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GlanceParameter:242: called app_id=0x00000300, buffer_size=0x00001000
[   1.411710] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::NotifyToWait:102: (STUBBED) app_id=768
[   1.412159] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::ReceiveParameter:220: called app_id=0x00000300, buffer_size=0x00001000
[   1.412902] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:308: (STUBBED) called command=0x00000007, buffer1_size=0x00000004, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF40, buffer2_addr=0x0FFFFF0C
[   1.413577] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:308: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF08, buffer2_addr=0x0FFFFF0C
[   1.416144] Service.FS <Warning> core\hle\service\fs\fs_user.cpp:Service::FS::InitializeWithSdkVersion:725: (STUBBED) called unk1=0x050200C8, unk2=0x00000020, unk3=0x0007001A
[   1.418425] Service.SRV <Warning> core\hle\service\srv.cpp:SRV::Subscribe:109: (STUBBED) called, notification_id=0x209
[   1.438515] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::AcquireRight:663: called
[   1.438761] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::RegisterInterruptRelayQueue:368: called, flags=0x00000001
[   1.463477] HW.Memory <Error> core\memory.cpp:Memory::GetPointer:279: unknown GetPointer @ 0x1f600000
[   1.608202] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:DSP_DSP::LoadComponent:148: Firmware hash: 0x101236429b43db7
[   1.608767] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:DSP_DSP::LoadComponent:151: Structures hash: 0x3c82b932a5857c7e
[   1.609316] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::LoadComponent:154: (STUBBED) called size=0x35378, prog_mask=0x000300FF, data_mask=0x000300FF, buffer=0x160AE998
[   1.609986] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:DSP_DSP::RegisterInterruptEvents:239: Registered type=2, pipe=2, event_handle=0x000F002C
[   1.610574] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::GetSemaphoreEventHandle:171: (STUBBED) called
[   1.610947] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::SetSemaphoreMask:429: (STUBBED) called mask=0x00002000
[   1.611554] Audio.DSP <Info> audio_core\hle\pipe.cpp:DSP::HLE::PipeWrite:134: Application has requested initialization of DSP hardware
[   1.612175] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::SetSemaphore:261: (STUBBED) called
[   1.612718] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:DSP_DSP::SetSemaphore:261: (STUBBED) called
[   1.655803] Service.CFG <Warning> core\hle\service\cfg\cfg.cpp:Service::CFG::GenHashConsoleUnique:167: (STUBBED) called app_id_salt=0x55D
[   1.657464] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFileDirectly:119: failed to get a handle for archive archive_id=0x2345678A archive_path=[Binary: 02030100db00040000ffffff01000000]
[   1.658441] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:70: unknown / unimplemented function 'SetClientSdkVersion': port=frd:u, cmd_buff[1]=0x50200C8, cmd_buff[2]=0x20, cmd_buff[3]=0x118031
[   1.659139] Service.FRD <Warning> core\hle\service\frd\frd.cpp:Service::FRD::GetMyPresence:30: (STUBBED) called
[   1.659532] Service.FRD <Warning> core\hle\service\frd\frd.cpp:Service::FRD::GetFriendKeyList:48: (STUBBED) called, unknown=0, frd_count=100, frd_key_addr=0x08C53570
[   1.660599] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:70: unknown / unimplemented function '0x00010082': port=boss:U, cmd_buff[1]=0x0, cmd_buff[2]=0x0, cmd_buff[3]=0x20, cmd_buff[4]=0x0
[   1.661312] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::ResumeDaemons:99: (STUBBED) daemon_bit_mask=0x0000000B
[   1.661888] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::ResumeDaemons:99: (STUBBED) daemon_bit_mask=0x0000000F
[   1.662547] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:70: unknown / unimplemented function '0x00300000': port=boss:U
[   1.663181] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:70: unknown / unimplemented function '0x00030000': port=boss:U
[   1.663827] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:70: unknown / unimplemented function '0x002F0140': port=boss:U, cmd_buff[1]=0x55D, cmd_buff[2]=0x0, cmd_buff[3]=0x100000, cmd_buff[4]=0x14, cmd_buff[5]=0x1
[   1.666110] Service.LDR <Warning> core\hle\service\ldr_ro\ldr_ro.cpp:LDR_RO::LoadCRR:204: (STUBBED) called, crr_buffer_ptr=0x08C5F000, crr_size=0x00002000, descriptor=0x00000000, process=0xFFFF8001
[   1.711675] Service.CFG <Warning> core\hle\service\cfg\cfg.cpp:Service::CFG::GenHashConsoleUnique:167: (STUBBED) called app_id_salt=0x55D
[   1.712415] HW.Memory <Error> core\memory.cpp:Memory::WriteBlock:461: unmapped WriteBlock @ 0x33646832 (start address = 0x33646832, size = 16)
[   1.712997] Service.FRD <Warning> core\hle\service\frd\frd.cpp:Service::FRD::GetMyFriendKey:90: (STUBBED) called
[   1.723815] Service.CFG <Warning> core\hle\service\cfg\cfg.cpp:Service::CFG::GenHashConsoleUnique:167: (STUBBED) called app_id_salt=0x55D
[   1.724462] HW.Memory <Error> core\memory.cpp:Memory::WriteBlock:461: unmapped WriteBlock @ 0x33646832 (start address = 0x33646832, size = 16)
[   1.725043] Service.FRD <Warning> core\hle\service\frd\frd.cpp:Service::FRD::GetMyFriendKey:90: (STUBBED) called
[   1.916727] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:70: unknown / unimplemented function 'GetStepHistory': port=ptm:u, cmd_buff[1]=0x18, cmd_buff[2]=0x91FBAC00, cmd_buff[3]=0x7A, cmd_buff[4]=0x30C, cmd_buff[5]=0xFFFFF50
[   1.942765] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFileDirectly:119: failed to get a handle for archive archive_id=0x2345678A archive_path=[Binary: 020401009b00040000ffffff01000000]
[   1.952110] Service.FS <Error> core\file_sys\archive_savedata.cpp:FileSys::ArchiveFactory_SaveData::GetFormatInfo:81: Could not open metadata information for archive
[   1.952772] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::GetFormatInfo:824: Failed to retrieve the format info
[   1.953700] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenArchive:389: failed to get a handle for archive archive_id=0x00000006 archive_path=[Binary: 010000005d05000000000000]
[   1.960082] HW.Memory <Error> core\memory.cpp:Memory::GetPointer:279: unknown GetPointer @ 0x00000000

Happened when Pokemon Y is opened
Also happens after the intro of Alpha Sapphire
shared_font.bin is in the correct folder

**Comment by einstein95** [comment]
The game is looking for other files that need dumping from the 3DS, the one in particular from a skim of the error log is nand/00000000000000000000000000000000/title/0004009b/00010402/content/00000000.app.romfs

**Comment by MerryMage** [comment]
This issue tracker is not a help forum. Please post to [the Citra forums](https://discuss.citra-emu.org/) in the future.

Closing.
