### ISSUE TITLE
Video / Texture forward: assertion failure in debug build

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#2053]
This is an old issue. Open this so that we won't forget.

Some games experiencing assertion failure in debug build in texture forward code:
![bissue](https://cloud.githubusercontent.com/assets/4592895/18268708/91cede26-7457-11e6-9897-f16f78449849.PNG)

In release build there is nothing wrong.

Games with this issue known to me are _Pokemon OR/AS_ and _Paper Mario Sticker Star_. Probably more.

**Comment by yuriks** [comment]
Pokemon ORAS? I wonder if this is related to the stencil clearing bug.

**Comment by wwylele** [comment]
Closed by #2103
