### ISSUE TITLE
Citra does not compile with gcc (mingw64) on Windows

### ISSUE THREAD

**Issue by Jobenblue** [citra-emu/citra#2054]
https://www.reddit.com/r/emulation/comments/503y2y/citra_implemented_cro_pr_merged/d73euqu?context=3

I was having a conversation with lw9k on Reddit who said that unofficial Citra builds are running faster because it has the latest version of GCC and that no one has implemented it yet which would make the official Citra much faster. The original PR was closed without a given reason and lw9k is feeling a little lazy to finish it himself so nobody is working on this important optimization implementation right now.

**Comment by jroweboy** [comment]
I have a PR open for this https://github.com/citra-emu/citra/pull/2043

**Comment by Jobenblue** [comment]
Ok, awesome. I wasn't aware somebody else had already addressed it, so this is safe to close?

**Comment by JayFoxRox** [comment]
Won't we loose binary compatibility with people running older std lib then on Linux?

**Comment by JayFoxRox** [comment]
Fixed by #2172
