### ISSUE TITLE
Gamepad Connectivity Functionality

### ISSUE THREAD

**Issue by shinra358** [citra-emu/citra#2056]
I would like to request hotplugging and afterplugging with xinput gamepads for this emulator. Current controllers time out to save battery now and leaving them on constantly drains it. If we have to take a break, we rely on currect tech to help save us power. When resuming gameplay, users would like to be able to resume their gameplay by reinitializing the gamepads for further gameplay. Usually for emus like this, turning the controller on after the emu has already started results in the controller not working and makes the user restart the entire emu, resetting gameplay. Same thing happens if we resume while already in game. So please, consider this feature when controller support is added. Thank you.

**Comment by hong620** [comment]
it's high priority on these days, not like 90~early 2000's emulator softwares,
in this time almost majority gamepad in pc are wireless.
and even in wired state, it's more often disconnect cause of it's microusb port.

it could be easily to fix, just keep on recive input on background or resync controller when xinput controller give pairing/plugin signal, or just add manually refresh button.

**Comment by FearlessTobi** [comment]
Hotplugging has been implemented.

**Comment by shinra358** [comment]
but has afterplugging been implemented as well?
