### ISSUE TITLE
Missing lorry sound effect playback in Pokémon OR/AS intro

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2058]
The lorry sound after effect is no longer audible in Pokemon OR/AS intro after the [audio](https://github.com/citra-emu/citra/pull/1734) is being merged officially. It used to playback that sound effect when audio support is still in development stage so it appears to be a regression.
- This is the lorry sound effect playback before audio is being merged officially.
  ![Old Citra.ogg](https://github.com/Dragios/Cloud-Drive/blob/master/Old%20Citra.ogg?raw=true)
- This is the lorry sound effect playback after audio being merged officially. The latest commit c3307b4 is used as the reference.
  ![Latest Citra.ogg](https://github.com/Dragios/Cloud-Drive/blob/master/Latest%20Citra.ogg?raw=true)

**Comment by thepulim** [comment]
aaa

**Comment by Dragios** [comment]
Not fix with PR #2422 unfortunately.
