### ISSUE TITLE
Super Mario 3D Land Stuck on White Screen with 3 shining stars save file

### ISSUE THREAD

**Issue by 1425720626** [citra-emu/citra#2081]
When I get 3 shining stars on my save file, I just get a blank white screen every time I press A to start on the title screen.
Version: HEAD-f196924
Specs:
Windows 7 x64
i7-6700k
16GB RAM
Nvidia GeForce GTX 970 4GB
attach log:
![default](https://cloud.githubusercontent.com/assets/22231730/18576684/5f6c3d0e-7c16-11e6-9b7b-1ea026325a51.png)

**Comment by pippo2931** [comment]
Regression
Bisected to:
git bisect good
14085ec670330b72d897d19ee844da87402ef39c is the first bad commit
commit 14085ec670330b72d897d19ee844da87402ef39c
Author: bunnei <bunneidev@gmail.com>
Date:   Thu Sep 1 23:18:01 2016 -0400

    core: Add configuration option for CPU JIT.

Workaround is to disable ENABLE CPU JIT from the general preferences menu.

**Comment by pippo2931** [comment]
Works again for me in e27d824.
