### ISSUE TITLE
Game speed regulation issues (No frame limiter)

### ISSUE THREAD

**Issue by lunafreya** [citra-emu/citra#2087]
After the post-JIT branch merges and resulting speed-wise optimizations, I noticed that the emulation speed might go a way too fast.

Observed on Etrian Odyssey IV (title screen) and Fire Emblem Awakening (title screen) on 8bf09b5

**Comment by MerryMage** [comment]
There is currently no frame-limiter other than vsync.

**Comment by Araschon** [comment]
How do you limit the frames using vsync? I'm not sure if my issue is a frame issue, but...citra runs my game at like 4x speed (even the audio and stuff is faster), and I can't figure out how to slow it down..

**Comment by JayFoxRox** [comment]
@Araschon: This is a bug tracker for developers of Citra.
Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.

**Comment by ryanterry131** [comment]
@Araschon You can turn on vsync in Citra's settings, it limits the framerate to your monitor's refresh rate (probably 60Hz) and may act as a temporary fix for your problem.

**Comment by emmauss** [comment]
can this be closed?

**Comment by MerryMage** [comment]
Closed by #2223.
