### ISSUE TITLE
Zelda: ALBW - Hookshot  glitches and softlocks the game with the CPU JIT

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#2090]
(Reported on the [forums](https://discuss.citra-emu.org/d/659-zelda-between-worlds/) and on IRC by PPLToast. Verified my myself.)
Version tested: 8bf09b5302dc7717477f6c3b5c1f0ea8f2c80717

When using the CPU JIT, launching the hookshot against a wall or object will cause it to either get stuck, or, when returning to Link, skip past him and go off in the opposite direction of the screen. In either case, you'll be unable to move or do any other action, and you'll get stuck. (Enemies, using the inventory and menus still behave properly.)

This works normally when using the interpreter.

Savegame reproducing the issue: [000ec400.zip](https://github.com/citra-emu/citra/files/479228/000ec400.zip)

**Comment by yuriks** [comment]
Disabling VFP JIT-ing by replacing [this line](https://github.com/MerryMage/dynarmic/blob/master/src/frontend/translate/translate_arm.cpp#L40) with `should_continue = visitor.InterpretThisInstruction();` makes the problem go away, which confirms it's a VFP emulation bug.

**Comment by wwylele** [comment]
probably related to #1990 or #1919 ?

**Comment by MerryMage** [comment]
For the record there are two known VFP emulation inaccuracies:

* FPSCR isn't saved when doing a memory operation
* vcvt is known to not correctly set some FPSCR flags

Related issue is MerryMage/dynarmic#18

**Comment by ryanterry131** [comment]
Out of curiosity, does x86_64 have instructions directly corresponding to arm's VFP functionality, or would they need to be emulated with multiple x86 instructions?

**Comment by MerryMage** [comment]
@ryanterry131 

* Edge-case behaviour differs. ARM11MPCore implements FTZ differently from x64, for example, by always flushing to positive zero.
* Exception behaviour differs in non-IEEE compliant modes.
* Some instructions have no direct equivalent on x64, like the unsigned version of VCVT.

**Comment by luansilva2000** [comment]
Guys, when you receive damage while you're stuck, the game back to normal, so, you can use a bomb to damage yourself to pass this part from the dungeon Swamp Palace. I do this and works, but, I have another problem...
In certain part of the dungeon, I have to level up the water, but the wood when I up the water doesn't up too, so this block me to take the key and pass the dungeon.

Here's an image from this part.
![sem titulo6](https://cloud.githubusercontent.com/assets/23062353/19702078/7eb6a55a-9ad4-11e6-9533-c194de360a80.png)

**Comment by JayFoxRox** [comment]
@luansilva2000 Create a seperate issue for that with more details

**Comment by IronFox** [comment]
I noticed that this issue does not always happen. Rather it seems that whatever is behind Link, opposite to the direction of the shot, determines or at least affects whether it enters soft lock.
An open door or map edge behind Link that connects to a different area seems to almost guarantee this issue to appear.
Though I am uncertain whether this helps at all, since you're not debugging the game itself, but rather the engine that tries to interpret it.
Up to this point you are making remarkable progress, though. The game is almost playable.

**Comment by Subv** [comment]
Could someone please re-test this on the latest master? There have been numerous VFP fixes in the JIT lately.

**Comment by yuriks** [comment]
Yup, seems to be fixed!
