### ISSUE TITLE
Zelda: ALBW - Savegame doesn't load properly on interpreter

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#2091]
(Reported by PPLToast on IRC, verified by myself.)
Version tested: 8bf09b5302dc7717477f6c3b5c1f0ea8f2c80717

This save game [000ec400.zip](https://github.com/citra-emu/citra/files/479228/000ec400.zip) loads normally when using the CPU JIT. When using the interpreter, it loads as if you had 999 rupees, all inventory items and no discovered weather vanes or map markers. Even more strangely, ~~if you save the game none of the changes will be made permanent~~ (EDIT: It wasn't actually saving, see comment below.), if you reload using the JIT, you'll be back to your old items and story position.

PPLToast speculates that this might be a debug feature being activated somehow.

**Comment by yuriks** [comment]
The same thing happens on a brand new save (saved as soon as you exit the house in the beginning). So it's not specific to this save.

**Comment by yuriks** [comment]
The game actually seems to have a bunch of bizarre issues with savegames that depend on the CPU backend in use. When using the JIT:

  - Starting a new game softlocks.
  - Copying, deleting or saving a save file sometimes works, but often softlocks. However, after restarting the game the copying always ended up succeeding.

When using the interpreter:

  - Starting a new game softlocks again.
  - Copying, deleting or saving *always* softlocks, and after restarting, the action didn't succeed.

This is a very strange thing to be dependent on the CPU core being used. I'd expect it to be an issue with the FS code or thread scheduling.

**Comment by hrydgard** [comment]
Smells like uninitialized variable somewhere, that ends up in different states depending on which CPU backend is used just by accident. Is the behaviour consistent between win/linux/others?

**Comment by wwylele** [comment]
> Starting a new game softlocks.

This is due to unimplemented syscore, which locks a syscore thread that has low priority. Confirmed by me.

For the bug in the interpreter, probably related to #1990 or #1919?

**Comment by yuriks** [comment]
At some point this started happening with the JIT too. They're now both broken. I bisected it down to:

```
27be446049cf09f2025451d53eb6c49597cf097b is the first bad commit
commit 27be446049cf09f2025451d53eb6c49597cf097b
Author: MerryMage <MerryMage@users.noreply.github.com>
Date:   Sat Nov 26 20:32:33 2016 +0000

    dynarmic: Add ticks based on ticks executed, not ticks requested

:040000 040000 37dbdb9320e6d7d15736c6952556916c961fcc3d 33f12a536035dc25cf70607c5098a6f6c6500aa8 M      src
```

**Comment by yuriks** [comment]
#2260 fixes this
