### ISSUE TITLE
Resizing window after game launch results in graphical glitches (Qt, OSX)

### ISSUE THREAD

**Issue by WishfulThinking** [citra-emu/citra#2092]
Built from commit 8bf09b5

Reproduction instructions:

Stop emulation and resize the main window to a small size

<img width="333" alt="screen shot 2016-09-19 at 1 27 18 am" src="https://cloud.githubusercontent.com/assets/22286460/18623176/46ecbf4e-7e08-11e6-8c05-23ff34cc3c8b.png">

Start emulation and resize the main window to a larger size

<img width="587" alt="screen shot 2016-09-19 at 1 29 06 am" src="https://cloud.githubusercontent.com/assets/22286460/18623204/828ba308-7e08-11e6-8234-8ff55129dd75.png">

If the main window starts at a larger size then the glitches don't appear.

<img width="738" alt="screen shot 2016-09-19 at 1 30 37 am" src="https://cloud.githubusercontent.com/assets/22286460/18623222/b3adffbc-7e08-11e6-849e-2c7d88b27cc0.png">

**Comment by archshift** [comment]
This is caused by #1883.
