### ISSUE TITLE
Gundam Try Age SP hanging 

### ISSUE THREAD

**Issue by suelo50** [citra-emu/citra#2095]

**Comment by suelo50** [comment]
Keyboard wont appear
![gundam try age sp](https://cloud.githubusercontent.com/assets/16906404/18631608/6114eff4-7e49-11e6-98d7-fdcb353a18df.png)

**Comment by wwylele** [comment]
Could you provide the log (text in the black window)?

**Comment by suelo50** [comment]
log ![teclado gundam](https://cloud.githubusercontent.com/assets/16906404/18631761/42ef87cc-7e4a-11e6-9379-b2dd449ec63b.png)

**Comment by suelo50** [comment]
@wwylele yes this games use software keyboard

**Comment by benderscruffy** [comment]
still happens in the latest nightly
![gundam](https://user-images.githubusercontent.com/2696404/33237606-6a8279de-d2b3-11e7-9e34-afc435447b1a.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1503673/log.zip)
