### ISSUE TITLE
Nvidia Geforce GT 545

### ISSUE THREAD

**Issue by zieak1** [citra-emu/citra#2098]
im running this card, it runs opengl 4.2 and for some reason, i get critical errors when loading up pokemon, it runs smoothly through the videos but when any "play" is involved it bogs down, ive tried multiple patches and even tried to combine a couple peoples fixes to see if i could fix the problem, idk why its going critical, andbody have any answers? thanks.

**Comment by wwylele** [comment]
AS IT SAID:

Please read the FAQ:
https://citra-emu.org/wiki/FAQ

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
http://discuss.citra-emu.org/

If the FAQ does not answer your question, please go to:
http://discuss.citra-emu.org/

====================================================

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of Citra you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

--------------------------------

Closed as invalid

**Comment by zieak1** [comment]
fuck you, its not a  support question its a why the fuck is it crashing
still after ive done everything i can so fuck you and your small dick you
fucking blowjob.
