### ISSUE TITLE
Pokémon Mystery Dungeon: Gates to Infinity – Transparency issue

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2104]
The staircase should become transparent when the Pokemon walks on top of it. As we can see here the opaque staircase is actually overlapping the Pokémon's body texture.
![Transparency issue](https://cloud.githubusercontent.com/assets/18496868/18956715/08add18e-868f-11e6-80c7-53eb635b193f.png)

This is how it looks like on the actual console:
![Actual graphic](https://cloud.githubusercontent.com/assets/18496868/18956736/19046e44-868f-11e6-8109-1c78a3968018.png)

Switching to software renderer does not change anything but I notice the clouds in the background is not rendered with this mode.
![Transparency issue](https://cloud.githubusercontent.com/assets/18496868/18956871/9f96897e-868f-11e6-890b-0d92dd5a7685.png)

A save game as requested by @JayFoxRox 
[Save data](https://github.com/Dragios/Cloud-Drive/blob/master/PMD%20-%20GtI%20Save%20File.zip?raw=true)

**Comment by wwylele** [comment]
Log, please

**Comment by Dragios** [comment]
There is no log indicating this particular issue unfortunately.

Just this appear upon entering the dungeon (could be related but not sure)
`HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:GLShader::AppendSource:58: Unhandled texture type 1`

And when switch to software renderer it spams with this:
`Render.OpenGL <Error> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:478: API ERROR 1282: GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.`

**Comment by ds84182** [comment]
Unimplemented cubemap textures, related to #1772 and #1801 

Can someone add the gpu:texture-cube and unimplemented labels?

**Comment by JayFoxRox** [comment]
Are you sure this particular bug is caused by cubemaps? It feels like an alpha or stencil issue.
The cubemap issue might be unrelated (other reflections in frame, bad state or some skybox)

**Comment by j-selby** [comment]
This also occurs in Super Mystery Dungeon in exactly the same context.

![devenv-05-10-2016_19-29-00](https://cloud.githubusercontent.com/assets/1404334/19106245/16875ab2-8b32-11e6-8f58-64961224beb2.png)

**Comment by Subv** [comment]
The game uses a weighted blend mode MAX to draw the staircase, but we currently don't take factors into account when blending with MIN or MAX, this is the same problem as #2684

Implementing the factors in the sw renderer fixed it, but there's no trivial way to do this for opengl

**Comment by yuriks** [comment]
What is the complete blend mode being used by the game exactly?

**Comment by Subv** [comment]
This is the blend mode for the staircase, as per RenderDoc: ![Image](https://user-images.githubusercontent.com/357072/26947564-c0d7c14a-4c58-11e7-934e-581cdab96dfb.png)

I'll upload the RenderDoc capture:
https://mega.nz/#!NIEAhZAA!ZJL_00gltJmJa5cEGeo_tqDukWfeGtKzKjTpVGAx6dA

**Comment by Dragios** [comment]
I was researching something about this few months ago and found out a blog that seems like can tackle the issue we currently facing. I leave a note here for anyone who is interested in fixing this.

The [blog post](http://casual-effects.blogspot.com/2014/03/weighted-blended-order-independent.html) and the complete [documentation](http://jcgt.org/published/0002/02/09/).

**Comment by benderscruffy** [comment]
still happens in the latest nightly
HW.GPU <Error> video_core/command_processor.cpp:WriteUniformFloatReg:94: Invalid vertex shader float uniform index 127
![mystery](https://user-images.githubusercontent.com/2696404/50718442-93c35100-10ca-11e9-9eb2-dd0963fb6e30.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2729001/citra_log.zip)

**Comment by benderscruffy** [comment]
still an issue
