### ISSUE TITLE
A build for Fantasy life (for people who do not know how to merge or branch and stuff like that)

### ISSUE THREAD

**Issue by Blankface345** [citra-emu/citra#2108]
I have been searching for many hours now to get fantasy life to work on the citra emulator..nothing. I have found nothing except people telling us to wait till the merge the data  in. The issue that many are having trouble with is when we start up the game it will not let us play it, instead it simply says failed to detect sd card.. I have just about went crazy trying to get this to work and have checked in many places. some help with this would be greatly appreciated  and telling me or others to mess with some of the coding might not help because not all of us know how to do it.

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

Also note that we do not support unofficial builds and we won't compile for you either.
Wait for a fix instead.

---

Closed as invalid
