### ISSUE TITLE
Dragon Quest Monsters Joker 3 - Texture Forwarding bug

### ISSUE THREAD

**Issue by Salijour** [citra-emu/citra#2112]
In Dragon Quest Monsters Joker 3, there are areas that texture forwarding reverts back to standard. In these areas there are light shafts. 
The light shafts are just there to make everything brighter unless I am blind. Upon researching between the emulator and real 3ds I noticed no changes to the shadows on the PC or NPCs. Nor does the PC walking through the light cause it to change anything but increase the brightness on character model. 

Citra
![Citra](https://i.gyazo.com/c2a001b44df12a4844083ec378dff0a7.png)

Real
![Real](https://i.gyazo.com/f183c77d5600f06cb90e3d45e262e03c.png)

The log doesn't really give much to go on.
http://pastebin.com/v5WPSJjD

Saves from two locations. Due to the fact you can save anywhere in the game and how the bug affects the game in an on/off nature. I placed the saves in two different locations with the bug where you can take a few steps and it go to another area without the bug for testing. 

[Save Data Tex.zip](https://github.com/citra-emu/citra/files/507205/Save.Data.Tex.zip)

**Comment by JayFoxRox** [comment]
Just to clarify: This is about the resolution being lower in the areas where the light shafts are influencing the brightness [IIRC].

**Comment by Salijour** [comment]
![issueclo](https://user-images.githubusercontent.com/4398286/48976014-e41bad80-f04c-11e8-9f05-f79c78e578a5.png) Objects interact correctly with light shafts. Much easier to see the effect at high resolutions on Citra. Issue closed.
