### ISSUE TITLE
Hellppp!!!!!!!!!!!!!! Pokemon Super Mystery Dungeon is freezing after the main title :( How to fix this?? Pleassse?? Help me :(

### ISSUE THREAD

**Issue by AlmariJosh** [citra-emu/citra#2113]

**Comment by wwylele** [comment]
This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://discuss.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build, or
 - use pirated copies of the games, 3DS BIOS files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid and duplicated

**Comment by AlmariJosh** [comment]
@wwylele ANswer me :( help me to fix that

**Comment by AlmariJosh** [comment]
@wwylele help me fix this pleassee
