### ISSUE TITLE
cant run it on debian 8 

### ISSUE THREAD

**Issue by treakiandroid** [citra-emu/citra#2122]
Hi,

it lookes like your citra-20161007-cc7f115-linux-amd64 build dosent work on Debian 8:
```
user@host:~/bin/3dsemu/citra-20161007-cc7f115-linux-amd64$ ./citra-qt 
./citra-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./citra-qt)
./citra-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./citra-qt)
```

it would be grate if you could fix that.

Thanks

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

It looks like your libc(++) is too old. Upgrade it and / or recompile from source.
Feel free to package and maintain a package.

---

Closed as invalid

**Comment by treakiandroid** [comment]
i cant upgrade it, its the latest debian version, could you compile a version that is also working with Debian 8, its the latest version of it and there are Manny debian users.

thanks in advance

**Comment by JayFoxRox** [comment]
Check or add instructions on the wiki for Debian (Ubuntu is probably a good starting point) or, better yet, if there are so many debian users: convince one of them to maintain a package.

Distribution is a user task in my personal opinion.
We only provide basic instructions what this depends on - you do the rest.

We also don't provide support for user issues on github.
