### ISSUE TITLE
Asynchronous file reading softlocks Brunswick Pro Bowling

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#2125]
# Observation

After making two small modifications (see below) to the Citra source that _technically_ should improve Citra's emulation accuracy of the CTROS scheduler, Brunswick Pro Bowling softlocks upon startup in a function called FileRead. This is surprising, since an asynchronous file reading operation seems like a very elementary operation, and it's one of the first things the game is doing to load its resources.
# Analysis

The following outlines the behavior of my (modified) Citra build, which reflects our current understanding of the CTR scheduler:
- The game ships with an `.axf` file in its RomFS that includes full symbol information (function names and parameter list, type information), making analysis of this issue very easy
- FileRead requests a worker thread to read data from a RomFS file by appending a work item to a task queue. The addition of the new item is signaled using a LightEvent (implemented via svcArbitrateAddress), which causes a deschedule of the main thread.
- The worker thread gets scheduled in and finds a new item appended to the task queue, and hence eventually calls FS::File::Read (using svcSendSyncRequest) on a RomFS FS file handle. In (modified) Citra, this causes a deschedule of the worker thread (see the list of modifications to see why; for reference, the file reading operation is executed before the deschedule).
- The main thread is scheduled back in and enters a stationary loop (presumably waiting for the asynchronous file reading operation to complete) without ever calling a system call. It hence never gets scheduled out and hence indefinitely blocks the AppCore, preventing the worker thread from ever getting scheduled back in.
- Note that the worker thread technically has higher priority than the main thread, but this is useless since on the real system the svcSendSyncRequest wouldn't return immediately (since file reading takes some time) but rather block the current thread until the service process replies.

As far as I can tell, this behavior is perfectly in line with what's publicly documented about the cooperative CTROS scheduler, which suggests we are missing a piece of the bigger picture.
# Theories

I considered the following theories to resolve the issue. Unfortunately, most of these seem to have already been proven wrong, and the rest are plain guesses.
- Maybe BPB runs threads on the SysCore? If the worker thread were allowed to run on the SysCore, it could be scheduled in even when the AppCore is blocked. However, the game's exheader suggests it's using the AppCore for the main thread, and the parameters to svcCreateThread suggest it doesn't use SysCore on the helper threads either.
- Maybe BPB uses SysCore slices? It was suggested applications may use [APT:SetApplicationCpuTimeLimit](https://3dbrew.org/wiki/APT:SetApplicationCpuTimeLimit) to use small time slices of the SysCore. This service command doesn't seem to be used in BPB, though.
- Maybe svcSendSyncRequest blocks the entire process from being scheduled in until the request is complete? If this were the case, instead of scheduling in the main thread after the worker thread calls svcSendSyncRequest, the OS would just put all process threads to sleep and schedule in the highest-prioritized process thread (i.e. the worker thread) once the request reply is received. However, testing has indicated that svcSendSyncRequest indeed only puts one process thread to sleep.
- Perhaps the game assumes the svcSyncRequest call is processed early enough by the FS module such that the next thread scheduled in on the AppCore will in fact be the worker thread? Since the FS module runs on the SysCore, it seems unlikely that the sync request is processed quicker than the AppCore reschedule.
# Modifications to the Citra Source

Granted, it's not common to report issues against a modified source tree. In this case, the issue is masked in the official Citra tree by two hacks:
- VBlankCallback calls [Service::HID::Update](https://github.com/citra-emu/citra/blob/58ae94af4c5c7777cab40ebb4f2bc517dd0f9f2c/src/core/hw/gpu.cpp#L546) along the way, which is obviously nonsense. The crucial downside of this hack is that it causes a thread reschedule even when the active application thread has not invoked any system calls.
- svcSendSyncRequest does not cause a thread reschedule in Citra. On the actual 3DS, sync requests take a while to be processed (especially file IO, which may last an eternity in terms of CPU time) and as such (always?) cause the current thread to be unscheduled. In Citra, sync requests are HLEed and finish instantly, and hence the reschedule is omitted. I think triggering the reschedule should be considered a functional property of the system that should hence be emulated, however.

A branch of Citra is available publicly on my fork, see https://github.com/neobrain/citra/tree/issue_2125.
# Relevance
- The underlying issue might be manifesting in other games even without the local changes I made to the Citra tree
- My local changes certainly are steps towards a more faithful scheduler implementation: Issues like this block Citra from becoming a more accurate emulator
- One of the changes I made essentially blocks LLEing system modules, since a sync request cannot be processed by an LLEed system module without a reschedule of the main thread.

**Comment by wwylele** [comment]
I tried to make [a small program](https://gist.github.com/wwylele/fd35b67c6571bee334fdca4f7f9e173c) doing a similar thing. However, it runs fine on _both_ 3ds _and_ your modified citra... where did I get it wrong?

**Comment by Subv** [comment]
@wwylele The VBlank callback signals the vblank interrupts, which causes a Reschedule.
In a way, we're not actually running a Cooperative scheduler since we may preempt the running thread every now and then (Every time a vblank fires)

**Comment by yuriks** [comment]
Some thoughts:

```
[22:12:11] <yuriks> Subv: I think the reason that VBlank "doesn't preempt" in hw is that it signals GSP, and GSP runs on the syscore
[22:15:42] <yuriks> but yeah, moving reschedule out is probably the solution
[22:16:03] <yuriks> though it's going to be a bit messy
[22:16:50] <yuriks> might be better to just make a version of Signal that doesn't reschedule so we can manually call it
[22:17:03] <yuriks> otherwise that change is going to ripple through a lot of stuff and probably cause some other regressions
[22:18:14] <yuriks> the deeper question though is that Reschedule is a "core-dependent" function, so we're going to have to think about how to deal with that kind of stuff in the future
[22:18:52] <yuriks> it could just be a thread_local global, or we're going to have to pass that sort of context when signalling things and throughout the HLE
[22:19:28] <yuriks> (the interrupt then switches the context to syscore before doing the work)
```

**Comment by Subv** [comment]
````
[01:41:36] <@Subv> neobrain: i just tested a program similar to yours and it freezes
[01:41:41] <@Subv> the threads deadlock
[01:42:11] <@Subv> https://gist.github.com/Subv/dcb0faca2386a71a53c2d1eab11873b1 here it is
[01:48:38] <@Subv> yeah
[01:49:04] <@Subv> (sure enough, in that test up there, the giant file is not written, because the main thread was never scheduled back in after the other thread was created)
[01:49:46] <@Subv> now lets try creating the other thread with the same priority as the main thread
[01:53:10] <@Subv> creating the thread with the same priority as the main thread allows the main thread to continue up to the FSUSER_OpenFileDirectly (Which is a SyncRequest), where it waits, then the spinwait thread is scheduled in, and never returns
````

This is consistent with our knowledge of the 3DS's cooperative scheduler. The problem in BPB might just be an artifact of erroneous thread scheduling order (#2260 fixes it).
These tests and @wwylele's confirm that there is no preemption going on during svcSyncRequest / svcReplyAndReceive

**Comment by mailwl** [comment]
the game is really pure in used API, but how do you think, it's legal (well not legal of course) but using this info as IDA FLIRT signature for other... games?

**Comment by Subv** [comment]
I have deleted my comment as it was wrong. The 3DS's cooperative scheduler does preempt on some very specific cases (Citra already somewhat implements this, the specific cases will be fixed in my next PR).

See https://gist.github.com/Subv/02f29bd9f1e5deb7aceea1e8f019c8f4 for more information about the 3DS's scheduling behavior.
