### ISSUE TITLE
Keybinds are inconsistent in Citra-QT

### ISSUE THREAD

**Issue by Goofybud16** [citra-emu/citra#2129]
After setting custom keybindings in Citra-QT, the keys will randomly unbind themselves when starting an emulation.

System Specs:

i5-4690k @ 4.3GHz
8GB DDR3
500GB Samsung 850 Evo SSD for / (where Citra-qt is installed)
2TB WD Blue for /home (where .cxi files are and config files are)
R9 Fury running with Mesa 12.0.3
Debian Testing, Kernel 4.7

Citra version: cc7f115
Compiled following instructions provided on Wiki.

Steps to reproduce:
1. Build Citra following Wiki instructions. Install with `sudo make install`
2. Launch citra-qt (terminal or otherwise)
3. Choose File -> Select Game Directory, then select a directory
4. Launch a game. Observe that all keys appear to work correctly. In this case, I used Mariokart 7. 5. Stop the emulation.
5. Choose Emulation -> Configure. Switch to the Input tab. Rebind any keys (in my test case, I rebount **A** to <kbd>R</kbd>, **B** to <kbd>T</kbd>, **X** to <kbd>Y</kbd>, and **Y** to <kbd>U</kbd>). Click OK.
6. Choose Emulation -> Configure. Observe that certain keys are unbound, despite being bound correctly before.
7. Repeat 7, they keys do not appear to change again.
8. Launch the game again. Observe that certain keys do/do not work.
9. While the emulation is running, open the Citra Configuration menu (Emulation -> Configure). Observe the bound and non-bound keys.
10. Stop the emulation.
11. Repeat from 8 as many times as desired. Each time different keys will be bound and unbound.

The only solution I have observed at this time is to completely remove the configuration file and let Citra regenerate it.

[Citra Log.txt](https://github.com/citra-emu/citra/files/532244/Citra.Log.txt)

[Youtube Video Demonstrating Problem](https://youtu.be/dT8rn2SbWJM) Normally the game runs at an acceptable speed, however my recording software (due to encoding on the CPU) caused slowdowns. This does not effect the problem.

**Comment by wwylele** [comment]
cc @makotech222

**Comment by nairaner** [comment]
For some reason sometimes & is added before keybind which causes problems

**Comment by MerryMage** [comment]
Is this still an issue?

**Comment by Goofybud16** [comment]
After testing with the latest commit (0f28ed9ce8bae510728e8651a81e240874022338), I was no longer able to reproduce this issue.
