### ISSUE TITLE
osGetTime() of ctrulib "judders"

### ISSUE THREAD

**Issue by esoteric-programmer** [citra-emu/citra#2130]
Commit: [cc7f115](https://github.com/citra-emu/citra/commit/cc7f1155a890e049299911aa54ec82804a2e5347)

About every 8 seconds (not real time, but time reported by osGetTime()), the time reported by osGetTime() from ctrulib jumps 16 seconds back. Then, 8 seconds later, it jumps 16 seconds forward, and so on. On a 3DS system, the time reported by osGetTime() is fine, thus it might not be a bug in ctrublib, but in citra. See to following simple example for a demonstration (prints time in milliseconds since started; exit via tap or pressing any button): [example_homebrew.zip](https://github.com/citra-emu/citra/files/537343/example_homebrew.zip)
ctrulib commit: [bd34fd5](https://github.com/smealum/ctrulib/commit/bd34fd59dbf0691e2dba76be65f260303d8ccec7)

**Comment by wwylele** [comment]
Didn't look into it but it's probably my bad. The system time is implemented from #1963, where, to mimic the real 3DS behaviour, the time is synchronized with the real time every internal hour. When the program is not running at correct speed (too slow or too fast), it will experience such time jump on synchronization.

So what if you lock the speed to the normal speed (assuming currently it runs too fast) by turning on V-Sync or using other external tools? Does this still happen?

**Comment by esoteric-programmer** [comment]
When turning on V-Sync, the problem still occurs.

**Comment by wwylele** [comment]
I tried the RTC example from devKitPro. It seems that turn off CPU JIT can resolve the problem. So this can be a problem in `CoreTiming::GetTicks` working with JIT.

**Comment by Subv** [comment]
Was this fixed by 27be446049cf09f2025451d53eb6c49597cf097b ?

**Comment by wwylele** [comment]
Nope, this is not fixed in current master

**Comment by Dragios** [comment]
Try to test again on the latest master with the new Dynarmic submodule update. If it is not fix still I will remove the above referenced issue.

**Comment by wwylele** [comment]
Fixed in master cf5b848, probably by updated dynarmic
