### ISSUE TITLE
Luigi's Mansion 2 crash with shader jit

### ISSUE THREAD

**Issue by Zangetsu38** [citra-emu/citra#2137]
Citra crash juste before show anything and log show this :

> [  16.699161] HW.GPU <Error> video_core\shader\shader.cpp:WriteProgramCode:299: Invalid GS program offset 1024
[  18.547832] Debug <Critical> video_core\shader\shader_jit_x64.cpp:operator():789: Assertion Failed!
Tried to compile already compiled shader location!

**Comment by Dragios** [comment]
I'm pretty sure there are more logs beyond this. Can you include all the purple logs here?
And also please fix your typos.

**Comment by Zangetsu38** [comment]
Yes, full Log here
[Log.txt](https://github.com/citra-emu/citra/files/546711/Log.txt)

**Comment by Dragios** [comment]
Based on this log, you're using the Bleeding Edge version, which is not supported. Can you try this game on the latest official build? If this game works on the official build then this case is closed.

Since the server to download official build is down, use this instead which is my own build of the latest master.
https://ci.appveyor.com/api/buildjobs/cq58agxgtpqt69dv/artifacts/citra-latest-windows-amd64.7z

**Comment by Zangetsu38** [comment]
Yes, I know, master build have exaclty same error

**Comment by Zangetsu38** [comment]
Oh yes, works with master build, aznd i have several error 
>[  17.261052] HW.GPU <Critical> core\hw\gpu.cpp:GPU::MemoryFill:89: invalid start address 0x00000000
[  17.261991] HW.GPU <Critical> core\hw\gpu.cpp:GPU::MemoryFill:89: invalid start address 0x00000000
[  17.279723] HW.GPU <Critical> core\hw\gpu.cpp:GPU::MemoryFill:94: invalid end address 0x10B00000

**Comment by Dragios** [comment]
That one is not related if the game still can runs. Case closed then. I suspect is the Geometry Shader branch that causes that assertion failure.

**Comment by Zangetsu38** [comment]
But very Slow in menu, only 3 fps in menu, strange

**Comment by legoj15** [comment]
With this being said, does that mean this is safe to close?

**Comment by Dragios** [comment]
Please have this conversation in Discord channel instead rather than bombarding with useless comments.
Moderators please remove the useless comments if you see this message.

**Comment by Zangetsu38** [comment]
Good news, this problem fixed with last Bleeding Edge version 43, but i don't know why run only 3 fps in menu.
This game appears to be a case and is slow for everyone.
But in general, I do not understand why I have less fps on games in general than the other person.
I see people have 60 fps on games, and I was only 15 or 30/40 depending on the game.
I have an AMD FX 8350 has a 4.6 Ghz and GTX 1080 and those that have more fps me of laptop sometimes are far less powerful than I, except that we all intel.
So I was wondering if there would not be a performance problem with the AMD CPU?
Sorry for my english

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
We do only support the latest nightly builds though. There is no support for Bleeding Edge.
---

Closed as invalid
