### ISSUE TITLE
Cut the Rope: Triple Treat ‒ Emulation stop with fatal error at loading screen

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2138]
Happens with both Shader JIT on/off & hardware/software renderer.
_Does the game works before?_ I don't think so.

Nothing special before the loading screen.
Upon loading the rom it will show a warning not to close the game if you see the candy logo loading as it saves the game automatically, followed by the copyrights notice and then comes the **Activision** logo animation screen.
Next, it will show "The game is best played with a stylus" before it jumps into the loading screen as shown below.

![Cut the Rope - Triple Treat](https://cloud.githubusercontent.com/assets/18496868/19630024/a806ba60-99b4-11e6-8449-658d98edd18b.png)

Log:
![Cmd Log](https://cloud.githubusercontent.com/assets/18496868/19630025/b0a9e746-99b4-11e6-98f6-a6e2ad67a827.png)

**Comment by wwylele** [comment]
> RSL: 0xD8E007F7

```
Module:
  Kernel (1)
Description:
  Invalid handle (1015)
Summary:
  Invalid argument (7)
Level: 
  Permanent (27)
```

So a candidate is unimplemented `mic:u:GetEventHandle`, or in other words, the whole microphone service.

**Comment by Subv** [comment]
See #2168
