### ISSUE TITLE
Harvest Moon 3d - a new beginning HANG

### ISSUE THREAD

**Issue by gdeliana** [citra-emu/citra#2140]
Harvest Moon 3d hangs with infinite errors like these:

HW.Memory <Error> core\memory.cpp:Read:184: unmapped Read32 @ 0x00014E8C

The hex address is constantly changing at the log.

Tried it with Citra Bleeding edge v44.

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support for Bleeding Edge - only Nightly Builds are supported.

---

Closed as invalid
