### ISSUE TITLE
Zelda A link btw Worlds Slowdowns at places

### ISSUE THREAD

**Issue by gdeliana** [citra-emu/citra#2141]
When the slowdown happens, in the log you can see in yellow this message:

[ 118.803602] Service.APT <Warning> core\hle\service\apt\apt.cpp:SetAppCpuTimeLimit:332: (STUBBED) called cpu_percent=30, value=1
[ 119.345845] Service.APT <Warning> core\hle\service\apt\apt.cpp:SetAppCpuTimeLimit:332: (STUBBED) called cpu_percent=20, value=1

Citra Bleeding edge v44

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support for Bleeding Edge - only Nightly Builds are supported.

---

Closed as invalid
