### ISSUE TITLE
Unimplemented function 'ReplySleepQuery'

### ISSUE THREAD

**Issue by Cyxo** [citra-emu/citra#2151]
Hello.

After deleting my Pokemon Y save, I get this error (on the console):
```
[1152.469161] Service <Error> core\hle\service\service.cpp:SyncRequest:74: unknown / unimplemented function 'ReplySleepQuery': port=APT:U, cmd_buff[1]=0x300, cmd_buff[2]=0x74680000
```

I think it is not really hard to implement a game quit or restart (or whatever you want) after getting this message :)

**Comment by mailwl** [comment]
there is no way to put Citra to sleep (and why do it?)

**Comment by wwylele** [comment]
You mean to use the delete save key combination on the title screen? That probably involves rebooting the game which is not implemented in citra.

**Comment by jroweboy** [comment]
@p4ulolol `ReplySleepQuery` appears to do more than just close or restart the game, it also is used to pause the game when an applet such as the system keyboard is launched. (Check the logs in this and you'll see it everytime the software keyboard is activated https://github.com/citra-emu/citra/issues/1583)

**Comment by p4ulolol** [comment]
Ok thanks anyway, I didn't expect it had something to do with system keyboard

**Comment by B3n30** [comment]
closed as the sole existance of such line in the log is not a valid issue
