### ISSUE TITLE
Pokemon X/Y - Debug Panic Error!

### ISSUE THREAD

**Issue by CDAGaming** [citra-emu/citra#2152]
Commit Hash: master-ae2fab4

Issue Details: Issue occurs when loading my Pokemon X Decrypted 3ds rom.
Screenshot:
![2016-11-01](https://cloud.githubusercontent.com/assets/16328918/19908367/0375e7c0-a051-11e6-8c7a-3122a210e9b3.png)
*There are hundreds of lines of the same error after loading

**Comment by wwylele** [comment]
You need to [dump home folder files](https://github.com/citra-emu/citra/wiki/Home-Folder)
---

This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://discuss.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build, or
 - use pirated copies of the games, 3DS BIOS files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid
