### ISSUE TITLE
Build failed on os x el capitan

### ISSUE THREAD

**Issue by algua1213** [citra-emu/citra#2158]
I try to build on my mac but it fails. I have this error:

citra/externals/dynarmic/src/common/mp.h:34:27: fatal error: no template named 'tuple_element_t' in namespace 'std'; did you mean 'tuple_element'?
        using type = std::tuple_element_t<ParameterIndex, std::tuple<Args...>>;

citra/externals/dynarmic/src/common/mp.h:34:27: fatal error: no template named 'tuple_element_t' in namespace 'std'; did you mean 'tuple_element'?
        using type = std::tuple_element_t<ParameterIndex, std::tuple<Args...>>;

** BUILD FAILED **

The following build commands failed:
	CompileC build/externals/dynarmic/src/citra.build/Release/dynarmic.build/Objects-normal/x86_64/disassembler_arm.o externals/dynarmic/src/frontend/disassembler/disassembler_arm.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/externals/dynarmic/src/citra.build/Release/dynarmic.build/Objects-normal/x86_64/disassembler_thumb.o externals/dynarmic/src/frontend/disassembler/disassembler_thumb.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

Any ideas?

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.
Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.

---

Follow instructions on https://citra-emu.org/wiki/building-for-os-x

**Comment by algua1213** [comment]
Thanks!
