### ISSUE TITLE
[OS X] Qt5 build error

### ISSUE THREAD

**Issue by rweichler** [citra-emu/citra#2162]
commit: 1f70365faa75e5dc25108d22bf0a0399b93761df

I followed the build instructions for both OS X and Linux. Neither worked. Some weird issue with qhexedit.

[Error from using Linux instructions](http://pastebin.com/raw/SCCdUSEW)

[Error from using OS X instructions](http://hastebin.com/raw/yimipafipa)

**Comment by JayFoxRox** [comment]
Please avoid renaming issues.
I'm tempted to close this due to the lack of information.

What OS are you building on/for? What compiler? What version of Qt [how was it installed?]? What commands did you run? ...

**Comment by rweichler** [comment]
@JayFoxRox 

All of the information is in the post. the OS is in the title. The compiler is clang. The version of Qt is whatever is on homebrew right now. I used the regular ol' `mkdir build;cd build;cmake ..;make` command.

**Comment by endrift** [comment]
Looks like there's a conflict between the Qt in externals and the Qt you have installed on your system.

**Comment by JayFoxRox** [comment]
Why did you follow the Linux build instructions then?
Did you cmake properly?
Did you export all variables correctly?
Did you use the updated guide? (Updated yesterday!)
Can you check what version of Qt you have?
Did you clone correctly / what steps did you follow / which commands did you run?

This feels like a user error. So we should probably discuss this elsewhere (Forums or Discord?).

**Comment by endrift** [comment]
I'm trying to discuss it in IRC right now.

**Comment by rweichler** [comment]
here is the [stdout](https://gist.githubusercontent.com/rweichler/10e37211fb84f65ad8bc52bcfda8ab5a/raw/bf092e81b7fb56cd7203a2a9f83c2c6591c390ed/stdout.txt) and [stderr](https://gist.githubusercontent.com/rweichler/10e37211fb84f65ad8bc52bcfda8ab5a/raw/bf092e81b7fb56cd7203a2a9f83c2c6591c390ed/stderr.txt) of this:

```
export CMAKE_PREFIX_PATH=$(brew --prefix)/opt/qt5
mkdir build
cd build
cmake ..
make VERBOSE=1
```

**Comment by rweichler** [comment]
Updating Xcode didn't help. Same exact error, except now the SDK changed from 10.11 to 10.12, and used an updated clang.

**Comment by endrift** [comment]
Diagnosed the problem on IRC. It was including a header from Qt 4. `brew unlink qt4` before doing a `make` solved the issue. Not a Citra issue.

**Comment by jroweboy** [comment]
Thanks for the help. I'll add that to the wiki page then
