### ISSUE TITLE
 unknown / unimplemented function 'StoreDataCache'

### ISSUE THREAD

**Issue by Sitasan** [citra-emu/citra#2163]
**Steps to reproduce the Issue:** 
1.  Unresponsive black screen in both top and bottom screens following defeat of champion and directly prior to Hall of Fame registration.  (full log is attached under the relevant subheading)

Log spam during black screen contains multiple instances of lines such as
```
[ 251.545395] Service <Error> core\hle\service\service.cpp:SyncRequest:74: unknown / unimplemented function 'StoreDataCache': port=gsp::Gpu, cmd_buff[1]=0x304A8780, cmd_buff[2]=0x20, cmd_buff[3]=0x0, cmd_buff[4]=0xFFFF8001
[ 251.546669] Service <Error> core\hle\service\service.cpp:SyncRequest:74: unknown / unimplemented function 'StoreDataCache': port=gsp::Gpu, cmd_buff[1]=0x304D4200, cmd_buff[2]=0x200, cmd_buff[3]=0x0, cmd_buff[4]=0xFFFF8001
[ 251.548159] Service <Error> core\hle\service\service.cpp:SyncRequest:74: unknown / unimplemented function 'StoreDataCache': port=gsp::Gpu, cmd_buff[1]=0x304C6200, cmd_buff[2]=0x1000, cmd_buff[3]=0x0, cmd_buff[4]=0xFFFF8001
```
2. Error is reproduced whether or not Shader JIT is on/off and whether or not software/hardware renderer is used

**Build:** Bleeding Edge 46 (HEAD-a803978) but I believe that it would be present in all prior builds too.
**Affected game:** Pokemon Moon
**Operating System:** Windows 10 64 bit 

**Full Log** (log contains events including and up to the defeat of the champion and subsequent attempt at Hall of Fame registration)
https://gist.githubusercontent.com/Sitasan/536c7d5208ef54cc12cdc9191d77c683/raw/179f8f88432b8a6818c8b9a5dbc827dde1d28902/service.cpp
**Save file:**
[00175e00.zip](https://github.com/citra-emu/citra/files/582316/00175e00.zip)

**Comment by Sitasan** [comment]
Actually, is this a duplicate of issue $1428?

**Comment by wwylele** [comment]
we don't accept issue report from bleeding edge build, nor from pokemon sun & moon leak.
