### ISSUE TITLE
Improvement: simplify dumping the config savegame

### ISSUE THREAD

**Issue by d0k3** [citra-emu/citra#2167]
The process described here can be simplified greatly:
https://github.com/citra-emu/citra/wiki/Home-Folder#how-to-dump-the-config-savegame-nanddata00000000000000000000000000000000sysdata0001001700000000config

Decrypt9 can dump the file at ctrnand:/nand/data/00000000000000000000000000000000/sysdata/00010017/00000000 directly. The option is in SysNAND -> Dump System Saves -> Dump configsave.bin (alternatively EmuNAND). The output file is called "configsave.bin". This file should be mountable via the process described in step 6.

**Comment by JayFoxRox** [comment]
The wiki is publicly editable. Feel free to add information on your own.
(As alternative approach maybe, as we might need a full NAND for other things)

**Comment by d0k3** [comment]
[Decrypt9WIP](https://github.com/d0k3/Decrypt9WIP) can now dump the "config" file directly - I assume this almost means that wohle page can go. Afaik, @Plailect is on it, though.

**Comment by Plailect** [comment]
It has been edited in.

**Comment by d0k3** [comment]
Closing this now...
