### ISSUE TITLE
Strange lines of code

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#2169]
I am trying to make run fw application "Friend List", and found some strange things:

1) https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/kernel.cpp#L133
Friend List try to allocate memory, which don't fit in this layout

2) https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/process.cpp#L139
kernel_version == 0x22C, but app from old 3ds

3) https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/process.cpp#L88
not related, but very odd, local var not used after assigning

**Comment by Subv** [comment]
> https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/kernel.cpp#L133
Friend List try to allocate memory, which don't fit in this layout

See #1849 

> https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/process.cpp#L88
not related, but very odd, local var not used after assigning

IIRC that's IO pages, which we don't currently handle (Or we handle them elsewhere)

**Comment by Subv** [comment]
> https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/process.cpp#L139
kernel_version == 0x22C, but app from old 3ds

I don't think it matters, the real kernel performs that check too.

I'll close this because it isn't really a bug report.

**Comment by JayFoxRox** [comment]
I actually think this was a valid report. If you know reasons for the code being like that it should be documented in the source code itself (as part of a comment).

**Comment by yuriks** [comment]
It's 3 unrelated issues in one report. It would be better if they were filed separately. (For example, some of those seem to be invalid/WAI, and it's hard to managed if they're in one issue.)
