### ISSUE TITLE
Where to find my older file for Citra after updates? HELP PLEASE

### ISSUE THREAD

**Issue by qin93** [citra-emu/citra#2174]
Recently i've played pokemon omega ruby on citra edge 0.1.46 and saved the game frequently. However today it updated to new version build of 0.1.56 and when i opened it load the old save games which means not the updated save game i save before. So when ive open the file location, the citra 0.1.46 have been deleted same goes with my save file for the game. Please help me or teach me how to regain back my save file from that older game folder that citra deleted?

**Comment by jroweboy** [comment]
This is an issue tracker for developers. Please do not open bug reports here. Use the official forums for help on the matter. https://discuss.citra-emu.org/ Open a support request there instead.

Closed as invalid.
