### ISSUE TITLE
Mario Party Star Rush is unstable

### ISSUE THREAD

**Issue by legend800** [citra-emu/citra#2176]
Repro steps:
1) Launch game
2) Play for about 5-20 min

Results:
The game will eventually (seemingly randomly) become unstable:
It may crash when loading a minigame
or...
It may freeze during gameplay.

Version being used (observed on a few different recent builds):
Bleeding edge - a803978

Specs:
Geforce GPU
Intel CPU
Win 10

Original thread here - and confirmation from another user:
https://discuss.citra-emu.org/d/868-problem-in-citra-need-help-mario-party-star-rush-game-crash

These two line are observed at the end of log if it helps:

```
[ 654.304285] Audio.DSP <Error> audio_core\hle\source.cpp: DequeueBuffer:249: Looped buffers are unimplemented at the moment

[ 115.167631] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:484: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched.
```

**Comment by JayFoxRox** [comment]
Please find a nightly build where this happens - bleeding edge might contain code which is not in master.
We have to avoid false positives.

**Comment by legend800** [comment]
Thanks for the response. Here are my comments:

1) I can't access nightly builds at the moment - not available:
https://citra-emu.org/page/download

2) The stability issues seem to occur within 5 mins more often than not.

3) What debugging settings do you want on exactly?

**Comment by Subv** [comment]
Does this still happen?
Our nightly builds are back, please re-test it.
