### ISSUE TITLE
Screen layout discussion

### ISSUE THREAD

**Issue by SonofUgly** [citra-emu/citra#2178]
This is a followup to some issues and ideas from https://github.com/citra-emu/citra/pull/1753

## Issues
- [ ] Minimum window size needs changed depending on what layout is used. [400*480 is the current minimum.](https://github.com/citra-emu/citra/blob/master/src/common/emu_window.h#L211)
- [ ] Independent screen rendering resolution. Currently the rendering resolution for both screens is determined by the top screen's size.
- [ ] https://github.com/citra-emu/citra/pull/1753#discussion_r87596409
- [ ] Change which screen gets drawn first - for a screen overlap option. [Top screen always gets drawn first currently.](https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/renderer_opengl.cpp#L408)

## Enhancements
- [ ] Hotkey to switch between layouts.
- [ ] Individual windows per screen.
- [ ] Screen rotation.
- [ ] Screen gap. Some games take the gap between the 3DS' screens into account. A n3DS has ~80px gap at native resolution, n3DS XL ~72px, and 2DS ~38px.
- [ ] Overlapping screen. [Here's an example video](https://a.pomf.cat/qcqvmh.webm) of overlapping the bottom screen at 1x over the 'single screen' layout. Or have it work more like [large screen](https://a.pomf.cat/cylxja.webm) layout and not center the large window.
- [ ] And a hotkey to switch the overlap option on/off.
- [ ] Secondary screen position. Should be able to change where the secondary screen is on any layout. Like having the bottom screen be on the sides with the default layout, or putting the small screen in any corner/side with the large screen layout. Having a [little radio button table thing](http://i.imgur.com/QiE9L7n.png) could work.

Also, previously discussed but curious if anyone else has an opinion, IMO how the large screen layout should work: large screen scales to fit the window, and the small screen remains at its native resolution (maybe 2x native for 4k and above monitors). [Example](https://a.pomf.cat/oudnmw.webm).
How it currently works: the large screen is 4x the small screen and they both scale to the window's size. [Example](https://a.pomf.cat/mhsmps.webm).
My reasoning: Citra shouldn't display at a lower than native resolution. The bottom screen (the secondary screen in most games) often has text, which can be hard to read at a lower than native resolutions. The bottom screen is mostly 2D, so it would be best to keep it integer scaled.

**Comment by RavenHome1** [comment]
can i request a side by side screen layout

**Comment by JayFoxRox** [comment]
* "Individual windows per screen." and "Screen rotation" are more complicated and should be seperate issues in my opinion.

* "Hotkey to switch between layouts." and " And a hotkey to switch the overlap option on/off." are a seperate issue about making it possible to map most config options to hotkeys.

* "Secondary screen position." is far more complicated and conflicts with our simple existing layouts. As such, it's a seperate issue about creating more complicated layouts.

* "Minimum window size needs changed depending on what layout is used. 400*480 is the current minimum." is a concrete feature / bug and deserves it's own issue. It should be fixed asap

* "Independent screen rendering resolution. Currently the rendering resolution for both screens is determined by the top screen's size." also a seperate issue, please create one accordingly.

---

Some of these other features, such as "screen gap", only make sense for some layouts.
So we need a more complicated config setup which shows extra configs per config. This would also be useful for different audio / video / cpu backends.

---

The problem with these meta issues that it's hard to find them later + nobody will ever complete the entire checklist.
So please give unique identifiers to each problem so we can make the disucsion easier, then split as many features as possible into seperate issues (so they can be worked on).

**Comment by SonofUgly** [comment]
Some of these can be done through custom layout now, and the rest should be split into individual issues as JFR said.
