### ISSUE TITLE
Phoenix Wright - Ace Attorney - Dual Destinies Issue

### ISSUE THREAD

**Issue by ZER0SHAWN** [citra-emu/citra#2179]
The Models are Mess up and the background is pitch black and the for somehow the frame rate are low making it unplayable

Here's a Citra screenshot
![screenshot 616](https://cloud.githubusercontent.com/assets/23099589/20344503/e109fb6a-aba7-11e6-964b-6d6779649bc4.png)

And here's a hardware screenshot
![phoenix_wright_dual_destinies_launch_screenshot_012](https://cloud.githubusercontent.com/assets/23099589/20344726/bc1acf7c-aba8-11e6-970b-514b52df9692.jpg)

I'm using CPU JIT builds (some CPU JIT builds doesn't work either)
I tried to open this to bleeding-edge builds but it doesn't work

**Comment by ZER0SHAWN** [comment]
I for

**Comment by JayFoxRox** [comment]
This needs more info (affected versions of citra etc). I feel this is a GS issue but it's a good one.
