### ISSUE TITLE
When using homebrew

### ISSUE THREAD

**Issue by TechnoPrism** [citra-emu/citra#2180]
I try using hbc but I cant upload all the hoc files I want to. Can u make it so that all the files that can be used in hbc show up when in use

**Comment by jroweboy** [comment]
Github is not the right place to log this. Please ask on the forums help and support requests like this one.

**Comment by TechnoPrism** [comment]
Where would be a good place to say this or find out how to use it
>
>

-- 
parker hirschi

a school
student

**Comment by jroweboy** [comment]
>  Please ask on the forums for help and support requests like this one.

https://discuss.citra-emu.org/

**Comment by TechnoPrism** [comment]
Thank you for your help
>
>

-- 
parker hirschi

a school
student
