### ISSUE TITLE
How do u use homebrew

### ISSUE THREAD

**Issue by TechnoPrism** [citra-emu/citra#2181]
I tried using hbc and when I did I can't use any of the hbc apps I downloaded can u fix this?

**Comment by TechnoPrism** [comment]
Or explain to me how to use hbc with citra

**Comment by wwylele** [comment]
Please don't spam

**Comment by TechnoPrism** [comment]
Ok, how would I find out how to use it on the cigar program though

**Comment by TechnoPrism** [comment]
Citra*
