### ISSUE TITLE
Pre-compiled builds?

### ISSUE THREAD

**Issue by hiya-tiger** [citra-emu/citra#2182]
I would just like to download Cintra without any hassle... :/

**Comment by wwylele** [comment]
Nightly is down. We are fixing it.

-----
This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://discuss.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build, or
 - use pirated copies of the games, 3DS BIOS files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid
