### ISSUE TITLE
why not try vulkan ?

### ISSUE THREAD

**Issue by KnightBlood** [citra-emu/citra#2184]
why not try vulkan 
i think you can build a branch use vulkan

**Comment by jroweboy** [comment]
Why not write it yourself? 

This is not a place for feature requests. Please use the forums for that instead. Closed as invalid.

(PS Someone did start on it. so you have a head start)

**Comment by JayFoxRox** [comment]
![why not vulkan?](https://media.makeameme.org/created/why-not-vulkan.jpg)
