### ISSUE TITLE
Pokémon Moon: Main thread lockup at fade transition to hall of fame

### ISSUE THREAD

**Issue by j-selby** [citra-emu/citra#2190]
At commit fb13bfe

Pokémon Moon (I don't have Sun to test, but I would assume that the same happens there) crashes at the end of the final battle, transitioning into a black screen, which should normally load into the hall of fame. [Stubbing StoreDataCache](https://github.com/j-selby/citra/tree/stub-data-cache) does not fix the problem.

EDIT: All 6 of my Pokémon have nicknames.

Issue occurs when compiling Citra using both Mingw and MSVC.

End of Log: (that was a nice 50MB total log file...)
https://gist.github.com/j-selby/53f967f6d447c016645a2ea258b94b1c

Save File (You do have to go through a pretty long battle, as there is no place to save between this point and the crash): [00175e00.zip](https://github.com/citra-emu/citra/files/601363/00175e00.zip)

EDIT (Updated): Wait Tree:
![updated waittree](https://cloud.githubusercontent.com/assets/1404334/21628666/48707218-d275-11e6-9424-7af9753b22a7.png)

**Comment by EnderTheFerret** [comment]
so I found 2 fixes for this issue I had it as well.
1.fight the elite 4 only with 3 pokemon (it would take some grinding tho)
2.i didn't test that but there is an option in PKHex that makes you the champion without fighting (**use it at your own risk!!!!!)**

**Comment by Subv** [comment]
Could you please try with #2393 and see if that fixes it?

**Comment by Dragios** [comment]
@EnderTheFerret Those are not fixes. More of an override/bypass method to circumvent the issue.

**Comment by lefta** [comment]
@subv I just ran on this issue with my own save, so this PR did not fix it. I'm on 16a3f9e3.

**Comment by therabidpotatoe** [comment]
Can someone please give me a walk-through on how to fix this problem(I am extremely new to programming and don't really know what I'm doing)?

**Comment by einstein95** [comment]
@therabidpotatoe Learn how to program

**Comment by adityaruplaha** [comment]
Hmmm..... Can anyone tell me what exactly is the problem? Why the he*k is the main thread locking up?

**Comment by RavenHome1** [comment]
just a heads up, the same issue exists in ultra sun/moon *spoilers after this point* after you fight hau in the league.

**Comment by B3n30** [comment]
This is an edited savegame of the one above with all pokemons in the party at LV 100 to make testing a bit faster:
[main.zip](https://github.com/citra-emu/citra/files/1649181/main.zip)

**Comment by CaptV0rt3x** [comment]
Can confirm still occurs on Pokemon Sun as well. 
Tested on [Canary 310 - 4a11be6](https://github.com/citra-emu/citra-canary/commit/4a11be6614013406f78c59e9b9294cb39076cbd0)

**Comment by wwylele** [comment]
Fixed by #3440
