### ISSUE TITLE
I Continuously Get Error Messages When trying to run games 

### ISSUE THREAD

**Issue by TheHomeyDrake** [citra-emu/citra#2191]
This probabaly sounds stupid to some but i keep on getting these errors popping up in red when i launch a game in Citra. I am specifically trying to launch Paper Mario Sticker Star and i see that everyone on Youtube at this moment can run this game absoluteley fine at full speed. This is the error that i keep getting:  

4.412708] HW.GPU <Error> video_core\shader\shader.cpp:WriteProgramCode:299: Invalid GS program offset 1024

I dont know if its my graphics card or my drivers but they are all up to date to the latest versions. I also think that it might be the actual game but im not too sure. Here are my PC specs:
Intel Core I5 4690K
Geforce GTX 670
Corsiar Vengeance Pro 16GB DDR4 RAM

This is the Version of Citra im using. What the programs called:

citra-qt-gcc-jit-sse3-15.exe

Maybe someone knows what this issue is wich they probabaly do. I also keep getting some other errors on launch but i cannot remember what they were.

**Comment by wwylele** [comment]
This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://discuss.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build (__you are using one!__), or
 - use pirated copies of the games, 3DS BIOS files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid
