### ISSUE TITLE
Build fails on architectures other than amd64

### ISSUE THREAD

**Issue by linkmauve** [citra-emu/citra#2201]
When building on AArch64 for example, the following error happens:
```
In file included from /mnt/dev/citra-git/src/citra/externals/dynarmic/src/./backend_x64/abi.h:10:0,
                 from /mnt/dev/citra-git/src/citra/externals/dynarmic/src/backend_x64/abi.cpp:19:
/mnt/misc/citra-git/src/citra/externals/dynarmic/src/./backend_x64/hostloc.h:93:8: error: ‘Reg64’ in namespace ‘Xbyak’does not name a type
 Xbyak::Reg64 HostLocToReg64(HostLoc loc);
        ^~~~~
```

This happens on 609023ceaf6bc8ab2cc4b9f359aeb83ba777c841 (latest master), and is a regression compared to before dynarmic.

**Comment by jroweboy** [comment]
This is a known issue with dynarmic and is reported on that repo here https://github.com/MerryMage/dynarmic/issues/35

(We also had a discussion on it in this pull request https://github.com/citra-emu/citra/pull/2123 In short, lots of discussion about enabling 32bit, and Aarch64 builds by adding a disable JIT flag and so on.)

**Comment by JayFoxRox** [comment]
I'll add that `video_core` already has checks in shader/shader.cpp and CMakeLists.txt to disable compilation of the JIT for non x64 builds.
We can probably easily adapt this for the frontends and the CPU code

**Comment by BreadFish64** [comment]
Citra is currently buildable on Aarch64 and we have no plans to enable 32-bit support.
