### ISSUE TITLE
Audio Failure during emulation

### ISSUE THREAD

**Issue by Sashpuri** [citra-emu/citra#2205]
Tried reinstalling a couple of times, emulation works perfectly, lack of audio each time

Here's the error message 
[   0.000621] Audio.Sink <Critical> audio_core/sdl2_sink.cpp:SDL2Sink:48: SDL_OpenAudioDevice failed
![s1](https://cloud.githubusercontent.com/assets/14137548/20529227/7e73d496-b0f5-11e6-8051-a1d71e44e708.png)

**Comment by freiro** [comment]
Does audio work in other applications?

**Comment by Sashpuri** [comment]
Yes, working fine everywhere else

**Comment by mailwl** [comment]
may you try with SDL 2.0.5?
sorry, i don't know, how to replace it correctly, maybe Merry helps

**Comment by freiro** [comment]
This is not enough information to understand what happens, if you feel comfortable editing the code please do the following (this will not fix your problem, just increase verbosity):
In file src/audio_core/sdl2_sink.cpp, line 47 change

`        LOG_CRITICAL(Audio_Sink, "SDL_OpenAudioDevice failed");`

with

`        LOG_CRITICAL(Audio_Sink, "SDL_OpenAudioDevice failed with: %s", SDL_GetError());`

Compile again, execute citra and give us the "new" error.

**Comment by Subv** [comment]
> This is not enough information to understand what happens, if you feel comfortable editing the code please do the following (this will not fix your problem, just increase verbosity):

Could you please make a PR with this change? It'd be very useful.

**Comment by Sashpuri** [comment]
Did exactly as you asked, here's the output

**[   0.054857] Audio.Sink <Critical> audio_core/sdl2_sink.cpp:SDL2Sink:48: SDL_OpenAudioDevice failed with: No such audio device**


![s2](https://cloud.githubusercontent.com/assets/14137548/20531056/85156f34-b0fb-11e6-947f-df1fa083db72.png)

**Comment by mailwl** [comment]
i saw this error, when not inserted headphone was only sound output device.
may you show your settings with output devices?
i have russian windows, so, don't know, how it looks on yours. On me it looks:
![sound](https://cloud.githubusercontent.com/assets/629437/20531802/ebf52dba-b0e8-11e6-8c48-fa21caf7c2bc.png)

**Comment by freiro** [comment]
@Subv done

@Sashpuri this is something we need to investigate but may as well be a problem with your configuration.

**Comment by Sashpuri** [comment]
I'm working on Ubuntu, so there isn't any menu to configure my hardware output devices really, its all terminal
From my knowledge, i was able to list the playback audio devices as follows
![sb](https://cloud.githubusercontent.com/assets/14137548/20532570/7d882964-b100-11e6-890e-3e8b52113afb.png)

Here's some other details about my audio output devices I was able to fetch
![sc](https://cloud.githubusercontent.com/assets/14137548/20532690/e5fcd742-b100-11e6-9680-84d59fd90e17.png)
![sd](https://cloud.githubusercontent.com/assets/14137548/20532704/ef1e824e-b100-11e6-8d85-52584dfd9a6e.png)

And here's the audio modification menu, not much use
![Uploading sb.png…]()

**Comment by mailwl** [comment]
Ahh, ubuntu, sorry then, i am not linuxoid

**Comment by freiro** [comment]
Can you provide which version of ubuntu, output of "uname -a" and your full setup?
Also for long terminal outputs it might be easier to use [pastebinit](https://help.ubuntu.com/community/Pastebinit)
`sudo apt-get install pastebinit`

**Comment by Sashpuri** [comment]
My Version is : Ubuntu 16.04 LTS
Linux sash 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Didn't really get what you meant by my full setup, any command's output i should give you?

**Comment by freiro** [comment]
By full setup I meant laptop or desktop, which model (CPU,GPU,Motherboard etc.) at least for reference.

I just tested Citra under Ubuntu linux 16.04 and it works properly, can you copy the relevant output from:

`ldconfig -v | grep SDL 
aplay --list-devices 
lspci -vv
`

**Comment by Sashpuri** [comment]
Full setup: http://pastebin.com/sxAeuvmi
SDL command output: http://paste.ubuntu.com/23518011/
Playback Hardware Devices command output: http://paste.ubuntu.com/23518017/
Lspci command output : http://paste.ubuntu.com/23518019/

**Comment by freiro** [comment]
@Sashpuri did you build SDL2 yourself or downloaded with apt-get?

**Comment by Sashpuri** [comment]
apt-get

**Comment by Sashpuri** [comment]
Removed the SDL, reinstalled it and built it again, its working now, thanks a lot for your help :)
