### ISSUE TITLE
Pokemon sun FPS

### ISSUE THREAD

**Issue by Dennis002** [citra-emu/citra#2214]
Hi, im experiencing an extreme lag in using pokemon sun on Citra, or better in close area like Home's it's very fluid, but in a large one like a city or a normal fight it's very laggy.
I tried tu uncheck the frame limit but the result its the same, my conf is i5 4590 and r9380 4gb, so i don't think that the problem is it
Any solutions?

**Comment by emmauss** [comment]
please use the forum or discord to discuss these things. the issue tracker aint for these.

**Comment by jroweboy** [comment]
This is an issue tracker for developers. Please use the forums for help and support. https://discuss.citra-emu.org/

Closed as invalid
