### ISSUE TITLE
Use of `false` / `true` instead of `GL_FALSE` / `GL_TRUE`

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra#2219]
While reviewing #2218 I noticed that our use of GL constants and types is usually very sloppy.
Often when we are working with `GLboolean` variables (which should be `GL_FALSE` or `GL_TRUE`) we still assign `bool` constants (`false` / `true`) instead of the actual GL enums.

While this probably doesn't cause any bugs it's still not good for code quality either and should be fixed.

[Example for bad code](https://github.com/citra-emu/citra/blob/49b10339bf87ce69dafee78eb3957fb6d51424d8/src/video_core/renderer_opengl/gl_rasterizer.cpp#L873)

**Comment by Illasera** [comment]
I am not sure if i follow the example but the CORRECT practice and i do mean correct as in right and not wrong , is to use the API typedefs and datatypes given.

Firat , Tomorrow khronos team can release a version to their standards and and will claim that GL_TRUE value is 1002 , and they will be in their right to do so.

Second , the openGL headers as well as GLEW were written againts the C language, The C language does not define bool datatype nor true and false.

To sum it all up , use the given API values as good practice and save yourself from future bugs and headaces.

**Comment by JayFoxRox** [comment]
@Illasera yes. This is just to confirm what this issue is about: The issue (problem) is "use of `false` / `true`". The proposed solution is `GL_FALSE` / `GL_TRUE` (for your reasons mostly).

**Comment by JSFernandes** [comment]
I was looking to get some early contributions and it seems that this has already been fixed by #2356 
I also double checked and couldn't find any other incorrectly set `GLboolean`s. Should this issue be closed?
