### ISSUE TITLE
Crash at Shutdown

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#2221]
This is a very old but not documented(?) issue.

A common crash happens here:
![image](https://cloud.githubusercontent.com/assets/4592895/20651480/f09cb7a2-b4ee-11e6-900e-c991597371fb.png)

where `g_renderer` is already reset in `VideoCore::Shutdown();`

Edit: this is on the master d3b7f57, running Pokemon Sun (but this can happen in many other games)

**Comment by freiro** [comment]
You should check this on master (just to be sure is not something related to framelimit).

**Comment by RavenHome1** [comment]
i always wanted to open up an issue regarding the crash, but since it's been there for a long time i figured it was an already known issue

**Comment by yuriks** [comment]
I think this is a race condition between the frontend and the backend. We need to fix our threading.

**Comment by wwylele** [comment]
@yuriks I don't think it does anything with the front-end. 

All `Shutdown` is called in a determined order in on thread. The problem is that the `Kernel::Shutdown` can sometimes try to access the video core (which is already shut down) due to a scheduled VBlank event. Probably we can call it a race condition in our emulated threading.

**Comment by wwylele** [comment]
It seems that this doesn't happen any more on my side. Probably fixed by recent scheduler reworking. Close this for now.

**Comment by yuriks** [comment]
This was actually more likely fixed by #2343

**Comment by RavenHome1** [comment]
the crash happened again on shutdown with bleeding 144.

**Comment by RavenHome1** [comment]
i tried to debug using visual studio but i couldn't do it here is what i can provide 

![capture](https://cloud.githubusercontent.com/assets/12820322/22174476/28dfecb4-dfe8-11e6-8f1b-ccf8b4cdc89a.PNG)

**Comment by wwylele** [comment]
@RavenHome1 It seems that the cause is different, given the Fault Module Name is OPENGL32.dll. Please make sure your graphics is updated and no graphic hooking software is running. If the problem is still there, open a new issue

**Comment by RavenHome1** [comment]
@wwylele i got the crash again but this time it is different, the crash happens if you attempt to close the console window instead of the QT GUI


![capture](https://cloud.githubusercontent.com/assets/12820322/22399202/84421236-e5a0-11e6-95b1-1f2cfaa16a6b.PNG)


![capture2](https://cloud.githubusercontent.com/assets/12820322/22399203/872e6080-e5a0-11e6-9043-3288b6d61486.PNG)

should i open an issue for this?

**Comment by yuriks** [comment]
@RavenHome1 Please do

**Comment by RavenHome1** [comment]
@yuriks i tried with the latest nightly and the issue did not happen, but on the latest bleeding (162) it does happen, does this change anything or should i continue with opening up a new issue for this?

**Comment by yuriks** [comment]
@RavenHome1 In that case it would be better to try to figure out which PR causes the crash and posting this there.

**Comment by RavenHome1** [comment]
@yuriks i tried to move backward from bleeding 162 to 86 and all of them have the crash issue while the latest nightly does not, could this be a bleeding edge only issue?.

**Comment by yuriks** [comment]
@RavenHome1 It's possible it's a gcc-related problem. If it happens in a lot of versions then I think you can open an issue saying that since it's probably not just a one-off issue with a PR.

**Comment by RavenHome1** [comment]
@yuriks alright i will open an issue and try to add as much details as i can

**Comment by WizLizard** [comment]
I'm having this issue with the latest Stable and Canary build. Every time i close the emulator i get a crash.

**Comment by RavenHome1** [comment]
@WizLizard  what you speak of is a different known issue

**Comment by WizLizard** [comment]
Oh sorry is there already an issue opened for it?

On Oct 28, 2017 3:42 AM, "RavenHome1" <notifications@github.com> wrote:

@WizLizard <https://github.com/wizlizard> what you speak of is a different
known issue

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/citra-emu/citra/issues/2221#issuecomment-340157305>,
or mute
the thread
