### ISSUE TITLE
Cut the Rope: Triple Treat ‒ Crash with Shader JIT on

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2226]
Now that #2168 has been merged the game will only load when *Shader JIT* is disabled. Enabling *Shader JIT* will result in a crash.

Related to #2138 

*Crash Log*
![crash log](https://cloud.githubusercontent.com/assets/18496868/20666561/bf2da8c8-b59f-11e6-803a-79c5d10aa2c0.png)

Tested on the latest commit as of 3174bfd using my own build.

**Comment by Subv** [comment]
That's not a crash log, what's your OS and compiler? Please provide a backtrace.

**Comment by Dragios** [comment]
OS: Windows 10 build 14393.447
Compiler: Both MSVC and MinGW

![Output](https://cloud.githubusercontent.com/assets/18496868/20671774/a9adc8e2-b5b9-11e6-9656-7b93b57b7007.png)
![Call stack](https://cloud.githubusercontent.com/assets/18496868/20671775/aa8cd8d4-b5b9-11e6-89cc-e693c8c9ea22.png)
![Disassembly](https://cloud.githubusercontent.com/assets/18496868/20671778/ac1bc642-b5b9-11e6-9315-461b8f54bb04.png)

**Comment by JayFoxRox** [comment]
Fixed by #2255
