### ISSUE TITLE
[Performance] - Silence the IO logger by default

### ISSUE THREAD

**Issue by Illasera** [citra-emu/citra#2231]
While it may seems harmless and a good idea to print away all the errors and warning to the terminal,
Its not, it is slow, and i am talking about performance impact that sums up to a real number counted in frames per second (I don't need to prove it because its proven already and its kinda common knowledge and i shall explain the slowdown below)
I shall also provide methods of fixing it. 

The first issue is that rendering to a terminal requires a different , old and extremely unpotimized code to run, see here : http://stackoverflow.com/questions/11487568/c-does-printing-to-terminal-significantly-slow-down-code

The second problem is , using the output buffers are limited in their size and assuming you are calling the logging functions from a non dedicated thread, writing to such buffers is considered a "blocking operation" which means your emulator will have to wait until the operation is done, The kernel/operating system also need to perform a lot of internal operations in order to deal with the given I/O. and as mentioned earlier, not only that the rendering process is slow, but the operating system I/O handling is also slow.

Both of the above actually do add up to a measurable performance issue, so how to resolve?

1.)By default, we silence the terminal output messages (except fatal/crashing errors).
2.)We only output critical errors that cause crashes.
3.)We use a unique logger for warnings, That means that if we have multiple warnings with the same string, we only write down the warning ONCE.
4.)We write non critical errors and all warnings at the proper time, delayed writing if you will, which should be when the emulator starts or closes down, in the meantime, we hold the error strings in RAM without writing them.

Hope that helps.

**Comment by wwylele** [comment]
I am against doing such performance enhancement on the logging system _at current stage_.There are still so many unimplemented things and hidden bugs that we can't even tell whether each log is important or not. We had cases like one small warning in one careless screenshot turning out to be critical to resolve the issue. We will lose many useful log report if we silence the log now. I like the ideas of yours to improve the performance, but we really should do that only when citra gets much stable.

**Comment by Illasera** [comment]
Well, You are not really losing any data since you are saving it all in your RAM storage and then flushing it to a file, But , If you care so much about displaying everything at runtime, I may suggest at least writing it to a QT window since you guys are already using it, Or even better, an internal virtualized console ingame that is rendered with openGL (Since you are using that as well).

On a sidenote, It does not mean it should be down now but it needs to considered.

**Comment by freiro** [comment]
Unfortunately this is a complicated issue atm, we should move the logging to a file for general users, and allow them to enable it in case of problems.

**Comment by JayFoxRox** [comment]
Did you look at the logging before writing this issue?

New log entries are created - non-blocking - in the [Logger backend](https://github.com/citra-emu/citra/blob/master/src/common/logging/backend.cpp)
Afterwards they are printed using the [text_formatter](https://github.com/citra-emu/citra/blob/master/src/common/logging/text_formatter.cpp) (which, indeed, is blocking).

It has been discussed numerous times to implement a Qt frontend for logger or a flush to file at the end of emulation. However, there are more important issues at hand.
If you feel like this is important you are free to work on an alternative to the text_formatter.

Note that the backend also [supports filtering](https://github.com/citra-emu/citra/blob/master/src/common/logging/filter.cpp) to print fewer messages.
However, we strongly advise against it as these logs are usually the main indicator for unimplemented features and solving support requests. Unfortunately it's common for unofficial builds to change these configs which has lead to confusion in the past, when certain warnings did not appear for some users.

(Also see #258 for the original PR which implemented it)

**Comment by Illasera** [comment]
Noted and i shall look into it and see if i can help.

**Comment by Subv** [comment]
I'm against this. There are many other slower hotspots that we could optimize before resorting to desperate measures like removing the logging.

**Comment by Illasera** [comment]
You may want to give the post another read, we are talking about redirecting the output to a faster medium (as in, QT window or virtualized console rendered in openGL within the emulator itself) and adding the  _option_  to silence the terminal output, obviously one shouldn't remove warnings/errors from any software.

**Comment by yuriks** [comment]
We used to have an asynchronous logger. It didn't help with performance much. You can just make the log filter more strict in the configuration. Something like logging to a Qt pane that allows saving to a file could certainly be done, but that's a separate issue.
