### ISSUE TITLE
Generator Rex Agent of Providence - Hangs at menu while saving

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#2237]
Tested on https://github.com/citra-emu/citra/commit/cf5b8483fc53ca3b4919d231045348625a507d05 .

[LOG](http://pasted.co/6ca984c8)

![generator](https://cloud.githubusercontent.com/assets/11453507/20746112/babed2da-b6e4-11e6-8875-23eee57765ad.PNG)

**Comment by j-selby** [comment]
> [  35.449064] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:74: unknown / unimplemented function 'ControlArchive': port=fs:USER, cmd_buff[1]=0x7, cmd_buff[2]=0x0, cmd_buff[3]=0x0, cmd_buff[4]=0x1, cmd_buff[5]=0x1, cmd_buff[6]=0x1A, cmd_buff[7]=0xFFFFEC4, cmd_buff[8]=0x1C, cmd_buff[9]=0xFFFFEC0

Does this work with #1748 ? Its an old commit, but it does implement this function.

**Comment by Subv** [comment]
Does this still happen?

**Comment by JohnGodgames** [comment]
Tested on https://github.com/citra-emu/citra-nightly/commit/b36677daff771d4791f3b13e0d7cb95f4b0b47f6

I can't get past this:

![generator rex](https://cloud.githubusercontent.com/assets/11453507/21862004/b4ae6224-d837-11e6-98f1-68281d041ae9.PNG)


[LOG](http://pastie.org/10989351)

**Comment by Subv** [comment]
So the original bug was fixed? Please open a new issue for the new bug.
