### ISSUE TITLE
Real Heroes Firefighter 3D - Black screen after Loading screen

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#2239]
Tested on https://github.com/citra-emu/citra/commit/cf5b8483fc53ca3b4919d231045348625a507d05 .

[LOG](http://pastebin.com/wHCuP6Dq)

![real](https://cloud.githubusercontent.com/assets/11453507/20747004/aa2707cc-b6e8-11e6-9835-10e84ea4ed71.PNG)

**Comment by mailwl** [comment]
it's really funny, if you merge @JayFoxRox  branch https://github.com/JayFoxRox/citra/tree/gs-new-refactor to pass this stuck, but later game stuck again on:
![firefighter](https://cloud.githubusercontent.com/assets/629437/21240137/fb270a9e-c31a-11e6-8344-aac99e706340.png)

and on next run game stuck again on screen from TS, until delete save at title\00040000\000b9900

**Comment by JayFoxRox** [comment]
Your takeaway is very different from mine about this one @mailwl .
I'd like to see an updated master log + a lot for GS rebased onto master.
Your finding suggest that the game doesn't get stuck at all, but merely renders a fullscreen quad or something which we can't see without GS.
However, the original log doesn't contain anything about GS instructions, so theoretically, my GS branch should not have any impact at all. This probably means that the original log is outdated already.

**Comment by Subv** [comment]
Does this still happen?

**Comment by JohnGodgames** [comment]
I can go past loading screen and after that nothing.Looks like that the game uses GS to show more.Add GS label someone pls

**Comment by Subv** [comment]
Please update the top post and remove the old information.

**Comment by wwylele** [comment]
Is this fixed?

**Comment by benderscruffy** [comment]
it is the same as the first post using the latest nightly and canary
![fire](https://user-images.githubusercontent.com/2696404/32989934-bb29a2a8-cd5a-11e7-80a2-cbf276d5a3f0.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1485470/log.zip)

**Comment by benderscruffy** [comment]
still happens on the latest nightly 
[citra_log.zip](https://github.com/citra-emu/citra/files/2705903/citra_log.zip)

**Comment by benderscruffy** [comment]
can be closed now
goes ingame no problems so far
