### ISSUE TITLE
Ocarina of Time 3D - Notes continue playing after learning songs

### ISSUE THREAD

**Issue by Schplee** [citra-emu/citra#2242]
Citra | HEAD-ae8ff84

[Audio Issue](https://www.youtube.com/watch?v=l3Ru__ERdh0)

I know sound emulation is incomplete, but while playing Ocarina of Time, I notice a bizarre thing with the audio. Whenever you learn a new song and the person teaching you it plays, once they hit a place where the song is supposed to pause, the note they last played plays over and over again until the pause finishes and then they continue on with the song, and then it happens again when they finish the song. 

If you couldn't follow that shoddy explanation, the video I uploaded should demonstrate the issue.

**Comment by TTFH** [comment]
That's not a bug, that happend too in a real 3DS, in a Nintendo 64 and in Project64.
And also in Majora's Mask

**Comment by Schplee** [comment]
That's not true. If you were to watch the video, you'd understand. On the N64, when you learn a new song, and during the skull kid mini-game, the notes are pure and consistent, rather than a single note playing repeatedly.

**Comment by yuriks** [comment]
Video captured from a 3DS of that section: https://youtu.be/og0m-22oWxw?t=7m9s

The sound does keep playing until the end. The only thing wrong in Citra is that the sample loop point seem to be incorrect, causing the note's attack to play twice.

**Comment by Schplee** [comment]
I know, it's supposed to keep playing until the end. I guess I didn't explain that well enough, I don't know how to describe audio through text very well, I guess. 

> The only thing wrong in Citra is that the sample loop point seem to be incorrect, causing the note's attack to play twice.

That description probably nails what I was trying to report on the head.

**Comment by MerryMage** [comment]
Likely due to unimplemented looped buffers, which would normally allow for nonzero loop start positions.

**Comment by MerryMage** [comment]
Does this still happen?

**Comment by Schplee** [comment]
@MerryMage Checked against `e1bb198`. This is fixed.
