### ISSUE TITLE
Clean-up CMakeLists.txt and add clang-cl support

### ISSUE THREAD

**Issue by freiro** [citra-emu/citra#2244]
~~To properly support clang-cl CMakeLists.txt needs to be a bit modified~~ (fixed), we could take this opportunity to rework CMake files a bit and clean them up:

- [x]  Add support to clang-cl
- [ ]  Use LIST(APPEND) to concatanate variables instead of SET()
- [x]  Remove dualities and move WINVER definition to cmake #2228
- [ ]  Decide whether -DNOMINMAX should be used also when compiling with MinGW
- [x] CMake does not copy SDL2.dll in the correct folder if the target is only citra-qt #2303 
- [ ] Use CMake copy tool (platform independent) to properly copy dlls etc. https://github.com/citra-emu/citra/pull/2303#discussion_r91857562

And maybe use a convention for IF ELSE ENDIF, sometimes they are lowercase and sometimes uppercase.

**Comment by lioncash** [comment]
Note that clang-cl can be checked for with

```cmake
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang" AND "${CMAKE_CXX_SIMULATE_ID}" STREQUAL "MSVC")
    # Handling here 
endif()
```

**Comment by freiro** [comment]
@lioncash thanks, I actually have a working version for clang,  https://github.com/freiro/dynarmic/pull/1 and https://github.com/citra-emu/citra/pull/2245/files

**Comment by lioncash** [comment]
@freiro You should use the above if-statement over checking against platform-specific variables like `WIN32`

**Comment by freiro** [comment]
@lioncash you mean in general or just with the clang-cl PR?
If you mean in general, this is how CMakeFiles.txt currently works and we can add this change to the list.

**Comment by freiro** [comment]
I will close this pseudo-issue for now, maybe we can get back at this later.
