### ISSUE TITLE
smm for 3ds issue

### ISSUE THREAD

**Issue by pikachu15** [citra-emu/citra#2250]
well say you dont have any mii pleaseback to 3ds home menu 
``

**Comment by pikachu15** [comment]
i have screnshots but i dont know how to add screnshots to github

**Comment by mailwl** [comment]
you have to run MiiMaker in Citra and create your Mii first

**Comment by pikachu15** [comment]
how to do that?

**Comment by mailwl** [comment]
https://discuss.citra-emu.org/d/341-how-to-do-mii-maker-dump-from-3ds

there is more easy way, just dump app from nand from 3ds file browser, but now i don't remember  exactly name of this homebrew

**Comment by pikachu15** [comment]
i dont have 3ds

**Comment by mailwl** [comment]
piracy is illegal here...
issue will be closed

**Comment by pikachu15** [comment]
can you send your mand for me ?

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid
