### ISSUE TITLE
uniform block size do not match (pokemon moon)

### ISSUE THREAD

**Issue by rasendr** [citra-emu/citra#2256]
when im running pokemon moon it says uniform block size do not match. i have tried a lot of builds and still the same. anyone can help me?

**Comment by mailwl** [comment]
Amm... What a problem? Uniform block size do not match, and what? The game is unplayable?

**Comment by jroweboy** [comment]
@rasendr This is not a help forum, this is an issue tracker for developers. Please use the forums for that. Additionally, I see that you have already posted about this on the forums, so just wait for a response there instead. If we find an actual bug behind this, then we can move the conversation back here.

Closed as invalid.

**Comment by rasendr** [comment]
@mailwl yes i cant start the game

**Comment by mailwl** [comment]
Please lock this issue.
@rasendr, citra-emu
