### ISSUE TITLE
Resident Evil Revelations / Resident Evil The Mercenaries 3D - Unknown alpha combiner operation 7

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#2258]
Tested on https://github.com/citra-emu/citra/commit/018191c1f01980d6a642b0ef1bd0a4cd636c0178

Both of these games have the same "Unknown alpha combiner operation: 7" in the log.I'm sure that Super Street Fighter IV: 3D Edition has the same problem too - look at this [video](https://www.youtube.com/watch?v=Oo8kkBcFIQc)

`Render.OpenGL <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:GLShader::AppendAlphaCombiner:272: Unknown alpha combiner operation: 7`

**Resident Evil - Revelations**

scaled resolution on:
![resi 1](https://cloud.githubusercontent.com/assets/11453507/20859664/3486ff5c-b965-11e6-9a22-ae4135a327be.PNG)

scaled resolution off:
![resi 2](https://cloud.githubusercontent.com/assets/11453507/20859667/3e4e2ca4-b965-11e6-8674-e1f6b50fe9de.PNG)

sw:
![resi 3](https://cloud.githubusercontent.com/assets/11453507/20859777/37a21a10-b969-11e6-88e3-07d693844b6d.PNG)

**Resident Evil The Mercenaries 3D**

scaled resolution on:
![res mer 1](https://cloud.githubusercontent.com/assets/11453507/20859682/7c3e8216-b965-11e6-809d-cceca4eeb170.PNG)

scaled resolution off:
![res mer 2](https://cloud.githubusercontent.com/assets/11453507/20859683/8755922a-b965-11e6-8703-1a78db45d25e.PNG)

sw:
![res mer 3](https://cloud.githubusercontent.com/assets/11453507/20859779/499f5cc8-b969-11e6-9438-69f3b9e100eb.PNG)

**Comment by mailwl** [comment]
bleeding edge build fix it?

**Comment by JohnGodgames** [comment]
Nope...there is no implementation for effects as film grain propably.

**Comment by JayFoxRox** [comment]
Yes, apparently I left this out in #1655 due to insufficient testing and lack of hardware test cases.

**Comment by wwylele** [comment]
fixed by #2671
