### ISSUE TITLE
Pokémon X/Y ‒ Absent of lighting on model in software renderer

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2263]
*Hardware renderer*/*Software renderer* on left & right screenshot respectively.
![Both renderers](https://cloud.githubusercontent.com/assets/18496868/20865849/e27e06ee-ba57-11e6-82f7-e6f70cb8d8ef.png)

Notice there is one inconsistent diagonal line spacing (could be missing a diagonal line) on the bottom of the 3DS screen using the software renderer mode.

Log:
`Render.OpenGL <Error> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:483: API ERROR 1282: GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.`

Tested this on commit 4f0f88b

**OS:** _Windows 10 build 14393.447 (codename Redstone 1)_
**GPU:** _nVidia GT 610 2GB DDR3 (Asus)_
**Driver:** _Version 375.95_
**OpenGL:** _Version 4.5_

**Comment by Subv** [comment]
Please test with #2766

**Comment by Dragios** [comment]
Yup it's fixed with your PR. The missing diagonal line issue on bottom screen only show sometimes in *software renderer* when toggling between *software*/*hardware renderer*.

**Comment by Dragios** [comment]
Fixed by #2822
