### ISSUE TITLE
Fantasy Life crash at female character creation

### ISSUE THREAD

**Issue by emmauss** [citra-emu/citra#2276]
This crash occurs when creating a female character, before you choose a life. It is right after you type in the name of your character.
System Specs;
Intel Core i5 4210u @ 2.4GHz
Nvidia Geforce 840m
6GB DDR3 ram

Using master build HEAD-c4e4fa5 , slightly dirty

Call stack http://pastebin.com/vaGTUvzM

Screens
![screenshot 71](https://cloud.githubusercontent.com/assets/5307160/20958296/d534d692-bc4c-11e6-8069-5376a7fc082c.png)
![screenshot 72](https://cloud.githubusercontent.com/assets/5307160/20958295/d53482b4-bc4c-11e6-9b6d-42adb50ab3eb.png)
http://imgur.com/a/FsYVO

**Comment by JayFoxRox** [comment]
Does this happen with / without CPU-JIT?

When this error popped up on the forum recently I've looked up the blend-equation table on 3dbrew.
There is no value for mode 14 (0b1110), worse yet, there isn't a mode for 6 (0b110) either and 2 bits (0b10 = mode 2) isn't able to represent mode 4. So it's probably not an issue with the field size.

This raises the questions wether we mess up something on the CPU, command transfers, command parsing (e.g. offset wrong too) or if the GPU has another blend-equation we did not consider yet and how it handles invalid values (if this is just a bug in the game?).

**Comment by emmauss** [comment]
It happens with or without CPU JIT.

**Comment by mailwl** [comment]
looks like GPU regression, because that very old branch works from https://github.com/citra-emu/citra/issues/1607

**Comment by JayFoxRox** [comment]
Are you sure? If anything, this sounds more like a CPU regression unless we modified command parsing or something similar. Can you bisect the issue (first verifying you reproduce it correctly on a recent master)?

**Comment by mailwl** [comment]
@JayFoxRox, hm... your right, if i uncheck all CPU/GPU options, i can go ingame, but it really slow, because if HW.Memory error, even if disable it in logs.
default master don't get ingame because of null pointer in
https://github.com/citra-emu/citra/blob/master/src/video_core/rasterizer.cpp#L579

**Comment by mailwl** [comment]
it' funny, but boy character may be created without errors... What a sexism

**Comment by RavenHome1** [comment]
@mailwl thank god there is no apache attack helicopter option.

**Comment by skylynx442** [comment]
Since the behavior of the unknown blend modes is known to be the same as add, could you remove the UNREACHABLE from the code?

https://github.com/citra-emu/citra/blob/6c63bb11d9acc909efcc83281cbabdffd9e172e8/src/video_core/renderer_opengl/pica_to_gl.h#L107

**Comment by wwylele** [comment]
I once looked in the the command list this game submits to GPU and other related stuff, and couldn't find any clue indicating this is a bug somewhere else. So I am fine with accepting it as games bug and implement BlendEquation as tested behaviour (removing the UNREACHABLE)
