### ISSUE TITLE
i need help error hastoped working citra-qt.exe in citra emu version v81

### ISSUE THREAD

**Issue by asunavn** [citra-emu/citra#2288]
I used to play Fire Emblem awakening in a match, but I get the message about working citra-qt.exe hastoped fault so please help me fix it

**Comment by freiro** [comment]
Please use http://discuss.citra-emu.org/

**Comment by MerryMage** [comment]
This issue tracker is not a help forum. Please post to [the Citra forums](https://discuss.citra-emu.org/) in the future.
