### ISSUE TITLE
configure_input: Setting strings should not be translated

### ISSUE THREAD

**Issue by MerryMage** [citra-emu/citra#2289]
Poor design in `configure_input`.

[`ConfigureInput::getKeyName`](https://github.com/citra-emu/citra/blob/84fbbe26297652d994d203bde543ec252c2d801a/src/citra_qt/configure_input.cpp#L108-L121) returns translated strings. This is not an issue in itself, but these English versions of these strings are subsequently used retrieve the appropriate `Qt::Key` value with [`ConfigureInput::getKeyValue`](https://github.com/citra-emu/citra/blob/84fbbe26297652d994d203bde543ec252c2d801a/src/citra_qt/configure_input.cpp#L71). This is not a round-trip conversion in the general case.

**Comment by makotech222** [comment]
Does this occur in my inputcore PR? I don't remember what I do in it, lol. If so, i'll try and fix in there.
