### ISSUE TITLE
Citra Error/Crash at the same time 

### ISSUE THREAD

**Issue by alansussi** [citra-emu/citra#2293]
Latest Citra Build (NOT THE FAST OR THE ONE THAT ¨DOESNt¨ CRASH

[   7.704383] HW.GPU <Critical> core\hw\gpu.cpp:MemoryFill:99: invalid start address 0x00000000
[   7.706017] HW.GPU <Critical> core\hw\gpu.cpp:MemoryFill:99: invalid start address 0x00000000
[ 242.926091] Service.ERR <Critical> core\hle\service\err_f.cpp:ThrowFatalError:173: Fatal error
[ 242.927456] Service.ERR <Critical> core\hle\service\err_f.cpp:ThrowFatalError:176: Fatal error type: Generic
[ 242.928479] Service.ERR <Critical> core\hle\service\err_f.cpp:LogGenericInfo:146: PID: 0x0000000A
[ 242.928843] Service.ERR <Critical> core\hle\service\err_f.cpp:LogGenericInfo:148: REV: 0x00000000_0x0000F21D
[ 242.928927] Service.ERR <Critical> core\hle\service\err_f.cpp:LogGenericInfo:150: TID: 0x00000000_0x00000000
[ 242.929007] Service.ERR <Critical> core\hle\service\err_f.cpp:LogGenericInfo:152: AID: 0x00000000_0x00000000
[ 242.929088] Service.ERR <Critical> core\hle\service\err_f.cpp:LogGenericInfo:153: ADR: 0x00172ED8
[ 242.929167] Service.ERR <Critical> core\hle\service\err_f.cpp:LogGenericInfo:155: RSL: 0xD90103FA
[ 242.929246] Service.ERR <Critical> core\hle\service\err_f.cpp:LogGenericInfo:156:   Level: 27
[ 242.929326] Service.ERR <Critical> core\hle\service\err_f.cpp:LogGenericInfo:157:   Summary: 8
[ 242.929419] Service.ERR <Critical> core\hle\service\err_f.cpp:LogGenericInfo:158:   Module: 64
[ 242.929512] Service.ERR <Critical> core\hle\service\err_f.cpp:LogGenericInfo:159:   Desc: 1018
[ 242.929692] Service.ERR <Critical> core\hle\service\err_f.cpp:ThrowFatalError:186: Datetime: 2016/12/08

PC Specs Ok.
Thanks!

**Comment by RavenHome1** [comment]
please use the forums for support

https://discuss.citra-emu.org/

**Comment by JayFoxRox** [comment]
Yeah this has zero information.

---

This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files. There is only support for official versions downloaded from our website. Limited support for Bleeding-Edge while nightly builds are down.

---

Closed as invalid
