### ISSUE TITLE
Megami Meguri: ShaderJIT+XBayk, regression

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#2323]
Before #2309 works. If you need some additional info, i try to give

![megami](https://cloud.githubusercontent.com/assets/629437/21232717/b7f539a2-c2fd-11e6-83a1-22361a108040.png)

**Comment by JayFoxRox** [comment]
Probably due to LOOPCOUNT_REG being R12d instead of simply R12 (how did this work in the old jit?)

**Comment by yuriks** [comment]
#2325 should fix this

**Comment by mailwl** [comment]
yes, fixed

**Comment by mailwl** [comment]
also fix again our old friends: Cut The Rope, Exctetra... (who used loops)
