### ISSUE TITLE
Apps that try to close themselves causes the emulator to crash

### ISSUE THREAD

**Issue by deadair3210** [citra-emu/citra#2326]
version = HEAD-b3c53b6
Any application that calles 'PrepareToCloseApplication' or 'CloseApplication' will cause the emulator to crash, the last thing in the log is 'Unreachable Code'

**Comment by mailwl** [comment]
link here related #1663

**Comment by deadair3210** [comment]
Didn't know it already existed, sorry.
The only thing I noticed was that the result was different, will add that info to the other issue

**Comment by mailwl** [comment]
no, it different issues, one from user applications, another from system/homebrew

**Comment by deadair3210** [comment]
So the issue still stands?
