### ISSUE TITLE
Cave Story 3D Issues!

### ISSUE THREAD

**Issue by gdfsgdfg** [citra-emu/citra#2333]
Sorry don't know where else to post, anyway.

Sound issue, that apparently was not present in some probably modified? older versions of Citra ex. https://www.youtube.com/watch?v=U6Qcu-Am85w only music seems to play for me everything else is silent in some very rare cases a sound effect may play but its barely audible, I've been waiting patiently for this to be fixed but I get a sad face every time.

Scaled Resolution makes the text look funky but its very minor - http://i.imgur.com/aw5pVmh.png

Using Citra Edge build 90

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid
