### ISSUE TITLE
Fantasy Life - Unable to boot

### ISSUE THREAD

**Issue by emmauss** [citra-emu/citra#2336]
Fantasy life shows black screen when booting. It no longer goes to menu. This is caused by #2260 , which was merged recently.
log : http://pastebin.com/EbuBFBFA
log before merge (at ec9130d ) : http://pastebin.com/2Jisu2fY
i also tested it as a single merge of @2260 on master, so i am sure it was caused by the scheduling branch.

**Comment by Subv** [comment]
Could you please test #2393 ?

**Comment by emmauss** [comment]
Still does not work. Black screen.

**Comment by Subv** [comment]
I've updated the PR, could you please try again?

**Comment by emmauss** [comment]
no, still black screen.

**Comment by Subv** [comment]
Please try again with the latest master? :)

**Comment by emmauss** [comment]
still not working.

**Comment by Subv** [comment]
This game's main thread spinlocks until two values are cleared. Presumably these values are cleared by the SysCore thread that the game spawns at startup.

**Comment by emmauss** [comment]
tested working on latest master.

**Comment by Subv** [comment]
That's... weird, could you please help pinpoint the commit that fixed it?

**Comment by emmauss** [comment]
from the nightly builds, it is https://github.com/citra-emu/citra-nightly/commit/78f2571/ . it was merged from master after all your threading commits,other than sleepthread, were merged into master.

**Comment by Subv** [comment]
thanks!
