### ISSUE TITLE
omega ruby, black line around dialogue box

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#2340]
possibly a duplicate of the already know black lines issue but decided to report it just in case.

simply a black line appears near the dialogue box in omega ruby when upscale resolution is active

tested on bleeding 92

with upscaling

![capture3](https://cloud.githubusercontent.com/assets/12820322/21267357/99ea5784-c3b2-11e6-8db8-04139982c330.PNG)

![capture](https://cloud.githubusercontent.com/assets/12820322/21267367/a56578aa-c3b2-11e6-9a3c-3124516a7386.PNG)

without upscaling

![capture4](https://cloud.githubusercontent.com/assets/12820322/21267381/b4970082-c3b2-11e6-9b10-d333fee1edef.PNG)

![capture2](https://cloud.githubusercontent.com/assets/12820322/21267389/bcca7dc4-c3b2-11e6-91df-7edb6d5b3d5b.PNG)

also a small note this appears only on a specific dialogue box, specifically the cloud shaped one, normal rectangle/square ones don't seem to have this issue

with scaled

![capture8](https://cloud.githubusercontent.com/assets/12820322/21267481/32dca294-c3b3-11e6-90dd-8f9d4dc88092.PNG)

without scaled

![capture9](https://cloud.githubusercontent.com/assets/12820322/21267485/39081b4e-c3b3-11e6-8fdd-be212eeab8be.PNG)

**Comment by hyperdrive3** [comment]
I encountered a similar issue using the latest master(_master-acc83a1, built 17/12/2016_), difference is that it's a different UI element(Scroll bar UI elements). I haven't checked whether the examples above occur on my build, but I'm willing to bet it does.

Here's a image album of the issue in 2 different circumstances: [Upscaled Enabled vs Upscaled Disabled](http://imgur.com/a/b7Yy4)

Doubt it's a regression of any merge as of late.

**Comment by yuriks** [comment]
Looks like a sub-pixel misalignment issue. I don't think this is something we can fix.
