### ISSUE TITLE
Pokemon Sun - Jittery effect on top screen

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#2341]
This issue started with `0e03257` (#2321) and only affects the top screen ([log](https://paste.ee/p/XoMlu)).
https://streamable.com/i1b4q

Compared to `ec9130d` ([log](https://paste.ee/p/SI8Ye)).
https://streamable.com/nsq78

**Comment by Subv** [comment]
Is this with Scaled Resolution enabled? Could you please try disabling it?

**Comment by Leo626** [comment]
@Subv Yes this is with Scaled Resolution enabled. This doesn't happen with it disabled.

**Comment by Leo626** [comment]
Closing as this issue no longer occurs with #2347 now merged.
