### ISSUE TITLE
dragon quest 7 scaled resoultion problem and pokemon sun scaled resloution too

### ISSUE THREAD

**Issue by asbel123** [citra-emu/citra#2342]
i put scaled resoultion on dragon quest 7 doesnt go high deatil still low deatil and i am using latest build from ur  update night build everyday can u fix it and dragon quest 7 is playable no crashes i am up to volcano area  but it  too slow everything is perfect i see no issues i am using new laptop with desktop cpu is i7 6700k and nvdia 1080 single.

i just finsh one game on ur emulator is braverly second its perfect on this laptop with this high resoultion perfect no problem i am happy ur work now u fixed pokemon sun but fix the resloution probblem on scaled   beacuse ur graphics look like iphone graphcis final fantasy 4 high res.

**Comment by bunnei** [comment]
This isn't a support forum - please see the [citra forums](discuss.citra-emu.org).
