### ISSUE TITLE
Just not know how to install

### ISSUE THREAD

**Issue by Siriox** [citra-emu/citra#2349]
Hi, I'm a not expert about code. I'm using elementary OS Loki. Everything was fine until I reach this step of the installation:
Compile
cd citra
mkdir build
cd build
export CC=gcc-5
export CXX=g++-5
~/cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DCITRA_FORCE_QT4=ON
make

Until the export codes was fine, but when I try «~/cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DCITRA_FORCE_QT4=ON» there is a problem, the Terminal shows a message saying that the directory or the file not exist.

Can you help? May your assuming something I don't know?

**Comment by hyperdrive3** [comment]
Hi,

This is place is for developers to track issues with Citra development. If you need support check the [discussion forum](https://citra-emu.org/), there's a discord too which should be quicker for general questions like this.
