### ISSUE TITLE
Combat of Giants: Dinosaurs 3D - Hangs on black screen with CPU JIT

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra#2358]
This is a regression (or revealing bug) caused by https://github.com/citra-emu/citra/pull/2260 (Thread scheduling / cda7210fade53a96fcba5fe5cd6dfd7b604f8277 ).

The game hangs on a black screen instead of showing the UBISOFT logo on startup.

The game continues to work fine with the CPU Interpreter. Only the CPU JIT is affected.
Any idea if this is related to scheduling ( @Subv ) or JIT ( @MerryMage ) ?

---

Test results to find regression:

* 3a1eaf2efc4e5cb3358ab7451182711dfbaa061b (master) + revert cda7210fade53a96fcba5fe5cd6dfd7b604f8277 = works
* 3a1eaf2efc4e5cb3358ab7451182711dfbaa061b (master) = broken
* d25a37966d705c5b2e672d0c146b09d1efb893f3 = broken
* cda7210fade53a96fcba5fe5cd6dfd7b604f8277 = broken
* a89471621b3b156300700f29ebed601da9b582a5 = works
* bde54333dff178c8c2d7704a91df23a69a55a1cc = works

**Comment by Subv** [comment]
Could you please test #2393 ?

**Comment by JayFoxRox** [comment]
Fixed by #2343 (aa47af7fb6efd0bda54cca2373ed978e538f6d61) or one of its fixups (56e4066f4f51fe944dcbb2f6cbff2cbe823915ed or 6409b1d).
It works on current master but when reverting those 3 commits it will break again.
