### ISSUE TITLE
Hi?

### ISSUE THREAD

**Issue by fati18** [citra-emu/citra#2359]
Hi I have a question will the internet connection and the homebrew / home menu and the services of the 3ds on the emulator function?
and For me the emulator does not work I have a pc with an Intel (R) Core (TM) 2 Duo CPU E8500 @ 3.16 GHz 3.17 GHz processor

**Comment by MerryMage** [comment]
This issue tracker is not a help forum. Please post to [the Citra forums](https://discuss.citra-emu.org/) in the future.

**Comment by JayFoxRox** [comment]
Just to avoid useless forum threads: no internet support yet. None planned either (at least not how you want it)

Use your 3DS if you want to play online / use online functionality. Also homebrew is also hit-and-miss. Some works, some does not.
