### ISSUE TITLE
Severe performance regression encountered on a few games

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2371]
Performance regression due to PR #2343. Some games are less likely affected but a few are hit severely.
Since no one has reported this issue during *Bleeding Edge* testing, I assumed that it only affects older generation processors.
Left & right image is tested on build commit 17d7402 & aa47af7 respectively

There are other games with varying performance within a certain degree.
I used this 3 games as the example.

Nano Assault is least affected
![Nano Assault](https://cloud.githubusercontent.com/assets/18496868/21465980/8177a6b6-c9f2-11e6-9efb-e76e59d9ab12.png)

Performance hit is moderately affected but at least it is still playable
![Pokémon Mystery Dungeon – Gates to Infinity](https://cloud.githubusercontent.com/assets/18496868/21465981/82d1e788-c9f2-11e6-97e4-19c871475d6e.png)

Performance hit is severely affected for this particular game making it not playable at all
![Pokémon Super Mystery Dungeon](https://cloud.githubusercontent.com/assets/18496868/21465982/83e3c948-c9f2-11e6-9552-d16df23709ea.png)
With the log filter set to Info level the game slow down until becoming like a slide show. <1 FPS

**OS:** _Windows 10 build 14393.576 (codename Redstone 1)_
**Processor:** _Intel(R) Core(TM)2 Duo CPU E7500  @ 2.93GHz, 2926 Mhz, 2 Core(s), 2 Logical Processor(s) [Overclocked to 3.7 GHz]_
**GPU:** _nVidia GT 610 2GB DDR3 (Asus)_
**Driver:** _Version 376.33_
**OpenGL:** _Version 4.5_

**Comment by wwylele** [comment]
#2343 has several commits in it. Could you please bisect the regression to one commit?

**Comment by Dragios** [comment]
I will try. That will take a lot of time

**Comment by wwylele** [comment]
@Dragios I didn't record the FPS these days on my side, nor paid attention to the speed change, so I can't tell...

**Comment by Dragios** [comment]
I have successfully bisected the commit that causes the regression.
It was commit 4fc8b8229ed1d9ea9d20faee7059c898265db6cf

**Comment by wwylele** [comment]
@Dragios does #2372 fix it?

**Comment by Dragios** [comment]
It is. Thanks for the quick fix @wwylele

**Comment by Dragios** [comment]
Yes it does, Thanks for the quick fix @wwylele

**Comment by bunnei** [comment]
#2372 just adds back a speed hack that was intentionally removed (see my explanation in that PR). This isn't a bug any more than "the emulator is slow at times"... I'm not sure we gain much by having hacks like this, it will probably only introduce other issues that will be hard to identify down the road. This particular hack messed with timing for pretty arbitrary/unknown reasons.
