### ISSUE TITLE
pokemon sun/moon weird light bug when exiting pokemon refresh

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#2375]
related to scaled res, basically when exiting pokemon refresh a weird colored lines will appear , disabling scaled res and re enabling it removes the lines.

![capture](https://cloud.githubusercontent.com/assets/12820322/21468605/5eee84bc-ca23-11e6-95bb-50ca54bef2ac.PNG)

**Comment by hcorion** [comment]
I've encountered this problem as well, entering a Pokemon battle or restarting the game fixes it.

**Comment by rganapathykarthikeyan** [comment]
For me the my character and their pokemons are black in colour plz hrlp

**Comment by wwylele** [comment]
Fixed by #3281 as reported so closing. Feel free to reopen if it is not the case.
