### ISSUE TITLE
externals/Dynarmic fails to compile on Win10 x64

### ISSUE THREAD

**Issue by Ancano** [citra-emu/citra#2377]
When attempting to build all solutions on Win10 x64 in Visual Studio 2015, all projects compile except for externals\dynarmic. 
VS spits out the following error: 
```
C2220 - warning treated as error - no 'object' file generated (compiling source file C:\Users\larry\citra\externals\dynarmic\src\ir_opt\verification_pass.cpp)
```
This error occurs for every .cpp file in the dynarmic folder, and thus, the dynarmic.lib file cannot be built.

I followed the compilation guide to a tee and still got this error.

**Comment by MerryMage** [comment]
Could you please provide your complete compiler output.

**Comment by Ancano** [comment]
[output.txt](https://github.com/citra-emu/citra/files/674649/output.txt)
Sure thing.

**Comment by MerryMage** [comment]
For my records, would it be possible for you to go to Help → About Microsoft Visual Studio and tell me the exact version you're using? It will be under the line "Microsoft Visual Studio Community 2015" and start with "Version 14.x.xxxx.xxxx Update x".

====

Temporary fix for you: Go to `C:\Users\larry\citra\externals\dynarmic\CMakeLists.txt` and remove the line with `/WX` on it.

I'll think about how to fix this properly later.

**Comment by Ancano** [comment]
Here's the exact version:
Version 14.0.23107.0 D14REL

And yes, I can confirm that removing /WX has fixed the issue and everything has compiled.

**Comment by MerryMage** [comment]
MerryMage/dynarmic#77
