### ISSUE TITLE
After playing for a bit, Citra crashes

### ISSUE THREAD

**Issue by PumpSkel** [citra-emu/citra#2378]
Any way to fix this? The game is Pokémon Sun, I play for some minutes and Citra stops working, and i hate to go to the folder and stuff to enter Citra again and enter the game and save everytime.

**Comment by wwylele** [comment]
This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://discuss.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build, or
 - use pirated copies of the games, 3DS BIOS files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid
