### ISSUE TITLE
Compilation fails on debian jessie comit 14f8065843bf865cbd0f2f34eabf54c37e52df81

### ISSUE THREAD

**Issue by c-h-u-c-k** [citra-emu/citra#2380]
-> % make                     
Scanning dependencies of target inih
[  1%] Building C object externals/inih/CMakeFiles/inih.dir/inih/ini.c.o
[  1%] Building CXX object externals/inih/CMakeFiles/inih.dir/inih/cpp/INIReader.cpp.o
[  1%] Linking CXX static library libinih.a  
[  1%] Built target inih                                                       
Scanning dependencies of target fmt                                             
[  2%] Building CXX object externals/dynarmic/externals/fmt/fmt/CMakeFiles/fmt.dir/posix.cc.o
[  2%] Building CXX object externals/dynarmic/externals/fmt/fmt/CMakeFiles/fmt.dir/format.cc.o
[  2%] Building CXX object externals/dynarmic/externals/fmt/fmt/CMakeFiles/fmt.dir/ostream.cc.o
[  2%] Building CXX object externals/dynarmic/externals/fmt/fmt/CMakeFiles/fmt.dir/printf.cc.o
[  3%] Linking CXX static library libfmt.a                               
[  3%] Built target fmt                     
Scanning dependencies of target dynarmic
[  3%] Building CXX object externals/dynarmic/src/CMakeFiles/dynarmic.dir/common/memory_pool.cpp.o
[  3%] Building CXX object externals/dynarmic/src/CMakeFiles/dynarmic.dir/frontend/arm/types.cpp.o
In file included from /usr/local/src/citra/externals/dynarmic/src/./common/bit_util.h:13:0,
                 from /usr/local/src/citra/externals/dynarmic/src/frontend/arm/types.cpp:10:
/usr/local/src/citra/externals/dynarmic/src/./common/bit_util.h: In function ‘constexpr bool Dynarmic::Common::Bit(size_t, T)’:
/usr/local/src/citra/externals/dynarmic/src/./common/assert.h:33:20: error: compound-statement in constexpr function [-Wpedantic]
     do if (!(_a_)) { assert_noinline_call([&] { \
                    ^
/usr/local/src/citra/externals/dynarmic/src/./common/bit_util.h:54:5: note: in expansion of macro ‘ASSERT_MSG’
     ASSERT_MSG(bit_position < BitSize<T>(), "bit_position must be smaller thansize of T");
     ^
compilation terminated due to -Wfatal-errors.
externals/dynarmic/src/CMakeFiles/dynarmic.dir/build.make:86: recipe for target'externals/dynarmic/src/CMakeFiles/dynarmic.dir/frontend/arm/types.cpp.o' fail$
d
make[2]: *** [externals/dynarmic/src/CMakeFiles/dynarmic.dir/frontend/arm/types.cpp.o] Error 1
CMakeFiles/Makefile2:270: recipe for target 'externals/dynarmic/src/CMakeFiles/dynarmic.dir/all' failed
make[1]: *** [externals/dynarmic/src/CMakeFiles/dynarmic.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wwylele** [comment]
This looks like an issue in the submodule [dynarmic](https://github.com/MerryMage/dynarmic). Please open the issue there.
