### ISSUE TITLE
Pokemon Alpha Sapphire Route 101 crash

### ISSUE THREAD

**Issue by SwooshyCueb** [citra-emu/citra#2381]
With shader JIT enabled, citra crashes (`SIGSEGV`) upon entering route 101 for the first time (when the cutscene before getting your first pokemon plays), just after the top screen fades to black. Turning off shader JIT (even just long enough to play the cutscene) avoids the crash. Tested with commit `2f746e9` on Linux, compiled with `-O3 -march=native`

[catchsegv output](https://paste.weasyldev.com/show/AGcWvRhYGfeB69QRuCC8/). Citra's stdout doesn't seem to contain anything relevant as far as I can tell.

**Comment by RavenHome1** [comment]
i tested using latest bleeding on omega ruby and the cutscence played out fine and managed to get my starter and go into a battle with a wild pokemon.

using windows 7 on latest bleeding, this could be an issue on linux build perhaps or specifically for alpha sapphire (don't own that game so i can't test it out)

**Comment by wwylele** [comment]
@SwooshyCueb @RavenHome1 Could you please provide the CPU information? The different behaviour can be caused by different JIT fallback path

**Comment by JayFoxRox** [comment]
This is due to not persisting ESI and EDI. I've fixed it locally and will send a PR once we have refactored the shader stuff.

**Comment by RavenHome1** [comment]
@wwylele 

![capture](https://cloud.githubusercontent.com/assets/12820322/21563733/96f54878-ce8d-11e6-8d9f-d104e040c091.PNG)

**Comment by SwooshyCueb** [comment]
@wwylele I've got an i7-4720HQ
