### ISSUE TITLE
Severe Kernel Rescheduling stalling on Super Smash Bros: Smash Run

### ISSUE THREAD

**Issue by FernandoS27** [citra-emu/citra#2383]
I've been running some tests to measure different performance bottlenecks on different games. This particular game has scheduling issues as you can see from the images:
![issue1](https://cloud.githubusercontent.com/assets/1731197/21557482/b8c57eb6-cdfa-11e6-9486-645203e16984.jpg)

With CPU Jit Off:
![issue2](https://cloud.githubusercontent.com/assets/1731197/21557486/ce1af232-cdfa-11e6-874c-4df652c1d788.jpg)

how to reproduce the problem?
Enter super smash, go into smash run, you'll notice a massive lag all over the place.

tested on:
3f6c82b, 14f8065 and personal branch.

related Pull Requests::
#2260

**Comment by Subv** [comment]
I really want to just close this, we can not know if this is normal for this game.

However, yes, there are a few things that are doing unneeded reschedules in our codebase, and will be fixed soon (TM).

**Comment by FernandoS27** [comment]
Hmn, leave it open until more investigation is done. I do not find a game taking 33.98% of cpu power for rescheduling normal. it could mean some race condition, deadlocking or something.

**Comment by Subv** [comment]
Could you please test #2393 ?
