### ISSUE TITLE
QT - keypress event gets stuck  when emuwindow looses focus.

### ISSUE THREAD

**Issue by emmauss** [citra-emu/citra#2392]
this occurs only in the qt frontend, and has existed for as long as i can remember. when playing any game, while pressing a input key, make the main emulation window loose focus( by pressing ALT, window key, or by causing an external window to gain focus). the input key gets 'stuck'. It behaves as if the key is still being pressed, even when the window has lost focus, and can only be fixed when you press the same input key after you switch to the emuwindow.
Tested it on Windows 10.

**Comment by freiro** [comment]
I also experienced this situation.
