### ISSUE TITLE
Puyo Puyo Chronicle fails to boot and crashes Citra

### ISSUE THREAD

**Issue by Electricstar** [citra-emu/citra#2398]
Self-explanatory; Puyo Puyo Chronicle, a recently released entry in the _Puyo Puyo_ series, will immediately crash Citra when loaded.

The debug window yields

"<Critical> core/memory.cpp:operator():319: Assertion Failed!", followed by:
"Rasterizer resource cache counter overflow!".

This occurs in the most recent build I got via update, version 0.1.116

Edit: added the hash of my build.

Hash: HEAD-b79ad3b

**Comment by mailwl** [comment]
The game want to open itself as archive:
`[   3.898988] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFileDirectly:130: failed to get a handle for archive archive_id=0x2345678A archive_path=[Binary: 007519008c00040001fd800001000000]`

**Comment by wwylele** [comment]
@mailwl @Electricstar Could you please provide a full log?

**Comment by mailwl** [comment]
http://pastebin.com/y1eJ2H5y (sorry, not master, i add logs fo log hwregs only)
same error in game Skylanders - Spyros Adventure

**Comment by mailwl** [comment]
as i can see, the game can't read any file from ROM (maybe it looks for it in update or something...)

**Comment by wwylele** [comment]
Rechecked this log:
`[ 3.898988] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFileDirectly:130: failed to get a handle for archive archive_id=0x2345678A archive_path=[Binary: 007519008c00040001fd800001000000]`

Rearrange the archive path:
`007519008c00040001fd800001000000` -> `0x00197500, 0x0004008C, 0x0000D81F, 0x00000001`

Notice this higher word of title ID:
`0x0004008C` <- note this, this is DLC content according to 3dbrew. It is not the game itself (in which case it should be `0x00040000`)

**Comment by benderscruffy** [comment]
using the latest nightly goes ingame now
can be closed
