### ISSUE TITLE
Games sending threads on Syscore starving.

### ISSUE THREAD

**Issue by FernandoS27** [citra-emu/citra#2411]
This happens due to syscore threads not being implemented. This affects Donkey Kong Country Returns 3D and Fantasy Life.

I published this issue for the record, so it's 'registered'.

As a sidenote: Syscore threads run on Core1 and have a different scheduling based on Round Robin.

**Comment by Subv** [comment]
Related to #2336

**Comment by wwylele** [comment]
> Syscore threads run on Core0 and have a different scheduling based on Round Robin.
Isn't it Core1?

**Comment by Subv** [comment]
Indeed, there was a typo in the issue, I have corrected it.

**Comment by JohnGodgames** [comment]
**Sonic & All-Stars Racing Transformed**

`Kernel.SVC <Warning> core\hle\svc.cpp:SVC::CreateThread:563: Newly created thread is allowed to be run in the SysCore, unimplemented.`

[Trace log](http://pasted.co/6f0da120)

**Comment by benderscruffy** [comment]
this issue can be closed now
Fixed by #4913.
