### ISSUE TITLE
 7cfe3ef Crashing (won't load at all) in macOS Sierra.

### ISSUE THREAD

**Issue by Lord-Kamina** [citra-emu/citra#2417]
I compiled citra yesterday in 10.11 on my MBP 2011 and had it working as nicely as can be expected.
I tried to run it on a Hackintosh (better processor, better GPU and more RAM) to see how it would go and it wouldn't run, I got a segfault. I assumed maybe I needed to compile it with 10.12 as a target so I rebuilt all dependencies from scratch on the Sierra machine, using 10.12 x86_64 as target and eventually got around to compiling Citra, but it will won't run.

Attached is the crash report.

[citra-qt_2017-01-08-142820_Tiamat.crash.txt](https://github.com/citra-emu/citra/files/692315/citra-qt_2017-01-08-142820_Tiamat.crash.txt)

**Comment by wwylele** [comment]
It crashes in the Qt initialization (=not even stepped into citra main code). Could you check if your Qt library is installed correctly? (I am not a macOS user, so sorry if I asked a dumb question)

 Also, is the SDL frontend working?

**Comment by Lord-Kamina** [comment]
It might not be, I modified the portfile (using macports because I like it better than homebrew) to build Qt as dylibs instead of Frameworks, in order to make it more portable; so it COULD be related to that. Although the one I'd built on 10.11 with Frameworks had an identical crash on Sierra so frankly I'm not that sure.

Weird thing, though... the "official" nightly runs on the Sierra hackintosh but not on my actual MBP running 10.11.6

**Comment by Lord-Kamina** [comment]
Well, I recompiled Qt5 and this time it appears to work. Although I'm not actually sure THAT was the issue as I also noticed (and fixed) an old version of SDL2 sitting in my /Library as a framework.

**Comment by mailwl** [comment]
macports in trash, and use homebrew.

btw, why this issue still open?
