### ISSUE TITLE
The Denpa Men: They Came By Wave Incorrect Audio

### ISSUE THREAD

**Issue by Vectrex33** [citra-emu/citra#2426]
Citra Version 84d72fd.

~~The issue occurs with the music that starts playing right as you press New Game on the Title Screen.~~ The issue occurs with most of the games music, an example is provided down below from the music played in the Antenna Tower in-game.
Correct Audio (3DS): https://drive.google.com/open?id=0B1OJjvmvY2MCSEpDN0xuVG1hTzg
Incorrect Audio (Citra): https://drive.google.com/open?id=0B1OJjvmvY2MCeFVVWm53N2N1ZzA

**Comment by jmerdich** [comment]
I downloaded the free demo and got the same result. It seems that this is due to lack of polyphase interpolation.

**Comment by Vectrex33** [comment]
@jmerdich Apparantly the bleeding edge builds do not have looped buffers right now, as I am still receiving the warning in the log about looped buffers. http://i.imgur.com/0haadXI.png

The audio issue persists in the Bleeding Edge Build regardless.

**Comment by Vectrex33** [comment]
I have no idea why this is still open but it's been fixed for a good while now so...
