### ISSUE TITLE
Denpa Ningen RPG FREE freezes on boot.

### ISSUE THREAD

**Issue by Vectrex33** [citra-emu/citra#2427]
Citra version 84d72fd.

Denpa Ningen RPG FREE freezes upon bootup, seemingly due to an unimplemented service.

Log: http://pastebin.com/gdVb561N

**Comment by wwylele** [comment]
>[   8.610498] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenFileDirectly:130: failed to get a handle for archive archive_id=0x2345678A archive_path=[Binary: 02030100db00040000ffffff01000000]

The game tries to open the bad word list but it failed, meaning that you don't have [a full dump of system archives](https://github.com/citra-emu/citra/wiki/Dumping-System-Archives-and-the-Shared-Fonts-from-a-3DS-Console). Close this for now until you place the system archives and update the log if it still freezes

**Comment by Vectrex33** [comment]
Updated the log, game still does not boot with system archives in place.

**Comment by mailwl** [comment]
with #2368 the game a kind of work (need move camera for character).

**Comment by benderscruffy** [comment]
this can be closed or change the description now as it boots but u cant move the camera to follow the character
