### ISSUE TITLE
Face Raiders Freezes on Boot

### ISSUE THREAD

**Issue by LunaDook** [citra-emu/citra#2430]
Tested on version ba271f6.

Log: http://pastebin.com/eZpM0Pkk

**Comment by yuriks** [comment]
Why did you close this?

**Comment by Vectrex33** [comment]
@yuriks http://i.imgur.com/ISsISW0.png

The official website says that issues shouldn't be created for games that do not boot, so... I closed the issue. I'll re-open it if I'm just misunderstanding or what not.

**Comment by FernandoS27** [comment]
Could you get us an screenshot of the log citra outputs?

**Comment by yuriks** [comment]
@FernandoS27 They already posted the log.

@Vectrex33 I'm not sure why that ruele exists nowadays, I think this issue is fine. Do try to post a full log going back to the game boot though.

**Comment by TuxSH** [comment]
Shared sytem ExtSaveData 0xf0000001 : "NAND JPEG/MPO files and phtcache.bin from the camera application are stored here. This also contains UploadData.dat."

This is the archive that was attempted to be open. It's likely not implemented (?)

**Comment by mailwl** [comment]
I suppose this game from firmware?
there is retail game (eShop maybe...) with name "Face Racers Photo Finish"
it works with merged CAM #2368

**Comment by mailwl** [comment]
enought create folder by hand:
`user\nand\data\00000000000000000000000000000000\extdata\00000000\F0000001\user`
not playable without camera

**Comment by tgsm** [comment]
For some reason, you need to run home menu on Citra to get this game to boot

![citra nightly 1063 _ face raiders 10_26_2018 4_00_27 pm](https://user-images.githubusercontent.com/11739422/47589881-86565180-d938-11e8-9893-0107ff30a549.png)

**Comment by Dragios** [comment]
This can be close. The app no longer freezes on boot and it does not require workaround to launch from Home Menu 1st before opening this game. This is directly opening the game.
![Face Raiders](https://user-images.githubusercontent.com/18496868/80166022-78f25400-860f-11ea-8a9f-beab6b0be13e.png)

**Comment by milesthecreator** [comment]
How do I get this game working? It crashes after the "Preparing..." screen.
[citra_log.txt](https://github.com/citra-emu/citra/files/4567600/citra_log.txt)
![preparing fr](https://user-images.githubusercontent.com/45196539/80863086-cb281a80-8c8a-11ea-9429-36a9aa1f5b1f.png)
