### ISSUE TITLE
The Denpa Men 2: Beyond the Waves Booting Regression

### ISSUE THREAD

**Issue by Vectrex33** [citra-emu/citra#2431]
Somewhere between commit 84d72fd and 1d088c6, The Denpa Men 2: Beyond The Waves stopped booting.

Log from commit 84d72fd: http://pastebin.com/ymgpZntE
Log from commit 1d088c6: http://pastebin.com/aGxpYuv6

There is no difference between the log from 1d088c6 and ba271f6 other then that 1d088c6's log contains a singular message after the Critical Error: `[   8.431122] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:483: API PERFORMANCE 131218: Program/shader state performance warning: Fragment shader in program 3 is being recompiled based on GL state.`

EDIT: Fixed links and adding that this also occurs on ba271f6.

**Comment by wwylele** [comment]
> [   6.199558] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:153: RSL: 0xD9001BEA

Module: OS (6) | Description: Not authorized (1002) | Summary: Wrong argument (8) | Level: Permanent (27)

There is a commit in between that added this error:https://github.com/citra-emu/citra/commit/1ddff1451140ef58058237a3198d363b96dc238e

So here is my guess: did you dump your game via Braindump? Braindumped game is known to possibly create a thread with wrong priority

**Comment by Vectrex33** [comment]
It seems my original dump was made with braindump, yes. I now have the game booting on ba271f6 with a proper dump. As such, I will close this.
