### ISSUE TITLE
Super Mario 3D Land Title Screen/File Select Menu Regression

### ISSUE THREAD

**Issue by Vectrex33** [citra-emu/citra#2432]
In commit 1d088c6, Super Mario Land will crash after pressing A on the title screen to access the File Select menu. In commit 84d72fd and ba721f6  however, the game proceeds on for a while longer (later crashes when trying to create a save, don't know if this is because of missing Mii support but whatever, unrelated).

Log from 1d088c6: http://pastebin.com/KuE67f1k

EDIT: ~Was just messing around with 84d72fd, it seems a similar crash to the one experienced in 1d088c6 occurs if you select "No" for Streetpass. 1d088c6 and onwards will crash regardless what is chosen though.~ 84d72fd seems spotty in being able to reach the File Select Menu after some extended testing, however I still have not gotten into that menu with commit 1d088c6 onwards at all.

**Comment by Leo626** [comment]
I am unable to reproduce this with ba271f6. Was able to start a new game and complete the first level. I have CPU JIT, Hardware Renderer, Shader JIT, V-Sync and Limit framerate turned on and compiled with msvc.

**Comment by Vectrex33** [comment]
Ok, now here's some spooky action: I turned on V-Sync and ba271f6 suddenly got into the Menu Select just fine... that one time. Now it's doing what it did earlier. Is it possible because I haven't dumped my NAND for use in citra that could be causing these issues?

**Comment by Vectrex33** [comment]
I'm going to close this until I figure out whether it's an issue on my end or Citra's fault.
