### ISSUE TITLE
The Denpa Men 2: Beyond The Waves Incorrect Water Rendering

### ISSUE THREAD

**Issue by Vectrex33** [citra-emu/citra#2433]
~~Tested in Citra Commit 84d72fd (Cannot test on latest nightly (see #2431), however no commits between this one and the latest as of this report seem to do anything to either the HW or SW renderers).~~ Just tested in 16a3f9e. Issue persists.

Citra: http://i.imgur.com/n9ZXfvX.png

3DS: http://i.imgur.com/Cl7rBI9.jpg

Log: http://pastebin.com/gjPkg2Zi

Seems to be something related to shaders.

**Comment by wwylele** [comment]
is this fixed?

**Comment by Vectrex33** [comment]
Yes, yes it is.
