### ISSUE TITLE
Devil Survivor Overclocked black screen on start

### ISSUE THREAD

**Issue by estelle82** [citra-emu/citra#2436]
Can't start the game cuz it has a black screen with music playing at the beginning. Buttons are'nt responding. 
citra-windows-msvc-20170113-ba271f6
citra-windows-msvc-20170110-84d72fd

![-1](https://cloud.githubusercontent.com/assets/25080920/21953964/e5248260-da55-11e6-861b-46cce83348d1.jpg)

**Comment by mailwl** [comment]
just listen sound twice, and game starts

(yes i know, i know, bkack screen it's a bug, textures are generated in memory, but as workaround is enough, and song is good)

**Comment by estelle82** [comment]
Oh ty!

**Comment by benderscruffy** [comment]
still happens in the latest nightly
but now still a black screen but the music just keeps repeating and the game never starts 
[citra_log.zip](https://github.com/citra-emu/citra/files/2722741/citra_log.zip)

**Comment by noyoda** [comment]
nightly 1169 , still happen keep repeating and the game never start

**Comment by vaniljmust** [comment]
seems like every place i have tried this rom at have the same issue with my citra nightly (1236).
intro logo, black screen, intro music only looping, no controllers working except l+r+select+start.
any thoughts if this will ever get fixed or is it forever broken?

**Comment by vitor-k** [comment]
Can you confirm this still happens on latest nightly?

**Comment by benderscruffy** [comment]
yep goes ingame now in the nightly
can be closed

**Comment by Keppl** [comment]
I think the issue is back. Or something very similar happening.

Starting with nightly 1561 (2632b42) black screen is shown, and intro has to go through one or two (1.5?) loops before video starts to play and inputs start to work. I (sparsely)  checked up to 1594 (d88d220_, this behavior seems to be the same from 1561 to 1594. 

Nightly 1560 (565e598) seems to still work as  it starts the video after few seconds into initial audio loop; Though I think audio and video of intro are not quite synchronized, since there is a black screen for ~5-7 seconds before video starts and first ~5-7 of audio are played again at the end of first intro video.

Also for 1560, if main menu times out back to intro, it goes into black screen and the wait time is ~30 seconds before video starts playing and it response to inputs.

**Comment by rlpowell** [comment]
Confirmed that dropping the CPU to 50% seems to fix it.  Weirdly, it seems to *stay* fixed?

**Comment by nickkeane** [comment]
Getting the same issue in libRetro Citra. There doesn't seem to be an option to drop cpu to 50%, but the fix does work in my standalone Citra exe.

**Comment by SentaiBrad** [comment]
Dropping the CPU speed to 45% or 50% just makes the song play at half speed and I did get the original popping to go away by changing the sound engine to SDL2. I just updated  to Citra 2103.

**Comment by ORLOX93** [comment]
> Dropping the CPU speed to 45% or 50% just makes the song play at half speed and I did get the original popping to go away by changing the sound engine to SDL2. I just updated to Citra 2103.

You didn't change the cpu speed, you changed the emulation speed.

**Comment by rlpowell** [comment]
> You didn't change the cpu speed, you changed the emulation speed.

Confirmed, it's definitely not the CPU speed that does it.

This has been a problem for me, actually, because the Android Citra doesn't *have* an emulation speed control.  -_-;

**Comment by SentaiBrad** [comment]
> > Dropping the CPU speed to 45% or 50% just makes the song play at half speed and I did get the original popping to go away by changing the sound engine to SDL2. I just updated to Citra 2103.
> 
> You didn't change the cpu speed, you changed the emulation speed.

Mostly using the same verbiage on the thread to keep track of things. Different versions also labeled it different things too if I recall. But yes, its the emulation speed. Either way, never solved it.

**Comment by vitor-k** [comment]
> > > Dropping the CPU speed to 45% or 50% just makes the song play at half speed and I did get the original popping to go away by changing the sound engine to SDL2. I just updated to Citra 2103.
> > 
> > 
> > You didn't change the cpu speed, you changed the emulation speed.
> 
> Mostly using the same verbiage on the thread to keep track of things. Different versions also labeled it different things too if I recall. But yes, its the emulation speed. Either way, never solved it.

These are two different options. The emulation speed is in General > Emulation, and just changes the speed the game runs at. It used to be on Graphics as "Limit speed percent", but that's the only names it's had, as far as I'm aware.

CPU clock speed is a different (newer) option that has nothing to do with emulation speed. It's on System > Advanced. This is the option that changes game behaviors for multiple games, which should include this one. It's also not available on android, as far as I'm aware.

**Comment by SentaiBrad** [comment]
> > > > Dropping the CPU speed to 45% or 50% just makes the song play at half speed and I did get the original popping to go away by changing the sound engine to SDL2. I just updated to Citra 2103.
> > > 
> > > 
> > > You didn't change the cpu speed, you changed the emulation speed.
> > 
> > 
> > Mostly using the same verbiage on the thread to keep track of things. Different versions also labeled it different things too if I recall. But yes, its the emulation speed. Either way, never solved it.
> 
> These are two different options. The emulation speed is in General > Emulation, and just changes the speed the game runs at. It used to be on Graphics as "Limit speed percent", but that's the only names it's had, as far as I'm aware.
> 
> CPU clock speed is a different (newer) option that has nothing to do with emulation speed. It's on System > Advanced. This is the option that changes game behaviors for multiple games, which should include this one. It's also not available on android, as far as I'm aware.

Double-checked on the latest nightly, changed the CPU Speed to 50%, and the intro played instantly.
