### ISSUE TITLE
Lalaloopsy Carnival of Friends crash Citra with HW Renderer On

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#2437]
in SW mode works. If need additional information, i try to give

![lalo](https://cloud.githubusercontent.com/assets/629437/21955069/f05cbe7c-da73-11e6-968c-5d2bab20fc9e.png)

**Comment by mailwl** [comment]
i replace selected line (UNREACHABLE();) with:
```
                page_type = PageType::RasterizerCachedSpecial;
                break;
```
and game starts work on HW. really weird...

**Comment by benderscruffy** [comment]
using nightly HEAD-a66e458
had no crash so far with HW Renderer on
![lalaloopsy](https://user-images.githubusercontent.com/2696404/34598170-15959748-f226-11e7-8589-c13a46d17fb0.PNG)
this can be closed
