### ISSUE TITLE
Devil Summoner: Soul Hackers warning spam during cutscenes

### ISSUE THREAD

**Issue by Barlowe11** [citra-emu/citra#2438]
Tested Shin Megami Tensei IV, Soul Hackers and Etrian Odyssey Untold 1. During any cutscenes, this games start to spam log with the same message. Played on ba271f6.
Service.Y2R <Warning> core\hle\service\y2r_u.cpp:Service::Y2R::SetTransferEndInterrupt:248: (STUBBED) called

**Comment by mailwl** [comment]
at my sight, Y2R enough implemented for long time, need PR, which remove (STUBBING) and change log to TRACE.

@Barlowe11, you need to add log filter to your config file, to avoid spamming, something like:
```
[Miscellaneous]
log_filter=*:Info Service.Y2R:Error
```

**Comment by Barlowe11** [comment]
I know that citra is in development, buy i wonder why this cutscenes can cause fps drop on my pc. Other than that, atlus games run fullspeed for me.

**Comment by mailwl** [comment]
@Barlowe11, issue tracker, about user expirience asks on https://discuss.citra-emu.org/

**Comment by MerryMage** [comment]
Not an issue.
