### ISSUE TITLE
The Denpa Men 2: Beyond the Waves Crashes Citra on SW Backend

### ISSUE THREAD

**Issue by LunaDook** [citra-emu/citra#2440]
Tested on 16a3f9e.

To reproduce, simply turn on the software renderer and launch the game.

Log: http://pastebin.com/iyqTrsF3

Stacktrace: http://i.imgur.com/UxodcVO.png

**Comment by yuriks** [comment]
The stack trace isn't very useful unfortunately... Have you built it yourself? It should have debug info then and show function names.

**Comment by jroweboy** [comment]
@Vectrex33 you can download the debug symbols from appveyor as well https://ci.appveyor.com/api/buildjobs/38hpp9sxt44vexdd/artifacts/citra-windows-msvc-20170114-16a3f9e-debugsymbols.zip

simply unzip the file, and put the pdb files next to the citra exe and then the stack trace will actually show useful information

**Comment by Vectrex33** [comment]
Sorry, here's a proper stack trace: http://i.imgur.com/IZIUjXN.png

Still from the same commit, I'm going to retest this on latest master and see if anything has changed.

**Comment by Vectrex33** [comment]
Just built ebe01506, log shows more information.

Log: http://pastebin.com/2wYrW056

Also here's another stack trace: http://i.imgur.com/2hP7GQS.png

**Comment by Vectrex33** [comment]
This still happens on a4f88c7.

**Comment by benderscruffy** [comment]
nightly HEAD-a66e458
still happens

**Comment by benderscruffy** [comment]
still happens in the latest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2729036/citra_log.zip)

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update
