### ISSUE TITLE
Only works when Hardware renderer is turned OFF

### ISSUE THREAD

**Issue by Armonite** [citra-emu/citra#2444]
I have been trying to boot Pokemon games and they boot up but the only thing is I can see the game playing when hardware renderer is turned OFF.
When I turn it on, everything goes away and I get a black screen on my emulator.
Also my GPU supports OpenGL 4.3 so its not an issue about the openGL.
I'm running the latest version.
Please help me solve this.
![lol](https://cloud.githubusercontent.com/assets/12455548/21995138/44a16344-dc49-11e6-86ca-42688f3bc7ea.png)

**Comment by Armonite** [comment]
Also when its turned off the game gets like 4-5 FPS.
And when hardware renderer is turned ON, gets like 20-25 FPS but there is no Video only the black screen.

**Comment by wwylele** [comment]
This is more like an issue in your graphics driver. Please update the driver and turn of any software that hooks the graphics. I am going to close this for now. Please Use our [Citra Forum](https://discuss.citra-emu.org/) for questions and support instead.  If you still believe it is an issue in citra. please provide the log and screenshot with **hardware renderer ON**
