### ISSUE TITLE
Super mario maker hang when creating extra data

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#2446]
(This issue is to document a possible solution rather than just to report a bug)

Note: to boot the game you need to make a mii first. you can run mii maker on citra or import a mii save data.

After checking the mii, the game will try create (huge) extdata, while a scene of a eating pigeon is displayed on the screen. On real 3DS this process takes about 3 minutes. On citra, the file creating process finishes instantly, but the scene goes forever.

This issue is likely caused by [instant return from svcSendSyncRequest without rescheduling](https://github.com/citra-emu/citra/blob/master/src/core/hle/svc.cpp#L253). I tried to put the svcSendSyncRequest caller thread to sleep for 1ms, then wake and preempt it. This successfully bypasses the hang and lets it go in game. I also tried 0.1ms but it doesn't work well.

cc @Subv

**Comment by Subv** [comment]
Ooh interesting, what about quick reschedules? ie. SleepThread(0)

**Comment by wwylele** [comment]
@Subv SleepThread(0) doesn't work. SleepThread(1ms) without preempting does work, though. Similarly SleepThread(0.1ms) doesn't work. 

The detailed observation:
 - Current master / SleepThread(0) at the end of SendSyncRequest with/out preempting: the pigeon doesn't eat the food at all and hangs forever.
 - SleepThread(0.1ms) at the end of SendSyncRequest with/out preempting: the pigeon eats the food to some point and stop, then hangs forever
 - SleepThread(1ms) at the end of SendSyncRequest with/out preempting: the pigeon eats all food and then go in game.

**Comment by mailwl** [comment]
I want to add game Animal Crossing: Happy Home Designer, without sleep, game just hang, only L trigger (screenshot) works

**Comment by RobbyWoW** [comment]
Hey @wwylele i downloaded the cia mario maker and converted it to 3ds and now i have the same problem as u.....even tho u explained how to get into the game am not familiar with the terms and "developer part" so can u help me make citra start the game somehow....or u can send me ur build... Thx :D

**Comment by mailwl** [comment]
@RobbyWoW i suppose, you understand, Citra team not support pirates?

**Comment by Colmines92** [comment]
I like this:
_SleepThread(1ms) at the end of SendSyncRequest with/out preempting: the pigeon eats all food and then go in game._
Is it a change that can be done without affecting other games or cause other issues or slowdowns?

**Comment by Subv** [comment]
Does manually adding ticks inside SendSyncRequest fix the issue?

**Comment by wwylele** [comment]
@Subv I am not sure if this is the correct way to do this. I added `Core::System::GetInstance().CPU().AddTicks(ticks);` in `SendSyncRequest`, where for `ticks` I tried 0.1ms, 1ms and 10ms. None of them helps

**Comment by Subv** [comment]
Maybe try https://github.com/citra-emu/citra/issues/2526#issuecomment-279085036 and see if it helps?

**Comment by wwylele** [comment]
@Subv I have tried that before (and tried again today), but it doesn't help

**Comment by ThatOtterGuy** [comment]
how do i change the SendSyncRequest thing? (sorry i'm new to these stuff)

**Comment by ayunami2000** [comment]
I'm no expert, but I think the issue is forward slashes instead of back slashes.

**Comment by mailwl** [comment]
on windows? i don't think so. Try this on terminal:
`cd c:\/\/windows`

**Comment by Dragios** [comment]
As of Canary-201 this issue is considered partially fixed.
It needs PR #3091 + #3184 and possibly #3119 as well for it to be able to load the game (when save file existed).
If starting new game, it will still hang when creating extra data but soft reset the game afterward will work as usual.

A [video](https://streamable.com/braab) for preview.

**Comment by Subv** [comment]
Does it really hang? afaik the game takes a very long time creating the extdata on console

**Comment by valentinvanelslande** [comment]
broken

**Comment by Dragios** [comment]
Info: The game is still broken due to the new delay value does not fix the stalled animation. It works with the previous higher delay value.

**Comment by Loudude28** [comment]
@wwylele Thanks For All Of This Help But How Do You Do That? :)

**Comment by jurassicjordan** [comment]
is this not implemented in the latest build?

**Comment by Korkonica** [comment]
Hey, I would like to know how to do this, but honestly I don't understand how to. Do I have to download the Citra source code, edit something and build it? And if not, do I need a specific release?

**Comment by jroweboy** [comment]
@Korkonica see https://github.com/citra-emu/citra/pull/3440 for more information about how to fix it. That PR only adds appropriate delays for reading data, but citra doesn't emulate delays on *writing* data. So what you need to do is change the homebrew that is linked there to write to each location instead of read, run it on hardware and get appropriate values, and add a write delay generator in the same manner that the read generator works.

**Comment by Migmag789** [comment]
Hey is there a way to fix this ? This don't work for me :(

**Comment by enzosanchez7u7** [comment]
hi, i don't know how do that. can someone send me a video?
