### ISSUE TITLE
Game works when hardware renderer is turned ON but only black screen

### ISSUE THREAD

**Issue by Armonite** [citra-emu/citra#2448]
I was trying to boot Pokemon and I have been facing this issue since long.
Whenever my hardware renderer is turned ON the game boots up and I can see anything only black screen.
When I turn OFF "Use Hardware Renderer" then I can see the game but it is very slow and I get like 2-3 FPS.
Since @wwylele u told me to add a screen with Hardware renderer turned ON here you go.
Also there is not application running in th background that hooks my graphic card and mentioned earlier it supports upto OpenGL 4.4.
![xd](https://cloud.githubusercontent.com/assets/12455548/22060744/16f464a0-dd98-11e6-88cf-49e769adecc3.png)

**Comment by Armonite** [comment]
P.S. The graphics card driver is at its latest version.

**Comment by yuriks** [comment]
Disable/uninstall any OpenGL hooking software you might be using (Steam Overlay, FRAPS, MSI Afterburner, etc.) since they often cause this issue.

**Comment by yuriks** [comment]
And please use the forums for support.
