### ISSUE TITLE
Stopping Emulation not release the rom (at least on Windows)

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#2455]
How to reproduce:
1) Start rom
2) Select menu Emulation/Stop
3) Try to delete rom - Got error Write Protected
4) Start another rom
5) Now first rom can be deleted

**Comment by mailwl** [comment]
just a guess: ROM opened twice - as a ExeFS and as RomFs, maybe file closed only one time?

**Comment by LASTWINDOW** [comment]
I just performed a quick test with a blank text file I created called "test.3ds" and same thing happens (can't perform write operations on it unless I try opening a different rom or close Citra, it remains open even after dismissing the "Could not determine the system mode.").

Windows 10, Citra | HEAD-b36677d.
