### ISSUE TITLE
Compatibility with OpenGL 3.1 and below

### ISSUE THREAD

**Issue by 3dsemu** [citra-emu/citra#2461]
Currently, Citra only supports computers with OpenGL 3.3+. I know there's a reason 
for that, but not everybody has OpenGL 3.3. I just think that someone should add 
compatibility for OpenGL 3.1 and below. 

I have a friend who wants to use Citra, but they do not have OpenGL 3.3. So it 
would be great if someone added support for OpenGL 3.1 and below, or made
an unofficial build that supports lower versions of OpenGL.

Please do not close this issue without leaving an answer.

Thanks!

Jon

**Comment by RavenHome1** [comment]
citra used to need openGL 3.1 but there was a needed upgrade to 3.3

https://github.com/citra-emu/citra/issues/978

also github is for tracking bugs, use the forums for questions

https://community.citra-emu.org/

**Comment by 3ds-emu** [comment]
Do you have a link to an earlier build that supported OpenGL 3.1?

**Comment by 3ds-emu** [comment]
My friend's GPU does not support OpenGL 3.3. That's why I said "not everybody has OpenGL 3.3".

**Comment by FernandoS27** [comment]
a build that old wouldn't be usable for playing. The best he can do is get Mesa 3D installed.

**Comment by 3dsemu** [comment]
Why not? If it worked back then, it should work now.

**Comment by yuriks** [comment]
@3dsemu "back then" Citra wasn't able to run much of anything in the first place.

Anyway, I'm closing this since we're not going to do it. If you have any other graphics-related support issues post in the forums.
