### ISSUE TITLE
Home Menu: Does not boot

### ISSUE THREAD

**Issue by khang06** [citra-emu/citra#2465]
Tested on latest nightly with a home folder dump.

The Home Menu I used was a CXI extracted from a 4.5 O3DS Home Menu CIA downloaded from NUS. After #2196 was merged, I can get to this screen:
![image](https://cloud.githubusercontent.com/assets/11239786/22178625/170ca91a-e00a-11e6-8370-2d6fb6a0a726.png)
Instead of spamming memory errors, now it gets slightly further. It's still a black screen, though. It also fails to load on Bleeding Edge. Oddly, the pull request says you can boot the home menu without modifications, but I have no idea what else I need.

**Comment by mailwl** [comment]
affaik, home menu is not standalone app, it requires a lot of game archives.

**Comment by KillzXGaming** [comment]
@mailwl the cxi is enough to boot on its own. I've had my copy work before untill some day it stopped working again.

**Comment by Subv** [comment]
As of right now, the Home Menu tries to restart iself upon boot because of some unimplemented ptm:sysm functions

**Comment by DerProGamer2000** [comment]
working again but crashes a few seconds in but if you press the internet or brightness button it runs fine until u close out of the messages

**Comment by khang06** [comment]
That's odd, it booted but I could only hear the audio, there was no display or anything.

**Comment by khang06** [comment]
@DerProGamer2000 what version of the home menu did you use? My 4.5 copy only plays the menu music.
