### ISSUE TITLE
Inazuma eleven go shadow blue screen

### ISSUE THREAD

**Issue by tri621** [citra-emu/citra#2472]

**Comment by wwylele** [comment]
In case you didn't read:

Please read the FAQ:
https://citra-emu.org/wiki/FAQ

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

====================================================

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of Citra you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

====================================================

I am closing this for now until more detailed information is provided

**Comment by tri621** [comment]
![citra](https://cloud.githubusercontent.com/assets/25362238/22324830/e8dcf23e-e3dd-11e6-88fa-b028c0d2c6d9.png)

**Comment by tri621** [comment]
It went to blue screen when I tried to find that place

**Comment by j-selby** [comment]
Read the rest of what wwylele said - 

 - **You have provided the version (commit hash) of Citra you are using.** (It is in the screenshot, but we still need it in text)
 - **You have provided sufficient detail for the issue to be reproduced.** (Where and when does it happen? After any particular event? More context)
**You have provided system specs (if relevant)**. (Which would be really useful here).
[...]
**For graphical issues, comparison screenshots with real hardware.**
