### ISSUE TITLE
build linux fail

### ISSUE THREAD

**Issue by leonardoo** [citra-emu/citra#2480]
Hi, when i try to build citra i get 

> -- Target architecture: x86_64
-- Boost 1.57.0 or newer not found, falling back to externals
<FindSDL2.cmake>
</FindSDL2.cmake>
CMake Error at CMakeLists.txt:263 (add_subdirectory):
  The source directory
/home/leonardoo/sideproject/citra/externals/dynarmic
does not contain a CMakeLists.txt file.
CMake Error at CMakeLists.txt:274 (add_subdirectory):
  The source directory
/home/leonardoo/sideproject/citra/externals/soundtouch
does not contain a CMakeLists.txt file.
-- Configuring incomplete, errors occurred!

the commit where im build is https://github.com/citra-emu/citra/commit/372db835f48fe6e9dbf1e5652469c0a8a7447f58

**Comment by leonardoo** [comment]
from this commit 3feb3ce283b53be644bc4ca884817aba9cf63a81 it works

**Comment by Kloen** [comment]
Do you even ```git submodule update --init --recursive```?
