### ISSUE TITLE
Performance Drop on GCC with AVX Flag

### ISSUE THREAD

**Issue by tabnk** [citra-emu/citra#2481]
If use AVX or AVX2 flag after Master 3feb3ce, it will cause performance issue (- 10 fps) Mario Kart 7 and Super Mario 3D Land, Dragon Quest VII - Fragments of the Forgotten Past, etc.

GCC with **SSSE3** is higher optimization flag that can be use after Master 3feb3ce.

**Comment by FernandoS27** [comment]
Note: the problem with AVX is that cpu jit and shader jit use SSE. AVX has a performance penalty when used in conjuction with legacy SSE instructions. Now I'm not sure if there's any code that uses SSE intrinsics.

**Comment by yuriks** [comment]
That commit doesn't change any float math-related code, so it can't be the cause of the issue. Furthermore, we don't really target AVX. I'd accept a PR that fixed this issue (by using vzeroupper/etc. in the appropriate places?) if it isn't much additional code and if it doesn't regress performance for non-AVX builds, but meanwhile I'm closing this as invalid.

**Comment by tabnk** [comment]
Anyway, shader-refactor2 was the cause of it.
