### ISSUE TITLE
Fire Emblem Fates Special Edition: Birthright hangs

### ISSUE THREAD

**Issue by mraper3** [citra-emu/citra#2487]
I was playing FE Fates Special Edition: Birthright just fine up until I got the "My Castle" feature.  Within about a minute of being able to walk around the castle, the game just hangs while I'm walking around doing things.

See the citra log, gameplay screenshot at the time it happened, and my speccy below.
Citra version is nightly ac4ea52 for Windows.

Let me know if you need more information.

![citra log](https://cloud.githubusercontent.com/assets/5323781/22399761/d9770144-e569-11e6-9f44-63135f3cb384.JPG)
![gameplay at point of crash](https://cloud.githubusercontent.com/assets/5323781/22399759/d9756a1e-e569-11e6-96f0-3f67ba5e77f5.JPG)
![speccy](https://cloud.githubusercontent.com/assets/5323781/22399760/d9767094-e569-11e6-9953-4fbf80527fbd.JPG)

**Comment by mraper3** [comment]
Urk, I forgot that there may be a difference between crashing and hanging.  No program crash is recorded in Windows so there's no Windows trace, the game just hangs.  Just clarifying here.

**Comment by ElGobernador** [comment]
im using one build that doesnt crash but too slow so, u might not enjoy it  unless ur willing to play without animation

**Comment by mraper3** [comment]
@ElGobernador Which build are you using?  What's the date and commit number on it?

**Comment by mraper3** [comment]
Tried things again on the same save with citra-windows-msvc-20170325-eb8a7a9 and... it seems to work fine now.  No hanging at all, and it seems to run smoothly outside of heavily-animated sequences.  Huh.  I guess something changed within the past week or so to make it work fine.  Uh, thanks anyway!  I'll go ahead and close this issue since it seems to have been resolved.

**Comment by ElGobernador** [comment]
r u playing it pass chapter 6? usually it hangs ON MY CASTLE, not on playthrough, and i used that build as well , but it hangs on me, the only one i used that didnt hang is the input core fix build, sorry there no number in it its named like that when i downloaded it

**Comment by mraper3** [comment]
> r u playing it pass chapter 6? usually it hangs ON MY CASTLE, not on playthrough, and i used that build as well , but it hangs on me, the only one i used that didnt hang is the input core fix build, sorry there no number in it its named like that when i downloaded it

@ElGobernador I intend to continue past chapter 6, yes.  I closed this issue since it no longer seems to hang at all, at least in My Castle.  Now if it hangs later, I might reopen it again.  "input core fix build", huh.  I'll have to search around for that, I guess.

**Comment by avbitran** [comment]
Playing fates Special Edition and have the same issue. Iv'e tried several versions of citra including eb8a7a9 and the issue stays the same: whenever I gain a weapon level/support level, enter or exit a building in my castle or start a challenge there is chance the game will freeze and i'll have to restart it.

**Comment by avbitran** [comment]
Update:  After extensive testing I can confirm that the latest Bleeding Edge Version (6f5063c) Fixed the problem and there is no more hanging whatsoever.

**Comment by mraper3** [comment]
@avbitran Cool, I'll check that out and confirm.
