### ISSUE TITLE
Make system modules/services variables as member variables

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#2499]
This was something that was brought up in #2497 
Currently almost all variables related system services are defined as local `static` variables, which should be system states encapsulated by `System`. So they should be member variables of something like `Module` or existed `Interface`, which are eventually members of `System`.

Another thing need to note is that, these variables should be in three different scopes:
 - per-module variables (≈ global scope)
 - per-port variables (≈ `Interface` scope)
 - per-client variables (≈ `Session` scope)

They are currently not well-documented.

**Comment by mailwl** [comment]
just want to add: different services (user/privileged) may have different implementations

**Comment by wwylele** [comment]
This was already done after global state clean up.
