### ISSUE TITLE
Fire Emblem Fates Special Edition Crash

### ISSUE THREAD

**Issue by OniMalkav** [citra-emu/citra#2508]
Hi, I ran into a problem with Citra d0bf7df and a version few days earlier (can't remember the code but think it was Saturday) where after finishing Birthright route chapter 14 "Light Scatters" and watching Azura cutscene the screen goes black and console shows this message:
[8190.367328] Service.Y2R <Warning> core\hle\service\y2r_u.cpp:Service::Y2R::SetTransferEndInterrupt:248: <STUBBED> called
![crash](https://cloud.githubusercontent.com/assets/25461097/22474400/5a0f3f98-e7e4-11e6-96bf-be6f88fde11f.png)

After 1st crash I tried doing other scenarios (Challenge) and they worked fine.

**Comment by RavenHome1** [comment]
if i remember correctly the game works in bleeding 42, try to use that version or this might be a different crash issue.

**Comment by OniMalkav** [comment]
Didn't work. Same message on console.

**Comment by OniMalkav** [comment]
UPDATE:
Did the same map again, seems the crash is caused by reinforcements that spawn inside fortress. Cleared it twice fast enough that the reinforcements didn't spawn and no crashing. On 1st clear I only deployed 2 characters and on 2nd I had all deployed.

Still would be nice to know exact reason for the crash.

**Comment by FernandoS27** [comment]
open your citra config file in the config folder (qt-config.ini)

and change this:
[Miscellaneous]
log_filter=*:Info

to

[Miscellaneous]
log_filter=*:Debug

play the game and get the full log once the crash occurs.

**Comment by OniMalkav** [comment]
> open your citra config file in the config folder (qt-config.ini). (note the config folder is next to the sdmc, sysdata and nand).
> 
> and change this:
> [Miscellaneous]
> log_filter=*:Info
> 
> to
> 
> [Miscellaneous]
> log_filter=*:Debug
> 
> play the game and get the full log once the crash occurs. It should be more informative for us.

> 

Done, though I already gotten past the crash and overwritten the save file, however this is nice to know for the future.

**Comment by benderscruffy** [comment]
Has this been fixed ???
Please update
