### ISSUE TITLE
Clang-format bypass control on git hook

### ISSUE THREAD

**Issue by Kloen** [citra-emu/citra#2510]
Actually, there is a way to bypass the clang-format. I open this issue because I think that someone willing to contribute could attempt to fix this.

Steps to repeat:

1. Write something non compilant with clang-format rules.
2. git add -A
3. git commit -m "Test"
4. Enjoy the clang-format error
5. Fix clang-format on file and save it
6. Don't do git add, and directly use git commit -m "X"
7. Enjoy your non-compilant code on your branches, or PR's

**Comment by jroweboy** [comment]
This sounds like a non issue to me personally. Running the pre commit hook is for convenience, but its not meant to force you to comply. I mean, a git commit --no-verify would just not run the commit hook as well, and there are several times where I don't want to struggle to get my clang format working just to make a commit to a local branch before switching branches or something. At the end of the day, when the code is PRed, the linux build will fail if its not formatted correctly and you just don't merge the code to master until its properly formatted. In theory thats what should happen at least :)

**Comment by jfmherokiller** [comment]
well i hopefully made it compatable with github desktop for linux and mac as long as clang-format is installed.

**Comment by MerryMage** [comment]
pre-commit hook no longer runs clang-format locally as of #2579.
