### ISSUE TITLE
Shader JIT crashes Fire Emblem Fates - Conquest

### ISSUE THREAD

**Issue by pekenizo** [citra-emu/citra#2516]
Edited for clarity.

The following was tested on my home PC:
Tha game boots up fine, and starts playing the intro video. Pressing a button to skip the video or watching it to the end results in a crash, every time.
Deactivating the Shader JIT removes the crashing and allows going ingame. Managed to play halfway the intro mission with no crashes or any other issues save for very low speed. Reactivating the Shader JIT ingame instantly crashes the emulation.

The following was done on the office PC:
Started the emu with the Shader JIT active and played seven missions with no major issues at all, not a single crash.

My home PC is running Windows 10, with a Nvidia 750ti card.
My office PC is running Windows 8.1, with an onboard Intel 4600 graphics chip
The emu version is 20170131-d0bf7df

**Comment by wwylele** [comment]
Do you mean the crash doesn't happen on your office PC? Could you please provide the CPU information of each PC?

**Comment by pekenizo** [comment]
Home PC is a core i3, don't have the exact version at hand.
Office PC is a core i5-4440.
Both are desktop PCs

**Comment by mailwl** [comment]
for me the game works just fine.

**Comment by wwylele** [comment]
Does this still happen with #2520 ?

**Comment by pekenizo** [comment]
Is #2520 included in Nightly 38 or Bleeding Edge 172?
Can't tell you otherwise, my PC is no set up for compiling the code.

**Comment by wwylele** [comment]
@pekenizo I tagged #2520 so that it will be included in the next bleeding edge build (173+). You can test it when it is out.

**Comment by pekenizo** [comment]
Bleeding edge 174 solves this issue, everything points at wwylele's 16 dummy bytes doing the trick.
Unless anyone else has this same problem, I think this issue can be safely declared closed.
