### ISSUE TITLE
Majora's Mask - Deku Scrub - Very Loud Walking Sound

### ISSUE THREAD

**Issue by Schplee** [citra-emu/citra#2517]
As users have reported on the forums, there is a huge difference in the walking sound effect of the Deku Scrub on Citra and the 3DS. I've recorded a comparison video for those who wish to hear the difference, as well as uploaded a save file so you can test it yourself.

https://www.youtube.com/watch?v=wrG-LFSLsOo&feature=youtu.be

Here is a visual representation of how much louder the Deku Scrub sound is in Citra, with the upper audio track being Citra and the lower two being recorded from the 3DS.

![8odokm7](https://cloud.githubusercontent.com/assets/24275329/22571096/3ae5252c-e96c-11e6-8a04-bad2f4edd01d.png)

[Save File for Replicating Sound Issue](https://github.com/citra-emu/citra/files/749107/00125600.zip)

This has occurred in all versions of Citra.

For those who don't know, the sudden interrupts in the walking audio are me also demonstrating the differences in the "dash" sound.

**Comment by DerProGamer2000** [comment]
the animation which plays when you put off a mask is also loud and has some kind of hum sound to it and it is a bit diffrent sounding but i don't know

**Comment by crx-au** [comment]
I'm not sure if this helps at all, but I found a workaround for this issue online and posted about it on the Citra forums.

https://community.citra-emu.org/t/majoras-mask-deku-link/414/8

**Comment by PPLToast** [comment]
This was fixed by what I presume to be merry's pr. The rupee collecting sound still seems to be a bit off though, sounding a tad less "sharp" than it's supposed to.

[Latest bleeding edge](https://www.youtube.com/watch?v=GKMHSb757B8)

[3DS](https://youtu.be/KyjSqg0WGio?t=7m49s)

**Comment by Schplee** [comment]
Fixed by #2858
