### ISSUE TITLE
Picross 3D Round 2 get stuck after click on puzzle

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#2521]
log: http://pastebin.com/wsHCxHuA
Win10, Core i7, NVidia GTX 980M
stuck at ArbitrateAddress()

![picross](https://cloud.githubusercontent.com/assets/629437/22598558/e9f5174c-ea44-11e6-870a-279464e4da2b.png)

**Comment by wwylele** [comment]
Candidate:

>[   3.472951] Audio.DSP <Critical> audio_core\hle\pipe.cpp:DSP::HLE::PipeWrite:166: pipe_number = 3 unimplemented

**Comment by mailwl** [comment]
hmm... merging https://github.com/MerryMage/citra/tree/pipe3 fixed problem.
should i close issue?

**Comment by wwylele** [comment]
@mailwl no, keep this open until that one is merged to master

**Comment by mailwl** [comment]
Eh, default amiibo from Mini Mario & Friends not supported by this game :(
it's time to bruteforce

**Comment by mailwl** [comment]
summon @MerryMage , your workaround helps to run 2 games already, maybe it deserve to be in master as temporary?

**Comment by ijh89oid7g** [comment]
How can I fix that I understand nothing that is written here can some one explain it to a noob how to fix it?

**Comment by benderscruffy** [comment]
still doesn't work on the latest nightly or canary

**Comment by benderscruffy** [comment]
has not been added to nightly yet

**Comment by wwylele** [comment]
DSP LLE is merged. Please report back and continue to track this issue on while we fix DSP HLE.

**Comment by FearlessTobi** [comment]
Can confirm this is fixed with DSP HLE.
