### ISSUE TITLE
Optimize log spam

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#2522]
Main idea:
if previous log string equal current one, do not show current, but add counter, and then log string changes, log previous + number of counter. i.e:
```
[  11.423697] HW.GPU <Error> video_core\command_processor.cpp:Pica::CommandProcessor::WritePicaReg:364: Invalid VS uniform index 127
[  12.246473] HW.GPU <Error> video_core\command_processor.cpp:Pica::CommandProcessor::WritePicaReg:364: Invalid VS uniform index 127 (repeats 238 times)
```

**Comment by FernandoS27** [comment]
uhh maybe generate a unique id depending on where it was called and compare that id to last id. Comparing strings is a no go for logs unless you want to exchange lag for span.

**Comment by mailwl** [comment]
comparing strings in mooore faster console output

**Comment by FernandoS27** [comment]
yeah but you are forgetting of the massive trace and debug logs that are already filtered.

**Comment by mailwl** [comment]
check after filtering? don't remember, is it possible.
when i need to log all service logs, except spamming, i did such dirty hack:
https://github.com/mailwl/citra/blob/sys-services/src/core/hle/service/service.cpp#L132
but it do not work in common

**Comment by FernandoS27** [comment]
you could add new filtering option to config.ini and apply it on the log filter in main.cpp

log/filter.h allows you to filter based on class (module which is writing to log).

**Comment by mailwl** [comment]
for sure i can do what i want with opensource (if you look at code i link, i log very useful register LR to see where in code was service call).
Idea for Citra codebase - get rid spam

**Comment by Hexagon12** [comment]
Is this for #2473 ?

**Comment by mailwl** [comment]
No, i hate pokemon games, it was just a random game to introduce the problem

**Comment by Hexagon12** [comment]
Still, it will fix that issue also. Don't it?

**Comment by mailwl** [comment]
no. in this case it just hide issue a little.
it was bad example
