### ISSUE TITLE
Mega Man Legacy Collection hang at loading screen

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#2526]
version: master 9590c93 
OS: Ubuntu 16.04

This is a regression from some point, probably from scheduler reworking. It was playable when CRO is implemented

![screenshot from 2017-02-04 11-59-38](https://cloud.githubusercontent.com/assets/4592895/22617592/9ba3ef5e-ead1-11e6-92c2-b89980aede70.png)

(the revision is dirty due to an unrelated dynarmic warning-fix change)
These threads are:
 - [178] the main thread
 - [183] SRV event listener 
 - [191] APT event listener
 - [221] video thread
 - [230] audio thread
 - [239] possibly working thread on FS

All these threads are on the AppCore

Note that the thread 239 (the last one) is always ready but is never scheduled to execute (PC = entry point). It has the same priority as the main thread. The main thread can be seen scheduled sometimes (when the video and audio threads are not busy). So this probably involves how 3DS schedules two threads with the same priority. It was able to run probably due to priority boost for starved threads

Log: http://pastebin.com/VJKqBQX1
Log with level Trace (except for Audio and Service.GSP) http://pastebin.com/cxv302AD

**Comment by mailwl** [comment]
LR=0 it's very bad. eh, bad, when my proposal about creating thread was declined

**Comment by yuriks** [comment]
Are the other threads all AppCore threads too?

**Comment by wwylele** [comment]
@yuriks: yes, sorry I forgot to mention

**Comment by wwylele** [comment]
@mailwl I don't see what's bad with that. It just indicates that the thread hasn't called into any function (because it hasn't been even scheduled)

**Comment by mailwl** [comment]
i suppose main thred sleep at ArbitrateAdress?

**Comment by wwylele** [comment]
@mailwl it is "ready", which means it doesn't wait on anything. If it is sleeping at ArbitrateAddress， it will be shown as "wait on address..." with brown color

**Comment by mailwl** [comment]
sorry to ask about it, but may you add log?

**Comment by FernandoS27** [comment]
Could you get the TRACE Log ?

**Comment by wwylele** [comment]
A small update with a random hack: change [the `push_front` here](https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/thread.cpp#L159) to `push_back`, and the it bypasses the loading screen. In the source there are thread push operation to `read_queue`, but only this one is `push_front`. I don't know if it means something, but at least it confirms that the hang is related to the scheduling between two threads with the same priority.

**Comment by B3n30** [comment]
Closed by #3091
