### ISSUE TITLE
Ultimate NES Remix ID: 0004000000132100 - Region Auto-Select Error

### ISSUE THREAD

**Issue by Kumoashi** [citra-emu/citra#2527]
It seems that the Auto Region Select is selecting the wrong settings for Ultimate NES Remix. The Title ID for this ROM is 0004000000132100. Citra version is HEAD-9590c93.
When you run the game with Region set to Auto-select, it fails to start and the log shows this.

**Citra Log - Region Set To Auto-select:**
[  12.065266] Service.FS <Info> core\file_sys\archive_sdmc.cpp:FileSys::ArchiveFactory_SDMC::ArchiveFactory_SDMC:309: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/ set as SDMC.
[  12.067773] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/
[  12.068023] Service.FS <Info> core\file_sys\archive_sdmcwriteonly.cpp:FileSys::ArchiveFactory_SDMCWriteOnly::ArchiveFactory_SDMCWriteOnly:35: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/ set as SDMCWriteOnly.
[  12.068437] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/
[  12.068658] Service.FS <Info> core\file_sys\archive_source_sd_savedata.cpp:FileSys::ArchiveSource_SDSaveData::ArchiveSource_SDSaveData:42: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
[  12.068844] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:176: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  12.266240] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
[  12.267516] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:176: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  12.268064] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/nand/data/00000000000000000000000000000000/extdata/
[  33.033712] Frontend <Info> citra_qt\main.cpp:GMainWindow::BootGame:339: Citra starting...
[  33.808873] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:142: Loading file E:/Roms/3DS/Decrypted/Ultimate NES Remix (E).3ds as NCSD...
[  33.810049] Loader <Warning> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:256: Only loading the first (bootable) NCCH within the NCSD file!
[  33.810330] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:280: Name:                        HeriC
[  33.811024] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:281: Program ID:                  0004000000132100
[  33.839723] Service.FS <Info> core\file_sys\archive_sdmc.cpp:FileSys::ArchiveFactory_SDMC::ArchiveFactory_SDMC:309: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/ set as SDMC.
[  33.841700] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/
[  33.842030] Service.FS <Info> core\file_sys\archive_sdmcwriteonly.cpp:FileSys::ArchiveFactory_SDMCWriteOnly::ArchiveFactory_SDMCWriteOnly:35: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/ set as SDMCWriteOnly.
[  33.842566] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/
[  33.842822] Service.FS <Info> core\file_sys\archive_source_sd_savedata.cpp:FileSys::ArchiveSource_SDSaveData::ArchiveSource_SDSaveData:42: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
[  33.843042] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:176: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  33.843869] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
[  33.844232] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:176: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  33.844891] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/nand/data/00000000000000000000000000000000/extdata/
[  33.888030] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sysdata/shared_font.bin
[  33.901679] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:495: GL_VERSION: 3.3.0 - Build 10.18.10.4425
[  33.902020] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:496: GL_VENDOR: Intel
[  33.902191] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:497: GL_RENDERER: Intel(R) HD Graphics
[  33.960565] Loader <Info> core\hle\kernel\process.cpp:Kernel::Process::ParseKernelCaps:99: ExHeader kernel version: 2.33
[  33.962838] Service.CFG <Info> core\hle\service\cfg\cfg.cpp:Service::CFG::SetPreferredRegionCode:582: Preferred region code set to 0
[  33.963106] Service.CFG <Warning> core\hle\service\cfg\cfg.cpp:Service::CFG::SetPreferredRegionCode:590: System language 1 does not fit the region. Adjusted to 0
[  34.313177] Service.SRV <Warning> core\hle\service\srv.cpp:Service::SRV::RegisterClient:40: (STUBBED) called
[  34.563322] Service.SRV <Warning> core\hle\service\srv.cpp:Service::SRV::EnableNotification:64: (STUBBED) called
[  34.572399] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GetLockHandle:120: (STUBBED) called handle=0x00030008 applet_attributes=0x00000000
[  34.585951] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::SetScreenCapPostPermission:416: (STUBBED) screen_capture_post_permission=0
[  34.590781] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::OverrideDefaultDaemons:201: (STUBBED) default_daemon_bit_mask=0x0000000F
[  34.593960] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::SuspendDaemons:87: (STUBBED) daemon_bit_mask=0x00000009
[  34.595149] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Enable:128: (STUBBED) called attributes=0x00000000
[  34.601579] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GlanceParameter:247: called app_id=0x00000300, buffer_size=0x00001000
[  34.606237] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::NotifyToWait:102: (STUBBED) app_id=768
[  34.610199] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::ReceiveParameter:224: called app_id=0x00000300, buffer_size=0x00001000
[  34.641045] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:318: (STUBBED) called command=0x00000007, buffer1_size=0x00000004, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF40, buffer2_addr=0x0FFFFF0C
[  34.646579] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:318: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF08, buffer2_addr=0x0FFFFF0C
[  34.650241] Service.FS <Warning> core\hle\service\fs\fs_user.cpp:Service::FS::InitializeWithSdkVersion:798: (STUBBED) called, version: 0x070201C8
[  34.657652] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::SetAppCpuTimeLimit:332: (STUBBED) called cpu_percent=25, value=1
[  34.757677] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::AcquireRight:690: called
[  34.787782] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::RegisterInterruptRelayQueue:384: called, flags=0x00000001
[  35.851005] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:142: Firmware hash: 0x348ac2f23aa20bca
[  35.853916] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:146: Structures hash: 0x93e48663943cad39
[  35.854111] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:150: (STUBBED) called size=0xC288, prog_mask=0x505300FF, data_mask=0x000D00FF, buffer=0x0036A064
[  35.856563] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::RegisterInterruptEvents:241: Registered type=2, pipe=2, event_handle=0x000E002C
[  35.859289] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::GetSemaphoreEventHandle:167: (STUBBED) called
[  35.860364] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphoreMask:446: (STUBBED) called mask=0x00002000
[  35.861639] Audio.DSP <Info> audio_core\hle\pipe.cpp:DSP::HLE::PipeWrite:134: Application has requested initialization of DSP hardware
[  35.864665] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphore:264: (STUBBED) called
[  35.871553] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphore:264: (STUBBED) called
[  35.929004] Kernel.SVC <Warning> core\hle\svc.cpp:SVC::CreateThread:563: Newly created thread is allowed to be run in the SysCore, unimplemented.
[  36.124717] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::ThrowFatalError:171: Fatal error
[  36.126674] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::ThrowFatalError:174: Fatal error type: Generic
[  36.126837] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:144: PID: 0x0000000A
[  36.126998] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:146: REV: 0x00000000_0x0000DDB5
[  36.127138] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:148: TID: 0x00000000_0x00000000
[  36.127277] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:150: AID: 0x00000000_0x00000000
[  36.127416] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:151: ADR: 0x00201E48
[  36.127588] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:153: RSL: 0xC8804471
[  36.127726] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:154:   Level: 25
[  36.127863] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:155:   Summary: 4
[  36.128031] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:156:   Module: 17
[  36.129091] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::LogGenericInfo:157:   Desc: 113
[  36.129368] Service.ERR <Critical> core\hle\service\err_f.cpp:Service::ERR::ThrowFatalError:184: Datetime: 2017/02/04 08:52:20

The system language also gets set to Japanese, as shown here.
![image](https://cloud.githubusercontent.com/assets/24490104/22619090/672f4118-eaba-11e6-95a8-0e573b82230d.png)

If you manually set the Region to EUR, the game starts normally.
![image](https://cloud.githubusercontent.com/assets/24490104/22619103/c507256c-eaba-11e6-9c1b-3f1be6ff2b1e.png)
![image](https://cloud.githubusercontent.com/assets/24490104/22619112/f0972fd8-eaba-11e6-8e18-70b5d10b79ef.png)

Here is the log from the game running while set to EUR for comparison.
**Citra Log - Region Set To EUR:**
[  83.915183] Frontend <Info> citra_qt\main.cpp:GMainWindow::BootGame:339: Citra starting...
[  84.237740] Loader <Info> core\loader\loader.cpp:Loader::GetLoader:142: Loading file E:/Roms/3DS/Decrypted/Ultimate NES Remix (E).3ds as NCSD...
[  84.239166] Loader <Warning> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:256: Only loading the first (bootable) NCCH within the NCSD file!
[  84.239460] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:280: Name:                        HeriC
[  84.239632] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::LoadExeFS:281: Program ID:                  0004000000132100
[  84.259476] Service.FS <Info> core\file_sys\archive_sdmc.cpp:FileSys::ArchiveFactory_SDMC::ArchiveFactory_SDMC:309: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/ set as SDMC.
[  84.261425] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/
[  84.261654] Service.FS <Info> core\file_sys\archive_sdmcwriteonly.cpp:FileSys::ArchiveFactory_SDMCWriteOnly::ArchiveFactory_SDMCWriteOnly:35: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/ set as SDMCWriteOnly.
[  84.262125] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/
[  84.262357] Service.FS <Info> core\file_sys\archive_source_sd_savedata.cpp:FileSys::ArchiveSource_SDSaveData::ArchiveSource_SDSaveData:42: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
[  84.262543] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:176: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  84.264445] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
[  84.264682] Service.FS <Info> core\file_sys\archive_extsavedata.cpp:FileSys::ArchiveFactory_ExtSaveData::ArchiveFactory_ExtSaveData:176: Directory C:\Users\Kumoa_000\AppData\Roaming/Citra/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[  84.265178] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/nand/data/00000000000000000000000000000000/extdata/
[  84.657197] Common.Filesystem <Warning> common\file_util.cpp:FileUtil::CreateFullPath:200: path exists C:\Users\Kumoa_000\AppData\Roaming/Citra/sysdata/shared_font.bin
[  84.671135] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:495: GL_VERSION: 3.3.0 - Build 10.18.10.4425
[  84.671395] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:496: GL_VENDOR: Intel
[  84.671562] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:497: GL_RENDERER: Intel(R) HD Graphics
[  84.741329] Loader <Info> core\hle\kernel\process.cpp:Kernel::Process::ParseKernelCaps:99: ExHeader kernel version: 2.33
[  84.744560] Service.CFG <Info> core\hle\service\cfg\cfg.cpp:Service::CFG::SetPreferredRegionCode:582: Preferred region code set to 0
[  85.069773] Service.SRV <Warning> core\hle\service\srv.cpp:Service::SRV::RegisterClient:40: (STUBBED) called
[  85.295341] Service.SRV <Warning> core\hle\service\srv.cpp:Service::SRV::EnableNotification:64: (STUBBED) called
[  85.304497] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GetLockHandle:120: (STUBBED) called handle=0x00030008 applet_attributes=0x00000000
[  85.313373] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::SetScreenCapPostPermission:416: (STUBBED) screen_capture_post_permission=0
[  85.315948] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::OverrideDefaultDaemons:201: (STUBBED) default_daemon_bit_mask=0x0000000F
[  85.317379] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::SuspendDaemons:87: (STUBBED) daemon_bit_mask=0x00000009
[  85.318502] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Enable:128: (STUBBED) called attributes=0x00000000
[  85.322559] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GlanceParameter:247: called app_id=0x00000300, buffer_size=0x00001000
[  85.328593] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::NotifyToWait:102: (STUBBED) app_id=768
[  85.332299] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::ReceiveParameter:224: called app_id=0x00000300, buffer_size=0x00001000
[  85.337801] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:318: (STUBBED) called command=0x00000007, buffer1_size=0x00000004, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF40, buffer2_addr=0x0FFFFF0C
[  85.339319] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:318: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF08, buffer2_addr=0x0FFFFF0C
[  85.342463] Service.FS <Warning> core\hle\service\fs\fs_user.cpp:Service::FS::InitializeWithSdkVersion:798: (STUBBED) called, version: 0x070201C8
[  85.350133] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::SetAppCpuTimeLimit:332: (STUBBED) called cpu_percent=25, value=1
[  85.440107] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::AcquireRight:690: called
[  85.443798] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::RegisterInterruptRelayQueue:384: called, flags=0x00000001
[  86.362092] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:142: Firmware hash: 0x348ac2f23aa20bca
[  86.364224] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:146: Structures hash: 0x93e48663943cad39
[  86.364424] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:150: (STUBBED) called size=0xC288, prog_mask=0x505300FF, data_mask=0x000D00FF, buffer=0x0036A064
[  86.366868] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::RegisterInterruptEvents:241: Registered type=2, pipe=2, event_handle=0x000E002C
[  86.368037] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::GetSemaphoreEventHandle:167: (STUBBED) called
[  86.369098] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphoreMask:446: (STUBBED) called mask=0x00002000
[  86.370501] Audio.DSP <Info> audio_core\hle\pipe.cpp:DSP::HLE::PipeWrite:134: Application has requested initialization of DSP hardware
[  86.371339] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphore:264: (STUBBED) called
[  86.376090] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphore:264: (STUBBED) called
[  86.414156] Kernel.SVC <Warning> core\hle\svc.cpp:SVC::CreateThread:563: Newly created thread is allowed to be run in the SysCore, unimplemented.
[  86.695888] Service.AC <Warning> core\hle\service\ac\ac.cpp:Service::AC::SetClientVersion:156: (STUBBED) called, version: 0x070201C8
[  86.698723] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:95: unknown / unimplemented function 'GetLastErrorCode': port=ac:u
[  86.798094] Service.CFG <Warning> core\hle\service\cfg\cfg.cpp:Service::CFG::GenHashConsoleUnique:186: (STUBBED) called app_id_salt=0x0
[  86.947608] Service.FRD <Warning> core\hle\service\frd\frd.cpp:Service::FRD::SetClientSdkVersion:110: (STUBBED) called, version: 0x070201C8
[  86.949851] Service.FRD <Warning> core\hle\service\frd\frd.cpp:Service::FRD::GetMyPresence:29: (STUBBED) called
[  87.270155] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:318: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF80, buffer2_addr=0x0FFFFF84
[  87.272546] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:318: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF80, buffer2_addr=0x0FFFFF84
[  93.032672] Service.FS <Error> core\hle\service\fs\archive.cpp:Service::FS::File::HandleSyncRequest:110: Reading from out of bounds offset=0x0 length=0x0003BC00 file_size=0x3BBE0
[  93.444151] Service.FS <Error> core\hle\service\fs\archive.cpp:Service::FS::File::HandleSyncRequest:110: Reading from out of bounds offset=0x3BBE0 length=0x00000020 file_size=0x3BBE0
[ 159.379297] Service.CFG <Warning> core\hle\service\cfg\cfg.cpp:Service::CFG::GenHashConsoleUnique:186: (STUBBED) called app_id_salt=0x1321
[ 160.177005] Service.CFG <Warning> core\hle\service\cfg\cfg.cpp:Service::CFG::GenHashConsoleUnique:186: (STUBBED) called app_id_salt=0x1321
[ 160.783721] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:95: unknown / unimplemented function 'ControlArchive': port=fs:USER, cmd_buff[1]=0x5, cmd_buff[2]=0x0, cmd_buff[3]=0x0, cmd_buff[4]=0x1, cmd_buff[5]=0x1, cmd_buff[6]=0x1A, cmd_buff[7]=0xFFFFF98, cmd_buff[8]=0x1C, cmd_buff[9]=0xFFFFF9C
[ 169.999941] Service.FS <Warning> core\hle\service\fs\archive.cpp:Service::FS::File::HandleSyncRequest:172: (STUBBED) File command OpenLinkFile Path: [Binary: 000000000000000000000000]

**Comment by wwylele** [comment]
I want to confirm this first: is the game an original dump from cartridge/installed title? I ask this because there are some people using "region-free" ROMs (which by definition doesn't contain information for region detection)

**Comment by Kumoashi** [comment]
I'm not sure, to be honest, The title id is for the cartridge version through. I'm not sure where the ROM came from. I mostly got it too test region settings among other things. I'm in the US and I don't have any easy ways of getting out of region games right now, so finding a new copy to test might be difficult. Is there a way to check if it's region-free? If it helps, the game fails to start if region is set to anything else except for EUR. Sorry that I can't be of any more help.

**Comment by wwylele** [comment]
> I'm not sure where the ROM came from.

I treat this as a statement of using pirated copies. We do not support piracy.
