### ISSUE TITLE
[Regression] Build failure

### ISSUE THREAD

**Issue by lefta** [citra-emu/citra#2529]
On the latest git head (9590c93), citra fails to build with this error:

    /var/tmp/portage/games-emulation/citra-9999/work/citra-9999/externals/dynarmic/src/backend_x64/emit_x64.cpp: In member function ‘void Dynarmic::BackendX64::EmitX64::EmitCoprocLoadWords(Dynarmic::IR::Block&, Dynarmic::IR::Inst*)’:
    /var/tmp/portage/games-emulation/citra-9999/work/citra-9999/externals/dynarmic/src/backend_x64/emit_x64.cpp:3178:25: error: ‘*((void*)& option +1)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         boost::optional<u8> option{has_option, coproc_info[5]};
                             ^~~~~~

I'm building on Linux with GCC 6.3.0.

**Comment by wwylele** [comment]
Can confirm with GCC 6.2.0. This seems a bug in GCC. currently an workaround is to remove the `-Werror` flag in dynarmic CMakeLists. This issue should probably be opened in dynarmic repo, though

**Comment by MerryMage** [comment]
Pushed a commit: MerryMage/dynarmic@a77710e5cf7222c3c257be315ddd9a2ab36c1d68

**Comment by lefta** [comment]
I confirm that this latest commit fixes the build, thanks.

**Comment by mailwl** [comment]
@lefta please, close issue, as it fixed

**Comment by lefta** [comment]
I was not if you wanted to wait for it to be updated in Citra, I'm closing.

**Comment by mailwl** [comment]
ups, i think, fix is already merged

**Comment by Dragios** [comment]
Dynarmic commit is not merged to master yet. Don't close yet.

**Comment by j-selby** [comment]
Weird. This bug didn't appear on GCC 6.2.0, and works fine with -Werror. Using dpkg-buildpackage on Ubuntu Server 16.10.

**Comment by mailwl** [comment]
bug in gcc 6,3? It's very rare to find a bug in such old software

**Comment by wwylele** [comment]
Fixed by #????

**Comment by lefta** [comment]
For completeness, `#????` is 3a96dd0. Thanks guys ;)
