### ISSUE TITLE
Rhythm Heaven Megamix: Hangs at a black screen when loading any game

### ISSUE THREAD

**Issue by khang06** [citra-emu/citra#2543]
https://gfycat.com/GrandioseVariableEider
Video was recorded on Bleeding Edge, but it also happens on the nightlies (bleeding edge is just slightly faster as the game runs very slowly)
Nothing helpful is printed in the log.

**Comment by 1425720626** [comment]
Seems like the current version lacks AAC audio format support. This also happens on Pokemon X/Y.

**Comment by wwylele** [comment]
Please still provide the full log. Helpful thing might be printed before the hang

**Comment by khang06** [comment]
The first time I tested it, it would just spam the looped buffers message over and over. Now when I test it, I get an actually useful message!

https://gist.github.com/khang06/4df9a54ce3998407eaf6fe815c4c4c67

`[  27.768306] Audio.DSP <Critical> audio_core\hle\pipe.cpp:DSP::HLE::PipeWrite:166: pipe_number = 3 unimplemented`

**Comment by khang06** [comment]
Using code from https://github.com/MerryMage/citra/commits/pipe3 doesn't help, either. It simply doesn't print the pipe unimplemented line.

**Comment by BeeMovieScript** [comment]
Make a fork that actually plays Rhythm Heaven Megamix

**Comment by Monkena** [comment]
using Citra-Mingw-18-04-2017 loaded just fine, low fps, but that's probably a fault from my side

**Comment by 1425720626** [comment]
I got another useful message from the log of the latest version of Citra.
`[  12.359954] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:RegisterInterruptEvents:241: Registered type=2, pipe=3, event_handle=0x00180083`
`[  12.362612] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:RegisterInterruptEvents:246: Unregistered interrupt=2, channel=3, event_handle=0x00000000`

**Comment by ljyloo** [comment]
Still got the same error on the lastest nighty build :(

**Comment by Donktopus** [comment]
Nobody got a solution yet? Well, I guess I have to keep waiting... having the same problems in latest nightly.

**Comment by jdenm8** [comment]
Also got the error on Tales of the Abyss at boot time, reducing it from Graphically Broken to No-Boot.

Looks like it calls a bunch of stubbed DSP methods then hits virtually the same critical error as seen here.

`[2.440916] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:LoadComponent:157: (STUBBED) called size=0x34BB6, prog_mask=0x000000FF, data_mask=0x000D00FF, buffer=0x09990020`
`Stubbed calls getting and setting the state of DSP Semaphores, probably not important`
`A Kernel error about an SVC thread that's probably not relevant`
`[2.559250] Audio.DSP <Critical> audio_core/hle/pipe.cpp:PipeWrite:166: pipe_number = 3 unimplemented`

**Comment by khang06** [comment]
Does that game use AAC music? My theory on why Megamix won't run is because AAC is unimplemented, and the game seems to depend a lot on the music file (for example i changed one of the music files and it sped up the gameplay for some reason)

**Comment by 1425720626** [comment]
I think that's not the main problem. The original GBA Music in the recording gallery of Mario & Luigi: Superstar Saga + Bowser's Minions also use AAC format, I tested it and it just skipped them, no hanging or crashing.

**Comment by jdenm8** [comment]
I can't really tell what codec it's using. Maybe it does use some AAC and acted like Superstar Saga did for 1425720626 before this started happening. It did work going back to at least July. AFAIK, Rhythm Heaven Megamix has never worked. Though I think it might have played the intro screens for the songs which it doesn't now.

**Comment by hyarsan** [comment]
It does the same thing for me.

**Comment by khang06** [comment]
![image](https://user-images.githubusercontent.com/11239786/37547134-3d5e867a-2946-11e8-9b2d-c63971754c1e.png)
now it shows another message

**Comment by Imorales80** [comment]
Really want this to be fixed thought, i'll be patient and check everyday to see how this goes, it's all on you guys since I don't know shit about programming

**Comment by jdenm8** [comment]
Nothing's going to happen until the Sound Emulation is looked at. At the moment, it appears most of the attention is being placed on timing and shading.

The issue has sat here for over a year. It might sit here for another year. 

As for the change above, PipeWrite's probably been expanded, bumping the the issue from Line 166 to Line 181. It's probably exactly the same call doing it though. Looks like it's been allowed past it though to the next line where it crashes for a different reason. Dunno, not a dev.

Also, confirming that the same thing still happens in Tales of the Abyss.

**Comment by tommyTsaiTou** [comment]
Latest canary build log:
[citra_log.txt](https://github.com/citra-emu/citra/files/1958797/citra_log.txt)

**Comment by tommyTsaiTou** [comment]
I have imported a fully passed save data from a real 3ds console.
I found that it can not skip aac file loading or some service warnings.
Still wanted to be fix.

**Comment by starwarswii** [comment]
Just tested with the latest nightly and canary. Still an issue. (Windows x64)

**Comment by sufumin** [comment]
Still an issue. canary

**Comment by oddMLan** [comment]
Is a there LLE audio option?

**Comment by imlatefortheshow** [comment]
LLE audio is implemented, now you can play it on the latest Canary build.
Too slow and laggy though.

**Comment by jdenm8** [comment]
Can confirm, LLE lets Rhythm Heaven into the Rhythm games and Tales of the Abyss now boots.

Speed is 1/5th of correct on my system, but this will eventually get ironed out. Props to the devs!

**Comment by Dragios** [comment]
Just a note to reference that this is fixed with PR #4490

**Comment by robzombie91** [comment]
Game works in HLE with the newest additions by @B3n30

**Comment by wwylele** [comment]
DSP LLE is merged. Please continue to track this issue on while we fix DSP HLE.

**Comment by xperia64** [comment]
I'm not seeing any black screens anymore, and it's out of canary, so I think this specific issue can be closed (https://github.com/citra-emu/citra/issues/4649 should remain open however)
