### ISSUE TITLE
I can't install nightly builds on MacOS

### ISSUE THREAD

**Issue by pikachu6598** [citra-emu/citra#2547]
Every nightly build I've downloaded downloads as a .tar file, and when I open it, it only creates a copy of itself. It's a completely recursive process, and I can't find any information on the issue or how to handle it anywhere.

**Comment by Dragios** [comment]
Please use the forum for such issues you encounter. This is a bug tracker report for developers.
Please close this.

**Comment by pippo2931** [comment]
Open terminal
cd /Users/"your user"/Downloads
tar xvf citra-osx-20170206-c04062c.tar.xz

**Comment by jroweboy** [comment]
This is a issue tracker for citra and not a support site. Please use the forums for support. https://community.citra-emu.org

Closed as Invalid

(PS: its a .tar.xz file so you need to extract it first)
