### ISSUE TITLE
Fire Emblem: Awakening - Effects Error

### ISSUE THREAD

**Issue by DieggoN** [citra-emu/citra#2548]
Hello sirs!
First i wanted to thank you for create this project. Citra is really awesome.
I'm having a problem playing Fire Emblem: Awakening and i wanted to show you.

Please see this images:
![fe - prints1](https://cloud.githubusercontent.com/assets/25653048/22767787/778fb9d4-ee5c-11e6-916d-f0afc55fa862.jpg)

![fe print 2](https://cloud.githubusercontent.com/assets/25653048/22767859/f8e3fa68-ee5c-11e6-9515-6662e2c29666.png)

The number 1 images are from "citra-qt-gcc-24-no-inputcore" version of 12/01/2016. And the number 2 images are from the latest version. As you can see, the effects are nos showing very well It only happens with effects, the characters and videos are okay. 

You sirs know what it can be?
Thanks for the attention.
------------------------

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forum for support requests instead. https://community.citra-emu.org

Closed as invalid

(PS: this is because of missing geometry shaders, a feature that is under development. Check the forums for more information)
