### ISSUE TITLE
Pokémon Main Series (X/Y, OR/AS, S/M) – Lighting/Shadowing Issue

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2551]
I just discovered this regression is due to **Lighting LUT Quickfix #2367**.
Exact commit will be 88f409aec9a490138012cde35789d1f21f20818f

**Before** (commit 14f8065843bf865cbd0f2f34eabf54c37e52df81) / **After** (commit 2f746e9946f78a2e283dfdcbeda9cf332e44d099) / **Console**

**[Pokémon X/Y]**
![Pokémon X](https://cloud.githubusercontent.com/assets/18496868/25071192/7ee350a4-22e3-11e7-9051-6616b7ce6a5c.png)
Source: [Before](https://cloud.githubusercontent.com/assets/18496868/25092820/ef8cc680-23c1-11e7-835e-d4ee8d9abd8c.png) | [After](https://cloud.githubusercontent.com/assets/18496868/25092822/f12a442c-23c1-11e7-9fc9-950f71d833ce.png) | [Console](https://cloud.githubusercontent.com/assets/18496868/25092824/f254f7ca-23c1-11e7-9d8d-a03b4ffdbdc0.png) (Darker background unrelated)
<blockquote class="imgur-embed-pub" lang="en" data-id="a/cohbg"><a href="//imgur.com/a/cohbg">[Gallery] New 3DS XL – Pokémon X</a></blockquote>

**[Pokémon Alpha Saphire]**
![Pokémon Alpha Saphire](https://cloud.githubusercontent.com/assets/18496868/25071054/90528600-22e0-11e7-8969-6e4517a5d1f3.png)
Source: [Before](https://cloud.githubusercontent.com/assets/18496868/25092409/1ea4041c-23c0-11e7-90b8-e70b8ec12a16.png) | [After](https://cloud.githubusercontent.com/assets/18496868/25092411/206a621e-23c0-11e7-818a-b19531583f9d.png) | [Console](https://cloud.githubusercontent.com/assets/18496868/25092414/22e5a15c-23c0-11e7-96ae-8c845e2aa3c6.png) (Bubble effect unrelated)
`//Gallery of images to be added later`

**[Pokémon Sun & Moon]**
![Pokémon Sun](https://cloud.githubusercontent.com/assets/18496868/25071568/73fe5dc8-22ed-11e7-8fbc-4496d156e670.png)
Source: [Before](https://cloud.githubusercontent.com/assets/18496868/25093083/30291508-23c3-11e7-8321-1e79b3c54c17.png) | [After](https://cloud.githubusercontent.com/assets/18496868/25093086/313371aa-23c3-11e7-8be4-15f80cf83f91.png) | [Console](https://cloud.githubusercontent.com/assets/18496868/25093088/325b3fae-23c3-11e7-8dc7-db69c49ff515.png)
<blockquote class="imgur-embed-pub" lang="en" data-id="a/fMNDB"><a href="//imgur.com/a/fMNDB">[Gallery] New 3DS XL – Pokémon Sun</a></blockquote>

___________________________________________________________________________________________________________
**OS:** _Windows 10 Pro Insider Preview build 15025 (codename Redstone 2)_
**Processor:** _Intel® Core™2 Duo CPU E7500  @ 2.93GHz, 2926 Mhz, 2 Core(s), 2 Logical Processor(s) [Overclocked to 3.7 GHz]_
**GPU:** _nVidia GT 610 2GB DDR3 (Asus)_
**Driver:** _Version 376.53_
**OpenGL:** _Version 4.5_

**Comment by JayFoxRox** [comment]
Can we get some reference screenshots from hardware please?
We should test this with MESA SW rendering etc. too. Maybe this is due to some texture filtering improvements in the host graphics driver?

We should also have a look at the LUTs used by Pokemon and how we treat them.

**Comment by Dragios** [comment]
But I can't really screenshot from my hardware, I can only capture images from my camera. How would that be?

**Comment by Saphiresurf** [comment]
Reference screenshots made on hardware (New 3DS XL) for Pokemon Alpha Sapphire. I'll add reference shots for X/Y and Sun/Moon as pictured (if I'm able to, the timing on some of these screenshots is a little hard to catch, but we'll see) sometime when I get the time to.

**Pokemon Alpha Sapphire**
![top_0008](https://cloud.githubusercontent.com/assets/272940/24641794/6bf2db9e-18b7-11e7-8e52-6ac17b88d137.png)
![bot_0008](https://cloud.githubusercontent.com/assets/272940/24641796/6e0010e6-18b7-11e7-9a5b-770c857eb165.png)

**Comment by Dragios** [comment]
I have added a gallery of images for Pokémon X and Sun for comparison. Most are pixel perfect accurate in Pokémon X (except for battle scene) but not in Pokemon Sun due to the character always in motion.

**Comment by wwylele** [comment]
Are all these fixed in current master?

**Comment by Dragios** [comment]
All fixed in #2792
