### ISSUE TITLE
Games that broke after removing priority boost hack

### ISSUE THREAD

**Issue by jroweboy** [citra-emu/citra#2554]
Original title: Digimon World Re:Digitize Decode stuck loading regression

Forum user Lord Vulkan bisected this issue to this commit. https://github.com/citra-emu/citra/pull/2408

To reproduce this issue load the save file, turn to the left and walk into the town to trigger the action.

Save file: https://mega.nz/#!mQRgCJRT!Ht_WmqUg87ByCZVd3QpXnDZyEsHD8Ehs10FiXxTHl2U

When you enter that section of the map, the game never stops loading.

(Reported on the forums here: https://community.citra-emu.org/t/digimon-world-re-digitize-decode-stuck-loading/491)

**Comment by wwylele** [comment]
Probably related: #2526 
Could anyone get a screenshot of the wait tree at the hang? (like I did in #2526)

**Comment by LordVulkan** [comment]
How can I see the wait tree on linux? All debugging windows seem to be empty

**Comment by TTFH** [comment]
@LordVulkan Click in "View"->"Debugging"->"Wait Tree" and then in "Emulation"->"Pause"

**Comment by LordVulkan** [comment]
Here it is.

![image](https://cloud.githubusercontent.com/assets/562386/22848993/173bf496-eff9-11e6-9d4e-2a88d0c65c15.png)

**Comment by jroweboy** [comment]
A few more games that broke from removing the priority boost were found on reddit today https://www.reddit.com/r/Citra/comments/63tebw/sonic_boom_titles_on_the_latest_nightly_b292395/

I changed the title of the issue to reflect the change that introduced these regressions.

Sonic Boom: Fire and Ice and Sonic Boom: Shattered Crystals both seem to be affected by this.

**Comment by FearlessTobi** [comment]
Please retest on latest Nightly.

**Comment by vvanelslande** [comment]
I'm trying to download the save file
![image](https://user-images.githubusercontent.com/62673824/77853040-73882200-71a7-11ea-9a84-0fbdf5a029e1.png)

**Comment by Dragios** [comment]
This should be fix with #4913 ? I think this can be close.
