### ISSUE TITLE
The Legend of Zelda: Ocarina of Time - Can't play the Ocarina!!!

### ISSUE THREAD

**Issue by MasterEv** [citra-emu/citra#2556]
Well, I'm sorry if I mess up with this post, I'm not American... 

The emulator runs Zelda Smoothly, but the problem is when I try to play the ocarina. The game simply freezes, and I have to restart the emulator to it go back to normal...

The Citra Version is Nightly Build 2889372

**Comment by Kumoashi** [comment]
I just tried it on Citra Nightly da6a40e and everything worked fine on the US version of Ocarina Of Time. No freezing while using either ocarina (Fairy or Time), and being kid Link didn't mater either. Also tried with buttons and touchscreen control, as well as multiple songs, but could not get it to freeze.

I've never seen it freeze on any of the older versions of Citra either.

Try the lastest Nightly build and if you still have problems with this, be sure to post what Citra shows in the log window, what version of the game you're having the problem with, and some basic information about your computer.

Without any extra information, it won't be possible to check for the problem that your having.

**Comment by SigmaVirus** [comment]
I'm experiencing the same as @Kumoashi, playing the ocarina works great in any version of Citra.
I'm on the European version playing on bleeding-edge-190.

There must be something bad with either your game or save file somehow.

**Comment by PPLToast** [comment]
This still happens to me on latest bleeding edge (7311b1c) as of now. From what I've tested, the freeze happens if you boot up OoT3D or some other game, close it and then boot up OoT3D and try to use the Ocarina. To avoid it, close citra completely and just boot OoT3D straight up. Not sure if its some Intel thing, but eh...

Citra doesn't give any error for it, but maybe the verbosity is too low or something?

**Comment by SigmaVirus** [comment]
That makes a whole lot more sense actually and explains why it never happened to me in the first place because I always close the game and exit Citra before launching a new game.

**Comment by yuriks** [comment]
Sounds like a re-initialization bug (where we forget to reset something when closing a game.) Can someone try to bisect it?

**Comment by TTFH** [comment]
The game simply freezes but emulation stay running, it don't show any error or crash.
![oot-freeze](https://cloud.githubusercontent.com/assets/23284861/23026928/90264478-f441-11e6-8ab9-622f5ccb40a0.png)

**Comment by TTFH** [comment]
It's happend because HID:EventAccelerometer it's not resumed.
Before #2442 work fine, the exact commit that cause the freeze is:
 [3c333c53f1f2c8daa3eab8c83d403d0d23682747](https://github.com/citra-emu/citra/pull/2442/commits/3c333c53f1f2c8daa3eab8c83d403d0d23682747)

**Comment by wwylele** [comment]
@TTFH does #2574 fix it?

**Comment by TTFH** [comment]
Yes, that fix it.
