### ISSUE TITLE
Pokemon X not working on my Mac of nightly build

### ISSUE THREAD

**Issue by VHSenpai** [citra-emu/citra#2559]
I recently got into Citra and legally got a copy of Pokemon X (my friend allowed me to borrow it) through Homebrew and everything and then I downloaded the nightly build of citra and loaded but unfortunately I saw nothing but two black screens and on the terminal read ----> critical error and debug or something like that I searched it up and it seems many people have encountered the same problem as I. I wish for you guys to fix this problem so I can enjoy the game XDD

**Comment by wwylele** [comment]
Mostly like missing sysem archives. Please refer to this guide: https://github.com/citra-emu/citra/wiki/Dumping-System-Archives-and-the-Shared-Fonts-from-a-3DS-Console

Note that Pokemon X is still not playable even if you get those files.

Please use [our forums](https://community.citra-emu.org/) for support.
