### ISSUE TITLE
Super Mario 3D Land - Loading Save Softlocks Regression

### ISSUE THREAD

**Issue by Schplee** [citra-emu/citra#2560]
When the player selects a save file to load/create, the game soft locks indefinitely in BE-196, 194, and 192.
BE-190 works normally, and the only difference between the two builds is #2533 (apart from changes to #2497 which I highly doubt cause this regression). #2533 isn't merged with BE-190.

Here's a screenshot of what it looks like (the Applet messages repeat):

![mgcx3pc](https://cloud.githubusercontent.com/assets/24275329/22853368/aeeb5560-f022-11e6-8518-b0ae82696046.png)

**Comment by wwylele** [comment]
You may want to comment this under that PR. We usually open issues only for master branch problems

**Comment by Schplee** [comment]
Yes, you're right. Just talked to Yuriks about it.

**Comment by yuriks** [comment]
Yeah, my fault, I thought that PR had been merged to master already.
