### ISSUE TITLE
Fire Emblem Fates - Special Edition NA ver freezes after or during certain cutscenes

### ISSUE THREAD

**Issue by xMysticSong** [citra-emu/citra#2565]
Not sure how to write/report this properly...

Thing is, in Fire Emblem Fates Special Edition, whenever the "invite guest" scene happens (Where the removed "skinship" mini-game was), the game goes on, but the music will stop playing and no voice files are played, even though they should. Any other event that comes after it (i. e. battle start, support scenes, sometimes even shops) will freeze either at the end or right in the beginning. 
The class change scenes have the same effect: game goes on normally, but sounds are no more. Certain scenes after it freeze.

The log indicates that several .bak files from AppData cannot be found when this happens... Not sure if that's the ROM's fault or not, but considering it's something from the AppData directory it might be an issue with Citra.
Another thing the log mentions is:
"Service.DSP <Error> core\hle\service\dsp_dsp.cpp:Service: :DSP_DSP: :WriteProcessPipe:290: IPC static buffer descriptor failed validation (0x80402) . pipe=3, size=0x20, buffer=0x31D2C630"
Have absolutely no idea what this means, sorry.

Most of the freezes can be avoided by saving and resetting the emulation... However one particular scene has an immediate freeze that has no workarounds: the confession scenes.

The specs of my gaming laptop are:
2 Nvidia GeForce GT 755m, 2GB VRAM
4th Gen intel i7-4700MQ @2.40 GHz
16 GB RAM

According to the FAQ I should be able to run Citra just fine (Just that the performance sucks).

Not sure if this has been reported before. In any case it'll be great if this can be looked into or any kind of answer (Probably that my, back then expensive, laptop sucks and I should never buy one again)... In the meantime I'll just play on my 3DS.

Thank you in advance. And thank you for making Citra and working as hard as you do.

**Comment by wwylele** [comment]
> Service.DSP core\hle\service\dsp_dsp.cpp:Service: :DSP_DSP: :WriteProcessPipe:290: IPC static buffer descriptor failed validation (0x80402) . pipe=3, size=0x20, buffer=0x31D2C630

From this log I believe that you are running on the bleeding edge versions. Note that we do not provide support on the bleeding edge build, nor accept issue for it. Please retest the game on the nightly build. If the issue still presents, please provide _the full log_ here. If it is only in the bleeding edge build, probably you can report it here: https://github.com/citra-emu/citra-bleeding-edge/pull/19

Close this for now until more information is provided
