### ISSUE TITLE
Significant slowdown on recent versions of Citra (a1393dc)

### ISSUE THREAD

**Issue by conlei** [citra-emu/citra#2567]
Version: HEAD-a1393dc
System Specs: Ubuntu GNOME 16.10, Intel i7-5820K, 16GB DDR4, GTX 1060 6GB (with nvidia-378 driver)

I have my Home Folder and shared font dumped and working properly, and have attempted regenerating the settings files to no effect. From commit a1393dc onwards, I have been experiencing massive performance decreases on all games; Games that would run at or near full speed before (Such as OoT3D now run around 1 fps, and some games that previously ran will now hang on a black screen (Such as MK8).

Attached are two log files from the commit in which the issue started to occur (a1393dc) and the commit before that in which the issue does not occur (d8af401). With d8af401, OoT3D was booted, allowed to load to the title screen, and closed. I tried to do the same thing with a1393dc but this resulted in a 109MB large logfile, so I just ran that one for 10 seconds instead.
[a1393dc.txt](https://github.com/citra-emu/citra/files/773082/a1393dc.txt)
[d8af401.txt](https://github.com/citra-emu/citra/files/773080/d8af401.txt)

**Comment by MoochMcGee** [comment]
That PR shouldn't have affected performance much at all. I'm thinking this
is something else.

**Comment by yuriks** [comment]
Working log:
```
[   1.085344] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:GetSemaphoreEventHandle:167: (STUBBED) called
[   1.087046] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphoreMask:446: (STUBBED) called mask=0x00002000
[   1.089853] Audio.DSP <Info> audio_core/hle/pipe.cpp:PipeWrite:134: Application has requested initialization of DSP hardware
```

Broken log:
```
[   1.103019] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:GetSemaphoreEventHandle:167: (STUBBED) called
[   1.105125] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphoreMask:446: (STUBBED) called mask=0x00002000
[   1.108605] Service.DSP <Error> core/hle/service/dsp_dsp.cpp:WriteProcessPipe:290: IPC static buffer descriptor failed validation (0x10402). pipe=2, size=0x4, buffer=0x0FFFFBD4
```

So, it's tangentially related to the commit, but given that that commit did not move DSP::DSP over to the new helper it's probably some kind of latent bug. I can't reproduce the issue here but I'll take a look and see if I find anything.

**Comment by yuriks** [comment]
@conlei Can you upload the `dsp_dsp.o` file generated from the compilation? Also, what compile are you using?

**Comment by conlei** [comment]
@yuriks I was using the precompiled release from https://github.com/citra-emu/citra-nightly/releases/tag/nightly-48, but I have now have cloned and compiled a1393dc using the instructions from the wiki, with the same results. The only file I found in my build that matches what you're looking for is dsp_dsp.cpp.o, which I have attached (GitHub won't let me attach it directly so I've zipped it)
[dsp_dsp.cpp.zip](https://github.com/citra-emu/citra/files/773155/dsp_dsp.cpp.zip)
.

**Comment by yuriks** [comment]
I think I fixed the issue. Try compiling with #2568.

**Comment by conlei** [comment]
@yuriks This fixed the issue for me.

**Comment by yuriks** [comment]
@conlei Great! I'll merge it soon. Btw, while discussing this on IRC we noticed that our nightly builds are actually being built in debug mode. You'll probably get much better results if you build Citra yourself while passing `-DCMAKE_BUILD_TYPE=Release` to CMake. (We plan on fixing this in the nightly builds too.)

**Comment by conlei** [comment]
@yuriks I'll be sure to do that from now on. Thanks!
