### ISSUE TITLE
pokemon sun/moon texture over lapping caused by two specific pokemon (pokemon refresh)

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#2575]
so testing around with my "totally not cheated legit team".

I've run into a very odd issue, it is related to two specific pokemon , ash's pikachu and yvelta 

to put it into words yvelta will have a duplicate glitchy eyes in the refresher, the only condition for that to occur is to visit ash's pikachu in the refresher at least once, here is a video explaining it if you are confused

https://vid.me/5qdG

i tested a couple of times to check if any other condition is producing the issue, so far i've run into none, testing with a normal pikachu did not produce the issue either

tested on both latest nightly and bleeding

**Comment by wwylele** [comment]
Please use the original game without any cheats to take screenshots and videos. I say this because I see no outline is rendered, which implies that the game is modified. Please avoid this to reduce false positives

**Comment by RavenHome1** [comment]
@wwylele way ahead of you on that one, i already tested with an unmodified game and the same issue happens, i used a modified copy for recording , other wise the video would run at horrible frame

**Comment by wwylele** [comment]
@RavenHome1 still, please upload the unmodified one, even if it runs at horrible frame.

**Comment by RavenHome1** [comment]
@wwylele so my recording software refused to start recording at low frame but can these two pictures provide enough details?. the steps to produce are the same


![capture](https://cloud.githubusercontent.com/assets/12820322/23040535/54d81816-f49a-11e6-877e-c075a1c93149.PNG)


![capture2](https://cloud.githubusercontent.com/assets/12820322/23040540/585240a2-f49a-11e6-9447-2f4ad9c44541.PNG)

**Comment by wwylele** [comment]
Does #2686 fix this?

**Comment by RavenHome1** [comment]
i don't know how to compile and add any PR to citra so if you can provide me with a compiled version with the PR i will gladly test it for you ^^,

**Comment by jroweboy** [comment]
@RavenHome1 if you use windows, there is a pre built binary you can download from appveyor https://ci.appveyor.com/project/bunnei/citra/build/1.0.5353/artifacts (but we don't recommend doing this for untrusted pull requests and much prefer people to build on their own until we get our own trusted architecture)

**Comment by RavenHome1** [comment]
@jroweboy oh. thanks for the heads up i will test it

**Comment by RavenHome1** [comment]
nope still derpy as ever

![capture](https://cloud.githubusercontent.com/assets/12820322/25681684/e87c8422-305d-11e7-9f95-6f79a437396d.PNG)

**Comment by Dragios** [comment]
Is this still an issue now?

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update

**Comment by SleepingSnakezzz** [comment]
Just tested this out, cannot reproduce. Assumed fixed.
