### ISSUE TITLE
Latest citra bleeding edge stopped working

### ISSUE THREAD

**Issue by paulconrad12345** [citra-emu/citra#2578]

**Comment by Barlowe11** [comment]
Today after updating, Bleeding Edge crashes on launch.

**Comment by RavenHome1** [comment]
yup i can confirm that, it crashes at startup , ping @jroweboy

**Comment by wwylele** [comment]
This issue tracker is only for nightly builds.

**Comment by jroweboy** [comment]
FYI this is the sort of thing that should be reported on the forums. I've tracked it down to be an issue with the Crypto PR (a bug in cryptopp library it seems), so its removed for the next build. I'll be working on figuring out what is exactly wrong with it later

**Comment by mailwl** [comment]
@jroweboy, "_No description provided._" don't look as right issue, anyway.
all day i wait someone post log... nobody did...
