### ISSUE TITLE
SD card "not enough space" error

### ISSUE THREAD

**Issue by bag3318** [citra-emu/citra#2583]
So I am trying to dump a .cia file from my Pokemon X cartridge and it says I don't have enough space on my SD card, even though I clearly do. I checked the amount of space on my 3ds and on the decrypt9 page (on my 3ds) and the numbers show correctly. Please help.

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

**Comment by bag3318** [comment]
so that is the appropriate place to post this issue?

**Comment by mailwl** [comment]
https://community.citra-emu.org/
