### ISSUE TITLE
Evil Citra

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#2584]
I think, Citra can damage host, for example, the "FragDisk" tryes to defragment my mac harddrive.
i don't try, but what if some app will try to open ../../../etc/passwd or something?
we have to proper sandbox it

**Comment by jfmherokiller** [comment]
but this sounds like a special case because someone would need to know the user runs the emulator and convince them to run the homebrew

**Comment by wwylele** [comment]
We already "sandboxed" out file system: https://github.com/citra-emu/citra/blob/master/src/core/file_sys/path_parser.cpp#L42. The cases you mentioned will just returns an error

**Comment by mailwl** [comment]
@wwylele , may you check FragDisk? i think, it's some kind standart N. tool

**Comment by jfmherokiller** [comment]
i tried it and it doesn't seem to cause issues for me

**Comment by wwylele** [comment]
@mailwl I have no idea which "FragDisk" you are talking about is. And please stop speaking secret words that others can't clearly understand.

And I am closing this anyway because it doesn't clearly file any valid issue (what does that title mean?!)
