### ISSUE TITLE
No name is accepted in Shin Megami Tensei: Devil Survivor 2 Record Breaker

### ISSUE THREAD

**Issue by Vaientus** [citra-emu/citra#2586]
When trying to submit a name for the protagonist, the game simply says it cannot be used. I've tried several names, but to no avail.

Not sure if it's relevant to the problem, but I looked for the file called "ContinueSave.bin" myself (since I thought it might be similar to the situation mentioned in the FAQ), but it wasn't there.

I'm using Citra version 7628f3a

![skjermbilde 327](https://cloud.githubusercontent.com/assets/25888052/23107606/5856a652-f700-11e6-8802-7e275fd62659.png)
![skjermbilde 325](https://cloud.githubusercontent.com/assets/25888052/23107607/58598610-f700-11e6-9157-a9a7a292aba7.png)
![skjermbilde 326](https://cloud.githubusercontent.com/assets/25888052/23107605/58562f56-f700-11e6-9e04-67175b7d6b72.png)

**Comment by wwylele** [comment]
please [dump system archives](https://github.com/citra-emu/citra/wiki/Dumping-System-Archives-and-the-Shared-Fonts-from-a-3DS-Console). The game is trying to open the bad word list. There are already some success reports after dumping the archive. Close as this is not an issue in citra
