### ISSUE TITLE
error: use of undeclared identifier 'timer_handle'

### ISSUE THREAD

**Issue by B3n30** [citra-emu/citra#2596]
I tried to build the recent master on Mac but it seems that with the merge of #2421 a small error occurred.

citra/src/core/hle/kernel/timer.cpp:81:52: error: use of undeclared identifier 'timer_handle'
    LOG_TRACE(Kernel, "Timer %08" PRIx64 " fired", timer_handle);
                                                   ^
1 error generated.

** BUILD FAILED **

It's easy to fix, by either changing the log entry or hand over timer_handle to timer::signal.

I'm no active programmer for citra so i didn't fix it my self, but if you wish to i will make a pull request for it.

**Comment by Dragios** [comment]
Do it. Make a PR.

**Comment by mailwl** [comment]
again error which occur only in debug build

**Comment by wwylele** [comment]
Fixed by #2600
