### ISSUE TITLE
Paper Mario Sticker Star Boot on Black screen and freeze

### ISSUE THREAD

**Issue by zaranrapu** [citra-emu/citra#2597]
Used nightly-81 Citra.
Can not go to the title screen!
Error log
``[   2.745894] HW.GPU <Critical> core\hw\gpu.cpp:GPU::MemoryFill:100 invalid end address 0x10B00000
``
![snapcrab_noname_2017-2-26_7-54-3_no-00](https://cloud.githubusercontent.com/assets/11900318/23335458/301163a0-fbf9-11e6-978f-8b5b1efc2fd0.png)

Old Bulid Citra (9/3/2016) works.
![snapcrab_noname_2017-2-26_8-1-1_no-00](https://cloud.githubusercontent.com/assets/11900318/23335480/cf47015a-fbf9-11e6-9ca8-9f07ec27df82.png)

win10 x64
i7 6700
GTX 1080

**Comment by wwylele** [comment]
I tested on the current master  f2ae2a7, and t still boots fine. The black screen when booting is sort of long but not it doesn't freeze. Please make sure it was not you just didn't wait for enough time

**Comment by zaranrapu** [comment]
But you can not go to the title screen.
The same thing as being frozen.

**Comment by wwylele** [comment]
@zaranrapu Yes I can. And If you still believe you find an issue, please provide a _full_ log

**Comment by zaranrapu** [comment]
Here.
Bleeding Edge Build 228 Error log.
http://pastebin.com/NsVvQa6c

**Comment by wwylele** [comment]
Did you dumped your game using Braindump or Decrypt9

**Comment by zaranrapu** [comment]
Used Braindump.

**Comment by wwylele** [comment]
@zaranrapu It is known that Braindump can make bad dump, and I highly suspect this is one of the cases. Could you try Decrypt9? (Also for the other issue you made)

**Comment by zaranrapu** [comment]
Decrypt9 dump, works!
![snapcrab_noname_2017-2-27_22-35-34_no-00](https://cloud.githubusercontent.com/assets/11900318/23363337/888bd912-fd3d-11e6-9958-5a2685cfd353.png)

But, it is heavier and sad than the old version.(old Citra MAX 90fps > 30～40fps)
![snapcrab_noname_2017-2-27_22-44-35_no-00](https://cloud.githubusercontent.com/assets/11900318/23363525/64da9782-fd3e-11e6-81a9-c1b14903cf08.png)

Other reported software was dumped with Decrypt 9, so it does not matter.
