### ISSUE TITLE
Donkey Kong Country Returns 3D Boot on Black screen and freeze

### ISSUE THREAD

**Issue by zaranrapu** [citra-emu/citra#2599]
Used nightly-81 Citra.
Not Error...
![snapcrab_noname_2017-2-26_8-20-8_no-00](https://cloud.githubusercontent.com/assets/11900318/23335637/a5674a18-fbfc-11e6-83f5-8f20e147411e.png)
win10 x64
i7 6700
GTX 1080

Bleeding Edge Build 228 Error log.
`[   9.636248] Kernel.SVC <Warning> core\hle\svc.cpp:CreateThread:563: Newly created thread is allowed to be run in the SysCore, unimplemented.`

Old Citra Bulid (12/1/2016) works.
(However, huge noise flows through the sound all the time.)
![snapcrab_noname_2017-2-26_8-25-11_no-00](https://cloud.githubusercontent.com/assets/11900318/23335670/7653fb44-fbfd-11e6-8ac9-7913d38117d2.png)

**Comment by FernandoS27** [comment]
This is corelated to #2411

**Comment by benderscruffy** [comment]
still happens in the latest nightly and canary
![dk](https://user-images.githubusercontent.com/2696404/32989802-5e89098c-cd58-11e7-88e3-6fb49df150b3.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1485459/log.zip)

**Comment by benderscruffy** [comment]
still happens in the lastest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2722733/citra_log.zip)

**Comment by FearlessTobi** [comment]
Fixed by https://github.com/citra-emu/citra/pull/4913.
