### ISSUE TITLE
Super Mario 3D Land stuck in Toad Room after start video

### ISSUE THREAD

**Issue by Streedy21** [citra-emu/citra#2601]
I used the latest nightly build and the master version of citra from 08-09-2026:

Super Mario 3D Land does not react when pressing the start button icon with mouse, keyboard start button does not react (M), when I do Mario stays in the room with the toad figures and the background music does not play anymore, but he can move. 

Unfortunately console does not express anything useful here. I have used a Win10 setup with Geforce 750 GTX Ti and a MacBook Air with Intel HD Graphics 6000 1536 MB.

**Comment by Leo626** [comment]
You need to dump the [shared fonts](https://github.com/citra-emu/citra/wiki/Dumping-System-Archives-and-the-Shared-Fonts-from-a-3DS-Console) from your 3DS. This is not really an issue.
