### ISSUE TITLE
Always Use Same RAM Offset For 3DS RAM

### ISSUE THREAD

**Issue by xnamkcor** [citra-emu/citra#2602]
bleeding-edge-228
Build number 228

Is it possible to make it so when I start up a game again the 3DS RAM inside Citra's RAM is always in the same place? Recalculating all my addresses every time I crash or start a new session of the emulation is inconvenient.

**Comment by Subv** [comment]
We can't guarantee that Citra will always get loaded at the same base address because of ASLR (Address Space Layout Randomization). However, the 3DS's RAM will always be located at the same offset from the base address that the operating system assigned your Citra instance.
