### ISSUE TITLE
Use Same RAM Range When Stopping Then Starting Emulation

### ISSUE THREAD

**Issue by xnamkcor** [citra-emu/citra#2604]
bleeding-edge-228
Build number 228

If I "Stop" emulation, then open the same game, the RAM addresses used by the game changes. Is there a way to have Citra reserve a section of RAM to use until you close it so I can Stop and start emulation without having to refind the RAM offset?

**Comment by yuriks** [comment]
No, we make no effort to have the RAM base be stable (and it's unfeasible to do so since it's dynamically allocated.)
