### ISSUE TITLE
Tekken 3D: Prime Edition - Unable to boot

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#2609]
Tested at 	Nightly Build - ad4097e

You can see only a black screen...

[Trace log](http://pasted.co/6f6d2e87)

maybe related to https://github.com/citra-emu/citra/issues/2411

**Comment by Xcedf** [comment]
Investigated this issue
game was broken by 1c792389
reverting it allows to try the game on newest builds

**Comment by benderscruffy** [comment]
still happens in the lastest nightly
![tekken](https://user-images.githubusercontent.com/2696404/33059290-a4ff0886-cece-11e7-818d-ec20a427cb80.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1490352/log.zip)

**Comment by benderscruffy** [comment]
nightly HEAD-a66e458
this goes ingame
![tekken](https://user-images.githubusercontent.com/2696404/34600350-f8b69fda-f231-11e7-9d54-eb6fd7bb3f12.PNG)
this can be closed
