### ISSUE TITLE
Missings lots of buildings + Crash

### ISSUE THREAD

**Issue by Sprik07** [citra-emu/citra#2610]
Here are the characteristics of my computer : 
- GPU : GTX 760 OC 2GB
- CPU : AMD FX-8320E
- RAM : 16GB
- MotherBoard : MSI 970-A Krait

Information : 
- The game : Animal Crossing : New Leaf
- Version of citra used : Citra Bleeding Edge | HEAD-f239770

Problem : 
Buildings are missing and errors have appeared in the console.
Spam in the console : 
- HW.Memory <Error> core\memory.cpp:Read:186: unmapped Read8 @ 0x00002A18
- HW.Memory <Error> core\memory.cpp:Write:226: unmapped Write8 @ 0x00000000 @ 0x00002A18

**Comment by wwylele** [comment]
Duplicated of #1105
