### ISSUE TITLE
Pokemon Sun Moon (Use The +Control) issue!!

### ISSUE THREAD

**Issue by Shinoe** [citra-emu/citra#2613]
i can hear the game sounds but nothing appears only this 
https://s3.postimg.org/a2zz62tlf/image.png

when i try to press buttons i can hear the sound effects of it 
tried many Citra buildings but its all the same result :( 
downloaded both Sun and Moon and its also the same :(

**Comment by RavenHome1** [comment]
downloaded both sun and moon.

sorry we don't provide support for pirated games.
