### ISSUE TITLE
Pokemon Sun + Moon Warning Error

### ISSUE THREAD

**Issue by qazsazsaz** [citra-emu/citra#2616]
Hey guys,

This is my first time using Citra, and I keep getting a Service.Y2R <Warning> core\hle\service\y2r_u.cpp:SetTransferEndInterrupt:246: (STUBBED) called
![image](https://cloud.githubusercontent.com/assets/26238233/23638471/df006516-02af-11e7-8577-75b1eaf3e6e9.png)
I think it slows down my FPS.  I get this error as the game is loading the homescreen.

Then, when I start actually playing, I keep getting the follow:
![image](https://cloud.githubusercontent.com/assets/26238233/23638499/02dada8e-02b0-11e7-9e46-dbf059e5cea5.png)

These errors severely hamper my FPS and make the game unplayable.  

I have the latest Bleeding Edge build

Can anyone help?

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Closed as Invalid.

P.S. theres a wiki article on how to change the logging level. If you need more help ask about it on the forums instead.
