### ISSUE TITLE
Mario & Luigi: Dream Team unmapped read after encountering inky piranha plant

### ISSUE THREAD

**Issue by zapkabosu** [citra-emu/citra#2617]
**Issue**: 
In Mario & Luigi: Dream Team, if inky piranha plant (a background enemy) appears in battle, after the battle ends, opening the menu or trying to save will freeze the game

**System Information**
* Operating System: win10
* CPU: i7 6700k
* GPU: gtx980
* Citra Version (found in titlebar): master-ad4097e7
* Game: Mario & Luigi: Dream Team
Log:
http://pastebin.com/pLZvgF3r

key events in the log:
at [33], successful attempt to switch from "FReal" to "Save"
at [39], switch back from "Save" to "FReal"
at [45], enter battle
at [106], inky piranha plant shows up in background
at [189], escape from battle, Service.MIC handles the disappearing of inky piranha plant, Service.LDR handles switch scene from "BNormal" to "FReal" (if I do not escape but instead kill inky piranha plant without ending the battle, the Service.MIC lines will show up in log as soon as it dies)
at [194] I attempted to save (attempted to switch from "FReal" to "Save"), but failed, followed by unstopping invalid reads (the 10th invalid read is at 0x00000000, subsequent reads at increment of 4)

**Comment by wwylele** [comment]
>[ 194.145802] Service.LDR core\hle\service\ldr_ro\ldr_ro.cpp:Service::LDR::LoadCRO:343: CRO original buffer is in invalid state

Interesting, our first real error coming from CRO. Could you [lower the log level](https://github.com/citra-emu/citra/wiki/Log-Filters) to `Debug` and produce a more detailed log? (Mainly want to see the params passed to `LoadCRO`.

Two possible issue here:
 - There are some wrong assumption to CRO which fails the validation
 - Some unimplemented/poorly stubbed services (say, MIC) pollute the memory, leading the game passing invalid params to `LoadCRO`

I have some question:
 - Does he issue only happen if you want to save right after encountering a inky piranha plant?
 - Is inky piranha plant the only enemy that uses MIC services (i.e. produces some MIC log) ?

**Comment by zapkabosu** [comment]
below is log from inky piranha plant appears to error in LoadCRO (debug log on LDR only):
http://pastebin.com/9dpniXxz

for reference, below is log of normal transition from "FReal" to "Save" and back:
http://pastebin.com/Ea9FzzmK

for your questions:
1.the issue happens no matter how long after the encounter, it happens in the first transition from "FReal" to anything (save scene, menu scene, shop scene, etc.), except for the battle scene, can still switch to and from battle scene without a problem
2.I tested on several background enemies and inky piranha plant is the only enemy I know that uses MIC services

**Comment by wwylele** [comment]
Thanks for the info! 

Here is what I noticed from the log:

CRO buffer seems often begin from `0x0801C000`. For example, the CRO in question, "save", loads with
>[  89.415316] Service.LDR <Debug> core\hle\service\ldr_ro\ldr_ro.cpp:Service::LDR::LoadCRO:301: called (old), **cro_buffer_ptr=0x0801C000**, cro_address=0x00730000, **cro_size=0x29000**, ...

On the other hand, right before MIC service is called, there is a shared memory creating:
>[  65.670687] Kernel.SVC <Warning> core\hle\svc.cpp:SVC::CreateMemoryBlock:948: called **addr=0x0801F000**

One can notice that the two memory spaces are overlapping. Though there is not a log indicating, I believe the game should have destroyed the shared memory and free the space for CRO use. But `LoadCRO` fails on checking the memory states, probably because we do something wrong when releasing the shared memory and restoring the memory state.

Just my little guess. Haven't looked into it.

**Comment by zapkabosu** [comment]
not sure how memory management works in citra, but UnmapSharedMem in core\hle\service\mic_u.cpp doesn't seem to do anything before returning success, is this intended?

static void UnmapSharedMem(Interface* self) {
    u32* cmd_buff = Kernel::GetCommandBuffer();

    cmd_buff[1] = RESULT_SUCCESS.raw; // No error
    LOG_WARNING(Service_MIC, "called");
}

**Comment by Subv** [comment]
@wwylele Just a friendly reminder that some parts of our Shared Memory implementation are incomplete (#1802)

**Comment by zapkabosu** [comment]
the issue can be avoided by rejecting call to CreateMemoryBlock at addr = 0x0801F000, I can kill the inky piranha plant and save now, although games requiring usage of microphone might still need to wait until shared memory is completely implemented

**Comment by wwylele** [comment]
Is this fixed in the latest nightly (Nightly-1111 and above)? If not could you upload a new log file from the latest version?

**Comment by Dragios** [comment]
Any update on this?

**Comment by benderscruffy** [comment]
Has this been fixed ???
Please update
