### ISSUE TITLE
Black screen in Intel HD Graphics 4600

### ISSUE THREAD

**Issue by Subv** [citra-emu/citra#262]
When running Citra using my Intel HD Graphics 4600, every loaded program will just display a black screen on top, and white screen at the bottom, even programs that are just supposed to show a pixel, they however work fine in every other aspect, they just don't show anything. This behavior doesn't happen when running Citra with my NVIDIA GTX 860m graphics card, and applications show graphics when using it.

I tested it with hwtests and several other homebrews of mine (https://github.com/Subv/3ds-homebrew) they all exhibit this behavior.

I ran glIntercept using both the HD 4600 and the GTX 860m in full debug mode, apparently the images are being correctly placed in the textures (the Images folder contains the images, and they appear to be fine), however they are never shown to the user in the frontend.

This happens with both the GFWL and Qt frontens.

Here are the glIntercept results of each card:

HD 4600: https://gist.github.com/Subv/24e737464a2507cc1783
GTX 860m: https://gist.github.com/Subv/bfdc9c7ae39d28f8dc0a

I noticed however that smealum's hbmenu somewhat works when using the HD 4600, the would-be bottom screen (the homebrew list) is displayed in the top screen of the Qt frontend, and the bottom screen remains white.

Image of hbmenu on HD 4600 http://i.imgur.com/QO3OJWD.png
Image of hbmenu on GTX 860m: http://i.imgur.com/1knEZHJ.png

Operating System: Windows 8.1 x64
Graphics Card: 
- Intel HD Graphics 4600 integrated into cpu Intel Core i7 4710MQ using Intel driver v10.18.10.3960
- Nvidia GTX 860m using driver GeForce Game Ready Driver v344.75

**Comment by prusswan** [comment]
I have HD4000.

**Comment by chinhodado** [comment]
I have HD3000

**Comment by darkf** [comment]
I have an HD 4000 as well.

**Comment by woody2014** [comment]
Could patch be added into next pr build please as I also have same problem

**Comment by Subv** [comment]
Still broken with driver version 10.18.14.4080

**Comment by yuriks** [comment]
I've reported this to an Intel engineer, and he said that the next driver version after 4080 will have this fixed. I'll close the issue once the driver is released and I'm able to test.

**Comment by woody2014** [comment]
New Drivers released fixed bug.

**Comment by Zaneo** [comment]
Is this confirmed fixed, can this be closed? Or is it open for reference?

**Comment by yuriks** [comment]
I'm waiting for some more confirmation from others, as I haven't had time to re-test this on an Intel GPU yet.

**Comment by Subv** [comment]
Can confirm, the newest Intel driver (4156) fixes the issue
