### ISSUE TITLE
Run Citra on XFCE 14.04

### ISSUE THREAD

**Issue by Bibster2169** [citra-emu/citra#2621]
I have all the directories but when I try to run citra from the xfce terminal it pops up with this:

(trusty)bibster@localhost:~/Downloads/citra-linux-20170306-eb43581$ chmod +x ./citra-qt
(trusty)bibster@localhost:~/Downloads/citra-linux-20170306-eb43581$ ./citra-qt
./citra-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./citra-qt)
./citra-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./citra-qt)
./citra-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./citra-qt)
./citra-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./citra-qt)
./citra-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./citra-qt)

I tried downloading the 'requirements' but they don't exist.

Can anyone help in some way?

**Comment by hcorion** [comment]
My best guess is that you're operating system is too old. Try building directly from the source, or upgrade to a newer version. It looks like you're running Ubuntu Trusty, would that be 14.04.5?

**Comment by Bibster2169** [comment]
That would be correct. Thanks for the advice!

**Comment by j-selby** [comment]
14.04... whew lad.

You will need to build from source, or better yet, get on the process of upgrading.

**Comment by MerryMage** [comment]
Build instructions for 14.04 are available on the Wiki: https://github.com/citra-emu/citra/wiki/Building-for-Ubuntu-14.04

Note that these may be out of date.

**Comment by lainz** [comment]
Hi, I'm running on Ubuntu 16.04 LTS so it's actually not an old version, and I got the same error messages plus SDL2 missing. Installed SDL2 and then I got this:

> /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found

**Comment by hcorion** [comment]
@lainz According to [this answer](https://askubuntu.com/a/582910) you should try: 
`sudo apt-get install libstdc++6`
if it's already installed do
```shell
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```

**Comment by lainz** [comment]
Hi @hcorion thanks, I did that but actually needed also this line to get it working.

> sudo add-apt-repository ppa:ubuntu-toolchain-r/test
