### ISSUE TITLE
Fire Emblem Fates: freeze upon opening a save

### ISSUE THREAD

**Issue by ThecanadianFish** [citra-emu/citra#2624]
After opening one save the FPS and speed both drop to zero however the code still continues to run but all that it shows is a black screen. This doesn't happen to every save in the game just one. I am using the nightly build and up until now it has worked fine but this is the second save this has happened to, one on birthright separate game and now on the special edition. The code continues to count up until citra is closed.
![screenshot 2](https://cloud.githubusercontent.com/assets/26353963/23828431/73b5a568-068e-11e7-8758-3d3f467ab3ab.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/26353963/23828434/7d8ecee8-068e-11e7-83a7-234d3e277464.png)

**Comment by mailwl** [comment]
you forgot to add save itself

**Comment by ThecanadianFish** [comment]
Its the fire emblem save, how would i post it

**Comment by mailwl** [comment]
maybe mega.nz, dropbox.com, some of sharing service, if you have account

**Comment by ThecanadianFish** [comment]
how would i isolate the save though, or should i post the whole game

**Comment by jroweboy** [comment]
@ThecanadianFish This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/ Open up an issue there and we'll be happy to help answer questions there. Lots of the developers are signed up to receive email updates on github, and asking for help here usually just ends up spamming everyone with emails and making people upset.

Closing this until more information is gathered on the forums

P.S: When you open the issue on the forums, please include the log and the save file that is causing this issue. You can get to the save file by right clicking on the game in the game click and choosing open save location. Do not send us your game rom or any other copyrighted materials. (Save files: OK; Games NOT OK)
