### ISSUE TITLE
Pokemon Sun just has a grey screen. Pls help.

### ISSUE THREAD

**Issue by harry5633** [citra-emu/citra#2627]
When i try to open pokemon sun everything is fine until the display pops up and then its all grey.
I can hear the music fine but the screen is just grey. What do I do?

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

**Comment by RavenHome1** [comment]
i know this is a closed issue but i have an important question. do you have an ATI gpu?
