### ISSUE TITLE
missing battle animation Pokemon ORAS

### ISSUE THREAD

**Issue by hess1301** [citra-emu/citra#2629]
Lately, the battle animation from Pokemon ORAS has been missing

For example Vulpix attacks with Ember and there is no flame

![citra_isssue_ember](https://cloud.githubusercontent.com/assets/26231810/24054395/4f4687da-0b3c-11e7-8a5f-f94d48a811a4.png)

tested on Bleeding Edge 239

**Comment by Hexagon12** [comment]
Please use the forums for support, GitHub is used for tracking bugs.
https://community.citra-emu.org/

If you want to get animations back, use Bleeding Edge 86 or lower.

**Comment by jroweboy** [comment]
This is a well known issue and is due to unimplemented geometry shaders. Closing this issue as its similar enough to https://github.com/citra-emu/citra/issues/2419
