### ISSUE TITLE
Hyrule Warriors Legends won't boot

### ISSUE THREAD

**Issue by CubertZ** [citra-emu/citra#2632]
whenever i run Hyrule Warriors Legends I get this error (spam): 
[  12.685189] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write32 0x00000000 @ 0x0001361C
[  12.690331] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write32 0x00000000 @ 0x00013624
[  12.698092] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write8 0x00000000 @ 0x00013628
[  12.698338] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write8 0x00000000 @ 0x00013629
[  12.698554] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write32 0x00000000 @ 0x0001362C
[  12.698763] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write32 0x00000000 @ 0x00013630
[  12.698971] HW.Memory <Error> core\memory.cpp:Memory::Read:186: unmapped Read32 @ 0x000135F8
[  12.699145] HW.Memory <Error> core\memory.cpp:Memory::Read:186: unmapped Read32 @ 0x000135F8
[  12.699311] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write32 0x00000000 @ 0x0001363C
[  12.704682] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write32 0x00000000 @ 0x00013640
[  12.704975] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write32 0x00000000 @ 0x00013648
[  12.705213] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write32 0x007ADB44 @ 0x00013638
[  12.705486] HW.Memory <Error> core\memory.cpp:Memory::Write:226: unmapped Write32 0x007ADB58 @ 0x00013644
Any solution ?.. I'm running zelda ocarina of time and majora's mask fine and wihout issues so its kinda weird
![screenshot 21](https://cloud.githubusercontent.com/assets/23615018/24084948/b6069236-0cf3-11e7-8f7d-fe4a778d3b28.png)

**Comment by SigmaVirus** [comment]
You may want to keep information about downloading games to yourself next time before opening an issue.
Downloading games is a crime and is not OK by any means and the team behind Citra don't condone piracy.

Don't expect much help here.

**Comment by CubertZ** [comment]
Oh I'm sry about that i'll keep that in mind next time thanks

**Comment by SigmaVirus** [comment]
We're not the ones you have too apologize to here, it's the companies that put their heart and soul into these games that you and many others steal from you have too apologize to.

You are more then welcome to file a proper issue if/when you have dumped your own games and there's plenty of tutorials around on how to do just that.

Good luck!
