### ISSUE TITLE
Mario & Luigi Paper Jam Crashes

### ISSUE THREAD

**Issue by syedraza1997** [citra-emu/citra#2635]

**Comment by syedraza1997** [comment]
When I try to run this game it crashes

**Comment by neobrain** [comment]
Simple solution: You can prevent the crash from happening by not running the game.

**Comment by syedraza1997** [comment]
But it runs and crashes at the title screen

**Comment by mailwl** [comment]
double issue. use search

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid
