### ISSUE TITLE
Error while compiling Citra

### ISSUE THREAD

**Issue by Bibster2169** [citra-emu/citra#2643]
I have all the libraries and followed all the instructions here on git-hub, but when I enter the command ~/cmake-3.5.1-Linux-x86_64/bin/cmake .. -DCMAKE_BUILD_TYPE=Release it says:
-- The C compiler identification is unknown
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/g++-5
-- Check for working C compiler: /usr/bin/g++-5 -- broken
CMake Error at /home/bibster/cmake-3.5.1-Linux-x86_64/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/g++-5" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /home/bibster/citra/build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_5e09b/fast"

  /usr/bin/make -f CMakeFiles/cmTC_5e09b.dir/build.make
  CMakeFiles/cmTC_5e09b.dir/build

  make[1]: Entering directory `/home/bibster/citra/build/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_5e09b.dir/testCCompiler.c.o

  /usr/bin/g++-5 -o CMakeFiles/cmTC_5e09b.dir/testCCompiler.c.o -c
  /home/bibster/citra/build/CMakeFiles/CMakeTmp/testCCompiler.c

  /home/bibster/citra/build/CMakeFiles/CMakeTmp/testCCompiler.c:2:3: error:
  #error "The CMAKE_C_COMPILER is set to a C++ compiler"

   # error "The CMAKE_C_COMPILER is set to a C++ compiler"
     ^

  make[1]: *** [CMakeFiles/cmTC_5e09b.dir/testCCompiler.c.o] Error 1

  make[1]: Leaving directory `/home/bibster/citra/build/CMakeFiles/CMakeTmp'

  make: *** [cmTC_5e09b/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:36 (project)

-- Configuring incomplete, errors occurred!
See also "/home/bibster/citra/build/CMakeFiles/CMakeOutput.log".
See also "/home/bibster/citra/build/CMakeFiles/CMakeError.log".

Can anyone please help? I've been trying to get Citra for so long and am almost there, I just need this fixed.

Much appreciated!

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Closed as Invalid

---

P.S: It looks like your system has some messed up paths. Its picking up gcc 4.8 and trying to call gcc5? Ask on the forums so all the devs don't get spammed with emails :)
