### ISSUE TITLE
A MISSING DLL FILE

### ISSUE THREAD

**Issue by nobeac** [citra-emu/citra#2652]
When trying to execute the program (WINDOWS is saying this is an unrecognized file and might be unsafe  by the way so I needed to click over ride on the screen, and it says it is missing a DLL file. 
Why not include that into the program to make it work? And where the heck would I even put the file when I myself get it? Hello? c

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://community.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid
