### ISSUE TITLE
Sonic Boom Shattered Crystals and Sonic Boom Fire & Ice regression

### ISSUE THREAD

**Issue by Sonikko** [citra-emu/citra#2654]
Both games stopped working on the Jan 6 nightly 78f2571 build, they were working on the Jan 5 654a508 build release.
As of now (latest nightly 04/04/2017 b292395) they're not fixed yet, Shattered Crystals just shows a black screen and Fire and Ice hangs on a black screen after the startup loading, just like on the Jan 6 build.
These are the errors shown:

**Sonic Boom Fire & Ice**

Kernel.SVC <Error> core\hle\svc.cpp:SVC::CreateThread:573: Newly created thread must run in the SysCore (Core1), unimplemented.

**Sonic Boom Shattered Crystals**

Kernel.SVC <Error> core\hle\svc.cpp:SVC::CreateThread:573: Newly created thread must run in the SysCore (Core1), unimplemented.

Specs:
Windows 10  x64
i5 6600
GTX970
8gb DDR4 2133
Running the latest video driver, Windows is up to date.

**Comment by wwylele** [comment]
Although the provided log entry looks like the critical one, it will still be better if you can provide a full log so that we can make sure there is no other stuff get involved in this issue.

**Comment by Sonikko** [comment]
**Sonic Boom Fire & Ice log**

[   0.000000] Frontend <Info> citra_qt\main.cpp:GMainWindow::BootGame:373: Citra starting...
[   0.427392] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:490: GL_VERSION: 3.3.0 NVIDIA 378.92
[   0.427405] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:491: GL_VENDOR: NVIDIA Corporation
[   0.427411] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:492: GL_RENDERER: GeForce GTX 970/PCIe/SSE2
[   1.429080] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::Load:340: Program ID: 0004000000161300
[   1.448323] Loader <Info> core\hle\kernel\process.cpp:Kernel::Process::ParseKernelCaps:99: ExHeader kernel version: 2.50
[   1.448990] Service.CFG <Info> core\hle\service\cfg\cfg.cpp:Service::CFG::SetPreferredRegionCode:599: Preferred region code set to 1
[   1.511971] Service.SRV <Warning> core\hle\service\srv.cpp:Service::SRV::RegisterClient:40: (STUBBED) called
[   1.672425] Service.SRV <Warning> core\hle\service\srv.cpp:Service::SRV::EnableNotification:64: (STUBBED) called
[   1.674134] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GetLockHandle:122: (STUBBED) called handle=0x00038009 applet_attributes=0x00000000
[   1.676286] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::SetScreenCapPostPermission:418: (STUBBED) screen_capture_post_permission=0
[   1.676717] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::OverrideDefaultDaemons:201: (STUBBED) default_daemon_bit_mask=0x0000000F 
[   1.676801] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::SuspendDaemons:87: (STUBBED) daemon_bit_mask=0x00000009 
[   1.677359] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Enable:130: (STUBBED) called attributes=0x00000000
[   1.678222] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GlanceParameter:249: called app_id=0x00000300, buffer_size=0x00001000
[   1.678839] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::NotifyToWait:104: (STUBBED) app_id=768
[   1.679616] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::ReceiveParameter:226: called app_id=0x00000300, buffer_size=0x00001000
[   1.680587] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:320: (STUBBED) called command=0x00000007, buffer1_size=0x00000004, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF38, buffer2_addr=0x0FFFFF04
[   1.680823] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:320: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF00, buffer2_addr=0x0FFFFF04
[   1.681225] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:320: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFFA0, buffer2_addr=0x0FFFFFA4
[   1.683987] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::SetAppCpuTimeLimit:334: (STUBBED) called cpu_percent=30, value=1
[   1.685167] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GetAppCpuTimeLimit:348: (STUBBED) called value=1
[   1.685635] Kernel.SVC <Error> core\hle\svc.cpp:SVC::CreateThread:573: Newly created thread must run in the SysCore (Core1), unimplemented.
[   1.686283] Service.FS <Warning> core\hle\service\fs\fs_user.cpp:Service::FS::InitializeWithSdkVersion:801: (STUBBED) called, version: 0x0B0400C8
[   1.720152] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::AcquireRight:692: called
[   1.720784] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::RegisterInterruptRelayQueue:386: called, flags=0x00000001
[   1.751500] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:95: unknown / unimplemented function 'SetInternalPriorities': port=gsp::Gpu, cmd_buff[1]=0x19, cmd_buff[2]=0x1A
[   2.884169] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:142: Firmware hash: 0x943f5565dbcf6767
[   2.884296] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:146: Structures hash: 0x93e48663943cad39
[   2.884301] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:150: (STUBBED) called size=0xC25C, prog_mask=0x505300FF, data_mask=0x000E00FF, buffer=0x0042C320
[   2.885210] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::RegisterInterruptEvents:241: Registered type=2, pipe=2, event_handle=0x000E802E
[   2.885402] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::GetSemaphoreEventHandle:167: (STUBBED) called
[   2.885584] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphoreMask:446: (STUBBED) called mask=0x00002000
[   2.885851] Audio.DSP <Info> audio_core\hle\pipe.cpp:DSP::HLE::PipeWrite:134: Application has requested initialization of DSP hardware
[   2.886051] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphore:264: (STUBBED) called
[   2.887029] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphore:264: (STUBBED) called
[   2.972526] Kernel.SVC <Error> core\hle\svc.cpp:SVC::CreateThread:573: Newly created thread must run in the SysCore (Core1), unimplemented.
[   3.077833] Kernel.SVC <Error> core\hle\svc.cpp:SVC::CreateThread:573: Newly created thread must run in the SysCore (Core1), unimplemented.
[   3.077880] Kernel.SVC <Error> core\hle\svc.cpp:SVC::CreateThread:573: Newly created thread must run in the SysCore (Core1), unimplemented.

**Sonic Boom Shattered Crystals log**

[   0.000000] Frontend <Info> citra_qt\main.cpp:GMainWindow::BootGame:373: Citra starting...
[   0.413776] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:490: GL_VERSION: 3.3.0 NVIDIA 378.92
[   0.413821] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:491: GL_VENDOR: NVIDIA Corporation
[   0.413832] Render.OpenGL <Info> video_core\renderer_opengl\renderer_opengl.cpp:RendererOpenGL::Init:492: GL_RENDERER: GeForce GTX 970/PCIe/SSE2
[   0.415139] Loader <Info> core\loader\ncch.cpp:Loader::AppLoader_NCCH::Load:340: Program ID: 0004000000127500
[   0.421069] Loader <Info> core\hle\kernel\process.cpp:Kernel::Process::ParseKernelCaps:99: ExHeader kernel version: 2.39
[   0.421374] Service.CFG <Info> core\hle\service\cfg\cfg.cpp:Service::CFG::SetPreferredRegionCode:599: Preferred region code set to 0
[   0.421384] Service.CFG <Warning> core\hle\service\cfg\cfg.cpp:Service::CFG::SetPreferredRegionCode:607: System language 1 does not fit the region. Adjusted to 0
[   0.481694] Service.SRV <Warning> core\hle\service\srv.cpp:Service::SRV::RegisterClient:40: (STUBBED) called
[   0.613748] Service.SRV <Warning> core\hle\service\srv.cpp:Service::SRV::EnableNotification:64: (STUBBED) called
[   0.615632] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GetLockHandle:122: (STUBBED) called handle=0x00038009 applet_attributes=0x00000000
[   0.617358] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::SetScreenCapPostPermission:418: (STUBBED) screen_capture_post_permission=0
[   0.617761] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::OverrideDefaultDaemons:201: (STUBBED) default_daemon_bit_mask=0x0000000F 
[   0.617836] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::SuspendDaemons:87: (STUBBED) daemon_bit_mask=0x00000009 
[   0.618369] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Enable:130: (STUBBED) called attributes=0x00000000
[   0.619184] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GlanceParameter:249: called app_id=0x00000300, buffer_size=0x00001000
[   0.620001] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::NotifyToWait:104: (STUBBED) app_id=768
[   0.620798] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::ReceiveParameter:226: called app_id=0x00000300, buffer_size=0x00001000
[   0.621829] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:320: (STUBBED) called command=0x00000007, buffer1_size=0x00000004, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF38, buffer2_addr=0x0FFFFF04
[   0.622045] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:320: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFF00, buffer2_addr=0x0FFFFF04
[   0.622546] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:320: (STUBBED) called command=0x00000004, buffer1_size=0x00000001, buffer2_size=0x00000001, buffer1_addr=0x0FFFFFA0, buffer2_addr=0x0FFFFFA4
[   0.625212] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::SetAppCpuTimeLimit:334: (STUBBED) called cpu_percent=30, value=1
[   0.626209] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::GetAppCpuTimeLimit:348: (STUBBED) called value=1
[   0.626613] Kernel.SVC <Error> core\hle\svc.cpp:SVC::CreateThread:573: Newly created thread must run in the SysCore (Core1), unimplemented.
[   0.627204] Service.FS <Warning> core\hle\service\fs\fs_user.cpp:Service::FS::InitializeWithSdkVersion:801: (STUBBED) called, version: 0x070101C8
[   0.659507] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::AcquireRight:692: called
[   0.660008] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::RegisterInterruptRelayQueue:386: called, flags=0x00000001
[   0.686894] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:95: unknown / unimplemented function 'SetInternalPriorities': port=gsp::Gpu, cmd_buff[1]=0x19, cmd_buff[2]=0x1A
[   1.596856] Kernel.SVC <Error> core\hle\svc.cpp:SVC::CreateThread:573: Newly created thread must run in the SysCore (Core1), unimplemented.
[   1.613384] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:142: Firmware hash: 0x348ac2f23aa20bca
[   1.613398] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:146: Structures hash: 0x93e48663943cad39
[   1.613403] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:150: (STUBBED) called size=0xC288, prog_mask=0x505300FF, data_mask=0x000F00FF, buffer=0x003A1204
[   1.613888] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::RegisterInterruptEvents:241: Registered type=2, pipe=2, event_handle=0x000F8030
[   1.614058] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::GetSemaphoreEventHandle:167: (STUBBED) called
[   1.614217] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphoreMask:446: (STUBBED) called mask=0x00002000
[   1.614456] Audio.DSP <Info> audio_core\hle\pipe.cpp:DSP::HLE::PipeWrite:134: Application has requested initialization of DSP hardware
[   1.614570] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphore:264: (STUBBED) called
[   1.615532] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphore:264: (STUBBED) called
[   1.704301] Kernel.SVC <Error> core\hle\svc.cpp:SVC::CreateThread:573: Newly created thread must run in the SysCore (Core1), unimplemented.

**Comment by shinespeciall** [comment]
#####Any new progress in this? I don't have enough time to test all the commits on the Jan 5 and build into nightly build, but only know it perhaps not the problem mentioned as "Newly created thread must run in the SysCore (Core1), unimplemented.". Because some runable games also will report this.

**Comment by MerryMage** [comment]
If anyone wants to investigate this: The 654a508 build corresponds to c18cb1b192d60499af3d68b244e86c8dd8f55200 in this repository.

**Comment by shinespeciall** [comment]
it seems there are more than one commit were build-in according to the nightly build that day.

**Comment by benderscruffy** [comment]
nightly HEAD-a66e458
still happens
[Debug log F&I.zip](https://github.com/citra-emu/citra/files/1605847/Debug.log.F.I.zip)
[Debug log SC.zip](https://github.com/citra-emu/citra/files/1605848/Debug.log.SC.zip)

**Comment by matiffeder** [comment]
Sonic Boom: Shattered Crystal stuck at black screen after few seconds launch the game. (2018/05/16)

My Specs:
Citra Canary - 6b84ed9
I5-6300HQ
GTX950M
Windows 10 1709
12 GB Ram
[citra_log.txt](https://github.com/citra-emu/citra/files/2008849/citra_log.txt)

**Comment by benderscruffy** [comment]
still happens in the latest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2722620/citra_log.zip)

**Comment by FearlessTobi** [comment]
Fixed by https://github.com/citra-emu/citra/pull/4913.

**Comment by benderscruffy** [comment]
can be closed
