### ISSUE TITLE
Mario Sports Superstars - Unimplemented ExitProcess()

### ISSUE THREAD

**Issue by Schplee** [citra-emu/citra#2660]
Like in #1663 the app calls for the unimplemented ExitProcess; however, this is the first time I've seen this error occur in a retail game. I've only seen this error occur in various homebrew apps and the homebrew launcher, like #1663 states.

Tested in Nightly `9007c48` and Bleeding Edge `9d90cd4`
However, the version shouldn't matter as this hasn't been implemented in any version previously (even tested with the Nightly build the day #1663 was posted).

Mario Sports Superstars immediately crashes after loading the ROM.

![citra-qt_2017-04-11_21-28-34](https://cloud.githubusercontent.com/assets/24275329/24937318/e1dd3844-1efd-11e7-85f9-e7777f799b13.png)

**[Full Log File](https://github.com/citra-emu/citra/files/915132/log.txt)**

**Comment by wwylele** [comment]
I think ExitProcess is not the issue itself. It is more like the game hits some assertion failure and decides to crash. Those ummapped reads/writes are suspicious.

**Comment by FearlessTobi** [comment]
This is an updated log: https://pastebin.com/0m43bbMB

**Comment by FearlessTobi** [comment]
Fixed by #4392.
