### ISSUE TITLE
steel diver light blue screen while booting

### ISSUE THREAD

**Issue by nathanhitch** [citra-emu/citra#2670]
when the game is starting up it gives me a light blue screen in the log while the screen is up it prints this text

[   1.862064] HW.GPU <Critical> video_core\shader\shader_jit_x64_compiler.cpp:Pica::Shader::JitShader::Compile_NextInstr:811: Unhandled instruction: 0x2b (0xac000000)

the hash is "HEAD-941a3dd"
[log.txt](https://github.com/citra-emu/citra/files/931527/log.txt)
![blue screen](https://cloud.githubusercontent.com/assets/19424968/25159992/78fb9398-24f2-11e7-841a-c3301e9abd93.PNG)

**Comment by Senjosei** [comment]
looks like because the game uses geometry shaders, it cant render properly (instruction 0x2a and 0x2b are for geometry shaders which isnt implemented yet)

**Comment by Pirater12** [comment]
How did you get steel driver to boot?For me it just fails after this:-
`[   0.793527] HW.Memory <Error> core/memory.cpp:VirtualToPhysicalAddress:685: Unknown virtual address @ 0x096D2605
[   0.794941] HW.Memory <Error> core/memory.cpp:VirtualToPhysicalAddress:685: Unknown virtual address @ 0x096CFF05
[   0.795115] HW.Memory <Error> core/memory.cpp:VirtualToPhysicalAddress:685: Unknown virtual address @ 0x08000104
[   0.803343] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFileDirectly:133: failed to get a handle for archive archive_id=0x2345678A archive_path=[Binary: 020201009b00040000ffffff02000000]
[   0.803862] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFileDirectly:153: failed to get a handle for file [Binary: 0000000000000000000000000000000000000000] mode=1 attributes=0`

**Comment by wwylele** [comment]
Is this fixed?

**Comment by danzel** [comment]
Still broken.
Logs:
https://gist.github.com/danzel/ec204d4476d5c26f3bdd2a86b58e85b7

**Comment by benderscruffy** [comment]
in the latest nightly it goes ingame 
this can be closed
