### ISSUE TITLE
HarmoKnight Demo - Partial/cut-off rendering on top screen

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#2672]
Tested with 941a3dd. This occurs mostly throughout of the game. The only part that I noticed unaffected is the overworld. Changing the hardware renderer, shader JIT, internal resolution and CPU JIT settings had no effect. Note that some parts of the top screen aren't completely cut-off like the logo in the title screen and text boxes.

Left (3DS hardware) / Right (941a3dd)
![harmoknight_1](https://cloud.githubusercontent.com/assets/17358613/25211471/b73edba6-255b-11e7-8920-e23fc951fbee.png)
[Gallery of additional comparisons](http://imgur.com/a/BXwX8)

[Full log](https://github.com/citra-emu/citra/files/939658/log.txt)

Windows 10
i5 4670k
GTX 970 (381.65)
8GB RAM

**Comment by benderscruffy** [comment]
still happens on the latest nightly
![harmo](https://user-images.githubusercontent.com/2696404/33058977-30f8360c-cecd-11e7-82c3-0aba0f3a120d.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1490331/log.zip)

**Comment by FearlessTobi** [comment]
Fixed in Nightly due to one of wwyleles memory PRs.
