### ISSUE TITLE
Linux binaries require PPA on common Debian based distros

### ISSUE THREAD

**Issue by ahoischen** [citra-emu/citra#2674]
The provided Citra binaries for Linux depend on a `libstdc++6 version` which is not available in the
default repositories on the following distributions:
- Ubuntu 14.04 (Trusty Tahr)
- Ubuntu 16.04 (Xenial Xerus)
- Ubuntu MATE 16.04 (Xenial Xerus)
- KDE Neon 10.5 (Xenail Xerus)
- Debian 8.7 (Jessie)

The required version of `libstdc++6` is provided by the PPA `ppa:ubuntu-toolchain-r/test`. Its package provides versions of `GLIBCXX_3.4.*` up to revision `22`, which matches Citra's requirements. The Ubuntu packages provide revisions up to `20` and the Debian ones up to `19`.

An up to date version of `libstdc++6` is available in Debian Stretch (testing). Jessie users can set up their environment to selectively install packages from testing. See [this serverfault post](https://serverfault.com/questions/22414/how-can-i-run-debian-stable-but-install-some-packages-from-testing) for instructions.

This has been tested on the following machines:
- My personal laptop running Ubuntu MATE 16.04.2
- My personal laptop running KDE Neon 5.10 (based on ubuntu xenial)
- The docker image `ubuntu:trusty`
- The docker image `ubuntu:xenial`
- The docker image `debian:jessie`

The tested commit was ~~`941a3dd`~~ `e646bd9` nightly.

This should at the very least be documented on the downloads page, inform Ubuntu users of the PPA and Debian users of the stretch packages. Since both methods require changing package sources it would be ideal, if a common version such as `19` was used.

I have not tested if building from source under `19` or `20` fails.

**Comment by ahoischen** [comment]
#2665 is related.

**Comment by lainz** [comment]
I can confirm this in Ubuntu 16.04.

**Comment by BreadFish64** [comment]
Seeing as we only officially support flatpack for linux now, and those distro's are fairly old, I'm going to go ahead and close this.
