### ISSUE TITLE
[   0.014694] Loader <Error> core/loader/ncch.cpp:LoadExeFS:295: ExHeader Program ID mismatch: the ROM is probably encrypted. [   0.014709] Core <Critical> core/core.cpp:Load:79: Failed to determine system mode! [   0.014728] Frontend <Critical> citra_qt/main.cpp:LoadROM:339: Failed to load ROM!

### ISSUE THREAD

**Issue by maatttkkkk** [citra-emu/citra#2678]
Im a damn noob. Can someone help?

I keep getting "Could Not Deteermine System Mode" every time with multiple files. 

terminal window -

[   0.014694] Loader <Error> core/loader/ncch.cpp:LoadExeFS:295: ExHeader Program ID mismatch: the ROM is probably encrypted.
[   0.014709] Core <Critical> core/core.cpp:Load:79: Failed to determine system mode!
[   0.014728] Frontend <Critical> citra_qt/main.cpp:LoadROM:339: Failed to load ROM!

-

**Comment by neobrain** [comment]
> Can someone help?

No.
