### ISSUE TITLE
Critical Error while playing Pokemon Sun - Fire Emblem Awakening? 

### ISSUE THREAD

**Issue by Ichigetsu** [citra-emu/citra#2688]
Im Using the newest Bleeding Edge Build of Citra and i always get this Error when playing the mentioned games. 

![citra error](https://cloud.githubusercontent.com/assets/28511873/25783624/9f0aac7e-335f-11e7-8e58-82712140e50e.jpg)

Im not that good with Computers and such stuff whatsoever... but i also only get max 50% speed when playing and i think this maybe could be the issue of it?  Any thoughts or help about it?

Running on 
Fx 8350 Cpu
R9 290 Gpu
16Gb Corsair vengeance

**Comment by wwylele** [comment]
The error is unrelated to the speed.

----

This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://community.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build, or
 - use pirated copies of the games, 3DS BIOS files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid
