### ISSUE TITLE
libpng12 not working Ubuntu 17.04

### ISSUE THREAD

**Issue by PizzicatoWolf** [citra-emu/citra#2701]
Hi, I'm currently running Ubuntu 17.04, and running Citra through the nightly builds will throw out an error when I try to run it.

`./citra: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory`

This seems to be an issue on your end because the newest version of Ubuntu does not use libpng12 anymore. Is there any way to allow Citra to implement newer versions?

**Comment by yuriks** [comment]
Our CI environment uses libpng12. If you just compile Citra yourself then it should work.

**Comment by PizzicatoWolf** [comment]
ok
