### ISSUE TITLE
OpenGL rendering LUTs should be defined by something other than 1D textures

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#2704]
The original reason they used textures was to take advantage of linear filtering to do the interpolation for us. This approach has since shown to be insufficient (#1775) and will need to be replaced. Using something other than a texture (texture buffer, or a uniform) might enable us to do quicker updates of the values. 

@degasus gave some advice about the best approach to use on IRC, which I failed to save the logs for I think.

**Comment by JayFoxRox** [comment]
I'm very sure degasus said to use a uniform buffer.
We should do the bitfield decoding on the CPU. As we'll probably use integer logic in the future, the data in the buffers should still be integers probably, but this could probably be changed around easily.

**Comment by Subv** [comment]
is this still relevant?

**Comment by magcius** [comment]
Using a UBO for 256 floats is pretty simple and should be faster than a 1D texture LUT on most GPUs.

**Comment by wwylele** [comment]
Actually we have been using UBO for LUT for a long time. Closing as this is not relevant any more
