### ISSUE TITLE
Changable CPU/GPU clock for debugging.

### ISSUE THREAD

**Issue by damteenagers** [citra-emu/citra#2711]
I use citra because i do not having a working console as of now, I need to know how CPU/GPU clocks affect my brew. Thnx

**Comment by RavenHome1** [comment]
changing clocks is known to cause many issues and break games. and almost no emulator out there ever recommends using. afaik even dolphin removed the ability to manipulate the cpu clocks from the emulator. is it a good idea to do this?

**Comment by yuriks** [comment]
This wouldn't do anything since we don't emulate timings of any kind right now anyway.

**Comment by emmauss** [comment]
@RavenHome1  dolphin still supports overclocking. most people currently use it for frame rate hacks, and some games have been known to show better performance on low end systems. though it is not relevant here in citra
