### ISSUE TITLE
Mario & Luigi: Paper Jam - Extremely slow when battling with multiple paper stacks

### ISSUE THREAD

**Issue by 1425720626** [citra-emu/citra#2712]
After entering the battle with Paper Goombas come in a multiple stacks, the FPS suddenly goes extremely low. It also happens when entering a battle after Paper Mario is joined.
Using version bleeding-edge-315 (56d2222). The log when entering the battle is here.
`[ 109.398581] Service <Error> core\hle\service\service.cpp:HandleSyncRequest:95: unknown / unimplemented function 'GetStepHistory': port=ptm:u, cmd_buff[1]=0x18, cmd_buff[2]=0xB3315000, cmd_buff[3]=0x7F, cmd_buff[4]=0x30C, cmd_buff[5]=0xFFFFA68`
`[ 109.411143] Service.HID <Warning> core\hle\service\hid\hid.cpp:GetGyroscopeLowCalibrateParam:342: <STUBBED> called`
`[ 109.886759] Service <Error> core\hle\service\service.cpp:HandleSyncRequest:95: unknown / unimplemented function 'GetStepHistory': port=ptm:u, cmd_buff[1]=0x18, cmd_buff[2]=0xB3315000, cmd_buff[3]=0x7F, cmd_buff[4]=0x30C, cmd_buff[5]=0xFFFFA68`
`[ 110.028644] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:478: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched.`

**Comment by 1425720626** [comment]
Using the latest version of Citra still have this issue.

**Comment by drewthatgamer** [comment]
Probably just due to the amount of sprites on screen at once. About 90% sure the game keeps all the sprites for each Goomba loaded.

**Comment by Zsashas** [comment]
Do we know if there any way to resolve this yet? Or is this just always going to be an issue?

**Comment by Dragios** [comment]
Is this still an issue now since @jroweboy marked #2845 as duplicate with this one and yet that is close but not this.
