### ISSUE TITLE
Possible Edge Case

### ISSUE THREAD

**Issue by NWPlayer123** [citra-emu/citra#2720]
Running on Citra Nightly | HEAD-c291db7
I'm running Pokemon Super Mystery Dungeon for the first time, going through the pick-your-character stuff, and it keeps spouting this:
[ 230.145475] HW.GPU <Error> video_core\command_processor.cpp:Pica::CommandProcessor::WriteUniformFloatReg:94: Invalid vertex shader float uniform index 127
(Picture: http://imgur.com/rFUG7YT)

**Comment by Hexagon12** [comment]
Duplicate of #2473.

If you're not experiencing any graphical issues, just ignore those warnings.

**Comment by wwylele** [comment]
Closed as duplicated
