### ISSUE TITLE
Dragon Quest Monsters 2 (J) - Tangent mapping unimplemented

### ISSUE THREAD

**Issue by ruineka** [citra-emu/citra#2723]
This is the first time for me to ever post something like this before so bear with me. I have been playing Dragon Quest Monsters 2 (J) on Citra and it was playing fine until I get to a spot where it crashes each time. It appears to be caused by a missing unimplemented tangent map. The files within the romfs that cause this crash are located at /data/Effects/EFC_803.bcres and EFC_804.bcres. Simply swapping them out with another animation that does work in Citra is a workaround to the crash.

<img width="960" alt="crashdqm2" src="https://cloud.githubusercontent.com/assets/16360335/26442178/fd3b0144-40f8-11e7-9adc-16f3dbf716bc.PNG">

I have attached a log of where the crash occurs.

System Information:

GTX 1080
i7 7700k
16gb 3200mhz ram
Citra Bleeding Edge | HEAD-50bf56b

[crash.txt](https://github.com/citra-emu/citra/files/1028396/crash.txt)

**Comment by wwylele** [comment]
This is due to unimplemented tangent mapping mode.

**Comment by wwylele** [comment]
Could you get a new log from the most recent bleeding edge build (which includes spot light)? It will crash still, but I expect some log change.

**Comment by ruineka** [comment]
[Head-b44970c Crash.txt](https://github.com/citra-emu/citra/files/1038250/Head-b44970c.Crash.txt)

**Comment by wwylele** [comment]
fixed by #2762
