### ISSUE TITLE
Allow RomFS/ExeFS patch files to be applied to games

### ISSUE THREAD

**Issue by briman0094** [citra-emu/citra#2735]
I'm currently refactoring/rewriting the `pk3DS` Pokemon randomizer, which operates on an extracted 3DS ROM filesystem, with the typical format of:

```
ExeFS
--code.bin
RomFS
--<rom FS files>
```

The latest versions of Luma allow live-patching running ROMs with a structure identical to this, meaning I can test randomizations or ROM edits without having to wait for an entire ROM repack operation to complete (which takes a while). However, it's not easy to constantly swap test saves on and off of a game cartridge, and it's obnoxious having to constantly move my SD card between my 3DS and computer.

It would be nice if Citra had a feature similar to Luma's, where a directory could be specified for a specific title to patch individual RomFS files, or the ExeFS `code.bin`.

I'm not familiar with the inner-workings of Citra specifically, so I'm not sure if this is possible without major modifications, but I thought I'd bring it up in case it's something that could be done.

**Comment by yuriks** [comment]
This is quite hard to do. I wouldn't expect it any soon.
