### ISSUE TITLE
Phoenix Wright Ace Attorney: Spirit of Justice – Flashing Graphical Glitches on Hardware Renderer

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#2741]
This only happens on the integrated __**Intel**__ GPU and I have no idea why. This issue is not present when using the dedicated __**nVidia**__ GPU. Tested on latest master based on commit 4857eb441bbe7ba1637838c9e5158f0801f40730
Altering *Shader JIT* on/off yield the same result.
Partial mirroring from top screen shown on bottom screen indicates a separate issue.

*Hardware renderer* with [full log](https://pastebin.com/K9YzPTz3) attached:
![Flashing Graphical Glitch](https://cloud.githubusercontent.com/assets/18496868/26680851/8a031318-470d-11e7-8ce8-aaedc7711a1d.png)

*Software renderer*:
![Software Renderer](https://cloud.githubusercontent.com/assets/18496868/26681064/57486aa8-470e-11e7-8517-759f06e77391.png)

Log spams with this in *Software Renderer*:
`Render.OpenGL <Error> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:472: API ERROR 1282: Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error`

I have include a [video](https://streamable.com/6f47m) for a better picture.

**Comment by RavenHome1** [comment]
there is also some glitchy effects right as the game boots from the video you provided

**Comment by Dragios** [comment]
@RavenHome1 That one is not related and has been explained [here](https://github.com/citra-emu/citra/issues/2715#issuecomment-302906860)

**Comment by Dragios** [comment]
@RavenHome1 Well it could be this as explained [here](https://github.com/citra-emu/citra/issues/2715#issuecomment-302906860) or not.

**Comment by yuriks** [comment]
Seems like some state tracking bug from us. We have a few of these that show up pretty often depending on what you're playing...

@Dragios that issue isn't the same as this one. That one is only about the glitched video showing for a frame at boot.

**Comment by wwylele** [comment]
Fixed by #3281
