### ISSUE TITLE
Changing the language in Bravely Default For the Sequel freezes citra

### ISSUE THREAD

**Issue by naruto020499** [citra-emu/citra#2745]
The last line of code is "[2160.689265] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:472: API OTHER 65536: Framebuffer unsupported. Framebuffer object 3 is unsupported because the depth and stencil attachments are mismatched."

**Comment by wwylele** [comment]
Please paste the full log.
And is that a in-game language selection?

**Comment by naruto020499** [comment]
Can I put it in a txt file or something? It exceeds the limit of characters and yes both in-game text and language freeze it after changing it from japanese to english then exiting config menu going back to game..

**Comment by naruto020499** [comment]
[log.txt](https://github.com/citra-emu/citra/files/1049552/log.txt)

**Comment by Secmess** [comment]
Same problem. Tested with Bravely Default: For the Second (JPN) and Bravely Default (USA), both give the same problem either by changing the text or the voice language. No problem with other configs.

**Comment by SomeHobo0** [comment]
Can we note that language changes work fine now?

**Comment by FearlessTobi** [comment]
Did you test on Nightly? If not, can you confirm it works there too?

**Comment by naruto020499** [comment]
@FearlessTobi 
[log.txt](https://github.com/citra-emu/citra/files/2546111/log.txt)
And yes the audio and text does change in the in-game selector and doesn't crash after leaving the menu. Thank you to the Citra team and the community for the help.
