### ISSUE TITLE
Star Fox - Stuck Initializing Game Data

### ISSUE THREAD

**Issue by Schplee** [citra-emu/citra#2749]
Nightly - 8f0a23b

Star Fox won't continue without a save file.

![xjvxs0o](https://cloud.githubusercontent.com/assets/24275329/26764961/729118ea-4926-11e7-833c-0e27a4dee94c.png)

[EDIT] Updated Log file to trace log
[log.txt](https://github.com/citra-emu/citra/files/1056122/log.txt)

**Comment by Subv** [comment]
Log?

**Comment by Schplee** [comment]
@Subv Yes, sorry. I forgot to include a log file when I rushed to get this issue posted for the compatibility list.

**Comment by arkhamsaiyan** [comment]
The only time this happens is when you do not have a previous save from your actual system import that and it will go away

**Comment by eadmaster** [comment]
do you have a savegame for the European version?
I've tried loading the USA savegame but it says it is corrupted...

**Comment by einstein95** [comment]
No premade savedata is needed, only 0 byte files in the save folder called:
- menu0.sav
- n640.sav
- rmain00.sav
- rmain01.sav
- rmain02.sav
- rscore00.sav
- rscore01.sav
- rscore02.sav

**Comment by arkhamsaiyan** [comment]
well technically, you need certain files from the main save to get past the initializing... screen then

**Comment by einstein95** [comment]
Technically those files just need to be present, not valid files. The game
will then properly format them.

**Comment by arkhamsaiyan** [comment]
but you get those files from the actual system or do you get them from the game data?

**Comment by eadmaster** [comment]
@einstein95: i've tried what you suggested with the latest nightly build, but it still freeze on the initializing screen...
the save files  for the EUR version should go in `C:\Users\[your-user-name]\AppData\Roaming\Citra\sysdata\00040000\00049100\data\00000001`, right?

**Comment by einstein95** [comment]
@arkhamsaiyan Neither. They can be just 0 byte files. In Windows, a renamed new text document should do the trick (making sure extensions are shown).
@eadmaster No.  `%APPDATA%\Citra\sdmc\Nintendo 3DS\00000000000000000000000000000000\00000000000000000000000000000000\title\00040000\00049100\data\00000001`.

**Comment by eadmaster** [comment]
@einstein95: thank you, it works now!

**Comment by benderscruffy** [comment]
still doesn't work in the latest nightly but works in the canary version

**Comment by lino11** [comment]
Using nightly.... and by adding the 0 byte .sav files (and even downloading an intro save from Citra's main Star Fox page)... it calls that existing data corrupt, tries to erase it, and never moves on from there.

**Comment by B3n30** [comment]
Closed by #3091
