### ISSUE TITLE
Picross e4-e7 - Can't read prior game's save data for bonus unlocks.

### ISSUE THREAD

**Issue by SonofUgly** [citra-emu/citra#2751]
Picross games, starting with Picross e4, give you a few bonus puzzles if save data for the previous Picross e games is found. These bonus puzzles can't be unlocked in Citra. Can Citra not load save data for anything but the currently loaded game?

![](http://i.imgur.com/S1kt0kz.png)

[Log file](https://pastebin.com/WkhKJUWx)
Relevant part of the log seems to be:
`[   3.600133] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:685: Unknown virtual address @ 0x08EC8440
[   3.600153] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:685: Unknown virtual address @ 0x08EC959C
[   3.600160] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:685: Unknown virtual address @ 0x08EC9EF4
[   3.600167] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:685: Unknown virtual address @ 0x08ECA84C
[   3.600173] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:685: Unknown virtual address @ 0x08ECB1A4
[   3.600180] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:685: Unknown virtual address @ 0x08ECBAFC
[   3.600186] HW.Memory <Error> core\memory.cpp:Memory::VirtualToPhysicalAddress:685: Unknown virtual address @ 0x08ECC454`

**Comment by Schplee** [comment]
A log file may help.

**Comment by Subv** [comment]
`[   1.720372] Service.FS <Warning> core\file_sys\archive_other_savedata.cpp:FileSys::ArchiveFactory_OtherSaveDataPermitted::Open:72: (stubbed) Unimplemented media type GameCard`
mmm, it might be trying to open the archive from the gamecard exclusively?

**Comment by wwylele** [comment]
Theoretically citra is able to load save from other game. 
 - Do these game have digital version?
 - Do you have those previous games (e1-e3, I assume?), and have them run in citra, and save any data?

analyse of the log:
```
// Tries to open the gamecard version of game 00000e5d (Picross e1?). This is currently stubbed in citra and will always produce these two line of log
[   1.720372] Service.FS <Warning> core\file_sys\archive_other_savedata.cpp:FileSys::ArchiveFactory_OtherSaveDataPermitted::Open:72: (stubbed) Unimplemented media type GameCard 
[   1.720382] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenArchive:459: failed to get a handle for archive archive_id=0x567890B4 archive_path=[Binary: 020000005d0e000000111000]

// Tries to open the digital version of game Picross e1. If the archive was opened successfully, citra wouldn't log anything. This log means citra can't find any save data of Picross e1 saved in its virtual sdmc.
[   1.720511] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenArchive:459: failed to get a handle for archive archive_id=0x567890B4 archive_path=[Binary: 010000005d0e000000111000]

// Now the same process for the game 00000cd4 (Picross e2?). These two line is game card save open failure
[   1.720641] Service.FS <Warning> core\file_sys\archive_other_savedata.cpp:FileSys::ArchiveFactory_OtherSaveDataPermitted::Open:72: (stubbed) Unimplemented media type GameCard
[   1.720650] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenArchive:459: failed to get a handle for archive archive_id=0x567890B4 archive_path=[Binary: 02000000d40c000000111000]

// And this line is digital version save open failure
[   1.720679] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenArchive:459: failed to get a handle for archive archive_id=0x567890B4 archive_path=[Binary: 01000000d40c000000111000]

// Same goes 000001d1 (Picross e3?)
[   1.720689] Service.FS <Warning> core\file_sys\archive_other_savedata.cpp:FileSys::ArchiveFactory_OtherSaveDataPermitted::Open:72: (stubbed) Unimplemented media type GameCard
[   1.720696] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenArchive:459: failed to get a handle for archive archive_id=0x567890B4 archive_path=[Binary: 020000001d10000000111000]
[   1.720720] Service.FS <Error> core\hle\service\fs\fs_user.cpp:Service::FS::OpenArchive:459: failed to get a handle for archive archive_id=0x567890B4 archive_path=[Binary: 010000001d10000000111000]
```

**Comment by SonofUgly** [comment]
Okay, I'm a big dummy. It was from region issues.
