### ISSUE TITLE
Regular Updates to citra AUR package

### ISSUE THREAD

**Issue by Lord-Haji** [citra-emu/citra#2757]
It'd be nice if you ppl can update the AUR package regularly for using the latest version on Arch Linux and other distros based on it

**Comment by j-selby** [comment]
I strongly disagree with this. We already have mechanisms to support building on Linux, and distro-specific build systems should be left to distributions themselves (the AUR itself), as has been the case for ages now.

**Comment by linkmauve** [comment]
AUR packages based on a git version don’t need any regular update, as running `makepkg` again will always give you the latest version.

Closing, as this isn’t an issue.
