### ISSUE TITLE
Pokemon Sun and Moon graphical slowdown.

### ISSUE THREAD

**Issue by Oquantumfoam** [citra-emu/citra#2765]
Whilst playing Pokemon moon on citra (master-895cc51-dirty) game gradually slows down from slightly faster than normal to unplayable levels, over the course of a couple hours of playtime. Restarting the game seems to reset it, but not fix it. The game is still entirely playable despite the bug, as one can save, quit and restart quite rapidly to get better speeds. Another point is that the speed slowdown does not seem to be an FPS slowdown, as FPS remains consistent at 60, even whilst the game gets to unplayable slowness.

**Comment by wwylele** [comment]
you are using an old unofficial build. This has been fixed in the official build months ago.
