### ISSUE TITLE
[FEATURE REQUEST] Creating a Vulkan/SYCL GPGPU Renderer for Citra

### ISSUE THREAD

**Issue by tiagmoraismorgado** [citra-emu/citra#2768]
# Hey Guys
It would be really interesting if, within sense: 
- _citra could be rendered using a vulkan/sycl GPGPU. please let me know what are your thoughts on this regard_

**looking forward
T.**

**Comment by RavenHome1** [comment]
https://community.citra-emu.org/t/would-vulkan-improve-speeds/411

**Comment by tiagmoraismorgado** [comment]
I see

**Comment by RavenHome1** [comment]
since this is not an issue or a bug report then please close this and use the forums i linked for any further questions regarding citra
