### ISSUE TITLE
Pokemon Super Mistery Dungeon Jittery Audio DSP when you crank resolution up on macbook pro 13" a1278

### ISSUE THREAD

**Issue by tiagmoraismorgado** [citra-emu/citra#2769]
# Greetings

**I would like to state that:**

- _Pokemon Super Mistery Dungeon Audio DSP gets Jittery when you crank resolution up on macbook pro 13" a1278_

I should notice that i only increased it it up to 1200*700 px

**Kind Regards
T.**

**Comment by j-selby** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

---

*Citra* is currently in very early stages of development. Games usually run less than full-speed even on the best computers. Expect bugs and glitches to appear in most games. Many features found in more mature emulators are still in the works. 

---

Requesting to close.
