### ISSUE TITLE
[FEATURE REQUEST] - Support For VR Headset Technologies

### ISSUE THREAD

**Issue by tiagmoraismorgado** [citra-emu/citra#2770]
**Subject - [FEATURE REQUEST] - Support For VR Headset Technologies**

# Greetings

**It would be really great if:**
- _Citra could feature Support for VR Headset Technologies **(even if not all the their features are supported)**_

**Comment by MerryMage** [comment]
While this could be something that might happen in the future, I don't really see it happening anytime soon.
