### ISSUE TITLE
[FEATURE REQUEST] Support for Ambisonics Audio Rendering

### ISSUE THREAD

**Issue by tiagmoraismorgado** [citra-emu/citra#2771]
**Subject - [FEATURE REQUEST] Support for Ambisonics Audio Rendering**

# Greetings

**It would be really interesting if we could:**
- _add Support for Ambisonics Audio Rendering (perharps using Oculus SDK Ambisonic Features);_

**Kind Regards
T.**

**Comment by tiagmoraismorgado** [comment]
another really great thing to have a look at is raya audio engine: https://www.youtube.com/watch?v=05EL5SumE_E

**Comment by j-selby** [comment]
Yeah, that Raya junk requires knowledge of the game world, and would essentially be game-specific hacks. No thanks.

I don't agree with linking against a proprietary VR solution either (i.e Oculus's) as it will be dead in a few years anyway, and it only complicates the audio core.

Finally, I don't think any kind of pseudo-3D sound system is even possible - from what I can see of Citra's HLE audio implementation it only produces stereo sound.

I really don't think the idea of adding crap audio effects to Citra to create functionality that wasn't there is a good idea.

Voting to close.
