### ISSUE TITLE
791cd14 - Crash when loading game

### ISSUE THREAD

**Issue by Eliastik** [citra-emu/citra#2777]
![screen_citra_crash](https://user-images.githubusercontent.com/26941242/27095560-7057cc00-506e-11e7-9165-67671cffad0f.png)

Nightly - [791cd14](https://github.com/citra-emu/citra-nightly/commit/791cd14c8d0878aa69c2470f99276e08ea601cd4)

When launching any game, Citra crash with this errors in the console (here, I launched Super Mario 3D Land) : 
`[   3.848232] HW.Memory <Error> core\memory.cpp:Memory::GetPointer:284: unknown GetPointer @ 0x1f1e6000
[   3.848572] HW.Memory <Error> core\memory.cpp:Memory::GetPointer:284: unknown GetPointer @ 0x1f1e6000
[   3.848721] HW.Memory <Error> core\memory.cpp:Memory::GetPointer:284: unknown GetPointer @ 0x1f48f000
[   3.848842] HW.Memory <Error> core\memory.cpp:Memory::GetPointer:284: unknown GetPointer @ 0x1f48f000`

My OS is Windows 10, my graphic card is a Nvidia GTX 950 with drivers up-to-date. My games are dumped from my cartridges with [Braindump](https://github.com/neobrain/braindump). Citra worked before I updated it.

**Comment by wwylele** [comment]
I think from #2687 we completely stopped supporting braindump ROM (though it was already removed from the dumping guide earlier). Please redump your games using Decrypt9 or GodMode9. I am closing this because it looks really like braindump issue. Report back if you still have issue with properly dumped games.

**Comment by yuriks** [comment]
What exactly in the rom causes it to fail after my PR? We might want to add a pop-up dialog when we detect a Braindump ROM like that, like we have for other common errors.
