### ISSUE TITLE
Professor Layton and the Miracle Mask - Graphical glitches

### ISSUE THREAD

**Issue by Eliastik** [citra-emu/citra#2780]
Citra version: Nightly - 791cd14

There are some graphical glitches with the characters and major slowdowns during dialogs in the game Professor Layton and the Miracle Mask.

Screenshot :
![screen_citra_layton](https://user-images.githubusercontent.com/26941242/27111732-755c950c-50b2-11e7-940a-8b40b0ced0e9.png)

Log :
[log.txt](https://github.com/citra-emu/citra/files/1073291/log.txt)

OS: Windows 10
GC: GTX 950 / drivers up-to-date
Citra config:  HW renderer/V-sync/Shader JIT/Limit Framerate/Native resolution

**Comment by Subv** [comment]
Is that the entire log? it seems incomplete

**Comment by RavenHome1** [comment]
@Subv the issue is due to lack of GS if that is what you are after

https://community.citra-emu.org/t/professor-layton-and-the-miracle-mask-errors-in-3d-parts/695/2?u=ravenhome

**Comment by FearlessTobi** [comment]
Graphical bugs are fixed because Geometry Shaders are now implemented.

Screenshot from latest Nightly: 
![screenshot](https://user-images.githubusercontent.com/20753089/31553222-ff4ac0ea-b039-11e7-8474-fc2b69170729.png)
