### ISSUE TITLE
Implement custom speed controller

### ISSUE THREAD

**Issue by BynariStar** [citra-emu/citra#2781]
From #2663 by @wwylele's suggestion,

Add support for a custom speed controller allowing the game to be run at different speeds (i.e., 60fps) or even at a variable refresh rate.

**Comment by MerryMage** [comment]
> custom speed controller

@wwylele was likely referring to running the game at a speed other than 100%, which while closely related to the framerate probably isn't what you're looking for.

**Comment by BynariStar** [comment]
Ah, I see. So what would be the proper way to describe this feature?

**Comment by MerryMage** [comment]
An emulator can't do much to do what you're looking for. What you're looking for is probably a [60 fps hack](https://dolphin-emu.org/blog/2015/02/07/game-modification-60-fps-hacks/), something which requires modification of the game or its engine to work, which has to be done on a per-game basis.
