### ISSUE TITLE
SNES Virtual Console Games - Crash on Boot

### ISSUE THREAD

**Issue by Schplee** [citra-emu/citra#2782]
Nightly - `ac168ee`

All SNES Virtual Console games crash on boot.

[log.txt](https://github.com/citra-emu/citra/files/1073749/log.txt)

**Comment by yuriks** [comment]
SNES VC is n3DS exclusive, so we need to support emulating it's features for it to work. In this case it's using the extra CPU.

**Comment by Dragios** [comment]
New 3DS mode is already supported. It should be fixed by now @Schplee Could you test and let us know the status of this issue?

**Comment by Schplee** [comment]
Confirmed that New 3DS support resolves this issue. Solved by #5117 and B3n30's PRs
