### ISSUE TITLE
Can not open in windows 10

### ISSUE THREAD

**Issue by JustShinaa** [citra-emu/citra#2786]
the emulator Nightly Build-da1bec1 can not be open on windows 10. my system 32-bit operational system and x64-based processor. its not just Nightly Build-da1bec1, i cant use any version on my computer. 
![citra crash](https://user-images.githubusercontent.com/29513640/27257490-e7d0d50a-5402-11e7-9c96-893e648b7c6b.png)

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Citra only runs on 64bit operating systems.

Closed as not an issue
