### ISSUE TITLE
System Settings - Unknown GetPointer @ 0x1f300000

### ISSUE THREAD

**Issue by khang06** [citra-emu/citra#2788]
When trying to boot System Settings (Latest version, N3DS) with a complete Home Folder, I get an error before anything even renders.

`[   0.421472] HW.Memory <Error> core/memory.cpp:GetPointer:284: unknown GetPointer @ 0x1f300000`
`[   0.421488] HW.Memory <Error> core/memory.cpp:GetPointer:284: unknown GetPointer @ 0x1f300000
`

Happens on both latest nightly (Linux Mint 18.1) and bleeding edge (Windows 10). This is a regression, because this worked fine in the past.
Full log here: https://hastebin.com/ecuyinidof.bash

EDIT: Happens in eShop, too.

**Comment by yuriks** [comment]
How did you dump this?

**Comment by khang06** [comment]
Aaaaaand I just realized that dump was from a long time ago and made from braindump. I made a fresh new dump with GodMode9 and now it works perfectly. Closing this issue.
