### ISSUE TITLE
Super Mario 3D Land - Missing water effect in W4-1 level

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#2791]
Apart from the GS related lines (tested with BE-86 and the water is still the same), log (Critical) shows:

```HW.GPU <Critical> video_core\renderer_opengl\gl_shader_gen.cpp:GLShader::SampleTexture:169: Unhandled texture type 5```

[LOG](https://hastebin.com/daqorohage.pas)
[LOG](https://hastebin.com/ijakinoqot.rb) (Non-shining stars)

![sm3dland](https://user-images.githubusercontent.com/17358613/27290756-8c5ac5ae-54e4-11e7-9cac-217a29c0d74e.png)

[Save file](https://github.com/citra-emu/citra/files/737215/SM3DL.-.Regular.World.zip)
[GameData.zip](https://github.com/citra-emu/citra/files/1086330/GameData.zip) (Non-shining stars)

What it looks like in on 3DS in [video](https://youtu.be/NvXMg_H8ByQ?t=1m20s). 

Commit: d0888f8
Windows 10
i5 4670k
GTX 970 (382.05)
8GB RAM

**Comment by wwylele** [comment]
not necessarily related, but `Commandlist tried to write to invalid register` error looks pretty broken. Does it shows up in the same area or somewhere else?

**Comment by Leo626** [comment]
It only shows when I press A to start on the start screen. It doesn't appear when I start that level.

**Comment by B3n30** [comment]
solve by #2921

**Comment by Leo626** [comment]
This isn't fixed. What I had meant to say was the water shader effects were missing hence the water looked bland in Citra. The small black thing (ripples) by Mario is batching related and is fixed though.

Hardware
![ntr_0041](https://user-images.githubusercontent.com/17358613/30820156-7728fbdc-a1f7-11e7-9409-449632a17a1a.png)
Hardware with annotations
![ntr_0041](https://user-images.githubusercontent.com/17358613/30820174-8421e9ca-a1f7-11e7-82f0-fbab8b55cfe9.png)
Nightly-d881dee
![citra-qt_2017-09-25_09-14-04](https://user-images.githubusercontent.com/17358613/30820200-9a761f84-a1f7-11e7-93eb-7a47e0128acf.png)
