### ISSUE TITLE
Moco Moco Friends - softlock on chapter screen

### ISSUE THREAD

**Issue by ariehfabbro** [citra-emu/citra#2794]
Citra version: Nightly - ecd332b

The game had a solflock at the chapter screen. The music was still playing, but inputs doesn't do anything. 

![screen shot 06-20-17 at 01 28 pm](https://user-images.githubusercontent.com/8531737/27362900-af4d3690-5607-11e7-95d9-ed0c16468668.JPG)

[log.txt](https://github.com/citra-emu/citra/files/1090086/log.txt)

System Information
* Operating System: Windows 7 Ultimate Service Pack 1
* CPU: Intel(R) Core(TM) i7-3610QM CPU @ 2.3GHz
* GPU: Geforce GTX 660M
* Citra Version (found in title bar): citra-windows-msvc-20170619-ecd332b
* Game: Moco Moco Friends (USA)

**Comment by Reboot80** [comment]
any chance this is getting worked on? this issue still persists and I'm confused as to why this issue has been closed..
