### ISSUE TITLE
[Enhancement] Viewmode - Both Screens Same Size

### ISSUE THREAD

**Issue by shinra358** [citra-emu/citra#2806]
I would like to ask for a view mode where the 2nd screen is the same size as the first. That way it can fill the whole area when using a dual monitor touchscreen setup.

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Closed as Invalid

There is a feature to configure a custom screen layout in citra already. Try asking on the forums for some help using it.
