### ISSUE TITLE
GDB Stub does not support VFP registers in IDA Pro

### ISSUE THREAD

**Issue by viocar** [citra-emu/citra#2810]
As of Citra Bleeding Edge | HEAD-7c224ee, when using the GDB Stub, you cannot view the contents of the VFP registers in IDA Pro (6.6). If you click or mouse over these registers, IDA Pro gives the following error:

Bad register number passed to arm.get_register_value: <value>

(Value is 93 + the register number. S0 is 93, S1 is 94, and so on. I'm not sure what D or Q registers return as I don't run into those).

Is this a bug in Citra, a bug in IDA Pro 6.6, or a missing implementation?

**Comment by MerryMage** [comment]
Do earlier versions work?

**Comment by viocar** [comment]
Can't test at the moment, but someone in the Discord said he got the same errors a few months ago, so I'm guessing it's either been broken for a long time or never worked at all.

**Comment by TuxSH** [comment]
It's defintely a Citra bug which doesn't handle reading/writing registers correctly at all (there are bugs even when writing CPU regs).

Here's my own (and @Stary2001 's) gdbstub: https://github.com/AuroraWright/Luma3DS/tree/master/sysmodules/rosalina/source/gdb

**Comment by viocar** [comment]
On [L548 of gdbstub.cpp,](https://github.com/citra-emu/citra/blob/master/src/core/gdbstub/gdbstub.cpp#L548), the gdbstub's author wrote the comment "VFP registers should start at 26, so one after CSPR_REGISTER." This seems to be an incorrect assumption. If I try to get the value of the D0 register in IDA Pro, which to my knowledge is the lowest VFP register, I receive [this error message](http://i.imgur.com/NDVQRvl.png), suggesting that the VFP registers start at 61, and not 26 like gdbstub.cpp's author believed. I lack the skills to make the changes necessary, so I can't test my theory.

**Comment by viocar** [comment]
Alright, after a lot of searching, I figured out that this is an IDA Pro issue, and not a Citra issue, so I'm closing this.
