### ISSUE TITLE
Unnecessary warning about NG Bad Word list in Pokemon Sun and Moon

### ISSUE THREAD

**Issue by lewhitemale** [citra-emu/citra#2817]
Most recent version tested: nightly 2e37ce0

log is from nightly 56d718b but identical:
![citra_nightly__head-56d718b_2017-07-08_01-20-42](https://user-images.githubusercontent.com/29827796/27983175-bb6d2062-637b-11e7-9c3d-061a55ca69b3.png)

error message:
![citra_nightly__head-56d718b_2017-07-01_07-20-18](https://user-images.githubusercontent.com/29827796/27983176-be34944c-637b-11e7-9faa-8a9a21f3c91a.png)

To reproduce:
Load Pokemon Sun and Moon and encounter the Player naming screen without a 3DS system dump installed

This file isn't actually required in any way, only requested, and the message creates the hazard of unintentionally closing the game and losing progress for no reason, or making a less determined player believe the game doesn't actually work in Citra without a system dump. The log above is from naming the player; when naming a pokemon that alert pops up five times which is very annoying.

**Comment by lewhitemale** [comment]
Sorry, non-technical github virgin here, this may not be done perfectly... created issue to link on the wiki according to the style guide there.

**Comment by wwylele** [comment]
But the system archive is necessary, otherwise the filter on name input screen won't work properly. Sure, you the game is still playable, but we define "actually work in Citra" as "exactly the same behaviour as it on 3DS"

Closed as this is not an issue
