### ISSUE TITLE
MinGW build fails on compiling cpr/curl

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#2826]
(Just open this so that we won't forget)
log: https://pastebin.com/AGy2BBgS

Also another related issue: `make install` used to work on my ubuntu. However after adding cpr, although it still compiles, `make install`ed executable can't boot with error of "can't find libcurl.so". The local executable in the build directory can still boot without problem, though.

**Comment by wwylele** [comment]
Also a proposal: disable web service by default, and only enable it for CI / releases. The cpr/curl lib is pretty big and takes long time to build, and when developing citra the web service tends to send more noise than useful info.

**Comment by mailwl** [comment]
there is also compiling problem for macos:
1) brew renames Qt5 to Qt
2) libcurl:

> -- Not using system Curl, using built-in curl project instead.
> CMake Error at externals/cpr/opt/CMakeLists.txt:48 (add_subdirectory):
>   The source directory
> 
>     /Users/wl/projects/citra/externals/cpr/opt/curl
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at externals/cpr/opt/CMakeLists.txt:60 (set_property):
>   set_property could not find TARGET libcurl.  Perhaps it has not yet been
>   created.
> 
> 
> -- Set CURL_FOUND to TRUE.
> -- Set CURL_LIBRARIES to libcurl.
> -- Set CURL_INCLUDE_DIRS to /include;/include/curl.
> -- Using CURL_INCLUDE_DIRS: /include;/include/curl.
> -- Using CURL_LIBRARIES: libcurl.
> CMake Error at src/citra_qt/CMakeLists.txt:83 (qt4_wrap_ui):
>   Unknown CMake command "qt4_wrap_ui".
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/wl/projects/citra/build/CMakeFiles/CMakeOutput.log".
> See also "/Users/wl/projects/citra/build/CMakeFiles/CMakeError.log".

**Comment by jroweboy** [comment]
@mailwl curl is a submodule of cpr which is a submodule so you need to do `git submodule update --init --recursive` to pull it in.

**Comment by mailwl** [comment]
@jroweboy thanks!

**Comment by wwylele** [comment]
Fixed by using mingw system curl. See the wiki update.
