### ISSUE TITLE
Memory Error - Picross e2 - Citra 5137a19

### ISSUE THREAD

**Issue by superheri** [citra-emu/citra#2835]
https://pastebin.com/bXhRQnab
[log.txt](https://github.com/citra-emu/citra/files/1159178/log.txt)

I get an error that pop infinitely when playing a puzzle in Picross e2. This error look like this:
[ 15.771697] HW.Memory core\memory.cpp:Memory::VirtualToPhysicalAddress:700: Unknown virtual address @ 0x08B4176C

This error is visible in the pastebin linked. It pops so often that is if filling my RAM a lot. For only 113 seconds I get 3MB log file.

I also see that Citra is not able to send you the log automatically.

I use the Nightly build 5137a19.

I tested it and it does the same for Picross e too.

Thank you for your help.
I hope it will be able to help you in your developpement of Citra.

**Comment by superheri** [comment]
After testing it with debug in Visual Studio, I saw that the address given to this function is too low for the brackets that citra make possible. Is is possible that adding a new bracket of possibilities could help to translate theses address?

**Comment by chris062689** [comment]
On your pastebin link, 

This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

**Comment by superheri** [comment]
@chris062689 I've just updated the link to the Pastebin by creating a new one. I see that my last one has expired.

**Comment by superheri** [comment]
I've just add the log file to the issue after finding that it is possible.

**Comment by j-selby** [comment]
Both https://citra-emu.org/game/picross-e/ and https://citra-emu.org/game/picross-e2/ are reported as running perfectly on Citra. Likely a issue with the game dump (i.e using Braindump).

**Comment by superheri** [comment]
These games work fine, but there are still errors that are triggered in the background...

**Comment by superheri** [comment]
I've just tested it on f2f3910 and no more errors are triggered and the game is still correctly playable. So I assume it has been corrected.
