### ISSUE TITLE
Missing libcurl.so - Citra 5621a65

### ISSUE THREAD

**Issue by itsarjunsinh** [citra-emu/citra#2836]
OS: Ubuntu 16.04 (elementary OS)

> ./citra-qt: error while loading shared libraries: libcurl.so: cannot open shared object file: No such file or directory

[Official Binary](https://github.com/citra-emu/citra-nightly/releases/download/untagged-fafc37e2a9a4247399aa/citra-linux-20170718-5621a65.tar.xz) from Citra Downloads page. 

"curl" package is already installed. The last build I tested was some months ago but I did not encounter this issue then.

**Comment by j-selby** [comment]
Could you `whereis libcurl`?

**Comment by itsarjunsinh** [comment]
I also tried installing libcurl3-dbg. This issue might be limited to my a system.
> libcurl:

**Comment by itsarjunsinh** [comment]
The following package solved it: libcurl4-gnutls-dev 

Apologies for submitting this issue.

**Comment by j-selby** [comment]
This might be something to re-open, or create a new issue for. You shouldn't need to install a development package to run Citra. I'll assume this has to do with the broken Curl build system.
