### ISSUE TITLE
TOMODACHI LIFE CITRA ERROR (HW.AES <Error> core\hw\aes\ccm.cpp:HW::AES::EncryptSignCCM:49: Key slot 49 not available. Will use zero key.)

### ISSUE THREAD

**Issue by howyaldoin** [citra-emu/citra#2841]
Hi, I have an issue with Tomodachi life this **(** HW.AES <Error> core\hw\aes\ccm.cpp:HW::AES::EncryptSignCCM:49: Key slot 49 not available. Will use zero key.**)** keeps repeating itself when I launch the game. As I start the game Citra gives me a fatal error stating I should check the log then I exited out of the error and pressed the "no" button on the game which resulted in a white screen that would not change. **(pictures will be below** ).Could someone identify this error or tell me a solution to this problem. (I am also new to this platform is this the right place to post this message. if not could you please direct me to a place to get further help )

LOG DATA: https://pastebin.com/gnhnKV98
Citra version: Bleeding edge head-eb3024b
My Specs:
![specs](https://user-images.githubusercontent.com/30354908/28480658-b9ea9710-6e2f-11e7-9fed-e0760ac34406.PNG)

Pictures of Error:

Fatal Error:
![fatal error](https://user-images.githubusercontent.com/30354908/28480678-d7215ab2-6e2f-11e7-9243-c50b932731c3.PNG)

When I pressed no:
![pressed no](https://user-images.githubusercontent.com/30354908/28480687-df6e3708-6e2f-11e7-819d-bce85dd2a8e8.PNG)

White Screen:
![white screen](https://user-images.githubusercontent.com/30354908/28480692-e33e2352-6e2f-11e7-9fb9-2123642fe6a4.PNG)

Log:
![log](https://user-images.githubusercontent.com/30354908/28480739-094a160a-6e30-11e7-8421-c6e7c32f75f6.PNG)

**Comment by RavenHome1** [comment]
use the forums please, github is for dev and bug tracking

https://community.citra-emu.org/

**Comment by jroweboy** [comment]
https://github.com/citra-emu/citra/issues/2475 this is a known issue and had been reported here. If you would like to fill out the template to add it to the compatibility page please do so. 

Closed as invalid.
