### ISSUE TITLE
Fire Emblem Echoes: Shadows of Valentia - striped line graphical glitch 

### ISSUE THREAD

**Issue by Hexagon12** [citra-emu/citra#2846]
Tested on Nightly f2f3910.

The game's top and bottom screens has striped lines.

Reproduce: Load the game, press A to skip the cutscene.
![1](https://user-images.githubusercontent.com/25362478/28617773-716f2bca-720a-11e7-948d-79c7398beb0f.PNG)

Log file here: 
[log.txt](https://github.com/citra-emu/citra/files/1176362/log.txt)
(note that the game uses GS, but it doesn't affect this glitch.)

**Comment by Demos25** [comment]
3d-fun branch fixing it

**Comment by benderscruffy** [comment]
still happens in the latest nightly
![fire](https://user-images.githubusercontent.com/2696404/33226173-4376a4c4-d1c2-11e7-897d-b162197f6632.PNG)

**Comment by wwylele** [comment]
Fixed by #3281 as reported so closing. Feel free to reopen if it is not the case.
