### ISSUE TITLE
Android/iOS

### ISSUE THREAD

**Issue by dericot18** [citra-emu/citra#2851]
Can we start working on the Citra 3ds for Our High graphics and High performance phones? I noticed on the download versions page that there is a notice saying "Currently there are no Android/IOS versions of Citra and I and probably a ton of people would like to see this on our high graphics and performance phones. I have a Samsung Galaxy S8+, meaning it has Snapdragon chipset 835 and can run anything at a very high potential. IPhone 7 and 7 plus should have around the same performance without any issues. You guys should start there with high performance Android Nougat 7.0 devices and Ios 10 and then make your way to low performance devices.

**Comment by j-selby** [comment]
This has been asked countless times, both on the forums and by misusing this issue tracker (which you are doing). The answer is no, not at this time - phones are not powerful enough, and there are a crazy amount of things that need porting.

---

This isn't a request forum, this is a bug tracker. Requesting to close.

**Comment by MerryMage** [comment]
Nobody's currently working on this.
