### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dericot18** [citra-emu/citra#2852]
I am having issues with the games: Pokémon Moon, Pokémon X and Y. With Pokémon X and Y, the emulator just gives me a black screen. It is decrypted, but I don't see why there is a black screen on those two games, but when I play Pokémon Moon on the other hand just is lagging. Pokémon Moon shows good, but yeah, it's a very big lagging issue with that. I'm using the Bleeding edge version, so it should've been working just fine. I also get an error stating that Citra encountered a fatal error when playing Pokémon X.  With Pokémon Y, I get an error stating that the 3ds shared fonts aren't there. I tried to continue to load Y, but that's what I get. I haven't received those errors on the previous versions of bleeding edge,but they still came up as a black screen.

**Comment by RavenHome1** [comment]
use the forums not github please

https://community.citra-emu.org/

or straight up read the FAQ because this over asked to death issue is solved there 

https://citra-emu.org/wiki/faq/

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/
