### ISSUE TITLE
i have an issue . with whatever citra im using , when i try to open a pokemon game i got an error let me give you a screenshot

### ISSUE THREAD

**Issue by vacume21** [citra-emu/citra#2853]

**Comment by vacume21** [comment]
![error citra](https://user-images.githubusercontent.com/30601577/28791166-30cf977a-7634-11e7-8da3-e9d2f263ab0d.png)

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests.https://community.citra-emu.org/
