### ISSUE TITLE
Build on Arch Linux fails with undefined reference to `inflateValidate@ZLIB_1.2.9'

### ISSUE THREAD

**Issue by JuanPotato** [citra-emu/citra#2854]
Tried both debug and release, installed all the packages states at the beginning of the guide.
I was running 
```
mkdir build && cd build
cmake ../
make
sudo make install
```

make crashes with 

```
[ 94%] Linking CXX executable tests
/usr/lib/libpng.so: undefined reference to `inflateValidate@ZLIB_1.2.9'
```
[full log](https://pastebin.com/raw/NR6zwMeU)

Going off of other online resources I'd guess this is an issue with zlib not being properly linked. (I already have zlib installed) but I am not familiar enough with cmake to know how to try to fix that.

I have only tested with the latest commit as of posting this issue `035716d57bfc2142779e421ee242efc0d51059f6`

I am running fully updated Arch Linux.

**Comment by linkmauve** [comment]
What happens when you build from the citra-git package in AUR?  Any reason you are building manually instead of using it?

**Comment by JuanPotato** [comment]
same thing happened. which is why I tried doing it manually to see if anything different would happen

**Comment by JuanPotato** [comment]
Ayy I managed to get progress. I ran `cmake -DCMAKE_CXX_FLAGS="-L/usr/lib -lz" ../` instead of `cmake` (based off of https://serverfault.com/a/831681) and I got passed that. Then I crashed at 100%

new logs

```
In file included from /home/juan/Programming/citra/build/src/citra_qt/citra-qt_autogen/moc_compilation.cpp:2:0:
/home/juan/Programming/citra/build/src/citra_qt/citra-qt_autogen/EWIEGA46WW/moc_bootmanager.cpp:9:10: fatal error: ../../../../../../../Documents/Programming/citra/src/citra_qt/bootmanager.h: No such file or directory
 #include "../../../../../../../Documents/Programming/citra/src/citra_qt/bootmanager.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/citra_qt/CMakeFiles/citra-qt.dir/build.make:703: src/citra_qt/CMakeFiles/citra-qt.dir/citra-qt_autogen/moc_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1273: src/citra_qt/CMakeFiles/citra-qt.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
make  285.39s user 20.55s system 99% cpu 5:08.51 total
```

[full logs](https://pastebin.com/raw/cHcq504G)

**Comment by JuanPotato** [comment]
I'm at least 100% the file exists

**Comment by j-selby** [comment]
You shouldn't need any workarounds on Arch - I can build it just fine. Could we see:
gcc version
g++ version
cmake version
full build log (on Pastebin)

Make sure you have run `pacman -Syu` recently, and have `libpng` installed.

**Comment by JuanPotato** [comment]
@j-selby Yeah I am more than willing to admit that my installation on my desktop is really screwy. On my laptop this worked first try. Even though I installed Arch on my desktop much later than my laptop, and I _should_ have had more experience. zsh is my shell, filesystem isn't anything special.

 * gcc - 7.1.1
 * g++ - 7.1.1
 * cmake 3.8.2

I included the build log in the [first message](https://pastebin.com/raw/NR6zwMeU), but I might have left something out that you need or I'm just not sending the right thing.

**Comment by j-selby** [comment]
That log didn't include CMake - likely inconsequental, but still would be good to get a look at.

**Comment by j-selby** [comment]
Do you also have `zlib` installed?

**Comment by JuanPotato** [comment]
If it was in the beginning list of dependencies then yes, but otherwise
you'll have to wait until I wake up for me to get back and give you the
logs. Thanks for helping out. I appreciate it

**Comment by hcorion** [comment]
I just built citra on latest master on Arch Linux.

**Comment by JuanPotato** [comment]
I do have zlib installed.

[cmake and make output](https://pastebin.com/raw/xRTgJ67j)

**Comment by hcorion** [comment]
Have you tried doing a Release build?
`cmake ../../ -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"`
Also, make sure you've updated your submodules.
`git submodule update --init --recursive`

**Comment by hcorion** [comment]
Something also seems strange with your libpng/zlib, can you run
`md5sum /usr/lib/libpng.so`
and 
`md5sum /usr/lib/libz.so`?
Mine are
```shell
$ md5sum /usr/lib/libpng.so
c74688d5738c12e6e700d822d38f0795  /usr/lib/libpng.so
```
and
```shell
$ md5sum /usr/lib/libz.so  
c7e8411b592892bbb93adc5598bdad57  /usr/lib/libz.so
```
on latest 64-bit Arch Linux.

```shell
$ uname -a
Linux zion-linux-pc 4.12.3-1-ARCH #1 SMP PREEMPT Sat Jul 22 15:32:02 UTC 2017 x86_64 GNU/Linux
```

Here is a dump of my CMakeCache.txt: https://gist.github.com/c3de7a078864d8485dd2120d8e3b092e

**Comment by JuanPotato** [comment]
git modules are up to date, I had cloned the repo recursively today and I ran the update command just to be sure.

Here are the checksums.
```
% md5sum /usr/lib/libpng.so
c74688d5738c12e6e700d822d38f0795  /usr/lib/libpng.so
```
and
```
% md5sum /usr/lib/libz.so
c7e8411b592892bbb93adc5598bdad57  /usr/lib/libz.so
```

seems to be a match.

```
% uname -a
Linux hasan_desktop 4.12.3-1-ARCH #1 SMP PREEMPT Sat Jul 22 15:32:02 UTC 2017 x86_64 GNU/Linux
```

[Release build cmake and make logs](https://pastebin.com/LRdLy88A) and [CMakeCache.txt](https://pastebin.com/raw/m0iKBFk4)

**Comment by hcorion** [comment]
I think I found the issue.
After diffing your CMakeCache.txt, and my CMakeCache.txt, I found that
your citra is trying to link against a custom zlib, here:
```
	ZLIB_LIBRARY_RELEASE:FILEPATH=/usr/local/lib/libz.so
```
but mine is trying to link against system zlib.
```
ZLIB_LIBRARY_RELEASE:FILEPATH=/usr/lib64/libz.so
```
It looks like you've got a custom zlib installed into /usr/local/lib/libz.so

**Comment by hcorion** [comment]
Also, I'd recommend building citra with `USE_SYSTEM_CURL` (at least for Arch Linux) because otherwise it'll install a libcurl lib into `/usr/local/lib`, and Arch's curl is kept up-to-date anyway.

**Comment by JuanPotato** [comment]
used `find` to find any other files that were made on the same day as `/usr/local/lib/libz.so` (there are tons of other libs there with the same date) and it was my attempt at building telegram desktop from source. Wow. 

This probably fixes the issue I had here https://github.com/telegramdesktop/tdesktop/issues/3666

removing the files and rebuilding.

**Comment by hcorion** [comment]
You might want to remove your CMakeCache.txt before the rebuild
just do `cmake ../ -DUSE_SYSTEM_CURL=ON -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"`

**Comment by hcorion** [comment]
Or, y'know, just use the AUR: https://aur.archlinux.org/packages/citra-qt-git/

**Comment by JuanPotato** [comment]
debug mode didnt work. I got `/bootmanager.h: No such file or directory` as I said up top. But compiling from aur worked. Thanks again for all your help.

**Comment by hcorion** [comment]
:+1: Glad you could get it solved!
