### ISSUE TITLE
Citra quit unexpectedly

### ISSUE THREAD

**Issue by djadwad** [citra-emu/citra#2896]
Every time i try to load pokemon alpha sapphire or any other rom into citra the app always crashes and it says "Citra quit unexpectedly."
I am using a mid 2014 macbook pro, my processor is 2.6 GHz Intel Core i5, memory 8GB 1600 MHz DDR3, Graphics Intel Iris 1536 MB
 
this is what my terminal says when it crashes
[   0.000000] Frontend <Info> citra_qt/main.cpp:BootGame:382: Citra starting...
[   0.035897] Loader <Warning> core/loader/loader.cpp:GetLoader:137: File /Users/angadstuff/Desktop/Pokemon Alpha Sapphire.3ds has a different type than its extension.
[   0.035919] Core <Critical> core/core.cpp:Load:83: Failed to determine system mode (Error 2)!
Segmentation fault: 11
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/
