### ISSUE TITLE
tengo problemas al jugar al citra

### ISSUE THREAD

**Issue by rashid5327** [citra-emu/citra#2913]
---> hola
tengo un problema cuando entro  a jugar cualquier juego suena la música pero se ve la pantalla de color gris ayuda porfavor
![captura de pantalla 3](https://user-images.githubusercontent.com/31538945/29968278-354e4788-8f1b-11e7-8a9c-4174c67ebddd.png)

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/
