### ISSUE TITLE
Majora Mask 3d fails to load with HW.Memory errors

### ISSUE THREAD

**Issue by marouf33** [citra-emu/citra#2916]
Hi, I tried loading Majora's Mask 3D with latest nightly build (415d3c0) . It fails with an infinitley repeating HW.Memory error

I have attached the log here : https://pastebin.com/kAmWbTGD

**Comment by RavenHome1** [comment]
[   1.007673] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Init:1004: Unable to load shared font

dump the home folder

https://citra-emu.org/wiki/dumping-system-archives-and-the-shared-fonts-from-a-3ds-console/

also github is for devolopers use, please use the forums for further questions

https://community.citra-emu.org/

**Comment by wwylele** [comment]
Retroactive comment: this looks more like wrong region/language settings (and probably a modified ROM cause region detection failure). But anyway, please go to the forum for support
