### ISSUE TITLE
Avoid performance dip when loading/unloading CROs (e.g. Mario & Luigi - Dream Team)

### ISSUE THREAD

**Issue by whyisthisfieldhere** [citra-emu/citra#2924]
Howdy,

I've noticed Mario & Luigi - Dream Team stutters quite badly every time you enter or leave the menus.
I've checked and this happens because currently the code in ldr_ro.cpp clears the **entire** instruction cache each time any cro is loaded or unloaded, instead of clearing just the cro's address range that was updated.

I've tweaked the code to get the ldr_ro code to call Jit::InvalidateCacheRange with the appropriate address range instead of Jit::ClearCache. 
This caused a crash so I've had to additionally add a hack in PerformCacheInvalidation to only do jit_state.ResetRSB and block_of_code.ClearCache when a full cache invalidation was requested.
This seemed to have cleared the stuttering in the game (after the first time, of course).

While the hack I've made in PerformCacheInvalidation might introduce memory leaks or even bugs, it shouldn't be too difficult to turn it into proper bugfree code.

Since I don't plan to do this myself, I'm opening an issue so others can.

**Comment by MerryMage** [comment]
> add a hack in PerformCacheInvalidation to only do jit_state.ResetRSB and block_of_code.ClearCache when a full cache invalidation was requested.

Good catch on the latter, that's a mistake. I'm not convinced that jit_state.ResetRSB shouldn't be called, however.

**Comment by whyisthisfieldhere** [comment]
@MerryMage : entirely possible - I didn't check all possibilities and didn't try too hard to figure out what ResetRSB does 😛

**Comment by MerryMage** [comment]
Feel free to submit a PR. I've pushed MerryMage/dynarmic@b992e5f8ecd89a265cfc6197a46a854d1ec2ca1a which should hopefully fix that side of things.

**Comment by whyisthisfieldhere** [comment]
I don't currently plan to submit PRs, sorry - hopefully someone else will choose to.
Thanks for your side of the fix, though.

**Comment by MerryMage** [comment]
#2925 contains an initial implementation. However performance is abysmal, faster invalidation is required.

**Comment by B3n30** [comment]
according to @Hexagon12 this is fixed by #3227
