### ISSUE TITLE
Performance improvement low-hanging fruit - use of glBufferData

### ISSUE THREAD

**Issue by whyisthisfieldhere** [citra-emu/citra#2926]
Currently gl_rasterizer.cpp calls glBufferData to update the uniform & array buffers in RasterizerOpenGL::DrawTriangles.
This is inefficient - it's considerably faster (at least on my nvidia graphics card) to use glBufferSubData as much as possible instead. (This is because glBufferData recreates the buffer in some way while glBufferSubData just copies to it)
For the uniform buffer, you can just call glBufferData once in the constructor and call glBufferSubData each time it needs to be updated.
For the array buffer, it's probably best to keep track of the size of the buffer and only call glBufferData if the data you wish to copy to the buffer is larger than the buffer's size, otherwise call glBufferSubData.

(I don't currently plan on making PRs, so I'm opening this as an issue so that others may PR this if they so choose)

(EDIT: To be slightly more helpful, here's my fork with this change included: https://github.com/whyisthisfieldhere/citra )

**Comment by B3n30** [comment]
I just tested this 'improvement' with Super Smash Bros. and New Super Mario Bros 2. It didn't increase the speed, but instead lowered the speed in some parts of about 10%. 

I didn't test the two improvements separate from each other.

**Comment by whyisthisfieldhere** [comment]
Hmm - I guess this was too naive of me. I saw a nice improvement in slower scenes of Mario-Luigi-Dream-Team and though the improvement would be universal.

Though when I try super-smash-bros, I get the same speed either way, so the effect my also depend on the graphics card/etc.

Maybe there's still some core idea here that'd be useful to look into (E.g. by someone more opengl-experienced than me), but for now I'm closing the issue.

Thanks for taking a look.
