### ISSUE TITLE
canary 31 - error loading list games

### ISSUE THREAD

**Issue by elcorsico** [citra-emu/citra#2931]
hi
thanks for canary , but now crash in loading list games
thanks resolve this devs 
;-)

**Comment by j-selby** [comment]
Canary is a unsupported, testing version of Citra. Issues with these should be redirected to the forums, which can be found here: https://community.citra-emu.org/

---

Requesting to close.

**Comment by wwylele** [comment]
Retroactive comment: for issues found in canary, please check the merge list of the build and find out which PR causes the problem, and report it under the PR.
