### ISSUE TITLE
Performance of FromAttributeBuffer

### ISSUE THREAD

**Issue by huwpascoe** [citra-emu/citra#2932]
A disproportionate amount of execution time is spent in Pica::Shader::OutputVertex::FromAttributeBuffer.

![perf](https://user-images.githubusercontent.com/1812087/30521158-014290c6-9bb3-11e7-863d-84ad43ca0035.png)

**Comment by wwylele** [comment]
Can this just be caused by a large amount of vertices to process? I don't see any obvious reason that makes it inefficient.

Or probably the usage of `union` like that can be an issue?

**Comment by huwpascoe** [comment]
@wwylele There is potential for a nice performance gain if someone can find a way to make it faster.

**Comment by urdaneta09** [comment]
how much amount of execution time is spent now  with #2933
