### ISSUE TITLE
Minecraft n3ds edition crashes

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#2934]
Hello, I dumped the game,( .3ds file) put it on my PC, launched the game and it gave this error.
Not really playable.
Minecraft new Nintendo 3DS edition, 
Title id: 00040000001B8700
Nightly Build - 255fd87
![screenshot 167](https://user-images.githubusercontent.com/16990273/30523071-e3feb06c-9bda-11e7-808e-ec0e4de3b1bf.png)

(specs: I7 3635QM
AMD radeon hd8700
8GB RAM)

**Comment by Calvineries** [comment]
same

**Comment by Jhon591** [comment]
Game is asking for this
https://github.com/Jhon591/citra/commit/85696efa5b23784dfe33aea59db42116095ad327

But other ongoing issue is either with saving, are same issue as mario maker.

**Comment by hyarsan** [comment]
The same thing happens to me.

**Comment by FearlessTobi** [comment]
Fixed when enabling N3DS mode in latest Nightly.
