### ISSUE TITLE
Citra-qt process doesn't end when closing the window

### ISSUE THREAD

**Issue by andreieichler** [citra-emu/citra#2935]
When closing citra-qt window after starting a game, it doesn't exit the citra-qt process.
It only happens when a game is running, if one doesn't start a game, closing the window ends the process normally

Steps to reproduce:

1) Execute citra-qt binary
2) Select and start a game
3) Close the window through the window decoration
4) Click OK on "Are you sure you want to close Citra? pop-up
5) The process keep running

Citra Version: HEAD 255fd87
OS Info: Linux 4.13, Manjaro KDE 17.0.5

**Comment by jroweboy** [comment]
@andreieichler it sounds like it is messing up when attempting to submit telemetry. Linux has been having problems with telemetry submissions recently. Are you compiling citra yourself or using the binary download provided on the website?

**Comment by andreieichler** [comment]
I'm using the provided binary from download page, should I try an older version that doesn't contains the telemetry change to see if that happens?

**Comment by andreieichler** [comment]
@jroweboy even using older versions, the error persists.

The workaround to achieve the correct behavior is to stop the emulation, so I am back to the choose game window, then I can close the window and the process exit normally

**Comment by hcorion** [comment]
I've also noticed this issue on Arch, happens on every run, I'm using the `citra-qt-git` package from the AUR.

**Comment by SleepingSnakezzz** [comment]
We've had no further reports of this. Given the large amount of changes to Citra since this post, this was likely fixed at some point. Will reopen if we get any new reports.
