### ISSUE TITLE
Yo-kai Watch 2 - Incomplete map

### ISSUE THREAD

**Issue by valentinvanelslande** [citra-emu/citra#2938]
Using latest nightly
Same issue #2940
The character dies upon touching and revives in another place (soft reset with auto save?) 

Specs:
Intel Core i5-7200U
Intel HD Graphics 620
Windows 10 15063

Citra:
![citra](https://user-images.githubusercontent.com/22228082/30609838-0da4d5aa-9d42-11e7-9ec6-05d1d89b81d7.png)

3DS:
![3ds](https://user-images.githubusercontent.com/22228082/30609818-00c7d972-9d42-11e7-9bb6-b6e6e201ad76.PNG)

Log: https://pastebin.com/AGMQjutu

**Comment by wwylele** [comment]
The log is incomplete. Please upload a full log

**Comment by acnleditor2** [comment]
log is complete!!!

**Comment by Hexagon12** [comment]
`[   1.524112] Render.OpenGL <Warning> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:472: API PERFORMANCE 131218: Program/shader state performance warning: Fragment Shader is going to be recompiled because the shader key based on GL state mismatches.`

This could be related?

**Comment by acnleditor2** [comment]
[Temporal fix](https://community.citra-emu.org/t/yo-kai-watch-2-incomplete-map-github-issue-2938-temporal-fix/3951)

**Comment by chris062689** [comment]
Was this issue fixed?

**Comment by valentinvanelslande** [comment]
yes

**Comment by EliwoodSSB** [comment]
how to resolve this problem?
