### ISSUE TITLE
inazuma elven go light and shadow - blue area, unable to advance

### ISSUE THREAD

**Issue by alvan12** [citra-emu/citra#2940]
Citra Version : citra nightly | head - 5880771 

After the start of the game in the school area, when you enter the path to the soccer club, that happens.
The entire area turns blue, some npcs appear in different proportions and you can't advance to the next area, you can only go back

Specs:
Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 CPUs), ~1.9GHz
intel(r) hd graphics family
windows 10 pro x64 bit

Citra:
![image](https://user-images.githubusercontent.com/31838249/30624642-d1e409a8-9de8-11e7-9af7-7304d720dcdb.png)

3DS:
![image](https://user-images.githubusercontent.com/31838249/30624688-15d8883c-9de9-11e7-815d-a36a8dd7ef2b.png)

Log: 
https://pastebin.com/ZVbpLWEM

**Comment by KlowN8** [comment]
Same Problem

**Comment by KlowN8** [comment]
Same Problem
[log.txt](https://github.com/citra-emu/citra/files/1338462/log.txt)
I don't know if that log is correct but there it is.

**Comment by benderscruffy** [comment]
@alvan12 is this still a problem ???

**Comment by alvan12** [comment]
@benderscruffy already fixed

**Comment by benderscruffy** [comment]
@alvan12  fixed in the latest nightly ??
if so this can be closed then
