### ISSUE TITLE
Super Mario 3d Land fails now and will not ingame anymore.

### ISSUE THREAD

**Issue by Luffykun007** [citra-emu/citra#2960]
Super Mario 3d Land fails now when trying to start the game in the last Citra Canary 55

![capturar](https://user-images.githubusercontent.com/26087621/30842155-aac4550e-a256-11e7-88c3-c2e05cbbe6fd.JPG)

LOG: 
[Super mario 3D Land.zip](https://github.com/citra-emu/citra/files/1331799/Super.mario.3D.Land.zip)

P.S: the problem appears to be caused by #2953

**Comment by wwylele** [comment]
Please report Canary issue to its relevant PR, thank you!

**Comment by Subv** [comment]
Could you please test with Canary 56 after it finishes building?

**Comment by Luffykun007** [comment]
Yes, I'll test thank you.
