### ISSUE TITLE
Mario & Luigi: Paper Jam crash when entering battle with Paper Mario

### ISSUE THREAD

**Issue by Truhard** [citra-emu/citra#2964]
After the Goomba stack with Paper Mario in the party, encountering any enemy, paper or not, the emulator crashes. I have an Intel i7-7200U 2.5GHz with Intel HD Graphics 520/620.
This is the best log I can get before Citra crashes. This is similar to other issues other people have had, but I don't think it is the same.
https://pastebin.com/pR3RD79q
EDIT: Tested it on latest, 0d42706

**Comment by chris062689** [comment]
Was this issue resolved by one of the latest nightlies?
