### ISSUE TITLE
"libcurl.so.4: version `CURL_OPENSSL_3' not found"  In Citra nightly

### ISSUE THREAD

**Issue by geplus** [citra-emu/citra#2976]
Hi,
I tried the latest citra nightly on Manjaro/Arch Linux, but I have the error : " /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /[folder of citra]/cita-qt)

I think this error could be fixed compiling citra as described in these links:

https://github.com/nodegit/nodegit/issues/1225
https://bbs.archlinux.org/viewtopic.php?id=213870

**Comment by hcorion** [comment]
Just
```shell
sudo pacman -S libcurl-compat
```
should work

**Comment by geplus** [comment]
I've already tried, but it  doesn't work: `libcurl.so.4` is a symlink of `libcurl.so.4.4.0`, that is a library of `curl` package.
It's definitively a compiling issue, as reported in the two links I've posted.

**Comment by SuperNascher** [comment]
@geplus Try to open the Citra with: `LD_PRELOAD=/usr/lib/libcurl.so.3 ./citra-qt`.

**Comment by B3n30** [comment]
The problem here is that citra requires openssl, but Manjaro/Arch Linux seems to use a libcurl that is build with gnutls. I don't know if there is a version for Manjaro/Arch Linux available, that is build with openssl, but this is required to use the nightly. 

Another solution is to build citra for your own following https://github.com/citra-emu/citra/wiki/Building-For-Linux. But this will result in the fact, that you can't use the web-services

**Comment by SuperNascher** [comment]
@B3n30 libcurl-compat is builded with openssl. The gnutls version is builded seperatly as `libcurl-gnutls`.

**Comment by geplus** [comment]
@SuperNascher: `LD_PRELOAD=/usr/lib/libcurl.so.3 ./citra-qt` solved the issues, now citra runs correctly.
Thank you so much.
My counsil is to build with gnutils for Arch people, or insert this command in a script for runs citra with a duble click, and add it in the downloadable archives of the builds.

**Comment by tswaggy007** [comment]
I have the same problem

**Comment by hcorion** [comment]
Install libcurl-compat and run citra with `LD_PRELOAD=/usr/lib/libcurl.so.3 ./citra-qt` @tswaggy007

**Comment by B3n30** [comment]
We don't use curl anymore, so I assume this can be closed

**Comment by timhughes** [comment]
https://github.com/julianoappelklein/hokus/issues/31
