### ISSUE TITLE
"The size of the UniformData structure has changed"

### ISSUE THREAD

**Issue by huwpascoe** [citra-emu/citra#2978]
This failed for me, dunno if legit.
gl_rasterizer.h:157
```
    static_assert(
        sizeof(UniformData) == 0x470,
        "The size of the UniformData structure has changed, update the structure in the shader");
```

**Comment by wwylele** [comment]
Please provide more information:
 - What is the system and the compiler?
 - did you change the code?

**Comment by huwpascoe** [comment]
MSVC. I didn't change the code.

**Comment by wwylele** [comment]
IntelliSense false positive. Closing
