### ISSUE TITLE
Nintendo 3DS NAND on Citra

### ISSUE THREAD

**Issue by WodsonKun** [citra-emu/citra#2979]
How I can setup my 3DS NAND on Citra?

- Using lastest Citra nightly release (HEAD-9c123c2)
- Using lastest Nintendo 3DS System version (11.6.0-39U)

**Comment by mailwl** [comment]
i think, this forum for developers

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Requesting to close.
