### ISSUE TITLE
Flipnote Studio 3D US: Crash on boot

### ISSUE THREAD

**Issue by khang06** [citra-emu/citra#2980]
Log: https://hastebin.com/icugikuyoy.xml
Commit: 30fabc4
Reproduction Steps: Run the application, see a crash.

**Comment by mailwl** [comment]
what is it? if homebrew, send to my mail, mailwl@gmail.com, i will look via IDA debugger

**Comment by khang06** [comment]
http://flipnotestudio3d.nintendo.com/

Available as a My Nintendo reward, but you can't buy it from the e-Shop.

**Comment by mailwl** [comment]
something wrong with memory - assert on trying to call svc 1F - MapMemoryBlock. 
but more important - it appear while initializing ErrEula applet,  
My log is differs:

> [ 128.378864] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:733: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001, input_addr=0x0FFFFF08, output_addr=0x0FFFFF0C
> [ 128.381416] Service.FS <Warning> core\file_sys\ncch_container.cpp:FileSys::NCCHContainer::LoadOverrides:238: Loaded NCCH C:\Users\wl\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00014002/content/00000000.app is tainted, application behavior may not be as expected!
> [ 128.384058] Service.FS <Warning> core\file_sys\ncch_container.cpp:FileSys::NCCHContainer::ReadOverrideRomFS:377: File C:\Users\wl\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00014002/content/00000000.app.romfs overriding built-in RomFS
> [ 128.436245] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::AcquireRight:702: called
> [ 128.436815] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::RegisterInterruptRelayQueue:397: called, flags=0x00000001
> [ 128.645213] Service.FS <Warning> core\hle\service\fs\fs_user.cpp:Service::FS::GetArchiveResource:868: (STUBBED) called Media type=0x00000002
> [ 129.017696] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:148: Firmware hash: 0x348ac2f23aa20bca
> [ 129.019217] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:152: Structures hash: 0x93e48663943cad39
> [ 129.020030] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::LoadComponent:157: (STUBBED) called size=0xC288, prog_mask=0x000000FF, data_mask=0x000D00FF, buffer=0x003BBA68
> [ 129.022099] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::RegisterInterruptEvents:248: Registered type=2, pipe=2, event_handle=0x000E002D
> [ 129.022953] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::GetSemaphoreEventHandle:174: (STUBBED) called
> [ 129.024471] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphoreMask:469: (STUBBED) called mask=0x00002000
> [ 129.025421] Audio.DSP <Info> audio_core\hle\pipe.cpp:DSP::HLE::PipeWrite:134: Application has requested initialization of DSP hardware
> [ 129.026571] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphore:271: (STUBBED) called
> [ 129.028082] Service.DSP <Warning> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::SetSemaphore:271: (STUBBED) called
> [ 129.180021] Service.FS <Warning> core\file_sys\ncch_container.cpp:FileSys::NCCHContainer::LoadOverrides:238: Loaded NCCH C:\Users\wl\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/000400db/00010302/content/00000000.app is tainted, application behavior may not be as expected!
> [ 129.182843] Service.FS <Warning> core\file_sys\ncch_container.cpp:FileSys::NCCHContainer::ReadOverrideRomFS:377: File C:\Users\wl\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/000400db/00010302/content/00000000.app.romfs overriding built-in RomFS
> [ 129.184004] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:733: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001, input_addr=0x0FFFFFA8, output_addr=0x0FFFFFAC
> [ 129.188829] Service.SRV <Warning> core\hle\service\sm\srv.cpp:Service::SM::SRV::Subscribe:146: (STUBBED) called, notification_id=0x209
> [ 129.481158] Service.FRD <Warning> core\hle\service\frd\frd.cpp:Service::FRD::SetClientSdkVersion:158: (STUBBED) called, version: 0x070202C8
> [ 129.482394] Service.FRD <Warning> core\hle\service\frd\frd.cpp:Service::FRD::GetMyPresence:35: (STUBBED) called
> [ 129.482729] Service.FRD <Warning> core\hle\service\frd\frd.cpp:Service::FRD::GetMyScreenName:106: (STUBBED) called
> [ 129.556996] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:95: unknown / unimplemented function 'Initialize': port=nim:aoc
> [ 129.559452] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:95: unknown / unimplemented function 'GetPatchTitleInfos': port=am:app, cmd_buff[1]=0x1, cmd_buff[2]=0x1, cmd_buff[3]=0x8A, cmd_buff[4]=0xFFFFF08, cmd_buff[5]=0x18C, cmd_buff[6]=0xFFFFEE8
> [ 129.560938] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:95: unknown / unimplemented function 'ReplySleepQuery': port=APT:A, cmd_buff[1]=0x300, cmd_buff[2]=0x0
> [ 129.561597] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::AppletUtility:733: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001, input_addr=0x0FFFFEA8, output_addr=0x0FFFFEAC
> [ 129.562172] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:95: unknown / unimplemented function 'SaveVramSysArea': port=gsp::Gpu
> [ 157.792122] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:Service::GSP::ImportDisplayCaptureInfo:687: called
> [ 188.193421] Debug <Critical> core\hle\kernel\vm_manager.cpp:Kernel::VMManager::SplitVMA::<lambda_0e09dc1e8b9acb1b5394a0debc94f83e>::operator ():287: Assertion Failed!

**Comment by mailwl** [comment]
dumb stubbing function `GetPatchTitleInfos` let the game go (at least at start :) )

try this:
https://github.com/mailwl/citra/tree/flipnote
