### ISSUE TITLE
I need software keyboard as fast as possible

### ISSUE THREAD

**Issue by acnleditor2** [citra-emu/citra#2987]

**Comment by j-selby** [comment]
The quicker you get working on it, the quicker it will get implemented. This is not a feature request forum, this is a bug tracker.

---

Requesting to close.

**Comment by acnleditor2** [comment]
with https://github.com/jroweboy/citra/blob/swkbd/src/core/hle/applets/swkbd.cpp and https://github.com/jroweboy/citra/blob/swkbd/src/core/hle/applets/swkbd.h works.

**Comment by acnleditor2** [comment]
with
https://github.com/jroweboy/citra/blob/swkbd/src/core/hle/applets/swkbd.cpp
https://github.com/jroweboy/citra/blob/swkbd/src/core/hle/applets/swkbd.h
works perfectly
