### ISSUE TITLE
Symbols problems on future swkbd implementation?

### ISSUE THREAD

**Issue by acnleditor2** [citra-emu/citra#2994]
Suddenly it occurred to me to put this in the code:

std::cout << "¿ ¡ ´´´´ ````  ¨" << std::endl;

But the result was: ┬┐ ┬í ┬┤┬┤┬┤┬┤ ```` ┬¿

if i put symbols of these on a software keyboard: ¿ ¡ ´´´´ ````  ¨
the game crashes.
so when the keyboard is implemented, you can not put those symbols.
or yes?

**Comment by j-selby** [comment]
This is not related to any Citra code -the software keyboard implementation you keep talking about is going to be different then other implementations, and may not even be merged.

---

Please close this.
