### ISSUE TITLE
Citra Nightly Build - 74d4050 Not responding

### ISSUE THREAD

**Issue by Bharath18121** [citra-emu/citra#2998]
Citra Nightly Build - 74d4050 is the citra build version i downloaded at latest...Then i downloaded a 
Pokemon x (region free) rom..I then loaded it in citra-qt..Then the black screen showed some crypting for 11 lines with mixed colours of pale blue,red,yellow and violet..Then a dialogue appeares stating that 
citra-qt has stopped working..Then i tried to open citra....a=After i double click on the citra icon a black dialogue box appears for a split second and disappears..But I right clicked on the rom and selected open with citra..Then it opened but then showed the same problem mentioned.....I would like to why is there such a problem and i think this is a unique problem..maybe this is because the rom i downloaded is not good.....Anyway i wantit clarified...Anyways Ur team is doing a wonderful job and keep doing it...

Best Wishes,
From,
Bharath
 
Curriclam Vitae..

MY PC`S SPECS

PROCESSOR:  Intel(R)Core(TM) i5-5200 CPU
INSTALLED MEMORY(RAM):8GB
OPERATING SYSTEM:x64 Based Processor,x64 Based Operating System

I have intel graphics..Windows 10..Dell laptop.........

====================================================

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of Citra you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

--->

**Comment by Bharath18121** [comment]
Its the same with canary build too

**Comment by wwylele** [comment]
This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://community.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build, or
 - use pirated copies of the games, 3DS BIOS files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid

**Comment by Bharath18121** [comment]
Thank Youu...My dear sir...And sorry if i did anything wrong...
