### ISSUE TITLE
Pokemon X and Y sound issue

### ISSUE THREAD

**Issue by J-Eagle** [citra-emu/citra#3009]
The issue is that there's very several sound effects that play but very poorly, menu sound effects don't working and no background song playing. This was ever since the start of citra until now.

Version i use: citra-windows-mingw-20171015-e9d1e8c

More then that, the graphics performance is very bad for high specs pc (with intel core i7, Geforce GTX 1050 TI, 16GB RAM)

**Comment by Soban44444** [comment]
X and Y are currently very broken and don't work on Citra and Citra is not optimized.

**Comment by Jhon591** [comment]
Not sure Heard some think of it using a Brass Band audio.. Well it sounds like it on a real 2/3ds, PIP3 branch fixed some of the missing sounds, are AAC audio cannot be implemented at this time..

**Comment by khang06** [comment]
Music doesn't play because Citra does not yet support AAC audio. Also, I'm pretty sure this is already known.

**Comment by J-Eagle** [comment]
So they working on it to make it work?

**Comment by Jhon591** [comment]
Maybe DSP LLE service.., but would run heavy on the emulator maybe.

**Comment by Jhon591** [comment]
Maybe DSP LLE one of the (Core) was not fully added.. although LLE could be heavy of the emulator..

**Comment by esQmo** [comment]
Of course they are. I should be patient and wait, or as Citra is an open source projet, you can contribute if you have programming skills.

**Comment by J-Eagle** [comment]
Well i can wait for it, but the thing is that it's taking much time to solve it, and i don't have much programming skills unfortunately

**Comment by khang06** [comment]
This isn't going to make it any faster...

**Comment by Jhon591** [comment]
DSP LLE maybe.. but not added to test. nore i could do.

**Comment by MerryMage** [comment]
@wwylele patched the Pokemon Y DSP firmware (romfs:/sound/dspaudio.cdc) with the homemenu DSP fimware. This results in Pokemon Y on the 3DS having no background music but with sound effect followed by a freeze at the same location Citra freezes.

This suggests that this issue is likely due to the Pokemon Y DSP firmware behaving in a manner different to what our DSP HLE emulation currently behaves.

**Comment by wwylele** [comment]
Just to make it clearer

> no background music but with sound effect

I didn't go beyond the intro sequence, so I don't know if all sound effects are played (for example, I don't know about menu sound effects as @J-Eagle mentioned). I don't know if I missed some sound effect that is not played, either. However, I did try progressing the intro scene simultaneously on 3DS and on citra, and compare their audio output. In the part I have tested, the audio behaviour of 3DS (with DSP binary replaced) and citra perfectly matches: those which are played on citra are played on 3DS, and those which are not on citra are not on 3DS.

**Comment by WellBeSerious** [comment]
This is still an issue on Citra Nightly Updater #961 HEAD-f86c993 (2018-09-08)!!! Setting audio Output Engine and Audio Device to null didn't do anything, with 100% and 0% Volume!!!

**Comment by Dragios** [comment]
Fix with DSP LLE #4490

**Comment by wwylele** [comment]
DSP LLE is merged. Please continue to track this issue on while we fix DSP HLE.

**Comment by KostaSaizo7** [comment]
Isn't this fixed since  #4508 merged?

**Comment by J-Eagle** [comment]
Thanks for anyone for helping fixing this issue, i'm so excited ^^
