### ISSUE TITLE
Fire Emblem Warriors EU - Stuck on loading

### ISSUE THREAD

**Issue by Jhon591** [citra-emu/citra#3015]
##Just to bring this up for some one else.
https://community.citra-emu.org/t/fire-emblem-warriors-fix-on-new-builds/4283

Fire Emblem Warriors EU - Stuck on loading ?
---
It works on much older/older builds
Any Thoughts into why ?.., same issue also with JPN version.

![o54nbu5](https://user-images.githubusercontent.com/32848227/31774292-3b7637b4-b4dd-11e7-8706-0c68fd526015.jpg)
---
Last work on one off
https://mega.nz/#!ZaRj3QIC!8FCHOisXfnDC_6acXM6HST3hArvPqKYKq2nN8HqaVQE

**Comment by Jhon591** [comment]
[img]https://i.imgur.com/O54nbU5.jpg[/img]

**Comment by Soban44444** [comment]
Umm you aren't suppose to link unofficial builds and it is illegal files in it so .....

**Comment by Hexagon12** [comment]
This issue contains unofficial build downloads and a unreleased game issue. (The game releases on October 20th)

Requesting to close.
