### ISSUE TITLE
Fire Emblem Warriors J/EU - Stuck / Froze on loading ?

### ISSUE THREAD

**Issue by Jhon591** [citra-emu/citra#3018]
Just to bring this up for some one else.
https://community.citra-emu.org/t/fire-emblem-warriors-fix-on-new-builds/4283

Fire Emblem Warriors J/EU - Stuck / Froze on loading ?
---
It works on much older/older builds
Any Thoughts into why ?..  JPN version, EU tomorrow 

![675756](https://user-images.githubusercontent.com/32848227/31781796-4255d4e0-b4f1-11e7-870a-cbc31af0af17.jpg)

**Comment by RavenHome1** [comment]
please don't open up issues about games that are unreleased. this indicates downloaded games and piracy is not supported here

**Comment by masaki1988** [comment]
game release in japan at 28 september so its not piracy. Who want already play it or download.

**Comment by Jhon591** [comment]
I mean JPN, EU is tomoz so same issue.

**Comment by masaki1988** [comment]
So game came out in europe. I dump eshop version through my friend n3ds but still game not work on citra (((((. Its realy can t be fixed?. I realy want to play in this game but i don t have 3ds. My friend only agreed dump the game but he not give me to play it ((((

**Comment by B3n30** [comment]
Using a friends dump and you don't own it is still illegal. 

Since no dev owns the game, there is no way we can fix it. 

So I close it, till an appropriate (complete log, legal obtained game, etc) issue is opened

**Comment by Jhon591** [comment]
Then buy it on the eshop.

**Comment by mailwl** [comment]
looks like it's New 3DS only?

**Comment by Jhon591** [comment]
The JPN game new 3ds wont change a thing, enabled are disabled qt-config.ini , its the main Citra its self that has been broken over time, maybe a unimplemented service needs adding.

**Comment by Jhon591** [comment]
@mailwl yes, think so.

**Comment by Jhon5912** [comment]
A fix would be kind of, But I'm no pro for a work around. ?
https://github.com/Jhon5912/citra-1/commit/f2265cf94b3898633c267754f8d3ca45e6dd0a2d
