### ISSUE TITLE
QKeySequence::Cancel requires Qt 5.6

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#3023]
[This](https://github.com/citra-emu/citra/blob/master/src/citra_qt/main.cpp#L248) was introduced recently by the fullscreen feature. [The version requirement of this enum value is undocumented.](https://bugreports.qt.io/browse/QTBUG-54189)

This version requirement might be too high for some linux distros, where the shipped version are still around 5.2~5.5. Our CI, running Ubuntu 16.04, also uses Qt 5.5 (See #3022 for why it didn't report the error in the PR)

We can consider using other `QKeySequence` for this. Otherwise we need to explicitly note the version requirement in the building guide and upgrade the CI

**Comment by jroweboy** [comment]
Should be easy to just hardcode a value for escape instead of using the key sequence for it
