### ISSUE TITLE
Latest Nightly and Canary builds don't have any sound.

### ISSUE THREAD

**Issue by Hexagon12** [citra-emu/citra#3038]
Using both Nightly-aee8bf6 and Canary-c77463f

Sound is not present in both latest builds.

If the older build SDL2.dll file is copied over, the sound is back.

The issue is only related to MinGW builds.

**Comment by Dragios** [comment]
See https://github.com/citra-emu/citra/issues/3036#issuecomment-338834163

**Comment by MerryMage** [comment]
Related SDL2 issue: https://bugzilla.libsdl.org/show_bug.cgi?id=3858
Above comment is unrelated.

**Comment by jroweboy** [comment]
Should be fixed with #3047
