### ISSUE TITLE
Clicking "Verify" with valid credentials filled in on the "Web" tab causes Citra to crash

### ISSUE THREAD

**Issue by Hexagon12** [citra-emu/citra#3039]
Using both Nightly-aee8bf6 and Canary-c77463f

If someone would click "Verify" with all valid credentials filled in, it would crash Citra.

This error is applicable to MinGW builds only.

**Comment by jroweboy** [comment]
This is related to #3036 because appveyor decided to update msys2 without warning, the custom compiled curl will also need to be updated.

See: https://github.com/citra-emu/ext-windows-bin/tree/master/curl

**Comment by FearlessTobi** [comment]
This can be closed?
