### ISSUE TITLE
Delay when opening configuration menu

### ISSUE THREAD

**Issue by Colmines92** [citra-emu/citra#3049]
This is an issue that can not be seen by screenshots.
It happens when I change any setting via Emulator>Configure...
Citra keeps working but don't allows me to do anything (can't play, can't access any menu) for about 6-10 seconds.

I'm using Citra Nightly 377 b36f748.
This started happening from the first Canary releases.

**Comment by RavenHome1** [comment]
i see what you mean but for me the emulator freezes for less than a second, this might be because the emulator is applying the changes and it is taking longer to respond based on how powerful the machine is

**Comment by Colmines92** [comment]
My PC is very poor.
Intel Core-i3 2250
RAM: 4GB

I am using citra to play games for some time and with those specs there are games I can play smoothly, I finished TLoZ OoT, TLoZ MM, TLoZ LBW, some Etrians, Bravely Default-Second.

The case is this started happening with the first Canary releases, I though it would be fixed but it still happens.

Is it possible to make citra save/apply the settings and allow you to continue playing?

**Comment by esQmo** [comment]
Some issue.
Intel Core-i7 (Q740, 1.73 GHz)
8Gb RAM

**Comment by FearlessTobi** [comment]
I've stopped experiencing this or getting reports of this for a long time now, so I guess this is fixed. If not, the issue can be reopened.
