### ISSUE TITLE
Happy Home Designer freezes during opening

### ISSUE THREAD

**Issue by Chrisatsinnoh** [citra-emu/citra#3054]
I tried sending a support ticket to the Citra Community, but then they tell me to submit it here.
Here's what I said regarding my problem:

When I try to run Happy Home Designer in the latest Citra, it always causes the game to never continue during the opening, as the office chair appears to be empty and clicking on the Manual Option causes the game to freeze. How can I solve this?

System Information

Operating System: Windows 8.1
CPU: ??
GPU: ??
Citra Version (found in title bar): Latest Version
Game: Animal Crossing Happy Home Designer
Screenshot of Issue (include the full Citra window including titlebar):
https://i.imgur.com/vlnnlun.jpg3
Log: ??
<???>
Here's the log file of the problem (The [ 0.838167] Render.OpenGL video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:472: API PERFORMANCE 131218: Program/shader state performance warning: Fragment Shader is going to be recompiled because the shader key based on GL state mismatches. code seems to be causing the issue, but it's currently unknown. I did not use any 3rd parties for Citra.)
[log.txt](https://github.com/citra-emu/citra/files/1422655/log.txt)

**Comment by chris062689** [comment]
In order for your bug report to be useful, we need the full output of your log, along with the full game name and title ID. Along with CPU and GPU.

**Comment by Chrisatsinnoh** [comment]
Animal Crossing Happy Home Designer with a Title ID of 000400000014F100

My computer's CPU is an Intel Core i7-4800MQ CPU @2.70GHz 2.70 GHz and its GPU is an NVIDIA GeForce, I believe. A GTX 770M with 4095 MB.

The full output of my log in is the text file above.

**Comment by mailwl** [comment]
no matter. it's common bug for Animal Crossing, related with not accurate threading emulation, i think...

**Comment by Chrisatsinnoh** [comment]
Did anyone fix the common Animal Crossing bug, though? As for the emulation used, it was a nightly Citra build.

**Comment by mailwl** [comment]
i don't remember details, but bug is easy fixed by inserting pause in WaitSyncronization SVC, but game will looks like slide show, can't find discussion about it, sorry

**Comment by Chrisatsinnoh** [comment]
then the game is simply incompatible? That's a shame.

**Comment by acnleditor2** [comment]
@mailwl i need the files, i want the fix on my fork, send the files to valentinvanelslandeacnl@gmail.com
#2446

**Comment by Chrisatsinnoh** [comment]
Do you need the 3DS Game file or the emulator files?

**Comment by acnleditor2** [comment]
emulator

**Comment by Chrisatsinnoh** [comment]
It's available on the official Citra Website. It's the latest build.

**Comment by mailwl** [comment]
ah sorry, i don't remember, what exactly need to fix, it's so slow games, i don't record the changes.
maybe @wwylele helps

**Comment by Chrisatsinnoh** [comment]
I hope wwylele can help. That issue also happened to someone else but nobody helped them.

**Comment by Chrisatsinnoh** [comment]
In the meantime... Did anyone else find the solution to the problem?

**Comment by acnleditor2** [comment]
with a save is unplayable. freeze on open items menu

**Comment by Chrisatsinnoh** [comment]
Huh... Mine can only freeze the game when I press the Manual option in the title screen, but glitches the opening to make it unprogressable when I Start the game.

**Comment by acnleditor2** [comment]
past intro.

**Comment by Chrisatsinnoh** [comment]
in my case, I couldn't go past the intro. How were you able to make it through, @acnleditor2?

**Comment by BreadFish64** [comment]
@Chrisatsinnoh they used a save file from a 3DS to bypass the intro.

**Comment by Chrisatsinnoh** [comment]
Interesting, @breadfish64... Where can I find that save file?

**Comment by Chrisatsinnoh** [comment]
Where can I find the save file that can bypass the intro, though?

**Comment by riperiperi** [comment]
Why'd you post the same thing twice? You can dump a save file for use in citra from your 3DS, by following these instructions: https://github.com/citra-emu/citra/wiki/Dumping-Save-Data-from-a-3DS-Console (this is probably where they got theirs, afaik theres no AC:HHD saves on the net)

**Comment by Chrisatsinnoh** [comment]
@riperiperi It's just for confirmation. Unfortunately, my 3DS cannot access Homebrew and in other words, I do not want to access homebrew via payments.

**Comment by FearlessTobi** [comment]
How did you get your game then?

**Comment by Chrisatsinnoh** [comment]
@FearlessTobi Via downloading a citra-compatible rom somewhere.

**Comment by Chrisatsinnoh** [comment]
However, I have a 3DS and legal copies of New Leaf and Happy Home Designer, but I can't dump them because every update increases the difficulty to access homebrew, and I don't want to use paid alternatives to access the program.

**Comment by B3n30** [comment]
Closed by #3091
