### ISSUE TITLE
Pokemon Omega Ruby And Alpha Sapphire No Foot Step Sounds.

### ISSUE THREAD

**Issue by LogPod** [citra-emu/citra#3058]
There are no foot step sounds tested with Citra Nightly HEAD - 79852d3
Here is the log.
[log.txt](https://github.com/citra-emu/citra/files/1423981/log.txt)

**Comment by Dragios** [comment]
Reasons for closing?

**Comment by LogPod** [comment]
It is fixed.

**Comment by Dragios** [comment]
Is it fixed by PR #3459? The devs will appreciate if you do the testing and let them know the result, if you don't mind.
