### ISSUE TITLE
Pokédex 3D stuck at black screen

### ISSUE THREAD

**Issue by superheri** [citra-emu/citra#3061]
There is the log with DEBUG filter :
[logPokedex3d.txt](https://github.com/citra-emu/citra/files/1424527/logPokedex3d.txt)

Tested on commit : 26065fd

Critical errors popping in core\hle\svc.cpp

**Comment by Subv** [comment]
The hell? why is this thing trying to open `pxi:dev`?

Is this a game or a homebrew application?

**Comment by BreadFish64** [comment]
@Subv it's a 3D Pokemon viewer application, not Homebrew, not really a game either

**Comment by superheri** [comment]
Corrected by #3091 

There is now the possibility to see something interact with a bit of the menu but there is a bug while writing th the SD card :

[logPokedex3dAfterBoot.txt](https://github.com/citra-emu/citra/files/1503415/logPokedex3dAfterBoot.txt)


![pkdex3d1](https://user-images.githubusercontent.com/30275781/33234943-e885bd3a-d1fc-11e7-98eb-0e32caf5fdb3.PNG)
![pkdex3d2](https://user-images.githubusercontent.com/30275781/33234944-e9e653e2-d1fc-11e7-8107-5cde992b15a3.PNG)

**Comment by FearlessTobi** [comment]
This should be closed because of #3091.
