### ISSUE TITLE
Add a back button  in Chat client UI

### ISSUE THREAD

**Issue by esQmo** [citra-emu/citra#3074]
Please add a back button to the chat client beacause when you select a room and go in, there is no way to go back to the room browser, you have to close the chat client windows and then re-open it again from the Multiplayer tab. to be able to, say,  select another rom. Or you can make it open in a new window instead of that same. [Windows]

**Comment by jroweboy** [comment]
Please leave this as feedback on the multiplayer UI PR and not as an issue.

**Comment by esQmo** [comment]
Yeah, sorry. I was asking myself on which category I should post this.
