### ISSUE TITLE
citra won't play any games!

### ISSUE THREAD

**Issue by roald040** [citra-emu/citra#3089]
hey im using citra canary HEAD-DAE7537
and everytime i want  to open a .3ds file on it it says 
citra was unable to locate the 3DS shared fonts the game you are trying to load requires additional files
from your 3ds to be dumped before playing

how can i fix this problem? please help

**Comment by einstein95** [comment]
RTFM

**Comment by roald040** [comment]
rtfm?

**Comment by wwylele** [comment]
It literally tells you what to do in the message box.

--------

This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://community.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build, or
 - use pirated copies of the games, 3DS BIOS files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid
