### ISSUE TITLE
pokemon moon, game no longer displayes the intro

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#3100]
using latest canary the game only shows a black screen where the intro should play, the audio continues to play in the background normally. i can't pinpoint what change caused this

nightly works just fine 

log
https://pastebin.com/fsNknGw7

**Comment by FearlessTobi** [comment]
Iirc it's caused by Subvs delay PR.

**Comment by Subv** [comment]
Please post this in the PR's description if it does not happen on Nightly.
