### ISSUE TITLE
Phoenix Wright -  Dual Destinies Both Screen Malfunction

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#3102]
I have found that PR #3048 cause this regression. This is kind of weird, not sure how this PR can cause such bugs. But I bisected it till here. The upper display no longer works as it should anymore for some reason. It just show that static image.
![glitch](https://user-images.githubusercontent.com/18496868/32637405-8f64388a-c5f4-11e7-95f9-999c0d079ff5.png)

Switching renderer from HW to SW just shows black screen for both screens.
Switching it back to HW again results the same as SW now.

When it black screen it will show this log:
`Render.OpenGL <Error> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:472: API ERROR 1282: GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.`

Full log [here](https://pastebin.com/fbqrsXax)

**Separate issue:**
There is another funky thing going horibly wrong on the bottom screen (also introduced by this PR).
Only triggers by auto internal resolution setting. Can be explain by viewing this [video](https://streamable.com/j9qia).

---
**Update:** The glitch will be gone if you have a save file to begin with.

**Comment by Hexagon12** [comment]
The latest Nightly doesn't produce the issue.
![citra-qt_2017-11-13_12-49-23](https://user-images.githubusercontent.com/25362478/32722020-32b8f042-c871-11e7-834b-045045c60034.png)

If this issue is still present for you, it means that your GPU drivers produce artifacts with Citra and I would suggest either updating to the latest or previous drivers.

**Comment by Dragios** [comment]
I know why @Hexagon12 does not have the issue. It's because he have a save file to begin with. This glitch will only occur if you start a **New Game**

**Comment by Dragios** [comment]
Fixed by #3307
