### ISSUE TITLE
Sega 3D Classics Collection (Europe)

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3105]
Using  nightly HEAD-7ef905e
which ever game you choose from the menu straight away it comes up with a top black screen and a bottom white screen and nothing else

**Comment by Hexagon12** [comment]
A log file would be useful here.

**Comment by benderscruffy** [comment]
ok 
[log.zip](https://github.com/citra-emu/citra/files/1466624/log.zip)

**Comment by Hexagon12** [comment]
The game calls for ExitProcess...?
`[  23.385202] Kernel.SVC <Error> core\hle\svc.cpp:SVC::CallSVC:1418: unimplemented SVC function ExitProcess(..)`

**Comment by mailwl** [comment]
calling ExitProcess means something goes wrong.
in this case, i think, the problem is: `unknown / unimplemented function 'PrepareToDoApplicationJump'`

**Comment by benderscruffy** [comment]
still happens in the latest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2705891/citra_log.zip)

**Comment by benderscruffy** [comment]
it is still an issue

**Comment by SleepingSnakezzz** [comment]
@benderscruffy Can you retest with New 3DS Mode disabled in the system settings?

**Comment by benderscruffy** [comment]
still crashes out with New 3DS mode disabled

**Comment by GPUCode** [comment]
Now games work correctly
