### ISSUE TITLE
Ridge Racer 3D (USA) not enough space on the SD card

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3110]
using the lastest nightly HEAD-fae52d3
go to options then create new extra data and it says the SD card is not inserted
![rr1](https://user-images.githubusercontent.com/2696404/32766218-eb92f6bc-c948-11e7-8707-c3ccce804f00.PNG)
![rr2](https://user-images.githubusercontent.com/2696404/32766234-f71cf442-c948-11e7-83f0-4a6b467e62d7.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1469776/log.zip)

**Comment by PeterOliver** [comment]
Gives a similar error saying not enough space to save extra data after every race, which I assume it because it can't find the sdcard.

**Comment by benderscruffy** [comment]
using the latest nightly comes up with the message now about not enough space on the SD card
![ridge](https://user-images.githubusercontent.com/2696404/50621045-592cad80-0f3e-11e9-88a8-b117d18f3e20.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2722594/citra_log.zip)

**Comment by benderscruffy** [comment]
it is still an issue
