### ISSUE TITLE
3D Classics - Excitebike (USA) (eShop) cannot move motorbike

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3111]
using the latest nightly
after it play a tune you cannot move your motorbike
![excite](https://user-images.githubusercontent.com/2696404/32767226-65d5e5fc-c94d-11e7-849b-ca7d035ef1f8.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1469830/log.zip)

**Comment by Craftyawesome** [comment]
It never starts the countdown sound. You can get around this with a quicksave.

**Comment by benderscruffy** [comment]
still happens in the latest nightly 
[citra_log.zip](https://github.com/citra-emu/citra/files/2705888/citra_log.zip)

**Comment by dhkellenberger** [comment]
After the race introduction music, the game simply freezes and never starts the race. This is still an issue in the latest nightly (1418 at the time of writing this).

**Comment by benderscruffy** [comment]
still an issue

**Comment by benderscruffy** [comment]
using Canary 2618
still an issue

**Comment by ScottNash042** [comment]
goes ingame now no problems
can be closed
