### ISSUE TITLE
Resident Evil - The Mercenaries 3D (Europe) black screens 

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3115]
tried it on the lastest nightly (HEAD-fae52d3)
both screens black and no sound
works in the latest canary version (HEAD-ab27b920
[log.zip](https://github.com/citra-emu/citra/files/1474045/log.zip)

**Comment by Subv** [comment]
Could you see if the reason it works in Canary is #3091 specifically? You can grab a build of Nightly + that PR from the AppVeyor (Artifacts) link in the PR.

**Comment by benderscruffy** [comment]
using nightly HEAD-b88ed52
still doesnt boot in the nightly and now it doesnt boot in the canary version 
[Debug log.zip](https://github.com/citra-emu/citra/files/1551566/Debug.log.zip)

**Comment by benderscruffy** [comment]
goes ingame 
Press anywhere on the touch screen when you first start the game, this isn’t a crash or a black screen, it’s just a message that doesn’t appear due to a bug in the emulator.
![evil](https://user-images.githubusercontent.com/2696404/49632470-c9740c00-fa30-11e8-821c-36734409e1ef.PNG)
