### ISSUE TITLE
Pokemon Ultra moon Black Screen

### ISSUE THREAD

**Issue by qtu1996** [citra-emu/citra#3117]
I have tried the pkm ultra moon on the latest nightly (Nightly Build - f0027e9)

The game went black when I was playing, and stayed at 0 FPS.

![capture1](https://user-images.githubusercontent.com/33696596/32847617-0fb537f2-ca5d-11e7-86a1-8566f727052b.PNG)
![capture](https://user-images.githubusercontent.com/33696596/32847619-0fe31c44-ca5d-11e7-922d-bab574bfebb3.PNG)

**Comment by jroweboy** [comment]
Please do not open issues for unreleased games as none of the developers can test the game to fix issues until the game is released.

**Comment by qtu1996** [comment]
OK. Thank you. I will notice this next time.
