### ISSUE TITLE
Screenshot Function for Citra

### ISSUE THREAD

**Issue by MiniMii1** [citra-emu/citra#3121]
_I was [instructed by a fellow member](https://community.citra-emu.org/t/any-potential-for-a-screenshot-option/1706/6?u=minimii) to start an issue here._
A built-in screenshot function in Citra would be great to have, my main reason for needing it en lieu of the usual "Windows" way (using PrntScr) is because I run some games at native resolution but with a stretched window. Doing this causes some blurriness to show, which would be captured if I use PrntScr and I don't want that... What I want is for screenshots to have the game's internal resolution, regardless of the user's window size/layout.

_**Example:** Native resolution in a non-stretched window vs. in a stretched window (enlarge)_
![](https://community.citra-emu.org/uploads/default/original/2X/b/be67440dba61dc3d029fd275767cdcbd80854ec0.jpg)

**Comment by Subv** [comment]
@danzel

**Comment by adityaruplaha** [comment]
Do you want auto res? You need to capture to a svg.

**Comment by PandarinDev** [comment]
I am not very familiar with the codebase of Citra, but I want to start contributing and this seems like an easy first task. Can I implement this feature, @Subv ?

**Comment by jroweboy** [comment]
@PandarinDev Subv pinged @danzel specifically because they already have working code for this that you can find here: https://github.com/citra-emu/citra/compare/master...danzel:screenshot

**Comment by danzel** [comment]
Yep feel free to steal my code from over there :)

**Comment by PandarinDev** [comment]
Ah, I see. Mkay, I'll take a look at your branch and see what I can do.

**Comment by PandarinDev** [comment]
For the record I started working on this. It'll might take a few days, as I'm trying to make sense of @danzel 's code, learn and not just copy-paste it, but actually make improvements to it where possible.

**Comment by danzel** [comment]
See #2895 for some feedback on that PR too, there are improvements suggested in there that will need making.

**Comment by PandarinDev** [comment]
So sorry guys for taking so long. Holiday season + exams leaves me with barely any freetime. Got the screenshot code working on the software renderer, will do for HW too and hopefully open the PR early next week.

**Comment by adityaruplaha** [comment]
This involves rendering to an off-screen image. Which is not very easy I guess. Please remove `e-easy` label.

**Comment by hyarsan** [comment]
Citra Libretro has it working perfectly :p

**Comment by adityaruplaha** [comment]
Libretro?

**Comment by hyarsan** [comment]
I don't mean to promote Libretro / RetroArch, but yes it does have working screenshot functionality.

https://github.com/libretro/citra
https://www.libretro.com/
http://retroarch.com/
