### ISSUE TITLE
Dead or Alive - Dimensions (Europe) cannot create extra data

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3131]
using HEAD-c810a3f
comes up with the message (Not enough space on SD memory card to save extra data)
![dead](https://user-images.githubusercontent.com/2696404/32974225-812a6cf0-cc37-11e7-9335-1677abca3e44.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1484178/log.zip)

**Comment by benderscruffy** [comment]
still happens in the latest nightly
![dead](https://user-images.githubusercontent.com/2696404/50621723-add22780-0f42-11e9-90e1-bae10b6e010c.PNG)
[  41.576905] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:167: unknown / unimplemented function 'GetSdmcArchiveResource': port='fs:USER' cmd_buf={[0]=0x8140000}

[citra_log.zip](https://github.com/citra-emu/citra/files/2722634/citra_log.zip)

**Comment by benderscruffy** [comment]
same as #3110

**Comment by tallestdavid** [comment]
still getting this issue today... any fix?

**Comment by benderscruffy** [comment]
still present
