### ISSUE TITLE
Citra running very slow

### ISSUE THREAD

**Issue by alynicole** [citra-emu/citra#3132]
hello, I downloaded Citra nightly the other day got a game but it is running very slow. Is there something I can do to fix it, like in the configuration? Also I have Windows 10. Thanks!

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Citra is slow. If you have something misconfigured, the wonderful people on the forms would be glad to help you figure that out.
