### ISSUE TITLE
Dragon Ball Fusions - Crash on Opening Video

### ISSUE THREAD

**Issue by CrownFox** [citra-emu/citra#3137]
Tested on several nightly builds. The earliest nightly build the error occurs is [ec8dfc8](https://github.com/citra-emu/citra-nightly/commit/ec8dfc8fb7218e5c552c42d30a68e13e350c3d0e), and the error is not present on the nightly build made earlier that day [96528b3](https://github.com/citra-emu/citra-nightly/commit/96528b3aab159f646042dd7a287483cf50e3c0b1)

After the opening splash screens, the game attempts to start the opening video but immediately crashes instead. The compatibility for the game has regressed between those two builds.

The log file is attached
[log.txt](https://github.com/citra-emu/citra/files/1485813/log.txt)

**Comment by B3n30** [comment]
this issue is either to be introduced by https://github.com/citra-emu/citra/commit/a06220682cd4fb56f4db1eec7cdf647d3e21d88a or https://github.com/citra-emu/citra/commit/4e884588142fa7f2c98eb6a3bd1984d696273f2e.
So probably an error in dynarmic?!

**Comment by CrownFox** [comment]
Is it possible to try a build with a rolled back version of dynarmic to see if that is what is causing the issue? I'm new to this whole github thing, so I'm not sure what's possible.

**Comment by MerryMage** [comment]
I was unable to reproduce this issue. Could you provide more information?

**Comment by MerryMage** [comment]
I was unable to reproduce this issue on either Windows on macOS. Could you provide more information? Note that I was using the JP version, since that's the only copy I have.

**Comment by CrownFox** [comment]
I actually tried it on my Girlfriend's PC, and was able to run the game. I'm wondering if this may have something to do with my CPU. My CPU is an old Phenom II x4. While 64bit applications that properly multi-thread tend to run fine, I run into issues where applications use SSE4.1 or other features my CPU doesn't support. Could this be the reason I'm having the issue?

**Comment by MerryMage** [comment]
Thanks very much for that very helpful additional information.

Audited the instructions that dynarmic uses. It uses `pmaxuw` and `pminuw` which are SSE 4.1 instructions without verifying the CPU supports them first. I'll write a fix when I have time.

**Comment by MerryMage** [comment]
Likely fix at #3139.

@CrownFox Could you please test [this test build](https://ci.appveyor.com/project/bunnei/citra/build/1.0.6593/job/vm2sv7s9nbxc0bs2/artifacts) please?

**Comment by CrownFox** [comment]
That fixed it!

**Comment by MerryMage** [comment]
Thanks!
