### ISSUE TITLE
Cannot get updates on latest nightly

### ISSUE THREAD

**Issue by superheri** [citra-emu/citra#3140]
Using de0af83

[   0.000000] Frontend <Warning> citra_qt/main.cpp:CheckForUpdates:401: Unable to start check for updates

**Comment by Dragios** [comment]
This is not a bug report. It happens when you are not using the installer version (which means you get it directly from GitHub download page).
Please download it from https://citra-emu.org/download/ to solve your issue.

**Comment by superheri** [comment]
Ok thank you for your answer.
