### ISSUE TITLE
Cave Story (Europe) (eShop) music and sound fx really quiet

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3146]
using the latest nightly (HEAD-e145a56)
you have to turn the volume up to full on your speakers just to hear anything it is so quiet

[log.zip](https://github.com/citra-emu/citra/files/1502825/log.zip)

**Comment by MerryMage** [comment]
Todo: Verify [PCM8](https://github.com/citra-emu/citra/blob/master/src/audio_core/codec.cpp#L81-L85) is correct.

**Comment by benderscruffy** [comment]
using nightly 1144
no problem
