### ISSUE TITLE
3D Galaxy Force II (USA) (eShop) crashes out

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3149]
using the latest nightly after you press start game the emulator crashes out
![galaxy](https://user-images.githubusercontent.com/2696404/33229735-7cfa839e-d20f-11e7-8ea7-6f81771f701b.PNG)
[Debug log.zip](https://github.com/citra-emu/citra/files/1504775/Debug.log.zip)

**Comment by benderscruffy** [comment]
3D After Burner II (Europe) (eShop) has the same problem

**Comment by benderscruffy** [comment]
still happens in the latest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2723340/citra_log.zip)

**Comment by SergeEXE** [comment]
Also occurs with 3D After Burner II

**Comment by benderscruffy** [comment]
still an issue
