### ISSUE TITLE
VVVVVV (Europe) (eShop) fatal error

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3150]
using the latest nightly after you press button a then a fatal error happens then nothing but black screens
[log.zip](https://github.com/citra-emu/citra/files/1502988/log.zip)

![vvvvv](https://user-images.githubusercontent.com/2696404/33229809-696c3dd4-d211-11e7-9a4a-b21cfcfb68b4.PNG)

**Comment by wwylele** [comment]
I am testing the JAP version on last nightly, but it hangs before the title screen. iirc I once tried hacking core1 scheduler stuff and managed to let it goes to the title screen *and ingame* without encounter such error. Looks like this is a region-specific issue.

**Comment by shinyquagsire23** [comment]
I had to [backtrack on my Twitter](https://twitter.com/ShinyQuagsire/status/784910893310025729) but it was either the EUR or USA version of VVVVVV which actually booted on the latest eShop version at some point, the original did not get past the title screen iirc. This is also when it got a JAP release, could be some regressions? @wwylele

**Comment by wwylele** [comment]
@shinyquagsire23 the hang can be a regression due to removal of some scheduler hack. Note that the game uses unimplemented core 1.

**Comment by benderscruffy** [comment]
goes ingame now
