### ISSUE TITLE
Marvel Pinball 3D (Europe) (eShop) crashes out

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3152]
using the latest nightly as soon as u press the  "touch to start" screen the emulator crashes out
![marvel](https://user-images.githubusercontent.com/2696404/33239575-a0e4d9d2-d2df-11e7-9a42-ce68c9514254.PNG)
[Debug log.zip](https://github.com/citra-emu/citra/files/1504778/Debug.log.zip)

**Comment by benderscruffy** [comment]
Zen Pinball 3D (Europe) (eShop) has the same problem as well

**Comment by wwylele** [comment]
>wwylele / 白疾風 - Yesterday at 7:01 PM
@ Subv  https://github.com/citra-emu/citra/issues/3152 looks like a incorrect assumption in HLE static buffer translation (https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/hle_ipc.cpp#L54)
I suppose this could happen when a service function receive a static buffer from request, and response also with a static buffer with the same buffer id
>
>Subv - Yesterday at 7:03 PM
indeed
