### ISSUE TITLE
Bit Boy!! Arcade (Europe) (eShop) freezes up

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3155]
during the intro it freezes up 
![bit](https://user-images.githubusercontent.com/2696404/33239739-575ead48-d2e3-11e7-836c-e0f1d9bd07fe.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1503854/log.zip)

**Comment by mailwl** [comment]
it crash because of ExitProcess(), caused unimplemented service functions. But on second run it just start without intro video.
try to use save: 
[SCORE.zip](https://github.com/citra-emu/citra/files/1509910/SCORE.zip)

**Comment by benderscruffy** [comment]
goes ingame now no problems
