### ISSUE TITLE
Governor of Poker (Europe)(eShop) crashes out

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3158]
using the latest nightly the game crashes out nearly straight away
![poker](https://user-images.githubusercontent.com/2696404/33247773-771c9424-d35b-11e7-8c7d-c098b5fa0835.PNG)
[Debug log.zip](https://github.com/citra-emu/citra/files/1504745/Debug.log.zip)

**Comment by Dragios** [comment]
Next time when creating a crash report, make sure to include a stack trace and debug reports. The developer here will not have a clue to fix the issues without those information. Log alone is not enough to justify the issue. Or else, it will be literally kind of pointless to open an issue ticket.

**Comment by Hexagon12** [comment]
To get the stack trace, you would need to build Citra in the Debug configuration with MSVC.

**Comment by mailwl** [comment]
wrong implementation of `AC_U::SetRequestEulaVersion`
Anyway, game is unplayable, because SOC_U not implemented at all

**Comment by wwylele** [comment]
Looks like the same problem as #3152
@Subv are you planning to fix it soon?
