### ISSUE TITLE
Kirby Battle Royale Crash when Booted (Assertion Failed! Inconsistent AddressArbiter State)

### ISSUE THREAD

**Issue by greggameplayer** [citra-emu/citra#3164]
## Citra Version :
I use the version HEAD-e9a95b2.
## My system spec is :
- Nvidia GeForce GTX 960
- AMD FX 6300
- 8 GB Of Ram
- Windows 7 6.1.7601
## The issue :
The issue is that kirby battle royale boot but an error "core/hle/kernel/address_arbiter.cpp:operator():45: Assertion Failed! Inconsistent AddressArbiter State" cause the crash of the game so I test the game on the LLVM5 nehalem custom build and on this build the game boot and run perfectly. So in my opinion that's an issue you can easily patch.

**Comment by wwylele** [comment]
> I test the game on the LLVM5 nehalem custom build and on this build the game boot and run perfectly. So in my opinion that's an issue you can easily patch.

Please only test (old) official builds and bisects which commit broke it exactly, otherwise a random unofficial build test would just make it harder to patch.

**Comment by greggameplayer** [comment]
ok but the error happen in all the official citra nightly and canary build.

**Comment by valentinvanelslande** [comment]
@greggameplayer test with nightly 411

**Comment by greggameplayer** [comment]
ok i will the now.

**Comment by greggameplayer** [comment]
that's work ! OMG

**Comment by greggameplayer** [comment]
that's nearly the same result as the LLVM5 nehalem custom build. So now @wwylele or another person can you patch this error ?

**Comment by wwylele** [comment]
@greggameplayer could you confirm that 411 is the last working version (i.e. 412 doesn't work)?

**Comment by greggameplayer** [comment]
412 was not built for windows

**Comment by wwylele** [comment]
nvm, #3096 issue already got filed there

**Comment by greggameplayer** [comment]
in nightly build 413 it's didn't work

**Comment by greggameplayer** [comment]
So I suppose that the latest working version is 411
