### ISSUE TITLE
Sonic Boom Fire&Ice Boot but nothing after

### ISSUE THREAD

**Issue by greggameplayer** [citra-emu/citra#3165]
## Citra Version:
HEAD-e9a95b2
## System Specs:
- Nvidia GeForce GTX 960
- AMD FX 6300
- 8 GB Of Ram
- Windows 7 6.1.7601
## Issue:
Sonic Boom : Fire&Ice EU Version boot (there is a loading represented by a ring) but after there is nothing. So I've tested the game on the LLVM5 nehalem custom build (version : sandbox-be583a48-dirty) and as by chance the game work perfectly on this build. So what is the problem because these two builds have the same error, on the onehand it's not working and on the otherhand it's working.

**Comment by jroweboy** [comment]
This is a duplicate issue of https://github.com/citra-emu/citra/issues/2654 and https://github.com/citra-emu/citra/issues/2554 which seem to imply that it broke after the priority boost hack, meaning theres still some scheduler bugs left to fix.

Closing as a duplicate.
