### ISSUE TITLE
Horrible Audio

### ISSUE THREAD

**Issue by MarcoProlo** [citra-emu/citra#3167]
The graphic are very nice. However, there are a huge problem with the audio. Audio is actually went really crappy. For example, the audio sometimes went very fast and sometimes very slow(Unstable). Second Example, is that the audio sound like a lagging computer, but the graphic looks so smooth(30fps with limited frame rate enabled)
Citra Version: Citra Nightly HEAD-b2a9904
Here is the spec(In case you need it):
CPU: Intel Core i7 7567U
GPU: Intel Iris Plus 650 (OpenGL 4.5)
Ram: 8GB
Audio Driver: Cirrus Logic CS8409 (AB 54) Ver.10.0.16299.15

**Comment by YOUDONTSAYMEMEWILLBEMINE** [comment]
Github is for developers if you want support use the forums.
