### ISSUE TITLE
WebService error? A problem while opening public room browser from multiplayer.

### ISSUE THREAD

**Issue by PreciousTrainer** [citra-emu/citra#3169]
Using latest build idk why this is happening?
http://prntscr.com/hhu6r4

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum.

This is also pretty clearly not a build downloaded from citra's web site. Ask who ever you got it from for support instead. If you built it yourself then likely something went wrong with cpr, and we would need more details to actually consider this an issue
