### ISSUE TITLE
Latest Citra Nightly Builds  and Canary Builds wasn't build for windows

### ISSUE THREAD

**Issue by greggameplayer** [citra-emu/citra#3175]
On the site, the 4 latest nightly builds and canary builds of citra wasn't build for windows so can you fix them please ?

**Comment by wwylele** [comment]
This is due to Appveyor backlogging our build. We have already requested for cleaning it up. This is not an issue in citra itself, so sadly we can't do much about it on our side.

**Comment by greggameplayer** [comment]
no one can clean up apart from the creator of the github repository ?

**Comment by wwylele** [comment]
@greggameplayer Even the repo creator/owner can't do much, because the building process is hosted on [AppVeyor](https://www.appveyor.com/), which itself is maintained by others. By "requested for cleaning up" I meant to request to AppVeyor maintainer.

**Comment by greggameplayer** [comment]
ok so how long you think will it take ?

**Comment by greggameplayer** [comment]
It is normal that the PR Builder inside the website gives error 404 (page not found) ?
