### ISSUE TITLE
Chat-A-Lot (USA) (eShop) need to lift the child online privacy protection

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3180]
after you press start it comes up with the message to lift the child online privacy protection
![chat](https://user-images.githubusercontent.com/2696404/33524274-53fc52ce-d854-11e7-8e01-816cc6c36547.PNG)
[Debug log.zip](https://github.com/citra-emu/citra/files/1524641/Debug.log.zip)

**Comment by wwylele** [comment]
Among the following, which one did you do with your config savegame?
 - Didn't do anything and let citra create it from fresh (and no user directory copied from others / downloaded from the internet / inherited from unofficial build)
 - Dumped your own config savegame from your 3DS to citra
 - Used others config savegame (including copying others user directory, used unofficial build etc.)

**Comment by benderscruffy** [comment]
Didn't do anything and let citra create it from fresh (and no user directory copied from others / downloaded from the internet / inherited from unofficial build)

**Comment by wwylele** [comment]
I doubt that your answer is accurate, for the first line in your log:
`[   0.000000] Common.Filesystem <Info> common/file_util.cpp:GetUserPath:695: Using the local user directory`

This can only happens with the following possibility:
 - You inherited the user directory from a very old citra build / unofficial citra build / directly downloaded from the internet
 - You manually created it, which is discouraged in our guides.

Either way, please remove the directory `user/nand/data` and test it again.
