### ISSUE TITLE
Mario and Donkey Kong: Minis on the Move collection models not really textured

### ISSUE THREAD

**Issue by greggameplayer** [citra-emu/citra#3182]
## The issue :
Collection models of Mario and Donkey Kong: Minis on the Move wasn't textured properly
## Screenshots :
[First Screenshot](https://image.noelshack.com/fichiers/2017/49/4/1512667813-screenissue1.png)

[Second Screenshot](https://image.noelshack.com/fichiers/2017/49/4/1512667815-screenissue2.png)
## The Log :
[Click Here](https://pastebin.com/qNvQ143x)
## Tested Citra Version:
citra canary builds:
- HEAD-d72e3ca
- HEAD-1defb28

citra nightly builds:
- HEAD-b2a9904
- HEAD-689fe57
## System Specs:
- Nvidia GeForce GTX 960
- AMD FX-6300
- 8 GB Of Ram
- Windows 7 6.1.7601

**Comment by Hexagon12** [comment]
Please provide screenshots and a full log.

**Comment by greggameplayer** [comment]
here is the log : https://pastebin.com/qNvQ143x

**Comment by Leo626** [comment]
You need to post a screenshot along with a comparison screenshot to 3DS hardware.

**Comment by greggameplayer** [comment]
I've upload screenshots of the bug but I can't publish the screen with a 3ds hardware because I don't have 3ds

**Comment by benderscruffy** [comment]
still happens on the latest nightly
![mini1](https://user-images.githubusercontent.com/2696404/50634255-fad8ec80-0f88-11e9-9151-91566e441711.PNG)
![mini](https://user-images.githubusercontent.com/2696404/50634256-fd3b4680-0f88-11e9-841a-f1e17023ac79.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2723440/citra_log.zip)

**Comment by benderscruffy** [comment]
still an issue

**Comment by benderscruffy** [comment]
using Canary 2610
this is still an issue

**Comment by benderscruffy** [comment]
@GPUCode 
has been fixed in open gl and software
still not fixed in Vulkan

**Comment by GPUCode** [comment]
Could you upload screenshot of the issue, as the poster ones are unavailable

**Comment by benderscruffy** [comment]
disable spirv shader generation in vulkan and it works properly
can be closed

**Comment by GPUCode** [comment]
Still would like screenshot so I can fix it with spirv

**Comment by benderscruffy** [comment]
ok here they are
![Screenshot 2023-09-09 154913](https://github.com/citra-emu/citra/assets/2696404/f893cd8f-bea9-423f-966c-3734d8c6daf7)
![Screenshot 2023-09-09 154933](https://github.com/citra-emu/citra/assets/2696404/e7d92b9e-72cd-45c1-83cf-6d004b8bfbd5)

**Comment by GPUCode** [comment]
I think this may have been fixed by the blending PR

**Comment by FearlessTobi** [comment]
okay, then i will close this since it has been fixed in nightly builds.
