### ISSUE TITLE
Mario vs. Donkey Kong: Tipping Stars slow down or freeze when minis are on a slope

### ISSUE THREAD

**Issue by greggameplayer** [citra-emu/citra#3183]
## The issue:
Mario vs. Donkey Kong: Tipping Stars slow down or freeze when minis are on a slope due to the error "HW.GPU <Error> video_core/command_processor.cpp/WritePicaReg:128: Commandlist tried to write to invalid register"
## The Log:
[Click Here](https://pastebin.com/RKCaTpG9)
### Canary Builds:
- HEAD-d72e3ca
- HEAD-1defb28

### Nightly Builds :
- HEAD-b2a9904
- HEAD-689fe57
## System Specs:
- Nvidia GeForce GTX 960
- AMD FX-6300
- 8 GB Of Ram
- Windows 7 6.1.7601

**Comment by Hexagon12** [comment]
We need a full log.

**Comment by greggameplayer** [comment]
where I can find the log ?

**Comment by RavenHome1** [comment]
@greggameplayer  https://community.citra-emu.org/t/how-to-upload-the-log-file/296

you can upload the file here or to pastebin.

**Comment by greggameplayer** [comment]
here is a log : https://pastebin.com/RKCaTpG9

**Comment by benderscruffy** [comment]
can be closed 
same as #4554

**Comment by yalopov** [comment]
still happening, is there a workaround for this bug?
