### ISSUE TITLE
Phoenix Wright: Ace Attorney Dual Destinies crashes almost immediately upon load

### ISSUE THREAD

**Issue by draeklae** [citra-emu/citra#3224]
PW: AA DD crashes ~2 seconds into loading.

Using my previous build (5621a650) it went much further before crashing. Now using the latest nightly e784434a it crashes almost instantly upon load.

Citra Version: e784434a

[phoenix.log](https://github.com/citra-emu/citra/files/1534909/phoenix.log)

**Comment by Dragios** [comment]
PR #3086 broke this game. I have already notified the developer about this issue.
```
Debug <Critical> core/hle/service/apt/apt.cpp:operator():117: Assertion Failed!
Unknown applet id
```
