### ISSUE TITLE
Kirby Battle Royale Missing sounds

### ISSUE THREAD

**Issue by greggameplayer** [citra-emu/citra#3233]
## The issue :
Some sounds like the main menu music are missing in Kirby Battle Royale.

## The Log :
https://pastebin.com/yb7qUhYU

### Citra Canary Builds :
- HEAD-eb90e2f

### Citra Nightly Builds :
- HEAD-040006f
- HEAD-689fe57

## System Specs :
- Nvidia GeForce GTX 960
- AMD FX-6300
- 8GB Of Ram
- Windows 7 6.1.7601

**Comment by Hexagon12** [comment]
This game is one of the users of pipe3, which isn't implemented yet.

**Comment by greggameplayer** [comment]
Yes I've seen that so I upload this because later I will upload Kirby Battle Royale game report

**Comment by wwylele** [comment]
DSP LLE is merged. Please report back and continue to track this issue on while we fix DSP HLE.

**Comment by Amnesia1000** [comment]
The lack of audio is fixed by putting LLE (multi-core) or LLE (accurate), but the performance of the game is quite affected, not reaching 20fps in my case. 

Tested on: 
Citra Canary 1181. 
Linux Manjaro. 
i7 7700
16GB ram.
Nvidia 1060 6GB.

**Comment by benderscruffy** [comment]
can be closed now fixed
