### ISSUE TITLE
LLE applets issues

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#3243]
(mii selector 7.0.0-13E) Super Mario 3D Land freeze
(swkbd) no sound, log spam of csnd stubbed called
(swkbd 3) Miitopia crashes reading address ???
(swkbd 4) FBI and Mii Maker crashes reading address ???, NNID Settings password keyboard not appearing completely with hardware renderer, works with dumped config savegame

**Comment by CDAGaming** [comment]
Can Verify this also for Super Mario Maker

**Comment by Subv** [comment]
For the record, this is the lifetime of an LLE library applet:
![image](https://user-images.githubusercontent.com/357072/34065069-698d8a14-e1cc-11e7-8b78-8add4ff01564.png)

**Comment by Dragios** [comment]
This can be close as well?
