### ISSUE TITLE
Saving twice in XY causes the game to crash.

### ISSUE THREAD

**Issue by LogPod** [citra-emu/citra#3260]
Oh wow another XY issue
tested on Head-e8209ea(latest canary)
[log.txt](https://github.com/citra-emu/citra/files/1546108/log.txt)

**Comment by legoj15** [comment]
Could you also test on latest nightly for posterity? Canary builds can have some funky side effects.

**Comment by LogPod** [comment]
Head-2146311 Latest Nightly
[Nightly log.txt](https://github.com/citra-emu/citra/files/1546135/Nightly.log.txt)
Same error @legoj15

**Comment by LogPod** [comment]
Or open-gl errors are not causes by any programs. i have literally nothing open so i don't why it gives those errors.

**Comment by CDAGaming** [comment]
Tested on Latest Canary, Master, and 'Sandbox':

Stacktrace (From MerryMage's crash-trace PR):
https://hastebin.com/ojocumolez.scala

**Comment by CDAGaming** [comment]
@LogPod I've only seen those OpenGL errors on PC's using Integrated Graphics that don't support the proper version for OpenGL.

**Comment by LogPod** [comment]
My Graphics card supports up to open gl 4.4 so that isn't the problem

**Comment by legoj15** [comment]
The log mentions a NVIDA Quadro card, but it's running on Qudro driver version 377.61. The latest one I have is Quadro 386.01. Is there a way that you could try to update your drivers, just incase?

**Comment by LogPod** [comment]
This is the latest one for me 
![capture](https://user-images.githubusercontent.com/30522087/33828788-41a865d6-de8f-11e7-8b5d-148217d48795.PNG)

**Comment by MerryMage** [comment]
Hi guys. Thanks for the enthusiasm. From the log it looks like an assertion in the texture forwarding code, hence my label.

Either cached_res_count is too small or there's a logic error somewhere else.

**Comment by LogPod** [comment]
Seems like this is fixed in the latest canary.

**Comment by LogPod** [comment]
Issues are closed when they are fixed in nightly builds @adityaruplaha

**Comment by adityaruplaha** [comment]
Oh, I see. Sorry, I didnt know that.

**Comment by wwylele** [comment]
Fixed by #3281 as reported so closing. Feel free to reopen if it is not the case.
