### ISSUE TITLE
Tappingo 2 (Europe) (eShop) wont boot

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3267]
using the latest nightly HEAD-9699194
Tappingo 2 (Europe) (eShop) wont boot in the latest nightly or canary
[Debug log.zip](https://github.com/citra-emu/citra/files/1546302/Debug.log.zip)

**Comment by mailwl** [comment]
you do something wrong (maybe file is crypted or broken?). On latest master game is fully playable

**Comment by valentinvanelslande** [comment]
try to change the region to the game region

**Comment by benderscruffy** [comment]
it made no difference changing the region
