### ISSUE TITLE
Ocean Runner (Europe) (eShop) crashes out straight away

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3269]
using the latest nightly HEAD-9699194
it crashes out straight away in both the latest nightly and canary
[Debug log.zip](https://github.com/citra-emu/citra/files/1546337/Debug.log.zip)

**Comment by j-selby** [comment]
Has this issue been fixed?

**Comment by benderscruffy** [comment]
my copy is corrupt
