### ISSUE TITLE
Disney Planes - Fire & Rescue (Europe) black screen

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3276]
using nightly HEAD-b88ed52
nothing but a black screen
[Debug log.zip](https://github.com/citra-emu/citra/files/1550554/Debug.log.zip)

**Comment by valentinvanelslande** [comment]
needs ssl:C

**Comment by benderscruffy** [comment]
still happens in the latest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2705925/citra_log.zip)

**Comment by benderscruffy** [comment]
it is still an issue

**Comment by benderscruffy** [comment]
goes ingame now
no problems so far
