### ISSUE TITLE
Tom Clancy's Splinter Cell 3D (USA) infinite loading

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3279]
using nightly HEAD-b88ed52
stuck on the loading screen
![image](https://user-images.githubusercontent.com/2696404/33885203-a571ca1e-df7d-11e7-9cd6-0de1c26b2966.png)
[Debug log.zip](https://github.com/citra-emu/citra/files/1551598/Debug.log.zip)

**Comment by valentinvanelslande** [comment]
is not nightly

**Comment by benderscruffy** [comment]
@valentinvanelslande the picture is from the other thread i just copied it

**Comment by valentinvanelslande** [comment]
@benderscruffy try in nightly

**Comment by FearlessTobi** [comment]
@valentinvanelslande He actually tried in Nightly, but he just copied the picture from the other Thread....

**Comment by benderscruffy** [comment]
it is still an issue

**Comment by 0987654321252** [comment]
What is the solution for this.

**Comment by SirGryphin** [comment]
Still stuck on title screen, log below.
[citra_log.txt](https://github.com/citra-emu/citra/files/6437874/citra_log.txt)

**Comment by NoUserNameForYou** [comment]
Saw a few YT vids playing this. How?

**Comment by SirGryphin** [comment]
@NoUserNameForYou 
If they have a modded 3ds with a capture feature you can plug into PC and record gameplay.

**Comment by NoUserNameForYou** [comment]
> @NoUserNameForYou If they have a modded 3ds with a capture feature you can plug into PC and record gameplay.

You think such thing is employed here? https://www.youtube.com/watch?v=lilWNB61jhs

**Comment by SirGryphin** [comment]
@NoUserNameForYou 
No He seems to be using Citra MMJ for Android. I've tried the CIA file he provides in Citira for PC, using latest nightly build and decryption key and it still crashes on loading screen.

The only thing  I can think of is the unofficial android version he's using must seem to have a fix for this game. I can't test as I don't have a Android and APK won't install on Bluestacks.

https://github.com/weihuoya/citra/releases

**Comment by NoUserNameForYou** [comment]
> @NoUserNameForYou No He seems...

Okay, I'll try the Android version on different hardware and will let you know.
In the mean time, there's also a PC canary build running the game: https://www.youtube.com/watch?v=4qraAaHhRMo

**Comment by SirGryphin** [comment]
@NoUserNameForYou 
Not sure what it is then, I've tried 4 different cia files and all of them crash on loading screen.

**Comment by NoUserNameForYou** [comment]
> @NoUserNameForYou Not sure what it is then, I've tried 4 different cia files and all of them crash on loading screen.

I'm not sure either, I tried 3 different (regional) 3ds, decrypted files and they all hang up in the start loading screen. Maybe he built his own cia/3ds file and hex edited execs or something. Or maybe, citra unintentionally fixed that problem and rebroke it again after a certain revision.

**Comment by NoUserNameForYou** [comment]
Update: Latest Vulkan qt build fixed the issue for EU and US roms. I went ingame and played a bit. 

Japanese rom doesn't get stuck like the previous builds but it gets stuck at new game loading. Previously it was stuck right after intro.

**Comment by benderscruffy** [comment]
goes ingame now
![Screenshot 2023-04-23 085158](https://user-images.githubusercontent.com/2696404/233813676-b7f6ac25-cabe-436c-9f9e-7ef4042fd5c1.png)
