### ISSUE TITLE
SMT4 :apocalypse crashes when on prompt to continue 

### ISSUE THREAD

**Issue by smokeyphil** [citra-emu/citra#3285]
I was told to come here and make an issue from the citra forums:
https://community.citra-emu.org/t/smt4-apocalypse-crash-on-choosing-to-look-for-relics/6592/5

As detailed above when playing smt4:apocalypse the the prompt that moves the game onto the 3d section (look for relics) causes the game to crash out.

Attached is the log file generated by playing it though and causing it to crash on the last nightly build. 
[lognew.txt](https://github.com/citra-emu/citra/files/1556933/lognew.txt)
 
Tested on citra nightly HEAD-aecd2b8

If you want more info or logs e.c.t just ask.

Thanks in advance .

**Comment by FearlessTobi** [comment]
For me, the game only hangs on the difficulty select screen but doesn´t crash.

**Comment by smokeyphil** [comment]
Interesting what kinda hardware are you using I've got in on on i5-7200u 4 cores at 2.50GHz and a nvidea gtx 950m (intelHD graphics 620 onboard) i can maybe help you get it to the point where it crashes for me i dont know if that is really "helping" you out there :P

**Comment by FearlessTobi** [comment]
Your log seems to bet cut off so we can´t see whats causing it to crash... I have an Gtx970 + i7 7700k but I don´t think it´s related to the issue.

**Comment by benderscruffy** [comment]
Has this been fixed ???
Please update

**Comment by GPUCode** [comment]
Did not encounter any crashes while testing the game for https://github.com/citra-emu/citra/pull/6925. Closign due to this and inactivity
