### ISSUE TITLE
Nintendo 3DS Guide - Louvre (Europe)  freezes up with audio issue

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3288]
using the latest nightly 
choose listen to all and then soon after the game freezes up 
![louvre](https://user-images.githubusercontent.com/2696404/33996566-90261480-e11c-11e7-92ce-8855437cf1d7.PNG)
![louvre1](https://user-images.githubusercontent.com/2696404/33996571-9265ac1a-e11c-11e7-9482-060c4feb84fe.PNG)
[Debug log.zip](https://github.com/citra-emu/citra/files/1559488/Debug.log.zip)

**Comment by Hexagon12** [comment]
`[ 119.868353] Service.DSP <Debug> core/hle/service/dsp_dsp.cpp:ReadPipeIfPossible:381: pipe=3, unknown=0x00000000, size=0x20, buffer=0x0FFFFB48, return cmd_buff[2]=0x00000000`

Pipe3 is unimplemented.

**Comment by benderscruffy** [comment]
has not been added to nightly yet

**Comment by wwylele** [comment]
DSP LLE is merged. Please report back and continue to track this issue on while we fix DSP HLE.

**Comment by benderscruffy** [comment]
it works in the nightly
