### ISSUE TITLE
LT and RT Buttons on XBox360 Controller get recognized as Joystick Axes

### ISSUE THREAD

**Issue by FearlessTobi** [citra-emu/citra#3303]
The bug happens in both latest Nightly and Canary. The problem is, that the LT and RT Buttons (the shoulder buttons at the back) on the Xbox360 Controller get recognized as "Joystick 0 Axis 2+" and as "Joystick 0 Axis 5+". 
This causes another problem: When I push either the LT or RT button, the button keeps being pushed in the game, even when I have stopped pushing it in reality.
When I now push the button again, the button isn't pushed anymore in the game.

Log shouldn't be necessary.

EDIT: Now the issue seems to have disappeared. Please keep this open though, as I will try to investigate what fixed it.

**Comment by BreadFish64** [comment]
The Xbox 360 controller has analog triggers right? In which case they are correctly identified as axes, not sure why they stay pressed

**Comment by FearlessTobi** [comment]
@BreadFish64 I was way to tired to notice that when I opened the issue this morning xD. I will close it for now because it seems to be something on my end.
