### ISSUE TITLE
Rabbids Travel in Time 3D: Top Screen cut in half during cutscenes

### ISSUE THREAD

**Issue by FearlessTobi** [citra-emu/citra#3308]
The bug happens in both latest Nightly and Canary. To reproduce the issue, just start the game. 
You will see this: 
![bug2](https://user-images.githubusercontent.com/20753089/34075156-37ed4236-e2be-11e7-9d55-ea1707b4f299.png)

It always happens when video is played over y2r.

- [Cropped log for better readability](https://pastebin.com/ctEV9AsD)

- [Full log](https://pastebin.com/DeK96xEf)

**Comment by Subv** [comment]
There's a bug in our Virt->Phys address translation for memory fills. The end of VRAM will get incorrectly translated to an IO address. Our GSP implementation should just be calculating the physaddr by adding a constant, not calling VirtualToPhysicalAddress.

**Comment by FearlessTobi** [comment]
@Subv So just for the record... does https://github.com/citra-emu/citra/issues/2672 have the same cause?

**Comment by Subv** [comment]
probably, maybe. The way to know is to fix it and see

**Comment by greggameplayer** [comment]
This bug is only happen on cinematics and happen too in this in the rayman and rabbid family pack

**Comment by FearlessTobi** [comment]
Issue still exists in the latest builds.

**Comment by Dragios** [comment]
@FearlessTobi How about now?

**Comment by FearlessTobi** [comment]
Still happens.

**Comment by benderscruffy** [comment]
still an issue

**Comment by GPUCode** [comment]
This is caused by incorrect clip plane emulation
