### ISSUE TITLE
E.X. Troopers: OpenGL Renderer Error

### ISSUE THREAD

**Issue by BladeStrife** [citra-emu/citra#3314]
Hi CITRA Team! I'm kinda new here in GitHub, but i'll try to contribute here with the best of my abilities.

Title of Game: _E.X. Troopers_
Publisher: _Capcom_
Citra Emulator Issue: _OpenGL Renderer Error_

When i first played this great game using the latest build (Nightly Build - 3f37976), i noticed a particular error with the game. This error was:
```
[ 168.651596] Render.OpenGL <Error> video_core\renderer_opengl\gl_shader_gen.cpp
:GLShader::SampleTexture:221: Using Texture3 without enabling it
```
I think it has something to do with the choppy fpm (running between 1 to 5 fpm), especially during the in-game CG cut-screens.

Anyways, i'm currently using this [Citra build](https://goo.gl/KATPsY) when i'm actually playing it, but i'm using the official Citra to test (and play) some 3DS games, especially games that weren't that popular (_Gaist Crusher God_ is one such example).

Anyways, here's my PC specs:
_OS: Windows 7
Processor: Intel Core i3-2330M CPU@2.20GHz 
Installed RAM: 4.00G
Graphic Driver: NVIDIA GEForce 410M_

**Comment by FearlessTobi** [comment]
I don't think it's the line you pointed out that's causing your performance problems, I think it's just your CPU. You can look it up in [this](https://www.cpubenchmark.net/singleThread.html) benchmark. If you have a CPU that's below 1800, Citra won't run fast enough. 
Your CPU scores 1060 there, so it's single core performance is way to low for Citra. The only thing you can do is buy a better model or wait for further performance optimizations.

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/
Please do not report performance issues here.

Requesting to close.

**Comment by BladeStrife** [comment]
Sorry!
