### ISSUE TITLE
Monster High - 13 Wishes (Europe) black screens

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3316]
using the latest nightly and canary
nothing but black screens
[Debug log.zip](https://github.com/citra-emu/citra/files/1571640/Debug.log.zip)
![monster](https://user-images.githubusercontent.com/2696404/34157209-98ee1ac6-e4fb-11e7-9446-e6dac07283b1.PNG)

**Comment by Hexagon12** [comment]
`[   3.656254] Service.SRV <Debug> core/hle/service/sm/srv.cpp:GetServiceHandle:114: called service=ssl:C -> session=256`

ssl:C is unimplemented, the game might require Nintendo Network access.

**Comment by benderscruffy** [comment]
it is still an issue

**Comment by benderscruffy** [comment]
goes ingame now
only problem is your character is invisible (that's another issue)
