### ISSUE TITLE
Monster Hunter Generations: connection lost when creating a hub (local play)

### ISSUE THREAD

**Issue by hisatsu** [citra-emu/citra#3317]
Build version: citra-windows-mingw-20171218-3f37976

Test Steps:
1. Launch Monster Hunter Generations
2. Click 'hub' on the touch screen
3. Click 'Multiplayer' then 'create hub' (local play)
4. Press Confirm

Expected Result:
a hub created

Actual Result:
connection lost

console log:
`[ 225.373184] Service.NDM <Warning> core/hle/service/ndm/ndm.cpp:EnterExclusiveState:37: (STUBBED) exclusive_state=0x00000002`
`[ 225.374440] Kernel.SVC <Warning> core/hle/kernel/svc.cpp:CreateMemoryBlock:1079: called addr=0x0874A000`
`[ 226.261098] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetFriendKeyList:53: (STUBBED) called, unknown=0, frd_count=100, frd_key_addr=0x0FFFCB50`
`[ 226.263449] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetFriendAttributeFlags:89: (STUBBED) called, count=0, frd_key_addr=0x0FFFCB50, attr_flags_addr=0x0FFFD190`
`[ 247.186539] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetMyFriendKey:97: (STUBBED) called`
`[ 250.523777] Service.NWM <Warning> core/hle/service/nwm/nwm_uds.cpp:Shutdown:444: (STUBBED) called`
`[ 250.524028] Service.NDM <Warning> core/hle/service/ndm/ndm.cpp:LeaveExclusiveState:46: (STUBBED) exclusive_state=0x00000000`

**Comment by Hexagon12** [comment]
Since this is a issue related to Canary (which you can't report issues on), report this issue on the corresponding PR.

Requesting to close.

**Comment by hisatsu** [comment]
then which PR should I report on?
