### ISSUE TITLE
Suggestion: Allow printing to console from homebrew

### ISSUE THREAD

**Issue by RicBent** [citra-emu/citra#3323]
libnds had a very useful function for homebrew development that allowed printing to the consoles of emulators. It just printed to console whenever the instruction "mov r12, r12" occured.

libnds implementation: https://github.com/devkitPro/libnds/blob/master/source/common/debugprint.s

Would be cool if someone could implement something like that into citra/citrulib to allow better debugging.

**Comment by Subv** [comment]
There's an svc called svcOutputDebugString that does just this. Set your log level to Debug so that you can see the output.

**Comment by RicBent** [comment]
Thank you a ton Subv :)
