### ISSUE TITLE
Mario and Luigi: Dream Team crash

### ISSUE THREAD

**Issue by ThunderVolt5560** [citra-emu/citra#3327]
Wew. So I found a crash with Mario and Luigi: Dream Team. In the scene where the Dream Stone goes belowground, the game crashes. It's not too far into the game, can be reproduced within about 3 hours of gameplay (albeit laggily). My version of Citra is HEAD-c143a5a (I recently updated, so this may be inaccurate). My system specs can be found on my Dolphin Profile: 
https://forums.dolphin-emu.org/User-thundervolt
I have a log, though it's incomplete due to the crash cutting it off: 
https://pastebin.com/RbFBJWxP
If you want more detail (just a bit more), here's where I submitted it (scroll all the way down):
https://community.citra-emu.org/t/mario-and-luigi-dream-team-bros-mid-game-crash/1140/20

**Comment by Hexagon12** [comment]
If the log does cut off, can you run citra-qt in the command prompt (or type cmd into Powershell) and copy everything in there after the crash? (it doesn't crash the console, so you can view and copy everything)

**Comment by FearlessTobi** [comment]
It would be great if you also could provide a savegame right before the crash. If you don't know how to do find it: right-click your game in the game list and then there will be a option to open the savegame location.

**Comment by ThunderVolt5560** [comment]
Running Citra in Powershell yields no result, as seen here:
![image](https://user-images.githubusercontent.com/34785496/34321910-4cea8592-e7df-11e7-96ab-efe5877b2692.png)
However, I ran Citra normally to see what would be shown in the console and just screenshot that to see if that would be of any help. I ended up with this:
![image](https://user-images.githubusercontent.com/34785496/34321917-79ae3966-e7df-11e7-8599-5d0b39601ae8.png)
I don't know if wither of those will help, or if I just did it wrong. 

As for the save game, when I located the save game location, there were three:
![image](https://user-images.githubusercontent.com/34785496/34321924-b4a47c24-e7df-11e7-8d29-f86413f70056.png)
However, GitHub doesn't support uploading this file type. So I compressed all three into a ZIP archive, and I'm going to upload that. The ZIP contains all three saves.
[Mario and Luigi Dream Team Bros. Saves.zip](https://github.com/citra-emu/citra/files/1584370/Mario.and.Luigi.Dream.Team.Bros.Saves.zip)

**Comment by wwylele** [comment]
Could you try turning off CPU JIT or/and Shader JIT to see if they resolve the crash?

**Comment by FearlessTobi** [comment]
On my system I'm not able to reproduce the crash in the latest Nightly or Canary. Maybe it's an Intel Graphics specific problem? The guy who opened the Thread in the forums in the first place also had an Intel GPU.

**Comment by ThunderVolt5560** [comment]
Shutting off CPU JIT is the same thing. 
Shutting off Shader JIT allows the scene to progress for one more second (although the Dream Stone Spirit turns invisible) but then Citra halts completely. It doesn't crash, yet speel lowers to 0%. Stopping the game causes it to crash.

**Comment by ThunderVolt5560** [comment]
Tried messing around with my Intel Graphics settings and nothing yet.

**Comment by ThunderVolt5560** [comment]
What is it about Shader JIT that provides a small speedup yet is (sort of) causing this crash?

**Comment by Dragios** [comment]
Is this still an issue?

**Comment by benderscruffy** [comment]
Has this been fixed ???
Please update

**Comment by SleepingSnakezzz** [comment]
This appears to have been a bug with Intel's old drivers. No longer occurs.
