### ISSUE TITLE
Style Savvy Fashion Forward: Exported save data from console gets erased

### ISSUE THREAD

**Issue by Robz8** [citra-emu/citra#3328]
I put the game's save data extracted with Checkpoint, into the game's save location, and whenever I start the game, after it shows "Checking system data..." it then shows "Creating system data..." and as a result, I have to start a new game.
When opening savedata.dat in a hex editor, some parts of the save data is still there.

This wasn't an issue in the older nightly builds.
Tested with nightly build 3f37976.

EDIT: Now tested with nightly build ae42267. Issue persists.

**Comment by wwylele** [comment]
>This wasn't an issue in the older nightly builds.

Could you find the last working nightly?

**Comment by Robz8** [comment]
Tried builds 11baa40 and 2bbff9f. Same issue. And those builds actually used to handle my exported save files just fine, it's just now that the issue occurs.

I get this error in the log (from 11baa40), which I think is the cause.

> [   8.450309] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:53: Non-existing file D:\emulators\citra\nightly_old/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00196500/data/00000001/savedata.dat can't be open without mode create.
[   8.452788] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFile:93: failed to get a handle for file [Wchar: /savedata.dat]

**Comment by Robz8** [comment]
Today, I backed up my save file, and moved it to citra.
It worked! It did not get erased.
So the save file before that must've got corrupted, somehow.
