### ISSUE TITLE
Popups for missing system files repeat and spam the user. 

### ISSUE THREAD

**Issue by chris062689** [citra-emu/citra#3331]
This is a requested enhancement for the pop-up dialog messages when users are missing system files or shared fonts. 

In Pokemon USUM when a user goes to the festival plaza and are missing system files, the game attempts to load these files repeatedly, causing the dialog box to open multiple times, spam the user, and eventually crash the emulator. 

For each type of error, could we keep track of if it's already appeared to the user, and only show the dialogue box once? (We'd still want to log it though in the console)

![](https://i.imgur.com/HK1MZUH.png)

Attached screenshot submitted by a user, notice the black outline indicating multiple popups.

**Comment by einstein95** [comment]
For one, try dumping the required files from a 3DS like it's telling you to do.

Secondly, activate Windows.

**Comment by Subv** [comment]
We could pause the emulation when the error is triggered and resume it when the dialog is closed.

**Comment by chris062689** [comment]
@Subv seems a PR was open for that. Is that the best approach?

**Comment by chris062689** [comment]
An issue I see with pausing the main thread in #3333 is it would cause multiplayer desync if the emulation thread is paused.

**Comment by hyarsan** [comment]
This happened one time.... it nearly crashed my computer!

**Comment by adityaruplaha** [comment]
Erm, it doesn't look at all easy to me, so why is it labelled so? Afaik, 
![image](https://user-images.githubusercontent.com/30696515/34907920-86216b18-f8ac-11e7-891a-e03ca6f04178.png)
No disrespect meant tho.

**Comment by jroweboy** [comment]
@adityaruplaha It is an easy task; was two lines to fix: https://github.com/citra-emu/citra/pull/3333/files It doesn't touch anything but the qt frontend and doesn't require any citra specific knowledge. Also I'm closing this as the fix was merged :)

**Comment by adityaruplaha** [comment]
Oh, I was thinking of writing to a shared location to check if that has appeared.... etc & what not. Also this is  **not** a sarcastic comment.

**Comment by adityaruplaha** [comment]
Anyways, @jroweboy , if u r free, can you please review #3366 , I really need some guidance (also some advice about how to use clang-format).
