### ISSUE TITLE
Citra crashes after loading a game with a folder in nand\00000000000000000000000000000000\title with dddd in the name

### ISSUE THREAD

**Issue by valentinvanelslande** [citra-emu/citra#3332]
example: 000400dbdddd
crash:
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoull

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by wwylele** [comment]
but `000400dbdddd` is not a valid 32-bit ID expected for the first level folder in `.../title`. Did you mean something like `.../title/000400db/dddd0000/` instead?
