### ISSUE TITLE
Xenoblade Chronicles 3D - game doesn't boot

### ISSUE THREAD

**Issue by Hexagon12** [citra-emu/citra#3343]
Tested on HEAD-337e9e1 (Nightly)

The game freezes at boot without any display and the frametime keeps fluctuating.
Note: not related to unimplemented New 3DS cores, since it gets stuck even before that gets initialized.
Log file: [log.txt](https://github.com/citra-emu/citra/files/1597029/log.txt)

**Comment by mailwl** [comment]
it's easy enough to make it run, but it REALLY slow, new 3ds much faster old one, usual computers can't emulate this with reasonable speed

**Comment by nero81af** [comment]
The game is still not launching: any hint on how to launch the game?

**Comment by nero81af** [comment]
> 
> 
> it's easy enough to make it run, but it REALLY slow, new 3ds much faster old one, usual computers can't emulate this with reasonable speed

Any hint on how to mod code and make it run?

**Comment by nero81af** [comment]
up

**Comment by FearlessTobi** [comment]
Fixed when enabling N3DS mode in latest Nightly.

**Comment by nero81af** [comment]
> 
> 
> Fixed when enabling N3DS mode in latest Nightly.

How do you enable N3DS mode? the game still gives me black screen
