### ISSUE TITLE
Super Mario Maker: Stuck while creating save data

### ISSUE THREAD

**Issue by 2ASCII2** [citra-emu/citra#3345]
In Super Mario Maker, while creating a new save data it justs get stuck in a ''freeze screen'' while some ''sounds'' play.

Citra Nightly | HEAD-4192937

Log:
https://pastebin.com/2h6CXtbj 

Specs:
Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Intel(R) HD Graphics 5500
4,0GB DDR3
1366x768 Screen Size
x64 bits
Intel(R) Dual Band Wireless-AC 3160
Intel(R) Wireless Bluetooth(R)
Intel(R) 8 Series Chipset Family SATA AHCI Controller
WDC WD5000LPCX-75VHATO

**Comment by chris062689** [comment]
Duplicate https://github.com/citra-emu/citra/issues/2446
