### ISSUE TITLE
Yu-Gi-Oh! Zexal - World Duel Carnival (3DS0994) hang at "Please enter your name"

### ISSUE THREAD

**Issue by oobol2000oo** [citra-emu/citra#3346]
The game runs smoothly until "enter your name", it's suddenly hang

My specs:

i5-6200U

Intel(R) HD Graphics 520

Nvidia 930M

8GB RAM

Citra Nightly HEAD-9b19c21

[LOGS.txt](https://github.com/citra-emu/citra/files/1599712/LOGS.txt)

**Comment by benderscruffy** [comment]
related to #1583
