### ISSUE TITLE
Photos with Mario (EUR) crash on boot

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#3347]
Specs:
Intel Core i5-7200U
Intel HD Graphics 620
Windows 10 15063

Commit: a66e458
[Log](https://github.com/citra-emu/citra/files/1604893/log_eur.txt)

**Comment by MerryMage** [comment]
Does this run if you disable the CPU JIT?

**Comment by Subv** [comment]
It seems LDRT/STRT and its family can be executed from User mode too.

From the ARM ARM:
`User mode If this instruction is executed in User mode, an ordinary User mode access is performed.`

**Comment by MerryMage** [comment]
That's just unimplemented atm. :p

(Wanted to just confirm it wasn't a different bug that causes, for example, execution of data-as-code. Just because I haven't seen the T family used by usermode game code as of yet.)

**Comment by valentinvanelslande** [comment]
with cpu jit disabled:
[3797.327812] Debug <Critical> core/arm/dyncom/arm_dyncom_trans.cpp:operator():15: Assertion Failed!
Translation cache is full!

**Comment by zhaowenlan1779** [comment]
Please check if this is fixed by #5116

**Comment by vvanelslande** [comment]
> Please check if this is fixed by #5116
I created this issue with a old account and I don't have the game.

**Comment by vvanelslande** [comment]
@zhaowenlan1779 not fixed. now the PC runs out of RAM.
[log.txt](https://github.com/citra-emu/citra/files/4332280/log.txt)

**Comment by benderscruffy** [comment]
still happens using Canary 2600

**Comment by GPUCode** [comment]
Game boots now
