### ISSUE TITLE
Photos with Mario (USA) stuck on loading screen

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#3348]
Specs:
Intel Core i5-7200U
Intel HD Graphics 620
Windows 10 15063

Commit: a66e458
[Log](https://github.com/citra-emu/citra/files/1604948/log_usa.txt)

**Comment by Leo626** [comment]
[Log](https://pastebin.com/sJ8XP0Ee) and [wait tree](https://i.imgur.com/3GSvCZB.png) from cf9bfe0. This hangs right before the camera is suppose to be activated.

**Comment by zhaowenlan1779** [comment]
Fixed by #5116
