### ISSUE TITLE
LEGO Star Wars The Force Awakens (EUR) black screens

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3349]
using the latest nightly 
comes up with one screen about saving then nothing but black screen
[   9.819090] Audio.DSP <Critical> audio_core/hle/pipe.cpp:PipeWrite:166: pipe_number = 3 unimplemented
![lego](https://user-images.githubusercontent.com/2696404/34591520-27f99db2-f1f9-11e7-868d-4bbef2e99171.PNG)
[Debug log.zip](https://github.com/citra-emu/citra/files/1605248/Debug.log.zip)

**Comment by suelo50** [comment]
work for me but still  the song is not playable

**Comment by Dragios** [comment]
Should be fix with DSP LLE #4490

**Comment by benderscruffy** [comment]
has not been added to nightly yet

**Comment by wwylele** [comment]
DSP LLE is merged. Please continue to track this issue on while we fix DSP HLE.

**Comment by benderscruffy** [comment]
it works in the nightly
