### ISSUE TITLE
Hoppechan Minna de Odekake! Waku Waku Hoppe Land!! (Japan) stuck on the first screens

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3350]
it is stuck on the first screens
![hoppo](https://user-images.githubusercontent.com/2696404/34663489-16e67c16-f492-11e7-8dec-637762ef78dc.PNG)
[Debug log.zip](https://github.com/citra-emu/citra/files/1610964/Debug.log.zip)

**Comment by RavenHome1** [comment]
[  17.185443] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:175: ExHeader Program ID mismatch: the ROM is probably encrypted.

**Comment by wwylele** [comment]
@RavenHome1 that message is from another game from the the game list loader, and it is unrelated.

From the log looks like it requires a proper cecd service implementation.

**Comment by valentinvanelslande** [comment]
works merging wwylele:cec

**Comment by valentinvanelslande** [comment]
@benderscruffy #3583 fixes this?

**Comment by FearlessTobi** [comment]
Please retest on latest Nightly.

**Comment by benderscruffy** [comment]
goes ingame now
