### ISSUE TITLE
Drop in FPS after updating canary from 305 to 307

### ISSUE THREAD

**Issue by Hitogami** [citra-emu/citra#3354]
I could play Story of Seasons and SMT IV just fine with 20+ fps. But after updating canary to 307 today SoS drops to 14-18 fps while SMT IV drops under 10 fps

**Comment by wwylele** [comment]
Please test nightly and report the performance drop if any. If nightly is unaffected, please report this to the PR that changed between the two canary version (likely the texcache PR)

**Comment by Leo626** [comment]
Request to close due to lack of response.
