### ISSUE TITLE
Hero Bank 2 (Japan) missing text and other problems

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3357]
using HEAD-8002579
all the text in the game is missing
![hero](https://user-images.githubusercontent.com/2696404/34707128-a8b5f3c4-f546-11e7-86a1-15351275f7df.PNG)
[Debug log.zip](https://github.com/citra-emu/citra/files/1614055/Debug.log.zip)

**Comment by wwylele** [comment]
could you change the log level to Info? Debug level is too verbose.

**Comment by benderscruffy** [comment]
ok here it is
[log.zip](https://github.com/citra-emu/citra/files/1614306/log.zip)

**Comment by benderscruffy** [comment]
this works properly in the latest canary HEAD - 33e81ef
but still the same problems in the latest nightly

**Comment by benderscruffy** [comment]
still the same problem in the latest nightly 
[citra_log.zip](https://github.com/citra-emu/citra/files/2705900/citra_log.zip)

**Comment by benderscruffy** [comment]
still an issue

**Comment by benderscruffy** [comment]
using canary 2602
still an issue with the missing text

**Comment by benderscruffy** [comment]
@GPUCode 
using Canary 2620
still missing text in software ,open gl and vulkan
in software the videos are blank but you can here the sound
(sega video at start and intro video)

**Comment by GPUCode** [comment]
This has not been fixed
