### ISSUE TITLE
Ace Combat - Assault Horizon Legacy+ (Europe) hangs after the mission 1 screen

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3358]
using HEAD-8002579
choose story mode and after the mission 1 screen both screens go black with nothing
[Debug log.zip](https://github.com/citra-emu/citra/files/1617795/Debug.log.zip)

**Comment by valentinvanelslande** [comment]
`[   8.765828] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:RegisterInterruptEvents:248: Registered type=2, pipe=3, event_handle=0x00120038
[   8.766591] Audio.DSP <Critical> audio_core/hle/pipe.cpp:PipeWrite:166: pipe_number = 3 unimplemented
[   8.766649] Service.DSP <Debug> core/hle/service/dsp_dsp.cpp:WriteProcessPipe:334: pipe=3, size=0x20, buffer=0x30A100B0`
pipe3 is unimplemented

**Comment by benderscruffy** [comment]
has not been added to nightly yet

**Comment by wwylele** [comment]
DSP LLE is merged. Please report back and continue to track this issue on while we fix DSP HLE.

**Comment by evelyndooley** [comment]
Can confirm DSP LLE fixes this issue, you are able to begin Mission 1. However the frame rate is extremely low even on high-end hardware.
Specs:
Ryzen 7 1700x @ 3.8GHz
NVIDIA GTX 980 Ti 6GB
16GB DDR4-2933
Here's a log and a screenshot of the mission.
[citra_log.zip](https://github.com/citra-emu/citra/files/2794608/citra_log.zip)
<img width="1324" alt="acecombat" src="https://user-images.githubusercontent.com/31457788/51724819-16d22a00-202d-11e9-94d8-18b644dfda6b.PNG">

**Comment by FearlessTobi** [comment]
Could you also please try out if it works with HLE in the Canary build?

**Comment by evelyndooley** [comment]
The game is fully playable to the end. The only issue was moderate slowdown when the terrain is visible, depending on how complex the model is and how much of it is on screen. It did have an impact on the gameplay at times. 

Here's a log file from Mission 2 which has this problem.
[citra_log.zip](https://github.com/citra-emu/citra/files/2798126/citra_log.zip)

I submitted a compatibility report with a rating of 'Okay'. I think this issue can be safely closed.

**Comment by wwylele** [comment]
Close this until the HLE fix is merged in master

**Comment by benderscruffy** [comment]
it works in the nightly

**Comment by wwylele** [comment]
@benderscruffy 
>Open this until the **HLE** fix is merged in master
