### ISSUE TITLE
Yowamushi Pedal - Ashita e no High Cadence (Japan) crashes out

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3359]
using HEAD-8002579
choose story mode then as it goes to save the game crashes out with HW errors
[Debug log.zip](https://github.com/citra-emu/citra/files/1617810/Debug.log.zip)

**Comment by valentinvanelslande** [comment]
correct region? applets dumped?

**Comment by wwylele** [comment]
Info level log please. Debug level is often too verbose.

**Comment by benderscruffy** [comment]
ok here it is
[log.zip](https://github.com/citra-emu/citra/files/1620772/log.zip)

**Comment by benderscruffy** [comment]
still happens in the latest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2705897/citra_log.zip)

**Comment by benderscruffy** [comment]
still happens in the latest nightly and canary

**Comment by benderscruffy** [comment]
goes ingame now 
no problems so far
