### ISSUE TITLE
Imagine - Fashion World 3D (Europe) top and bottom screen reversed

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3360]
using HEAD-8002579
as you can see from the pictures the top and bottom screen are not correct
![fashion](https://user-images.githubusercontent.com/2696404/34761245-ecd5fe32-f61d-11e7-84af-ef412bb2a51c.PNG)
![fashion1](https://user-images.githubusercontent.com/2696404/34761249-efbeda6a-f61d-11e7-940f-0cc077660d7e.PNG)
[Debug log.zip](https://github.com/citra-emu/citra/files/1617899/Debug.log.zip)

**Comment by Hexagon12** [comment]
Log level: Info, please.

**Comment by wwylele** [comment]
Could you also upload a screenshot from 3DS for comparison?

**Comment by benderscruffy** [comment]
https://www.youtube.com/watch?v=nCsd21t6Njc
here is a video
[log.zip](https://github.com/citra-emu/citra/files/1624439/log.zip)

**Comment by benderscruffy** [comment]
using the latest nightly this has been fixed
![fashion](https://user-images.githubusercontent.com/2696404/50621829-8fb8f700-0f43-11e9-9529-e3c3cc60c5c9.PNG)
