### ISSUE TITLE
Professor layton and the azran legacy (Slowdown)

### ISSUE THREAD

**Issue by Djipi71** [citra-emu/citra#3368]
When I use the last rev , when i play professor Layton, after playing like 20 minutes , when you have 2 or 3 characters at screen , there is a slowdown. Strange because if you stop emulator and restart your savegame , the same scene is ok without slowdown.

**Comment by Arachno67** [comment]
I'm experiencing this issue since Canary build 256. I can remedy the problem temporarily by switching resolutions, let's hope devs will find a solution. My post linked below:

https://community.citra-emu.org/t/professor-layton-games-slowdown/8460/5

**Comment by Hexagon12** [comment]
Please report this bug on the corresponding PR: #3281 and close this issue.

**Comment by MerryMage** [comment]
Thanks for taking the time to open an issue and thanks for the report.

As the code in question is not yet part of the codebase (this wasn't clear from the initial issue report!) and that there was no additional useful information provided, I'm closing this issue.
