### ISSUE TITLE
Unable to play any game!

### ISSUE THREAD

**Issue by Murtazaraza2002** [citra-emu/citra#3372]
I keep getting this error "An error occured while running the video core"
log file contains:
[   0.000000] Frontend <Info> citra_qt/main.cpp:CheckForUpdates:412: Update check started
[   5.399852] Frontend <Info> citra_qt/main.cpp:OnUpdateFound:425: No updates found
[  17.304353] Frontend <Info> citra_qt/main.cpp:BootGame:552: Citra starting...
[  17.316034] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:488: GL_VERSION: 1.1.0
[  17.316059] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:489: GL_VENDOR: Microsoft Corporation
[  17.316067] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:490: GL_RENDERER: GDI Generic
[  17.316078] Render <Error> video_core/video_core.cpp:Init:35: initialization failed !
[  17.316086] Core <Critical> core/core.cpp:Load:106: Failed to initialize system (Error 9)!

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum. Please use the [**forums**](https://community.citra-emu.org/) for support requests.

Requesting to close.
