### ISSUE TITLE
High level design documentation

### ISSUE THREAD

**Issue by techzilla** [citra-emu/citra#3374]
Unable to locate any high level design documentation, such as rationalizations for choices made, libraries and any considerations regarding other opensource code.

**Comment by MerryMage** [comment]
Hi! Welcome to Citra.

I'm uncertain of what kinds of choices and decisions you are referring to. Justification and discussion on the issue of library choices had historically occured on the IRC channel.

What type of high-level design documentation would interest you? Would a brief overview of the codebase from 50,000 feet be something you might find valuable? If you have any specific, concrete questions, feel free to drop by the IRC channel or Discord for a chat.

**Comment by MerryMage** [comment]
We have a built-in profiler (microprofile). Use exclusive times as those remove overlap between components.

Design documentation for dynarmic is available here: https://github.com/MerryMage/dynarmic/tree/r1/docs (Use the `r1` tag, future commits are not yet Citra-compatible.)

>  Essentially it was the ARM11 emulation that is the biggest problem, and adding new features is adding a non insignificant overhead.

There hasn't been a change to ARM11 emulation in the period that you're describing.

---

I'm not sure you're reading your profile correctly. All system calls pass through CallSVC, so dynarmic would (obviously) almost always be at the top of the call-graph.

The current bottleneck is GPU emulation.

**Comment by MerryMage** [comment]
<img width="1073" alt="screen shot 2018-01-14 at 14 02 33" src="https://user-images.githubusercontent.com/8682882/34916666-bf8c52be-f933-11e7-9de5-1c058078c63c.png">

In this example scene, for example, we notice that CPU emulation makes up 10% of the frametime. Surface management makes up 25% of it, shader emulation 20%, and drawing makes up the majority of the remainder.

**Comment by techzilla** [comment]
This is what I'm talking about when discussing design choices, every time you don't use something that is already used within the open source community.  You should explain how the existing options don't fulfill the requirements, and how it was not possible to do a commit to the upstream to meet requirements. 

It shows that thoughtful design is part of the project, and thus investing time in this project is far more beneficial than starting another project.

**Comment by MerryMage** [comment]
**If** you are speaking about the CPU core specifically, there are two alternatives: (Can you *please* be more concrete instead of hand-wavy and vague.)

* Unicorn: Unicorn has a greater focus on fine-grained instrumentation; performance is a secondary goal. We are already faster than unicorn, qemu's code-emission is quite easy to beat. Unicorn will unlikely be receptive to necessary performance enhancements because that would constrain instrumentation.
* SkyEye: We already use SkyEye as an alternative CPU core.

As for everything else we pretty much use presently available open source libraries where available.
