### ISSUE TITLE
Teenage Mutant Ninja Turtles - Master Splinter's Training Pack (Europe) freezes up

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3375]
using the latest nightly
which ever game you choose on the title screen the game freezes up with the music playing in the background
![tmnt](https://user-images.githubusercontent.com/2696404/34913555-e1d716a8-f93b-11e7-9fc9-2d73446527d2.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1629114/log.zip)

**Comment by Hexagon12** [comment]
`[  54.746813] Service <Error> core/hle/service/service.cpp:HandleSyncRequest:97: unknown / unimplemented function 'PrepareToDoApplicationJump': port=APT:A, cmd_buff[1]=0x2, cmd_buff[2]=0xFFFFFFFF, cmd_buff[3]=0xFFFFFFFF, cmd_buff[4]=0x0
[  54.748222] Audio.DSP <Info> audio_core/hle/pipe.cpp:PipeWrite:150: Application has requested sleep of DSP hardware`

The game tries to shutdown itself to launch the other game.

**Comment by tom-overton** [comment]
I'm pretty sure this same issue causes Fire Emblem Fates to crash when pressing L+R+Start+Select. On real hardware, that works as a soft reset code to take you back to the title screen. On Citra, it crashes the emulator, and the log file says this:

`[  11.347034] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:97: unknown / unimplemented function 'PrepareToDoApplicationJump': port=APT:A, cmd_buff[1]=0x2, cmd_buff[2]=0xFFFFFFFF, cmd_buff[3]=0xFFFFFFFF, cmd_buff[4]=0x0
[  11.349952] Audio.DSP <Info> audio_core\hle\pipe.cpp:DSP::HLE::PipeWrite:150: Application has requested sleep of DSP hardware
[  11.351916] Service.DSP <Info> core\hle\service\dsp_dsp.cpp:Service::DSP_DSP::RegisterInterruptEvents:253: Unregistered interrupt=2, channel=2, event_handle=0x00000000
[  11.352593] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:97: unknown / unimplemented function 'UnloadComponent': port=dsp::DSP
[  11.353188] Service.GSP <Warning> core\hle\service\gsp\gsp_gpu.cpp:Service::GSP::GSP_GPU::ReleaseRight:692: called
[  11.354576] Service <Error> core\hle\service\service.cpp:Service::Interface::HandleSyncRequest:97: unknown / unimplemented function 'DoApplicationJump': port=APT:A, cmd_buff[1]=0x0, cmd_buff[2]=0x0, cmd_buff[3]=0x2, cmd_buff[4]=0x0, cmd_buff[5]=0x802, cmd_buff[6]=0x0
[  11.355915] Kernel.SVC <Info> core\hle\kernel\svc.cpp:Kernel::ExitProcess:147: Process 10 exiting
[  11.356872] Debug <Critical> core\hle\kernel\svc.cpp:Kernel::ExitProcess::<lambda_0432e0ddd9e2cc6194e0bda1b7ce1ab1>::operator ():165: Assertion Failed!
Exiting processes with non-waiting threads is currently unimplemented`

**Comment by benderscruffy** [comment]
it is still an issue

**Comment by benderscruffy** [comment]
both games go ingame now
no problems so far
