### ISSUE TITLE
Funky Barn 3D (Europe) cannot pass difficulty screen

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3376]
using the latest nightly
![funky](https://user-images.githubusercontent.com/2696404/34913907-7376cffc-f943-11e7-91d7-82007d99eeee.PNG)
after  you choose your difficulty it says the sd card has been removed
[log.zip](https://github.com/citra-emu/citra/files/1629129/log.zip)

**Comment by Hexagon12** [comment]
`[  45.825177] Service <Error> core/hle/service/service.cpp:HandleSyncRequest:97: unknown / unimplemented function 'OpenRawFile': port=cecd:u, cmd_buff[1]=0x52200, cmd_buff[2]=0x2, cmd_buff[3]=0x2, cmd_buff[4]=0x20, cmd_buff[5]=0x9FA4980
[  45.825313] Service <Error> core/hle/service/service.cpp:HandleSyncRequest:97: unknown / unimplemented function 'ReadRawFile': port=cecd:u, cmd_buff[1]=0x60, cmd_buff[2]=0x60C, cmd_buff[3]=0xFFFF5DC`

CECD isn't implemented.

**Comment by FearlessTobi** [comment]
Please retest on latest Nightly.

**Comment by benderscruffy** [comment]
goes ingame now
