### ISSUE TITLE
Pippi Longstocking 3D (Europe) crashes out on the title screen

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3377]
using the latest nightly
the game crashes out on the title screen
![pippi](https://user-images.githubusercontent.com/2696404/34913962-59ae3d84-f944-11e7-820c-1ad07cf0838f.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1629130/log.zip)

**Comment by wwylele** [comment]
could you screenshot the log window on crash? Because the  log file is incomplete.

**Comment by benderscruffy** [comment]
![pippi1](https://user-images.githubusercontent.com/2696404/34922115-77224b3a-f9c6-11e7-93e4-9e83fda1001f.PNG)

**Comment by benderscruffy** [comment]
![pippi](https://user-images.githubusercontent.com/2696404/37652603-024290f2-2c77-11e8-86e0-0a231607d9e6.PNG)
goes ingame now
