### ISSUE TITLE
Disney Princess - My Fairytale Adventure (USA) corrupt graphics 

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3378]
using the latest nightly 
and the top screen during the intro and to customise your princess are corrupt and missing graphics
that is as far as i can get so far
here is a video pf the gameplay
https://www.youtube.com/watch?v=tpSpdwWXWMU
![disney](https://user-images.githubusercontent.com/2696404/34923584-420ba286-f9d8-11e7-84da-0aaa9ab3afb1.PNG)
![disney1](https://user-images.githubusercontent.com/2696404/34923585-441ff4e6-f9d8-11e7-9f47-1fe097f5a150.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1630065/log.zip)

**Comment by FearlessTobi** [comment]
@benderscruffy Please retest on latest *Canary.*

**Comment by benderscruffy** [comment]
doesnt get to the intro anymore
crashes out at the start of a new game

**Comment by benderscruffy** [comment]
has been fixed
