### ISSUE TITLE
Rise of the Guardians (Europe) corrupt save data

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3379]
using the latest nightly
every time you load the game it says the data is corrupt and deletes it
![rise](https://user-images.githubusercontent.com/2696404/34923706-32c549a2-f9d9-11e7-8d88-c53245934ef5.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1630078/log.zip)

**Comment by benderscruffy** [comment]
still happens in the latest nightly
![rise](https://user-images.githubusercontent.com/2696404/50621405-aa3da100-0f40-11e9-9c45-942cdbd28c0f.PNG)
![rise1](https://user-images.githubusercontent.com/2696404/50621406-ac076480-0f40-11e9-904c-99edfd2e38b2.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2722623/citra_log.zip)

**Comment by zhaowenlan1779** [comment]
Please check if this is fixed by #5120

**Comment by benderscruffy** [comment]
has been fixed

**Comment by zhaowenlan1779** [comment]
Was this fixed by #5120 or was it fixed in nightly already?
If it is only fixed in Canary please do not close this right now.
