### ISSUE TITLE
Art Academy - Lessons for Everyone (USA) black screens

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3383]
using the latest nightly HEAD-79dca3d
nothing but black screens
[log.zip](https://github.com/citra-emu/citra/files/1630322/log.zip)

**Comment by Hexagon12** [comment]
`[   2.904772] Audio.DSP <Critical> audio_core/hle/pipe.cpp:PipeWrite:166: pipe_number = 3 unimplemented`

**Comment by Dragios** [comment]
Should be fix with DSP LLE #4490

**Comment by benderscruffy** [comment]
has not been added to nightly yet

**Comment by wwylele** [comment]
DSP LLE is merged. Please continue to track this issue on while we fix DSP HLE.

**Comment by benderscruffy** [comment]
it works in the nightly
