### ISSUE TITLE
Crash when trying to run dumped SKATER Browser from N3DS

### ISSUE THREAD

**Issue by frozenLake** [citra-emu/citra#3384]
`[   0.000000] Frontend <Info> citra_qt/main.cpp:CheckForUpdates:412: Update check started
[   1.031031] Frontend <Info> citra_qt/main.cpp:OnUpdateFound:425: No updates found
[   4.559814] Frontend <Info> citra_qt/main.cpp:BootGame:552: Citra starting...
[   4.770856] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\charlie\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00010202/content/00000000.app is tainted, application behavior may not be as expected!
[   4.772100] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\charlie\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00010402/content/00000000.app is tainted, application behavior may not be as expected!
[   4.772635] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\charlie\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00014002/content/00000000.app is tainted, application behavior may not be as expected!
[   4.773142] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\charlie\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00014102/content/00000000.app is tainted, application behavior may not be as expected!
[   4.773735] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\charlie\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00014202/content/00000000.app is tainted, application behavior may not be as expected!
[   4.774643] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\charlie\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00014302/content/00000000.app is tainted, application behavior may not be as expected!
[   4.775774] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\charlie\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/000400db/00010302/content/00000000.app is tainted, application behavior may not be as expected!
[   4.779414] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:488: GL_VERSION: 3.3.0 NVIDIA 388.13
[   4.781175] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:489: GL_VENDOR: NVIDIA Corporation
[   4.781678] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:490: GL_RENDERER: GeForce GTX 1050 Ti/PCIe/SSE2
[   4.784901] Loader <Info> core/loader/ncch.cpp:Load:159: Program ID: 0004003020009402
[   4.785488] Service.FS <Warning> core/file_sys/ncch_container.cpp:OpenFile:109: Failed to open C:\Users\charlie\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004003e/20009402/content/00000000.app
[   4.805724] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:114: ExHeader kernel version: 2.46
[   4.807502] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:SetPreferredRegionCode:615: Preferred region code set to 1
[   4.835257] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:48: (STUBBED) called
[   4.903786] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:70: (STUBBED) called
[   4.918184] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetLockHandle:501: (STUBBED) called handle=0x00038008 applet_attributes=0x00000002
[   4.922793] Service.FS <Warning> core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:811: (STUBBED) called, version: 0x0B0200C8
[   4.932299] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:803: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001, input_addr=0x0FFFFF60, output_addr=0x0FFFFF64
[   4.938956] Service <Error> core/hle/service/service.cpp:HandleSyncRequest:97: unknown / unimplemented function 'Initialize': port=http:C, cmd_buff[1]=0x0, cmd_buff[2]=0x20, cmd_buff[3]=0x90019, cmd_buff[4]=0x0, cmd_buff[5]=0x0
[   4.985979] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:663: called flag=00000000 process=10 thread_id=0
[   5.018702] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\charlie\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00014002/content/00000000.app is tainted, application behavior may not be as expected!
[   5.020469] Service.FS <Warning> core/file_sys/ncch_container.cpp:ReadOverrideRomFS:399: File C:\Users\charlie\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00014002/content/00000000.app.romfs overriding built-in RomFS
[   5.080026] Service.FRD <Warning> core/hle/service/frd/frd.cpp:SetClientSdkVersion:158: (STUBBED) called, version: 0x0B0200C8
[   5.081880] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetMyPresence:35: (STUBBED) called
[   5.086105] Service.AC <Warning> core/hle/service/ac/ac.cpp:SetClientVersion:166: (STUBBED) called, version: 0x0B0200C8
[   5.087505] Service.AC <Warning> core/hle/service/ac/ac.cpp:CreateDefaultConfig:30: (STUBBED) called
[   5.088581] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function '0x250042': port='ac:u' cmd_buf={[0]=0x250042, [1]=0x1, [2]=0x800002, [3]=0xffffd98}
[   5.089708] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function '0x2c0042': port='ac:u' cmd_buf={[0]=0x2c0042, [1]=0x3, [2]=0x800002, [3]=0xffffd98}
[   5.096137] Service.NDM <Warning> core/hle/service/ndm/ndm.cpp:QueryExclusiveMode:55: (STUBBED) exclusive_state=0x00000000
[   5.097556] Service.CECD <Warning> core/hle/service/cecd/cecd.cpp:GetCecStateAbbreviated:28: (STUBBED) called
[   5.100670] Kernel.SVC <Warning> core/hle/kernel/svc.cpp:CreateMemoryBlock:1109: called addr=0x08041000
[   5.129915] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:LoadComponent:148: Firmware hash: 0xc52cbdb9a519f782
[   5.130954] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:LoadComponent:152: Structures hash: 0xe9c69ad6eb7c76f2
[   5.131807] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:LoadComponent:157: (STUBBED) called size=0x35378, prog_mask=0x000300FF, data_mask=0x003500FF, buffer=0x3458F260
[   5.133211] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:RegisterInterruptEvents:248: Registered type=2, pipe=2, event_handle=0x00160035
[   5.133833] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:GetSemaphoreEventHandle:174: (STUBBED) called
[   5.134448] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphoreMask:469: (STUBBED) called mask=0x00002000
[   5.135236] Audio.DSP <Info> audio_core/hle/pipe.cpp:PipeWrite:134: Application has requested initialization of DSP hardware
[   5.135954] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphore:271: (STUBBED) called
[   5.138303] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphore:271: (STUBBED) called
[   5.154020] Kernel.SVC <Error> core/hle/kernel/svc.cpp:CreateThread:754: Newly created thread must run in the SysCore (Core1), unimplemented.
[   5.202077] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:803: (STUBBED) called command=0x00000007, input_size=0x00000004, output_size=0x00000001, input_addr=0x0FFFFFA8, output_addr=0x0FFFFF74
[   5.203272] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:803: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001, input_addr=0x0FFFFF78, output_addr=0x0FFFFF7C
[   5.205568] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:478: (STUBBED) app_id=276
[   5.206233] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:803: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001, input_addr=0x0FFFFAC8, output_addr=0x0FFFFACC
`

It appears that the issue might be a bunch of missing services or something. I'm using version HEAD-79dca3d, and I dumped from a N3DS on 11.6.0-39U with Luma installed.

**Comment by CHNBUILD** [comment]
Typeface? I didn't get it.

**Comment by Dragios** [comment]
New 3DS mode already implemented. Can someone test this on latest Nightly?

**Comment by GPUCode** [comment]
Fixed in https://github.com/citra-emu/citra/pull/6828
