### ISSUE TITLE
Zelda Picross (homebrew) stuck on first screen

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3388]
https://gbatemp.net/threads/release-zelda-picross.452708/
download
https://github.com/nop90/ZeldaPicross/releases/download/v1%2C0RC/ZeldaPicross.1.0RC.zip

**Comment by MerryMage** [comment]
Hi, you're making a large number of low-effort issue reports that do not contain any useful information. Could you at least triage the bug?

**Comment by benderscruffy** [comment]
that is why i have put the download links in for the devs to download and there is the source on the pages aswell to look at most times
with homebrew anyone can download it and look at the source

**Comment by FearlessTobi** [comment]
https://pastebin.com/8UPxwraS This is the relevant part of the log.

This game seems to check for New3DS and hangs because of badly stubbed functions, but I will try to test this further.

**Comment by FearlessTobi** [comment]
The games goes ingame. It was just me beeing soo dumb. On the first screen you just have to push the A button and the game will start.

![funzt](https://user-images.githubusercontent.com/20753089/35391647-8a55d44e-01df-11e8-9a62-bccd6bfa6440.png)

I think this issue can be closed.
