### ISSUE TITLE
Feature Request --- Multiple games folders

### ISSUE THREAD

**Issue by superheri** [citra-emu/citra#3391]
Citra is actually offering the option to select a folder to automatically search the games in it and show them on the menu screen. It can also allow to search in subfolders witch is nice. But for people like me who have games on multiple drives, this option is actually not enough.

So this is what I am asking here. Could you add the opportunity to select multiple folders, like in dolphin?

This capture is taken from dolphin :
![image](https://user-images.githubusercontent.com/30275781/34956036-469957e0-f9f5-11e7-84a1-bc76fd30287e.png)

**Comment by jroweboy** [comment]
I like the idea, but i don't like how dolphin does it. I also don't have an idea of a *better* way to do it, so if someone wants to work on this, I'd approve of this design. Perhaps just move some options out of the general tab and add this to there? Not keen on adding a brand new tab just for one config option. But maybe it'll be useful when we allow customizing of the location emulated sdcard/nand and so on. Just some thoughts; thanks for the idea :)

**Comment by BreadFish64** [comment]
I can probably slip this in with my other game list improvements

**Comment by adityaruplaha** [comment]
Is this being worked upon currently? @BreadFish64

**Comment by LogPod** [comment]
Also add an apply box ;)

**Comment by BreadFish64** [comment]
Nope, I have ideas about this, but I'm busy with other things currently
