### ISSUE TITLE
Monster 4x4 3D (USA) music and sound fx just a loud static sound

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3392]
using nightly HEAD-79dca3d
music and sound fx just a loud static sound
here is a video of how it is supposed to sound
https://www.youtube.com/watch?v=vBrI7xTytbU
[log.zip](https://github.com/citra-emu/citra/files/1633994/log.zip)

**Comment by FearlessTobi** [comment]
Should also be realated to https://github.com/citra-emu/citra/issues/3313.

**Comment by FearlessTobi** [comment]
Very likely fixed by #4483. If that's not a case, leave a comment and we can reopen this. @benderscruffy
