### ISSUE TITLE
Amazing Spider-Man, The (USA) music,voice and sound fx are loud static noise

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3393]
using nightly HEAD-79dca3d
music and sound fx and voices just a loud static sound from the title screen onwards
here is a video of how it is supposed to sound
https://www.youtube.com/watch?v=slwCk2-vVxY
[log.zip](https://github.com/citra-emu/citra/files/1634197/log.zip)

**Comment by FearlessTobi** [comment]
Same issue as https://github.com/citra-emu/citra/issues/3313.

**Comment by wwylele** [comment]
Fixed by #4483
