### ISSUE TITLE
 Wan Nyan Pet Shop (Japan) stuck on first screen

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3397]
the game is stuck on the first screen
![wan](https://user-images.githubusercontent.com/2696404/35093722-279072f8-fc7e-11e7-82b8-3d3c517feb45.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1642486/log.zip)

**Comment by valentinvanelslande** [comment]
CECD is unimplemented

**Comment by valentinvanelslande** [comment]
@benderscruffy #3583 fixes this?

**Comment by FearlessTobi** [comment]
Please retest on latest Nightly.

**Comment by benderscruffy** [comment]
goes ingame now
