### ISSUE TITLE
Nekketsu Kouha Kunio-Kun Special (Japan) corrupt characters

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3400]
whenever any character is facing left the character is cut in half but if they are facing right they are alright
![nekko](https://user-images.githubusercontent.com/2696404/35142644-d2dbaf72-fd39-11e7-8a47-37d18d16bd65.PNG)
[log.zip](https://github.com/citra-emu/citra/files/1645848/log.zip)

**Comment by benderscruffy** [comment]
still happens in the latest nightly
![net](https://user-images.githubusercontent.com/2696404/50718756-ece0b400-10cd-11e9-8cb4-aff0bc87a27a.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2729024/citra_log.zip)

**Comment by benderscruffy** [comment]
it is still an issue

**Comment by benderscruffy** [comment]
still an issue

**Comment by Dragios** [comment]
Should be fix by PR #6945
