### ISSUE TITLE
Layton's Mystery Journey - Katrielle and the Millionaires' Conspiracy (USA)cannot get past title screen

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3406]
the title screen is missing and and the bottom screen is supposed to say touch to continue but you cannot pass the screen
this works in the latest canary 
[log.zip](https://github.com/citra-emu/citra/files/1650997/log.zip)
![layton](https://user-images.githubusercontent.com/2696404/35208858-58b3dc58-ff85-11e7-8d5f-915155d39637.PNG)

**Comment by FearlessTobi** [comment]
Im able to boot the game just fine using the EU version.

![conspiracy](https://user-images.githubusercontent.com/20753089/35222849-96ecbc98-ff7f-11e7-90c6-36bbb5862148.png)

**Comment by benderscruffy** [comment]
using nightly HEAD-dca5fd2 it goes ingame
