### ISSUE TITLE
Feature Request　Screen rotation

### ISSUE THREAD

**Issue by GAWAYU1** [citra-emu/citra#3413]
I am grateful for the wonderful emulator.
But there is a problem. Please confirm the above image. I would like to make the screen vertical using the UI.
My ideal is to be like the image below.
Are developers planning to implement rotation  the screen?
Thank you for reading.

![0001](https://user-images.githubusercontent.com/35886339/35479816-b49ca3f2-0443-11e8-8031-6cab792100ff.jpg)

![0002](https://user-images.githubusercontent.com/35886339/35479819-bb555c20-0443-11e8-87c0-02f1599bb86c.jpg)

**Comment by j-selby** [comment]
Likely dup of #1534

**Comment by GAWAYU1** [comment]
I'm sorry, I was short of confirmation
