### ISSUE TITLE
Dragon Quest 8 Sound FX Missing in every cutscenes

### ISSUE THREAD

**Issue by firehawkx** [citra-emu/citra#3414]
Problem : No sound effects are played during any cutscenes of the game (this includes when casting zoom to teleport)

Video Reference :
On Citra : https://youtu.be/Zgy9IyhY10Y?t=22m26s
On 3DS : https://youtu.be/arzxUwOK6xg?t=36m56s

I did not capture those 2 video, but notice how you hear the waterfall in the version captured on an actual 3ds while the one recorded on citra does not. It's even more jaring and weird in later cutscenes when a character casts a spells and you heard nothing at all. Or in a bar fight when all you heard is music while stuff is flying all over the place.

I have been testing DQ8 (both US and EUR versions) on 5 different Citra versions/builds
I tried with both Nightly and Canary builds
citra-windows-mingw-20180128-27ed8a3
citra-windows-mingw-20180122-11af6f3

as well as with many other build found all over the place
citra-windows-mingw-20171212-dec3a46
Citra Night Wolf 360 Build (HEAD-109b5ed)
Citra-CC-Mingw_18_01_2018_warweeny-NewUpdate (Master-1776e235-dirty)
(this last one is the most stable and fastest build i found)

With all 5 of them, there is no audio at all when casting zoom, or any sfx during every cutscenes...

Sadly as I am currently replaying through the game, i doubt this will get fixed until I am done... 
but if my info can help the project and others in the future then its good :)

do not hesitate to ask if you need any more info, i went through the FAQ but wasnt sure if i needed to provide anything else...

**Comment by Hexagon12** [comment]
Please provide a full log from the latest Nightly build.

**Comment by firehawkx** [comment]
Alright as requested, I followed the instructions given on this page here to create a log file... 
https://community.citra-emu.org/t/how-to-upload-the-log-file/296

Downloaded the most recent nightly from 15h ago, created the log, loaded my save game, cast zoom, and thats it... no sound effects at all are being played (for the spell, or when the character bonk their head on the ceiling either)

Here is the log :
https://pastebin.com/2sikCayh

let me know if i can assist in any other way! :)

**Comment by tywald** [comment]
Should been fixed by #3459 Zoom spell's sound effect plays now since Nightly-560.
@firehawkx can you verify if it's been fixed on your end as well?

**Comment by firehawkx** [comment]
I actually tested on latest canary a day or two ago and it was indeed fixed!! :)

With the amazing progress being made recently its really awesome!

Thanks for your time!
