### ISSUE TITLE
Taiko no Tatsujin - Chibi Dragon to Fushigi na Orb (Japan) freezes up on loading screen

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3418]
using HEAD-27ed8a3
freezes up on the loading screen
[  50.441908] Audio.DSP <Critical> audio_core/hle/pipe.cpp:PipeWrite:166: pipe_number = 3 unimplemented
[log.zip](https://github.com/citra-emu/citra/files/1688609/log.zip)

**Comment by Dragios** [comment]
Should be fix with DSP LLE #4490

**Comment by benderscruffy** [comment]
has not been added to nightly yet

**Comment by wwylele** [comment]
DSP LLE is merged. Please continue to track this issue on while we fix DSP HLE.

**Comment by benderscruffy** [comment]
it works in the nightly
