### ISSUE TITLE
Citra crashes

### ISSUE THREAD

**Issue by PompoBoi** [citra-emu/citra#3419]
I have downloaded the latest version of Citra found on the homepage but when i start citra.exe or citra-qt.exe it immediately closes. I have reinstalled twice now but it isnt working.

Specs ryzen 5 1400, gtx1050, A320M

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum. Please use the [**forums**](https://community.citra-emu.org/) for support requests.

Requesting to close.
