### ISSUE TITLE
Build fails since dca5fd291fcdf4cb40852af9807e424089377d68

### ISSUE THREAD

**Issue by GabMus** [citra-emu/citra#3420]
When building from commit `dca5fd291fcdf4cb40852af9807e424089377d68` I get the following: https://pste.eu/p/hvt6.html (please ignore the colored weird characters in the paste, this is caused by copy-pasting from my zsh shell with non-standard characters).

Building from `8e4b806419007e5cc1b4ef8e171e8825fa03c7e7` works fine tho.

I am building from Arch Linux.

**Comment by MerryMage** [comment]
`git submodule update`.

**Comment by GabMus** [comment]
Build works now, thanks.
