### ISSUE TITLE
Citra crashes when trying to load native modules

### ISSUE THREAD

**Issue by hax0kartik** [citra-emu/citra#3424]
Due to [Line number 40](https://github.com/citra-emu/citra/blob/a21b9deb986c21114207b099de1438163aa99748/src/core/hle/service/sm/sm.cpp#L40) in SM HLE implementation native modules fail to load and error out. I'm not sure how this can be fixed.
Error log:-
![image](https://user-images.githubusercontent.com/16360444/35785001-05715a20-0a43-11e8-8384-b58b2ad53a81.png)

**Comment by Subv** [comment]
You have to remove the line that registers the module you want to run from service.cpp.

**Comment by FearlessTobi** [comment]
It is now possible to toggle the loading of LLE modules in the UI.
