### ISSUE TITLE
System Settings App, can't past 3D check

### ISSUE THREAD

**Issue by RealRexen** [citra-emu/citra#3425]
Nightly: 587450c
Canary: 5133a3

Decided to boot the Settings app to see how far I can get and I can't get pass the 3D check which means the setup of settings can't be finish.

![capture](https://user-images.githubusercontent.com/18408903/35809832-c902db94-0a57-11e8-8186-52c2ebce7559.PNG)

**Comment by wwylele** [comment]
For anyone wondering, I have already tried stubbing https://github.com/citra-emu/citra/blob/master/src/core/hle/shared_page.h#L53 with some non-zero values, but it didn't work. It seems that the app uses other method to detect the 3D slider. The only work around I have found is dumping a config savegame from 3ds OR create a config block 0x00110000 with non-zero value, to indicate that this 3DS doesn't need to do system setup and thus bypass the 3d screen check.

**Comment by valentinvanelslande** [comment]
Change the console model to 2DS/New 2DS
Change offset 0xC8 of config savegame to 03 for 2DS and 05 for New 2DS

**Comment by Subv** [comment]
@wwylele Try changing ledstate_3d, IIRC some things check for that value instead of sliderstate when checking the 3D state.

**Comment by RealRexen** [comment]
I been thinking if we got this to work would that fix some games not working? Because I swear I heard some games don't like it if the 3ds hasn't been setup yet

**Comment by BreadFish64** [comment]
@RealRexen you could pretty easily test that by figuring out which games require the config savegame from a 3DS (I can't think of any right now) and then test those games with a generated config savegames and the edit wwylele suggested.

**Comment by Tres-Tigers** [comment]
> Change the console model to 2DS/New 2DS
> Change offset 0xC8 of config savegame to 03 for 2DS and 05 for New 2DS

Where is this offset to change?

> @wwylele Try changing ledstate_3d, IIRC some things check for that value instead of sliderstate when checking the 3D state.

Where is this ledstate_3d?

> For anyone wondering, I have already tried stubbing https://github.com/citra-emu/citra/blob/master/src/core/hle/shared_page.h#L53 with some non-zero values, but it didn't work. It seems that the app uses other method to detect the 3D slider. The only work around I have found is to dump a config savegame from 3ds OR to create a config block 0x00110000 with non-zero value, to indicate that this 3DS doesn't need to do system setup and thus bypass the 3d screen check.

Where would I put this config block 0x00110000 at, and how?

**Comment by FabulousPhantom** [comment]
You can go past the 3D check by enabling Stereoscopic 3D Mode in Citra's Graphics configuration.

**Comment by SleepingSnakezzz** [comment]
https://github.com/citra-emu/citra/pull/5676

**Comment by Anonymous941** [comment]
What about changing to a 2DS?
