### ISSUE TITLE
Gamepad stop working

### ISSUE THREAD

**Issue by Lleon23** [citra-emu/citra#3427]
Gamepad dont work if i turn him on after loading Citra. Also this is happen if gamepad discharged and i turn him on after recharge or use another gamepad.

Im using xbox 360 wireless gampads.
Citra build: Canary 5133a33

**Comment by adityaruplaha** [comment]
Known issue I guess. Just try to prevent this from happening.

**Comment by Lleon23** [comment]
Yes find this in issue #2056
