### ISSUE TITLE
Minecraft New 3DS - Crashes on boot

### ISSUE THREAD

**Issue by hyarsan** [citra-emu/citra#3428]
On the latest Canary release of Citra, Minecraft - New 3DS crashes on boot.

> [ 515.254513] Debug <Critical> core/hle/kernel/svc.cpp:operator():758: Assertion Failed!
> Unsupported thread processor ID: 2

I am using Windows 10 64-bit.

**Comment by Hexagon12** [comment]
Duplicate of #2934.

Requesting to close.

**Comment by literalmente-game** [comment]
Duplicate of https://github.com/citra-emu/citra/issues/2934

**Comment by hyarsan** [comment]
alright, I'll close it myself
