### ISSUE TITLE
Triforce Heroes crashes after like 2 seconds after booting on latest Citra Canary

### ISSUE THREAD

**Issue by hyarsan** [citra-emu/citra#3433]
This did not always happen. Just recently Triforce Heroes started crashing when you boot on the latest Canary release. I am using Windows 10 64-bit if that matters.

> [  59.946895] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'ReplySleepQuery': port='APT:A' cmd_buf={[0]=0x3e0080, [1]=0x300, [2]=0x0}
> [  59.951668] Loader <Error> core/loader/loader.cpp:GetLoader:126: Failed to load file C:\Users\yarsa\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/00040030/0000c502/content/00000000.app
> [  59.953188] Service.NS <Warning> core/hle/service/ns/ns.cpp:LaunchTitle:19: Could not find .app for title 0x000400300000c502
> [  59.956254] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'SaveVramSysArea': port='gsp::Gpu' cmd_buf={[0]=0x190000}
> [  59.957630] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:ImportDisplayCaptureInfo:651: called
> [  59.960912] Debug <Critical> core/hle/kernel/hle_ipc.cpp:operator():89: Assertion Failed!
> Empty static buffer!

**Comment by FearlessTobi** [comment]
This has probably something to do with https://github.com/citra-emu/citra/pull/3421.

**Comment by valentinvanelslande** [comment]
this will be fixed in the next canary.

**Comment by hyarsan** [comment]
well that was quick! :D

**Comment by wwylele** [comment]
closing as we only open issues for nightly
