### ISSUE TITLE
The Legend of Zelda: Tri Force Heroes - Error

### ISSUE THREAD

**Issue by valentinvanelslande** [citra-emu/citra#3437]
Commit: 3c03da1
![error](https://user-images.githubusercontent.com/22228082/36239472-7f90dc16-11cf-11e8-8f30-d665d3fe981c.PNG)
[Log](https://github.com/citra-emu/citra/files/1726344/log.txt)

**Comment by wwylele** [comment]
please provide more information of where, when and how to reproduce the issue. For example, you must have been using native applet which isn't a common use case and should be noted in the issue.

**Comment by legoj15** [comment]
Once you boot the game (opening it from the games list) this appears immediately

**Comment by FearlessTobi** [comment]
The game works fine for me in latest Nightly (without native applets).

**Comment by valentinvanelslande** [comment]
@FearlessTobi the game works perfectly without native applets, but it is 100% unplayable with native applets because you can not exit applets

**Comment by FearlessTobi** [comment]
I'm unable to even get the popup, but exiting native applets has been fixed either way.
