### ISSUE TITLE
`CXXABI_1.3.11' not found with Nightly Build - 775fb38

### ISSUE THREAD

**Issue by ierpe** [citra-emu/citra#3439]
Hi,

After updating this morning, Citra won't start anymore : 

```
$:/opt/Citra/nightly|⇒  ./citra
./citra: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./citra)
$:/opt/Citra/nightly|⇒  ./citra-qt 
./citra-qt: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.9' not found (required by ./citra-qt)
./citra-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./citra-qt)
```

Using Debian 9 up to date

Previous version was working fine (I downloaded the previous build : Nightly Build - 3c03da1 and it's working fine)

**Comment by wwylele** [comment]
This is likely due to the version bump in #3430 
We still haven't figured out how to make a proper linux build release, so please compile from source yourself in the meantime.

**Comment by ierpe** [comment]
The weird thing is, I tried to download and reinstall the latest build, wasn't working, but with the previous build, it works...

**Comment by WinterMute** [comment]
@wwylele If you're moving to c++17 citra can't be built on or for Debian9, possibly other Debian based distros

**Comment by daniellimws** [comment]
This is kinda late, somehow just saw this...

For anyone that happens to see this, I'm using Debian 9 right now and it is possible to build citra with c++17 on it. Just need to go through the long way of building gcc 7 from source.

**Comment by WinterMute** [comment]
@daniellimws can you build something that will work on ubuntu 16.04 going that way?

**Comment by daniellimws** [comment]
I think it is possible to build gcc 7 from source in Ubuntu 16.04 but I'm not using Ubuntu right now so I can't be 100% sure. It's just that apt doesn't ship with it for that version. Iirc @wwylele uses Ubuntu 16.04.

**Comment by MerryMage** [comment]
We have [instructions for building on Ubuntu 16.04](https://github.com/citra-emu/citra/wiki/Building-for-Ubuntu-16.04) using the jonathonf/gcc-7.1 ppa.

**Comment by daniellimws** [comment]
Oh didn't know that. Thanks!
