### ISSUE TITLE
Fire Emblem: Fates, pipe_number 3 REPRODUCABLE 0 fps crash - nightly and canary

### ISSUE THREAD

**Issue by Ulinsky** [citra-emu/citra#3443]
Hello, I have noticed a reproducable 0 fps crash, with the error being [  28.404429] Audio.DSP <Critical> audio_core/hle/hle.cpp:PipeWrite:181: pipe_number = 3 unimplemented

Tested in canary d8fde9b and nightly 3c03da1

System specs are:
i5 6600 non k, gtx 1060, 8gb ram, windows 10, latest drivers etc.

To reproduce the bug: have to play till you unlock your castle, before a mission, go into private quarters, invite a character, you can hear the background music stop, and the error [  28.404429] Audio.DSP <Critical> audio_core/hle/hle.cpp:PipeWrite:181: pipe_number = 3 unimplemented will be printed. the game does not crash yet, but instead on your next action (like entering/leaving a building). 

only specific actions triger this, for example building a new building does not crash the game.

I found this issue opened here: https://github.com/citra-emu/citra/issues/2565  but it is closed.

**Comment by MerryMage** [comment]
**Summary:** Long standing issue due to unimplemented features in DSP HLE.

**Versions affected:** Last tested version was 775fb388c29530a9e552da83b7f2ab75e9227e28, issue affects all versions before this.

**What should occur:** 
What should occur is demonstrated in this video: https://www.youtube.com/watch?v=xWC4T1Mt2T4
Freeze would occur on Citra at 0:09 in the video.

**Comment by Ulinsky** [comment]
[00000001.zip](https://github.com/citra-emu/citra/files/1731283/00000001.zip)

save game, load chapter 8

**Comment by Ulinsky** [comment]
To add to this issue: when reaching S rank with a unit, and watching the cutscene, at the end it fades to white, and the game prints  [ 28.404429] Audio.DSP audio_core/hle/hle.cpp:PipeWrite:181: pipe_number = 3 unimplemented, and hangs. The fps isn't 0 this time, but 30, yet the game never continues. Skipping the cutscene does not freeze the game. 

Also, upon reaching S rank, instead of invite ally, going to the private quarters and selecting "bond" also prints  [ 28.404429] Audio.DSP audio_core/hle/hle.cpp:PipeWrite:181: pipe_number = 3 unimplemented and the game stops working with 0 fps shown.

Both of these are reproducable in the savegame attached here: 
[00000001.zip](https://github.com/citra-emu/citra/files/1734785/00000001.zip) 

where a unit is ready for S rank.

**Comment by Patrickzzz22** [comment]
Is there any workaround for this problem yet?

**Comment by juraki** [comment]
I also have the same problem
I can not get married!

**Comment by MerryMage** [comment]
Closed by #4490.

**Comment by MerryMage** [comment]
Reopening as not fixed in HLE.

**Comment by Dragios** [comment]
Is it fix in HLE now?

**Comment by FearlessTobi** [comment]
I think this is fixed with the HLE AAC decoder.
