### ISSUE TITLE
Citra and videodriver crashes after playing 10-15 minutes

### ISSUE THREAD

**Issue by Lleon23** [citra-emu/citra#3445]
Citra and videodriver crashes after playing 10-15 minutes in Legend of Zelda A Link Between Worlds. 
citra nightly 3c03da1 and canary e4a00b3

![1](https://user-images.githubusercontent.com/36202446/36338674-4f9b5a36-13d7-11e8-83fc-df54c8162223.png)
![2](https://user-images.githubusercontent.com/36202446/36338675-4fba81a4-13d7-11e8-8a29-cccd7b0433ed.png)
![3](https://user-images.githubusercontent.com/36202446/36338676-4fd946d4-13d7-11e8-8741-59ae50c2f110.png)

**Comment by j-selby** [comment]
What GPU are you using?

**Comment by Lleon23** [comment]
I have Nvidia  GeForce GTX 560 TI

**Comment by j-selby** [comment]
That is a really old card. Have you updated your GPU drivers recently?

**Comment by Lleon23** [comment]
Yes, i changed driver on 390.77 but i did this after problem appear on 38x.xx driver

**Comment by Lleon23** [comment]
After some testing i have a conclusion that the problem in my GPU. On another Nvidia or AMD works fine.
