### ISSUE TITLE
[Feature Request] Optional multi-core support

### ISSUE THREAD

**Issue by CyberSonic96** [citra-emu/citra#3453]
Hello. I'm wondering if it would be possible to add multi-core support to Citra as an option in settings?

**Comment by jroweboy** [comment]
Multicore support will happen when someone codes it, and no sooner. Adding an option is the easy part, actually writing multicore support is very challenging though. When its added, it will be up the person who wrote it to determine if it should be a setting or not, and there isn't much point to make it a setting. Closing as this isn't a real issue.
