### ISSUE TITLE
Kirby: Triple Deluxe issue :/

### ISSUE THREAD

**Issue by Chadman246** [citra-emu/citra#3483]
So in Kirby triple deluxe, it runs great on my computer, (The only game my computer can handle so far :/) but on a certain section of Stage 2 of Lvl 1, you have to tilt the 3ds to tilt the bowl to put out the fire, but it's impossible to continue the game without passing that part. Since citra is an emulator, you cant pass that area, so is there a chance you can add a mappable tilt input? That would help ALOT. Thanks!

**Comment by legoj15** [comment]
You can, right click on the emulation window and drag the mouse, it "tilts" the emulated 3DS (if i recall correctly

This kind of issue would've been better suited for the [Citra Community Forums](https://community.citra-emu.org/), or the Citra official Discord server.
