### ISSUE TITLE
SIZEOF_SIZE_T not defined when building externals/cpr

### ISSUE THREAD

**Issue by Road-Drum** [citra-emu/citra#3485]
hit this error when building citra. do i need to reconfigure curl? libcurl is downloaded exactly from the wiki instruction

OS: Ubuntu 17.10 artful
curl-config --version: libcurl 7.55.1

```
[ 31%] Building C object externals/cpr/opt/curl/lib/CMakeFiles/libcurl.dir/warnless.c.o
/home/hello/citra/externals/cpr/opt/curl/lib/warnless.c:117:4: error: "SIZEOF_SIZE_T not defined"
#  error "SIZEOF_SIZE_T not defined"
   ^
/home/hello/citra/externals/cpr/opt/curl/lib/warnless.c:333:37: error: use of undeclared identifier 'CURL_MASK_SSIZE_T'
  return (ssize_t)(uznum & (size_t) CURL_MASK_SSIZE_T);
                                    ^
/home/hello/citra/externals/cpr/opt/curl/lib/warnless.c:352:40: error: use of undeclared identifier 'CURL_MASK_USIZE_T'
  return (size_t)(sonum & (curl_off_t) CURL_MASK_USIZE_T);
                                       ^
3 errors generated.
externals/cpr/opt/curl/lib/CMakeFiles/libcurl.dir/build.make:1814: recipe for target 'externals/cpr/opt/curl/lib/CMakeFiles/libcurl.dir/warnless.c.o' failed
make[2]: *** [externals/cpr/opt/curl/lib/CMakeFiles/libcurl.dir/warnless.c.o] Error 1
CMakeFiles/Makefile2:605: recipe for target 'externals/cpr/opt/curl/lib/CMakeFiles/libcurl.dir/all' failed
make[1]: *** [externals/cpr/opt/curl/lib/CMakeFiles/libcurl.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2``
```

**Comment by wwylele** [comment]
Did you add `-DUSE_SYSTEM_CURL=ON` in cmake configuration?

**Comment by Road-Drum** [comment]
as in wiki it was configured as  `-DUSE_SYSTEM_CURL=1 ` and passed cmake configuration

**Comment by wwylele** [comment]
cmake probably didn't find the installed curl library and trying to build the bundled curl instead (which is known having issues on linux). Could you provide the cmake configuration log?

**Comment by Road-Drum** [comment]
ok `-DUSE_SYSTEM_CURL=ON` now works instead of `-DUSE_SYSTEM_CURL=1`  so the wiki might need an update

> trying to build the bundled curl instead (which is known having issues on linux). 

if the bundled curl is problematic, why it is still there?  

thanks for the help, it's compiling now. I'm using AMD Optimized C/C++ Compiler which uses clang so already expecting stuff like this

**Comment by wwylele** [comment]
> if the bundled curl is problematic, why it is still there?
The bundled curl is needed for windows build. Also, it is a second level dependency and managed by first level dependency cpr, which is out of our control.

**Comment by Road-Drum** [comment]
anyway with AOCC there is slight fps increase in Dai Gyakuten Saiban 2.  

got full frames with FE Fates too! but that may be due to mesa amdgpu driver with mesa_glthread=true
