### ISSUE TITLE
version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by andreieichler** [citra-emu/citra#3491]
Since the release https://github.com/citra-emu/citra-nightly/releases/tag/nightly-565, citra can't run, exit with this error:

/usr/lib/libm.so.6: version `GLIBC_2.27' not found (required by /home/andrei/.citra/nightly/citra-qt)

My computer:

lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        17.1.6
Codename:       Hakoila

**Comment by j-selby** [comment]
This can be fixed, for now, by compiling from source.

**Comment by j-selby** [comment]
The AUR also provides package buildfiles.

**Comment by andreieichler** [comment]
@j-selby I'm using the citra-setup from the site, which AUR should I use then? citra-nightly-bin?

**Comment by j-selby** [comment]
https://aur.archlinux.org/packages/citra-git/

**Comment by harm0nic** [comment]
I too have this issue. I compiled from source to get normal Citra to run, but how do I get Canary?

**Comment by YamashitaRen** [comment]
I didn't find any source for citra-nightly. The repository is empty.

**Comment by daniellimws** [comment]
@YamashitaRen if you want citra-nightly you can use master of citra-emu/citra

**Comment by YamashitaRen** [comment]
Sorry for the bother. I just figured that nightly and canary repo use a splash as default branch...

**Comment by EchoUrandom** [comment]
I want to try out the canary build since that one should have the new hardware renderer but it runs into this issue. Though compiling master will work, but it does not include the new hardware renderer.

**Comment by YamashitaRen** [comment]
@EchoUrandom You can build master branch of canary repo. It has the hardware renderer.

**Comment by benderscruffy** [comment]
Can be closed now
