### ISSUE TITLE
Metroid Samus Returns audio sounds like playing through running fan

### ISSUE THREAD

**Issue by GinoMan** [citra-emu/citra#3492]
Hello everyone, 

I'm using Citra Version HEAD-3cda637. When running the dumped ROM of Metroid Samus Returns on Citra, the audio seems to sound as though it is running through a fan like when kids talk through box fans and sound like robots. There seems to be a lag to it. I'm not sure what's causing it. I have the issue regardless the sound card I run on (the ROCCAT Juke or the internal speakers). 

Thanks

Gino Vincenzini

**Comment by BreadFish64** [comment]
Sound is tied to speed, if the speed is less than optimal the audio may be choppy.

**Comment by GinoMan** [comment]
Ok. It seems to have a very variable speed if I set the process to realtime. 

Also I see this in the terminal windows scrolling infinitely: 

![image](https://user-images.githubusercontent.com/528834/37186545-2115461c-2314-11e8-82f4-6dd4bb1fdbe5.png)

I had heard/read or something that Samus Returns uses a ton of texture copying which really affects the performance in the emulator. Is that still so with the version I mentioned?

**Comment by 1425720626** [comment]
Go to the user folder, then config, edit the qt-config.ini, find the string "log_filter", change the value "Info" to "Critical", then save the file, and it's OK now

**Comment by wwylele** [comment]
Not a real audio issue, so closing. Please use the forum for supporting.

**Comment by GinoMan** [comment]
I mean, ok, there's a workaround but shouldn't it work out of the box? I can understand that it's probably not high priority, but i would like to see the issue resolved for future users. I have some programming experience; can I help? Has someone else already done any work on this that I could work from?

**Comment by 1425720626** [comment]
Please search the wiki by yourself. I posted the workaround above but got deleted, so I can't help you now.
