### ISSUE TITLE
[Feature Request] The ability to configure touchscreen positions to a joypad button/keyboard key

### ISSUE THREAD

**Issue by GinoMan** [citra-emu/citra#3494]
The idea would be to allow simple and complex things that utilize the touchscreen. 

So the idea is that if you press a key on the keyboard, it will imitate a touchscreen touch at a specific x and y location on the bottom touchscreen.

The idea though would also for it to be sort of scriptable. The specifics would be that you could make it so pressing that key/hitting that button, would make a single momentary press to the touchscreen in a specific place. 

Or make it so that an array of locations are given and so every time the button is pressed, it cycles through those locations with each press. 

Or it could be a Slide from point A to B and back again either on button down, button up, or with each button press (so once slides it to B, again slides it to A). 

Or it could map infinitely to an analog stick direction (so when you move the analog stick to 35 degrees, it starts in the bottom left corner of the screen and goes up at a 35 degree angle to the top right immediately returning to the bottom left as soon as it reaches the top right and continuing on (think about how this would control your movement in Metroid Prime Hunters) It could also be set at a specific radius and speed and origin on the touchscreen. 

I think implementing these would obviate the need for external software that emulates a mouse and maps that emulation to button and key presses. If the system is flexible enough, then any game could be played without leaving the controller if one uses a joypad, or keyboard if they use a keyboard. 

Just some ideas. I would love to help design the UI for this if someone decides to implement it.

Thanks,

Gino Vincenzini

**Comment by jroweboy** [comment]
Thanks for the suggestion. I have many controller fixes coming down the pipeline that I am looking forward to submitting for review. This particular suggestion won't be coming any time soon, but it is on the TODO list and I have a WIP implementation for it. Unfortunately, I've been very busy lately doing other things for citra and haven't had any time to devote to the controller work. Hopefully soon my current work log for citra will clear up and I can get back to working on this again.

Citra's input support is designed to handle these ideas, but it still takes a little work to connect everything together.

**Comment by johelegp** [comment]
I think this can be closed.
