### ISSUE TITLE
Nightly builds not always creating builds for windows

### ISSUE THREAD

**Issue by superheri** [citra-emu/citra#3508]
Even when all CI builds are complete, there is not always a build created on windows, while there are some for MacOS and Linux. It would be nice if it is fixed so we could have updates more often.

**Comment by wwylele** [comment]
This is usually Appveyor queueing our build and there isn't much we can do for it.

**Comment by superheri** [comment]
Even if Appveyor is not giving any result?

**Comment by adityaruplaha** [comment]
We can't do anything about this. Sometimes, Appveyor puts Citra builds into a queue, instead of building immediately. That's why this happens.
