### ISSUE TITLE
Citra crashes

### ISSUE THREAD

**Issue by TooBadForTroll** [citra-emu/citra#3509]
Hello,

When im running a game in Citra, it works.

And all of the sudden, it crashes for no reason.

Idk why it crashes like this, for no fuckin' reason.

I can't play DS games. I need help!

-TooBadForTroll

**Comment by valentinvanelslande** [comment]
game?

**Comment by MYSTERlOUSGUY** [comment]
Change "Shader Emulation" to CPU. That temporary fixes this issue for me. Seems to happen in every game.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests.

Requesting to close.

**Comment by CesarAxe** [comment]
Yes, It's a problem with shader emulation, crash with many games. For future consultations use the forums.
