### ISSUE TITLE
(Feature Request) Add an ability to dump game sprites/textures and allow for injection of custom textures.

### ISSUE THREAD

**Issue by KatouMegumi-osu** [citra-emu/citra#3510]
It would be awesome if you could download a custom textures pack for Pokemon Mood, for example and inject it into the game to have said custom textures. This idea is inspired by Project64 graphics plugin "GLideN64" which allows to dump the game textures and also inject custom textures.

My plan on this feature is to dump the textres in preferrably .png format, then upscale them with waifu2x and inject the upscaled textures into the game in the emulator (Similarily how it's done with P64 and GLideN64 plugin).

**Comment by MelonSpeedruns** [comment]
Why not just implement a texture filter inside the emulator instead of upscaling every single texture?
Also, they would look way better if they were hand-made.

**Comment by KatouMegumi-osu** [comment]
@MelonSpeedruns I have mentioned a possibility of people doing hand-drawn as "custom textures". It's up to users to either use waifu2x on dumped textures and keep the original art style or get a custom texture pack. Plus waifu2x is an image upscaling neural network designed for Anime artwork, considering a good heap of 3DS games are anime-styled. Though, including waifu2x as internal texture upscaler is taxing, so having texture injection of upscaled or custom textures is a far greater option.

**Comment by Subv** [comment]
This has already been implemented
