### ISSUE TITLE
FullScreen F11 strange behaviour

### ISSUE THREAD

**Issue by Claod44** [citra-emu/citra#3512]
Hi,
When I press "share" on my dualshock 4 gamepad Ds4windows sends F11, it's working when I launch citra as normal.

I try to find a way to hide the log console,
I found a way to do it...
I use AutoHotKey, and I did a launcher : 

```
citra = %1%
game = %2%

Run %citra% %game%
WinWait, ahk_exe citra-qt.exe
WinHide ahk_exe citra-qt.exe
```

So to use it (ahk or exe if compiled): 
c:\pathtomyscript\myscript.ahk c:\pathtocitra\citra-qt.exe c:\gamesDir\game.3ds

It's launching citra, the game starts, but for any reason ... "Share" button doesn't fullscreen...
Any idea, you got 3 hours. xD ?

**Comment by CodingKoopa** [comment]
It's worth noting that, when the logging system rewrite goes into effect, there will be the ability to hide the log console (It may be enabled by default, even.).

**Comment by Claod44** [comment]
You mean the console shouldn't be displayed ?

**Comment by CodingKoopa** [comment]
I believe the plan is to, when that update rolls around, hide the console altogether by default.

**Comment by Claod44** [comment]
So for now there is no way to hide it okey.
We don't know when that update will be in our PC.
That's why I try to do it myself ^^'.
This F11 not working is still strange... I wonder why it's occuring.

**Comment by jroweboy** [comment]
Closed by the logging rewrite (for windows at least)
