### ISSUE TITLE
Citra makes xorg-session.log grow bigger and bigger

### ISSUE THREAD

**Issue by YamashitaRen** [citra-emu/citra#3517]
Version : 6c63bb1
System : Archlinux, AMDGPU driver, Plasma 5
Game : Pokemon Moon

How to reproduce : 
Play the game.

What happens : 
When the game starts, before the menu, log file is flooded with this warning : 
 `[  24.125300] Service.Y2R <Warning> core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:198: (STUBBED) called`
When I'm playing the game, the log file is flooded with this error instead :
`[ 743.827055] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'SetProbeResponseParam': port='nwm::UDS' cmd_buf={[0]=0x210080, [1]=0x321f00, [2]=0x40000}`
Some other errors are logged too, but mainly theses ones.
My log file grew up to 16GB before I identified the issue. Game plays fine.

Workaround : 
Disable logging xorg-session errors to file in the display's manager configuration (in my case /etc/sddm.conf).

May or may not be related to https://community.citra-emu.org/t/hard-drive-space-eaten-while-playing-pokemon-moon/1757

I don't know if the issue is citra writing all theses errors to xorg-session.log or is citra having theses errors in the first place... Probably the former.

**Comment by wwylele** [comment]
Citra only logs to stderr, so it is likely the operating system that decides to store stderr on the driver.

**Comment by YamashitaRen** [comment]
You're correct. Should have checked stderr before submitting the bug report.
The issue being on my side, I'm closing this.
Thanks for your help :)
