### ISSUE TITLE
[Feature Request] LayeredFS on Citra

### ISSUE THREAD

**Issue by AngelSora** [citra-emu/citra#3524]
Since the GPU Update of Citra, i decided to only use this to play 3ds Games. But... i want to put SuperNova Sun and Lots of Custom Music on Ultra Sun. I have a real 3ds and all but... the process is really annoying especially when i want to do quick testing. It would be useful to use it just like the Update Path of CEMU (mlc01).

**Comment by AngelSora** [comment]
Am i ignored...? (Just wondering)

**Comment by daniellimws** [comment]
Probably just no one keen on taking up this task :stuck_out_tongue: 
The closest one that seems to be currently worked on is https://github.com/citra-emu/citra/issues/3529#issuecomment-373586598

If you want a feature I suppose the fastest way to get it is to send a pull request

**Comment by LITTOMA** [comment]
This could be a very helpful feature an emulator should support. 
Because building a large RomFS for just a little modification on a 10-year-old Laptop is really pain. 
No need to say building the CCI. 
Three times of that pain. 😿

**Comment by zhaowenlan1779** [comment]
LayeredFS was added in #5088
