### ISSUE TITLE
[Feature request] Fast forward hotkey button

### ISSUE THREAD

**Issue by Shideravan** [citra-emu/citra#3525]
In the most recent version, increase/decrease speed limit hotkeys are working fine.
Could we have a fast forward button, where when pressed, the speed can go automatically to unlimited or to a huge value fast and after release the button the speed goes to previous value?
Thanks!

**Comment by legoj15** [comment]
#3417

**Comment by jroweboy** [comment]
Closing as duplicate of #3417 (chime in there if you have something to say <3)
