### ISSUE TITLE
Crashmo - Incorrect shadow effect

### ISSUE THREAD

**Issue by Krusher97** [citra-emu/citra#3526]
Windows 7 Ultimate 64-bit SP1
Intel Core i5 6500 @ 3.20GHz
NVIDIA GeForce GTX 750 Ti
Tested in Canary d610ac3
Video of 3DS running it : https://youtu.be/M3TREbMoEKc?t=3m32s
Log : [log.txt](https://github.com/citra-emu/citra/files/1815963/log.txt)

![emu](https://user-images.githubusercontent.com/25664221/37472307-a6a552c8-2863-11e8-853c-f98ebf7a2322.png)

![real](https://user-images.githubusercontent.com/25664221/37472325-ae0dface-2863-11e8-8c85-dc93e9de8a62.png)

When the bottom block is pulled in the first lesson, it causes a "shadow" when you walk over them.

**Comment by wwylele** [comment]
Could you test this in software renderer ("hardware renderer" disabled) with #3516?

**Comment by Krusher97** [comment]
![citra-qt_2018-03-15_21-55-56](https://user-images.githubusercontent.com/25664221/37476655-9b8570e4-286d-11e8-8165-7c0bb8112565.png)

Looks proper when using the software renderer of the linked build.

**Comment by Krusher97** [comment]
![citra-qt_2018-05-15_20-56-36](https://user-images.githubusercontent.com/25664221/40066827-79bd4ec0-5854-11e8-87c0-4c4a2081a684.png)

Seems to be fixed in latest canary using GPU shaders. Should this be closed?

**Comment by wwylele** [comment]
@Krusher97 THanks for the test! Please wait for #3729 to merge. We only close issues when they are fixed in nightly

**Comment by wwylele** [comment]
@Krusher97 Does it work fine with CPU shader in canary?
