### ISSUE TITLE
Build failure on debian.

### ISSUE THREAD

**Issue by y-salnikov** [citra-emu/citra#3527]
Build failing on same file (archive_backend.cpp) with both GCC-6.3 and CLANG-3.8 compillers. I tried GCC-5.4, same results.
[cmake.log](https://github.com/citra-emu/citra/files/1816604/cmake.log)
error log:
```
[ 45%] Building CXX object src/core/CMakeFiles/core.dir/file_sys/archive_backend.cpp.o
/home/jarik/build/Citra/citra/src/core/file_sys/archive_backend.cpp: In constructor ‘FileSys::Path::Path(FileSys::LowPathType, const std::vector<unsigned char>&)’:
/home/jarik/build/Citra/citra/src/core/file_sys/archive_backend.cpp:24:32: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
         std::memcpy(string.data(), data.data(), string.size());
                     ~~~~~~~~~~~^~
In file included from /usr/include/c++/6/cstring:42:0,
                 from /home/jarik/build/Citra/citra/src/./common/swap.h:28,
                 from /home/jarik/build/Citra/citra/src/./core/file_sys/archive_backend.h:13,
                 from /home/jarik/build/Citra/citra/src/core/file_sys/archive_backend.cpp:10:
/usr/include/string.h:42:14: note:   initializing argument 1 of ‘void* memcpy(void*, const void*, size_t)’
 extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
              ^~~~~~

```

**Comment by wwylele** [comment]
You need GCC 7+ for c++17 support

**Comment by y-salnikov** [comment]
It would be nice if cmake told me that.

**Comment by wwylele** [comment]
We already [added the c++17 requirement to CMake](https://github.com/citra-emu/citra/blob/master/CMakeLists.txt#L95). If CMake doesn't error on it, there isn't really much we can do.

**Comment by y-salnikov** [comment]
Well, it could be done by comparing CMAKE_CXX_COMPILER_VERSION variable but it is cmake's job. Thanks. I used latest cmake by the way.

**Comment by akien-mga** [comment]
Was about to report the same issue on Mageia 6 x86_64 with GCC 5.5.0.

CMake indeed did not complain about my compiler and let the build proceed to this point and that same error.
