### ISSUE TITLE
Empty Games List on First Launch

### ISSUE THREAD

**Issue by chris062689** [citra-emu/citra#3529]
When a Games List directory is not specified, the first window presented to the user is blank.

Instead of showing a blank list, we should have a window prompting them to select a game list directory.

Screenshot of the current implementation:
![Screenshot](https://user-images.githubusercontent.com/278907/37500373-156b5cf4-28c1-11e8-98c3-ccf3aab86563.png)

Reference screenshot for future implementation:
![Reference](https://user-images.githubusercontent.com/278907/37500408-479aaad6-28c1-11e8-9e22-aa73f64fdd13.png)

**Comment by BreadFish64** [comment]
![image](https://user-images.githubusercontent.com/28246325/37500866-b7ded272-2899-11e8-8fce-20dcb282aa90.png)
I'm already working on something for this because I wanted to support multiple game folders. feedback is welcome :)

**Comment by chris062689** [comment]
We need some kind of a screen to show if they do not have anything installed.

Users starting off with a blank slate.

I assume once we properly emulate the full SYSNAND we would want to discourage game directories anyway?

**Comment by BreadFish64** [comment]
I don't agree with either of those statements, "add new game directory" is fairly easy to understand and I don't know why you'd want to force a user to pick one on first boot. 
I don't know about you but I'd rather not store everything in the user folder, that sounds like a pain especially when there's multiple instances of Citra, even if the location becomes configurable it's still useful to store things in multiple places.

**Comment by adityaruplaha** [comment]
@BreadFish64 I don't like the icons. Mind if I suggest some? I know they are just place holders but it's better to do it as it will just be a switch.

**Comment by adityaruplaha** [comment]
Folder icon: http://www.iconarchive.com/show/mac-folders-icons-by-hopstarter/Blank-icon.html

System Titles icon:
https://www.google.co.in/search?q=computer+microchip+icon+colour&oq=computer+microchip+icon+colour&aqs=chrome..69i57.11462j0j7&client=ms-android-xiaomi&sourceid=chrome-mobile&ie=UTF-8#imgrc=m4ZvjUpDHdyilM:

Installed Titles icon:
https://www.flaticon.com/free-icon/sd-card_30986

**Comment by jroweboy** [comment]
@BreadFish64 This is about adding a game list placeholder message on first boot. While I think "Add new game directory" is an excellent stop gap, having a giant icon with "No games found! Add a new game directory" would clarify that this is indeed a game list in addition to showing the user how to configure it. After the first directory is added or title is installed, then it can go back to game list you are working on.

This request isn't about forcing anyone to choose a game directory, nor does it have anything to do with the user folder, I'm not sure where you got that from. :D

@adityaruplaha please don't post offtopic comments, thanks.

**Comment by adityaruplaha** [comment]
I was just suggesting icons for the UI.

Adityarup Laha

**Comment by BreadFish64** [comment]
@jroweboy I see what you're saying, but what about people who only use installed titles? I supposed I could test if those are empty... `I assume once we properly emulate the full SYSNAND we would want to discourage game directories anyway?` I understood this as not wanting configurable game directories in favor of instead titles.

**Comment by BreadFish64** [comment]
@adityaruplaha these probably aren't the final icons, but I was going for something color neutral that looks good in 48x48 and match eachother. So I was just making them myself.

**Comment by chris062689** [comment]
Closing due to papercut being resolved.
