### ISSUE TITLE
Automatically install open source system files

### ISSUE THREAD

**Issue by chris062689** [citra-emu/citra#3530]
Open source equivalent of system file should automatically be installed on launch of Citra if the original is missing from the user's SYSNAND.

Currently available:
* Shared Font
  * B3N30 Shared Font: #2870 / https://github.com/B3n30/citra_system_archives

Missing open source equivalents:
* Miipicker
* Software Keyboard
* Bad Word List
* Region List

**Comment by BreadFish64** [comment]
![image](https://user-images.githubusercontent.com/28246325/37500753-42402674-2899-11e8-8285-596b91aea8fe.png)
I'm already working on this as I'm trying to support multiple game directories. :)

**Comment by chris062689** [comment]
We need some kind of a screen to show if they do not have anything installed.

Users starting off with a blank slate.

I assume once we properly emulate the full SYSNAND we would want to discourage game directories anyway?

**Comment by valentinvanelslande** [comment]
https://github.com/nop90/SwKbd is for homebrews, is not a applet

**Comment by chris062689** [comment]
Is there an open source equivalent of that applet that you know of?

**Comment by valentinvanelslande** [comment]
https://gist.github.com/B3n30/64a0c1ff7f1cd8eed404b9eb34f67619, but text is stubbed to always be Citra

**Comment by adityaruplaha** [comment]
You might want this?
https://youtu.be/5jlYHxK_-2A

**Comment by valentinvanelslande** [comment]
@adityaruplaha is not open source and the video contains the original keyboard

**Comment by adityaruplaha** [comment]
Really? In that case, I'll delete that comment.

Adityarup Laha

**Comment by adityaruplaha** [comment]
Bad word list:

https://www.reddit.com/r/3dshacks/comments/45yhop/full_list_of_censored_words_on_3ds/

**Comment by khang06** [comment]
the bads words list should be replaced with a stub instead of actual bad words imo

**Comment by khang06** [comment]
i think it'd just be a placeholder, maybe have an option between word filtering disabled and enabled?

**Comment by legoj15** [comment]
I was thinking the same thing @khang06 was

**Comment by adityaruplaha** [comment]
Why stub it while it is possible to fully implement it? I have previously
provided the list of the words, I'll leave the rest to the pros.

Adityarup Laha

**Comment by BreadFish64** [comment]
All the mentioned files have been implemented
