### ISSUE TITLE
Monster Hunter XX Particle Distortion in GPU mode

### ISSUE THREAD

**Issue by Malrodin** [citra-emu/citra#3534]
Citra Canary Build - 04273de

CPU: Intel I5 6600K
GPU: Nvidia 1060

Citra Settings: GPU mode; 4X native; accurate hardware shader off.

Citra example: https://streamable.com/ytaaw
Comparison: https://youtu.be/1-AyKSvP2qk?t=67

This issue seems to be related to the rendering of particle effects. Some do not render at all, but cause no distortion (stun effect) while other effects like this beast mode distort the effect to the top left of the screen. It seems to always be centered to the top left of the screen regardless of position of effect or camera.

Another example: https://streamable.com/1t804

This gets quite messy the more effects are on screen. At the 20 second mark it also shows how the "stun stars" are missing which is probably related.

CPU mode does not have either issue.

On activation of the beast mode example the console will output:
[906.885273] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_gen.cpp
:SampleTexture:312: Using Texture3 without enabling it

Tho i'm not sure if that's related.
Easiest way to reproduce is to hire a beast type cat and go into a quest, punch a bunch of monsters for 2 skill points, activate beast mode.

**Comment by jroweboy** [comment]
Thank you for the detailed report. Issues that are for canary builds should instead be reported on the respective pull request for the feature that has the issue. In this case, you'll want to post this log on #3499 so we can track the progress there. Please move the content of this issue to a comment there and close this issue when you are done, thanks.
