### ISSUE TITLE
Audio Error with Bluetooth device

### ISSUE THREAD

**Issue by superheri** [citra-emu/citra#3536]
I have a bluetooth audio device, a Bose Soundlink AE2 working pretty fine with my laptop, i can easily listen to Youtube videos, and when i try to play citra with these hearphones, citra actually gives me no sound. But when i plug my hearphones with the Jack plug, everything works fine after rebooting Citra.

I would have liked to give you a log, but there is nothing about audio that is writing in the log box...

Thank you in advance. ;)

**Comment by superheri** [comment]
I forgot to say, I'm on Windows 10.

**Comment by adityaruplaha** [comment]
I got this. Just go to audio config, and make sure the output device is set to auto. You should be fine.

**Comment by superheri** [comment]
@adityaruplaha I have it to auto and nothing appened in my ears...

**Comment by adityaruplaha** [comment]
Make sure your volumes are ok. Anyways, I think it's becoming like a
support request. Ask in the forums or in Discord of you please.

Adityarup Laha
