### ISSUE TITLE
Pokédex 3D failing to create Extra SD Card Data.

### ISSUE THREAD

**Issue by MelonSpeedruns** [citra-emu/citra#3537]
I've tried launching Pokédex 3D. The "game" seem to boot up correctly, but I can't get past the "Extra data will be created." screen, making the game unplayable. I'm using the latest Canary (HEAD-04273de).

![](https://i.imgur.com/1ZnqnKW.png)
![](https://i.imgur.com/VG83mhv.png)

**Comment by wwylele** [comment]
Full log please

**Comment by superheri** [comment]
This isn't new, as I mentionned it in #3061 .

**Comment by MelonSpeedruns** [comment]
https://pastebin.com/BtShTMXC

**Comment by wwylele** [comment]
related log
```
[   7.238048] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'DeleteExtSaveData': port='fs:USER' cmd_buf={[0]=0x8350080, [1]=0x1, [2]=0x326}
[   7.260947] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'CreateExtSaveData': port='fs:USER' cmd_buf={[0]=0x8300182, [1]=0x1, [2]=0x326, [3]=0x0, [4]=0x36c0, [5]=0x20, [6]=0x800, [7]=0x36c0a, [8]=0x81718e4}
```
This game is using the legacy FS interfaces
