### ISSUE TITLE
Frozen visual output in canary

### ISSUE THREAD

**Issue by JRBdatascience** [citra-emu/citra#3541]
I started back using Citra when I read about the new feature for shader emulation on the GPU. Before then I last used Citra on the 22nd of February 2018 and it was fine then. However, when I play games now the emulation goes on as normal for a while, then the screen will freeze and the speed percentage drops to 0%. The speed then goes back up to normal and the sound continues to play but both screens remains frozen on what they were displaying when the emulator froze. The touch screen and input works as in Mario and Luigi: Dream Team I can click the spot where the save button would be and press the A button to save even though nothing happens visually. I have had it happen in the three games I tested which include Mario and Luigi: Paper Jam and Mario Kart 7 along with Dream Team.

The issue happens on canary, if it happens on nightly I have not seen it yet. The Canary version I am using now which I can confirm the issue happens is 04273de. I am on Windows 10 64 bit with 4 gb of ram, i5 6200u processor with hd 520 graphics. All drivers are the latest I can install. I attached a log file. The issue does not happen at a set point but can occur a few seconds after emulation started and I usually cannot go more than 15 minutes before it occurs.

![frozen graphical output](https://user-images.githubusercontent.com/8836727/37555306-35d7217c-29c4-11e8-85ba-cb98464c383f.jpg)
Figure 1: Graphical output frozen while emulation continues

![citra window size maximised after crash](https://user-images.githubusercontent.com/8836727/37555308-39acfd3a-29c4-11e8-8417-2c55b8708a9b.jpg)
Figure 2: Results of maximising Citra's window size after the freeze

[log.txt](https://github.com/citra-emu/citra/files/1821578/log.txt)

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum. Please use the [**forums**](https://community.citra-emu.org) for support requests.

Requesting to close.

**Comment by JRBdatascience** [comment]
Would this not be a bug and thus an issue? That is why I uploaded the log file.

**Comment by FearlessTobi** [comment]
Please report issues occurring in Canary under their respective PRs.

Requesting to close.
