### ISSUE TITLE
RAM Usage increasing over time

### ISSUE THREAD

**Issue by LOuroboros** [citra-emu/citra#3543]
**Version of Citra**: Citra Canary mingw-20180317-96c554e, the latest build available right now.

**Issue**: Citra starts eating around 400 MBs of RAM which then quickly raises to 700 MBs and it doesn't stop. The more you play a game, the more RAM it eats.
I created a log file after playing Pokémon Omega Ruby with the Shader Emulation set to CPU for around 2 or 3 hours. I don't know if it'll help you all to pinpoint whatever is causing it, but I suppose that it shouldn't happen, right?
Anyway, here it is: https://pastebin.com/BEv4P1Qx
If there's some other test that I should do, please tell me about it and I'll give it a shot right away.

**Specs**: I have an Intel Celeron N2840 with its Integrated GPU, 2 GBs of RAM and Windows 8.1 _(64 Bits)_.

**Comment by wwylele** [comment]
The increase of CPU usage is expected as how the shader cache works. Does it ever excess 1.5 GB usage? If not I think this is pretty normal.

**Comment by LOuroboros** [comment]
Well, I don't have a way to check that, unfortunately. I have 2 GBs and Windows 8.1 is constantly using around 800 MBs, so I suppose that Citra would crash around the 1.2 GB of RAM used.

Say, would it be possible to make it so the Shader Cache is stored in a file so whenever the user runs X game on Citra, the file is loaded along with it?
I know basically 0 about the development of an emulator, but I would definitely sacrifice space of my SSD or my External HDD instead of RAM, if it was possible and if I had the option.

**Comment by mailwl** [comment]
If Pagefile is enbled, Citra will not crash, just slow down

**Comment by wwylele** [comment]
@LOuroboros your system should have already done this automatically when managing the RAM - use the external disk to store excessful RAM. If it didn't work, either you somehow disabled it, or it was too slow and caused program to freeze or crash

**Comment by LOuroboros** [comment]
@wwylele Alright, yeah, it looks like that might have been the problem. Thanks, I think I was able to fix it!
I'm sorry for bothering you all, and again, thanks!
