### ISSUE TITLE
Ability to cast screen to Android/Windows Tablets/iOS

### ISSUE THREAD

**Issue by phly95** [citra-emu/citra#3544]
It would be useful to cast the touchscreen to a separate touch capable device, similar to that seen on the Wii U, as it would allow for people who are using a controller on a TV to utilize touch only features.

An example would be changing weapons on Metroid Samus Returns, where using the mouse is cumbersome, especially from a couch.

**Comment by chris062689** [comment]
This can be accomplished using third party software. Such as Moonlight, Splashtop, and others.

**Comment by phly95** [comment]
But what about casting just the bottom screen? Android phones are too tiny to cast the whole citra display, plus you'd be wasting space on your primary display by having the touchscreen on both screens.
