### ISSUE TITLE
Touchscreen Hotkeys/Macros/Scripts/Custom inputs

### ISSUE THREAD

**Issue by phly95** [citra-emu/citra#3545]
It would be quite useful if tapping areas of the touchscreen could be mapped to inputs. For example, selecting a weapon in Metroid Samus Returns involves tapping specific areas of the touchscreen, and it would be much easier if these could be mapped to a keyboard.

**Comment by MelonSpeedruns** [comment]
This was already requested in #3494 .

**Comment by MerryMage** [comment]
Duplicate of #3494.
