### ISSUE TITLE
Rhythm Heaven Megamix and Citra

### ISSUE THREAD

**Issue by Gushasad** [citra-emu/citra#3546]
Hello.
I have tried playing Rhythm Heaven Megamix using Citra emulator, and... the game crashes when I try to load a save state.
Creating one was painless, I was also able to complete the tutorial.
Here's a log from my console
[   0.000000] Frontend <Info> citra_qt/main.cpp:CheckForUpdates:467: Update check started
[   2.289271] Frontend <Info> citra_qt/main.cpp:OnUpdateFound:480: No updates found
[  19.461584] Frontend <Info> citra_qt/main.cpp:BootGame:607: Citra starting...
[  19.532987] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\Nuno\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00010202/content/00000000.app is tainted, application behavior may not be as expected!
[  19.535167] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\Nuno\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00010402/content/00000000.app is tainted, application behavior may not be as expected!
[  19.536861] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\Nuno\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/000400db/00010302/content/00000000.app is tainted, application behavior may not be as expected!
[  19.543504] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:488: GL_VERSION: 3.3.0 - Build 10.18.10.4358
[  19.544493] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:489: GL_VENDOR: Intel
[  19.544822] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:490: GL_RENDERER: Intel(R) HD Graphics 4000
[  19.554299] Loader <Info> core/loader/ncch.cpp:Load:159: Program ID: 000400000018A500
[  19.555232] Service.FS <Warning> core/file_sys/ncch_container.cpp:OpenFile:109: Failed to open C:\Users\Nuno\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/0018a500/content/00000000.app
[  19.584867] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:114: ExHeader kernel version: 2.50
[  19.587278] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:SetPreferredRegionCode:602: Preferred region code set to 2
[  19.646118] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:48: (STUBBED) called
[  19.735650] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:70: (STUBBED) called
[  19.741729] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetLockHandle:255: (STUBBED) called applet_attributes=0x00000000
[  19.750380] Service.APT <Warning> core/hle/service/apt/apt.cpp:SetScreenCapPostPermission:584: (STUBBED) screen_capture_post_permission=0
[  19.751930] Service.NDM <Warning> core/hle/service/ndm/ndm.cpp:OverrideDefaultDaemons:207: (STUBBED) default_daemon_bit_mask=0x0000000F
[  19.753664] Service.NDM <Warning> core/hle/service/ndm/ndm.cpp:SuspendDaemons:92: (STUBBED) daemon_bit_mask=0x00000009
[  19.756397] Service.DLP <Warning> core/hle/service/dlp/dlp_srvr.cpp:IsChild:20: (STUBBED) called
[  19.764138] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:234: (STUBBED) app_id=768
[  19.770086] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000007, input_size=0x00000004, output_size=0x00000001
[  19.772233] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  19.775689] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function '0x1030000': port='APT:A' cmd_buf={[0]=0x1030000}
[  19.780647] Service.FS <Warning> core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:540: (STUBBED) called, version: 0x0A0101C8
[  19.788835] Service.FS <Error> core/file_sys/archive_extsavedata.cpp:OpenFile:123: C:\Users\Nuno\AppData\Roaming/Citra/nand/data/00000000000000000000000000000000/extdata/00048000/F000000B/user/ubll.lst not found
[  19.790540] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFile:69: failed to get a handle for file [Wchar: /ubll.lst]
[  19.795176] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'Initialize': port='act:u' cmd_buf={[0]=0x10084, [1]=0xa0101c8, [2]=0x0, [3]=0x20, [4]=0x0, [5]=0x0, [6]=0x0}
[  19.804035] Service.FS <Error> core/file_sys/file_backend.h:GetReadDelayNs:52: Delay generator was not initalized. Using default
[  19.813923] Service.SRV <Warning> core/hle/service/sm/srv.cpp:Subscribe:145: (STUBBED) called, notification_id=0x207
[  19.814753] Service.SRV <Warning> core/hle/service/sm/srv.cpp:Subscribe:145: (STUBBED) called, notification_id=0x209
[  19.913113] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:665: called flag=00000000 process=10 thread_id=0
[  19.953009] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'SetInternalPriorities': port='gsp::Gpu' cmd_buf={[0]=0x1e0080, [1]=0x19, [2]=0x1a}
[  20.132211] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetSharedFont:200: Loaded shared font by legacy method
[  20.298830] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:240: Loaded NCCH C:\Users\Nuno\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00010202/content/00000000.app is tainted, application behavior may not be as expected!
[  20.302036] Service.FS <Warning> core/file_sys/ncch_container.cpp:ReadOverrideRomFS:399: File C:\Users\Nuno\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00010202/content/00000000.app.romfs overriding built-in RomFS
[  20.434169] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.445497] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.448835] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.450723] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.454689] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.457484] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.460529] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.462533] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.467629] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.469765] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.472481] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.476487] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GenerateUuid': port='act:u' cmd_buf={[0]=0xd0040, [1]=0xfffffffe}
[  20.494829] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  20.506971] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'ControlArchive': port='fs:USER' cmd_buf={[0]=0x80d0144, [1]=0xb, [2]=0x0, [3]=0x0, [4]=0x1, [5]=0x1, [6]=0x1a, [7]=0xe000f88, [8]=0x1c, [9]=0xe000f8c}
[  20.517751] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  20.528376] Service.FS <Error> core/file_sys/archive_extsavedata.cpp:OpenFile:123: C:\Users\Nuno\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/00000000/000018A5/user/data.bin not found
[  20.531682] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFile:69: failed to get a handle for file [Wchar: /data.bin]
[  20.536095] Service.FS <Error> core/file_sys/savedata_archive.cpp:DeleteFile:109: File not found C:\Users\Nuno\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/00000000/000018A5/user/data.bin
[  20.540690] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  20.650405] Service.NDM <Warning> core/hle/service/ndm/ndm.cpp:SuspendDaemons:92: (STUBBED) daemon_bit_mask=0x0000000E
[  20.654367] Service.CECD <Warning> core/hle/service/cecd/cecd.cpp:GetCecInfoEventHandle:37: (STUBBED) called
[  20.657917] Service <Error> core/hle/service/service.cpp:HandleSyncRequest:98: unknown / unimplemented function 'OpenAndRead': port=cecd:u, cmd_buff[1]=0x60, cmd_buff[2]=0x18A500, cmd_buff[3]=0x2, cmd_buff[4]=0x12, cmd_buff[5]=0x20, cmd_buff[6]=0x1, cmd_buff[7]=0x60C, cmd_buff[8]=0xFFFFED0
[  20.661436] Service <Error> core/hle/service/service.cpp:HandleSyncRequest:98: unknown / unimplemented function 'OpenRawFile': port=cecd:u, cmd_buff[1]=0x18A500, cmd_buff[2]=0x3, cmd_buff[3]=0x2, cmd_buff[4]=0x20, cmd_buff[5]=0x20
[  20.665406] Service <Error> core/hle/service/service.cpp:HandleSyncRequest:98: unknown / unimplemented function 'OpenAndRead': port=cecd:u, cmd_buff[1]=0x3, cmd_buff[2]=0x18A500, cmd_buff[3]=0x3, cmd_buff[4]=0x12, cmd_buff[5]=0x20, cmd_buff[6]=0x1, cmd_buff[7]=0x3C, cmd_buff[8]=0x87A97AC
[  20.669337] Service.NDM <Warning> core/hle/service/ndm/ndm.cpp:ResumeDaemons:107: (STUBBED) daemon_bit_mask=0x0000000F
[  20.691484] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:LoadComponent:150: Firmware hash: 0x7f38630a8c994617
[  20.692240] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:LoadComponent:154: Structures hash: 0x1732733d14b84894
[  20.693445] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:LoadComponent:159: (STUBBED) called size=0x35378, prog_mask=0x000300FF, data_mask=0x003500FF, buffer=0x087AA220
[  20.696866] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:RegisterInterruptEvents:251: Registered type=2, pipe=2, event_handle=0x00148049
[  20.699818] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:GetSemaphoreEventHandle:176: (STUBBED) called
[  20.700895] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphoreMask:473: (STUBBED) called mask=0x00002000
[  20.703968] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:149: Application has requested initialization of DSP hardware
[  20.707265] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphore:274: (STUBBED) called
[  20.711592] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphore:274: (STUBBED) called
[  20.834177] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:InitializeSession:40: (STUBBED) unk_param=0x0000000000000000, translation=0x00000020, unk_param4=0x00000000
[  20.995200] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  25.861298] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'ReplySleepQuery': port='APT:A' cmd_buf={[0]=0x3e0080, [1]=0x300, [2]=0x0}
[  25.865684] Loader <Error> core/loader/loader.cpp:GetLoader:126: Failed to load file C:\Users\Nuno\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/00040030/0000d102/content/00000000.app
[  25.867742] Service.NS <Warning> core/hle/service/ns/ns.cpp:LaunchTitle:19: Could not find .app for title 0x000400300000d102
[  25.869375] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  25.872019] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'SaveVramSysArea': port='gsp::Gpu' cmd_buf={[0]=0x190000}
[  25.875423] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:ImportDisplayCaptureInfo:653: called
[  25.909925] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:ReleaseRight:698: called
[  25.911771] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'ReplySleepQuery': port='APT:A' cmd_buf={[0]=0x3e0080, [1]=0x300, [2]=0x0}
[  25.913885] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  25.915267] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:234: (STUBBED) app_id=768
[  25.916435] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  25.918755] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:665: called flag=00000000 process=10 thread_id=0
[  25.923466] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'RestoreVramSysArea': port='gsp::Gpu' cmd_buf={[0]=0x1a0000}
[  25.925570] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000007, input_size=0x00000004, output_size=0x00000001
[  25.927306] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  25.929102] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:665: called flag=00000000 process=10 thread_id=0
[  25.933039] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000007, input_size=0x00000004, output_size=0x00000001
[  25.934083] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  25.935695] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:665: called flag=00000000 process=10 thread_id=0
[  25.962656] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'ControlArchive': port='fs:USER' cmd_buf={[0]=0x80d0144, [1]=0xe, [2]=0x0, [3]=0x0, [4]=0x1, [5]=0x1, [6]=0x1a, [7]=0xe000f88, [8]=0x1c, [9]=0xe000f8c}
[  26.007086] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001
[  29.319215] Service.FS <Warning> core/hle/service/fs/archive.cpp:OpenLinkFile:231: (STUBBED) File command OpenLinkFile Path: [Binary: 000000000000000000000000]
I thing my PC hardware is not needed, as it happens on every PC i test it on. If you need more details, I am happy to provide them

**Comment by mailwl** [comment]
dup
https://github.com/citra-emu/citra/issues/2543

**Comment by Gushasad** [comment]
Is there a chance it will get fixed?

**Comment by mailwl** [comment]
not sure if any developers start fix exactly this game, so it will be fixed, when Citra gets more features like original 3DS

**Comment by wwylele** [comment]
Close as duplicated
