### ISSUE TITLE
Broken Graphics in Lego Star Wars III using GPU mode 

### ISSUE THREAD

**Issue by Luffykun007** [citra-emu/citra#3548]
Broken Graphics in Lego Star Wars III using GPU mode in mode Cpu is normal 
and in Master Build also the graphics are corrects, certainly relates to  ##3499

Canary 421: df68f0b

Canary 421 GPU Mode:
![canary 421 gpu](https://user-images.githubusercontent.com/26087621/37570753-732a2236-2ad2-11e8-9e9b-e6b6c78f67e6.JPG)

Canary 421 CPU Mode:
![canary 421 cpu](https://user-images.githubusercontent.com/26087621/37570761-85939c22-2ad2-11e8-8027-9b7df11a2d6a.JPG)

LOG: [Log Canary 421.zip](https://github.com/citra-emu/citra/files/1823092/Log.Canary.421.zip)

---------------------------------------------------------------------------------------------------------------

Master Build: 79d1bcf5

![master](https://user-images.githubusercontent.com/26087621/37570774-c6f1a52e-2ad2-11e8-80c4-9dde41665f7b.JPG)

LOG Master Build: [Log Master.zip](https://github.com/citra-emu/citra/files/1823103/Log.Master.zip)

PC Specifications:

CPU: I5 6400
GPU: GTX 960
Windows 10 Pro 64 Bits
Version:1607
Build SO: 14393.0

**Comment by chris062689** [comment]
Can you screenshot your graphics tab in Canary?
My guess is this game needs "Accurate Shader" checked.

Can you confirm? Can you show before / after that is checked?

**Comment by Luffykun007** [comment]
yes I'll check this!

**Comment by Luffykun007** [comment]
I just found out that when you tick accurate hardware shader option the error disappears,so I'm closing it.
![5](https://user-images.githubusercontent.com/26087621/37570948-38714388-2ad5-11e8-8902-9cfe6cf88b37.JPG)

**Comment by chris062689** [comment]
:+1: Some games require the accurate hardware shader option.
If you could add this to the game's wiki, it would be useful for other users.
