### ISSUE TITLE
Chat messages padded with gibberish on Linux

### ISSUE THREAD

**Issue by indivisible** [citra-emu/citra#3551]
I'm getting every chat message padded with some bogus chinese-looking character on Linux with the latest canary. After some digging it seems like the client receives the chat message string padded with 0x0 characters.

https://github.com/citra-emu/citra/blob/9e4f670ea98b7d79ea8a518fa996c5dc6eeb82a2/src/network/room.cpp#L439
This looks like the source of the error (in the server side code of the room). Resize will pad with nulls if the string is smaller than the new size, so this should be conditional.

**Comment by johelegp** [comment]
Can confirm:
![1616629710](https://user-images.githubusercontent.com/21071787/112398172-f455fd00-8cd9-11eb-8092-0a851d145bb0.png)
