### ISSUE TITLE
Compiling change in macOS ?

### ISSUE THREAD

**Issue by azoreseuropa** [citra-emu/citra#3555]
I always compiled Citra in the past. What I did was:

For Citra-canary:

1) 

git clone --recursive -b master https://github.com/citra-emu/citra-canary.git

Wait while it is in progressing

2) 

cd citra-canary 

3) 

mkdir build; cd build

4) 

export MACOSX_DEPLOYMENT_TARGET=10.9

5) 

export Qt5_DIR=$(brew --prefix)/opt/qt5

6) 

cmake .. -GXcode

7) 

xcodebuild -config Release -project citra.xcodeproj -target citra-qt

I got an error.

So I  try to use this one recently changed in January 2018:

https://github.com/citra-emu/citra/wiki/Building-for-macOS

And it's working great.

Should I use January 2018 and dont used the old compiled above anymore ? CONFUSION.

**Comment by jroweboy** [comment]
Yes it changed. The wiki has the newer instructions. Also we have canary builds for macOS listed on the website. You don't need to build it yourself. Please ask these sort of questions on the forums in the future, thanks!
