### ISSUE TITLE
[Feature Request] Add Nearest Neighbour filter for the game window.

### ISSUE THREAD

**Issue by MelonSpeedruns** [citra-emu/citra#3556]
When upscaling Citra while keeping the native resolution, the games look blurry, so why not add a nearest neighbour option in the View menu so games look sharper?

**Comment by xperia64** [comment]
This issue can be closed as of #4578. Looks nice and sharp with "Enable Linear Filtering" disabled and resolution set to that of the 3DS.
I'm opening a separate issue to request per-texture NN for higher resolutions.
