### ISSUE TITLE
[OpenBSD] SDL doesn't open correct audio device

### ISSUE THREAD

**Issue by thfrwn** [citra-emu/citra#3559]
First of all, thanks for the great work on this emulator! Thanks to [@hubslave 's instructions](https://github.com/citra-emu/citra/wiki/Building-for-OpenBSD) I was able to build it on OpenBSD. I know OpenBSD isn't officially supported, but there's the minor issue that when I built it first, the audio device couldn't be opened. However, after looking at [SDL_OpenAudioDevice documentation](https://wiki.libsdl.org/SDL_OpenAudioDevice) I patched sdl2_sink.cpp and now audio works!

Here the diff:

```cpp
diff --git a/src/audio_core/sdl2_sink.cpp b/src/audio_core/sdl2_sink.cpp
index 219152ab..f475ed87 100644
--- a/src/audio_core/sdl2_sink.cpp
+++ b/src/audio_core/sdl2_sink.cpp
@@ -56,7 +56,7 @@ SDL2Sink::SDL2Sink() : impl(std::make_unique<Impl>()) {
     }
 
     impl->audio_device_id = SDL_OpenAudioDevice(
-        device, false, &desired_audiospec, &obtained_audiospec, SDL_AUDIO_ALLOW_FREQUENCY_CHANGE);
+        NULL, false, &desired_audiospec, &obtained_audiospec, SDL_AUDIO_ALLOW_FREQUENCY_CHANGE);
     if (impl->audio_device_id <= 0) {
         LOG_CRITICAL(Audio_Sink, "SDL_OpenAudioDevice failed with code %d for device \"%s\"",
                      impl->audio_device_id, Settings::values.audio_device_id.c_str());
```

Could this be changed to default to NULL? Or I could send you a PR with ifdefs for OpenBSD to pick NULL on our platform.

Thanks.

**Comment by j-selby** [comment]
This should most certainly not be null by default - on most platforms, you can choose your audio device through the audio settings. Does this work on BSD?

**Comment by thfrwn** [comment]
On OpenBSD, any combination of audio device and output engine doesn't work without the patch. Audio device is only 'auto' in the pull-down menu, output engine is 'auto', 'sdl2', or 'null'

All show in the log:

```
Audio.Sink <Critical> audio_core/sdl2_sink.cpp:SDL2Sink:62: SDL_OpenAudioDevice failed with code 0 for device "System audio output device"
```

With above patch, audio works if I choose output engine sdl2.

If this is a bug on our platform, it wouldn't be a problem to patch the port downstream. I brought it up here in case this might an issue elsewhere. Of course shouldn't be removed on platforms where it allows choosing the audio device.

**Comment by j-selby** [comment]
If your platform isn't providing a list of audio devices, I would think that to be a bug either in SDL2 or in your platforms audio stack. Setting this to a `nullptr` will damage platforms where in-application audio output configuration is critical (i.e windows). This is a bug that shouldn't be stubbed out here, but investigated somewhat more rather then simply removing code.

**Comment by thfrwn** [comment]
I'll investigate some more.

**Comment by Radhew** [comment]
I also had this issue occur using the installer from Citra's website.
![screenshot from 2018-03-27 10-37-25](https://user-images.githubusercontent.com/37844785/37982550-dd8e8962-31be-11e8-8a3f-ff0dcebb7414.png)

**System Specs:** 
Ubuntu 18.04
CPU: AMD A8-5600k
GPU: AMD Radeon RX 480

Screenshot of my sound settings:
![screenshot from 2018-03-27 12-04-49](https://user-images.githubusercontent.com/37844785/37982817-9f4d6974-31bf-11e8-8627-a9ccdf737c91.png)

**Comment by thfrwn** [comment]
@Radhew What version of SDL2 are you using?
