### ISSUE TITLE
Cannot see the game except using fullscreen

### ISSUE THREAD

**Issue by Yurica39** [citra-emu/citra#3561]

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

When creating a topic on the forums, please fill out the support template.

Closing as invalid

**Comment by Yurica39** [comment]
PC specs :
- Intel G2020 2.9GHz
- Nvidia Geforce GT 9500 512mb ddr2 (Driver 290.53 beta)
- Ram 4GB ddr3 1333mhz

Hello guys, i'm using the latest canary build and the latest valentin build, but i'm not seeing the game unless i use fullscreen, if i use the driver version 300 and up, the game is shown, but since the driver version 300 and up give me much of driver display opengl error code 3, i have to use the previous build which is more stable
Do any of you know exactly the problem?
I'm not in a rush tough, since i can still play using fullscreen as of now, it's only matter when i'm playing online, since i can't see the chat room in fullscreen

**Comment by adityaruplaha** [comment]
Sorry, we can't help out with unofficial builds, but maybe you want to contact the creator?

@valentinvanelislande
