### ISSUE TITLE
Fire Emblem Awakening Graphic Bug

### ISSUE THREAD

**Issue by fizawira** [citra-emu/citra#3562]
On this particular map 'Divine Dragon Ground' the map ground texture isn't rendered properly using the OpenGL settings. I've tried with older nightly builds up to the earliest.

**System Information**

- Operating System: Windows 10
- CPU: i5-3470
- GPU: Nvidia GTX670
- Citra Version: Canary | HEAD-66312b5
- Game: Fire Emblem Awakening
- Screenshot of Issue:

OpenGL:
https://community.citra-emu.org/uploads/default/original/2X/2/20716f3c7c62236ec4e654e3fa4820c23913a426.jpg

Software mode:
https://community.citra-emu.org/uploads/default/original/2X/8/8bcfed46f98cfd953ed7b9a5118809e2d2a2d827.jpg

log.txt file here:
https://pastebin.com/wx74FNbz

Save file of the game (head to the Divine Dragon Grounds: Paralogue 17 in the overworld and start a battle there):
[000a0500.zip](https://github.com/citra-emu/citra/files/1842919/000a0500.zip)

**Comment by RitaPena** [comment]
This bug is still present in the latest Canary (1214) and Nightly (1198), and disabling the Hardware Renderer still "fixes" it, though it slows the game too much to be playable. I have no idea what's causing it, but I'd wager its related to the way water is rendered in this map, which seems to be underneath the land.

**Comment by NickZiggy** [comment]
Same here, thanks for the advice 
![100](https://user-images.githubusercontent.com/28703677/53361396-55b31280-3940-11e9-9b6e-aa451834ba97.png)

> This bug is still present in the latest Canary (1214) and Nightly (1198), and disabling the Hardware Renderer still "fixes" it, though it slows the game too much to be playable. I have no idea what's causing it, but I'd wager its related to the way water is rendered in this map, which seems to be underneath the land.

**Comment by SteveCraftwood** [comment]
Canary 1406, still seeing this issue

**Comment by ThisNekoGuy** [comment]
Also, in the majority of 3D engine-rendered scenes when set to anything above native resolution, all characters have a strange "ghosting" effect where there seems to be transparent "mirror images" of them and, in some cases, weapons (like the bronze sword) are transparent at certain angles (most noticeably seen when characters [like the main character] do a victory pose after combat).

**Comment by ThisNekoGuy** [comment]
The visual ground with the ground being pitch-black is still present even with a very, very recent git build of Citra, as well; I was only recently able to verify this

**Comment by benderscruffy** [comment]
still an issue in the latest nightly
![Screenshot 2023-05-10 164515](https://github.com/citra-emu/citra/assets/2696404/b743fd2b-00bf-43f7-a691-a1865d9c0452)

**Comment by benderscruffy** [comment]
using Canary 2615
has been fixed
can be closed
![Screenshot 2023-09-10 150319](https://github.com/citra-emu/citra/assets/2696404/7d15bee7-28a9-41cd-93b5-6e34d6e1706b)

**Comment by Dragios** [comment]
Fixed by PR #6920
Can someone modify the original PR comment to include this info?
Will be useful for future reference.

**Comment by GPUCode** [comment]
The linked PR also affects vulkan

**Comment by Dragios** [comment]
Unfortunately, the result says otherwise.
![FE:A Graphical Bug](https://github.com/citra-emu/citra/assets/18496868/b5a6a7ea-ea6a-4ff5-aab7-4bb20fdb7bf9)

**Comment by benderscruffy** [comment]
works for me in vulkan
![Screenshot 2023-09-10 175949](https://github.com/citra-emu/citra/assets/2696404/a5545ea2-5b37-4f9f-8c5d-3f9ecfda005c)

**Comment by benderscruffy** [comment]
disable spirv shader generation in vulkan and it works properly

**Comment by GPUCode** [comment]
This is still confusing as spirv affects fragment and not vertex shader generation. So the linked pr could not have fixed the issue. It would either be the blending pr or the previous buffer fix

**Comment by GPUCode** [comment]
The previous fix is simple to port to spirv, I forgot to do it in the original pr. The blend fix is more involved to port though

**Comment by Dragios** [comment]
> This is still confusing as spirv affects fragment and not vertex shader generation. So the linked pr could not have fixed the issue. It would either be the blending pr or the previous buffer fix

I initially shared the same thought as you, but after bisect, I discovered that the issue still occur in [Nightly-1980](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1980). However, it has been successfully addressed in [Nightly-1981](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1981). This led me to my conclusion.

If you still have doubts, perhaps you could consider conducting another test from your end to double-check and confirm.

**Comment by Dragios** [comment]
> This is still confusing as spirv affects fragment and not vertex shader generation. So the linked pr could not have fixed the issue. It would either be the blending pr or the previous buffer fix

I believe you are right. I bisected further it was this PR #6921 that fixes this issue instead. There are multiple PR merged between **Nightly-1980** vs **1981**. Sorry for any confusion caused.

**Comment by GPUCode** [comment]
Dw, thanks for confirming. I will implement this fix to spirv so vulkan can be fixed too

**Comment by GPUCode** [comment]
Closing as has been fixed
