### ISSUE TITLE
Poochy & Yoshi's Woolly World 4-6 Spooky Scraps! Don't Get Spooked!

### ISSUE THREAD

**Issue by mvisser81** [citra-emu/citra#3563]
He Guys,
I found a issue in level 4-6. It is impossible to go any further in the game.

**Screenshot of the problem**
<img width="961" alt="schermafbeelding 2018-03-23 om 20 06 14" src="https://user-images.githubusercontent.com/12214127/37848794-aa9f6166-2ed5-11e8-86c4-e15127a9349c.png">

**Youtube video how it should be**
https://www.youtube.com/watch?v=hO9P1clqCXg

**Log**
[log.txt](https://github.com/citra-emu/citra/files/1843096/log.txt)

**Comment by windwakr** [comment]
This seems to be fixed in the software renderer by #3516.

**Comment by Mickevincent** [comment]
I have the exact same problem. So this game is not possible to finnish, sadly.

**Comment by TheLocoBandito** [comment]
The game might not be able to be completed 100% at the moment but you can still beat the game without clearing 4-6 Spooky Scraps! Don't Get Spooked!

There is a badge called "Clear course badge" which functions just like as running through the stage without collecting anything, you should have unlocked that badge by now?

Here's to hoping that the issue will be solved eventually.

**Comment by Clector** [comment]
![4-6 Yoshi](https://user-images.githubusercontent.com/27870718/56400139-ccb9a880-6217-11e9-9447-e53da88eefc9.png)
The curtain shadows seems to be working fine now in nightly 1248.

**Comment by wwylele** [comment]
@Clector Does nightly 1249 still work? And does canary 1299 not work? and could you upload a screen shot of "kind of messed"?

**Comment by Clector** [comment]
1249 seems to be like cnary now, here I attach an screenshot of how it looks in 1249 and canary. 
![4-6 - 1249](https://user-images.githubusercontent.com/27870718/56457619-279bee80-6343-11e9-96f5-699c27c8a1a1.png)

**Comment by benderscruffy** [comment]
this works properly in both the latest nightly and  canary
can be closed
