### ISSUE TITLE
Severe performance decrease after nightly-591

### ISSUE THREAD

**Issue by Mistraval** [citra-emu/citra#3571]
I noticed after not using Citra for a while and it doing an update at launch that performance has severely decreased on my 2015 Macbook Pro.

I tried downloading a bunch of different nightly's and I was able to pinpoint the decrease to nightly-591. nightly-591 can barely hold 15FPS on Ocarina of Time, while nightly-590 worked flawlessly and held a consistent 30FPS on my mac.

Whatever was changed in nightly-591, still seems to be an issue in the most recent nightly update, so I've disabled auto-updates until whatever happened can be fixed, which hopefully would be some time soon.

**Comment by wwylele** [comment]
It is caused by #3504 and is already reported there.

**Comment by Hexagon12** [comment]
Requesting to close if it was reported already.

**Comment by Dragios** [comment]
@Mistraval Please retest with latest Nightly version. Pretty sure there are plenty of performance improvement by now.

**Comment by SleepingSnakezzz** [comment]
Citra no longer support OpenGL with MacOS due to Citra requiring a higher OpenGL version now.
