### ISSUE TITLE
Fantasy Life - Hair and skin color selection squares are black

### ISSUE THREAD

**Issue by windwakr** [citra-emu/citra#3586]
Picture of the hair color picker:
![untitled](https://user-images.githubusercontent.com/284886/37939762-a9578608-3132-11e8-96b6-2a15931e0a30.png)
That's with the hardware renderer. I can't test with the software renderer because of #3585. Nothing unusual shows up in the log. It's all related to unimplemented friends things. Tested with latest master.

You can see how it's supposed to look in this video. https://www.youtube.com/watch?v=ZLTZIvt7lYw

**Comment by FearlessTobi** [comment]
Please always post a **full** log when opening issues, even when you don't think it's relevant. Please also add one for #3585.

**Comment by windwakr** [comment]
I can't post one with #3585 because you lot seem to think it's a good idea to cause the emulator to crash whenever an error happens.

**Comment by FearlessTobi** [comment]
You should still be able to use CTRL+A/CTRL+C in the console window to get the log.

**Comment by windwakr** [comment]
Everything closes immediately when it crashes.

**Comment by j-selby** [comment]
Then pipe your log to a file.

**Comment by windwakr** [comment]
Nice reading comprehension. Honestly, this isn't worth the bother.

**Comment by j-selby** [comment]
Ha. All I'm hearing is a user who feels like a group of volunteers owes you something.

**Comment by T0DS** [comment]
I have the same issues (this and #3585 ) with the latest canary build b40c597.
Here is a log during character creation with OpenGL https://pastebin.com/LRmAf6uG
All squares for color picking are black. Skin and hair color still change in the character model , but eye color stays black.
With software mode, citra crashes as soon as it gets to the screen to start a new game/load character on the main menu. Changing to software mode past this screen immediately crashes citra.
Log with software:
https://pastebin.com/3u7MuPKj

**Comment by FearlessTobi** [comment]
@T0DS It would be great if you could open a new issue if the problem still exists.
