### ISSUE TITLE
Void Linux x64 MUSL

### ISSUE THREAD

**Issue by Jakecheslekov** [citra-emu/citra#3592]
Hi, I'm trying to compile Citra for Void x64 MUSL, I've ran into some errors & was hoping you may be able to give me some insight into what I could possibly be missing, I just git cloned the repo so the commit hash should be: 7446538  

Is this emulator compatible with MUSL, or does it rely on GLIBC?

Output of cmake & make:
https://pastebin.com/zsY30AtM

Package request to get Citra into the Void x64 MUSL repo:
https://github.com/voidlinux/void-packages/issues/12988

Thank you for your time.

**Comment by wwylele** [comment]
Some system defines `PAGE_SIZE` as a macro. You can try adding `#undef PAGE_SIZE` before that line.

**Comment by Jakecheslekov** [comment]
I'm sorry but where exactly do I do that?

**Comment by Jakecheslekov** [comment]
What file do I go into? Would be nice to know the line too, I'm not sure where I'm supposed to edit this...

**Comment by Jakecheslekov** [comment]
/citra/src/core/hle/kernel/thread.cpp ???? This file? 

Am I supposed to comment out PAGE_SIZE entirely? I'm really not sure how to do this, some clarification would be nice.

**Comment by wwylele** [comment]
I though you could read the log your self...
```
/tmp/citra/src/./core/memory.h:25:11: error: expected unqualified-id before numeric constant
 const u32 PAGE_SIZE = 0x1000;
```
**core/memory.h:25**
So what I said was, to add `#undef PAGE_SIZE` between line 24 and line 25 in core/memory.h

**Comment by Jakecheslekov** [comment]
Ohh my bad, I overlooked that... Sorry about that! thought the edit had to be done elsewhere.
Great emulator btw! 
It has successfully finished compiling - -  thank you for your help!

**Comment by Jakecheslekov** [comment]
One last question, should I be concerned about this?:

[   0.000000] Frontend <Warning> citra_qt/main.cpp:CheckForUpdates:475: Unable to start check for updates
inotify_add_watch("/home/kzn/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000") failed: "No such file or directory"
inotify_add_watch("/home/kzn/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e") failed: "No such file or directory"

**Comment by wwylele** [comment]
@Jakecheslekov no need to concerned about it. For further questions/support please go to our forum or discord server. The issue tracker is only for bug report.
