### ISSUE TITLE
Mario & Luigi Superstar Saga: Can't jump or interact or use the buttons A & B in the game outside of the Menu.

### ISSUE THREAD

**Issue by DrOutside** [citra-emu/citra#3613]
Hi there! So the game starts off fine, I'm able to jump around, talk to NPCs, etc. etc.
But as soon the beginner tutorial is over and I head into Bowsers ship and have Luigi with you for the first time, I can't jump at all. I can't interact with NPCs or do any actions. I can move around and I can make the Brothers jump at the same time via the button command meant for making them jump at the same time.

But the buttons "A" and "B" on the 3ds don't work at all. I'm using Z for the button "A" and X for the button "B", neither of which work.

If I go into the Menu, "A" and "B" work fine. I can click items, check status, hit back by clicking the "B" button, but as soon as I'm out of the menu and in the actual game "A" and "B" stop working. 

Neither Mario nor Luigi can Jump, and I can't interact with anything causing me to get stuck.

**System Information**
* Operating System: Windows 10
* CPU: i5 4690k
* GPU: GTX 970
* Citra Version (found in title bar): HEAD-11b9d30 (If I go into updates, my Installed Version is 623)
* Game: Mario and Luigi Superstar Saga
* Screenshot of Issue (include the full Citra window including titlebar): https://i.imgur.com/H15QH7s.jpg
Also a gif showing that I can't use "A" and "B" in the actual game where I can move around, but if I go into the Menu both the buttons work flawlessly: https://gfycat.com/DisguisedPaleLeafbird

Edit: Issue was with Controller controls. Fixed by copying these controls in this video: https://youtu.be/mxmNYK9b194?t=62

**Comment by Hexagon12** [comment]
Requesting to close.
