### ISSUE TITLE
Sudoku by Nikoli corrupts save

### ISSUE THREAD

**Issue by robzombie91** [citra-emu/citra#3627]
https://pastebin.com/NZGzcrvM

I have started the game, it creates a save file but when i go to restart the game via stop - > double click on game, it says that the save is corrupt and must be remade.

**Comment by zhaowenlan1779** [comment]
Please check if this is fixed by #5120, thanks

**Comment by benderscruffy** [comment]
still happens and i even deleted my save
[citra_log.zip](https://github.com/citra-emu/citra/files/4331928/citra_log.zip)

**Comment by zhaowenlan1779** [comment]
@benderscruffy Please use the Canary build, thanks.

Anyway I bought the game myself and confirmed that it had been fixed on the latest Canary (i.e. by #5120).
