### ISSUE TITLE
File and Emulation menu no longer can be hovered with mouse

### ISSUE THREAD

**Issue by monotykamary** [citra-emu/citra#3633]
Citra Canary 446 (HEAD-eb8c415)
Windows 10.0.16229

Low priority issue in UI. File and Emulation menu can't be hovered with mouse; but no problems showing with View, Multiplayer, and Help menus. Alt menu selecting still works fine.

**Comment by jroweboy** [comment]
Thanks for the report. This is already reported on the appropriate canary pull request that causes the issue, so I'll be closing this one as a duplicate https://github.com/citra-emu/citra/pull/3073#issuecomment-379238916
