### ISSUE TITLE
3D rendering on any game crashes Citra, if shader emulation is GPU

### ISSUE THREAD

**Issue by Robz8** [citra-emu/citra#3640]
Any time 3D is rendered in any game, the emulator crashes, unless if shader emulation is set to CPU, instead of GPU.

Citra: Canary Build - 9c7d6b7

Log:
![3drendercrash-log](https://user-images.githubusercontent.com/16110127/38473801-db9b6498-3b52-11e8-9408-9fb9a9b9253c.png)

PC specs:
OS: Windows 10 x64
GPU: NVIDIA GeForce GTX 260

**Comment by wwylele** [comment]
Please report this to #3499, as GPU shader emulation is not merged in master/nightly yet. Closing.
