### ISSUE TITLE
Sorting the game list increases width

### ISSUE THREAD

**Issue by jl91569** [citra-emu/citra#3642]
Clicking any of the sorting options increases the width of the list.

It happens on both the current Nightly (bdf7b46) and Canary (e8ac99e).

**Comment by BreadFish64** [comment]
Please provide a before and after screenshot of the issue.

**Comment by jl91569** [comment]
<img width="641" alt="citrabefore" src="https://i.imgur.com/nI6lc6n.png">
<img width="641" alt="citraafter" src="https://i.imgur.com/g5Bu1hB.png">
<img width="641" alt="citraafter2" src="https://i.imgur.com/7cxQLiA.png">

That's what happens after clicking it a few times.

**Comment by FearlessTobi** [comment]
Seems to be fixed in latest Nightly.
