### ISSUE TITLE
 Run full screen

### ISSUE THREAD

**Issue by joun0102** [citra-emu/citra#3646]
![20180410_154923947_ios](https://user-images.githubusercontent.com/38256784/38568627-13a5f308-3d24-11e8-9cfd-19859693fe83.jpg)
![20180410_154930309_ios](https://user-images.githubusercontent.com/38256784/38568629-13d394a2-3d24-11e8-8b37-6e37fde97a1d.jpg)

Resolution ?????????

**Comment by adityaruplaha** [comment]
It's your monitors problem that it's pixelated. And the UI getting stuck in full-screen is fixed in Canary by #3610.

**Comment by daniellimws** [comment]
Should be #3611 but whatever doesn't really matter. 

Just download the canary build.

**Comment by FearlessTobi** [comment]
This is fixed by #3611, which is merged now.

Requesting to close.
