### ISSUE TITLE
Pokemon X and Y Cant get past start

### ISSUE THREAD

**Issue by wingedonezero** [citra-emu/citra#3648]
I know everyone has mentioned it before but there isn't a issue open on it. But when you name your character and it zooms off to the door the game doesn't go any further. It doesn't crash but it more hangs than anything. Log is using canary build b40c597.

[pokemon y log.txt](https://github.com/citra-emu/citra/files/1897496/pokemon.y.log.txt)

**Comment by tgsm** [comment]
This is a known crash. You can get past it if you already have a save file, but even then the game softlocks when most sound effects are attempted to be played.

**Comment by robzombie91** [comment]
#3009

**Comment by wwylele** [comment]
closing as duplicated
