### ISSUE TITLE
Keyboard Shortcuts Feature Request And Issues

### ISSUE THREAD

**Issue by Rafidmuhaiminwafi** [citra-emu/citra#3650]
I'm not being able to use keyboard shortcut of fullscreen. But I'm not sure as I'm using one month old build. So please retest it with the latest build. Also I want that the citra team adds shortcuts to toggle single screen, slide to slide, default view, swap screen on or off.

**Comment by N00byKing** [comment]
To toggle the Layout press F10

**Comment by Rafidmuhaiminwafi** [comment]
For any layout or for a particular?

**Comment by Rafidmuhaiminwafi** [comment]
Thanks.

**Comment by adityaruplaha** [comment]
Please close as this has been resolved.
