### ISSUE TITLE
Fantasy Life - Hair, Skin and Eye color selection boxes are black.

### ISSUE THREAD

**Issue by T0DS** [citra-emu/citra#3654]
![capture](https://user-images.githubusercontent.com/38330443/38704236-0b2b4846-3e7c-11e8-9d0d-2a7bcb7acc64.PNG)

While the boxes are black, selection for hair and skin color still work on the character model. Eyes stay black no matter what. Here is a log running with Opengl:
https://pastebin.com/EA2Y6PcC

Trying to run it on software mode causes the emulator to crash on the save selection screen. 
Log for software mode:
https://pastebin.com/eHiAyzyw

**Comment by wwylele** [comment]
The software renderer crash is due to invalid texture address, which might or might not be related (the game might just leave it invalid and doesn't use the texture. Our software renderer doesn't handle well in this case). After bypassing the invalid texture (set the texture sample color to zero), software renderer also shows the same black color issue.

**Comment by ds84182** [comment]
@wwylele What happens when you set the sample color to white?

**Comment by benderscruffy** [comment]
still happens in the latest nightly
![fantasy](https://user-images.githubusercontent.com/2696404/50719374-21586e00-10d6-11e9-99a6-6b7d2bb8b2f8.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2729080/citra_log.zip)

**Comment by benderscruffy** [comment]
it is still an issue

**Comment by zmarotrix** [comment]
This is still an issue. To add onto this, the eyes on the player character are also always black.

**Comment by Azurion42** [comment]
using Citra Canary 2306 on Kubuntu Linux and this eye texture problem is still going on. I'm even using custom HD textures. The missing textures were happening even before I added the HD ones.

**Comment by benderscruffy** [comment]
using the latest nightly it is still an issue

**Comment by MidoriMushrooms** [comment]
Hello. I have the same issue, but it's showing the textures as white for me. Does anyone have a fix for this?
