### ISSUE TITLE
problem installing some CIA's

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#3658]
tried to install Journey to Kreisia  and SteamWorld Dig 2  both are cia's
nothing comes up in the menu but it says that they were installed successfully 
have tried it many times
happens both in canary and nightly 
maybe a problem with the newer cia's

**Comment by benderscruffy** [comment]
still happens in the latest nightly
i just installed steamworld dig 2
nothing in the log 
![app](https://user-images.githubusercontent.com/2696404/50721778-00a50e00-1100-11e9-9569-4ff528c13df4.PNG)

**Comment by jvook** [comment]
@benderscruffy  did you solve this issue somehow?

**Comment by B3n30** [comment]
The solution is to dump your games without encryption or provide aes-keys. For advice how to do this go to discord/our forums

**Comment by benderscruffy** [comment]
closed as there are multiple issues that are the same already open

**Comment by jvook** [comment]
Why not close them all and point at this one with the solution?
