### ISSUE TITLE
Build error under Fedora

### ISSUE THREAD

**Issue by KAMiKAZOW** [citra-emu/citra#3672]
Today's git checkout doesn't build under Fedora (26&27). Four days ago it was fine. Fedora's Qt 5.9 [did not change in two months](https://koji.fedoraproject.org/koji/buildinfo?buildID=1044282), so it's not that.

[ 1289s] In file included from /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/build/src/citra_qt/citra-qt_autogen/EWIEGA46WW/moc_game_list_p.cpp:9:0,
[ 1289s]                  from /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/build/src/citra_qt/citra-qt_autogen/mocs_compilation.cpp:14:
[ 1289s] /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/build/src/citra_qt/citra-qt_autogen/EWIEGA46WW/../../../../../src/citra_qt/game_list_p.h: In constructor 'GameListItemCompat::GameListItemCompat(QString)':
[ 1289s] /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/build/src/citra_qt/citra-qt_autogen/EWIEGA46WW/../../../../../src/citra_qt/game_list_p.h:160:17: error: 'QCoreApplication' has not been declared
[ 1289s]          setText(QCoreApplication::translate("GameList", status.text));
[ 1289s]                  ^~~~~~~~~~~~~~~~
[ 1289s] /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/build/src/citra_qt/citra-qt_autogen/EWIEGA46WW/../../../../../src/citra_qt/game_list_p.h:161:20: error: 'QCoreApplication' has not been declared
[ 1289s]          setToolTip(QCoreApplication::translate("GameList", status.tooltip));
[ 1289s]                     ^~~~~~~~~~~~~~~~
[ 1290s] In file included from /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/src/./common/microprofile.h:23:0,
[ 1290s]                  from /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/build/src/citra_qt/citra-qt_autogen/TBDDORYXJM/../../../../../src/citra_qt/debugger/profiler.h:10,
[ 1290s]                  from /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/build/src/citra_qt/citra-qt_autogen/TBDDORYXJM/moc_profiler.cpp:9,
[ 1290s]                  from /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/build/src/citra_qt/citra-qt_autogen/mocs_compilation.cpp:28:
[ 1290s] /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/externals/./microprofile/microprofile.h: In function 'MicroProfileLogEntry MicroProfileMakeLogIndex(uint64_t, MicroProfileToken, int64_t)':
[ 1290s] /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/externals/./microprofile/microprofile.h:830:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
[ 1290s]      MP_ASSERT(t == nBegin);
[ 1290s]                ~~^~~~
[ 1290s] /home/abuild/rpmbuild/BUILD/citra-0.0.20180418+git.048b0fc0d/externals/./microprofile/microprofile.h:238:30: note: in definition of macro 'MP_ASSERT'
[ 1290s]  #define MP_ASSERT(a) do{if(!(a)){MP_BREAK();} }while(0)
[ 1290s]                               ^
[ 1291s] make[2]: *** [src/citra_qt/CMakeFiles/citra-qt.dir/build.make:553: src/citra_qt/CMakeFiles/citra-qt.dir/citra-qt_autogen/mocs_compilation.cpp.o] Error 1
[ 1291s] make[1]: *** [CMakeFiles/Makefile2:1613: src/citra_qt/CMakeFiles/citra-qt.dir/all] Error 2
[ 1291s] make: *** [Makefile:141: all] Error 2

Complete log under https://build.opensuse.org/build/home:KAMiKAZOW:Emulators/Fedora_27/x86_64/citra/_log

**Comment by FearlessTobi** [comment]
cc @jroweboy

**Comment by lioncash** [comment]
This is likely fixed by #3670
