### ISSUE TITLE
make release bundles? would be helpful for porters

### ISSUE THREAD

**Issue by rfht** [citra-emu/citra#3685]
Hi,

Any chance you could publish release bundles/assets of citra? I got a working port for OpenBSD that I want to submit to the ports tree and with just checking out a commit, the size and hash regularly change when github changes its tools, breaking the port system that checks these before building.

An upload of the distfiles as a tarball would be perfect because that's the only really stable way of providing distfiles that don't change.

Thanks!

**Comment by j-selby** [comment]
What is the problem with the .zip/.tar.gz files provided at https://github.com/citra-emu/citra-nightly/releases or https://github.com/citra-emu/citra-canary/releases ?

**Comment by rfht** [comment]
Thanks, good to know that these exist. The ideal situation for the port would be if you could add an upload of a .7z or .tar.gz or .tar.xz of the source code. The source code links at the bottom are the auto-generated ones from github and they do change in size/hash sometimes.

An example of how this would look like can be found here for fs2open:

https://github.com/scp-fs2open/fs2open.github.com/releases/tag/release_3_8_0

The file `fs2_open_3_8_0-source-Unix.tar.gz` contains the source files, and other than the auto-generated ones, they don't change over time as github changes its tools.

**Comment by baka0815** [comment]
Cirrently Citra doesn't do builds as it's not stable enough for that. The nighltys and canaries change too often to provide source tarballs in my opinion.

**Comment by rfht** [comment]
@baka0815 This makes sense and is good to know - means I'll start the versioning accordingly to leave the option to do major.minor versioning later when citra is maybe more stable.
