### ISSUE TITLE
Dragon Ball Extreme Butoden - Multiplayer is not working correctly

### ISSUE THREAD

**Issue by MojoJojoDojo** [citra-emu/citra#3687]
![image](https://user-images.githubusercontent.com/33392696/39211947-dc53ce14-4815-11e8-91b9-3180ec0b54d9.png)

I cant get the game to work using local multiplayer over the internet.
I get the error above as you see.
My version of citra is 7d8b7d9 i tried both canary and nightly.

this is the log:
[log.txt](https://github.com/citra-emu/citra/files/1944462/log.txt)

**Comment by greggameplayer** [comment]
@MojoJojoDojo The Mulitplayer doesn't work in lot of games. You can find the good working one here : https://citra-emu.org/entry/announcing-networking-support/

**Comment by MojoJojoDojo** [comment]
ahh it worked before.

**Comment by MojoJojoDojo** [comment]
Got fixed in the latest canary.

**Comment by B3n30** [comment]
How was it fixed? What was the PR that fixed it?
