### ISSUE TITLE
Pokemon Alpha Sapphire - Seafloor Cavern issue

### ISSUE THREAD

**Issue by Speedsteer148** [citra-emu/citra#3691]
when i am in seafloor cavern the cmd screen send me a error, and after defeating Archie, the cinematic when the legendary pokemon awakening dont continue, stuck in black screen.
The rest of the game works fine, and this issue happens in 2 versions of citra, Canary and Nightly

Operating System: Windows 7 Ultimate 64 bits
CPU: Intel Pentium G6950 2.8ghz
GPU: Zotac Geforce GT 630
Citra Version: Canary Build - 60e094e
Game: Pokemon Alpha Sapphire

![1](https://user-images.githubusercontent.com/38736145/39269893-2e2eec1e-48a2-11e8-8be4-198a6be89539.jpg)
![2](https://user-images.githubusercontent.com/38736145/39269907-3de6f0d4-48a2-11e8-9fdc-95e37db69376.jpg)
![3](https://user-images.githubusercontent.com/38736145/39269923-4aa63e88-48a2-11e8-98d2-6cfb7e0ca70e.png)

this is my log: 
[log.txt](https://github.com/citra-emu/citra/files/1948677/log.txt)

**Comment by wwylele** [comment]
could you provide a save near the issue point?

**Comment by Speedsteer148** [comment]
there it is! test it if happen the same issue pls!
[save AS.zip](https://github.com/citra-emu/citra/files/1949242/save.AS.zip)

**Comment by wwylele** [comment]
Issue reproduced on my end. I also did a quick experiment: changed the language to English using pkhex and it bypassed the freeze.

Looks like an language-dependent issue another round.

**Comment by Speedsteer148** [comment]
so the language is problem?

**Comment by MojoJojoDojo** [comment]
Pokemon have the weirdest bugs

**Comment by cxuy97** [comment]
I have the same problem, but I could not solve it. Please help.

**Comment by cxuy97** [comment]
How is the game language changed? The PKHEX does not allow it.

**Comment by RocketRobz** [comment]
@cxuy97 You change it in the emulator settings.

**Comment by zhaowenlan1779** [comment]
@RocketRobz I think he meant game language which is different. I believe it is changeable somewhere in PKHex, but haven't actually tried myself.

**Comment by vdelae** [comment]
Can some one please help me, i have this same problem on a
[main.zip](https://github.com/citra-emu/citra/files/2777044/main.zip)

 mac, my game is in spanish and when Kyogre is gonna be waken up the game stays in a black screen

**Comment by debugzxcv** [comment]
unable to reproduce issue on citra canary 1522

**Comment by MIDAS369** [comment]
I also solved this issue with PKHex

**Comment by tywald** [comment]
The issue is still present on Nightly 1465: https://community.citra-emu.org/t/black-screen-in-pokemon-alpha-sapphire-when-primal-kyogre-awakes/210318 this user's save file is in Spanish.

**Comment by Hareon** [comment]
The problem occurs when we use a layered translation on Citra too.
In 3DS games, this video is rendered and plays normally, but, in Citra (Canary and Naughtly versions).

The patch is from here https://www.e4t.com.br/downloads/oras/pokemon-alfa-safira/ (PatchMOD)

This issue appears to be the same issue that occurred in XY until 2019, where the game crashed before the intro video played.

In this version it seems to crash in the same way, on a black screen and before the execution of a video.

**Comment by benderscruffy** [comment]
using canary 2610 
this has been fixed
can be closed
