### ISSUE TITLE
Duplicated logs

### ISSUE THREAD

**Issue by valentinvanelslande** [citra-emu/citra#3693]
Commit: 1b94f25
![duplicated-logs](https://user-images.githubusercontent.com/22228082/39342769-29c37bb0-499f-11e8-9f6a-b62c1c1d380d.png)

**Comment by valentinvanelslande** [comment]
@daniellimws yes

**Comment by jroweboy** [comment]
@daniellimws no we attach a console backend in https://github.com/citra-emu/citra/blob/1b94f25e6c0fdf73068d3566a60ec433f869cfd3/src/citra_qt/debugger/console.cpp#L25 as well

**Comment by daniellimws** [comment]
Oh oops because I was running from the command line, and also on Linux, not Windows.

**Comment by jroweboy** [comment]
@daniellimws probably the best thing to do would be to add an `#else` to ToggleConsole that adds a colorbackend for every other system
