### ISSUE TITLE
Feature request: support multiple displays

### ISSUE THREAD

**Issue by eproxus** [citra-emu/citra#3698]
It would be awesome if it was possible to split the top and bottom screen and show each one on a separate computer display.

**Comment by jroweboy** [comment]
Strange. Thought we already had an issue for this, but I guess not.

Anyway, if someone wants to work on this, I started on it a year ago, and have an old, out of date branch here: https://github.com/jroweboy/citra/tree/splitscreen Its not functional of course, but should give an idea about how I was thinking about supporting this for citra.

**Comment by adityaruplaha** [comment]
It's already possible if you extend the displays & follow a tutorial on the forums.

**Comment by Nikorasu95** [comment]
I 2nd this!
