### ISSUE TITLE
Fire Emblem Awakening Issues

### ISSUE THREAD

**Issue by Fewshin** [citra-emu/citra#3713]
Version: db43205 (canary)

When setting the voices to Japanese with the game in the North America region, when the game is restarted the voices revert back to English. Something to note is that in the settings it says the voices are in Japanese but in game they are in English. This can be fixed by switching the voices back to English and then to Japanese again but it's still a bug. 

I wasn't able to find specific details about the extent to which DLC was supported looking around but using the install CIA file feature with the Fire Emblem Awakening DLC didn't work as intended. Looking at the console while trying to access the DLC in game it seems like there are out of bounds errors. I attached the log of my installation of the DLC, attempt to access the DLC in game, and a section of gameplay. 

If any additional information is needed just ask and I will do my best to provide it. 

[FEA_Error_Log.txt](https://github.com/citra-emu/citra/files/1973504/FEA_Error_Log.txt)

**Comment by BreadFish64** [comment]
It's a known issue that the vast majority of DLC fails to load in Citra right now.

**Comment by jroweboy** [comment]
This seems to be resolved now that DLC in citra is fixed. Please reopen this issue if its still happening.

**Comment by Airys** [comment]
I installed the .cia file successfully, but when i go to the outrealms portal, the game shows a massage saying that the dlc maps are loading.  The ROM is still running, but it seems to have issues to load the maps.
I deleted the dlc files in Citra's folders, and reinstalled it successfully, but it stills do the same.
