### ISSUE TITLE
Shared Fonts Issue On Mac

### ISSUE THREAD

**Issue by mtgrules217** [citra-emu/citra#3718]
I am getting the following error:

**Citra was unable to locate the 3DS shared fonts. 
The game you are trying to load requires additional
files from your 3DS to be dumped before playing.**

I've see fixes for windows but nothing for Mac.

**Comment by jl91569** [comment]
https://citra-emu.org/wiki/dumping-system-archives-and-the-shared-fonts-from-a-3ds-console/

**Comment by wwylele** [comment]
https://github.com/citra-emu/citra/wiki/Dumping-System-Archives-and-the-Shared-Fonts-from-a-3DS-Console
This guide applies to all operating systems including Mac.

----
This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://community.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
 - use any kinds of non-official build, or
 - use pirated copies of the games, 3DS system files or any copyrighted content.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid
