### ISSUE TITLE
Shantae and the Pirate's Curse retail releases won't pass the intro

### ISSUE THREAD

**Issue by Mc-muffin** [citra-emu/citra#3726]
The retail game just plays the _RisingStar Games_ animation and then crashes the emulator, while the eShop releases seem perfectly fine

**System Information:**

* Operating System: Windows 10
* CPU: i5-3317U
* Citra Version: Canary | HEAD-1191910
* Game: Shantae and the Pirate's Curse [000400000019D900] (retail european version)

![crash](https://user-images.githubusercontent.com/8714476/39701502-098d4080-51c7-11e8-8dc0-501c766b77a7.png)

It might be related to #2411 because of this lines
```
[ 959.225467] Kernel.SVC <Error> core/hle/kernel/svc.cpp:CallSVC:1411: unimplemented SVC function GetCurrentProcessorNumber(..)
[ 959.225491] Kernel.SVC <Error> core/hle/kernel/svc.cpp:CreateThread:750: Newly created thread must run in the SysCore (Core1), unimplemented.
```

[Log.txt](https://github.com/citra-emu/citra/files/1979791/Log.txt)

**Comment by Leo626** [comment]
Just to clarify this is the retail version? I was told the eShop version has no issues.

**Comment by Mc-muffin** [comment]
You are right his is the retail version, I haven't tested the eShop version so I don't know if that one works.

**Comment by Mc-muffin** [comment]
Just tested the European eShop version, you are right it works as expected.

![2018-05-09 05_53_02-citra canary _ head-1191910](https://user-images.githubusercontent.com/8714476/39811128-53d4dd10-534d-11e8-99c2-1885302aff49.png)

**Comment by mailwl** [comment]
maybe change topic name to "Retail"?

**Comment by benderscruffy** [comment]
using the latest nightly this goes ingame now
this can be closed
![curse](https://user-images.githubusercontent.com/2696404/50382470-ea985600-06da-11e9-9351-bd5c87900f08.PNG)
