### ISSUE TITLE
Building fails on ARM

### ISSUE THREAD

**Issue by DrDab** [citra-emu/citra#3727]
I am running Debian 9 buster/sid. I used the following commands to attempt build for ARM CPU:
```
mkdir build && cd build
cmake ../
make
```
However, when building using GCC 7.3, while building ``externals/cryptopp/CMakeFiles/cryptopp.dir/cryptopp/rjindael-simd.cpp.o`` I run into the following error:
```
c++: error: unrecognized command line option '-msse4.1'
c++: error: unrecognized command line option '-maes'; do you mean '-mapcs'?
externals/cryptopp/CMakeFiles/cryptopp.dir/build.make:478: recipe for target 'externals/cryptopp/CMakeFiles/cryptopp.dir/rjindael-simd.cpp.o' failed
```

These flags are x86-specific flags, and should be dynamically applied instead. It may be a good idea to remove these flags being added by default, as the inclusion of these flags by default results in a crash when compiling on ARM-based platforms (Raspberry Pi, Beaglebone, etc.).

**Comment by MerryMage** [comment]
Relevant lines: 
https://github.com/citra-emu/citra/blob/1f04e2e4a1119b73e7d2246c72237b28c0a8d310/externals/cryptopp/CMakeLists.txt#L192

Upstream:
https://github.com/noloader/cryptopp-cmake/blob/649f44c40e395863d2e046fcb1e71fe45cf54694/CMakeLists.txt#L432
