### ISSUE TITLE
Citra-qt.exe Has stopped working

### ISSUE THREAD

**Issue by Speedfist** [citra-emu/citra#3728]
okay so I downloaded citra and whenever I try to play ocarina of time 3d it says Citra-qt.exe has stopped working, please help Im sad

**Comment by BreadFish64** [comment]
This is an issue tracker for developers, it is not for user support, please post a topic in our [User forums](https://community.citra-emu.org/) or join our [Discord server](https://citra-emu.org/discord/) for support.
