### ISSUE TITLE
Drop EMU_PLATFORM usage

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#373]
It provides virtually no advantage over checking for the platform-specific preprocessor definitions, maybe other than being consistent, which is kind of useless because it trades that consistency for being de facto standardized.

I like having few project-specific oddities, so I suggest dropping and replacing it with the corresponding preprocessor definitions.

**Comment by lioncash** [comment]
This is likely fixed now by @linkmauve's cleanups

**Comment by yuriks** [comment]
Yep, it is. "Syntax" of the commit message was wrong, so it didn't auto-close.
