### ISSUE TITLE
[Monster Hunter XX] Artifacts due to Nvidia GPU's tiled cache (workaround available)

### ISSUE THREAD

**Issue by Hoshiyuu** [citra-emu/citra#3731]
Edit: Workaround courtesy of /u/FIocker and @Krusher97 
https://www.reddit.com/r/cemu/comments/6qwmon/got_blocky_artifacts_in_lava_water_and_other/
Edit 2: Workaround only works on (non-native) 2x rendering and above.

Artifacts started showing up in Monster Hunter XX on canary-481-2763adf (last issue-free version tested is canary-478-db43205, no windows build was made available for 479 and 480 so i can't confirm)
![image](https://user-images.githubusercontent.com/6470662/39865542-cf577bf4-547f-11e8-9cb9-72c2de99c12a.png)

Apparently it was a long standing issue for Nvidia cards that was pseudo-fixed for a while but came back.

Details from wwylele @ https://github.com/citra-emu/citra/pull/3499#issuecomment-387960317
"@Hoshiyuu that kind of artifact has been there for some Nvidia GPU since the first time citra was able to run Monster Hunter. It is in the texturing/rasterizer and is about the tiled cache. It was somehow "fixed" by the original version of this PR. However, it is likely that this PR didn't fix it, because this PR didn't touch the texturing/rasterizer part; instead, it was some unusual GPU usage, such as sharing different data in the same buffer, that disabled the (erroneous?) Nvidia optimization and removed the artifact. In recent commits I changed the code so that it worked in a more common way, which might enable the optimization again, and therefore the artifact is back."

**Comment by Hexagon12** [comment]
Please report Canary issues only under their PRs.

Requesting to close.

**Comment by wwylele** [comment]
This should also happen in nightly, right?

**Comment by Hoshiyuu** [comment]
@Hexagon12 https://github.com/citra-emu/citra/pull/3499#issuecomment-387894671
Reported and,
https://github.com/citra-emu/citra/pull/3499#issuecomment-387960317
"In short, it is out of scope of this PR."
Hence the issue.

@wwylele yeap. Quick test on Nightly-3bd1cd0
![image](https://user-images.githubusercontent.com/6470662/39868105-b485bc86-548a-11e8-8a7c-86d2f8100ba7.png)

**Comment by wwylele** [comment]
The current theory of @degasus and mine is that the game binds a the same texture to both sampler and framebuffer. I did a quick test and it shows that there is indeed such case in this game, and the game probably legitimately samples from and renders to the same texture at the same time. So the following question need to be answer:
 - Is that the intended behaviour of the game?
 - Does 3DS/PICA support sampling from & rendering to the same texture, without undefined behaviour?

**Comment by Krusher97** [comment]
These artifacts only show up when I am at 3x Native resolution or above on my Nvidia 750Ti. I don't see them at 2x and Native resolution.

**Comment by Hoshiyuu** [comment]
![image](https://user-images.githubusercontent.com/6470662/40073632-f0baa586-58a9-11e8-9016-f0204873a2e9.png)
Nvidia 1060 @ Native is a fullscreen artifacting for me, the higher resolution i go, the less of the screen it affects (only a decently narrow bar of artifact at left of screen at 9x resolution)

**Comment by Krusher97** [comment]
I managed to get rid of the blocky artifacts by using an Nvidia inspector guide for Cemu and adding Citra-qt as an additional application
This is the guide : https://www.reddit.com/r/cemu/comments/6qwmon/got_blocky_artifacts_in_lava_water_and_other/

**Comment by Hoshiyuu** [comment]
I can confirm @Krusher97 's method works with minimal side effects or frame time differences (+-2ms frame time), I'll add it to the starting post and edit the title for the known workaround until a proper fix can be implemented?
