### ISSUE TITLE
Camera image not shown in some games

### ISSUE THREAD

**Issue by RocketRobz** [citra-emu/citra#3739]
For some games, instead of the camera image being shown, it's just a solid black image.
Seems like the unimplemented `SetPhotoMode` function is the culprit of this issue (EDIT: which actually, is not the culprit), as during testing, that appeared in the log for both Dragon Ball Heroes: Ultimate Mission X, and Style Savvy: Fashion Forward.

Log for Style Savvy: Fashion Forward
![ssff-camera-log](https://user-images.githubusercontent.com/16110127/39960325-16711978-55de-11e8-9548-2aaf8bf1cc0a.png)

Known games with this issue:
* Dragon Ball Heroes: Ultimate Mission X (tested by @Zantar)
* Gundam Try Age SP (tester unknown)
* PriPara Mezase! Idol * Grand Prix No. 1! (tested by @SeravySensei)
* PriPara Mezameyo! Megami no Dress Design (tested by @SeravySensei)
* PriPara Idol Time: Yume All-Star Live! (tested by @SeravySensei)
* Style Savvy: Fashion Forward

**Comment by CaptV0rt3x** [comment]
The log mentions CAM service, which is a 3ds service and isn't fully implemented yet. 

The Camera support for Citra which was recently merged is just code for using the PC camera in place of the actual 3ds camera - to facilitate features like QR code scanning etc.

**Comment by wwylele** [comment]
@CaptV0rt3x the CAM service is supposed to be at a near-fully-implemented stage now, so this report does contain its own value that you can't pass by saying "the whole stuff is not implemented yet".

**Comment by zhaowenlan1779** [comment]
Would you please upload citra log? In fact, I don't think the unimplemented functions will cause this...

**Comment by zhaowenlan1779** [comment]
My own test results:
It's not something about ```SetPhotoMode```, because even Pokemon UM (camera working) calls it.
However, the games with the issue continuously calls this:
```
[ 753.856920] Service.CAM <Warning> core/hle/service/cam/cam.cpp:GetTransferBytes:478: (STUBBED)called, port_select=1
[ 753.857237] Service.CAM <Warning> core/hle/service/cam/cam.cpp:GetTransferBytes:478: (STUBBED)called, port_select=2
[ 753.968739] Service.CAM <Warning> core/hle/service/cam/cam.cpp:GetTransferBytes:478: (STUBBED)called, port_select=1
[ 753.969253] Service.CAM <Warning> core/hle/service/cam/cam.cpp:GetTransferBytes:478: (STUBBED)called, port_select=2
``` 
Strangely enough, the qt camera is started correctly, but just nothing is displayed
```
[ 746.151949] Service.CAM <Info> citra_qt/camera/qt_multimedia_camera.cpp:GetHandler:148: Successfully got handler 0
[ 746.660581] Service.CAM <Info> citra_qt/camera/qt_multimedia_camera.cpp:GetHandler:148: Successfully got handler 1
```
I think nothing is wrong elsewhere in the log.
Code clip in core/hle/service/cam/cam.cpp:GetTransferBytes
```cpp
    if (port_select.IsSingle()) {
        int port = *port_select.begin();
        rb.Push(RESULT_SUCCESS);
        rb.Push(cam->ports[port].transfer_bytes);
    } 
```
[citra log](https://pastebin.com/RqHH92Yr)

**Comment by Robz8** [comment]
The AR Games app also shows:
```
[  41.276154] Service.CAM <Warning> core/hle/service/cam/cam.cpp:GetTransferBytes:493: (STUBBED)called, port_select=1
[  41.277741] Service.CAM <Warning> core/hle/service/cam/cam.cpp:GetTransferBytes:493: (STUBBED)called, port_select=2
[  41.378838] Service.CAM <Warning> core/hle/service/cam/cam.cpp:GetTransferBytes:493: (STUBBED)called, port_select=1
[  41.380164] Service.CAM <Warning> core/hle/service/cam/cam.cpp:GetTransferBytes:493: (STUBBED)called, port_select=2
```
but the image is displayed.

**Comment by zhaowenlan1779** [comment]
Test log in debug level
[log](https://pastebin.com/z4BUZgr2)

**Comment by Robz8** [comment]
Did another test with Fashion Forward on Canary #905.
I have provided the full log this time.
[citra_log.txt](https://github.com/citra-emu/citra/files/2435873/citra_log.txt)

**Comment by SeravySensei** [comment]
Having this problem in the two Pripara games : https://gamefaqs.gamespot.com/3ds/176042-pripara-mezase-idol-grand-prix-no1 https://gamefaqs.gamespot.com/3ds/193016-pripara-mezameyo-megami-no-dress-design
The loaded image shows in the preview in the configuration menu, but in the game, nothing, just a black background. The first game requires a QR code to unlock two characters, unfortunately.
Is there anything I can do to provide more information? I'm not familiar with how the debugging works.

**Comment by RocketRobz** [comment]
@SeravySensei Test the first Pripara game, then upload `citra_log.txt` from `user/log`, after reaching the black background.
Restart Citra, then test the second Pripara game, and upload `citra_log.txt` from `user/log` again.

**Comment by SeravySensei** [comment]
First game log : https://drive.google.com/open?id=1VmeezbnK5oeMdVy0IpeT8kmZigDVFQdq
Second game log : https://drive.google.com/open?id=1Eu_FCuuX4p80desTexuAYD60D_3NsJw7
Third game log : https://drive.google.com/open?id=16Qk1BntB3zmSMzZ0iM5i8YRJq195Kbd9 game link : https://gamefaqs.gamespot.com/3ds/214510-pripara-idol-time-yume-all-star-live seems to have the same problem.

**Comment by FearlessTobi** [comment]
this seems suspicious:
```Service.CAM <Warning> core/hle/service/cam/cam.cpp:GetTransferBytes:480: (STUBBED)called, port_select=1```
```Service.CAM <Warning> core/hle/service/cam/cam.cpp:GetTransferBytes:480: (STUBBED)called, port_select=2```
