### ISSUE TITLE
Sonic Boom: Shattered Crystal stuck after few seconds launch

### ISSUE THREAD

**Issue by matiffeder** [citra-emu/citra#3748]
Sonic Boom: Shattered Crystal stuck at black screen after few seconds launch the game.

My Specs:
Citra Canary - 6b84ed9
I5-6300HQ
GTX950M
Windows 10 1709
12 GB Ram
[citra_log.txt](https://github.com/citra-emu/citra/files/2008849/citra_log.txt)

**Comment by Hexagon12** [comment]
Duplicate of #2654 

Requesting to close.

**Comment by matiffeder** [comment]
Sorry, I think it's long time ago, so I post it again, should I delete?
