### ISSUE TITLE
Graphical Glitch - Pokemon Omega Ruby

### ISSUE THREAD

**Issue by jared53** [citra-emu/citra#3752]
I have just updated to the latest version of citra and i am experiencing graphical issues. I had been playing omega ruby a lot today before i updated it so i know it must be something from the update. When i try to open the game it is just a black screen for a while and then some overlays of smoke and fire pop up but besides that it's just all black. It seems as if the menu screen is still there, as when i click up and down the the little "ding" sound effect plays, but i clicked where you normally would to continue a game and i don't think it opened it. I am sorry if i did not provide enough information as i am newer to emulation and this is my first post on this site. Would gladly appreciate any advice! I'm playing on a new macbook pro if that helps. Thank you so much!!!!

\
<img width="1440" alt="screen shot 2018-05-18 at 7 36 42 pm" src="https://user-images.githubusercontent.com/39422538/40262142-34a23cfc-5ad3-11e8-9751-a4e1abdbd94b.png">

**Comment by jared53** [comment]
also i have not tested any other games yet because i am kind of afraid if it messed up my game

**Comment by keeano92** [comment]
I noticed switching hardware shaders off gave me the frame rate i needed.

**Comment by jared53** [comment]
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	8 GB
  Boot ROM Version:	MBP141.0173.B00
  SMC Version (system):	2.43f6
  Serial Number (system):	C02V2B41HV27
  Hardware UUID:	BF93C4C4-274C-59AF-8EAB-54E707781929

I am sorry I'm having a heck of a time finding my log file with mac sierra. I have been looking for almost an hour but they don't try to make it easy to access ANY files smh. I will try to look for it more and will let you know if i find it. Sorry again

**Comment by jared53** [comment]
@keeano92 I am sorry I'm having a heck of a time finding my log file with mac sierra. I have been looking for almost an hour but they don't try to make it easy to access ANY files smh. I will try to look for it more and will let you know if i find it. Sorry again

Hardware Overview:

Model Name:	MacBook Pro
Model Identifier:	MacBookPro14,1
Processor Name:	Intel Core i5
Processor Speed:	2.3 GHz
Number of Processors:	1
Total Number of Cores:	2
L2 Cache (per Core):	256 KB
L3 Cache:	4 MB
Memory:	8 GB
Boot ROM Version:	MBP141.0173.B00
SMC Version (system):	2.43f6
Serial Number (system):	C02V2B41HV27
Hardware UUID:	BF93C4C4-274C-59AF-8EAB-54E707781929

**Comment by jared53** [comment]
@Hexagon12 I am sorry I'm having a heck of a time finding my log file with mac sierra. I have been looking for almost an hour but they don't try to make it easy to access ANY files smh. I will try to look for it more and will let you know if i find it. Sorry again

Hardware Overview:

Model Name:	MacBook Pro
Model Identifier:	MacBookPro14,1
Processor Name:	Intel Core i5
Processor Speed:	2.3 GHz
Number of Processors:	1
Total Number of Cores:	2
L2 Cache (per Core):	256 KB
L3 Cache:	4 MB
Memory:	8 GB
Boot ROM Version:	MBP141.0173.B00
SMC Version (system):	2.43f6
Serial Number (system):	C02V2B41HV27
Hardware UUID:	BF93C4C4-274C-59AF-8EAB-54E707781929

**Comment by keeano92** [comment]
@jared53  You can find everything you need to pull your system specs in great detail by simply typing
`system_profiler` into the terminal.

Find more details here: https://www.itechlounge.net/2013/09/mac-osx-get-full-system-information-through-terminal/

**Comment by Dragios** [comment]
Possible candidate PR #5230 that can fix your issue. Based on the Macbook specs given I can confirm with 100% certainty that this model uses the integrated Intel Iris Plus Graphics 640 graphics.

**Comment by SleepingSnakezzz** [comment]
This issue does not occur on Windows, Linux or Android. MacOS OpenGL is no longer supported, so this is no longer relevant.
