### ISSUE TITLE
Graphic issues in pokemon ultra sun after Nightly update

### ISSUE THREAD

**Issue by Lunarhawk** [citra-emu/citra#3754]
Using the latest Citra Nightly version, 691, introduced some graphical glitches that weren't there before in 689. On closeups such as npcs talking in pokemon pelago or the pokemon in refresh mode there's now occasional flickering on parts of he models. I've also had a black rectangle flash in the middle of the bottom screen when in Refresh. Too fast to really get a picture of

Current graphics options turned on are:
Limit Speed (100%) 
Enable Hardware Renderer
3x Native
Enable Hardware Shader
Accurate Geometry Shader
Enable Shader JIT

System Specs are a 960 4gb, i5-6600k, and Windows 10

**Comment by Hexagon12** [comment]
What is your Nvidia's driver version?

**Comment by Lunarhawk** [comment]
Current driver, 397.64

**Comment by Dragios** [comment]
Is this still an issue?
