### ISSUE TITLE
Please eliminate the need for dumping from 3DS.

### ISSUE THREAD

**Issue by Nikorasu95** [citra-emu/citra#3760]
I have a 3DS and the games I want to play on Citra I own. If I already own the fuc**** game it's not piracy if I download said copy from a program such as WII USB Helper now is it? Because I already own the game it's not piracy if I download the game to play on Citra. How before you go bashing me on that "oh oh it's still piracy" hear me out. Not everyone has a hacked 3DS. I have a New Nintendo 3DS on the latest firmware and I know it's near impossible to get homebrew on it. Also, a lot of people don't want to hassle with hacking their 3DS. My biggest problem with Citra is the need for 3DS system files such as mii data and shared font. I already have the shared font, but now I need mii data. I'm trying to play "Breavly Default" a game I legally own on, but I haven't found a way to get the mii data. Any suggestions? Please help me out.

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Theres already an issue open for this, so closing as a duplicate https://github.com/citra-emu/citra/issues/2636

**Comment by Nikorasu95** [comment]
This is a issue, and a big one at that! You didn't have to be an as*hole and close the thread.

**Comment by jroweboy** [comment]
This is not a support forum. Its clear that you aren't planning on contributing to the project in anyway
