### ISSUE TITLE
Need mii data, please help!

### ISSUE THREAD

**Issue by Nikorasu95** [citra-emu/citra#3761]
I have a 3DS and the games I want to play on Citra I own. If I already own the fuc**** game it's not piracy if I download said copy from a program such as WII USB Helper now is it? Because I already own the game it's not piracy if I download the game to play on Citra. How before you go bashing me on that "oh oh it's still piracy" hear me out. Not everyone has a hacked 3DS. I have a New Nintendo 3DS on the latest firmware and I know it's near impossible to get homebrew on it. Also, a lot of people don't want to hassle with hacking their 3DS. My biggest problem with Citra is the need for 3DS system files such as mii data and shared font. I already have the shared font, but now I need mii data. I'm trying to play "Breavly Default" a game I legally own on, but I haven't found a way to get the mii data. Any suggestions? Please help me out.

**Comment by jroweboy** [comment]
You already opened an issue for this. If you insist on spamming the issue tracker again, you will get banned.

**Comment by Nikorasu95** [comment]
That's cool because i'll just create multiple accounts and protest my issue!

**Comment by einstein95** [comment]
Because that'd definitely get the developers to listen to you and not just ignore the issue and think that only whiny users want said feature
