### ISSUE TITLE
Retroarch Core crashes retroarch on exit

### ISSUE THREAD

**Issue by budtz** [citra-emu/citra#3762]
There was a new version of the Core that now crashes on exit.

Also majuras mask wont load and there is no text in metroid seamus returns.

Otter than that is a grelt Core.

**Comment by jroweboy** [comment]
The retroarch core is not an officially maintained core. As such you'll need to open an issue there instead: https://github.com/libretro/citra/

**Comment by budtz** [comment]
Thx
