### ISSUE TITLE
System camera is mirrored

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#3763]
With the system camera, the image is mirrored. This is shown in the preview and game. Using Ultra Moon as an example. Tested with 80bfd87.

![citra-qt_2018-05-19_20-01-21](https://user-images.githubusercontent.com/17358613/40274230-3814b240-5ba8-11e8-936a-370d8bbbc103.png)

[Log](https://pastebin.com/rsGRbw8r)

**Comment by zhaowenlan1779** [comment]
I'm already working on a fix.
I will add an 'Flip Image' option, so that the users can configure it themselves.
