### ISSUE TITLE
Suggestion : emulation window background in black (or other color)

### ISSUE THREAD

**Issue by knightofnet** [citra-emu/citra#3766]
Hello. I've been following and using Citra for quite some time now and it's clear that the emulator is getting better and better with each release. I always had a little suggestion, just for visual comfort: In the emulation window, wouldn't it be more comfortable to have a black background instead of a white background? This background (white) is particularly visible when the two screens are side-by-side.

It might be possible to change the color or put it in black/white with a small checkbox.

Translated with www.DeepL.com/Translator

**Comment by BreadFish64** [comment]
The default background color was changed to black a long time ago, you can change the color in the config file

**Comment by chris062689** [comment]
The black background was set years ago.
The issue is we currently do not have a system to automatically update the config file from the default value, so if you've been using Citra for a while, you'll still see the old value.

If you clear your config file, you should see the black background.
