### ISSUE TITLE
AMD pre-gcn issues with hardware shader emulation

### ISSUE THREAD

**Issue by RoySullivan** [citra-emu/citra#3767]
**Note**: i don't know if that happens on +gcn cards hence the title.

Firstly i wanted to report the performance issues while
using hardware shader emulation, because that's partly 
the reason (purpose) to use such feature (i'm assuming).
but graphical issues correlate with the previous mentioned issues.

Also note that these fps and frametime measures are taken from
the same screenshots below and using native resolution.

Note: these performance issues occur ever since hardware shader emulation
(canary 408) was introduced.

**OS**: Windows 7 SP1
**CPU**: Phenom II X4 810
**GPU**: XFX HD 6750 1GB
**Driver Version**: 16.2.1 Crimson
**citra-canary**(502): Head-f69feeb

**The Legend of Zelda: A Link Between Worlds:**
Enable Hardware Shader: Checked
_FPS: ~23 Frametime:~42.45_

Enable Hardware Shader:Unchecked
_FPS: ~25 Frametime:~40.00_

**Note:** although 'Accurate Multiplication' fixes a small portion of it.

Enable Hardware Shader: Unchecked
![enable hardware shader - unchecked](https://user-images.githubusercontent.com/9091067/40282589-82e75dbc-5c26-11e8-87e9-21662319497d.png)

Enable Hardware Shader: Checked
![enable hardware shader - checked](https://user-images.githubusercontent.com/9091067/40282628-329a6538-5c27-11e8-95cd-c69731f7c6d6.png)

Enable Hardware Shader & Accurate Multiplication: Checked
![enable hardware shader - checked - accurate multiplication - checked](https://user-images.githubusercontent.com/9091067/40282638-3e321134-5c27-11e8-8e53-82f74dba8760.png)

**The Legend of Zelda: Majora's Mask 3D:**
Enable Hardware Shader: Checked
Accurate Geometry Shader: Checked
Accurate Multiplcation: Checked
_FPS: ~21 Frametime:~23.28_

Enable Hardware Shader:Unchecked
_FPS: ~24 Frametime:~20.50_

Enable Hardware Shader: Unchecked
![enable hardware shader - unchecked](https://user-images.githubusercontent.com/9091067/40282750-af50819c-5c28-11e8-9aca-e99bff5fb2e5.png)

Enable Hardware Shader: Checked
![enable hardware shader - checked - accurate multiplication checked](https://user-images.githubusercontent.com/9091067/40282747-abf03e70-5c28-11e8-896c-9dc62e4220ab.png)

Enable Hardware Shader & Accurate Multiplication: Checked
![enable hardware shader - checked](https://user-images.githubusercontent.com/9091067/40282748-ad6e94cc-5c28-11e8-849c-5bb0fb92f5f3.png)

**The Legend of Zelda: Ocarina of Time 3D:**
Enable Hardware Shader:Checked
Accurate Geometry Shader:Checked
Accurate Multiplcation:checked
_FPS: ~23 Frametime:~21.63_

Enable Hardware Shader:Unchecked
_FPS: ~25 Frametime:~20.30_

**Note:** both 'Enable Hardware Shader: unchecked' and 'Accurate Multiplication' 
cause map texture to disappear.

Enable Hardware Shader: Unchecked
![enable hardware shader - unchecked](https://user-images.githubusercontent.com/9091067/40282792-37088152-5c29-11e8-8bfc-4600439fd781.png)

Enable Hardware Shader: Checked
![enable hardware shader - checked](https://user-images.githubusercontent.com/9091067/40282791-341e80a4-5c29-11e8-948f-79555e3c16ab.png)

Enable Hardware Shader  & Accurate Multiplication: Checked
![enable hardware shader - checked accurate multiplcation checked](https://user-images.githubusercontent.com/9091067/40282790-33ce1380-5c29-11e8-9acf-988461518d79.png)

**Super Smash Bros:**
Enable Hardware Shader:Checked
Accurate Geometry Shader:Either
Accurate Multiplcation:Either
_FPS: ~15 Frametime:~70.00_

Enable Hardware Shader:Unchecked
_FPS: ~26 Frametime:~38.00_

**Note:** small difference (i didn't pause)

Enable Hardware Shader: Unchecked
![enable hardware shader - unchecked](https://user-images.githubusercontent.com/9091067/40283271-80fb05ee-5c30-11e8-940a-cbbf69acfc9e.png)

Enable Hardware Shader: Checked
![enable hardware shader - checked](https://user-images.githubusercontent.com/9091067/40283266-6b21fe8a-5c30-11e8-9672-77867253cc44.png)

**Poochy & Yoshi's Woolly World:**
Enable Hardware Shader:Checked
Accurate Geometry Shader:Either
Accurate Multiplcation:Either
_FPS: ~14 Frametime:~35.16_

Enable Hardware Shader:Unchecked
_FPS: ~28 Frametime:~17.70_

**Picross e6:**
Enable Hardware Shader:Checked
Accurate Geometry Shader:Either
Accurate Multiplcation:Either
_FPS: ~16 Frametime:~61.50_

Enable Hardware Shader:Unchecked
_FPS: ~32 Frametime:~32.00_

**Note:** this is the only picross game presenting this issue
but other picross games do run faster with Enable Hardware Shader:Unchecked.

**Ever Oasis:**
Enable Hardware Shader:Checked
Accurate Geometry Shader:Either
Accurate Multiplication:Either
_FPS: ~19 Frametime:~25.30_

Enable Hardware Shader:Unchecked
_FPS: ~26 Frametime:~19.00_

Enable Hardware Shader: Unchecked
![enable hardware shader - unchecked](https://user-images.githubusercontent.com/9091067/40282853-efdebf5c-5c29-11e8-948f-22138c331001.png)

Enable Hardware Shader: Checked
![enable hardware shader - checked](https://user-images.githubusercontent.com/9091067/40282850-ecf2ec3c-5c29-11e8-89aa-895e0cf4b663.png)

**Yoshi's New Island:**
Enable Hardware Shader:Checked
Accurate Geometry Shader:Either
Accurate Multiplcation:Either
_FPS: ~48 Frametime:~20.40_

Enable Hardware Shader:Unchecked
_FPS: ~52 Frametime:~18.80_

**Logs:**
Ever Oasis: [citra_log.txt](https://github.com/citra-emu/citra/files/2020766/citra_log.txt)
Majora's Mask: [citra_log.txt](https://github.com/citra-emu/citra/files/2020767/citra_log.txt)
Ocarina of Time: [citra_log.txt](https://github.com/citra-emu/citra/files/2020768/citra_log.txt)
Super Smash Bros: [citra_log.txt](https://github.com/citra-emu/citra/files/2020769/citra_log.txt)
A Link Between Worlds: [citra_log.txt](https://github.com/citra-emu/citra/files/2020770/citra_log.txt)
Yoshi's Woolly World:  [citra_log.txt](https://github.com/citra-emu/citra/files/2020771/citra_log.txt)

**Comment by urdaneta09** [comment]
Yeah some games run more slow with gpu mode in AMD cards (cry) or dont give all the speed boost like in a nvidia card... yet (let me dream) 

add to you list Kingdom Hearts Dream Drop Distance run more slow in gpu mode in a AMD card

And in Fire Emblem there are some gliches only in AMD i test in a Nvidia card and are fine
![imagen1ds](https://user-images.githubusercontent.com/25537618/40286066-b4662224-5c71-11e8-8370-bb21720e383c.jpg)

**Comment by CesarAxe** [comment]
All this is a problem of the AMD drivers and OpenGL. In other emulators there are also losses in performance, even if you have an RX Vega card.

**Comment by jroweboy** [comment]
For people with AMD cards, can you test these same games against a build of this PR https://github.com/citra-emu/citra/pull/3759 You can find a link to the build in the "Show All Checks -> Appveyor -> Mingw environment -> Artifacts -> update.zip" (heres the direct link for now, but this will likely get out of date as soon as changes are made to that PR https://ci.appveyor.com/api/buildjobs/8i1badkxr4l6i2m9/artifacts/citra-windows-mingw-20180520-cb0d1ed.zip )

Please report your findings on that PR in a similar manner to the original post in this issue (aka mention your hardware, and comparison of FPS of that build vs nightly) 

We suspect that those changes will bring a lot of the performance benefits and could really use some testing before we put it on canary for the general public to test. Thanks!

**Comment by MojoJojoDojo** [comment]
There are still many bugs and problems with graphics.
and its still slower.
