### ISSUE TITLE
Hardware shaders produce garbled rendering on macOS / Intel

### ISSUE THREAD

**Issue by kemenaran** [citra-emu/citra#3772]
On macOS with Hardware-shaders enabled, for all games, only garbled triangles are visible.

- Citra version : 45aa9509
- Games : any game
- macOS 10.12.6
- Intel Iris 5100
- Hardware-shaders: enabled

_Workarounds: the rendering works properly with Hardware-shaders disabled._

_It also works on Windows (on the same machine) with Hardware-shaders enabled._

<img width="401" alt="capture d ecran 2018-05-23 a 15 15 12" src="https://user-images.githubusercontent.com/179923/40427107-0c7451fc-5e9d-11e8-9cdc-bae8448c6417.png">

![ezgif-4-fec5eebb57](https://user-images.githubusercontent.com/179923/40427170-3c22bf88-5e9d-11e8-82ab-e8347746daa8.gif)

**Comment by SmiVan** [comment]
This issue is no longer present on macOS as of 5727e1b43d85aee137174375c41d35e44bc8b06f, at least for Tomodachi Life, can't check other games.

**Comment by kemenaran** [comment]
I just checked with A Link Between Worlds, and the issue is still the same on my machine (Macbook Pro, macOS 10.14.5, Intel Iris 5000).

**Comment by Subv** [comment]
This issue is caused by the `ARB_separate_shader_objects` extension not actually working properly on Intel macs for some reason, not even the AMD workaround seems to fix it. Disabling the usage of the extension fixes the issue.

**Comment by FearlessTobi** [comment]
Can we just check the GLString and OS then and disable it? @Subv

**Comment by SleepingSnakezzz** [comment]
Citra no longer supports OpenGL on MacOS builds.
