### ISSUE TITLE
pls check the spec of my pc

### ISSUE THREAD

**Issue by divyansh91** [citra-emu/citra#3775]

**Comment by divyansh91** [comment]
![captujre](https://user-images.githubusercontent.com/39583357/40471828-71f732fc-5f55-11e8-971c-c17c877135d3.PNG)
pls check why the citrs not supporting it allways show this when i start any game 
![captudre](https://user-images.githubusercontent.com/39583357/40471893-a1deb0da-5f55-11e8-9cff-e2efd9ba02f3.PNG)

**Comment by einstein95** [comment]
It's saying that you need to install WIndows ME

**Comment by j-selby** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

---

Requesting issue to be closed.
