### ISSUE TITLE
Small visual glitch in Pokémon OR/AS using Internal Resolution 3x

### ISSUE THREAD

**Issue by LOuroboros** [citra-emu/citra#3785]
So, I just noticed this and I thought that I should report it just in case.
If I raise the Internal Resolution to 3x and play on Fullscreen, there's this black line showing up sometimes in the textboxes of Pokémon Omega Ruby.
![citra-qt_2018-05-27_13-22-42](https://user-images.githubusercontent.com/4485172/40588360-b8e92be8-61b2-11e8-956f-bb52b4953e37.png)

Citra Version: Citra Canary 514 _(7989b29)_ MinGW.
CPU & GPU: Intel Celeron N2840 and its iGPU
OS: Windows 8.1 x64

**Comment by legoj15** [comment]
I don't think this is inherently a glitch, but just a side effect of running the game at a higher resolution.
