### ISSUE TITLE
Unable to play properly after Updating

### ISSUE THREAD

**Issue by Omega7343** [citra-emu/citra#3792]
Hi there,

I have a massive problem regarding Citra at the moment. I recently updated to the latest Citra build (released 28 May I think), and after doing so, I found that I was not able to play games on Citra properly after the update. Both the Touch Screen and the Upper Screen are black, save for some graphical glitches. I can still hear the music of every game. This is extremely weird as I was able to play games perfectly before this update. I tried using older versions, but for some reason, the same problem occurs. Anybody able to help?

Thanks.

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Requesting to close.
