### ISSUE TITLE
Gundam Try Age SP: can’t scan QR code (camera doesn’t work), and freeze after exit this mode 

### ISSUE THREAD

**Issue by xxx169** [citra-emu/citra#3794]
Citra Version: Nightly | HEAD-65f5bc7

Operating System: Win 10
CPU: i7 6700
GPU: GTX 960M
Game: Gundam Try Age SP (Japan)

Issue:
The camera will be used in QR code mode (can use the system cam qt or select image. both front and back cam.), but it not working. The image and cam does’t show up ingame at all.
And the game is freeze after exit the QR code mode (black screen).

[https://community.citra-emu.org/uploads/default/original/2X/8/8fd3fcb571f286ca9510b4c6459cdfaeb36aaf68.jpg](url)

[https://community.citra-emu.org/uploads/default/original/2X/2/2b874a619fca37460333774caaa8d8e7d76d1bb4.jpg](url)
preview works fine here. both image and system cam (qt)
and i did it in pokemon games too w/o any problem.
but it is just not showing up in this game.

log:

`[ 0.738561] Frontend citra_qt/main.cpp:GMainWindow:141: Citra Version: Nightly | HEAD-65f5bc7`
`[ 0.772034] Frontend citra_qt/main.cpp:CheckForUpdates:508: Update check started`
`[ 4.295575] Frontend citra_qt/main.cpp:OnUpdateFound:521: No updates found`
`[ 6.167375] Frontend citra_qt/main.cpp:BootGame:647: Citra starting…`
`[ 6.865610] Service.FS core/file_sys/ncch_container.cpp:LoadOverrides:244: Loaded NCCH D:\Citra\nightly-mingw/user/nand/00000000000000000000000000000000/title/0004009b/00010202/content/00000000.app is tainted, application behavior may not be as expected!`
`[ 6.867215] Service.FS core/file_sys/ncch_container.cpp:LoadOverrides:244: Loaded NCCH D:\Citra\nightly-mingw/user/nand/00000000000000000000000000000000/title/0004009b/00010402/content/00000000.app is tainted, application behavior may not be as expected!`
`[ 6.868527] Service.FS core/file_sys/ncch_container.cpp:LoadOverrides:244: Loaded NCCH D:\Citra\nightly-mingw/user/nand/00000000000000000000000000000000/title/000400db/00010302/content/00000000.app is tainted, application behavior may not be as expected!`
`[ 6.890052] Render.OpenGL video_core/renderer_opengl/renderer_opengl.cpp:Init:488: GL_VERSION: 3.3.0 NVIDIA 397.93`
`[ 6.890056] Render.OpenGL video_core/renderer_opengl/renderer_opengl.cpp:Init:489: GL_VENDOR: NVIDIA Corporation`
`[ 6.890058] Render.OpenGL video_core/renderer_opengl/renderer_opengl.cpp:Init:490: GL_RENDERER: GeForce GTX 960M/PCIe/SSE2`
`[ 6.918069] Loader core/loader/ncch.cpp:Load:159: Program ID: 000400000012FB00`
`[ 6.918496] Service.FS core/file_sys/ncch_container.cpp:OpenFile:113: Failed to open D:\Citra\nightly-mingw/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/0012fb00/content/00000000.app`
`[ 6.954272] Loader core/hle/kernel/process.cpp:ParseKernelCaps:114: ExHeader kernel version: 2.35`
`[ 6.956211] Service.CFG core/hle/service/cfg/cfg.cpp:SetPreferredRegionCode:602: Preferred region code set to 0`
`[ 6.989111] Service.SRV core/hle/service/sm/srv.cpp:RegisterClient:48: (STUBBED) called`
`[ 7.201207] Service.SRV core/hle/service/sm/srv.cpp:EnableNotification:70: (STUBBED) called`
`[ 7.203812] Service.APT core/hle/service/apt/apt.cpp:GetLockHandle:255: (STUBBED) called applet_attributes=0X00000000`
`[ 7.209780] Service.NDM core/hle/service/ndm/ndm.cpp:OverrideDefaultDaemons:207: (STUBBED) default_daemon_bit_mask=0x0000000F`
`[ 7.211117] Service.NDM core/hle/service/ndm/ndm.cpp:SuspendDaemons:92: (STUBBED) daemon_bit_mask=0x00000009`
`[ 7.665211] Service.APT core/hle/service/apt/apt.cpp:NotifyToWait:234: (STUBBED) app_id=768`
`[ 7.669052] Service.APT core/hle/service/apt/apt.cpp:AppletUtility:455: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001`
`[ 7.669541] Service.APT core/hle/service/apt/apt.cpp:AppletUtility:455: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001`
`[ 7.670603] Service.APT core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:471: (STUBBED) called, cpu_percent=25, value=1`
`[ 7.671397] Service.FS core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:540: (STUBBED) called, version: 0x050203C8`
`[ 7.844627] Service.GSP core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:665: called flag=00000000 process=10 thread_id=0`
`[ 7.979879] Service.DSP core/hle/service/dsp_dsp.cpp:LoadComponent:150: Firmware hash: 0xe00a211577bc944e`
`[ 7.979886] Service.DSP core/hle/service/dsp_dsp.cpp:LoadComponent:154: Structures hash: 0x228655de1258d999`
`[ 7.979888] Service.DSP core/hle/service/dsp_dsp.cpp:LoadComponent:159: (STUBBED) called size=0xC288, prog_mask=0x000000FF, data_mask=0x000E00FF, buffer=0x0065F060`
`[ 7.980992] Service.DSP core/hle/service/dsp_dsp.cpp:RegisterInterruptEvents:251: Registered type=2, pipe=2, event_handle=0x000F002E`
`[ 7.984247] Service.DSP core/hle/service/dsp_dsp.cpp:GetSemaphoreEventHandle:176: (STUBBED) called`
`[ 7.984795] Service.DSP core/hle/service/dsp_dsp.cpp:SetSemaphoreMask:473: (STUBBED) called mask=0x00002000`
`[ 7.985371] Audio.DSP audio_core/hle/hle.cpp:PipeWrite:149: Application has requested initialization of DSP hardware`
`[ 7.985592] Service.DSP core/hle/service/dsp_dsp.cpp:SetSemaphore:274: (STUBBED) called`
`[ 7.987658] Service.DSP core/hle/service/dsp_dsp.cpp:SetSemaphore:274: (STUBBED) called`
`[ 8.002588] Kernel.SVC core/hle/kernel/svc.cpp:CreateThread:750: Newly created thread must run in the SysCore (Core1), unimplemented.`
`[ 21.319468] Service core/hle/service/service.cpp:ReportUnimplementedFunction:163: unknown / unimplemented function ‘ReplySleepQuery’: port=‘APT:U’ cmd_buf={[0]=0x3e0080, [1]=0x300, [2]=0x0}`
`[ 21.353300] Service.APT core/hle/service/apt/apt.cpp:AppletUtility:455: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001`
`[ 22.863503] Service.Y2R core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:198: (STUBBED) called`
`[ 26.442758] Service.FS core/hle/service/fs/archive.cpp:OpenLinkFile:231: (STUBBED) File command OpenLinkFile Path: [Binary: 000000000000000000000000]`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread`
`[ 80.317385] Service.CAM core/hle/service/cam/cam.cpp:SetTransferBytes:460: (STUBBED)called, port_select=1, bytes=2560, width=512, height=240`
`[ 80.317690] Service.CAM core/hle/service/cam/cam.cpp:GetSuitableY2rStandardCoefficient:963: (STUBBED) called`
`[ 80.321082] Service core/hle/service/service.cpp:ReportUnimplementedFunction:163: unknown / unimplemented function ‘SetNoiseFilter’: port=‘cam:u’ cmd_buf={[0]=0x280080, [1]=0x1, [2]=0x1}`
`[ 80.321897] Service core/hle/service/service.cpp:ReportUnimplementedFunction:163: unknown / unimplemented function ‘SetAutoExposure’: port=‘cam:u’ cmd_buf={[0]=0x190080, [1]=0x1, [2]=0x1}`
`[ 80.324177] Service core/hle/service/service.cpp:ReportUnimplementedFunction:163: unknown / unimplemented function ‘SetAutoWhiteBalance’: port=‘cam:u’ cmd_buf={[0]=0x1b0080, [1]=0x1, [2]=0x1}`
`[ 80.328835] Service.Y2R core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:198: (STUBBED) called`
`[ 80.330221] Service.CAM core/hle/service/cam/cam.cpp:GetBufferErrorInterruptEvent:328: (STUBBED) called, port_select=1`
`[ 80.330842] Service.CAM core/hle/service/cam/cam.cpp:GetVsyncInterruptEvent:310: (STUBBED) called, port_select=1`
`[ 80.336397] Service.CAM core/hle/service/cam/cam.cpp:ClearBuffer:292: (STUBBED) called, port_select=1`

**Comment by adityaruplaha** [comment]
One small thing, can you enclose the log in backticks (`)? It's damn hard to read.
