### ISSUE TITLE
Citra Emulador Drive Nvidia beta397.96

### ISSUE THREAD

**Issue by NekokoTime** [citra-emu/citra#3802]
Latest driver version of NVIDIA Citra Emulator is giving black screen start gaming or white screens without shows images of games some solution logs.txt images below problem reported?
![anotacao 3](https://user-images.githubusercontent.com/38867013/40837898-4ba55232-6572-11e8-9421-e21b23b824b9.png)
![anotacao 4](https://user-images.githubusercontent.com/38867013/40837899-4be9813c-6572-11e8-8db5-21c6e9ca5f5e.png)
![anotacao 5](https://user-images.githubusercontent.com/38867013/40837900-4c30b890-6572-11e8-814a-7e1a96a82908.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/2062443/citra_log.txt)

**Comment by wwylele** [comment]
Does the latest canary have the same issue?

**Comment by Hexagon12** [comment]
@wwylele This is the latest Canary in the pictures.
@NekokoTime This issue isn't related to Citra. Downgrade your driver to the last stable version and everything should work fine.

Requesting to close.

**Comment by NekokoTime** [comment]
@Hexagon12 Oky plus problem is in Canary and occurs in NVIDIA stable drive.

**Comment by NekokoTime** [comment]
@wwylele  latest canary  Oky plus problem is in Canary and occurs in NVIDIA stable drive.
