### ISSUE TITLE
Bloodstained Curse of the Moon crashes Citra

### ISSUE THREAD

**Issue by Tutankhamun8080** [citra-emu/citra#3814]
# Citra summary
- Canary Build - d69147b
- Nightly Build - 50def5a

# Issues
- Bloodstained COTM crashes Citra

# Test environment summary
- Tested by: Tutankhamun8080
- OS: Windows 10 Pro 
- CPU: Intel core i7 4930mx @3.1 GHz
- GPU: Nvidia GTX 880m x2 VRAM: 8gb x2 in SLI
- RAM: Dell 16gb DDR3-1600 MHz SODIMM

# Canary's Log
  - For crashes, a backtrace.
[citra_log.txt](https://github.com/citra-emu/citra/files/2070510/citra_log.txt)

# Nightly's Log
 - For crashes, a backtrace.
[citra_log.txt](https://github.com/citra-emu/citra/files/2070537/citra_log.txt)

**Comment by Leo626** [comment]
This happens with the latest Nightly?

**Comment by Tutankhamun8080** [comment]
I've got to test the nightly build.

**Comment by Tutankhamun8080** [comment]
Same issue with the latest Nightly build Nightly Build - 50def5a

**Comment by Tutankhamun8080** [comment]
I tried creating a dummy SystemData.bin & a 00000000.app files in the location listed in the Log but, it still crashes. I went back & deleted those files I created.

**Comment by Tutankhamun8080** [comment]
Here is the Log for Canary after creating the dummy SystemData.bin & a 00000000.app files.
[citra_log.txt](https://github.com/citra-emu/citra/files/2070582/citra_log.txt)

**Comment by mailwl** [comment]
looks like gdbstub is completely broken? i tryed to debug this game with IDA 7.0 without success.
may anyone from active developers check this? @wwylele maybe?

**Comment by benderscruffy** [comment]
using the latest nightly
still crashes out nearly straight away
Debug <Critical> core/arm/dynarmic/arm_dynarmic.cpp:operator():149: Assertion Failed!
ExceptionRaised(exception = 1, pc = 081A1AA4, code = 08000000)
[citra_log1.zip](https://github.com/citra-emu/citra/files/2729127/citra_log1.zip)

it goes in game when you use the save provide by mafiffeder
here is the log
![blood](https://user-images.githubusercontent.com/2696404/50720032-6da8ab80-10e0-11e9-8e2a-22ab7b423811.PNG)
[citra_log.zip](https://github.com/citra-emu/citra/files/2729125/citra_log.zip)

**Comment by benderscruffy** [comment]
goes ingame now no problems 
can be closed
