### ISSUE TITLE
Suggestion: Allow customizing save file directory

### ISSUE THREAD

**Issue by notmutiny** [citra-emu/citra#3818]
<-- not an emulator issue, merely a suggestion and nowhere to put it -->

Other emulators (such as Dolphin) allow you to choose a custom directory for game saves. This works well for cases like Dropbox that syncs a folder in %AppData% between any devices logged in with that Dropbox account. There are many other uses for custom save directories but that is my usage. This can currently be fixed by using symbolic links but the feature would be a nice addition regardless.

**Comment by wfowler1** [comment]
I use symlinks to sync my save to Google Drive. It'd be much more convenient if I could just point Citra to the folder.

**Comment by ToppestOfDogs** [comment]
I'm still waiting on this too.

**Comment by jroweboy** [comment]
Note: this has already been added to yuzu and the code is pretty much the same https://github.com/yuzu-emu/yuzu/pull/1223 @FearlessTobi if you were looking for something to port 👍
