### ISSUE TITLE
Error that caused Citra to force-close (Game : FE Fates Special Edition)

### ISSUE THREAD

**Issue by tincan13** [citra-emu/citra#3833]
Greetings, dev team.
I've been using Citra since I've first found it about 2 to 3 years ago, and I must say thank you awesome developers for doing so!

Unfortunately I've come across some problems that I can say I didn't encounter in the last version of Citra. The problem involved something about NG bad or something, and that it didn't do anything at first, or so I thought, before the Windows deployed a message in regards of unexpected error that forced the Citra to close itself. I have enclosed the warning message over here. The game is Fire Emblem Fates Special Edition.
![complains](https://user-images.githubusercontent.com/40244303/41366796-651f9700-6f67-11e8-993a-a23cc9c58fe9.png)

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Requesting to close.
