### ISSUE TITLE
[Rune Factory 4] Black Screen Issue on Mac

### ISSUE THREAD

**Issue by lanlan93x** [citra-emu/citra#3835]
**ISSUE**

Game screen is not working. Only black screen with working audio when the emulation is playing. Tried several cases to modify the graphics so that the black screen problem is solved.
CASE 1: Default (Enable Hardware Renderer, Hardware Shader & Shader JIT)
CASE 2: Disable Hardware Shader
CASE 3: Disable Hardware Shader & Shader JIT
CASE 4: Total Disable Renderer

CASE 1

![screen shot 2018-06-16 at 5 48 24 pm](https://user-images.githubusercontent.com/37877466/41497778-fe36daba-718e-11e8-9e18-0e402bbcf660.png)
_Case 1 graphic setting. Enabled Hardware Renderer, Hardware Shader & Shader JIT_

![screen shot 2018-06-16 at 5 48 43 pm](https://user-images.githubusercontent.com/37877466/41497785-2d0c5568-718f-11e8-8589-92c215887597.png)
_Case 1 screen result. Total darkness, but the audio works._

CASE 2

![screen shot 2018-06-16 at 5 49 13 pm](https://user-images.githubusercontent.com/37877466/41497791-494be95a-718f-11e8-9fc7-9abe1214c555.png)
_Case 2 graphic setting. Hardware Shader disabled._

![screen shot 2018-06-16 at 5 49 35 pm](https://user-images.githubusercontent.com/37877466/41497794-6efffdda-718f-11e8-9e3d-0128cb873d4c.png)
_Case 2 screen result 1. Working when showing/playing cinematic intro (I assume it's video file)._

![screen shot 2018-06-16 at 5 49 51 pm](https://user-images.githubusercontent.com/37877466/41497805-b5dd2d86-718f-11e8-9eb2-b802a1012eb3.png)
_Case 2 screen result 2. Working when showing 2D graphics on the bottom (right) screen, but fail at showing 3D graphics at the top (left) screen, which is the big part of the gameplay._

![screen shot 2018-06-16 at 5 50 01 pm](https://user-images.githubusercontent.com/37877466/41497808-c20c56d6-718f-11e8-8bdd-9ec5a2d6a6c5.png)
_Case 2 screen result 3. Fail at showing 3D graphics after pressing 'New Game' at the top (left) screen, and graphic went faulty (2 backgrounds overlapped) at bottom (right) screen._

CASE 3

![screen shot 2018-06-16 at 5 50 25 pm](https://user-images.githubusercontent.com/37877466/41497843-8022c5ba-7190-11e8-80f3-6b1f383213c1.png)
_Case 3 graphic setting. Hardware Shader & Shader JIT disabled._

![screen shot 2018-06-16 at 5 50 43 pm](https://user-images.githubusercontent.com/37877466/41497847-aa6e2c88-7190-11e8-883a-e5236e0e487b.png)
_Case 3 screen result. Same result as Case 2, along with the other screen results. Not much big difference here._

CASE 4

[screenshot not available]
_Case 4 graphic setting: Hardware Renderer, Hardware Shader and Shader JIT all disabled._

![screen shot 2018-06-16 at 5 51 20 pm](https://user-images.githubusercontent.com/37877466/41497860-edb80a9a-7190-11e8-92c7-94ba81359612.png)
_Case 4 screen result. Top (left) screen shown, but emulation stutters in such a way that the frame goes 1 frame per second. Audio also stutters. Video/GIF not available._

Note to Citra Team: Look, I am craving to play this game for a such long time to have this game works on my Macbook, since this is the only computer I have to play my favorite games. If you guys could make this work on Mac Sierra, I think you guys can guarantee a 'PERFECT' score for the game. I'm not sure the details of how the compatibility test works, but I believe in you guys. I hope I could contribute more to help you guys in solving this issue, but I don't have the programming knowledge like you do, maybe in another way. Please fix this, I will be expecting a new update soon. Thanks, you're the best!

**SYSTEM INFORMATION**

Operating System: Mac High Sierra Version 10.13.4
CPU: 2.3 GHz Intel Core i5
GPU: Intel HD Graphics 3000 512 MB
Citra Version (found in title bar): Nightly | HEAD cf9bfe0
Game: Rune Factory 4

**DIAGNOSTIC LOG**

[citra_log.txt](https://github.com/citra-emu/citra/files/2108042/citra_log.txt)

**Comment by MerryMage** [comment]
Am I correct in summarizing that you have to disable all three of hardware renderer, shader jit, and hardware shader for the game to work properly?

**Comment by lanlan93x** [comment]
Please refer Case 4, I have disabled all three of them, both screen and audio stutters, means it still doesn't work properly. None of these cases make it work.

**Comment by MerryMage** [comment]
> screen and audio stutters

But does it work properly other than the speed? It's expected that disabling hardware acceleration would slow things down.

**Comment by lanlan93x** [comment]
Understanding from what you are trying to point out here, then yes. Other than the speed, the screen works properly.

**Comment by SleepingSnakezzz** [comment]
Citra macOS builds with OpenGL are no longer supported.
