### ISSUE TITLE
unable to enter room in citra

### ISSUE THREAD

**Issue by irrelevantpanic** [citra-emu/citra#3836]
I play pokemon ultra sun on citra. Whenever I try to join a room in multiplayer, a message pops up saying connection to room lost try to reconnect and i am unable to join the room. I have tried joining room with different nicknames but its not working. This problem is happening in both nightly and canary.

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Requesting to close.
