### ISSUE TITLE
Nanatsu no taizai Unjust Sin

### ISSUE THREAD

**Issue by jlalopez** [citra-emu/citra#3841]
when you start the game, the emulator tells you that you need some files but they do not know they are also saying that you need a real 3DS

**Comment by jlalopez** [comment]
If someone could share these files or at least say where they are obtained, I have already visited several sites but they have the same problem.

**Comment by CaptV0rt3x** [comment]
@jlalopez , You need to dump these system files from ***your own 3DS***. You should dump these files along with the games ***you purchased***. You can find further instructions [here](https://github.com/citra-emu/citra/wiki). We at Citra condemn piracy and will not provide support for such users.
