### ISSUE TITLE
Mii Maker - Softlock when scanning QR Code

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#3897]
Commit: f9a89ff

Screenshot:
![screenshot](https://user-images.githubusercontent.com/22228082/42122296-38f420c4-7c05-11e8-9829-0c5a02ecdd37.PNG)

QR Code:
![hni_0002](https://user-images.githubusercontent.com/22228082/42122297-3ea910ec-7c05-11e8-822a-7d4804926fb2.png)

The QR Code was created by Citra.
I have the 0x31 key.

[Log](https://github.com/citra-emu/citra/files/2151490/citra_log.txt)

**Comment by zhaowenlan1779** [comment]
This seems to be fixed by #5116
