### ISSUE TITLE
Mii Maker - Softlock when trying to quit when scanning a QR Code

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#3903]
Commit: dd81e25

Screenshot:
![quit](https://user-images.githubusercontent.com/22228082/42127941-b36918e4-7c66-11e8-95b5-cc55f20d85d0.png)

[citra_log.txt](https://github.com/citra-emu/citra/files/2152080/citra_log.txt)

**Comment by zhaowenlan1779** [comment]
This seems to be fixed by #5116
