### ISSUE TITLE
Captain Toad: Treasure Tracker (Demo): Incorrect shadow intensity

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#3920]
Citra (master - fd5f71b):

![screenshot from 2018-07-07 12-11-34](https://user-images.githubusercontent.com/4592895/42409325-6a0dbff8-81e1-11e8-977e-bc8c62e0cefe.png)

3DS:

![top_0001](https://user-images.githubusercontent.com/4592895/42409317-47579bdc-81e1-11e8-8715-a453df0fbc54.png)

Tested on all kinds of graphics settings (sw/hw renderer/shader...), all produce the same incorrect result.

The shadow is rendered using shadow map method, without soft shadow involving. Shadow map is sampled in the fragment lighting unit, applied to the primary color. The lighting unit is likely where the error happens, but the root problem is still unclear.

----

Seriously with so many people playing this demo why hasn't anyone reported this.

**Comment by CHNBUILD** [comment]
The gap is so big that it will definitely affect the game experience (sorry, I'm translation software).

**Comment by benderscruffy** [comment]
still an issue in the latest canary and nightly

**Comment by benderscruffy** [comment]
using canary 2608
still is a problem
![Screenshot 2023-09-03 190120](https://github.com/citra-emu/citra/assets/2696404/f3e1d220-8c2f-41c1-8166-4b4e22092ebc)
this is how it is supposed to look (look at 2 minute mark)
https://www.youtube.com/watch?v=_94GJgRFt0E&list=PLloXenWtlGXpdSZ7sLzTHC-ROC87SDTry
