### ISSUE TITLE
Provide a homebrew to dump the required files for emulation

### ISSUE THREAD

**Issue by Subv** [citra-emu/citra#393]
As of the creation date of this issue, the required files are:
- [x] **sysdata**
  - [x] sysdata/shared_font.bin
- [ ] **syssavedata**
  - [ ] syssavedata/00010017/00000000/config (A placeholder file with some placeholder data is created automatically if this file is not found)
- [x] **savedatacheck**
  - [x] savedatacheck/000400db00010302.bin
  - [x] savedatacheck/0004009b00010202.bin
  - [x] savedatacheck/0004009b00010402.bin

A homebrew application should be provided in the 3dsutils repo to dump each of these files

**Comment by JayFoxRox** [comment]
What's the state on this in https://github.com/citra-emu/3dsutils?
Looks like we are still only missing 'syssavedata' until we can close this?

(What's contained in said files?)

**Comment by poutros** [comment]
@JayFoxRox I have openned an issue there but so far it has gotten no response.

**Comment by JayFoxRox** [comment]
@poutros I've seen it, next time someone comes to the IRC channel and asks how they can help, this is probably one of the things we should mention.

---

Also a heads up: I've started writing a parser for the shared-font (in C99 and also fixed [3dstools](https://github.com/ObsidianX/3dstools) by @ObsidianX - it's currently broken in various ways with the last PRs).
I've also started checking the legal issues (but didn't get very far) in the US and EU + I've tried to locate fonts we can use as replacement.
I intended to upload this already, but was too lazy. It will probably end up in a new repo called citra-emu/sysdata or something?

I've also started [reading about Miis](https://www.3dbrew.org/wiki/Mii). I might even write our own version of Mii Maker - at least provide a default Mii or some way to import Miis by QR code.

The config file is probably useless and we should just use some documentation to implement our own version properly once and for all.

The NG word list is probably not that important. It's probably enough to block a few simple, obvious, words such as `^neobot$` or `^cemu$` :stuck_out_tongue_winking_eye:

**Comment by poutros** [comment]
@JayFoxRox Well, a few days ago I finally got 3dsfuse to work and I have already extracted the config. I also dumped my nand's mii maker and all its save data just in case (pokémon rumble world wouldn't work without mii maker's save data).

**Comment by yuriks** [comment]
The config savegame can be dumped reasonably easily using GodMode9 these days, and afaik we don't have any way of dumping it from unprivileged userland anyway, so I'm gonna close this one as not an issue anymore.
