### ISSUE TITLE
Transitioning into battles looks different on Ultra Sun and Ultra Moon compared to 3DS.

### ISSUE THREAD

**Issue by Gityashr** [citra-emu/citra#3931]
To illustrate what I mean, 

GIF of a battle vs Trainer on 3DS copy of Ultra Moon: https://imgur.com/j78Fq3h
GIF of a battle vs Trainer on a ROM of Ultra Sun: https://imgur.com/wkDu7qO

I am using Canary version 630, and I use a laptop with an i5-4210U, 4GB RAM, NVIDIA GeForce 830M and a 1TB 5400RPM HDD. I also tried this on a laptop with an i5-5200U, 8GB RAM, NVIDIA GeForce 920M and the same HDD.

**Comment by Leo626** [comment]
Can you point exactly what is the difference you see?

**Comment by Gityashr** [comment]
At the end of the color explosion thingy that happens upon zooming in, on the 3DS it fades to white and then does some wipe to reveal the trainer. On Citra, it just cuts directly to the trainer. In the 3DS GIF I linked to, the effect happens from 0:04 to 0:01 seconds. In the Citra GIF, the interval is 0:02 to 0:01. I see a difference comparing the two.

I'm sorry if my comment didn't make sense, this was the best way I could put it.

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update

**Comment by GPUCode** [comment]
Does this still occur?
