### ISSUE TITLE
Hardware Shader problem on last driver Nvidia (Linux and Windows)

### ISSUE THREAD

**Issue by Illynir** [citra-emu/citra#3939]
OS: Linux Mint 19 Cinnamon
Nvidia GTX 1050 TI 4GO
i5 4670K 3,8 Ghz
8 Go of ram

On the latest Nvidia drivers (396.24/396.24.2) on Linux, Hardware shader no longer works on 75 percent of the games. Instead you get a black screen, but the sound always works. For example on Ocarina of Time, Majora's mask, etc..

Disabling the Hardware Shader setting makes the image work again. Hardware shader worked very well on the previous drivers: 390.XX.

There is nothing significant or informative in the logs and no particular error, it just doesn't work.

Tested all version of Citra and Citra canary of 400 to 625. None of them work anymore with Hardware shader.

Thread with the same problem on other user:
https://www.reddit.com/r/Citra/comments/8uvs71/black_screen_on_every_game_nvidia396_linux_mint/
https://community.citra-emu.org/t/enabling-hardware-shader-results-in-black-screen/29123
And many more.

**Comment by Illynir** [comment]
If you need further information or testing, please let me know. I managed to confirm the problem on other PCs with Nvidia and these same drivers.

**Comment by Illynir** [comment]
Tested with the latest Nvidia driver just released, the 396.24.10, same problem.

**Comment by K0bin** [comment]
Same thing happens on Windows on 398.58.

Games I tested:
- Ocarina of Time
- Super Mario 3D Land
- New Super Mario Bros 2

**Comment by Illynir** [comment]
I mention Windows in the title then, it doesn't surprise me because on Linux we usually have the drivers ahead of Windows. So it makes sense to find this problem now on Windows.

**Comment by Dragios** [comment]
This looks like the latest NVIDIA driver is buggy and should be reported to them instead.

**Comment by K0bin** [comment]
To be fair, 398.58 (or the Linux equivalent 396.24.10) is technically a [beta driver](https://developer.nvidia.com/vulkan-driver). 

I thought the changes in that driver compared to the latest stable one were limited to Vulkan though.

**Comment by Illynir** [comment]
There's a next gen recompiler shader for Vulkan too, the biggest piece. But anyway the problem is the same on the 396.45 which are official on Linux.

I also don't think it's a bug directly related to Nvidia because I don't have any problems anywhere else. CEMU, RPCS3, all the native games works normally.

After as said since I opened this issue, I am open to any discussion if further information or testing is needed. But as it is, Hardware Shader doesn't work with Nvidia anymore, either on Windows or Linux with recent drivers.

**Comment by K0bin** [comment]
The latest Windows stable driver 398.82 does indeed work fine so it probably comes down to driver bugs which Nvidia is hopefully gonna fix before the rest of the beta changes get pushed to the stable branch.

**Comment by Illynir** [comment]
The latest Linux stable driver 396.51 works fine also. Hopefully bugs related to the beta driver will not be included on the official drivers before debugguage then. 

I leave still open for the moment to see what it will give on the next official driver but if it is still good I will close this issue.

**Comment by indivisible** [comment]
I can confirm that the bug is present on the 396.54.2 Linux drivers.

**Comment by Subv** [comment]
Is this still an issue today?

**Comment by Illynir** [comment]
No. It's good now, Forgot about that issue, I'm closing.
