### ISSUE TITLE
Cut the Rope: Triple Treat ‒ Star not rendered correctly with Hardware Shader

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#3940]
Thought this issue will be fixed somehow after #3499 merged but til now the issue still remain.
The star should be rendered yellow as shown on the left table.
Nothing useful in full [log](https://pastebin.com/3w3W07bT)

| Hardware Shader [Off] | Hardware Shader [On] |
| ------------- | ------------- |
| ![Normal](https://user-images.githubusercontent.com/18496868/42729966-11cb509e-881c-11e8-9e69-59e84a1fdfd2.png) | ![Glitched](https://user-images.githubusercontent.com/18496868/42729959-e84f20e2-881b-11e8-82bd-a0f17a7d1555.png) |

*GPU: NVIDIA GTX 1050 Ti*

**Comment by Dragios** [comment]
This is what it look like with *Accurate Multiplication* disabled on the same main menu where the star is spinning. Not directly related but I mention it anyway.
![Accurate Multiplication Off](https://user-images.githubusercontent.com/18496868/42730135-dce0781a-881f-11e8-89e7-74c8d81bf9b9.gif)

**Comment by benderscruffy** [comment]
it is still an issue

**Comment by Z3USI0TA** [comment]
Hi. please! One question.

![42729959-e84f20e2-881b-11e8-82bd-a0f17a7d1555](https://user-images.githubusercontent.com/57224781/86813316-60160e00-c056-11ea-8967-54994ef64d0d.png)
![42729966-11cb509e-881c-11e8-9e69-59e84a1fdfd2](https://user-images.githubusercontent.com/57224781/86813344-6efcc080-c056-11ea-9753-353a018f0de9.png)

I modifed code:
![001](https://user-images.githubusercontent.com/57224781/86813118-26dd9e00-c056-11ea-82e7-746b29bb7c6f.jpg)
![002](https://user-images.githubusercontent.com/57224781/86813237-48d72080-c056-11ea-9422-de294d4c04cb.jpg)
![003](https://user-images.githubusercontent.com/57224781/86813273-4ecd0180-c056-11ea-978c-24c3c2320d60.jpg)

The star exist in all cases but i belive that if enabled Hardware Shader is true then the star is not drawed white.
if enabled Hardware Shader is true what is code part draw the star?

**Comment by benderscruffy** [comment]
using the latest nightly it is still an issue
