### ISSUE TITLE
Yo-Kai Watch 2 Demo - Black Top Screen with Hardware Renderer

### ISSUE THREAD

**Issue by Leo626** [citra-emu/citra#3941]
The top screen is black during the title screen when Hardware Renderer is on. Tested on Nightly-800 ( 3799b16). Turning off Hardware Shader and/or Shader JIT does not affect this.

[citra_log.txt](https://github.com/citra-emu/citra/files/2196101/citra_log.txt)

Specs:
* Windows 10
* Intel Core i5-4670K
* NVIDIA GeForce GTX 970
* 8GB RAM

Hardware Renderer | Software Renderer
:-------------------------:|:-------------------------:
![citra-qt_2018-07-15_16-30-34](https://user-images.githubusercontent.com/17358613/42738176-62b39184-884d-11e8-8680-5f3c77efe72b.png)  |  ![citra-qt_2018-07-15_16-32-16](https://user-images.githubusercontent.com/17358613/42738177-6519d1cc-884d-11e8-8f7c-f43a42575d05.png)

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update

**Comment by benderscruffy** [comment]
@GPUCode 
using Canary 2615
works in software and vulkan
still missing in opengl

**Comment by GPUCode** [comment]
Hm it's interesting that it works in vulkan but not opengl
