### ISSUE TITLE
A question regarding things like scripting-support for Citra

### ISSUE THREAD

**Issue by Gagert** [citra-emu/citra#3942]
I'm not sure if this has been discussed before regarding 3DS emulation, or if suggestions like this is either within this emulators scope or technical viable altogether.

What I have in mind is the possibility of game specific overlays to display over the main screen in-game in this emulator, maybe made possible with methods such as custom scripts (using a script-language) for each specific game. 

What I'm thinking about is a way to make 3DS emulation more doable on single screen setups, by also drawing some HUD elements from the secondary 3DS screen onto the main 3DS screen itself. If we take a game like Zelda Ocarina of Time for the 3DS, it's a known fact that some HUD elements like the hearth-containers, ocarina, crossbow and such are only drawn on the secondary screen.

Could it be a possibility/ technical viable or within this emulators scope itself to have support for any kind of methods for also drawing existing HUD elements (like the hearth-containers from Zelda OiT) from the secondary screen onto the primary 3DS screen? 

I read some time ago something about the MAME emulator getting Lua-scripting support, thereby maybe (if I'm not mistaken) making it possible to manipulate the game roms temporarily by using custom made game specific scripts (I don't know the technical details about how that's working though).

It's really a first-world problem, and maybe way to over ambitious to even consider anything like this. But it would be cool to being able to play Ocarina of Time 3DS on Citra without having to either switch to the secondary screen or displaying two screens at once to know how much HP Link has left.

**Comment by jroweboy** [comment]
Relevant PR https://github.com/citra-emu/citra/pull/4016

**Comment by valentinvanelslande** [comment]
#4016 is now merged.
