### ISSUE TITLE
No sound upon starting game from Nightly #799

### ISSUE THREAD

**Issue by KPJoshi** [citra-emu/citra#3950]
This issue is present starting from Nightly 799 to Nightly 802. It was not present upto Nightly 798.

Issue: No sound upon starting a game.

Steps: Start a game. There will be no sound.

Workaround: After starting game, open the configurations window and immediately press OK to close it (Cancel won't work). Sound starts working again.

Build: Ryzen 3, Win 10 w/ latest updates, motherboard soundcard (AsRock AB350M Pro 4) with latest drivers

Notes: The workaround must be used each time a game is started, not just the first time you start a game.

**Comment by zhaowenlan1779** [comment]
If it starts from nightly-799, #3909 is likely the cause.

**Comment by Dragios** [comment]
Try not to use `#` here when mentioning the release number as it will link to unrelated reference unnecesarily. `#` is only used for GitHub issue/pull request number.
cc @MerryMage

**Comment by KPJoshi** [comment]
@jroweboy I set the audio sink to 'auto'. When I manually set it, I found that sdl2 does not have this issue but cubeb does.

The audio device is also set to auto, but I only have one: I use headphones as I do not have speakers, but they are always connected to my PC.

**Comment by MerryMage** [comment]
I was unable to reproduce this. However, since pretty much the only logic I changed was not enumerating devices in cubeb at initialization, perhaps I should see if doing that fixes it for you.

**Comment by MerryMage** [comment]
Please see if #3955 resolves your issue.

**Comment by FearlessTobi** [comment]
@KPJoshi Please retest if possible.

**Comment by KPJoshi** [comment]
@FearlessTobi as of Nightly 1195 and Canary 1211 this issue is not present. Sound works properly for both audio backends without having to do any of the workarounds listed above. I've closed the issue.
