### ISSUE TITLE
Log file doesn't show Citra version being used.

### ISSUE THREAD

**Issue by CaptV0rt3x** [citra-emu/citra#3954]
Currently, the log file isn't logging the Citra version info. (#3665)
wwylele found out that this was due to the version logging call ([here](https://github.com/citra-emu/citra/blob/master/src/citra_qt/main.cpp#L142)) being called before the file backend is added. ([here](https://github.com/citra-emu/citra/blob/master/src/citra_qt/main.cpp#L1465))
cc: @adityaruplaha 
![](https://cdn.discordapp.com/attachments/220746723545448458/469167157499002897/notepad_2018-07-18_11-41-47.png)

**Comment by adityaruplaha** [comment]
All right, I'll look into this sometime within the next month.

**Comment by zhaowenlan1779** [comment]
Fixed by @jroweboy 's pr.
Requesting to close.
