### ISSUE TITLE
Canary build 443 introduced a memory leak

### ISSUE THREAD

**Issue by greasythemattis** [citra-emu/citra#3962]
[Canary Build-443](https://github.com/citra-emu/citra-canary/tree/canary-443) introduced a memory leak that persists till this day. Build 442 and older versions(at least until version Build 419) didn't have this issue. Needless to say the memory leak it's also present in the newer nightly builds.

Memory goes through the roof when I play Shin Megami Tensei 4 - Apocalypse using the newer builds(Canary-652), going up to 1.8GB until my OS freezes and crashes. 

Reproduction
- Play smt4-apocalypse using the newest canary/nightly build
- Load a save or create new file
- Check memory usage using Task Manager

System
i5-6200u
intel hd 520 | driver: Version: 24.20.100.6194 (Latest) Date: 7/11/2018
4gb ddr3l
Windows 10

**Comment by wwylele** [comment]
https://github.com/jroweboy/citra/commit/0cf6793

The only change at that time is this commit, which meant to workaround an AMD bug in separate shader object. It might trigger bugs in other drivers.

**Comment by wwylele** [comment]
Fixed by #4042
