### ISSUE TITLE
Graphics flickering in AMD GPU

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#3963]
The graphics flicker in the over world and in conversations and the game is noticeably 
slower then on Intel GPU.
Tested game : Sushi Stiker
Using Hardware Renderer with or without its optional options.
GPU's : Radeon 530 and Intel HD 630.
Here are videos to compare:
[Intel+AMD.zip](https://github.com/citra-emu/citra/files/2210524/Intel%2BAMD.zip)
I cant show it in pictures.
Here is the log : [citra_log.txt](https://github.com/citra-emu/citra/files/2210529/citra_log.txt) .
Tested on nightly #812.

**Comment by RinMaru** [comment]
Prepare to be bashed for having an AMD GPU it comes with the territory sadly

**Comment by MojoJojoDojo** [comment]
Someone must stand for AMD

**Comment by RinMaru** [comment]
We try but we keep getting knocked back down

**Comment by SleepingSnakezzz** [comment]
Due to the age of the issue, and the large changes to our OpenGL backend, as well as to OpenGL drivers since this issue was created, I'm going to close this now. Feel free to reopen it if the issue still occurs on the latest Citra Nightly build.
