### ISSUE TITLE
Eula agreement prevents playing Ace Attorney 6 DLC

### ISSUE THREAD

**Issue by Colmines92** [citra-emu/citra#3969]
When I try to play Ace Attorney 6 DLC there appears a message like this:

ErrEula
Error Code: 0x00016F78

...without asking anything and the DLC episodes simply doesn't load.

[backlog.txt](https://github.com/citra-emu/citra/files/2214906/backlog.txt)

**Comment by CaptV0rt3x** [comment]
@Colmines92 , You are using an unofficial build of Citra. We do not give support to unofficial builds. Moreover, this is an issue tracker for devs and actual bugs. We already have DLC support in our latest canary builds. Download them from http://citra-emu.org/download/
Requesting to close!

**Comment by wwylele** [comment]
I'll keep this open as it is likely a valid issue. Could you please update your log using official build?

Related code:
https://github.com/citra-emu/citra/blob/78685065cfbecdc3214318b69f663364e717c085/src/core/hle/service/cfg/cfg.cpp#L509-L512

And this also related to the [ErrEula applet](https://github.com/citra-emu/citra/blob/f9a89ff410fa798f79bbb2613e865823a04d3825/src/core/hle/applets/erreula.cpp), which should display the EULA to let the user agree if it is not yet.

**Comment by wwylele** [comment]
Actually, nvm, likely I have been misguided. @valentinvanelslande handle your own dirty thing.
