### ISSUE TITLE
Captain Toad Fatal Error

### ISSUE THREAD

**Issue by GamerzHell9137** [citra-emu/citra#3980]
Nothing more to report about it. Using the latest citra canary revision.
[citra_log.txt](https://github.com/citra-emu/citra/files/2218973/citra_log.txt)

**Comment by wwylele** [comment]
The log is incomplete (it doesn't even shows you started the game). Could you please: 1. run the game to the error, 2. close citra, 3. upload the log?

**Comment by GamerzHell9137** [comment]
[citra_log.txt](https://github.com/citra-emu/citra/files/2219023/citra_log.txt)
Here you go

**Comment by legoj15** [comment]
Some more details are needed. Is this when starting the game? Or doing something inside the game? I can boot and play Captain Toad fine on Nightly 817.

**Comment by LuigisMansion** [comment]
Fatal error usually means you don't have mii data or you don't have shared font data. Dump both from your 3DS and try again. I've tested this game myself and it runs quite well. The upscaling is not very obvious though.

**Comment by wwylele** [comment]
I am closing this as it is likely the region setting issue. Please go to the forum for further support
