### ISSUE TITLE
Pokemon Freeze on Z-Move (Intel GPU)

### ISSUE THREAD

**Issue by Whacc** [citra-emu/citra#3982]
Issue:
Every time a pokemon uses a Z-move, the image on the screen freezes, while the game clearly continues. I managed to go through the z-move tutorial by blindly pressing “A”, and then blindly saving, and restarting the game, but now, it’s in a trainer battle, so I can’t do that anymore.

System Information

Operating System: Windows 10 64x
CPU: 1.60GHz
GPU: Intel UHD Graphics 620
Citra Version (found in title bar): Nightly #814
Game: Pokemon Sun
Here's a screenshot (and yes, the image gets stretchy when you resize it)
![bandicam 2018-07-22 22-20-01-854](https://user-images.githubusercontent.com/41585848/43086691-96aae034-8e63-11e8-8ee9-06f315c810f5.jpg)

Here's a log:
[citra_log.txt](https://github.com/citra-emu/citra/files/2219962/citra_log.txt)

**Comment by MojoJojoDojo** [comment]
I have the same problem and the same gpu.
Sometimes the picture will freeze randomly without doing a z-move.

**Comment by Tabish4675** [comment]
Maybe... just maybe it's the situation where your Graphics card stops working and then gets recovered cause that's the error I get when I face that type of problem with my Intel GPU on Cemu

**Comment by lioids** [comment]
HI, this bug is still happening, please, please fix this because it ruins the entire game

**Comment by Tabby4675** [comment]
@lioids I am gonna test this tomorrow and see if my Intel GPU faces this issue as well, cause I've played through the whole Pokemon Sun some time ago and didn't encounter this issue at all.
Also, try updating your graphics card to the latest version, that should help a ton, if not done already.

**Comment by lioids** [comment]
So sorry, I've mistaken, this bug is happening on pokemon ultra moon, at
least to me and i don't have a low graphic computer, so i don't know 😔

**Comment by Tabby4675** [comment]
@lioids What are your specs exactly?

**Comment by SleepingSnakezzz** [comment]
Please test on the latest Citra Nightly build. There have been a lot of changes to the OpenGL side of things, so this may already be fixed. Also make sure that your GPU drivers are up to date. Upload a log file if the crash/freeze still occurs: https://community.citra-emu.org/t/how-to-upload-the-log-file/296

**Comment by SleepingSnakezzz** [comment]
This does not appear to be an issue anymore on the latest GPU drivers and Citra versions. Closing.
