### ISSUE TITLE
Shin Megami Tensei 4 DLC quests not accessible, even if succesfully loaded

### ISSUE THREAD

**Issue by RandomGuy6197** [citra-emu/citra#4029]
Using latest canary (#686) to play my save of SMT4 works fine, except DLC quests are not being recognized. I dumped using the latest commit of gm9, cia loaded fine, and a confirmation screen that add-ons were being loaded showed up on game start. DLC specific demons still showed in my party, but I get kicked out of the map if I load a save while within a DLC map:  https://puu.sh/B5hEZ/3a60a49aa1.png 

Log: https://community.citra-emu.org/uploads/default/original/2X/2/276fc641651e71c62eb0ecedf5aec7e70bac7009.txt

DLC dump and load works for SMT4 - Apocalypse though, so seems like a weird bug to me.

**Comment by Dragios** [comment]
Please redump using the latest [GodMode9 v1.7.1](https://github.com/d0k3/GodMode9/releases/download/v1.7.1/GodMode9-v1.7.1-20180802021438.zip) and retest if the issue persist.

**Comment by RandomGuy6197** [comment]
From above reference:

> Built it, anddddddd it works! https://puu.sh/B8T6m/d2f9f98183.png
> Thank you so much for your work!
> 
> Log: https://puu.sh/B8T8P/15da29a66d.txt

**Comment by zhaowenlan1779** [comment]
You shouldn't close an issue for it being fixed in a non-merged PR.

**Comment by RandomGuy6197** [comment]
oh sorry

**Comment by RandomGuy6197** [comment]
Um since it's been merged, I'll close it now, okay? Shout at me if I shouldn't have.
