### ISSUE TITLE
Dillon's Dead-Heat Breakers (Europe) text empty

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#4058]
using Citra nightly #866
in the menus all it says is empty text
it works properly in Canary #724
![dillions](https://user-images.githubusercontent.com/2696404/43700890-dec6dbf6-9986-11e8-8406-4c894cf8d9c2.PNG)

**Comment by Leo626** [comment]
You're not new here. At least post the log file.

**Comment by Demos25** [comment]
change the region

**Comment by benderscruffy** [comment]
this is fixed
