### ISSUE TITLE
Fast Forward button?

### ISSUE THREAD

**Issue by Blitzoreo** [citra-emu/citra#4067]
Maybe I'm simply going crazy...But wasn't Spacebar the "Fast Forward" button, at least for Citra Nightly #869?

**Comment by Leo626** [comment]
FYI you can enable/disable the speed limit with Ctrl+Z but that is a toggle which. If you mean holding down a key, there is already an issue for this (#3417).

Requesting to close.

**Comment by Blitzoreo** [comment]
Alright, so it's confirmed that there is no Fast Forward key but it's on the works.
