### ISSUE TITLE
Black Screen on Professor Layton and the Azran Legacy

### ISSUE THREAD

**Issue by paperming** [citra-emu/citra#4068]
Well, actually it is a playable game and I keep playing it until updated to Nightly#861.
I still can enter game menu, but there is only BGM left after I load my save.
I have try to start a new game. I can watch the CG, solve the 1st question, and become black screen.
I have try to click the black screen, and heard some "response"
so I believe the game is still running.

**Comment by LexLight** [comment]
Can you put a log of that happening, please?

**Comment by paperming** [comment]
[citra_log.txt](https://github.com/citra-emu/citra/files/2271318/citra_log.txt)

**Comment by Dragios** [comment]
Breaks *Prof. Layton and vs Phoenix Wright: Ace Attorney* game menu on *Intel HD 4600*
Stuck at this log for 3 seconds (game halts during this time) before the game responds with no graphics but audio continue playing.
`Render.OpenGL <Debug> video_core/renderer_opengl/gl_shader_util.cpp:LoadProgram:55: Linking program...`
PR #4042 introduced this.

**Comment by benderscruffy** [comment]
must be an Intel HD Graphics problem as the game plays on my amd no problems

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update

**Comment by benderscruffy** [comment]
using Canary 2602
this can be closed as got up to the 3rd puzzle 
no problems so far
