### ISSUE TITLE
Shin Megami Tensei: Strange Journey Redux Frames drops by 50% in Menu's

### ISSUE THREAD

**Issue by StriFe79** [citra-emu/citra#4070]
So this game is stated as great on the compatibility list, but the FPS drops with 50% from 30 fps to 15 fps once you enter a menu. Main menu works just fine no slowdown, but as soon you go in Mission, Item, Fusion, Team the game does the fps drop. I've tried many things and settings to see if I can get some FPS back, but no matter what I do the fps drop keeps on happening. The game is overall playable, but the slowdowns are quite annoying.

Citra build: Nightly #1350
OS: Windows 10 Pro x64
CPU: AMD Ryzen 5 1600x
GPU: ASUS Arez Strix Radeon Vega 64 8 GB HBM2

[citra_log.txt](https://github.com/citra-emu/citra/files/3586237/citra_log.txt)

**Comment by zhaowenlan1779** [comment]
> So this game is stated as great on the compatibility list

Just to clarify, compatibility list ratings have nothing to do with performance or speed

**Comment by StriFe79** [comment]
Hmm well I posted this on the forums already (Which are down right now) and someone asked me to put it up here instead, so if that person is wrong and I am aswell my bad.

**Comment by urdaneta09** [comment]
Maybe beacuse you are a AMD user (the video card not the CPU) citra sadly have bad optimization with AMD GPU

**Comment by StriFe79** [comment]
Like I said the game itself outside of the menu's run just fine at 30 fps. Battles don't have a slowdown, but purely when you're in the menu's (It seems it might have to do with the Font?)

**Comment by StriFe79** [comment]
So one year further it seems this still hasn't been fixed. Game itself runs flawlessly at 30, but as soon you open any menu (Besides main menu) the FPS drops with 50% roughly and the game runs at 13 to 15fps. This happens in the fusion menu, item menu, equip menu, save menu. I know that AMD has still not fixed their OGL Drivers, but it seems weird that this game is the only one who have that issue. For example SMT IV Apocalypse doesn't.

**Comment by sschnug** [comment]
Just a remark: 

I can confirm this behaviour = heavy slowdown related to menues (without scientific measurement being done) and i'm using an (underpowered) Intel Pentium 4415Y (Surface Go): it's probably not an AMD-based problem, although my HW might be special (due to non-dedicated video-memory; and beeing very low-spec).

Not sure if thats an issue with Citra though, as there are other cases of "strange" menu-lags (e.g. Borderlands + Consoles).

**Comment by AntimatterTheFallen** [comment]
Likewise, I can confirm I go down to 15 frames per second when going into menus, **especially** when opening up the documents. The only thing I can think is perhaps the blur layer from the menu is causing a frame drop. But yeah this game Shouldn't be labeled with a "Perfect" rating of stability with such a glaring issue. But I perhaps it's only an issue when lower powered Pcs deal with this game.

**Comment by GPUCode** [comment]
Does this still occur?

**Comment by AntimatterTheFallen** [comment]
> Does this still occur?

According to the testing I just did, no. It's far more stable, and doesn't drop FPS in menus at all.

**Comment by FearlessTobi** [comment]
awesome!
