### ISSUE TITLE
[Error] the variable 'temp' is being used without being initialized

### ISSUE THREAD

**Issue by MK73DS** [citra-emu/citra#409]
Hi,

I have this error while trying to run Zelda Ocarina of Time 3D on Citra :/
![capture](https://cloud.githubusercontent.com/assets/10391562/5606867/3716e702-9444-11e4-85a4-eef7670d3304.PNG)

This error arrives only with this ROM, 3DSCraft, GameYob and other HomeBrews runs perfectly (very very slow but it runs !) :)

I'm a very noob in programming (I can just open a window with a button and a text :/ ) and I can't fix it myself :(

Thank you for your helping and sorry for my bad english :D

**Comment by neobrain** [comment]
Hi,

Sorry, but we don't give end user support, yet. I'm sure we'll eventually reach a point where this works fine for you though.
