### ISSUE TITLE
[UDS] Monster Hunter XX - multiplayer with 3 and 4 players is not working since Nightly-864

### ISSUE THREAD

**Issue by tywald** [citra-emu/citra#4090]
According to https://community.citra-emu.org/t/monster-hunter-xx-multiplayer-problems/40044 and https://www.reddit.com/r/Citra/comments/96ihlj/monster_hunter_xx_i_cant_connect_more_than_2/

Bisected to Nightly-864, PR being #3985 

![image](https://user-images.githubusercontent.com/10337060/44003184-f654a0a6-9e4e-11e8-875a-49bfb20a79cc.png)
![image](https://user-images.githubusercontent.com/10337060/44003186-fffefb24-9e4e-11e8-91ba-087635571b2e.png)

@BreadFish64 fixup requested!

**Comment by redsonjr** [comment]
Which version should I download then to play with 3 players? of citra and valentine

**Comment by B3n30** [comment]
wait till the fix for it is merged. probably within the next few hours

**Comment by redsonjr** [comment]
Okay, and valentines version?
