### ISSUE TITLE
Warioware Gold Multiplayer - Host does not see Client has connected

### ISSUE THREAD

**Issue by legend800** [citra-emu/citra#4097]
In WWG, the host can create a 'game room' (right pic), the client can see it, but upon selecting the game room, it remains on the following indefinitely:

![2018-08-12 21_24_10-citra canary 761 _ warioware gold](https://user-images.githubusercontent.com/20983844/44012792-6b5764b6-9e76-11e8-99f7-0935a976e4fa.png)

The host is just missing some notification so they can proceed to gameplay selection. Let me know what other info you need.

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by MojoJojoDojo** [comment]
Similar #3709

**Comment by legend800** [comment]
Just updating the ticket - still active of latest canary. 

![2019-03-03 23_24_19-citra canary 1224 _ warioware gold](https://user-images.githubusercontent.com/20983844/53717085-e93a8680-3e0b-11e9-83f3-481c86940615.png)

**Comment by MojoJojoDojo** [comment]
This got improved with the latest canary changes.

**Comment by legend800** [comment]
Can you describe the improvements? I verified you can connect and set up the game now, but once gameplay starts you get disconnected.

**Comment by MojoJojoDojo** [comment]
Yeah similar to what you said.
There is some progress but it still does not work all the way.

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update

**Comment by legend800** [comment]
All Fixed!!
