### ISSUE TITLE
Monster Hunter Generations - #3731 artifacts problem still remains

### ISSUE THREAD

**Issue by tywald** [citra-emu/citra#4098]
It seems the issue (#3731) still remains, tested with i7-3770K and GTX 1070 on Nightly `#899`. It appears on some resolutions, screenshots below taken at 3x.

I can't see any problem during actual gameplay.

Driver version: 398.82

Top screen(at the character selection)
![image](https://user-images.githubusercontent.com/10337060/44033109-a35e8d10-9f09-11e8-8639-15b9b36fb23a.png)

Bottom screen(at the Smithy)
![image](https://user-images.githubusercontent.com/10337060/44033112-a6c00ede-9f09-11e8-8903-86702a6920da.png)

**Comment by tywald** [comment]
An update, it seems this issue has a workaround by doing this trick:
1) Before you start the game, check `Enable Stereoscopic 3D` and set it to `1%` in Graphics tab in Citra configuration.
2) Start the game.
3) Uncheck `Enable Stereoscopic 3D`.

It will last until you change resolution.

**Comment by tywald** [comment]
I no longer have the same hardware but can't replicate the issue on a 2080 Ti.

**Comment by FearlessTobi** [comment]
Then I am going to close this for now.
