### ISSUE TITLE
Sega 3d classic games Colors are off since nightly build 812, also the same in current canary builds

### ISSUE THREAD

**Issue by suppaflie** [citra-emu/citra#4103]
https://community.citra-emu.org/t/sega-3d-classics-games-like-streets-of-rage-and-shinobi-iii-colors-are-wonky-after-nightly-811/42255/9

All this information can be found in the link i posted up above.

I have the nightly build of 811 and the sega games (not the collections) work almost perfect with
good colors however starting from 812 and onwards the colors are not right. some of the colors produce
a “negative effect”

Before and After Shots on nightly build 811 (correct colors) and nightly build 903 (incorrect):
![screenshot 785](https://user-images.githubusercontent.com/42449330/44228230-02226980-a152-11e8-965e-9bbf4358c83e.png)
top is incorrect - 903
bottom is correct - 811

![screenshot 786](https://user-images.githubusercontent.com/42449330/44228260-1d8d7480-a152-11e8-9214-9da3c5307ffd.png)
Blue sky is correct - 811
Red sky is incorrect - 903

![screenshot 783](https://user-images.githubusercontent.com/42449330/44228298-35fd8f00-a152-11e8-9e74-27726a2f3460.png)
Left is incorrect - 903
Right is correct - 811

This color glitch appears in all the sega 3d classic games I have (streets of rage, streets of rage 2 (US), Shinobi III (EUR), and Altered Beast/ btw these are individual games not the sega collections.) I haven't noticed any other problems in the current builds with other games, only the sega classics specifically.

The same goes for the canary builds although I'm not sure which canary build this started with.

another user on the forum I linked above believes this may have something to do with it
https://github.com/citra-emu/citra/pull/3916

Here are my logs:
811
[citra_log 811.txt](https://github.com/citra-emu/citra/files/2294874/citra_log.811.txt)
903
[citra_log 903.txt](https://github.com/citra-emu/citra/files/2294877/citra_log.903.txt)

and finally my System Information:

Operating System: windows 10 home x64
CPU: ryzen 1600 oc 3.9
GPU: msi gtx 1060 gaming X
Citra Version (found in title bar): any after nightly release 811
Game: any of the sega 3d classics game (Shinobi III and streets of rage 2 specifically, and altered beast)
Screenshot of Issue (include the full Citra window including titlebar):

Hope I covered it all and here's hoping this is an easy fix.

**Comment by saphiresurf** [comment]
Hey, would you mind organizing this so that the left image is the correct colors and the right image is the incorrect colors?

This will make it a lot easier for any contributor to eyeball this issue when working on it so they don't have to worry about the inconsistency in placement. If you'd be able to do this it'd be much appreciated, thank you!

**Comment by suppaflie** [comment]
This issue looks like it has been fixed in the latest canary build (#815), tested with Shinobi III and Streets of Rage 2 . Can this change be added to the nightly build?
