### ISSUE TITLE
Dead Or Alive Dimensions - regression in Canary 766

### ISSUE THREAD

**Issue by Demos25** [citra-emu/citra#4108]
There is a focus bug appeared in Canary 766
![766](https://user-images.githubusercontent.com/26468105/44343580-ee02a300-a496-11e8-8262-b3c525a3ebc1.gif)

Canary 763
![763](https://user-images.githubusercontent.com/26468105/44343588-f3f88400-a496-11e8-9862-c68bbe478624.gif)

**Comment by Leo626** [comment]
First try to reproduce this in Nightly and find the first build that started this regression. Also post the log file.

**Comment by Demos25** [comment]
There is no such problem in Nightly builds. It's only applies to post canary-764 builds. There is nothing unusual in the logs.

**Comment by B3n30** [comment]
Can you please provide the log nevertheless? There should be some log entries that are helpful for us

**Comment by B3n30** [comment]
Probably caused by #4108. Since this is not yet in nightly please move the talk to that PR
