### ISSUE TITLE
CMake Gui problem with the submodule Boost

### ISSUE THREAD

**Issue by Dante38490** [citra-emu/citra#411]
Since the addition of the submodule Boost, configures Cmake on the poster this error:

![sans titre](https://cloud.githubusercontent.com/assets/5261759/5608094/aac90df0-9477-11e4-8a14-4094c0a212bf.jpg)

>Could NOT find Boost
Boost 1.57.0 or newer not found, falling back to externals

I do not understand the submodule is updated and the Boost folder is well too, so why?

**Comment by chinhodado** [comment]
I believe CMake checks for boost on your path, and if it doesn't find it, it will use the boost externals/submodule. It is not an error.

**Comment by neobrain** [comment]
What @chinhodado said. It's just an info message saying that you don't have boost installed, hence it uses the boost copy shipping with citra.

**Comment by Dante38490** [comment]
I have not understood, of course if it's a problem, the Boost folder is present in (citra \ externals \ boost) but it does not copy it in (build \ externals) and he said he not find this folder, there is indeed a problem here.

**Comment by chinhodado** [comment]
For boost, CMake uses the `externals \ boost` directory directly. It does not need to copy that folder over to the `build` folder. If you still think it's an error, try to build the project with Visual Studio.

**Comment by Dante38490** [comment]
No, but the compilation work, but it's just that I do not understand the error message that it is not the case.
