### ISSUE TITLE
Weapon Shop de Omasse - Opening Level 5 logo does not play properly

### ISSUE THREAD

**Issue by Krusher97** [citra-emu/citra#4111]
When you load up the game, it starts with showing a video of Level 5's logo. The audio plays and the game continues just fine to the opening cutscene but the logo video itself is completely black.
Tried both canary 770 and nightly 907. The log is from Nightly 907.
[citra_log.txt](https://github.com/citra-emu/citra/files/2303508/citra_log.txt)
![weapon shop](https://user-images.githubusercontent.com/25664221/44358642-3cce2e00-a4d3-11e8-8172-4e0fcf41f52e.png)

How it looks on real hardware : https://youtu.be/ZG0C3ojOTTs?t=22s

**Comment by benderscruffy** [comment]
still happens in the latest nightly
[citra_log.zip](https://github.com/citra-emu/citra/files/2722609/citra_log.zip)

**Comment by benderscruffy** [comment]
still an issue

**Comment by benderscruffy** [comment]
@GPUCode 
using Canary 2615
still an issue
happens in software , opengl and vulkan
