### ISSUE TITLE
Yo-Kai Watch overworld sprite

### ISSUE THREAD

**Issue by mehwter** [citra-emu/citra#4136]
Sys Specs although I don't think is relevant to this case:
i5-2400
GTX 1050
8GB 1333 ram
Win 10 
------------------------------------------------------------------
 Uh, hi. This is my first time doing this but I read the FAQ and stuff so hopefully I do this right. 
 Yo-Kai Watch, the overworld(?) sprites for yo-kai no longer show up as of the latest update (Canary #784) I have this screenshot of it. Where the blue aura is, there should be a little creature, but they no longer show up. 
 Mostly I just wonder if this will affect other games. 
https://i.gyazo.com/424c73781ebc42df2043bad703f3f0e0.png 
------------------------------------------------------------------
 [I'm not smart enough to go back to the other Citra for a screenshot, my apologies. I also wouldn't mention this, but it's pretty important to gameplay. Sorry if I did this wrong, I'll do my best to fix it if I did.]
edit: I was able to try it out in Nightly #921 and the sprite appears (https://i.gyazo.com/aff2682d0133b4f4469c201464bd7341.png) more or less as it should. (This time no blue aura instead of no sprite which is much more conducive to gameplay)

**Comment by miepo** [comment]
Hey, if possible I'd like this issue to be re-opened. It is still a problem in Canary 891. I noticed this issue around the same version number as @mehwter.

The game works fine except for the overworld/hidden yokai being invisible and there only being a blue aura. It is still possible to catch them, but it's quite hard and annoying. Previously those yokai were visible, but the framerate always dropped really low in those segments.

The issue shouldn't have been closed in the first place as it never got fixed. @mehwter just went back to a previous emulator version without the issue as I understand.

Cheers

**Comment by wwylele** [comment]
Is this broken in the last nightly? Or only in canary?

**Comment by miepo** [comment]
@wwylele 
The latest Canary (900) still has the bug. The latest Nightly (1007) is fine.

I always get the latest Canary so I didn't know Nightly was fine (I assumed the bug would get ported at some point).

Here's a -hopefully working- screenshot comparison of the problem: https://imgur.com/a/j2nkF7b

Ok, I did the testing to find the version where the problem popped up. Canary 763 is the last one with visible yokai. Starting with **Canary 764** they're invisible.
I can't help with the coding but testing stuff is fine with me. Though I don't know how to compile a release or use the debugger.

Cheers

**Comment by wwylele** [comment]
Likely related #4089
