### ISSUE TITLE
Failing to build on debian, again.

### ISSUE THREAD

**Issue by y-salnikov** [citra-emu/citra#4145]
When i try to build on debian i got
[ 93%] Linking CXX executable tests
/usr/bin/ld: ../core/libcore.a(framebuffer_layout.cpp.o): undefined reference to symbol 'roundf@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/tests/CMakeFiles/tests.dir/build.make:379: recipe for target 'src/tests/tests' failed

Looks like libm not linked. No issues on ubuntu.
[cmake_out.txt](https://github.com/citra-emu/citra/files/2325779/cmake_out.txt)

**Comment by y-salnikov** [comment]
Is there a way to disable tests compilation?

**Comment by wwylele** [comment]
> Is there a way to disable tests compilation?
Just don't build it. Do `make citra-qt`

**Comment by y-salnikov** [comment]
Now i got this:
[ 92%] Linking CXX executable citra-qt
/usr/bin/ld: ../core/libcore.a(err_f.cpp.o): undefined reference to symbol '_ZNKSt8time_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE3putES3_RSt8ios_basecPK2tmPKcSB_@@GLIBCXX_3.4'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/citra_qt/CMakeFiles/citra-qt.dir/build.make:1094: recipe for target 'src/citra_qt/citra-qt' failed

**Comment by wwylele** [comment]
@y-salnikov It seems like you have a broken c++ library. I notice that you are using libstdc++ 6, which is likely incorrect, as citra only compiles on gcc 7/8, which requires corresponding libstdc++ 7 and up.

**Comment by y-salnikov** [comment]
Is there correct way to build with non-system gcc? I use this: 
`/opt/cmake-3.12.1/bin/cmake   .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/home/jarik/build/Citra/prefix/bin/gcc -DCMAKE_C_COMPILER=/home/jarik/build/Citra/prefix/bin/gcc`
Maybe i should specify LIBRARY_PATH or something like that?

**Comment by wwylele** [comment]
https://stackoverflow.com/questions/33185432/how-to-force-cmake-link-against-custom-gcc-libraries
See if this helps

**Comment by wwylele** [comment]
I am closing this issue for now as it looks more like problem with custom gcc, which is out of scope of citra build system. Please come to the discord server/forum/irc channel for further support. Thank you.
