### ISSUE TITLE
Add the function to disable the open-source font

### ISSUE THREAD

**Issue by Spmario233** [citra-emu/citra#4146]
After the open-source font was added, It's no longer able to run Chinese/Korean games properly. Could there be a option to disable the open-source font in order to run games with the old shared_font.bin?

**Comment by B3n30** [comment]
The old shared_font.bin isn't supported any more. You need to dump the shared_font again to get Chinese/Korean games working properly until we add open-source shared-font for those languages

**Comment by Spmario233** [comment]
I mean, do not force to use the open-source font while the region was set to JPN/USA/EUR...
Some fan-translated games have a DLC, and if the region was set to CHN/TWN/KOR, the DLC doesn't work...

**Comment by Spmario233** [comment]
I have already made a hacked shared_font.bin to run these games before the open-source font was added...
I mean, do not force to use the open-source font while the region was set to JPN/USA/EUR...
Some fan-translated games have a DLC, and if the region was set to CHN/TWN/KOR, the DLC doesn't work...

**Comment by B3n30** [comment]
The legacy method will get removed anyway soon... The solutions is just to dump your shared_font properly and put it inside the correct folder. For further discussion please use discord/forums/irc
