### ISSUE TITLE
Black camera image

### ISSUE THREAD

**Issue by valentinvanelslande** [citra-emu/citra#4148]
OS: Ubuntu 18.04.1
Build: Nightly 931
Screenshot:
![screenshot](https://user-images.githubusercontent.com/22228082/44748730-119c9d80-aad6-11e8-8b8e-2de948ec1e68.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/2329739/citra_log.txt)

**Comment by Leo626** [comment]
This has to be a Linux thing cause system camera runs fine for me on Windows with Nightly 931.

![citra-qt_2018-08-28_17-01-27](https://user-images.githubusercontent.com/17358613/44750749-3c8dee00-aae4-11e8-974c-94d383c0e456.png)

**Comment by MojoJojoDojo** [comment]
It doesn't work on arch linux either.
