### ISSUE TITLE
6×1≠UNLIMITED? - Player and enemies do not render

### ISSUE THREAD

**Issue by AlterShiki** [citra-emu/citra#4149]
Build: Nightly 931

Citra:
![citra-qt_2018-08-28_01-00-11](https://user-images.githubusercontent.com/42754652/44777776-ba510880-ab7b-11e8-9a7d-7ef2aabffeae.png)
![citra-qt_2018-08-29_11-07-06](https://user-images.githubusercontent.com/42754652/44777779-bcb36280-ab7b-11e8-920b-7d7f3895420d.png)

Actual hardware:
![6x1-20](https://user-images.githubusercontent.com/42754652/44777796-c6d56100-ab7b-11e8-97b8-5b556977882b.jpg)
![6x1-21](https://user-images.githubusercontent.com/42754652/44777800-c89f2480-ab7b-11e8-8725-e79adb9e724d.jpg)

Citra only shows the particle effects or lights that appear but everything else including the hexagon field isn't rendered on the top screen.

[citra_log.txt](https://github.com/citra-emu/citra/files/2332540/citra_log.txt)

**Comment by FearlessTobi** [comment]
Your issue is missing a log file. 
Please also try with the following settings on/off: Accurate multiplication, accurate geometry shaders (or what it's called now), hardware **shaders** (, hardware renderer).

**Comment by AlterShiki** [comment]
Sorry about that, added log
I have also tried some combinations of those but there seems to be no difference.

**Comment by AlterShiki** [comment]
This issue has been fixed, tested on Nightly build 1148
