### ISSUE TITLE
SmileBASIC major graphical error

### ISSUE THREAD

**Issue by csehp99** [citra-emu/citra#4150]
i noticed a major graphical error in SmileBASIC
![image](https://user-images.githubusercontent.com/42844584/44865872-82b49000-ac51-11e8-9b7d-9f4d155ab3fd.png)

this is the code editor screen, it is supposed to have a black background.
![image](https://user-images.githubusercontent.com/42844584/44865897-9c55d780-ac51-11e8-802e-d2806f74942e.png)
on the surface this doesn't LOOK like a problem, it just doesn't have a black background, not exactly game breaking.

here is the options page where you change the syntax highlight colors and background color.
![image](https://user-images.githubusercontent.com/42844584/44865991-ec349e80-ac51-11e8-9e3e-ef2275a79413.png)
if you notice, the "STATEMENT" color is the one being used for the background instead of the "BACK" (background) color

this causes problems. since the "STATEMENT" color is part of the syntax highlighting the majority of commands are rendered invisible. it goes without saying this would be a major problem while coding.
example:
![image](https://user-images.githubusercontent.com/42844584/44866204-94e2fe00-ac52-11e8-96e2-469b00859eb3.png)
line 01 is gspoit (34,54)
line 04 is gcircle (200,120,30)

this error renders the game half unplayable. its near impossible to code anything without the ability to see the commands you've written, but loading and running already made programs, as far as i can tell, works flawlessly.

System Information (probably not needed but here anyway.):
Operating System: Windows 10 Pro 64 Bit
CPU: Intel Core i5-4590s CPU @ 3.00GHz
GPU: NVIDIA GeForce GTX 970
Citra Version (found in title bar): Nightly 931
Game: SmileBASIC 

EDIT: oops forgot to say, i tried every combination of enabling and disabling in the graphics options, nothing fixed the error.

[citra_log.txt](https://github.com/citra-emu/citra/files/2337181/citra_log.txt)

**Comment by TheV360** [comment]
I ran through all the versions of Citra and **I narrowed it down to release 812**.
Here's my theory: the custom theme is a procedural texture generated from the 8 colors, and the mipmap is screwing up and making everything one color because it thinks the texture is too high quality?

**Comment by wwylele** [comment]
>i tried every combination of enabling and disabling in the graphics options, nothing fixed the error.

Even software renderer didn't work? Because if so that would be imteresting

**Comment by csehp99** [comment]
> Even software renderer didn't work? Because if so that would be imteresting

i cant get software renderer to work. citra crashes whenever i try to use it. i figured it was just that my computer isn't fast enough to handle it. im pretty new at all this stuff so i just let it crash again and i'm including the log file just in case someone needs it.
[citra_log.txt](https://github.com/citra-emu/citra/files/2342042/citra_log.txt)
