### ISSUE TITLE
Gamepad input - triggers registering in reverse

### ISSUE THREAD

**Issue by yunti** [citra-emu/citra#4166]
Citra Nightly #937 (MacOS 10.13.6). 

Currently when registering a gamepad (tested with both bluetooth xbox controller -wireless (in built os driver) and non bluetooth controller - xbox 360/xbone driver and tested wired) both register LR shoulder buttons in reverse eg (bluetooth one) it registers as Joystick 0 axis 4- (or joystick 0 axis 5- for the other trigger) rather than what should probably be Joystick 0 axis 4. 
(tested with majora's mask).

**Comment by SleepingSnakezzz** [comment]
Appears to be solved by https://github.com/citra-emu/citra/pull/5509
We can reopen it if the issue still isn't completely resolved.
