### ISSUE TITLE
joystick controls not recognized by citra

### ISSUE THREAD

**Issue by GuyPersonson** [citra-emu/citra#4167]
Windows 10 home
Version 807 Citra Canary

The first time I openned Citra after the latest update, none of the controls that I had set up for my x box one controller were working, so I restarted my computer, and it still didn't work. I then went into the settings to reset the controls, and all of the inputs except for the 2 joysticks were accepted. I could neither register the directions individually nor set up the analog stick (yes I did do the sequence correctly). The program would simply wait for an input, and then decide that no input was given and revert back to the previous key. I tested the joysticks on cemu to make sure they were working and it turns out that they did work. I restarted my computer and tried again (for good measure) and nothing different happened. So the conclusion I've got from this is that Citra isn't accepting analog stick inputs in this version. It was definitely this version that had the problem and not last version, since last version played fine.

**Comment by GuyPersonson** [comment]
Issue is fixed in Version 814 Citra Canary

**Comment by wwylele** [comment]
Is this fixed in nightly?
(@superheri we only open and close issue regarding to nightly build)

**Comment by B3n30** [comment]
I think this issue was never in nightly but an intermediate state of hotplug PR. So closing is ok
