### ISSUE TITLE
Gameplay/audio desync issue in Theatrhythm Final Fantasy CC

### ISSUE THREAD

**Issue by useredge** [citra-emu/citra#4169]
The game suffers from progressive gameplay-to-audio synchronization issues while playing any song.
It starts out fine but as the stage progresses, micro-stutters force the audio to fall back thus making it harder to hit most of the notes. Sometimes also big hiccups happen, freezing the game for a good 0.5 seconds (visible in the clip provided below).

[https://www.youtube.com/watch?v=gDuRbvjH_ko&feature=youtu.be](url)

You can see the audio starts to fall behind the gameplay at around 1:26, and a particularly big hiccup at 2:33.
Can this be avoided in any way? Is the emulator at fault or my system?

Citra build: Citra Nightly #940

Graphical settings: 
- Resolution: 4x Native
- V-Sync: disabled
- Accurate Multiplication: disabled
- Accurate Geometry Shader: disabled

Audio settings: 
- Output engine: cubeb
- Audio stretching: disabled

System specifications: 
- CPU: Ryzen 3 1200
- GPU: GTX 1050Ti
- RAM: 8 GB DDR4 2667MHz
- OS: Windows 10 64-bit

**Comment by xperia64** [comment]
I can confirm this behavior still occurs. I haven't measured it, but the game seems to desync during special attack transitions more than it does just over time?
