### ISSUE TITLE
Super Mario 3D Land crash on Linux w/ Hardware Shader turned off

### ISSUE THREAD

**Issue by Emogop** [citra-emu/citra#4172]
Operating System: Linux Mint 19
CPU: i5 750
GPU: AMD HD5870 (GL_VERSION: 4.3 (Core Profile) Mesa 18.0.5)
Citra Version 31.08.2018 master 

Citra crashes after a short while after street pass dialog if don’t press any buttons. This happens only on Linux and only with Hardware Shader disabled and only while showing prerecorded footage, so the stage selection and stages themselves work fine.
 Log: 
[citra_log.txt](https://github.com/citra-emu/citra/files/2342147/citra_log.txt)

**Comment by GPUCode** [comment]
Does this still occur?

**Comment by GPUCode** [comment]
Has been fixed
