### ISSUE TITLE
Compatibility reporting tool is unusable on higher-DPI monitors

### ISSUE THREAD

**Issue by TheV360** [citra-emu/citra#4175]
**Issue**
Here's the high DPI (250%) version:
![Can't read this message, it's even cut off around halfwa](https://user-images.githubusercontent.com/25177071/44951209-04f8ac00-ae2c-11e8-8e20-c207941a9254.png)

And the 100% DPI version:
![Can read this message, and you can finally read past the halfway point.](https://user-images.githubusercontent.com/25177071/44951176-0bd2ef00-ae2b-11e8-880d-d2d002ee5429.png)

As you can see, the first image is unreadable at my DPI. The second image shows what it should look like.

**System Information**
- Operating System: Windows 10 (1803)
- CPU: Intel Core i7-6700HQ
- GPU: Nvidia Geforce GTX 960M
- Citra Version: Canary 815, reproduced in Nightly 944.
- Game: N/A

**Steps to reproduce**
1. Ensure screen DPI set to something greater than 100%.
2. Open Citra.
3. Ensure you are logged in with your username and token, then double click a game.
4. Back in game listing window, click Report Compatibility.

**Comment by wwylele** [comment]
Could you also provide additional information about your hardware resolution and DPI?
