### ISSUE TITLE
Username hasn't any limitation

### ISSUE THREAD

**Issue by edoaxyz** [citra-emu/citra#4177]
Before joining a room you need to put your username and if you leave it blank this error will show up:
<br>
![immagine](https://user-images.githubusercontent.com/17519322/44987791-bc0a3a00-af88-11e8-8bb4-d967c8058588.png)
<br>
It clearly says that every username must be around 4 and 20 characters and this must be only alphanumeric but this is not true because anyone can join a room with any username which lenght is more than zero.
Here there are some proofs:
<br>
![immagine](https://user-images.githubusercontent.com/17519322/44987992-6d10d480-af89-11e8-8b6a-1a9d924349ac.png)
Username lenght < 4
<br>
![immagine](https://user-images.githubusercontent.com/17519322/44988287-72baea00-af8a-11e8-90b7-2195d8a82188.png)
Username lenght > 20 that contains non-alphanumerical characters

**Comment by chris062689** [comment]
There needs to be both a client check and a lobby server side check.

**Comment by edoaxyz** [comment]
Can I ask if this check is really necessary? I don't see any side effect if an user can choose freely is own username

**Comment by wwylele** [comment]
Looks like it is already implemented server side (=citra-room side according to Flame Sage). Closing https://github.com/citra-emu/citra/blob/a65f07301aead566b6c4bc98c51fe2d796afc46f/src/network/room.cpp#L564-L574
