### ISSUE TITLE
Harvest Moon: A New Beginning infinite error loop on [unmapped Read32] 

### ISSUE THREAD

**Issue by yuki1213455** [citra-emu/citra#4178]
**Issue:**
Harvest Moon: A New Beginning enters on an infinite error loop [unmapped Read32] after entering the name of the character. Exactly when the pop-up input window closes. Occurs with any branch and with and without system file dumped from 3DS. Importing a Save from 3DS, the problems still occurs with any input you need to do in the game (animals and stuff).

This seems to happen since long ago, people speculated about being a system keyboard emulation issue, most of the issues related to this topic are closed, but no one reported/checked if this game was working.

**System Information**

**Operating System:** Windows 10
**CPU:** Pentium G4560
**GPU:** GTX 760
**Citra Version (found in title bar):** 817
**Game:** Harvest Moon: A New Beginning
**Screenshot of Issue (include the full Citra window including titlebar):** Unnecessary

**Log (point of error):**

```
[  17.245310] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
[  17.245330] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  17.245450] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:680: called flag=00000000 process=10 thread_id=0
[  17.245628] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
[  17.245664] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:454: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  17.368646] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:644: Emulated program broke execution!
[  17.368654] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:660: Break reason: PANIC
[  17.368682] HW.Memory <Error> core/memory.cpp:Read:154: unmapped Read32 @ 0x00000000
[  17.370804] HW.Memory <Error> core/memory.cpp:Read:154: unmapped Read32 @ 0x00000004
[  17.371245] HW.Memory <Error> core/memory.cpp:Read:154: unmapped Read32 @ 0x00000008
[  17.371249] HW.Memory <Error> core/memory.cpp:Read:154: unmapped Read32 @ 0x0000000C
```

**Complete Log:** https://community.citra-emu.org/uploads/default/original/2X/4/47217531df805fc757d6d56de8eda1127644c436.txt

**Comment by wwylele** [comment]
Just to make it clear this has been a very old issue that was originally reported in #1583. It has never got fixed.

**Comment by yuki1213455** [comment]
Thanks for pointing out, this issue always take to a messy log of guesses without conclusion...

Ever tested if a dummy `signal = 5` can bypass this like with Puzzle & Dragons Z?

**Comment by wwylele** [comment]
I think I have tested it (assuming signal=5 is for the verification callback) but it didn't resolve.

**Comment by wwylele** [comment]
Using LLE swkbd doesn't have this issue, so it is clear that the problem is inside HLE swkbd

**Comment by FunctionsCome** [comment]
Fix this

**Comment by FunctionsCome** [comment]
Omg I think I found the clue

**Comment by FunctionsCome** [comment]
Nvm
