### ISSUE TITLE
Mario and Luigi: Superstar Saga + Bowser's Minions graphics freeze. (game still functions but graphics are frozen)

### ISSUE THREAD

**Issue by Mario0051** [citra-emu/citra#4179]
* Version: Citra Canary ##827
* Reproducing Details: When Luigi picks up Mario out of the ground after the Koopa Cruiser gets bombarded, it causes this to happen.
* System Information (probably not needed): 
    * CPU: Intel Core i3-4160 @ 3.60GHz
    * GPU: Intel HD Graphics 4400
    * RAM: 8GB @ 1.6GHz (dual-channel)

**Comment by Mario3264** [comment]
I managed to hit the save block nearby and restarted emulation, the game seems to run fine after that; Though this is kind of an issue when you really don't know where the save block is because the graphics are frozen.

**Comment by Leo626** [comment]
If you experience issues with Canary, confirm it on Nightly first. You didn't provide a log file. IIRC this game requires Accurate Multiplication enabled. Try disabling Hardware Shader.

**Comment by Mario3264** [comment]
I haven't seem to be able to find a log file and disabling Hardware Shader would disable Accurate Multiplication.

**Comment by Leo626** [comment]
Guide for [log file](https://community.citra-emu.org/t/how-to-upload-the-log-file/296). Ignoring Accurate Multiplication, what happens when you disable Hardware Shader? Also, please confirm if this happens on Nightly.

**Comment by Mario3264** [comment]
When I disabled Hardware Shader on another file, it seems to work fine. It seems to run at the very same performance with it. This same issue happens on Nightly with Hardware Shader on.

**Comment by Mario3264** [comment]
After the graphics froze again during the Starshade Bros. tutorial, I restarted the game and I can't seem to boot it again unfortunately...

**Comment by Mashibro** [comment]
I was about to make an issue on this! Glad to hear that I'm not the only one experiencing this. I did all of the stuff that you did too, hitting the save block while frozen but then it proceeded to freeze again during the Starshade tutorial.
Remember that you cannot really disable anything as the game requires Enabled Multiplication.

**Comment by Nerboruto** [comment]
various versions tested, Canary and Nightly.
the crash happens only on intel 4400 always in the same place, when mario and luigi fall from the bowser spaceship and luigi pulls out mario from the ground. on nvidia it seems ok.
[citra_log.txt](https://github.com/citra-emu/citra/files/2592857/citra_log.txt)

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update

**Comment by benderscruffy** [comment]
this can be closed 
has had no updates for over 5 years

**Comment by GPUCode** [comment]
Will close this for above reason, open new issue if this still a problem
