### ISSUE TITLE
Xbox One S Controller not recognized

### ISSUE THREAD

**Issue by PSmiet** [citra-emu/citra#4185]

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use the [Citra forums](https://community.citra-emu.org) instead.

Requesting to close.

**Comment by PSmiet** [comment]
Already done that, the Citra forum directed me to this site.

**Comment by B3n30** [comment]
@PSmiet I will try to figure out the issue with you on the forums. If it's really an issue with Citra we can reopen this. But then I would ask you to make a complete issue report (with log, details about your system, tested citra version, etc...)
