### ISSUE TITLE
Rune Factory 4 (Japan) Text Rendering Issue

### ISSUE THREAD

**Issue by sleepingreen** [citra-emu/citra#4189]
This seems to have been introduced in later versions (Nightly 764 and Canary 588 onwards). For comparison (previous version and later):

Canary 588
![a1](https://user-images.githubusercontent.com/43074026/45233622-f16c9b80-b298-11e8-915d-2718791a0949.png)

Canary 834
![a2](https://user-images.githubusercontent.com/43074026/45233630-f3cef580-b298-11e8-88d4-0df2370184f4.png)

**Comment by tgsm** [comment]
it looks like it's using the open source font instead of the one dumped from your 3ds.

**Comment by B3n30** [comment]
This is not an issue. You need to provide your own dumped shared_font in the new method: https://citra-emu.org/wiki/dumping-system-archives-and-the-shared-fonts-from-a-3ds-console/

(We removed support for the old way the shared font was loaded and thus it loaded the open source replacement which isn't perfect, especially for Japanese signs)
