### ISSUE TITLE
Can't open installed citra file

### ISSUE THREAD

**Issue by dude10** [citra-emu/citra#4198]
Hi, I just got a new computer and wanted to try out M&L Superstar saga game but unfortunately my computer correctly install because of this problem.
Even if I install it ignoring this problem, It won't execute but I can see in "Applications and Features" Citra installed.
![problem](https://user-images.githubusercontent.com/6996253/45265460-ba8eb500-b453-11e8-9e23-90f5b634ff23.png)

How I can fix it?

**Comment by Hexagon12** [comment]
This is an issue tracker for developers and not a support forum.
Please use the [Citra forums](https://community.citra-emu.org/) instead.

Requesting to close.
