### ISSUE TITLE
lego ninjago: shadowof ronin sound bug

### ISSUE THREAD

**Issue by Demir2007** [citra-emu/citra#4199]
when i play dis game 
the voice acting/music
is broken

Operating System: Windows 10
CPU: İ7-7700
GPU: GTX 1050
Citra Version :Canary 842
Game: Lego Ninjago: Shadow of Ronin

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use the [Citra forums](https://community.citra-emu.org/) instead.

Requesting to close.
