### ISSUE TITLE
 Puyo Puyo Chronicles - Hardware rendering inaccuracy - eyebrows and shader effects missing

### ISSUE THREAD

**Issue by NostalgiaNinja** [citra-emu/citra#4202]
Specifications:

**Citra:**
Citra Canary #842 HEAD-68d48ac (2018/09/09)
Game: Puyo Puyo Chronicles

**System specifications:**
OS: Ubuntu 18.04 x64
CPU: Intel i7 7700
GPU: Nvidia GTX 1050 TI

Issue:
When using hardware rendering (Enable Hardware Renderer, Enable Hardware Shader, Accurate Multiplication, Accurate Geometry Shader), Eyebrows of characters do not show(in battle, and in cutscenes), as well as some shaders behave differently (glow effects missing on Ally's Heart).

Screenshots:
**_with Hardware Renderer enabled:_**
cutscene:
![citra - hardware rendering - cut scene](https://user-images.githubusercontent.com/6517782/45384921-b6a79200-b60f-11e8-9ba6-5aa26fd8fa43.png)
Battle:
![citra - hardware rendering - in battle](https://user-images.githubusercontent.com/6517782/45384922-b7402880-b60f-11e8-849a-748a3d6f19b9.png)

**_with Hardware Renderer disabled:_**
Cutscene:
![citra - software rendering - cut scene](https://user-images.githubusercontent.com/6517782/45384925-b7402880-b60f-11e8-9b55-34c9623cebff.png)
Battle:
![citra - software rendering - in battle](https://user-images.githubusercontent.com/6517782/45384926-b7d8bf00-b60f-11e8-9521-c0785d575168.png)

**_Actual 3DS hardware:_**
Cutscene:
![3ds hardware - cut scene](https://user-images.githubusercontent.com/6517782/45384918-b6a79200-b60f-11e8-90b4-636d0e9e0e82.jpg)
Battle:
![3ds hardware - in battle](https://user-images.githubusercontent.com/6517782/45384919-b6a79200-b60f-11e8-9d19-4316b8dfb5e2.jpg)

**Comment by PyroJay4** [comment]
bumps this because it happens consistently for everyone on our translation team, even on the latest build, universal problem with the games emulation 
(am i allowed to bump things idk, either way this is still importante)

**Comment by PyroJay4** [comment]
im tired of seeing allys bigass forehead help

**Comment by JeonDohyeon** [comment]
Same here: Citra Nightly 1714, Canary 1977 / playing Puyo Puyo Chronicle
When using GPU Renderer, eyebrows disappears.
When disabled it(framerate drops from 60 to 5), I can EXACTLY see the eyebrows.

OS: Microsoft Windows 10 21H1(Build 10.0.19043.1052)
CPU: Intel(R) 11th Gen i5-1135G7
GPU: Intel(R) Iris Graphics
RAM: 8GB DDR4

**Comment by benderscruffy** [comment]
Has this been fixed ???
Please update

**Comment by NostalgiaNinja** [comment]
See image 1 of my initial update. Still applies even now, It's not game breaking, but it isn't hardware accurate.

**Comment by GPUCode** [comment]
Fixed by https://github.com/citra-emu/citra/pull/6921
