### ISSUE TITLE
Fails to build without network access

### ISSUE THREAD

**Issue by jbeich** [citra-emu/citra#4206]
Regressed by #4016. See [error log](https://ptpb.pw/ifPl).

```
$ cmake -DENABLE_QT=off /path/to/citra
$ gmake
Scanning dependencies of target libzmq-external
[  0%] Creating directories for 'libzmq-external'
[  0%] Performing download step (git clone) for 'libzmq-external'
Cloning into 'libzmq'...
fatal: unable to access 'https://github.com/zeromq/libzmq/': Could not resolve host: github.com
Cloning into 'libzmq'...
fatal: unable to access 'https://github.com/zeromq/libzmq/': Could not resolve host: github.com
Cloning into 'libzmq'...
fatal: unable to access 'https://github.com/zeromq/libzmq/': Could not resolve host: github.com
-- Had to git clone more than once:
          3 times.
CMake Error at libzmq-external-prefix/tmp/libzmq-external-gitclone.cmake:66 (message):
  Failed to clone repository: 'https://github.com/zeromq/libzmq'


gmake[2]: *** [externals/CMakeFiles/libzmq-external.dir/build.make:90: externals/libzmq-external-prefix/src/libzmq-external-stamp/libzmq-external-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:155: externals/CMakeFiles/libzmq-external.dir/all] Error 2
gmake: *** [Makefile:141: all] Error 2
```

**Comment by jbeich** [comment]
@abbradar, @rfht, do Nix or OpenBSD allow packages use network during build i.e., after download phase?

**Comment by rfht** [comment]
I can only speak for OpenBSD, but there packages are built in bulk builds with a low-privilege user that doesn't have network access. So the answer is no.

**Comment by FearlessTobi** [comment]
We are looking into the various issues with that submodule and hopefully push out a fix soon.

**Comment by KAMiKAZOW** [comment]
Well, hopefully your fix involves that I also can use my system's libzmq-devel package. The reliance of Citra on statically linking almost everything is a pain. See eg. #3572

**Comment by KAMiKAZOW** [comment]
-DENABLE_SCRIPTING=OFF works as a workaround.

**Comment by jroweboy** [comment]
@KAMiKAZOW As an update, we are looking at replacements for zmq as its a hefty dependency that likes to break the build a lot :)

**Comment by jbeich** [comment]
[Builds fine](https://ptpb.pw/Bm_F) after #4609.
