### ISSUE TITLE
Fails to build with Ninja generator

### ISSUE THREAD

**Issue by jbeich** [citra-emu/citra#4207]
Regressed by #4016. See [error log](https://ptpb.pw/nTeY).

```
$ cmake -GNinja -DENABLE_QT=off /path/to/citra
$ ninja
ninja: error: 'externals/libzmq-external-prefix/src/libzmq-external-build/lib/libzmq.a', needed by 'src/tests/tests', missing and no known rule to make it
```

**Comment by j-selby** [comment]
Note that this issue specifically relates to FreeBSD, and not Lin/Win/Mac.

**Comment by jbeich** [comment]
@j-selby, can you show verbose build log (i.e., `ninja -v`)? I'd like to investigate the difference. TravisCI doesn't use Ninja yet (see #4125).

**Comment by filialpails** [comment]
I had this issue on Linux when building with Ninja. Solved by adding `BUILD_BYPRODUCTS ${CMAKE_CURRENT_BINARY_DIR}/libzmq-external-prefix/src/libzmq-external-build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}zmq${CMAKE_STATIC_LIBRARY_SUFFIX}` to the `ExternalProject_Add(libzmq-external` calls in `externals/CMakeLists.txt`. See [this CMake mailing list thread](https://cmake.org/pipermail/cmake/2015-April/060234.html).

**Comment by tgsm** [comment]
libzmq has been removed from the repo, is this issue fixed now?

**Comment by jbeich** [comment]
[Yes](https://ptpb.pw/Koar)
