### ISSUE TITLE
Citra Nightly Build #966 crashing

### ISSUE THREAD

**Issue by Aaron-Wang1012** [citra-emu/citra#4208]
Whenever I launch this version of the nightly build I experience crashes frequently, here is the log.txt:
https://pastebin.com/4KfeT64N
Thanks

**Comment by CaptV0rt3x** [comment]
This is an issue tracker for developers.
Please use our [forums](https://community.citra-emu.org/) or our [discord](https://citra-emu.org/discord/) server for support.
