### ISSUE TITLE
Nightly #976 is freezing up every 5 minutes for 2+ mins

### ISSUE THREAD

**Issue by brothers-morrison** [citra-emu/citra#4212]
1. Description:
Game freezes up - ROM screen completely gone, goes back to Citra Rom selection page/Game directories
Windows says: citra-qt.exe not responding.
If you wait for 2+ minutes it comes back briefly, then goes into another freeze later.
This gets worse over time - now the majority of time is "frozen".
Closing/Reopening program doesn't fix it.  Restarting machine didn't seem to fix it.
No other running programs (I tried killing a few background things (Dropbox, Onedrive) in case of low mem, but it doesn't seem to change the issue.
Looking at System Memory = normal, CPU spikes a bit, but then normal during the freezup
GPU spikes a little and is high - stays around 50% for the duration of the freezup. 

1. Current version (commit hash) of Citra you are using.
*Nightly #967 | HEAD-8c354ff*

1. Repro Case:
Playing Pokemon Sun - in main overworld, trying to catch pokemon, so going in and out of battles.  Just playing the game should cause the crash after 1 hour of play.

1.  System specs
Win10, i7 16GB ram, NVIDIA GeForce GTX 960M

1. Graphics Debug/Crash log below:
![image](https://user-images.githubusercontent.com/14063813/45521209-9103bf80-b7ac-11e8-882c-a7ccdd853e54.png)

**Comment by wwylele** [comment]
Is this a new issue in this particular nightly version or it has been an old issue?

**Comment by zhaowenlan1779** [comment]
I thought you meant 967 in the title

**Comment by Dragios** [comment]
Still an issue now?

**Comment by benderscruffy** [comment]
Can be closed now
