### ISSUE TITLE
[Feature request] Add an option to separate screens 

### ISSUE THREAD

**Issue by LuismaSP89** [citra-emu/citra#4216]
I use two screens on my pc. One of them is a touch screen. It would be awesome an option to separate/split the screens in order to play like a real 3DS. The first 3DS screen on my first screen, and the second 3DS screen on my second PC screen (Can be a tablet used as second screen) I think it´s the final thing to make this emulator perfect.

**Comment by BreadFish64** [comment]
Duplicate of #3968
