### ISSUE TITLE
about SRW BX Battle animation

### ISSUE THREAD

**Issue by rcyggdra** [citra-emu/citra#4225]
since [Kernel/IPC](https://github.com/citra-emu/citra/commit/98e38723530eb60e3f2c5ad509174f48f98ae882#diff-0c1281ca6c3a6125c8eb110d819d14e8`) change,some of battle animation dimness:
![snipaste_2018-09-16_00-38-56](https://user-images.githubusercontent.com/8652464/45588588-9d714f00-b949-11e8-99a4-5b08791dd39e.png)

![snipaste_2018-09-16_00-39-06](https://user-images.githubusercontent.com/8652464/45588605-d7daec00-b949-11e8-9064-399dc9263271.png)
the pic above is rollback`static constexpr u64 IPCDelayNanoseconds = 100;`
can you fix it?

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update
