### ISSUE TITLE
Crash when hitting GDB breakpoints when JIT is enabled

### ISSUE THREAD

**Issue by SydMontague** [citra-emu/citra#4234]
When running the emulator with CPU JIT enabled while using GDB the emulator will crash as soon as execution hits a breakpoint. The only log message related to it is

> [1202.966694] Debug <Critical> core/arm/dynarmic/arm_dynarmic.cpp:operator():129: Assertion Failed!
ExceptionRaised(exception = 2, pc = 00241880, code = E1A0000D)

I'm running Citra Nightly #975 (HEAD-241f10a) on Windows 7 and used IDA 6.8 (on Windows) as well as plain GDB 8.1.0 (remotely, on Linux) to set the breakpoints. I also tried Canaray #857 (HEAD-09df0fc) with IDA to no avail.

When disabling CPU JIT breakpoints start to work as intended.

The game used for testing was Digimon World Re:Digitize Decode.

**Comment by MerryMage** [comment]
PRed #4276.
