### ISSUE TITLE
Performance degredation during playing sessions

### ISSUE THREAD

**Issue by CodingKoopa** [citra-emu/citra#4238]
There have been several reports of Citra's performance degrading over time. Here, running Citra and starting a game, or restarting a game in an already open instance of Citra, will be considered a "session". In a session, after a varying amount of time (Reports have varied from immediate, to minutes, to hours after starting the session.), emulation will see a drastic reduction in performance. Regarding the build of Citra, on setups where this occurred, it occurred on every build tested, both Nightly (One that was tested being 687e3e7) and Canary ([`cfa6232`](https://github.com/citra-emu/citra-canary/commit/cfa6232) tested.).
I've gathered these testcases from the forum and Discord server:
- [Testcase 1](https://community.citra-emu.org/t/citra-was-running-well-and-then-it-suddenly-got-slow/43692?u=codingkoopa) ([@marcelomangerona](https://community.citra-emu.org/u/marcelomangerona)):
  - OS: macOS High Sierra 10.13.6
  - CPU: Intel Core i5 @ 2.5 GHz (model unspecified)
  - GPU: Radeon HD 6750M
  - Game(s) tested: [Pokémon Ultra Sun](https://citra-emu.org/game/pokemon-ultra-sun-ultra-moon/)
- [Testcase 2](https://community.citra-emu.org/t/frame-drop-random-but-constant/49668?u=codingkoopa) (also see [here](https://community.citra-emu.org/t/citra-was-running-well-and-then-it-suddenly-got-slow/43692/27?u=codingkoopa)) ([@Antonio_Di_Prisco](https://community.citra-emu.org/u/antonio_di_prisco)):
  - OS: Windows 7
  - CPU: Intel Core i7-2600 @ 3.40GHz
  - GPU: GeForce GTX 650 Ti BOOST
  - Game(s) tested: [Fantasy Life](https://citra-emu.org/game/fantasy-life/), [Super Mario 3D Land](https://citra-emu.org/game/super-mario-3d-land/), [Captain Toad: Treasure Tracker](https://citra-emu.org/game/captain-toad-treasure-tracker/) (Only reproduced on Fantasy Life)
- [Testcase 3](https://community.citra-emu.org/t/citra-was-running-well-and-then-it-suddenly-got-slow/43692/29?u=codingkoopa) ([@Rgnm14](https://community.citra-emu.org/u/rgnm14))
  - OS: Unspecified
  - CPU: Intel Core i7 (model unspecified)
  - GPU: GeForce GTX 1070 Ti
  - Game(s) tested: [The Legend of Zelda: Majora's Mask 3D](https://citra-emu.org/game/legend-of-zelda-majoras-mask/)
- [Testcase 4](https://community.citra-emu.org/t/low-fps-sudently/46982?u=codingkoopa) ([@Peteiro92](https://community.citra-emu.org/u/peteiro92))
  - OS: Unspecified
  - CPU: Unspecified
  - GPU: Unspecified
  - Game(s) tested: Pokémon Ultra Sun
- Testcase 5 (`KnightOfDQ#6953`)
  - OS: Windows 10 1803
  - CPU: Intel Core i7-2670QM @ 2.20GHz
  - GPU: GeForce GT 555M
  - Game(s) tested: [Bravely Default](https://citra-emu.org/game/bravely-default/)

From testcase 2, these are the microprofiles of idling and playing before the performance reduction occurs, and after:
![Microprofile of idling before performance reduction.](https://community.citra-emu.org/uploads/default/original/2X/0/0bb97da8c27d5fc640133b89b501c1bf0ccdbb62.png)
![Microprofile of playing the game in a 3D-heavy scene before performance reduction.](https://community.citra-emu.org/uploads/default/original/2X/8/83b6f6a0929821d5174900e5900e03164c2e7729.png)
![Microprofile of playing the game in a 3d-heavy scene after taking a screenshot.](https://community.citra-emu.org/uploads/default/original/2X/8/83b6f6a0929821d5174900e5900e03164c2e7729.png)
The last microprofile was created under the conditions of having just taken a screenshot, but acoording to OP, it looks the same as when the performance reduction normally occurs.

From testcase 5, these are the microprofiles of before and after the performance reduction occurs:
![Microprofiler before and after comparision.](https://cdn.discordapp.com/attachments/343888608442449920/490936365257588736/unknown.png)

I will be keeping this updated to fill in the unspecified fields, and add any new testcases.

**Comment by Dragios** [comment]
Is this still an issue?

**Comment by SleepingSnakezzz** [comment]
We have not encountered any more unresolved cases like these. There are also inconsistencies in the issues that the users reported, and the issue described in the opening post. Thus, I'll be closing this for now.
