### ISSUE TITLE
(Request) Customizable Directory

### ISSUE THREAD

**Issue by Moodie92** [citra-emu/citra#4239]
so i 've always wanted all citra files in one folder but not in C  partition , could you make it so the files in roaming folder can be change in anywhere users wanted via gui , it will be nice addition

**Comment by jroweboy** [comment]
Citra will need to keep the configuration files in appdata at minimum, but customizable emulated nand/sd directories is a planned feature. This feature has already been suggested here https://github.com/citra-emu/citra/issues/3818 so I'm going to close this issue as a duplicate.
