### ISSUE TITLE
[Request] Add configurable inputs/hotkeys for touchscreen touches

### ISSUE THREAD

**Issue by Dartz150** [citra-emu/citra#4261]
I thought of this while playing Ocarina of time.

It would be useful to configure, for example, the right stick directional axes and R3/L3 (or whatever you want it to be, depending of the game) into touchscreen presses, for quick use of items shown on the bottom screen without the need of recurring to click with the mouse, like a "C Stick" workaround for games that doesn't support it.

I think not only this game would benefit of such feature.

Maybe this can be configured as a coordinate or something.

What do you think? Is it possible?

**Comment by GinoMan** [comment]
I'd say not just presses for press button press screen, but also a way to map a button to a set of locations in a specific order that it will toggle between and press on each button press (think a single button to switch beams in Samus Returns). or a way to set two points on a screen to be a slider axis and mapping that analog axis against an extra thumbstick. I'd like to see all three of those.

**Comment by johelegp** [comment]
I think this can be closed.
