### ISSUE TITLE
Nightly 993/990: Game save reverting back to older one.

### ISSUE THREAD

**Issue by WellBeSerious** [citra-emu/citra#4264]
**EDIT: Just now I restored my game from a backup in a different folder, but need to report this so it could be fixed. Also, the log is from when the save was replaced, too late to undo it now.**

- **Issue**:
I was playing Pokemon: Alpha Sapphire for a long time yesterday, and lost a lot of progress. The previous save was from the left side (2nd floor Apartment Complex field) of Mauville City, the new save is from the Fallarbor Town top field, and the loaded save is from Slateport City beach. That's a lot of progress I lost! All I did was save properly (I save tons of times throughout important events/times), and shutdown properly (sometimes I 'Quit' emulation, sometimes I exit the Citra window through 'X'). Unless closing the window (even after you've saved multiple times) corrupts the save file, nothing else makes sense. I was on Build 990, problem occurred (_maybe it did in older builds, I wouldn't remember_), updated to 993 to potentially fix the issue, but it didn't.

- **Log**: https://drive.google.com/open?id=1DK8d7NhSw5hkMe9yl3P26Cpq3FxFwNwy

- **Hardware**: GIGABYTE GA-AB350M-Gaming 3 (Rev. 1.0), AMD Ryzen 7 1700X @3.89GHz, 16GB (2 x 8GB) DDR4 3200MHz, HIS/AMD Radeon R9 290 4GB GDDR5, Samsung SM953 Series MZ-1WV4800 480GB M.2 SSD (OS/apps), 4TB HDD (roms/installed on), 2TB HDD (PC games).

- **Game Save**: [irrelevant because I replaced the non-working one with the working one, works **now**.]

- **Screenshots**: [irrelevant because there are no graphical problems.]

This issue was occurring around 990, and still continues to 993 today. It may have happened in previous builds, but I wouldn't remember. I'm linking my last issue in case someone asks about deleting the **sdmc** folder or not.
https://github.com/citra-emu/citra/issues/4236

**Comment by j-selby** [comment]
Are you using the Citra updater to update from 990 to 993?

**Comment by WellBeSerious** [comment]
Yes. Nightly Updater from Citra itself. The original version from which I can't tell, but shouldn't matter since 'updating' is replacing the older program files (although other parts remain).

**Comment by Dragios** [comment]
Please try again with PR #5120 and let us know if this fixes your issue?
You can test by downloading the latest Canary.

**Comment by SleepingSnakezzz** [comment]
No response from OP, and this hasn't been reported again since #5120
