### ISSUE TITLE
(Linux/i915) Citra causes the GPU to hang/reset after extended period of gameplay.

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#4265]
After an extended period of time in Animal Crossing: New Leaf, the GPU will hang and reset, killing the x server and all open programs. I've looked around other bug reports, and I can't find anything relating to the i915 driver.

It usually occurs about an hour into gameplay, and I don't believe its a hardware issue. My temps are well below the critical point, and the only other thing I have open with citra is a web browser with mostly text-based pages. 

My hardware is a Thinkpad T420 with a Core i5 2450m (or 2520m, basically the same thing.) I'm running Arch Linux with i3wm and no compositor, and the only changes to my driver/X config is a higher DPI. 

Linux thinkpad 4.18.9-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018 x86_64 GNU/Linux

00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

I've attached some more relevant info in text files, and I appreciate your taking the time to read my bug report.

[crashdump](https://github.com/citra-emu/citra/files/2416720/fullerror.txt)

I'm also running Canary citra-linux-20180924-97ef13a but it also occurs in the nightly build.

**Comment by SleepingSnakezzz** [comment]
This appears to be an isolated incident, and the user in question no longer appears to be around for further comment. Closing for now.
