### ISSUE TITLE
Unpause Hotkey doesn't work on Canary Build (#998)

### ISSUE THREAD

**Issue by Real96** [citra-emu/citra#4268]
I'm using Citra Canary #998, i set the Continue/Pause Emulation hotkey (in configuration > controls > Hotkeys tab) as P.

I can pause the game without any problems. But after i pause it i can't unpause it with the same hotkey. I 
 can unpause it only using the emulator option (emulation > start).

The same thing doesn't happen on the Nightly build #998, the hotkey (F4 the default one) works perfectly

**Comment by B3n30** [comment]
Please post this issue in the corresponding canary PR. Probably #3786, since the issue tracker is for nightly/merged issues only. Thx

**Comment by Real96** [comment]
i'm sorry, thanks a lot!
