### ISSUE TITLE
Qt: Disassembler view *always* loads 125000 lines (500000 bytes) no matter how big the .code is. 

### ISSUE THREAD

**Issue by archshift** [citra-emu/citra#427]
Probably due to [this crazy function](https://github.com/citra-emu/citra/blob/master/src/citra_qt/debugger/disassembler.cpp#L102-L136) which populates the disasm with 125000 lines, with no concern for how large the .code actually is.

**Comment by mattvail** [comment]
Quick and dirty solution we had... Maybe @Kingcom can add this too his to-do.
Loading everything is still a bad idea for performance. Ideally this would be dynamic and load only x number of lines before and after the current op being displayed.

**Comment by JayFoxRox** [comment]
Referencing for #1480 (meta issue about improving debugger)
