### ISSUE TITLE
Citra does not load properly the first time when a gamepad is plugged in.

### ISSUE THREAD

**Issue by Paradoxed24** [citra-emu/citra#4292]
Version: Nightly # 1018

Issue: Citra does not load properly when a gamepad is plugged in.

System Information:
     Operating System: Windows 10
     CPU: AMD Ryzen 5 1600 Six-Core
     GPU: AMD Radeon HD 7800 Chipset (7850 specifically)
     Game: NA

Process: During the whole process, a gamepad was plugged in and enabled. These gamepads include a standard XBOX 360 controller and a USB SNES controller by iBuffalo.
     1: Visual C++ Redistributable for Visual Studio 2015 and 2017 were installed 
     2: Citra was installed using the auto download feature from citra-emu.org
     3: Citra was booted and was not visible. Citra did show up in Task Manager but was invisible and could not be interacted with in any way. Citra never generated a Diagnostic Log.
     4: Citra was killed from the task manager, controllers were unplugged/disabled via device manager. Then Citra was restarted and loaded properly.

Oddities:
     After unplugging/disabling the controllers and running Citra for the first time, the issue does not persist. Citra now properly boots even if the gamepads are connected and enabled.

**Comment by jroweboy** [comment]
This PR should fix that. https://github.com/citra-emu/citra/pull/4289

Test it out here and see if it fixes it.
https://ci.appveyor.com/project/bunnei/citra/build/1.0.9591/job/c2pmx07c1vfvp8yt/artifacts

**Comment by Emogop** [comment]
> This PR should fix that. #4289
> 
> Test it out here and see if it fixes it.
> https://ci.appveyor.com/project/bunnei/citra/build/1.0.9591/job/c2pmx07c1vfvp8yt/artifacts

It does, thanks.
