### ISSUE TITLE
POKEMON ULTRA MOON 3DS - Game's speed slows down drastically

### ISSUE THREAD

**Issue by vernari** [citra-emu/citra#4294]
Hi everyone,

The quality of the gameplay was perfect without any crash until now. (Even the 'famous' Photo Club crash didn't occurred.) After the part where Lillie's mother has gone to the ultrawormhole, the game became awfully slow. The speed dropped down to 60-70% in average. In battles it's sometimes even worse, like 30%. Thought it's a 'heavy' part of the game with massive graphics, but traveling back to the first island and just hanging around the streets didn't help.

Any thoughts what happened? Do you have any suggestions?

I always update to the latest version of Citra. I've got an iMac late 2012, with the latest OSX.

I'm using this ROM: [Removed due to piracy]

Thank you in advence.

**Comment by zhaowenlan1779** [comment]
@vernari Please read our community rules. Warez/downloading games talk is strictly prohibited. To prevent legal issues, you are not allowed to post links or refer to any kind of ROM, NAND, ISO, game, or other copyrighted material that has been illegally obtained or shared. https://citra-emu.org/rules/

I'm sorry, we cannot provide support for pirated content. I've edited out the link.
