### ISSUE TITLE
Etrian Odyssey V stays on the first screen when it starts. Is there a way to fix this?

### ISSUE THREAD

**Issue by LunaBiersack** [citra-emu/citra#4297]
I tired running the game on both Citra Nightly 1019 and Citra Canary 912. 

Once I start the game, it stays on this screen:
![etrian odyssey v issue](https://user-images.githubusercontent.com/43812122/46430689-cd756c00-c717-11e8-8e40-8b1d21a7386a.PNG)

**Comment by zhaowenlan1779** [comment]
Do you need to press A on a real 3DS?

**Comment by jroweboy** [comment]
Please test if this happens on nightly. There is a PR that is only in canary that has a potential to break games, but also tends to make many games faster

**Comment by LunaBiersack** [comment]
Thank u all. But apparently it was fixed with just pressing A.
