### ISSUE TITLE
Idle thread for when no threads are ready to run

### ISSUE THREAD

**Issue by Subv** [citra-emu/citra#430]
We need to implement an idle thread that will get scheduled when no other threads are ready to be scheduled. 
Right now we have a pretty serious bug with threads not waiting if a WaitSynchronization call made a reschedule, if there are no other ready threads, the calling thread will continue executing regardless of the result of the WaitSync operation.

This patch implements a **very awful hack** for an idle thread:
https://gist.github.com/Subv/3bf5329a97a370ec93ed

**Comment by yuriks** [comment]
I think the "ARM stub" thing is pretty terrible, TBH. It adds a lot of hacks throrough the rest of the code. (Syscall, memory map) Is there any reason we can't simply do this when the Kernel re-schedules and encounters a null thread?

**Comment by Subv** [comment]
Here's another way of fixing this issue without using an idle thread:
https://gist.github.com/Subv/beac7a45a9b2df50d7aa

I have some concerns about applications waiting on things that aren't events with this patch, for example an application waiting on a Semaphore that was initially configured to block on the next wait, if the app waits on said semaphore, it will just ignore the wait and continue execution with this patch (and with the current Citra), but will block properly with the patch up there.

**Comment by Subv** [comment]
Here's another possible way of fixing this that deals with the previous warning: https://gist.github.com/Subv/ee7756fcd8d701a65a9b
It uses a dummy thread that will not execute instructions, just advance the timing

**Comment by yuriks** [comment]
Last patch is good, but maybe you can use an invalid priority value instead of adding a new field. (You can keep the function, of course.)

**Comment by yuriks** [comment]
Also, shouldn't the priority of the idle thread be lower than lowest so that it doesn't interfere with any legitimate CTR threads with that priority?

**Comment by bunnei** [comment]
I don't really see this as a hack, as it actually mimics what would actually happen (from the userland application's perspective) better than not using any idle thread at all.

@yuriks wrt to giving it an invalid priority, that also seems like a hack to me, since whatever idle/dummy thread we switch to (to simulate a real OS idle thread or some other app's thread being ready) will have a valid priority.
