### ISSUE TITLE
[Android] There's finally a Citra 3ds emulator for android ? 

### ISSUE THREAD

**Issue by Emulatorer** [citra-emu/citra#4302]
There are post in youtube that working Citra 3ds emulator for android this is officially you guys or not?

Source: https://youtu.be/5ETDfCmzcCY
Apk: http://www.mediafire.com/file/c0w9tg2vxmqbqq9/Subscribe_TechUtopia_Youtube_CitraAndroid-release.apk/file

**Comment by Emulatorer** [comment]
![screenshot_2018-10-04-17-23-40](https://user-images.githubusercontent.com/37603562/46500403-4c4ecf80-c812-11e8-9f50-59aa54629a94.png)
![screenshot_2018-10-04-16-20-23](https://user-images.githubusercontent.com/37603562/46500428-57096480-c812-11e8-9e96-f1cca1718a75.png)
![screenshot_2018-10-04-16-20-04](https://user-images.githubusercontent.com/37603562/46500446-5f619f80-c812-11e8-88d6-9408a4d58323.png)
![screenshot_2018-10-04-16-19-49](https://user-images.githubusercontent.com/37603562/46500458-6688ad80-c812-11e8-868c-a61444b03a07.png)
![screenshot_2018-10-04-16-19-24](https://user-images.githubusercontent.com/37603562/46500473-6d172500-c812-11e8-8e44-4ea124c37157.png)

**Comment by legoj15** [comment]
Yeah no, that is 100% not real, it's a modified version of Dolphin for Android, edited to say Citra.

**Comment by FearlessTobi** [comment]
This emulator is not official and neither endorsed nor supported by the Citra team. Closing as this is not really an issue suitable for the tracker.

**Comment by jroweboy** [comment]
@legoj15 its real, but the author of the fork hasn't contacted us to talk about merging it or anything. no one is opposed to having an android frontend or anything, as long as its well built.
