### ISSUE TITLE
ctm files either record or output wrong inputs, sets input loops when simultaneous inputs occur

### ISSUE THREAD

**Issue by SilverMK** [citra-emu/citra#4318]
So the movie feature either records or outputs the inputs wrong. Whats happening here
https://cdn.discordapp.com/attachments/22074362740162560/498307262700584970/video.mov is that the ctm file seems to save each input in an individual frame instead of fluent, all at once. So when buttons are pressed simultaneously each button press is assigned a frame. Obviously I dont actually know the frame data, but we can randomly assign a guess of accel being pressed frame 1, r being pressed frame 2, and a directional input being pressed frame 3, and ctm takes those inputs as long as they are being pressed simultaneously and outputs them or records them in a loop, hence evidenced in the video with very slow accel, constant hopping, and turning where we can see the ghost on the minimap drifting. I would link the .ctm file here but it wont let me, but this is easily replicated as the same results occur every single time. What we would hope to achieve by fixing this issue is of course .ctm files outputting the correct inputs and accepting multiple simultaneous inputs. Something else concerning we can notice in the video ^there is that even with only one button being pressed a different result is immediately achieved

**Comment by zhaowenlan1779** [comment]
From Discord
```
Silver_MKToday at 10:33 AM
Im having trouble getting it to play the recording from start
zhaowenlan1779Today at 10:34 AM
you need to have the game in your game list
Silver_MKToday at 10:34 AM
How do I do that?
zhaowenlan1779Today at 10:34 AM
add the folder (your mk7  is in) as a game folder?
Silver_MKToday at 10:35 AM
Ive tried to a few times but it gives me an error
zhaowenlan1779Today at 10:35 AM
I just performed a time trial, played the movie back and it exactly matches the ghost data...
Silver_MKToday at 10:35 AM
So I just drag the game file into citra to play
zhaowenlan1779Today at 10:36 AM
what error did you get?
Silver_MKToday at 10:37 AM
Uh
Accidentily clicked out of the error, tried again and it worked

Whelp
Problem solved I guess
zhaowenlan1779Today at 10:38 AM
you should test it again. I think it syncs pretty well on my machine

my skill is shitty though
Silver_MKToday at 10:41 AM
It works perfect
I’ll try again on nightly
```

**Comment by zhaowenlan1779** [comment]
Closing, as this is likely caused due to not using the feature properly.
