### ISSUE TITLE
Citra speeds up to frame limit only when out of focus.

### ISSUE THREAD

**Issue by OverlordDerp** [citra-emu/citra#4319]
I have replicated this issue with every build of Citra Canary from 905 to the current one at the time of writing this (Canary build 937). 

The issue is as follows: If I set the Limit Speed Percent to anything above 100%, it will only reach that limit when the Citra window is out of focus. This limit is irrespective of pressing Ctrl + Z to toggle the speed limit, which as an aside, is not speeding up the game in any of these builds. 

These tests were performed with clean installs of each Canary build, playing the JP version of Dragon Quest Monsters: Joker 3, for retesting purposes.

Operating System: Windows 10 Home
CPU: Intel i5-8300H
GPU: Nvidia GeForce GTX 1050
Citra Version: Citra Canary, all builds from 905-937 inclusive

**Comment by jroweboy** [comment]
check if you have vsync setting enabled in the geforce control panel. another question, do you have a gsync monitor?

**Comment by SleepingSnakezzz** [comment]
This happens when V-Sync is enabled in Citra's setting, or in your GPU driver's setting. This isn't a bug. Closing.
