### ISSUE TITLE
Thread scheduling bugs

### ISSUE THREAD

**Issue by bunnei** [citra-emu/citra#432]
@Normmatt wrote a threading demo (that of which I have not seen the sourcecode for) that tests scheduling, and ran it against Citra, 3dmoo, and hardware. The results are here -> https://gist.github.com/Normmatt/b0a0440c9f55d1b54664

At first glance Citra looks very wrong... But I'm not sure that is true. It looks like there is simply a bug with new threads being immediately switched to, instead of only being switched to on the next qualifying event. If I move the "begins" to happen first for the Citra log, you get:

<pre>Thread 1 begins
Thread 2 begins
Thread 3 begins
Thread 4 begins
Thread 1, count = 0
Thread 2, count = 0
Thread 1, count = 1
Thread 2, count = 1
Thread 1, count = 2
Thread 1 ends
Thread 3, count = 0
Thread 2, count = 2
Thread 2 ends
Thread 3, count = 1
Thread 4, count = 0
Thread 3, count = 2
Thread 3 ends
Thread 4, count = 1</pre>

Which is actually pretty darn close to hardware - so it's probably just a simple fix. I'm going to take the action to go through thread scheduling after @Subv makes his upcoming timing changes, and make it more identical to hardware.

**Comment by purpasmart96** [comment]
Does thread 4 ever end on citra?

**Comment by archshift** [comment]
Is this still an issue?

**Comment by Subv** [comment]
I don't think so, but we'd have to check

**Comment by Normmatt** [comment]
Updated citra.txt with results from latest master.

**Comment by Subv** [comment]
The bug at the beginning (Thread 1 being scheduled twice) happens because we aren't locking the first Event after one of the threads is awoken. This needs some hwtests to verify if the event is locked as soon as the thread is released from wait, or if it remains signaled until the thread actually runs.

**Comment by bunnei** [comment]
Demo -> https://gist.github.com/Normmatt/27557d3cbf45a49080f5
