### ISSUE TITLE
Tomodachi Life - Can't Help With Baby

### ISSUE THREAD

**Issue by death1223** [citra-emu/citra#4320]
When you have a child, there's a random chance to have to take care of the crying baby. When you attempt to help, it soft locks and the baby just sits there crying. You're not able to click on it or anything, whereas you're supposed to be able to tickle it. There's also a peekaboo button which probably calls upon the camera and I pressed that, didn't work either.
Version is [#1039](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1039)
My log file is here 
[citra_log.txt](https://github.com/citra-emu/citra/files/2454403/citra_log.txt)

**Comment by valentinvanelslande** [comment]
Save file: [savedataArc.txt](https://github.com/citra-valentin/citra/files/1628831/savedataArc.txt)

**Comment by death1223** [comment]
What?

**Comment by RocketRobz** [comment]
It's a save file. I think it should be named `savedata.arc`.

**Comment by BrookCh4n** [comment]
excuse me, but the "savedataArc.txt" fix the problem?

**Comment by vvanelslande** [comment]
@BrookCh4n no and it's a 404

**Comment by vvanelslande** [comment]
can be closed
![image](https://user-images.githubusercontent.com/62673824/78622995-388f8980-784c-11ea-9989-02187e875d4d.png)
