### ISSUE TITLE
Pokemon x and y curiosity?

### ISSUE THREAD

**Issue by HackedGameMaker** [citra-emu/citra#4329]
I'm just curious as to why Pokemon x and y don't work for citra yet, I mean weren't they made using the same exact engine as Omega Ruby and alpha sapphire? I know that this question has been asked multiple times but I couldn't find the one that's open so I wanted to ask so someone can just redirect me to the original question. Also coding wise why do you guys think the game doesn't work when others do?

**Comment by MerryMage** [comment]
> weren't they made using the same exact engine as Omega Ruby and alpha sapphire

No. Okay, maybe they are, but at the very least they're using different audio firmware, so there's something different about them.

> I couldn't find the one that's open

The audio firmware issue is documented at #3009.

> Also coding wise why do you guys think the game doesn't work when others do?

Unsupported DSP firmware.
