### ISSUE TITLE
Glitches with the moon in Zelda: Ocarina of Time 3D

### ISSUE THREAD

**Issue by bunnei** [citra-emu/citra#433]
Just thought I'd capture this in case sometime down the road we're having trouble fixing the moon in Zelda. When we first got OoT working, the moon in the title screen looked fine. At the time of this issue post, with the latest upstream/master, the moon looks incorrect. This is very likely due to a very recent CPU change, but because we test every CPU change with valgrind, it could also very easily have just been luck that it looked better before (and therefore a GPU bug). Here's what it looks like with the bug:

![](http://i.imgur.com/mcCnmsB.png)

This branch produces that -> https://github.com/bunnei/citra/tree/pica_progress3c
This branch (the first time we had OoT booting) has no square around the moon -> https://github.com/bunnei/citra/tree/pica_progress3b

**Comment by purpasmart96** [comment]
Also some of the alpha blending and/or alpha testing isn't working at all.

**Comment by archshift** [comment]
I can't reproduce this issue. 

![image](https://i.imgur.com/mGqgAh3.png)

**Comment by purpasmart96** [comment]
@archshift It happens very quickly before it goes away.

**Comment by Subv** [comment]
I can't reproduce it either: http://i.imgur.com/eHddPmx.png

**Comment by bunnei** [comment]
@purpasmart96 is right, it is brief.
@lioncash thinks it might be due to a known issue with VCVTBFI that he plans on addressing

https://github.com/citra-emu/citra/blob/master/src/core/arm/skyeye_common/vfp/vfpdouble.cpp#L1371

Assigning issue to @lioncash to fix the instruction, then we can retest.

**Comment by mattcackles** [comment]
my citra won't run ANY game (including LOZ OOT), do you guys use decrypted roms?

**Comment by Subv** [comment]
Does this still happen?

**Comment by purpasmart96** [comment]
@Subv Yes

**Comment by Subv** [comment]
Does it still happen?

**Comment by purpasmart96** [comment]
@Subv No, this can be closed now.

**Comment by Subv** [comment]
I wonder what fixed it, oh well.

**Comment by purpasmart96** [comment]
@Subv It was fixed awhile ago by you I think. I'm pretty sure it had to do with the z-curve textures
