### ISSUE TITLE
Launching titles with seed crypto fails the first time

### ISSUE THREAD

**Issue by bakugo** [citra-emu/citra#4332]
On the latest nightly (0962AB8), attempting to launch a title with seed crypto (with the correct seed in seeddb.bin) after starting Citra will result in a "your rom is encrypted" message and the error "<Error> core/file_sys/ncch_container.cpp:Load:174: Seed for program 00040000001A7100 not found". Attempting to launch the title (or another seed crypto title) a second time works normally. The same happens for both installed titles and loose ncch files.

Another smaller but possibly related issue: installing a CIA with seed crypto will remove the name/icon in the game list from all previously installed CIAs (including the one being installed) until the emulator is restarted.

**Comment by bakugo** [comment]
Tried again with a clean config/user dir, still happens.
Here's the log: https://pastebin.com/raw/E9vki4Ur

**Comment by bakugo** [comment]
Maybe it's platform specific? I'm using Windows 8.1.
I'll see if I can debug this myself (if I can get citra to build on VS...)

**Comment by bakugo** [comment]
I've found the cause of this issue, but it goes a bit deeper than I was expecting...

It is indeed Windows-specific, it's caused by [this call to `file.Tell()`](https://github.com/citra-emu/citra/blob/0962ab8da93ce84edabb94821897543574cc7164/src/core/file_sys/seed_db.cpp#L37) (which in turn calls `ftello`, which is aliased to `_ftelli64` on windows). `_ftelli64` sometimes incorrectly returns 3 (should obviously be 4 every time) and this breaks all subsequent reads. Seems to only happen if the seeddb file is relatively large (900+ seeds), if I use a seeddb with a single seed in it, it works fine.

This is probably a mingw bug, I've found some mentions of it:
https://sourceforge.net/p/mingw/bugs/2173/
https://sourceforge.net/p/mingw-w64/mailman/message/36082437/

Maybe just using the `ftello` provided by mingw on windows would be a good idea, since it returns the correct value.

**Comment by wwylele** [comment]
That line could change to `file.Seek(SEEDDB_PADDING_BYTES, SEEK_CUR)`

**Comment by bakugo** [comment]
No, `_ftelli64` is the broken one. `ftello` is [aliased to it within file_util.cpp](https://github.com/citra-emu/citra/blob/20e42592ff1b3552fad9be2d45001642db7b2ef4/src/common/file_util.cpp#L27).
But mingw seems to provide its own `ftello` that works normally (at least on my setup).
This would probably break building on VS but that's already broken anyway...

**Comment by wwylele** [comment]
>This would probably break building on VS but that's already broken anyway...
What do you mean by VS is already broken

**Comment by bakugo** [comment]
Maybe it's just me but building on VC (using the exact instructions on the wiki) always fails with a libzmq error, I had to install mingw just to debug this.

**Comment by wwylele** [comment]
@bakugo oh that's an unrelated issue and we are fixing it. I think what you suggested is good (Just don't break MSVC. You can do that by wrapping with #ifdef _MSC_VER). Are you going to PR it?

**Comment by bakugo** [comment]
I don't know much C++ so it's probably a good idea if someone else did it.
