### ISSUE TITLE
Luigi's Mansion, Circle Pad Pro poltergust always enabled

### ISSUE THREAD

**Issue by robzombie91** [citra-emu/citra#4334]
Having the Circle pad pro toggled on always activates the poltergust 3000 which doesnt allow you to have the light to scare the ghosts

**Comment by FearlessTobi** [comment]
Why was this closed?

**Comment by windwakr** [comment]
To add some info to this, I'm assuming he had ZL/ZR bound to something like the analog triggers on a 360 controller. Any button bound to those acts like it's always pressed in.

**Comment by robzombie91** [comment]
ps3 controller via scp toolkit

**Comment by robzombie91** [comment]
and yes it was that was causing the issue

**Comment by FearlessTobi** [comment]
Ah then it's not an issue with the game emulation itself. For the input trigger issue there is already an issue opened on the yuzu Github.

**Comment by robzombie91** [comment]
https://github.com/yuzu-emu/yuzu/issues/1659

for reference
