### ISSUE TITLE
Citra Canary 969 and 970 Pokemon Ultra Sun Dont Load (Stuck on Black Screen)

### ISSUE THREAD

**Issue by Juantlo** [citra-emu/citra#4342]
![aaaa](https://user-images.githubusercontent.com/35728606/46994036-b6ce0c80-d13c-11e8-92ef-9fd0f7f7b577.png)
Citra Canary 969 and 970

**Comment by wwylele** [comment]
Should fixed in 971. Please try it when it is out (soon)
