### ISSUE TITLE
Citra running very slow when hardware shaders enabled on mesa/linux

### ISSUE THREAD

**Issue by Lithium64** [citra-emu/citra#4380]
When you run citra on Ubuntu with the hardware shader turned on and mesa driver, it runs very slow. Disabling the hardware shader will resolve the problem. On windows with hardware shader enabled the emulator runs faster or at least at the same speed.

**My specs:**

i3 4150
R7 260X 2GB
12GB RAM
Ubuntu 18.04 LTS
Mesa 18.2.3
Default Ubuntu kernel

**Comment by wwylele** [comment]
Hardware shader is trading with more GPU resource consumption (or whatever the graphics driver is using) for less CPU resource consumption. It is likely that your mesa driver doesn't support R7 260X, or it doesn't enable for it by default, and it falls back to Intel graphics or software implementation (comparable with integrated graphics on windows).

I am closing this issue as it is not likely citra's problem, as citra can only use what the driver uses. Please come to the forum/discord for further support or look for mesa support.

**Comment by Lithium64** [comment]
@wwylele The driver is working fine and supports my GPU, I play other emulators and PC games perfectly with it. Integrated graphics are disabled, I'm playing using the R7 260X.


> sudo lshw -C display
  *-display                 
       descrição: VGA compatible controller
       produto: Bonaire XTX [Radeon R7 260X/360]
       fabricante: Advanced Micro Devices, Inc. [AMD/ATI]
       ID físico: 0
       informações do barramento: pci@0000:01:00.0
       versão: 00
       largura: 64 bits
       clock: 33MHz
       capacidades: pm pciexpress msi vga_controller bus_master cap_list rom
       configuração: driver=amdgpu latency=0
       recursos: irq:27 memória:e0000000-efffffff memória:f0000000-f07fffff porta de E/S:e000(tamanho=256) memória:f7e00000-f7e3ffff memória:c0000-dffff

**Comment by wwylele** [comment]
Could you upload the log from citra running a game.

**Comment by Lithium64** [comment]
> Could you upload the log from citra running a game.

Here is the log
[citra_log.zip](https://github.com/citra-emu/citra/files/2522097/citra_log.zip)

**Comment by wwylele** [comment]
I'll leave this open as it is undecided which component is responsible for this. However, I still suspect that mesa is just not good as a driver for R7 260X.

**Comment by MojoJojoDojo** [comment]
Wow if mesa is slow its truly a problem with citra.
i get a pretty good perf with it.

**Comment by Lithium64** [comment]
I reported the issue on mesa gitlab, according to my tests it's a performance issue in the driver. Since with the i3 4150 integrated graphics I can play at full speed in the native resolution and I can't do that with the R7 260X which has much more processing power. 
https://gitlab.freedesktop.org/mesa/mesa/-/issues/4041

**Comment by SleepingSnakezzz** [comment]
From the driver issue page linked above, I can see that this issue still isn't resolved. However, as this issue is driver side, and not Citra side, I don't see a purpose in keeping this issue open here. Closing for now.
