### ISSUE TITLE
Swapdoodle - Softlock after loading

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#4388]
![screenshot](https://user-images.githubusercontent.com/22228082/47626117-7fc20880-daf7-11e8-9f71-2a695182f6c7.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/2523532/citra_log.txt)

**Comment by milesthecreator** [comment]
The issue still occurs in latest nightly version, hope this gets fixed someday.

**Comment by milesthecreator** [comment]
While the issue isn't fixed yet.. I found a workaround that bypass the softlock, you'll have to dump friend module savegame from your 3DS and enable "FRD" in LLE services.

**Comment by benderscruffy** [comment]
using the latest nightly it is still an issue

**Comment by ScottNash042** [comment]
this can go ingame now
just check #7252
