### ISSUE TITLE
Runbow Pocket - freezes/crashes in Intro

### ISSUE THREAD

**Issue by MojoJojoDojo** [citra-emu/citra#4397]
The game is  a New 3DS game that happens to not work correctly in the latest Canary/Nightly.
[citra_log.txt](https://github.com/citra-emu/citra/files/2544280/citra_log.txt)

![image](https://user-images.githubusercontent.com/33392696/47943021-ea5eb400-defc-11e8-83a9-4e1a952cb026.png)

**Comment by benderscruffy** [comment]
it is still an issue

**Comment by FearlessTobi** [comment]
Try with N3DS mode enabled.

**Comment by benderscruffy** [comment]
how do i enable n3ds mode ??

**Comment by benderscruffy** [comment]
nope still doesnt work

**Comment by benderscruffy** [comment]
goes ingame now
can be closed
