### ISSUE TITLE
Citra crashes when booting every game

### ISSUE THREAD

**Issue by Narugakuruga** [citra-emu/citra#4416]
- You have provided the version (commit hash) of Citra you are using.
Canary-1040 HEAD-9d67f76

- You have provided sufficient detail for the issue to be reproduced.
When Citra updated from Canary-1037 HEAD-a9337d3 to Canary-1040 HEAD-9d67f76, all games (cci format) crash Citra when I booting them.

- You have provided system specs (if relevant).
Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
NVIDIA GeForce GT 1030 GeForce Game Ready Driver 416.81 - WHQL
Windows 10 Insider Preview Build 18262.rs_prerelease.181012-1414

- Please also provide:
  - For crashes, a backtrace.
Sorry I don't have a log, because I reset Citra settings to default and it never crashes again. But some other users also reported this issue, so I think you can get the log somewhere else.

**Comment by wwylele** [comment]
Likely due to #4406. If this doesn't happen in nightly, please move the report to that PR and close this.

**Comment by Narugakuruga** [comment]
@B3n30 I think I have my citra folder backup, I can always reproduce the crash. Try it.
[Citra crash.zip](https://github.com/citra-emu/citra/files/2567782/Citra.crash.zip)

**Comment by wwylele** [comment]
@Narugakuruga Does it still crash on canary 1041?

**Comment by Narugakuruga** [comment]
@wwylele No, it's fixed.

**Comment by Narugakuruga** [comment]
@wwylele Sorry, I am so stupid.

**Comment by wwylele** [comment]
@Narugakuruga Don't worry. Just be aware next time and everything is fine. I am closing this as it is fixed
