### ISSUE TITLE
Special Character Freeze

### ISSUE THREAD

**Issue by Randomname789** [citra-emu/citra#4420]
I found a Scenario that instantly freezes the game and thought i report it.
Citra Version: Nightly 1095 HEAD-a59920e
System: Windows 7 x64
Game: Pokemon Omega Ruby (possibly any game)

So i changed my keyboard layout from German to English, to improve access to the Hotkeys, It works great but when i press a key for any special character (like <+#-) the game will freeze immediately, everytime. 

I'll attach the log file also.
[citra_log.txt](https://github.com/citra-emu/citra/files/2567723/citra_log.txt)

**Comment by zhaowenlan1779** [comment]
I don't really know what's happening here.

Did you happen to press `/`? that is the Frame Advance hotkey.

**Comment by Dragios** [comment]
Close this since the author does not bother to troubleshoot this issue and there is no update for past 5 months. Most likely this is user error triggering Frame Advance hotkey that halt the game.

**Comment by FearlessTobi** [comment]
I agree with Dragios. If it turns out to be an issue, we can reopen.
