### ISSUE TITLE
Pokémon Super Mystery Dungeon – Major speed fluctuation from Intro to Title Screen

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#4421]
Tested with Citra Nightly 1095. This has happen long time ago but I did not report it.
As you can see on this [video](https://streamable.com/i8lzo) it shows the animation speed fluctuates between fast and slow in a repeating pattern.
[citra_log.txt](https://github.com/citra-emu/citra/files/2568161/citra_log.txt)

For instance Nightly-321 also suffer from this but the reproducibility is not consistent and only affect the intro but not the title screen. So very hard for me to bisect which is the actual cause of this issue. (It could be due to the TCP/UDP connection trying to initiate that causes the lag but this is just wild guess)

First [video](https://streamable.com/27kv4) showing animation speed fluctuate in intro but not in title screen.
Second [video](https://streamable.com/6kdwu) showing all smooth animation in both intro and title screen.
Both are using the same MinGW Nightly build.

**Comment by chris062689** [comment]
Please post your system specs as well as your video settings.

**Comment by Dragios** [comment]
It looks like MSVC build is unaffected by this.
I used the one provided [here](https://ci.appveyor.com/project/bunnei/citra/builds/20149938/job/8aw1m66ntq0idh31/artifacts)

**Comment by wwylele** [comment]
I wonder if this is related to camera / y2r. What is your current camera setting? Is it blank?

**Comment by Dragios** [comment]
My current camera setting is blank for both front and rear,

**Comment by Dragios** [comment]
Retested again with LLE audio emulation and looks perfectly fine other than slow speed.
So only HLE audio is affected by this.

**Comment by Dragios** [comment]
The intro no longer suffers from slow speed but with uncapped frame rate the frame pacing is inconsistent.

**Comment by Dragios** [comment]
Seems like frame pacing issue no longer occur.
