### ISSUE TITLE
Tekken 3D - Prime Edition / Memory leak

### ISSUE THREAD

**Issue by MokuDuk** [citra-emu/citra#4424]
What is workaround? I will appreciate any temporal one:
1. It happens after >50 battles [>50 changed stages loading? >50 AI actors loading?]
2. At the beginning only 2 stages become a little bit slower
3. After every ~10 battles slow arenas become slower, other arenas become affected to.

What I have already tried:
1. Cleaning ram standby list by RAMMap utility
2. Turning on Accurate Geometry shader
3. Turning on both Accurate Geometry shader & Accurate Multiplication
4. Changing sound settings [auto, cubeb, null]
5. Deleting *.info from debugging settings in case of console leakage.
6. Testing with older citra HEAD-54390d5

Log files from recently Nightly 1095:
[citra_log-auto1.txt](https://github.com/citra-emu/citra/files/2568892/citra_log-auto1.txt)
[citra_log-auto2.txt](https://github.com/citra-emu/citra/files/2568893/citra_log-auto2.txt)
[citra_log-auto3.txt](https://github.com/citra-emu/citra/files/2568894/citra_log-auto3.txt)
[citra_log-cubeb.txt](https://github.com/citra-emu/citra/files/2568895/citra_log-cubeb.txt)
[citra_log-cubeb-stretch.txt](https://github.com/citra-emu/citra/files/2568896/citra_log-cubeb-stretch.txt)
[citra_log-null-exit.txt](https://github.com/citra-emu/citra/files/2568897/citra_log-null-exit.txt)
[citra_log-null-occur.txt](https://github.com/citra-emu/citra/files/2568898/citra_log-null-occur.txt)

Configuration:
CPU jit,
![citra configuration 2018-11-11 02 16 05](https://user-images.githubusercontent.com/20445390/48307266-4e672500-e55a-11e8-989a-bc3baa3aba8b.png)

Specs:
1) Pentium G2020 [it's only 2 cores 2,9GHz and citra is amazingly runs on it. Citra rocks!))]
2) Nvidia GT610 [no Vulkan support and still citra is great!]
3) Win7 x64

Extra1:
- I remember exactly the same behavior in ppsspp about 4-5 years ago, when Tekken 6 firstly became playable. Someone of devs who was working at that time fixed it and shared some news about - calling it a memory leakage that was very hard to find. [Already tried to google it. It might be erased or somewhere deep.]

Extra2:
- a game is already wonderful to play. Compared to known Tekken 6 it brings adjusted AI, and firstly in a Tekken series forces a player to train in survival modes under different rules like reduced hp, or only juggle damage. It's Ultra Hard AI, new music, new stages, recreated models, different lighting system, low-polygon style combines all of this in a unique 3ds way

And that is why every citra player will experience slowdowns. There is a lot of 40-battles survival modes, which player will try again & again to accomplish. Also there is 100-battles survival mode which might also lead with game progress to a new one 100-battle survival mode, and a new one.

Right now everything is perfect for 10-stages quick battle [4-5 times] or with combining it with 10-stages survival mode. In case of any long survival 40-battles survival mode it's better firstly to restart an emu.

Extra3:
- after some time will test it in Ubuntu. It's very interesting to know how linux Mesa drivers will behave on specified old hardware.

[probably should have notice that I am foreigner, I am sorry if I said something wrong, I am open for learning, and still improving social and language skills. Thank you for development of 3ds emulator on github!]

**Comment by MokuDuk** [comment]
Have tested a lot, and happy to find
that a new option "clear cache seconds" with a value of 30 seconds
fixes this issue

Found it in SickC builds. Have tested both Generic GCC & Generic LLVM. With GCC resulting smoother framerate on specified hardware [both showing the same game speed/fps ]

I am sure it will help other games too [Etrian Odyssey V and many more]

Settings are:
cpu jit, cubeb output,
![citra configuration 2018-11-19 09 23 33](https://user-images.githubusercontent.com/20445390/48689757-ccaf7100-ebc3-11e8-8355-6715ad7ce079.png)
![citra configuration 2018-11-19 09 22 55](https://user-images.githubusercontent.com/20445390/48689764-d042f800-ebc3-11e8-990f-4945c086aa09.png)

**Comment by MokuDuk** [comment]
@Dragios Ok then (= Reopened an issue, thank you for a reply

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update

**Comment by MokuDuk** [comment]
perfectly playable, performance stopped degrade over time, checked with latest Android Nightly build and last windows 7 version of may today. The only thing missing - are shadows only under characters [other shadows are in place] https://www.youtube.com/watch?v=LuzruNruFO8 quickest way to check is to run on 10 times 10-battle on easiest difficulty, or one 100-battle. Bug was possible to notice >50. Will close
