### ISSUE TITLE
HOME Menu softlocks when selecting theme from a CIA created with Howling Theme Tool

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#4428]
Video: https://streamable.com/0dnld
In the video you can see that selecting a color theme works and the icon of the theme with the issue is not correct.
[citra_log.txt](https://github.com/citra-emu/citra/files/2572771/citra_log.txt)
I'm using BOSS LLE, you can't change theme with BOSS HLE

**Comment by SleepingSnakezzz** [comment]
Due to the age of the issue, and the large changes to our home menu emulation, I'm going to close this now. Feel free to reopen it if the issue still occurs on the latest Citra Nightly build.
