### ISSUE TITLE
Feature request: GPU selection in Graphics settings

### ISSUE THREAD

**Issue by DarthJahus** [citra-emu/citra#4435]
In systems with multiple GPU devices and monitors plugged to more than a GPU, it would be great to choose which GPU is used by Citra.

Windows 10 does have an integrated setting for it (_Display > Graphics Settings > Graphics performance preference_), but it seems that Citra isn't taking it into account.

Instead of that, the emulator simply uses whichever GPU "main" monitor is plugged into (that can be changed from Windows 10 _Display settings > Multiple displays > [x] Make this my main screen_).

What this means is that if you want to run Citra on your external GPU, you have to set the screen attached to that GPU as your main screen, _before_ running Citra. While Citra is open, it's possible to change it back because the program will keep using the GPU it has been opened on.

My request is a parameter in Citra's Graphics settings to choose between available GPU devices. That would be used whenever Citra is running, independently from Windows desktop configuration.

**Comment by zhaowenlan1779** [comment]
Yes, you are correct. Citra would automatically choose your Nvidia GPU if you have one. I don't know how hard it would be to implement GPU selection though, and I'm not sure if we even need this...

**Comment by DarthJahus** [comment]
I am aware that the request only affects a niche, but some players may need to switch the graphics card manually, for example on dual GPU laptops, or simply on desktop computers with many graphics card (which was my case). Moreover, the emulator already allows the selection of audio device.

**Comment by Tekkenlord-X** [comment]
This request was opened on 2018 it is already 2021 and it is still open, please attend to this request, it would be a life saver for many people

**Comment by 28klotlucas2** [comment]
Citra only uses my awful amd gpu instead of my fast intel one.

**Comment by TCAtrevor** [comment]
It seems that #6130 should resolve this since the Vulkan backend will allow you to select which GPU device to use.

**Comment by GPUCode** [comment]
Fixed in https://github.com/citra-emu/citra/pull/6512
