### ISSUE TITLE
[Request] DirectX Video Backends

### ISSUE THREAD

**Issue by ReclaimerShawn** [citra-emu/citra#4463]
Could you all possibly implement DX11 and/or DX12 in the future? It'd likely lead to a lot of framerate and performance boosts for people.

**Comment by FearlessTobi** [comment]
I don't think DirectX will ever get implemented cause it's Windows specific and we don't have any devs that know how to use that API. It simply wouldn't be worth the effort to learn it and then invest thousands of hours into writing the code for it, without even knowing if it really would boost performance. 
I think even a Vulkan backend is more likely to get implemented into Citra than a DirectX one.

Closing.

**Comment by ReclaimerShawn** [comment]
Glad that I have an NVIDIA Card then. Vulkan would be nice.
