### ISSUE TITLE
Camera doesn't work in Flatpak

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#4482]
Hi I am running Citra Nightly (1136) in flatpak with a USB Camera on Ubuntu Budgie 18.10. The Camera works perfectly in Firefox but in Citra I get the following error message in the terminal: CameraBin error: "GStreamer error: negotiation problem."

To reproduce: Install Citra in Flatpak. Open Citra and go to Emultion > configure > System > Camera. Change the image source to System Camera (qt) and then click the button "click to preview". Watch as a black screen appears and the error message in the terminal window.

**Comment by bscubed** [comment]
Camera is working fine for me with my laptop's integrated webcam in Citra Nightly 1156. Flatpak has the necessary camera permissions. Could you test using the [latest non-flatpak Linux tarball](https://github.com/citra-emu/citra-nightly/releases/download/nightly-1156/citra-linux-20181217-29548bb.tar.xz) and confirm that this is a Flatpak specific issue?

**Comment by TheSIlentLink** [comment]
I would love too but unfortunately the tarball doesn't run on my system. ./citra: error while loading shared libraries: libsndio.so.6.1: cannot open shared object file: No such file or directory and version 6.1 of libsnidio isn't in the ubuntu 18.10 repositories.

**Comment by bscubed** [comment]
Just to make sure this isn't some one-off thing, there's a couple things you could do to help me solve this issue:

1. Test the USB webcam on another machine running Citra
2. Test the same webcam on another Citra platform (Windows, non-flatpak Linux, Mac, etc.)
3. See if another USB webcam works

Chances are, this could be a larger issue involving compatibility between Citra and your specific webcam. What kind of webcam is it and what's its device ID when you enter `lsusb` from the command-line?

**Comment by TheSIlentLink** [comment]
The Device id is: Bus 001 Device 002: ID 046d:08da Logitech, Inc. QuickCam Messanger. I shall try another platform and report back if it works. I can't test another camera as I don't have any other.

**Comment by TheSIlentLink** [comment]
I can confirm that the camera works in Windows 10 using Citra Nightly 1159

**Comment by SleepingSnakezzz** [comment]
This doesn't appear to be an issue on the latest Citra Nightly. Closing for now.
