### ISSUE TITLE
Citra Nighyly Build 1140 Black Screen issue

### ISSUE THREAD

**Issue by fazzal95** [citra-emu/citra#4486]
Pokemon X and Y keep blacking out after the intro menu it seems to be the issue after all the updates

**Comment by zhaowenlan1779** [comment]
This is an issue tracker for developers. For support please use our [forums](https://community.citra-emu.org) or [Discord](https://citra-emu.org/discord).

And, Pokemon X and Y currently do not work on Citra yet. You can check for their status [here](https://citra-emu.org/game/pokemon-x/).
