### ISSUE TITLE
nothing in graphics settings

### ISSUE THREAD

**Issue by Sagametroid** [citra-emu/citra#4487]
setting spanish language and choosing "graphics" nothing appears. but choosing english works without problems

Using Latest canary (1108)

![graphics](https://user-images.githubusercontent.com/38576597/49557384-6f126880-f8d5-11e8-980c-1eea9e86de72.PNG)

**Comment by zhaowenlan1779** [comment]
This was caused by #4437, should be fixed now.
If not please leave a comment and I'll reopen
