### ISSUE TITLE
[Feature request] Mod Support

### ISSUE THREAD

**Issue by RicBent** [citra-emu/citra#4488]
Mod support just like Yuzu has it for redirecting individual files from the romfs or the entire container.
Also support for redirecting code.bin and exheader.bin would make the life of modders way simpler.

**Comment by saphtea** [comment]
This would be awesome to see and could help with some of the modding scenes around 3DS games, especially to give it some afterlife :). Can the system implemented in Yuzu be ported over at all or would it have to be from scratch?

**Comment by leoetlino** [comment]
Overriding code.bin is already possible (#2975), but not exheader at the moment.

It should be very easy to add support for exheader.bin replacement (and in fact I already have a patch doing this) but I don't know if we should be looking for the exheader in .exefsdir/ (as with the other exefs files) or somewhere else.
