### ISSUE TITLE
[Audio LLE related] Audio stretching causes audio dissapears randomly

### ISSUE THREAD

**Issue by Narugakuruga** [citra-emu/citra#4495]
Game: Monster Hunter XX
Version: Canary 1116 d9b4a36
How to reproduce it: Walk in Yukumo village.
When audio dissapears, the emulation speed gets a boost.
Both Citra and the game audio settings were set to stereo. Cubeb backend.
[2018-12-09 13-37-34_audio_index0.zip](https://github.com/citra-emu/citra/files/2660260/2018-12-09.13-37-34_audio_index0.zip)
Audio sample is provided.

**Comment by wwylele** [comment]
If this is a LLE-only issue, please report under the LLE PR.
