### ISSUE TITLE
Pokémon X/Y - Black background at rival's introduction

### ISSUE THREAD

**Issue by lightgod87** [citra-emu/citra#4499]
Hi, guys.

Here's another issue for you, guys. This is regarding the rival's first appearance in-game, as the background appears incomplete. May be related with the black face issue, and if you select the female character, the male rival appears with black squares in this part as well.

![c92069743b207e364e97ee115cdca02a](https://user-images.githubusercontent.com/28798472/49771677-3a792500-fcb8-11e8-9f32-c79166bd14bb.png)

I didn't see this issue up in the rep, so I'll put it. Here's the log.

[citra_log.txt](https://github.com/citra-emu/citra/files/2665560/citra_log.txt)

My system specs:

Intel Core i7-8700
16 GB DDR4 RAM
Nvidia Geforce GTX 1070 Ti
Windows 10

And the version in which I evidenced this was in Citra Canary 1119.

Thanks in advance.

**Comment by wwylele** [comment]
How does it look like with different options, like hardware renderer and/or hardware shader?

**Comment by tgsm** [comment]
Reference for what it is supposed to look like:
![2018-12-10_20-39-39 844_top](https://user-images.githubusercontent.com/11739422/49772711-4830a980-fcbc-11e8-91dc-c0eb01bd3381.png)

This seems to happen on every configuration, however I couldn't test software renderer because it would crash Citra every time I tried to do anything in the game.

**Comment by lightgod87** [comment]
Just to show that both issues happen at the same time (black boxes at the male rival, and the lack of a background), here's the log and image.

![7266e5c99b6c48e0048c5aaf51f9e5f7](https://user-images.githubusercontent.com/28798472/50046519-ba194200-0072-11e9-8d40-f05afb6409c3.png)

And here's the Citra log, this time in Canary 1125 with the HLE implementation.

[citra_log.txt](https://github.com/citra-emu/citra/files/2682984/citra_log.txt)

**Comment by Tabish4675** [comment]
Additional info. - Same black background issue is seen in various other parts of the game too. Such as when seeing the fireworks with Shauna and when the Lumiose City tower lights up.

**Comment by bamikhan** [comment]
Guys,has a solution to this problem been found out yet?
If not,do you think this problem will be fixed by Citra anytime soon?

**Comment by Tabish4675** [comment]
It will be available... But I don't think it will be anytime soon as it doesn't hinder the gameplay in any way. @bamikhan

**Comment by Kanjiro123** [comment]
![Screenshot_2020-04-11-19-49-37-28_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/63500565/79044461-d1048000-7c37-11ea-91b1-be056feb17ac.png)
Does anyone know how to fix this? Please help.

**Comment by B3n30** [comment]
This is an issue tracker for development, not a support forum. 
If you need help ask ind discord or the forums.
(though, you are using an unofficial build, so don't expect too much help)

**Comment by JohelEGP** [comment]
> Additional info. - Same black background issue is seen in various other parts of the game too such as when seeing the fireworks with Shauna and when the Lumiouse City tower lights up.

I don't think I had problems during the fireworks. I haven't reached the other part you mention yet.

**Comment by KostaSaizo7** [comment]
Latest canary+no outlines
Serena and Shauna look their best
![xy](https://user-images.githubusercontent.com/39852873/227587746-caf34a89-16b1-472e-a1eb-ad695f8485d6.png)
