### ISSUE TITLE
After changing graphics settings while game runs, hotkeys become unavailable

### ISSUE THREAD

**Issue by Narugakuruga** [citra-emu/citra#4501]
Canary 1119 a9a83f6 Windows 10
After changing graphics settings while game runs, hotkeys become unavailable. For example, F9 and F10 can't change screen layout, Ctrl+Z can't unlock speed limit.

**Comment by adityaruplaha** [comment]
You're using an older version. Please retest on the latest version.

**Comment by zhaowenlan1779** [comment]
Thanks for your report!

However, please report this in #4437 instead as that PR is not merged yet

**Comment by Narugakuruga** [comment]
Okay.
