### ISSUE TITLE
[gdbstub] Memory breakpoints do not work and corrupt memory when used

### ISSUE THREAD

**Issue by viocar** [citra-emu/citra#4502]
Version: HEAD-65d62b1 (2018-12-12)

The following was tested using both IDA Pro 6.8 and arm-none-eabi-gdb with identical results.

If a memory breakpoint is set and execution is resumed then paused, the location where the breakpoint was set will be corrupted, leading to incorrect behaviour or game (not Citra) crashes. In neither of my examples is execution paused by the memory breakpoints as expected; all breaks here were manually triggered using ctrl+c. 

```
(gdb) x/4xb 0x81a4008
0x81a4008:      0x82    0x62    0x82    0x99
(gdb) awatch *0x81a4008
Hardware access (read/write) watchpoint 5: *0x81a4008
(gdb) c
Continuing.
Cannot access memory at address 0x1

Program received signal SIGTRAP, Trace/breakpoint trap.
0x001004d0 in ?? ()
(gdb) x/4xb 0x81a4008
0x81a4008:      0x70    0x00    0x20    0xe1
```

The contents at our memory address have been replaced with 70 00 20 E1. I get this value every time I corrupt memory, but I only tested with one game - perhaps it's different depending on which game you're debugging. Removing the `awatch` does not restore our memory values. If we use the `rwatch` command instead of `awatch`, we get this instead:

```
(gdb) x/4xb 0x81a4158
0x81a4158:      0x82    0x73    0x82    0x8f
(gdb) rwatch *0x81a4158
Hardware read watchpoint 6: *0x81a4158
(gdb) c
Continuing.
Cannot access memory at address 0x1

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00157554 in ?? ()
(gdb) x/4xb 0x81a4158
0x81a4158:      0x82    0x73    0x82    0x8f
```

While this appears to be correct behaviour, the behaviour exhibited in-game indicates that the memory is still being corrupted. However, unlike with `awatch`, if the `rwatch` is removed, the memory will return to normal and the corrupted behaviour stops (assuming other parts of the game state weren't corrupted as a result).

**Comment by viocar** [comment]
Ah, right. I knew it looked like an instruction, but when I looked it up, I got "ANDVC R2, R0, R1, ROR #1", which didn't seem like anything. If it's actually "bkpt 0", then that's definitely a clue. Is it placing an execution breakpoint when you tell it to use a memory breakpoint?

**Comment by hax0kartik** [comment]
I think so, not entirely sure.

**Comment by viocar** [comment]
Thanks for looking into it! It seems like fixing the crash bug is fairly straightforward, but we're still missing a piece of the puzzle for making it work correctly. Could you PR it? I don't have a working copy of the project right now.

**Comment by viocar** [comment]
https://github.com/citra-emu/citra/pull/4651 Fixes this.
