### ISSUE TITLE
[Monster Hunter XX] Frame rate drops when in certain areas

### ISSUE THREAD

**Issue by Narugakuruga** [citra-emu/citra#4504]
Tested in nightly-1146 and canary-1121. Set internal resolution to 2x or higher, in some special cases (using flash bomb or meet some monsters), frame rate will drop. Changing hardware shader settings will influence framerate as well.
Tested Canary-1000, the issue doesn't occur.
PC 1(The frame rate is much lower than Canary-1000):
Windows 10 Insider Preview 18298
Intel Core i5-8400
NVIDIA GTX 1050Ti
8G DDR4 RAM
PC 2(resolution set to 2x, frame time is 16ms, but I think it should have been lower.):
Windows 10 1803
Intel Core i3-6100
Intel HD Graphics 530
8G DDR4 RAM
PC3 (reported by my friend)
Windows 10
Intel Core i5-4200H
NVIDIA GTX 950M
8G RAM

**Comment by tywald** [comment]
This is due to the absent of #4089 which was taken out since Canary 1042. Canary 1041 is the last version with this change.

**Comment by Dragios** [comment]
Fixed by PR #5170 , I guess.
