### ISSUE TITLE
Why all amiibo file are read as mario amiibo in citra

### ISSUE THREAD

**Issue by Darth-Koopa** [citra-emu/citra#4506]
Issue:
All amiibo in Mini Mario & Friends: Amiibo Challenge are read as mario amiibo. It is not a bug caused by the version of citra since I tried many versions, not caused by amiibo file since other games played by citra can distinguish them.
System Information

Operating System: Windows 10
CPU: Intel® Core™ i7-5500U CPU @ 2.40GHz
GPU: AMD Radeon R7 M270 & Intel® HD Graphics 5500
Citra Version (found in title bar): any version that supports amiibo
Game: Mini Mario & Friends: Amiibo Challenge
Diagnostic Log
Upload your log file as an attachment by dragging & dropping.
https://community.citra-emu.org/uploads/default/original/2X/d/d7ba82f79e5aec811d9100ffab9d7abefc69a29e.txt

**Comment by FearlessTobi** [comment]
Relevant part of log: 
`[  91.754017] Service.NFC <Warning> core/hle/service/nfc/nfc.cpp:GetTagInfo:134: (STUBBED) called
[  91.757199] Service.NFC <Warning> core/hle/service/nfc/nfc.cpp:LoadAmiiboData:179: (STUBBED) called
[  91.758432] Service.NFC <Warning> core/hle/service/nfc/nfc.cpp:GetAmiiboConfig:149: (STUBBED) called
[  91.759281] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:162: unknown / unimplemented function 'GetAmiiboSettings': port='nfc:u' cmd_buf={[0]=0x170000}
[  91.759974] Service.NFC <Warning> core/hle/service/nfc/nfc.cpp:GetAmiiboConfig:149: (STUBBED) called
[  91.837867] Service.NFC <Warning> core/hle/service/nfc/nfc.cpp:StopCommunication:91: (STUBBED) called
[  91.838020] Service.NFC <Warning> core/hle/service/nfc/nfc.cpp:Shutdown:75: (STUBBED) called, param=2`

Will look into this eventually.

**Comment by Shideravan** [comment]
This happen in other games for me too...
I checked in Super Smash Bros. and Yoshi's Wooly Wold, but I'm sure that's will happen in more games

**Comment by FearlessTobi** [comment]
@Darth-Koopa @Shideravan Please retest on latest Canary or Nightly.

**Comment by Darth-Koopa** [comment]
The amiibo problem is solved in the latest verson, but there is a new issue: when a toy is sliding on any steep hill, the game clash while the BGM continues

**Comment by Darth-Koopa** [comment]
The log says: HW.GPU <Error> video_core/command_processor.cpp:WritePicaReg:127: Commandlist tried to write to invalid register 0x1055A (value: 00000000, mask: 0)
