### ISSUE TITLE
Linux flatpak bug: Citra Canary 1127 crash upon loading ROMs

### ISSUE THREAD

**Issue by MaCroX95** [citra-emu/citra#4510]
Since I updated Citra canary to version 1127 crashes upon launching any ROM on Linux, it worked without any problems before. I am using the official flatpak version on Linux. Bug can be reproduced every time when trying to load ROMs

System specs:
- Citra versions: 
     Citra Canary 1127 (HEAD-ab466dc86 (2018-12-15)
     Citra Nightly 1151 (HEAD-d2003dae (2018-12-15)
- MSI B150 Gaming M3, Intel Core i5 6600, Nvidia GTX 970
- Kernel version: 4.19.8-arch1-1-ARCH
- Antergos Linux with flatpak configured (shouldn't matter, flatpaks are universal)
- Nvidia-415.23 driver

When launching the emulator from terminal this is the output I get when I open the emulator and then try to load the ROM and emulator crashes:

flatpak run org.citra.citra-canary

Gtk-Message: Failed to load module "canberra-gtk-module"
QApplication: invalid style override passed, ignoring it.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
No XVisualInfo for format QSurfaceFormat(version 3.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 0, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(CoreProfile))
Falling back to using screens root_visual.
Could not initialize GLX

**Comment by liushuyu** [comment]
I can think of the following possibilities:

1. NVIDIA driver issue. (Try recompiling DKMS modules? Also, check for `dmesg` )
2. You are using an icon pack or theme that is screwing up things (See https://github.com/daniruiz/flat-remix/issues/72 )
3. A library, or a script set to intercept OpenGL calls, check `LD_PRELOAD` environment variables if this one contains anything

You can diagnose further by:
1. Check if PPSSPP using OpenGL rendering engine works on Flatpak (https://flathub.org/apps/details/org.ppsspp.PPSSPP)
2. Use another theme or default GTK theme with stock icon pack
3. Reset your environment variables

**Comment by MaCroX95** [comment]
I think that I've found out what the trouble is... The system Nvidia-driver is 415.23 and flatpak uses: org.freedesktop.Platform.GL.nvidia-415-22/x86_64/1.4
org.freedesktop.Platform.GL32.nvidia-415-22/x86_64/1.4

Apparently the problem is fixed when they update the driver in flatpak repos... I don't know who thought this would be a good idea though... to ship even such basic things as GPU drivers as flatpak packages and if they're out of sync (which probably will happen a lot across all distros) all the software that uses OpenGL or Vulkan is broken for the timebeing... GJ Flatpak devs

**Comment by FearlessTobi** [comment]
Closing as it's not really a bug on our side and we can't do much about it.

**Comment by bscubed** [comment]
The only possibility to fix this on our side would be to bundle NVIDIA drivers with the flatpak which would be problematic for a few reasons:

1. Significantly larger package size
2. Not all users use NVIDIA graphics
3. Would likely cause even more conflicting driver issues

Unless a more reasonable solution is found, all we can do is wait for flatpak to update it on their end, unfortunate as it is.

**Comment by MaCroX95** [comment]
> The only possibility to fix this on our side would be to bundle NVIDIA drivers with the flatpak which would be problematic for a few reasons:
> 
>     1. Significantly larger package size
> 
>     2. Not all users use NVIDIA graphics
> 
>     3. Would likely cause even more conflicting driver issues
> 
> 
> Unless a more reasonable solution is found, all we can do is wait for flatpak to update it on their end, unfortunate as it is.

I absolutely agree, updates have been pushed to flatpak repos and everything works as expected now... it is a terrible system to couple drivers with the packaging format ignoring the drivers already installed on the PC, but I can also see why it would be good (so they are universally configured etc across all distributions) but the downside is, if your system's driver version doesn't match the flatpak one, all OpenGL/Vulkan software stops working. It is what it is I guess... for better or for the worse
