### ISSUE TITLE
HLE AAC codec not found because avcodec_register_all is not called

### ISSUE THREAD

**Issue by Zombie-Feynman** [citra-emu/citra#4518]
Having just compiled [citra-canary 9224b4cab8a739569410af93b1a4bbe91e922eb6](https://github.com/citra-emu/citra-canary/tree/9224b4cab8a739569410af93b1a4bbe91e922eb6) on Gentoo, I found that AAC HLE did not work because the codec could not be found. A quick test program revealed that the codec is installed properly on my system, but Citra could not find it because it doesn't call `avcodec_register_all` before `avcodec_find_decoder`. Relevant packages used are ffmpeg-3.3.6 and fdk-aac-0.1.5.

A very quick-and-dirty patch fixes this, though I'm sure someone more familiar with Citra's code can figure out a better place to put the missing line:
```
--- src/audio_core/hle/ffmpeg_dl.h.old  2018-12-17 23:14:16.618582043 +0100
+++ src/audio_core/hle/ffmpeg_dl.h      2018-12-17 23:15:28.316260697 +0100
@@ -72,7 +72,8 @@
 const auto av_parser_parse2_dl = &av_parser_parse2;
 const auto av_parser_close_dl = &av_parser_close;
 
-bool InitFFmpegDL() {
+inline bool InitFFmpegDL() {
+    avcodec_register_all();
     return true;
 }
```

**Comment by jroweboy** [comment]
Thanks for looking into this! The AAC decoder is still only a PR at this point, it'd be great if you can put this comment on the appropriate pr #4508 so we can track the issue there. We prefer to reserve the issues for things that have actually been merged 👍
