### ISSUE TITLE
Pokedex 3D Pro is all sorts of broken

### ISSUE THREAD

**Issue by WilliamHCarter** [citra-emu/citra#4525]
Tested in nightly-1161. The game seems to be functioning in some way, as navigation through some controls is possible, but graphically there are major issues. character sprites are far too large and flash sporadically, the title is halfway off of the screen, etc. Decided to post as an issue due to the scope and unusual nature of the glitches. 

PC:
Windows 10
Intel i7-6500U
Intel HD Graphics 520

![citra-qt_gs61jftnno](https://user-images.githubusercontent.com/41378465/50376341-ecc6bb80-05d9-11e9-9d56-85c9e3ac420d.png)
![citra-qt_q3ybk2fcz9](https://user-images.githubusercontent.com/41378465/50376342-ecc6bb80-05d9-11e9-85d7-6e2450ae6878.png)
![citra-qt_s9ojmcmgfl](https://user-images.githubusercontent.com/41378465/50376343-ecc6bb80-05d9-11e9-963d-cfc52f7e1db3.png)
![citra-qt_ewn7rymvve](https://user-images.githubusercontent.com/41378465/50376344-ecc6bb80-05d9-11e9-87e0-efd6d6e6c6fb.png)
![citra-qt_l5kfgvh2j6](https://user-images.githubusercontent.com/41378465/50376366-023be580-05da-11e9-99d1-fb1b52f25b5e.png)

**Comment by FearlessTobi** [comment]
Your issue is missing a log file.

**Comment by valentinvanelslande** [comment]
try disabling hardware shaders

**Comment by WilliamHCarter** [comment]
oh, yep. Disabling hardware shaders does the trick. my b.
