### ISSUE TITLE
Graphical and Performance problems on Zelda Triforce Heroes and Between Worlds

### ISSUE THREAD

**Issue by Naivy-dev** [citra-emu/citra#4529]
Pc specs:
CPU: AMD FX 8320
GPU: AMD HD RADEON 6850
RAM: 8gb

Im having trouble in Zelda Triforce Heroes and Zelda Between worlds.
The graphics issue happens when i enable Hardware Shader (Just like the screenshot), and the performance is always beyond 23-29 fps, it doesn't matter if i try a lower resolution, when i tried in other pcs with i5 or i7 it worked pretty well, without graphical issues and low fps.
Is there a way to fix it? i would be very thankful...

![image](https://user-images.githubusercontent.com/4467292/50428733-02b9d200-08a1-11e9-9b2b-f7b64466f5d3.png)

![image](https://user-images.githubusercontent.com/4467292/50428904-26c9e300-08a2-11e9-913a-a0188f01b0c2.png)

![image](https://user-images.githubusercontent.com/4467292/50428941-62fd4380-08a2-11e9-8c28-8253afde9f37.png)
(when i disable the Hardware Shader, solves the graphical problem, but the performance is the same)

**Comment by SleepingSnakezzz** [comment]
This shouldn't be an issue in the latest Citra Nightly builds. Closing for now. If the issue *does* persist for you, please reopen the issue and add a log file: https://community.citra-emu.org/t/how-to-upload-the-log-file/296
