### ISSUE TITLE
Debug Button

### ISSUE THREAD

**Issue by RicBent** [citra-emu/citra#4536]
When connected to the debugger you can "press" the debug button on debug units there.

The bitmask of that button is 0x1000 for PadStatus or 
`BitField<12, 1, u32> dbg;`
here: https://github.com/citra-emu/citra/blob/master/src/core/hle/service/hid/hid.h#L55

Would be useful for testing dumped betas or for testing homebew.

**Comment by wwylele** [comment]
Could you provide some homebrew example that uses this?

**Comment by RicBent** [comment]
Sure:

Source: http://ricbent.nhp.sh/data/dbg-button-main.c
3dsx: http://ricbent.nhp.sh/data/dbg-button.3dsx

**Comment by RicBent** [comment]
This is implemented in pull request https://github.com/citra-emu/citra/pull/4537.

**Comment by mariomadproductions** [comment]
@RicBent Do you know any retail games or protos that use this?

**Comment by RicBent** [comment]
Sorry, no idea.
