### ISSUE TITLE
[Feature Request] Hybrid Screen

### ISSUE THREAD

**Issue by RyanBram** [citra-emu/citra#4542]
Hi developers.

One disadvantages when playing DS or 3DS in laptop is because laptop use landscape view while the combination of two 3DS screen will resulting portrait view. It leaves many wasted black screen in laptop which give impression that the screen looks small.

One of the nice features from DeSmuME Core in RetroArch is Hybrid Screen. It use unused screen area to show the entire DS Screen, so user can see the whole DS experience while enjoying bigger resolution for one of its screen. The Hybrid Screen can be illustrated as this:

![desmume 360x](https://user-images.githubusercontent.com/4508389/41812537-e1561f58-774e-11e8-9d46-ffeb07abebfd.png)

This hybrid method will have at least 3 advantages:
1. We can see the full experience of 3DS screen while enjoying bigger screen preview,
2. It looks symmetrical that give impression that the entire laptop screen has filled with game display.
3. The zoomed screen can be swapped by hotkeys.

This is one of mock up that I made from FE Awakening.
![citra](https://user-images.githubusercontent.com/4508389/50570196-2c4b8f80-0db2-11e9-9488-75357bd94b15.png)

Thank you for your attention.

**Comment by JohelEGP** [comment]
The actual geometry isn't that symmetrical.
![1617498793](https://user-images.githubusercontent.com/21071787/113495754-7526ad00-94c1-11eb-8782-cbfe1ab3fab5.png)

**Comment by foolmonkey** [comment]
Seconding this! Would love this feature.

**Comment by esliwka** [comment]
Hey, I've started working on that, does it look ok like that? 
![image](https://github.com/citra-emu/citra/assets/55389619/a321bde8-8ffc-4ae0-88de-d4daa09de70a)
Also should it support `Rotate Upright` and `Swap Screens` options?

**Comment by NineKain** [comment]
Looks really good!!

**Comment by esliwka** [comment]
Here it is with swapped zoomed screen:
![image](https://github.com/citra-emu/citra/assets/55389619/7122bc19-6ceb-412b-b9bb-3fb0ed4a3c9f)

**Comment by foolmonkey** [comment]
> Here it is with swapped zoomed screen:
> ![image](https://user-images.githubusercontent.com/55389619/243335024-7122bc19-6ceb-412b-b9bb-3fb0ed4a3c9f.png)

Looks great!
