### ISSUE TITLE
Joker codes using Start don't work properly when pressing circle pad directions

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [citra-emu/citra#4544]
I am playing Pokemon Ultra Moon (with update v1.2) via Citra Nightly 1167, and noticed that when using a joker code that involves pressing the Start button (e.g.: "No encounter, Start for instant encounter"), doing so while pressing any direction on circle pad cancels out the Start button being detected.  The code "(Hold START and Open OPTIONS menu)Access the PC from anywhere" works fine, as it doesn't require pressing a direction on the circle pad.

**Comment by chris062689** [comment]
How are you pressing the buttons?
Via a controller or keyboard / mouse?
Is it a wireless keyboard mouse, USB based, or laptop? 

Some computers have functionality where it locks the mouse if you currently are pressing keys. 

Some keyboards do not response to more than a certain number of keys being pressed at once.

**Comment by M1CR0H4CK3R** [comment]
I'm using a controller, and mapped the buttons properly via the Controls menu.

**Comment by M1CR0H4CK3R** [comment]
I'm using a Desktop PC, my mouse is is wireless, my keyboard is USB, and my controller is USB.

**Comment by M1CR0H4CK3R** [comment]
The code for an unupdated version of Ultra Moon is as follows:
[No Encounter, Hold START Instant Encounter v1.0]
5807E24C E3A00064
0807E244 E3A09000
DD000000 00000008
0807E244 E3A09064
D0000000 00000000
D0000000 00000000

**Comment by Salijour** [comment]
Gateway cheat engine is sensitive about button combos. Also stacking codes to the same key is probably the problem. 
The line that dictates the key press is:
DD000000 00000008

As I don't have the game and I don't know the control scheme of the game I am going to list three different button combinations to replace start with.
00000003 A+B
00000201 L+A
00000102 R+B

Replacing that line with DD000000 00000201 will make it L+A to activate the code.

**Comment by M1CR0H4CK3R** [comment]
I'll try it with just L and let you know what happens.

**Comment by M1CR0H4CK3R** [comment]
I might have figured it out - I think the 'Full Terminator' (Codetype D2) doesn't work properly. I modified some of the codes that I added to make them shorter by changing instances of double 'D0000000 00000000' to 'D2000000 00000000', and the code I replied with above was one of those. I'm about to test now.

**Comment by M1CR0H4CK3R** [comment]
I think I figured it out (hopefully for real this time). It's a conditional nesting issue. For some reason, nesting a conditional code inside a joker code works, but not the other way around. Editing the code to this makes it work properly:

[No Encounter, Hold START Instant Encounter v1.0]
5807E24C E3A00064
0807E244 E3A09000
D0000000 00000000
DD000000 00000008
5807E24C E3A00064
0807E244 E3A09064
D0000000 00000000
D0000000 00000000

Hopefully this can be fixed in the next Nightly.

**Comment by M1CR0H4CK3R** [comment]
Can I create a new issue with the (now determined) bug?

**Comment by zhaowenlan1779** [comment]
> both use the same flag, but for joker codes, state.if_flag is incremented by 1, which I assume means 'apply 2 end-ifs for joker codes instead of 1',

No, that's not true. that `if_flag` means "whether if conditons have failed". if `if_flag > 0` we would skip the code (and incrementing `if_flag` on condition code). on `endif`s we will decrease if_flag by 1. On full terminator the `if_flag` is reset.

**Comment by zhaowenlan1779** [comment]
I took some time to investigate this. From what I see I don't believe there's an actual issue with how Citra executes the codes.

The code `No Encounter, Hold START Instant Encounter` works like this: You have to go into another screen (for example the party screen, or any battle, etc) and back to the world while holding START to get encounters, or while not holding START to prevent encounters.

Both the original code and the version you posted here works the same, and I got similiar behavior on a real 3DS too.

**Comment by M1CR0H4CK3R** [comment]
> I think I figured it out (hopefully for real this time). It's a conditional nesting issue. For some reason, nesting a conditional code inside a joker code works, but not the other way around. Editing the code to this makes it work properly:
> 
> [No Encounter, Hold START Instant Encounter v1.0]
> 5807E24C E3A00064
> 0807E244 E3A09000
> D0000000 00000000
> DD000000 00000008
> 5807E24C E3A00064
> 0807E244 E3A09064
> D0000000 00000000
> D0000000 00000000
> 
> Hopefully this can be fixed in the next Nightly.

Why does the code work properly (you can move while holding Start to trigger an encounter) when using the quoted code, but it won't activate while moving (although opening menus works as you said above) for the code in comment 5? You might want to double-check using the same version It is definitely a nesting issue, either that, or something internally regarding Gateshark support is completely borked up.

Also, on hardware, the original code allows moving while holding Start to trigger encounters. I have used it many times on actual hardware, so I know it works like that, at least with CTRPF-AR. I never use newer Luma's built-in cheat functionality, since many code types are unsupported on it.

**Comment by zhaowenlan1779** [comment]
> Why does the code work properly (you can move while holding Start to trigger an encounter) when using the quoted code, but it won't activate while moving (although opening menus works as you said above) for the code in comment 5?

For me either doesn't work properly. The code also doesn't work with luma.
