### ISSUE TITLE
Beyblade Burst 3DS Japanese password not working.

### ISSUE THREAD

**Issue by InazumaFreak** [citra-emu/citra#4547]
So I was playing Beyblade burst on citra and I thought lemme put my jpn password and unlock lui, but citra says the password is too long even though it is 7 alphabets idk if it is just the jpn language but hopefully someone can fix this bug because it should be able to just go through and activate the battle.

**Comment by wwylele** [comment]
https://github.com/citra-emu/citra/blob/1de63f9b167a475587ff57b0e0180db99561c8b7/src/core/frontend/applets/swkbd.cpp#L56

This line is wrong. It takes string encoded in UTF-8 to check the length, where a japanese character would occupy 2~3 bytes.

**Comment by InazumaFreak** [comment]
> [citra/src/core/frontend/applets/swkbd.cpp](https://github.com/citra-emu/citra/blob/1de63f9b167a475587ff57b0e0180db99561c8b7/src/core/frontend/applets/swkbd.cpp#L56)
> 
> Line 56 in [1de63f9](/citra-emu/citra/commit/1de63f9b167a475587ff57b0e0180db99561c8b7)
> 
>  if (input.size() > config.max_text_length) { 
> This line is wrong. It takes string encoded in UTF-8 to check the length, where a japanese character would occupy 2~3 bytes.

Im sorry I don't know what theat means.

**Comment by legoj15** [comment]
It means that instead of counting each letter as a character, it counts the bytes to determine the amount of Japanese letters, which is an issue because Japanese characters usually occupy more than one byte, so lets say the max amount of letters is 10, and you put in 5 Japanese letters, then you could possibly already be over the max amount of bytes even though you've only typed 5 characters out. That line of code has to be changed by someone who has the time and knowledge of that area to fix this bug.

**Comment by liushuyu** [comment]
There is a simple code block counting Unicode codepoints by finding codepoint boundaries: https://gist.github.com/Inndy/10484418

**Comment by wwylele** [comment]
@liushuyu I doubt that 3DS has full UTF-16 support though. It is likely that it just support UCS-2 (every character is 2 bytes), so IMO `UTF8toUTF16(...).size()` is acceptable

**Comment by wwylele** [comment]
Fixed by #4668

**Comment by oJiroz** [comment]
How do I find the code for Lui I've searched for 5 days now and nothing please someone help

**Comment by oJiroz** [comment]
> So I was playing Beyblade burst on citra and I thought lemme put my jpn password and unlock lui, but citra says the password is too long even though it is 7 alphabets idk if it is just the jpn language but hopefully someone can fix this bug because it should be able to just go through and activate the battle.

How do you get the lui password
