### ISSUE TITLE
Mario vs Donkey Kong - Tipping Stars (USA) (eShop)slows right down during gameplay due to errors

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#4554]
using the latest nightly
during the game play it slows right down as it keeps spamming out these errors in the console window

HW.GPU <Error> video_core/command_processor.cpp:WriteUniformFloatReg:94: Invalid vertex shader float uniform index 127
HW.GPU <Error> video_core/command_processor.cpp:WritePicaReg:129: Commandlist tried to write to invalid register 0x10093 (value: 000F02C0, mask: 0)
[citra_log.zip](https://github.com/citra-emu/citra/files/2729335/citra_log.zip)

**Comment by SleepingSnakezzz** [comment]
@benderscruffy Please retest on the latest Citra Nightly build.
