### ISSUE TITLE
Hosts the Citra in Flathub

### ISSUE THREAD

**Issue by LeandroStanger** [citra-emu/citra#4555]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by LeandroStanger** [comment]
@chris062689 Flathub Beta is already available. More information on https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land

**Comment by CuriousTommy** [comment]
> We decided not to go with Flathub due to Flathub requiring us to have stable releases and limiting the amount of times we can release per day.
> That's completely justified on their end. We realize updating several times a day is not sustainable bandwidth wise for them.

That makes sense.

> We wanted to self-host as well to have more control over the timing of our release schedule.

When Citra stabilizes, you could do a compromise, similar to how [the Dolphin emulator](https://github.com/flathub/org.DolphinEmu.dolphin-emu/commits/master) is handled. Only update Citra on flathub when a new report is released.

**Comment by JohelEGP** [comment]
This can be closed.
