### ISSUE TITLE
Citra closes when a USB gamepad is plugged in.

### ISSUE THREAD

**Issue by haruuK10** [citra-emu/citra#4556]
Hello, First time user here of the Citra emulator. At first the emulator works fine and stuff, but when I try to plug in my Generic USB gamepad the window suddenly closes. When I try to launch Citra with the controller plugged in it doesn't open. Is there any solution to this? I am using the latest version of the Nightly build by the way.

**Comment by chris062689** [comment]
What USB gamepad do you have? Pictures? Take a picture of the back of it with serial numbers?

**Comment by haruuK10** [comment]
> What USB gamepad do you have? Pictures? Take a picture of the back of it with serial numbers?

@chris062689  I am using Cliptec RZG350 Dual Vibration Gamepad. Hope this helps. 

Pictures here: https://imgur.com/a/bnWAx4l

**Comment by Miepee** [comment]
Same problem here.
I'm using a Mayflash Gamecube Adapter.
Last working version was nightly 961

**Comment by ThiagoGames664** [comment]
I'm having this problem too
https://prntscr.com/qckpkb
https://prntscr.com/qckpk9

**Comment by Subv** [comment]
I'm closing this in favor of #4323 which has more info
