### ISSUE TITLE
Project Mirai 2 - Gameplay/audio desync issue

### ISSUE THREAD

**Issue by xperia64** [citra-emu/citra#4562]
This game experiences audio, synchronization drift of the background music and the rest of game likely similar to #4527 and #4169.
Happens on latest Citra Canary [#1154](https://github.com/citra-emu/citra-canary/releases/tag/canary-1154) and Citra Nightly [#1169](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1169).

To verify and roughly measure desync, I wrote a file-output audio sink backend to record game audio without having to worry about emulation speed or stuttering. I then played the game based on visuals alone and listened to the results afterwards.

- When using HLE audio, at the start of a ~3 minute song, the background music was 100-200ms ahead of the rest of the game
- When using LLE audio on the same song, the background music was 400ms+ behind the rest of the game

The audio sink type and other settings (including JIT) do not seem to matter regarding synchronization.

Unlike #4527, there is no warning in the Citra log about syscore being unimplemented.

System specifications:

- CPU: Intel Core i7-7700k
- GPU: GTX 1080 Ti
- RAM: 32GB DDR4 3200MHz
- OS: Ubuntu Mate 18.04

Log file:
[citra_log_nojit.txt](https://github.com/citra-emu/citra/files/2742261/citra_log_nojit.txt)

**Comment by xperia64** [comment]
I'm not very familiar with the 3DS internals, but if I had to take a guess, assuming something being stubbed is the issue, I'd say it'd be the DSP *Semaphore functions after reviewing both the logs for this game and Theatrhythm.

Otherwise if it's not an issue with a stubbed function, I have no idea where the timing is going off.

**Comment by Shideravan** [comment]
This happen in other games for me too... 
I checked in Super Smash Bros. and Yoshi's Wooly Wold, but I'm sure that's will happen in more games
