### ISSUE TITLE
Issue: Quadruple Screen

### ISSUE THREAD

**Issue by Zuiluj** [citra-emu/citra#4563]
The emulator provides me 4 screens.
CPU: Intel i5-3470s
Graphics: Integrated Intel HD 2500
Ram: 4gb DDR3

![image](https://user-images.githubusercontent.com/32010438/50982528-5af70200-1538-11e9-85ed-61d0fd935939.png)

**Comment by wwylele** [comment]
Please open configure and press "Reset". Please use the forum or discord for further support.

**Comment by valentinvanelslande** [comment]
disable 3d
