### ISSUE TITLE
Metroid Prime Federation Force - Huge Memory Consumption

### ISSUE THREAD

**Issue by xperia64** [citra-emu/citra#4564]
Citra Nightly 1169
A bug which causes Citra to consume excessive amounts of RAM (>1GB/minute) seems to have been encountered when launching the eShop version of Metroid Prime Federation Force a specific way:

0. Have AES keys installed in Citra, either via bootrom+dumps or text file (seeddb optional to reproduce this bug, but recommended)
1. Install the eShop Metroid Prime Federation Force base game (encrypted) CIA
2. Note that launching the new "00000001.app" associated with this game produces a dialog stating "An unknown error occured. Please see the log for more details"
3. Install the Federation Force update CIA (I used version 1.1.0)
4. Note that the "00000001.app" file should have an icon now
5. Launch "00000001.app"
6. Citra will now launch, but seems to excessively leak memory, and the log will complain about unmapped reads and writes

When the game is stopped, Citra will exit cleanly after it frees all of the memory it has allocated. It seems to free about 32MB of RAM/second when told to exit/stop.

System specifications:
- CPU: Intel Core i7-7700k
- GPU: GTX 1080 Ti
- RAM: 32GB DDR4 3200MHz
- OS: Windows 10 1803

Citra log file (decompresses to 52MB):
[citra_log.txt.gz](https://github.com/citra-emu/citra/files/2747420/citra_log.txt.gz)

**Comment by wwylele** [comment]
From discord: 00000001.app is the manual, not the game. Closing this issue as it is too misleading. Please open a new one about hiding manual partition from game list if you want.
