### ISSUE TITLE
[Feature Request] Hide non-game Content from Installed Titles List in Main Menu

### ISSUE THREAD

**Issue by xperia64** [citra-emu/citra#4565]
When installing full CIA files, they contain some NCCH partitions which are not the game itself, e.g. the Manual or Download Play Content.

These can be misleading in the main Citra menu. For instance, Metroid Prime Federation Force with the update installed shows three icons labeled "FEDERATION FORCE" with their respective .app files and no other indication besides size which is the correct one to launch. In this case, 00000003.app is the correct one.

Launching the other partitions can result in undefined behavior as they are not meant to be executed, including excessive memory consumption depending on the game/update.

**Comment by vitor-k** [comment]
#4922 should adress this issue, so we can close this.
But please do report if the issue persists.
