### ISSUE TITLE
Angry birds trilogy - Save problem

### ISSUE THREAD

**Issue by LuismaSP89** [citra-emu/citra#4566]
Can´t save the game in recent builds, if you exit citra and reopen the game, all the data is lost. This doesn´t happen in older citra builds, I don´t know why this is happening. Tested with citra Nightly 1169.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers.
Please use our [forums](https://community.citra-emu.org/) or our [discord](https://citra-emu.org/discord/) server for support.

**Comment by FearlessTobi** [comment]
Cool but your issue is missing all important information cause you entirely ignored the template. We can't do anything with such an issue report.

**Comment by LuismaSP89** [comment]
Then you can tell me that before closing the issue, and not "this is only for devs" I described the issue and provided the citra version tested on. My system specs are not relevant here, but if you need, here it is: 

i7 4790k 4,4 Ghz
16GB DDR3
GTX 970 GB
Windows 10 x64

There´s no much to say in order to reproduce the issue, angry birds PAL game. Is not a graphical issue to attach screenshots. What else do you need?

**Comment by valentinvanelslande** [comment]
the log

**Comment by wwylele** [comment]
I am reopening this as this seems like a legit issue, but please keep the formality of issue report: formal title and description, and information in detail.

**Comment by Dragios** [comment]
#PR 3235 cause this regression. It overwrites save file to zero state (like starting new game)

**Comment by benderscruffy** [comment]
it is still an issue
