### ISSUE TITLE
Android Bulid

### ISSUE THREAD

**Issue by Amul2004** [citra-emu/citra#4572]
Thank you all bringing **THE ONLY FUNCTIONAL 3DS EMULATOR**

I just wanted to ask if anyone in The Citra Team is working towards the making of a 3DS android/ios emulator??

I feel that android phones with Snapdragon 845 and latest IOS devices can support a 3DS emulator...

And all these devices(that I mentioned above) are supporting OPENGL ES 3.2

**Comment by FearlessTobi** [comment]
We are working on an Android port. Currently we don't know when it will be finished and released.
For any further questions, please use our Discord.

**Comment by Amul2004** [comment]
What's discord???
