### ISSUE TITLE
Grey/Invisible Textures

### ISSUE THREAD

**Issue by n00s7** [citra-emu/citra#4577]
When I start Pokémon Moon & Sun and put able the Shader Hardware, somes textures are unstable and are remplazed for a grey or invisible texture intermittent.

Invisible textures in the game and grey textures in the cinematics
Operating System:Windows Version
Windows 10 (64 bit)
CPU: CPU Type
AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
GPU: Graphics Chipset
AMD Radeon™ Vega 8 Graphics
Citra Version: Citra Nightly 1170
Game: Pokémon Sun, Pokémon Moon, Pokémon Ultra Sun and Pokémon Ultra Moon
 Screenshoot:
![error](https://user-images.githubusercontent.com/46767938/51357175-a2771400-1a8b-11e9-8030-590916cb58c7.png)
  -Power Kukui Ranger.
Pokémon Moon:
![nomames](https://user-images.githubusercontent.com/46767938/51357204-c3d80000-1a8b-11e9-8ad8-79d2b72439c9.png)
Pokemon Ultra Moon:
![same](https://user-images.githubusercontent.com/46767938/51357209-ccc8d180-1a8b-11e9-803b-bcb8c5fa258a.png)
  Log: 

[citra_log.txt](https://github.com/citra-emu/citra/files/2771078/citra_log.txt)

**Comment by adriancale0197** [comment]
Tengo un problema parecido, cuando estoy jugando el Ultrasun o Ultramoon y hay una escena donde hablan los personajes los sprites empienzan a parpadear. Soy el unico al que le pasa? Tengo una NVIDIA GTX 1060 6GB y esto me ha sucedido en las ultimas actualizaciones.
 
![citra canary 1154 _ pokemon ultra moon 2019-01-19 21-23-56_moment 2](https://user-images.githubusercontent.com/46855688/51434559-92993480-1c31-11e9-8b08-be110518ef08.jpg)
![citra canary 1154 _ pokemon ultra moon 2019-01-19 21-23-56_moment](https://user-images.githubusercontent.com/46855688/51434560-92993480-1c31-11e9-908e-54e2e0f6fb76.jpg)

**Comment by pikachuk** [comment]
I'm experiencing the same issue too with a gtx 1060 6gb 
![image](https://user-images.githubusercontent.com/16335601/51842868-247bfe00-2312-11e9-8b4f-eb4ba8127e6e.png)

**Comment by johelegp** [comment]
I also suffer this: https://community.citra-emu.org/t/triangle-flickering-and-outlines-of-hidden-graphics/385250?u=johelegp.

**Comment by SleepingSnakezzz** [comment]
This does not appear reproducible on the latest Citra Nightly builds and on the latest GPU drivers. Closing. Feel free to reopen if you still encounter this issue.
