### ISSUE TITLE
Graphics are half broken in the newly released Mario And Luigi RPG 3 DX

### ISSUE THREAD

**Issue by AregevDev** [citra-emu/citra#4581]
Mario Ang Luigi Bowser's inside story & Bowser JR's Journey has been released about a week ago and it has some glitches with the Citra emulator:

-All the character's 2d sprites are not rendering at all
-Text in the intro sequence not rendering as well

![image](https://user-images.githubusercontent.com/40574704/51429036-36271c80-1c13-11e9-85e4-df0da0ab8f10.png)

![image](https://user-images.githubusercontent.com/40574704/51429044-46d79280-1c13-11e9-9738-145fac7cc4e2.png)

![image](https://user-images.githubusercontent.com/40574704/51429049-5a82f900-1c13-11e9-9bf7-ee68ec8d6ec3.png)

![image](https://user-images.githubusercontent.com/40574704/51429056-6969ab80-1c13-11e9-8894-490e572a5652.png)

Technical details:
I am using Linux Mint 19.1 Tessa with the latest canary build
CPU: i5-7200U 2.5 GHz
GPU: Nvidia GeForce 940MX
12 GB of RAM

Important note:
When you turn on the "Accurate multiplication" option under the graphics tab
![image](https://user-images.githubusercontent.com/40574704/51429086-c06f8080-1c13-11e9-96f9-a47a8ad45ee8.png)
The sprites and the text are rendering normally

Thank you and have a nice day

**Comment by FearlessTobi** [comment]
`When you turn on the "Accurate multiplication" option under the graphics tab. The sprites and the text are rendering normally`

This is not a bug then. Just enable the option you just mentioned.
