### ISSUE TITLE
Lego game's graphical error

### ISSUE THREAD

**Issue by RyanXer0** [citra-emu/citra#4585]
I've been getting this graphical error in both of the Lego games I've played. The glitch starts immediately when the games starts, that is how i load in.
the verson is the latest citra nightly
HEAD -  #95a57a2

specs if needed;
Windows 10, a 64 bit operating system, 8 gigabytes of ram, 8th gen intel core i5, an Nvidea geforce 940MX.

- Edit: These games are european version; Issue fixed thanks to @FearlessTobi 

![image](https://user-images.githubusercontent.com/46869807/51442540-786d5e00-1ce6-11e9-9627-54d76d4d79d6.png)
![image](https://user-images.githubusercontent.com/46869807/51442618-2ed14300-1ce7-11e9-89b7-e2ad1234e6f0.png)

**Comment by FearlessTobi** [comment]
This issue is missing a log file.
 Also try enabling Accurate Multiplication and Accurate Geometry Shaders.

**Comment by benderscruffy** [comment]
doesnt happen on my amd card
![pirate](https://user-images.githubusercontent.com/2696404/51446727-ed757d80-1d50-11e9-897a-e09e08132852.PNG)

**Comment by zhaowenlan1779** [comment]
This is fixed by accurate multiplication / accurate GS?
If so, we should close it I think.

**Comment by takeshineale128** [comment]
I can't run with accurate multiplication turned on with the Nvidia Geforce 9500 GT gpu because the emulator just crashes
