### ISSUE TITLE
Fix Game order

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#4593]
When you want to sort the games by alphabetical order (showing the file name), the order of several of those games is not correct. It always seems to show the alphabetical order of the game name, not the file name, no matter what it shows.
You can fix that? because when you dump games from 3DS, many games don't show the full name, or sometimes it just shows the initials of the game so it's better to show the file name.

![screenshot_20190122_132546](https://user-images.githubusercontent.com/45115804/51549677-9bfce980-1e49-11e9-8cc8-4e7b46f16ce4.png)
Order by Game name

![screenshot_20190122_132649](https://user-images.githubusercontent.com/45115804/51549704-a7501500-1e49-11e9-9ed9-4f9e6b79a5a7.png)
Order by File name

![screenshot_20190122_132729](https://user-images.githubusercontent.com/45115804/51549720-b20aaa00-1e49-11e9-840e-74e4e62a71ca.png)
![screenshot_20190122_133002](https://user-images.githubusercontent.com/45115804/51549850-e716fc80-1e49-11e9-9501-5c3385e5bf44.png)
Example of a game with a shortened or incomplete name

My system is Manjaro Linux. I don't know if in other systems the same error will appear.

**Comment by zhaowenlan1779** [comment]
I'm afraid I cannot understand your issue too well - do you mean that the games are sorted by their title names, no matter what (title name, file name, etc) is displayed?

**Comment by Amnesia1000** [comment]
Sorry if you don't understand, I'm using a translator. The problem is that when you sort by name and show the file name and not the game name, the order shown is that of the game name and not the file name. 
For example:
![screenshot_20190130_194342](https://user-images.githubusercontent.com/45115804/52017902-7f0a8b00-24c7-11e9-8c5e-838bcef4fdda.png)

But if you display the name of the game and sort it in alphabetical order...
![screenshot_20190130_194256](https://user-images.githubusercontent.com/45115804/52017908-8467d580-24c7-11e9-84f3-4285ebe410f5.png)
