### ISSUE TITLE
Linux build not enforcing limit speed percent

### ISSUE THREAD

**Issue by youwereeatenbyalid** [citra-emu/citra#4595]
Version: Canary Build - 5bc98c2 

Currently, the limit speed percent checkbox does not seem to be functioning on the linux build of Yuzu.
Test case is Bayonetta 2, were cutscenes will speed up to 2-3 times their standard speed, instead of obeying the speed limit.

[yuzu_log.txt](https://github.com/citra-emu/citra/files/2785874/yuzu_log.txt)
[System.txt](https://github.com/citra-emu/citra/files/2785873/System.txt)

[video of test case](https://streamable.com/lekrv)

**Comment by legoj15** [comment]
Last time I checked bayonetta wasn't on the 3DS :P

**Comment by wwylele** [comment]
This is citra's issue tracker, not yuzu
