### ISSUE TITLE
citra dos'nt woek on osx mojave

### ISSUE THREAD

**Issue by Plaami20** [citra-emu/citra#4606]
the program Citra doesn't work/star, instead of starting it opens the “terminal” and releases this message
Last login: Mon Jan 28 20:27:41 on ttys000
MBP-di-Placido: ~ placidoamicone $ /Applications/Citra2/canary/citra-qt.app/Contents/MacOS/citra-qt-bin; exit;
dyld: Library not loaded: /usr/local/Cellar/ffmpeg/4.1_2/lib/libavutil.56.dylib
Referenced from: /Applications/Citra2/canary/citra-qt.app/Contents/Frameworks/libavcodec.58.dylib
Reason: image not found
Abort trap: 6
logout
Saving session …
… copying shared history …
… saving history … truncating history files …
… completed.

[Process completed]

I use macbook pro, but I can not specify the model, can you help me?

**Comment by FearlessTobi** [comment]
We only accept issue reports for Canary here. 
To fix the issue, either switch to Nightly or wait until we push a solution soon.
