### ISSUE TITLE
Android Bulid

### ISSUE THREAD

**Issue by Amul2004** [citra-emu/citra#4624]
Can you please tell that how much time will it take to make the initial release of Android Build of Citra?

I also earlier asked you in issue : https://github.com/citra-emu/citra/issues/4572

Please tell me!!!!!!!

**Comment by zhaowenlan1779** [comment]
Citra for Android is an unofficial port which was based on months old Citra core code. As we didn't make it, we cannot provide support for it. However, we are working along with the dev behind the port to bring out an official app sometime in the future.

As you can see @BreadFish64 and others are actively working on the android port (see PRs #4613, #4575). I'm afraid there is no ETA yet.

Also, this is an issue tracker for developers. I don't think this is the place for this kind of questions. Please use our [forums](https://community.citra-emu.org) or [discord](https://citra-emu.org/discord) instead.
