### ISSUE TITLE
Tomodachi Life Corrupted Graphics (Mac)

### ISSUE THREAD

**Issue by UmaiRamen** [citra-emu/citra#4638]
So I know this might be the results of using old hardware and a brick(imac), but Tomodachi Life seems to suffer major graphical issues that make certain games impossible to complete. This happens by just booting up the game. I know that this game isn't popular but I want to talk about these issues. I also acknowledge that the game has similar compability issues on other hardware https://citra-emu.org/game/tomodachi-life/. In terms of graphical bugs, (Stomach, Image Based Minigames, Thought bubbles[mii face], food items[minigames], dream mirror[reflection], and Foundation Shop(signs) are shown as a black image, corrupted image, or as noting. I also noticed that the brain texture is ok, so that might be something to look into. Thanks and have a good day.
![screen_shot_2019-02-10_at_10 54 16_pm](https://user-images.githubusercontent.com/34729683/52601981-a4778d00-2e15-11e9-9ea0-6120125a6adf.png)

Hardware specs:
Operating System: MacOS Mojave 10.14.3
CPU: 3.2 GHz Intel Core i5
GPU: NVIDIA GeForce GT 755M 1024 MB
Citra Version (found in title bar): Citra Nightly 1180
Game: Tomodachi Life (USA) v 1.01

![screen shot 2019-02-11 at 3 59 33 pm](https://user-images.githubusercontent.com/34729683/52602082-0e903200-2e16-11e9-903a-6be4f7a5551a.png)

[citra_log.txt](https://github.com/citra-emu/citra/files/2853484/citra_log.txt)

![screen shot 2019-02-11 at 3 36 49 pm](https://user-images.githubusercontent.com/34729683/52601930-76924880-2e15-11e9-99a3-344e0ddcde73.png)
![screen_shot_2019-02-10_at_10 54 22_pm](https://user-images.githubusercontent.com/34729683/52601940-78f4a280-2e15-11e9-8f0a-d53776072bb5.png)
![screen_shot_2019-02-10_at_11 29 23_pm](https://user-images.githubusercontent.com/34729683/52601944-7bef9300-2e15-11e9-99af-d7f358234782.png)
![screen_shot_2019-02-11_at_3 23 11_pm](https://user-images.githubusercontent.com/34729683/52601946-7db95680-2e15-11e9-8fcb-f7abafdcd105.png)
![screen_shot_2019-02-10_at_4 38 40_pm](https://user-images.githubusercontent.com/34729683/52601949-801bb080-2e15-11e9-8263-bca086b9f882.png)

**Comment by SleepingSnakezzz** [comment]
Citra macOS OpenGL is not longer supported due to Citra now having a higher OpenGL version requirement.
