### ISSUE TITLE
Crashes inside OpenGL driver

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#464]
Commit f7a3f45f1e5e507c81e2ad1a1a33dbeb62e64a99 introduced a crash when running certain applications. The PICA source framebuffer physical address remains set to 00000000, which is passed through the PhysicalToVirtual translation and is then passed to the glTexSubImage2D call, causing a crash inside the driver.

**Comment by guiand** [comment]
Is this still an issue?

**Comment by yuriks** [comment]
This has been fixed by #482

**Comment by purpasmart96** [comment]
I'm still getting the crash...

**Comment by yuriks** [comment]
Can you get a stack trace (or pinpoint when the crash is happening by stepping through)? Using which frontend?

**Comment by purpasmart96** [comment]
I'll see what I can do.
