### ISSUE TITLE
Graphical issue in Paper Mario Sticker Star

### ISSUE THREAD

**Issue by CesarAxe** [citra-emu/citra#4641]
Tested Nightly 1189 HEAD-1f31f23
Specs:
Intel core i3 7100
AMD Radeon R7 250 with driver version 19.1.2
![12](https://user-images.githubusercontent.com/17837481/52722860-765f8d80-2f7a-11e9-9b3e-a6165d05adf7.png)
![144](https://user-images.githubusercontent.com/17837481/52722887-7f505f00-2f7a-11e9-9798-ed1e4a97e40d.png)
![puto citra](https://user-images.githubusercontent.com/17837481/52722899-837c7c80-2f7a-11e9-9d81-375412ec40e8.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/2860964/citra_log.txt)

Edit: Tested with a NVIDIA card with the same rom and does not have that problem, 
It's AMD driver problem

**Comment by Loule95450** [comment]
It is surely a bug of the rom

**Comment by benderscruffy** [comment]
this is fixed
this can be close
i have an AMD card aswell on driver 20.2.2
![paper](https://user-images.githubusercontent.com/2696404/75598437-9bb43080-5ad6-11ea-8ce6-52ca0546d094.PNG)
