### ISSUE TITLE
Citra Nightly 1193 issue

### ISSUE THREAD

**Issue by SirGuren** [citra-emu/citra#4643]
As of 150219 1100 (GMT +8) 2 MacOS machines can't run Citra Nightly build 1193.  Both running the latest MacOS.  A 2016 MacBook Pro 15 running 10.14.3 and a 2012 MacBook Pro running MacOS 10.14.1.  Give abort code: 6.  Last running version is: 1180 (240119).  All other version give abort code 6.
![screenshot 2019-02-15 at 11 03 13](https://user-images.githubusercontent.com/12008744/52831919-64fcb980-3111-11e9-8ab6-45a282f04765.png)

**Comment by SiswoHandoko** [comment]
same with me pls fix this issue citra :'(

**Comment by SiswoHandoko** [comment]
Try installing the missing library: brew install ffmpeg. @SirGuren it works for me

**Comment by kuroko15** [comment]
@SiswoHandoko could you tell how to install it? I'm new to this.

**Comment by SiswoHandoko** [comment]
you just must open terminal and write this "brew install ffmpeg" and click enter
@kuroko15
