### ISSUE TITLE
Citra Canary after 1201 Regression with Rhythm Heaven Megamix

### ISSUE THREAD

**Issue by robzombie91** [citra-emu/citra#4644]
Game crashes outright after Canary 1201

@wwylele 
@B3n30 

[Log](
https://pastebin.com/mf5aeikS)

Edit: Forgot to mention it crashes on both hle and lle/lle multicore

**Comment by wwylele** [comment]
Please test Canary 1205 and report back to related PR. Please don't open issue for canary. This issue tracker is for master branch (nightly) only.
