### ISSUE TITLE
Rhythm Heaven Megamix - gameplay and sound are faster then normal

### ISSUE THREAD

**Issue by MojoJojoDojo** [citra-emu/citra#4649]
Tested on latest nightly-1193.
If you play the game the music will become faster then normal and then the gameplay too.

**Comment by FearlessTobi** [comment]
This issue is missing all important information (log, system specs, etc.).
You have opened enough issues here, you should know how it works.

**Comment by MojoJojoDojo** [comment]
[citra_log2.txt](https://github.com/citra-emu/citra/files/2873143/citra_log2.txt)
Ok here is a log.
And my I am using Windows 10 x64 with Intel CPU Inspiron Dell.

**Comment by xperia64** [comment]
I've checked before by dumping the output directly from the decoder as it came in, and the speed of the decoded audio is correct given the assumed sample rate parameters, so this shouldn't be related to the AAC decoder framework itself.

**Comment by sunho** [comment]
+1

**Comment by 1425720626** [comment]
LLE doesn't have this issue but the game is much slower. Only HLE does.

**Comment by Mario-119** [comment]
Any update on the status of the issue? I only ask because I haven't seen any mentions of it since around April.

**Comment by slashiee** [comment]
Gameplay in Rhythm Heaven Megamix is still faster than normal in Canary 1571.

**Comment by oddMLan** [comment]
This does indeed fix the audio speed but the visuals in Rhythm Heaven Megamix are still out of sync with the audio (the audio is behind the visuals by approx. half a second).
LLE does not seem to have this desync issue (but it's hard to tell since it runs at 10 FPS on my computer).
