### ISSUE TITLE
Pokemon Ultra Sun - SD Card could not be recognized

### ISSUE THREAD

**Issue by edogawa5498** [citra-emu/citra#4657]
![untitled](https://user-images.githubusercontent.com/47902626/53270212-11e4c100-3726-11e9-8f1f-82d943302a3a.png)

**Comment by edogawa5498** [comment]
I can't use the poke finder or can't clear the Alola Photo Club. I'm using Citra Canary 1215. How can I fix this? I tried uninstalling and reinstall it over and over again. Please send help.

**Comment by edogawa5498** [comment]
[citra_log.txt](https://github.com/citra-emu/citra/files/2895796/citra_log.txt)

**Comment by wwylele** [comment]
This is issue tracker for developement and doesn't provide support. Please use our forum or discord server for support. If you want to open an issue for legit bug, please test it on nightly/master.
