### ISSUE TITLE
Citra freezes upon stopping game when multiple instances of Citra are active

### ISSUE THREAD

**Issue by viocar** [citra-emu/citra#4662]
Version: HEAD-a79420e
OS: Windows 7

When running multiple instances of Citra, if you attempt to stop, restart, or exit any instance except the first one to load a game, Citra will freeze and must be force-killed. The message in the citra-qt window is:

`RPC_Server <Info> core/rpc/rpc_server.cpp:~RPCServer:20: Stopping RPC ...`

I was told that RPC is the Discord rich presence integration. Even if this feature is disabled in the options menu, this freeze will occur. This freeze will also occur even if the first launched instance is closed first; later instances will always freeze no matter what.

**Comment by jroweboy** [comment]
who told you that? RPC is external scripting interface to the core. We bind a socket on session start, but we probably need to take into account when theres multiple citras already listening on that socket and gracefully handle that.

**Comment by BreadFish64** [comment]
I told him that, my bad, the rich presence stuff is `DiscordRPC`.

**Comment by viocar** [comment]
Ah, no worries. As long as the problem's understood, it's all good.
