### ISSUE TITLE
Devil Survivor 2 Record Breaker UNDUB ROM VOICE

### ISSUE THREAD

**Issue by AmamiyaRenZ** [citra-emu/citra#4664]
I'm using Citra Canary 1224 and have played both eng-dub and undub Devil Survivor 2: record breaker. The dubbed one is in perfect state, the undub is playable but no voice in except for when it turn new day and at title screen.

If could, please look into the problems.

Thank you!

**Comment by AmamiyaRenZ** [comment]
Oh I forgot to mention that this is where i take it https://www.ziperto.com/shin-megami-tensei-devil-survivor-2-record-breaker-undub/.
Compared to the usa rom, its size is less 900MB. Could the missing part is the voice component

**Comment by tgsm** [comment]
@AmamiyaRenZ Please don't link to pirated ROMs.

**Comment by AmamiyaRenZ** [comment]
Oh right. Sorry for the comment

Vào 15:00, T.7, 2 Th3, 2019 Thomas <notifications@github.com đã viết:

**Comment by FearlessTobi** [comment]
This rom is missing all important information like system specs, log, etc.

**Comment by Salijour** [comment]
This doesn't have anything to do with Citra. It is a bad undub from 2 years ago that is still circling around. https://gbatemp.net/threads/release-shin-megami-tensei-iv-undub.373660/page-9#post-5487617
