### ISSUE TITLE
Japanese names "Text is too long (should be no more than 10 characters)"

### ISSUE THREAD

**Issue by phly95** [citra-emu/citra#4667]
When playing Zelda: A Link Between Worlds (Japanese version) entering a name such as フィリップ or even 田中さん runs into the problem where is states "Text is too long (should be no more than 10 characters)" for even really short names, which I'm sure a real JPN 3DS would support (I only have a US model, so I can't test that myself).

**Comment by wwylele** [comment]
Likely the same issue as #4547

**Comment by phly95** [comment]
Is there an override in Citra that will let you disable character counting?
