### ISSUE TITLE
Fire Emblem Echoes/Fates - High pitched voices and crackling sound

### ISSUE THREAD

**Issue by SushiCat12** [citra-emu/citra#4677]
When using the HLE sound option the voices have a higher pitch than normal and some crackling can be heard. When using LLE it doesn't look like it happens, but since the emulation becomes quite slow is not that easy to tell.

The issue occurs in FE Echoes in all the voice-overs, and in FE Fates on the private quarters' dialogues, which in both cases only started working since the LLE update.

An example of the issue is shown below.

FE Echoes - With HLE
https://www.youtube.com/watch?v=87VUhMMVsv8

FE Echoes - With LLE
https://www.youtube.com/watch?v=ztjgEIMx5As

FE Echoes - In the 3DS
https://youtu.be/bi2WM3fiPXk?t=11

**Comment by SushiCat12** [comment]
The crackling has been fixed in https://github.com/citra-emu/citra/pull/4763, but the voices are still too high-pitched and a little sped up.

**Comment by vitor-k** [comment]
Can you test if it was fixed by #5195?

**Comment by SushiCat12** [comment]
It seems to be fixed on my end! I can go ahead and close the issue if there are no objections.
