### ISSUE TITLE
[Feature Request] Hide mouse cursor

### ISSUE THREAD

**Issue by Hezkore** [citra-emu/citra#4687]
An option that hides the mouse cursor would be greatly appreciated.

It could either be timed; so when the mouse cursor hasn't move in ~3 seconds - it hides.
Or it could be input based; so when you've pressed a button on the keyboard/gamepad - it hides.

This would be good in situations where you're playing a game that doesn't (or barely) requires touch input.
Having the cursor on the screen is very distracting.

**Comment by legoj15** [comment]
Alternatively, the mouse could disappear when on the top screen viewport, but stay visible when on the bottom touch screen

**Comment by legend800** [comment]
Just so long as I can have the mouse visible at all times if I choose, I'm ok with this.
