### ISSUE TITLE
[Bug] Zelda OOT 3D Hardware Shader causes lower screen graphics to glitch out

### ISSUE THREAD

**Issue by robzombie91** [citra-emu/citra#4696]
Game: Legend of Zelda: Ocarina of Time 3D
GPU: Nvidia GTX 1070,  419.35
CPU: i5 8400
Tested on Canary Version 1229 but also affects 1255
imgur album: [imgur album](https://imgur.com/a/e6cKmno)
Log: [Pastebin](https://pastebin.com/Huppgqgz)

When hardware shader is toggled in the configuration menu and you are playing oot3d, most of your items on the bottom screen when going into the gear menu and item menu are not visible and the marker is nowhere to be found. This also affects the file selection screen too.

**Comment by wwylele** [comment]
This is known and enabling accurate multiplication fixes it.

**Comment by jroweboy** [comment]
Turn on accurate multiplaction. Known issue without it on, closing as theres no way to fix this without impacting performance for many other games where it doesn't matter.

**Comment by robzombie91** [comment]
wierd, im sure i enabled that on 1229 but my computer must have brain farted
