### ISSUE TITLE
citra nighty 1226's touch screen is broken

### ISSUE THREAD

**Issue by spaceyfacey** [citra-emu/citra#4704]
so I was trying out yokai watch 3, it runs much better thanks to some updates made to the emulator and what not, it lags sometimes but thats about it, but when it came to the fishing mini game that was neccesary for a quest, the touch screen kept just- not working all of a sudden, I tested this out with other games and with the pokemon amie in pokemon alpha sapphire and omega ruby it seems to have this issue too along with other games, I've tried everything to try and fix it, but I think I've done everything I can because nothing else seems to fix this, please try to see to it this bug gets fixed, I can't enjoy many games with this.

**Comment by wwylele** [comment]
Please reset the settings by pressing the "Reset all settings" button in the configuration-general. For further support, please use our forums instead. Closing this until I am informed that his is a real issue. I just tested the latest master and it worked for me.
