### ISSUE TITLE
Professor Layton and the Miracle Mask - can´t pass the game because there´s not a function for tilting the 3DS

### ISSUE THREAD

**Issue by NPMAG** [citra-emu/citra#4740]
It works OK, but when you arrive to puzzle 97, you must tilt you 3DS to pass the puzzle. I think that Citra doesn´t have this function, so I can´t pass the game (it´s a little bit dissapointing).  Is there any possibility to solve this problema and pass the puzzle?  I would be very grateful.

**Comment by wwylele** [comment]
Citra has this function. You can either use hold right mouse button and drag on the screen, or use a controller with motion control and connect with citra via cemuhook. Please use the discord server or the forum for further support.
