### ISSUE TITLE
When does Citra Team add new game submissions to the website list? 

### ISSUE THREAD

**Issue by KCcomics123** [citra-emu/citra#4741]
I used the in-emulator "report compatibility" feature and submitted a bunch of game tests. But only the games that were previously tested by someone else appeared on the website. Games like 3D Sonic the Hedgehog and Kirby's Extra Epic Yarn were two of the many new games I tested, but that was over a week ago and they are still not on the website's list. Any thoughts from anyone?

**Comment by Narugakuruga** [comment]
Go to https://github.com/citra-emu/citra-games-wiki, read the description there .
And here is a issue tracker, not a support forum.

**Comment by chris062689** [comment]
We are in the middle of a migration for getting more games loaded into our gamedb. Currently it is a very manual process, hence why you see some games missing. 
We're looking to improve this process and should have updated documents soon.
