### ISSUE TITLE
Multiplayer chat - Profile picture not updating

### ISSUE THREAD

**Issue by Alakagengar** [citra-emu/citra#4742]
https://community.citra-emu.org/t/profile-pic-wont-update-for-citra-nightly-1244/100160/3 I was asked to create a topic here

**Comment by Alakagengar** [comment]
https://community.citra-emu.org/t/profile-pic-wont-update-for-citra-nightly-1244/100160/3 i was asked to make a topic here about it

**Comment by chris062689** [comment]
I've resolved this issue by invalidating the profile image cache after a set amount of time. 
@Alakagengar I've verified your profile image now shows the correct image.
