### ISSUE TITLE
Tomodachi Life mii error

### ISSUE THREAD

**Issue by rilakkummaaa** [citra-emu/citra#4756]
I just want to fix this litte bug.

====================================================

  System Information :
**Processor : Intel(R) Core(TM) i3-5010U @ 2.10GHz 2.10Ghz
**Installed memory (RAM) : 6.00 GB
**System Type : 64-bit Operating System, x64-based processor

**Comment by rilakkummaaa** [comment]
can y'all respond ASAP ?

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use the Citra forums for help.
