### ISSUE TITLE
Upgrade libx264 155 to version 157

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#4761]
I'm testing the latest version of Citra Canary, and it doesn't open, since the dependency libx264 version 155 is not found. Trying to create a symbolic link gives error when opening citra. And in the Donwgrade options is not the 155 version.

I'm using Manjaro 18.
Citra Canary 1338

**Comment by liushuyu** [comment]
Hi there, try to use the Flatpak version, as the version installed through the old installer is no longer supported. You can install Flatpak version here: https://flatpak.citra-emu.org/

**Comment by Amnesia1000** [comment]
Ok, I appreciate the clarification, but I don't like snap apps, imageapps or flatpak, I'll have to compile them myself. Thank you very much for answering.

**Comment by liushuyu** [comment]
>Okay, I appreciate the clarification, but I don't like snap apps, imageapps, flatpak, as long as it's possible I try to use binaries. I'll have to compile them myself. Thank you very much for answering.

Since you are using Manjaro, you can try the package from AUR: https://aur.archlinux.org/packages/citra-canary-git/ if you want to compile it yourself.

Thanks

**Comment by Amnesia1000** [comment]
Thank you, but as I said, I use emulators from the binaries.  I have a script to update and compile citra, so I will use it again.  Thank you very much.

**Comment by wwylele** [comment]
Closing as the flatpak build is the only supported official binary release right now. Otherwise please compile it yourself.

**Comment by chris062689** [comment]
To expand on this, our build servers target and produce binaries for Ubuntu 18.04 via our Docker containers. 

That's what our binaries and flatpak packages use.
