### ISSUE TITLE
Stereoscopic 3D creates two identical images

### ISSUE THREAD

**Issue by Herny64** [citra-emu/citra#4771]
Hi, the stereoscopic view creates 2 identical images. I tried restarting the game like explained here https://github.com/citra-emu/citra/issues/4453 but it didn't help.
I've enabled it in the settings and cranked it up to 100% and I'm using Citra Nightly 1268 | Head-af197c1 (2019-05-11) on Windows 10 Enterprise 2016 LTSB.
[citra_log.txt](https://github.com/citra-emu/citra/files/3172835/citra_log.txt)
![screenshot](https://user-images.githubusercontent.com/22886346/57621744-86443900-758c-11e9-9eb8-9024f810db73.JPG)

**Comment by FearlessTobi** [comment]
Pokemon SM/USUM do not have 3d support on the original 3ds console either.
