### ISSUE TITLE
Mac screen scaling

### ISSUE THREAD

**Issue by s-strain** [citra-emu/citra#4772]
Due to known issues with recent builds of Citra in Mac OS High Sierra, I tried to run Citra from the terminal to avoid the QT launcher. However, the game displayed in the bottom quarter of the window, scaled to half size vertically and horizontally. Clicking on the bottom half of the window shows that mouse input is still mapped to the full size window. (So clicking at {x,y} in the window causes a button displayed at {x/2,y/2} to activate.)

**System Information**
* Operating System: Mac OS 10.13.4
* CPU: 3.1 GHz Intel Core i5
* GPU: Intel Iris Plus Graphics 650 1536 MB
* Citra Version (found in title bar): Nightly 1268 HEAD-af197c1
* Game: All tested
* Screenshot of Issue: 
<img width="401" alt="Screen Shot 2019-05-12 at 11 28 23 PM" src="https://user-images.githubusercontent.com/50600020/57657878-a0cce100-7591-11e9-9171-05d34e9c2ca4.png">

[citra_log.txt](https://github.com/citra-emu/citra/files/3175020/citra_log.txt)

**Comment by Sparen** [comment]
Note on Citra QT incompatibility with macOS High Sierra: Refer to https://github.com/citra-emu/citra/issues/4515

**Comment by matthewmaneja** [comment]
how to open or fix my citra after open gl 3.3? pls help.

**Comment by Sparen** [comment]
@matthewmaneja See https://github.com/citra-emu/citra/issues/4515. The only real solutions are to use an older version of Citra or to build from source with a custom version of QT.

**Comment by matthewmaneja** [comment]
do you have an older version with you now? pls send it to me directly. dont know where to download or revert back my citra version.

**Comment by matthewmaneja** [comment]
pls pls

**Comment by GPUCode** [comment]
Macos builds have changed significantly since, reopen if it's still an issue
