### ISSUE TITLE
Dragon Quest VIII overworld lags

### ISSUE THREAD

**Issue by Colmines92** [citra-emu/citra#4781]
This issue cannot be seen in screenshots.

I'm using Citra Canary 1358 cd3f1a0:
The game lags a lot in the overworld whenever a new enemy or trees appears. I suppose it is because I'm playing on integrated Intel HD Graphics 4600, but this doesn't happens in other games, which makes me think this is an specific issue with this game.
P.D. Almost all games I have played on citra on my Intel onboard graphics runs at 100%, except CAPCOM Gyakuten Saiban.

Specs:
Video:   Intel HD Graphics 4600
RAM:    8 GB
Micro:   Intel Core-i5 4460

**Comment by wwylele** [comment]
We don't accept "game is slow" issues unless it is shown that it is likely caused by some specific abusive behaviour by game and/or incorrect timing implementation in citra. Please use our forum or discord for general support on improving gaming experience.
