### ISSUE TITLE
mario 3d land crashing when rebuilt with sciresm's 3ds builder

### ISSUE THREAD

**Issue by mariomadproductions** [citra-emu/citra#4785]
This was working before, but stopped working seemingly randomly, without updating citra. I then tried updating to try and fix it, but that didn't help. I'm on Citra Nightly 1272.

Super Mario 3D World crashes once you get to the world map screen.
I haven't actually modified the romfs/exefs before rebuilding.

Config is set to default.
[citra_log.txt](https://github.com/citra-emu/citra/files/3240924/citra_log.txt)

**Comment by wwylele** [comment]
The log you provide is incomplete. If it is a hard crash, could you compile from source and get a stack trace from visual studio?

I am going to close this issue soon, as the modding tool should take the responsibility for this kind of issue first, unless 
 - a detailed stack trace, as requested above, shows potential bug in citra, or
 - it is proved that the same ROM runs perfectly fine on real 3DS

**Comment by mariomadproductions** [comment]
Yeah I should probably test it on my 3DS first.
