### ISSUE TITLE
Citra visual update pokemon omega ruby

### ISSUE THREAD

**Issue by Seloesje** [citra-emu/citra#4790]
Hello,

I just updated Citra to 1273. When I started pokemon Omega Ruby, the visuals where off. 
I can't see the color of the pokeballs in the pokecenter. And the water has changed, so now I cant see the edge of the water anymore. And when I am looking at the entrance of a cave, it is all weird. 

![image](https://user-images.githubusercontent.com/50302509/59055049-458ec580-8895-11e9-94dd-4c45482059b5.png)

![image](https://user-images.githubusercontent.com/50302509/59055101-6525ee00-8895-11e9-8c8e-58abebd61436.png)

**Comment by zhaowenlan1779** [comment]
This is an issue tracker for developers and not a support forum. For support, please use our [forums](https://community.citra-emu.org) or [discord](https://citra-emu.org/discord) instead.

Closing this as I cannot really reproduce right now. Please reopen if this is confirmed to be a real issue.

**Comment by Seloesje** [comment]
It is getting a real issue, I would like to reopen this thank you.

**Comment by wwylele** [comment]
If you mean to open a real issue (= help dev to fix it. Not help you to play it), please provide everything specified in the issue template, including log, and all tested version number.
