### ISSUE TITLE
LT/RT button problem using xbox controller

### ISSUE THREAD

**Issue by ZackhamGuo** [citra-emu/citra#4798]
issue #3303 happens on my citra. LT/RT is recognized as axis, and when pressed they are constantly triggered.
I noticed that #3303 is on 16 Dec 2017, so this problem long exists.

**Comment by tywald** [comment]
You need to rebind them so it says for example Axis 5+ and not Axis 5-. The easiest way is to push the trigger all the way in then click to bind and when you release it should be bound correctly.

**Comment by wwylele** [comment]
closing as there is a solution for this. Reopen if it doesn't work at all, or open a new one if you have UI suggestion.

**Comment by Papermanzero** [comment]
If you need to hold triggers like in mario kart 7 to drift this solution does not work
