### ISSUE TITLE
Loopback & Room Moderation

### ISSUE THREAD

**Issue by Luarst** [citra-emu/citra#4808]
With routers that don't support loopback, it is impossible to connect to a dedicated server one is hosting without using a local ip. Unfortunately, Citra's "Direct Connect to Room" does not give moderation ability when doing this.

**Comment by chris062689** [comment]
The original concept behind direct join rooms was that anything that was self hosted as a private room and connected via direct connect should bypass the authentication server, for privacy reasons. 

The only way to authenticate your account is joining a listed server on the server browser.

**Comment by Luarst** [comment]
Unfortunately, It's impossible to join through the server browser because it uses my public ip to connect to the server. So.. unless my dedicated server and Citra were both on a seperate networks it is also impossible to moderate the server at all. 

I'll just deal with using Create Room instead of having a dedicated one running from now on.
