### ISSUE TITLE
Building citra fails with visual studio

### ISSUE THREAD

**Issue by dflkj2323k** [citra-emu/citra#4809]
Because of too many errors, i had to build only citra project

1>------ Build started: Project: citra, Configuration: Release x64 ------
1>citra.cpp
1>config.cpp
1>emu_window_sdl2.cpp
1>Warning static builds of getopt violate the Lesser GNU Public License
1>C:\Users\777\citra\src\common/math_util.h(45): error C2955: 'Common::Rectangle': use of class template requires template argument list (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/math_util.h(15): note: see declaration of 'Common::Rectangle' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2988: unrecognizable template declaration/definition (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2143: syntax error: missing ')' before ',' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2365: 'T': redefinition; previous definition was 'template parameter' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/math_util.h(44): note: see declaration of 'T' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2059: syntax error: ',' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2059: syntax error: ')' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\condition_variable(180): error C2989: 'std::condition_variable_any': class template has already been declared as a non-class template (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(27): note: see declaration of 'std::condition_variable_any' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2955: 'Common::Rectangle': use of class template requires template argument list (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/math_util.h(15): note: see declaration of 'Common::Rectangle' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2988: unrecognizable template declaration/definition (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2143: syntax error: missing ')' before ',' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2365: 'T': redefinition; previous definition was 'template parameter' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/math_util.h(44): note: see declaration of 'T' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2059: syntax error: ',' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/math_util.h(45): error C2059: syntax error: ')' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\citra/emu_window/emu_window_sdl2.h(11): error C2989: 'SDL_Window': class template has already been declared as a non-class template (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>c:\users\777\citra\build\externals\sdl2-2.0.8\include\SDL_video.h(90): note: see declaration of 'SDL_Window' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\core/core_timing.h(60): error C2955: 'Log::Class': use of class template requires template argument list (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/logging/log.h(35): note: see declaration of 'Log::Class' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\core/core_timing.h(60): error C2027: use of undefined type 'Log::Class' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/logging/log.h(35): note: see declaration of 'Log::Class' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\core/core_timing.h(60): error C2065: 'Core_Timing': undeclared identifier (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\core/core_timing.h(60): error C2955: 'Log::Level': use of class template requires template argument list (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/logging/log.h(13): note: see declaration of 'Log::Level' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\core/core_timing.h(60): error C2027: use of undefined type 'Log::Level' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/logging/log.h(13): note: see declaration of 'Log::Level' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\core/core_timing.h(60): error C2065: 'Error': undeclared identifier (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\core/core_timing.h(64): error C2955: 'Log::Class': use of class template requires template argument list (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/logging/log.h(35): note: see declaration of 'Log::Class' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\core/core_timing.h(64): error C2027: use of undefined type 'Log::Class' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\common/logging/log.h(35): note: see declaration of 'Log::Class' (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\core/core_timing.h(64): error C2065: 'Core_Timing': undeclared identifier (compiling source file C:\Users\777\citra\src\citra\emu_window\emu_window_sdl2.cpp)
1>C:\Users\777\citra\src\core/core_timing.h(64): error C2955: 'Log::Level': use of class template requires template argument list (compiling source file 
.
. (skip) 
.
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(508): note: see declaration of 'std::lock_guard' (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>C:\Users\777\citra\src\common/thread.h(18): error C2514: 'std::lock_guard': class has no constructors (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(508): note: see declaration of 'std::lock_guard' (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>C:\Users\777\citra\src\common/thread.h(26): error C2514: 'std::unique_lock': class has no constructors (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(133): note: see declaration of 'std::unique_lock' (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>C:\Users\777\citra\src\common/thread.h(27): error C2664: 'void std::condition_variable::wait(std::unique_lock<std::mutex> &)': cannot convert argument 1 from 'std::unique_lock' to 'std::unique_lock<std::mutex> &' (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>C:\Users\777\citra\src\common/thread.h(50): error C2514: 'std::unique_lock': class has no constructors (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(133): note: see declaration of 'std::unique_lock' (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>C:\Users\777\citra\src\common/thread.h(68): error C2514: 'std::unique_lock': class has no constructors (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(133): note: see declaration of 'std::unique_lock' (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>C:\Users\777\citra\src\common/thread.h(76): error C2664: 'void std::condition_variable::wait(std::unique_lock<std::mutex> &)': cannot convert argument 1 from 'std::unique_lock' to 'std::unique_lock<std::mutex> &' (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>C:\Users\777\citra\src\common/thread.h(82): error C2514: 'std::unique_lock': class has no constructors (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(133): note: see declaration of 'std::unique_lock' (compiling source file C:\Users\777\citra\src\citra\config.cpp)
1>C:\Users\777\citra\src\common/thread.h(18): error C2514: 'std::lock_guard': class has no constructors (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(508): note: see declaration of 'std::lock_guard' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/thread.h(26): error C2514: 'std::unique_lock': class has no constructors (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(133): note: see declaration of 'std::unique_lock' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/thread.h(27): error C2664: 'void std::condition_variable::wait(std::unique_lock<std::mutex> &)': cannot convert argument 1 from 'std::unique_lock' to 'std::unique_lock<std::mutex> &' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/thread.h(50): error C2514: 'std::unique_lock': class has no constructors (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(133): note: see declaration of 'std::unique_lock' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/thread.h(68): error C2514: 'std::unique_lock': class has no constructors (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(133): note: see declaration of 'std::unique_lock' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/thread.h(76): error C2664: 'void std::condition_variable::wait(std::unique_lock<std::mutex> &)': cannot convert argument 1 from 'std::unique_lock' to 'std::unique_lock<std::mutex> &' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\common/thread.h(82): error C2514: 'std::unique_lock': class has no constructors (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\mutex(133): note: see declaration of 'std::unique_lock' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\core/core.h(20): error C2990: 'Frontend::EmuWindow': non-class template has already been declared as a class template (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\core/frontend/emu_window.h(33): note: see declaration of 'Frontend::EmuWindow' (compiling source file C:\Users\777\citra\src\citra\citra.cpp)
1>C:\Users\777\citra\src\citra\citra.cpp(182): error C2079: 'detached_tasks' uses undefined class 'Common::DetachedTasks'
1>C:\Users\777\citra\src\citra\citra.cpp(340): error C3203: 'EmuWindow_SDL2': unspecialized class template can't be used as a template argument for template parameter '_Ty', expected a real type
1>C:\Users\777\citra\src\citra\citra.cpp(340): error C2672: 'std::make_unique': no matching overloaded function found
1>C:\Users\777\citra\src\citra\citra.cpp(340): error C3206: 'std::make_unique': invalid template argument for '_Ty', missing template argument list on class template 'EmuWindow_SDL2'
1>E:\visual project\VC\Tools\MSVC\14.12.25827\include\memory(2599): note: see declaration of 'std::make_unique'
1>C:\Users\777\citra\src\citra\citra.cpp(346): error C2664: 'Core::System::ResultStatus Core::System::Load(Frontend::EmuWindow &,const std::string &)': cannot convert argument 1 from 'std::ios_base::iostate' to 'Frontend::EmuWindow &'
1>C:\Users\777\citra\src\citra\citra.cpp(402): error C2839: invalid return type 'int *' for overloaded 'operator ->'
1>C:\Users\777\citra\src\citra\citra.cpp(402): error C2039: 'IsOpen': is not a member of 'std::unique_ptr<int,std::default_delete<_Ty>>'
1>        with
1>        [
1>            _Ty=int
1>        ]
1>C:\Users\777\citra\src\citra\citra.cpp(340): note: see declaration of 'std::unique_ptr<int,std::default_delete<_Ty>>'
1>        with
1>        [
1>            _Ty=int
1>        ]
1>C:\Users\777\citra\src\citra\citra.cpp(408): error C2228: left of '.WaitForAllTasks' must have class/struct/union
1>C:\Users\777\citra\src\citra\citra.cpp(408): note: type is 'int'
1>Done building project "citra.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by wwylele** [comment]
What's the version of your Visual Studio? From the error it looks like it is too out-dated.
