### ISSUE TITLE
Build error on linux

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#4810]
Hi, I got to the point of giving the "make" command and 93% gave me these errors. What did I do wrong?

[ 93%] Linking CXX executable ../../bin/tests
/usr/local/lib/libavformat.a(mov.o): nella funzione "mov_read_cmov":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/mov.c:5125: riferimento non definito a "uncompress"
/usr/local/lib/libavformat.a(swfdec.o): nella funzione "swf_read_packet":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/swfdec.c:364: riferimento non definito a "uncompress"
/usr/local/lib/libavformat.a(swfdec.o): nella funzione "swf_read_header":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/swfdec.c:153: riferimento non definito a "inflateInit_"
/usr/local/lib/libavformat.a(swfdec.o): nella funzione "zlib_refill":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/swfdec.c:121: riferimento non definito a "inflate"
/usr/local/lib/libavformat.a(swfdec.o): nella funzione "swf_read_close":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/swfdec.c:531: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(cscd.o): nella funzione "decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/cscd.c:96: riferimento non definito a "uncompress"
/usr/local/lib/libavcodec.a(dxa.o): nella funzione "decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/dxa.c:250: riferimento non definito a "uncompress"
/usr/local/lib/libavcodec.a(exr.o): nella funzione "zip_uncompress":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/exr.c:273: riferimento non definito a "uncompress"
/usr/local/lib/libavcodec.a(exr.o): nella funzione "pxr24_uncompress":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/exr.c:837: riferimento non definito a "uncompress"
/usr/local/lib/libavcodec.a(flashsv.o): nella funzione "flashsv_decode_block":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:191: riferimento non definito a "inflateReset"
/usr/local/lib/libavcodec.a(flashsv.o): nella funzione "flashsv2_prime":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:158: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:160: riferimento non definito a "deflateInit_"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:166: riferimento non definito a "deflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:167: riferimento non definito a "deflateEnd"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:169: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:178: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(flashsv.o): nella funzione "flashsv_decode_block":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:207: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:210: riferimento non definito a "inflateSync"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:211: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(flashsv.o): nella funzione "calc_deflate_block_size":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:259: riferimento non definito a "deflateInit_"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:261: riferimento non definito a "deflateBound"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:262: riferimento non definito a "deflateEnd"
/usr/local/lib/libavcodec.a(flashsv.o): nella funzione "flashsv_decode_end":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:107: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(flashsv.o): nella funzione "flashsv_decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv.c:126: riferimento non definito a "inflateInit_"
/usr/local/lib/libavcodec.a(flashsv2enc.o): nella funzione "encode_zlib":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv2enc.c:354: riferimento non definito a "compress2"
/usr/local/lib/libavcodec.a(flashsv2enc.o): nella funzione "encode_zlibprime":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv2enc.c:366: riferimento non definito a "deflateInit_"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv2enc.c:375: riferimento non definito a "deflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv2enc.c:384: riferimento non definito a "deflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsv2enc.c:385: riferimento non definito a "deflateEnd"
/usr/local/lib/libavcodec.a(flashsvenc.o): nella funzione "encode_bitstream":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsvenc.c:182: riferimento non definito a "compress2"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsvenc.c:182: riferimento non definito a "compress2"
/usr/local/lib/libavcodec.a(flashsvenc.o): nella funzione "flashsv_encode_end":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/flashsvenc.c:95: riferimento non definito a "deflateEnd"
/usr/local/lib/libavcodec.a(g2meet.o): nella funzione "kempf_decode_tile":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/g2meet.c:1118: riferimento non definito a "uncompress"
/usr/local/lib/libavcodec.a(lcldec.o): nella funzione "zlib_decomp":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lcldec.c:134: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lcldec.c:143: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lcldec.c:134: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lcldec.c:143: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lcldec.c:134: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lcldec.c:143: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(lcldec.o): nella funzione "decode_end":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lcldec.c:640: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(lcldec.o): nella funzione "decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lcldec.c:614: riferimento non definito a "inflateInit_"
/usr/local/lib/libavcodec.a(lclenc.o): nella funzione "encode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lclenc.c:71: riferimento non definito a "deflateBound"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lclenc.c:81: riferimento non definito a "deflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lclenc.c:92: riferimento non definito a "deflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lclenc.c:98: riferimento non definito a "deflate"
/usr/local/lib/libavcodec.a(lclenc.o): nella funzione "encode_end":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lclenc.c:165: riferimento non definito a "deflateEnd"
/usr/local/lib/libavcodec.a(lclenc.o): nella funzione "encode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/lclenc.c:151: riferimento non definito a "deflateInit_"
/usr/local/lib/libavcodec.a(libfdk-aacdec.o): nella funzione "fdk_aac_decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:345: riferimento non definito a "aacDecoder_Fill"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:351: riferimento non definito a "aacDecoder_DecodeFrame"
/usr/local/lib/libavcodec.a(libfdk-aacdec.o): nella funzione "get_stream_info":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:102: riferimento non definito a "aacDecoder_GetStreamInfo"
/usr/local/lib/libavcodec.a(libfdk-aacdec.o): nella funzione "fdk_aac_decode_close":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:215: riferimento non definito a "aacDecoder_Close"
/usr/local/lib/libavcodec.a(libfdk-aacdec.o): nella funzione "fdk_aac_decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:227: riferimento non definito a "aacDecoder_Open"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:234: riferimento non definito a "aacDecoder_ConfigRaw"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:241: riferimento non definito a "aacDecoder_SetParam"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:265: riferimento non definito a "aacDecoder_SetParam"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:274: riferimento non definito a "aacDecoder_AncDataInit"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:283: riferimento non definito a "aacDecoder_SetParam"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:290: riferimento non definito a "aacDecoder_SetParam"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:297: riferimento non definito a "aacDecoder_SetParam"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:304: riferimento non definito a "aacDecoder_SetParam"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:311: riferimento non definito a "aacDecoder_SetParam"
/usr/local/lib/libavcodec.a(libfdk-aacdec.o):/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacdec.c:389: seguono ulteriori riferimenti non definiti a "aacDecoder_SetParam"
/usr/local/lib/libavcodec.a(libfdk-aacenc.o): nella funzione "aac_encode_close":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:112: riferimento non definito a "aacEncClose"
/usr/local/lib/libavcodec.a(libfdk-aacenc.o): nella funzione "aac_encode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:405: riferimento non definito a "aacEncEncode"
/usr/local/lib/libavcodec.a(libfdk-aacenc.o): nella funzione "aac_encode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:129: riferimento non definito a "aacEncOpen"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:138: riferimento non definito a "aacEncoder_SetParam"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:145: riferimento non definito a "aacEncoder_SetParam"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:153: riferimento non definito a "aacEncoder_SetParam"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:208: riferimento non definito a "aacEncoder_SetParam"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:215: riferimento non definito a "aacEncoder_SetParam"
/usr/local/lib/libavcodec.a(libfdk-aacenc.o):/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:233: seguono ulteriori riferimenti non definiti a "aacEncoder_SetParam"
/usr/local/lib/libavcodec.a(libfdk-aacenc.o): nella funzione "aac_encode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:313: riferimento non definito a "aacEncEncode"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/libfdk-aacenc.c:319: riferimento non definito a "aacEncInfo"
/usr/local/lib/libavcodec.a(mscc.o): nella funzione "decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/mscc.c:168: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/mscc.c:177: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(mscc.o): nella funzione "decode_close":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/mscc.c:249: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(mscc.o): nella funzione "decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/mscc.c:232: riferimento non definito a "inflateInit_"
/usr/local/lib/libavcodec.a(mwsc.o): nella funzione "decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/mwsc.c:101: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/mwsc.c:110: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(mwsc.o): nella funzione "decode_close":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/mwsc.c:175: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(mwsc.o): nella funzione "decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/mwsc.c:155: riferimento non definito a "inflateInit_"
/usr/local/lib/libavcodec.a(pngdec.o): nella funzione "decode_zbuf":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngdec.c:445: riferimento non definito a "inflateInit_"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngdec.c:459: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngdec.c:468: riferimento non definito a "inflateEnd"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngdec.c:473: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(pngdec.o): nella funzione "png_decode_idat":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngdec.c:413: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(pngdec.o): nella funzione "decode_frame_apng":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngdec.c:1499: riferimento non definito a "inflateInit_"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngdec.c:1523: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(pngdec.o): nella funzione "decode_frame_png":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngdec.c:1444: riferimento non definito a "inflateInit_"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngdec.c:1466: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(pngenc.o): nella funzione "png_write_row":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngenc.c:279: riferimento non definito a "deflate"
/usr/local/lib/libavcodec.a(pngenc.o): nella funzione "encode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngenc.c:498: riferimento non definito a "deflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngenc.c:520: riferimento non definito a "deflateReset"
/usr/local/lib/libavcodec.a(pngenc.o): nella funzione "png_write_row":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngenc.c:279: riferimento non definito a "deflate"
/usr/local/lib/libavcodec.a(pngenc.o): nella funzione "encode_apng":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngenc.c:862: riferimento non definito a "deflateBound"
/usr/local/lib/libavcodec.a(pngenc.o): nella funzione "encode_png":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngenc.c:532: riferimento non definito a "deflateBound"
/usr/local/lib/libavcodec.a(pngenc.o): nella funzione "png_enc_close":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngenc.c:1102: riferimento non definito a "deflateEnd"
/usr/local/lib/libavcodec.a(pngenc.o): nella funzione "png_enc_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/pngenc.c:1092: riferimento non definito a "deflateInit2_"
/usr/local/lib/libavcodec.a(rasc.o): nella funzione "decode_zlib":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:176: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:192: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:176: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:192: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(rasc.o): nella funzione "decode_kfrm":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:487: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:501: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(rasc.o): nella funzione "decode_zlib":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:176: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:192: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(rasc.o): nella funzione "decode_kfrm":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:516: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(rasc.o): nella funzione "decode_close":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:778: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(rasc.o): nella funzione "decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rasc.c:754: riferimento non definito a "inflateInit_"
/usr/local/lib/libavcodec.a(rscc.o): nella funzione "rscc_decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rscc.c:213: riferimento non definito a "uncompress"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/rscc.c:302: riferimento non definito a "uncompress"
/usr/local/lib/libavcodec.a(screenpresso.o): nella funzione "screenpresso_decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/screenpresso.c:141: riferimento non definito a "uncompress"
/usr/local/lib/libavcodec.a(svq3.o): nella funzione "svq3_decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/svq3.c:1284: riferimento non definito a "uncompress"
/usr/local/lib/libavcodec.a(tdsc.o): nella funzione "tdsc_decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/tdsc.c:541: riferimento non definito a "uncompress"
/usr/local/lib/libavcodec.a(tiff.o): nella funzione "tiff_uncompress":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/tiff.c:331: riferimento non definito a "inflateInit_"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/tiff.c:336: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/tiff.c:337: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(tiffenc.o): nella funzione "encode_strip":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/tiffenc.c:179: riferimento non definito a "compress"
/usr/local/lib/libavcodec.a(tscc.o): nella funzione "decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/tscc.c:86: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/tscc.c:95: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(tscc.o): nella funzione "decode_end":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/tscc.c:185: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(tscc.o): nella funzione "decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/tscc.c:165: riferimento non definito a "inflateInit_"
/usr/local/lib/libavcodec.a(wcmv.o): nella funzione "decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/wcmv.c:52: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/wcmv.c:94: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/wcmv.c:187: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/wcmv.c:101: riferimento non definito a "inflateReset"
/usr/local/lib/libavcodec.a(wcmv.o): nella funzione "decode_close":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/wcmv.c:247: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(wcmv.o): nella funzione "decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/wcmv.c:229: riferimento non definito a "inflateInit_"
/usr/local/lib/libavcodec.a(zerocodec.o): nella funzione "zerocodec_decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zerocodec.c:56: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zerocodec.c:79: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(zerocodec.o): nella funzione "zerocodec_decode_close":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zerocodec.c:109: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(zerocodec.o): nella funzione "zerocodec_decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zerocodec.c:127: riferimento non definito a "inflateInit_"
/usr/local/lib/libavcodec.a(zmbv.o): nella funzione "decode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zmbv.c:493: riferimento non definito a "inflateReset"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zmbv.c:541: riferimento non definito a "inflate"
/usr/local/lib/libavcodec.a(zmbv.o): nella funzione "decode_end":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zmbv.c:648: riferimento non definito a "inflateEnd"
/usr/local/lib/libavcodec.a(zmbv.o): nella funzione "decode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zmbv.c:633: riferimento non definito a "inflateInit_"
/usr/local/lib/libavcodec.a(zmbvenc.o): nella funzione "encode_frame":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zmbvenc.c:230: riferimento non definito a "deflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zmbvenc.c:221: riferimento non definito a "deflateReset"
/usr/local/lib/libavcodec.a(zmbvenc.o): nella funzione "encode_end":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zmbvenc.c:265: riferimento non definito a "deflateEnd"
/usr/local/lib/libavcodec.a(zmbvenc.o): nella funzione "encode_init":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavcodec/zmbvenc.c:325: riferimento non definito a "deflateInit_"
/usr/local/lib/libavformat.a(id3v2.o): nella funzione "id3v2_parse":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/id3v2.c:1023: riferimento non definito a "uncompress"
/usr/local/lib/libavformat.a(http.o): nella funzione "http_close":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/http.c:1649: riferimento non definito a "inflateEnd"
/usr/local/lib/libavformat.a(http.o): nella funzione "parse_content_encoding":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/http.c:680: riferimento non definito a "inflateEnd"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/http.c:681: riferimento non definito a "inflateInit2_"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/http.c:686: riferimento non definito a "zlibCompileFlags"
/usr/local/lib/libavformat.a(http.o): nella funzione "http_buf_read_compressed":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/http.c:1428: riferimento non definito a "inflate"
/usr/local/lib/libavformat.a(matroskadec.o): nella funzione "matroska_decode_buffer":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/matroskadec.c:1402: riferimento non definito a "inflateInit_"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/matroskadec.c:1417: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/matroskadec.c:1410: riferimento non definito a "inflateEnd"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/matroskadec.c:1420: riferimento non definito a "inflateEnd"
/usr/local/lib/libavformat.a(rtmpproto.o): nella funzione "rtmp_uncompress_swfplayer":
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/rtmpproto.c:1077: riferimento non definito a "inflateInit_"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/rtmpproto.c:1087: riferimento non definito a "inflate"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/rtmpproto.c:1105: riferimento non definito a "inflateEnd"
/home/alessio/Scaricati/ffmpeg-4.1.3/libavformat/rtmpproto.c:1105: riferimento non definito a "inflateEnd"
collect2: error: ld returned 1 exit status
src/tests/CMakeFiles/tests.dir/build.make:410: recipe for target 'bin/tests' failed
make[2]: *** [bin/tests] Error 1
CMakeFiles/Makefile2:1464: recipe for target 'src/tests/CMakeFiles/tests.dir/all' failed
make[1]: *** [src/tests/CMakeFiles/tests.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AnotherCoolDude** [comment]
same here. Maybe we are missing some libraries? Followed the guide to build for linux pretty thoroughly though. Any help is welcome :) i am building on Ubuntu 19.04

**Comment by wwylele** [comment]
I am closing this issue because the author is gone. @AnotherCoolDude Please open a new issue for your case with full error log, plus the configuration of CMake (ffmpeg enabled or not, for example) and other useful information. Thanks!
