### ISSUE TITLE
Citra on Android

### ISSUE THREAD

**Issue by B3n30** [citra-emu/citra#4815]
As a user I want to use Citra on my Android device

**Comment by greggameplayer** [comment]
Citra team you've been double by Mikage project on android take a look here : https://mikage.app/

**Comment by tgsm** [comment]
@greggameplayer it's not a competition.

**Comment by greggameplayer** [comment]
@tgsm absolutely not but i'm sad that citra isn't the first real 3ds emulator on android ( excluding sachinvin fork )

**Comment by Gamemulatorer** [comment]
Finally this is the official android port of Citra 🎉
https://github.com/citra-emu/citra-android

**Comment by archon810** [comment]
Is there any reason the version on the Play Store is "null"?
