### ISSUE TITLE
Include PC (program counter) in log messages of severity level "Warning" or higher

### ISSUE THREAD

**Issue by badda71** [citra-emu/citra#4819]
I as a homebrew developer would like to see the PC (program counter) in log messages of severity level "Warning" or higher. This will help me track down the reason for these errors in my source code (e.g. unmapped reads or writes).

**Comment by wwylele** [comment]
As a workaround, you can place breakpoints on the log you are interested in, and inspect the PC value when it pauses on the breakpoint.

I indeed also wanted this feature when I debug my homebrew apps. However, logging with CPU info means to pass those states everywhere, which can be quite a challenge to keep the code still maintainable. Not saying this is not possible. just my two cents.

**Comment by badda71** [comment]
I know this is now good practice in C++ but wouldn't this justify the use of a global object or a global pointer to the CPU registers?

**Comment by wwylele** [comment]
We don't have to resort to global state yet. One possible implementation is to record the PC value into the logging system whenever the code pass through the CPU-HLE boundary (=SVC calls).

**Comment by wwylele** [comment]
I just realized this isn't as simple as it sounds. Because almost all of our logs happens behind the SVC boundary, and maybe 90% of them are behind svcSendSyncRequest, the PC value at those point would surely be at those generic SVC stubs in ctrulib - they are all the same even if you call the SVC in different point of your program. To make this feature useful, the LR value and several level of stack trace needs to be logged.

**Comment by badda71** [comment]
If you have the PC, you can get the stack trace from gdb. Just set a breakpoint at the address the citra log will give you and backtrace when gdb breaks

**Comment by wwylele** [comment]
You don't really need to rely on citra to do that. ctrulib should already give you the symbol of all SVCs and just place breakpoints on them. Even without ctrulib symbols, a quick search of the specific SVC instruction opcode in the binary and you will quickly find it. Mind you that no matter how you get these positions (from citra or search for it yourself) and place breakpoints from them, you will likely get tons of false positive, especially on svcSendSyncRequest which is 90% the case. This doesn't solve the essential problem.

**Comment by badda71** [comment]
Ok, understood. But what about the log call for e.g. unmapped reads? This one spits out the address that the program is trying to read. When capturing this address, the PC could be captured as well.

**Comment by badda71** [comment]
It was really easy for me to get the PC into the log message for unmapped reads:
File src/core/memory.cpp
add line:
`#include "core/arm/skyeye_common/armstate.h"`

modify line:
`LOG_ERROR(HW_Memory, "unmapped Read{} @ 0x{:08X}", sizeof(T) * 8, vaddr);`
to:
`LOG_ERROR(HW_Memory, "unmapped Read{} @ 0x{:08X} PC 0x{:08X}", sizeof(T) * 8, vaddr, impl->cpu->GetPC());`

**Comment by badda71** [comment]
*bump* *bump*
would it be possible to include the PC at least in the unmapped reads and writes? This would help homebrew devs a lot!

**Comment by badda71** [comment]
ok, the proposed solution above is not working anymore. Here an alternative
modify line:
    LOG_ERROR(HW_Memory, "unmapped Read{} @ 0x{:08X}", sizeof(T) * 8, vaddr);
to:
    LOG_ERROR(HW_Memory, "unmapped Read{} @ 0x{:08X} at PC 0x{:08X}", sizeof(T) * 8, vaddr, Core::GetRunningCore().GetPC());

**Comment by GPUCode** [comment]
I think this was fixed by linked PR, reopen if it wasn't
