### ISSUE TITLE
Skybox renders incorrectly in Fire Emblem Fates when using Hardware Renderer since Canary 1277

### ISSUE THREAD

**Issue by tom-overton** [citra-emu/citra#4821]
After updating to the latest Canary version, I noticed that the skybox in Fire Emblem Fates rendered incorrectly in the Prologue where it previously worked. Bisecting the issue, I found that the effect worked properly in Canary 1276 (HEAD-98ee989) but started rendering incorrectly in Canary 1277 (HEAD-e9572e4). Comparing the two versions, the only difference appears to be pull request [3910](https://github.com/citra-emu/citra/pull/3910). See the screenshots below to view the difference.

I've also tried various options to see if they have any effect on the rendering of the skybox:
- Switching to software rendering fixes the issue, resulting in an image that looks like the real hardware screenshot below
- Since pull request 3910 is mipmap related, I tried changing my rendering resolution to see if it would have an effect. I was originally at 2x native, so I tried both 1x native and 10x native. Neither corrected the skybox issue
- I also tried messing with various options in the hardware renderer, but none seemed to make a difference. I turned off "Enable Hardware Shader" then turned it back on and tried various combinations of accurate multiplication and accurate geometry shaders, though nothing seemed to have an effect

Canary 1276 logs:
[citra_log.txt](https://github.com/citra-emu/citra/files/3364590/citra_log.txt)

Canary 1277 logs:
[citra_log.txt](https://github.com/citra-emu/citra/files/3364591/citra_log.txt)

System Specs:
OS: Windows 10 Pro
CPU: Intel Core i7-8700K
GPU: NVIDIA GeForce GTX 1080 Ti
GPU Driver: 430.86

Canary 1276 Screenshot:
![1276](https://user-images.githubusercontent.com/12245827/60754493-a396f180-9f96-11e9-8752-be68601b1042.png)

Canary 1277 Screenshot:
![1277](https://user-images.githubusercontent.com/12245827/60754496-a8f43c00-9f96-11e9-95c6-fa2cd243862f.png)

Real hardware:
![hardware](https://user-images.githubusercontent.com/12245827/60754497-ae518680-9f96-11e9-89df-c6f3e26926d1.png)

**Comment by tom-overton** [comment]
I built a version of Citra using the latest code in master, then I made a simple modification to gl_rasterizer.cpp and found that it fixed the issue. On line 1579 of the file (as of the time of this writing), you'll see the following block of code:
```
    if (min_filter != config.min_filter || mip_filter != config.mip_filter) {
        min_filter = config.min_filter;
        mip_filter = config.mip_filter;
        glSamplerParameteri(s, GL_TEXTURE_MIN_FILTER,
                            PicaToGL::TextureMinFilterMode(min_filter, mip_filter));
    }
```

By changing the last line of this block to instead be:
```
        glSamplerParameteri(s, GL_TEXTURE_MIN_FILTER, PicaToGL::TextureMagFilterMode(min_filter));
```

The issue is resolved, and the skybox renders again (there are probably *many* more issues that are now created, though). Here is screenshot proof from the version I built:
![dev](https://user-images.githubusercontent.com/12245827/60755533-e44a3700-9fa5-11e9-878e-00710e769e47.png)

**Comment by wwylele** [comment]
Could you place a break point on https://github.com/citra-emu/citra/blob/cae913d3d53e30003062fc594109114767c3557a/src/video_core/renderer_opengl/gl_rasterizer.cpp#L1590 and see if it gets hit when the sky appears on the screen?

**Comment by tom-overton** [comment]
Yes, the breakpoint gets hit 4 times per frame in the scenario shown in the above screenshots
