### ISSUE TITLE
FlipNote Stuido 3D Has Now Became Playable on Citra

### ISSUE THREAD

**Issue by RagdollFan2005** [citra-emu/citra#4824]
![Untitled](https://user-images.githubusercontent.com/52608114/60759764-17321080-a022-11e9-88fa-860481c1e7cb.png)

I Want to try FlipNote Studio On 3ds and now it works but yo cant use the Network but you can create animations and to send them online you will need recording soft ware and editing software
--->

**Comment by wwylele** [comment]
What do you want to say?

**Comment by RagdollFan2005** [comment]
i was able to getting it working since i was able to make a animation
