### ISSUE TITLE
Compatibility problem!!!!!!!!!

### ISSUE THREAD

**Issue by Kikita10Hl** [citra-emu/citra#4825]
Your emulator does not work for me, they should do it as a minimum more stable and make it minimally compratible with 16 bits because there are many cases like that.

If you read this, thank you.

**Comment by chris062689** [comment]
Game compatibility can be found on our website at https://citra-emu.org/game/ 
Citra only works on 64-bit machines. 

If you have any further questions please use our forums. 
https://community.citra-emu.org/
Github Issues are not to be used as a support forum.
