### ISSUE TITLE
x360 wired gamepad

### ISSUE THREAD

**Issue by DStrifer** [citra-emu/citra#4826]
I found this config but its useless, game-pad not working at all. I wanna play metroid 2 but can`t change beam type with my manual game-pad config.

ID 39: Controller (Xbox One For Windows) - Wired (Windows)
[Controls]
button_a="engine:sdl,joystick:0,button:1"
button_b="engine:sdl,joystick:0,button:0"
button_x="engine:sdl,joystick:0,button:3"
button_y="engine:sdl,joystick:0,button:2"
button_up="engine:sdl,joystick:0,hat:0,direction:up"
button_down="engine:sdl,joystick:0,hat:0,direction:down"
button_left="engine:sdl,joystick:0,hat:0,direction:left"
button_right="engine:sdl,joystick:0,hat:0,direction:right"
button_l="engine:sdl,joystick:0,button:4"
button_r="engine:sdl,joystick:0,button:5"
button_start="engine:sdl,joystick:0,button:7"
button_select="engine:sdl,joystick:0,button:6"
button_zl="engine:sdl,joystick:0,Unknown (+a2)!,threshold:-0.8,direction:+"
button_zr="engine:sdl,joystick:0,Unknown (-a2)!,threshold:-0.8,direction:+"
button_home="engine:keyboard,code:66"
circle_pad="axis_x:0,engine:sdl,joystick:0,axis_y:1"
c_stick="axis_x:3,engine:sdl,joystick:0,axis_y:4"

**Comment by FearlessTobi** [comment]
Please configure your controller directly in Citras UI.
