### ISSUE TITLE
Mario & Luigi Paper Jam Bros not showing mario & luigi in title screen

### ISSUE THREAD

**Issue by dnfanjos** [citra-emu/citra#4842]
![image](https://user-images.githubusercontent.com/25671367/61324033-60941400-a809-11e9-9eb6-c9bfb12db799.png)

THE Mario Bros didn´t appear when loading the game for the first time

Citra Nightly 1310

My CPU is Intel Core I5-7300HQ CPU @ 2.50 GHz

I have 8 gb of ram

Pls help/update this!

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use the Citra forums for help.

**Comment by dnfanjos** [comment]
i still think it should be a kwon issue
