### ISSUE TITLE
Conan instead of ext-libs

### ISSUE THREAD

**Issue by rerpha** [citra-emu/citra#4853]
Could we use [conan](https://conan.io/) in-place of the external lib submodules? 

i haven't properly looked into the code too much but i wonder if it might be easier to bring dependencies in when the cmake build is run. This might avoid having to run `git submodule update --init --recursive` manually

I am happy to give this a go if so.

**Comment by MerryMage** [comment]
> might be easier to bring dependencies in when the cmake build is run

Do note there was a previous attempt to do something similiar to this on Yuzu that was eventually reverted: yuzu-emu/yuzu#2474. (Notably their solution failed if the user doesn't have `git` installed or in $PATH, which was an issue on one of the buildbots.)

**Comment by rerpha** [comment]
> > might be easier to bring dependencies in when the cmake build is run
> 
> Do note there was a previous attempt to do something similiar to this on Yuzu that was eventually reverted: [yuzu-emu/yuzu#2474](https://github.com/yuzu-emu/yuzu/pull/2474). (Notably their solution failed if the user doesn't have `git` installed or in $PATH, which was an issue on one of the buildbots.)

OK, fair enough. This would bring an extra dependency in, conan, so may not be worth the trouble. I did make a start on this yesterday but if people think it's not a priority or not useful i will have a look at doing something else instead.

**Comment by rerpha** [comment]
Closing, I can't seem to get anywhere with it as there a few packages which are not conan-ised and i don;t think it's worth the effort.

**Comment by jroweboy** [comment]
@rerpha Is it possible to just conan-ize as many ext libs as you can and just leave the others alone? Even if we can't move them all over, its probably worth it if we can move most over

**Comment by rerpha** [comment]
@jroweboy yes it is, i will make a proper start on this soon if you think it's useful?

**Comment by SleepingSnakezzz** [comment]
This was discussed a bunch in the Citra Discord server last year. The consensus ended up being that most of the developers had bad experiences with using Conan in the past. So it was decided against using it.
