### ISSUE TITLE
Citra randomly hangs while playing

### ISSUE THREAD

**Issue by Developer-exe** [citra-emu/citra#4857]
I don't think I have a clue how to reliably reproduce this problem, but today I updated to _Citra Canary 1414_ (commit _6cfe9fe_) and after **more than an hour** of gameplay, **Citra suddenly freezes**. Audio still functions, but I can't interact with the game anymore.

GPU reports the game is running at 60 FPS, but the screen is frozen. Citra (as a whole) responds, but the game that is running is frozen. Happens **repetitively** (restarting doesn't solve the issue) and is very frustrating when in some games you can't save until you finish a chapter.

**Never happened before the update.** I was previously running _Canary 1406_. I suppose it has to do something with this:
`Service.Y2R <Warning> core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:198: (STUBBED) called`

The log file is here: [citra_log.txt](https://github.com/citra-emu/citra/files/3433030/citra_log.txt)

UPDATE: It doesn't matter how long the game is running, now it happened almost immediately (in 3 minutes). Another log file, confirming the same issue: [citra_log.txt](https://github.com/citra-emu/citra/files/3433074/citra_log.txt)

**Comment by wwylele** [comment]
Is this for a specific game (if so, which?) or for all/most games in general?

**Comment by wwylele** [comment]
Also, please always report bug base on nightly version unless the bug doesn't present there.

**Comment by Developer-exe** [comment]
This happened to me multiple times in _Project X Zone 2: Brave New World_ (European version). Will try to reproduce this on nightly version and multiple games. I'll keep you updated on this.

**Comment by Developer-exe** [comment]
I've been playing _Project X Zone 2 (EUR)_ for 30 minutes on _Nightly 1315_ (_45ff10c_) experiencing no issues at all. Then I copied my progress so far back to _Canary 1414_ (_57199fd_) and the game froze after approximately 2-3 minutes.

**Comment by wwylele** [comment]
Could you also test canary **1413**? Thank you.

**Comment by Developer-exe** [comment]
Happy to report that after 30+ minutes in _Project X Zone 2_, there are no issues at all. So something happened with the latest release.

**Comment by wwylele** [comment]
As we only open issue based on nightly/master branch, please migrate the information to #4850 which likely caused this issue. Thank you!

**Comment by Developer-exe** [comment]
Done. Glad I can help!

**Comment by wwylele** [comment]
Closing, unless this starts to happen in nightly.
