### ISSUE TITLE
OoT Crashes When Booting Up.

### ISSUE THREAD

**Issue by wynn1212** [citra-emu/citra#487]
When I trying to boot OoT, but it received signal SIGSEFV, Segmentation fault.

This is the information: http://1drv.ms/1GbQ5it
Also I try to build on windows. crashes at the same part

**Comment by Subv** [comment]
You are trying to load an encrypted game, Citra doesn't load encrypted files.
Also,

````
[  62.809664] Service.APT <Warning> core/hle/service/apt_u.cpp:Interface:324: Unable to load shared font: /home/wynn1212/.citra-emu/sysdata/shared_font.bin
````

**Comment by wynn1212** [comment]
So what can I do (P.S. I done add shared_font.bin)

**Comment by yuriks** [comment]
You'll need a 4.5 version 3DS and look for instructions on how to decrypt ROMs on the internet. We don't give support on how to do that, sorry.
