### ISSUE TITLE
Citra cannot keep screen awake

### ISSUE THREAD

**Issue by Tenchiro** [citra-emu/citra#4870]
I'm on Windows 7 and my laptop screen is set to turn off after 5min of inactivity, so screen turns off every 5min while playing in Citra **using a controller** and i need to move my mouse/press keyboard for the screen to wake up.
This occurs in both latest canary and nightly builds.

**Comment by jroweboy** [comment]
This should be resolved now. Please leave a comment here if it doesn't work, thanks!
