### ISSUE TITLE
Empty UI on Android

### ISSUE THREAD

**Issue by kenan1099** [citra-emu/citra#4883]
version / commit hash:
2f0ea48
system specs:
Model: Samsung A520F
CPU: Exynos 7880 @2GHz
RAM: 3GB
OpenGl: ES 3.2
Android 9.0

A Log file IS produced in /sdcard/citra/logs/log.txt and is of size 0 bytes. Irrelevant.
![Screenshot_20190813-212602](https://user-images.githubusercontent.com/37013292/62962986-1ce4f800-be11-11e9-8a79-d62b73a50752.jpg)

**Comment by Schplee** [comment]
We don't have an official Android release yet. Closing this issue.

**Comment by kenan1099** [comment]
Oh, Okay.
