### ISSUE TITLE
[Bug] Updating Via Maintenance tool - no space

### ISSUE THREAD

**Issue by Chaython** [citra-emu/citra#4888]
![image](https://user-images.githubusercontent.com/6486343/63070879-37cf6f00-beda-11e9-9249-183c7a25f324.png)
![image](https://user-images.githubusercontent.com/6486343/63070884-3a31c900-beda-11e9-816f-380010943d5c.png)
The maintenance tool says the installed version is 1119
Maybe this was fixed in a later build; sorry if it was.
I get the same error with citra-setup-windows.exe
I have a 10gb ram disk, where the tmp/temp are; this is the only program where I have an error.

**Comment by wwylele** [comment]
Did you install citra to A:, C: or D:?

**Comment by Chaython** [comment]
D:
________________________________

**Comment by wwylele** [comment]
Potentially should forward this issue to https://github.com/qtproject/installer-framework . However, before that, is our installer using the latest version? If not, could anyone build one and test it?

**Comment by user18081972** [comment]
I have this same problem. I dont know how the disk space check is implemented, but change it to something that isnt flawed please.
