### ISSUE TITLE
[Feature Request] Ability to blacklist/whitelist textures when dumping

### ISSUE THREAD

**Issue by Insidious611** [citra-emu/citra#4892]
This takes a bit of explaining. I am attempting to dump the textures of the game Shin Megami Tensei IV: Apocalypse. This game uses a large amount of 2D assets alongside its 3D ones, and my intent is to, for my own use and entertainment, run a scaling filter on the 2D assets such as the enemy artwork. 

However, this game constantly creates new 512x512 textures for Render-to-Texture effects, and therefore dumping textures during gameplay results in generating thousands of PNGs even when standing still, which slows the game down to single-digit FPS even on a very fast system and means that the dump folder has to have thousands of unusable and irrelevant textures removed from it to access the useful ones.

As such, I would like a way to get around this problem. I do not know if there is a way for Citra to tell if a texture was created on the fly as a render-to-texture effect, so my idea for a solution was to be able to tell Citra not to dump textures of a certain size, in this case 512x512. The game does use 512x512 textures for a number of non-RTT textures, but they aren't generally the ones I'm interested in scaling. 

I realize this is a niche feature, but I expect as the new texture dumping/custom textures feature gets used more, you'll come across more games that, without some sort of way to restrict what textures are dumped, will dump more useless textures than useful ones.

**Comment by wwylele** [comment]
please place this under the texture dumping PR. Issue tracker is only for master/nightly

**Comment by Insidious611** [comment]
Didn't realize. Sorry, done.
