### ISSUE TITLE
Monster Hunter Generation

### ISSUE THREAD

**Issue by XYProHero** [citra-emu/citra#4901]
Plss Help Me 

I got lag in my monster hunter when i face monster and go to other map and also when i play more than half hour or more early it starts to get lagger i love playing monster hunter but i experience of lag. I try to vhange my umulztor to latest but its lagger in the latest version. Help me plsss

My spec
intel hd graphics
1 core
intel celeron 1900ghz
2gb ram
256vram
Game: Monster Hunter Genneration 

citra ver:1248

Help me plss Dev i so much love this game 
I will wait for your response and I hope you can help me love you DEVELOPERS

**Comment by abdulrahmangamer** [comment]
Bro, i get that you like mhgen but that celeron cpu is too underpowered to handle emulation.
If you wanna play monster hunter, try ppsspp, i still don't think you can run ppsspp too, but try it.

**Comment by wwylele** [comment]
This is the bug tracker for developers of Citra. 

Please Use our [Citra Forum](https://community.citra-emu.org/) for questions and support instead.

If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Closed as invalid
