### ISSUE TITLE
Citra shader cache not persistent between runs on specific user accounts

### ISSUE THREAD

**Issue by HelloOO7** [citra-emu/citra#4903]
On Nightly-1343 and all versions before as far as I have checked, Citra stutters on shader compilation every time a game is run on Windows user accounts with unicode characters (ěščřž etc) in the user path. If the same game is used on an user account on the same machine without said characters, the shaders only get compiled the first time which removes any framedrops after.

Steps to reproduce:
1. Preferrably on an NVIDIA graphics card PC, create a user account with ě/š/č/ř/ž or similar characters in the user path (those I have tested).
2. Run a game in citra and play a bit, notice some framedrops.
3. Restart the game and play same as before, the framedrops are still present.
4. Repeat 2 and 3 on an user account without the characters (Administrator) - after first run, the stutters are gone.

Log file - Administrator user (less API PERFORMANCE warnings):
[citra_log_good.txt](https://github.com/citra-emu/citra/files/3538024/citra_log_good.txt)

Log file - Čeněk user (a lot of API PERFORMANCE warnings):
[citra_log_bad.txt](https://github.com/citra-emu/citra/files/3538025/citra_log_bad.txt)

What's also good to note is that there is no C:/Users/<user>/AppData/Local/NVIDIA/GLCache present on the Čeněk account but it is there on the freshly made Administrator one. What's even weirder, I found a GLCache directory in C:/Users/GLCache, googling this path yields absolutely no results. So maybe it's an NVIDIA issue which fails on cd-ing to the user directory with bad characters and creates the cache in the last working directory (C:/Users) then for some reason fails to read from it. If that's the case, could it be possible specifying the cache directory in Citra? I am pretty sure that NVIDIA wouldn't care if I reported this to them.

System specs:
CPU: AMD Ryzen 1600
GPU: NVIDIA GeForce GTX 1060
RAM: 16GB DDR4

**Comment by wwylele** [comment]
Citra doesn't handle on-disk cache at all. This is likely a bug in your driver or whatever is making the cache.
