### ISSUE TITLE
Armv7h

### ISSUE THREAD

**Issue by DannyKurniawan642** [citra-emu/citra#4904]
Please Support Citra mmj armv7h :(

**Comment by FearlessTobi** [comment]
Invalid issue

**Comment by kenan1099** [comment]
1. Citra MMJ isn't maintained by the official citra team
2. ARM v7 is 32 bit only and citra won't ever support 32 bit, just 64 bit. 
Anyways even if citra supported ARM v7 then it's not like you will be able to run anything at even slow speeds.
