### ISSUE TITLE
Pokemon X and Y Crashing when using Cheats

### ISSUE THREAD

**Issue by Ascidline** [citra-emu/citra#4905]
Hey there amazing people! I have issues that make my citra crash when I play pokemon with cheats. They work but they either slow the game down or crash it when I go to save or when I just used it. Very new to coding but need your support tell me what I need to give you to help me and how to do it. 

Thank you

**Comment by jroweboy** [comment]
Hello! This issue tracker is not used for support requests, but for tracking regressions and sometimes feature requests. Using a cheat code with a game causing issues isn't a regression, as its likely an issue with the cheat code itself, so please ask on the forums or on the discord for more help. Thanks!
