### ISSUE TITLE
Title 00000003 crash

### ISSUE THREAD

**Issue by Adeleine** [citra-emu/citra#4919]
Citra will crash if title 00000003 SAFE_MODE_FIRM is installed. This title is installed with update 11.10.0-43U. Citra seems to work fine if the title is removed from the nand, however. I'm using encrypted update 11.10.0-43U, with aes_keys to play encrypted content.

**Comment by zhaowenlan1779** [comment]
Note that you will have to use a decrypted firm for Citra to correctly load the keys. Crashing isn't good though.

**Comment by B3n30** [comment]
Iirc we just read from a specific spot in that file. We don't do any checks about the file at all. This leads to a wrong key. And then when it tries to decrypt anything with that key it fails. But that should be guarded by a try/catch section :-/

**Comment by B3n30** [comment]
#5108 should fix this. Since this is in canary, can you verify that it is fixed on canary

**Comment by SleepingSnakezzz** [comment]
Presumed fixed in https://github.com/citra-emu/citra/pull/5108
