### ISSUE TITLE
Incorrect directions for Report Combatibility when no account is connected

### ISSUE THREAD

**Issue by lambdanerd** [citra-emu/citra#4935]
Build: macOS Nightly 1356

Commit: HEAD-a65f073

Instead of

`Go to Emulation > Configure... > Web to do so.`

it should say

`Go to Citra > Preferences > General > Web to do so.`.

<img width="532" alt="Screen Shot 2019-09-15 at 5 49 29 PM" src="https://user-images.githubusercontent.com/36175659/64928712-bd985000-d7e1-11e9-9b06-aad5112d360c.png">
<img width="212" alt="Screen Shot 2019-09-15 at 5 58 18 PM" src="https://user-images.githubusercontent.com/36175659/64928786-7068ae00-d7e2-11e9-8c9b-2f09682ceb2d.png">
<img width="955" alt="Screen Shot 2019-09-15 at 5 56 33 PM" src="https://user-images.githubusercontent.com/36175659/64928793-73fc3500-d7e2-11e9-9ae2-4c8bbf0a5395.png">

I'm unsure if this is the case for the other target operating systems since this is the only system I have access to at the moment.

**Comment by Tenchiro** [comment]
There is nothing wrong with the directions citra gives, you can pretty much access it by "Emulation > Configure... > Web"
![1111](https://user-images.githubusercontent.com/53919721/64929235-17653e00-d813-11e9-97b5-33066c92b7ca.jpg)
![2222](https://user-images.githubusercontent.com/53919721/64929244-3e237480-d813-11e9-95a3-d670851496ad.jpg)

**Comment by wwylele** [comment]
This has to do with macOS + Qt black magic that automatically moves the "configuration" menu item to the macOS menu standard layout (https://doc.qt.io/qt-5/qmenubar.html#qmenubar-as-a-global-menu-bar)

**Comment by lambdanerd** [comment]
@Tenchiro This is not the case on the macOS build. I forgot to add this screenshot:
<img width="216" alt="Screen Shot 2019-09-15 at 8 39 49 PM" src="https://user-images.githubusercontent.com/36175659/64930745-2808ba80-d7f9-11e9-8eec-0c71667f4d0a.png">

Thank you for looking into it @wwylele. Looks like there is no way to change it for a specific OS. Oh well. Thanks again folks! 🚀
