### ISSUE TITLE
Monster Hunter 3 Ultimate - swkb not allowing digits in names

### ISSUE THREAD

**Issue by tywald** [citra-emu/citra#4938]
![image](https://user-images.githubusercontent.com/10337060/64999412-f91d4200-d8e7-11e9-87e1-860888b0690e.png)

Hardware:
![2019-09-17_01-07-27 555_top](https://user-images.githubusercontent.com/10337060/64999450-1e11b500-d8e8-11e9-9649-233830f05f5d.png)
![2019-09-17_01-07-27 555_bot](https://user-images.githubusercontent.com/10337060/64999452-1f42e200-d8e8-11e9-8cfa-6b913119d9e5.png)
![2019-09-17_01-08-25 109_bot](https://user-images.githubusercontent.com/10337060/64999468-3550a280-d8e8-11e9-85bc-912d836eec0d.png)

Bonus - shouldn't there be labels on the buttons for swkb?

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
me too!

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
I was making on Mii Maker, And I Wont Let To Use The Number!
