### ISSUE TITLE
maintenancetool wants to make changes

### ISSUE THREAD

**Issue by nik312123** [citra-emu/citra#4939]
I am using Citra Nightly 1357 on macOS Mojave 10.14.6.

Upon opening the citra-qt.app application, I am greeted with the following message: 
<img width="449" alt="maintenancetool" src="https://user-images.githubusercontent.com/24688726/65002027-9c099800-d8b7-11e9-93ff-3918b826ab09.png">

This message also appears upon closing the application.

This occurs every single time, which can get quite annoying.

Based on my research, this may be caused by a call to sudo.

My Citra directory is located in /Applications/ if that helps.

**Comment by Steveice10** [comment]
As far as I can tell this does not occur anymore, please let us know if it is.
