### ISSUE TITLE
Full Screen slows down games - 998b5fa

### ISSUE THREAD

**Issue by NiceGlassesDude** [citra-emu/citra#4941]
Tested on: Canary Build - 998b5fa

System: Windows 10, 32 GB ram, gtx 1080

Whenever I switched into fullscreen (F11) the game got into Slowmotion. Everything in the game including audio was extremely slow. Once I switched to windowed mode again, it run pretty fast.

Thanks to @jroweboy I switched the build to 1475 and everything runs smoothly now in fullscreen. It runs much better without stuttering or any kind of lags.

**Comment by wwylele** [comment]
Please post this under https://github.com/citra-emu/citra/pull/4940. Thank you
