### ISSUE TITLE
Citra Canary 1477 update bricks the application on macOS

### ISSUE THREAD

**Issue by Sparen** [citra-emu/citra#4942]
The September 17-18, 2019 automatic update of Citra breaks the application on macOS by seemingly performing the same way as running Citra from the command line rather than the usual behavior. This results in games unable to run at their standard resolution and at FPS levels low enough that it can be difficult to quit Citra without force quitting or manually killing the process. 

If this is an accident that will be rectified in the next build, please disregard this issue. If this is an intentional change, please note so such that affected users can download the last stable build and consider reverting the change.

Thank you.

**Comment by jroweboy** [comment]
Canary 1477 adds a new change that is known to have issues. Please repost your comment to https://github.com/citra-emu/citra/pull/4940 and use the nightly build in the mean time. I'll be posting updates to that PR, so please follow that one so you can retest when I fix you issue

**Comment by jroweboy** [comment]
> P.S. It's also worth noting that on High Sierra, Citra builds from the Citra website cannot be run due to the builds being 'damaged'

Could you please open up another issue for this bit? Does this affect both nightly and canary? (For canary only issues, we track them on the actual PR that caused the issue. For issues that affect nightly, we open up an issue on github in case you were wondering how this works :D)

**Comment by Sparen** [comment]
I'll open a separate issue.
