### ISSUE TITLE
macOS High Sierra marks all Citra Website QT builds as 'damaged'

### ISSUE THREAD

**Issue by Sparen** [citra-emu/citra#4943]
As of September 18, 2019, automatic builds of Citra uploaded to the Citra website for macOS at https://citra-emu.org/download/# (under manual downloads) cannot be run. This affects both Canary and Nightly qt builds.

<img width="420" alt="Screen Shot 2019-09-18 at 1 58 43 PM" src="https://user-images.githubusercontent.com/5430590/65173307-83ff5900-da1c-11e9-98e9-c830e74996df.png">

This error message seems to serve two purposes:  
* Mark executables that are actually broken or damaged  
* Mark executables that are not signed properly (i.e. security hazard)  

While the primary downloads for Citra are not affected (afaik), this issue prevents individual builds of Citra from being run on macOS High Sierra (and possibly others) unless the end user manually disables security features via the command line. The side effect of this is that if an update to Citra breaks compatibility, it is not possible to download a previous, working build.

This issue was made in response to a follow up on #4942

**Comment by GPUCode** [comment]
Has been fixed by https://github.com/citra-emu/citra/pull/6527
