### ISSUE TITLE
[Linux] line 43: unexpected EOF while looking for matching `"'

### ISSUE THREAD

**Issue by KAMiKAZOW** [citra-emu/citra#4951]
I get this error for several Linux distributions (Fedora 29 & 30, openSUSE Leap 15.1 & TW).

Right after calling cmake I get

    line 43: unexpected EOF while looking for matching `"'

Same for Yuzu, btw.

No idea which line 43 of which file it's referring to. The error message doesn't match a CMakeList.txt file I could find. More details: https://build.opensuse.org/package/show/home:KAMiKAZOW:Emulators/citra

**Comment by wwylele** [comment]
Could you please post the full log? (or kindly point out where to find in the detail page)

**Comment by KAMiKAZOW** [comment]
The box on the right side. Click on any of the red "failed" links. https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/citra/openSUSE_Leap_15.1/x86_64

**Comment by wwylele** [comment]
https://build.opensuse.org/package/view_file/home:KAMiKAZOW:Emulators/citra/citra.spec Line 82 you missed a `"`

Closing as this is unrelated to the main repo

**Comment by KAMiKAZOW** [comment]
Oops. Thanks a lot for pointing my mistake out. Surprised about the wrong line number, though.
