### ISSUE TITLE
Mario & Luigi: Bowser's Inside Story + Bowser Jr.'s Journey crashing with Enable Hardware Shader and Accurate Multiplication both disabled?

### ISSUE THREAD

**Issue by Ridley12** [citra-emu/citra#4958]
So, when I start BIS DX without those two enabled, the game stops responding at the screen with Peach and the four Toads (right before Mario and Luigi jump on-screen) and then Citra crashes.
Specs are Intel Core i5-6500 and Radeon HD 7850.
Citra version is 1366.
[citra_log.txt](https://github.com/citra-emu/citra/files/3678487/citra_log.txt)

**Comment by BreadFish64** [comment]
Can you confirm if this happens with hardware shaders enabled and accurate multiplication disabled?

**Comment by Ridley12** [comment]
Well, if Enable Hardware Shaders is enabled and Accurate Multiplication is disabled, the game kinda freaks out and makes the characters disappear (except when the characters start going towards the middle of the top screen, in which they are seen for a brief moment.) But there's shadow circles where the characters are supposed to be (except on the file select screen; I didn't go past the file select screen.) I would upload a video, but even the ZIP file is larger than 10 MB.

**Comment by BreadFish64** [comment]
I see, that's not necessary. This may be related to #2297, can you try turning off hardware shaders and shader hit and see if it still crashes?

**Comment by Ridley12** [comment]
Yep, the game still crashes.

**Comment by vitor-k** [comment]
Under the same circumstances, Mario & Luigi Superstar Saga also crashes. It happens in the opening cinematics, a few seconds before Mario and Luigi are supposed to appear. The game also used to crash upon launch with these settings, but it stopped somewhere between canary 1279 and 1388.

This is also something I noticed when testing: it doesn't happen with my MSVC build, neither with AppVeyor CI's.
Could you also test with a MSVC build?
(This one only has frontend UI changes, in case you can't build yourself: https://ci.appveyor.com/api/buildjobs/7cjsm1a7w8vt7j26/artifacts/citra-windows-msvc-20190928-1aba437.7z)

**Comment by Ridley12** [comment]
I use Citra QT, right? Not the other two Citra .exe files?

**Comment by vitor-k** [comment]
Yes, citra-qt.exe

**Comment by Ridley12** [comment]
Using this version I have made the following discoveries:
1. Having both disabled, the game does not crash at the specified screen, and instead plays normally.
2. Having Enable Hardware Shader enabled but Accurate Multiplication disabled, the same shadow/characters disappear issue occurs.

**Comment by vitor-k** [comment]
The issue of characters disappearing is not relevant here, as it's kind of a known issue, and can be fixed by turning Accurate Multiplication _on_. Accurate Multiplication doesn't affect the crashing.

As of my testings, the following configurations cause the crash:
-Hardware Rendering turned _off_.
-Hardware Rendering turned _on_, hardware shaders turned _off_.

Neither JIT nor Accurate Multiplication matter as of my testing, tested all combinations.

**Comment by Ridley12** [comment]
I don't disable Hardware Rendering, and JIT improves performance, so I leave those two enabled. And I leave Internal Resolution on Native. What's Linear Filtering?

**Comment by Ridley12** [comment]
Woo hoo, BIS DX doesn't crash anymore with Enable Hardware shader disabled! Using latest Nightly.
