### ISSUE TITLE
FFMpeg packages necessary to build with Cmake

### ISSUE THREAD

**Issue by g7fernandes** [citra-emu/citra#4959]
It is not a bug of Citra, but a problem with Ubuntu that people building the program may encounter. Please add the following to the https://github.com/citra-emu/citra/wiki/Building-for-Linux wiki. 

You need to make sure you have the the dev packages necessary to build with ffmpeg:
sudo apt install ffmpeg libswscale-dev libavdevice57 libavformat-dev libavcodec-dev libavdevice-dev

For ubuntu > 18.10 libavdevice57 is  libavdevice58

**Comment by vvanelslande** [comment]
anyone can edit the wiki
![image](https://user-images.githubusercontent.com/48442070/66016468-67dbcd00-e49c-11e9-8f2e-eb66fb22c97a.png)

**Comment by wwylele** [comment]
Did you build citra with any additional CMake arguments? I think it shouldn't need ffmpeg with the default configuration.

**Comment by g7fernandes** [comment]
With ` cmake .. -DENABLE_FFMPEG=ON` in order to get ACC.
