### ISSUE TITLE
Citra Android Samsung Galaxy S10/S10+ Exynos 9820 very slow

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#4967]
Hi I loaded this citra 3DS emulator for Android

https://github.com/weihuoya/citra/releases
https://github.com/SachinVin/citra_android/releases

But on the Samsung Galaxy S10 (Exynos 9820 CPU) with Android 9 is very slow. The FPS are extremely low and the sound is not synchronous. I tested New Super Mario Bros. 2 3DS rom (decrypted).

A friend of mine uses a OnePlus 7 Pro (Snapdragon 855 CPU) and here it runs very smoothly. No problems at all.

It seems that the exynos cpu doesn't work properly, because I still have an old galaxy s6 (Samsung Exynos 7420) and the same problem here.

No problems with Qualcomm Snapdragon CPU.

**Comment by wwylele** [comment]
As you already realized those are not from this repo, please ask them.
