### ISSUE TITLE
Urban Trial Freestyle 2 - Hangs when Attempting to Connect to Internet

### ISSUE THREAD

**Issue by Smoker1** [citra-emu/citra#4969]
Run UTF2
When it shows Touch to Start, it then proceeds to Connect to the Internet.

At this point, the FPS drops from 30, to 0 FPS. The Audio continues to run until the Track is finished, but it is stuck at this Screen. 

Note - This also happened to UTF1, but now runs past this point.
Note 2 - UTF1 and 2 both used to run, but after a Update last Year, UTF2 stopped being able to get past this point.

**Comment by SleepingSnakezzz** [comment]
@Smoker1 Please retest on the latest Nightly on whether this issue persists.

**Comment by benderscruffy** [comment]
still an issue
[  21.357728] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:165: unknown / unimplemented function '0x030002': port='frd:u' cmd_buf={[0]=0x30002 (0x0003, 0, 2), [1]=0x0, [2]=0x0}

**Comment by ScottNash042** [comment]
goes ingame with citra 2060 nightly
![Screenshot 2023-12-25 093015](https://github.com/citra-emu/citra/assets/139027919/5300c95e-f16f-41be-aa5f-faa129b3adaa)
