### ISSUE TITLE
citra has stoped working trying any 3ds file

### ISSUE THREAD

**Issue by synepcice** [citra-emu/citra#497]
whenever I try to launch a game (3ds Game) , Citra or Citra-qt close with this message.
I've tried all versions (x86 or x64) with Zelda Oot.3ds but nothing happen. The software close with the message : "citra a cessé de fonctionné" (in french).
I've tried the latest merged submit versions , it's the same.
Thank you for your work. Good luck !

**Comment by mattvail** [comment]
Citra will not run encrypted 3ds files

**Comment by synepcice** [comment]
I am not sure if it's the problem , But I will try tonight with an undecrypted rom ...

**Comment by synepcice** [comment]
It's Ok , It's working Fine , I was just using 3DS file encrypted. Now , with a Bin file Non-encrypted , it's working perfectly. Thank you.
