### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by farouk327** [citra-emu/citra#4970]
I am new in github so i want to ask if there is an official citra for android?

**Comment by FearlessTobi** [comment]
We are working on an official port which is one of our top priorities right now.

**Comment by jroweboy** [comment]
This is an issue tracker for developers and not a support forum. Please use the forums for support requests. https://community.citra-emu.org/

Feel free to ask stuff like this on the discord or forums in the future, but this isn't the place for questions thanks in advance! :)
