### ISSUE TITLE
Commit information request

### ISSUE THREAD

**Issue by Askmewho** [citra-emu/citra#4972]
Hi, when did you went from 3.1 to 3.3? I need the commit to do a hard reset. Thanks on advance

**Comment by jroweboy** [comment]
You'd be better off changing the current code to get it to support 3.1 than trying to build citra from 2015 imo.

**Comment by Askmewho** [comment]
2015? ive thought it was not that much ago...

**Comment by jroweboy** [comment]
Before this commit it was 3.2 as well and we still have the glfw frontend back then too. https://github.com/citra-emu/citra/pull/1087 We don't have any plans right now to lower the GL requirement because hardware shaders needs host geometry shaders at least.

**Comment by Askmewho** [comment]
@jroweboy well, you shouod try at least to support opengl 3.2 ES, because rpi4 its capable of that on hard level and mesa will reach it eventually...being so famous...  hope you think about it, we recentrly get 3.1 ES support from mesa. This has a vulkan backend too?

**Comment by jroweboy** [comment]
OpenGL ES is different than OpenGL. Please don't mix up the two, we required Desktop GL 3.3 right now and when the android release is ready, we will have a GLES backend ready too. As of now, we do not support the rasp pi, but hold tight, as GLES support is underway.

**Comment by Askmewho** [comment]
I know than they are different! Yes! Thanks for your response
