### ISSUE TITLE
pp_shader_name FXAA not fuction in Citra last Dev. (20191014)

### ISSUE THREAD

**Issue by stizzo1** [citra-emu/citra#4974]
Hi @weihuoya,

the shader FXAA, does not work in the latest version of Citra.

In the previous version instead, it works perfectly. (20190919)

My spec: Snapdragon 855, Android Pie, Xiaomi Mi 9T Pro (RedMi K20 Pro).

Thanks.

**Comment by wwylele** [comment]
You are at the wrong place.
