### ISSUE TITLE
[Transifex] Translating to Czech

### ISSUE THREAD

**Issue by Developer-exe** [citra-emu/citra#4976]
Hello,

I'm aware this is probably not the best place to post about this, but I'm interested in translating Citra to Czech. I've sent a request to join the team more than a month ago, but got no response. Is there anything I can do to get approved and start contributing? Here's a link to my profile on Transifex: https://www.transifex.com/user/profile/DavidLangr/

Many thanks in advance.

**Comment by FearlessTobi** [comment]
According to one of our Transifex moderators, you haven't sent a join request yet.
Please use the translation channel in the future for this kind of stuff.
Thanks for wanting to help though!

**Comment by FearlessTobi** [comment]
Nevermind, you were just accepted into the translation team.

**Comment by Developer-exe** [comment]
Thank you very much.
