### ISSUE TITLE
UI Scaling on higher-DPI monitors + game sorting issue

### ISSUE THREAD

**Issue by Developer-exe** [citra-emu/citra#4977]
Because there's quite a lot to read, here's table of contents:
- Incorrect scaling of the UI (it's too big)
- In-game UI scaling
- "Report Compatibility" UI scaling
- "Citra Updater" UI scaling
- How scaling the UI affects Single Line Mode setting
- Game sorting issue

### Incorrect scaling of the UI (it's too big)
I've just updated to _Canary 1492_, and this is the first thing I saw after an update:
![UIscaling1](https://user-images.githubusercontent.com/14371091/67593322-3df78c80-f762-11e9-8b98-3c43532f0b55.png)
Now that Citra scales on higher-DPI monitors, the UI is just too big for the monitor.

Previously, the UI was smaller and had a much cleaner look:
![UIscaling2](https://user-images.githubusercontent.com/14371091/67593611-d7bf3980-f762-11e9-957a-7bc932d9f6d9.png)
The latest Nightly build isn't yet affected, so I thought I'd give you some feedback before it's pushed to Nightly build.

The look of the whole UI (_Nightly 1372_):
![UIscaling3](https://user-images.githubusercontent.com/14371091/67593548-a9d9f500-f762-11e9-84b5-6d57daf8e9fe.png)

### In-game UI scaling
It's basically the same as the previous one, but I'd like to point out how it looks when launching any game (notice the icon for connecting to the room at the bottom right corner of the emulator):
![UIscaling10](https://user-images.githubusercontent.com/14371091/67595853-d5131300-f767-11e9-9072-f48bac28ab51.png)

### "Report Compatibility" UI scaling
This is just for comparison on how it looks like when reporting game compatibility from within the Citra UI (the window covers a big portion of the screen but the font is a bit smaller - please note that the image is cropped, so it's not covering the screen this much):
![UIscaling8](https://user-images.githubusercontent.com/14371091/67595955-012e9400-f768-11e9-8ef9-41c594097fb8.png)
![UIscaling9](https://user-images.githubusercontent.com/14371091/67595956-012e9400-f768-11e9-8525-f51326d641d2.png)

### "Citra Updater" UI scaling
This is fortunately not a big problem, but a persistent one for a long time (it's not updated for scaling on higher-DPI monitors). Just making sure you know about this (for consistency across your provided apps):
![UIscaling11](https://user-images.githubusercontent.com/14371091/67596394-ea3c7180-f768-11e9-9b9b-8495f408a9fc.png)

### How scaling the UI affects Single Line Mode setting
The **Single Line Mode** in Citra's configuration now doesn't affect the height of the entry (I don't know if it's intentional or not - it just swaps the text of the second row between the first and second row).

Single-Line Mode ON (_Canary 1492_):
![UIscaling4](https://user-images.githubusercontent.com/14371091/67594325-5d8fb480-f764-11e9-87c1-861384f186e3.png)

Single-Line Mode OFF (_Canary 1492_):
![UIscaling5](https://user-images.githubusercontent.com/14371091/67594385-8152fa80-f764-11e9-94ab-c8134b3977d4.png)

Single-Line Mode ON (_Nightly 1372_):
![UIscaling6](https://user-images.githubusercontent.com/14371091/67594720-44d3ce80-f765-11e9-9660-f24460184a04.png)

Single-Line Mode OFF (_Nightly 1372_):
![UIscaling7](https://user-images.githubusercontent.com/14371091/67594771-5ddc7f80-f765-11e9-8660-d87593869f31.png)

### Game sorting issue
_Canary 1492_ sorts games differently than the previous versions (like the latest _Nightly 1372_), where it would sort the games by their actual file name, giving me the opportunity to sort them to my liking (like _01-Pokemon.3ds_ and _02-Smash.3ds_ - overriding alphabetical order of the games), which seems to be gone now.
Also, it's sorted by games' names in the alphabetical order, but when the game's name (not the file name anymore) is uppercase, Citra prioritizes it over the alphabetical order.
Here's an example:
> HarmoKnight
> PROJECT X ZONE 2
> Pokémon Moon
> Pokémon X
> Project X Zone
> Super Smash Bros.

PROJECT X ZONE 2 has the name written in uppercase letters making it the game at the top of the list of games starting with the letter **P**.

Monitor: 15,5" 3840x2160@60Hz (Dell XPS 15 9560)

I hope it'll help you with fixing some of the issues. :-)

**Comment by vitor-k** [comment]
The issue tracker is for issues in nightly, for canary issues leave a comment on the related Pull Request, if possible. (in the case of game sorting, #4956)
It's also not advisable to group unrelated issues together (UI scaling has nothing to do with sorting).

As for the scaling issue, there are currently 4 PRs included in canary, with one of them not even touching the frontend. It probably wouldn't take long to check each one individually.
If you feel so inclined, here are the build artifacts from the AppVeyor CI for each of them:
#4956 https://ci.appveyor.com/project/bunnei/citra/builds/27738448/job/8w91wi9i4y54cnx4/artifacts
#4940 https://ci.appveyor.com/project/bunnei/citra/builds/27647132/job/5gnbviqirxb359sg/artifacts
#4868 https://ci.appveyor.com/project/bunnei/citra/builds/28195340/job/q0552pql3l9b9pxw/artifacts

**Comment by Developer-exe** [comment]
> The issue tracker is for issues in nightly, for canary issues leave a comment on the related Pull Request, if possible.

Didn't know that someone was already fixing this, I'll check next time before opening a new ticket for that.

> It's also not advisable to group unrelated issues together (UI scaling has nothing to do with sorting).

Sorry about that, didn't want to open 3 issues in a row.

> As for the scaling issue, there are currently 4 PRs included in canary, with one of them not even touching the frontend. It probably wouldn't take long to check each one individually.

The thing is that it's been around a month or two since updating Citra builds, so I don't know exactly when this change to Canary build happened. But it must have, otherwise the UI wouldn't have changed at all. It's not about me, just trying to provide feedback in case something was not intended to change.

**Comment by vitor-k** [comment]
About the sorting, it's the opposite. The PR is about fixing the previous behavior, in which Citra would only sort by filename in ascending order. Now it sorts based on the chosen display name, and remembers the order. I'll fix the uppercase issue, but I don't know if the change in the sorting is actually an issue.

And about the builds, neither Canary nor Nightly have been changed in almost a month, but that's not important.
The links I provided are for builds that are made automatically for the individual Pull Requests that compose the canary build, so you should be able to find which one introduced the change.

**Comment by Developer-exe** [comment]
> The links I provided are for builds that are made automatically for the individual Pull Requests that compose the canary build, so you should be able to find which one introduced the change.

After trying these, I've discovered that #4940 has different scaling (the bigger one) than the others.

#4956:
![scaling#4956](https://user-images.githubusercontent.com/14371091/67616998-10045d80-f7df-11e9-9e07-d524798f17b3.png)

**#4940** (the one where the scaling change is probably introduced):
![scaling#4940](https://user-images.githubusercontent.com/14371091/67617032-6376ab80-f7df-11e9-8e5c-2ba49b734647.png)

#4868:
![scaling#4868](https://user-images.githubusercontent.com/14371091/67617072-c36d5200-f7df-11e9-82ea-99d7401e2e11.png)

> I'll fix the uppercase issue, but I don't know if the change in the sorting is actually an issue.

It doesn't actually matter that much, just wanted to ask if it's the expected behaviour or not.
