### ISSUE TITLE
Games lag heavily when using LLE audio mode

### ISSUE THREAD

**Issue by DogeIsCut** [citra-emu/citra#4983]
[citra_log.txt](https://github.com/citra-emu/citra/files/3800172/citra_log.txt)
i am using citra nightly
![image](https://user-images.githubusercontent.com/23178844/68066841-0493c380-fd04-11e9-85b3-74b13ab5f727.png)
im trying to play tomodachi life but the voice keep cutting out, i heard LLE fixes it but it lags way to much and its unplayable.

**Comment by chris062689** [comment]
This is not a bug. LLE mode is much more intensive and is slower than HLE.
