### ISSUE TITLE
Dynamic Resolution

### ISSUE THREAD

**Issue by Colmines92** [citra-emu/citra#4988]
This weekend I was playing on Citra and while doing so I had an idea that could greatly improve performance on mid-low-end PCs and even improve the quality of graphics in some scenarios.

This is a feature that I've been seeing lately in many games: **Dynamic resolution**.

Let's say that one is playing on a mid-low-end PC where you can set the graphics to only 2x or 3x and that at the risk of getting some slowdowns from time to time. With dynamic resolution one could set a higher graphics resolution and let it scale automatically according to the percentage of speed at which the emulator is running.

Let's see, this feature would of course be optional, the user could select whether to use it or not.

I know you are very busy implementing other features and I congratulate you all on your good work. I don't know how difficult it can be to implement it, but if it works like the image I have in mind, I think it would be a great contribution.

Here is information about how Dynamic Resolution works:
https://docs.unrealengine.com/en-US/Engine/Rendering/DynamicResolution/index.html

**Comment by BreadFish64** [comment]
I think it's a good idea, but I doubt it's feasible. If I recall correctly, we destroy the texture cache every time the resolution changes. We consider this acceptable because the user will be in menu or out of game when it happens; however, if the cache is nuked while the user is playing, it's likely to cause a major lag spike.

**Comment by Colmines92** [comment]
I just downloaded vvanelslande build of citra, that implemented hotkeys to change resolution ingame and I'm switching between 1x, 2x and 3x as far as my fingers can and the speed keeps at 100% without slowdowns (I am using Mii Maker for testing).

**Comment by GPUCode** [comment]
Vulkan has improved performance a lot already, no need for this feature
