### ISSUE TITLE
Style Savvy: Styling Star - Ghost characters caused by Hardware Shaders

### ISSUE THREAD

**Issue by RocketRobz** [citra-emu/citra#4989]
I switched to a Radeon RX 570 Series graphics card, and now in Style Savvy: Styling Star, any character is white, alongside the clothing, which are half-white.
This only happens with Hardware Shaders turned on, and in this particular game.

![image](https://cdn.discordapp.com/attachments/220742362740162560/636376067543662593/unknown.png)

**Comment by SleepingSnakezzz** [comment]
@RocketRobz Please retest on the latest Citra Nightly build.

**Comment by RocketRobz** [comment]
I forgot this issue as a thing. It's been long since fixed.

**Comment by SleepingSnakezzz** [comment]
I thought as much, but I thought I'd ask to be sure. I'm currently going through all the old issues to find out which ones are still relevant today. Much needed it seems. Thanks for confirming!
