### ISSUE TITLE
Graphic glitch on Linux after Mesa 19.2.3 update

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [citra-emu/citra#4991]
Operating System: Arch Linux x64
Citra Version: master-ff931590b
CPU: AMD Ryzen 5 2600X Six-Core Processor
GPU: Radeon RX 580 Series (POLARIS10, DRM 3.33.0, 5.3.8-arch1-1, LLVM 9.0.0)
Citra log: [citra_log.txt](https://github.com/citra-emu/citra/files/3823864/citra_log.txt)

---

After mesa 19.2.3 update, some games become unplayable

for example, in Animal Crossing: New Leaf, you can get "ghost" isabelle on start:
![Screenshot_20191108_172611](https://user-images.githubusercontent.com/36147447/68465204-f63a3000-024c-11ea-9485-bcb0f9303069.png)

...or glitched title screen in Super Smash Bros.
![Screenshot_20191108_171653](https://user-images.githubusercontent.com/36147447/68465252-136efe80-024d-11ea-9d85-ebb4ed259cef.png)

In citra logs, you can see this error message spamming: 
```
API ERROR 3: GL_INVALID_FRAMEBUFFER_OPERATION in glClearBufferfi(incomplete framebuffer)
```

Seems this commit is how this glitch happened:
https://gitlab.freedesktop.org/mesa/mesa/commit/aab604398d53c9a49af6d7703e7dddad68cdd517

And the code in citra:
https://github.com/citra-emu/citra/blob/3e9c2e77d929525100f0b8b31ae583a53ef2c2dd/src/video_core/renderer_opengl/gl_rasterizer_cache.cpp#L490

**Comment by wwylele** [comment]
Does the error present in almost every game (no matter with graphical glitch or not) or only a few games?

**Comment by WUGqnwvMQPzl** [comment]
> Does the error present in almost every game (no matter with graphical glitch or not) or only a few games?

I think is affected almost every game that uses 3D, but some game like Tomodachi Life and WarioWare Gold (which some minigames that have 3D) doesn't have this problem.

And this is Pokemon Ultra Moon screenshot I just take:
![Screenshot_20191109_124718](https://user-images.githubusercontent.com/36147447/68523129-8cbf2d80-02ef-11ea-962c-b7fb35321c6c.png)

Sorry for my bad English

**Comment by javashin** [comment]
926902cc5e57342d7ca1d82531a1c1db9771a40c

**Comment by djdeath** [comment]
The Mesa commit you pointed to earlier had an issue and it was fixed by this one : https://gitlab.freedesktop.org/mesa/mesa/commit/88d665830f27087cb2188e03b0b734acc144c593

This should be fixed in the next stable release.

**Comment by wwylele** [comment]
So I assume this is completely Mesa's fault then? I am closing this. Feel free to reopen if it is proven citra actually made mistakes too.

**Comment by djdeath** [comment]
Yeah, this broke a bunch of games unfortunately. Give a try to the Mesa master branch if you feel like it.
