### ISSUE TITLE
[moderation] button not displayed with new token format server.

### ISSUE THREAD

**Issue by ANTHENA-CITRA** [citra-emu/citra#5007]
i **created** test server with new token format 
(tested on linux : citraemu/citra-multiplayer-dedicated, windows : canary-1500)

and **joined** test server with new token format on other PC. (canary-1500 used)
can join server. (displayed my profile image=token is working)

**but can't use [Moderation] button. it's not displayed.**

![image](https://user-images.githubusercontent.com/55389306/69215297-a9d7e400-0bac-11ea-8dd4-8fb1425c3312.png)
(this screenshot from old citra with old token format)

**Comment by jroweboy** [comment]
This should be fixed by #5002 so when the next build goes out, please retest to see that it works.

**Comment by ANTHENA-CITRA** [comment]
fixed!
