### ISSUE TITLE
Citra - FPS and velocity drops on Fire Emblem Echoes - Shadows of Valentia during cutscenes

### ISSUE THREAD

**Issue by OlekksandrT** [citra-emu/citra#5009]
FPS drop 60 to 20 and velocity fromm 100%-90% to 50%-60% only on cutcenes, the rest of the gameplay is normal and without problems.

[citra_log.txt](https://github.com/citra-emu/citra/files/3881859/citra_log.txt)

**Comment by wwylele** [comment]
I am not saying we don't care about performance, but if everyone opens issue for every game that they got <100% speed, the issue tracker would be full of useless info. Closing
