### ISSUE TITLE
Rendering Problem???

### ISSUE THREAD

**Issue by stizzo1** [citra-emu/citra#5015]
My PC spec:

MB Asus, CpU Intel i8700, GpU Nvidia GTX 1660 TI-6 GB Ram, 16GB System Ram.

GpU Drivers: 441.20.

The problem occured in Resident Evil Revelations. The entire screen in attached screenshot.
![ok](https://user-images.githubusercontent.com/43874809/69905268-64d45e80-13b1-11ea-9d8f-5186b6df63d9.png)

The Citra version is last Canary Build - 1f76699, but the problem appear in any version.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use the Citra forum or our Discord for help.
