### ISSUE TITLE
PR #4940 Slows down the emulation a lot when switching Virtual Desktop

### ISSUE THREAD

**Issue by John-Gee** [citra-emu/citra#5026]
Hello,

as initially written in PR #4923, here's an independant issue to track it as requested by @jroweboy . I've just tried with latest canary commit and it is still the same:

When I switch virtual desktops, Citra's performance drop to probably about the same as if I disable the hardware renderer, obviously I cannot see the FPS counter but the audio is super slow/broken apart/jittery. I tried to disable the audio to see if it would fare differently, but after waiting 10+ seconds in another vdesktop, returning in Citra would show me it's still about the same place in the intro of the game.  Now interestingly just alt-tabbing out of Citra does not cause that issue, only switching virtual desktops. Toggling vsync in the option does not change anything.

No other game/app shows that issue, so I don't think it's my system's fault, but not completely sure either.

Specs wise:
I have a 4790k with a Radeon RX 580, running on Arch Linux 64b, using Mesa for the driver, and my DE is KDE's Plasma 5.17.4.

log: gist.github.com/John-Gee/9d38443f53575e1f19f9940d414b2d0d
The game I've tried in this log is Fire Emblem Echoes, but I've just tried with the much simpler (I think) Cave Story and it was the same.

I'll be happy to add any log/information needed or jump on chat if that's more helpful.

Thank you!

**Comment by John-Gee** [comment]
I tried bisecting again, hoping to find something and now the issue stems from the commit "Reintroduce a vsync option for people with really bad drivers".

I've tried changing the value of use_vsync_new, first in the ini.h and then directly in config.cpp, to 0, but it did not change anything.

**Comment by John-Gee** [comment]
So since that commit actually is pretty small I've been trying to manually apply part of it the previous commit, Runtime Load MediaFoundation dlls on Windows, to sort of bisect the commit itself.

But I'm getting some weird behavior here; I apologize if it's a dumb comment...

When I checkout on commit ddb7ead3e421397440c135f0a82c096d6c397115, I get these:

#git log
Merge: 8b1738aea 337ac7391
Author: James Rowe <jroweboy@gmail.com>
Date:   Sat Dec 14 10:13:54 2019 -0700

    Merge pull request #5020 from jroweboy/dynamic-mf

looks as expected

#git log src/citra_qt/bootmanager.cpp
Author: Tobias <thm.frey@gmail.com>
Date:   Thu Jul 11 18:46:44 2019 +0200

    Port yuzu-emu/yuzu#2529: "yuzu/bootmanager: Minor interface tid… (#4762 

Now this one is weird, it's like there history between July and now disappeared for that file, but there should have been a lot of commits since July: https://github.com/citra-emu/citra-canary/commits/master/src/citra_qt/bootmanager.cpp

but when I checkout on commit 36c5058d669dbc223db73cd6e4116d2bb1e665c1 I get this:

#git log src/citra_qt/bootmanager.cpp
commit 36c5058d669dbc223db73cd6e4116d2bb1e665c1 (HEAD -> makepkg)
Author: James Rowe <jroweboy@gmail.com>
Date:   Sun Dec 15 15:42:05 2019 -0700

    Reintroduce a vsync option for people with really bad drivers

commit ea40eb0994a4201ebe1bf5df958de116fcd73c8c
Author: James Rowe <jroweboy@gmail.com>
Date:   Thu Nov 28 20:35:50 2019 -0700

    Use the proper parent window

    Fixes an issue where the touch point is incorrect in OpenGLWindow when the render
    target is initialized for the first time with single window mode disabled.
[etc].

which looks as I expected.

This makes me wonder if the commit 36c5058d669dbc223db73cd6e4116d2bb1e665c1 is really the culprit or if it brings along a bunch of other stuff that it should not include, and something else in there is the culprit. Is my setup incorrect? I've tried with both canary and standard citra, clean git folders, and it's the same...

**Comment by John-Gee** [comment]
I see the same in https://github.com/citra-emu/citra/blob/ddb7ead3e421397440c135f0a82c096d6c397115/src/citra_qt/bootmanager.cpp it's easy to see the missing copyright compared to https://github.com/citra-emu/citra/blob/36c5058d669dbc223db73cd6e4116d2bb1e665c1/src/citra_qt/bootmanager.cpp so it's not only in my local setup, which makes me wonder if it is not simply as it should be and I'm simply misunderstanding something.

**Comment by jroweboy** [comment]
commit 36c5058 is almost entirely filler and doesn't really change almost anything about how the code works. (Its like 99% changes to add a new option, and one line of code to apply the option) If it'd help some, we could discuss this on the citra discord https://discord.gg/FAXfZV9. If you prefer to use IRC, you can hop on #citra-dev on freenode. I'm not convinced that bisecting will show us what the problem is, since the feature only works if everything is in place. Also you may have manually changed the settings wrong if you were editing citra-qt settings ini directly (we have a default settings line in there to facilitate upgrading people's settings to a new value if they have the default, but this causes it to reset your changes if you don't remove that line when editing the file manually ^^;)

**Comment by John-Gee** [comment]
Sure message me on discord, I'm currently on citra's server. :)

**Comment by John-Gee** [comment]
In case others are interested in this, from jroweboy on discord:

> i'm guessing that when you switch virtual desktops, the operating system is limiting the application, causing less redraws. citra-qt is timed to the rate at which the OS refreshes the draw, but citra-sdl isn't (just a quirk of how i implemented it)

> the issue is how we use Qt's event loop for driving the presentation, and in SDL we just push to the screen on a separate thread entirely. It'd be a somewhat large rewrite to pull out everything Qt related from the presentation thread

> So the two solutions would be 1) fix it so we don't stall the emulation thread if presentation is too slow. 2) prevent the presentation thread from ever getting to slow. You are suggesting the second which could be a fair bit of work.

I'll keep this open until a solution comes up, but it's real easy to workaround it for now.

Thank you!

**Comment by jroweboy** [comment]
Did a small bit of investigation and found that the "fall back to unused render frame" code doesn't work as intended because of the 100 ms timeout on waiting for a presentation frame. https://github.com/citra-emu/citra/blob/439d550850c0d5cef6e07e647dfcf5df187b5e72/src/video_core/renderer_opengl/renderer_opengl.cpp#L134-L139 Changing this to better handle getting the next available frame should resolve the issue.

**Comment by John-Gee** [comment]
Awesome, thank you for looking into this and for keeping me updated!

**Comment by John-Gee** [comment]
Yup that worked, thank you for the quick fix!
