### ISSUE TITLE
Pokemon X on Citra

### ISSUE THREAD

**Issue by Kambeast18** [citra-emu/citra#5032]
When you play Citra fullsize on your macbook and you alt tab then the fps goes very low and the music also starts to slow down alot (very laggy).

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a suppport forum.
Please use our forums or our Discord for support requests.

Thanks

**Comment by Kambeast18** [comment]
Hello,

Hmmm thats weird. Discord just sent me to github and now im being sent back

Op 18 dec. 2019 om 23:40 heeft Tobias <notifications@github.com> het volgende geschreven:

﻿

Closed #5032<https://github.com/citra-emu/citra/issues/5032>.

**Comment by jroweboy** [comment]
Fixed in #5030
