### ISSUE TITLE
Citra won't take keyboard input unless the window is clicked on

### ISSUE THREAD

**Issue by viocar** [citra-emu/citra#5040]
In Citra HEAD-fe2e072, if you alt-tab back into the Citra window, you must click on the window as well or else it will not accept keyboard input.

**Comment by jroweboy** [comment]
This is regression from #4940, thanks for reporting this!

**Comment by lrosilio** [comment]
Is there any update on this one? This is *really* annoying.

**Comment by lrosilio** [comment]
Any update on this one? This is *really* annoying.

**Comment by Tenchiro** [comment]
Had this problem happen for me with the lastest update
