### ISSUE TITLE
Speed and FPS sometimes drop to 0 when loading any game

### ISSUE THREAD

**Issue by cssobral2013** [citra-emu/citra#5042]
Notes:
- This (as of today, Dec 29, 2019, 16:38 -03) is the latest Stable release;
- The games (in this case, Pokémon Ultra Moon) were running fine with older stable versions;
- The PC I'm using is a Core i3 3th gen, 4GB RAM, with an Intel HD Graphics 4000 (the below average specs to run 3DS games on Citra);
- The actual hardware doesn't seem to display this issue;
- Sometimes, this issue is not displayed.

**Comment by TheEgghead27** [comment]
Do you have any log files from when this happens? Maybe we can sort it out over on the Citra Discord

**Comment by cssobral2013** [comment]
The console result is below.

[Novo Documento de Texto.txt](https://github.com/citra-emu/citra/files/4013215/Novo.Documento.de.Texto.txt)

**Comment by TheEgghead27** [comment]
According to the Citra Bot on the Citra Discord, your drivers are out of date.
![Result](https://user-images.githubusercontent.com/45245358/71630996-31653980-2bd4-11ea-9d4c-405dbec6ac52.png)
It suggests that you should update your drivers [here](https://downloadcenter.intel.com/product/80939/Graphics-Drivers)

**Comment by cssobral2013** [comment]
Looks like I have to buy a new PC. Thank you. Can ya close this issue for
me? Happy new year!

Em ter, 31 de dez de 2019 3:49 PM, TheEgghead27 <notifications@github.com>
escreveu:

**Comment by TheEgghead27** [comment]
I'm not a dev, I'll talk to them on the Discord. 
Have a great decade!

**Comment by cssobral2013** [comment]
Updated Jan 03, 2020: I'm trying to update BOTH Citra and the video driver. If and when it works, I'll tell you.

**Comment by cssobral2013** [comment]
@TheEgghead27, updated the GPU drivers and didn't worked.

**Comment by B3n30** [comment]
This is an issue tracker for development, not a help forum.
Please use discord or the citra forums for help

**Comment by cssobral2013** [comment]
@B3n30 and @TheEgghead27: nevermind it, because it worked on Citra 1300. I'll configure it and NEVER update it. Thank you for your support, despite this issue gone beyond it's scope.
