### ISSUE TITLE
Disney Magical World Crashes In Intro

### ISSUE THREAD

**Issue by drummerix** [citra-emu/citra#5048]
I am running Citra Nightly 1399 or build id Nightly Build - 01686f7 compiled on January 1, 2020.

Disney Magical World 1 USA version boots up now, but crashes during the intro cutscene.  The Canary build will not let you input your name as you are creating your character, but the Citra Nightly does allow the name input.  I also tried getting past the intro cutscene on my real 3DS and copying over the save, but the game crashes when walking around certain areas.  I am attaching the log files in both instances.  It appears to reference an invalid address in both crashes.

[citra_log_crash_in_intro.txt](https://github.com/citra-emu/citra/files/4022343/citra_log_crash_in_intro.txt)

[citra_log_moving_in_game.txt](https://github.com/citra-emu/citra/files/4022344/citra_log_moving_in_game.txt)

**Comment by benderscruffy** [comment]
still happens
Debug <Critical> video_core/renderer_opengl/gl_rasterizer_cache.cpp:operator():953: Assertion Failed!
[citra_log.txt](https://github.com/citra-emu/citra/files/4269764/citra_log.txt)

**Comment by Trilled-Meow** [comment]
I also just had this intro scene crash after making a character/save.

**Comment by benderscruffy** [comment]
goes ingame now
no problems so far
can be closed
