### ISSUE TITLE
Texture Bug on combat in Shin Megami Tensei IV

### ISSUE THREAD

**Issue by LOuroboros** [citra-emu/citra#5052]
I always say that if a picture is worth a thousand words, a video is worth ten thousand, soo...

The effect that appears when you kill a demon with a spell called "Bufu" should look like this: https://streamable.com/zpmh5

However, it currently looks like this: https://streamable.com/q9qkq

With Citra, there's like a black square that appears before the freezing effect kicks in, which is not how it should look as you can see in the first video.

The issue could be related to #2272 but I decided to open a new issue not only because that one was pretty old and inactive, but because SMTIVA is a separate game too.

**PC Specs**
**CPU**: i3 2120 (2c/4t running at 3.29-3.30 GHz)
**RAM**: 4 GB (Single Channel)
**GPU**: NVIDIA GeForce GT 1030 (Graphics Driver v441.66)
**OS**: Windows 8.1 Embedded Industry Pro (64 Bits)

Here's my citra_log file: https://pastebin.com/ZThwCZT8

**Comment by LOuroboros** [comment]
The issue is still present on Canary 1956.

https://user-images.githubusercontent.com/4485172/114110650-6ddf1500-98ae-11eb-9f09-bdff7a9714c7.mp4

**Comment by ofsaleem** [comment]
see also https://github.com/citra-emu/citra/issues/2272 for more info / de-dup

**Comment by LOuroboros** [comment]
> see also #2272 for more info / de-dup

> The issue could be related to #2272 but I decided to open a new issue not only because that one was pretty old and inactive, but because SMTIVA is a separate game too.

**Comment by LOuroboros** [comment]
Still happening in Canary 2032 btw.

https://user-images.githubusercontent.com/4485172/150968709-404ef16f-cc5d-4f5b-a86e-92ff1988533b.mp4

**Comment by LOuroboros** [comment]
Still happening in Canary 2271.

![citra-qt_20220920_203321550](https://user-images.githubusercontent.com/4485172/191382937-b2a16449-60fa-4495-8dd6-5ec3ce3c0d92.png)

**Comment by LOuroboros** [comment]
Still happening in Canary 2329.

https://user-images.githubusercontent.com/4485172/205199956-b1e0acc9-0a03-4b40-b163-bce1a2bac932.mp4

**Comment by LOuroboros** [comment]
Still happening in Canary 2413.

https://user-images.githubusercontent.com/4485172/222064644-55fb3035-bd76-4461-98af-86034ccc056f.mp4

**Comment by LOuroboros** [comment]
Still happening in Canary 2491, both OGL and Vulkan.

https://github.com/citra-emu/citra/assets/4485172/52b6464b-b5c8-4432-9eff-5c4f89416819

https://github.com/citra-emu/citra/assets/4485172/c9e7f8bf-4717-44fd-ba44-67eeff8fc9b7

More over, now there's another issue. Sometimes, the touchscreen is all black using the OpenGL renderer.

I'll submit a new Issue ticket for that one though.
