### ISSUE TITLE
Luigi's mansion dark moon suction effect

### ISSUE THREAD

**Issue by Owen404** [citra-emu/citra#5058]
i have noticed that the suction effect has been reduced alot
![Movies   TV 1_16_2020 9_51_05 PM](https://user-images.githubusercontent.com/59988414/72581919-03a81200-38af-11ea-8c53-030d99f39c6b.png)
![I'm Too Fragile - YouTube - Google Chrome 1_16_2020 9_52_22 PM](https://user-images.githubusercontent.com/59988414/72581932-128ec480-38af-11ea-91ec-0679fec07fa8.png)

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update
