### ISSUE TITLE
Games installed via .cia files not showing up in Citra

### ISSUE THREAD

**Issue by zbrasseaux** [citra-emu/citra#5065]
I have found similar descriptions of my issue at #4117 and #3658, both of which are still open.

I have installed Animal Crossing New Leaf via the .cia file. Citra tells me it has successfully installed. In the following directory: C:\Users\Jazz\AppData\Roaming\Citra\sdmc\Nintendo 3DS\00000000000000000000000000000000\00000000000000000000000000000000\title\00040000\00086300\content, there are 3 .app files. 

I have tried restarting Citra, have tries uninstalling and reinstalling Nightly. I would try Canary, but the other threads said it didn't help.

Any insight is appreciated.

**Comment by BreadFish64** [comment]
Was the CIA decrypted?

**Comment by zbrasseaux** [comment]
How do I tell if it was?

**Comment by B3n30** [comment]
Is there a way we can show decrypted apps/3ds files in the gamelist?
e.g. with an error sign. and on double click instead of opening the game, we show an error msg (maybe with links on how to properly dump/how to dump files to get keys)...

**Comment by jvook** [comment]
Decrypt the cia to a cci file with this tool then just use it like a .3ds file

https://gbatemp.net/threads/batch-cia-3ds-decryptor-a-simple-batch-file-to-decrypt-cia-3ds.512385/

**Comment by B3n30** [comment]
Deleted comment because of piracy link...

**Comment by creikey** [comment]
I am still encountering this issue even with the CIA file in a decrypted state

**Comment by israelvillamizar22** [comment]
i am having the same issue. i tried to create a room, but the list remains blank where is supposed to add the game i am going to host. so, i cant create anything.

**Comment by emulationator** [comment]
I am having this same problem, I downloaded the Flipnote dsi .cia, which works on my 3ds. But, it wouldn’t start even though it said it was successful. I know it is not encrypted.

**Comment by lKobi** [comment]
So is Citra supporting piracy now? Since you asking if CIA was encrypted, it is supposed to be encrypted.

I have legit CIA file and AES keys in the Citra folder, yet the game does not appear on my list after installing.

So I assume Citra only supports cracked CIA, which means piracy...

**Comment by SleepingSnakezzz** [comment]
Fixed by https://github.com/citra-emu/citra/pull/5130
