### ISSUE TITLE
Regression seen on "F1 2011" missing some geometry in some tracks

### ISSUE THREAD

**Issue by MarcoEstevez** [citra-emu/citra#5067]
While ago I managed to go through entire game without issues, but during some random sessions today I noticed some tracks do have areas where part of the geometry vanishes as car approaches it.

Examples - Monaco & Valencia, I'm using canary channel. I wanted to test older versions but I got also retroarch cores, and on RA normal and canary does work fine, I believe RA is far behind Citra development builds.

RA old builds
![image](https://user-images.githubusercontent.com/3447089/72754718-e46bf600-3bc8-11ea-9bcb-71610dea9f96.png)

Citra Canary
![image](https://user-images.githubusercontent.com/3447089/72754742-f8aff300-3bc8-11ea-84aa-6e5cd24732eb.png)

**Comment by BreadFish64** [comment]
Please test nightly when opening an issue, if it is a problem with canary, then we need to associate it with a specific pull request. A [log file](https://community.citra-emu.org/t/how-to-upload-the-log-file/296) would also be useful

**Comment by MarcoEstevez** [comment]
Same issue on nightly

![image](https://user-images.githubusercontent.com/3447089/72756458-93123580-3bcd-11ea-8170-9f665811d20a.png)

Here is the log file
[citra_log.zip](https://github.com/citra-emu/citra/files/4087768/citra_log.zip)

Ill try olders builds to try find which one introduced the issue

**Comment by MarcoEstevez** [comment]
Ok I managed to find the build who first introduced this bug

Nightly 1326
![image](https://user-images.githubusercontent.com/3447089/72757531-7f1c0300-3bd0-11ea-9758-2e5d9ba5d8b6.png)
nightly-1326: Use a clear texture instead of texture 0 (solid black) in the GL rasterizer (#4844)


Here the previous one: Nightly 1325, for comparison
![image](https://user-images.githubusercontent.com/3447089/72757781-2ac55300-3bd1-11ea-8fe2-0f831b24e3dd.png)

**Comment by hamish-milne** [comment]
I just tried reverting that change (it was a fairly simple one after all), but no effect. Needs more work to debug
