### ISSUE TITLE
A link Between World taking half an hour to start

### ISSUE THREAD

**Issue by HimanshuBansal112** [citra-emu/citra#5068]
The Legend Of Zelda A Link Between Worlds take half an hour to start
and takes 5-10 minutes to close.
speed,fps is 0 and frame in nan ms
Citra Nightly version -1407
System details-:
Intel R Core(TM) i3-6006U CPU @ 2GHZ
4GB RAM
Intel R HD Graphics 520 (version-26.20.100.7584)

I don't know the reason but can tell some things after which it started.
The problem started after some things that are on changing resolution in Emulation/Configure/Graphics/Render  some times while playing game , graphics driver update , changing shader cache options in Emulation/Configure/Graphics/utility while playing game.

[citra_log.txt](https://github.com/citra-emu/citra/files/4091514/citra_log.txt)

**Comment by jroweboy** [comment]
@HimanshuBansal112 Thanks for the report, this is a known issue with disk shader cache where it loads all your cached shaders but doesn't have a progress bar *yet*. I'm working very hard to make a progress bar right now, and we'll update this when its ready
