### ISSUE TITLE
Game won't start and lags PC

### ISSUE THREAD

**Issue by PKPeri** [citra-emu/citra#5075]
Citra itself seems to be fine, but when I open a game (Tomodachi Life), everything is at 0 and Frame says "nan ms", the game won't start and my PC starts lagging until I close the emulator through task manager. I could play perfectly fine up until probably last week. This happens with both Canary and Nightly. Did this just happen randomly or could it be because I recently downloaded a new game outside of Citra?

**Comment by tgsm** [comment]
> I recently downloaded a new game outside of Citra

you're not gonna get support here if you admit you downloaded a ROM.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord or our forum for support requests.

Thanks
