### ISSUE TITLE
RPC incorrect memory locations

### ISSUE THREAD

**Issue by NimbusFox** [citra-emu/citra#5080]
Citra versions: 1413, 1550 & 1553
Friend's Citra version: 1413

It's currently hard to reproduce as I am the only one in my dev space that has encountered this issue. I am currently trying to use the RPC feature to extract pokemon data from the 3ds games. For some reason when I run the code I get invalid data from the memory call.

We used the same save file supplied by my friend

My log from my program
Invalid encryption data
Invalid encryption data
Invalid encryption data
Invalid encryption data
Invalid encryption data
Invalid encryption data
Partyy slot 1: Species Num: undefined
Partyy slot 2: Species Num: undefined
Partyy slot 3: Species Num: undefined
Partyy slot 4: Species Num: undefined
Partyy slot 5: Species Num: undefined
Partyy slot 6: Species Num: undefined

When a friend runs my code they get the correct blocks of memory and correctly gets the first pokemon from the game (the offset is most likely my fault for the other pokemon)

My friend's log from my program: (2 invalid as they only had a party of 4)
Invalid encryption data
Invalid encryption data
Partyy slot 1: Species Num: 232 (Donphan successfully obtained. Rest is most likely my code messing up)
Partyy slot 2: Species Num: 64231
Partyy slot 3: Species Num: 64339
Partyy slot 4: Species Num: 1922
Partyy slot 5: Species Num: undefined
Partyy slot 6: Species Num: undefined

[citra_log.txt](https://github.com/citra-emu/citra/files/4125110/citra_log.txt)

My pc: specs
https://i.imgur.com/RJErkYd.png

Friend's pc specs:
https://cdn.discordapp.com/attachments/671016805522866204/671850479545876484/unknown.png

**Comment by jroweboy** [comment]
Hello! I don't know what help I can offer without seeing the code in your script. Are you taking into account different regions of the game will likely have different memory locations for these sort of things?

**Comment by NimbusFox** [comment]
Pokemon is non region specific last I checked for the 3DS game. They have no region specific releases

**Comment by NimbusFox** [comment]
Just confirming on 3dsdb.com they all share the same title id https://i.imgur.com/Vjx1hl9.png

**Comment by NimbusFox** [comment]
Should've mentioned. Omega Ruby is out testing game but I have the memory locations for all the pokemon games and they are consistant on my friend's pc

**Comment by NimbusFox** [comment]
If needed I can share the nodejs program I am coding to help with figuring out what is going on

**Comment by jroweboy** [comment]
Fair point. But I'm still unsure what I can do without seeing the code and testing it out myself. I'm unaware of anything that would change the guest memory locations that the RPC would read. Note that the RPC read is currently not synchronized with the guest emulation, meaning it could read something that is already out of date by the time you receive the data, but that doesn't sound like the issue you are experiencing.

**Comment by NimbusFox** [comment]
Let me zip up my js code and you can have a play

**Comment by NimbusFox** [comment]
https://cdn.discordapp.com/attachments/671016805522866204/671450313609314320/citra.zip

In the app.js change 

pokelink.Version.ORAS to pokelink.Version.(XY/ORAS/UM/USUM) depending on your version.

It should identify the first pokemon's ID

**Comment by jroweboy** [comment]
One more thing to check, but you are both using the same rom version right? https://www.serebii.net/omegarubyalphasapphire/patch.shtml I just remembered there were different versions of the game and it can't hurt to double check that.

**Comment by NimbusFox** [comment]
Will check with them tomorrow as they have gone to bed now

**Comment by NimbusFox** [comment]
Ok fun fact and in true mystery bug fashion... my program is behaving... and so is the rpc.

I wish I could explain what is going on. But... yeah... sorry for wasting everyone's time

**Comment by NimbusFox** [comment]
For future reference. It was because of Pokemon Y 1.5 moving the pokemon memory location that made me believe it was software based. Nope as Pokemon X 1.0 was fine
