### ISSUE TITLE
Error R6025 - Pure Virtual Function Call

### ISSUE THREAD

**Issue by schubertguilherme** [citra-emu/citra#5085]
Hi team... this error appear during playing and close emulator. I test various versions Windows 8.1 x64, update Library C++ but this error continue. 

Down example the error appear:

![images](https://user-images.githubusercontent.com/36903073/73609762-a058f800-45af-11ea-9e8e-ca102bb57cd3.png)

**Comment by FearlessTobi** [comment]
I don't really see how this issue is about Citra.
If you believe it is, please ask on our forums or our Discord.

Thanks.
