### ISSUE TITLE
Mods failing to load properly

### ISSUE THREAD

**Issue by ArMM1998** [citra-emu/citra#5090]
So I'm trying to load an english patch but citra is failing to load the graphics properly.   
Here are some screenshots https://imgur.com/a/MTfAzGl

The log is a memory error spam after all the files are loaded when launching the game
[citra_log.txt](https://github.com/citra-emu/citra/files/4184028/citra_log.txt)

My guess is that it's because they're too many files trying to be loaded at once maybe?

**Comment by jroweboy** [comment]
LayeredFS is still in development on this PR https://github.com/citra-emu/citra/pull/5088, please move comment to that thread instead.
