### ISSUE TITLE
Error R6025 In New Releases

### ISSUE THREAD

**Issue by schubertguilherme** [citra-emu/citra#5092]
This error happen more peoples, driver update, Library C++ update... in releases November not happen this error. I test difference options in emulator, sound, graphics etc... but this error continues... and happen during playing the game.
![THFGHFG](https://user-images.githubusercontent.com/36903073/74380214-f1df5f00-4dc7-11ea-9a6c-7a47869e2e8e.jpg)

**Comment by BreadFish64** [comment]
This is related to your system's configuration rather an issue in Citra. Please use our [forums](https://community.citra-emu.org/) or [discord server](https://citra-emu.org/discord/) for support requests.
