### ISSUE TITLE
New after updating to Nightly 1435 -- PS4 controller behavior changes

### ISSUE THREAD

**Issue by DimensionWarped** [citra-emu/citra#5118]
My previous version was a few days old, not sure on the exact number, but not more than a week.

After updating to Nightly 1435, when starting Citra the light on my PS4 controller (connected via USB, normally set by Steam) reverts to its standard color of bright blue. In addition, the mappings of all the buttons have changed in a somewhat strange way which initially caused some confusion. The directional pad used to show up as directional pad buttons but now appears as a left - Button 13, right - 14, up - Button 11, down - Button 12. A number of the face/trigger buttons also changed, but I think the axes for the analog sticks stayed the same.

I looked through a list of recent pull requests and nothing exactly jumped out at me. If there is a way of reverting to a previous nightly I could give that a shot.

The effect takes place immediately upon loading citra, before loading any roms or anything.

<!---

Please read the FAQ:
https://citra-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

[citra_log_controller_issue.txt](https://github.com/citra-emu/citra/files/4272219/citra_log_controller_issue.txt)

**Comment by FearlessTobi** [comment]
Thanks for your report.
It is probably caused by this: https://github.com/citra-emu/build-environments/pull/22.
We're currently investigating.

**Comment by B3n30** [comment]
Seems like the mapping inside SDL changed. I don't think this is really an issue we can fix. Just configure your controller again in the settings should fix it though

**Comment by vitor-k** [comment]
To elaborate further: SDL2.0.9 introduced hidapi drivers for PS4, Switch and Xbox controllers. 
I haven't read all of the driver files, but the new driver seems to have access to things like the lightbar of the PS4. During initialization the lightbar is set to (0,0,80) and there is currently no way to control it. (The value is hardcoded in the function that handles rumble)
The change in button mapping is expected for a driver change.
As there are other problems also caused by hidapi drivers, it may be necessary to disable them partially or completely in the near future. 
Whatever the solution ends up being, you'll be notified by Github when the issue is mentioned and eventually closed.

**Comment by vitor-k** [comment]
I've submitted a bug report on the lightbar behaviour to the SDL development bug tracker, and a fix is underway on their part.
The proposed solution is to have behavior similar to what Linux does it, with different colors based on the user, matching the PS4's. Keeping the previous color doesn't seem to be possible, while setting a custom color from SDL/Citra would probably take some work.
I'm investigating the issue to check if there isn't a different solution to the bug, so I request your cooperation in confirming the following:
You set your lightbar color via Steam's big picture mode controller settings, is that correct?
Are you also running Citra through Steam?

**Comment by DimensionWarped** [comment]
Yes to Steam's controller settings (though I don't really run it in Big Picture... it does use a big picture style interface for whatever reason), no to running Citra through Steam. I'm just running Citra through the executable file.

**Comment by vitor-k** [comment]
I don't think it's reasonable to expect Citra to keep Steam's color for the light bar if it's not run through Steam.
That being said, it'd be nice to test the behavior when running Citra through Steam, big picture mode or not.

**Comment by DimensionWarped** [comment]
I hadn't thought to do that before, so I just did.

The good news... is that loading Citra through Steam doesn't change my controller's light bar color.

The bad news is that Citra can't receive any input from the controller that way. Trying to remap the controls doesn't work since it won't respond to button presses or analog movement.

**Comment by vitor-k** [comment]
I was going to borrow a PS4 controller from a local place to test this, but it's closed due to a certain pandemic.
When you ran Citra through Steam, did you check the "playstation configuration support" checkbox?

**Comment by DimensionWarped** [comment]
I assume you mean the checkbox for Playstation Configuration Support in the controller settings menu, and if so, yes.

![image](https://user-images.githubusercontent.com/7477617/76974092-c7b91980-68fe-11ea-8d9a-33389dbf6349.png)
