### ISSUE TITLE
Inazuma Eleven:Galaxy Multiplayer lag

### ISSUE THREAD

**Issue by Ionutman** [citra-emu/citra#5121]
During multiplayer matches the player who joins a hosted match experiences lag and high delay which can make it almost unplayable.
-Problem always existed and persists in Citra Nighty 1391
-High Levels of lag and delay ruin the multiplayer experience

**Comment by SleepingSnakezzz** [comment]
Closing in favour of https://github.com/citra-emu/citra/issues/5122
