### ISSUE TITLE
Black textures when lightning uniforms are not initialized

### ISSUE THREAD

**Issue by marccane** [citra-emu/citra#5129]
Discovered on 01686f78f (linux) and checked against latest nightly ad3c464 (windows). Disabling hardware renderer/shader jit doesn't affect the output.
System specs don't appear to be relevant since the two machines i've tested with have nothing in common.
Log doesn't have anything relevant.

![Citra 01686f78f](https://user-images.githubusercontent.com/7304787/76692079-b39cc000-6651-11ea-8f34-ac795409e33f.png)

![3DS](https://user-images.githubusercontent.com/7304787/76692047-49841b00-6651-11ea-95ab-b3c72396974b.png)

CPP project, binaries included:
[globeCitra.zip](https://github.com/citra-emu/citra/files/4333540/globeCitra.zip)
Removing lines 142 and 138 from main.cpp makes it render correctly in Citra.

**Comment by benderscruffy** [comment]
still a problem on opengl ,software and Vulkan using Canary 2600

**Comment by GPUCode** [comment]
More lighting bug 👀

**Comment by GPUCode** [comment]
This is hard to test as vertex shader uniforms may be preserved from home menu/homebrew launcher and it accidentally works in this case

**Comment by GPUCode** [comment]
I did some tests and vertex uniform appear to be radomly set based, so closing as something that we can't realistically fix
