### ISSUE TITLE
(Donkey Kong Country Returns 3D)The Tie and Barrel is not rendering

### ISSUE THREAD

**Issue by RianCaio** [citra-emu/citra#5136]
https://www.youtube.com/watch?v=H-gk6fH8Bao
This is on the latest citra canary

https://www.youtube.com/watch?v=o2TlOOuk1Vw&list=PLYpDU5ElRBfk1ZUniPwIGfvNgFA54LCwb&index=2
This is on the hardware

**Comment by FearlessTobi** [comment]
Please get us a log and your system specs.

**Comment by RianCaio** [comment]
where i get the log

**Comment by RianCaio** [comment]
[citra_log.txt](https://github.com/citra-emu/citra/files/4350407/citra_log.txt)
I5 7400
GTX 1050
8GB Ram

**Comment by RianCaio** [comment]
Well,All that appears when you put 25% CPU Clock Speed

**Comment by legend800** [comment]
Why is this a bug then? What am I missing here? Put the cpu at 100% and play the game properly.

**Comment by wwylele** [comment]
Please report to #5025 as this is still in development.

**Comment by RianCaio** [comment]
> Why is this a bug then? What am I missing here? Put the cpu at 100% and play the game properly.
But the game is buged at 100% cpu

**Comment by legend800** [comment]
The game plays perfectly on the latest canary (at 100% cpu). Troubleshoot issues on the forums, not here.

![2020-03-21 11_34_07-Citra Canary 1606 _ DK Country Returns 3D](https://user-images.githubusercontent.com/20983844/77233946-29c88780-6b68-11ea-9cd7-09b301e8effb.png)

**Comment by vitor-k** [comment]
I believe RianCaio hasn't expressed the issue well. Based on the video and a previous report on the same bug, the problem is that some visual elements don't show on the loading screen.
Specifically the tie that swipes the screen and the barrel that appears on the bottom right.
@legend800 can you confirm whether these elements appear on your end?
[Here's](https://youtu.be/jHDBFy17N6o?t=1613) a timestamped video to compare to the [poster's](https://www.youtube.com/watch?v=H-gk6fH8Bao)

**Comment by legend800** [comment]
Well there's a few tie swipes when loading lvls - the first one does appear truncated but the lvl load done one is fine. Not sure what barrel you're talking about. 

![2020-03-21 18_37_12-Citra Canary 1606 _ DK Country Returns 3D](https://user-images.githubusercontent.com/20983844/77240447-04a53a80-6ba3-11ea-9f6e-e594fcb035fc.png)

**Comment by benderscruffy** [comment]
Has this been fixed ???
Please update

**Comment by benderscruffy** [comment]
can be closed 
the tie goes across and don't know what barrel his is talking about
