### ISSUE TITLE
Texture Filtering doesn't work in Metroid Prime Federation Force

### ISSUE THREAD

**Issue by SnesDna** [citra-emu/citra#5138]
this may be related to #3679, but it would seem that Federation Force has trouble with texture filtering turned on.
Version is Canary 1605
Here is how it looks at native resolution
![example3](https://user-images.githubusercontent.com/62406669/77123265-e30a4e80-69fc-11ea-8310-432c172cbab9.png)
 and here is the game scaled to 6x native resolution
![example4](https://user-images.githubusercontent.com/62406669/77123366-3086bb80-69fd-11ea-8ea9-6a88c43184a9.png)
here is the game with bicubic texture filtering set to 1, at 6x native resolution
![example1](https://user-images.githubusercontent.com/62406669/77123424-57dd8880-69fd-11ea-8ab8-05c34b9e99d2.png)
and here is the game set to 6x native resolution with bicubic filtering set to 2
![example2](https://user-images.githubusercontent.com/62406669/77123478-793e7480-69fd-11ea-93b3-0c18d6dc1e85.png)
Log
[citra_log.txt](https://github.com/citra-emu/citra/files/4357289/citra_log.txt)

**Comment by BreadFish64** [comment]
Hmm, I actually do see a difference in the text, although it's hard to tell if the surface was rescaled to 1x after filtering. Bicubic is naturally a little fuzzy on the edges.

**Comment by Bearborg** [comment]
If I'm understanding this correctly, this is an issue that only appears with a texture filter factor of 2 or greater. Since texture filter factor was removed as an option in #5166 , can this be closed?

**Comment by SleepingSnakezzz** [comment]
Texture filter factors no longer exist. So this issue does not appear relevant anymore. Although, if you're still experiencing the same issue with texture filters in the latest Citra Nightly build, feel free to reopen this issue/open a new issue for this.
