### ISSUE TITLE
Graphics Problem

### ISSUE THREAD

**Issue by mafnankhattak269** [citra-emu/citra#5140]
https://gyazo.com/113a85fe062347d5816ddb7d98099064
Seriously, What Is Wrong With The Graphics? I Just Saved The Game, Didnt Stop Emulation, Straight up Pressed The Exit Button, And That Happened.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord or our forum for support requests.
Thanks.
