### ISSUE TITLE
[Crazy feature request] Stream bottom screen to LAN smartphone and use its touchscreen to control it

### ISSUE THREAD

**Issue by EddyHg80** [citra-emu/citra#5155]
Hi everybody,

I know this is nuts, but I had this idea and I wanted to share it.
What I have in mind is an app, or a section in the Citra app itself when it will release, that let you connect to your pc via LAN, or even USB (I don't really know what would be the most practical method) and stream the bottom screen to your smartphone and control it via touchscreen.
In the same environment could be implemented an option to activate motion controls and on screen buttons.

I just think it could be cool 😅

**Comment by BreadFish64** [comment]
This is not likely to happen. All of this is possible via third-party solutions and it would be a lot of work for us.

**Comment by EddyHg80** [comment]
Yeah I thought it would be the case, still I wanted to post it :)

**Comment by Ghostotakoi** [comment]
![bugs_bunny_diciendo_no](https://user-images.githubusercontent.com/20958581/77812571-8223eb80-7078-11ea-9524-29ee161739e0.jpg)

**Comment by SleepingSnakezzz** [comment]
This appears to be something that the team is not interested in implementing or maintaining. Additionally, third party solutions can be used for this purpose instead.
