### ISSUE TITLE
Portal3DS - Not Rendering Correctly in Nightly

### ISSUE THREAD

**Issue by Schplee** [citra-emu/citra#5158]
Portal3DS has not been rendering correctly since nightly-1249 due to #3910

The game renders correctly on hardware, tested via my Original 3DS XL

In the latest nightly (nightly-1458), the issue can be fixed by disabling the Hardware Renderer

**Hardware Renderer disabled**
![nightly-1458-hardware-renderer-disabled](https://user-images.githubusercontent.com/24275329/77864040-46edfd80-71db-11ea-85c4-a897894e7ebd.png)

**Hardware Renderer enabled**
![nightly-1458-hardware-renderer-enabled](https://user-images.githubusercontent.com/24275329/77864042-49505780-71db-11ea-9791-c910e8f0032a.png)

Here is the log file: 
[citra_log.txt](https://github.com/citra-emu/citra/files/4400132/citra_log.txt)

Issue definitely seems related the mipmaps, as it spams variations of the following when running the game:
`Render.OpenGL <Critical> video_core/renderer_opengl/gl_rasterizer_cache.cpp:GetTextureSurface:1517: Texture size (64x64) does not support required mipmap level (10)`

Here is a link to the homebrew to replicate the error: https://drive.google.com/file/d/1PXyEOF8Nz-aQ2N7-Bgekfa1NvIbfg2vk/view?usp=sharing

**Comment by SleepingSnakezzz** [comment]
Fixed by https://github.com/citra-emu/citra/pull/6375
