### ISSUE TITLE
A link between words Dlc?

### ISSUE THREAD

**Issue by Kalem123123** [citra-emu/citra#5160]
Hyrule warriors works fine on my computer... after the update 1.6 i got the 3 maps (kolohint, wind waker and grand travel map) but cant find the lorule map... the other features such as the max lvl extended to 225 is there...so any idea how to get the map???

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord or forum for support requests.
Thanks
