### ISSUE TITLE
Web issue with game list

### ISSUE THREAD

**Issue by Steamsweet** [citra-emu/citra#5164]
![issue 1](https://user-images.githubusercontent.com/53945997/78180658-613a0c80-7463-11ea-9151-a89a07acce82.PNG)

all games wich i installed cant show up threre kompability

**Comment by Steamsweet** [comment]
![image](https://user-images.githubusercontent.com/53945997/78181444-add21780-7464-11ea-9f86-78c1376b5f48.png)

there are also an issue on the webpages

**Comment by FearlessTobi** [comment]
The website is missing the titleids for the games of your region.
We're planning to fix this sometime in the future.

Closing as this is not an issue with Citra itself.
