### ISSUE TITLE
Crashes when new texture filtering options turned on

### ISSUE THREAD

**Issue by enderandrew** [citra-emu/citra#5167]
Citra Canary 1629 HEAD-6273763

In several games I've tested, Citra will crash quickly in game with the new Graphics - Texture Filter option turned on. I can play the same games just fine with no crashing if the feature is turned off. For a more specific example I load New Super Mario Bros 2 3DS Gold Edition and load my save. I can go to the world map, but once I enter a specific level, it crashes before I can play the level.

I can reproduce this repeatedly, and the crash goes away as soon as I turn the feature off.

I have the same crash with other games I've tried.

**Comment by BreadFish64** [comment]
Hi, can you please upload a log of the crash?

**Comment by BreadFish64** [comment]
I tested the issue myself and I believe it will be fixed by #5166

**Comment by BreadFish64** [comment]
The fix is in Canary now, please confirm whether it works for you.

**Comment by enderandrew** [comment]
Sorry I didn't get you a log in time, but looks like you fixed it all the same. I just downloaded the latest Canary build from 3 hours ago and the crash is gone.

However I also noted there is no longer an option to select a scale on the Texture Filter. I assume that is intended.

But feel free to close this bug.

**Comment by BreadFish64** [comment]
Yes, the scale setting was intentionally remove. Thanks for checking 👍
