### ISSUE TITLE
Crashing issue when exiting citra if you skip update pop up notification

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#5168]
So citra is crashing every time you try to exit it, and thats if you launch a game directly without waiting for the update notification to show up.

![crash](https://user-images.githubusercontent.com/53919721/78238190-d3ded280-74cb-11ea-8f5f-1ca152dbe3f0.jpg)

**Comment by SleepingSnakezzz** [comment]
I cannot reproduce anymore. Seems like it was fixed at some point. Closing for now.
