### ISSUE TITLE
Minecraft v19 softlock on menus NOT v0 minecraft on Citra Canary 1631

### ISSUE THREAD

**Issue by Littlemac123** [citra-emu/citra#5171]
+

sometimes if im lucky I can go threw the menus really really fast and try to start the game but then it just softlocks forever Building the terrain. here is a log I got from it https://cdn.discordapp.com/attachments/572182622097375234/695535202549891072/citra_log.txt

to recreate this crash make shore you have V1.9 or the current update witch is 1.9 as of today and just go in the menus and move around up and down and it will softlock with the music still playing running at 100% 0FPS.  here is a log softlocking from the menus. https://cdn.discordapp.com/attachments/572182622097375234/695536631096016908/citra_log.txt

and yes all this stuff does work on real hardware its just broken rn in citra
and dont confuse this with a normal minecraft game with no updates, that works fine in citra with no menus crash. thank you for your time

**Comment by SleepingSnakezzz** [comment]
@Littlemac123 Please retest on the latest Citra Nightly build.

**Comment by benderscruffy** [comment]
@GPUCode 
using canary 2618
still an issue
this was the last line of the log
[ 336.946384] Debug <Critical> ./core/hle/ipc_helpers.h:operator():456: Assertion Failed!
Tried to pop mapped buffer but the descriptor is not a mapped buffer descriptor

**Comment by GPUCode** [comment]
Fixed by https://github.com/citra-emu/citra/pull/7159
