### ISSUE TITLE
Digimon World Re:Digitize Decode Video Input Button

### ISSUE THREAD

**Issue by Romsstar** [citra-emu/citra#5172]
Never actually worked so not a regression:

When pressing start during a video (any) in the game, a prompt to skip the video pops up.
During this citra slows down to 4%. So it will take anything from 30 secs to 1 minute to actually skip the video (by the time most videos are actually over already).

Using Canary 1632.

**Comment by Romsstar** [comment]
Pushing this, would be nice if someone looked into it.

**Comment by Romsstar** [comment]
![microprofiler](https://user-images.githubusercontent.com/17484361/101671004-35404380-3a54-11eb-9471-4b5081c2b4f0.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/5667864/citra_log.txt)

Log File and Microprofiler attached as per suggestion.

Underclocking to 25% sometimes seem to fix the issue but most of the time will just lead to crashing.

**Comment by Shideravan** [comment]
How the cinematics play for you if you don't skip them? I also have a big drop in fps in the cutscenes, then don't skip then isn't even a option :(

**Comment by Shideravan** [comment]
Here's my citra log for the latest version (Canary 1926)
[citra_log.zip](https://github.com/citra-emu/citra/files/5770367/citra_log.zip)

**Comment by Romsstar** [comment]
Pushing this become new information has come to light since.
https://github.com/citra-emu/citra/pull/4089 used to fix that but since it was a "hack" it was not the proper solution I suspect.

So in way this is a regression but not really since jroweboy was opposed of having this a solution in the first place.
I suspect it's not something that is easily fixable in this case.

**Comment by SleepingSnakezzz** [comment]
@Romsstar Could you try this out again. There have been changes to both FMVs (cutscene) and to the N3DS mode setting. So I'm wondering what the current status of this issue is.

**Comment by Romsstar** [comment]
Cutscene playback is much improved but the bug where it slows down when you press start still occurs, so I'd suspect there are still some issues with the scheduler present.
