### ISSUE TITLE
[Feature Request] Save State/Load State Button Mapping

### ISSUE THREAD

**Issue by robzombie91** [citra-emu/citra#5175]
With the newly added save state/load state features i think having the ability to map buttons to loading/saving states would be a nice addition for quick loading/saving

**Comment by jroweboy** [comment]
Thanks for the report! We decided that we would improve the UI after we have finished testing save states. Consider what is there a debug UI for the time being. If you would like to leave more feedback on the change, please leave a comment on the PR instead. https://github.com/citra-emu/citra/pull/4908

**Comment by Drayano** [comment]
Is there any plan for this feature now that the PR has been merged ? We can already map save to oldest and load from newest but no control over each individual slot is possible from hotkeys :/
