### ISSUE TITLE
Mario Golf World Tour cannot load menus

### ISSUE THREAD

**Issue by legend800** [citra-emu/citra#5177]
Upon boot, the game soft locks on this screen and cannot by bypassed:

![2020-04-01_22_09_27-Window](https://user-images.githubusercontent.com/20983844/78461387-4e028900-767d-11ea-81d5-536754ccf4a6.png)

[island tour.zip](https://github.com/yuzu-emu/yuzu/files/4432529/island.tour.zip)

Version: 
1633

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4.5 ghz
16GB RAM

**Comment by nnn1590** [comment]
Same here (I'm using the Japanese version of the game)
[citra_log.txt](https://github.com/citra-emu/citra/files/11162648/citra_log.txt)

Citra version: HEAD-84e54a52a
CPU: Intel Core i7-2700K
GPU: Radeon RX 570
OS: Ubuntu 20.04 LTS amd64
RAM: 16GB
Qt: 5.15.8(GPL/LGPL), static build
CMake command line: `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_FFMPEG_AUDIO_DECODER=ON`

**Comment by benderscruffy** [comment]
goes ingame now 
can be closed
