### ISSUE TITLE
Support encrypted 3DS file and its sav file

### ISSUE THREAD

**Issue by KPSH7AmcSRcfCqdJ** [citra-emu/citra#5182]
Hello developers,

I had a Sky3DS flash card in my Nintendo 3DS for years.

But my Nintendo 3DS with my flash card is no longer here. :(

Fortunately I still have the sav files and the encrypted 3DS file on my PC from the flash card.

How can I use this sav files in Citra? Is it possible to support encrypted 3DS files?

**Comment by jroweboy** [comment]
Citra already supports encrypted games https://citra-emu.org/wiki/aes-keys/

**Comment by vvanelslande** [comment]
reopen this issue because Citra doesn't support encrypted saves

**Comment by jroweboy** [comment]
@vvanelslande make a new issue if you think we should support encrypted saves

**Comment by B3n30** [comment]
> Is it possible to support encrypted 3DS files?
yes but you need to provide the keys for decryption. You dump those from your 3ds

> How can I use this sav files in Citra?
You need to dump (decrypt) them from your 3DS. In the future we might support encrypted save games but you still need keys from your 3DS

nevertheless this is not a valid issue or feature request. So it stays closed (there is already a feature request for encrypted save support)

**Comment by vvanelslande** [comment]
they don't have a 3DS

**Comment by KPSH7AmcSRcfCqdJ** [comment]
But I no longer have my Nintendo 3DS.

Is there no way to use the sav file from the flash card?

The save data is very important. The most important for me.
I've played more than 400 hours.

**Comment by B3n30** [comment]
Buy a cheap 2DS and dump them from there. There is nothing more to say. 

Also this is an issue tracker for development, not a support forum. Please use discord or the forums for such questions.

**Comment by KPSH7AmcSRcfCqdJ** [comment]
What if there are no more nintendo 3DS or 2DS in the future?

you rarely get answers about this topic in the forum. besides, everything depends on what the developers do.
