### ISSUE TITLE
IEGO Galaxy: Framerates dip lower and lower with time.

### ISSUE THREAD

**Issue by AkiraJkr** [citra-emu/citra#5187]
Issue that occurs with the latest Canary(1640), or older versions of Citra.

As you start the game, the performance of it is normal, and what is to be expected from the rest of the games of this series. But as you play the game further and further, the framerates keeps getting lower, and the RAM usage increases, until it becomes an unplayable, 5 FPS mess. The lower your RAM, the less time you can play the game.
![image](https://user-images.githubusercontent.com/27028529/78741955-11f74e80-7931-11ea-9359-6ac46b966794.png)
_RAM usage after about five/ten minutes of playing_
![image](https://user-images.githubusercontent.com/27028529/78741801-b5942f00-7930-11ea-9291-6d044586ca65.png)

Unless you change the internal resolution of the game, which seems to fix the framerate issues and clean some of the RAM usage. Although it happens over and over.

![image](https://user-images.githubusercontent.com/27028529/78741914-fd1abb00-7930-11ea-8941-85979919fa39.png)
_RAM usage immediately after switching to another internal resolution_

Interestingly enough, is that this issue only happens in Inazuma Eleven GO Galaxy, and not in the previous titles.(GO1 and Chrono Stone) Since you could play those games for several hours on end with 30 FPS(specially with the recent fix to the performance issues on dialogues like the 2nd image.), story or not.

If a video example is needed, here is one with a timestamp to a more notable area. https://youtu.be/OmdAKAEk6mQ?t=805

**Comment by SleepingSnakezzz** [comment]
@AkiraJkr Please retest on the latest Citra Nightly build.

**Comment by AkiraJkr** [comment]
Tested for over a hour and so and I never saw a increase in RAM usage that seemed abnormal, or a performance decrease with the latest, so I'll take it this issue was fixed.
