### ISSUE TITLE
Picross 3D Round 2 - No pictures while selecting puzzles

### ISSUE THREAD

**Issue by fefo-dev** [citra-emu/citra#5192]
Picross 3D Round 2 - No pictures while selecting puzzles
Nightly 1465 | HEAD-23921e3 (2020-04-07)
log file: https://pastebin.com/LtMNnaDv

While playing this game I found the aforementioned issue, which is properly outlined in it's wiki entry: https://citra-emu.org/game/picross-3d-round-2/

![](https://images2.imgbox.com/77/a3/KEyLIXnm_o.png)

However, while looking if there was already a mention to it on the issue tracker (none so far) I found https://github.com/citra-emu/citra/issues/2521, in which there's a print of the expected behaviour on this case. Have you traced what caused this rollback?

Thanks a lot.

**Comment by windwakr** [comment]
I think this was caused by #2884.

**Comment by dekiertanna** [comment]
The issue is still present, despite issue #2884 having been resolved.

Citra Version: Nightly 1621  | HEAD-df9e230
Host CPU: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
Host OS: Windows 10 (10.0)

Log below:
[citra_log.txt](https://github.com/citra-emu/citra/files/5250264/citra_log.txt)

**Comment by Kriskras99** [comment]
They do render for the combined puzzle, but doesn't show the individual puzzles. 
![Screenshot from 2022-06-02 12-13-07](https://user-images.githubusercontent.com/6293125/171608574-f01c1e42-d4b6-4afc-8055-c0fa6b60fab0.png)
![Screenshot from 2022-06-02 12-13-00](https://user-images.githubusercontent.com/6293125/171608578-fdb8b692-991e-44e0-b9ec-6c8e35064256.png)

**Comment by Nukle0n** [comment]
Still present in 1769

**Comment by benderscruffy** [comment]
using the latest nightly it is still an issue

**Comment by AncientPixel** [comment]
I think this has become an issue again or still. Is it a difficult technical issue or just low priority?

**Comment by ds8k** [comment]
Checked old Windows builds and found this broke between Canary 4 and Canary 6. Comparison here:
https://github.com/citra-emu/citra-canary/compare/canary-4...canary-6

Might be #2884 that broke it?
