### ISSUE TITLE
Review my code (I want to port it to Citra)

### ISSUE THREAD

**Issue by vvanelslande** [citra-emu/citra#5199]
RPC rewrite: https://github.com/vvanelslande/vvctre/tree/master/src/core/rpc
NFC fix: https://github.com/vvanelslande/vvctre/commit/9bdc82687d0c925a3c16bf89b347c3cbc04a2064
My camera implementation: https://github.com/vvanelslande/vvctre/tree/master/src/vvctre/camera

**Comment by B3n30** [comment]
To get your changes reviewed, please follow the same steps as every other dev: Open a PR for it.

Im closing this though, since it is not an issue

**Comment by vvanelslande** [comment]
no
