### ISSUE TITLE
Folder Ordering Bug

### ISSUE THREAD

**Issue by vitor-k** [citra-emu/citra#5218]
When you have multiple game folders (at least 3), multiple sequential reorders will cause the folder order not to be registered properly.
Eg: if you have 4 folders in the order ABCD, when moving up D twice you'd expect the order to be ADBC, which is what's shown right after reordering. However, when you close and open Citra again, the order will have changed to ACDB.
I do plan to work on this bug when I have the time, but I'm registering here so that it's not forgotten.
It also doesn't look like a hard bug to tackle, so if someone wants to work on this one as their first issue just say the word.

**Comment by KPSH7AmcSRcfCqdJ** [comment]
Here the same
