### ISSUE TITLE
[Feature Request] Secondary controller

### ISSUE THREAD

**Issue by QuintusNX** [citra-emu/citra#5254]
That can be usefull to allow users to use two controllers at the same time and switch between them.
For example, a joystick and a keyboard.

Some emulators have this function and I personnaly use it everyday.
Hope you will implement this feature in the future !

Thanks for your work, I love what you do.

**Comment by FearlessTobi** [comment]
Closing in favor of https://github.com/citra-emu/citra/issues/4795.
