### ISSUE TITLE
Savestates and game files need custom path files

### ISSUE THREAD

**Issue by FranzelDamasco909** [citra-emu/citra#5260]
My storage keeps fulling, i need to put the emulator files to the other path file it includes the external storage or SD Card but if there's no SD Card, it will be stay on the default path.

**Comment by FearlessTobi** [comment]
What platform are you on?

**Comment by vvanelslande** [comment]
@FearlessTobi Citra Android doesn't have savestates, it can only be PC.

**Comment by FranzelDamasco909** [comment]
Android, i'm not sure if there's an android platform. I Will remove this if there's no android version of Citra Emulator

**Comment by FearlessTobi** [comment]
We don't have an official Android build yet.

**Comment by Gamemulatorer** [comment]
This will be fix via https://github.com/citra-emu/citra/pull/6313
