### ISSUE TITLE
Ram usage on active textures are really high

### ISSUE THREAD

**Issue by Steamsweet** [citra-emu/citra#5269]
so its no issue but as game hacker and creator of custom textures it is a huge wall. So for 250MB of textures citra need 2900 GB of Ram this is really high.

**Comment by BreadFish64** [comment]
I assume that you don't really mean it used 2.9TB of RAM. 2.9GB would be reasonable, considering the textures are stored a compressed PNGs on disk, then decompressed into memory. If this is a problem, you can try turning off pre-loading. If you have any further problems with this, please contact us on Discord or the forums.

**Comment by Steamsweet** [comment]
i turn it off and it worked. Thanks
