### ISSUE TITLE
[3D Streets of Rage 2] New 3DS mode causes fatals 

### ISSUE THREAD

**Issue by legend800** [citra-emu/citra#5277]
SOR2 will hit a fatal randomly soon after starting if new 3ds mode is active. SOR1 doesn't have this problem.

![2020-04-26 16_29_16-Citra Canary 1695 _ 3D Streets of Rage 2](https://user-images.githubusercontent.com/20983844/80322708-a1c74480-87db-11ea-97ec-6af31e13e73c.png)

[citra_log.zip](https://github.com/citra-emu/citra/files/4536696/citra_log.zip)

Version:
1695

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4.5 ghz
16GB RAM

**Comment by Dragios** [comment]
You should create new issue only if it happens on Nightly builds. If it happens only on the Canary build, it should be reported under the respective affected PR.
In this case it should be reported under PR #5257
