### ISSUE TITLE
Compilation fails on teakra section

### ISSUE THREAD

**Issue by whp199** [citra-emu/citra#5286]
- You have provided the version (commit hash) of Citra you are using:
**64694b0f114e4709ccb3e9b62ff061518fe8cca9**
(latest as of today)
**- You have provided sufficient detail for the issue to be reproduced.**
removing older build files first, I did:
git pull origin master
git pull --recurse-submodules
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_FFMPEG_AUDIO_DECODER=ON
make -j8 

**Error occurs here:**
[ 16%] Built target SoundTouch
[ 16%] Building CXX object externals/teakra/src/CMakeFiles/teakra.dir/processor.cpp.o
In file included from /home/eric/bin/citra/externals/teakra/src/processor.cpp:1:
/home/eric/bin/citra/externals/teakra/src/interpreter.h:18:58: error: expected class-name before ‘{’ token
   18 | class UnimplementedException : public std::runtime_error {
      |                                                          ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [externals/teakra/src/CMakeFiles/teakra.dir/build.make:200: externals/teakra/src/CMakeFiles/teakra.dir/processor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1143: externals/teakra/src/CMakeFiles/teakra.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

**system details:**
Fedora 32 Linux, x86_64, Kernel 5.6.7, GCC 10.0.1

**Comment by Dragios** [comment]
Try this. It should fix your issue.
https://github.com/wwylele/teakra/commit/57bb1d241735702cec36a3a9f4a85e5f1a541db6

**Comment by whp199** [comment]
that worked, thanks!
not sure why git pull --recurse-submodules wouldn't have brought me your commit tho...

**Comment by wwylele** [comment]
Reopen this as citra needs to update to the last teakra commit.

**Comment by Dragios** [comment]
> 
> 
> that worked, thanks!
> not sure why git pull --recurse-submodules wouldn't have brought me your commit tho...

@whp199 That is because Citra is checkout to a certain submodule project commit. You need to update remote submodule in order to get the latest commit for teakra.
