### ISSUE TITLE
CMake Windows: Generate Issue

### ISSUE THREAD

**Issue by vitorsilverio** [citra-emu/citra#530]
Hello there,

When I click on generate i get this output:

Cache compiler flags ignored, please edit CMakeFiles.txt to change the flags.
libpng not found. Some debugging features have been disabled.
Could NOT find Boost
Boost 1.57.0 or newer not found, falling back to externals
Configuring done
CMake Error at externals/inih/CMakeLists.txt:11 (add_library):
  Cannot find source file:

    inih/ini.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: inih
Generating done

**Comment by yuriks** [comment]
You didn't initialize submodules: `git submodule init --update`

**Comment by vitorsilverio** [comment]
Thanks, it works when execute "git clone --recursive" too.
