### ISSUE TITLE
Citra Nightly 1535 is freezing and not responding when i want to save game (Pokémon X)

### ISSUE THREAD

**Issue by sadrak10** [citra-emu/citra#5326]
Why my Citra Nightly 1535 is freezing when i want to save game (Pokémon X)
![1](https://user-images.githubusercontent.com/64742854/80918952-167d1e80-8d9a-11ea-83d2-773e5ef832c4.jpg)
I click "Yes", and then it becomes like that. The button of "Yes" and "No" are disappear and there's no "Saving Game Data..." texts.

When i try to close normally the Citra Emulator, it's become "Not Responding"
![2](https://user-images.githubusercontent.com/64742854/80919015-488e8080-8d9a-11ea-919e-67de8e5ab913.jpg).
Now i have to force close the Citra Emulator using "end task" from Task Manager, and i only able to save the game using Save States. But the game is need to be saved "in game" when it comes to the end of the game's story.

My Laptop Specs :
ASUS A442U
Intel Core i5 8th Gen
Nvidia Geforce 930mx
8GB RAM
1TB HDD

Please fix this fast because it's really annoying. 

Edit : This happen after using cheat ("Items and Balls you own ×255" and "Med Pack items you own ×255") but when i use cheat "100% Catchrate" it works fine and i can save game normally.

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for developers, not a support forum. This appears to be caused by an incompatible cheat code, not Citra.
