### ISSUE TITLE
Dai Gyakuten Sabian 1 and 2 crash when using the new citra canary build

### ISSUE THREAD

**Issue by HalfEnder776** [citra-emu/citra#5334]
Im currently using Citra canary 735 HEAD-21bfc5d (2020-05-04)
i updated citra a few days ago and that version was able to run DGS fine but the new version which i just updated to today crashes the game at the title screen (only the logos appear)
I just want to say that I'm also using the DGS 1 and 2 english patch alongside them if that matters.
I'm currently using my outdated nightly build and the game works fine on it.

Not sure if my specs matter but ive got a i7 8700 and an rtx 2070
please fix this if you can

**Comment by vvanelslande** [comment]
735 is a typo

**Comment by zhaowenlan1779** [comment]
This should be fixed in the latest Canary. Also, for Canary bugs, please report directly to the related PR in the future.
