### ISSUE TITLE
Feature wich dump all Textures without play

### ISSUE THREAD

**Issue by Steamsweet** [citra-emu/citra#5337]
the dump textures just work if i play the intire game. A feature wich can dump all in once would be nice. The Dump RomFS function work but the file Names are not right. So its useless
![99](https://user-images.githubusercontent.com/53945997/81060417-b211aa80-8ed2-11ea-9be6-88d5283d875c.png)
The main problem for texture modding is that u need to play the intire game fully to get all textures

**Comment by wwylele** [comment]
This is out of citra's scope. If a tool dumps game data statically without running it, it is not an emulator. Citra is an emulator.
