### ISSUE TITLE
Why no filesystem changing like on yuzu?

### ISSUE THREAD

**Issue by DankBong420** [citra-emu/citra#5346]
like seriously, not everyone has a huge ass C drive. Most users secondary drive are bigger than their primary drive. And with Citra being the same GUI and shit as yuzu, it should take two seconds to add a file system tab inside Citra like you did with yuzu. 

And then a user in your Discord says it's currently in development? Citra's been out a lot longer than yuzu, even though they're made in the same language. 

I want my shit installed on my secondary drive.

**Comment by B3n30** [comment]
serously, I just explained to you that this is currently in development. See #5076

Also this is a duplicate issue. 

And this isn't a support forum but an issue tracker for development. 

Thus closed

**Comment by DankBong420** [comment]
Lol asshat
