### ISSUE TITLE
cirta nightly 1547 Enhanced features are not available in Chinese

### ISSUE THREAD

**Issue by Arlbenstock** [citra-emu/citra#5349]
1547 Enhanced features are not available in Chinese，The figure below shows the actual situation：
![image](https://user-images.githubusercontent.com/52063477/81937561-5c51a680-9626-11ea-8c3b-f5c26c41f455.png)

**Comment by FearlessTobi** [comment]
Please translate the tab on https://www.transifex.com/citra/citra/ if you want to have it in Chinese.
