### ISSUE TITLE
(Citra Canary 1755) Missing Text in Chibi-Robo Photo Finder

### ISSUE THREAD

**Issue by ruby234** [citra-emu/citra#5353]
[I'm using Citra Canary 1755. After reaching the title screen for Chibi Robo, immediately I notice that the typical "Hit A to start text" at the bottom screen is missing. I hit A, and it opens a blank text box at the top of the screen. I cannot close this textbox, meaning the game is softlocked, if that's the word to use. Adjusting Hardware Renderer and Accurate Multiplication do nothing. This is a link to show how it should normally work. [https://youtu.be/oAZylfKHENA](url)
![Screenshot_35](https://user-images.githubusercontent.com/65736400/82604044-a59f7a00-9b81-11ea-91ef-6fb17c054024.png)
![Screenshot_36](https://user-images.githubusercontent.com/65736400/82604049-a801d400-9b81-11ea-9e7f-db3ee64e3e80.png)

]

**Comment by SleepingSnakezzz** [comment]
@ruby234 Please retest on the latest Citra Nightly build.

**Comment by benderscruffy** [comment]
has been fixed 
can be closed
![Screenshot 2023-09-05 153441](https://github.com/citra-emu/citra/assets/2696404/d78ece4d-e649-4930-96bb-ff668d1359be)
