### ISSUE TITLE
GLES renderer for linux arm

### ISSUE THREAD

**Issue by Askmewho** [citra-emu/citra#5357]
HI, you had make really good progress on citra on android with gles.
you will add that render on linux to?

sorry about the channel used.

**Comment by FearlessTobi** [comment]
You can already find the GLES backend in the [citra-android](https://github.com/citra-emu/citra-android) repo.
Please use Discord for such questions in the future.

**Comment by Askmewho** [comment]
@FearlessTobi I tried to compile it but it keeps asking for 3.3 and fail. where is the android definition? ive hit discord and they mention that but it{s not clear at all

the are no documentation whatsoever about build it for android.
and even them , I wont use it on android! I want just the gles render
why there i no env var for that??

thanks.
