### ISSUE TITLE
[Software Keyboard Issue] Heroes of Ruin - Missing Button 

### ISSUE THREAD

**Issue by Schplee** [citra-emu/citra#5359]
This issue exists in the latest Citra Nightly (1549) and has existed since the Software Keyboard PR was merged (#3850 in Nightly-802).

Trying to name your character in Heroes of Ruin initializes the Software Keyboard, but the "OK" button doesn't appear. Citra Desktop allows you to click the "blank" button that should say "OK" to progress, but this prevents users from creating new save files on Citra Android.

Log file from Citra Nightly 1549: 
[citra_log.txt](https://github.com/citra-emu/citra/files/4672825/citra_log.txt)

Citra Nightly 1549: ![image](https://user-images.githubusercontent.com/24275329/82743908-91e14880-9d26-11ea-8601-ff8e22a56ae4.png)

Citra Android: 
![image](https://user-images.githubusercontent.com/24275329/82743913-a45b8200-9d26-11ea-9cdd-ffe6f6eae6b6.png)

**Comment by SutandoTsukai181** [comment]
This is the function that sets the text for that button on each frontend:
[Citra Qt](https://github.com/citra-emu/citra/blob/master/src/citra_qt/applets/swkbd.cpp#L51)
[Citra Android](https://github.com/citra-emu/citra-android/blob/cc08c6ae69caa20b38ff7e87b9b068c9034726d5/src/android/app/src/main/java/org/citra/citra_emu/applets/SoftwareKeyboard.java#L147)

**Comment by SutandoTsukai181** [comment]
Can someone provide an example of another game/app that uses software keyboard? This game provides 3 text options and 2 buttons only. The first text is "Cancel", second is an empty string, third is "Ok". This makes the buttons get initialized with the first 2 text strings only, resulting in the blank button.
