### ISSUE TITLE
(Android beta 2 6527551) Unable to activate touchscreen while virtual gamepad button

### ISSUE THREAD

**Issue by conductionblock** [citra-emu/citra#5360]
On Picross 3D Round 2, you have to hold down different buttons and touch things on the touchscreen to perform different actions (eg. hold X and touch a block to remove it, hold Y and touch block to paint blue).

This works fine on Windows but doesn't immediately work on Android when using the virtual gamepad. When I press and hold a button on the virtual gamepad, the touchscreen doesn't register any presses. This occurs with any button on the virtual gamepad, regardless of whether it is overlying the screen or off screen in empty space. Swapping screens or changing layouts doesn't make a difference either.

A workaround is to press and hold on the touchscreen, then press and hold the gamepad button, then release the touchscreen while still holding down on the gamepad. Any subsequent touches on the touchscreen then register properly.

I'm on beta 2 of the official Android build, though also had this issue on the initial beta release.

**Comment by FearlessTobi** [comment]
It would be nice if you could move this issue here: https://github.com/citra-emu/citra-android/issues/new.

**Comment by conductionblock** [comment]
Apologies, will do.
