### ISSUE TITLE
[android] captain toad crashes with hardware render

### ISSUE THREAD

**Issue by neversphere** [citra-emu/citra#5363]
- Version (commit hash) of Citra:

* Initial Beta release (May 22)
* Android Build 3: QQ3A.200605.001
* Pixel 3

- Steps to reproduce:

0) Enable hardware rendering (on by default)
1) Load captain toad
2) Crashes right after the initial screen (before the close up of toad)

Additional info
* I can't find the log file on Android or backtrace
* Changing other debug options doesn't help (disable JIT/hardware shading)

**Comment by FearlessTobi** [comment]
Please move this here: citra-emu/citra-android/issues/new.
