### ISSUE TITLE
Lego City Undercover crashes after load screen

### ISSUE THREAD

**Issue by Nintynuts** [citra-emu/citra#5367]
- The version (commit hash) of Citra: not sure. The version released on android play store on 23rd May 2020
- Detail for the issue to be reproduced: Run the game, it crashes after the intro video (which also runs very slowly) or when loading a save.
- System specs: Android 10 running on LG V50

I'm not sure where there is a crash log file on android.

**Comment by FearlessTobi** [comment]
Please move this here: https://github.com/citra-emu/citra-android/issues/new.
