### ISSUE TITLE
Intel HD video driver & Citra.

### ISSUE THREAD

**Issue by jvhellraiser** [citra-emu/citra#5369]
my Intel video drivers are making Citra crash every time i try to load a game.
this wont happen in any other emulator only on Citra Emulator. it freezes & to close 
Citra you will have to use task manager

Provider Intel Corporation
Driver Date 4/4/2016
Driver Version 10.18.10.4425

**Comment by tywald** [comment]
This is more suited to ask on the forums: https://community.citra-emu.org/

Also 4425 is outdated, there are:
5126, 5129 and 8190 as the latest depending on the GPU.

**Comment by jvhellraiser** [comment]
mines is  an older GPU the best it can do is that version of the driver if i rollback to the older driver then citra wont crash aint that funny? meaning the problem is on citra & Intel drivers compatibility. ok but i'll check on the forums.
