### ISSUE TITLE
Why is Citra so abnormally big?

### ISSUE THREAD

**Issue by JhonLoveJoy** [citra-emu/citra#5374]
Just out of curiosity why the emulator came to remarkable 256MB of files ? this is quite large compared to other emulators that are between 10mb ~ 40mb. Not that that's a big problem, but is it really necessary? :P

**Comment by BreadFish64** [comment]
Closing as this is question, not an issue, but the reason is probably because we have several dependencies, use lots of C++ templates, don't use LTO, etc. It's hard to tell what you mean unless we know what emulator you're comparing it to.
