### ISSUE TITLE
libav version 58 has installed but need version 57

### ISSUE THREAD

**Issue by yogithesymbian** [citra-emu/citra#5378]
so much file to install libav , when i install need other depend , when install the depend need against a file other for can install , 
should update 57 to 58 please .

![Screenshot from 2020-05-30 11-54-18](https://user-images.githubusercontent.com/28316296/83318987-acf31180-a26c-11ea-8116-57886eb8f845.png)

i just trying manual install on my debian , and now i updating OS for install with flatpak ( but wasting time ) downloading 6% and maybe someone can measure me about its would working on install with flatpak ? or error dependec need version 57 will come or nah ?

sorry bad grammer

thanks in advance

**Comment by zhaowenlan1779** [comment]
We only officially support Flatpak builds, and no, Flatpak won't have the issue
