### ISSUE TITLE
Inazuma Eleven 3 Lag Audio and FPS

### ISSUE THREAD

**Issue by InazumaElevenCitra** [citra-emu/citra#5384]
Hello,
Here is my problem, I always wanted to play Inazuma Eleven 3 in French and in good quality,
I have been looking for a solution not to bug Citra for over 1 month, but that does not change anything.
This problem does not happen only to me, I see this problem everywhere, the game would not be optimized on Citra. Knowing that I own an RTX 2080, I shouldn't have any worries.
![wwwwwwwwwwww](https://user-images.githubusercontent.com/66334765/83569177-5fa0c980-a524-11ea-8012-b7cd10eb6a88.PNG)

**Comment by FearlessTobi** [comment]
This issue is missing your full specs, a log, etc.

**Comment by InazumaElevenCitra** [comment]
There is no need for that, the developer just needs to fix the game concerns.

**Comment by FearlessTobi** [comment]
If you're unwilling to provide this info I'm gonna close this now and direct you to our Discord. 
It's well possible that your PC is not strong enough.
