### ISSUE TITLE
Multiplayer using Hostname instead of IP

### ISSUE THREAD

**Issue by SVNKoch** [citra-emu/citra#5385]
I'm on Nightly 1554.
It currently is not posible to connect to a multiplayer room using an Hostname. The input field allows only numbers and dots to be entered.

Can this please be added / allowed?

**Comment by xperia64** [comment]
There is no purpose to a URL here. A slash would not accomplish anything. That is not how servers work.

Hostnames on the other hand, as noted in this TODO, would serve a purpose: https://github.com/citra-emu/citra/blob/master/src/citra_qt/multiplayer/validation.h#L41

**Comment by SVNKoch** [comment]
apparently I was not usig the correct terminology. Thanks for clarifing. I updated my request accordingly.
My problem is that I want to play with friends however due to my situation I'm behind a firewall and use ssh forwarding services which only give hostnames instead of IPs to connect to.

**Comment by xperia64** [comment]
If you get the IP from the hostname, does it work?

Because if it doesn't, implementing this in Citra is no different than just automating the step of getting the IP from the hostname, so it wouldn't work if built in to Citra either.

**Comment by SVNKoch** [comment]
actually I've tried getting the IP from Webservices and the windows cmd ping command. The given IP did not work.
However I've also created a Minecraft server and used the service to forward the port. Minecraft allows hostnames as address and it did indeed work. No idea though where and what magic is happening there.

**Comment by xperia64** [comment]
Well, Minecraft is supposedly TCP while Citra is UDP, so if their service is incorrectly configured or doesn't support UDP, it wouldn't work.

This discussion should not be here as it no longer directly related to the issue and GitHub issues are not for support.

The issue itself can stand as it is a valid feature request/TODO

**Comment by FearlessTobi** [comment]
Fixed by https://github.com/citra-emu/citra/pull/6319.
