### ISSUE TITLE
Add option to uninstall a Cia game already installed

### ISSUE THREAD

**Issue by HJMBgit84** [citra-emu/citra#5386]
Please add an option to uninstall a Cia installed game, I requested this feature in Android version and the pull request was closed suggesting to request it here because there is no previous request for a feature like that, appreciate your hard work guys adding the feature as soon as you can, thanks :) it is easier to uninstall it than go to folder directory and try to guess what is the game title.

**Comment by dogtopus** [comment]
I second this. The code for uninstallation should be there already since uninstalling via FBI works.

**Comment by ElHave247** [comment]
And add a tab to show what dlc and update is installed of the game
