### ISSUE TITLE
Loading Savestate corrupts the playback of the input recording

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#5387]
Since there is now the possibility to save and load savestates, it would be very helpful for TAS creators if the input recording would work properly with the function to save and load savestates. The input playback does not output the input correctly from the moment you loaded a savestate when you was recording the inputs. After that, the result is no longer synchronized with the playback.

To implement this one function would be the first important step for TAS support and would open up many opportunities for TAS and speedrun communities. If that were changed, it would also make sense to implement certain TAS input tools for optimal TAS support, but that would be too much to ask for now.

This reddit post is also about this
https://www.reddit.com/r/Citra/comments/gui0i3/help_input_recording_and_playback_is_not_working/

**Comment by InfamousKnight** [comment]
Yeah, this definitely needs to be fixed.

**Comment by InfamousKnight** [comment]
Is this pull request related to this?
