### ISSUE TITLE
Emulating lagging and Keeping Crash

### ISSUE THREAD

**Issue by Amamiya-Tokie** [citra-emu/citra#5388]
Since Citra was release for android, fire emblem if is not smooth when it emulating a specially in the battle phase, from 2D graphic to 3D transitions was so lagging.

and then after Beta 8 ( Version 8aa76e7d7 )was been updated it just make emulator keeping crash when we press the bottom in the titles "press any keys to start".

My phone is Sony XZP and I still left the 4GB for emulator to work it.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
Thanks
