### ISSUE TITLE
Portrait mode screens

### ISSUE THREAD

**Issue by RhayneLyte** [citra-emu/citra#5390]
Im using the latest Version of the citra official app released 2 days ago. 
Oneplus 7 pro SD855 8GB ram

In portrait mode the bottom screen is much bigger than the top screen. 
I've tried swapping the screens and it doesn't change the size.
Changing my screen resolution didn't do anything either. 
It would be nice if screens were the same size and we could adjust the position some while in portrait mode. 
Thanks for all your hard work! ^_^

![Screenshot_20200604-104819](https://user-images.githubusercontent.com/66432876/83781555-50b93480-a654-11ea-915e-2c0f4dee12c6.jpg)

**Comment by RhayneLyte** [comment]
With screens swapped. 

![Screenshot_20200604-111436](https://user-images.githubusercontent.com/66432876/83781803-9fff6500-a654-11ea-9bff-b20c7362040f.jpg)

**Comment by vitor-k** [comment]
Hello.
The top and bottom screens of the 3ds have different aspect ratios, so it's either that or having black bars like the PC default layout.
For android specific issues please go to <https://github.com/citra-emu/citra-android/issues> instead.

**Comment by RhayneLyte** [comment]
Haha will do. I honestly thought i was in the android section. Lmao.

**Comment by njdom24** [comment]
I think this issue should be reopened, as some games rely on accurate screen sizes / a gap to display properly. Can technically be accomplished with a custom layout, but it breaks landscape display on Android.
