### ISSUE TITLE
Bug gráfico con Mudkip en Pokémon zafiro alfa en android

### ISSUE THREAD

**Issue by StoneySpring688** [citra-emu/citra#5391]
Estaba jugando Pokémon zafiro alfa y al ver al Pokémon inicial Mudkip me di cuenta de que se veía casi de color blanco.
De momento este es el único bug que he encontrado en Pokémon zafiro alfa con el emulador en android.
Espero que alguien sepa cómo arreglarlo.
Gracias por vuestra tiempo.

I was playing Pokémon Alpha Sapphire and when I saw the initial Pokémon Mudkip I realized that it looked almost white.
At the moment this is the only bug that I have found in Pokémon alpha sapphire with the emulator on android.
I hope someone knows how to fix it.
Thanks for your time.

**Comment by StoneySpring688** [comment]
El emulador es: citra y lo juego en android

**Comment by BreadFish64** [comment]
Duplicate of https://github.com/citra-emu/citra-android/issues/97
