### ISSUE TITLE
After setting a custom layout -> can’t click the second screen anymore

### ISSUE THREAD

**Issue by Defcon0** [citra-emu/citra#5406]
Hello,

I just set the custom layout configuration for my 4k monitor:

```
custom_layout\default=false
custom_layout=true
custom_top_left\default=true
custom_top_left=0
custom_top_top\default=true
custom_top_top=0
custom_top_right\default=false
custom_top_right=2400
custom_top_bottom\default=false
custom_top_bottom=1440
custom_bottom_left\default=false
custom_bottom_left=2400
custom_bottom_top\default=false
custom_bottom_top=1200
custom_bottom_right\default=false
custom_bottom_right=960
custom_bottom_bottom\default=false
custom_bottom_bottom=240
```

It works but if I set that, I can’t click the second screen anymore 😦 

Seems to be a bug.

Bye Defcon0

**Comment by tywald** [comment]
You have put the dimensions in reverse for the bottom screen. Though this question is more suited on the forums: https://community.citra-emu.org/

**Comment by Defcon0** [comment]
Not working. I tried:

```
custom_top_top=0
custom_top_right\default=false
custom_top_right=2400
custom_top_bottom\default=false
custom_top_bottom=1440
custom_bottom_left\default=false
custom_bottom_left=2400
custom_bottom_top\default=false
custom_bottom_top=1200
custom_bottom_right\default=false
custom_bottom_right=240
custom_bottom_bottom\default=false
custom_bottom_bottom=960
```

This way the bottom screen is messed up.

The layout looks totally ok. Only the clickable area seems to be moved around wrong.

I already posted in the forms with zero success. Hence I thought it might be a bug because the settings seem to be correct. Otherwise it wouldn't be displayed ok, would it (see attachment)?

![IMG_6818](https://user-images.githubusercontent.com/1485098/84367138-1875a100-abd4-11ea-86f7-c873a71d6989.jpg)

**Comment by tywald** [comment]
I have replied to your forum post: https://community.citra-emu.org/t/after-setting-a-custom-layout-can-t-click-the-second-screen-anymore/248933/5

**Comment by FearlessTobi** [comment]
@tywald Should we close this then?

**Comment by tywald** [comment]
Yes
