### ISSUE TITLE
Life bar is not displayed in Puzzle and Dragons Z Plus Puzzle and Dragons Super Mario Bros Edition

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#5408]
The enemies ife bar is not displayed in Puzzle and Dragons Z Plus Puzzle and Dragons Super Mario Bros Edition. 

Version of Citra: Citra Canary 1773

Ryzen 5 3600
Nvidia GT 1060 6GB

**Comment by FearlessTobi** [comment]
This issue is missing a log file (again)

**Comment by Amnesia1000** [comment]
Log File
[citra_log.zip](https://github.com/citra-emu/citra/files/4773724/citra_log.zip)

**Comment by Fijiboy99** [comment]
I'm having the same issue

**Comment by Fijiboy99** [comment]
Let me know if you find a fix for it, the game's pretty heavily damaged by this issue.

**Comment by Schplee** [comment]
Duplicate of #5139
