### ISSUE TITLE
Rhythm Heaven Megamix - Massive audio crackling

### ISSUE THREAD

**Issue by oddMLan** [citra-emu/citra#5409]
Citra https://github.com/citra-emu/citra/commit/16913feb4441ffba1a57347953a8a6aa0103e5c5
Windows 10 x64 build 1809

Backends affected: Cubeb, SDL2 (both HLE).

Steps to reproduce
**1. Make sure to disable timestretching**
2. Just play any minigame normally, the crackling is inmediately noticeable
Here's an example:
[crackle.zip](https://github.com/citra-emu/citra/files/4773319/crackle.zip)

This does not happen while using the "Dump video" feature

**Comment by xperia64** [comment]
For what it's worth, I cannot reproduce this issue myself on Linux or Windows 10 1909.

I am not sure what change I made that would cause crackling in only the frontend and not a recorded video, so please try older versions here to figure out which specific change broke: https://github.com/citra-emu/citra-nightly/releases

**Comment by oddMLan** [comment]
\*facepalm\*
I looked at the status bar and it said speed 105%.  I think I sped the game up on accident. Pressing - on the numpad to get it down to 100% fixed it.
