### ISSUE TITLE
Problem dragging window in Linux KDE

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#5413]
By clicking and holding on the touch screen, instead of making the corresponding movement, the window is dragged.
Only when a game is being played, by performing the same action in the game list window, the window remains intact.

I am using Linux Manjaro KDE.

Demonstration video: https://youtu.be/ABpEUeupjTU

**Comment by liushuyu** [comment]
Hi there, it looks like a configuration issue with your KDE settings (maybe set by your distribution). I tested on my Arch Linux KDE system and can not reproduce the issue.

**Comment by Amnesia1000** [comment]
It's not, it's also happening at Dolphin-emu. But not in melonDS. Right now I'm using gnome and the same thing happens.
