### ISSUE TITLE
[Feature Request] Touchscreen Buttons 

### ISSUE THREAD

**Issue by Papermanzero** [citra-emu/citra#5414]
Some 3DS games offer only a button on the touchscreen. It would be a quality-of-life feature to define buttons based on touchscreen coordinates which can be mapped to physical buttons on a controller. Every time the physical button is pressed it simulates a tap on the touchscreen on the defined coordinates.

Nox android emulator has equal features which can be used as reference.

**Comment by tywald** [comment]
You already can, #5163 is merged.

**Comment by Papermanzero** [comment]
Oh wow. Thanks
Completely oversaw that merge.😂
