### ISSUE TITLE
how does one fix no text ever appearing at the bottom

### ISSUE THREAD

**Issue by Darkness323** [citra-emu/citra#5416]
hello i decide to try out this emulator to play a game and no text at all was at and on the bottom screen.
![Capture](https://user-images.githubusercontent.com/64926324/85082201-1b6d2480-b1c6-11ea-9d99-4d43359f872f.PNG)

**Comment by wwylele** [comment]
This is issue tracker for development, not for answering user questions. For support please use our forum or Discord server. If this is intended to be a legit bug report, please include everything required in the issue template.

**Comment by FearlessTobi** [comment]
Closing until further info is provided.
