### ISSUE TITLE
SSB 3DS European dont start

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#5421]
Super Smash Bros does not start, the emulator tells me speed 100/100 and FPS 0. 

I dump the game again and it still doesn't start. I changed the region, video and audio settings and it still didn't work.

To test I download a USA and a European version of the game and the American one worked but the European one did not (my dump is also European). It seems that it is the European version that is incompatible with Citra.

More information: Try without the updates and DLCs and still do not start.

The log gives me this error repeatedly: "[24.900894] Service.FS <Error> core/hle/service/fs/file.cpp:Read:76: Reading from out of bounds offset=0x732a99e8 length=0x00000018 file_size=0x85000"
[citra_log.zip](https://github.com/citra-emu/citra/files/4810921/citra_log.zip)

I am using the latest canary on Linux (1787). 
In case it is relevant I have a i7 7700 and a Nvidia 1060.
All the other games work well for me.

**Comment by wwylele** [comment]
> To test I download a USA and a European version of the game ...

Sorry, no support for piracy.

**Comment by Amnesia1000** [comment]
It is not piracy, as I explained the dump is mine, I ownload other versions from the internet just for testing. The files have already been deleted, without that confirmation I would not know if it was a problem with my dump or a general problem.
