### ISSUE TITLE
Paper Mario: Sticker Star has buggy graphics since Nightly 1464

### ISSUE THREAD

**Issue by LexLight** [citra-emu/citra#5423]
I was trying one day to play "Paper Mario: Sticker Star" on the lastest version of Citra, however, I was very surprised when I've seen that the "white touch screen bug" was back, so I tried to bisect the bug, and I've seen that the lastest version that worked fine with the game is Nightly 1463.
Here's the title screen on Nightly 1463:
![vlcsnap-2020-06-22-18h11m26s909](https://user-images.githubusercontent.com/25409295/85310113-e86fad00-b4b3-11ea-87e7-a384b47b1a04.png)

And here's it on 1464 (when the problem began):
![vlcsnap-2020-06-22-18h12m05s086](https://user-images.githubusercontent.com/25409295/85310146-f1f91500-b4b3-11ea-87b3-c1da872f9117.png)

But that's not all, because it affects the Sticker Album, too.
Here's it on Nightly 1463:
![vlcsnap-2020-06-22-18h14m14s406](https://user-images.githubusercontent.com/25409295/85310476-53b97f00-b4b4-11ea-9382-48f699f34cf1.png)

And here's it on Nightly 1464:
![vlcsnap-2020-06-22-18h14m35s436](https://user-images.githubusercontent.com/25409295/85310496-5ae08d00-b4b4-11ea-9019-357896d1acd5.png)

Plus, the transition of when you move between the pages of the Sticker Album is affected, too.
Here's it working correctly on Nightly 1463: 
![Paper-Mario-Sticker-Star-Citra-1463](https://user-images.githubusercontent.com/25409295/85312064-9c723780-b4b6-11ea-9ca6-ee8668a80ef5.gif)

And here's the corrupted transition on 1464:
![Paper-Mario-Sticker-Star-Citra-1464](https://user-images.githubusercontent.com/25409295/85312123-ae53da80-b4b6-11ea-9046-2755f6a9c9e4.gif)

I'm showing that issue because it's still on both the lastest Nightly and Canary, and I suspect that it's because of the "D24S8->RGBA8 res_scale Hack" that was readded on the Nightly 1464.

Just in case, here's my log (which I've modified to erase my real name from it, but should still be useful): 
[citra_log.txt](https://github.com/citra-emu/citra/files/4814451/citra_log.txt)

And my specs (the most important ones):
CPU: Ryzen 3700X
GPU: nVidia GeForce RTX 2070 Super
RAM: 16 GB of DDR4 RAM at 3200 MHz

Thanks a lot in advance, and I'm sorry if I've commited any error, this is my first time doing an issue report for this emulator.

EDIT: I've forgot a detail, everything, except the transition, gets fixed when you change anything from the Graphics section in the Options.

**Comment by wwylele** [comment]
Nightly 1464 corresponds to #5170

**Comment by LexLight** [comment]
> 
> 
> Nightly 1464 corresponds to #5170

Thanks for telling me, I've added another detail to the issue.

**Comment by Amnesia1000** [comment]
In the last 3 Canary versions (I don't know before these 3) the album transitions are broken, showing strange colors, but unlike this bug the white album is not shown.

Citra Canary 1812-1814
Linux Manjaro
Ryzen 5 3600
Gforce GTX 1060

**Comment by SleepingSnakezzz** [comment]
@LexLight @Amnesia1000 Please retest using the latest Citra Nightly build.

**Comment by LexLight** [comment]
> @LexLight @Amnesia1000 Please retest using the latest Citra Nightly build.

Retested, and now, it seems to work fine!
Thanks a lot!

**Comment by benderscruffy** [comment]
can be closed
this has been fixed now

**Comment by LexLight** [comment]
> can be closed this has been fixed now

Of course, I haven't seen those graphic glitches as of the recent Nightly.
