### ISSUE TITLE
Input lag while playing Pokemon X/Y

### ISSUE THREAD

**Issue by Nishant765** [citra-emu/citra#5426]
When playing X/Y the key input does not register correctly. Only after the key is pressed multiple times the input registers.
Please fix this issue.
Device Specs:
Windows 10 Pro
4GB RAM 
Intel(R) Core(TM) i5-4300U CPU 2.5GHz

Log file:
[citra_log.txt](https://github.com/citra-emu/citra/files/4824073/citra_log.txt)

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for development, not a support forum. Please ask for support on our Discord server or Forum.
