### ISSUE TITLE
Graphical Issue with Fire Emblem Awakening's Unit Movement

### ISSUE THREAD

**Issue by AlMasque** [citra-emu/citra#5427]
Specs: I7-7700HQ | GTX 1050ti
Citra Version: Citra Canary 1791
Note: Issue also persists in Citra Nightly 1580
What Citra Currently Looks Like:
![Capture](https://user-images.githubusercontent.com/64135421/85647678-96a46e00-b6d1-11ea-8671-56404a17b6d3.PNG)

What Fire Emblem Should Look Like:
![fire-emblem-awakening-3ds-800x600-1](https://user-images.githubusercontent.com/64135421/85647528-3dd4d580-b6d1-11ea-82f9-56b413b14b2a.jpg)

This isn't an issue of using a texture pack as the issue persists when not using custom textures
Also: This issue only occurs in Awakening and not in other Fire Emblem Games (does not occur in FE Fates)

**Comment by benderscruffy** [comment]
Has this been fixed ???
Please update

**Comment by GPUCode** [comment]
Does this still occur?

**Comment by GPUCode** [comment]
Cannot reproduce this
