### ISSUE TITLE
Fire Emblem Echoes: Dashing pulls random textures from level over screen.

### ISSUE THREAD

**Issue by SilentHeII** [citra-emu/citra#5428]
Canary 1791
Specs: https://pcpartpicker.com/list/4qBFb8
Windows 10 latest update as of 6/24/2020
[citra_log.txt](https://github.com/citra-emu/citra/files/4828937/citra_log.txt)
![Citra](https://user-images.githubusercontent.com/29898818/85649657-4bef0b80-b669-11ea-9c44-6733b7a98f52.png)

Basically, when entering a dungeon, you can dash by holding B. Dashing on real hardware is supposed to generate a transparent after-image effect, however on the latest Canary and even the Nightly cause the game to pull random textures from the environment or the character model for the effect. Here's an example of what is actually supposed to happen on real hardware: https://youtu.be/Ylm4mFvSd14?t=194

**Comment by gallickgunner** [comment]
I'm having this issue as well on both the latest build of nightly and canary. Any updates?

**Comment by Dragios** [comment]
Try test if PR #6925 fix this issue or not

**Comment by ostrea** [comment]
Nightly 1984 - It doesn't pull random textures, but as far as I can tell transparent after-image effect is missing.

**Comment by FearlessTobi** [comment]
Okay, please open a new issue for the other problem then.
