### ISSUE TITLE
Can't Cross region play in recently Canary. (Monster Hunter 4U + MH4G)

### ISSUE THREAD

**Issue by ANTHENA-CITRA** [citra-emu/citra#5429]
**<Tested with Canary 1789.>
<Tested game : Monster Hunter 4U, Monster Hunter 4G. Online cross region play.>**

I have been playing Citra for the past two years.
Citra has presented me with many fun experiences.

> https://discord.gg/R3KsVp5 : 5,238 members. MHXX.
> https://discord.gg/qvE3RhM : 2,573 members. MH4U, 4G
> https://discord.gg/6arZq3P : 518 members. MH3U, 3G

I have Monster Hunter communities, that Discord for international.
We have many users with different nationalities.

It was can be cross region play in old citra, now it seems can't.
I tested in 1789. Also I tried changed region in Citra setting, got same result. Can't cross play.

I know it was some Citra bug, can't cross play in actual 3DS.
Actually, many users played Monster Hunter with Citra cross play.
Currently, we are still using the old Citra build to cross play the game.

**But Citra is emulator, if can cross play, more user can be make fun expiernce.
The advantage of emulator is that it can provide experiences that real device cannot.**

**Point : it worked before.**

My Discord account is **ANTHENA#0474** 
My English is not good, i'm from korea.
If can't understand my bad english, please message to me.

I'm rooting for the CITRA team.
Thank you for gave to me a great experience.

![ANTHENA](https://user-images.githubusercontent.com/55389306/85663791-789c3500-b6f4-11ea-818c-a6f6c0eaf673.png)

**Comment by fadillzzz** [comment]
I'm experience the same problem. If someone uses MH4G to host a hall, I can't see that hall because I'm on MH4U.

**Comment by ANTHENA-CITRA** [comment]
Tested 1795, Still can't cross play.

**Comment by ANTHENA-CITRA** [comment]
Tested 1797, Cross region play is worked again! Thanks! Thanks!!!
[https://imgur.com/RXwvnkj.png](url)
