### ISSUE TITLE
[Feature Request] to add dual windows

### ISSUE THREAD

**Issue by Eternal-plasma** [citra-emu/citra#5432]
I think it would be nice if we could have an option to split the one window with dual screens into 2 windows that could be moved around (yes I know you can change them to be side by side) :)

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/citra-emu/citra/issues/204.
Please use the issue search the next time when opening a new one.

**Comment by Eternal-plasma** [comment]
Oops didn't see that sorry
