### ISSUE TITLE
Citra - Framelimit

### ISSUE THREAD

**Issue by EduApps-CDG** [citra-emu/citra#5447]
While running some heavy games, i cant reach 60FPS. So, we actually have Speedlimitter which is pretty good but i cant find a Framelimitter.

My propourse is to run heavy games at 45/45FPS and light games at 60FPS

**Comment by wwylele** [comment]
Since 3DS has fixed guest fps of 60, speed limiter would be the same as framer limiter. You can set speed limiter to 75% for your purpose.

**Comment by wwylele** [comment]
Actually, do you mean limiting host frame rate without affecting game speed? It is kind of weird that your host frame rate wouldn't reach 60 fps because of the game, as the host rendering is a pretty light job. I'll leave this open for getting your answer.

**Comment by FearlessTobi** [comment]
The author is unresponsive - will close this for now and reopen if we get an answer.

**Comment by EduApps-CDG** [comment]
> Actually, do you mean limiting host frame rate without affecting game speed? 
Sorry for the late! Yes, i cant reach 60FPS in some games, i dont have a good CPU.
I want to reach 100% of speed with 45FPS, sorry for my bad english!
