### ISSUE TITLE
[Feature Request] shotkey to save  and load state

### ISSUE THREAD

**Issue by willowrosabelle** [citra-emu/citra#5450]
I would like a shortkey for save and load state on Citra, if it's possible, please! So you can save and load quickly, and don't need  to go through the menu on citra to save and load state

**Comment by KingGamingYT** [comment]
You opened this as an issue, not a feature request.

**Comment by FearlessTobi** [comment]
Citra already has Hotkeys for save states.

**Comment by PyrDeus** [comment]
We can configure the hotkeys via Preferences>Controls>Shortcuts.
But this way reset itself to each update of Citra.
