### ISSUE TITLE
Xenoblade Chronicles 3D attack bug

### ISSUE THREAD

**Issue by danielwj00** [citra-emu/citra#5451]
everything is fine and very good when playing, but after few minutes or sometimes almost immediately, when i'm trying to select target and then click attack button.. i can't. i can't even pick the skill after targeting monster. i don't know how to fix it... the game was very smooth to play around 60fps but because of that i can't play properly... i need to restart the emulator everytime that happens.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord or our forums for support requests.
