### ISSUE TITLE
Non-American compatibility

### ISSUE THREAD

**Issue by AJ11797** [citra-emu/citra#5458]
In the games list on all European/ Australian games it says not tested even when the American versions of the games have testing data.

![gamelist](https://user-images.githubusercontent.com/43966263/87849568-90c13780-c8e1-11ea-82fa-12ee4b94aaab.png)

Take the Zelda games for example which all have testing data.

**Comment by Steamsweet** [comment]
the issue appears between version 1319 and 1320

**Comment by Steamsweet** [comment]
![temp](https://user-images.githubusercontent.com/53945997/87850413-5e6b0680-c8f0-11ea-820e-0838d9dfd29c.png)

**Comment by Steamsweet** [comment]
![temp2](https://user-images.githubusercontent.com/53945997/87850501-041e7580-c8f1-11ea-8638-b79eb2da7beb.png)

**Comment by AJ11797** [comment]
The screenshot is from version 1594.

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/citra-emu/citra/issues/4880.
