### ISSUE TITLE
Audio device not recognized

### ISSUE THREAD

**Issue by Platypants** [citra-emu/citra#5461]
I am running Ubuntu Linux 18.04.4 with the latest stable Citra version (2020-7-14) and my audio device does not seem to be recognized. The only audio option I have on the configuration page is "auto". I have no sound output in my game (I have only tried Pokemon X) though it seems to be running fine otherwise. I have tried switching between different speakers and headphones with no effect. Other apps on my computer have normal audio.

Also, entering the configure menu while the game is loaded instantly crashes Citra, which may be a separate issue. 

My log is below. My only guess is that this may have to do with an improperly decrypted 3ds file? I'm not sure why the game would run at all in that case.

[   0.001411] Config <Info> core/settings.cpp:LogSettings:77: Citra Configuration:
[   0.001422] Config <Info> core/settings.cpp:LogSetting:73: Core_UseCpuJit: true
[   0.001423] Config <Info> core/settings.cpp:LogSetting:73: Renderer_UseGLES: false
[   0.001423] Config <Info> core/settings.cpp:LogSetting:73: Renderer_UseHwRenderer: true
[   0.001424] Config <Info> core/settings.cpp:LogSetting:73: Renderer_UseHwShader: true
[   0.001425] Config <Info> core/settings.cpp:LogSetting:73: Renderer_SeparableShader: false
[   0.001426] Config <Info> core/settings.cpp:LogSetting:73: Renderer_ShadersAccurateMul: false
[   0.001426] Config <Info> core/settings.cpp:LogSetting:73: Renderer_UseShaderJit: true
[   0.001427] Config <Info> core/settings.cpp:LogSetting:73: Renderer_UseResolutionFactor: 1
[   0.001428] Config <Info> core/settings.cpp:LogSetting:73: Renderer_FrameLimit: 100
[   0.001429] Config <Info> core/settings.cpp:LogSetting:73: Renderer_UseFrameLimitAlternate: false
[   0.001429] Config <Info> core/settings.cpp:LogSetting:73: Renderer_FrameLimitAlternate: 200
[   0.001430] Config <Info> core/settings.cpp:LogSetting:73: Renderer_PostProcessingShader: none (builtin)
[   0.001439] Config <Info> core/settings.cpp:LogSetting:73: Renderer_FilterMode: true
[   0.001439] Config <Info> core/settings.cpp:LogSetting:73: Renderer_TextureFilterName: none
[   0.001440] Config <Info> core/settings.cpp:LogSetting:73: Stereoscopy_Render3d: 0
[   0.001441] Config <Info> core/settings.cpp:LogSetting:73: Stereoscopy_Factor3d: 0
[   0.001441] Config <Info> core/settings.cpp:LogSetting:73: Layout_LayoutOption: 0
[   0.001442] Config <Info> core/settings.cpp:LogSetting:73: Layout_SwapScreen: false
[   0.001443] Config <Info> core/settings.cpp:LogSetting:73: Layout_UprightScreen: false
[   0.001443] Config <Info> core/settings.cpp:LogSetting:73: Utility_DumpTextures: false
[   0.001444] Config <Info> core/settings.cpp:LogSetting:73: Utility_CustomTextures: false
[   0.001445] Config <Info> core/settings.cpp:LogSetting:73: Utility_UseDiskShaderCache: true
[   0.001456] Config <Info> core/settings.cpp:LogSetting:73: Audio_EnableDspLle: false
[   0.001456] Config <Info> core/settings.cpp:LogSetting:73: Audio_EnableDspLleMultithread: false
[   0.001457] Config <Info> core/settings.cpp:LogSetting:73: Audio_OutputEngine: auto
[   0.001458] Config <Info> core/settings.cpp:LogSetting:73: Audio_EnableAudioStretching: true
[   0.001459] Config <Info> core/settings.cpp:LogSetting:73: Audio_OutputDevice: auto
[   0.001459] Config <Info> core/settings.cpp:LogSetting:73: Audio_InputDeviceType: 0
[   0.001460] Config <Info> core/settings.cpp:LogSetting:73: Audio_InputDevice: Default
[   0.001461] Config <Info> core/settings.cpp:LogSetting:73: Camera_OuterRightName: blank
[   0.001461] Config <Info> core/settings.cpp:LogSetting:73: Camera_OuterRightConfig: 
[   0.001462] Config <Info> core/settings.cpp:LogSetting:73: Camera_OuterRightFlip: 0
[   0.001463] Config <Info> core/settings.cpp:LogSetting:73: Camera_InnerName: blank
[   0.001464] Config <Info> core/settings.cpp:LogSetting:73: Camera_InnerConfig: 
[   0.001464] Config <Info> core/settings.cpp:LogSetting:73: Camera_InnerFlip: 0
[   0.001465] Config <Info> core/settings.cpp:LogSetting:73: Camera_OuterLeftName: blank
[   0.001467] Config <Info> core/settings.cpp:LogSetting:73: Camera_OuterLeftConfig: 
[   0.001468] Config <Info> core/settings.cpp:LogSetting:73: Camera_OuterLeftFlip: 0
[   0.001469] Config <Info> core/settings.cpp:LogSetting:73: DataStorage_UseVirtualSd: true
[   0.001469] Config <Info> core/settings.cpp:LogSetting:73: System_IsNew3ds: true
[   0.001470] Config <Info> core/settings.cpp:LogSetting:73: System_RegionValue: -1
[   0.001471] Config <Info> core/settings.cpp:LogSetting:73: Debugging_UseGdbstub: false
[   0.001471] Config <Info> core/settings.cpp:LogSetting:73: Debugging_GdbstubPort: 24689
[   0.302052] Input <Info> input_common/udp/client.cpp:StartCommunication:207: Starting communication with UDP input server on 127.0.0.1:26760
[   0.331072] Frontend <Info> citra_qt/main.cpp:GMainWindow:192: Citra Version:  | master-5192c511
[   0.331081] Frontend <Info> citra_qt/main.cpp:GMainWindow:194: Host CPU:         Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
[   0.331107] Frontend <Info> citra_qt/main.cpp:GMainWindow:196: Host OS: Ubuntu Core 18
[   0.337552] Frontend <Warning> citra_qt/game_list.cpp:LoadCompatibilityList:623: Game compatibility list is empty
[   0.337750] Frontend <Warning> citra_qt/main.cpp:CheckForUpdates:818: Unable to start check for updates
[   5.889052] Frontend <Info> citra_qt/main.cpp:BootGame:1008: Citra starting...
[   5.898013] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[   5.898021] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:343: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   6.008275] Audio.Sink <Critical> audio_core/cubeb_sink.cpp:CubebSink:76: Error initializing cubeb stream (-1)
[   6.008282] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:12: Starting RPC server ...
[   6.008328] RPC_Server <Info> core/rpc/rpc_server.cpp:HandleRequestsLoop:113: Request handler started.
[   6.008362] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:16: RPC started.
[   6.008983] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:827: ClCertA file missing
[   6.013312] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1194: GL_VERSION: 4.2 (Core Profile) Mesa 20.0.8
[   6.013316] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1195: GL_VENDOR: Intel Open Source Technology Center
[   6.013316] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1196: GL_RENDERER: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
[   6.020232] Loader <Info> core/loader/ncch.cpp:Load:192: Program ID: 0004000000055D00
[   6.020256] Service.FS <Warning> core/file_sys/ncch_container.cpp:OpenFile:130: Failed to open /home/allan/snap/citra-mts/177/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/00055d00/content/00000000.app
[   6.066220] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:141: ExHeader kernel version: 2.35
[   6.067626] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:SetPreferredRegionCodes:654: Preferred region code set to 1
[   6.081997] Render.OpenGL <Info> video_core/renderer_opengl/gl_shader_disk_cache.cpp:LoadTransferable:169: Found a transferable disk cache with 97 entries
[   6.129788] Render.OpenGL <Info> video_core/renderer_opengl/gl_shader_disk_cache.cpp:LoadPrecompiledFile:268: Found a precompiled disk cache with 97 decompiled entries and 97 binary entries
[   6.307770] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11
[   6.328461] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called
[   6.330715] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetLockHandle:313: (STUBBED) called applet_attributes=0X00000000
[   6.335106] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:187: (STUBBED) bit_mask=0x0000000F
[   6.336023] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:75: (STUBBED) bit_mask=0x00000006
[   6.337355] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:292: (STUBBED) app_id=768
[   6.340124] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:560: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
[   6.340466] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:560: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[   6.343986] Service.FS <Warning> core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:602: (STUBBED) called, version: 0x050200C8
[   6.344805] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[   6.347776] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[   6.355389] Service.SRV <Warning> core/hle/service/sm/srv.cpp:Subscribe:210: (STUBBED) called, notification_id=0x209
[   6.367932] Service.FS <Warning> core/file_sys/archive_ncch.cpp:OpenFile:151: Shared Font file missing. Loading open source replacement from memory
[   6.504742] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:704: called flag=00000000 process=11 thread_id=0
[   6.514588] Render.OpenGL <Error> video_core/renderer_opengl/gl_rasterizer_cache.cpp:MortonCopy:255: Out of bound texture
[   6.539173] HW.GPU <Critical> core/hw/gpu.cpp:MemoryFill:87: invalid end address 0X18600000
[   6.636382] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:497: Firmware hash: 0x7f38630a8c994617
[   6.636388] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:501: Structures hash: 0x1732733d14b84894
[   6.636389] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:189: called size=0x35378, prog_mask=0x000300FF, data_mask=0x003500FF
[   6.637149] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:255: Registered interrupt=2, channel=2, event=event-001487b8
[   6.637398] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:271: (STUBBED) called
[   6.637649] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:281: (STUBBED) called mask=0x2000
[   6.638008] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:257: Application has requested initialization of DSP hardware
[   6.638185] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[   6.639822] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[   6.780672] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[   6.780749] Service.FS <Warning> core/file_sys/archive_ncch.cpp:OpenFile:159: Bad Word List file missing. Loading open source replacement from memory
[   6.789615] Service.FRD <Warning> core/hle/service/frd/frd.cpp:SetClientSdkVersion:147: (STUBBED) called, version: 0x050200C8
[   6.789894] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetMyPresence:34: (STUBBED) called
[   6.790509] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetFriendKeyList:49: (STUBBED) called, unknown=0, frd_count=100
[   6.793174] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:InitializeSession:23: (STUBBED) programID=0X0000000000000000
[   6.793471] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:ResumeDaemons:90: (STUBBED) bit_mask=0x00000002
[   6.793563] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:ResumeDaemons:90: (STUBBED) bit_mask=0x00000004
[   6.794532] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:GetStorageEntryInfo:644: (STUBBED) called
[   6.794989] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:UnregisterStorage:46: (STUBBED) called
[   6.795475] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:RegisterStorageEntry:633: (STUBBED)  unk_param1=0X0000055D, unk_param2=0X00000000, unk_param3=0X00100000, unk_param4=0X00000014, unk_param5=0X01
[   6.800035] Service.LDR <Warning> core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRR:155: (STUBBED) called, crr_buffer_ptr=0x08C5F000, crr_size=0x00002000
[   7.344911] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetMyFriendKey:88: (STUBBED) called
[   7.377543] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetMyFriendKey:88: (STUBBED) called
[   7.446073] Service.PTM <Warning> core/hle/service/ptm/ptm.cpp:GetStepHistory:97: (STUBBED) called, from time(raw): 0x96f98f1c00, for 24 hours
[   7.463947] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[   7.464010] Service.FS <Warning> core/file_sys/archive_ncch.cpp:OpenFile:145: Country list file missing. Loading open source replacement from memory
[   7.562262] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[   7.565519] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[   7.730353] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default

**Comment by liushuyu** [comment]
Hi there, are you using the Flatpak version of the `citra` or the one downloaded from the GitHub?

If you have the Flatpak, then it's due to an issue we haven't figured out a way to resolve. 

If you have the one from the GitHub Release, then try installing `ffmpeg` from your package manager (`apt install ffmpeg`).

**Comment by SleepingSnakezzz** [comment]
As the OP has not responded, I'll be closing this for now.
