### ISSUE TITLE
Segfault in Cubic Ninja and Bravely Default

### ISSUE THREAD

**Issue by bunnei** [citra-emu/citra#547]
Cubic Ninja and Bravely Default currently segfault the emulator due to the VS MOVA instruction setting the shader "address register" to NaN. This is due to a vertex attribute being used that is never set.

**Comment by bunnei** [comment]
Note: If you set the address register to zero instead of NaN, both of these games boot past this (CN even goes in game)

**Comment by Subv** [comment]
Home Menu and Steel Diver have this same problem

**Comment by woody2014** [comment]
How do you fix this bug

**Comment by yuriks** [comment]
Has this already been fixed? Bravely Default has been working fine for a while.

**Comment by Subv** [comment]
Yep, fixed by #695
