### ISSUE TITLE
LSoD

### ISSUE THREAD

**Issue by conelover1234** [citra-emu/citra#5477]
This is not new, but in Smash 4 when you select certain characters or modes, it keeps loading forever. It's not new but, could you please fix it in the next Citra update?

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by conelover1234** [comment]
> This is an issue tracker for developers and not a support forum.
> Please use our Discord for support requests.

I'm not supporting, and where do I have to click in the Discord? I tried that and my message gets deleted.

**Comment by KingGamingYT** [comment]
If you're on computer, use #citra-support-desktop. If you're on android, use citra-support-android.
