### ISSUE TITLE
[Feature Request] Por from Yuzu "Game Properties" and "Per game Settings"

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#5480]
It would be ideal to be able to carry these yuzu features, from the game properties to be able to enable / disable DLCs and Updates, mods or textures. And the possibility of saving the settings that one believes necessary for the game to run as the user believes necessary on their PC (not only audio / video settings, but also controls).

Feature request based on  #4924 but with the addition of game properties and the ability to enable/disable things.

**Comment by FearlessTobi** [comment]
Please leave your requests as a comment on the original issue in order to avoid duplication.
