### ISSUE TITLE
Updated Mac builds missing from Citra nightly and canary

### ISSUE THREAD

**Issue by chaNcharge** [citra-emu/citra#5481]
When installing or updating Citra, I only have the options to download an outdated build of nightly and canary is entirely missing in the maintenance tool. The most recent available Mac build is nightly 1588.

**Comment by GMaxera** [comment]
@MerryMage I think that since https://github.com/citra-emu/citra/pull/5317 get merged the Mac OS build failed consistently and no new build (canary and nightly) has been pushed to repo.citra-emu.org

**Comment by GMaxera** [comment]
I think the culprit is that the job can't take more than 50 minutes otherwise Travis will terminate it: https://docs.travis-ci.com/user/customizing-the-build#build-timeouts

**Comment by GMaxera** [comment]
I've started to do various attempt to fix this issue on my fork playing around with Travis and test various suggestions I found on other repositories that had the same issue. Hopefully, I'll be able to provide a stopgap soon 🤞

**Comment by takeshineale128** [comment]
It's working high Sierra and pokemon XY also worked on the latest Canary build 1829

**Comment by chaNcharge** [comment]
The CI still seems to be failing, but if I understand this correctly, does this mean that after a few more commits, it'll fix itself?

**Comment by GMaxera** [comment]
> The CI still seems to be failing, but if I understand this correctly, does this mean that after a few more commits, it'll fix itself?

Yes, exactly. The last commit was my PR with the fix, and we need another commit or two before the cache get big enough to complete the build.
