### ISSUE TITLE
new art academy Only 1 or 2 frames.

### ISSUE THREAD

**Issue by xiantuan** [citra-emu/citra#5482]
![image](https://user-images.githubusercontent.com/10727426/89011046-4ceb1b00-d342-11ea-870c-89ef118eddb6.png)

**Comment by tywald** [comment]
Underclock Citra to 5% in the System tab.

This is more appropriate to ask on the forums: https://community.citra-emu.org/

**Comment by xiantuan** [comment]
> Underclock Citra to 5% in the System tab.
> 
> This is more appropriate to ask on the forums: https://community.citra-emu.org/

Thanks.And The story is over, the fps is up.
