### ISSUE TITLE
[Feature Request] screen streaming to phone/tablet

### ISSUE THREAD

**Issue by Papermanzero** [citra-emu/citra#5489]
A feature to make citra better and more playable would be to stream the touchscreen, both 3ds screens or the top screen to a tablet or phone.
The main screen can be displayed for example on the TV/Monitor while the touchscreen can be used on phone/Tablet.The phone can also be used to transmit gyro input or touch gestures.

The implementation should be based on moonlight.
https://moonlight-stream.org/
Moonlight is a streaming client for every kind of device (ios, android, etc)
Therefore Citra has to implement a server functionality to reach moonlight.
As baseline the application sunshine can be used.
https://github.com/loki-47-6F-64/sunshine

Citra shall either stream both screens, or one screen to the phone/tablet on which moonlight runs.
The touchinput or gyroinput from the phone tablet will be returned to citra. 

This would create an almost perfect 3DS emulation.

**Comment by FearlessTobi** [comment]
According to this setup guide, there's no modification needed for Citra to run with this program.
https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide
In a first step, I tried adding Citra to the GFE program list, which proved successful.

Also, we are wary of adding support for too many third party programs, especially if they require extensive modification to Citra.
This is even needed apparently for this program so I'm closing this issue.
