### ISSUE TITLE
Enabling hardware shader blurs Pokemon Sun/Moon/Ultra Sun/Ultra Moon text

### ISSUE THREAD

**Issue by renntbenrennt** [citra-emu/citra#5502]
As the screenshot display:
![image](https://user-images.githubusercontent.com/13610283/89724130-d7fa9e00-da31-11ea-98a2-9b6d5c90b238.png)

This is the relevant setting:(Hardware shader turn on)
![image](https://user-images.githubusercontent.com/13610283/89724122-c74a2800-da31-11ea-9c9c-450a290f0cd1.png)

At first I thought it's because the game rom is malfunctioned until I tried different rom source and finally post this question on Forum and got help eventually.

That is, by turning off the `Hardware Shader`.

And the post can be found in here:
https://community.citra-emu.org/t/help-blurry-text-of-the-game-pokemon-sun-and-pokemon-ultra-moon/289206

As you can see from this screenshot when I turn off the `Hardware Shader`
![image](https://user-images.githubusercontent.com/13610283/89724111-9ec22e00-da31-11ea-962b-26167f324f0a.png)

Setting:(Hardware shader turn off)
![image](https://user-images.githubusercontent.com/13610283/89724140-fa8cb700-da31-11ea-92dc-9d5dd60af8dc.png)

I understand since I can play game with the shader turn off, but... the gaming experience is much better when the shader is on... so... is this problem fixable?

Here's my log of the emulator:
[citra_log.txt](https://github.com/citra-emu/citra/files/5046714/citra_log.txt)

And here are some other specs:
Operating System: macOS 10.15.6 (19G73)
CPU: 16 GB 1600 MHz DDR3
GPU: AMD Radeon R9 M370X 2 GB Intel Iris Pro 1536 MB
Citra Version (found in title bar): 1588
Game: Pokemon Sun

Thanks in advance!

**Comment by GPUCode** [comment]
Has been fixed in macos vulkan builds
