### ISSUE TITLE
[Feature Request] Lock emulation to 30 FPS

### ISSUE THREAD

**Issue by MisterPrintf** [citra-emu/citra#5503]
I'm not sure if this is possible, due to the uniqueness of code from one 3DS game to the next, but it would be great to have an option to lock 3DS games to 30 FPS.
This way, even the most difficult games to emulate, such as Luigi's Mansion: Dark Moon, which tries (and usually fails) to hit 60 FPS, could be run with at least a slight performance boost.

**Comment by FearlessTobi** [comment]
I'm pretty sure this is not possible without making a mod for every game where the target framerate shall be changed.
