### ISSUE TITLE
Some textured surfaces failing to render in OoT3D

### ISSUE THREAD

**Issue by Leafdomain** [citra-emu/citra#5542]
Hi,

I've experienced a problem in Zelda OoT3D that I have not seen elsewhere, so I thought it needs to be reported.

**Some textured surfaces are rendering only when I'm close to them in distance.**

This graphical bug happened the most in Dodongo's Cavern, and also Goron City. I haven't necessarily observed it elsewhere yet, but it might certainly be happening at other locations as well.

![zeldabug](https://user-images.githubusercontent.com/70599421/91888808-90b0a780-ec95-11ea-9ca0-40b0d7ff0654.png)

I have Accurate Multiplication enabled, as it's necessary for the UI to render properly anyways.

So, anyone aware of this issue or how to solve it?...

**Comment by FearlessTobi** [comment]
Thanks for the report, it would be great if you could also provide a log file of this issue.
Also could you please check if this issue exists in Citra Nightly-1459? 
It's possible that your problem is a regression.

**Comment by Leafdomain** [comment]
@FearlessTobi Hi, I checked as you asked and this error is not happening in Nightly 1459.

This seems to be a regression as you said.

Here's my log file:
[citra_log.txt](https://github.com/citra-emu/citra/files/5166796/citra_log.txt)

**Comment by Colmines92** [comment]
I have a similar texture problem with Final Fantasy Explorers...
I can see some kind of a plane in the floor around the main character, and everything inside this plane renders ok, but outside it, some textures are all bugged.
I fix it just by changing the internal resolution and then putting it back to the value it has and this fixes the textures, but it is still a bug.
Here are some screenshots:

Before: (Bad)
![01_1](https://user-images.githubusercontent.com/25232329/92306516-b1128780-ef5d-11ea-9e09-cd3e7bdb7ebd.png)
After changing resolution and putting it back to its previos value: (Good)
![01_2](https://user-images.githubusercontent.com/25232329/92306517-b7086880-ef5d-11ea-9544-fea4e98d5379.png)

Before: (Bad)
![02_1](https://user-images.githubusercontent.com/25232329/92306521-ba9bef80-ef5d-11ea-818f-f30e61014aeb.png)
After: (Good)
![02_2](https://user-images.githubusercontent.com/25232329/92306522-bd96e000-ef5d-11ea-879e-d475b681c299.png)

In other places the rocks at the distance are full black, and when I get near they show the texture.

**Comment by Leafdomain** [comment]
This seems to be fixed in recent releases. Closing.
