### ISSUE TITLE
"Texture Swap" glitch in Zelda: Ocarina of Time 3D and Zelda: Majora's Mask 3D with linear filtering enabled

### ISSUE THREAD

**Issue by HenrikoMagnifico** [citra-emu/citra#5551]
====================================================

In Zelda: Ocarina of Time 3D and Zelda: Majora's Mask 3D, if texture filtering is enabled of any kind- a strange "texture swap" glitch starts occuring in certain regions of the game after a certain time with the game running has passed. More speficially, it appears to load in the wrong textures in the distance as mipmapped LOD textures are loaded into memory. The most common reported region this bug occurs in is inside the Forest Temple and inside Dodongos Cavern, after roughly 20-30 minutes of playing. These mipmapped textures are the wrong textures, when the camera gets close enough it displays correctly. The only way to solve the issue temporarily is by restarting the game completely. This happens no matter what custom textures are loaded, and no matter their resolution.

The bug has been tested and verified on the latest version of Citra Canary (1850) on both Windows 7 and Windows 10. It appears using either NVIDIA (GTX 1070ti) or AMD (RX 580) Graphics Cards or Intel (i9-10900K) or AMD (Ryzen 3700X) CPUs.

**Screenshots of the bug in action:**

![Screenshot_20200911-045118_Twitch](https://user-images.githubusercontent.com/11783274/92944995-f995dd80-f454-11ea-87db-d2ffb7ab16b7.jpg)
![Screenshot_20200911-045310_Twitch](https://user-images.githubusercontent.com/11783274/92944997-fa2e7400-f454-11ea-84cd-453596236ad9.jpg)
![Screenshot_20200911-045618_Twitch](https://user-images.githubusercontent.com/11783274/92945000-fb5fa100-f454-11ea-9e9d-1596f31f1805.jpg)

**Comment by HenrikoMagnifico** [comment]
Update: I've received reports of this issue happening without custom textures loaded as well. Changing the title!

**Comment by vascojdb** [comment]
Hey! Has this issue been solved? Or do we need to disable linear filtering? Because disabling Texture Filter does not solve it entirely.
