### ISSUE TITLE
Citra uses incredibly high amounts of memory to preload custom textures

### ISSUE THREAD

**Issue by HenrikoMagnifico** [citra-emu/citra#5552]
====================================================

Citra appears to be using incredibly high amounts of memory to preload custom textures. Using my HD texture packs as an example, preloading Zelda: Majora's Mask 3D using my 4K texture pack requires a whopping 24.13GB of RAM or else it'll never boot. This is **after** the textures have been properly optimized using tools like PNGGauntlet. The texture pack itself only takes up roughly 9.7GB, which is less than half of the memory Citra needs to preload it. Preferably, it would take up the same amount of space the textures themselves, or at least give the user an alert that it won't be able to preload the textures with the current amount of memory in the system. The optimal solution would be if .DDS support were implemented, since those take up way less space than .PNG files and can also be calculated much quicker by the GPU.

The bug has been tested and verified on the latest version of Citra Canary (1850) on both Windows 7 and Windows 10. It appears using either NVIDIA (GTX 1070ti) or AMD (RX 580) Graphics Cards or Intel (i9-10900K) or AMD (Ryzen 3700X) CPUs.

**Screenshots of the issue in action:**
![Skärmklipp](https://user-images.githubusercontent.com/11783274/92945578-c1db6580-f455-11ea-9f75-4430888f9dda.PNG)

**Comment by BreadFish64** [comment]
This is not a bug, Citra decompresses the PNG in memory. Support for actual compressed texture formats would alleviate some of this but that's already covered in issue #4997,

**Comment by Jules-A** [comment]
> This is not a bug, Citra decompresses the PNG in memory. 
LoadPNG's changes since the version Citra uses is mostly around memory allocation. I wonder if a newer version would help OP's case.
