### ISSUE TITLE
[Feature Request] Add HLE AAC Decoder for Flatpak

### ISSUE THREAD

**Issue by gal20** [citra-emu/citra#5556]
According to the [wiki](https://github.com/citra-emu/citra/wiki/HLE-AAC-Decoder), the flatpak version does not include HLE AAC decoder because it requires the non-free library libfdk-aac. However, I have successfully built from source, including the HLE AAC decoder, without this library.
Here are the steps I took:
- Fresh install of Ubuntu 20.04 LTS
- run the following commands:
`sudo apt-get install libsdl2-dev qtbase5-dev libqt5opengl5-dev qtmultimedia5-dev ffmpeg libavcodec-dev build-essential cmake git`
`git clone https://github.com/citra-emu/citra --recursive`
`cd citra`
`mkdir build`
`cd build`
`cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_FFMPEG_AUDIO_DECODER=ON`
`make`

Here's a screenshot after the build is complete, with commands to prove libfdk is not installed:
![citra](https://user-images.githubusercontent.com/71563441/93677588-7b20e780-fab5-11ea-94b9-434a218ee51d.png)
As you can see, the only AAC library installed is **libaacs**, which is licensed LGPLv2.1 (Compatible with GPL2).

I tested Pokemon X with this build, and it successfully played the game's music, indicating that the HLE AAC is working.

**Comment by xperia64** [comment]
That's using ffmpeg's internal AAC decoder, which of course, flatpak's variant of ffmpeg doesn't contain either last I checked.

**Comment by gal20** [comment]
> That's using ffmpeg's internal AAC decoder, which of course, flatpak's variant of ffmpeg doesn't contain either last I checked.

Can you check again? Apparently there's an extention to org.freedesktop.Platform.ffmpeg that [does include AAC](https://github.com/flathub/org.freedesktop.Platform.ffmpeg/blob/7e9f64c56619a67380ac29d48be36956d62ac4bc/org.freedesktop.Platform.ffmpeg.json#L66).
The list of [available runtimes](https://docs.flatpak.org/en/latest/available-runtimes.html) includes a "org.freedesktop.Platform.ffmpeg-full" runtime, that according to description includes "All ffmpeg codecs (extension)".

**Comment by gal20** [comment]
I addressed this issue in a [pull request](https://github.com/citra-emu/citra/pull/5561), so this isn't relevant anymore.
