### ISSUE TITLE
[Bug/Feature Request] Support loading from WSL Directories

### ISSUE THREAD

**Issue by TurtleP** [citra-emu/citra#5557]
**Citra Version**: Nightly 1623
**Citra Log**: [citra_log.txt](https://github.com/citra-emu/citra/files/5250668/citra_log.txt)

**Issue**:

It seems that Citra doesn't support loading off a Windows Subsystem for Linux directory. I'm trying to do some homebrew development testing and when I open a 3dsx file in my (Ubuntu) home directory, I get the following:

![image](https://user-images.githubusercontent.com/6239208/93689680-d4c9e780-fa9e-11ea-9cd3-29632f7ea5c6.png)

I can easily load the same file and have it run fine if I move it to my Windows Documents directory.

**Comment by xperia64** [comment]
For now you can use `%LOCALAPPDATA%\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\` or add it to your Citra path.

I think Citra doesn't like the '$' in `\\wsl$\Ubuntu`

**Comment by xperia64** [comment]
This appears to be a bug in Qt not handling the `\\wsl$\` format path in `QFileDialog::getOpenFileName`. We never receive the full proper path from Qt.

Citra itself supports these paths just fine. If you open Citra from the command line and pass the file to open as an argument directly, it works. Alternatively, you can manually add your WSL path to Citra's game directory by editing the config file.

**Comment by TurtleP** [comment]
Yeah, for now I'll just add it via the localappdata path you mentioned. Thank you!

**Comment by FearlessTobi** [comment]
Going to close this then as this seems to be a QT issue.
