### ISSUE TITLE
MONSTER HUNTER STORIES BLURRY ISSUE

### ISSUE THREAD

**Issue by SADORIAN** [citra-emu/citra#5558]
I am running Citra Nightly 1623.
Most battle and cutscenes are completely blurry .
![ss1](https://user-images.githubusercontent.com/58925768/93729468-26858580-fbf7-11ea-82d4-5bbbc6c8e8cf.PNG)
![ss2](https://user-images.githubusercontent.com/58925768/93729483-37ce9200-fbf7-11ea-92a2-388a3139ea17.PNG)

**Comment by tywald** [comment]
Related to #3287 (duplicate?).

**Comment by FearlessTobi** [comment]
Yes, it's probably a duplicate.

**Comment by kanelakis** [comment]
With a code the blur in the map and in the dialogues is resolved, but it remains in the battles.

**Comment by NineKain** [comment]
This is still an issue
