### ISSUE TITLE
[Feature Request] Improve custom texture loading performance

### ISSUE THREAD

**Issue by tbsp** [citra-emu/citra#5559]
When playing Monster Hunter 4 Ultimate with custom map textures, the time spent loading the textures can increase quest start times from ~6 seconds to 9-11 seconds if they aren't preloaded, which often leads to disconnections during multiplayer. Preloading the full texture pack requires lots (~32gb) of RAM, which makes it impractical.

Some ideas for how to improve performance:
- Add a means of preloading only a portion of the custom textures (likely per-folder), either on startup or on demand during emulation
- Pass custom texture loading off to a thread, with the base texture being used until the replacement is available

**Comment by NielsGx** [comment]
What about .dds files ? dxt5, bc7
Maybe that could help?

**Comment by tbsp** [comment]
That may help. I've done some additional testing and concluded the following:

- When _first_ loading custom textures using a spinning harddrive the load time is increased 3-5seconds (using an SSD this is only ~1sec).
- Even if the game is restarted, subsequent loads take only ~0.5sec longer than without custom textures.
- Restarting my PC causes the "super slow" initial load to occur again, which makes me think something on the OS-level is caching things.
- I've tested with a pack mostly made of PNGs, and again with all the PNGs converted to JPG (to make them much smaller), and the slow initial load appears to be about the same. I believe the delay is from seeking the thousands of files, not the loading.

Based on this I'll probably just:

- Only play multiplayer on systems with an SSD.
   -OR-
- Run a Python script to recursively read in all files in my custom texture directory after a restart to initialize the apparent OS-level cache if I plan to play multiplayer (seems kinda crazy, but oh well).

**Comment by NielsGx** [comment]
In my experience hdd's don't like copying thousands of files (dunno about reading), so maybe using packs in an archive or something like that could help ?
Maybe an archive without compression (because png/jpg already are compressed, normally?, and it would be longer to decompress an archive than what we already have I guess?)

I think there is soemthing like that in dolphin, and it's easier for end-user to install custom textures like that.

**Comment by tbsp** [comment]
That sounds like a potential solution for sure. I took a quick look at the Dolphin resource packs, though it seems when a pack is "activated" it merely copies the textures from the zip file to the appropriate directory, which wouldn't affect load times in Citra. Perhaps I'm misunderstanding how it works though.

Note that PNGs can be compressed in several ways, and depending on the tool used may actually have very little compression. A tool like oxipng can be used to optimize for maximum compression.

**Comment by slentara1** [comment]
I would like to suggest maybe pointing preload textures string to a new folder called preload ad opposed to directing it to the load folder. That way we could portion off the textures we wish to load into the preload folder without loading ALL the textures. 

See the example:
![unnamed](https://user-images.githubusercontent.com/67963757/105529674-57acba00-5cac-11eb-876b-a5af800077ab.png)

**Comment by SleepingSnakezzz** [comment]
@tbsp We now have Async custom texture loading as well as support for compressed formats with https://github.com/citra-emu/citra/pull/6452, which should alleviate some of these concerns. Can you test on the latest Citra Nightly build to see if this is still a problem?

**Comment by GPUCode** [comment]
Closing this due to above reason
