### ISSUE TITLE
Audio on pokemon xy not working on linux even after installing the necessary dependencies

### ISSUE THREAD

**Issue by Chico3589** [citra-emu/citra#5562]
I am using Arch Linux and have been trying to get audio to work, i have compiled citra with the necessary dependencies including libfdk-aac-2.0.1-2
here is a log file:
[citra_log.txt](https://github.com/citra-emu/citra/files/5284586/citra_log.txt)
 hope im not being a bother, thanks :)

**Comment by gal20** [comment]
You need to add -DENABLE_FFMPEG_AUDIO_DECODER=ON parameter to cmake. libfdk is not required, instead it uses libavcodec.

**Comment by Chico3589** [comment]
thanks, it worked!
