### ISSUE TITLE
Missing HP/EXP bar texture in status window of Metal Max 4 JP with hardware renderer

### ISSUE THREAD

**Issue by xxbidiao** [citra-emu/citra#5563]
I have found a bug in METAL MAX 4 (Japan) from Nightly 1248 to Nightly 1249. In Nightly 1249 the colors that indicate your HP, SP and EXP (see screenshots below) turn completely black.
As of Nightly 1326, The colors indicating those stats are completely blank. 
Using the newest version generates the log attached, with 
`Render.OpenGL <Critical> video_core/renderer_opengl/gl_rasterizer_cache.cpp:GetTextureSurface:1247: Texture size (4x4) is not multiple of 8`
Appear each frame when the status window is open.
[citra_log.txt](https://github.com/citra-emu/citra/files/5289472/citra_log.txt)

Please see screenshots from different versions of previous Citra nightly builds. The newest version (both canary and nightly) performs exactly like nightly 1326. All with Native resolution and post shaders disabled (unlike in the log).
<img width="577" alt="metal-max-4-citra-bug" src="https://user-images.githubusercontent.com/1439638/94382241-fe6fb800-0109-11eb-93ca-470d8619804f.png">

Disabling Hardware Renderer restores the colors.

**Comment by Colmines92** [comment]
I can confirm that nightly 1853 (last release at the moment) is still behaving as in nigthly 1326. This issue persists.

**Comment by Colmines92** [comment]
It is broken again on latest nightly.

**Comment by GPUCode** [comment]
Did that PR fix it and it was broken again or did it never work?

**Comment by Colmines92** [comment]
It was working perfectly until the other day.
Now I notice in  nightly 1888 it's broken again.

**Comment by Colmines92** [comment]
Nevermind.
After trying every build since 1876 I noticed the issue was in my side. Made a backup of my saves, deleted the user folder, put it back and it's working now on 1888.
Sorry for that.
