### ISSUE TITLE
My shaders are "braking"

### ISSUE THREAD

**Issue by Kael43** [citra-emu/citra#5564]
my problem is when i double click on a rom my citra closes
Specs:ryzen 51600 af
gtx 1050 zotac
citra: canary 1852
log:
[citra_log (1).txt](https://github.com/citra-emu/citra/files/5303052/citra_log.1.txt)

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and a support forum.
Please use our Discord for support requests.
