### ISSUE TITLE
Cmake build error

### ISSUE THREAD

**Issue by mariohackandglitch** [citra-emu/citra#557]
Hello everybody. I've downloaded the lastest version of citra (10/2/2015), but I can't build the solution. I get this error:

CMake Error at externals/inih/CMakeLists.txt:11 (add_library):
  Cannot find source file:

    inih/ini.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: inih

NOTE: the folder inside externals is empty.

**Comment by lioncash** [comment]
You need to initialize the git submodules with `git submodule init` and then `git submodule update`. To do this when cloning the repository, do `git clone --recursive https://github.com/citra-emu/citra.git`

**Comment by mariohackandglitch** [comment]
Ok, thanks a lot ;)

**Comment by archshift** [comment]
Is this still an issue for you?

**Comment by mariohackandglitch** [comment]
No, I had another problem on building, but now is solved. Also I forgot to close this.
