### ISSUE TITLE
Monster Joker 3 do multiples pauses every few seconds 

### ISSUE THREAD

**Issue by pidgey84** [citra-emu/citra#5578]
I starting notice this after the version 1543 of the nightly build of citra, all the new versions do multiples pauses on the game independly of the configs that i put, for example it do it if i put the game on 5x, 3x or even on native, i notice that the game after the simplygon logo get more than 2x time loading than the build i said before that works fine, maybe this is related to this issue also.

I hope that this help :).

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our forum or Discord for support requests.
