### ISSUE TITLE
The Legend of Dark Witch 3 have 0 music on standard sound driver

### ISSUE THREAD

**Issue by pidgey84** [citra-emu/citra#5579]
I notice this one also some time ago, this games works well and the sounds effect plays but it have no music, i try the accurate option, in this one the music works but is so slower that is impossible to play the game.

Greetings.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our forum or Discord for support requests.

**Comment by eadmaster** [comment]
can this be reopened? It is still affecting the latest builds i've checked...
