### ISSUE TITLE
Qt frontend: no graphical display until window resize

### ISSUE THREAD

**Issue by thejsa** [citra-emu/citra#5584]
On Citra Nightly 1628 (1c8461f), at least on macOS 11 and 10.15, nothing is displayed in the render window when using the Qt frontend until the window is resized, no matter what the initial size of the window:

<img width="512" alt="Screenshot 2020-10-19 at 13 15 04" src="https://user-images.githubusercontent.com/10799473/96450940-c5110080-120e-11eb-9655-f35f5c406664.png">

This seems to be a regression introduced in Nightly 1411 by #5071 and has apparently been reported by various users, although no formal issue had been created until now that I'm aware of.

**Comment by beeselmane** [comment]
Is there any fix for this issue? I've just built citra from the latest commit 6f6a9357c26eccf09bf0c993f159d69bbe472f49 on my M1 mac running macOS 12.2 and I'm seeing the same behavior.

**Comment by Steveice10** [comment]
This has been fixed since the re-release of macOS Citra with Vulkan.
