### ISSUE TITLE
Cannot install citra flatpak version

### ISSUE THREAD

**Issue by soredake** [citra-emu/citra#5588]
❯ flatpak install https://flatpak.citra-emu.org/citra-nightly.flatpakref
error: No such ref 'app/org.citra.citra-nightly/x86_64/master' in remote citra-nightly-origin

❯ flatpak install https://flatpak.citra-emu.org/citra-canary.flatpakref
error: No such ref 'app/org.citra.citra-canary/x86_64/master' in remote citra-canary-origin

**Comment by HenriqueAD7** [comment]
Equally.

I was receiving the message when updating via CLI that the repository did not exist, I uninstalled the version I already had on my system thinking that the Citra team changed the repository to something new. However, I cannot install via Flatpak for the same reason mentioned above.

**Comment by TheGreatestJannet** [comment]
I have the same issue. Unfortunately the flatpak version also still suffers from this major issue: https://github.com/citra-emu/citra/issues/5560 pretty much making it unusable if you want decent performance. Currently it's probably best to use the precompiled binary or the compile it yourself

**Comment by HenriqueAD7** [comment]
> I have the same issue. Unfortunately the flatpak version also still suffers from this major issue: #5560 pretty much making it unusable if you want decent performance. Currently it's probably best to use the precompiled binary or the compile it yourself

I also had the same problem. However, I realized that there were some problems with other emulators, such as GNOME Games.
In the end after updating my Nvidia video driver, for GTX 1060, to version 455.28, the same thing didn't happen anymore.

Soon, in my case, I discovered that the problem was the 450 series video driver and not the Citra Flatpak.
Detail, the same problem occurred with the precompiled version. After updating the driver, as described above, there were no further problems.

**Comment by soredake** [comment]
@zhaowenlan1779

**Comment by soredake** [comment]
```
error: Signature made Wed Oct 21 01:41:50 2020 using RSA key ID F8B088B90782CA9B
BAD signature from " <citra@citra-emu.org>"
Key expired Mon Oct 26 03:12:42 2020

**Comment by MuseHorizon** [comment]
Any update on this issue? Linux users have no way to install Citra without building it.

Thanks! Appreciate the hard work

**Comment by TheGreatestJannet** [comment]
You can download the precompiled version on the download page but that doesn’t work on all distros.

**Comment by abderrahim** [comment]
As @soredake mentioned, this is just an expired signing key. A workaround is to disable checking the signature, but then you can only install it for your user.

```
flatpak remote-delete citra-nightly-origin # if it's currently installed with the flatpakref
flatpak remote-add --user --no-gpg-verify citra https://flatpak.citra-emu.org/repo
flatpak install --user citra-nightly org.citra.citra-nightly # or canary
```

**Comment by ask-compu** [comment]
seems to be radio silence from the devs on anything flatpak related

**Comment by soredake** [comment]
AFAIK flatpak build are not enabled after https://github.com/citra-emu/citra/pull/5602 is merged

**Comment by B3n30** [comment]
Just for your info. We put flatpak support on a hold until android is merged to develop. This will most likely result in some other release parallel to nightly and canary like once every month/ every second month. With such a release plan we can use flathub, then

**Comment by soredake** [comment]
Citra on flathub will be super nice!

**Comment by pleonex** [comment]
May I suggest to update the webpage (https://citra-emu.org/download/) with this information (maybe a link to this issue too)?
Just to avoid people thinking they did some steps wrong :smile:

**Comment by VinnyVynce** [comment]
I agree there should be a warning or something about it.
For now I just added the citra-emu repository without gpg verification.
```
flatpak remote-add --if-not-exists --no-gpg-verify citra-emu https://flatpak.citra-emu.org/repo
flatpak install org.citra.citra-nightly
```
Hopefully it's going to be resolved in the near future 🤞🏻

**Comment by VinnyVynce** [comment]
I agree there should be a warning or something about it.
For now I just added the citra-emu repository without gpg verification.
```
flatpak remote-add --if-not-exists --no-gpg-verify citra-emu https://flatpak.citra-emu.org/repo
sudo flatpak install org.citra.citra-nightly # sudo is required here to bypass GPG verification.
```
Hopefully it's going to be resolved in the near future 🤞🏻

**Comment by databoose** [comment]
> I agree there should be a warning or something about it.
> For now I just added the citra-emu repository without gpg verification.
> 
> ```
> flatpak remote-add --if-not-exists --no-gpg-verify citra-emu https://flatpak.citra-emu.org/repo
> sudo flatpak install org.citra.citra-nightly # sudo is required here to bypass GPG verification.
> ```
> 
> Hopefully it's going to be resolved in the near future 🤞🏻

Note that this is the october 2020 nightly build, so this isn't actually nightly.

**Comment by Follpvosten** [comment]
Would be great to have up-to-date flatpaks again; I currently can't use that old version of citra on my laptop at all, I'm suspecting because some lib in there is too old to support my laptop's APU.

**Comment by TheGreatestJannet** [comment]
Try compiling it from source that should hopefully make it work on your laptop.

**Comment by soredake** [comment]
> Would be great to have up-to-date flatpaks again; I currently can't use that old version of citra on my laptop at all, I'm suspecting because some lib in there is too old to support my laptop's APU.

Citra is available in snap format https://snapcraft.io/citra-emu

**Comment by TheGreatestJannet** [comment]
That’s good but snaps can be annoying to install and get running on distros that aren’t Ubuntu.

**Comment by Follpvosten** [comment]
I usually don't have anything against snaps, but in this case they won't work since I'm on Void (which isn't supported and likely never will be since snap hard depends on systemd or some kind of systemd shim in place).
I might try building it myself, or maybe I can finally get around to installing Gentoo on a separate partition where I'll be building stuff from source anyways.

**Comment by marcoguilherme** [comment]
You can install with 'snap'. 

$ `snap install citra-emu`

**Comment by TheGreatestJannet** [comment]
Is this build official? Also if it is does that mean that the flatpak version is discontinued?

**Comment by soredake** [comment]
Good news! https://flathub.org/apps/details/org.citra_emu.citra

**Comment by TheGreatestJannet** [comment]
Great! Will this be regularly updated?
