### ISSUE TITLE
[Feature Request] Vulkan support

### ISSUE THREAD

**Issue by ss8688** [citra-emu/citra#5590]
Now，vulkan itself become stable and most devices have this fiction. It will benefit everyone,especially mobile devices that do not have a processor with good performance.So It would be great if add vulkan support like yuzu.

**Comment by ss8688** [comment]
It seems that vulkan will benefit Android users a lot.

**Comment by RinMaru** [comment]
was being worked on but the dev stopped. not sure when if ever it will be a thing

**Comment by ss8688** [comment]
It have stopped for 4 years

**Comment by Schplee** [comment]
We're aware that Vulkan is highly requested, but supporting a new backend is a very large task. We don't currently have any developer interest in building out a Vulkan backend.

**Comment by AbnormalPoof** [comment]
Implemented in #6516
