### ISSUE TITLE
Beyblade Burst God 3ds 

### ISSUE THREAD

**Issue by SemajPlayz** [citra-emu/citra#5592]
can someone pls put in some of the passwords so i can put them in to get the beys. and also how do you get to the solo world league after you finish the team league?

**Comment by Schplee** [comment]
This is an issue tracker and not a support forum. Please ask for support on our Forum or Discord server, or Google if it's a gameplay question.

**Comment by SemajPlayz** [comment]
oh im sorry i was not aware

**Comment by SemajPlayz** [comment]
man now I feel like a freaking dingbat
