### ISSUE TITLE
Performance in Pokémon Omega Ruby dropped a lot at nightly 1629

### ISSUE THREAD

**Issue by DaniloT** [citra-emu/citra#5597]
I was playing with little to no issue a game of pokemon omega ruby on citra nightly build 1628. Ever since I upgraded to 1629, I started to get random freezes and hickups during gameplay, mostly during battles. I tried installing the latest canary build, 1865, and it was even worse, hanging a lot in battles and some out of battles too, so whatever is being done to citra seems to be making performance noticeably bad for this pokemon game I'm playing right now, at least.
I reverted to 1628 and the game is back to basically perfect, just thought you should know of this impact.

**Comment by BreadFish64** [comment]
#5574 was the only change in nightly 1629. It is *extremely* unlikely for that to have made difference in performance. Are you sure you're using the same settings between the two versions?
