### ISSUE TITLE
Citra crashes after loading saved state

### ISSUE THREAD

**Issue by sjoerd1112** [citra-emu/citra#5599]
I just updated to the newest version of citra nightly (1630) and sometimes after loading a saved state citra completely crashes. I had this issue with the previous version as well.

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for developers, not a support forum. For support with citra, go to the forums: https://community.citra-emu.org/
Or join the Discord server: https://citra-emu.org/discord/
