### ISSUE TITLE
Senran Kagura Burst - Stage advancement bug

### ISSUE THREAD

**Issue by Drvx** [citra-emu/citra#5614]
This game gets stuck at the end of the minor cutscene on chapter 5, mission 6 of Hebijo arc, right before the white flash transition to the gameplay. This cutscene is non-skippable too, which renders this game impossible to beat.

[citra_log.txt](https://github.com/citra-emu/citra/files/5577829/citra_log.txt)

![senran freeze](https://user-images.githubusercontent.com/74725652/99880483-48fa4600-2c1c-11eb-9372-ec9d0aeece03.png)

Citra Nightly 1644
Windows x64
Ryzen 5 1600x
Gtx 1070

**Comment by SleepingSnakezzz** [comment]
@Drvx Please retest on the latest Citra Nightly build.

**Comment by Drvx** [comment]
Just tested with 1883 and newer, all working now.
