### ISSUE TITLE
Pokemon Ultra moon crashes when using z move

### ISSUE THREAD

**Issue by lioids** [citra-emu/citra#5625]
Hello, I've seen that someone report a bug like this on Pokemon sun long time ago, but this is happening again on pokemon ultra moon. it happened when professor kukui shows how to use z moves, then the game crashes, after that, every moment that i use z move the game crashes too. I noticed that the screen is freeze but the game it's still working, i can hear the steps if I'm moving, but i can't see anything. This bug stops working only if i desactivate the battle animations, but i think that desactivating it ruins the game experice
I'm playing on Citra nightly, the last version. Thanks so much

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for the developers, not a support forum.
Please ask for support in the Citra discord server: https://discord.gg/FAXfZV9
Or on the online forums: https://community.citra-emu.org/
