### ISSUE TITLE
Luigis Mansion 2

### ISSUE THREAD

**Issue by Dexter-1979** [citra-emu/citra#5628]
Graphical glitches of shadows on grids and rods (for example the elevator grid) in the attached video.

[Luigis_Mansion_2_with_vvctre_40.0.4.zip](https://github.com/citra-emu/citra/files/5642348/Luigis_Mansion_2_with_vvctre_40.0.4.zip)

**Comment by choppymaster** [comment]
That's VVCTRE

**Comment by SachinVin** [comment]
Unofficial builds are not supported!

**Comment by Dexter-1979** [comment]
Yes, but the video is only an example, the glitches are also in citra! Can you please re-open?

**Comment by SachinVin** [comment]
Please upload a log with the official version
This forum topic tells you how to get the log file: https://community.citra-emu.org/t/how-to-upload-the-log-file/296

**Comment by Dexter-1979** [comment]
Ok, thank you!
