### ISSUE TITLE
Performance Issues With Inazuma Eleven 3 games and Endou Mamoru Densetsu

### ISSUE THREAD

**Issue by marksgames** [citra-emu/citra#5639]
When playing those games the emulators suffers of lag on almost every PC, on overworld it almost keeps up, but when playing 3d animations it suffers a lot. Is it possible to fix this?

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for the developers, not a support forum.
Please ask for support in the Citra discord server: https://discord.gg/FAXfZV9
Or on the online forums: https://community.citra-emu.org/
