### ISSUE TITLE
@bunnei @FearlessTobi When I record It flickers Please fix this issue Phone-Realme 7 pro

### ISSUE THREAD

**Issue by snivy21** [citra-emu/citra#5645]
[citra screen record.zip](https://github.com/citra-emu/citra/files/5682966/citra.screen.record.zip)

@bunnei 
 @FearlessTobi 

Please read the FAQ:
https://citra-emu.org/wiki/faq/

THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://community.citra-emu.org/

If the FAQ does not answer your question, please go to:
https://community.citra-emu.org/

====================================================

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of Citra you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

--->

**Comment by FearlessTobi** [comment]
This is not a proper issue report. 
Please join our Discord for support.
