### ISSUE TITLE
HarmoKnight (USA) - Graphical errors

### ISSUE THREAD

**Issue by Shideravan** [citra-emu/citra#5652]
HarmoKnight has a graphical error in right of the screens for most of the scenes (take a look how the screen ends early than it should in the images).
The error happens in Citra Nightly 1659 (and in Citra Canary 1903 too).
The game is running at native resolution with all graphics improvements turned off.
![image](https://user-images.githubusercontent.com/12163923/102933549-31afb200-4481-11eb-89ea-9fe8fe90734d.png)
![image](https://user-images.githubusercontent.com/12163923/102933250-b4843d00-4480-11eb-9ded-2092c1848dee.png)
![image](https://user-images.githubusercontent.com/12163923/102933272-bbab4b00-4480-11eb-8569-db279338951e.png)
![image](https://user-images.githubusercontent.com/12163923/102932787-b13c8180-447f-11eb-95df-6b59c9e1be5e.png)
![image](https://user-images.githubusercontent.com/12163923/102933762-9ff47480-4481-11eb-9217-6614ed27695a.png)
![image](https://user-images.githubusercontent.com/12163923/102932931-05476600-4480-11eb-99d5-fb11affba071.png)

Specs:
Windows 10, GTX 1070, I7-4790

**Comment by Shideravan** [comment]
Also, note that the screenshots in wiki page shows the game without this weird graphic issue, then maybe it's a regression
https://citra-emu.org/game/harmoknight/
![image](https://user-images.githubusercontent.com/12163923/102933840-d4683080-4481-11eb-8e05-de1f332eeadb.png)

**Comment by Shideravan** [comment]
The bug happens in European version too:
![image](https://user-images.githubusercontent.com/12163923/102934087-3fb20280-4482-11eb-8651-48d392b2d6fa.png)

**Comment by vitor-k** [comment]
Please provide a log file.

If you suspect a regression, you can test the version from around the time the screenshots were added (https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1126), or of the single compatibility report (https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1371), though it's also possible the screenshots were just hw captured.
If some of these versions do not display the issue, confirming a regression, you can bisect further to find what PR could be causing it.

**Comment by Shideravan** [comment]
Tested with Citra Nightly 1126. I can now confirm the regression. The following images are tests made with that version.
![image](https://user-images.githubusercontent.com/12163923/103057085-76b90e80-457d-11eb-8e59-99abfe0f4bfa.png)
![image](https://user-images.githubusercontent.com/12163923/103057207-a7994380-457d-11eb-86cc-3355500b1ac9.png)
![image](https://user-images.githubusercontent.com/12163923/103057260-bed83100-457d-11eb-8815-17326fcb47fd.png)


> Please provide a log file.
> 
> If you suspect a regression, you can test the version from around the time the screenshots were added (https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1126), or of the single compatibility report (https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1371), though it's also possible the screenshots were just hw captured.
> If some of these versions do not display the issue, confirming a regression, you can bisect further to find what PR could be causing it.

**Comment by Chocolate2890** [comment]
I'm having this same graphical issue as well, I'm on Nightly 1733. Attached a screenshot and my log file
![citra-qt_44xpeZ4NQm](https://user-images.githubusercontent.com/31338325/142516153-147168d6-c93d-4114-a4cc-edcb93871663.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/7566823/citra_log.txt)

**Comment by DietImposter** [comment]
This issue is still present as of Nightly 1788. 
![image](https://user-images.githubusercontent.com/114704509/193155436-1b76e7c6-556e-4f69-a968-bfa4081a0586.png)
[citra_log (1).txt](https://github.com/citra-emu/citra/files/9679494/citra_log.1.txt)

I tested some different builds to determine when this issue reappeared, and here's what I found:

As Shideravan said, the issue is not present in 1126. I tested 1125 and the same grey bar appeared, so 1126 is the exact build in which the problem was initially fixed. I didn't try them all, but presumably every build between 1126 and 1480 work as intended with no grey bar. Starting with Nightly 1481 the grey bar reappeared and is present in presumably every build since. If we're looking to isolate and fix the issue I think the best place to start is by looking at the changes between 1125 and 1126, and between 1480 and 1481.

**Comment by vitor-k** [comment]
Hey can someone check if #6141 fixes this issue? You can get a build artifact from the CI [here](https://github.com/citra-emu/citra/actions/runs/3160646288) (artifacts are on the bottom of the page, linux-fresh is linux/ubuntu, linux-mingw is windows)

@DietImposter 
I checked the changes on 1126 but there were none that would be pertinent to this issue, so I had a look at the changes from 1481 (the big savestates PR) for the cause for this issue. Looking back the first working nightly should be 1115, so I'm not sure why you had a grey bar with 1125.

**Comment by saladplainzone** [comment]
Testing on Windows, this fixes it, thank you! I can test on Linux (got a steam deck earlier this month) sometime this week if nobody else does
![citra-qt_kOP1er4oPQ](https://user-images.githubusercontent.com/31338325/193358964-bf033afb-7939-493f-bb2a-eae16014c22b.png)
![citra-qt_1UWX3vCdfu](https://user-images.githubusercontent.com/31338325/193358968-3115a57f-35ce-4ec5-a285-806fcc0a8afd.png)

**Comment by DietImposter** [comment]
> Hey can someone check if #6141 fixes this issue? You can get a build artifact from the CI [here](https://github.com/citra-emu/citra/actions/runs/3160646288) (artifacts are on the bottom of the page, linux-fresh is linux/ubuntu, linux-mingw is windows)
> 
> @DietImposter I checked the changes on 1126 but there were none that would be pertinent to this issue, so I had a look at the changes from 1481 (the big savestates PR) for the cause for this issue. Looking back the first working nightly should be 1115, so I'm not sure why you had a grey bar with 1125.

Just tested on Windows as well as Linux on Steam Deck. Both ran perfectly as expected! I think you've figured out the problem! Thanks a lot for your help!
