### ISSUE TITLE
[Bug] Control profiles aren't saving

### ISSUE THREAD

**Issue by Shideravan** [citra-emu/citra#5659]
That simple as in the title: in the most recent version (Nightly 1659/Canary 1903) the control profiles created aren't saving properly.

**Comment by BreadFish64** [comment]
Are you certain Nightly 1659 is the first build with this problem, or is it just the first version where you noticed it? I don't see any changes in that build which would affect controller profiles.

**Comment by Shideravan** [comment]
I didn't tested in versions before it, just with the latest. I'm not sure if this is a regression or just a partially implemented feature.

**Comment by Shideravan** [comment]
Maybe it's a issue in my end. I'm now saving the controls properly, then I'm closing this issue for now. If the problems returns, I re-open again and post more informations.
