### ISSUE TITLE
Appveyor Mega builds don't appear in shared folder

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#566]
Due to the way Mega works, tools using the API need to manually update the contens of shared folders when uploading a file. Our tool doesn't currently support that, so any builds uploaded to our mega account won't appear in the public shared link.

Support for this feature is planned in megatools, but hasn't been released yet: megous/megatools#84

When megatools 2.0 is released we should update to it to make this work.

cc @chinhodado

**Comment by chinhodado** [comment]
More detailed explanation is available [here](https://github.com/megous/megatools/issues/54)

**Comment by yuriks** [comment]
We're now using @archshift's :heart: server to host builds.
