### ISSUE TITLE
Little Battlers eXperience Wars (CTR-U-BDNJ)(J) crashes before reaching the title.

### ISSUE THREAD

**Issue by YoutechA320U** [citra-emu/citra#5679]
Little Battlers eXperience Wars crashes before reaching the title.

https://user-images.githubusercontent.com/42425276/104017437-749cb400-51fb-11eb-8db5-45bc340ad1f9.mp4

Game: Little Battlers eXperience Wars (CTR-U-BDNJ) (J)
OS: Windows 10 Pro 20H2
Processor: AMD Ryzen5 2600 3.40GHz
GPU: NVIDIA GTX 1660 6GB GDDR5
Driver: Version 460.89
OpenGL: Version 4.6
Citra: Version Canary 1928
CPU JIT: [x]
Hardware Renderer: [x]
Hardware Shader: [x]
Hardware Shader, Accurate Multiplication: [x]
Shader JIT: [x]
Shader Disk Cache: [ ]

This is the Full citra log:

    [   0.003272] Config <Info> core/settings.cpp:LogSettings:78: Citra Configuration:
    [   0.003287] Config <Info> core/settings.cpp:operator():75: Core_UseCpuJit: true
    [   0.003295] Config <Info> core/settings.cpp:operator():75: Core_CPUClockPercentage: 200
    [   0.003295] Config <Info> core/settings.cpp:operator():75: Renderer_UseGLES: false
    [   0.003296] Config <Info> core/settings.cpp:operator():75: Renderer_UseHwRenderer: true
    [   0.003297] Config <Info> core/settings.cpp:operator():75: Renderer_UseHwShader: true
    [   0.003297] Config <Info> core/settings.cpp:operator():75: Renderer_SeparableShader: false
    [   0.003298] Config <Info> core/settings.cpp:operator():75: Renderer_ShadersAccurateMul: true
    [   0.003298] Config <Info> core/settings.cpp:operator():75: Renderer_UseShaderJit: true
    [   0.003299] Config <Info> core/settings.cpp:operator():75: Renderer_UseResolutionFactor: 2
    [   0.003299] Config <Info> core/settings.cpp:operator():75: Renderer_FrameLimit: 100
    [   0.003300] Config <Info> core/settings.cpp:operator():75: Renderer_UseFrameLimitAlternate: false
    [   0.003300] Config <Info> core/settings.cpp:operator():75: Renderer_FrameLimitAlternate: 400
    [   0.003301] Config <Info> core/settings.cpp:operator():75: Renderer_VSyncNew: true
    [   0.003301] Config <Info> core/settings.cpp:operator():75: Renderer_PostProcessingShader: none (builtin)
    [   0.003302] Config <Info> core/settings.cpp:operator():75: Renderer_FilterMode: true
    [   0.003302] Config <Info> core/settings.cpp:operator():75: Renderer_TextureFilterName: none
    [   0.003303] Config <Info> core/settings.cpp:operator():75: Stereoscopy_Render3d: 0
    [   0.003303] Config <Info> core/settings.cpp:operator():75: Stereoscopy_Factor3d: 100
    [   0.003304] Config <Info> core/settings.cpp:operator():75: Layout_LayoutOption: 0
    [   0.003304] Config <Info> core/settings.cpp:operator():75: Layout_SwapScreen: false
    [   0.003304] Config <Info> core/settings.cpp:operator():75: Layout_UprightScreen: false
    [   0.003305] Config <Info> core/settings.cpp:operator():75: Utility_DumpTextures: false
    [   0.003306] Config <Info> core/settings.cpp:operator():75: Utility_CustomTextures: false
    [   0.003306] Config <Info> core/settings.cpp:operator():75: Utility_UseDiskShaderCache: false
    [   0.003307] Config <Info> core/settings.cpp:operator():75: Audio_EnableDspLle: false
    [   0.003307] Config <Info> core/settings.cpp:operator():75: Audio_EnableDspLleMultithread: false
    [   0.003307] Config <Info> core/settings.cpp:operator():75: Audio_OutputEngine: auto
    [   0.003308] Config <Info> core/settings.cpp:operator():75: Audio_EnableAudioStretching: true
    [   0.003308] Config <Info> core/settings.cpp:operator():75: Audio_OutputDevice: auto
    [   0.003309] Config <Info> core/settings.cpp:operator():75: Audio_InputDeviceType: 0
    [   0.003309] Config <Info> core/settings.cpp:operator():75: Audio_InputDevice: Default
    [   0.003310] Config <Info> core/settings.cpp:operator():75: Camera_OuterRightName: image
    [   0.003310] Config <Info> core/settings.cpp:operator():75: Camera_OuterRightConfig: C:/Users/YoutechA320U/Pictures/unnamed.png
    [   0.003310] Config <Info> core/settings.cpp:operator():75: Camera_OuterRightFlip: 0
    [   0.003311] Config <Info> core/settings.cpp:operator():75: Camera_InnerName: blank
    [   0.003311] Config <Info> core/settings.cpp:operator():75: Camera_InnerConfig: 
    [   0.003312] Config <Info> core/settings.cpp:operator():75: Camera_InnerFlip: 0
    [   0.003312] Config <Info> core/settings.cpp:operator():75: Camera_OuterLeftName: image
    [   0.003313] Config <Info> core/settings.cpp:operator():75: Camera_OuterLeftConfig: C:/Users/YoutechA320U/Pictures/unnamed.png
    [   0.003314] Config <Info> core/settings.cpp:operator():75: Camera_OuterLeftFlip: 0
    [   0.003314] Config <Info> core/settings.cpp:operator():75: DataStorage_UseVirtualSd: true
    [   0.003315] Config <Info> core/settings.cpp:operator():75: System_IsNew3ds: false
    [   0.003315] Config <Info> core/settings.cpp:operator():75: System_RegionValue: 0
    [   0.003315] Config <Info> core/settings.cpp:operator():75: Debugging_UseGdbstub: false
    [   0.003316] Config <Info> core/settings.cpp:operator():75: Debugging_GdbstubPort: 24689
    [   0.439824] Input <Info> input_common/sdl/sdl_impl.cpp:InitGameController:478: opened joystick 0 as controller
    [   0.439848] Input <Info> input_common/udp/client.cpp:StartCommunication:207: Starting communication with UDP input server on 127.0.0.1:26760
    [   0.945143] Frontend <Info> citra_qt/main.cpp:GMainWindow:196: Citra Version: Canary 1928  | HEAD-625639a
    [   0.945151] Frontend <Info> citra_qt/main.cpp:GMainWindow:199: Host CPU: AMD Ryzen 5 2600 Six-Core Processor            
    [   0.945178] Frontend <Info> citra_qt/main.cpp:GMainWindow:201: Host OS: Windows 10 (10.0)
    [   0.986018] Frontend <Info> citra_qt/main.cpp:CheckForUpdates:825: Update check started
    [   2.233293] Frontend <Info> citra_qt/main.cpp:OnUpdateFound:838: No updates found
    [   2.862600] Frontend <Info> citra_qt/main.cpp:BootGame:1017: Citra starting...
    [   3.004262] Audio.DSP <Info> audio_core/hle/wmf_decoder.cpp:Impl:67: Media Foundation activated
    [   3.005729] Audio.DSP <Info> audio_core/hle/wmf_decoder_utils.cpp:MFDecoderInit:50: Windows(R) Media Foundation found 1 suitable decoder(s)
    [   3.204280] Audio.Sink <Info> audio_core/cubeb_sink.cpp:StateCallback:137: Cubeb Audio Stream Started
    [   3.204299] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:12: Starting RPC server ...
    [   3.204430] RPC_Server <Info> core/rpc/rpc_server.cpp:HandleRequestsLoop:113: Request handler started.
    [   3.204495] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:16: RPC started.
    [   3.212052] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:443: Failed to parse 
    [   3.255727] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:472: Loaded NCCH C:\Users\YoutechA320U\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00010202/content/00000000.app is tainted, application behavior may not be as expected!
    [   3.260361] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:472: Loaded NCCH C:\Users\YoutechA320U\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00014002/content/00000000.app is tainted, application behavior may not be as expected!
    [   3.331298] Common.Filesystem <Error> ./core/file_sys/cia_common.h:GetSignatureSize:36: Tried to read ticket with bad signature 1328901272
    [   3.331303] Service.FS <Error> core/file_sys/title_metadata.cpp:Load:31: Failed to load TMD from file C:\Users\YoutechA320U\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004008c/00008200/content/00000000.tmd!
    [   3.377225] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1208: GL_VERSION: 3.3.0 NVIDIA 460.89
    [   3.377229] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1209: GL_VENDOR: NVIDIA Corporation
    [   3.377230] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1210: GL_RENDERER: GeForce GTX 1660/PCIe/SSE2
    [   3.407691] Loader <Info> core/loader/ncch.cpp:Load:192: Program ID: 00040000000F4000
    [   3.432646] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:141: ExHeader kernel version: 2.33
    [   3.434677] Service.FS <Info> core/file_sys/ncch_container.cpp:LoadSectionExeFS:505: Attempting to load logo from the ExeFS
    [   3.434897] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:SetPreferredRegionCodes:654: Preferred region code set to 0
    [   3.562546] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11
    [   3.567947] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called
    [   3.570278] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetLockHandle:317: (STUBBED) called applet_attributes=0X00000000
    [   3.575629] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:186: (STUBBED) bit_mask=0x0000000F
    [   3.577109] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000006
    [   3.577814] Service.APT <Warning> core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:607: (STUBBED) called, cpu_percent=30, value=1
    [   3.579210] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:296: (STUBBED) app_id=768
    [   3.582238] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:590: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
    [   3.582613] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:590: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
    [   3.585159] Service.FS <Warning> core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:600: (STUBBED) called, version: 0x040205C8
    [   3.586408] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [   3.589614] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [   3.594691] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [   3.595317] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [   3.627947] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:703: called flag=00000000 process=11 thread_id=0
    [   3.639266] Render.OpenGL <Error> video_core/renderer_opengl/gl_rasterizer_cache.cpp:MortonCopy:255: Out of bound texture
    [   3.873574] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:496: Firmware hash: 0xe031661c89e654ee
    [   3.873580] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:500: Structures hash: 0x228655de1258d999
    [   3.873583] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:188: called size=0xC234, prog_mask=0x000000FF, data_mask=0x001100FF
    [   3.874271] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:254: Registered interrupt=2, channel=2, event=event-0019af58
    [   3.874544] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:271: (STUBBED) called
    [   3.874808] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:281: (STUBBED) called mask=0x2000
    [   3.875208] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:257: Application has requested initialization of DSP hardware
    [   3.875392] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
    [   3.877177] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
    [   5.946073] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [   5.946322] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:77: Non-existing file C:\Users\YoutechA320U\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/000f4000/data/00000001/sv1.bin can't be open without mode create.
    [   5.946327] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFile:77: failed to get a handle for file     [Wchar: /sv1.bin]
    [   5.948041] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'ControlArchive': port='fs:USER' cmd_buf={    [0]=0x80d0144,     [1]=0x5,     [2]=0x0,     [3]=0x0,     [4]=0x1,     [5]=0x1,     [6]=0x1a,     [7]=0x0,     [8]=0x1c,     [9]=0x1}
    [   6.041128] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [   6.041271] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:77: Non-existing file C:\Users\YoutechA320U\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/000f4000/data/00000001/sv2.bin can't be open without mode create.
    [   6.041275] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFile:77: failed to get a handle for file     [Wchar: /sv2.bin]
    [   6.041425] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'ControlArchive': port='fs:USER' cmd_buf={    [0]=0x80d0144,     [1]=0x6,     [2]=0x0,     [3]=0x0,     [4]=0x1,     [5]=0x1,     [6]=0x1a,     [7]=0x0,     [8]=0x1c,     [9]=0x1}
    [   9.419892] Service.Y2R <Warning> core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:212: (STUBBED) called
    [   9.669354] Service.Y2R <Warning> core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:212: (STUBBED) called
    [   9.673281] HW.Memory <Error> core/memory.cpp:GetPointer:412: unknown GetPointer @ 0x15d00000 at PC 0x001A07A8

**Comment by MojoJojoDojo** [comment]
You didn't try it on nightly.

**Comment by vitor-k** [comment]
`Core_CPUClockPercentage: 200` please retest with it set to 100%
And, as mentioned above, github issues should be tested on the nightly version. Issues that happen on canary but not on nightly are not valid issues, and should be reported on the corresponding PR.

**Comment by YoutechA320U** [comment]
https://user-images.githubusercontent.com/42425276/104061556-2b208900-523c-11eb-88da-a184086c5893.mp4

Sorry, I got Canary and Nightly wrong. But I have confirmed that it crashes with Nightly as well.

Core_CPUClockPercentage is set to 100.

Full citra log:

    [   0.010789] Config <Info> core/settings.cpp:LogSettings:78: Citra Configuration:
    [   0.010807] Config <Info> core/settings.cpp:operator():75: Core_UseCpuJit: true
    [   0.010813] Config <Info> core/settings.cpp:operator():75: Core_CPUClockPercentage: 100
    [   0.010815] Config <Info> core/settings.cpp:operator():75: Renderer_UseGLES: false
    [   0.010818] Config <Info> core/settings.cpp:operator():75: Renderer_UseHwRenderer: true
    [   0.010824] Config <Info> core/settings.cpp:operator():75: Renderer_UseHwShader: true
    [   0.010837] Config <Info> core/settings.cpp:operator():75: Renderer_SeparableShader: false
    [   0.010839] Config <Info> core/settings.cpp:operator():75: Renderer_ShadersAccurateMul: true
    [   0.010841] Config <Info> core/settings.cpp:operator():75: Renderer_UseShaderJit: true
    [   0.010843] Config <Info> core/settings.cpp:operator():75: Renderer_UseResolutionFactor: 1
    [   0.010845] Config <Info> core/settings.cpp:operator():75: Renderer_FrameLimit: 100
    [   0.010847] Config <Info> core/settings.cpp:operator():75: Renderer_UseFrameLimitAlternate: false
    [   0.010850] Config <Info> core/settings.cpp:operator():75: Renderer_FrameLimitAlternate: 400
    [   0.010852] Config <Info> core/settings.cpp:operator():75: Renderer_VSyncNew: true
    [   0.010854] Config <Info> core/settings.cpp:operator():75: Renderer_PostProcessingShader: none (builtin)
    [   0.010856] Config <Info> core/settings.cpp:operator():75: Renderer_FilterMode: false
    [   0.010858] Config <Info> core/settings.cpp:operator():75: Renderer_TextureFilterName: none
    [   0.010862] Config <Info> core/settings.cpp:operator():75: Stereoscopy_Render3d: 0
    [   0.010864] Config <Info> core/settings.cpp:operator():75: Stereoscopy_Factor3d: 100
    [   0.010866] Config <Info> core/settings.cpp:operator():75: Layout_LayoutOption: 0
    [   0.010869] Config <Info> core/settings.cpp:operator():75: Layout_SwapScreen: false
    [   0.010871] Config <Info> core/settings.cpp:operator():75: Layout_UprightScreen: false
    [   0.010874] Config <Info> core/settings.cpp:operator():75: Utility_DumpTextures: false
    [   0.010876] Config <Info> core/settings.cpp:operator():75: Utility_CustomTextures: false
    [   0.010878] Config <Info> core/settings.cpp:operator():75: Utility_UseDiskShaderCache: false
    [   0.010880] Config <Info> core/settings.cpp:operator():75: Audio_EnableDspLle: false
    [   0.010884] Config <Info> core/settings.cpp:operator():75: Audio_EnableDspLleMultithread: false
    [   0.010886] Config <Info> core/settings.cpp:operator():75: Audio_OutputEngine: auto
    [   0.010888] Config <Info> core/settings.cpp:operator():75: Audio_EnableAudioStretching: true
    [   0.010891] Config <Info> core/settings.cpp:operator():75: Audio_OutputDevice: auto
    [   0.010893] Config <Info> core/settings.cpp:operator():75: Audio_InputDeviceType: 0
    [   0.010895] Config <Info> core/settings.cpp:operator():75: Audio_InputDevice: Default
    [   0.010897] Config <Info> core/settings.cpp:operator():75: Camera_OuterRightName: image
    [   0.010899] Config <Info> core/settings.cpp:operator():75: Camera_OuterRightConfig: C:/Users/YoutechA320U/Pictures/unnamed.png
    [   0.010902] Config <Info> core/settings.cpp:operator():75: Camera_OuterRightFlip: 0
    [   0.010906] Config <Info> core/settings.cpp:operator():75: Camera_InnerName: blank
    [   0.010908] Config <Info> core/settings.cpp:operator():75: Camera_InnerConfig: 
    [   0.010910] Config <Info> core/settings.cpp:operator():75: Camera_InnerFlip: 0
    [   0.010912] Config <Info> core/settings.cpp:operator():75: Camera_OuterLeftName: image
    [   0.010914] Config <Info> core/settings.cpp:operator():75: Camera_OuterLeftConfig: C:/Users/YoutechA320U/Pictures/unnamed.png
    [   0.010916] Config <Info> core/settings.cpp:operator():75: Camera_OuterLeftFlip: 0
    [   0.010919] Config <Info> core/settings.cpp:operator():75: DataStorage_UseVirtualSd: true
    [   0.010921] Config <Info> core/settings.cpp:operator():75: System_IsNew3ds: false
    [   0.010923] Config <Info> core/settings.cpp:operator():75: System_RegionValue: 0
    [   0.010927] Config <Info> core/settings.cpp:operator():75: Debugging_UseGdbstub: false
    [   0.010929] Config <Info> core/settings.cpp:operator():75: Debugging_GdbstubPort: 24689
    [   0.847414] Input <Info> input_common/sdl/sdl_impl.cpp:InitGameController:478: opened joystick 0 as controller
    [   0.847460] Input <Info> input_common/udp/client.cpp:StartCommunication:207: Starting communication with UDP input server on 127.0.0.1:26760
    [   1.568132] Frontend <Info> citra_qt/main.cpp:GMainWindow:190: Citra Version: Nightly 1678  | HEAD-e33677b
    [   1.568142] Frontend <Info> citra_qt/main.cpp:GMainWindow:193: Host CPU: AMD Ryzen 5 2600 Six-Core Processor            
    [   1.568187] Frontend <Info> citra_qt/main.cpp:GMainWindow:195: Host OS: Windows 10 (10.0)
    [   1.635892] Frontend <Info> citra_qt/main.cpp:CheckForUpdates:817: Update check started
    [   2.463185] Frontend <Info> citra_qt/main.cpp:OnUpdateFound:830: No updates found
    [  31.191465] Frontend <Info> citra_qt/main.cpp:BootGame:1009: Citra starting...
    [  31.444065] Audio.DSP <Info> audio_core/hle/wmf_decoder.cpp:Impl:67: Media Foundation activated
    [  31.446089] Audio.DSP <Info> audio_core/hle/wmf_decoder_utils.cpp:MFDecoderInit:50: Windows(R) Media Foundation found 1 suitable decoder(s)
    [  31.678659] Audio.Sink <Info> audio_core/cubeb_sink.cpp:StateCallback:137: Cubeb Audio Stream Started
    [  31.678690] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:12: Starting RPC server ...
    [  31.678823] RPC_Server <Info> core/rpc/rpc_server.cpp:HandleRequestsLoop:113: Request handler started.
    [  31.678874] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:16: RPC started.
    [  31.720711] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:443: Failed to parse 
    [  32.204868] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:472: Loaded NCCH C:\Users\YoutechA320U\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00010202/content/00000000.app is tainted, application behavior may not be as expected!
    [  32.267729] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:472: Loaded NCCH C:\Users\YoutechA320U\AppData\Roaming/Citra/nand/00000000000000000000000000000000/title/0004009b/00014002/content/00000000.app is tainted, application behavior may not be as expected!
    [  33.162358] Common.Filesystem <Error> ./core/file_sys/cia_common.h:GetSignatureSize:36: Tried to read ticket with bad signature 1328901272
    [  33.162373] Service.FS <Error> core/file_sys/title_metadata.cpp:Load:31: Failed to load TMD from file C:\Users\YoutechA320U\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004008c/00008200/content/00000000.tmd!
    [  33.231319] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1208: GL_VERSION: 3.3.0 NVIDIA 460.89
    [  33.231330] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1209: GL_VENDOR: NVIDIA Corporation
    [  33.231336] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1210: GL_RENDERER: GeForce GTX 1660/PCIe/SSE2
    [  33.268093] Loader <Info> core/loader/ncch.cpp:Load:192: Program ID: 00040000000F4000
    [  33.294032] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:141: ExHeader kernel version: 2.33
    [  33.296654] Service.FS <Info> core/file_sys/ncch_container.cpp:LoadSectionExeFS:505: Attempting to load logo from the ExeFS
    [  33.297042] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:SetPreferredRegionCodes:654: Preferred region code set to 0
    [  33.701622] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11
    [  33.735100] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called
    [  33.744694] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetLockHandle:317: (STUBBED) called applet_attributes=0X00000000
    [  33.765301] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:187: (STUBBED) bit_mask=0x0000000F
    [  33.769630] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:75: (STUBBED) bit_mask=0x00000006
    [  33.772505] Service.APT <Warning> core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:611: (STUBBED) called, cpu_percent=30, value=1
    [  33.778130] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:296: (STUBBED) app_id=768
    [  33.790705] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:594: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
    [  33.792338] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:594: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
    [  33.802484] Service.FS <Warning> core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:602: (STUBBED) called, version: 0x040205C8
    [  33.807508] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [  33.820938] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [  33.835717] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [  33.837490] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [  33.957502] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:703: called flag=00000000 process=11 thread_id=0
    [  33.999076] Render.OpenGL <Error> video_core/renderer_opengl/gl_rasterizer_cache.cpp:MortonCopy:255: Out of bound texture
    [  34.863770] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:496: Firmware hash: 0xe031661c89e654ee
    [  34.863785] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:500: Structures hash: 0x228655de1258d999
    [  34.863791] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:188: called size=0xC234, prog_mask=0x000000FF, data_mask=0x001100FF
    [  34.866746] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:254: Registered interrupt=2, channel=2, event=event-0019af58
    [  34.867937] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:271: (STUBBED) called
    [  34.869151] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:281: (STUBBED) called mask=0x2000
    [  34.893252] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:257: Application has requested initialization of DSP hardware
    [  34.894156] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
    [  34.902042] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
    [  38.383153] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [  38.383370] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:77: Non-existing file C:\Users\YoutechA320U\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/000f4000/data/00000001/sv1.bin can't be open without mode create.
    [  38.383385] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFile:77: failed to get a handle for file     [Wchar: /sv1.bin]
    [  38.389643] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'ControlArchive': port='fs:USER' cmd_buf={    [0]=0x80d0144,     [1]=0x5,     [2]=0x0,     [3]=0x0,     [4]=0x1,     [5]=0x1,     [6]=0x1a,     [7]=0x0,     [8]=0x1c,     [9]=0x1}
    [  38.464616] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
    [  38.464800] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:77: Non-existing file C:\Users\YoutechA320U\AppData\Roaming/Citra/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/000f4000/data/00000001/sv2.bin can't be open without mode create.
    [  38.464815] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFile:77: failed to get a handle for file     [Wchar: /sv2.bin]
    [  38.465364] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'ControlArchive': port='fs:USER' cmd_buf={    [0]=0x80d0144,     [1]=0x6,     [2]=0x0,     [3]=0x0,     [4]=0x1,     [5]=0x1,     [6]=0x1a,     [7]=0x0,     [8]=0x1c,     [9]=0x1}
    [  44.301178] Service.Y2R <Warning> core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:214: (STUBBED) called
    [  44.995758] Service.Y2R <Warning> core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:214: (STUBBED) called
    [  45.008352] HW.Memory <Error> core/memory.cpp:GetPointer:412: unknown GetPointer @ 0x15d00000 at PC 0x001A07A8

Game: Little Battlers eXperience Wars (CTR-U-BDNJ) (J)
OS: Windows 10 Pro 20H2
Processor: AMD Ryzen5 2600 3.40GHz
GPU: NVIDIA GTX 1660 6GB GDDR5
Driver: Version 460.89
OpenGL: Version 4.6
Citra: Version Nightly 1678

**Comment by Chaitanya41** [comment]
Danball senki wars working on this emulator

Here's the link:https://stfly.io/xCPwk0H

**Comment by benderscruffy** [comment]
Has this been fixed ???
Please update

**Comment by YoutechA320U** [comment]
Thank you! Started up fine.

https://github.com/citra-emu/citra/assets/42425276/5fe72943-c611-4341-9093-62c92c253ac7
Full citra log:
[citra_log.txt](https://github.com/citra-emu/citra/files/12454750/citra_log.txt)

Game: Little Battlers eXperience Wars (CTR-U-BDNJ) (J)
OS: Windows 11 Pro 22H2
Processor: AMD Ryzen5 2600 3.40GHz
GPU: NVIDIA GTX 1660 6GB GDDR5
Driver: Version 531.79
OpenGL: Version 4.6
Citra: Version nightly 1980
