### ISSUE TITLE
[Feature Request] Make a Release

### ISSUE THREAD

**Issue by kawaiiamber** [citra-emu/citra#5681]
Distros generally won't package software unless there is a release. Nightly builds are updated too frequently and not generally considered stable enough to package. Having flatpak as the only stable way to use citra is unfortunate.

**Comment by BreadFish64** [comment]
We currently do not plan to make stable releases of Citra. Closing as this topic is sufficiently covered in other issues such as #4555, #2665

**Comment by kawaiiamber** [comment]
appimage and flathub are not the same as a release but ok. Ill take this as a "wont fix"
