### ISSUE TITLE
Birthday set

### ISSUE THREAD

**Issue by Slexer** [citra-emu/citra#5684]
It would be nice to have the option to set your birthday because many games provide special items just at your set birthday.

**Comment by adityaruplaha** [comment]
If I recall correctly, there was an option in Configure > System?

**Comment by Slexer** [comment]
> If I recall correctly, there was an option in Configure > System?

Yes. But not in the android version. I would like to see the option in the android version. :)

**Comment by jakedowns** [comment]
Added an Issue in the Android-specific repo:
https://github.com/citra-emu/citra-android/issues/251

I'll look into implementing this :)
