### ISSUE TITLE
OpenGL 3.0/ES supoport for the Raspberrfy pi 4

### ISSUE THREAD

**Issue by coreybruce** [citra-emu/citra#5704]
Hi I am just wondering if you could add support for OpenGL 3/ES for the Raspberry pi as it would really be awesome to be able to play the games on my pi, the emulator itself runs but I of course can't run the games because it requires OpenGL 3.3 and I only have OpenGL 3 ES

**Comment by xperia64** [comment]
https://github.com/citra-emu/citra-android already contains a GLES 3.2 renderer, which we are in the process of merging into this repository.

That said, the Raspberry Pi 4 is too weak to run Citra well.

**Comment by coreybruce** [comment]
Oh ok that's cool so it will have support for GLES 3.2 and will be merging sometime soon? 

I will have to test it out to see if it can run it well, will be cool anyways even if I have to run it on a smaller windows that is fine.
