### ISSUE TITLE
i can't run mario and luigi dream tream it says fatal error

### ISSUE THREAD

**Issue by AgRocks114** [citra-emu/citra#5708]
Yeah after years woth of wait my game finally downloaded when i tried to run it it said cannot run the game game fatal error
[citra_log.txt](https://github.com/citra-emu/citra/files/5899438/citra_log.txt)
this is the log according to the instructions pls help

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord or our forums for support requests.

**Comment by AgRocks114** [comment]
> This is an issue tracker for developers and not a support forum.
> Please use our Discord or our forums for support requests.

But this is a issue i am encountering thats why i decided to post here
