### ISSUE TITLE
Custom textures break MM3D in canary releases after 1928

### ISSUE THREAD

**Issue by Nerrel** [citra-emu/citra#5715]
Enabling custom textures in MM3D causes major graphical glitches and hangs when loading new areas; the emulator freezes for me when exiting an area either through a doorway or when using the song of soaring.  Numerous users have reported similar issues on Discord, so I can confirm that it's not just my system. 

The issue seems to have started with canary 1932 and is present in the most current releases.  Rolling back to canary 1928 gets rid of the issues.  

The texture pack I'm using while experiencing the issue is here:  https://drive.google.com/file/d/1sCDH7w9pawZX6U3JxOZvuRb_d0fFpDvO/view?usp=sharing

[citra_log.txt](https://github.com/citra-emu/citra/files/5946300/citra_log.txt)
![20210208131352_1](https://user-images.githubusercontent.com/29036408/107271520-fc036000-6a11-11eb-8b42-bfbdd675dcbe.jpg)

**Comment by vitor-k** [comment]
Please test the issue on the Nightly releases.
If an issue is only present canary, you should leave a comment on the relevant PR instead (in this case likely #5710)

**Comment by Nerrel** [comment]
The problems are not there in the latest nightly build, just canary.  I'll comment there, thanks.... do you want me to close this issue?
