### ISSUE TITLE
Sega 3D Classics crashes when New 3ds mode is enabled

### ISSUE THREAD

**Issue by suppaflie** [citra-emu/citra#5716]
Ever since Citra Nightly Build 1544 the Sega 3D Classics games encounter a Fatal Error a few seconds into each game. I have tested both .3ds and .CIA files to confirm this on games Altered Beast, Sonic 1, Streets of Rage 1, Streets of Rage 2. These are individual dumps and not the Sega Classics Collections 1 and 2 which to my knowledge are not currently working. I'm including the log and screenshot from Streets of Rage 2. They seem to run fine more or less on build 1543 but any build after including the newest 1689 encounter the error.
[citra_log.txt](https://github.com/citra-emu/citra/files/5949079/citra_log.txt)
![Screenshot (93)](https://user-images.githubusercontent.com/42449330/107319835-d2235b00-6a5c-11eb-8b6f-c9aac95ae047.png)

**Comment by legend800** [comment]
Try with new 3ds turned off. Fixes SOR2 for me. Been that way for over a year

**Comment by suppaflie** [comment]
Thank you tested this out on all the games mentioned above and had no issues.

**Comment by GPUCode** [comment]
Fixed by https://github.com/citra-emu/citra/pull/7159
