### ISSUE TITLE
Certain characters are garbled.

### ISSUE THREAD

**Issue by togetg** [citra-emu/citra#5722]
The Japanese character "ん" is garbled in many games.
![Rhythm Paradise](https://user-images.githubusercontent.com/18244518/107925426-c9300d80-6fb7-11eb-902e-e2601ac8ff57.png)
![taiko](https://user-images.githubusercontent.com/18244518/107925443-cdf4c180-6fb7-11eb-9a45-443fda4901cb.png)

**Comment by FearlessTobi** [comment]
Could you please provide more information?
Which games show this issue, what is your setup, what settings are you using etc.
Also, your report is missing a log file

**Comment by SleepingSnakezzz** [comment]
Closing due to lack of information provided by OP.
