### ISSUE TITLE
CPU clock speed is not perserved in save state

### ISSUE THREAD

**Issue by legend800** [citra-emu/citra#5724]
When loading a save state, the CPU speed setting is not preserved. Some games like Mario Golf games are only playable with 50% cpu speed but when loading a state, the game acts as the cpu=100%. If I go into settings, I can see the slider at 50% but I have to manually adjust it and close dialog to restore proper game speed.

![2021-02-17 16_15_58-Citra Configuration](https://user-images.githubusercontent.com/20983844/108285185-71221400-713b-11eb-997e-550f1a6ef4b1.png)

**Comment by SachinVin** [comment]
Duplicate of #5361

**Comment by legend800** [comment]
Closing as a dup of #5361
