### ISSUE TITLE
Texture mismatching after a certain threshold when HD custom textures are loaded (Invalid texture cache)

### ISSUE THREAD

**Issue by HenrikoMagnifico** [citra-emu/citra#5728]
====================================================

**Screenshots:**
![Skärmklipp7](https://user-images.githubusercontent.com/11783274/109360703-f1591f80-7887-11eb-8417-5b85b7603b9f.PNG)
![Skärmklipp](https://user-images.githubusercontent.com/11783274/109360706-f28a4c80-7887-11eb-8092-9dc4d27a1170.PNG)
![Skärmklipp2](https://user-images.githubusercontent.com/11783274/109360708-f322e300-7887-11eb-8477-96258fd46c97.PNG)
![Skärmklipp3](https://user-images.githubusercontent.com/11783274/109360711-f322e300-7887-11eb-990b-12beff2d4244.PNG)
![Skärmklipp4](https://user-images.githubusercontent.com/11783274/109360713-f3bb7980-7887-11eb-9d43-92fdc9aeaed4.PNG)
![Skärmklipp5](https://user-images.githubusercontent.com/11783274/109360715-f4541000-7887-11eb-983c-1d1ed5c84488.PNG)
![Skärmklipp6](https://user-images.githubusercontent.com/11783274/109360718-f4541000-7887-11eb-91b0-20ec65497291.PNG)

Screenshots of regular gameplay are not included since the issues above should be quite self explanatory.

**Version:**
Citra Canary 1953 (09100ec)

**Log file:**
[citra_log.txt](https://github.com/citra-emu/citra/files/6052726/citra_log.txt)

**Custom textures used:**
[Henriko Magnifico's Zelda: Ocarina of Time 3D 4K texture pack (1080p version)](https://www.henrikomagnifico.com/texture-packs)

**Description:**
This has been an issue for some years now and I don't think anyone's provided many details regarding the issue in question before. The bug is texture swapping, or commonly references as "corrupted textures". What happens is that textures at a certain distance from the camera in Zelda: Ocarina of Time 3D and Zelda: Majora's Mask 3D, when custom textures are loaded / reloaded, after a threshold is met (depending on the hardware and areas of the game loaded) start to be replaced with seemingly random textures from other parts of the game. Even on the highest end hardware, this issue can occur within seconds of starting the game- even on the title screen. This happens on all tested region versions of the games. This issue persists until a save state is loaded, or until the game has been restarted in Citra. Most commonly this occurs in dungeons or large structures with lots of interconnected rooms (the Forest Temple in Ocarina of Time 3D is the most reported location this issue occurs in. The hardware doesn't seem to matter in any noticable fashion, the bug seems to occur on both PCs with 8GB and PCs with 32GB of RAM. Or with vastly different GPUs or CPUs. It seems to happen most commonly when reloading large areas, but also in smaller areas like Kokiri Forest in Ocarina of Time 3D (presented in the screenshots above). Reloading an area several times makes the issue worse and worse until eventually almost all textures have been mismatched with something else.

**Workarounds:**
* Disabling custom textures.
* Disabling "Linear Filtering" and any active upscale filters in Citra.

**Hypothesis:**
* During my testing, it seems like the bug stems from a combination of texture filtering going on in Citra alongside custom texture being loaded. It might be related to mip maps as well, since it only affects textures far in the distance at first- where mip maps are normally rendered. But since the mismatched textures remain until they're reloaded, no matter how close to the camera they are, I don't think this is the case. Rather, it's probably just an issue with the mip maps getting mismatched alongside regular albedo textures as well- causing a double mismatch in some instances where approaching a mistmatched texture will switch to another mismatched texture once the mip maps transition between each other.

**Conclusion:**
Neither of these workarounds are ideal and makes using custom textures in Citra quite frustrating for many users. As a texture pack creator, this also makes it difficult for me to truly make my textures justice since users will have to deal with this bug eventually during their playthrough of either games (it's not a matter of _if_ it it will happen, but _when_ it will happen.)

This bug has been verified to appear on various builds of Citra since custom textures were introduced, to the present day most recent version of Citra Canary.

A more permanent fix under-the-hood for this bug inside the code of Citra would be very much appreciated. Thank you!

**Comment by dgdkevs801** [comment]
I have been enjoying your work Henriko, amazing stuff, Im still having issue with linear filtering corrupting the texture pack but I hope someone can find the fix.
