### ISSUE TITLE
Add the ability to seamlessly convert raw .sav file from original 3DS cartridge to Citra compatible save file

### ISSUE THREAD

**Issue by dfv54gdmsnsecfzsmfwhermkml** [citra-emu/citra#5737]
A friend who made this video here and other friends who do the same have told me that there is no way in Citra to use their raw .sav file dumped with SkyDock from their original 3DS cartridge.

https://www.youtube.com/watch?v=IfwWaZpGM58

I also found a thread in citra forum where other users are having similar problems and there was no answer as to what the solution was for this scenario.

https://community.citra-emu.org/t/how-can-i-use-encrypted-sav-files-from-3ds-flash-cards/356893
https://github.com/citra-emu/citra/issues/5082

The idea is to add the possibility to convert the raw .sav file to Citra compatible save file seamlessly.

**Comment by SleepingSnakezzz** [comment]
This request appears to ask for the same thing as this would require https://github.com/citra-emu/citra/issues/5082
So I'll be closing this for now. If I've misunderstood, feel free to reopen this.
