### ISSUE TITLE
Crashing and I have no clue why

### ISSUE THREAD

**Issue by MemoryFound** [citra-emu/citra#5738]
I have no clue but whenever i go to open my save file on Tomadachi Life, Citra crashes after a bit.

**Comment by BreadFish64** [comment]
The issue tracker is not a support forum. Unless you can provide precise technical information regarding an issue, you should not post in it. If you need support, first read the FAQ and then either visit our Discord channel or forum. If you post support questions, generic messages to the developers or vague reports without technical details, they will be closed and locked.

If you believe you have a valid issue report, please attach the log file (See this guide for getting the log file), as well as your hardware and software information if applicable.
