### ISSUE TITLE
Miitopia crash

### ISSUE THREAD

**Issue by Unocr** [citra-emu/citra#5740]
Hello there
I recently downloaded citra on Android ans miitopia, at the beginning everything is alright a few slowdowns but that's all, but when i encounter the 2nd character, at the end of the battle, whatever i do the game crash.
Could somebody explain me, i saw that the game could be finished on the compatibility list.
Thanks
Have a nice day

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
