### ISSUE TITLE
Citra canary does not close completely

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#5749]
The latest version of citra canary does not close when pressing the "X" in the taskbar or with "File->Exit". In the nightly version this does not happen.

OS: Linux Manjaro KDE
Citra version: Citra Canary 1956
Log file: [citra_log.zip](https://github.com/citra-emu/citra/files/6250751/citra_log.zip)

**Comment by SleepingSnakezzz** [comment]
@Amnesia1000 Can you retest if this is still an issue on your end?

**Comment by Amnesia1000** [comment]
No, it's not a problem anymore
