### ISSUE TITLE
Cirta Chrome os support?

### ISSUE THREAD

**Issue by ethanaobrien** [citra-emu/citra#5751]
Android 9 is native to modern chromebooks. I opened the play store and searched "Cirta" But I get this result
![image](https://user-images.githubusercontent.com/77750390/113487802-b4cca500-947f-11eb-90c4-430ddec5f34f.png)
It would be easy to include support for chrome os, as chrome os natively supports arm translations. I have enabled developer mode and downloaded and installed the citra apk before (I didnt keep it that way because of the security issues) and citra downloaded and installed with no problems. My guess is whoever maintains the updating in google play store to add chromebooks allowed or something. It would be simple and easy, please consider making citra available for chrome os.

Note: Chrome os only allows installing apks when you have enabled developer mode, which opens up your computer to many security risks and other things, this is why the only real way to get an app on a chromebook is to add it to the app store.

**Comment by NielsGx** [comment]
Still wo dering why they called their emu Cirta

doesn't make any sense

/s

**Comment by ethanaobrien** [comment]
Sorry for the very late reply, you are correct. I tested the apk and it seemed to run but it didnt, screen just remained blank. Would be a nice feature through

**Comment by GPUCode** [comment]
Fixed by https://github.com/citra-emu/citra/pull/7045
