### ISSUE TITLE
Pause hotkey doesn't work from the emulation window on non Single Window Mode

### ISSUE THREAD

**Issue by JohelEGP** [citra-emu/citra#5752]
Operating System: Arch Linux
CPU: Intel(R) Core™ i3-3220 CPU @ 3.30GHz
GPU: Intel® HD Graphics 2500
Citra Version (found in title bar): master-8e3c7674d
Game: Pokémon X

**Comment by SleepingSnakezzz** [comment]
@JohelEGP I cannot reproduce this anymore. Can you test whether this is still an issue on the latest Citra Nightly builds?

**Comment by JohelEGP** [comment]
My system won't run with the raised OpenGL requirements.
Would testing with https://github.com/GPUCode/citra be OK?
It's
> [82 commits behind](https://github.com/GPUCode/citra/compare/vulkan-2...citra-emu:citra:master) citra-emu:master.

Or I could wait until that's merged,
or ask the upvoter @Henny022.

**Comment by SleepingSnakezzz** [comment]
Ah, in that case it may be better to wait until Vulkan hits Canary to test again. That Vulkan branch may have many other unrelated issues, so it's best to wait for an official release to prevent any inaccuracies with closing or keeping this issue open.

**Comment by JohelEGP** [comment]
It seems to work fine now, thank you.
