### ISSUE TITLE
feat: alternate CPU Clock Speed and accompanying hotkey toggle

### ISSUE THREAD

**Issue by JohelEGP** [citra-emu/citra#5753]
This feature would be very useful when entering parts of games where one requires under/over-clocking for decent gameplay. It should work like the Alternate Emulation Speed:
![1617571164](https://user-images.githubusercontent.com/21071787/113521824-f3d72500-9569-11eb-8502-6a25bdfead4c.png)
![1617571175](https://user-images.githubusercontent.com/21071787/113521825-f3d72500-9569-11eb-87c0-13aae0dea9b9.png)

**Comment by legend800** [comment]
+1 Only way to play Mario Superstars golf game and few others. This, along with a mic toggle hotkey, would be very handy.

**Comment by JohelEGP** [comment]
> and few others

Do they all use the same %, or would you also require per-game configuration?

**Comment by legend800** [comment]
All of mine just need it underclocked to 50% across the board to work right.

**Comment by JohelEGP** [comment]
Developers have expressed disagreement to having this feature: https://discord.com/channels/220740965957107713/343888608442449920/828513438765416467.
