### ISSUE TITLE
Emulation crashes when running Smash Bros. 3DS with update patches

### ISSUE THREAD

**Issue by andrewdev738** [citra-emu/citra#5757]
Testing Smash Bros. 3DS, base game works fine but when a patch is installed, emulation crashes.
<a href="https://drive.google.com/file/d/1rC0J_fxC1iKX7rHoQX1RMz353D0Llj7_/view?usp=sharing">citra_log.txt</a>
Most relevant errors: 'LayeredFS is not enabled' Looking at #5088 only works with mods, and 'Unimplemented function' which can be result of the previous error or Citra missing features.
(From log) Citra Version: Nightly 1697  | HEAD-b3cab3c

**Comment by B3n30** [comment]
Problematic line: [  18.884346] Service.CFG <Error> core/hle/service/cfg/cfg.cpp:GetConfigInfoBlockPointer:339: Config block 0x170000 with flags 2 and size 4 was not found

**Comment by B3n30** [comment]
Since Citra creates this entry in the savegame you have either an outdated savegame or a corrupt one. So not a Citra issue. If you need help on how to reset your savegame go to discord. But I'm closing this issue...

**Comment by andrewdev738** [comment]
Still throwing error after resetting sdmc.
Installing the patch as a mod may fix this.

**Comment by andrewdev738** [comment]
Ok it's fixed now.
Before the mod was compiled with the patch my friend told me that i needed to reset the nand, and that's it, it works now
