### ISSUE TITLE
Is it possible to make the background of the second screen transparent?

### ISSUE THREAD

**Issue by CristobalManga** [citra-emu/citra#5758]
To do this, I made a change in texture, putting said texture in transparent, but in the end it could not reflect what was inside, which is the game, it only remains black.

I wonder if it is a function for the emulator or the game itself.

![image](https://user-images.githubusercontent.com/78171867/113891807-471fc200-977a-11eb-8cbf-0dee55a63e6b.png)

**Comment by SleepingSnakezzz** [comment]
The game likely does not actually render what is behind something that should be hidden. So making the textures of the foreground object transparent would just result in a black image showing up, since nothing behind it is getting rendered. 
Closing this for now.
