### ISSUE TITLE
The performance is incredibly low on all Powervr gpu. The fps ranges from 8 to 15 only. 

### ISSUE THREAD

**Issue by Flipknot123** [citra-emu/citra#5764]
The performance is so slow even on the latest mmj build 20210409. I've tested the emulator on pokemon games like omega ruby and alpha sapphire.  It lags like hell and besides from lagging, I've experienced a graphical bug like black screen only and missing textures if I won't turn on the "fast or Accurate" on accurate mul option in settings. 

Please kindly help me by fixing the performance and graphical bugs.
I know your help is truly appreciated. Thanks in advance.

**Comment by xperia64** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
