### ISSUE TITLE
Texture dumping not working correctly with New Super Mario Bros. 2

### ISSUE THREAD

**Issue by alexkiri** [citra-emu/citra#5765]
When enabling the "Dump textures" option with NSMB2, it works correctly until you start playing a level. At that point, the game slows down to a crawl, and a new texture is dumped every frame. 
![image](https://user-images.githubusercontent.com/6061770/114738288-8046cc00-9d50-11eb-894a-16f6993dae82.png)

This textures seems to contain a tileset, but some tiles (for example - the coins) are different in each textures.
I have attached 2 of these textures:
![tex1_1024x1024_D7A7F9FA30B4E23F_13](https://user-images.githubusercontent.com/6061770/114738423-a10f2180-9d50-11eb-80e6-6bee7d069e22.png)
![tex1_1024x1024_C8581DCD43F30952_13](https://user-images.githubusercontent.com/6061770/114738428-a1a7b800-9d50-11eb-9716-4d99164dfd83.png)

Is there any thing that can be done about this issue?
Let me know if you need additional info.

Citra Canary 1956 Canary Build - 7a60d46
Windows 10 version 20H2 OS Build 19042.928

**Comment by BreadFish64** [comment]
This isn't something we can fix unfortunately. It would be far too difficult to detect when pieces of a texture atlas are updated.
