### ISSUE TITLE
it keeps saying error: Nothing matches org.citra_emu.citra in remote flathub when i try to install it :(

### ISSUE THREAD

**Issue by Manga-Man** [citra-emu/citra#5769]

**Comment by liushuyu** [comment]
Can you elaborate more on what did you do? Like are you trying to install from a terminal (which command did you use?) or from GNOME Software or KDE Discover?

**Comment by liushuyu** [comment]
Also, make sure to follow the guide here prior to installing: https://flatpak.org/setup/

**Comment by Manga-Man** [comment]
> Can you elaborate more on what did you do? Like are you trying to install from a terminal (which command did you use?) or from GNOME Software or KDE Discover?

i typed flatpak install flathub org.citra_emu.citra but it doesn't work

**Comment by Manga-Man** [comment]
> Also, make sure to follow the guide here prior to installing: https://flatpak.org/setup/

and I've already used the setup guide

**Comment by Manga-Man** [comment]
![Screenshot 2021-04-27 11 25 48 AM](https://user-images.githubusercontent.com/72046004/116293297-963e8e80-a74b-11eb-9c75-235d466e6dba.jpg)

**Comment by SleepingSnakezzz** [comment]
@Manga-Man Please check whether this issue is still present.

**Comment by Manga-Man** [comment]
> @Manga-Man Please check whether this issue is still present.

I don't even use that PC anymore 💀

Thanks for asking though!

**Comment by SleepingSnakezzz** [comment]
Ah, then I'll close this issue for now.
