### ISSUE TITLE
citra出现贴图问题，声音流畅度问题和画面流畅度问题

### ISSUE THREAD

**Issue by hhhxfdf** [citra-emu/citra#5771]
![Screenshot_20210425_125726](https://user-images.githubusercontent.com/83153027/115981514-f2c47100-a5c6-11eb-91f0-bf598a8cce9e.jpg)
怎么解决呀！

**Comment by BreadFish64** [comment]
This is an issue tracker for developers, not for user support. Please use the forums or discord server for support.
