### ISSUE TITLE
Shin Megami Tensei IV (Shader Bug \ Unsupported Texture Alpha)

### ISSUE THREAD

**Issue by KrisanThyme** [citra-emu/citra#5775]
**Game**: _Shin Megami Tensei IV_
**Citra Build**: 9ff9727

This seems to be an issue that goes back a long way now, I'd say it's always been a bug throughout Cita's lifetime thus far. Essentially what is _suppose_ to happen in this game, is when you use certain skills (most actually) and they defeat an enemy in the game, the enemy sprites have an effect overlaid onto them and the sprite will then be spliced in some way. (Usually cut in half, but sometimes it's as simple as an icy\electric\fiery effect over the sprite and then a fadeout.)

However in Citra it seems as though this shader either isn't being compiled correctly, or something regarding the finalized texture it tries to render isn't being supported correctly. The reason is, the entire alpha layer of the produced texture seems like it's being dropped.. The result is usually the sprites turning into black boxes, and the shader effect applying to the entire region of that black box. (It's suppose to only apply over the cutout of the sprite itself, and ignore the alpha layer.)

This _also_ affects the games sequel, _Shin Megami Tensei IV: Apocalypse._

![screenshot](https://user-images.githubusercontent.com/13863112/116357253-49e66380-a7ca-11eb-8913-a46af8db6271.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/6389549/citra_log.txt)

![screenshot2](https://user-images.githubusercontent.com/13863112/116359138-700d0300-a7cc-11eb-90f7-00df0f4853c9.png)
[citra_log.txt](https://github.com/citra-emu/citra/files/6389649/citra_log.txt)

Here's one example of how the shader _should_ look when it is correctly applied to a sprite, versus how it currently looks in Citra.
![citra-bug](https://user-images.githubusercontent.com/13863112/116361958-8cf70580-a7cf-11eb-929d-97e2feda6df0.png)
_Left is real hardware, right is Citra._

**Comment by ofsaleem** [comment]
see also https://github.com/citra-emu/citra/issues/2272 (i know you're on that thread @KrisanThyme but i want to connect the issues for posterity / potential eventual de-dup )
