### ISSUE TITLE
citra-nightly: can not compile in Fedora 34

### ISSUE THREAD

**Issue by thesourcehim** [citra-emu/citra#5776]
In file included from /mnt/d/projects/git/citra-nightly/src/./audio_core/dsp_interface.h:13,
                 from /mnt/d/projects/git/citra-nightly/src/audio_core/dsp_interface.cpp:6:
/mnt/d/projects/git/citra-nightly/src/./common/ring_buffer.h:30:35: error: «numeric_limits» is not a member of «std»
   30 |     static_assert(capacity < std::numeric_limits<std::size_t>::max() / 2 / granularity);
      |                                   ^~~~~~~~~~~~~~
/mnt/d/projects/git/citra-nightly/src/./common/ring_buffer.h:30:61: error: expected primary-expression before «>» token
   30 |     static_assert(capacity < std::numeric_limits<std::size_t>::max() / 2 / granularity);
      |                                                             ^
/mnt/d/projects/git/citra-nightly/src/./common/ring_buffer.h:30:64: error: «::max» has not been declared; did you mean «std::max»?
   30 |     static_assert(capacity < std::numeric_limits<std::size_t>::max() / 2 / granularity);
      |                                                                ^~~
      |                                                                std::max

**Comment by thesourcehim** [comment]
Here's another error I don't understand:

/mnt/d/projects/git/citra-nightly/src/core/hle/service/gsp/gsp_gpu.cpp:287:68: error: «screen_id» is not a constant expression
  287 |                                                 framebuffer_config[screen_id].address_left1)),
      |                                                                    ^~~~~~~~~
/mnt/d/projects/git/citra-nightly/src/core/hle/service/gsp/gsp_gpu.cpp:286:62: note: in macro expansion «GPU_REG_INDEX»
  286 |         WriteSingleHWReg(base_address + 4 * static_cast<u32>(GPU_REG_INDEX(
      |                                                              ^~~~~~~~~~~~~

screen_id is a function parameter, why it has to be constexpr to be valid as an array subscript?

**Comment by B3n30** [comment]
Since this looks like an issue with your setup and is not a Citra issue, I will close this. If you need help go to our discord our forum

**Comment by thesourcehim** [comment]
It looks like it's gcc 11 compatibility issue. The second error seems to be because offsetof is compile-time only now and can not accept runtime variables.

**Comment by thesourcehim** [comment]
I made a patch to fix the issue but it looks clunky. Maybe there's more elegant solution. Please check:

[citra_nightly_gcc11_fix.diff.txt](https://github.com/citra-emu/citra/files/6392991/citra_nightly_gcc11_fix.diff.txt)
