### ISSUE TITLE
Link between Worlds: citra hangs in linux when trying to load a save with streetpass activated

### ISSUE THREAD

**Issue by thesourcehim** [citra-emu/citra#5787]
[citra_log.txt](https://github.com/citra-emu/citra/files/6509548/citra_log.txt)

If I try to load a saved game that has streetpass activated, citra hangs, I have to kill it. Messages about faulty read32 keep multiplying in log file, the file grows to many megabytes.
This does not happen when loading the same save in Windows nightly version (version is the same: 1708), the save loads just fine in Windows version.
Command line I use to build citra in linux:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/mnt/d/Games/citra -DENABLE_FFMPEG_AUDIO_DECODER=ON -DENABLE_FFMPEG_VIDEO_DUMPER=ON -DENABLE_QT_TRANSLATION=ON ..
make -j8
make install
```

**Comment by thesourcehim** [comment]
Flatpak version suffers from this too.

**Comment by GPUCode** [comment]
Please use support mediums for this issue, if it still exists
