### ISSUE TITLE
Pokemon Mystery Dungeon: Gates to Infinity's DLC Doesn't Work Properly

### ISSUE THREAD

**Issue by XModxGodX** [citra-emu/citra#5789]
When installing the DLC the added music doesn't play on the main menu like it's supposed to and going into DLC dungeons makes you turn around to the crossroad again essentially making the point of having the DLC completely pointless.

**Comment by Gameskiller01** [comment]
Did you ever find a fix for this? I'm having the same issue.

**Comment by benderscruffy** [comment]
Has this been fixed ??
Please update

**Comment by XModxGodX** [comment]
Just tested on Citra Nightly 1910 still seems to be an issue.

**Comment by Dragios** [comment]
The DLC music is playing properly on my side. Did you select the correct system region on Citra's setting?
It won't work if the game region does not match system region. Else, just use _Auto-select_
![image](https://github.com/citra-emu/citra/assets/18496868/9798a31a-c832-4dd1-9dfd-2542e03d795b)

Did not test DLC dungeon, as I did not progress the game far enough.

**Comment by FearlessTobi** [comment]
Okay, since the user did not provide a log file and it is fixed on your side, I will close this for now.

**Comment by XModxGodX** [comment]
Turns out gm9 dumped it wrong even on the latest version and I was using a workaround that zeroed out certain files ThreeSD was the only way I could get it to work either way turns out it's not a citra problem anyways.

**Comment by Dragios** [comment]
> Turns out gm9 dumped it wrong even on the latest version and I was using a workaround that zeroed out certain files ThreeSD was the only way I could get it to work either way turns out it's not a citra problem anyways.

You may report this issue and your findings on [GodMode9](https://github.com/d0k3/GodMode9/issues) repository instead
