### ISSUE TITLE
problem: Minecraft New 3DS Edition: controls do not work: Citra Nightly 1708

### ISSUE THREAD

**Issue by Saturn345** [citra-emu/citra#5791]
Some controls do not work in Minecraft New 3DS Edition

**Comment by Saturn345** [comment]
i had to use a diffrent controller:)

**Comment by Saturn345** [comment]
it worked for 3 seconds but then that happened again

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for the developers, not a support forum.
For help with your issue, please join the Citra discord server: https://discord.gg/FAXfZV9
Or open a support topic for your issue on the Citra forums: https://community.citra-emu.org/
