### ISSUE TITLE
[Feature Request] Being able to switch screen layout with a hotkey

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#5793]
I want to be able to change the screen layout with a keyboard- or controller hotkey,for example when I want to switch if the first screen or second screen or both is shown.

**Comment by poudink** [comment]
Use F9.

**Comment by Toadfield** [comment]
What odes that do?
I am not on my pc right now,so I can't test.

**Comment by GPUCode** [comment]
A keyboard hotkey exists for this purpose, feel free to open a separate issue for gamepad
