### ISSUE TITLE
[ANDROID] Unable to Access SD Card on Android 11+

### ISSUE THREAD

**Issue by djyoungcity** [citra-emu/citra#5795]
Due to system changes with Android 11, Citra on Android is unable to access files/roms on an external SD Card.  Please update the file browser to access files on the external storage.

Currently using the latest Citra Version on Google Play store.

**Comment by djyoungcity** [comment]
Raised Issue on wrong repo

**Comment by Gamemulatorer** [comment]
This will be fix via https://github.com/citra-emu/citra/pull/6313
