### ISSUE TITLE
game installed but not showing in the list

### ISSUE THREAD

**Issue by anuragoasis** [citra-emu/citra#5796]
I have just downloaded decrypted roms of 'Soul of Darkness' game from source: [https://www.reddit.com/r/3dspiracy/comments/kmfmmg/soul_of_darkness_gameloft_dsiware_classic/] 

USA version is decrypted. 

but the Latest Emulator on Android and Windows installed it successfully but didn't show on the list to play. 
Neither the unofficial MMJ version was able to show that. 

I'd Used Latest version of emulator on both platforms. 
Without seeing in the list how can I play??

So, please fix that issue, I really wanted to play Soul of Darkness.

**Comment by Schplee** [comment]
Piracy is not supported. Please dump your games and ask for support in the appropriate discord channel.

**Comment by anuragoasis** [comment]
Hiw about if I give you google drive link?
