### ISSUE TITLE
Hatsume Miku Project Mirai DX Crash

### ISSUE THREAD

**Issue by ualaa1** [citra-emu/citra#5809]
US Version
Nightly 1715
[citra_log.txt](https://github.com/citra-emu/citra/files/6773870/citra_log.txt)

**Comment by Schplee** [comment]
We do not support piracy. Please dump your games if you want us to provide assistance.

Additionally, this is an issue tracker and not a support forum. Please ask for support on our Discord server.

**Comment by ethanaobrien** [comment]
Additionally, I own the game and have dumped it from my ds and have had no such problems
