### ISSUE TITLE
Custom Texture loading is broken with Texture Filtering

### ISSUE THREAD

**Issue by RocketRobz** [citra-emu/citra#5819]
Possible duplicate of https://github.com/citra-emu/citra/issues/5761
EDIT: Turned out to be unrelated, and the issue info has been updated below.

**Citra Version**
1769 (Nightly), 1979 (Canary)

**Description**
Textures seem to be missing and/or loaded above different textures.

**Screenshots**
Canary 1903:
![Canary 1903 custom texture glitchless](https://user-images.githubusercontent.com/16110127/125736576-81a56346-b74c-4d9d-9d1f-4d8b8cb8d105.png)

Nightly 1769/Canary 1979:
![Canary 1979 custom texture glitch](https://user-images.githubusercontent.com/16110127/125736593-31342b35-7c17-4fa7-bc3b-dd63eb3d81e9.png)

**Log file**
[citra_log.txt](https://github.com/citra-emu/citra/files/6820728/citra_log.txt)

**Steps to reproduce**
1. Enable `Custom Texture` in the Emulation Settings.
2. Set `Texture Filtering` to a setting that isn't `none`.
3. Add custom textures, if you don't already have some.
4. Try a game, and go to an area which will load the custom textures.

**Workarounds**
* Disable Texture Filtering
* Revert back to Nightly 1651 (Untested) or Canary 1903

**Note**
* Enabling `Accurate Multiplication` does not fix this.

**Comment by vitor-k** [comment]
Try setting the texture filter to `none`, I suspect it's because of the known issue of texture filters not working properly with custom textures.
Besides that it should be noted that issues reported here on github should base their findings on the Nightly versions, as the Canary release channel is inherently unstable.

**Comment by RocketRobz** [comment]
> Try setting the texture filter to `none`, I suspect it's because of the known issue of texture filters not working properly with custom textures.
> Besides that it should be noted that issues reported here on github should base their findings on the Nightly versions, as the Canary release channel is inherently unstable.

Setting the texture filter to `none` has indeed fixed it! Thank you!
