### ISSUE TITLE
SMT IV: Apocalypse - Freeze when engaging battles

### ISSUE THREAD

**Issue by lorenzopeda** [citra-emu/citra#5820]
After the last update, everytime I try to fight an enemy, the emulator stop working and I have to force close it.
Here's a screenshot.

![smt iv apo](https://user-images.githubusercontent.com/15290498/126063045-77fab265-2d24-403d-8d6c-2f12d7673be7.png)

**Comment by SachinVin** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
