### ISSUE TITLE
Teddy Together doesn't work (won't continue after a certain point)

### ISSUE THREAD

**Issue by Ohnface** [citra-emu/citra#5821]
**Issue / steps to reproduce**
Start the game → main menu loads up → press the only available button → next screen loads (like in the screenshot) → nothing happens from then on. Yet, the framerate will still be updated, so the game seems to be running.
This problem persists through different game versions, different Citra versions AND different PC builds as well as on Android.

**System Information**
Operating System: Windows 10 Home
CPU: Intel Core i7-4790 3,6 GHz
GPU: NVIDIA GeForce GTX 970
Citra Version: Nightly 1628, 1714 / Canary 1858
Citra Log: [citra_log.txt](https://github.com/citra-emu/citra/files/6842844/citra_log.txt)
Game: Teddy Together (Kuma Tomo)
Screenshot of Issue: ![Problem](https://user-images.githubusercontent.com/87666782/126202507-b8619213-c571-4d42-b747-8c9b619a68d8.jpg)

**Comment by Ohnface** [comment]
Just a litte push.

**Comment by Ohnface** [comment]
.

**Comment by banana429** [comment]
im having the same problem. just today i tried to play it because it wasnt released in my region and i couldnt get past it.

**Comment by benderscruffy** [comment]
using the latest nightly it is still an issue

**Comment by SachinVin** [comment]
After some debugging, The game seems busy loop over `SourceStatus::status[0].buffer_position`. 
Citra sets this value to 130560, while the game expects 130632, this is off by 1 frame.
Need to do some more work on figuring out why citra is off by 1 frame.
