### ISSUE TITLE
Samus Returns top screen no controller input

### ISSUE THREAD

**Issue by KiwiZelda** [citra-emu/citra#5830]
Hi guys,

Forgive me if you think this counts as a support issue rather than a technical issue. I honestly don't know if it's a technical issue with the software or not. The only reason I think it might be, is that I would presume Citra should make a game controllable with its default settings, and mine is not.

I am playing on Switch CFW with Retroarch.
When I start up Samus Returns, I get past the opening cutscenes and get to the part where I am meant to take control of the character. However none of my button inputs are working on the Top screen (of the two dual screens). The only button that registers is R, which toggles the type of gun the character holds.

The buttons and thumbstick all work fine for navigating through the menus in the Bottom screen.

I can still use the L3 button to swap screen layouts anytime. One version of the layouts has the top screen only and no bottom screen. This places the crosshair-cursor on the top screen when I'm in this mode. Even in this layout however, where I'm clearly interacting with the top screen, only the R (shoulder) and L3 buttons have any effect.

I'm pasting some core options and game options dumps for you. Many thanks in advance!

Dumps:

**retroarch-core-options.cfg:**

mame2000-show_gameinfo = "disabled"
mame2000-skip_disclaimer = "enabled"
mesen_aspect_ratio = "Auto"
mesen_audio_sample_rate = "96000"
mesen_controllerturbospeed = "Fast"
mesen_disable_noise_mode_flag = "disabled"
mesen_fake_stereo = "disabled"
mesen_fdsautoinsertdisk = "disabled"
mesen_fdsfastforwardload = "disabled"
mesen_hdpacks = "enabled"
mesen_mute_triangle_ultrasonic = "enabled"
mesen_nospritelimit = "disabled"
mesen_ntsc_filter = "Disabled"
mesen_overclock = "None"
mesen_overclock_type = "Before NMI (Recommended)"
mesen_overscan_down = "None"
mesen_overscan_left = "None"
mesen_overscan_right = "None"
mesen_overscan_up = "None"
mesen_palette = "Default"
mesen_ramstate = "All 0s (Default)"
mesen_reduce_dmc_popping = "enabled"
mesen_region = "Auto"
mesen_screenrotation = "None"
mesen_shift_buttons_clockwise = "disabled"
mesen_swap_duty_cycle = "disabled"
mgba_allow_opposing_directions = "no"
mgba_color_correction = "OFF"
mgba_frameskip = "0"
mgba_gb_model = "Autodetect"
mgba_idle_optimization = "Remove Known"
mgba_interframe_blending = "OFF"
mgba_sgb_borders = "ON"
mgba_skip_bios = "OFF"
mgba_solar_sensor_level = "0"
mgba_use_bios = "ON"
mupen64plus-169screensize = "960x540"
mupen64plus-43screensize = "640x480"
mupen64plus-alt-map = "False"
mupen64plus-aspect = "4:3"
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "OnePiece"
mupen64plus-BilinearMode = "standard"
mupen64plus-CorrectTexrectCoords = "Off"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-d-cbutton = "C3"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHWLighting = "False"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableN64DepthCompare = "False"
mupen64plus-EnableNativeResTexrects = "Disabled"
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "True"
mupen64plus-ForceDisableExtraMem = "False"
mupen64plus-FrameDuping = "True"
mupen64plus-Framerate = "Original"
mupen64plus-FXAA = "0"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "4000"
mupen64plus-MultiSampling = "0"
mupen64plus-NoiseEmulation = "True"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "memory"
mupen64plus-pak2 = "none"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-r-cbutton = "C1"
mupen64plus-rdp-plugin = "gliden64"
mupen64plus-rsp-plugin = "hle"
mupen64plus-txCacheCompression = "True"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "Auto"
nestopia_aspect = "auto"
nestopia_blargg_ntsc_filter = "disabled"
nestopia_button_shift = "disabled"
nestopia_favored_system = "auto"
nestopia_fds_auto_insert = "enabled"
nestopia_genie_distortion = "disabled"
nestopia_nospritelimit = "disabled"
nestopia_overclock = "1x"
nestopia_overscan_h = "disabled"
nestopia_overscan_v = "enabled"
nestopia_palette = "cxa2025as"
nestopia_ram_power_state = "0x00"
nestopia_select_adapter = "auto"
nestopia_turbo_pulse = "2"
quicknes_aspect_ratio_par = "PAR"
quicknes_audio_eq = "default"
quicknes_audio_nonlinear = "nonlinear"
quicknes_no_sprite_limit = "disabled"
quicknes_palette = "default"
quicknes_turbo_enable = "none"
quicknes_turbo_pulse_width = "3"
quicknes_up_down_allowed = "disabled"
quicknes_use_overscan_h = "enabled"
quicknes_use_overscan_v = "disabled"

**Citra.opt:**

citra_3dfactor = "0"
citra_3dmode = "disabled"
citra_analog_function = "C-Stick and Touchscreen Pointer"
citra_deadzone = "15"
citra_is_new_3ds = "Old 3DS"
citra_layout_option = "Default Top-Bottom Screen"
citra_region_value = "Auto"
citra_resolution_factor = "1x (Native)"
citra_swap_screen = "Top"
citra_use_acc_geo_shaders = "disabled"
citra_use_acc_mul = "disabled"
citra_use_cpu_jit = "enabled"
citra_use_gdbstub = "disabled"
citra_use_hw_renderer = "enabled"
citra_use_hw_shaders = "enabled"
citra_use_libretro_save_path = "LibRetro Default"
citra_use_shader_disk_cache = "enabled"
citra_use_shader_jit = "enabled"
citra_use_virtual_sd = "enabled"
citra_vrmode = "disabled"

**Metroid - Samus Returns.opt:**

citra_3dfactor = "0"
citra_3dmode = "disabled"
citra_analog_function = "C-Stick and Touchscreen Pointer"
citra_deadzone = "15"
citra_is_new_3ds = "Old 3DS"
citra_layout_option = "Default Top-Bottom Screen"
citra_region_value = "Auto"
citra_resolution_factor = "1x (Native)"
citra_swap_screen = "Top"
citra_use_acc_geo_shaders = "disabled"
citra_use_acc_mul = "disabled"
citra_use_cpu_jit = "enabled"
citra_use_gdbstub = "disabled"
citra_use_hw_renderer = "enabled"
citra_use_hw_shaders = "enabled"
citra_use_libretro_save_path = "LibRetro Default"
citra_use_shader_disk_cache = "enabled"
citra_use_shader_jit = "enabled"
citra_use_virtual_sd = "enabled"
citra_vrmode = "disabled"

**Comment by KiwiZelda** [comment]
Update: I tried a different 3DS ROM (Shovel Knight) and it works just fine.
So then I downloaded the USA version of Samus returns (instead of the Euro version) and it has the same issue as the Euro version did.
So, something about this game in particular is not talking to Citra properly, perhaps?

**Comment by Schplee** [comment]
1) Piracy isn't supported
2) The Retroarch version of Citra is not official and not supported by us
3) This isn't a support forum, we'd be happy to assist on the official Citra [discord ](https://discord.gg/FAXfZV9) if you legally dump your games and are using an officially released build.

Closing

**Comment by KiwiZelda** [comment]
Ok fair, thanks
 
 
  On Wed, 11 Aug 2021 at 4:45 AM, ***@***.***> wrote:   


Closed #5830.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
