### ISSUE TITLE
Streetpass Mii Plaza Will not Detect Update 

### ISSUE THREAD

**Issue by AbdyyEee** [citra-emu/citra#5832]
I am putting this as an issue not for help but to inform and so this gets fixed in the future, al though a fix would be helpful.

Streetpass Mii Plaza will not detect any updates, in game it will ask you that an update is required to continue playing the game and due to Citra not being able to connect to Nintendo's severs it is impossible to play the game, and if you select no as the option it will just tell you to return to the home menu. I have checked system settings and it seems like the update is listed there.  I am almost certain that none of the Cia's are corrupted or anything and with ThreeSD the issue still remains.  Seems like a bug with Citra. I have found on Youtube someone playing the game with the latest update installed though.

It will say that it could not be found on the SD card even though the update is installed
![unknown](https://user-images.githubusercontent.com/82438230/129890932-981b200a-8918-4aee-91a7-4515a841645d.png)
It will then ask to redownload
![edsA](https://user-images.githubusercontent.com/82438230/129890479-e43a63d4-a18b-4e6d-8c0c-b8bfddc82676.png)
And if you click yes this would happen
![unknown (3)](https://user-images.githubusercontent.com/82438230/129890518-07b3afb7-0a9a-449f-a02a-b11918d79765.png)
And you can't go any further
![unknown (4)](https://user-images.githubusercontent.com/82438230/129890562-6215dc06-ef10-45bb-a7fc-4820da87c4f6.png)

[citra_log.txt](https://github.com/citra-emu/citra/files/7006870/citra_log.txt)

**Comment by AbdyyEee** [comment]
Never mind I fixed it.

**Comment by catscarlet** [comment]
> Never mind I fixed it.
> 
> To fix it once you have dumped Streetpass Mii Plaza and its Update go to \AppData\Roaming\Citra\sdmc\Nintendo3DS\00000000000000000000000000000000\00000000000000000000000000000000\title\0004000e\00021800\content The Files above depend on region so if the names are a bit different it does not matter Then drag 00000007.app into Citra
> 
> And done it should work now.

Well I made a quite mess and end up here. Seems it's an only way now to play Mii Paid DLCs althrough faild to import my 3DS savefiles.

![b85m-win052-snap](https://user-images.githubusercontent.com/10594035/149906071-2e67af26-eaff-46bb-b910-4b5070383622.png)


Anyway I can play Mii force on big screen now(with dogs and cats crews only).

Thanks @AbdyyEee
