### ISSUE TITLE
Freezing on Pokemon Ruby 

### ISSUE THREAD

**Issue by OMNIVader23** [citra-emu/citra#5857]
Everytime I try to walk into the pokemon center it freezes 
![Screenshot 2021-09-26 165505](https://user-images.githubusercontent.com/91316115/134815128-1091f089-90a2-49fe-822d-fab06dcc2c57.png)

**Comment by LOuroboros** [comment]
Can't confirm.

https://user-images.githubusercontent.com/4485172/135007474-afd7259a-88f0-4359-8b0d-370999691262.mp4

Specs:
**CPU**: i3 2120
**RAM**: 1x4GB, Single Channel.
**GPU**: Gigabyte's NVIDIA GeForce GT 1030 2GB GDDR5, Driver Version 471.68
**OS**: Windows 10 x64
