### ISSUE TITLE
[Feature Request] Implement display or export of game instruction manuals

### ISSUE THREAD

**Issue by Wazhai** [citra-emu/citra#5860]
It would be very useful if Citra could implement some form of displaying the instruction manuals that come included with all/most games on 3DS. Alternatively, the possibility to export that data to a PDF file or something similar could be explored as well.

On a 3DS, manuals can be accessed from the home screen by touching the Manual button when a corresponding game tale is highlighted. Manuals come as part of the game title data, because an online connection is not necessary to acquire them on a real 3DS, which also makes it possible for Citra to parse this data.

This has been asked about in at least on forum post https://community.citra-emu.org/t/any-way-to-view-the-game-manual-for-a-3ds-game-as-in-the-manual-youd-access-on-a-normal-3dss-home-screen/369373

and is also related to https://github.com/citra-emu/citra/issues/4552 (soft crash on attempted opening of 3ds game instruction manual through the game).

**Comment by SinaMegapolis** [comment]
As of latest Citra versions you should be able to view manuals of installed games by installing HOME Menu then using the manual applet

**Comment by FearlessTobi** [comment]
> As of latest Citra versions you should be able to view manuals of installed games by installing HOME Menu then using the manual applet

Correct
