### ISSUE TITLE
Country/region settings (originally in the 3DS System Menu) needed for accuracy in Pokémon main games

### ISSUE THREAD

**Issue by ShadyGuyJose** [citra-emu/citra#5877]
Hi! I've been playing Pokémon Moon on Citra Android, and while it runs fine, I've run into an admittedly minor issue, but it's been bugging me and I believe it would be easy to solve.

Pokémon games use the system's country and city settings to record the origin of a Pokémon. Citra records the country properly, but not the city (it's left blank). In-game, this matters only for Vivillon forms, as far as I'm aware, but anyone worried about Pokémon legitimacy would probably pick up on that quite easily. I've attached PKHeX screenshots showing the location data of a Pokémon caught in my actual 3DS first, then in Citra (Desktop) and Citra (Android) using the exact same save file.

![image](https://user-images.githubusercontent.com/31470147/138562907-f18dc8a9-ca40-41fa-bb10-09487bee9088.png)
(3DS)

![image](https://user-images.githubusercontent.com/31470147/138562931-9da5b984-3870-4ac1-89c7-7d1d9a3ccf62.png)
(Citra Desktop)

![image](https://user-images.githubusercontent.com/31470147/138562985-1322ac89-c5b6-4d22-bd6a-a9221e4df560.png)
(Citra Android)

Citra Desktop had the wrong region, but that's down to settings and I've managed to fix it afterwards. Nevertheless, I've been digging through settings and .ini files and I can't replicate this country/city setting. If this is something that can be solved in some other way (such as importing system files from my 3DS), please point me in the right direction. But, if not, I'd like this to be added, if possible.

I'll be posting this in both the desktop and Android repos, but I'll close one of them if deemed appropriate.

Thanks in advance!

**Comment by vitor-k** [comment]
I investigated this issue a bit and I'm gonna dump the info here for future me or whoever decides to do this:

I suspect the sub region referred here is stored in the config savegame, specifically on [this part (3dbrew)](https://www.3dbrew.org/wiki/Config_Savegame#CountryInfo), which has a state/province code that's currently listed as unknown on Citra (see [here](https://github.com/citra-emu/citra/blob/master/src/core/hle/service/cfg/cfg.cpp#L100))

So the ideal fix would be to implement that and a setting to change the value, with the GUI showing what each value will be.
The thing is, the state/province that's represented by the sub-region code is dependent on the country (a value of 002 could be Tokyo, if the country is Japan, or Washington DC, if the country is the USA), so to do it properly that has to be taken in consideration. (the full list would either need to be reverse engineered from a 3ds or we could maybe use pkhex's [list](https://github.com/kwsch/PKHeX/tree/master/PKHeX.Core/Resources/text/locale3DS/subregions), if there's no license incompatibility or such)

**Comment by ShadyGuyJose** [comment]
> I investigated this issue a bit and I'm gonna dump the info here for future me or whoever decides to do this:
> 
> I suspect the sub region referred here is stored in the config savegame, specifically on [this part (3dbrew)](https://www.3dbrew.org/wiki/Config_Savegame#CountryInfo), which has a state/province code that's currently listed as unknown on Citra (see [here](https://github.com/citra-emu/citra/blob/master/src/core/hle/service/cfg/cfg.cpp#L100))
> 
> So the ideal fix would be to implement that and a setting to change the value, with the GUI showing what each value will be. The thing is, the state/province that's represented by the sub-region code is dependent on the country (a value of 002 could be Tokyo, if the country is Japan, or Washington DC, if the country is the USA), so to do it properly that has to be taken in consideration. (the full list would either need to be reverse engineered from a 3ds or we could maybe use pkhex's [list](https://github.com/kwsch/PKHeX/tree/master/PKHeX.Core/Resources/text/locale3DS/subregions), if there's no license incompatibility or such)

Thank you for taking up this issue, even if not just yet. From your reply, I take it that, while not yet implemented in Citra, this could be worked around by making sure my 3DS is properly set, then dumping and importing a config savegame?
