### ISSUE TITLE
Citra is not recognizing the 'user' folder on macOS

### ISSUE THREAD

**Issue by HenrikoMagnifico** [citra-emu/citra#5878]
It seems like Citra is not recognizing the existence of a 'user' folder in the same directory as citra-qt, which means portable installations aren't possible for Citra on Mac. Changing the location of the citra-qt app does not seem to make a difference. [According to the Citra documentation](https://citra-emu.org/wiki/user-directory/), "on any system, the presence of a directory named user on the same directory of the executable will override the default behavior and Citra will use that instead.", whereas on macOS this isn't the behaviour observed.

In the [Building for macOS section of the Citra wiki](https://citra-emu.org/wiki/building-for-macos/), near the bottom of the page, it's stated that "For portability of the appbundle between machines please refer to this script." The script in question is the [upload.sh](https://github.com/citra-emu/citra/blob/master/.ci/macos/upload.sh) script inside of the citra/.ci/macos/ directory of the Citra github repository. However, it is not specified how to utilize this script to build a portable installation of Citra for macOS.

This has been tested and confirmed on MacOS Monterey on a M1-fitted Macbook Air.

**Comment by willgu903** [comment]
any update on this issue? I added user folder where `citra-qt.app` is located, but it always points to `~/.local/share/citra-emu` instead

can reproduce on the latest builds

nightly: citra-osx-20220515-46c6e5c
canary: citra-osx-20220519-605fd45

**Comment by Steveice10** [comment]
This appears to be working as intended on the latest macOS nightly builds, if I create a `user` folder alongside `citra-qt.app` it correctly uses that directory.
