### ISSUE TITLE
[Feature Request] async custom texture loading in Citra

### ISSUE THREAD

**Issue by HenrikoMagnifico** [citra-emu/citra#5881]
This is a feature request for Citra, although it can be seen as a solution to an issue in the emulator as well. At this time, Citra will stutter whenever the user is using a high resolution texture pack installed into Citra and new textures are getting loaded in-game. This can be whenever the player enters a new room, a cutscene occurs, a character appears or if the camera changes position suddenly. The severity of the stutter differ depending on the hardware being used, which custom textures are being loaded and what the game is. The currently known ways to alleviate the stuttering somewhat are;

- Moving the Citra installation to a faster hard drive, if possible. Like an M.2 SSD.
- Reducing the amount of background processes to give more headroom for Citra.
- Upgrading the RAM in your computer, both in terms of capacity but also speed.
- Upgrading your graphics card.
- Using lower resolution custom textures, or none at all.

None of these options are ideal, of course. Preferably, some kind of async loading of new textures could be implemented into Citra to reduce the stuttering whilst the new textures are being loaded in. That way the game could still display the regular base textures until the new one is ready to be displayed.

Furthermore, support for more texture formats would be a fantastic addition to Citra. Specifically BC7 DDS files, since they are both more space efficient and offer higher performance than the currently used PNG format. This might also help reduce the stuttering even further.

**Comment by GPUCode** [comment]
Fixed by new custom texture system
