### ISSUE TITLE
Fire Emblem graphical bug

### ISSUE THREAD

**Issue by NineKain** [citra-emu/citra#5883]
![image](https://user-images.githubusercontent.com/72826232/139320705-267bb325-0cbd-4d3b-83ec-c4dcefaa1e08.png)

at native res its present but less noticeable

**Comment by NineKain** [comment]
So there is no fix?

**Comment by SachinVin** [comment]
This was discussed before, it likely wont be fixed on citra's end, as it requires game specific hacks.
