### ISSUE TITLE
[macOS] Builds newer than nightly-1728 (9019212) are unable to execute due to missing dylib

### ISSUE THREAD

**Issue by SuperOkazaki** [citra-emu/citra#5888]
There is a regression introduced in the commits between `nightly-1728` and `nightly-1729` that make the application unable to be executed on macOS. The application is unable to launch on `nightly-1729` and newer. The reason is unpackaged .dylib files.

Here is a pastebin of the crash report:
https://pastebin.com/xWkLzpP7

**This is unrelated to other macOS issues, such as crashes during emulation execution.**
Builds `nightly-1728` and older continue to work.

System:
M1 MacBook Pro
macOS 12.0.1
16 GB RAM

**Comment by SachinVin** [comment]
Dupe of #5879, fixed in canary.

**Comment by spotanjo3** [comment]
So it works for M1 ?

**Comment by SachinVin** [comment]
You tell me, I don't have an M1 mac
