### ISSUE TITLE
Ever Oasis Blur Issue

### ISSUE THREAD

**Issue by laminaf** [citra-emu/citra#5890]
![Screenshot_20211105_145416](https://user-images.githubusercontent.com/93778469/140526185-e93c1e88-66fb-4879-bfe8-33a08eb0bbd6.png)
![Screenshot_20211105_145807](https://user-images.githubusercontent.com/93778469/140526188-033fa1ec-0047-44ae-8c73-b0e16de97d19.png)
Noticed this blur issue that causes minor graphical differences but is very apparent during noon in the desert or when aiming with the crossbow while using canary branch on Linux.
Tried older release versions until I found the issue appearing between canary-1984 and canary-1983 and I can reproduce the issue on nightly-1732 too.
[citra_log_canary1983.txt](https://github.com/citra-emu/citra/files/7486902/citra_log_canary1983.txt)
[citra_log_canary1984.txt](https://github.com/citra-emu/citra/files/7486903/citra_log_canary1984.txt)

**Comment by SachinVin** [comment]
@BreadFish64 seems like glCopyImageSubData, doesn't copy  to the correct channels, specifically the Green and Alpha seem to be swapped, and the game looks like it uses the Green channel for blurring. 

Not sure how helpful it is, but this is this is what the DS to RGBA looks like 

<details>
<summary>with <code>glCopyImageSubData</code>:</summary>

![ever oasis copy sub data](https://user-images.githubusercontent.com/26602104/145715258-d827faaa-13f3-4f16-a3a6-3bb580976e6d.png)

Only the Green:
![ever oasis copy sub data 2](https://user-images.githubusercontent.com/26602104/145716799-7b03d800-82aa-4293-af46-f8b6fe722b7d.png)

</details>
<details>
<summary>And with <code>texture_views</code>:</summary>

![ever oasis texture view 2](https://user-images.githubusercontent.com/26602104/145715527-1ed6c616-aaa1-40d7-8a08-a532df044918.png)

Only the Green:
![ever oasis texture view](https://user-images.githubusercontent.com/26602104/145716807-3de1a6c4-2509-46ef-af21-6ec4417431d5.png)

</details>
