### ISSUE TITLE
Way too hard to play roms as is

### ISSUE THREAD

**Issue by MightBeChris** [citra-emu/citra#5892]
I have zero desire to buy a 3DS.  I have zero desire to buy games for the system.  You've GOT to know the largest use of emulators is the use of ripped games.  Fix the emulator so it can function w/out needing original hardware.

**Comment by Efadd** [comment]
So, you're asking to make it easier to use distributed copyrighted materials? Good luck, and bless your soul!

**Comment by Iammethe24** [comment]
ask your parents for money kid

**Comment by MightBeChris** [comment]
Piss off.  Why the hell are you defending the pocketbook of a corporation?  Besides, I'm 41.  I've been stealing software for decades.  Don't act you owe Nintendo or any of those publishing companies anything.
