### ISSUE TITLE
Putting Citra on background while a game is running freezes framebuffer on Qt Wayland (Linux)

### ISSUE THREAD

**Issue by SuperSamus** [citra-emu/citra#5895]
The title is bad, I'll try to explain.

I'm running Citra on Linux with Sway as window manager (Wayland).
If I switch workspace or move Citra to another workspace while a game is running, the framebuffer will stop updating: the image of the game running will not change, while the rest of the game is still being emulated.
Stopping the emulation is the only way to solve the problem.

Launching `citra-qt` from the terminals logs multiple times `dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension`
The bug and that log only appear with the Qt interface running on Wayland: they don't happen if I run Citra through XWayland or the SDL interface.

The logs on the file don't say anything useful, they are the same whether I run Citra with Wayland or XWayland, but here they are anyway: [citra_log.txt](https://github.com/citra-emu/citra/files/7574845/citra_log.txt)

Linux NixOS unstable, Citra rev 5a7d8017

Quick way to reproduce my setup:
- Install `sway` and `alacritty` (or `foot` if installing Sway 1.7 or above);
- Run `sway` from a TTY;
- Press Win+Enter to open a terminal;
- Run `XDG_SESSION_TYPE=wayland citra-qt`;
- Launch a game on Citra;
- Switch workspace (Win+2, then Win+1);
- The framebuffer will stop updating, but the emulation is still going.

I am using a laptop with an AMD Ryzen 4500U and iGPU Vega 6 with mesa drivers.

EDIT: I can also reproduce the bug with Gnome Wayland if I force Wayland on Citra with `QT_QPA_PLATFORM=wayland`.

**Comment by 0xSteeW** [comment]
I have the same issue on FreeBSD wayland, using wayfire. Game freezes when switching workspace and nothing can be done to resume it. This does not happen with the SDL2 interface as mentioned.

**Comment by euclip** [comment]
Running Citra on Fedora 36 as a flatpak installed from Flathub exhibits this issue still. Opening the configuration menu doesn't cause an issue, but focusing any non-Citra window will cause the image to freeze even though, based on audio, game emulation continues in the background.

**Comment by luca-brambilla** [comment]
I still have the same issue on Fedora 37. As a temporary fix I save the state with `ctrl + c` and restart the simulation. Then I reload the state with `ctrl + v`.
It's not ideal, but it avoids losing your progress.

**Comment by SuperSamus** [comment]
Testing again on nightly 2020.
The issue completely solved on Vulkan.
On OpenGL, the issue is different: the parts that are supposed to be black become transparent (even on fullscreen). Still, the game is moving.
Closing.
