### ISSUE TITLE
[Feature Request] Per game control profiles and settings.

### ISSUE THREAD

**Issue by ha7ak3** [citra-emu/citra#5897]
It would be great to have the option to set a custom control profile to every game that way you don't need to open the settings window everytime you change game (I play with KB&Mouse so I have a lot of profiles) and a way to set some graphics setting to a game would nice too. for example in my system I need to enable "Accurate Multiplication" for some games but citra freeze with other games if the option is active.

**Comment by Hiroex** [comment]
Duplicate of #4924.
