### ISSUE TITLE
Taiko No Tatsujin: Doko don! Mystery Adventure! does not progress pass accessing the SD card

### ISSUE THREAD

**Issue by odog8** [citra-emu/citra#5909]
Citra Nightly 1737
[citra_log.txt](https://github.com/citra-emu/citra/files/7749546/citra_log.txt)

use any version of "Taiko No Tatsujin: Doko Don! Mystery Adventure!" to reproduce the error.

1. open the game. There is a message that roughly translates to "An error has occurred while accessing the SD card. So, when can't I use the communication?"
![image](https://user-images.githubusercontent.com/36713157/146870691-3b0ad33c-9fa5-46c8-875c-07c15e157161.png)

2. after clicking either A or B, there is another prompt. By using the arrow keys, you can tell that there is supposed to be a top screen, but it is completely black. It roughly translates to "".

![image](https://user-images.githubusercontent.com/36713157/146870957-d0161efc-e66a-48bf-95fd-500faaa9b1e9.png)

3. then the screen stays black no matter how long you wait.

**Comment by odog8** [comment]
The second one translates to "do you wanna disable spotpass?" Sorry, I forgot that was there ✌️

**Comment by calinz** [comment]
The reason this is happening was posted 2 years ago:
https://community.citra-emu.org/t/taiko-no-tatsujin-do-docon-mystery-stops-rendering-and-has-no-music/47389

**Comment by odog8** [comment]
Thats interesting, i hope it gets patched soon

**Comment by benderscruffy** [comment]
using the latest nightly it is still an issue

**Comment by GPUCode** [comment]
Is this fixed?

**Comment by GPUCode** [comment]
Fixed by https://github.com/citra-emu/citra/pull/6883
Can also use LLE BOSS in latest nightly to fix the game

**Comment by YousefSlimani99** [comment]
I hope somebody could fix this game, I want to play it so badly!
