### ISSUE TITLE
The Loading Glitch Occured

### ISSUE THREAD

**Issue by P0W3** [citra-emu/citra#5912]
I use citra-windows-mingw-20211212-28039d3.

I was setting up Citra. When I opened the decrypted 3DS ROM, the loading glitch occurred.

Here are my log files.

```
Archive File Group Size (Log): 106,847 bytes
CRC32: 1BA889F7
```

https://jumpshare.com/v/16FfUkCzLf3vFif1qT9v

```
Archive File Group Size (Video): 13,304,458 bytes
CRC: 4C03B8DC
```

https://jumpshare.com/v/uSidLt3wxX9DRzkzYrDf

**Comment by SachinVin** [comment]
This is an issue tracker for developers, not a support forum. Please ask for support on our discord server or on the Citra forums.
