### ISSUE TITLE
[Feature Request] Toggle custom textures ingame

### ISSUE THREAD

**Issue by BlinksTale** [citra-emu/citra#5931]
I think this feature could really help Citra marketing with hires texture packs, and I'd love to use it myself to show friends my experiments with AI upscaling.

"Configure > Graphics > Use Custom Textures" is a great feature, but loading a 5GB texture pack takes time, and it's hard to demonstrate how significant the improvements are when the game has to be restarted to load the default pack again, and even slower to load the high res pack all over again. It seems like it could be a small feature to let Citra load both custom and default texture packs into memory (if users selected an extra "Load both custom and default textures to toggle between" option) at a minimal memory expense compared to any hires packs. 

If a hotkey also toggled between the two, like F11 (not sure if that's in use yet) then demonstrating the power of Citra's custom texture packs visually for screencaptures would be much, much easier.

Thanks all!

**Comment by GPUCode** [comment]
Fixed by new custom texture system
