### ISSUE TITLE
Rhythm Heaven Megamix - Music is out of sync

### ISSUE THREAD

**Issue by Coffeline** [citra-emu/citra#5932]
I believe this is the same issue as #5265, but it is happening again. When starting a minigame, there is a weird static sound, and then, when the minigame starts, the music starts a bit late, making the game sounds and music be out of sync (music is off-beat, sounds are fine). The game is kinda playable like that, but It would make it difficult to play on remixes where the music is constanly changing.

This issue wasn't on Citra before, because I used to play the same game on it, and It was working perfectly with no issues. I tried downgrading to the Citra version I used before (Nightly 1544), I also tried to downgrade my video driver, but none of that solved the issue. The difference is that I'm now using Windows 11, instead of Windows 10, which I was previously using.

I'm currently using Citra Nightly 1747, but I don't think the problem is with this specific version. I tried an older version, and also tried Citra Canary, both with the same issue. And just to clarify again, this issue was NOT happening on Windows 10, it started happening after updating to Windows 11.

My specs are:
CPU: AMD Ryzen 5 1600 Six-Core 3.20GHz
GPU: Radeon RX 570 Series 4gb VRAM
RAM: 16GB DDR4
OS: Windows 11 Pro 64-bit

Here's the log file
[citra_log.txt](https://github.com/citra-emu/citra/files/7918647/citra_log.txt)

Comparison below. The difference is subtle, but it is really bad on a rhythm game.

My recording: https://youtu.be/IYTbt3UxNdo
Real hardware: https://youtu.be/I_i-XfJxAqo

**Comment by SleepingSnakezzz** [comment]
Can you try disabling V-Sync in Emulation -> Configuration -> Graphics -> Advanced Tab?
That might also be causing this issue for you.

**Comment by Coffeline** [comment]
> Can you try disabling V-Sync in Emulation -> Configuration -> Graphics -> Advanced Tab? That might also be causing this issue for you.

I've already tried that, even tried it again to make sure. No luck though :(

**Comment by realguystuff** [comment]
I can still confirm this is happening on the latest Citra. (To be honest, the other minigames are in sync, but some are not.) In Flock Step, it was making my gameplay almost unplayable, and I am sure because I played this on a real 3ds until the owner moved out.

**Comment by realguystuff** [comment]
I tried using LLE and the issue was fixed, but the problem was the performance, which was just going to be irritating.

**Comment by JustAJasmin** [comment]
> I tried using LLE and the issue was fixed, but the problem was the performance, which was just going to be irritating.

same issue with me, felt like i was going down the depths of hell while punching some pots lmao

**Comment by JustAJasmin** [comment]
problem's been going on for me too for a while, ever since i switched to a new laptop
reported on the citra discord server already just now
well, here's my log file: [citra_log.txt](https://github.com/citra-emu/citra/files/10355721/citra_log.txt)

**Comment by Coffeline** [comment]
Recent update:

I went back to Windows 10 because of Window 11's performance issues. I've tried running the game again, same specs and all, and it runs just fine on W10! No static sound, no audio lag, perfectly playable! I even went back to the Citra Nightly 1747, and it worked just fine on that older version too. It seems the issue only happens to me on W11.

**Comment by JustAJazzJAJ** [comment]
yeah, my old laptop where the game worked perfectly fine was windows 10, and i'm on windows 11 now

**Comment by SleepingSnakezzz** [comment]
Windows 11 *did* make some changes to audio drivers (early Windows 11 builds did not). So maybe that's related.

**Comment by JustinSpedding** [comment]
I have a similar issue with Rhythm Paradise Megamix. I am running Linux, so this problem is not solely limited to particular windows versions.

When using HLE:
* There is some static at the beginning of the level that sounds like it is playing the entire sound track sped up into a couple seconds.
* Then, there is no background music for the rest of the level.
* It seems like it plays the music as fast as the processor can play it, and then stops when there is nothing left to play.

When using LLE:
* It plays the music correctly in sync with the gameplay
* However, the performance is so bad and inconsistent that the game is unplayable.

Is there anything that I can do do help test? I am not sure if this is on the roadmap to be worked on.

**Comment by Kunshigo** [comment]
I have also experienced this and have the exact same issue. Have been waiting for a fix for a while now and hope its coming soon

**Comment by Miepee** [comment]
Something similar (not quite sure if it's the same) happens under Linux as well. But there only a quick static plays at the start of mingames and after that no music plays at all.
Tested using the nightly appimage builds, not sure if the flatpak builds behave differently.

**Comment by oddMLan** [comment]
Duplicate? #5265 
cc @xperia64

**Comment by Sawtaytoes** [comment]
This is still happening in the current Windows 11 22H2 build. Just got the latest nightly for Citra and noticed the same issue on the very first stage where you're punching stuff.

**Comment by mangtomas24** [comment]
> I believe this is the same issue as #5265, but it is happening again. When starting a minigame, there is a weird static sound, and then, when the minigame starts, the music starts a bit late, making the game sounds and music be out of sync (music is off-beat, sounds are fine). The game is kinda playable like that, but It would make it difficult to play on remixes where the music is constanly changing.
> 
> This issue wasn't on Citra before, because I used to play the same game on it, and It was working perfectly with no issues. I tried downgrading to the Citra version I used before (Nightly 1544), I also tried to downgrade my video driver, but none of that solved the issue. The difference is that I'm now using Windows 11, instead of Windows 10, which I was previously using.
> 
> I'm currently using Citra Nightly 1747, but I don't think the problem is with this specific version. I tried an older version, and also tried Citra Canary, both with the same issue. And just to clarify again, this issue was NOT happening on Windows 10, it started happening after updating to Windows 11.
> 
> My specs are: CPU: AMD Ryzen 5 1600 Six-Core 3.20GHz GPU: Radeon RX 570 Series 4gb VRAM RAM: 16GB DDR4 OS: Windows 11 Pro 64-bit
> 
> Here's the log file [citra_log.txt](https://github.com/citra-emu/citra/files/7918647/citra_log.txt)
> 
> Comparison below. The difference is subtle, but it is really bad on a rhythm game.
> 
> My recording: https://youtu.be/IYTbt3UxNdo Real hardware: https://youtu.be/I_i-XfJxAqo

Is there any update for this problem? i've been digging for solutions. I am also in windows 11

**Comment by Steveice10** [comment]
Can you test on the latest canary?

**Comment by Steveice10** [comment]
Should be fixed in next nightly.
