### ISSUE TITLE
random freezes

### ISSUE THREAD

**Issue by ineedhelpcitra** [citra-emu/citra#5933]
Random freezes in the legend of zelda: ocarina of time 3d
Device name	DESKTOP-CIFL52N
Processor	Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz   2.40 GHz
Installed RAM	8.00 GB
Device ID	B055EBA7-83E6-4423-AE30-D72BF7C25920
Product ID	00327-60000-00000-AA381
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by ineedhelpcitra** [comment]
[citra_log.txt](https://github.com/citra-emu/citra/files/7920033/citra_log.txt)
log file

**Comment by SachinVin** [comment]
This is an issue tracker for developers, not a support forum. Please ask for support on our discord server or on the Citra forums.
