### ISSUE TITLE
Citra cannot be built on Apple Silicon Mac using arm64

### ISSUE THREAD

**Issue by nik312123** [citra-emu/citra#5934]
Commit hash of build used: 45a4a56264b3d26b4dd1a16b13feda4f9fd5fe37

System: MacBook Pro 2021 using arm64 on macOS Monterey 12.1

Issue: The arm64 build of Citra fails when following the instructions [here](https://github.com/citra-emu/citra/wiki/Building-for-macOS). (Note: I ensured that I followed the instructions under "About building on Apple Silicon machines.")

Here is the output from `cmake .. -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_BUILD_TYPE=Release`: [cmake_output.txt](https://github.com/citra-emu/citra/files/7920110/cmake_output.txt)
 
Here is the output from `make -j4`: [make_output.txt](https://github.com/citra-emu/citra/files/7920111/make_output.txt)

**Comment by SachinVin** [comment]
Make sure you've installed and are running the arm version of homebrew and not the intel version.

**Comment by nik312123** [comment]
I am fairly sure that I did. When I migrated from my previous computer, I completely removed all my Homebrew stuff and reinstalled using `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`.

**Comment by SachinVin** [comment]
Doesn't seem like you removed whatever you installed with x64 brew, `/usr/local/include/SDL2` isn't the default path for arm brew.

**Comment by nik312123** [comment]
Hmm... You may be right. I'm going to completely uninstall and reinstall Homebrew to see if that fixes things.

**Comment by nik312123** [comment]
Yep. That resolved the issue. My apologies.
