### ISSUE TITLE
Kirby Battle Royale Shadow Bug

### ISSUE THREAD

**Issue by Peduls** [citra-emu/citra#5935]
Shadows in Kirby Battle Royale seem a little broken
[citra_log.txt](https://github.com/citra-emu/citra/files/7930359/citra_log.txt)

**Comment by Peduls** [comment]
![KBR](https://user-images.githubusercontent.com/34750422/150904882-76179e06-f926-449c-96c4-55c9aad687c8.png)

**Comment by benderscruffy** [comment]
using Canary 2610
still an issue

**Comment by GPUCode** [comment]
I have an idea on what causes it, will push it for next canary

**Comment by FearlessTobi** [comment]
Okay, I will close this then.

**Comment by benderscruffy** [comment]
using Canary 2614
shadow still missing in Vulkan

**Comment by GPUCode** [comment]
The shadows should be fixed if you disable spirv shader generation in vulkan

**Comment by benderscruffy** [comment]
yep it does work

**Comment by benderscruffy** [comment]
@GPUCode 
please reopen as vulkan is still not fixed yet

**Comment by GPUCode** [comment]
Shadows in vulkan should work correctly now
