### ISSUE TITLE
FEATURE REQUEST: More human-readable texture dump?

### ISSUE THREAD

**Issue by lindenmori** [citra-emu/citra#5936]
Making custom textures is kind of a slog and a significant part of that is sifting through the dumps to find the texture you need or to figure out what is meant to be what, so maybe there could be a possibility to dump textures in some more organized human readable way? I know we can't change the names of the dumped files anymore or existing texture packs will be broken. However, since Citra reads subfolders in the texture load folder fine, maybe it would be possible to dump textures into a folder structure? in this case, i think this would not affect how they are loaded, just how they are dumped?
for example, if the texture is stored in the romfs in /Item/Model/int_cat_black.bcres (using ACNL as an example here) the dumped image would go in /dump/textures/[gameid]/Item/Model/int_cat_black/[citra name].png? 
this would make it easier to figure out what a texture is to make the replacement (in my case, i am porting the ACPC textures, that are largely stored under the same names for the items that do exist in PC). and then, you could keep the same folder structure the dump created, just put it in load, and have an organized pack that makes it easier to guess whats the broken texture if you see one in game? obviously, old packs aren't going to organize themselves, but it would make creating new ones a less tedious process.

**Comment by GPUCode** [comment]
The new custom texture system allows for custom texture filenames
