### ISSUE TITLE
404 Response From Lobby API Crashes Room

### ISSUE THREAD

**Issue by fadillzzz** [citra-emu/citra#5937]
I've been hosting several rooms and lately have been noticing the rooms disappearing from the room browser.  When I looked into the problem, I noticed that the Docker containers all exited with an error like the following:

```
[29536.208276] WebService <Error> web_service/web_backend.cpp:GenericRequest:129: POST to https://api.citra-emu.org//lobby/f599b519-7fb3-46ca-b654-726265241086 returned error status code: 404
terminate called after throwing an instance of 'nlohmann::detail::out_of_range'
  what():  [json.exception.out_of_range.403] key 'id' not found
```

Seems like when trying to update the room info, the API would sometimes return a 404 and it causes the room to crash with the error above?

**Comment by SachinVin** [comment]
is this still an issue?

**Comment by SleepingSnakezzz** [comment]
Some backend stuff was changed recently. The dev said that restarting the room should fix the issue.

**Comment by fadillzzz** [comment]
Hasn't been happening again so far. Will reopen if it happens again.
