### ISSUE TITLE
[Feature Request] Free Camera Mode?

### ISSUE THREAD

**Issue by SolidSouless** [citra-emu/citra#5946]
A Citra emulation mod that allows Free camera movement in game. I assume it would be difficult as each game is different, but I thought it wouldn't hurt to ask.

**Comment by RocketRobz** [comment]
I've opened the same issue: https://github.com/citra-emu/citra/issues/5038

**Comment by AlexDecker64** [comment]
would be a good feature :/

**Comment by merryhime** [comment]
Duplicate of #5038.

**Comment by Dudee15** [comment]
I tried compiling the camhax but kept running into errors. To be specific, 498 errors.
