### ISSUE TITLE
Frogger 3D: Frog missing textures

### ISSUE THREAD

**Issue by BigheadSMZ** [citra-emu/citra#5953]
In Frogger 3D, the frog is completely white without a texture. Works with hardware renderer disabled, but speed is unplayable.  

Issue can be seen in this video at the marked time:
https://youtu.be/TJbVDvtcahg?t=136

Currently using Citra Canary 2053, but also happens in mainline. This has been an issue for a few years now, but was working at some point. A video way back from 2016 shows the frog with a texture.
https://youtu.be/fthDZdXwLNE?t=119

**Comment by benderscruffy** [comment]
using the latest nightly still an issue

**Comment by benderscruffy** [comment]
using Canary 2617
this has been fixed
can be closed
