### ISSUE TITLE
Citra Android [Bugs] [Glitches] [Graphical Issues] [Slow downs] Art Academy Lessons for Everyone! 

### ISSUE THREAD

**Issue by RFL0WGitPR** [citra-emu/citra#5958]
**I've experienced lag and slowdowns while testing Art Academy lessons for everyone! On Citra for Android.**

**[Graphical Issues]**

- You'll notice  just when you launch the game on Citra.

- Lags and slowdowns on main menu.

- Lags and slowdowns when gameplay and reading text from characters. 

- Slowdowns during cutscenes. 

**Citra build: bed6a4f12**

**Device: Motorola One Ace 5G (T-Mobile)**

**OS / Platform: Android 10**

**RAM: 6GB**

**Display: 6.7" Full HD+ Max Vision display [HDR 10]**

**Camera: 48 Quad-pixel Camera**

**Chipset: Qualcomm SM7225 Snapdragon 750G 5G (8 nm)**

**CPU: Octa-core (2x2.2 GHz Kryo 570 & 6x1.8 GHz Kryo 570)**

**GPU: Adreno 619**

**Conectivity: Wi-Fi 802.11a/b/g/n/ac,Dual Band (2.4GHz and 5GHz), Bluetooth 5.1**

**Comment by GPUCode** [comment]
Fixed by https://github.com/citra-emu/citra/pull/7096
