### ISSUE TITLE
Citra Android "Star Fox 3D" [Graphical / Audio Glitches]

### ISSUE THREAD

**Issue by RFL0WGitPR** [citra-emu/citra#5960]
**Issues**
**Game functions, but with major graphical or audio glitches. Unable to progress in specific areas due to glitches even with workarounds.**

**- Intro [Half of the screen has black bar covered].**
**- Slowdowns in Gameplay.**
**-choppy audio lags.**

**Citra build: bed6a4f12**

**Device: Motorola One Ace 5G (T-Mobile)**

**OS / Platform: Android 10**

**RAM: 6GB**

**Display: 6.7" Full HD+ Max Vision display [HDR 10]**

**Camera: 48 Quad-pixel Camera**

**Chipset: Qualcomm SM7225 Snapdragon 750G 5G (8 nm)**

**CPU: Octa-core (2x2.2 GHz Kryo 570 & 6x1.8 GHz Kryo 570)**

**GPU: Adreno 619**

**Conectivity: Wi-Fi 802.11a/b/g/n/ac,Dual Band (2.4GHz and 5GHz), Bluetooth 5.1**

**Comment by GPUCode** [comment]
The half screen issue has been fixed, the rest perf issuea are documented in https://github.com/citra-emu/citra/issues/5763
Closing as duplicate
