### ISSUE TITLE
[Feature Request] CTRPlugin support

### ISSUE THREAD

**Issue by patataofcourse** [citra-emu/citra#5962]
CTRPlugins, loadable on hardware using [this](https://github.com/Nanquitas/Luma3DS/tree/3gx-loader) fork of Luma3DS, are an extremely useful tool for 3DS modding. Both the Mario Kart 7 and Rhythm Heaven Megamix communities use CTRPlugins for modding in some way or another, and it's used as a general cheat system in lots of other games too. CTRPluginFramework also introduces some very useful tools for debugging.
It would be very much appreciated to have support for this feature, which is essential for the mantainability of code edits.

**Comment by GPUCode** [comment]
Fixed by https://github.com/citra-emu/citra/pull/6172
