### ISSUE TITLE
std::bad_alloc was thrown when saving state

### ISSUE THREAD

**Issue by kimkaesar** [citra-emu/citra#5970]
### Versions

Citra Nightly 1756

---
### Rom playing

Pokemon Ultra Moon

---
### Scenario

std::bad_alloc was thrown when saving state

![image](https://user-images.githubusercontent.com/24259469/156111589-c4acde2e-557f-4d78-aaaa-cbe5c513024f.png)

---
### Log file

[citra_log.txt](https://github.com/citra-emu/citra/files/8159038/citra_log.txt)

```
[  68.862726] Core <Info> core/core.cpp:RunLoop:128: Begin save
[  69.314453] Core <Error> core/core.cpp:RunLoop:133: Error saving: std::bad_alloc
```

**Comment by kimkaesar** [comment]
it seems like there is some memory leaks

**Comment by SachinVin** [comment]
Piracy is prohibited, Dump your purchased games from your 3DS.
