### ISSUE TITLE
[Feature Request] Load/Save state function; Pause emulation; Texture filters

### ISSUE THREAD

**Issue by dnyce13** [citra-emu/citra#5972]
Loving this emulator so far! A few requests I would make and I'm sure it already has been requested:

Load/save state function (like in official build on PC and Android)

Pause emulation (like in official build on PC)

Add texture filters (like in official build on PC)

Thank you!

**Comment by SachinVin** [comment]
All those are already implemented

**Comment by dnyce13** [comment]
I meant for the android version.

**Comment by SachinVin** [comment]
They are implemented even in the android version. If you are talking about the mmj version then you are in the wrong place.

**Comment by Gamemulatorer** [comment]
This will be fix via https://github.com/citra-emu/citra/pull/6313
