### ISSUE TITLE
Force CPU clock cycles

### ISSUE THREAD

**Issue by HTML-TM** [citra-emu/citra#5975]
Hello Citra community, it's a pleasure to write to you, I may have a "no programming geek" solution on the issue of "intel" PC game performance in Citra Nightly. 

I saw in another emulator called Dolphin, that there is a possible option to have control over the processor. They give you the opportunity to force CPU clock cycles. As they explain it, high values ​​can cause variable refresh rate games to run at a higher frame rate, at the expense of processor performance. Low values ​​can cause variable refresh rate games to run at a lower frame rate, saving processor resources. In my case, by default 100%, it would be (486 mhz) the game is slow, out of sync, the sound slow... but when I adjust the percentage to approximately 13%, a considerable drop compared to the initial value, about 64 mhz , the game maintains high-quality performance. I am using Citra Nightly, running with the game Pokemon X/Y, and it happens that the performance of the game is not smooth, the movement of the characters is not fast, in the transitions of scenes, when it enters an animation it gets stuck a bit, when the game enters battle mode it chokes. 

I was wondering if is it possible to review this option and replicate what they have done in the Dolphin emulator, in Citra? Thank you for your time, and I hope I have contributed to the community. A cordial greeting.

**Comment by poudink** [comment]
Citra's already had that for a while. It's the "CPU Clock Speed" option.

**Comment by GPUCode** [comment]
Closing due to above reason
