### ISSUE TITLE
[Feature Request] Incremental screenshot saving.

### ISSUE THREAD

**Issue by ReyVGM** [citra-emu/citra#5980]
Hello guys, first time using Citra now that I have a computer that can run it decently.

I love taking multiple screenshots from games. Their levels, animations, cutscenes, endings, etc. Right now when I press the screenshot key, it prompts me to name and save the shot. It would be great if you could add a way so that if I press the screenshot key, let's say, five times, it automatically takes and saves 5 screenshots in a predetermined directory.

Thanks and hopefully this is something that can be added in the future!

(Or is there a way to modify the qt-config.ini to achieve the results I'm looking for?)

**Comment by Z11-V** [comment]
#6025 solves this.

**Comment by ReyVGM** [comment]
Great!
