### ISSUE TITLE
Can't get out of the "Advance frame" option.

### ISSUE THREAD

**Issue by ReyVGM** [citra-emu/citra#5982]
Whenever I press the "\" key to advance a frame, it stays in that mode unless I close the emulator.

In other emulators, pressing the "Pause/continue emulation" key normally takes you out of Advance Frame mode. Is that something that could be implemented in Citra too?

Thanks!

**Comment by SachinVin** [comment]
You can use Ctrl+A to to stop frame advance, also consider using discord before creating issues.
