### ISSUE TITLE
Android version w/ JIT enabled spawns ball outside table in SpaceCadetPinball port

### ISSUE THREAD

**Issue by tomrow** [citra-emu/citra#5987]
https://github.com/MaikelChan/SpaceCadetPinball/tree/3ds
Using Android version bed6a4f2, game version 0.5 in both formats, and the Full Tilt! resource files, the ball is placed at the top left corner of the screen, a considerable distance outside the pinball table. In this state the ball cannot be launched.

**Comment by SachinVin** [comment]
fixed in nightly
