### ISSUE TITLE
3DS Firmware Compatibility Problem

### ISSUE THREAD

**Issue by SamRohod** [citra-emu/citra#5989]
I wanted to use the Mii Maker system app to make my own Mii. So, I installed the system archives files, installed aes_keys.txt, got the .cia files for the 3DS Firmware v11.15.0-47 U and **only** installed the 0004001000021700.cia file.

At this stage everything worked fine. with Citra giving me a popup to write the name:
![Before 1](https://user-images.githubusercontent.com/71593901/161135848-a9ccb20a-0901-4f63-a6e7-dbf81ba2baec.png)
![Before 2](https://user-images.githubusercontent.com/71593901/161135896-7d3564ce-d856-49cb-bef7-171e4788f58d.png)

Then I deleted the contents of my user folder, installed the system archives, and installed **ALL** the .cia files from the firmware. Now I get the 3DS keyboard (and Mii selector in Tomodachi Life) but every time I'm done using the 3DS keyboard the game glitches out (sometimes crashes):
![After 1](https://user-images.githubusercontent.com/71593901/161136523-3587d4eb-f778-4506-84fe-5f6cc9846cfd.png)
![After 2](https://user-images.githubusercontent.com/71593901/161136547-87527504-feb9-46a8-8b6a-bb153d14b265.png)

I only tested this with the Mii Maker and with Tomodachi Life. It would be nice to use the 3DS keyboard and Mii Selector instead of using the Citra popups (Assuming the user has the firmware) or at the very least not have the games break if the full firmware is installed.

Also, I tried to use the local multiplayer in Mario Kart 7 (which requires DLP LLE) and it worked with only installing the system archives files, aes_keys.txt, and the 3DS firmware v11.15.0-47 U. I didn't need the "Config savegame" files that are mentioned [HERE](https://citra-emu.org/help/feature/multiplayer/). Does that mean that the "Config savegame" files are not needed if the 3DS firmware is installed? (The system app "Download Play" never worked with me with or without the "Config savegame" files)

Side Question: If the user installs the full firmware, does the user still need [THOSE FILES](https://citra-emu.org/wiki/dumping-system-archives-and-the-shared-fonts-from-a-3ds-console/) (even though the installed ones are .app not .romfs).

**Comment by CyberYoshi64** [comment]
![Bildschirmfoto_2022-12-12_14-45-44](https://user-images.githubusercontent.com/35138367/207291588-e8abd511-6d74-49ee-940f-e65f642deb1f.png)
![Bildschirmfoto_2022-12-12_14-47-05](https://user-images.githubusercontent.com/35138367/207291605-c0b1fb72-bc78-44b2-8bd1-3517178ce1be.png)
![Bildschirmfoto_2022-12-13_11-03-10](https://user-images.githubusercontent.com/35138367/207291618-b6b3d900-59d1-4270-bec1-7828aa68a190.png)
![Bildschirmfoto_2022-12-13_11-13-31](https://user-images.githubusercontent.com/35138367/207291629-87ee038f-cb2b-4452-91f6-155c25040490.png)
Depending on the app, the corruption ranges from tame to completely unplayable. Mario Tennis Open can make Citra eat up all available resources. Super Mario 3D Land appears to be tame in that you might be okay to switch a Mii once, but do it the second time and will start to bug out the graphics as well.

**Comment by GPUCode** [comment]
Has been fixed in recent builds
