### ISSUE TITLE
Failed to load module "xapp-gtk3-module" Fedora 35 Cinnamon

### ISSUE THREAD

**Issue by ronaldofas** [citra-emu/citra#5998]
I have problems with citra flatpak on Fedora 35 Cinnamon
Citra                      org.citra_emu.citra                                  nightly-1759          stable      flathub  system

I try to use citra installed from a flatpak from flathub

OS: Fedora release 35 (Thirty Five) x86_64 
Host: A320M-S2H 
Kernel: 5.16.18-200.fc35.x86_64 
Resolution: 1366x768, 1366x768 
DE: Cinnamon 
CPU: AMD Ryzen 3 2200G (4) @ 3.500GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 2990MiB / 13981MiB 

backtrace.
  Gtk-Message: 00:54:19.025: Failed to load module "xapp-gtk3-module"
(citra-qt:2): GLib-GIO-ERROR **: 00:54:19.100: Settings schema 'org.cinnamon.desktop.interface' is not installed

**Comment by ronaldofas** [comment]
Fedora distro doesn't have this package. Can be added to flatpak?

**Comment by ChainSwordCS** [comment]
@ronaldofas I had this appear too, I'm running Linux Mint (probably 20.3 but I actually forget...)

According to one of the replies to this issue, https://github.com/linuxmint/xapp/issues/134
The module "xapp-gtk3-module" should not be necessary for the program to run. If Citra doesn't run, the core issue probably lies elsewhere.

**Comment by ronaldofas** [comment]
Men, I don't know how, but I uninstalled the flatpak and reinstalled and now it's working! I believe that you can close this Issue!
