### ISSUE TITLE
Gunman clive 1 & 2 compatability issues

### ISSUE THREAD

**Issue by Seamed** [citra-emu/citra#6006]
Gunman Clive 1 crashes upon a bullet being present, doesn't matter if it was shot by an enemy or the player
Gunman Clive 2 crashes also upon a bullet being fired

https://user-images.githubusercontent.com/103855819/163729008-258e89d5-ec14-4a8c-b854-f355b4055d6b.mp4

Log for Gunman Clive 1 (Windows)
[citra_log.txt](https://github.com/citra-emu/citra/files/8502183/citra_log.txt)

Log for Gunman Clive 2 (Windows)
[citra_log.txt](https://github.com/citra-emu/citra/files/8502185/citra_log.txt)

However, the android version of citra differs here, instead of the whole emulator outright crashing, it instead shows a major graphical glitch and continues working fine, this graphical glitch seems to be exclusive for Gunman Clive 1 and is present at the beginning of the first stage, not sure if it shows up later, however Gunman Clive 2 showed some other graphical glitches throughout the first stage, mostly incorrect colors and explosions not showing correctly

https://user-images.githubusercontent.com/103855819/163729048-35b5a7c2-1c1d-46a7-8d7a-997e015fb7fe.mp4

https://user-images.githubusercontent.com/103855819/163729255-5f3628ea-7c8f-4733-ac13-00c29f3c0954.mp4

Log for Gunman Clive 1 (Android)
[citra_log.txt](https://github.com/citra-emu/citra/files/8502213/citra_log.txt)

Log for Gunman Clive 2 (Android)
https://www.mediafire.com/file/7d2cnutcwb4uguv/citra_log.txt/file      (For some reason it wouldn't let me upload it normally)

Here are some video showcasing graphical issues with Gunman Clive 2

https://user-images.githubusercontent.com/103855819/163728689-f3e2e630-6a96-4663-8164-e956552b1559.mp4

https://user-images.githubusercontent.com/103855819/163728705-ef2e8e78-64cd-44a0-ba62-a2e2be7c647e.mp4

Real hardware

https://user-images.githubusercontent.com/103855819/163728744-fc13c20f-a6fb-43cb-8107-1f73c7b6c753.mp4

https://user-images.githubusercontent.com/103855819/163728746-7b82f5b4-b340-473a-bef4-5e025745a8b3.mp4

**Comment by SachinVin** [comment]
Hi, thanks for the detailed report, can you also try disabling hardware shaders do desktop and see if it is similar to android

**Comment by Seamed** [comment]
Well, turns out disabling JIT on deskstop yields the same results as android

https://user-images.githubusercontent.com/103855819/163911530-798a13e8-0702-438e-b931-6620e424fa80.mp4


https://user-images.githubusercontent.com/103855819/163911537-923159aa-c090-4c6f-9b22-0aac6ac86fb2.mp4

**Comment by SachinVin** [comment]
And what about with Shader JIT ON and Hardware Shaders OFF

**Comment by Seamed** [comment]
> And what about with Shader JIT ON and Hardware Shaders OFF

The whole emulator outright crashes

**Comment by SachinVin** [comment]
Alright, thanks

**Comment by Seamed** [comment]
Gunman Clive 2 gets a little further, but crashes upon getting to the title screen
[citra_log.txt](https://github.com/citra-emu/citra/files/8515560/citra_log.txt)

**Comment by benderscruffy** [comment]
using 2607
both go ingame and don't crash
can be closed

**Comment by SachinVin** [comment]
I think the graphics issues persist with shader jit off, so I left it open

**Comment by GPUCode** [comment]
Has been fixed in interpreter as well, so can be closed now
