### ISSUE TITLE
3D interlaced mode results in distorted image per eye

### ISSUE THREAD

**Issue by FireGate13** [citra-emu/citra#6007]
I can confirm that interlaced (normal or inverted) does not display normally in all games. For example in Mario Kart 7 , the image is distorted.
![wrong intelacing mario kart 7](https://user-images.githubusercontent.com/103507213/162959027-0dcabc6f-e406-400c-b8b4-f8907bfe9c21.png)
![wrong intelacing mario kart 7 2](https://user-images.githubusercontent.com/103507213/162959037-c5b1a1ca-f5e1-4007-b91b-f9ecb26d75ef.png)

if you isolate one eye , you can see the image is distorted:
![mk7 one eye](https://user-images.githubusercontent.com/103507213/163131067-83b0eb66-3d43-4f6a-a46a-f3b4afe488d9.png)

**Comment by Emayeah** [comment]
i noticed it's for all games, dunno why (i was trying to open the same issue but i stumbled across yours
it's not fixed yet
