### ISSUE TITLE
Storage Locations Ignored

### ISSUE THREAD

**Issue by Kalio83** [citra-emu/citra#6011]
This is for Citra Nightly 1762. It is completely ignoring custom locations configured in Emulation > Configure > System > Storage. It will always use/create the NAND and SDMC folders in my Windows user profile (roaming) regardless of what is set here. For what it is worth, I am trying to use a mapped network drive location (mapped to my V drive), I did not test it on a different local drive location. As a work-around I have created symbolic links for these two folders to force the emulator into using the locations I want to use.

**Comment by SachinVin** [comment]
are you using save states ?

**Comment by Kalio83** [comment]
Nope, not using any save states. But I did just notice something... when selecting a folder in the GUI, it puts the wrong slash in the directory path. This is what mine is currently set to:

V:/3DS/NAND

V:/3DS/SDMC

...but the / should be \ normally for a Windows path. The path is set by the Change button so it's not directly editable in the GUI. I wonder if that could be it?

**Comment by SachinVin** [comment]
Doesn't seem the the paths are ever actually set... I'm not sure if the setting ever did anything

**Comment by SachinVin** [comment]
Hi, let me know if canary works.

**Comment by Kalio83** [comment]
I can confirm the storage paths are working now. Thanks!

**Comment by Kalio83** [comment]
Nope, not using save states. However... I just noticed something. The 
wrong slash is being used in the file path for the folder I selected:

V:/3DS/NAND

V:/3DS/SDMC



The "/"s should be "\"s, normally.

The file paths are not used-editable in the GUI and automatically filled 
in using the Change button, so... no idea why it put "/" in the path 
instead of "\". Maybe that could be the problem?
