### ISSUE TITLE
No rom specified

### ISSUE THREAD

**Issue by Qu3ntin** [citra-emu/citra#603]
I need help with build recognizing the rom can anyone help me?

**Comment by purpasmart96** [comment]
What is the actual question?

**Comment by Qu3ntin** [comment]
I need help building the citra and I everytime i load it it says no rom specified
Any suggestions or help? :(

**Comment by yuriks** [comment]
Hm, where did you get this "Citra" from?

**Comment by Qu3ntin** [comment]
this website

**Comment by Qu3ntin** [comment]
i did the instructions as said on the windows build

**Comment by purpasmart96** [comment]
And did you manage to compile it?

**Comment by yuriks** [comment]
Oh, we actually do have that message somewhere. Are you trying to use the GLFW front-end? You have to pass the ROM as an argument. If possible use the Qt version instead since it has a GUI.

**Comment by Qu3ntin** [comment]
first i installed all the stuff on the windows build
second i did the clone git thingy as said on windows build 
third i did the cmake thing with no error
fourth i opened the citra sln file
fifth i did setup as start project then rebuild
sixth i try running the citra and it said no rom specified and press any key
