### ISSUE TITLE
Warioware Gold: the wall in the Doggy Door microgame does not render

### ISSUE THREAD

**Issue by aldelaro5** [citra-emu/citra#6032]
In the Ashley set, there's a microgame in Warioware Gold that involves twisting your 3ds to guide the thing to the holes in a wall to avoid them. In Citra however, the wall does not render.

Here is how it looks in citra on my end (tested on both my desktop pc with an intel igpu as well as on Steam Deck):
![Screenshot from 2022-05-19 18-16-05](https://user-images.githubusercontent.com/8932978/169413833-72554c69-bc6a-4f94-b163-b0bfffbc6e35.png)

And here is how it should look:

![Screenshot from 2022-05-19 18-21-30](https://user-images.githubusercontent.com/8932978/169414047-11a6bf5b-c6b4-49d3-b433-0eb7e86254bb.png)

The above screenshot was taken from this vid (timestamped at 56:08) where you can see the microgame in action: https://youtu.be/G26Rbus2y_w?t=3368

I took a log file by doing the folowing: cleaning existing ones, launch citra, launch the game, going to the index to access the microgame (it needs to be unlocked by seeing it at least once while playing through other modes such as Ashley's set) and play it once before exiting citra: 

[citra_log.txt](https://github.com/citra-emu/citra/files/8734558/citra_log.txt)

To reproduce the issue, you need to have seen this microgame at least once, but to unlock the Ashley set, you need to clear the twist league into set. I actually couldn't get the boss microgame to work on my desktop pc, so I simply transfered my nand and saves from my Steam Deck to my PC (the Steam Deck has a gyro and the ability to make it work through citra via DSU). What I mean is that you may need to import a save file to better test this.

Version info (sorry I can't seem to be able to copy the text in this dialog, I was using a flatpak which I updated just before posting this report)
![Screenshot from 2022-05-19 18-26-22](https://user-images.githubusercontent.com/8932978/169414557-def73ca3-1faf-46d7-924f-a530904a11fa.png)

Specs:
- CPU: intel core i7 9700k
- GPU: whatever the igpu of my CPU is called
- 32GB RAM
- Arch Linux (cinnamon 5.2.7)
- Issue was also reproducible on Steam Deck.

**Comment by Seamed** [comment]
I can confirm this really is the case, it happens on my copy too

Here's a recording I made on citra canary 2149

https://user-images.githubusercontent.com/103855819/169674416-cb2bb505-3c87-42c1-ab3c-a8700fa1a109.mp4

And here's the log of this recording
[citra_log.txt](https://github.com/citra-emu/citra/files/8748603/citra_log.txt)

**Comment by cicoa** [comment]
Would you have solved this error？I meet this error too.

**Comment by benderscruffy** [comment]
using the latest nightly this has been fixed
can be closed
![Screenshot 2023-05-10 174441](https://github.com/citra-emu/citra/assets/2696404/586ba390-9e3d-4f0c-847f-019a2543198f)
