### ISSUE TITLE
Poor dedicated GPU performance on Linux

### ISSUE THREAD

**Issue by jochuan** [citra-emu/citra#6034]
When i use the DRI_PRIME=1 command for making citra use the dedicated GPU it is performing way worse than my integrated GPU, on pokemon omega ruby i get 30 fps with my vega 8 in almost all parts but with my Radeon 540x it begins at 30fps but then it begins to stutter and the fps can drop to 22 or lower. I am using the flatpak version of citra but i also tried with a compiled version and still had the same issue.

Operating System: Linux Mint 20.3
CPU: Ryzen 5 3500U
GPU: Vega 8 and Radeon 540x
Citra Version: 1763
Game: Pokemon omega ruby

Vega 8:
![image](https://user-images.githubusercontent.com/11268912/169920095-40c8f8b0-3897-4412-8d7b-4df319f9f3ee.png)

Radeon 540x:
![image](https://user-images.githubusercontent.com/11268912/169920134-65281128-f56f-4975-bb8e-47d9945307ff.png)

Log while using vega 8:
[citra_log.txt](https://github.com/citra-emu/citra/files/8758545/citra_log.txt)

Log while using Radeon 540x:
[citra_log.txt](https://github.com/citra-emu/citra/files/8758548/citra_log.txt)

**Comment by GPUCode** [comment]
Has been fixed by recent opengl refactors and the vulkan backend
