### ISSUE TITLE
Fix enable hardware shader / make a switch to make it off or on

### ISSUE THREAD

**Issue by sammadness** [citra-emu/citra#6049]
Graphic issues with ocarina of time 3D when hardware shader is on. Also, the speed is reduced a little at the start screen when HW shader is off but after the start screen or the gameplay, the game has no graphic problem with HW off. FYI, I am using mediatek helio G95. Please fix this or make a switch on/off for HW shader.

**Comment by adiityeay** [comment]
no hope.. citra only supports vulkan while the g95 processor can only render opengl

**Comment by GPUCode** [comment]
Should be fixed by the Vulkan PR. Due to inactivity I'm closing this
