### ISSUE TITLE
Metroid Prime Federation Force freezes in New 3DS mode depending on player username

### ISSUE THREAD

**Issue by Bearborg** [citra-emu/citra#6054]
This is a weird one.

Metroid Prime Federation Force consistently hangs during the initial loading screen when New 3DS mode is enabled, but only if the player's username meets certain criteria. Specifically, I was able to reproduce this crash only when the player's username was exactly 5 letters long, and began with a character whose ASCII value was outside the range [64-80] ("@" to "P"). "Peter" causes the game to boot normally, "Quint" causes a freeze.

Tested with latest nightly (88a4759). Issue first appeared in 67f1e41, which is the first build where player usernames are returned via GetMyScreenName.

Specs: Windows 10 Home 21H2, Intel i5-8600K CPU @ 3.60GHz, GTX 1060 6GB, 16GB RAM

Log: [citra_log.txt](https://github.com/citra-emu/citra/files/8904731/citra_log.txt)

**Comment by Dragios** [comment]
Could you try latest Nightly and see if this issue still happens?
It might have been be fix by PR #7159

**Comment by Bearborg** [comment]
This does appear to be fixed, thanks!
