### ISSUE TITLE
[Feature Request] Add NDS Support

### ISSUE THREAD

**Issue by Brainterminator** [citra-emu/citra#6063]
I know there currently already are other NDS Emulators like DeSmuME but there is noone that supports Wireless Multiplayer via Network Emulation. My friends and I would like to play the old Pokemon Games (4th Gen) and be able to fight and trade Pokemon.
Do you think this could ever be implemented?

p.s. Great Work so far! My friends and I love Citra. It's one of the best Emulators ever made :)

**Comment by RocketRobz** [comment]
Pretty sure NDS support is out of scope for Citra. There's melonDS, which is being worked on, and currently supports WiFi, but (afaik) not local wireless. You could try opening an issue in their repo about it.

**Comment by SachinVin** [comment]
No
