### ISSUE TITLE
Professor Layton vs Phoenix Wright bug

### ISSUE THREAD

**Issue by Efadd** [citra-emu/citra#6067]
I'm attempting to run the aforementioned game on my Samsung tablet with a Qualcomm SD 865 and it crashes at the latest during the opening fmv, logs attached, and version bed6a4f12

Will add logs in a second, Android GH issues are weird.

**Comment by Efadd** [comment]
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/9077595/citra_log.txt.old.txt)
[citra_log.txt](https://github.com/citra-emu/citra/files/9077596/citra_log.txt)
Old crashed during logos, new crashed during fmv

**Comment by Steveice10** [comment]
Could have been fixed by https://github.com/citra-emu/citra/pull/6690, needs re-testing

**Comment by Efadd** [comment]
@Steveice10 Re-tested, got to gameplay this time on nightly.
