### ISSUE TITLE
interface language

### ISSUE THREAD

**Issue by Kira-YamatoTZC** [citra-emu/citra#6082]
I create this program on my computer,but in the citra's configure interface language, only has English,how can i get other lanuage,thank you

**Comment by vitor-k** [comment]
If you're saying you compiled Citra from source and want to enable the translations for the interface, you're probably looking for the `ENABLE_QT_TRANSLATION` cmake option. You can enable it by adding `-DENABLE_QT_TRANSLATION=ON` to the cmake command or via the cmake gui.

**Comment by Kira-YamatoTZC** [comment]
yes,I am saying I compiled Citra from source,I remember I don't click ENABLE_QT_TRANSLATION,thrank you for your help
