### ISSUE TITLE
[Build error] [Linux] clang-12 failed to build the project, array usage error

### ISSUE THREAD

**Issue by xwang186** [citra-emu/citra#6088]
No issue to build the project using the default compiler
```
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
```

However, if I switch to the clang-12 compiler

```
-- The C compiler identification is Clang 12.0.1
-- The CXX compiler identification is Clang 12.0.1
```
, I see error like this:

```
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/array:295:52: fatal error: instantiating fold expression with 649 arguments exceeded expression nesting limit of 256
      -> array<enable_if_t<(is_same_v<_Tp, _Up> && ...), _Tp>,
                           ~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/ayase/repo/citra/externals/dynarmic/src/frontend/ir/opcodes.cpp:46:25: note: while substituting deduced template arguments into function template '<deduction guide for array>' [with _Tp = Dynarmic::IR::OpcodeInfo::Meta, _Up = <Dynarmic::IR::OpcodeInfo::Meta, Dynarmic::IR::OpcodeInfo::Meta, Dynarmic::IR::OpcodeInfo::Meta, ...

```

Would be nice to support clang-12 if possible, or mention it in https://github.com/citra-emu/citra/wiki/Building-For-Linux to recommand to use older clang instead.

**Comment by merryhime** [comment]
Clang 12 requires `-fbracket-depth=1024`

**Comment by xwang186** [comment]
> Clang 12 requires `-fbracket-depth=1024`
> 
> For some reason in version 12 they decided to link maximum pack expression expansion size to bracket depth.

Yes Thank you for the information! I am new to clang-12, and your solution resolves my issue!
This works for me:
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fbracket-depth=1024

Not sure if it is worth to add something like this in the code:

```
if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  ...
  if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 12)
    string(APPEND CMAKE_CXX_FLAGS " -fbracket-depth=1024")
  endif ()
endif()

```

Maintainer feel free to close this issue; or you can keep it if it is worth to add a clang version fix for the future devs

**Comment by SachinVin** [comment]
Is this still an issue on the latest commit?

**Comment by GPUCode** [comment]
Fixed by https://github.com/citra-emu/dynarmic/commit/811b07b78c43f2cbb4de81d5579336522f87d977
