### ISSUE TITLE
Kirby Blowout Blast background missing on hw renderer

### ISSUE THREAD

**Issue by cam1170** [citra-emu/citra#6101]
In Kirby Blowout Blast the background is missing using the hardware renderer, instead appearing gray. The background objects are there but not the skybox.
Nightly 1779 | HEAD-58d0705 (2022-08-15)
GPU: Radeon RX 6600 XT driver 22.5.1
![image](https://user-images.githubusercontent.com/47539094/185481840-00a0d0f3-ec19-44b4-9051-ee8130d946a9.png)

**Comment by cam1170** [comment]
In motion it pretty much looks like this
https://www.youtube.com/watch?v=tEItoXevVO8

**Comment by cam1170** [comment]
With the hardware renderer disabled. Runs at like 4 FPS
![image](https://user-images.githubusercontent.com/47539094/185482069-02ec92d6-2775-436d-a441-134c82f12924.png)

**Comment by GPUCode** [comment]
I spent some time investigating this and it seems the games uses a texture cube to render the skybox instead of clearing the screen to that color. Probably a mistake in the texture cube implementation.

**Comment by benderscruffy** [comment]
using the latest nightly it is still an issue

**Comment by GPUCode** [comment]
Fixed by https://github.com/citra-emu/citra/pull/6921
