### ISSUE TITLE
Game Close after App switch S22U

### ISSUE THREAD

**Issue by ThTechTom** [citra-emu/citra#6104]
Hello,

my Citra close the Game after app switch.

Device: Samsung S22 Ultra
CPU: Exynos 2200
GPU: Samsung Xclipse 920 GPU
Android: 12
Citra Version: f6ea37342

My  Samsung Note 10+ don't have this issue

[Video](https://www.youtube.com/shorts/FOrpGhnMABA)

Thanks and show forward.

**Comment by GPUCode** [comment]
The video you posted is not accessible

**Comment by GPUCode** [comment]
Please upload a log file, the video is not enough to deduce the issue

**Comment by ThTechTom** [comment]
> Please upload a log file, the video is not enough to deduce the issue

You can close this issue, I have an unofficial version from Citra. Wrong Thread.
