### ISSUE TITLE
[Feature Request] Amiibo Write Funtionality

### ISSUE THREAD

**Issue by HackMeMan** [citra-emu/citra#6109]
Whenever I use an amiibo in games that require the Write functionality (SSB4, Pikmin, Chibi-Robo, etc), it claims to have written all data to the amiibo, and it is safe to remove it, but when I try to access the "saved data", it either reverts back to default (lvl 1 in SSB4) or just says it's empty/throws an error. Can you please add the ability to write to amiibo bin files?

**Comment by chichibooxd** [comment]
Amiibo functionality is currently being worked on yuzu. If they finished its implementation, we might see it ported to citra too.

**Comment by GPUCode** [comment]
Fixed in linked PR
