### ISSUE TITLE
Is it possible to yank broken macOS releases?

### ISSUE THREAD

**Issue by ian-h-chamberlain** [citra-emu/citra#6120]
[`d42cc68` (#6103)](https://github.com/citra-emu/citra/pull/6103/commits/d42cc6882fd875c194cadba8c332a5a865176474) removes the macOS build from CI. In that PR OpenGL minimum requirement was bumped such that macOS no longer works, so new macOS builds will not be published until macOS support is added back again (which that PR claims will eventually happen).

However, in the meantime it seems some macOS builds were published that contain the higher minimum requirement, and do not work:
- https://github.com/citra-emu/citra-canary/releases/tag/canary-2255
- https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1784

Both of these builds fail to start the emulator on my Mac, which is pretty unfortunate. I'd be fine with using the last working version, but I got auto-upgraded to these and so will need to manually downgrade to get it working again.

Is it possible that these builds could be removed manually to keep others from running into this scenario? It looks like the subsequent build didn't publish for macOS, so probably it would be fine to do just this once, until support can be added back and new macOS builds generated.

Thanks!

**Comment by merryhime** [comment]
canary-2255 removed; unfortunately I don't have access to citra-nightly to do the same there.

**Comment by GPUCode** [comment]
Macos releases are now back with the vulkan backend
