### ISSUE TITLE
A little big problem with Miitopia

### ISSUE THREAD

**Issue by Nolteng** [citra-emu/citra#6126]
While trying to emulate Miitopia, there was always a big "Not possible" icon in the place of the Mii's face while I was creating my Mii, even when I change the color skin that color looked like the color skin didn't changed at all.

**Comment by sakuramipha** [comment]
This is an issue tracker for developers, not a support page. We have a forum page and Discord server for that. Links to these can be found on the Citra website. 

The no entry sign in the space of the head is there to stop your game from crashing, you must dump some additional files from your 3DS to get the heads to display correctly. 
https://citra-emu.org/wiki/dumping-system-archives-and-the-shared-fonts-from-a-3ds-console/

**Comment by Nolteng** [comment]
Dear sakuramipha, I must say you that disgracefully you can´t  because I have no 3DS... alas I have no Homebrew Launcher. I did that post beacuse I though that that was a bug of some sort, now I see my mistake.

Now there's a final question to answer... will I buy 3DS in order to play Miitopia? No, it's no neccesary at all... I have a DS and, what makes this able to play 3DS is the backward compativility.
