### ISSUE TITLE
Missing Backgrounds for Fire Emblem Fates in Citra Nightly 1783 onward

### ISSUE THREAD

**Issue by AceWill8302** [citra-emu/citra#6128]
Backgrounds in Fire Emblem Fates don't appear properly in Citra Nightly 1783 and beyond, but do appear in Citra Nightly 1782 (Not sure if it shows properly in prior versions to 1782). Here's two comparison shots from both 1782 (Mountain Background) and 1783 (Blue Background):
![1782 - Present Background](https://user-images.githubusercontent.com/79551939/189802314-a390474c-ef2d-43a2-8100-81a30857baa9.PNG)
![1783 - Missing Background](https://user-images.githubusercontent.com/79551939/189802349-e8fcba65-bc18-46da-b51a-c8de7697fab2.PNG)

**Comment by GPUCode** [comment]
Looking into this it seems like a cube map related regression; the texture runtime isn't binding the correct OpenGL target to build the sky texture. I'll push a fix soon
