### ISSUE TITLE
After some ROMs save the state at some frame positions and load the state at other frame positions, some maps will be displayed in the game screen in black tiles.

### ISSUE THREAD

**Issue by a65090482** [citra-emu/citra#6136]
After some ROMs save the state at some frame positions and load the state at other frame positions, some maps will be displayed in the game screen in black tiles. It seems that these conditions do not exist in other ROMs. The full original name of this file is X_ 1.5_ R1.cia. The original file is encrypted.
---
![image](https://user-images.githubusercontent.com/12964634/192131953-c3f7442d-6dc0-4acb-a2e1-f43922d37f51.png)
![image](https://user-images.githubusercontent.com/12964634/192131969-24d1ae96-4509-4aee-ad02-6dc1e1ab77cf.png)
---
Full name of ROM I use - X_ 1.5_ R1-decrypted.cci.
---
annotation:
X_ 1.5_ R1: This ROM was made by an unofficial Team that called themselves "Sailing Chineselization  Team", who also made a Chinese Culture version of Pokmon Y.

**Comment by GPUCode** [comment]
Cannot reproduce this anymore, feel free to reopen if the issue persists
