### ISSUE TITLE
Zen Pinball 3D – Pinball reflection not rendered (Regression)

### ISSUE THREAD

**Issue by Dragios** [citra-emu/citra#6143]
_Zen Pinball 3D_, texture of pinball on title screen rendered incorrectly starting from Nightly 1783 onwards until the latest build which is Nightly 1788. PR #6103 introduce this regression. No useful log to be found either.
cc @GPUCode

[citra_log.txt](https://github.com/citra-emu/citra/files/9690515/citra_log.txt)

![image](https://user-images.githubusercontent.com/18496868/193413863-2212786b-13a4-4276-8532-d244c802cfc1.png) ![image](https://user-images.githubusercontent.com/18496868/193413868-b699c3c0-b257-4b4e-9a6f-9810fda09502.png)

System specs:
**OS:** _Windows 11 Pro Insider Preview build 22622_
**Processor:** _AMD Ryzen™ 5 5600G_
**iGPU:** _Radeon™ Graphics_
**Driver:** _Adrenalin 22.5.1 (WHQL)_

**Comment by GPUCode** [comment]
Fixed in my vulkan branch
![image](https://user-images.githubusercontent.com/47210458/193548070-193fbe96-a226-445e-b229-dbdd51f51c88.png)

**Comment by GPUCode** [comment]
Also works with the Vulkan renderer
![image](https://user-images.githubusercontent.com/47210458/193557966-0e493435-9c0e-400a-b536-d044d28fbbb6.png)

**Comment by GPUCode** [comment]
For the record this issue was fixed by #6158
