### ISSUE TITLE
Precompiled releases do not start on openSUSE

### ISSUE THREAD

**Issue by AlfredoRodda** [citra-emu/citra#6153]
Citra will not launch due to it not being able to find the following files even though they are installed.

```
libswscale.so.5
libavcodec.so.58
libavfilter.so.7
libavformat.so.58
libavutil.so.56
libswresample.so.3
```

An example of the error message when launching Citra.
`error while loading shared libraries: libswscale.so.5: cannot open shared object file: No such file or directory`

For Citra to launch, the "missing" files need to be symlinked.
```
sudo ln -s /usr/lib64/libswscale.so.5.9.100 /usr/lib64/libswscale.so.5
sudo ln -s /usr/lib64/libavcodec.so.58.134.100 /usr/lib64/libavcodec.so.58
sudo ln -s /usr/lib64/libavfilter.so.7.110.100 /usr/lib64/libavfilter.so.7
sudo ln -s /usr/lib64/libavformat.so.58.76.100 /usr/lib64/libavformat.so.58
sudo ln -s /usr/lib64/libavutil.so.56.70.100 /usr/lib64/libavutil.so.56
sudo ln -s /usr/lib64/libswresample.so.3.9.100 /usr/lib64/libswresample.so.3
```

Not sure if this is a hard-coded dependency issue for releases built. If this is not expected behavior, should this be noted on the wiki or site?

Environment
openSUSE Tumbleweed
Citra Nightly Build - [[c6153bb]](https://github.com/citra-emu/citra/commit/c6153bb32ef15c0e7245fdf5bbf3af51104dfa35) or Canary Build - [[c15eeee]](https://github.com/citra-emu/citra-canary/commit/c15eeee714e8c1d46c5d371a32c03af67ba76514)

**Comment by SachinVin** [comment]
Linux doesn't support using prebuilt binaries. You need to compile Citra yourself or use the flatpak version.
