### ISSUE TITLE
Graphical issues with Mario Luigi Paper Jam

### ISSUE THREAD

**Issue by Adamillo** [citra-emu/citra#6159]
I discovered a pretty interesting graphical bug where if you turn off hardware shaders you'll be able to see the lighting change when Paper Mario turns directions. This doesn't happen with hardware shaders at all. This happens with the latest Nightly build which is 1792. Here's how it looks when Paper Mario turns around:
![image](https://user-images.githubusercontent.com/45568316/194774885-153b64c6-b5af-4bf5-bdb2-5246865491f1.png)

**Comment by SleepingSnakezzz** [comment]
Please add a log file as well.

**Comment by Adamillo** [comment]
Sure thing
[citra_log.txt](https://github.com/citra-emu/citra/files/9768054/citra_log.txt)

**Comment by benderscruffy** [comment]
has this been fixed ??
please update

**Comment by benderscruffy** [comment]
using Canary 2615
this has been fixed
can be closed
