### ISSUE TITLE
Emulator crashing when started in vulkan.

### ISSUE THREAD

**Issue by Igor15123** [citra-emu/citra#6170]
I downloaded the latest version of the emulator on 10/21/2022 and when launched from the Vulkan API, the emulator just crashes on my PC.
My settings are:
Windows 10 64 bit
16gb ram
500gb SSD
AMD RX6400 GPU
AMD Athloon 3000G Processor
![SharedScreenshot](https://user-images.githubusercontent.com/116460269/197361342-aaf5b633-7d6d-486a-ac92-952ddf370416.jpg)

**Comment by FearlessTobi** [comment]
The Vulkan backend has not been released yet.
Crashes and inaccuracies are to be expected.
If you want to test Vulkan, you can join our Discord and do so in the #vulkan-testing channel.

**Comment by Igor15123** [comment]
> The Vulkan backend has not been released yet. Crashes and inaccuracies are to be expected. If you want to test Vulkan, you can join our Discord and do so in the #vulkan-testing channel.

Got it, I thought that here I could also report problems related to this version so that it could be fixed. Thanks for letting me know!
