### ISSUE TITLE
[Frontend Feature Request] Controller Tab

### ISSUE THREAD

**Issue by Amnesia1000** [citra-emu/citra#6174]
Change the control tab to display an image of the bottom of the 3DS or a 2DS. As seen in Yuzu.
![prueba](https://user-images.githubusercontent.com/45115804/199027515-84302674-f6a2-4335-ae63-85041ba0dbe8.png)
The image is for concept only (forgive my poor skills using Gimp). I suppose that for the C-Stick it would be better to use an image from a 3DS. 

I know they are currently working on more important things like the Vulkan backend, but it would be a good life improvement if in the future they take it into consideration.

**Comment by Daisouji** [comment]
> Change the control tab to display an image of the bottom of the 3DS or a 2DS. As seen in Yuzu. ![prueba](https://user-images.githubusercontent.com/45115804/199027515-84302674-f6a2-4335-ae63-85041ba0dbe8.png) The image is for concept only (forgive my poor skills using Gimp). I suppose that for the C-Stick it would be better to use an image from a 3DS.
> 
> I know they are currently working on more important things like the Vulkan backend, but it would be a good life improvement if in the future they take it into consideration.

Would do it but it's tied to the backend rework of yuzu and we don't have anyone who can translate it over.

**Comment by FearlessTobi** [comment]
Closing as duplicate.
