### ISSUE TITLE
[Feature Request] - Being able to map hotkeys to controllers

### ISSUE THREAD

**Issue by MarcoEstevez** [citra-emu/citra#6185]
As title says, as it is now one can only map hotkeys to Keyboard input
![image](https://user-images.githubusercontent.com/3447089/201073910-fe5377a9-0ea5-42bb-8dc9-91a71349e7a2.png)

Unlike yuzu does
![image](https://user-images.githubusercontent.com/3447089/201073773-13c2dd2f-5782-40ff-ad19-e540ea2bbe4a.png)

would it be possible to port over that feature from yuzu?

**Comment by Daisouji** [comment]
We don't have anybody currently to do this LOL

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/citra-emu/citra/issues/5885.
