### ISSUE TITLE
Mario vs. Donkey Kong: Tipping Stars random crashes!

### ISSUE THREAD

**Issue by momoids** [citra-emu/citra#6192]
The game has random crashes, even running at good speed!
My SPEC
RYZEN 1600x
GTX 1060 6GB
32GB RAM
Windows 11 (22H2)
nightly-mingw: 1811

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for developers, not a support tracker. For support with Citra, please open a topic on the forums: https://community.citra-emu.org/ or on our discord server: https://discord.gg/FAXfZV9
