### ISSUE TITLE
Make MacOS Apple Silicon Build Available

### ISSUE THREAD

**Issue by leonewton253** [citra-emu/citra#6195]
I built a MacOS Apple Silicon version of Citra. I would like to make it available for other people.  Its based on Citra Nightly commit d380980

I followed these build steps and manually set the JIT flag.

https://community.citra-emu.org/t/citra-macos-m1-arm64-build/347604/28?page=2

[citra-qt.zip](https://github.com/citra-emu/citra/files/10048299/citra-qt.zip)

**Comment by lnew253** [comment]
When starting a game you need to adjust the window for the video to appear but everything works great.

**Comment by 556644O** [comment]
Thanks for your build, I ran Monster Hunter 4G and XX on my M1 Pro Macbook using your build. The games could run without crash, but the performance was poor，both games had only about 25 frames. As far as I know, Citra only supports openGL up to now, when Citra support Vulkan, it may perform better on the apple silicon Mac.

**Comment by lukasong** [comment]
Just wanted to say thank you for providing a new ARM64 build! I hope that Citra themselves can just automate the process on their end in the future~ Now if only we could get Metal support :) a gamer can dream ~~_cries cos itll never happen_~~

**Comment by phirestalker** [comment]
I just compiled using those instructions, but there is no vulkan support like there is in the current x64 release for macos. What do I have to do to enable vulkan in this build?

**Comment by shinra-electric** [comment]
This issue can probably be closed. 

A universal binary is already available in [canary](https://github.com/citra-emu/citra-canary/releases). Nightly and official releases will follow soon.

**Comment by phirestalker** [comment]
I found an installer for macos on the website for canary. I guess that will install the universal? I may have already had it. I just assumed it was Intel, because of performance.

**Comment by axu2** [comment]
@phirestalker You can check if it's Intel or Apple by checking the Type column in Activity Monitor for CPU

**Comment by phirestalker** [comment]
> @phirestalker You can check if it's Intel or Apple by checking the Type column in Activity Monitor for CPU

Thanks. I just checked the build the installer is using for canary against the download page and it is a universal build, so that mystery is solved.

**Comment by GPUCode** [comment]
Builds are now available on the website
