### ISSUE TITLE
[Feature Request] Ability to disable/skip a screen layout

### ISSUE THREAD

**Issue by djr928** [citra-emu/citra#6197]
Hello, I'm using Citra on my Steam Deck and it works perfectly but I always have issues with the separate windows layout when toggling through layouts while in game mode. 

Could you possibly add a way to disable or even just skip a screen layout when using the toggle screen layout hotkey?

Maybe a list in which you can toggle layouts will work?

**Comment by Daisouji** [comment]
resolved ##6198
