### ISSUE TITLE
Lighting causes the screen to flicker wildly ！

### ISSUE THREAD

**Issue by innovation2013** [citra-emu/citra#6200]
When I play Fire Emblem Echoes: Shadows of Valentia, the lights flicker wildly in the sky at the start of the game, and in the cave where there are light sources.

https://user-images.githubusercontent.com/18549968/203851057-2460f8f2-f8d9-4037-81ae-949971f2c642.mp4

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for development, not a support tracker. Please use our Discord server, https://discord.gg/FAXfZV9, or our support forums, https://community.citra-emu.org/,  for support requests.
