### ISSUE TITLE
Texture Flickering Bug on Android Citra-Emu running Rocket Slime 3

### ISSUE THREAD

**Issue by Fwoggey** [citra-emu/citra#6222]
I am experiences intense texture flickering when trying to run Rocket Slime 3 on my android using the Citra Emulator Beta 15 app. The game itself runs very well at a steady 30 fps with very brief drops here and there. This is a video recording of the issue itself on my phone https://www.youtube.com/watch?v=RgQoXhgP4gk . I am also running an English translation patch with the game but the texture flickering persists without the translation patch installed at about the same frequency.

Below is my android's specs and model

![android](https://user-images.githubusercontent.com/120693128/207996175-89747056-148d-41af-847c-aba7228b46b2.png)

And my log file of me starting up the game, loading my file, walking around for like 10 seconds, then saving and closing the game. [citra_log.txt](https://github.com/citra-emu/citra/files/10241736/citra_log.txt)

I haven't experienced any emulations inaccuracies. As you can see on the video all of the text boxes do not flicker. Not on the video when the gameplay turns to sailing the text boxes are invisible but interactable so they can be proceeded through anyways. Here is a timestamped youtube video of what the gameplay looks like without flickering at about the same time my gameplay is at. https://youtu.be/6LwKiZ0D5xU?t=200 .The exact same game and patch on Citra Nightly for my PC run without these graphical issues 

EDIT 1
I played for an hour more to gather some additional data. Here is a longer video of boat travel and battling. https://youtu.be/ISInvljEdPM Ironically the bottom screen does not actually have any issues and despite the flickering of the top screen the game otherwise runs very well on the hardware. Texture flickering when walking around only seems to happen when the action is on the top screen as you can see halfway through the video that walking around is fine but at the end of the video when I am on the top screen again it is glitching. [citra_log[3].txt](https://github.com/citra-emu/citra/files/10243120/citra_log.3.txt) That is my log from after closing the game after the recorded session. Perhaps there the glitch lies with how the the top DS screen for this game is being emulated! Additionally you can hear text boxes open and progress during the sailing sections at the start of the video but these oddly remain invisible. Perhaps another effect of this bug.

**Comment by GPUCode** [comment]
There have been many opengl improvements recently, feel free to reopen if it's still an issue
