### ISSUE TITLE
Emulation slows down until the Texture Filter setting is changed

### ISSUE THREAD

**Issue by MEMESCOEP** [citra-emu/citra#6223]
Whenever I play games, the emulation speed significantly drops until the `Texture Filter` property is changed. So far it seems like it can be changed to any value, and once it is, the emulation sheep returns to normal.

**Comment by GPUCode** [comment]
Do all games exhibit this games or can you provide specific examples? Changing the texture fliter resets, so your problem may be related to the rasterizer cache being slow due to a large amount of surfaces being stored, something that should have been solved by #5710

**Comment by MEMESCOEP** [comment]
Yes all games have this issue for me (My examples are Mario Kart 7 and NSMB 2).

If it's the rasterizer cache, how do I clear it?

**Comment by GPUCode** [comment]
The only way to clear the cache is either change the texture filtering or the screen resolution. However this shouldn't be happening under normal circumstances. How long after you boot each game, do you notice a slowdown?

**Comment by MEMESCOEP** [comment]
It's instantaneous. It also happens on every computer I've tested it on.

**Comment by GPUCode** [comment]
Does this still happen?
