### ISSUE TITLE
Playing a movie file (.ctm) makes citra run extremely slow and somehow makes the bottom bar grow relative to the file length

### ISSUE THREAD

**Issue by kamijoan** [citra-emu/citra#6225]
I'm running Citra Canary 2326
So as the title says, the lag also gets worse of the file is bigger, cant really show the lag but I can show the bar at the bottom.

![2022-12-16_17608_citra-qt](https://user-images.githubusercontent.com/49537119/208174695-f47ebac9-c548-4ad7-8f6a-9c4ebf2a1dc1.jpg)

This happens with a file at around 12 hours, can't really say when the bar started growing but it was slow to play even on the first hour.

![2022-12-16_17609_citra-qt](https://user-images.githubusercontent.com/49537119/208174848-80c64460-39da-418c-acb3-054093c0d0ea.jpg)

And it looks like this when playing an old file that says >1day.

The crazy bar aside, I would really like to at least fix the lag.
Here's a log from the first screenshot.

[citra_log.txt](https://github.com/citra-emu/citra/files/10248502/citra_log.txt)

**Comment by kamijoan** [comment]
Also tried on canary 2336 some days ago after resetting all configs to default but the issue was the same.

**Comment by SachinVin** [comment]
You seem to have texture dumping enabled, can you retry with that disabled

**Comment by kamijoan** [comment]
Disabled both texture dumping and custom texture loading, issue still present.

[citra_log.txt](https://github.com/citra-emu/citra/files/10249118/citra_log.txt)

**Comment by vitor-k** [comment]
The bar growing should be fixed now, can you re-test?

**Comment by kamijoan** [comment]
Canary 2470, tested with the old files and the issue is fixed.

Thanks
