### ISSUE TITLE
Luigi's Mansion: Dark Moon: Rain does not appear in Gloomy Manor

### ISSUE THREAD

**Issue by verygladen** [citra-emu/citra#6226]
In Luigi's Mansion: Dark Moon, rain is suppose to appear outside the Gloomy Manor level, but does not render on the emulator compared to real hardware.

Citra version: Nightly 1821

How to reproduce:

1. Boot the game
2. Go into a Save File
3. Select the A-1 mission from Gloomy Manor
4. Load into the mission
5. See issue

Log: 
[citra_log.txt](https://github.com/citra-emu/citra/files/10250582/citra_log.txt)

Images:
![image](https://user-images.githubusercontent.com/37459940/208219363-22d5b044-5b96-416b-b265-a9b65236c5a7.png)
![image](https://user-images.githubusercontent.com/37459940/208219371-29d0aa5c-6578-4547-bd21-ca284ae68195.png)

**Comment by benderscruffy** [comment]
@GPUCode 
using 2618
still an issue with open gl and vulkan
could check software as it ran way to slow (couldn't get to title screen)
https://www.youtube.com/watch?v=9FPWZn7LVnI
look at the 10 minute mark to see how it is supposed to look
