### ISSUE TITLE
Android 13 (One UI5) Can't access Quick Menu ingame

### ISSUE THREAD

**Issue by xastrosrulex** [citra-emu/citra#6230]
Swiping down to try and access the quick menu doesn't work anymore. My Galaxy Fold 4 just updated from Android 12 to 13 with the One UI 5. Before this update, the feature was working as advertised. Now it won't even appear anymore. I am using the latest nightly build as of this writing (nightly-1822). I have observed that multiple users in Reddit are having the same issue right after their phones updated. It appears to be happening on the latest Samsung phones (S21, S22, S22 Ultra, Note 21, etc.)

**Comment by SleepingSnakezzz** [comment]
We've had other reports from users saying the same thing. Samsung phones start suffering from this after updating to Android 13, yet we've also had reports of users on other brands starting to get this issue from Android 12 onward. Seems to be dependent on your Android skin.

**Comment by Anayka-Ryu** [comment]
But My Cellphone is Samsung Series A 22 i don't have where playing m3ds
emulators with cheats witouth bugs and black Screen in fact What Citra
Version for A22 or A22 Other version of Samsung is more Recomended for
playing my games on Citra?

**Comment by Anayka-Ryu** [comment]
But in fact for put Cheats Not anymore Bugs or Black Screens   and also playing games (Pokémon Zelda Mario and Smash Bros and more games Without Error generic games on all cellphones What Version of Citra Emulator Can recomended for All cellphones that Happened this Problems? And also Allowed put Cheats in games on Ultra Moon or Ultra Sun of Pokémon And Other Games And Avoid the Chrashes and Bugs and Black Screens and Cellphones that not have Snapdragon? And the gb ram is for 4 gb for cellphones of 128 gb for series A 22 samsung or other model of phones? Can help us?

**Comment by Anayka-Ryu** [comment]
Help For Citra! Also saying Error 12 Generic! What need for the emulator...Everyone those cant Waiting more

**Comment by xastrosrulex** [comment]
By Android skin, do you mean different Themes? I am running the default Theme on Android and have no interest in installing different themes

**Comment by SleepingSnakezzz** [comment]
Not sure what you mean by themes. But I'm referring to the brand specific Android user interface variants. For example, Samsung uses "One UI", Oppo uses "ColorOS", Xiaomi uses "MiUI", ect. 
They're "skins" that change the way your phone's UI looks, as well as functions at times. Google might have demanded a new implementation, guideline or API for accessing the slide down menu. Which would explain why some Android skins only have issues on Android 13, and others already on Android 12. It just means that the skin's company hadn't implemented the new requirements yet in Android 12, whilst other companies had. Then again, I'm not a dev, this is just a guess.

**Comment by GPUCode** [comment]
Fixed by #6248
