### ISSUE TITLE
build.gradle, should we change jcenter to mavenCentral?

### ISSUE THREAD

**Issue by jakedowns** [citra-emu/citra#6232]
https://github.com/citra-emu/citra/blob/b588d6181bcae7b6886e3b3116c9475a59836c2d/src/android/build.gradle#LL7C9-L7C16

![image](https://user-images.githubusercontent.com/1683122/209885441-7106b419-7b6f-40a0-bf16-66521b678ff1.png)

**Comment by SachinVin** [comment]
Sounds good
