### ISSUE TITLE
Launching game deselects post-processing shader

### ISSUE THREAD

**Issue by Peduls** [citra-emu/citra#6238]
Using Citra Nightly 1825 launching a game de-selects any post-processing shader and has to be manually re-enabled after launching a game.

**Comment by Peduls** [comment]
I tried deleting qt-config.ini and resetting all my settings but it still happens. I also tried setting qt-config.ini to Read-only and it changes my post-processing shader back to default/off after launching a game.

**Comment by FearlessTobi** [comment]
Can you please test if this also happens on Nightly 1816? (https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1816)

**Comment by Peduls** [comment]
That build didn't have the issue.
