### ISSUE TITLE
Closing Citra wizard re-opens the updater instead of Citra

### ISSUE THREAD

**Issue by kevincrans** [citra-emu/citra#6254]
I reproduced it on Windows 11, 12 insider builds and Windows server 2022.
I hope this will be added instead of rejected.

**Comment by SleepingSnakezzz** [comment]
This is intended behavior, if a bit confusing. So this isn't a bug.

**Comment by FearlessTobi** [comment]
We can't do anything about this, as this behavior is caused by the Qt updater.
