### ISSUE TITLE
Regression in Cave Story 3D "bubble" rendering

### ISSUE THREAD

**Issue by JMC47** [citra-emu/citra#626]
For some reason, part of the bubble around the two characters in the opening is missing/corrupted/offset.  You can see it in the software renderer sort of (right side) but it shows up more clearly on the hardware renderer. (left)

![rituhgc](https://cloud.githubusercontent.com/assets/6598209/6461153/4c05f672-c16b-11e4-828e-3a527efbf50d.png)

This did not happen originally, our Cave Story 3D video did not show any kind of glitch in the bubble.

https://www.youtube.com/watch?feature=player_detailpage&v=ZGQWVMCdfK0#t=19

**Comment by tfarley** [comment]
Both of those screens were sourced from the hardware renderer, just with different resolutions. Sorry for the confusion. When I switch to the software renderer this issue goes away on my end.
