### ISSUE TITLE
Android 8(API +26) can still run Citra

### ISSUE THREAD

**Issue by Bardock88** [citra-emu/citra#6260]
Hello, I'm here to show that _Android 8_ is capable of running **Citra** in both **_canary_**  and **_nightly_** versions that contain the new '_cubeb_' audio feature as shown in the _comparison video_ I made between the **_official Citra_**([_build bed6a4f12_ - _beta 15_](https://github.com/citra-emu/citra-android/releases/tag/beta-15)) and **_Citra MMJ_**([_version release of 10/18/2022_](https://github.com/weihuoya/citra/releases/tag/20221018)):

https://user-images.githubusercontent.com/102046116/214139902-a5ca0079-8d79-4d78-8c6e-901f06e5b2fb.mp4

PS:I hope what I just demonstrated helps in some way.

**Comment by SachinVin** [comment]
Using 4 year old cubeb is not the solution. Feel free to reopen if you have a solution with modern cubeb.
