### ISSUE TITLE
overlay single screen integration

### ISSUE THREAD

**Issue by phly95** [citra-emu/citra#627]
I was thinking, the DS makes full screen not entirely possible (without letter-boxing) and some critical info is placed on the bottom screen (ie: health). What about adding some type of sprite display detection, that sees if heart (or custom script for each game) is located in a certain location on the bottom screen, move to top screen gameplay display in a set location.

Maybe even custom interfaces if certain keys are pressed

I made a demo pic. Although it's sloppy, I believe it gets the point across (In a library that only has Paint)
![modded](https://cloud.githubusercontent.com/assets/3526540/6471739/ac1fdece-c1bb-11e4-92a2-07b2adf7156b.png)

of course it would need some added transparency compared to my demo, but it could have great potential for fullscreen 1080p 3ds games like it were a console game.

Note: this is more of a task for people without the means of contributing bug-fixes. There is too much to fix to take away time from bug fixes.

**Comment by yuriks** [comment]
Sorry, but this is never going to happen. It simply isn't feasible.
