### ISSUE TITLE
Severe frame drops after updating dynamics

### ISSUE THREAD

**Issue by innovation2013** [citra-emu/citra#6270]
#6240
After updating to the upstream, the game now runs very slowly, such as Monster Hunter 3G, the FPS dropped from the original 60 to 20, and the FMV dropped from the original 15 to the current 3-5, and it is very unstable. The equipment I tested It is Samsung S20, CPU is Qualcomm 865
@SachinVin @Steveice10

**Comment by SachinVin** [comment]
This is an issue tracker for developers, not a support forum. Please ask for support with your issue on our Discord server (https://discord.gg/FAXfZV9), or on our forums (https://community.citra-emu.org/).
