### ISSUE TITLE
Crash when playing both TLOZ OOT 3D and Cave Story 3D.

### ISSUE THREAD

**Issue by LittlePippy** [citra-emu/citra#628]
Encrypting doesn't seem to work, .3ds copies don't work...

**Comment by MoochMcGee** [comment]
You have to decrypt your games first.

**Comment by LittlePippy** [comment]
I decrypted TLOZ 3ds yesterday. Got an autocrash when loading the profile bin file it has.

**Comment by wynn1212** [comment]
Did you followed the [Decryption](https://github.com/citra-emu/citra/wiki/Decryption)

**Comment by archshift** [comment]
Sorry, this issue report is too vague. Closing.
