### ISSUE TITLE
Ocarina of time Crash during cutscene

### ISSUE THREAD

**Issue by IsopropanolUtilizer** [citra-emu/citra#6281]
So Ocarina of Time is crushing during cutscene considering Triforce when Sheikah reveals as Zelda.
I've concluded that the main issue when using OpenGl is lack of 4-7 wrap modes, but idk how about Vulkan core.

[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/10579646/citra_log.txt.old.txt)

Device: Macbook Air M1 2020 16/256

Citra version: [https://github.com/MichaelGDev48/citra-nightly-arm64-mac/releases/tag/vulkan-experimental-10](url)

**Comment by SleepingSnakezzz** [comment]
Apple Silicon devices aren't officially supported currently. The Citra version you've linked also isn't an official Citra build.

**Comment by MichaelGDev48** [comment]
I also archived the repo and announced if you want the experimental vulkan use gpucode’s fork

**Comment by IsopropanolUtilizer** [comment]
> I also archived the repo and announced if you want the experimental vulkan use gpucode’s fork

How to enable this?

**Comment by MichaelGDev48** [comment]
Get the latest build here https://github.com/GPUCode/citra/actions
