### ISSUE TITLE
Fatale error

### ISSUE THREAD

**Issue by seropigeorgedev** [citra-emu/citra#6285]
Error: `Loader <Error> core/loader/loader.cpp:GetLoader:120: Failed to load file` and then the file I can't play face raiders witch normally does work on citra android version and I can't play nsmb 2 witch also does normally work on citra android version i have citra nightly build f66d03d android

**Comment by SachinVin** [comment]
This is an issue tracker for developers, not a support forum. Please ask for support with your issue on our Discord server (https://discord.gg/FAXfZV9), or on our forums (https://community.citra-emu.org/).
