### ISSUE TITLE
update Android SDK API and add free pure black theme for OLED screens

### ISSUE THREAD

**Issue by soundsnow** [citra-emu/citra#6288]
Nightly and Canary
I guess it's Android 10 currently
For Android 11, 12, 12.1(12L), 13, 14

I payed for Dark theme
it's not pure black
The best color for our eyes and OLED screens

I think themes are a basic option and not worth my money

It should be free
Change Theme Free
Texture Filter Premium

**Comment by FearlessTobi** [comment]
Thanks for your providing your opinion, however the dark theme is our only revenue stream on Citra Android and will not be made free.
