### ISSUE TITLE
All 48 Possible Fullscreen NDS Screen Layouts for PC and Android

### ISSUE THREAD

**Issue by soundsnow** [citra-emu/citra#6302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Swap, Rotate (90°, 180°, 270°), Hide, Big/Small
![image54](https://user-images.githubusercontent.com/109885044/218662614-03029d6b-8435-4705-8a1a-670f623dcbd5.png)

### Why would this feature be useful?

Sorry I submitted a issue, and I forgot to close it
This is my final issue about Screen Layouts
For Android Phone and PC Rotating Monitor

I don't like submit issues with template

**Comment by FearlessTobi** [comment]
What I said in #6253 still applies.

> Thanks a lot for your suggestions.
Some of those ideas seem like they are limited to only a few specific usecases and don't need to be presets in Citra.
I think what we really need here, is the ability for users to define their own layouts.
That request already exists here: https://github.com/citra-emu/citra/issues/6047.
Therefore I'm closing as a duplicate.
