### ISSUE TITLE
OoT Crashed During Triforce Loading Bar on bunnei/citra/pica_progress3f 

### ISSUE THREAD

**Issue by wynn1212** [citra-emu/citra#631]
Crash on booting up OoT during the loading bar. It says "Run-Time Check Failure #3 - The variable 'val' is being used without being initialized." on Visual Studio 2013 Community Update 4 on Windows 10  

Here's a log from terminal:
http://1drv.ms/1x0q7oH
Here's a log from VS Output Debug:
http://1drv.ms/1x0pZWt

**Comment by bunnei** [comment]
This branch is obsolete. Use master instead!

**Comment by wynn1212** [comment]
Thank You!
