### ISSUE TITLE
[Home Menu] Remaining tasks for home menu compatibility

### ISSUE THREAD

**Issue by Steveice10** [citra-emu/citra#6327]
Setting up an issue to track some of the major issues remaining for home menu compatibility.

Application Management:
- [x] HLE DSP does not properly support putting the DSP to sleep. This is needed for games to properly transition to the home menu. Currently games can range from having minor audio glitches when suspending to hanging trying to put the DSP to sleep.
- [ ] The kernel does not have full cleanup of process resources on exit. Currently we release the process from the process list, which will free its handles. However we should also free any resources owned by the process that exited, regardless of what other stale handles may exist to them.
- [x] The kernel does not currently support exiting a process with non-waiting threads. Unknown what the blocker is here; we can skip the assert and exit the process but later on launching another app will hang. Could be related to the resource cleanup issue. Causes a number of crashes exiting certain games or applets.
- [x] There’s a memory bug when launching sometimes, where the guest will try to break execution on a failed memory allocation and then perform really slowly hitting a lot of unmapped memory accesses.
- [ ] The kernel does not support terminating running processes currently. This doesn’t seem to cause any issues currently as long as the process exits itself properly, but if anything misbehaves APT can’t terminate it like it would in real hardware.

Applets:
- [x] ~~The internet browser has issues mapping some CROs into memory which causes unmapped memory accesses and a hang when you try to use it.~~ Fixed in https://github.com/citra-emu/citra/pull/6407
- [x] ~~The instruction manual applet does not load, getting stuck when the home menu tries to send over the parameters for what manual to load to the applet.~~ Fixed in https://github.com/citra-emu/citra/pull/6409
- [x] ~~The Miiverse applet button on the home menu currently complains about needing a system update for some reason.~~ Fixed by correcting installation and reading of NVer title.

**Comment by SinaMegapolis** [comment]
Would it be possible to implement region-breaking HOME menus as a settings option? So that the menu can display any installed title regardless of the region

**Comment by Adamillo** [comment]
What's also interesting to takes notes in the compatibility list is the fact that DSP LLE has no audio output on the home menu at all

**Comment by Rulumi** [comment]
Both DSP LLE options seems to work fine with the Home Menu.

**Comment by Steveice10** [comment]
Closing this out, most of these points are now resolved and anything further can be handled case-by-case.
