### ISSUE TITLE
Persona Q2 Softlocking at certain times.

### ISSUE THREAD

**Issue by stepsy** [citra-emu/citra#6329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canery 2416

### Description of Issue

When I play the game. It seems to softlock at random times. Either during when a character talks or a dungeon. The music in the game is still playing but I can't progress or press anything.

The only way to progress through the game is to use save states.

I genuinely don't know what causes the softlock issue.

Here is what I mean.
![Screenshot_20230304_220719](https://user-images.githubusercontent.com/114864941/222907220-19dca304-cc6c-48f6-b91a-ff8d194bf2b0.jpg)

It's on fast forward but it's not moving.

The softlocking happened on either Canery and Nightly builds

### Expected Behavior

It's supposed to progress the game.

### Reproduction Steps

Play the game and wait for the softlock to happen.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/10888865/citra_log.txt)

### System Configuration

CPU: Snapdragon 680
GPU/Driver: Snapdragon 680
RAM:8
OS:Android 12

**Comment by Zer077** [comment]
This happen to me too, on Steam Deck in the last Version nightly-1855

I was tested that de Freeze is random, sometimes it takes 10 minutes, other times 30 minutes... Is inconsistent

**Comment by Arrowsden** [comment]
I'm not sure what's *causing* the bug, but it appears that it only happens during dialogue. No other times.

**Comment by Invadetor** [comment]
Dude I had the same problem and it seems to work 100% fine without any stutter or freezing if you use Citra Nightly 1675! I've only played for an hour straight so maybe I just couldn't see them, but I'm positive it is working correctly. The only con is that you can't use fastfoward in this old version of Citra ahah!

**Comment by GabrielSorienni** [comment]
I'm currently testing for this issue and other PQ2 bugs, and it appears to be happening on newer versions and not older ones like Invadetor suggested. If anyone is interested in helping pinpoint the exact version where this started, check out [this thread on the Forum](https://community.citra-emu.org/t/possible-regression-for-persona-q2/763808). I'd appreciate anyone who could double-check my work by reproducing these issues.

**Comment by SleepingSnakezzz** [comment]
Some people have reported that turning off New 3DS Mode in Citra's system settings prevents these softlocks from occurring. Please try this out and see if this works for you. If it does, that would be useful information.

**Comment by stepsy** [comment]
> Some people have reported that turning off New 3DS Mode in Citra's system settings prevents these softlocks from occurring. Please try this out and see if this works for you. If it does, that would be useful information.

Okay, turned off New 3ds mode in config file and did an hour long playthrough. Seems to have no softlocks as far as I can tell. 

This is on latest canary with vulkan.

**Comment by SleepingSnakezzz** [comment]
Could you also try with OpenGL on the latest Nightly build?

**Comment by stepsy** [comment]
> Could you also try with OpenGL on the latest Nightly build?

Alright, tested on latest nightly with new 3ds turned off. Seems to have no softlocks so far. I'm only 35 minutes in the game (I'm starting a new game. I can play for longer if you want.)

**Comment by Zer077** [comment]
> > Some people have reported that turning off New 3DS Mode in Citra's system settings prevents these softlocks from occurring. Please try this out and see if this works for you. If it does, that would be useful information.
> 
> Okay, turned off New 3ds mode in config file and did an hour long playthrough. Seems to have no softlocks as far as I can tell.
> 
> This is on latest canary with vulkan.

If you Turn off New 3ds mode works fine. 1h in the game

**Comment by MajoraMaker8120** [comment]
It still happens on the latest builds. Turning off new 3ds mode is the only way to fix it.

**Comment by GPUCode** [comment]
Can someone test if this is fixed in latest nightly?

**Comment by stepsy** [comment]
Tested with Canary 2778 with new 3ds mode on.
Over an hour of gameplay and haven't seen any freezes/soft locking yet. 
Not closing this issue yet. Need more hours in the game/people to confirm it.

**Comment by Dragios** [comment]
Could have been solved by PR #7159.
If you have time to do further testing, try compare between [Nightly-2034](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-2034) vs [Nightly-2035](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-2035)

**Comment by stepsy** [comment]
Closing due to encountering no issues for hours.
Will reopen if any issues pop up.
