### ISSUE TITLE
Citra only supports OpenGL versions above 3.2

### ISSUE THREAD

**Issue by ILOVEPIE** [citra-emu/citra#633]
the QT interface when running on fedora 20 displays only what occupied that screen space beforehand. when the interface is put in multi-window mode the display window shows only what occupied it's screen space beforehand while the main window displays correctly.

**Comment by yuriks** [comment]
Have you started a game?

**Comment by ILOVEPIE** [comment]
yes, nothing happens.

**Comment by archshift** [comment]
What version of GL is available with your drivers?

**Comment by jroweboy** [comment]
This sounds like #174 where it is not clearing the area while the emulator is not running.

**Comment by archshift** [comment]
The real issue here is that your OpenGL version is too low:

`[12:39:01]  <ILOVEPIE>	yeah mine [OpenGL] goes up to 3.0`

Citra, however, really should support GL versions below 3.2.

**Comment by ILOVEPIE** [comment]
Well i've managed to make a branch that lowers the glsl support requirement from 1.5 to 1.3

**Comment by baka0815** [comment]
Is this still open? Do we really want to support OpenGL below 3.2?
On Linux any current system supports OpenGL 4.0+ and even the lower AMD cards using r600 support at least OpenGL 3.3. MacOS also supports OpenGL 4.0+.
