### ISSUE TITLE
boot home menu says that rom is incompatible

### ISSUE THREAD

**Issue by tommogus** [citra-emu/citra#6342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

canary 2419

### Description of Issue

try to boot home menu says that the rom is incompatible

### Expected Behavior

to boot the home menu

### Reproduction Steps

go to file cilck boot home menu

### Log File

dont have

### System Configuration

CPU: intel core i5
GPU/Driver: nvidia geforce 710m laptop
RAM:8G
OS:Windows 10

**Comment by SleepingSnakezzz** [comment]
This is an issue tracker for developers, not a support forum. Please ask for support in one of these places first:
Citra Discord server: https://discord.gg/FAXfZV9
Citra forums: https://community.citra-emu.org/

**Comment by tommogus** [comment]
opps sorry

**Comment by franzmcfreya** [comment]
@tommogus how did you fix this
