### ISSUE TITLE
Vulkan experimental smash bros lag

### ISSUE THREAD

**Issue by Fbn316** [citra-emu/citra#6350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Vulkan 

### Description of Issue

Smash bros lag 

### Expected Behavior

Smash bros lag 

### Reproduction Steps

https://user-images.githubusercontent.com/108166313/224874098-1819560e-65bc-4457-a165-7fa7395c7409.mp4

### Log File

https://user-images.githubusercontent.com/108166313/224873883-2800c71c-7239-478d-9696-9c47a10a05f9.mp4

### System Configuration

CPU:
GPU/Driver:
RAM: 8
OS: androide 12

**Comment by SachinVin** [comment]
Issues for Vulkan should be reported on discord.
