### ISSUE TITLE
citra crashes when loading game

### ISSUE THREAD

**Issue by izzura** [citra-emu/citra#6369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

i cant start the game.when i double-click the game,it will crash and close.this just happen when i update citra.the latest update is 2430(citra canary).plz help.i have try everything but still cant.it never happen before.i have play this citra with cheat for a year.
[citra_log.txt](https://github.com/citra-emu/citra/files/11068655/citra_log.txt)

### Why would this feature be useful?

fix the 30 fps to 60 fps if can

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
