### ISSUE TITLE
Installing .cia files broken as of Nightly 1862 on Android

### ISSUE THREAD

**Issue by sakuramipha** [citra-emu/citra#6370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1862 onwards

### Description of Issue

After the implementation of SAF, .cia files now are broken on Citra Android. They cannot be installed without Citra crashing, cause the game to not work once installed and result in "Unmapped Read" spam in the log file, which is usually indicative of Citra running into something corrupted. 

@hank121314 Ping as you worked on SAF (also, can you join the Discord server so we can give you the dev role and talk more about SAF stuff with other devs?)

### Expected Behavior

Installing a .cia works and allows for the update/DLC file to work properly in game.

### Reproduction Steps

1 - Launch any version of Citra Android with SAF
2 - Install a .CIA file
3 - Once Citra has crashed, restart it.
4 - Launch the game

### Log File

[citra_log.txt.old.zip](https://github.com/citra-emu/citra/files/11070433/citra_log.txt.old.zip)

### System Configuration

SOC/Driver: Snapdragon 865, Adreno 650. Driver: OpenGL ES 3.2 V@0502.0
RAM: 12GB
OS: Android 12, ColorOS V12.1

**Comment by SleepingSnakezzz** [comment]
Discord invite: https://discord.gg/FAXfZV9

**Comment by stepsy** [comment]
Can i add that loading amiibos are broken on Android?

**Comment by sakuramipha** [comment]
> Can i add that loading amiibos are broken on Android?

Test if this is a SAF issue by using an artifact from that PR first, if you can. If it isn't open an issue of your own. Would test it myself but can't because of this issue lol

**Comment by stepsy** [comment]
> > Can i add that loading amiibos are broken on Android?
> 
> Test if this is a SAF issue by using an artifact from that PR first, if you can. If it isn't open an issue of your own. Would test it myself but can't because of this issue lol

It was working before the saf merge. Now it just spits out an error.

**Comment by hank121314** [comment]
That is weird, I was not able to reproduce it.
Can you provide the log when cia installation crashing?

**Comment by hank121314** [comment]
> Can i add that loading amiibos are broken on Android?

I am able to reproduce it, will open a PR later, many thanks for the report! 🙇

**Comment by SleepingSnakezzz** [comment]
@hank121314 Hey, I was wondering if you might have some ideas on how to speed up the loading of the title list on Android. After SAF, loading a large title library takes a very long time compared to before.

**Comment by SachinVin** [comment]
So, CIA do install fine, it is just very, very, slow, and since the whole thing runs on the UI thread, I assume android thinks the app is not responding and interrupts install, leading to broken updates on subsequent launches.

**Comment by sakuramipha** [comment]
> > They cannot be installed without Citra crashing, cause the game to not work once installed 
> 
> That is weird, I was not able to reproduce it.
> Can you provide the log when cia installation crashing?

![citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/11072380/citra_log.txt.old.txt)

The log file is reporting that the .cia file is encrypted, which is incorrect too.
