### ISSUE TITLE
Android Hardware Shader white textures in Pokemon games

### ISSUE THREAD

**Issue by KostaSaizo7** [citra-emu/citra#6371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1865 / Canary 2431

### Description of Issue

This a known issue (https://github.com/citra-emu/citra-android/issues/97,) but since https://github.com/citra-emu/citra-android was archived, I thought of moving it here.
Hardware shader on:
![b](https://user-images.githubusercontent.com/39852873/227759576-34ef1aeb-7779-46b1-864f-ae2ab9544d1d.jpg)

### Expected Behavior

Hardware shader off:
![a](https://user-images.githubusercontent.com/39852873/227759429-31e59f9a-a93d-4748-bd06-71634eef7d6d.jpg)

### Reproduction Steps

1. In Settings>Debug, turn "Enable hardware shader" on
2. Launch a Pokemon gen6 game and look at the water starter pokemon

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11070940/citra_log.txt)

### System Configuration

CPU: Qualcomm Snapdragon 765G
GPU/Driver: Qualcomm Adreno 620
RAM: 6GB
OS: Android 12

**Comment by KostaSaizo7** [comment]
In latest nightly (2026) and canary (2676), this bug occurs even with hardware shader off.

**Comment by KostaSaizo7** [comment]
In my Adreno 620, this is fixed by using PR #7108 and installing [Mesa Turnip Driver](https://github.com/K11MCH1/AdrenoToolsDrivers/releases).

![image](https://github.com/citra-emu/citra/assets/39852873/54b29ef0-3c47-48f1-afee-03697b8a817b)![image](https://github.com/citra-emu/citra/assets/39852873/23214875-c6a7-4541-ab7c-44b481757211)

**Comment by GPUCode** [comment]
This is a qcom driver issue that's fixed by turnip, so marking this as closed
