### ISSUE TITLE
Feature Request - Set up cheat codes in/out of games.

### ISSUE THREAD

**Issue by stepsy** [citra-emu/citra#6380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

As Citra stands right now. You can only set cheat codes in game. You can't set cheat codes outside of games. Plenty of emulators can let you set cheat codes when not running a game.

### Why would this feature be useful?

It would make it easier for the user to set cheat codes outside of games.

**Comment by luc-git** [comment]
We can close this issue
