### ISSUE TITLE
Citra Canary crashes when starting a game when internal resolution is set to "Auto (Window Size)"

### ISSUE THREAD

**Issue by SuperFromND** [citra-emu/citra#6384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2433

### Description of Issue

If Citra's internal resolution setting is set to "Auto (Window Size)" and one attempts to start a game, Citra will immediately crash. This only occurs if the backend is set to OpenGL; software rendering does not have this issue by its very nature.

This crash can be avoided by setting the internal resolution to anything else.

### Expected Behavior

Auto (Window Size) usually defaults to whatever resolution will fit within the size of the current window, assuming the default setting of "Single Window Mode" is enabled.

### Reproduction Steps

- Go to Emulation -> Configure.
- In the Graphics panel, set the Internal Resolution option to "Auto (Window Size)".
- Start any game or application.

### Log File

The crash mentioned above happens so quickly that the full contents of the log do not actually get printed to file in time. Nevertheless, here is my log file:

[citra_log.txt](https://github.com/citra-emu/citra/files/11096563/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 5 3600X
GPU/Driver: Nvidia RTX 3060 Ti
RAM: 32 GB @ 3000 MhZ
OS: Windows 10 Professional

**Comment by GPUCode** [comment]
Fixed in #6378

**Comment by SuperFromND** [comment]
Just tested latest Canary (2434), can confirm this is fixed now. Closing. 👍
