### ISSUE TITLE
Citra Android - Config.ini file is getting overwritten when settings are saved.

### ISSUE THREAD

**Issue by SleepingSnakezzz** [citra-emu/citra#6406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1862

### Description of Issue

When saving your settings in Citra Android, the config.ini file seems like it's getting overwritten by a different file entirely. Leading to some settings not being saved at all properly. I first noticed this when I was trying to enable the Debug Renderer in the GUI debug settings. As an example:

config.ini file before toggling the Debug Renderer in the GUI:
![image](https://user-images.githubusercontent.com/71992016/229309596-d66f2fdb-317b-4b53-a5a9-1304ad89d6e1.png)

config.ini file After Toggling the Debug Renderer in the GUI:
![image](https://user-images.githubusercontent.com/71992016/229309636-0627a708-f228-4798-9a89-e23bf67e999f.png)

A developer commented on it saying that this was likely at fault: https://github.com/citra-emu/citra/blob/b5d6f645bd67633f54b96aa0bd500ca750d17e1e/src/android/app/src/main/java/org/citra/citra_emu/features/settings/utils/SettingsFile.java#L236
They said "This uses the default file mode which is “w”, which with Android 10+ storage APIs is write without truncate"

@hank121314 since this appears to be related to SAF, we'd appreciate it if you could take a look.

### Expected Behavior

Settings should get properly saved to the config file after changing them in the GUI.

### Reproduction Steps

Delete the old config file. Let Citra create a new config file. Activate the debug renderer in the GUI's Debug settings, exit out of the setting menu to save the settings, then open up the config.ini file and see the weirdness.

### Log File

A log file doesn't reveal any useful information. Other than confirming that settings like the Debug Renderer were not enabled properly.

### System Configuration

Device: Poco x3 Pro
SoC: Snapdragon 860
Android 12 MiUI

**Comment by hank121314** [comment]
Many thanks for the report and the detail description!
