### ISSUE TITLE
[Citra Nightly - Linux] Citra version 1867 and above crashes on Linux

### ISSUE THREAD

**Issue by nz0543** [citra-emu/citra#6411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1867 and above

### Description of Issue

Citra crashes on Linux right after you launch a game, this happens from nightly version 1867 and above. This issue does not occur on nightly 1866. I have tested with the citra binary from the releases page on github and attached a log file for nightly 1866 and the latest one since writing this, nightly 1874. This issue also occurs with citra flatpak. 

### Expected Behavior

Launching a game is not supposed to crash citra.

### Reproduction Steps

Launch a game on citra nightly version 1867 and above and it will crash on Linux.

### Log File

[citra_log-nightly-1866.txt](https://github.com/citra-emu/citra/files/11136576/citra_log-nightly-1866.txt)
[citra_log-nightly-1874.txt](https://github.com/citra-emu/citra/files/11136577/citra_log-nightly-1874.txt)

### System Configuration

CPU: AMD Athlon Silver 3050U with Radeon
GPU/Driver: AMD ATI Radeon Vega Series/mesa 23.0.1-1
RAM: 6 GB 
OS: Arch Linux x86_64

**Comment by GPUCode** [comment]
Could you run citra with gdb to get a stack trace?

**Comment by nz0543** [comment]
Hmmm, how do I do that by the way?

**Comment by GPUCode** [comment]
I would recommend joining our discord server if you haven't already. This way you can showcase the issue to us and we can fix it much faster

**Comment by nz0543** [comment]
https://github.com/citra-emu/citra/pull/6412
This pull request seems to fix my issue.

**Comment by purpasmart96** [comment]
For a temporary solution, use `env GDK_BACKEND=x11` as an argument before launching citra. For the flatpak version just disable Wayland for citra using flatseal.
