### ISSUE TITLE
[Feature Request] Add user directory (and ROM directory) file path somewhere within Citra Android's GUI

### ISSUE THREAD

**Issue by SleepingSnakezzz** [citra-emu/citra#6420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add a way in Citra's GUI to find the folder path for the custom Citra user folder, and Citra ROMs folder locations.

### Why would this feature be useful?

It is easy for non-tech savvy users to forget what folder they've selected for their Citra user folder and their ROMs folder on Citra Android, since the SAF implementation allows for users to set both folders wherever users wish. 

This means that when we direct users to troubleshoot, support needs to be able to guide users to the user's custom Citra user folder. And if the user does not know where this folder is, we cannot guide them.

So, with an option to find out the folder path in Citra's GUI, this issue would be solved. 

@hank121314 It'd appreciate it if you could take a look into adding this🙏(I realize that making you add this exact directory logging in the log file in the SAF PR, was probably not the best idea from my end....sorry about that)

**Comment by hank121314** [comment]
I have created a folder path label at the top of the game list. Is this UI appearance acceptable?

![image](https://github.com/citra-emu/citra/assets/17615229/0b6e020d-2085-4fba-ba93-5b2aebc93bc1)

Please feel free to tell me if you have any UI idea!

**Comment by SleepingSnakezzz** [comment]
Hi there! It looks good, however we're currently working on some something that will change a lot of the UI stuff, so we may need to wait with this until after that. On that note, we'd love it if you could join our Discord server to further discuss this type of stuff more easily (it's where almost all of the Citra development related discussions take place 😄): https://discord.gg/FAXfZV9

**Comment by hank121314** [comment]
> Hi there! It looks good, however we're currently working on some something that will change a lot of the UI stuff, so we may need to wait with this until after that. 

Got it! Looking forward to it!

> On that note, we'd love it if you could join our Discord server to further discuss this type of stuff more easily 

I have already join the Discord server. My id is 可愛的柳丁皮.
