### ISSUE TITLE
Important announcement about citra

### ISSUE THREAD

**Issue by rgbarros120** [citra-emu/citra#6425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2447

### Description of Issue

Hello goodnight. I'm sending this message to the citra development team, just to let them know that it's no longer possible to put the texture pack in the emulator. Please review this for immediate correction as in older builds it was working normally. I ask for the repair as soon as possible. Thanks.

### Expected Behavior

Nothing

### Reproduction Steps

Nothing

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11184481/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/11184482/citra_log.txt.old.txt)

### System Configuration

CPU: ryzen 5 1600
GPU/Driver: galax gtx 1650
RAM: 16gb 
OS: Windows 10

**Comment by MT19048** [comment]
From the citra-updates channel on the Citra Discord:
Canary 2443
```- Rasterizer cache refactor [#6375]
 > Part 2 of a series of PRs that breaks up the currently rather massive Vulkan PR into multiple pieces to allow for easier reviewing and testing 
 > This will improve Citra's performance with Mali GPUs by about 40%.
 > As a consequence of the improvements, the old Custom Textures implementation had to be axed. As soon as this PR has been tested and reviewed it will get merged into Nightly, after which we will put another PR into Canary which will add a rewritten Custom Textures implementation. So, if you're using Custom Textures USE NIGHTLY FOR NOW!

**Comment by SachinVin** [comment]
This is an issue tracker for developers, not a support forum. Please ask for support in one of these places first:
Citra Discord server: https://discord.gg/FAXfZV9
Citra forums: https://community.citra-emu.org/
