### ISSUE TITLE
Citra crashing trying to read transferable shader cache

### ISSUE THREAD

**Issue by SachinVin** [citra-emu/citra#6429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Post #6344

### Description of Issue

For some reason nullopt isn't returned here, instead a vector of zero size is returned, then trying to decompression it aborts - https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/gl_shader_disk_cache.cpp#L159
So a couple of questions here is

Why does reading the raw fails in the first place?
Why is a nullopt not returned here

### Expected Behavior

Read file without crashing

### Reproduction Steps

Unknown, seems to happen only sometimes for some users 

### Log File

TODO

### System Configuration

CPU: Any
GPU/Driver: Any?
RAM: Any
OS: Windows

**Comment by SomeKitten** [comment]
Possibly relevant mod for reproduction:
`romfs/BAI/BAI.dat`
https://drive.google.com/file/d/1m-2mVAG-H3FpFmF4gc_ninhk3lgOPHXY/view?usp=sharing

Crash occurs when using the jump attack as Mario in battle (due to my malformed edit). This crash seems to corrupt shaders sometimes :)

**Comment by SachinVin** [comment]
@SomeKitten can you test the artifacts on #6483

**Comment by SomeKitten** [comment]
I've caused a few crashes with it and the issue seems to be resolved!!! :D
I will give an update if I manage to cause the issue again with the new build!

**Comment by SachinVin** [comment]
Thanks for testing!
Sorry, I got distracted and couldn't reply
