### ISSUE TITLE
Citra Gdrive sync crash

### ISSUE THREAD

**Issue by FredericVincent0** [citra-emu/citra#6437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary-2451

### Description of Issue

when i sync save folder with gdrive or other the games list refreshes and citra crashes

### Expected Behavior

Citra crash

### Reproduction Steps

sync citra backup folder with gdrive or other

### Log File

N/A

### System Configuration

CPU: Ryzenx 5
GPU/Driver: Nvidia GeForce RTX 2060
RAM: 16G
OS: Windows 10

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord server or our forum for support requests.
