### ISSUE TITLE
Citra crash after opening a game

### ISSUE THREAD

**Issue by Fernando11101** [citra-emu/citra#6442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2453

### Description of Issue

The emulator crash after the opening a game.

### Expected Behavior

In Canary 2451 The game loads perfectly.

https://user-images.githubusercontent.com/44506229/232276795-6c216411-8d47-4aff-9143-8745de3e48b1.mp4

In Canary 2453 The game after loads the emulator immediately crash.

https://user-images.githubusercontent.com/44506229/232276797-6e8b3e11-2b90-4d0f-b04d-77e4fedaff73.mp4

### Reproduction Steps

Open any game, after wait and will see that the emulator crashes immediately.

### Log File

Log - Canary 2451
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/11241304/citra_log.txt.old.txt)

Log - Canary 2453
[citra_log.txt](https://github.com/citra-emu/citra/files/11241308/citra_log.txt)

### System Configuration

CPU: AMD A4-9125 RADEON R3
GPU/Driver: AMD Radeon(TM) R3 Graphics
RAM: 4GB
OS: Windows 10

**Comment by GPUCode** [comment]
Please try latest nightly, feel free to reopen if this still occurs
