### ISSUE TITLE
Unable to launch games in Wayland

### ISSUE THREAD

**Issue by MarkGhanz** [citra-emu/citra#6445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1877

### Description of Issue

I opened the emulator through the terminal and launched Mario Kart 7. Although no errors appeared on the terminal, the game doesn't showed up and the display region for the game becomes transparent. On GNOME it returns a black screen.
Also, after launching Pokemon Ultra Sun, the emulator crashes with the following terminal output:
`QWaylandGLContext::makeCurrent: eglError: 3002, this: 0x7fca7416a980`
I have tried on GNOME with 150% scaling (experimental) and Hyprland without scaling. On GNOME Xorg, the game starts normally.

### Expected Behavior

The game showed up without errors in the emulator after launching.

### Reproduction Steps

1. Open Citra (flatpak) on a DE or WM with wayland backend with `QT_QPA_PLATFORM=wayland` environment variable
2. Launch a game.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11255338/citra_log.txt) for Pokemon Ultra Sun

### System Configuration

CPU: Intel i5-1135G7
GPU/Driver: Mesa Intel(R) Xe Graphics (TGL GT2)
RAM: 16GB DDR4 3200
OS: Arch Linux
Kernel: 6.2.11-arch1-1

**Comment by GPUCode** [comment]
Has been fixed in newer nightlies by #6412, please update. If the issue persists feel free to reopen
