### ISSUE TITLE
Canary 2461 terminated after loading state

### ISSUE THREAD

**Issue by lasers** [citra-emu/citra#6455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2461

### Description of Issue

Loading a game state after updating canary threw this. Just FYI.
```
./citra-canary/bin/citra-qt
terminate called after throwing an instance of 'std::out_of_range'
  what():  unordered_map::at
terminated by signal SIGABRT (Abort)
```

### Expected Behavior

Silently deal with the issue.

### Reproduction Steps

Not sure if it's reproduction. Here it is.
1) Save state.
2) Update Canary.
3) Load state.

### Log File

Possible log.
```
[  22.120065] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:806: ClCertA file missing
[  22.145205] Kernel <Info> core/hle/kernel/process.cpp:~Process:478: Cleaning up process 127
[  22.185878] Core <Error> core/core.cpp:RunLoop:122: Error loading: unregistered class
```

### System Configuration

CPU: 5700G
GPU/Driver: NVIDIA RTX 3060
RAM: 16GB
OS: NixOS

**Comment by SachinVin** [comment]
Save states are not transferable between versions

**Comment by lasers** [comment]
The issue is about error though. Should this be silently ignored... instead of getting citra terminated?

**Comment by SachinVin** [comment]
if you mean `[  22.185878] Core <Error> core/core.cpp:RunLoop:122: Error loading: unregistered class`
the error happens when a class is added, removed or renamed, between the previous or current version of citra. it is only an issue if it happens when you load a state that was created on the same version.
