### ISSUE TITLE
Danball Senki W Chou Custom: Unmapped Read32 errors preventing game from working.

### ISSUE THREAD

**Issue by pla-sma** [citra-emu/citra#6457]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Nightly 1885 / Canary 2461

### Description of Issue

Loading Danball Senki W Chou Custom will load the below screen, then crash to a black screen when you press A. The log attached shows that it is a 'HW.Memory <Error> core/memory.cpp:Read:469: unmapped Read32 @ ', with hundreds of addresses appearing. It continues to do this for a long time, so I closed the program to log some of it. I read that this error means a corrupted dump, but I have dumped it with several programs and it all ends the same. The same dump that doesn't work in Citra, does run on my N3DSXL with no issues.

I know we shouldn't mention unofficial Citra builds, but weihouyas for Android does have this game working, so it is possible, but of course, there's no working option for PC users.

![image](https://user-images.githubusercontent.com/56777153/233796314-703a19fd-ba33-4f92-a421-15246a019fc1.png)

### Expected Behavior

Game should load past the screen that it gets stuck on.

### Reproduction Steps

Boot up Danball Senki W Chou Custom in any Citra build.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11301805/citra_log.txt)

### System Configuration

CPU: Ryzen-9 5950X
GPU/Driver: RTX 3080
RAM: 128GB
OS: Win11

**Comment by pla-sma** [comment]
As a test, I implemented weihouyas fix they posted as a commit here (https://github.com/citra-emu/citra/pull/5379/commits/9764e2aeda32d206c8a5067f84de3c7be62c035d) and the game itself now boots, saves and loads perfectly fine - however, now I get a strange duplicate shadow model problem 

![image](https://user-images.githubusercontent.com/56777153/234337378-cb0b4f42-7657-4af4-ac95-5d8d1f3864b4.png)


Any ideas? Its clear that the game CAN work on Citra.

**Comment by HaidenaX** [comment]
Hey, so i'm new to this and i was wondering how do you put this fox on citra

i'm bored of playing this on PPSP

**Comment by pla-sma** [comment]
As of Citra Canary 2548, this is now fixed, the games boot, which is something that couldn't be done beforehand. Thank you all!
