### ISSUE TITLE
Unimplemented function 'ControlArchive'

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

latest nightly and canary

### Description of Issue

have come across this in a few games now
[  26.842443] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:163: unknown / unimplemented function 'ControlArchive': port='fs:USER' cmd_buf={[0]=0x80d0144, [1]=0x5, [2]=0x0, [3]=0x0, [4]=0x1, [5]=0x1, [6]=0x1a, [7]=0x0, [8]=0x1c, [9]=0x1}

### Expected Behavior

N/A

### Reproduction Steps

N/A

### Log File

N/A

### System Configuration

CPU:Ryzen 7 5700x
GPU/Driver:RTX 3060
RAM:32G
OS:Windows 11

**Comment by SachinVin** [comment]
Closing, because this isn't associated with any issues in games

**Comment by benderscruffy** [comment]
why does it say then 
ReportUnimplementedFunction

**Comment by B3n30** [comment]
This log entry is for developers to figure out why something isn't working. But there can be a lot of unimplemented functions but games will still run fine. So as long as it isn't impacting games those log lines can just be ignored and the existence of such line in the logs alone is not a reason to open an issue
