### ISSUE TITLE
The texture with the same filename as the custom texture is dumped again.

### ISSUE THREAD

**Issue by kevin98761234** [citra-emu/citra#6466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2461

### Description of Issue

In the current Canary build, if the two options "UseCustomTextures" and "DumpTextures" are enabled, textures with the same file name as the loaded custom textures will be dumped.
Previously, textures with the same name as the loaded custom texture were not dumped.

The current specification is very confusing when creating custom textures and requires tedious verification.

Could you please revert to the previous specification?

### Expected Behavior

Textures with the same name as the custom texture will not be dumped.

### Reproduction Steps

Start citra. Dump the texture.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11306540/citra_log.txt)

### System Configuration

CPU:Intel(R) Core(TM) i3-8300 CPU @ 3.70GHz | AVX2 | FMA
GPU/Driver:NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 NVIDIA 531.61
RAM:15.94 GiB
OS:Windows 10 Version 22H2 (Build 19045.2846)

**Comment by GPUCode** [comment]
Should be fixed in the next canary

**Comment by kevin98761234** [comment]
Canary2465 confirmed that textures with the same filename as the custom textures are not dumped. Great job! Thanks!
