### ISSUE TITLE
Mario Kart 7 corrupt graphics using Software renderer

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

latest nightly and canary

### Description of Issue

using software renderer the graphics are corrupt
![Screenshot 2023-04-25 154609](https://user-images.githubusercontent.com/2696404/234210029-50736e52-2e28-40fc-82c8-422280e4203a.png)

### Expected Behavior

no corruption

### Reproduction Steps

just load game

### Log File

nothing in the log file

### System Configuration

CPU:Ryzen 7 5700x
GPU/Driver:RTX 3060
RAM:32G
OS:Windows 11

**Comment by PabloMK7** [comment]
When does this happen? Does it "fix" when reaching the title screen?

**Comment by benderscruffy** [comment]
No that is the mii maker screen and when it gets to the title screen both top and bottom screen are corrupt

**Comment by benderscruffy** [comment]
and this is the title screen and menu 
![Screenshot 2023-04-26 141938](https://user-images.githubusercontent.com/2696404/234486467-8c1c03b6-dd32-4195-9b9b-1700d5c55b92.png)

**Comment by benderscruffy** [comment]
using canary 2602 
graphics are fixed
