### ISSUE TITLE
Sound disappears after unpausing the game coming back from a PC sleep state

### ISSUE THREAD

**Issue by danilaml** [citra-emu/citra#6474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1888

### Description of Issue

After pausing the game (F4) in the emulator, and putting the laptop in the sleep mode, the sound is no longer there after waking it up and unpausing. So I have to restart the paused game. Only tested on a few Professor Layton games (Miracle Mask specifically).

### Expected Behavior

The sound remains after unpausing.

### Reproduction Steps

1. Launch the game, confirm the sound is on.
2. Pause the game (F4).
3. Enter PC in sleep mode.
4. Wait some time. Wake it up.
5. Unpause the game.
6. Verify that the sound is gone.

### Log File

[citra_log.zip](https://github.com/citra-emu/citra/files/11340892/citra_log.zip)

### System Configuration

CPU: i7-8550U
GPU/Driver: MX150/527.56
RAM: 16 GB
OS: Win10 x64

**Comment by danilaml** [comment]
Seems to be the same issue as https://github.com/yuzu-emu/yuzu/issues/7499 .
The underlying issue is how cubeb handles timout events that happen when PC goes to sleep: https://github.com/mozilla/cubeb/blob/master/src/cubeb_wasapi.cpp#L1404

At some point long ago the timeout was reduced from 3 to 5 seconds to help with some Firefox issue, which means that sleep triggers error most of the time now.

Don't know why Dolphin is seemingly unaffected according to yuzu issue (unless it is).
Perhaps some sort of automatic stream restart in case this happens would work. Alternatively, there is a MR on review that will likely fix this issue (as it rewrites this part of cubeb entirely), but it's been in "approved, going to merge soon" state for 3+ years: https://github.com/mozilla/cubeb/pull/542

**Comment by Steveice10** [comment]
There’s a PR in Canary right now that adds OpenAL as another audio output option, you could try that and see if it doesn’t suffer from this issue.

**Comment by danilaml** [comment]
It probably doesn't, just like sdl2. But cubeb is supposed to be better in terms of latency.
