### ISSUE TITLE
LLVM failed to upload shader

### ISSUE THREAD

**Issue by EnderMk9** [citra-emu/citra#6476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1893

### Description of Issue

I recently upgraded mesa drivers in Fedora 38 to version 23.0.3-1, and when loading any game in citra either it shows a black screen or the rendered graphics are very glitchy, i get the following message in the console

LLVM failed to upload shader
EE ../src/gallium/drivers/radeonsi/si_state_shaders.cpp:2557 si_build_shader_variant - Failed to build shader variant (type=3)

### Expected Behavior

The games render properly

### Reproduction Steps

Install fedora 38 and upgrade the packages to the latest version, particularly the mesa packages to version 23.0.3-1

### Log File

[   0.000034] Config <Info> common/settings.cpp:LogSettings:95: Citra Configuration:
[   0.000037] Config <Info> common/settings.cpp:operator():81: Core_UseCpuJit: true
[   0.000039] Config <Info> common/settings.cpp:operator():81: Core_CPUClockPercentage: 100
[   0.000039] Config <Info> common/settings.cpp:operator():81: Renderer_UseGLES: false
[   0.000040] Config <Info> common/settings.cpp:operator():81: Renderer_UseHwRenderer: true
[   0.000040] Config <Info> common/settings.cpp:operator():81: Renderer_UseHwShader: true
[   0.000040] Config <Info> common/settings.cpp:operator():81: Renderer_SeparableShader: false
[   0.000040] Config <Info> common/settings.cpp:operator():81: Renderer_ShadersAccurateMul: true
[   0.000040] Config <Info> common/settings.cpp:operator():81: Renderer_UseShaderJit: true
[   0.000043] Config <Info> common/settings.cpp:operator():81: Renderer_UseResolutionFactor: 6
[   0.000043] Config <Info> common/settings.cpp:operator():81: Renderer_FrameLimit: 100
[   0.000043] Config <Info> common/settings.cpp:operator():81: Renderer_VSyncNew: false
[   0.000044] Config <Info> common/settings.cpp:operator():81: Renderer_PostProcessingShader: none (builtin)
[   0.000044] Config <Info> common/settings.cpp:operator():81: Renderer_FilterMode: true
[   0.000044] Config <Info> common/settings.cpp:operator():81: Renderer_TextureFilterName: xBRZ freescale
[   0.000047] Config <Info> common/settings.cpp:operator():81: Stereoscopy_Render3d: 0
[   0.000047] Config <Info> common/settings.cpp:operator():81: Stereoscopy_Factor3d: 0
[   0.000047] Config <Info> common/settings.cpp:operator():81: Stereoscopy_MonoRenderOption: 0
[   0.000048] Config <Info> common/settings.cpp:operator():81: Layout_LayoutOption: 0
[   0.000048] Config <Info> common/settings.cpp:operator():81: Layout_SwapScreen: false
[   0.000048] Config <Info> common/settings.cpp:operator():81: Layout_UprightScreen: false
[   0.000048] Config <Info> common/settings.cpp:operator():81: Utility_DumpTextures: false
[   0.000048] Config <Info> common/settings.cpp:operator():81: Utility_CustomTextures: true
[   0.000049] Config <Info> common/settings.cpp:operator():81: Utility_UseDiskShaderCache: true
[   0.000049] Config <Info> common/settings.cpp:operator():81: Audio_Emulation: HLE
[   0.000049] Config <Info> common/settings.cpp:operator():81: Audio_OutputEngine: auto
[   0.000050] Config <Info> common/settings.cpp:operator():81: Audio_EnableAudioStretching: true
[   0.000050] Config <Info> common/settings.cpp:operator():81: Audio_OutputDevice: auto
[   0.000050] Config <Info> common/settings.cpp:operator():81: Audio_InputDeviceType: 0
[   0.000050] Config <Info> common/settings.cpp:operator():81: Audio_InputDevice: Default
[   0.000051] Config <Info> common/settings.cpp:operator():81: Camera_OuterRightName: blank
[   0.000051] Config <Info> common/settings.cpp:operator():81: Camera_OuterRightConfig: 
[   0.000051] Config <Info> common/settings.cpp:operator():81: Camera_OuterRightFlip: 0
[   0.000051] Config <Info> common/settings.cpp:operator():81: Camera_InnerName: blank
[   0.000051] Config <Info> common/settings.cpp:operator():81: Camera_InnerConfig: 
[   0.000052] Config <Info> common/settings.cpp:operator():81: Camera_InnerFlip: 0
[   0.000052] Config <Info> common/settings.cpp:operator():81: Camera_OuterLeftName: blank
[   0.000052] Config <Info> common/settings.cpp:operator():81: Camera_OuterLeftConfig: 
[   0.000052] Config <Info> common/settings.cpp:operator():81: Camera_OuterLeftFlip: 0
[   0.000052] Config <Info> common/settings.cpp:operator():81: DataStorage_UseVirtualSd: true
[   0.000053] Config <Info> common/settings.cpp:operator():81: DataStorage_UseCustomStorage: false
[   0.000053] Config <Info> common/settings.cpp:operator():81: System_IsNew3ds: true
[   0.000053] Config <Info> common/settings.cpp:operator():81: System_RegionValue: -1
[   0.000053] Config <Info> common/settings.cpp:operator():81: System_PluginLoader: false
[   0.000053] Config <Info> common/settings.cpp:operator():81: System_PluginLoaderAllowed: true
[   0.000053] Config <Info> common/settings.cpp:operator():81: Debugging_UseGdbstub: false
[   0.000054] Config <Info> common/settings.cpp:operator():81: Debugging_GdbstubPort: 24689
[   0.065528] Input <Info> input_common/udp/client.cpp:StartCommunication:206: Starting communication with UDP input server on 127.0.0.1:26760
[   0.091132] Frontend <Info> citra_qt/main.cpp:GMainWindow:208: Citra Version:  | master-5eb72e948-dirty
[   0.091137] Frontend <Info> citra_qt/main.cpp:GMainWindow:224: Host CPU: AMD Ryzen 7 6800U with Radeon Graphics          | AVX2 | FMA
[   0.091156] Frontend <Info> citra_qt/main.cpp:GMainWindow:226: Host OS: Fedora Linux 38 (KDE Plasma)
[   0.091163] Frontend <Info> citra_qt/main.cpp:GMainWindow:229: Host RAM: 13.32 GiB
[   0.091164] Frontend <Info> citra_qt/main.cpp:GMainWindow:230: Host Swap: 8.00 GiB
[   0.094234] Frontend <Warning> citra_qt/game_list.cpp:LoadCompatibilityList:679: Game compatibility list is empty
[   0.094347] Frontend <Warning> citra_qt/main.cpp:CheckForUpdates:889: Unable to start check for updates
[   0.104341] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:242: Secure1 KeyX missing
[   0.104347] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:261: Secure2 KeyX missing
[   0.104348] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:347: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[  21.378993] Frontend <Info> citra_qt/main.cpp:BootGame:1086: Citra starting...
[  21.379204] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:161: 16384
[  21.379532] Frontend <Info> citra_qt/main.cpp:BootGame:1108: Using per game config file for title id 00040000000A8600
[  21.379537] Config <Info> common/settings.cpp:LogSettings:95: Citra Configuration:
[  21.379539] Config <Info> common/settings.cpp:operator():81: Core_UseCpuJit: true
[  21.379540] Config <Info> common/settings.cpp:operator():81: Core_CPUClockPercentage: 100
[  21.379541] Config <Info> common/settings.cpp:operator():81: Renderer_UseGLES: false
[  21.379542] Config <Info> common/settings.cpp:operator():81: Renderer_UseHwRenderer: true
[  21.379542] Config <Info> common/settings.cpp:operator():81: Renderer_UseHwShader: true
[  21.379543] Config <Info> common/settings.cpp:operator():81: Renderer_SeparableShader: false
[  21.379544] Config <Info> common/settings.cpp:operator():81: Renderer_ShadersAccurateMul: true
[  21.379545] Config <Info> common/settings.cpp:operator():81: Renderer_UseShaderJit: true
[  21.379545] Config <Info> common/settings.cpp:operator():81: Renderer_UseResolutionFactor: 6
[  21.379546] Config <Info> common/settings.cpp:operator():81: Renderer_FrameLimit: 100
[  21.379547] Config <Info> common/settings.cpp:operator():81: Renderer_VSyncNew: false
[  21.379547] Config <Info> common/settings.cpp:operator():81: Renderer_PostProcessingShader: none (builtin)
[  21.379548] Config <Info> common/settings.cpp:operator():81: Renderer_FilterMode: true
[  21.379551] Config <Info> common/settings.cpp:operator():81: Renderer_TextureFilterName: xBRZ freescale
[  21.379553] Config <Info> common/settings.cpp:operator():81: Stereoscopy_Render3d: 0
[  21.379553] Config <Info> common/settings.cpp:operator():81: Stereoscopy_Factor3d: 0
[  21.379555] Config <Info> common/settings.cpp:operator():81: Stereoscopy_MonoRenderOption: 0
[  21.379556] Config <Info> common/settings.cpp:operator():81: Layout_LayoutOption: 0
[  21.379557] Config <Info> common/settings.cpp:operator():81: Layout_SwapScreen: false
[  21.379557] Config <Info> common/settings.cpp:operator():81: Layout_UprightScreen: false
[  21.379558] Config <Info> common/settings.cpp:operator():81: Utility_DumpTextures: false
[  21.379558] Config <Info> common/settings.cpp:operator():81: Utility_CustomTextures: true
[  21.379559] Config <Info> common/settings.cpp:operator():81: Utility_UseDiskShaderCache: true
[  21.379560] Config <Info> common/settings.cpp:operator():81: Audio_Emulation: HLE
[  21.379561] Config <Info> common/settings.cpp:operator():81: Audio_OutputEngine: auto
[  21.379562] Config <Info> common/settings.cpp:operator():81: Audio_EnableAudioStretching: true
[  21.379562] Config <Info> common/settings.cpp:operator():81: Audio_OutputDevice: auto
[  21.379563] Config <Info> common/settings.cpp:operator():81: Audio_InputDeviceType: 0
[  21.379564] Config <Info> common/settings.cpp:operator():81: Audio_InputDevice: Default
[  21.379565] Config <Info> common/settings.cpp:operator():81: Camera_OuterRightName: blank
[  21.379566] Config <Info> common/settings.cpp:operator():81: Camera_OuterRightConfig: 
[  21.379566] Config <Info> common/settings.cpp:operator():81: Camera_OuterRightFlip: 0
[  21.379567] Config <Info> common/settings.cpp:operator():81: Camera_InnerName: blank
[  21.379568] Config <Info> common/settings.cpp:operator():81: Camera_InnerConfig: 
[  21.379568] Config <Info> common/settings.cpp:operator():81: Camera_InnerFlip: 0
[  21.379569] Config <Info> common/settings.cpp:operator():81: Camera_OuterLeftName: blank
[  21.379572] Config <Info> common/settings.cpp:operator():81: Camera_OuterLeftConfig: 
[  21.379573] Config <Info> common/settings.cpp:operator():81: Camera_OuterLeftFlip: 0
[  21.379574] Config <Info> common/settings.cpp:operator():81: DataStorage_UseVirtualSd: true
[  21.379574] Config <Info> common/settings.cpp:operator():81: DataStorage_UseCustomStorage: false
[  21.379575] Config <Info> common/settings.cpp:operator():81: System_IsNew3ds: true
[  21.379576] Config <Info> common/settings.cpp:operator():81: System_RegionValue: -1
[  21.379576] Config <Info> common/settings.cpp:operator():81: System_PluginLoader: false
[  21.379577] Config <Info> common/settings.cpp:operator():81: System_PluginLoaderAllowed: true
[  21.379578] Config <Info> common/settings.cpp:operator():81: Debugging_UseGdbstub: false
[  21.379578] Config <Info> common/settings.cpp:operator():81: Debugging_GdbstubPort: 24689
[  21.522063] Audio.Sink <Info> audio_core/cubeb_sink.cpp:StateCallback:137: Cubeb Audio Stream Started
[  21.522075] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:12: Starting RPC server ...
[  21.522281] RPC_Server <Info> core/rpc/rpc_server.cpp:HandleRequestsLoop:113: Request handler started.
[  21.522300] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:16: RPC started.
[  21.523319] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:806: ClCertA file missing
[  21.525562] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1277: GL_VERSION: 4.6 (Core Profile) Mesa 23.0.3
[  21.525564] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1278: GL_VENDOR: AMD
[  21.525564] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:1279: GL_RENDERER: AMD Radeon Graphics (rembrandt, LLVM 16.0.1, DRM 3.49, 6.2.13-300.fc38.x86_64)
[  21.530135] Render.OpenGL <Info> video_core/renderer_opengl/gl_format_reinterpreter.cpp:ShaderD24S8toRGBA8:167: Texture views are unsupported, reinterpretation will do intermediate copy
[  21.530137] Render.OpenGL <Info> video_core/renderer_opengl/gl_format_reinterpreter.cpp:FormatReinterpreterOpenGL:255: Using shader for D24S8 to RGBA8 reinterpretation
[  21.530844] Render.OpenGL <Critical> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:1254: API ERROR 2: GL_INVALID_VALUE in glthread
[  21.530846] Render.OpenGL <Critical> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:1254: API ERROR 2: GL_INVALID_OPERATION in glUniform(program not linked)
[  21.531567] Loader <Info> core/loader/ncch.cpp:Load:204: Program ID: 00040000000A8600
[  21.531590] Service.FS <Warning> core/file_sys/ncch_container.cpp:OpenFile:130: Failed to open /home/ender/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/000a8600/content/00000000.app
[  21.558601] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:147: ExHeader kernel version: 2.32
[  21.559379] Service.FS <Info> core/file_sys/ncch_container.cpp:LoadSectionExeFS:510: Attempting to load logo from the ExeFS
[  21.559497] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:SetPreferredRegionCodes:727: Preferred region code set to 2
[  21.575015] Render.OpenGL <Info> video_core/renderer_opengl/gl_shader_disk_cache.cpp:LoadTransferable:171: Found a transferable disk cache with 3 entries
[  21.575141] Render.OpenGL <Info> video_core/renderer_opengl/gl_shader_disk_cache.cpp:LoadPrecompiledFile:274: Found a precompiled disk cache with 3 decompiled entries and 3 binary entries
[  21.715056] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11
[  21.715206] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called
[  21.716374] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetLockHandle:317: (STUBBED) called applet_attributes=0X00000000
[  21.718444] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:186: (STUBBED) bit_mask=0x0000000F
[  21.718882] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000006
[  21.719287] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:296: (STUBBED) app_id=768
[  21.720612] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:590: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
[  21.720818] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:590: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  21.721346] Service.APT <Warning> core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:607: (STUBBED) called, cpu_percent=30, value=1
[  21.721583] Service.FS <Warning> core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:600: (STUBBED) called, version: 0x030301C8
[  21.722088] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[  21.731824] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[  21.736377] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000006
[  21.746289] Service.FS <Error> core/file_sys/savedata_archive.cpp:CreateFile:233: /home/ender/.local/share/citra-emu/nand/data/00000000000000000000000000000000/extdata/00048000/F000000B/user/gamecoin.dat already exists
[  21.750320] Service.PTM <Warning> core/hle/service/ptm/ptm.cpp:GetTotalStepCount:107: (STUBBED) called
[  21.761775] Service.GSP <Warning> core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:711: called flag=00000000 process=11 thread_id=0
[  21.768155] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:163: unknown / unimplemented function 'SetInternalPriorities': port='gsp::Gpu' cmd_buf={[0]=0x1e0080, [1]=0x10, [2]=0x11}
[  21.783794] Service.Y2R <Warning> core/hle/service/y2r_u.cpp:SetTransferEndInterrupt:212: (STUBBED) called
[  21.784672] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetAppCpuTimeLimit:622: (STUBBED) called, value=1
[  21.785766] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:496: Firmware hash: 0x4e08624ada4a60e0
[  21.785767] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:500: Structures hash: 0x228655de1258d999
[  21.785768] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:191: called size=0xBFFA, prog_mask=0x000000FF, data_mask=0x000000FF
[  21.786126] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:257: Registered interrupt=2, channel=2, event=event-003a40b4
[  21.786266] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:274: (STUBBED) called
[  21.786403] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:284: (STUBBED) called mask=0x2000
[  21.786609] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:257: Application has requested initialization of DSP hardware
[  21.786726] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[  21.787622] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[  21.792875] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetAppCpuTimeLimit:622: (STUBBED) called, value=1
[  21.872805] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:InitializeSession:23: (STUBBED) programID=0X0000000000000000
[  21.873145] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:GetOptoutFlag:124: output_flag=48
[  21.873368] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:GetTaskIdList:174: (STUBBED) called
[  21.873619] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:ReceiveProperty:304: (STUBBED) property_id=0X0035, size=0X00000002
[  21.873723] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:ReceiveProperty:304: (STUBBED) property_id=0X0036, size=0X00000400
[  22.422727] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:590: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  22.477139] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
[  25.142758] Service.FS <Warning> core/hle/service/fs/file.cpp:OpenLinkFile:214: (STUBBED) File command OpenLinkFile Path: [Binary: 000000000000000000000000]
[  27.839346] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:77: Non-existing file /home/ender/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/000a8600/data/00000001/game1.lt5dx can't be open without mode create.
[  27.840176] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:77: Non-existing file /home/ender/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/000a8600/data/00000001/game2.lt5dx can't be open without mode create.
[  41.094500] RPC_Server <Info> core/rpc/rpc_server.cpp:~RPCServer:20: Stopping RPC ...
[  41.094607] RPC_Server <Info> core/rpc/server.cpp:NewRequestCallback:37: Received end packet
[  41.094653] RPC_Server <Info> core/rpc/rpc_server.cpp:~RPCServer:24: RPC stopped.
[  41.095004] Audio.Sink <Info> audio_core/cubeb_sink.cpp:StateCallback:140: Cubeb Audio Stream Stopped
[  41.142142] Service.CAM <Info> citra_qt/camera/qt_multimedia_camera.cpp:StopCameras:217: Stopping all cameras
[  41.142147] Service.CAM <Info> citra_qt/camera/qt_multimedia_camera.cpp:ReleaseHandlers:236: Releasing all handlers

### System Configuration

CPU: AMD Ryzen 6800 U
GPU/Driver: AMD Radeon 680M
RAM: 16 GB
OS: Fedora 38

**Comment by GPUCode** [comment]
The log file indicates your citra version is much older than nightly 1893. This issue has been resolved in the latest nightlies but feel free to reopen if you face the issue again
