### ISSUE TITLE
LLVM failed to upload shader

### ISSUE THREAD

**Issue by EnderMk9** [citra-emu/citra#6477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1893

### Description of Issue

I recently upgraded mesa drivers in Fedora 38 to version 23.0.3-1, and when loading any game in citra either it shows a black screen or the rendered graphics are very glitchy, i get the following message in the console

LLVM failed to upload shader
EE ../src/gallium/drivers/radeonsi/si_state_shaders.cpp:2557 si_build_shader_variant - Failed to build shader variant (type=3)

Last time I opened this issue I mixed the log files of my old version of citra and the latests nightly, but this issue is happening in the latest nightly.
https://github.com/citra-emu/citra/issues/6476

### Expected Behavior

The games render properly

### Reproduction Steps

Install fedora 38 and upgrade the packages to the latest version, particularly the mesa packages to version 23.0.3-1

### Log File

https://pastebin.com/tjkAwd62

### System Configuration

CPU: AMD Ryzen 6800 U
GPU/Driver: AMD Radeon 680M
RAM: 16 GB
OS: Fedora 38

**Comment by GPUCode** [comment]
Does it crash the same way as before?

**Comment by EnderMk9** [comment]
Yes, the app does not crash, but in some games the is black screen and in others 3d does not render and the upper screen mirrons the bottom one.

**Comment by SleepingSnakezzz** [comment]
Unrelated, but please upload the log **file**, not the text. The text just clutters up the entire post, and makes things hard to read as a result.

**Comment by EnderMk9** [comment]
Done

**Comment by GPUCode** [comment]
Enable debug renderer and repost the log

**Comment by EnderMk9** [comment]
https://pastebin.com/9jMsZ6R2

**Comment by GPUCode** [comment]
I don't see anything wrong with the log file. Can you describe with more detail what issue this newer build has?

**Comment by EnderMk9** [comment]
I think the previous one is not right because the log only changes when citra closes
https://pastebin.com/BifC7eJ9

**Comment by EnderMk9** [comment]
In games like Professor Layton the canvas is completely black, but you can hear the music. In Monster Hunter 4 Ultimate textures load but both screens are the same as shown in the image.
![image](https://user-images.githubusercontent.com/16853434/235235531-997947a4-6953-4756-baa9-6d3123b83d5c.png)

**Comment by EnderMk9** [comment]
When I open citra with the terminal i get this output
https://pastebin.com/5F6X2MWq

**Comment by EnderMk9** [comment]
Furthermore in previous versions of the mesa driver it worked without problem, but this is the only software that I've encountered problems, other games and emulators work fine with 3d render.

**Comment by GPUCode** [comment]
Then something in the mesa driver, citra uses a shared context for presenting to a window and wayland doesn't seem to like those. I guess your best bet would be to wait for the pending vulkan release

**Comment by EnderMk9** [comment]
I'm loading the app in compatibility mode with X11, so wayland should have no say

**Comment by GPUCode** [comment]
Hm it depends if the opengl strict context rules applies with xwayland or not, I don't know myself about that though

**Comment by elektronicznypank** [comment]
Confirmed on Manjaro and Radeon RX 6600XT. I have same errors and only get audio, no video at all.

ac_rtld error(1): too much LDS (used = 48492, max = 32768)
LLVM failed to upload shader
EE ../mesa-23.0.3/src/gallium/drivers/radeonsi/si_state_shaders.cpp:2557 si_build_shader_variant - Failed to build shader variant (type=3)

**Comment by EnderMk9** [comment]
Update, the error is related to hardware shaders (kinda expected), if disabled in the menu, the games render, however the performance is obviously very poor. Furthermore, I tested on Canary 2490 with Vulkan and the error persists, so the problem is probably the mesa driver.

**Comment by EnderMk9** [comment]
ac_rtld error(1): too much LDS (used = 48492, max = 32768)
It may also be related to this error that mesa gives in the terminal when running citra that suggests that it using more memory than allowed

**Comment by NerosTie** [comment]
It looks like it's fixed with Mesa 23.1, can you try on your side?

**Comment by EnderMk9** [comment]
It's gonna take some time for Fedora to update so i'll have to wait

**Comment by EnderMk9** [comment]
I can confirm, on a development version of Mesa 23.2 it is fixed, so it's just a matter of the update arriving to everyone having the problem, closing this issue
