### ISSUE TITLE
citra-qt.exe remains in task manager after closing it

### ISSUE THREAD

**Issue by Gabezin64** [citra-emu/citra#6480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1893 / Canary 2466

### Description of Issue

When closing the emulator, citra-qt.exe remains in the task manager, and it is necessary to end the process every time.
The same goes for the yuzu emulator.

### Expected Behavior

The expected thing would be to close the emulator and the process also close automatically.

### Reproduction Steps

Simply open Citra and close it, after that check in the task manager.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11357748/citra_log.txt)

### System Configuration

CPU: Intel Core i3-9100F
GPU/Driver: NVIDIA GTX 1650 Super 
RAM: 16GB
OS: Windows 11

**Comment by FearlessTobi** [comment]
I'm unable to reproduce this.

**Comment by Gabezin64** [comment]
Strange, because here all programs/emulators close normally, except for yuzu and Citra.
The process of both always remain in the task manager.

**Comment by GPUCode** [comment]
Cannot reproduce this either and haven't heard any reports of this, assuming it's an error on your environment.
