### ISSUE TITLE
[Regression] Digimon World Decode - No Model Rendering in Menus

### ISSUE THREAD

**Issue by Romsstar** [citra-emu/citra#6481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2467

### Description of Issue

Between Canary 2442 (last known working) and 2443 happened that now either no longer renders the models on the menu or turns them invisible. (See Screnshots).

The issue is still present in 2467.

### Expected Behavior

Model Rendered

### Reproduction Steps

Enter the Digivice Menu.

### Log File

[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/11358721/citra_log.txt.old.txt)

### System Configuration

CPU: Ryzen 5 5600X
GPU/Driver: RTX 2070 
RAM: 32  GB RAM
OS: Windows  #10

Expected:
![expected](https://user-images.githubusercontent.com/17484361/235293589-4420e008-8dd4-45d6-b36e-690ca99e763e.png)

Result:
![result](https://user-images.githubusercontent.com/17484361/235293588-e70b80e4-c486-4ee9-bb65-082885dd4a0f.png)

**Comment by Romsstar** [comment]
[citra_log.txt](https://github.com/citra-emu/citra/files/11358727/citra_log.txt)
As per request, log from Canary 2443 with Debug Rendering enabled.

**Comment by SachinVin** [comment]
https://github.com/citra-emu/citra-canary/compare/canary-2442...canary-2443

Probably related PR #6375

**Comment by Romsstar** [comment]
After some more digging and finding that the regression occcured in nightly between 1884 and 1885 #6375 indeed currently seems to be the most likely culprit.

**Comment by GPUCode** [comment]
Fixed in https://github.com/citra-emu/citra/pull/6479
