### ISSUE TITLE
(Updated) Games don't render correctly on Linux canary and nightly builds if you use Hardware Shaders.

### ISSUE THREAD

**Issue by AmyRoxwell** [citra-emu/citra#6485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Tested on canary 2468 and Nightly 1894 but basically affects every build.

### Description of Issue

While trying to play MH4U, MH3U, SMT 4, Braverly Default and a couple of other games will render the image incorrectly, making things like:
1. Showing the top screen graphics on the bottom screen and vices versa
2. Graphics not rendering at all.
3. Displaying any static image permanently and 3D models won't load 
This issue seems to happen if you use recent mesa drivers (Most recent on arch at may 01, 2023) like mesa 23.0.3-1 and try to play with "Hardware Shaders" enabled on the advanced graphics settings, said issues don't happen if you disable that option but most games will have worse performance. 
![Screenshot from 2023-04-28 20-19-49](https://user-images.githubusercontent.com/89411895/235324202-ec364ff6-dd7d-4296-88a9-c01e362522ff.png)
![Screenshot from 2023-04-28 20-20-52](https://user-images.githubusercontent.com/89411895/235324203-0a2731a2-e8a5-406d-a7fe-7f68d1ea2ec2.png)
![Screenshot from 2023-04-28 20-22-03](https://user-images.githubusercontent.com/89411895/235324204-e6076443-b9ea-4758-b74d-258debe55065.png)
![Screenshot from 2023-05-01 20-03-14](https://user-images.githubusercontent.com/89411895/235557637-3256aa20-dcc9-44a7-b4d2-283794d7b593.png)
![Screenshot from 2023-05-01 20-04-42](https://user-images.githubusercontent.com/89411895/235557822-db30764a-98b9-47ae-b9b6-f81f76e05c22.png)
![Screenshot from 2023-05-01 20-07-09](https://user-images.githubusercontent.com/89411895/235558033-86854eb2-ccbd-4a0e-8fc1-cec58f4fe6c4.png)

### Expected Behavior

Game renders bottom screen correctly and display the game like normal
![title-screen](https://user-images.githubusercontent.com/89411895/235324183-404ee7ac-9a3f-4427-b6a2-d2a61ad25b03.png)
![dundorma](https://user-images.githubusercontent.com/89411895/235324186-6141c8f9-7a6c-4bf3-97fb-c579cb430403.png)
![a](https://user-images.githubusercontent.com/89411895/235324189-2ad2c257-73cb-4ae7-baf7-91b279dca61a.jpeg)

### Reproduction Steps

1. Boot up the game
5. Try to play and you will see the visual bugs

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11360064/citra_log.txt) Monster Hunter 4U
[citra_log.txt](https://github.com/citra-emu/citra/files/11360070/citra_log.txt) Monster Hunter 3U
[citra_log.txt](https://github.com/citra-emu/citra/files/11368916/citra_log.txt) Ocarina of time.
[citra_log.txt](https://github.com/citra-emu/citra/files/11368930/citra_log.txt) Bravely Default
[citra_log.txt](https://github.com/citra-emu/citra/files/11368936/citra_log.txt) SMT 4

### System Configuration

CPU: Ryzen 5 5600
GPU/Driver: Rx 6600 using mesa's arch last version (23.0.3-1)
RAM: 16gbs
OS: EndeavourOS (arch linux based distro)

**Comment by GPUCode** [comment]
Has been fixed for a while in mesa

**Comment by AmyRoxwell** [comment]
Can confirmed they had been fixed.
