### ISSUE TITLE
`SDL_CONTROLLERDEVICEADDED` event being hit every frame? (Excessive logging)

### ISSUE THREAD

**Issue by TheGag96** [citra-emu/citra#6487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

master

### Description of Issue

I was running a homebrew of mine using the command line `citra` with a freshly-built master, and I noticed there was a lot of console output saying things like:

```
[   2.442991] Input <Info> input_common/sdl/sdl_impl.cpp:InitGameController:508: opened joystick 0 as controller
```

If I unplug my GC controller adapter, it goes away. I tried connecting my DS4 over Bluetooth, and I get those printouts for it as well.

I looked at the source code for a minute and figured that the handler for `SDL_CONTROLLERDEVICEADDED` is somehow being hit every frame. It would seem like then that this isn't the fault of Citra but rather the version of SDL2 you guys are using - do you think this is the case?

Not sure if this is related, but if I re-plug in the GC controller adapter after having unplugged it, Citra segfaults.

### Expected Behavior

The described printout doesn't occur every frame, nor the crash.

### Reproduction Steps

- Build master for Linux x64.
- Run any game, enabling the log in some way.
- Connect a controller.
- Observe the excessive info logging.

### Log File

https://pastebin.com/sD6aAeGg

### System Configuration

CPU: AMD Ryzen 3700X
GPU/Driver: Nvidia 1660 TI
RAM: 32 GB
OS: Artix Linux x86_64 (openrc)

**Comment by Steveice10** [comment]
SDL and libusb were both updated in https://github.com/citra-emu/citra/pull/6461 if you want to try building from that PR and seeing if that helps.

**Comment by TheGag96** [comment]
According to my logs, that appears to fix it. Although, using `citra` (not `citra-qt`), I get:

```
[   0.003316] Frontend <Critical> citra/emu_window/emu_window_sdl2.cpp:InitializeSDL2:120: Failed to initialize SDL2: No available video device! Exiting...
```

Will repost this detail in the PR, too.

**Comment by TheGag96** [comment]
Just an update, as of latest master with #6461 merged, this is unfortunately not fixed.

**Comment by SleepingSnakezzz** [comment]
@TheGag96 https://github.com/citra-emu/citra/pull/6577 should fix this
