### ISSUE TITLE
building broken since https://github.com/citra-emu/citra/pull/6435

### ISSUE THREAD

**Issue by theofficialgman** [citra-emu/citra#6490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

master branch

### Description of Issue

building broken since https://github.com/citra-emu/citra/pull/6435

detection of bundled boost library is broken
```
CMake Error at /usr/share/cmake-3.24/Modules/FindBoost.cmake:1825 (file):
  file STRINGS file "/home/switch/citra/externals/boost/boost/version.hpp"
  cannot be read.
Call Stack (most recent call first):
  externals/dynarmic/CMakeLists.txt:132 (find_package)


CMake Error at /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost: Found unsuitable version "0.0.0", but required is at
  least "1.57" (found /home/switch/citra/externals/boost, )
Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.24/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
  externals/dynarmic/CMakeLists.txt:132 (find_package)
```

### Expected Behavior

boost bundled works normally

### Reproduction Steps

https://github.com/cobalt2727/L4T-Megascript/blob/master/scripts/games_and_emulators/citra.sh

### Log File

https://cdn.discordapp.com/attachments/905503803820884008/1102261865146494986/install-fail-Citra.txt

### System Configuration

CPU: generic arm64
GPU/Driver: N/A
RAM: N/A
OS: Linux

**Comment by Steveice10** [comment]
Are you certain that PR was the cause? It doesn’t touch boost, or really the Linux build paths at all.

**Comment by theofficialgman** [comment]
I am currently running verification CI
the bug report was from a user and CI was last run and tested good 3 days ago.
the pr is the only thing that touched boost since

I will report back when the verification CI fails or succeeds (it takes a while)

**Comment by Steveice10** [comment]
> the pr is the only thing that touched boost since

That’s what I’m saying though, the PR doesn’t touch any logic related to boost. Most of the modified logic is all stuff related to downloading pre-builds and macOS bundling, which don’t apply to Linux at all

**Comment by theofficialgman** [comment]
yeah can't reproduce in CI from a fresh clone (you won't be able to see the step until the CI finishes in a few hours)
https://github.com/cobalt2727/L4T-Megascript/actions/runs/4845428590/jobs/8634343436#step:3:4060
https://github.com/cobalt2727/L4T-Megascript/actions/runs/4845428590/jobs/8634343530#step:3:3779

sorry for the misattribution

l can only assume corruption. is there anything in particular otherwise that could cause this file to be unreadable? git reports all the submodules as up to date.
