### ISSUE TITLE
AppImage: Citra crashes when select "configure" in "Emulation" menu

### ISSUE THREAD

**Issue by legluondunet** [citra-emu/citra#6495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

citra-linux-20230501-cdcd487.AppImage

### Description of Issue

Hello,
just download AppImage citra-linux-20230501-cdcd487.AppImage, 
Citra crashes when select "configure" in "Emulation" menu.

```
./citra-linux-20230501-cdcd487.AppImage 
could not load multimedia backend ""
QtMultimedia is not currently supported on this platform or compiler.
Abandon (core dumped)
```

### Expected Behavior

no crash when click on configure

### Reproduction Steps

Citra crashes when select "configure" in "Emulation" menu.

### Log File

```
./citra-linux-20230501-cdcd487.AppImage 
could not load multimedia backend ""
QtMultimedia is not currently supported on this platform or compiler.
Abandon (core dumped)
```

### System Configuration

CPU: Intel Core i7-8850H @ 12x 4,3GHz [34.0°C]
GPU: Quadro P1000
RAM: 7142MiB / 31934MiB
OS: Ubuntu 22.04

**Comment by SleepingSnakezzz** [comment]
Should be fixed with https://github.com/linuxdeploy/linuxdeploy-plugin-qt/pull/145
Next Canary build *should* have it if I understood it correctly. @Steveice10 correct me if I'm wrong.

**Comment by Steveice10** [comment]
> Canary build _should_ have it if I understood it correctly. @Steveice10 correct me if I'm wrong.

It will depend on the build Docker image being updated first, it's being worked on.

**Comment by Steveice10** [comment]
Should be resolved next Canary, will verify and close if so.

**Comment by Steveice10** [comment]
Fixed in Canary 2473
