### ISSUE TITLE
src/web_service/verify_login.cpp build error under gcc 13

### ISSUE THREAD

**Issue by heavysink** [citra-emu/citra#6500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2473/ master

### Description of Issue

Build failed with error:

 Building CXX object src/web_service/CMakeFiles/web_service.dir/verify_login.cpp.o
/home/heavysink/src/citra-canary/src/web_service/verify_login.cpp: In function ‘bool WebService::VerifyLogin(const std::string&,
 const std::string&, const std::string&)’:
/home/heavysink/src/citra-canary/src/web_service/verify_login.cpp:25:21: Error：no match for ‘operator==’ (operand types are ‘con
st std::string’ {aka ‘const std::__cxx11::basic_string<char>’} and ‘nlohmann::json_abi_v3_11_2::basic_json<>’)
   25 |     return username == *iter;
      |            ~~~~~~~~ ^~ ~~~~~
      |            |           |
      |            |           nlohmann::json_abi_v3_11_2::basic_json<>
      |            const std::string {aka const std::__cxx11::basic_string<char>}
In file included from /home/heavysink/src/citra-canary/src/web_service/verify_login.cpp:5:

Building with gcc 12/clang 15 does not have such problem.

### Expected Behavior

Does not build

### Reproduction Steps

Build flags: cmake ..  \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_QT_TRANSLATION=ON \
      -DCITRA_ENABLE_COMPATIBILITY_REPORTING=ON \
      -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON \
      -DUSE_DISCORD_PRESENCE=ON \
      -DENABLE_FFMPEG_VIDEO_DUMPER=ON \
      -DENABLE_FFMPEG_AUDIO_DECODER=ON \
      -DUSE_SYSTEM_BOOST=ON \
      -DUSE_SYSTEM_SDL2=ON \
      -DENABLE_MF=OFF \
      -DBUILD_TESTS=OFF

### Log File

[1.log](https://github.com/citra-emu/citra/files/11393249/1.log)

### System Configuration

CPU: 12700K
GPU/Driver: 7900XTX
RAM: 32G
OS: Arch Linux

A possible simple fix is the same as https://github.com/yuzu-emu/yuzu/blob/master/src/web_service/verify_login.cpp, change to return *iter == username;

**Comment by purpasmart96** [comment]
Confirmed on my side too.

**Comment by Vorthas** [comment]
Confirmed I get this error too.  If I wrap the `*iter` with std::string() like `std::string(*iter)` then it seems to build.  Just not sure if that's the correct way compared to doing `*iter == username`.  Just a thought.

**Comment by FearlessTobi** [comment]
Would be great if someone could port the yuzu fix and verify it fixes compilation.

**Comment by Vorthas** [comment]
I pulled down citra-canary, made the Yuzu fix, confirmed that it was able to compile, and am now able to play the games I got with no issue (mostly Pokemon Prismatic Moon).  So the fix should be good.

**Comment by Steveice10** [comment]
This is fixed for a while now, closing
