### ISSUE TITLE
Crash when starting Pokémon Omega Ruby

### ISSUE THREAD

**Issue by DosScie** [citra-emu/citra#6514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Citra Nightly 1900

### Description of Issue

I wanted to refresh my save of Omega Ruby, but when the game is starting after the title screen, Citra crashes.
It seems like Citra crashes with the starting cinematic of this game because I can load the game with my ancient save.

### Expected Behavior

Game will start correctly after title screen.

### Reproduction Steps

Just start the game with no save and Citra will crash after the title screen.

### Log File

I don't know.

### System Configuration

CPU: 
GPU/Driver:
RAM:
OS:

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord or our forums for support requests.

**Comment by DosScie** [comment]
It's a bug. It operated correctly before.

**Comment by GetBucked** [comment]
> It's a bug. It operated correctly before.

Then go see if you can't get help from someone who had the same issue in the Discord or forums.
