### ISSUE TITLE
citra linux/arm64 

### ISSUE THREAD

**Issue by luc-git** [citra-emu/citra#6516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Compile citra for arm64 desktop linux

### Why would this feature be useful?

There are linux arm computer that support vulkan or latest opengl api and could run citra pretty well.
There is this issue https://github.com/citra-emu/citra/issues/5554. But It can be better to just have an executable ready to run for  arm64 and not just the raspberry pi.

**Comment by merryhime** [comment]
You can already build and run Citra on arm64 Linux.

**Comment by luc-git** [comment]
I don’t see an arm64 executable from the website and from github action

**Comment by FearlessTobi** [comment]
Thanks for your request, however arm64 is still very niche and we do not plan to offer prebuilt binaries for it at the moment.
Most people who are currently running such devices have the skills to build Citra themselves.
