### ISSUE TITLE
trying to load a rom that doesn't work cause it's damaged / corrupted causes citra to make screen glitchy when loading a healthy rom

### ISSUE THREAD

**Issue by Emayeah** [citra-emu/citra#6519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1899 / Canary 2474

### Description of Issue

screen gets glitchy after faulty rom gets opened

https://user-images.githubusercontent.com/84565620/236759473-2233cd15-9378-4da7-8fdc-1375855f53bf.mp4

![corrupted rom](https://user-images.githubusercontent.com/84565620/236759534-e2dc2b2a-cd76-4cfc-bf2b-eeb72839ddd7.png)

don't ask why the rom is in korean

### Expected Behavior

should not make the virtual screen split in half and flickery

### Reproduction Steps

make citra somehow show that error, load a healthy rom, it should pop that glitched screen

even if it's piracy, ask me the rom if you need to

i will update you if it's just the rom that had a problem during download / decrypting or if the problem occurs even if the download / decrypting process hasn't problems

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11418812/citra_log.txt)

### System Configuration

CPU: i5 10300h
GPU/Driver: rtx 3060 laptop with driver 531.41
RAM: 8 gigs
OS: win 11 pro

**Comment by Emayeah** [comment]
update!!!!! just download the korean version with hshop, decrypt it with batch 3ds cia decryptor: gbatemp .net/threads/batch-cia-3ds-decryptor-a-simple-batch-file-to-decrypt-cia-3ds.512385/ (download 2nd link, not github one), enjoy

**Comment by FearlessTobi** [comment]
We do not support piracy here.
