### ISSUE TITLE
High pitched voice clips in Fire Emblem Echoes and Fire Emblem Fates on Linux

### ISSUE THREAD

**Issue by RukaDragoon** [citra-emu/citra#6529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1898

### Description of Issue

With HLE Audio selected, all out of battle voice clips in Fire Emblem Echoes play at a very high pitch in the Linux build of Citra. This also happens in Fates, but only in the My room and confession cutscenes. This does not happen in the Windows version of Citra.
### Expected Behavior

The audio is playing at a much higher pitch than normal.

### Reproduction Steps

-Open Fire Emblem Echoes in Citra on Linux
-Start the game
-Listen to any character speak outside of battle

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11456924/citra_log.txt)

### System Configuration

CPU: AMD Custom APU 0405
GPU/Driver: AMD Custom GPU 0405
RAM: 16GB
OS: SteamOS 3.4.6

**Comment by SleepingSnakezzz** [comment]
> In the most recent appimage version of Linux on Citra's website, these lines also crash the games.
As a note, this is a separate issue, as this is caused by appimage builds not having an AAC decoder enabled.

**Comment by RukaDragoon** [comment]
> > In the most recent appimage version of Linux on Citra's website, these lines also crash the games.
> 
> As a note, this is a separate issue, as this is caused by appimage builds not having an AAC decoder enabled.

My apologies, i have edited that out
