### ISSUE TITLE
language switch not work

### ISSUE THREAD

**Issue by thedoc013** [citra-emu/citra#6531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

newest

### Description of Issue

i try to change rom language but not works 

still english 

at all games

### Expected Behavior

should switch languages

### Reproduction Steps

download europe rom /all roms tested
change language to german

### Log File

no log

### System Configuration

Steamdeck

**Comment by Efadd** [comment]
Dl European rom?

**Comment by thedoc013** [comment]
> Dl European rom?

download europe rom i meaned sorry

**Comment by SleepingSnakezzz** [comment]
We don't support piracy here.
