### ISSUE TITLE
Citra runs Mario Kart 7 Creating multiplayer mode stuck

### ISSUE THREAD

**Issue by Helloworld996** [citra-emu/citra#6536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

latest nightly and canary

### Description of Issue

Citra creates multiplayer mode, click to create a group, and the game will freeze.Pressing any button has no response
![Screenshot_2023-05-12-00-29-22-999_org citra citra_emu canary](https://github.com/citra-emu/citra/assets/58156832/c354e4d3-afb4-45d1-9795-9b97c7f0e9c6)

### Expected Behavior

It is normal for Citra MMJ to establish a team. The following is the page that will be accessed normally after creation
![Screenshot_2023-05-12-00-27-10-059_org citra emu](https://github.com/citra-emu/citra/assets/58156832/b237cc38-83e4-467b-9448-46f86279c5c3)

### Reproduction Steps

Game:Mario Kart 7
Game Link:
https://drive.google.com/file/d/1K3XzBBFATHAJBt5x0rBs653uQmPrrEcf/view?usp=drivesdk
![Screenshot_2023-05-12-16-07-46-158_org citra citra_emu canary](https://github.com/citra-emu/citra/assets/58156832/d55e6e84-81bd-461d-a865-a3ec98a81a6e)
![Screenshot_2023-05-12-00-29-22-999_org citra citra_emu canary](https://github.com/citra-emu/citra/assets/58156832/65d15487-e5bc-4304-9ff6-2f2e0c0e48e5)

### Log File

nothing in the log file

### System Configuration

CPU:Qualcomm Snapdragon 710
GPU/Driver:Adreno 616
RAM:4G
OS:Android

**Comment by stepsy** [comment]
Um, Citra MMJ is unofficial. You'll get no support.

**Comment by sakuramipha** [comment]
Citra Android does not support multiplayer at this moment. Citra, as a whole, also does not support piracy. Closing this issue.

**Comment by stepsy** [comment]
Um, you can't play multiplayer on android on official Citra. Also why on earth are you linking the game? Citra doesn't support piracy.
