### ISSUE TITLE
Mario Kart 7 Creating group stuck(Under normal circumstances, this page can still be opened when not online)

### ISSUE THREAD

**Issue by Helloworld996** [citra-emu/citra#6537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

latest nightly and canary

### Description of Issue

Regarding the description of the previous question, I would like to clarify that creating a group on this multiplayer game page does not require a network to enter. But the official version of MMJ will get stuck when clicking to create a new group. The MMJ I am using also does not use any online services and can enter the next page normally without getting stuck

about“Citra Android does not support multiplayer at this moment” reply:I understand that Citra cannot connect online. But I did this step without activating online mode, and MMJ can perform normal display. The official version will get stuck.

Original problem:
Citra creates multiplayer mode, click to create a group, and the game will freeze.Pressing any button has no response。

### Expected Behavior

I hope he can go directly to the next page like the MMJ version without getting stuck。I did not use networking or online functions. But the official version will get stuck in the creation area. The MMJ version will not get stuck there. Normally, it won't get stuck.

![Screenshot_2023-05-12-00-27-10-059_org citra emu](https://github.com/citra-emu/citra/assets/58156832/c9bf1d92-6bca-44d4-b465-1624c1afb60a)

### Reproduction Steps

The operation of these two steps is stuck.
![Screenshot_2023-05-12-16-07-46-158_org citra citra_emu canary](https://github.com/citra-emu/citra/assets/58156832/cc30bf8e-5c15-410d-84e5-3f44f90233b8)
![Screenshot_2023-05-12-00-29-22-999_org citra citra_emu canary](https://github.com/citra-emu/citra/assets/58156832/6d086e64-b28d-4a00-9db8-ead4d5001eb9)

### Log File

nothing in the log file

### System Configuration

CPU:Qualcomm Snapdragon 710
GPU/Driver:Adreno 616
RAM:4G
OS:Android

**Comment by SachinVin** [comment]
dupe #6536

**Comment by Helloworld996** [comment]
> 欺骗#6536

I'm disappointed why you said that, but this page is indeed accessible directly, and the next step is to connect to the internet. Could you please verify? What I said is true!

**Comment by Helloworld996** [comment]
> 欺骗#6536

I specifically mentioned the bug because I found that the official version would get stuck in this step. Even if I am offline, I can still access the MMJ version of that page because the "Create Group" step has not yet enabled the online function. Could you really check if it's the same as what I said.

**Comment by Helloworld996** [comment]
> 欺骗#6536

I have put a lot of effort into editing and I don't want to be treated like this. I hope you can follow the steps I mentioned to verify. I'm here at 1 o'clock in the morning, and I don't need to lie to anyone by staying up late. I hope I can take it seriously.
