### ISSUE TITLE
Nightly 1899 The procedure entry point SystemParametersInfoForDpi ...

### ISSUE THREAD

**Issue by SachinVin** [citra-emu/citra#6539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1899+

### Description of Issue

Opening issue for documentation and searchability.

Opening Citra on any of the below OS's will error with `The procedure entry point SystemParametersInfoForDpi could not be located in the dynamic link library`

### Expected Behavior

X

### Reproduction Steps

1. Open Citra
2. Observe

### Log File

NA

### System Configuration

CPU: NA
GPU/Driver: NA
RAM: NA
OS: Windows 7, 8, 8.1, 10 (Only Build 10240?)

**Comment by SachinVin** [comment]
Support for older windows is dropped, https://github.com/citra-emu/citra/wiki/Citra-Legacy-Builds#last-supported-build-for-windows-781

**Comment by Steveice10** [comment]
For reference, Qt 6 minimum requirements: https://doc.qt.io/qt-6/supported-platforms.html
