### ISSUE TITLE
Swap Screen/Layout hotkey binding

### ISSUE THREAD

**Issue by Retroism** [citra-emu/citra#6542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Ability to use shortcut hotkeys to swap screen and layout (single/top-bottom) and bind them to a controller key. 
eg. L3 for swapping screen
R3 for switching from dual to single screen layout

### Why would this feature be useful?

For devices with small screen such as retro handhelds. Switching from dual screen to single screen is useful in different game scenarios. Single screen for immersive viewing and dual screen for games that utilize both screen when gaming. I use this with Drastic.

**Comment by Daisouji** [comment]
https://github.com/citra-emu/citra/issues/5885

**Comment by jakedowns** [comment]
i'm working on this here: https://github.com/jakedowns/citra/issues/9

https://github.com/jakedowns/citra/tree/jakedowns/bindableSwapScreenButton

will submit a PR when it's ready

**Comment by MaxiMuM1441** [comment]
+1

**Comment by darrenhaken** [comment]
What happened to this feature. The issue is closed but it’s not available in Android Citra

**Comment by Howchie** [comment]
Can't you just copy the code from the MMJ fork? I actually struggle to understand how people play 3ds without this feature.

**Comment by darrenhaken** [comment]
A level of this hotkey support is now in Citra for Android.

**Comment by Howchie** [comment]
> Android Citra

Oh really? On the playstore build or nightly?

**Comment by darrenhaken** [comment]
Nightly or canary, one of them. Not the play store. I was one of the testers for the contributor that added it. 

The only improvement to the feature I wish we could have is a hotkey trigger plus another key. This would allow you to have keys per layout.

The person who added the feature is nevertheless, brilliant for adding it.
