### ISSUE TITLE
Enable mapping swap screen to button 

### ISSUE THREAD

**Issue by resetter** [citra-emu/citra#6546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It would be useful to be able to map the swap screen toggle to a physical button like in a certain fork.

### Why would this feature be useful?

This would allow the full screen to be used as the main window, with quick access to the second screen, enhancing the play.

**Comment by Daisouji** [comment]
https://github.com/citra-emu/citra/issues/5885
