### ISSUE TITLE
The Legend of Zelda: Ocarina of Time 3D Visions Slowdown

### ISSUE THREAD

**Issue by KostaSaizo7** [citra-emu/citra#6550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1907 / Canary 2491

### Description of Issue

I remember years ago playing OoT and encountering a slowdown when I used the [Vision](https://zelda.fandom.com/wiki/Vision) feature. So, I tried the latest version only to find out that the slowdown is even worse now!
Tested with default settings:
Nightly 295 (from Aug 11, 2017): **14fps**
Nightly 1907: **3-4fps**

### Expected Behavior

30fps as everywhere else in the game

### Reproduction Steps

Enter a Sheikah Stone to trigger the slowdown. Here's a savefile near one: [save00.zip](https://github.com/citra-emu/citra/files/11508749/save00.zip)

![image](https://github.com/citra-emu/citra/assets/39852873/173dd688-f66a-48aa-9094-e2de0acb3c35)

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11508641/citra_log.txt)

### System Configuration

CPU: Intel i3-4160
GPU/Driver: NVIDIA GTX 750 Ti
RAM: 8GB
OS: Windows 10

**Comment by Leafdomain** [comment]
I've been running into the same issue over the years, so can confirm it exists, it should be fixed somehow

**Comment by KostaSaizo7** [comment]
A log made with pr #[6617](https://github.com/citra-emu/citra/pull/6617) and debug filter
[debug 6617.txt](https://github.com/citra-emu/citra/files/11778311/debug.6617.txt)

**Comment by KostaSaizo7** [comment]
Fixed by #7096
