### ISSUE TITLE
Sometimes, the contents in the 2 screens get corrupted with the OGL renderer (Shin Megami Tensei IV)

### ISSUE THREAD

**Issue by LOuroboros** [citra-emu/citra#6551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2491

### Description of Issue

I updated Citra after a while, and I'm noticing that sometimes, when I start a battle, the touchscreen shows nothing at all instead of the game's battle UI.

This only seems to happen with the OpenGL renderer, and it didn't happen before.

https://github.com/citra-emu/citra/assets/4485172/343b5e27-b5ca-4bfa-a265-17fde2c50b2c

### Expected Behavior

I expected all the battles to behave in the same way they used to, where the touchscrene would show the actual battle UI normally.

### Reproduction Steps

Set the Graphics API to OpenGL, enable Async Shader Compilation and Async Presentation, and just roam the overworld in search for battles.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11511273/citra_log.txt)

### System Configuration

**CPU**: i3 2120
**GPU/Driver**: Gigabyte's NVIDIA GeForce GT 1030, Driver Version 512.95 (sadly stuck there in order to avoid crashes on Yuzu)
**RAM**: 4 GB, running on Single Channel for reasons
**OS**: Windows 11 v22H2 x64, Build 22621.1702

**Comment by GPUCode** [comment]
Does this still happen? If yes please provide a save file so the issue can be reproduced

**Comment by LOuroboros** [comment]
> Does this still happen? If yes please provide a save file so the issue can be reproduced

After a couple of minutes of testing, I can no longer replicate the problems on Canary 2538 using OGL to render the graphics.

However, I'm noticing that I cannot select the Vulkan API, so I cannot test that.

Was it removed from the emulator, or was it disabled on specific GPUs?

**Comment by LOuroboros** [comment]
😅 .......

I would have appreciated a response before closing the ticket.

**Comment by GPUCode** [comment]
Well the issue has been fixed so it can be closed. About your question, vulkan has been removed from canary because of stability issues. We don't have an ETA of when it will be available again
