### ISSUE TITLE
Please let games detect each other's saves / Streetpass data

### ISSUE THREAD

**Issue by avengah** [citra-emu/citra#6552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Some games offer extra features if they detect save or Streetpass data for other games. In particular, if Streetpass data for Kirby Triple Deluxe is present, Dedede's Drum Dash Deluxe and Kirby Fighters Deluxe get extra features. However, this currently doesn't work in Citra on Windows (but apparently it does work on Android). Streetpass doesn't need to work, the data just needs to be there and findable by the games. Thanks!

### Why would this feature be useful?

The extra features unlocked are not just cosmetic and minor. In Kirby Fighters Deluxe, you get two extra copy abilities and an extra level.

**Comment by avengah** [comment]
There is another way to do this that's much simpler. If Citra detects that a game is searching for the existence of another game's Streetpass Data or anything like that, simply make Citra always return a positive. That way there's very little coding necessary and all the relevant bonus features will automatically unlock. Is this a possible solution?

**Comment by SachinVin** [comment]
Please open an issue instead, stuff that works on the 3ds and not on Citra should be considered an issue. 
Feature requests are generally for new features additional to what Citra/3ds offers.

Thanks

**Comment by avengah** [comment]
OK, which template should I use? I'm not a developer so I don't want to use the wrong template. Thanks!

**Comment by SachinVin** [comment]
You can use the 
Bug Report
File a bug report
