### ISSUE TITLE
Change save file read/write to not require full file handle lock

### ISSUE THREAD

**Issue by Nintynuts** [citra-emu/citra#6558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Currently, when the game creates a save file, it does this:

https://github.com/citra-emu/citra/blob/fa8c530e1088d85b3edb5ee22ffeb2d5ee27a87a/src/common/file_util.cpp#L1058-L1065

I have been trying to reverse engineer a save file for a game, and the Hex Editor I'm using to decode the file has done its best to do as little file locking as possible, but it still prevents citra from reading or writing a save because citra wants a full lock on the file.

### Why would this feature be useful?

If this could be changed to something which allows sharing, it would prevent me having to close and re-open files every time I needed to read or write a save file.

**Comment by GPUCode** [comment]
Fixed by above PR
