### ISSUE TITLE
Persona Q: Shadow of the Labyrinth won't run

### ISSUE THREAD

**Issue by Ouroboros650** [citra-emu/citra#6571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2500 / Nightly 1913

### Description of Issue

Persona Q: Shadow of the Labyrinth launches, stays on black screen and RAM usage continues to rise quickly until system lags

### Expected Behavior

The game creates sd card data before going on to the title screen

### Reproduction Steps

Install .cia file, launch the game and nothing will happen, but the RAM usage will increase until unstable

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11583170/citra_log.txt)

### System Configuration

CPU:  AMD Ryzen 5600
GPU/Driver: GTX 1660 Ti
RAM: 16GB DDR4 3200
OS: Windows 11

**Comment by SleepingSnakezzz** [comment]
Please upload a Nightly log file for this

**Comment by Ouroboros650** [comment]
[citra_log.txt](https://github.com/citra-emu/citra/files/11583430/citra_log.txt)

**Comment by SleepingSnakezzz** [comment]
The log file seems to indicate that your ROM is corrupted. Could you give it a redump? Please refer to our game dumping guides:

[**Dumping Game Cartridges**](https://citra-emu.org/wiki/dumping-game-cartridges)
[**Dumping Installed Titles**](https://citra-emu.org/wiki/dumping-installed-titles)

Make sure your GM9 is up to date and that you have enough free storage space available on your SD-Card to perform the dump.

**Comment by Ouroboros650** [comment]
It was the ROM, i redumped it and it still wouldn't load, then I actually checked if the cartridge played on my 3DS, the cartridge is completely dead, won't even boot up (still recognized by the 3ds), so I dumped my brother's copy and it works, thanks for your help!
