### ISSUE TITLE
Citra-qt window not active when launching from command line

### ISSUE THREAD

**Issue by Dime333** [citra-emu/citra#6576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1867 and most likely all versions after that

### Description of Issue

I talked to SleepingSnake on Discord about this. He was able to reproduce the issue and asked me to make an issue report for it. The issue started happening with Nightly Build 1867. When using this build or a newer one, the Citra-qt window is not active when launching a game from command line in windowed mode. This can be seen by looking at the title bar text that says "Citra nightly". The text is gray instead of black until you click on the window. This causes issues when using the emulator in a frontend.

### Expected Behavior

Emu wiindow should be active. This works with Nightly 1866 and older versions.

### Reproduction Steps

Launch a game in windowed mode using command line.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11584227/citra_log.txt)

### System Configuration

CPU: i7-7700K
GPU/Driver: NVIDIA GTX 1060
RAM: 16GB
OS: Windows 10

**Comment by SleepingSnakezzz** [comment]
Should be fixed in the next Canary build: https://github.com/citra-emu/citra/pull/6565

**Comment by SachinVin** [comment]
Closed with #6565
