### ISSUE TITLE
Broken Cheats from version Canary 2465+

### ISSUE THREAD

**Issue by Ninjistix** [citra-emu/citra#6590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2466

### Description of Issue

the UI changes that went into effect from canary-2466 to date have broken some cheat codes for several games.

all codes for my current games only work upto version 2465

this also affect's the nightly version, but I didn't check when that UI change went into effect with the nightly version but should be around the same release time as 2466

### Expected Behavior

from build 2465 and lower there's a cheats menu visible from the emulation tab, from 2466+ that has been moved into configure current game

### Reproduction Steps

download build 2465 test the codes (currently tested for pokemon gen 6-7)

download any build after 2466+ and you'll see most of the codes stopped working.

[cheats.zip](https://github.com/citra-emu/citra/files/11630794/cheats.zip)

### Log File

lno log file, but provided screenshots of when the changes took effect.

Before Build -2465
![image](https://github.com/citra-emu/citra/assets/12572974/6551ba90-def8-41f2-ab60-bceea85fa89e)

after build 2466+
![image](https://github.com/citra-emu/citra/assets/12572974/a5949864-35d2-4d15-a40a-e851623cc495)

### System Configuration

CPU:Intel(R) Core(TM) i9-9960X
GPU/Driver: RTX 3080 Ti
RAM: 128GB
OS: Windows 11

**Comment by Daisouji** [comment]
It's in configure current game.

**Comment by Ninjistix** [comment]
The issue is not the location of the cheats menu the issue is the cheats stopped working after that change was made to the UI

**Comment by GPUCode** [comment]
Can you provide an example cheat code alongside with the expected behaviour? I'm able to use cheats normally

**Comment by GrueFinder** [comment]
OoT 3D US (0004000000033500):
```
[Always` Max Health]
DA000000 0058799A
D7000000 0058799C
D2000000 00000000
```
I can verify that in the latest version of Citra nightly (1940) that cheat codes like this are only working when the "Configure Current Game..." window is open and active. Otherwise, the codes stop working once you close the window and go back to the game, at least for the "always on codes" I've tried (max health, max rupees, etc.).

**Comment by Steveice10** [comment]
This should be fixed in Canary already and in Nightly when 2066 releases, please let us know if this is not the case.
