### ISSUE TITLE
please create version number and git branch

### ISSUE THREAD

**Issue by amidevous** [citra-emu/citra#6603]
### Issue

please create version number and git branch

the reason why citra-emu has no packages

in any distribution and mainly due to the fact that you do not indicate the version number anywhere

even if the project is in development it is vital that version numbers are clearly defined

even if it should be 0.0.1 then 0.0.2 etc

without this, no packager can create any package for any distribution because a version number must be provided in the packages

is we can't set the version number for you

only the developers of a project can define when a modification is considered a version

so thank you for clearly indicating version numbers and making tags or branches on your git for each version so that we can package our work

Cordially

**Comment by Efadd** [comment]
Have you looked at the citra-nightly or citra-canary repos?

**Comment by amidevous** [comment]
but what provides as a number above it's not okay

a version number cannot be so high

nightly-1920 and canary 2519

it would have been better to put

1.9.20 and 2.5.19

the way it is not fessable for packages on operating systems

not to mention that it would have been necessary to put them all on the same git

and not to make submodules for packages it fakes a single unique tar source file

therefore cannot work with git submodules

all must be included in an archive and therefore come from the same git

in other words all that is here

https://github.com/citra-emu/ext-boost.git

must be moved here

https://github.com/citra-emu/citra-canary/tree/canary-2519/externals/boost

is here

https://github.com/citra-emu/citra-nightly/tree/nightly-1920/externals/boost

and the same thing is to do for all your other git submodules

the if i prned the tarball and you can check it

git submodule folders are empty

https://github.com/citra-emu/citra-canary/archive/refs/tags/canary-2519.tar.gz

https://github.com/citra-emu/citra-nightly/archive/refs/tags/nightly-1920.tar.gz

can't compile system packages only from full tar source only one tar file can be used can't put more than one

**Comment by SachinVin** [comment]
> without this, no packager can create any package for any distribution because a version number must be provided in the packages

What do you mean, arch has no problem with it
https://aur.archlinux.org/packages/citra-bin

Neither does freebsd
https://www.freshports.org/emulators/citra

Or even flatpak
https://flathub.org/apps/org.citra_emu.citra

> a version number cannot be so high
Why not?

> git submodule folders are empty

This is a limitation of GitHub, so we also provide a tarball with the full. Source
https://github.com/citra-emu/citra-nightly/releases/download/nightly-1920/citra-unified-source-20230607-238a574.tar.xz

**Comment by amidevous** [comment]
arch linux and freebsd are particular distributions which cannot be compared to other linux distributions

and are very far from being the most used

flatpak is an external manager that does not depend on distributions
the distribution strongly advises against its use since this one modifies certain system files which are not supposed to be modified and therefore causes incompatibility

and for yuzu you see it well they have to put
a 0 to allow compatibility

it's marquet 0-1335 and not 1335

I'm going to do 0.1920 suddenly and it will be fine
