### ISSUE TITLE
Using the Vulkan Backend crashes Citra when launching any game.

### ISSUE THREAD

**Issue by CarlJorenzGimeno** [citra-emu/citra#6604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2519

### Description of Issue

Launching any game while using the vulkan backend crashes the app.

### Expected Behavior

Game runs normally without any crashes.

### Reproduction Steps

1. Set backend to Vulkan
2. Launch any game

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11717170/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 3 3250U
GPU/Driver: AMD Radeon Vega 3
RAM: 6GB
OS: Windows 11 Home

**Comment by sakuramipha** [comment]
This is an issue tracker for developers, not a place for support. Please join our [Discord server](https://discord.gg/FAXfZV9) and ask for support there.
