### ISSUE TITLE
Why does it say "OpenGL shared contexts are not supported."

### ISSUE THREAD

**Issue by Zue5s** [citra-emu/citra#6622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2519 & others

### Description of Issue

What happens when I use laptop's internal display
![Screenshot (3)](https://github.com/citra-emu/citra/assets/131946266/59215625-a281-4b6f-9713-cb94f5986ee1)

### Expected Behavior

What happens when I use an external display through HDMI
![Screenshot (4)](https://github.com/citra-emu/citra/assets/131946266/9fcafe5d-a925-44c0-917c-ca07ef31729c)

### Reproduction Steps

This Issue Only Happens if I use the Laptop's internal display. When I use an external display, it works absolutely fine.
I suspect it's because when I use internal display, Citra tries to use the internal graphics, but when I use an external display, the game runs fine. A workaround of this issue is to start the game on external display, unplug it, then continue on internal display, but it's inconvenient.

The Issue: Intel HD 3000 Only supports up to OpenGL 3.1, but NVS 4200M supports up to OpenGL 4.6.

On another note, other emulators that does require the latest version of OpenGL works fine with the internal display, maybe because they find the display adaptor that is compatible & can be used, while Citra tries to use the display adaptor already in use (which is incompatible becaues outdated OpenGL)

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11780727/citra_log.txt)

### System Configuration

Device: Dell Latitude E6420
CPU: Intel Core I5 2520M 2.5 gHz
Discrete GPU/Driver: nVidia NVS 4200M
Internal GPU/Driver: Intel HD Graphics 3000
RAM: 10GB DDR3 1333 mHz
OS: Windows 10 Pro 22H2

**Comment by SachinVin** [comment]
This is an issue tracker for developers, not a place for support. Please join our Discord server or the Citra forum and ask for support there.
