### ISSUE TITLE
Nintendo Switch: Compilation fails

### ISSUE THREAD

**Issue by PeterKnecht93** [citra-emu/citra#6624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest

### Description of Issue

When trying to install Citra through the L4T-Megascript, the compilation fails at around 60% with the following error:

![20230618_174945](https://github.com/citra-emu/citra/assets/129611251/06e396d7-94c7-49dc-bf32-00e1cc331952)

All packages are up to date, and the Switchroot team asked me to send the log to the Citra Devs. 
The issue should not depend on my environment, as the installation failed on both of my Switch Consoles(V1 and oled), and I re-installed Ubuntu.

### Expected Behavior

When installing Citra through the L4T Megascript, the compilation suceeds and you have a working build of Citra.

### Reproduction Steps

Open the L4T-Megascript, tick the Citra box, select "install items" and wait till the error occurs.

### Log File

[install-fail-Citra.log](https://github.com/citra-emu/citra/files/11782034/install-fail-Citra.log)

### System Configuration

Nintendo Switch 2017
Nintendo Switch oled
OS: Ubuntu 18.04.6 LTS

**Comment by SachinVin** [comment]
delete the citra folder and run it again.
Closing because you should ask on https://github.com/cobalt2727/L4T-Megascript/
cc @cobalt2727

**Comment by cobalt2727** [comment]
Sorry about the inconvenience, I've been busy with other stuff - probably should have checked over the error log he sent in before just throwing him your way. 18.04's version of ffmpeg is old.

@PeterKnecht93 We disabled building ffmpeg in the script [last month](https://github.com/cobalt2727/L4T-Megascript/commit/94b6e8d9b9f05280b388a97a65610eede6553572), so deleting the `citra` folder in your home directory and running things again _would_ most likely do the trick.

**Comment by SachinVin** [comment]
It's fine, thanks for looking into it.
