### ISSUE TITLE
Custom normal maps appearing on wrong objects

### ISSUE THREAD

**Issue by Nerrel** [citra-emu/citra#6635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1929

### Description of Issue

Normal maps created for the new custom texture system sometimes appear on other objects as well.  In this case, a map made for the door to the treasure shop in Majora's Mask 3D shows up on a different texture for the stock pot inn door just across the square. 

![normalMap](https://github.com/citra-emu/citra/assets/29036408/3d659da8-db21-4b51-8bc1-94964663fe67)

### Expected Behavior

Normal maps should only apply to the texture sharing the same filename as the map

### Reproduction Steps

Load the custom textures provided below and check the doors in east clock town.  The door to the stock pot inn door should have the map applied to it, despite not having custom textures in the pack
https://drive.google.com/file/d/1xUZSY_yRT-_pLixbblHXetqfYlhZdGgN/view?usp=sharing

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/11850864/citra_log.txt)

### System Configuration

CPU:  AMD Ryzen 9 7900
GPU/Driver: RTX 3070
RAM: 32GB DDR5
OS: Windows 11

**Comment by FearlessTobi** [comment]
Should be fixed now?
