### ISSUE TITLE
error compiling on opensuse 13.2

### ISSUE THREAD

**Issue by Tolmino** [citra-emu/citra#664]
Hi, i attach the log

**Comment by Tolmino** [comment]
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Could NOT find Boost
-- Boost 1.57.0 or newer not found, falling back to externals
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/libX11.so
-- Found OpenGL: /usr/lib/libGL.so  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for one of the modules 'glfw3'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/maria/citra/build
Scanning dependencies of target inih
[  1%] Building C object externals/inih/CMakeFiles/inih.dir/inih/ini.c.o
[  1%] Building CXX object externals/inih/CMakeFiles/inih.dir/inih/cpp/INIReader.cpp.o
Linking CXX static library libinih.a
[  1%] Built target inih
Scanning dependencies of target qhexedit_automoc
[  2%] Automatic moc for target qhexedit
Generating moc_qhexedit.cpp
Generating moc_qhexedit_p.cpp
[  2%] Built target qhexedit_automoc
Scanning dependencies of target qhexedit
[  3%] Building CXX object externals/qhexedit/CMakeFiles/qhexedit.dir/commands.cpp.o
[  3%] Building CXX object externals/qhexedit/CMakeFiles/qhexedit.dir/qhexedit.cpp.o
[  4%] Building CXX object externals/qhexedit/CMakeFiles/qhexedit.dir/qhexedit_p.cpp.o
[  5%] Building CXX object externals/qhexedit/CMakeFiles/qhexedit.dir/xbytearray.cpp.o
[  5%] Building CXX object externals/qhexedit/CMakeFiles/qhexedit.dir/qhexedit_automoc.cpp.o
Linking CXX static library libqhexedit.a
[  5%] Built target qhexedit
Scanning dependencies of target common
[  5%] Building CXX object src/common/CMakeFiles/common.dir/break_points.cpp.o
[  6%] Building CXX object src/common/CMakeFiles/common.dir/emu_window.cpp.o
[  6%] Building CXX object src/common/CMakeFiles/common.dir/file_util.cpp.o
[  7%] Building CXX object src/common/CMakeFiles/common.dir/hash.cpp.o
[  8%] Building CXX object src/common/CMakeFiles/common.dir/key_map.cpp.o
[  8%] Building CXX object src/common/CMakeFiles/common.dir/logging/filter.cpp.o
[  9%] Building CXX object src/common/CMakeFiles/common.dir/logging/text_formatter.cpp.o
[  9%] Building CXX object src/common/CMakeFiles/common.dir/logging/backend.cpp.o
[ 10%] Building CXX object src/common/CMakeFiles/common.dir/math_util.cpp.o
[ 11%] Building CXX object src/common/CMakeFiles/common.dir/mem_arena.cpp.o
[ 11%] Building CXX object src/common/CMakeFiles/common.dir/memory_util.cpp.o
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/misc.cpp.o
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/profiler.cpp.o
[ 13%] Building CXX object src/common/CMakeFiles/common.dir/scm_rev.cpp.o
[ 14%] Building CXX object src/common/CMakeFiles/common.dir/string_util.cpp.o
[ 14%] Building CXX object src/common/CMakeFiles/common.dir/symbols.cpp.o
[ 15%] Building CXX object src/common/CMakeFiles/common.dir/thread.cpp.o
[ 15%] Building CXX object src/common/CMakeFiles/common.dir/timer.cpp.o
Linking CXX static library libcommon.a
[ 15%] Built target common
Scanning dependencies of target core
[ 16%] Building CXX object src/core/CMakeFiles/core.dir/arm/disassembler/arm_disasm.cpp.o
[ 17%] Building CXX object src/core/CMakeFiles/core.dir/arm/disassembler/load_symbol_map.cpp.o
[ 17%] Building CXX object src/core/CMakeFiles/core.dir/arm/dyncom/arm_dyncom.cpp.o
[ 18%] Building CXX object src/core/CMakeFiles/core.dir/arm/dyncom/arm_dyncom_dec.cpp.o
In file included from /home/maria/citra/src/core/arm/dyncom/arm_dyncom_dec.cpp:6:0:
/home/maria/citra/src/./core/arm/dyncom/arm_dyncom_dec.h:7:0: warning: "BITS" redefined [enabled by default]
 #define BITS(a,b)   ((instr >> (a)) & ((1 << (1+(b)-(a)))-1))
 ^
In file included from /home/maria/citra/src/core/arm/dyncom/arm_dyncom_dec.cpp:5:0:
/home/maria/citra/src/./core/arm/skyeye_common/armdefs.h:25:0: note: this is the location of the previous definition
 #define BITS(s, a, b) ((s << ((sizeof(s) * 8 - 1) - b)) >> (sizeof(s) * 8 - b + a - 1))
 ^
In file included from /home/maria/citra/src/core/arm/dyncom/arm_dyncom_dec.cpp:6:0:
/home/maria/citra/src/./core/arm/dyncom/arm_dyncom_dec.h:8:0: warning: "BIT" redefined [enabled by default]
 #define BIT(n)      ((instr >> (n)) & 1)
 ^
In file included from /home/maria/citra/src/core/arm/dyncom/arm_dyncom_dec.cpp:5:0:
/home/maria/citra/src/./core/arm/skyeye_common/armdefs.h:26:0: note: this is the location of the previous definition
 #define BIT(s, n) ((s >> (n)) & 1)
 ^
[ 18%] Building CXX object src/core/CMakeFiles/core.dir/arm/dyncom/arm_dyncom_interpreter.cpp.o
[ 19%] Building CXX object src/core/CMakeFiles/core.dir/arm/dyncom/arm_dyncom_run.cpp.o
[ 20%] Building CXX object src/core/CMakeFiles/core.dir/arm/dyncom/arm_dyncom_thumb.cpp.o
[ 20%] Building CXX object src/core/CMakeFiles/core.dir/arm/interpreter/armcopro.cpp.o
[ 21%] Building CXX object src/core/CMakeFiles/core.dir/arm/interpreter/arminit.cpp.o
[ 21%] Building CXX object src/core/CMakeFiles/core.dir/arm/interpreter/armsupp.cpp.o
[ 22%] Building CXX object src/core/CMakeFiles/core.dir/arm/skyeye_common/vfp/vfp.cpp.o
[ 23%] Building CXX object src/core/CMakeFiles/core.dir/arm/skyeye_common/vfp/vfpdouble.cpp.o
[ 23%] Building CXX object src/core/CMakeFiles/core.dir/arm/skyeye_common/vfp/vfpinstr.cpp.o
[ 24%] Building CXX object src/core/CMakeFiles/core.dir/arm/skyeye_common/vfp/vfpsingle.cpp.o
[ 24%] Building CXX object src/core/CMakeFiles/core.dir/file_sys/archive_extsavedata.cpp.o
[ 25%] Building CXX object src/core/CMakeFiles/core.dir/file_sys/archive_romfs.cpp.o
[ 26%] Building CXX object src/core/CMakeFiles/core.dir/file_sys/archive_savedata.cpp.o
[ 26%] Building CXX object src/core/CMakeFiles/core.dir/file_sys/archive_savedatacheck.cpp.o
[ 27%] Building CXX object src/core/CMakeFiles/core.dir/file_sys/archive_sdmc.cpp.o
[ 27%] Building CXX object src/core/CMakeFiles/core.dir/file_sys/archive_systemsavedata.cpp.o
[ 28%] Building CXX object src/core/CMakeFiles/core.dir/file_sys/disk_archive.cpp.o
[ 29%] Building CXX object src/core/CMakeFiles/core.dir/file_sys/ivfc_archive.cpp.o
[ 29%] Building CXX object src/core/CMakeFiles/core.dir/hle/kernel/address_arbiter.cpp.o
[ 30%] Building CXX object src/core/CMakeFiles/core.dir/hle/kernel/event.cpp.o
[ 30%] Building CXX object src/core/CMakeFiles/core.dir/hle/kernel/kernel.cpp.o
[ 31%] Building CXX object src/core/CMakeFiles/core.dir/hle/kernel/mutex.cpp.o
[ 32%] Building CXX object src/core/CMakeFiles/core.dir/hle/kernel/semaphore.cpp.o
[ 32%] Building CXX object src/core/CMakeFiles/core.dir/hle/kernel/session.cpp.o
[ 33%] Building CXX object src/core/CMakeFiles/core.dir/hle/kernel/shared_memory.cpp.o
[ 33%] Building CXX object src/core/CMakeFiles/core.dir/hle/kernel/timer.cpp.o
[ 34%] Building CXX object src/core/CMakeFiles/core.dir/hle/kernel/thread.cpp.o
[ 35%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ac_u.cpp.o
[ 35%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/act_u.cpp.o
[ 36%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/am_app.cpp.o
[ 37%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/am_net.cpp.o
[ 37%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/am_sys.cpp.o
[ 38%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/apt/apt.cpp.o
[ 38%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/apt/apt_a.cpp.o
[ 39%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/apt/apt_s.cpp.o
[ 40%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/apt/apt_u.cpp.o
[ 40%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/boss_p.cpp.o
[ 41%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/boss_u.cpp.o
[ 41%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/cam_u.cpp.o
[ 42%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/cecd_s.cpp.o
[ 43%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/cecd_u.cpp.o
[ 43%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/cfg/cfg.cpp.o
[ 44%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/cfg/cfg_i.cpp.o
[ 44%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/cfg/cfg_s.cpp.o
[ 45%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/cfg/cfg_u.cpp.o
[ 46%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/csnd_snd.cpp.o
[ 46%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/dsp_dsp.cpp.o
[ 47%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/err_f.cpp.o
[ 47%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/frd_a.cpp.o
[ 48%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/frd_u.cpp.o
[ 49%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/fs/archive.cpp.o
[ 49%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/fs/fs_user.cpp.o
[ 50%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/gsp_gpu.cpp.o
[ 50%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/hid/hid.cpp.o
[ 51%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/hid/hid_user.cpp.o
[ 52%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/hid/hid_spvr.cpp.o
[ 52%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/gsp_lcd.cpp.o
[ 53%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/http_c.cpp.o
[ 53%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ir_rst.cpp.o
[ 54%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ir_u.cpp.o
[ 55%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ldr_ro.cpp.o
[ 55%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/mic_u.cpp.o
[ 56%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ndm_u.cpp.o
[ 56%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/news_s.cpp.o
[ 57%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/news_u.cpp.o
[ 58%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/nim_aoc.cpp.o
[ 58%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ns_s.cpp.o
[ 59%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/nwm_uds.cpp.o
[ 59%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/pm_app.cpp.o
[ 60%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ptm/ptm.cpp.o
[ 61%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ptm/ptm_play.cpp.o
[ 61%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ptm/ptm_u.cpp.o
[ 62%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ptm/ptm_sysm.cpp.o
[ 62%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/service.cpp.o
[ 63%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/soc_u.cpp.o
[ 64%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/srv.cpp.o
[ 64%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ssl_c.cpp.o
[ 65%] Building CXX object src/core/CMakeFiles/core.dir/hle/service/y2r_u.cpp.o
[ 65%] Building CXX object src/core/CMakeFiles/core.dir/hle/config_mem.cpp.o
[ 66%] Building CXX object src/core/CMakeFiles/core.dir/hle/hle.cpp.o
[ 67%] Building CXX object src/core/CMakeFiles/core.dir/hle/shared_page.cpp.o
[ 67%] Building CXX object src/core/CMakeFiles/core.dir/hle/svc.cpp.o
[ 68%] Building CXX object src/core/CMakeFiles/core.dir/hw/gpu.cpp.o
[ 68%] Building CXX object src/core/CMakeFiles/core.dir/hw/hw.cpp.o
[ 69%] Building CXX object src/core/CMakeFiles/core.dir/hw/lcd.cpp.o
[ 70%] Building CXX object src/core/CMakeFiles/core.dir/loader/elf.cpp.o
[ 70%] Building CXX object src/core/CMakeFiles/core.dir/loader/loader.cpp.o
[ 71%] Building CXX object src/core/CMakeFiles/core.dir/loader/ncch.cpp.o
[ 71%] Building CXX object src/core/CMakeFiles/core.dir/loader/3dsx.cpp.o
[ 72%] Building CXX object src/core/CMakeFiles/core.dir/core.cpp.o
[ 73%] Building CXX object src/core/CMakeFiles/core.dir/core_timing.cpp.o
[ 73%] Building CXX object src/core/CMakeFiles/core.dir/mem_map.cpp.o
[ 74%] Building CXX object src/core/CMakeFiles/core.dir/mem_map_funcs.cpp.o
[ 74%] Building CXX object src/core/CMakeFiles/core.dir/settings.cpp.o
[ 75%] Building CXX object src/core/CMakeFiles/core.dir/system.cpp.o
Linking CXX static library libcore.a
[ 75%] Built target core
Scanning dependencies of target video_core
[ 75%] Building C object src/video_core/CMakeFiles/video_core.dir/renderer_opengl/generated/gl_3_2_core.c.o
[ 76%] Building CXX object src/video_core/CMakeFiles/video_core.dir/renderer_opengl/renderer_opengl.cpp.o
[ 77%] Building CXX object src/video_core/CMakeFiles/video_core.dir/renderer_opengl/gl_shader_util.cpp.o
[ 77%] Building CXX object src/video_core/CMakeFiles/video_core.dir/debug_utils/debug_utils.cpp.o
[ 78%] Building CXX object src/video_core/CMakeFiles/video_core.dir/clipper.cpp.o
[ 78%] Building CXX object src/video_core/CMakeFiles/video_core.dir/command_processor.cpp.o
[ 79%] Building CXX object src/video_core/CMakeFiles/video_core.dir/primitive_assembly.cpp.o
[ 80%] Building CXX object src/video_core/CMakeFiles/video_core.dir/rasterizer.cpp.o
[ 80%] Building CXX object src/video_core/CMakeFiles/video_core.dir/utils.cpp.o
[ 81%] Building CXX object src/video_core/CMakeFiles/video_core.dir/vertex_shader.cpp.o
/home/maria/citra/src/video_core/vertex_shader.cpp:20:16: error: ‘nihstro::OpCode’ has not been declared
 using nihstro::OpCode;
                ^
/home/maria/citra/src/video_core/vertex_shader.cpp: In function ‘void Pica::VertexShader::ProcessShaderCode(Pica::VertexShader::VertexShaderState&)’:
/home/maria/citra/src/video_core/vertex_shader.cpp:158:38: error: request for member ‘GetInfo’ in ‘instr.nihstro::Instruction::opcode.nihstro::Instruction::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<26u, 6u, nihstro::Instruction::OpCode>()’, which is of non-class type ‘nihstro::Instruction::OpCode’
         switch (instr.opcode.Value().GetInfo().type) {
                                      ^
/home/maria/citra/src/video_core/vertex_shader.cpp:159:14: error: ‘OpCode’ has not been declared
         case OpCode::Type::Arithmetic:
              ^
/home/maria/citra/src/video_core/vertex_shader.cpp:161:59: error: request for member ‘GetInfo’ in ‘instr.nihstro::Instruction::opcode.nihstro::Instruction::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<26u, 6u, nihstro::Instruction::OpCode>()’, which is of non-class type ‘nihstro::Instruction::OpCode’
             bool is_inverted = 0 != (instr.opcode.Value().GetInfo().subtype & OpCode::Info::SrcInversed);
                                                           ^
/home/maria/citra/src/video_core/vertex_shader.cpp:161:79: error: ‘OpCode’ has not been declared
             bool is_inverted = 0 != (instr.opcode.Value().GetInfo().subtype & OpCode::Info::SrcInversed);
                                                                               ^
/home/maria/citra/src/video_core/vertex_shader.cpp:201:116: error: request for member ‘GetIndex’ in ‘instr.nihstro::Instruction::common.nihstro::Instruction::<anonymous union>::dest.nihstro::Instruction::<anonymous union>::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<21u, 5u, unsigned int>()’, which is of non-class type ‘unsigned int’
             float24* dest = (instr.common.dest.Value() < 0x10) ? &state.output_registers[instr.common.dest.Value().GetIndex()][0]
                                                                                                                    ^
/home/maria/citra/src/video_core/vertex_shader.cpp:202:117: error: request for member ‘GetIndex’ in ‘instr.nihstro::Instruction::common.nihstro::Instruction::<anonymous union>::dest.nihstro::Instruction::<anonymous union>::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<21u, 5u, unsigned int>()’, which is of non-class type ‘unsigned int’
                         : (instr.common.dest.Value() < 0x20) ? &state.temporary_registers[instr.common.dest.Value().GetIndex()][0]
                                                                                                                     ^
/home/maria/citra/src/video_core/vertex_shader.cpp:207:42: error: request for member ‘EffectiveOpCode’ in ‘instr.nihstro::Instruction::opcode.nihstro::Instruction::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<26u, 6u, nihstro::Instruction::OpCode>()’, which is of non-class type ‘nihstro::Instruction::OpCode’
             switch (instr.opcode.Value().EffectiveOpCode()) {
                                          ^
/home/maria/citra/src/video_core/vertex_shader.cpp:208:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::ADD:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:220:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::MUL:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:232:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::MAX:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:241:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::DP3:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:242:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::DP4:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:245:63: error: ‘OpCode’ has not been declared
                 int num_components = (instr.opcode.Value() == OpCode::Id::DP3) ? 3 : 4;
                                                               ^
/home/maria/citra/src/video_core/vertex_shader.cpp:259:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::RCP:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:274:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::RSQ:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:288:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::MOVA:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:301:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::MOV:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:312:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::CMP:
                  ^
In file included from /home/maria/citra/src/./common/common.h:29:0,
                 from /home/maria/citra/src/./common/file_util.h:14,
                 from /home/maria/citra/src/video_core/vertex_shader.cpp:9:
/home/maria/citra/src/video_core/vertex_shader.cpp:353:53: error: request for member ‘EffectiveOpCode’ in ‘instr.nihstro::Instruction::opcode.nihstro::Instruction::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<26u, 6u, nihstro::Instruction::OpCode>()’, which is of non-class type ‘nihstro::Instruction::OpCode’
                           (int)instr.opcode.Value().EffectiveOpCode(), instr.opcode.Value().GetInfo().name, instr.hex);
                                                     ^
/home/maria/citra/src/./common/logging/log.h:99:39: note: in definition of macro ‘LOG_GENERIC’
         __FILE__, __LINE__, __func__, __VA_ARGS__)
                                       ^
/home/maria/citra/src/video_core/vertex_shader.cpp:352:17: note: in expansion of macro ‘LOG_ERROR’
                 LOG_ERROR(HW_GPU, "Unhandled arithmetic instruction: 0x%02x (%s): 0x%08x",
                 ^
/home/maria/citra/src/video_core/vertex_shader.cpp:353:93: error: request for member ‘GetInfo’ in ‘instr.nihstro::Instruction::opcode.nihstro::Instruction::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<26u, 6u, nihstro::Instruction::OpCode>()’, which is of non-class type ‘nihstro::Instruction::OpCode’
                           (int)instr.opcode.Value().EffectiveOpCode(), instr.opcode.Value().GetInfo().name, instr.hex);
                                                                                             ^
/home/maria/citra/src/./common/logging/log.h:99:39: note: in definition of macro ‘LOG_GENERIC’
         __FILE__, __LINE__, __func__, __VA_ARGS__)
                                       ^
/home/maria/citra/src/video_core/vertex_shader.cpp:352:17: note: in expansion of macro ‘LOG_ERROR’
                 LOG_ERROR(HW_GPU, "Unhandled arithmetic instruction: 0x%02x (%s): 0x%08x",
                 ^
/home/maria/citra/src/video_core/vertex_shader.cpp:361:14: error: ‘OpCode’ has not been declared
         case OpCode::Type::MultiplyAdd:
              ^
/home/maria/citra/src/video_core/vertex_shader.cpp:363:38: error: request for member ‘EffectiveOpCode’ in ‘instr.nihstro::Instruction::opcode.nihstro::Instruction::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<26u, 6u, nihstro::Instruction::OpCode>()’, which is of non-class type ‘nihstro::Instruction::OpCode’
             if (instr.opcode.Value().EffectiveOpCode() == OpCode::Id::MAD) {
                                      ^
/home/maria/citra/src/video_core/vertex_shader.cpp:363:59: error: ‘OpCode’ has not been declared
             if (instr.opcode.Value().EffectiveOpCode() == OpCode::Id::MAD) {
                                                           ^
/home/maria/citra/src/video_core/vertex_shader.cpp:411:114: error: request for member ‘GetIndex’ in ‘instr.nihstro::Instruction::mad.nihstro::Instruction::<anonymous union>::dest.nihstro::Instruction::<anonymous union>::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<24u, 5u, unsigned int>()’, which is of non-class type ‘unsigned int’
                 float24* dest = (instr.mad.dest.Value() < 0x10) ? &state.output_registers[instr.mad.dest.Value().GetIndex()][0]
                                                                                                                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:412:115: error: request for member ‘GetIndex’ in ‘instr.nihstro::Instruction::mad.nihstro::Instruction::<anonymous union>::dest.nihstro::Instruction::<anonymous union>::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<24u, 5u, unsigned int>()’, which is of non-class type ‘unsigned int’
                             : (instr.mad.dest.Value() < 0x20) ? &state.temporary_registers[instr.mad.dest.Value().GetIndex()][0]
                                                                                                                   ^
In file included from /home/maria/citra/src/./common/common.h:29:0,
                 from /home/maria/citra/src/./common/file_util.h:14,
                 from /home/maria/citra/src/video_core/vertex_shader.cpp:9:
/home/maria/citra/src/video_core/vertex_shader.cpp:423:53: error: request for member ‘EffectiveOpCode’ in ‘instr.nihstro::Instruction::opcode.nihstro::Instruction::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<26u, 6u, nihstro::Instruction::OpCode>()’, which is of non-class type ‘nihstro::Instruction::OpCode’
                           (int)instr.opcode.Value().EffectiveOpCode(), instr.opcode.Value().GetInfo().name, instr.hex);
                                                     ^
/home/maria/citra/src/./common/logging/log.h:99:39: note: in definition of macro ‘LOG_GENERIC’
         __FILE__, __LINE__, __func__, __VA_ARGS__)
                                       ^
/home/maria/citra/src/video_core/vertex_shader.cpp:422:17: note: in expansion of macro ‘LOG_ERROR’
                 LOG_ERROR(HW_GPU, "Unhandled multiply-add instruction: 0x%02x (%s): 0x%08x",
                 ^
/home/maria/citra/src/video_core/vertex_shader.cpp:423:93: error: request for member ‘GetInfo’ in ‘instr.nihstro::Instruction::opcode.nihstro::Instruction::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<26u, 6u, nihstro::Instruction::OpCode>()’, which is of non-class type ‘nihstro::Instruction::OpCode’
                           (int)instr.opcode.Value().EffectiveOpCode(), instr.opcode.Value().GetInfo().name, instr.hex);
                                                                                             ^
/home/maria/citra/src/./common/logging/log.h:99:39: note: in definition of macro ‘LOG_GENERIC’
         __FILE__, __LINE__, __func__, __VA_ARGS__)
                                       ^
/home/maria/citra/src/video_core/vertex_shader.cpp:422:17: note: in expansion of macro ‘LOG_ERROR’
                 LOG_ERROR(HW_GPU, "Unhandled multiply-add instruction: 0x%02x (%s): 0x%08x",
                 ^
/home/maria/citra/src/video_core/vertex_shader.cpp:451:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::END:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:455:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::JMPC:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:461:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::JMPU:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:467:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::CALL:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:474:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::CALLU:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:483:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::CALLC:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:492:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::NOP:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:495:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::IFU:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:510:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::IFC:
                  ^
/home/maria/citra/src/video_core/vertex_shader.cpp:529:18: error: ‘OpCode’ has not been declared
             case OpCode::Id::LOOP:
                  ^
In file included from /home/maria/citra/src/./common/common.h:29:0,
                 from /home/maria/citra/src/./common/file_util.h:14,
                 from /home/maria/citra/src/video_core/vertex_shader.cpp:9:
/home/maria/citra/src/video_core/vertex_shader.cpp:544:53: error: request for member ‘EffectiveOpCode’ in ‘instr.nihstro::Instruction::opcode.nihstro::Instruction::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<26u, 6u, nihstro::Instruction::OpCode>()’, which is of non-class type ‘nihstro::Instruction::OpCode’
                           (int)instr.opcode.Value().EffectiveOpCode(), instr.opcode.Value().GetInfo().name, instr.hex);
                                                     ^
/home/maria/citra/src/./common/logging/log.h:99:39: note: in definition of macro ‘LOG_GENERIC’
         __FILE__, __LINE__, __func__, __VA_ARGS__)
                                       ^
/home/maria/citra/src/video_core/vertex_shader.cpp:543:17: note: in expansion of macro ‘LOG_ERROR’
                 LOG_ERROR(HW_GPU, "Unhandled instruction: 0x%02x (%s): 0x%08x",
                 ^
/home/maria/citra/src/video_core/vertex_shader.cpp:544:93: error: request for member ‘GetInfo’ in ‘instr.nihstro::Instruction::opcode.nihstro::Instruction::<anonymous struct>::<anonymous>.nihstro::BitField<position, bits, T>::Value<26u, 6u, nihstro::Instruction::OpCode>()’, which is of non-class type ‘nihstro::Instruction::OpCode’
                           (int)instr.opcode.Value().EffectiveOpCode(), instr.opcode.Value().GetInfo().name, instr.hex);
                                                                                             ^
/home/maria/citra/src/./common/logging/log.h:99:39: note: in definition of macro ‘LOG_GENERIC’
         __FILE__, __LINE__, __func__, __VA_ARGS__)
                                       ^
/home/maria/citra/src/video_core/vertex_shader.cpp:543:17: note: in expansion of macro ‘LOG_ERROR’
                 LOG_ERROR(HW_GPU, "Unhandled instruction: 0x%02x (%s): 0x%08x",
                 ^
src/video_core/CMakeFiles/video_core.dir/build.make:261: set di istruzioni per l'obiettivo "src/video_core/CMakeFiles/video_core.dir/vertex_shader.cpp.o" non riuscito
make[2]: *** [src/video_core/CMakeFiles/video_core.dir/vertex_shader.cpp.o] Errore 1
CMakeFiles/Makefile2:334: set di istruzioni per l'obiettivo "src/video_core/CMakeFiles/video_core.dir/all" non riuscito
make[1]: *** [src/video_core/CMakeFiles/video_core.dir/all] Errore 2
Makefile:76: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

**Comment by jroweboy** [comment]
In the future, I recommend using pastebin or gist to post your logs in and link them here instead. :smile: it just makes it easier to read.

It looks like your nihstro isn't up to date. When you cloned the repo, did you remember to `git submodule update --init --recursive` and did you pull to the latest master? For future reference, when cloning repos with git versions >= 1.6.5 you can just use `git clone --recursive` to do all of that at clone time.

**Comment by archshift** [comment]
Please confirm whether that fixed your problem, otherwise this issue will be closed.

**Comment by neobrain** [comment]
Looks like an outdated submodule checkout. Not an actual issue.
