### ISSUE TITLE
Parsing the Package 

### ISSUE THREAD

**Issue by Abhijit0010** [citra-emu/citra#6663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly Build - 2126c24

### Description of Issue

I'm face a parsing problem with this built and some previous builts.
My device is Vivo Y95, it is compatible with Citra but still having this problem.
Please fix this or suggest me a way to fix it.

### Expected Behavior

I don't really know what to write here

### Reproduction Steps

Same goes with this,  I don't know what to write here 

### Log File

I don't have a log file

### System Configuration

CPU: Snapdragon 439
GPU/Driver:
RAM:4gb
OS: FuntouchOS

**Comment by GPUCode** [comment]
Please upload a log file

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
