### ISSUE TITLE
Vulkan Citra

### ISSUE THREAD

**Issue by rgbarros120** [citra-emu/citra#6689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2545

### Description of Issue

Goodnight. Any predictions of when the Vulkan api will return in the emulator. Whether to return or not.

### Expected Behavior

Goodnight. Any predictions of when the Vulkan api will return in the emulator. Whether to return or not.

### Reproduction Steps

Goodnight. Any predictions of when the Vulkan api will return in the emulator. Whether to return or not.

### Log File

Goodnight. Any predictions of when the Vulkan api will return in the emulator. Whether to return or not.

### System Configuration

CPU: RYZEN 3600
GPU/Driver: GALAX GEFORCE GTX 1650
RAM: 16GB
OS: WINDOWS 10 22H2

**Comment by FearlessTobi** [comment]
no
