### ISSUE TITLE
Crash while opening Theatrhythm

### ISSUE THREAD

**Issue by 716Girl** [citra-emu/citra#670]
http://puu.sh/gJ9HU/5b5df6d4ed.png
:error: core\mem_map_funcs.cpp:Memory:Read:99: unknown read32 @ 0x00000F98
:error: core\mem_map_funcs.cpp:Memory::Getpointer:179: unknown getpointer @ 0xfffffffc

**Comment by archshift** [comment]
Sorry, but this isn't really helpful.
