### ISSUE TITLE
Citra becomes unresponsive after a few seconds of gameplay on macOS

### ISSUE THREAD

**Issue by tech-ticks** [citra-emu/citra#6706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2530

### Description of Issue

After a few seconds of gameplay, Citra doesn't accept any inputs anymore although emulation continues and the game frame buffer keeps updating. The menu bar doesn't react either and the OS detects the application as unresponsive. Audio behavior depends on output type; OpenAL audio keeps playing while the "auto" backend gets stuck in sync with inputs.

I tested the two similar titles *Pokémon Super Mystery Dungeon* and *Gates to Infinity*, but I'm not sure if the issue is game-specific.

### Expected Behavior

Emulation should continue without Citra becoming unresponsive.

### Reproduction Steps

- Launch *Pokémon Super Mystery Dungeon* or *Gates to Infinity*
- Wait for a few seconds

I can reproduce the issue both by running the native ARM64 version and by running the Intel version via Rosetta.

### Log File

[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12093682/citra_log.txt.old.txt)

### System Configuration

CPU: Apple M2 Max
GPU/Driver: Apple M2 Max/Vulkan
RAM: 32 GB
OS: macOS 13.4.1

**Comment by WojciechJamroz** [comment]
Is this the same issue?

https://github.com/citra-emu/citra/issues/6633

**Comment by tech-ticks** [comment]
Looks like it is. I searched for "macOS" instead of "M1" in the closed issues, sorry for that.
