### ISSUE TITLE
Style Savvy: Fashion Forward - Crashes when loading a fashion venue

### ISSUE THREAD

**Issue by RocketRobz** [citra-emu/citra#6709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1950 / Canary 2554-2555

### Description of Issue

Whenever the game tries to load a currently set fashion venue, the game crashes.
This has not occurred in past couple of builds or so.

### Expected Behavior

Loading a fashion venue should not cause a crash, and should be displayed.

### Reproduction Steps

1. Select `Continue`
2. Press B to exit room
3. Press B to exit The Avenue
4. Select bottom-right place to enter Taylor Arcade
5. Select top-left place to enter Beaumonde Arena

Method one:

6. Select `Choose a Venue`
7. Select `Change`

Method two:

6. Select `Open the Fashion Show`
7. Press START in every menu displayed

Save file: https://cdn.discordapp.com/attachments/909943497455464509/1128113556504727583/savedata.dat
Place it in the root save data folder.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12096128/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 5 5600G with Radeon Graphics | AVX2 | FMA
GPU/Driver: Radeon RX 570 Series
RAM: 16GB
OS: Windows 10 Version 22H2 (Build 19045.3208)

**Comment by GPUCode** [comment]
If it's a recent regression, ca you figure out which build broke the game?

**Comment by RocketRobz** [comment]
Tried a build as far back as Canary 2513 (where I knew it didn't crash), and even prior, and the game still crashes.
At that point, I figured I somehow corrupted my save file, so I tried putting it on my N3DS XL console, and the game didn't crash there, so it's not the save data.

**Comment by RocketRobz** [comment]
Ah, just saw there's a fix available.
