### ISSUE TITLE
Incorrect color output for background graphics in Go! Go! Kokopolo Harmonious Forest Revenge

### ISSUE THREAD

**Issue by RupeeClock** [citra-emu/citra#6715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1952 / Canary 2557

### Description of Issue

Go! Go! Kokopolo Harmonious Forest Revenge (title ID `00040000001E2A00`) is a 3DS port of a DSiWare title available exclusively as a 3DS North American physical release.
It is unique in that it is a DSiWare game that runs in 3DS mode, and features a display scaling toggle between full-screen / original resolution by pressing L+Y.

When emulated using Citra's OpenGL Graphics API, a majority of graphics display with incorrect color information, with character animation unaffected. Emulating using Software Graphics API will display graphics with their correct colors.

[Go Go Kokopolo - Citra Canary 2557 - OpenGL - Hardware Share with Accurate Multiplication (2).webm](https://github.com/citra-emu/citra/assets/24753760/3388543b-9482-41ac-8e83-c59ac2fb0885)

### Reference screenshots captured from Nintendo New 3DS XL hardware using Luma3DS and firmware v11.16.0
![2023-07-21_21-20-24 598](https://github.com/citra-emu/citra/assets/24753760/470b4c6d-4310-4b94-b82f-2b601707370c) ![2023-07-21_21-20-31 206](https://github.com/citra-emu/citra/assets/24753760/5cb018b1-6ffd-4625-9060-d51c330a185e)
![2023-07-21_21-20-43 698](https://github.com/citra-emu/citra/assets/24753760/f340d89d-3c07-448f-b29d-157f009b2fdc) ![2023-07-21_21-21-53 064](https://github.com/citra-emu/citra/assets/24753760/ca1939c4-a0f9-463a-ae35-94e5ab5bc0d3)
![2023-07-21_21-24-47 191](https://github.com/citra-emu/citra/assets/24753760/175161c5-1807-47a2-8c8f-26bdbb0f1ec0) ![2023-07-21_21-25-16 454](https://github.com/citra-emu/citra/assets/24753760/b40279b9-7488-491e-aad5-ac61dcde78d6)
![2023-07-21_21-26-34 839](https://github.com/citra-emu/citra/assets/24753760/36c4bd10-96b9-41cc-b25f-7f5bff27a0ec) ![2023-07-21_21-26-41 637](https://github.com/citra-emu/citra/assets/24753760/1cfa6766-5256-4be2-b1bb-8ca3c73991e3)

### Reproduction Steps

- Set Graphics API to OpenGL
- Emulate Go! Go! Kokopolo Harmonious Forest Revenge (title ID `00040000001E2A00`)
- Color issues manifest as shown in screenshots below

![Go! Go! Kokopolo_21 07 23_19 31 30 366](https://github.com/citra-emu/citra/assets/24753760/9996137c-539b-4828-9966-51a219da6bfe) ![Go! Go! Kokopolo_21 07 23_19 31 32 213](https://github.com/citra-emu/citra/assets/24753760/036c1704-f6e8-4604-8915-87992fa22db1)
![Go! Go! Kokopolo_21 07 23_19 32 17 7](https://github.com/citra-emu/citra/assets/24753760/3340b07c-da23-485d-a7db-a6e83f3f0892) ![Go! Go! Kokopolo_21 07 23_19 31 49 904](https://github.com/citra-emu/citra/assets/24753760/5553e535-7daa-4ba5-bfa4-f6277bcf6f7d)
![Go! Go! Kokopolo_21 07 23_19 32 21 08](https://github.com/citra-emu/citra/assets/24753760/8d43e20e-af91-4c15-a34a-3edfc31fe540) ![Go! Go! Kokopolo_21 07 23_19 32 27 831](https://github.com/citra-emu/citra/assets/24753760/45b4ca1a-a7fb-4897-8f45-a72215de2ac4)
![Go! Go! Kokopolo_21 07 23_19 32 48 088](https://github.com/citra-emu/citra/assets/24753760/abf8b47c-015d-4574-a132-e03e5da24e37)![Go! Go! Kokopolo_21 07 23_19 32 56 027](https://github.com/citra-emu/citra/assets/24753760/d4cef3b2-c4fd-47bd-93a6-6725bab23a18)

Modifying these properties did not appear to have any bearing on the issue:
- System
    - Enable New 3DS Mode
- Enhancements
     - Internal Resolution
     - Enable Linear Filtering
     - Texture Filter
- Graphics
     - Enable Hardware Shader / Accurate Multiplication
     - Use Disk Shader Cache
     - Enable VSync
 - Debug
      - Enable debug renderer

### Log File

[citra_log_Go_Go_Kokopolo.txt](https://github.com/citra-emu/citra/files/12134957/citra_log_Go_Go_Kokopolo.txt)

### System Configuration

CPU: Intel Core i7 12700k
GPU/Driver: Nvidia RTX 3070 version 531.41
RAM: 32GB (2x16GB DDR5-5600 / PC5-44800 DDR5 SDRAM UDIMM)
OS: Windows 10 Professional version 22H2

**Comment by GPUCode** [comment]
@RupeeClock Please check linked PR to confirm the fix

**Comment by RupeeClock** [comment]
Fix appear to be a success.
Citra Canary build 2586 now displays Go! Go! Kokopolo Harmonious Forest Revenge with the correct colors, when using the OpenGL or Vulkan graphics APIs/backends. The issue was still present in build 2584 (from 2 days ago).
Testing was performed on a different machine than usual (Intel N100 with UHD graphics, Windows 11).

During testing, two things were encountered:
- Launching the game using Vulkan when a shader cache exists was prone to crashing; game would launch when Citra's shader folder was deleted, suggesting that either an invalid shader cache is being generated, or previously generated shaders are not compatible with this change
- Screenshots captured using Citra's screenshot tool (Ctrl+P) using the Vulkan API were upside down by being flipped vertical as opposed to rotated (not exclusive to this game), something that I will log as an issue in more detail when I am able

Build 2584 OpenGL screenshot:
![Go! Go! Kokopolo_14 08 23_13 35 18 16](https://github.com/citra-emu/citra/assets/24753760/08e58ab5-b3da-4085-a769-69c5cc09bf2f)

Build 2586 OpenGL screenshot:
![Go! Go! Kokopolo_14 08 23_13 44 53 072](https://github.com/citra-emu/citra/assets/24753760/8a570fde-f517-4e4e-ae9e-45160e55239f)

Build 2586 Vulkan screenshot (uncorrected):
![Go! Go! Kokopolo_14 08 23_13 41 21 414](https://github.com/citra-emu/citra/assets/24753760/7a08aefb-f460-4d51-bf97-853fbb2ef5c0)
