### ISSUE TITLE
Glslangvalidator not found

### ISSUE THREAD

**Issue by WOOVYWOOVY** [citra-emu/citra#6822]
### Issue

I was building the latest release in androidstudio with the latest dependencies on, and did all the instructions. But there's an error in cmakelist.txt at the video_core/host_shaders. It says that  program glslangvalidator not found, even though i already did recursive the whole git.

Is there any solution to this? Sorry if i don't quite understand this.

**Comment by wheremyfoodat** [comment]
Have you installed the Android Vulkan SDK?

**Comment by WOOVYWOOVY** [comment]
Yep, but nah actually nevermind, i was just trying to make the build for android api 22, and just realized that vulkan only support api level 24 lol
