### ISSUE TITLE
Smart pointers in config per game

### ISSUE THREAD

**Issue by luc-git** [citra-emu/citra#6830]
### Issue

https://github.com/citra-emu/citra/blob/335fb78c5cfeedfe0e285a475b31ee8158e703da/src/citra_qt/configuration/configure_per_game.cpp#L37

Why using smart pointers? Those widgets have parents and in QT if you delete a widget its children are deleted as well

**Comment by GPUCode** [comment]
Qt lifetime system will only destroy these if the parent is destroyed as well. The main window stays alive after the configuration pages are closed so we need to manually destroy these and thus smart pointers are used

**Comment by GPUCode** [comment]
Actually you might be correct on this one, the parrent here is ConfigurePerGame which is destroyed when the dialog exits

**Comment by GPUCode** [comment]
The question is if the lifetime system applies when the parent is created in the stack

**Comment by GPUCode** [comment]
It seems like it does. Though does using smart pointers really matter in the real world?

**Comment by luc-git** [comment]
Wdym by really matter?

**Comment by luc-git** [comment]
And if you close qdialog I think it is destroyed

**Comment by GPUCode** [comment]
> Wdym by really matter?

Is using unique_ptr here actively detrimental to the application stability? In general the code style rules say never use new/delete so unique_ptr is prefered in almost all cases

**Comment by GPUCode** [comment]
> And if you close qdialog I think it is deleted. It has no parent

Most of the dialogs I've seen are stack constructed so they get destroyed automatically when they go out of scope. Don't quote me on that though

**Comment by FearlessTobi** [comment]
Since this does not really matter for us, I'm going to close this issue again.
