### ISSUE TITLE
cant play mk7 multiplayer

### ISSUE THREAD

**Issue by soupnuts6061** [citra-emu/citra#6831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1958

### Description of Issue

mk7 multiplayer always fails, it never works, constant connects/disconnects, dlp doesn't work, i only got to the please wait screen once

### Expected Behavior

i should be able to play mk7 multiplayer properly

### Reproduction Steps

play mk7 multiplayer, no really thats it thats how buggy it is

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12221739/citra_log.txt)

### System Configuration

CPU: 11th gen intel core i7-11370H @ 3.30GHz
GPU/Driver: intel iris xe graphics/ nvidia geforce rtx 3050 ti laptop gpu
RAM: no clue
OS: Windows 11

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum, please use our Discord for support.
