### ISSUE TITLE
Some outlines missing in Yo-Kai Watch 1+2+3

### ISSUE THREAD

**Issue by Yo-Kai-Modding** [citra-emu/citra#6833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1958 + Canary 2569 (bug started to occur before these released though)

### Description of Issue

Depending on what part of the game you are in, some outlines can be missing (happens mostly in cutscenes and always in the new save file creation screen)
![image](https://github.com/citra-emu/citra/assets/115092262/f1cf192b-b157-43a0-aff2-24c35d427306)

### Expected Behavior

I expect the outlines to render.
![image](https://github.com/citra-emu/citra/assets/115092262/c7afef9d-7a80-42e1-a472-d3d6ecf0c3fa)

### Reproduction Steps

Open either Yo-Kai Watch 1, 2 or 3 and go to New Game, select a save slot and dismiss the dialogue. You will see that the player model on the top screen is missing an outline.

### 
[citra_log.txt](https://github.com/citra-emu/citra/files/12230122/citra_log.txt)

### System Configuration

CPU: Intel i7 4770k
GPU/Driver: Nvidia Quadro 2000
RAM: 16GB
OS: Windows 10

**Comment by GPUCode** [comment]
Cannot reproduce this issue on the specified build. Your GPU drivers appears to be very outdated (377.83). Do the outlines work in Vulkan? Also send a log file with debug renderer enabled (General -> Debug tab). 
![YO-KAI WATCH_05 08 23_13 17 31 601](https://github.com/citra-emu/citra/assets/47210458/bee4becd-33ee-492f-9537-020ad8a1effb)

**Comment by Yo-Kai-Modding** [comment]
Nevermind, the bug is fixed by turning on Accurate Multiplication
