### ISSUE TITLE
Not working well when installing DLC files created by CIA using makerom

### ISSUE THREAD

**Issue by rcyggdra** [citra-emu/citra#6836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

canary 2574

### Description of Issue

This DLC file works on my 3DS, but Citra cannot.
the 00000013.app has become 0 bytes:
![image](https://github.com/citra-emu/citra/assets/8652464/8f43a34e-38e8-4f83-adef-2c69c5cf614f)

This is a list of the original DLC files:
![image](https://github.com/citra-emu/citra/assets/8652464/0174e465-edac-4904-9546-516ae8b7cccf)

sample files:
https://mega.nz/folder/pJ4lkTCR#6hB99DeKUYjn92UCvu9Ocw

### Expected Behavior

none

### Reproduction Steps

none

### Log File

none

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by FearlessTobi** [comment]
As you said yourself, after using makerom data is missing now.
Also you did not fill out the issue template correctly.
