### ISSUE TITLE
Luigi Mansion breaking in citra vulkan

### ISSUE THREAD

**Issue by rgbarros120** [citra-emu/citra#6841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2575

### Description of Issue

Luigi Mansion breaking in citra vulkan

### Expected Behavior

Luigi Mansion breaking in citra vulkan

### Reproduction Steps

Luigi Mansion breaking in citra vulkan

### Log File

Luigi Mansion breaking in citra vulkan

### System Configuration

CPU: ryzen 5 3600
GPU/Driver: Gtx 1650 oc 4GB
RAM: 16G ram 2400mhz
OS: Windows 10 22H2

**Comment by SleepingSnakezzz** [comment]
Please don't ignore the issue creation template, thanks.

**Comment by rgbarros120** [comment]
> Please don't ignore the issue creation template, thanks.

Good afternoon, you keep removing the bug report this way, it gets complicated, so apparently it's no use reporting bugs on this emulator. Better close this github.
