### ISSUE TITLE
Canary 2575 - Vulkan Backend semaphore crash on DQMJ3Pro

### ISSUE THREAD

**Issue by Xemorr** [citra-emu/citra#6842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2575

### Description of Issue

DQMJ3Pro (english patch if relevant?) crashes when using Vulkan Backend (freezes, sometimes makes it into a loaded save file, but sometimes crashes on main menu)

### Expected Behavior

It does not crash and you can play the game as expected

### Reproduction Steps

Load a DQMJ3Pro game using Vulkan Backend, attempt to play

### Log File

[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12244214/citra_log.txt.old.txt) (all three SPIR-V, async presentation, async shader compilation turned on)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12244253/citra_log.txt.old.txt) (just async presentation)
.. probably same 
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12254633/citra_log.txt.old.txt) (crash without any of these settings, took longer was when I attempted to battle a monster)

### System Configuration

CPU: Ryzen 9 5950X
GPU/Driver: NVIDIA Titan XP, 531.79
RAM: 32GB, 2666MHz DDR4 (doubt it's that relevant?)
OS: Windows 11

**Comment by Xemorr** [comment]
To be clear, it happens with all three settings on, or any one of them on. (have not bothered to test with only two on, but I assume it happens still)

**Comment by GPUCode** [comment]
Have you tried any other games?

**Comment by Xemorr** [comment]
> Have you tried any other games?

I just tried Dragon Quest VIII (don't have any other roms to hand), this also crashed with SPIR-V enabled, haven't tested the other parameters specifically, these were all off in my test of DQVIII.

**Comment by GPUCode** [comment]
Can you enable debug renderer in the debug menu and send new logs with the crash?

**Comment by Xemorr** [comment]
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12254891/citra_log.txt.old.txt)
This log should have those details in

**Comment by GPUCode** [comment]
Should be f ixed in the next canary
