### ISSUE TITLE
Can’t open citra in game mode nor desktop mode for steam deck

### ISSUE THREAD

**Issue by anhcestor** [citra-emu/citra#6846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1234

### Description of Issue

I have tried uninstalling and reinstalling and nothing works the app can’t open for some reason in game mode nor desktop mode for the steam deck.

### Expected Behavior

Usually it opens fine but first time encountering this issue

### Reproduction Steps

N/A

### Log File

Can’t open log because app can’t open

### System Configuration

CPU:
GPU/Driver:
RAM:
OS: Steam OS

**Comment by AvidGamer19** [comment]
Yeah, i have the same issue, unfortunately

**Comment by anhcestor** [comment]
sudo flatpak update --commit=8cc58188ccf54c6bcae70aa53199504b878f8e491421efd4d90fc93533a253ac org.citra_emu.citra


Is what fixed it for me thank you citra discord.

**Comment by AvidGamer19** [comment]
> sudo flatpak update --commit=8cc58188ccf54c6bcae70aa53199504b878f8e491421efd4d90fc93533a253ac org.citra_emu.citra
> 
> Is what fixed it for me thank you citra discord.

Will using this in the terminal mess with emudeck's built in emulator manager?

**Comment by anhcestor** [comment]
> > sudo flatpak update --commit=8cc58188ccf54c6bcae70aa53199504b878f8e491421efd4d90fc93533a253ac org.citra_emu.citra
> > Is what fixed it for me thank you citra discord.
> 
> Will using this in the terminal mess with emudeck's built in emulator manager?

I mean so far nothing has happened to me so I guess you are good for now this is what the developers told me on the discord

**Comment by Creepergabbe** [comment]
> sudo flatpak update --commit=8cc58188ccf54c6bcae70aa53199504b878f8e491421efd4d90fc93533a253ac org.citra_emu.citra
> 
> Is what fixed it for me thank you citra discord.

i did this and it didn't work it just says "org.citra_emu.citra not installed"

**Comment by anhcestor** [comment]
> > sudo flatpak update --commit=8cc58188ccf54c6bcae70aa53199504b878f8e491421efd4d90fc93533a253ac org.citra_emu.citra
> > Is what fixed it for me thank you citra discord.
> 
> i did this and it didn't work it just says "org.citra_emu.citra not installed"

Did you download citra thru their website or emu deck?

**Comment by Creepergabbe** [comment]
> > > sudo flatpak update --commit=8cc58188ccf54c6bcae70aa53199504b878f8e491421efd4d90fc93533a253ac org.citra_emu.citra
> > > Is what fixed it for me thank you citra discord.
> > 
> > 
> > i did this and it didn't work it just says "org.citra_emu.citra not installed"
> 
> Did you download citra thru their website or emu deck?

emudeck
