### ISSUE TITLE
Samus Returns Crashing at Startup with Preload Custom Textures on

### ISSUE THREAD

**Issue by greensad** [citra-emu/citra#6852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1962 / Canary 2575

### Description of Issue

Metroid Samus Returns crashes with no error code or dialogue box/output the window simply closes. This happens after launching the game, stopping the game or closing Citra, and then launching the game again. I have re-dumped my cart multiple times and deleted my shaders folder but the issue persists. Should be very easy to reproduce/test in your own environments. Something to note; re-dumping my cart allows the game to work on first boot once again but closing/stopping emulation re-introduces the issue.

### Expected Behavior

Launch the game as many times as desired without game closing on boot.

### Reproduction Steps

1. Launch game.
2. Stop/close game.
3. Launch game again.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12265918/citra_log.txt)

### System Configuration

CPU: Intel 13600k
GPU/Driver: EVGA FTW3 3080 10GB
RAM: 32gb
OS: Win11

**Comment by greensad** [comment]
Hey y'all, I did a bit of testing on various nightlies:

- crash origin appears to be nightly 1960.
- nightly1959 does not crash.
- 1960 and above crash consistently.

Will test on another device to see if I can reproduce, then I'll post the results.

**Comment by FearlessTobi** [comment]
Thanks a lot, thats very helpful!

The culprit is https://github.com/citra-emu/citra/pull/6834 then.

**Comment by GPUCode** [comment]
Can you test if latest Nightly (1970) has the crashing issue?

**Comment by greensad** [comment]
> 

At the time of posting, 1960 and above were crashing, including 1970

**Comment by greensad** [comment]
Bit of an update, did some more testing and found out the issue. Had "Preload Custom Textures" on and turning that option off solves the issue. I do have custom textures for this game and they load fine when this option is disabled. Additionally I could not reproduce the issue on another device using the same settings as my main device. The second device I tried was running Win10 where are my main device where the game is crashing is running Win11.

**Comment by greensad** [comment]
Well somewhere along the way this got resolved in one of the releases post 2000. I was testing periodically up until 2000 which was still having the issue when preloading custom textures but I tried 2030 tonight and am happy to report that the crashing has stopped, I'll close the issue!
