### ISSUE TITLE
Scrolling too fast with custom textures in Pokémon games crashes Citra

### ISSUE THREAD

**Issue by TwistedTempest** [citra-emu/citra#6857]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

Nightly 1692/Canary 2575

### Description of Issue

I have observed this issue in both Pokémon Y and Omega Ruby. Going into the item menu and holding down the D-Pad or circle stick (or just tapping in one direction rapidly enough) to scroll through items causes the game to freeze and then Citra to crash. It only occurs if custom textures are enabled, but even if the textures do not affect the items in question Citra will still crash. No amount of changes to graphical settings, including but not limited to changing APIs or enabling and disabling nearly every feature under the "graphics" part of settings one by one, will solve the issue - with the sole exception of turning off custom textures altogether.

### Expected Behavior

Crashing when scrolling "too fast" in the Item menu of Pokémon Y/Omega Ruby (the speed achieved when holding one direction on the circle or D-pad) and custom textures are enabled and present. Provided is a video of the phenomenon

https://github.com/citra-emu/citra/assets/75958359/bf580e0e-0058-497e-86e7-e12cd4cee9c0

### Reproduction Steps

On any save of Y or Omega Ruby with enough progress to open the item menu, scroll in any direction by holding that direction on the D-pad or circle pad. Custom textures must be enabled. Provided are my custom textures and save files for both games

[Y Texture Pack](https://github.com/Ullr8/Pokemon-Y-Resurrection/releases/download/v0.2/0004000000055E00.7z)
[OR Texture Pack](https://drive.google.com/file/d/16c2r-XY0bUT9PfvkebJusp4zKBXfTqPo/view)
[saves.zip](https://github.com/citra-emu/citra/files/12268242/saves.zip)

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12268228/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 7 3800X
GPU/Driver: Nvidia RTX 3060 Ti - 536.67 Driver
RAM: 32GB DDR4 @ 3200MT/s
OS: Windows 10 Home 22H2

**Comment by GPUCode** [comment]
Can you test artifact of this PR if it fixes the issue? https://github.com/citra-emu/citra/pull/6851

**Comment by TwistedTempest** [comment]
> Can you test artifact of this PR if it fixes the issue? #6851

I apologize as I am not very inclined when it comes to GitHub terminology, is there a simpler way of describing what I should do?

**Comment by GPUCode** [comment]
Test if this build crashes https://github.com/citra-emu/citra/suites/14844625324/artifacts/845394119

**Comment by TwistedTempest** [comment]
The issue is not present on the provided build. Thank you!
