### ISSUE TITLE
Super Smash Bros. for 3DS crashes Citra loading character select screen

### ISSUE THREAD

**Issue by SpareEnderboy** [citra-emu/citra#6858]
### Issue

Upon loading the character select screen, the game will freeze and then Citra will crash.

https://github.com/citra-emu/citra-games-wiki/assets/113299492/00cfa3c5-d25c-49c7-b28b-cc19f1bbae5a

**Comment by SachinVin** [comment]
Please use the issue template and fill ALL the details
