### ISSUE TITLE
Menu only displays every second game's cover art

### ISSUE THREAD

**Issue by TwistedTempest** [citra-emu/citra#6860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1692 / Canary 2576

### Description of Issue

Exclusively in the nightly build of Citra (formerly, now in both Nightly and Canary builds), when sorting through games every even numbered game in the list from the top will show its cover art and a color indicator of its compatibility with Citra. The odd-numbered games are still fully displayed. Hovering over an even-numbered game with the cursor will display the hidden images

### Expected Behavior

https://github.com/citra-emu/citra/assets/75958359/939a377c-5f09-4e10-9b3a-962009ded25d

### Reproduction Steps

Open latest Citra build with at least 2 games in chosen directory

### Log File

N/A, but [just in case](https://github.com/citra-emu/citra/files/12268362/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 7 3800X
GPU/Driver: Nvidia RTX 3060 Ti - 536.67 Driver
RAM: 32GB DDR4 @ 3200MT/s
OS: Windows 10 Home 22H2

**Comment by SpareEnderboy** [comment]
I got the same problem. Though, it doesn't seem to happen in light mode....

https://github.com/citra-emu/citra/assets/113299492/f843bfff-78d1-4641-ac54-87325aeec86b

**Comment by TwistedTempest** [comment]
This issue now affects the latest Canary build (a bug imported from Nightly?) and it has been updated to say so
