### ISSUE TITLE
Emulator crashing on pokemon ultra moon with custom textures 

### ISSUE THREAD

**Issue by jochuan** [citra-emu/citra#6861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1962

### Description of Issue

After updating the emulator today it is closing everytime that i try to open pokemon ultra moon and after some tinkering i found out that disabling the HD custom texture that i am using make the game to boot normally. I didn't had this issue before so it must be some kind of regression.

### Expected Behavior

The emulator should load the game without closing

### Reproduction Steps

Have custom textures enabled and try to boot the game

### Log File

[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12268481/citra_log.txt.old.txt)

### System Configuration

CPU: Ryzen 5 5600
GPU/Driver: RX6750XT/ Driver version 23.7.2
RAM: 16gb
OS: Windows 10

**Comment by SleepingSnakezzz** [comment]
This should be fixed in the next Canary build by https://github.com/citra-emu/citra/pull/6851

**Comment by jochuan** [comment]
Did this change was already merged on the nighlty builds ? because the emulator is still closing for me
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12387029/citra_log.txt.old.txt)

**Comment by SleepingSnakezzz** [comment]
Does it also crash without using Preload Custom Textures?

**Comment by jochuan** [comment]
> Does it also crash without using Preload Custom Textures?

I was already using that option when it crashed the only difference from before is that the crash is in-game now instead of when it is booting.

**Comment by jochuan** [comment]
Disabling preload custom textures makes the crash to not happen

**Comment by SleepingSnakezzz** [comment]
Then that's why. Preload Custom Textures requires an enormous amount of RAM, even for relatively small texture packs. With async custom textures, it's also generally not needed.

**Comment by jochuan** [comment]
> Then that's why. Preload Custom Textures requires an enormous amount of RAM, even for relatively small texture packs. With async custom textures, it's also generally not needed.

The strange thing is that i always had this option on before and the game emulator never crashed like that. And recently i upgraded my ram for 32gb so even if it is using a lot of ram it shouldn't be a problem unless this is some kind of memory leak.

**Comment by SleepingSnakezzz** [comment]
This is preloading custom textures when the texture pack is 3.1GB in size. Commits RAM until 31.1GB, then runs just fine afterwards. Though, it does seem like it's using more RAM than it did previously. The same texture pack used about 24GB of RAM in the past if I recall correctly. But I'm not entirely positive on that.
![image](https://github.com/citra-emu/citra/assets/71992016/8fc50ce7-994c-4eab-a66e-24cfdf7cb76e)
![image](https://github.com/citra-emu/citra/assets/71992016/e623652a-7800-45f4-8601-ac92f063d7b1)
