### ISSUE TITLE
Games display white screen while outputting audio and accepting input

### ISSUE THREAD

**Issue by TwistedTempest** [citra-emu/citra#6869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1693/Canary 2577

### Description of Issue

With the introduction of both the new Nightly and Canary builds, games now throw a white screen that accepts button input and still plays audio, but has no video. Doing some digging revealed that this issue has sometimes appeared on MacOS and was solved by resizing the game window, but this issue is on Windows 10 and changing the game window's size has no effect.

### Expected Behavior

https://github.com/citra-emu/citra/assets/75958359/cfa6a177-15a0-46b8-a30a-2f03420f2b42

### Reproduction Steps

Open any game on latest Nightly or Canary build

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12271522/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 7 3800X
GPU/Driver: Nvidia RTX 3060 Ti - 536.67 Driver
RAM: 32GB DDR4 @ 3200MT/s
OS: Windows 10 Home 22H2

**Comment by Steveice10** [comment]
Should be fixed by Nightly 1964 / Canary 2578.
