### ISSUE TITLE
Games load to blank screen

### ISSUE THREAD

**Issue by Garebear13** [citra-emu/citra#6870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1963

### Description of Issue

All of my downloaded games, Pokemon Ultra Sun, Pokemon X, and Pokemon Omega Ruby, load to blank screens. They output audio and accept controller input but there is no video whether using OpenGL or software rendering.

https://github.com/citra-emu/citra/assets/38664971/90b41734-b362-4db4-83c7-4e18256e128b

### Expected Behavior

All games were working fine before today's update (8/6)

### Reproduction Steps

Only thing changed that caused this issue was an update from previous Nightly to current Nightly (1963)

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12271531/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 5 3600X
GPU/Driver: NVidia GTX 1030 3gb Driver 536.67
RAM: 32gb G.SKILL Trident Z RGB 3200mhz
OS: Windows 10 22H2

**Comment by bornout** [comment]
Same with Canary 2577.  Vulkan works OpenGL no.

**Comment by SleepingSnakezzz** [comment]
We do not support piracy here.
