### ISSUE TITLE
Mario Sports Superstars - Fatal error on Golf or Tennis

### ISSUE THREAD

**Issue by SleepingSnakezzz** [citra-emu/citra#6882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1948 and onwards

### Description of Issue

Choosing Tennis or Golf will result in a fatal error.
Likely relevant part of the log file:

```
[ 155.041365] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:262: Unregistered interrupt=2, channel=2
[ 155.041661] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:UnloadComponent:203: (STUBBED)
[ 155.102187] Service.LDR <Info> core/hle/service/ldr_ro/ldr_ro.cpp:UnloadCRO:369: Unloading CRO "uniform_core"
[ 155.114054] Service.LDR <Error> core/hle/service/ldr_ro/cro_helper.cpp:Rebase:1130: Error rebasing header D9012C11
[ 155.114061] Service.LDR <Error> core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRO:279: Error rebasing CRO D9012C11
[ 155.114564] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:1102: Emulated program broke execution!
[ 155.114567] Debug.Emulated <Critical> core/hle/kernel/svc.cpp:Break:1118: Break reason: PANIC
```
Edit: I've been informed that this part is probably not relevant. The issue likely happens before this.
### Expected Behavior

Should be able to play the minigame and not be presented with a fatal error.

### Reproduction Steps

Choose Tennis or Golf in-game

### Log File

Log file from user wokie (wokiie\326413698325413898) on discord: [Mario Sports Superstars log.txt](https://github.com/citra-emu/citra/files/12319800/Mario.Sports.Superstars.log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz | AVX2 | FMA
GPU/Driver: NVIDIA GeForce MX350/PCIe/SSE2 - NVIDIA 536.99
RAM: Host RAM: 7.80 GiB - Host Swap: 9.24 GiB
OS: Windows 11 Version 22H2

**Comment by FearlessTobi** [comment]
This has been supposedly fixed before: https://github.com/citra-emu/citra/pull/5125.
Can you please retest on an older build of Citra?

**Comment by SleepingSnakezzz** [comment]
According to SachinV, the error I quoted likely happened after what causes the crash. Regardless, it was a user who reported this issue, I didn't test this myself. I'll ask them to try it out on Discord.

**Comment by sakuramipha** [comment]
Either of these two PRs caused this issue: https://github.com/citra-emu/citra/pull/6680 or https://github.com/citra-emu/citra/pull/6684
@Steveice10
