### ISSUE TITLE
Captain Toad - Treasure Tracker dark walls using vulkan

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2588

### Description of Issue

start the game and the walls are really dark
![Screenshot 2023-08-16 151138](https://github.com/citra-emu/citra/assets/2696404/cbccdb55-ce35-4b79-b37f-62bdcd50562e)

### Expected Behavior

lighting to be correct

### Reproduction Steps

start a new game

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12356697/citra_log.txt)

### System Configuration

 AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
 Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, 
 GPU: 'NVIDIA GeForce RTX 3060' running on driver 536.99.0.0

**Comment by GPUCode** [comment]
This is a bug in the shadow code and should be present in opengl and software as well

**Comment by benderscruffy** [comment]
close in favour of #3920
