### ISSUE TITLE
Battle circle shadow not rendered correctly in Pokémon X

### ISSUE THREAD

**Issue by Lolothepro** [citra-emu/citra#6894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Citra Canary 2587

### Description of Issue

![Pokémon X_16 08 23_14 01 42 1](https://github.com/citra-emu/citra/assets/68275908/b05cfde1-dcd7-48d7-9a7f-a9a76d7871f7)

### Expected Behavior

Expected:
That the shadow is correctly rendered, and all around the circle

### Reproduction Steps

Launch Pokémon Y and go into battle.

### Log File

[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12359157/citra_log.txt.old.txt)

### System Configuration

CPU: Ryzen 3600
GPU/Driver: GTX 1070
RAM: 16 Go
OS: Ubuntu 22.04

**Comment by rgbarros120** [comment]
Goodnight. I would like to say that all games continue to be unstable with this new vulkan api, you removed this api for repair, but it remains the same as before, many games crashing all the time.

**Comment by Lolothepro** [comment]
Note: this bug occurs with both Vulkan and OpenGL.

**Comment by GPUCode** [comment]
Do you know if this is a recent regression or if thisnbug has existed for a while?

**Comment by Lolothepro** [comment]
> Do you know if this is a recent regression or if thisnbug has existed for a while?

No, but I'll check

**Comment by Lolothepro** [comment]
Ok, enabling "Accurate Multiplication" fixes the bug, is it possible to fix it without using "Accurate Multiplication"?
@GPUCode

**Comment by FearlessTobi** [comment]
I will close this then as this is fixed by enabling the setting.
