### ISSUE TITLE
Many games crashing on vulkan

### ISSUE THREAD

**Issue by rgbarros120** [citra-emu/citra#6896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Goodnight. I would like to say that all games continue to be unstable with this new vulkan api, you removed this api for repair, but it remains the same as before, many games crashing all the time.

### Why would this feature be useful?

Goodnight. I would like to say that all games continue to be unstable with this new vulkan api, you removed this api for repair, but it remains the same as before, many games crashing all the time.

**Comment by gidoly** [comment]
Post log

**Comment by FearlessTobi** [comment]
Wrong issue template.
