### ISSUE TITLE
Flow control statements are not properly nested - externals/CMakeLists.txt

### ISSUE THREAD

**Issue by MagelessMayhem** [citra-emu/citra#6897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest Git

### Description of Issue

CMake fails when trying to read CMakeLists.txt under `externals/`:
![Screenshot_20230816_211707](https://github.com/citra-emu/citra/assets/107271276/73cdd4a7-6ba1-4fc3-8993-c1a36dfa92dd)

This is on an up-to-date install of Gentoo Linux 2.13.

### Expected Behavior

`externals/CMakeLists.txt` should be properly formatted and the build process proceed as normal.

### Reproduction Steps

This issue is very easy to reproduce on an install of Gentoo:

- Enable the GURU overlay (`sudo eselect repository enable guru && sudo emerge --sync guru`). You need Git installed for this.
- Unmask Citra (`games-emulation/citra`) by issuing `sudo emerge --autounmask=y citra`. Proceed with any autounmasking process you use.
- Install Citra after unmasking it (`sudo emerge citra`).
- Observe the failure when Portage runs CMake.

### Log File

This is the Portage log of the build process: [build.log](https://github.com/citra-emu/citra/files/12364541/build.log)

### System Configuration

CPU: Intel Core i5-12600KF
GPU/Driver: AMD Radeon RX 6650 XT. Mesa 23.1.3 AMDGPU
RAM: 32 GB
OS: Gentoo Linux 2.13

**Comment by Steveice10** [comment]
You’ll need to file this with the maintainers of the GURU scripts, they make modifications to the build files using sed that are broken.
