### ISSUE TITLE
Mario and Donkey Kong - Minis on the Move (USA) (eShop) crashes out with Vulkan

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2591

### Description of Issue

start the main game
and then it crashes out the emulator
[  22.048940] Debug <Critical> ./video_core/renderer_vulkan/pica_to_vk.h:operator():129: Assertion Failed!
Unknown logic op 9202
goes in game with opengl

### Expected Behavior

play 1st level

### Reproduction Steps

start a new game

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12385506/citra_log.txt)

### System Configuration

AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none,
GPU: 'NVIDIA GeForce RTX 3060' running on driver 536.99.0.0

**Comment by wheremyfoodat** [comment]
Weird, the logic op requested is invalid, seemingly like the color op select config is not being properly masked
https://github.com/citra-emu/citra/blob/6ddf4b241f19ecec89b867fc8d5fa30d1645fd12/src/video_core/renderer_vulkan/pica_to_vk.h#L128

**Comment by GPUCode** [comment]
Fixed in next canary
