### ISSUE TITLE
WarioWare Gold (USA) crashes out on 5volt with Vulkan

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2591

### Description of Issue

after you do a couple of mini games and when it comes up with goal it always freezes up and crashes out the emulator
doesnt happen it opengl
![Screenshot 2023-08-19 175205](https://github.com/citra-emu/citra/assets/2696404/717deb0c-c900-4daa-b152-5a5b1ec90b59)
the error doesnt show up in the log
![Screenshot 2023-08-19 175835](https://github.com/citra-emu/citra/assets/2696404/4dde4a15-d18e-4be7-bbe5-801387c84f65)

### Expected Behavior

continue game and not crash out

### Reproduction Steps

play 5 volt mini games

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12385531/citra_log.txt)

### System Configuration

AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none,
GPU: 'NVIDIA GeForce RTX 3060' running on driver 536.99.0.0

**Comment by GPUCode** [comment]
Is this consistently reproducible or it crashes randomly?

**Comment by GPUCode** [comment]
Can't reproduce crashes with the Goal minigame

**Comment by benderscruffy** [comment]
it crashes out constantly at the same spot every time without fail

**Comment by GPUCode** [comment]
Could you upload a video of the crash and a save file?

**Comment by GPUCode** [comment]
I have seen this error before and most of the time it's quite random so having a place where it can be consistenly reproduced would be nice

**Comment by benderscruffy** [comment]
ok just upgraded to 2593 and it got past it 
i tried it 3 times and it past it all the time
weird ???

**Comment by GPUCode** [comment]
Next canary fixes this crash

**Comment by benderscruffy** [comment]
@GPUCode 
havent had any crashes or  device lost as in #6912 in any games so far
great job
