### ISSUE TITLE
VK: Pokémon Mystery Dungeon's introduction is broken

### ISSUE THREAD

**Issue by Lolothepro** [citra-emu/citra#6904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Citra Canary 2593

### Description of Issue

![image](https://github.com/citra-emu/citra/assets/68275908/7ee3b1b1-ddc2-4872-9d3b-08655b038fe5)

### Expected Behavior

![image](https://github.com/citra-emu/citra/assets/68275908/35fdd415-0f46-4d93-ab9d-3abb5ee577af)

### Reproduction Steps

*

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12388494/citra_log.txt)

### System Configuration

CPU: Ryzen 3600
GPU/Driver: GTX 1070
RAM: 16 Go
OS: Ubuntu 22.04

**Comment by GPUCode** [comment]
Fixed in next canary
