### ISSUE TITLE
Donkey Kong Country Returns 3D (USA) large flashing black square on map using Vulkan

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2595

### Description of Issue

large flashing black square on the map
doesn't happen on opengl

### Expected Behavior

no flashing black square

### Reproduction Steps

load game and get to map to see it

### Log File
here is a video of it
[Base Profile 2023.08.22 - 16.46.56.04.zip](https://github.com/citra-emu/citra/files/12406825/Base.Profile.2023.08.22.-.16.46.56.04.zip)

### System Configuration

AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none,
GPU: 'NVIDIA GeForce RTX 3060' running on driver 536.99.0.0

**Comment by GPUCode** [comment]
Fixed in next canary
