### ISSUE TITLE
New Super Mario Bros. 2 (USA) crashes out when you start a new game with Vulkan

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2595

### Description of Issue

click on a new game and the emulator will crash out happens every time
doesnt happen on open gl
[  15.932631] Render.Vulkan <Critical> video_core/renderer_vulkan/vk_master_semaphore.cpp:SubmitWork:101: Device lost during submit: vk::Queue::submit: ErrorDeviceLost
[  15.932636] Debug <Critical> video_core/renderer_vulkan/vk_master_semaphore.cpp:operator():102: Unreachable code!

### Expected Behavior

go ingame

### Reproduction Steps

click on new game

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12407249/citra_log.txt)

### System Configuration

AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none,
GPU: 'NVIDIA GeForce RTX 3060' running on driver 536.99.0.0

**Comment by GPUCode** [comment]
Cannot reproduce

**Comment by GPUCode** [comment]
Please test PR artifact, as current canary has a bug that causes many issues

**Comment by GPUCode** [comment]
I've tested the latest canary build and all games I tested work correctly. Have you tried resetting your settings or update your driver?

**Comment by benderscruffy** [comment]
haven't changed any settings and updated to the latest nvidia driver today
not all crash out at the start but you play for a few minutes or so and and crashes out with the same error or the error in #6900

**Comment by GPUCode** [comment]
@benderscruffy Can you enable command buffer dumping in the debug menu and send the file after it crashes?

**Comment by benderscruffy** [comment]
i enable command buffer
and it got stuck on the loading screen
![Screenshot 2023-08-24 165133](https://github.com/citra-emu/citra/assets/2696404/d76cbdd3-7efe-4055-aa7c-afeb2f2cc723)

**Comment by benderscruffy** [comment]
works with Canary 2597
