### ISSUE TITLE
[Windows] Updating to 1976 silently moved folder, broke everything

### ISSUE THREAD

**Issue by sanityormadness** [citra-emu/citra#6914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1976

### Description of Issue

When I updated from Nightly 1970 to Nightly 1976, my pinned link disappeared from the Start Menu, and opening Citra presented me with, essentially, a blank installation. It took several minutes for me to realise that it was caused by moving the folder from (folder where I installed it)\nightly-mingw\ to .\nightly\ without any warning or reason. (The blank installation is because I have the data in a .\user\ folder rather than under AppData, because I don't want it on the C: drive for Reasons. And that did NOT get moved as part of the upgrade.)

Honestly, this is much more of a "please never do this again" than anything else - moving it back would just break everything all over again, but you shouldn't do this sort of thing silently and break installs. At least fix it for anyone who hasn't updated recently enough to hit this.

### Expected Behavior

Upgrade should respect existing paths.

### Reproduction Steps

Have Citra Nightly 1970 (or earlier) installed in a ..\nightly-mingw\ folder. Have user data in a user folder under ..\nightly-mingw\ rather than the default (AppData) folder. Also, have a pinned start menu link in Windows 10. Then upgrade to 1976. Pinned Start Menu link will vanish, and opening Citra will appear to be a fresh installation (no games or configuration data) as \user\ folder is no longer in the same folder as executable.

### Log File

N/A

### System Configuration

CPU: Ryzen 7 4800H
GPU/Driver: 3050 RTX (mobile)
RAM: 24GB
OS: Windows 10

**Comment by wheremyfoodat** [comment]
This is annoying, yeah. The reason -mingw was dropped is because the CI no longer uses MinGW and it was a legacy artifact at this point. Something like this will most likely not happen again. You can restore your shortcut by navigating to the new folder and doing right click + create shortcut on the exe.

**Comment by sanityormadness** [comment]
Yeah, I figured out how to fix it all, including the pinned icon, before I posted this. But that was after a couple of minutes of WTF I could have done without. Not moving the /user/ folder was... yeah.

Nice to know it probably won't happen again, but at least dropping a warning in the updater for anyone updating from before the change to after would be nice.

**Comment by Steveice10** [comment]
We generally discourage putting user data inside the install folder when using the Citra Qt-based installer and not a portable build from our GitHub releases. The Qt installer framework can be volatile with the files inside its install directory; for example if you uninstall it will delete everything inside.

That being said, the change to nightly/canary for the folder name unifies it with our other releases and should allow us to avoid needing these kinds of changes in the future. So I wouldn’t expect to see this happening again.
