### ISSUE TITLE
Citra crashes with Vulkan renderer when you load state the second time

### ISSUE THREAD

**Issue by draccfacc** [citra-emu/citra#6918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2596

### Description of Issue

Citra drops out back to windows with Vulkan renderer when you load state the second time.  Happens in Canary build with Vulkan. The first time you load state it works normally, the second time it crashes every time. With any game.

### Expected Behavior

load states work normally as you use Vulkan renderer.

### Reproduction Steps

1.Run Citra
2.Use Vulkan renderer
3.Run any game
4.Save state
5.Load state
6.Load state again

### Log File

[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12428774/citra_log.txt.old.txt)

### System Configuration

CPU: R5 1600 AF
GPU/Driver: HD 7870
RAM: 8 GB
OS: Win 11 64 pro

**Comment by GPUCode** [comment]
Fixed in next canary
