### ISSUE TITLE
Poochy & Yoshi's Woolly World (USA) shadow is wrong in world 4-6 in Vulkan

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2600

### Description of Issue

in world 4-6 your shadow is wrong 
doesnt happen in opengl
![Screenshot 2023-08-27 171532](https://github.com/citra-emu/citra/assets/2696404/768c974b-4a89-43a2-9546-23194d21a379)

### Expected Behavior

shadow is not wrong

### Reproduction Steps

load world 4-6 and play

### Log File

no log

### System Configuration

AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none,
GPU: 'NVIDIA GeForce RTX 3060' running on driver 536.99.0.0

**Comment by GPUCode** [comment]
Post a save file too, thanks

**Comment by benderscruffy** [comment]
ok here it is
[savedata.zip](https://github.com/citra-emu/citra/files/12447700/savedata.zip)

**Comment by benderscruffy** [comment]
@GPUCode 
did you find a solution to this ???

**Comment by Steveice10** [comment]
There was a recent fix related to shadows, have you tried the latest release?

**Comment by benderscruffy** [comment]
yes
still the same problem

**Comment by benderscruffy** [comment]
disable spirv shader generation in vulkan and it works properly
