### ISSUE TITLE
GLFW Libraries for MSVC 2010 problem. 

### ISSUE THREAD

**Issue by djask** [citra-emu/citra#693]
When I try to configure in CMAKE, it tells me to manually input the GLFW libraries for my version. I changed the path to direct to my VC2010 libraries in the CMAKE configuration, but it still keeps giving me this error. How can I solve this?

Sorry, I am not very good at this sort of stuff.

**Comment by purpasmart96** [comment]
Don't use VC2010.

**Comment by neobrain** [comment]
We don't support that version of MSVC.
