### ISSUE TITLE
[Regression] Mario Party Island Tour can no longer connect via Local Wireless

### ISSUE THREAD

**Issue by legend800** [citra-emu/citra#6933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2602

### Description of Issue

An error is now shown on this game when creating a lobby. This used to work fine for me. 

I was able to do local wireless on this same build today on MP Top 100 and Warioware Gold. So my setup is not the issue.

This is shown for a brief sec before the error:
<img width="847" alt="2023-08-28 19_14_47-Citra Canary 2602 _ Mario Party_ Island Tour" src="https://github.com/citra-emu/citra/assets/20983844/f6a3f41f-eb6e-40fa-97f1-f87b763bc093">

<img width="701" alt="2023-08-28 19_14_06-Citra Canary 2602 _ Mario Party_ Island Tour" src="https://github.com/citra-emu/citra/assets/20983844/10a60e3e-7824-4769-9ac3-c883c155aba8">

### Expected Behavior

Connection works like before

### Reproduction Steps

Select Multiplayer from main menu and click through, it'll error out before rendering lobby

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12459591/citra_log.txt)

### System Configuration

CPU: AMD 5900
GPU/Driver: Nvidia 3070
RAM: 32gb
OS: Win11

**Comment by FearlessTobi** [comment]
Can you please try to figure out when this regressed roughly?
There haven't been any changes to our local wireless code in a long time.

**Comment by legend800** [comment]
After doing some more research, I can confirm Island Tour is DLP ONLY. I must have misremembered here. Doesn't help that there's some conflicting stuff out there too like wiki:
"Up to four people can play together either with local multiplayer or Download Play using only one game cartridge"

If you wouldn't mind linking me to the latest Download Play instructions, that would be great! Last time I tried was a few years ago and it was fairly intense. Hopefully it's a little easier now. :)

**Comment by SleepingSnakezzz** [comment]
DLP instructions are at the bottom of this page: https://citra-emu.org/help/feature/multiplayer/
