### ISSUE TITLE
Inazuma Eleven Go! Light crashes when taking a photo

### ISSUE THREAD

**Issue by The-RealBobi** [citra-emu/citra#6941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2606

### Description of Issue

When trying to interact with a photographable object, Citra crashes completely.

### Expected Behavior

It's supposed to make a camera snap animation with a sound, and then return an object.

### Reproduction Steps

(Using the save file provided)

Interact with the piano
[game.zip](https://github.com/citra-emu/citra/files/12495644/game.zip)

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12495670/citra_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
GPU/Driver: Intel (R) UHD Graphics 620 / Vulkan
RAM: 16 GB
OS: Windows 11 Pro 64 Bits Ver. 22H2 (OS Compilation 22621.2215)

**Comment by The-RealBobi** [comment]
It works on SOFTWARE and on OPENGL mode, it's only faulty on VULKAN

**Comment by benderscruffy** [comment]
using canary 2617
this has been fixed
just took a picture of the piano and no crash using vulkan
can be closed
