### ISSUE TITLE
Ultra Moon Menu doesnt work

### ISSUE THREAD

**Issue by ItzzSkye** [citra-emu/citra#6947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1984

### Description of Issue

I cant get into the Pause Menü do i cant heal my Pokemons or anything Like that i can just Play the game
![image](https://github.com/citra-emu/citra/assets/144104785/7e51cfda-2273-4a6f-850e-9d69395076e9)

### Expected Behavior

It should Pop up a Menu where i can do many stuff Like Play with Pokémon Open up my Bag etc.

### Reproduction Steps

Just Open Up Ultra Moon and try Open up the Menu

### Log File

idk sorry:(

### System Configuration

CPU: MD Ryzen 5 5600G Prozessor mit 6 x 3.9 GHz Taktrate (bei Bedarf bis zu
4.4 GHz Turbotakt durch AMD Boost Technik)
GPU/Driver:
RAM:16 GB
OS:22621.2215

**Comment by SachinVin** [comment]
This is an issue tracker for developers, not a place for support. Please join our Discord server or the Citra forum and ask for support there.
