### ISSUE TITLE
Mighty Final Fight (USA) (eShop) keeps on spamming Unimplemented reinterpretation RGBA4 -> RGB5A1 (Vulkan)

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2612

### Description of Issue

keeps on spamming this message in the log
[  31.476235] Render.Vulkan <Warning> video_core/renderer_vulkan/vk_texture_runtime.cpp:Reinterpret:302: Unimplemented reinterpretation RGBA4 -> RGB5A1
doesnt happen with opengl or software

### Expected Behavior

not spamming message

### Reproduction Steps

just run the game and it happens straight away

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12547309/citra_log.txt)

### System Configuration

AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none,
GPU: 'NVIDIA GeForce RTX 3060' running on driver 536.99.0.0

**Comment by GPUCode** [comment]
This log means that vulkan cannot accelerate this operation like opengl, but won't cause any glitches. Closing as it's not an issue
