### ISSUE TITLE
Pokemon super mystery dungeon bug

### ISSUE THREAD

**Issue by Shushkris** [citra-emu/citra#6955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Beta 15

### Description of Issue

I want to play pokemon super mystery dungeon on mobile
But when the game open after a bit it crushes and it says that there is a bug :/

### Expected Behavior

.

### Reproduction Steps

.

### Log File

.

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:
.

**Comment by SachinVin** [comment]
This is an issue tracker for developers, not a place for support. Please join our Discord server or the Citra forum and ask for support there.
