### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by VisionR1** [citra-emu/citra#6957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly Build - 3e254d0

### Description of Issue

I have Xiaomi Poco X3 NFC Android 10, the status bar and button not hide and the touch screen not work properly, and little glitch

### Expected Behavior

Hide, touch screen work normal and not so much glitch

### Reproduction Steps

Open a game

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12561538/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12561540/citra_log.txt.old.txt)

### System Configuration

CPU:Octa-core (2x2.3 GHz Kryo 470 Gold & 6x1.8 GHz Kryo 470 Silver)
GPU/Driver:Adreno 618
RAM:6
OS: Android 10

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum. Please use our Discord for support requests.
