### ISSUE TITLE
[solved] Since nightly 1982, no longer functioning with android 10

### ISSUE THREAD

**Issue by zen253230** [citra-emu/citra#6960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1982

### Description of Issue

No game loads anymore.
No crash but shows the game list after restarting the app

### Expected Behavior

The game should load as it does with the nightly 1981 version 

### Reproduction Steps

After starting the emulator appears correctly the game list. Any game will refuse to launch. 

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12566067/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12566068/citra_log.txt.old.txt)

### System Configuration

CPU: Cortex a73
GPU/Driver: Mali g51
RAM:4gb
OS:Android 10

**Comment by stepsy** [comment]
Can you try this build?
https://github.com/citra-emu/citra-canary/releases/download/canary-2614/citra-android-universal-20230909-e4174a6.apk
This might have a fix for Mali devices.

**Comment by zen253230** [comment]
Thank you for your help, but it doesn't work either!

**Comment by stepsy** [comment]
Ok. Could you try vulkan by going into setting>graphics > graphics API?

**Comment by zen253230** [comment]
OK thanks a lot!
With vulkan and your canary version it works again!
But what about nightly versions. Are they planned to integrate vulkan?

**Comment by stepsy** [comment]
> OK thanks a lot!
> With vulkan and your canary version it works again!
> But what about nightly versions. Are they planned to integrate vulkan? 

No problem. Yes, Nightly will have vulkan soon. Btw could you give a new log file when  you're using OpenGL on the canary build?

**Comment by zen253230** [comment]
[citra_log.txt](https://github.com/citra-emu/citra/files/12566444/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/12566445/citra_log.txt.old.txt)

**Comment by vitor-k** [comment]
Can you retest with the latest nightly (1987)? It has the fix for the mali gpus without a breaking change that was in canary

**Comment by FearlessTobi** [comment]
Closing as user is unresponsive. We can reopen otherwise.

**Comment by zen253230** [comment]
Sorry for delay!
it works as expected with latest nightly
