### ISSUE TITLE
[Feature Request] Add audio output test button

### ISSUE THREAD

**Issue by theKnightsOfRohan** [citra-emu/citra#6961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A simple button in the Citra Configuration settings where you can press a button to test whether you can hear audio well using the given configurations. Maybe one for the microphone as well, but that is probably less important.

### Why would this feature be useful?

It seems pretty simple, and would prevent lots of jumping back and forth to opening games, pausing games, and going back to preferences in order to make sure your audio settings work.

**Comment by FearlessTobi** [comment]
This is a feature already implemented by your operating system.

**Comment by theKnightsOfRohan** [comment]
Yes, but there are occasions were I need to test Citra's audio output, rather than my headphones in general, because some setting may have gotten changed somewhere, or I'm using an incorrect backend. Are you saying there's already a feature in the OS to test audio output from a specific application?
