### ISSUE TITLE
Mario Golf - World Tour (USA) intro runs at 7-8 fps

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest Nightly and Canary

### Description of Issue

during the intro it goes 7-8fps 
keeps on spamming this error
[  39.010428] HW.GPU <Error> video_core/command_processor.cpp:WritePicaReg:123: Commandlist tried to write to invalid register 0xF5B9 (value: 0080519B, mask: 0)
happens in software ,opengl and vulkan

### Expected Behavior

the intro to run at normal speed

### Reproduction Steps

load game and watch intro

### Log File

[citra_log.zip](https://github.com/citra-emu/citra/files/12640391/citra_log.zip)

### System Configuration

AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none,
GPU: 'NVIDIA GeForce RTX 3060' running on driver 536.99.0.0

**Comment by vitor-k** [comment]
Please test all issues with nightly instead of canary.
If it's an issue exclusive to canary, you can reach out to the support team to pinpoint the relevant PR and leave a comment there.
