### ISSUE TITLE
Centipede - Infestation (USA) explosions not rendered properly

### ISSUE THREAD

**Issue by benderscruffy** [citra-emu/citra#6986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2620

### Description of Issue

on the first level the explosions are not rendered properly on the wall (missing parts of the explosion)
happens in opengl and vulkan
![Centipede Infestation_16 09 23_18 32 53 261](https://github.com/citra-emu/citra/assets/2696404/b0951d11-5e0b-402a-8088-4f86a43b0329)
![Centipede Infestation_16 09 23_18 33 42 177](https://github.com/citra-emu/citra/assets/2696404/79e4d593-4f6f-46ab-be57-d47f3df1df78)

### Expected Behavior

get to see the full explosion

### Reproduction Steps

play the tutorial 

### Log File

nothing in log

### System Configuration

AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none,
GPU: 'NVIDIA GeForce RTX 3060' running on driver 536.99.0.0

**Comment by gidoly** [comment]
These kind of issue is better to document with picture of how it renders on console

**Comment by vitor-k** [comment]
Please test all issues with nightly instead of canary.
If it's an issue exclusive to canary, you can reach out to the support team to pinpoint the relevant PR and leave a comment there.

**Comment by benderscruffy** [comment]
closing as i cant test on my 3ds right now
might or might not be a bug
