### ISSUE TITLE
Citra closes instantly on Wayland using Vulkan

### ISSUE THREAD

**Issue by DaniElectra** [citra-emu/citra#6987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1991

### Description of Issue

When opening any application on using Vulkan on Wayland, Citra closes instantly with one the following texts on the terminal:

```
wl_display@1: error 1: invalid method 1, object wl_buffer@49
The Wayland connection experienced a fatal error: Invalid argument
The Wayland connection experienced a fatal error: Invalid argument
```

or

```
wl_display@1: error 0: invalid object 77
The Wayland connection experienced a fatal error: Invalid argument
The Wayland connection experienced a fatal error: Invalid argument
```

The issue does not happen under XWayland or when using OpenGL on Wayland. Tested with the Flatpak version and from the latest source code.

### Expected Behavior

Citra launches the application successfully on Wayland as it does on XWayland using Vulkan.

### Reproduction Steps

1. Launch Citra from a terminal and set the Graphics API to Vulkan
2. Try to open any application or the Home Menu
3. Citra closes instantly and shows one of the texts from above on the terminal

### Log File

Example launching Download Play on XWayland:

[citra_log_xwayland.txt](https://github.com/citra-emu/citra/files/12641342/citra_log_xwayland.txt)

Example launching Download Play on Wayland:

[citra_log_wayland.txt](https://github.com/citra-emu/citra/files/12641343/citra_log_wayland.txt)

### System Configuration

CPU: 16 × AMD Ryzen 7 5700U with Radeon Graphics
GPU/Driver: AMD Radeon Graphics (RADV RENOIR)
RAM: 15,0 GiB of RAM
OS: Arch Linux | Linux 6.5.3-zen1-1-zen | KDE Plasma 5.27.8

**Comment by nz0543** [comment]
I get the same issue on wayland. I've tried on both nobara linux and endeavour os and the emulator crashes when set to vulkan on wayland.

Log Files:

[Wayland Vulkan.txt](https://github.com/citra-emu/citra/files/12782999/Wayland.Vulkan.txt)
[X11 Vulkan.txt](https://github.com/citra-emu/citra/files/12783000/X11.Vulkan.txt)

Specs: 
CPU: 2 x AMD Athlon Silver 3050U with Radeon Graphics
GPU Driver: Mesa 23.2.1-1
RAM: 5802MiB
OS: EndeavourOS
Kernel: 6.5.5-arch1-1
DE: GNOME 44.5

**Comment by DaniElectra** [comment]
The issue has been solved :+1:
