### ISSUE TITLE
All LBX games now crash when using opengl

### ISSUE THREAD

**Issue by LBX1234567** [citra-emu/citra#6994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2623

### Description of Issue

After updating to canary 2623 launching Danball senki/LBX W or Wars citra would just close down. LBX the english release worked but i tried recently and no longer did. The first time i got LBX to work I opened up LBX W Chou Custom and it worked a bit but now none work since this morning. I believe nightly has a similar issue. After switching to vulkan it started working though but this should still be looked at 

### Expected Behavior

Before the game would open and I would play no issues however both chou custom and wars can stop working after sometime Chou custom soft locking the most during battles so that should be addressed to. 

### Reproduction Steps

Update to 2623 on canary install LBX wars or chou custom and it will just not work. 

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12654212/citra_log.txt)
the first one is wars

[citra_log.txt](https://github.com/citra-emu/citra/files/12654214/citra_log.txt)
This second one is chou custom which also suffers from a lot of soft locking

[citra_log.txt](https://github.com/citra-emu/citra/files/12654216/citra_log.txt)
This is LBX the english game

### System Configuration

CPU:Intel Core i7-5500U
GPU/Driver: NVIDIA GeForce GTX 950m 532.03 or Intel HD Graphics 5500 20.19.15.5107
RAM: 8
OS: Windows 10 Home 22h2 19045.3448

**Comment by Steveice10** [comment]
Tested Little Battlers eXperience and could not reproduce with OpenGL or Vulkan, using NVIDIA 537.13 drivers.

Please try deleting the game's shader cache and see if that helps.

**Comment by benderscruffy** [comment]
right click on the game then Disk Shader Cache and open  Shader Cache location and delete the files in open gl or vulkan

**Comment by LBX1234567** [comment]
Fixed!
