### ISSUE TITLE
Vulkan crashes on Radeon GCN1 card (but works fine on canary-2533)

### ISSUE THREAD

**Issue by narutorun-19** [citra-emu/citra#7000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

canary-2533 (Work). From canary-2574 to canary-2625 (Not Work)

### Description of Issue

Vulkan was working properly on and before canary-2533 (30 Jun 2023). 

After this version, Vulkan was temporarily removed for development reasons. When Vulkan was re-added on canary-2574 (02 Aug 2023), the crash issue occurred.

The crash issue remains on the current canary-2625.

### Expected Behavior

Game should start properly.

### Reproduction Steps

1. Select Vulkan
2. Leave anything to default
3. Run any game
4. Citra crashes instantly

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12674010/citra_log.txt)

### System Configuration

CPU: i7 6700K
GPU: Radeon HD 7850 (GCN1)
GPU Driver: Radeon 22.6.1 (Vulkan 1.2.170)
RAM: 16 GB
OS: Windows 10 22H2

**Comment by KrossX** [comment]
I don't know if it's the same problem (R7 260, same legacy driver) but.... I compiled a debug build and it crashed on a bad_alloc after `Instance::CollectToolingInfo` => `vkGetPhysicalDeviceToolProperties`  returned  a rather large `pToolCount`.

Updating the Vulkan runtimes solved it. 
[Vulkan Downloads](https://vulkan.lunarg.com/sdk/home#windows), current [RuntimeInstaller](https://sdk.lunarg.com/sdk/download/1.3.261.1/windows/VulkanRT-1.3.261.1-Installer.exe)

**Comment by Mad-Matty** [comment]
> I don't know if it's the same problem (R7 260, same legacy driver) but.... I compiled a debug build and it crashed on a bad_alloc after `Instance::CollectToolingInfo` => `vkGetPhysicalDeviceToolProperties` returned a rather large `pToolCount`.
> 
> Updating the Vulkan runtimes solved it. [Vulkan Downloads](https://vulkan.lunarg.com/sdk/home#windows), current [RuntimeInstaller](https://sdk.lunarg.com/sdk/download/1.3.261.1/windows/VulkanRT-1.3.261.1-Installer.exe)

I can second this.  I pulled out an old gcn1 r7 250 card and sure enough it failed after initial driver install.  Updating Vulkan runtime fixed it right up.

**Comment by narutorun-19** [comment]
Thanks KrossX and Mad-Matty for the quick response.

As my Radeon GCN1 card only supports up to Vulkan 1.2, I downloaded and installed the latest runtime for Vulkan 1.2.

`VulkanRT-1.2.198.1`

The crash issue has been solved. Thank you for your help! Cheers~
