### ISSUE TITLE
Android version of Rhythm Heaven When will the audio sync issue be resolved? I understand that the PC version can be played

### ISSUE THREAD

**Issue by monggo1404** [citra-emu/citra#7007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Android version of Rhythm Heaven
When will the audio sync issue be resolved?
I understand that the PC version can be played

### Why would this feature be useful?

android

**Comment by SachinVin** [comment]
Dupe #5932
