### ISSUE TITLE
Hide mouse when playing the game

### ISSUE THREAD

**Issue by MrRokiIsBored** [citra-emu/citra#7008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

i want a feature in yuzu where when playing the game it hides the mouse but still can use the mouse in-game

### Why would this feature be useful?

for people who want to play the game with a mouse

**Comment by SleepingSnakezzz** [comment]
> i want a feature in yuzu where when playing the game it hides the mouse but still can use the mouse in-game

Then open up an issue in yuzu for it? This is the Citra repo. If you meant to say Citra, then you'll be happy to learn that we already have this exact feature: 
![image](https://github.com/citra-emu/citra/assets/71992016/15f1e419-c6f7-411d-b91a-2622679cbb82)
