### ISSUE TITLE
Frame skipping

### ISSUE THREAD

**Issue by jm1358343** [citra-emu/citra#7009]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What feature are you suggesting?

Adding frame skipping to citra

### Why would this feature be useful?

Help low end devices

**Comment by tywald** [comment]
There used to be one: #347 

But there were issues so it was removed #2222 

#1960

**Comment by FearlessTobi** [comment]
Frameskip will very likely never be supported in Citra.
You can read the reasons in the posts that were linked above.
