### ISSUE TITLE
Try to make 32bit OS Builds !

### ISSUE THREAD

**Issue by Shinox** [citra-emu/citra#701]
Citra team , don't do what Dolphin team does .. give 32bit builds a chance so you could please everyone with this emulator to be success , don't repeat Dolphin team mistake .

**Comment by purpasmart96** [comment]
Not likely to happen at all.

**Comment by MoochMcGee** [comment]
It wasn't a mistake, you dense fucker. 32-bit builds were just so much
slower than 64-bit builds and for so little benefit. Read their article on
this.

**Comment by Shinox** [comment]
Goosh ! i didn't expect that you guys are so closed minded to the point that make you avoid important requests like this , i was expecting a "change" from Citra developers ( even though i know they already worked on Dolphin before ) but that doesn't mean you have to be strict about that , this is just a reminder no more or less so no need to be lazy to think about it , Citra already has 32bit versions before .. never say never i guess ?

**Comment by MoochMcGee** [comment]
How is this request important? Your CPU should already support 64-bit programs, and if it doesn't, it's too slow for Citra anyway. The same, sound logic was used by the Dolphin team when they got rid of 32-bit builds. If you aren't using a 64-bit OS on your CPU that can clearly handle it, well, that's just your own fault. Not that of the Citra or Dolphin teams.

**Comment by MoochMcGee** [comment]
In other words, no, this is never going to happen.

**Comment by yuriks** [comment]
@Shinox: Currently the 32-bit builds are broken due to a bug. When this bug is fixed, we may or may not provide 32-bit builds, however it's unlikely we will unless we get our own CI infrastructure, as our current build process with AppVeyor is already very slow, and this would double the amount of work it has to do.

32-bit support might be removed entirely when JIT support is implemented, but this is still a ways off, and even then there's a possibility we might keep support.

**Comment by Shinox** [comment]
Thank you @yuriks for your response , that's understandable when it comes to technical issues , i bet 32bit support may become difficult in the near future if you guys want to extend your programing abilities to 64x builds only to avoid limitations . the point is .. it isn't necessary to drop the 32bit support that early in the mean time , even if the emulator originally designed to be running at 64x bit keep in mind that crazy optimization happens in the near future and it may help 32bit users to play the games at full speed ,even if you guys plan to extend your support to people who uses smartphones it may have the ability to run Citra at full speed if their phones designed on 32bit ( which the majority of people use it currently since 64x bit phones seems very expensive and rarely to find ) , anyway .. keep up the good work guys , i'm not here to complain or anything .. i'm just here to encourage you guys to try to bring "possibilities" to those who still uses 32bit OS's in Citra .. hope you guys take this with a grain of salt and take it as a request no more or less .

**Comment by GitHub36** [comment]
@Unlimax Same some people can't afford much... and i want to support them

**Comment by neobrain** [comment]
Citra is open-source and has free software license. All of you are hence welcome to fork the project and maintain 32-bit support by themselves.
