### ISSUE TITLE
HELP, HOW CAN I USE SIXASIS IN RPCS3?

### ISSUE THREAD

**Issue by dias9922** [citra-emu/citra#7021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I know this is not for any problem regarding the topic. I just don't know how to use github at all and I don't know how to create a discussion about rpcs3, that's why I do it this way.
The problem is that I have a PS2 controller. It doesn't have SIXASIS but I would like to use my cell phone as a movement and configure it in rpcs3 and I really have no idea how to do it.
I would like your support in that regard with all due respect to the moderators and to know how to connect my phone as SIXAS in a game that needs it on the RPCS3 platform. Thank you.

### Why would this feature be useful?

Sorry people. i just need help

**Comment by sakuramipha** [comment]
This is the GitHub page for Citra, a Nintendo 3DS emulator. We are not a PlayStation 3 emulator.
The place you're looking for is this: https://github.com/RPCS3/rpcs3

Please make sure to ask for help in their Discord server.
