### ISSUE TITLE
when d3d

### ISSUE THREAD

**Issue by SpareEnderboy** [citra-emu/citra#7038]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What feature are you suggesting?

i would like to have d3d12 in a new update of citra

### Why would this feature be useful?

from my research, 85% of americans use windows and d3d12 gives better performance than vulkan

**Comment by SleepingSnakezzz** [comment]
This would be very low priority, as Citra is a multi-platform program. Vulkan was recently implemented precisely because we can use it on all platforms. DirectX only works with Windows and Xbox.

**Comment by SpareEnderboy** [comment]
k

**Comment by SpareEnderboy** [comment]
ok thanks i guess

**Comment by Inazuka** [comment]
Well at the very least he was polite ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
