### ISSUE TITLE
Loss of audio when loading a save state.

### ISSUE THREAD

**Issue by Mad-Matty** [citra-emu/citra#7047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2638+

### Description of Issue

When loading a savestate the audio is dropped.

I suspect this commit is causing the issue as it is all that was added for build 2638.

https://github.com/citra-emu/citra-canary/commit/376d33cff44e718848dd00157db612bf4c71bec4

Previous build canary 2637 is fine. 

### Expected Behavior

The audio continues playing as normal

### Reproduction Steps

Load Game
Save State
Load state

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/12837818/citra_log.txt)

### System Configuration

CPU: 5950x
GPU/Driver: R290
RAM: 32
OS: Win11

**Comment by Steveice10** [comment]
Commit in question would be this one, which was added to canary merge in the build you mentioned: https://github.com/citra-emu/citra/commit/72ff0c53375b487c5a95ba9702d391a19c629b88
