### ISSUE TITLE
Support for WIA compression format.

### ISSUE THREAD

**Issue by Cristobal15** [citra-emu/citra#7060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Compression formats have been very much requested by people but most of them like CHD, 7zip, Gzip seem to have problems like not allowing byte-level ramdon access on 3DS cartridges. 
Dolphin created 2 new compression formats being the most popular "RVZ" and the most forgotten one called "WIA". This last one apparently does allow ramdon access (although I don't know at what level or if it would work). 
Unfortunately no one talks about the "WIA" format and it is extremely unknown. 

https://github.com/dolphin-emu/dolphin/blob/master/docs/WiaAndRvz.md

### Why would this feature be useful?

It would be of help mainly for Android mobile devices that with each passing year the number of smartphones with MicroSD slot is decreasing. A compressed format would help to optimize space. 

Yes, I am a user and part of the Android community but I am not toxic and I will not insist if the option is not viable. There are really a lot of things I don't know about these compression formats.

**Comment by Cristobal15** [comment]
Oh I understand. Apparently for something like this to happen would require the creation of a total compression format specific to 3ds cartridges which is time consuming and not a priority. 
Thanks for the reply.

**Comment by FearlessTobi** [comment]
I think ZArchive (https://github.com/citra-emu/citra/issues/6013) would be the better option in this case.
