### ISSUE TITLE
Dynamically link HLE AAC Decoder on Linux to avoid patent issues?

### ISSUE THREAD

**Issue by hwittenborn** [citra-emu/citra#7066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Currently Citra [requires compiling on Linux if the HLE AAC Decoder wants to be used](https://citra-emu.org/wiki/hle-aac-decoder/), which isn't ideal for me as I'd like to use the existing prebuilt binaries for Citra.

I'm not sure what the patent issues are for using the HLE AAC Decoder in the official releases, but if it's just a library or something, could it not just be dynamically linked?

I'm not sure on the current state of things, I'm just throwing this out there to get some thoughts.

### Why would this feature be useful?

It would help to avoid needing to compile Citra for the HLE AAC Decoder.

**Comment by Steveice10** [comment]
This isn't the case anymore, we already dynamically link the AAC decoder. I'll look into updating that wiki page.

**Comment by hwittenborn** [comment]
I'm having audio issues on Pokemon X though @Steveice10 (sound effects play, but not any actual game audio), is that related to something else? My current version is `Nightly 2009 | HEAD-40ba522 (2023-10-12)` (from the AppImage in https://github.com/citra-emu/citra-nightly/releases/tag/nightly-2009) if that helps.

**Comment by Steveice10** [comment]
Post a log please, it should say whether it found a suitable version of a supported library to load.

**Comment by hwittenborn** [comment]
Here's the log:

[citra_log.txt](https://github.com/citra-emu/citra/files/12879930/citra_log.txt)

Is it due to these lines?

```
[  44.523301] Common <Warning> common/dynamic_library/fdk-aac.cpp:LoadFdkAac:33: Could not dynamically load libfdk-aac: libfdk-aac.so.2: cannot open shared object file: No such file or directory
[  44.523438] Common <Warning> common/dynamic_library/ffmpeg.cpp:LoadAVUtil:132: Could not dynamically load libavutil: libavutil.so.56: cannot open shared object file: No such file or directory
```

**Comment by Steveice10** [comment]
Yes, I would recommend installing libfdk-aac as it is usually the easiest to get the right version of from distribution repos.

Ubuntu: `sudo apt install libfdk-aac2`
Arch: `sudo pacman -S libfdk-aac`
Fedora: `sudo dnf install fdk-aac` (or `fdk-aac-free`? not sure)

etc.

**Comment by hwittenborn** [comment]
I was in the middle of typing that :sweat_smile: that did the trick great. Do you think it'd be good for the Wiki page to mention those packages need installed?

**Comment by Steveice10** [comment]
I've updated the wiki on the GitHub side: https://github.com/citra-emu/citra/wiki/HLE-AAC-Decoder

It should propagate to the Citra site eventually.

**Comment by hwittenborn** [comment]
That looks good, thanks for the help @Steveice10!
