### ISSUE TITLE
SMT 4 transparency error

### ISSUE THREAD

**Issue by Lplumb** [citra-emu/citra#7074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2009

### Description of Issue

This is an issue that has occurred and has been "fixed" before in #5775.

### Expected Behavior

The previous listed error ticket will show the correct behavior 

### Reproduction Steps

When playing the game in battles any attack that causes an enemy to die with an effect will reproduce the error, any skill in the game with the ability to kill will cause the error to occur.

### Log File

Won't let me upload log, doing this from my phone will see if I can upload at my pc if needed 

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

Running on the steam deck

**Comment by GPUCode** [comment]
You haven't uploaded a log so can't be sure, but the issue has only been fixed in opengl not vulkan

**Comment by Lplumb** [comment]
I was playing the game in openGL, I'll try vulkan and see if that changes anything but I'll upload a log file here soon

**Comment by Lplumb** [comment]
> You haven't uploaded a log so can't be sure, but the issue has only been fixed in opengl not vulkan

I was playing the game in openGL, I'll try vulkan and see if that changes anything but I'll upload a log file here soon

**Comment by Lplumb** [comment]
[citra_log_opengl.txt](https://github.com/citra-emu/citra/files/12922614/citra_log_opengl.txt)

[citra_log_vulkan.txt](https://github.com/citra-emu/citra/files/12922615/citra_log_vulkan.txt)

**Comment by Lplumb** [comment]
> You haven't uploaded a log so can't be sure, but the issue has only been fixed in opengl not vulkan

@GPUCode got those logs uploaded, the issue was happening with both openGL and Vulkan on the steam deck. If there's anything else I can help provided let me know.

**Comment by GPUCode** [comment]
Appologies for the delay, this has been fixed
