### ISSUE TITLE
Warn the user their ROM is probably encrypted

### ISSUE THREAD

**Issue by linkmauve** [citra-emu/citra#708]
Encrypted ROMs are the number one cause of issues people have with Citra, and it doesn’t display any meaningful error.

The best way to handle that would be to error when the encrypted bit is set, but many decrypters apparently don’t clear that bit, which means a ROM can be both decrypted and have the encrypted bit set.

Thus, a warning that would tell the user their ROM is probably encrypted, while allowing them to still run it if they are sure it isn’t would be the best compromise we can do.

To prevent the user from seeing that warning again and again we could also have some way to unset the bit on successful run.

**Comment by i30817** [comment]
Why should you care about buggy decrypters - why not let the users dump the games again with something better?

**Comment by yuriks** [comment]
As far as I know, the usual heuristic used for this is to verify fields that are present in both the main NCCH header (which is always plain text) with the one in the inner exheader (which can be encrypted). If both match, then the NCCH is not encrypted.
