### ISSUE TITLE
Request the ability to connect via hostname as well as ip address.

### ISSUE THREAD

**Issue by slentara1** [citra-emu/citra#7088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I'm requesting the ability to connect to direct connect to an unlisted room with a domain instead of only an ip address.

### Why would this feature be useful?

It would make it safer for people who stream Citra games to allow users to join without giving out their ip address and without hosting a public room and have to deal with having to kick out unwanted randoms.

**Comment by FearlessTobi** [comment]
https://github.com/citra-emu/citra/blob/master/src/citra_qt/multiplayer/validation.h#L62C1.

This is already possible.

**Comment by slentara1** [comment]
On what build is this possible? Every attempt to type anything other than numbers and dots into the address does nothing

**Comment by slentara1** [comment]
@FearlessTobi there may be code to allow but you can't actually input a domain in the field unless you know something I don't.

**Comment by FearlessTobi** [comment]
This has been possible on all builds released in the last 7 months.

**Comment by slentara1** [comment]
I'll check them out. Thank you
