### ISSUE TITLE
Thousands of Junk Textures Being Dumped Per Minute

### ISSUE THREAD

**Issue by BayoNX19** [citra-emu/citra#7095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2665

### Description of Issue

This issue is exclusive to Kid Icarus: Uprising. All other games that I’ve tested seem to dump textures normally. Whenever I get into a level (actual gameplay, not menus), Citra starts dumping a ridiculous number of junk textures, see screenshot. Citra is dumping the normal game textures, but in addition to that, it’s dumping tons of other images.

**From only 60 seconds of gameplay, Citra has dumped over 16,000 images.**
![aksljdf](https://github.com/citra-emu/citra/assets/32692398/84c52a75-82ae-43f4-b294-e51f18348c43)

This bug has made it nearly impossible to pull the actual textures from the game because of the thousands upon thousands of junk textures that appear in the folder as well.
![asjkodfjko](https://github.com/citra-emu/citra/assets/32692398/7867ccd0-a1ce-4d56-beb4-fe38e49da0ac)

### Expected Behavior

See attached image of junk textures; expected behavior is Citra only dumping actual game textures.

### Reproduction Steps

This bug occurs with Vulkan and OpenGL, and I’ve played around with most of the graphics settings in Citra, yet nothing has solved this.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13181626/citra_log.txt)

### System Configuration

CPU: 13600k
GPU/Driver: RTX 3070  537.58
RAM: 32GB DDR5
OS: Windows 11

_This bug has also been posted on the citra official forums by me, see this link: https://community.citra-emu.org/t/thousands-of-junk-textures-dumped-per-minute/926350/5. Also SleepingSnake says that this issue actually applies to one of the inazuma games as well._

**Comment by GPUCode** [comment]
Should be fixed by linked PR, please confirm

**Comment by BayoNX19** [comment]
fixed!
