### ISSUE TITLE
RK3588s Armbian Compilation Issue (Nightly 1918)

### ISSUE THREAD

**Issue by StonedEdge** [citra-emu/citra#7104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1918

### Description of Issue

Hi there, 

I am trying to compile Citra from source using clang 14 as the compiler. The reason for doing the 1918 build is that the RK3588s SoC doesn't support Vulkan SDK or Vulkan drivers (not sure if I am able to compile the latest nightly build without it as per the Wiki - it does say it is a dependency for building correctly here: https://citra-emu.org/wiki/building-for-linux/) 

I am setting up my cmake files as per the below:
cmake .. -DCMAKE_CXX_COMPILER=clang++-14  -DCMAKE_C_COMPILER=clang-14     -DCMAKE_CXX_FLAGS="-O2 -g -stdlib=libc++" -DCMAKE_BUILD_TYPE=Release -DENABLE_FFMPEG_AUDIO_DECODER=ON

I then try to compile the build by running cmake --build . -- -j"$(nproc)"

I am compiling up until around 74%, and then I am coming across this error log. 
[message (2).txt](https://github.com/citra-emu/citra/files/13223872/message.2.txt)

### Expected Behavior

Expected to be able to compile Citra for ARM Linux x64 on the RK3588s. Running on Armbian (kernel version 5.10.160) 

### Reproduction Steps

git clone --recursive https://github.com/citra-emu/citra
cd citra
git reset --hard 52f88f8fb49154cf6389981c8d208de6019702ae
git submodule update --init --recursive
cmake .. -DCMAKE_CXX_COMPILER=clang++-14  -DCMAKE_C_COMPILER=clang-14     -DCMAKE_CXX_FLAGS="-O2 -g -stdlib=libc++" -DCMAKE_BUILD_TYPE=Release -DENABLE_FFMPEG_AUDIO_DECODER=ON

cmake --build . -- -j"$(nproc)"

### Log File

[ 74%] Building CXX object src/video_core/CMakeFiles/video_core.dir/debug_utils/debug_utils.cpp.o
[ 74%] Building CXX object src/video_core/CMakeFiles/video_core.dir/geometry_pipeline.cpp.o
[ 74%] Building CXX object src/video_core/CMakeFiles/video_core.dir/primitive_assembly.cpp.o
[ 74%] Building CXX object src/video_core/CMakeFiles/video_core.dir/rasterizer_accelerated.cpp.o
/home/stonededge/citra/src/video_core/custom_textures/material.cpp:71:17: error: no viable conversion from 'std::vector<u8>' (aka 'vector<unsigned char>') to 'std::span<const u8>' (aka 'span<const unsigned char>')
        LoadPNG(input, flip_png);
                ^~~~~
/usr/lib/llvm-14/bin/../include/c++/v1/span:401:15: note: candidate constructor not viable: no known conversion from 'std::vector<u8>' (aka 'vector<unsigned char>') to 'const std::span<const unsigned char, 18446744073709551615> &' for 1st argument
    constexpr span           (const span&) noexcept = default;
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:425:15: note: candidate template ignored: could not match 'unsigned char[_Sz]' against 'std::vector<u8>' (aka 'vector<unsigned char>')
    constexpr span(type_identity_t<element_type> (&__arr)[_Sz]) noexcept : __data{__arr}, __size{_Sz} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:430:15: note: candidate template ignored: could not match 'array' against 'vector'
    constexpr span(array<_OtherElementType, _Sz>& __arr) noexcept : __data{__arr.data()}, __size{_Sz} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:435:15: note: candidate template ignored: could not match 'array' against 'vector'
    constexpr span(const array<_OtherElementType, _Sz>& __arr) noexcept : __data{__arr.data()}, __size{_Sz} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:445:19: note: candidate template ignored: could not match 'span' against 'vector'
        constexpr span(const span<_OtherElementType, _OtherExtent>& __other,
                  ^
/home/stonededge/citra/src/./video_core/custom_textures/material.h:51:38: note: passing argument to parameter 'input' here
    void LoadPNG(std::span<const u8> input, bool flip_png);
                                     ^
/home/stonededge/citra/src/video_core/custom_textures/material.cpp:75:17: error: no viable conversion from 'std::vector<u8>' (aka 'vector<unsigned char>') to 'std::span<const u8>' (aka 'span<const unsigned char>')
        LoadDDS(input);
                ^~~~~
/usr/lib/llvm-14/bin/../include/c++/v1/span:401:15: note: candidate constructor not viable: no known conversion from 'std::vector<u8>' (aka 'vector<unsigned char>') to 'const std::span<const unsigned char, 18446744073709551615> &' for 1st argument
    constexpr span           (const span&) noexcept = default;
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:425:15: note: candidate template ignored: could not match 'unsigned char[_Sz]' against 'std::vector<u8>' (aka 'vector<unsigned char>')
    constexpr span(type_identity_t<element_type> (&__arr)[_Sz]) noexcept : __data{__arr}, __size{_Sz} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:430:15: note: candidate template ignored: could not match 'array' against 'vector'
    constexpr span(array<_OtherElementType, _Sz>& __arr) noexcept : __data{__arr.data()}, __size{_Sz} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:435:15: note: candidate template ignored: could not match 'array' against 'vector'
    constexpr span(const array<_OtherElementType, _Sz>& __arr) noexcept : __data{__arr.data()}, __size{_Sz} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:445:19: note: candidate template ignored: could not match 'span' against 'vector'
        constexpr span(const span<_OtherElementType, _OtherExtent>& __other,
                  ^
/home/stonededge/citra/src/./video_core/custom_textures/material.h:53:38: note: passing argument to parameter 'input' here
    void LoadDDS(std::span<const u8> input);
                                     ^
/home/stonededge/citra/src/video_core/custom_textures/material.cpp:88:34: error: no viable conversion from 'std::vector<u8>' (aka 'vector<unsigned char>') to 'std::span<u8>' (aka 'span<unsigned char>')
        Common::FlipRGBA8Texture(data, width, height);
                                 ^~~~
/usr/lib/llvm-14/bin/../include/c++/v1/span:401:15: note: candidate constructor not viable: no known conversion from 'std::vector<u8>' (aka 'vector<unsigned char>') to 'const std::span<unsigned char, 18446744073709551615> &' for 1st argument
    constexpr span           (const span&) noexcept = default;
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:425:15: note: candidate template ignored: could not match 'type_identity_t<std::span<unsigned char, 18446744073709551615>::element_type>[_Sz]' (aka 'unsigned char[_Sz]') against 'std::vector<u8>' (aka 'vector<unsigned char>')
    constexpr span(type_identity_t<element_type> (&__arr)[_Sz]) noexcept : __data{__arr}, __size{_Sz} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:430:15: note: candidate template ignored: could not match 'array' against 'vector'
    constexpr span(array<_OtherElementType, _Sz>& __arr) noexcept : __data{__arr.data()}, __size{_Sz} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:435:15: note: candidate template ignored: could not match 'array' against 'vector'
    constexpr span(const array<_OtherElementType, _Sz>& __arr) noexcept : __data{__arr.data()}, __size{_Sz} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:445:19: note: candidate template ignored: could not match 'span' against 'vector'
        constexpr span(const span<_OtherElementType, _OtherExtent>& __other,
                  ^
/home/stonededge/citra/src/./common/texture.h:12:37: note: passing argument to parameter 'tex' here
void FlipRGBA8Texture(std::span<u8> tex, u32 width, u32 height);
                                    ^
3 errors generated.
gmake[2]: *** [src/video_core/CMakeFiles/video_core.dir/build.make:141: src/video_core/CMakeFiles/video_core.dir/custom_textures/material.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from /home/stonededge/citra/src/video_core/primitive_assembly.cpp:8:
In file included from /home/stonededge/citra/src/./video_core/shader/shader.h:15:
/home/stonededge/citra/externals/./nihstro/include/nihstro/shader_bytecode.h:89:5: warning: non-void function does not return a value in all control paths [-Wreturn-type]
    }
    ^
In file included from /home/stonededge/citra/src/video_core/geometry_pipeline.cpp:9:
In file included from /home/stonededge/citra/src/./video_core/geometry_pipeline.h:9:
In file included from /home/stonededge/citra/src/./video_core/shader/shader.h:15:
/home/stonededge/citra/externals/./nihstro/include/nihstro/shader_bytecode.h:89:5: warning: non-void function does not return a value in all control paths [-Wreturn-type]
    }
    ^
1 warning generated.
In file included from /home/stonededge/citra/src/video_core/rasterizer_accelerated.cpp:8:
In file included from /home/stonededge/citra/src/./video_core/pica_state.h:14:
In file included from /home/stonededge/citra/src/./video_core/geometry_pipeline.h:9:
In file included from /home/stonededge/citra/src/./video_core/shader/shader.h:15:
/home/stonededge/citra/externals/./nihstro/include/nihstro/shader_bytecode.h:89:5: warning: non-void function does not return a value in all control paths [-Wreturn-type]
    }
    ^
In file included from /home/stonededge/citra/src/video_core/debug_utils/debug_utils.cpp:17:
In file included from /home/stonededge/citra/externals/./nihstro/include/nihstro/shader_binary.h:32:
/home/stonededge/citra/externals/./nihstro/include/nihstro/shader_bytecode.h:89:5: warning: non-void function does not return a value in all control paths [-Wreturn-type]
    }
    ^
In file included from /home/stonededge/citra/src/video_core/pica.cpp:8:
In file included from /home/stonededge/citra/src/./video_core/geometry_pipeline.h:9:
In file included from /home/stonededge/citra/src/./video_core/shader/shader.h:15:
/home/stonededge/citra/externals/./nihstro/include/nihstro/shader_bytecode.h:89:5: warning: non-void function does not return a value in all control paths [-Wreturn-type]
    }
    ^
In file included from /home/stonededge/citra/src/video_core/command_processor.cpp:20:
In file included from /home/stonededge/citra/src/./video_core/pica_state.h:14:
In file included from /home/stonededge/citra/src/./video_core/geometry_pipeline.h:9:
In file included from /home/stonededge/citra/src/./video_core/shader/shader.h:15:
/home/stonededge/citra/externals/./nihstro/include/nihstro/shader_bytecode.h:89:5: warning: non-void function does not return a value in all control paths [-Wreturn-type]
    }
    ^
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
/home/stonededge/citra/src/video_core/custom_textures/custom_tex_manager.cpp:269:35: error: no viable constructor or deduction guide for deduction of template arguments of 'span'
        const std::span encoded = std::span{pixels}.first(data_size);
                                  ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:186:28: note: candidate template ignored: could not match 'span' against 'vector'
class _LIBCPP_TEMPLATE_VIS span {
                           ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:210:15: note: candidate template ignored: could not match 'span' against 'vector'
    constexpr span           (const span&) noexcept = default;
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:239:41: note: candidate template ignored: could not match 'type_identity_t<element_type>[_Extent]' (aka 'typename type_identity<type-parameter-0-0>::type[_Extent]') against 'typename remove_reference<vector<unsigned char> &>::type' (aka 'std::vector<unsigned char>')
    _LIBCPP_INLINE_VISIBILITY constexpr span(type_identity_t<element_type> (&__arr)[_Extent]) noexcept : __data{__arr} {}
                                        ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:244:15: note: candidate template ignored: could not match 'array' against 'vector'
    constexpr span(array<_OtherElementType, _Extent>& __arr) noexcept : __data{__arr.data()} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:249:15: note: candidate template ignored: could not match 'array' against 'vector'
    constexpr span(const array<_OtherElementType, _Extent>& __arr) noexcept : __data{__arr.data()} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:261:19: note: candidate template ignored: could not match 'span' against 'vector'
        constexpr span(const span<_OtherElementType, _Extent>& __other,
                  ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:269:28: note: candidate template ignored: could not match 'span' against 'vector'
        constexpr explicit span(const span<_OtherElementType, dynamic_extent>& __other,
                           ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:573:5: note: candidate template ignored: could not match '_Tp[_Sz]' against 'typename remove_reference<vector<unsigned char> &>::type' (aka 'std::vector<unsigned char>')
    span(_Tp (&)[_Sz]) -> span<_Tp, _Sz>;
    ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:576:5: note: candidate template ignored: could not match 'array' against 'vector'
    span(array<_Tp, _Sz>&) -> span<_Tp, _Sz>;
    ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:579:5: note: candidate template ignored: could not match 'array' against 'vector'
    span(const array<_Tp, _Sz>&) -> span<const _Tp, _Sz>;
    ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:208:41: note: candidate function template not viable: requires 0 arguments, but 1 was provided
    _LIBCPP_INLINE_VISIBILITY constexpr span() noexcept : __data{nullptr} {}
                                        ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:219:24: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    constexpr explicit span(_It __first, size_type __count)
                       ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:231:24: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    constexpr explicit span(_It __first, _End __last) : __data{_VSTD::to_address(__first)} {
                       ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:569:5: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    span(_It, _EndOrSize) -> span<remove_reference_t<iter_reference_t<_It>>>;
    ^
/home/stonededge/citra/src/video_core/custom_textures/custom_tex_manager.cpp:270:35: error: no viable constructor or deduction guide for deduction of template arguments of 'span'
        const std::span decoded = std::span{pixels}.last(decoded_size);
                                  ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:186:28: note: candidate template ignored: could not match 'span' against 'vector'
class _LIBCPP_TEMPLATE_VIS span {
                           ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:210:15: note: candidate template ignored: could not match 'span' against 'vector'
    constexpr span           (const span&) noexcept = default;
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:239:41: note: candidate template ignored: could not match 'type_identity_t<element_type>[_Extent]' (aka 'typename type_identity<type-parameter-0-0>::type[_Extent]') against 'typename remove_reference<vector<unsigned char> &>::type' (aka 'std::vector<unsigned char>')
    _LIBCPP_INLINE_VISIBILITY constexpr span(type_identity_t<element_type> (&__arr)[_Extent]) noexcept : __data{__arr} {}
                                        ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:244:15: note: candidate template ignored: could not match 'array' against 'vector'
    constexpr span(array<_OtherElementType, _Extent>& __arr) noexcept : __data{__arr.data()} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:249:15: note: candidate template ignored: could not match 'array' against 'vector'
    constexpr span(const array<_OtherElementType, _Extent>& __arr) noexcept : __data{__arr.data()} {}
              ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:261:19: note: candidate template ignored: could not match 'span' against 'vector'
        constexpr span(const span<_OtherElementType, _Extent>& __other,
                  ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:269:28: note: candidate template ignored: could not match 'span' against 'vector'
        constexpr explicit span(const span<_OtherElementType, dynamic_extent>& __other,
                           ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:573:5: note: candidate template ignored: could not match '_Tp[_Sz]' against 'typename remove_reference<vector<unsigned char> &>::type' (aka 'std::vector<unsigned char>')
    span(_Tp (&)[_Sz]) -> span<_Tp, _Sz>;
    ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:576:5: note: candidate template ignored: could not match 'array' against 'vector'
    span(array<_Tp, _Sz>&) -> span<_Tp, _Sz>;
    ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:579:5: note: candidate template ignored: could not match 'array' against 'vector'
    span(const array<_Tp, _Sz>&) -> span<const _Tp, _Sz>;
    ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:208:41: note: candidate function template not viable: requires 0 arguments, but 1 was provided
    _LIBCPP_INLINE_VISIBILITY constexpr span() noexcept : __data{nullptr} {}
                                        ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:219:24: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    constexpr explicit span(_It __first, size_type __count)
                       ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:231:24: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    constexpr explicit span(_It __first, _End __last) : __data{_VSTD::to_address(__first)} {
                       ^
/usr/lib/llvm-14/bin/../include/c++/v1/span:569:5: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    span(_It, _EndOrSize) -> span<remove_reference_t<iter_reference_t<_It>>>;
    ^
2 errors generated.
gmake[2]: *** [src/video_core/CMakeFiles/video_core.dir/build.make:125: src/video_core/CMakeFiles/video_core.dir/custom_textures/custom_tex_manager.cpp.o] Error 1
1 warning generated.
gmake[1]: *** [CMakeFiles/Makefile2:1668: src/video_core/CMakeFiles/video_core.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

### System Configuration

CPU: RK3588s
GPU/Driver: Panfrost (Mali-G610)
RAM: 16GB
OS: Armbian Linux (5.10.160 Kernel)

**Comment by Steveice10** [comment]
Your clang has a broken libc++ and isn't supported, see: https://github.com/rui314/mold/issues/407#issuecomment-1085532789

Use a newer version of clang.
