### ISSUE TITLE
emulated time twice slower as it should ? FPS capped at 30

### ISSUE THREAD

**Issue by Lectem** [citra-emu/citra#711]
There seems to be some problems with the emulated time, every homebrew I give to Citra *thinks* it's running at 30fps. On hardware it does work at 60fps.

I'm using this function : https://github.com/xerpi/sf2dlib/blob/master/libsf2d/source/sf2d.c#L200
It's based on ctrulib osGetTime

**Comment by Subv** [comment]
Citra doesn't currently emulate the time registers

**Comment by Subv** [comment]
1210
