### ISSUE TITLE
"Invalid vertex shader float uniform index: 127" spam in Pokemon ORAS when certain Pokemon are sent out

### ISSUE THREAD

**Issue by Steveice10** [citra-emu/citra#7112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2022 / Canary 2673

### Description of Issue

See https://github.com/citra-emu/citra/issues/6696#issuecomment-1791741940

When certain Pokemon are sent out, we get "Invalid vertex shader float uniform index: 127" spam in the log, indicating something is likely wrong, or we need to HW test the behavior if the game is supposed to do this.

### Expected Behavior

We should either handle this case properly and reduce the log message to DEBUG, or diagnose why it is happening if it shouldn't be.

### Reproduction Steps

See the original linked issue.

### Log File

See the original linked issue.

### System Configuration

See the original linked issue.

**Comment by Dragios** [comment]
This error log spam also consistently appears intermittently during screen transitions to "Preparing Save Data..." and the main menu, as well as after selecting "Start" from Nightly-1997 onwards in Mini Mario & Friends.
