### ISSUE TITLE
citra-qt should only use one configuration file

### ISSUE THREAD

**Issue by linkmauve** [citra-emu/citra#712]
Currently it will create a `$XDG_CONFIG_HOME/Citra team/Citra.ini` file in which it puts the last state of its windows, as well as configured shortcuts.

This file should be merged into `$XDG_CONFIG_HOME/citra-emu/qt-config.ini` so that there is only one file to manage.

**Comment by LittleWhite-tb** [comment]
I totally agree with this, since I notice lot of "configuration files" for citra.

Although, the ini file from Qt code is determined by these two lines :
```
QCoreApplication::setOrganizationName("Citra team");
QCoreApplication::setApplicationName("Citra");
```
and does not seem incorrect (semantically). So, how do you suggest to fix this properly ?

**Comment by yuriks** [comment]
I dunno, I kinda like keeping the UI and emulator configurations separate. It means you can easily delete the emulator config to make sure you're using the defaults, without messing up your window layout. We should unify the Qt and GLFW settings files though. (As well as Debug/Release ones in Windows.)

**Comment by neobrain** [comment]
A lot of valuable discussion on this topic happened in #108. (tl;dr: I don't think it's sensible nor desirable to unify configuration handling across different frontends.)

**Comment by archshift** [comment]
As well as #387.

**Comment by poutros** [comment]
Doesn't citra create only one config now?
`Citra\user\config`

**Comment by wwylele** [comment]
We have been using unified config file for a while. I couldn't find which commit fixed it though.
