### ISSUE TITLE
CITRA ANDROID CRASH WITH VULKAN(POKEMON GAMES) PLEASE HELP ME!

### ISSUE THREAD

**Issue by daeklo4** [citra-emu/citra#7124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2026/Canary 2676

### Description of Issue

When entering with vulkan in the pokemon games (omega ruby, ultra moon, etc and new super mario bros 2) the emulator closes, it does not happen with other games, only the ones I mentioned, please I need help with this since Thanks to Vulkan I will be able to run Pokémon games faster than with OpenGL, please help, thank you very much for all your efforts and for this great emulator, many blessings to the entire Citra Emulator team

### Expected Behavior

When starting (with vulkan only, not with opengl) the Pokémon games close in previous versions of citra with vulkan all the games closed but in the current ones only the Pokémon games and New super mario bros 2.

### Reproduction Steps

When starting (with vulkan only, not with opengl) the Pokémon games close in previous versions of citra with vulkan all the games closed but in the current ones only the Pokémon games and New super mario bros 2.

### Log File

Log files here:
[citra_log.txt](https://github.com/citra-emu/citra/files/13262129/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/13262130/citra_log.txt.old.txt)

### System Configuration

CPU:MediaTek6762(HelioP22)
GPU/Driver:
RAM:3GB
OS:Android 10
![Screenshot_2023-11-05-22-21-51-951](https://github.com/citra-emu/citra/assets/109567065/5e22f491-b8e0-4bc3-a691-ce239c8444cd)

**Comment by daeklo4** [comment]
Help me please!

**Comment by SleepingSnakezzz** [comment]
```
[   9.701151] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:CollectTelemetryParameters:647: VK_DRIVER: PowerVR Rogue Vulkan Driver 1.300.2589
[   9.701185] Render.Vulkan <Info> video_core/renderer_vulkan/vk_instance.cpp:CollectTelemetryParameters:648: VK_DEVICE: PowerVR Rogue GE8320
```
PowerVR... Yea, don't bother. PowerVR have the most horrible hardware *and* drivers in the industry. To the point that they're only included in budget devices, or in products where the company is trying to cut corners. Buy a device with a Mali or an Adreno GPU instead.

**Comment by daeklo4** [comment]
Thanks for the tip!
