### ISSUE TITLE
Fails to render player's portrait in Ultra Moon's title screen

### ISSUE THREAD

**Issue by Skorlupka** [citra-emu/citra#7131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

nightly-2027 / canary-2677

### Description of Issue

When opening Ultra Moon while loading the player's portrait, the main menu interface disappears for one frame, after which it is displayed again, but instead of the portrait it just shows a blue square
![Screenshot_2023-11-07-08-45-49-789_org citra citra_emu canary](https://github.com/citra-emu/citra/assets/46283144/c10f37df-d275-48dc-bc2c-055cb11581fd)
. 

### Expected Behavior

Must render player`s portrait

### Reproduction Steps

Just open the game and get to the player selection screen

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13275938/citra_log.txt)

### System Configuration

CPU: Helio G95
RAM: 8 Gb
OS: MIUI Global, Android 13

**Comment by SleepingSnakezzz** [comment]
This is because you're using Async Shader Compilation. It causes these graphical issues. Please disable it to confirm.

**Comment by Skorlupka** [comment]
Well it does work without async sure
