### ISSUE TITLE
Vulkan backend creates water graphical errors/seamlines in Animal Crossing New Leaf - Welcome Amiibo

### ISSUE THREAD

**Issue by Abbanon** [citra-emu/citra#7150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2030 (introduced), Nightly 2031

### Description of Issue

When using the Vulkan API graphics backend, strange seamlines can be seen in the rivers in New Leaf - Welcome Amiibo.
OpenGL does not have this issue.
This issue was introduced with [Nightly 2030](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-2030).

## What it should be doing:
![Screenshot_2](https://github.com/citra-emu/citra/assets/37251822/25f0d123-a53b-4b72-b1bb-3124489eb6b0)

## What it's currently doing:
![Screenshot_1](https://github.com/citra-emu/citra/assets/37251822/34d3e7bf-dad2-43c6-987b-2a301713da97)

### Reproduction Steps

Have graphics backend set to Vulkan. Launch the game, and walk along the rivers in your town. You will see these seamlines appear in several places.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13325535/citra_log.txt)

### System Configuration

CPU: Intel i7-4790K
GPU/Driver: NVIDIA GeForce GTX 1660 SUPER 6GB // Driver version 546.01
RAM: 32GB DDR3
OS: Windows 10 Pro x64 // Version 22H2

**Comment by GPUCode** [comment]
Should be fixed by above PR, please test
