### ISSUE TITLE
Hanging when on-screen keyboard should appear 

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#718]
Any ideas how to fix?
Games that it probably also needs on-screen keyboard support:
- Acrylic Palette: Irodori Cafe - Cheers
- Animal Hospital
- A-Train 3D
- Beyblade Evolution (log - http://pastie.org/10100354)
- Dead or Alive: Dimensions (log - http://pastie.org/10100510)
- ESSE Rakuraku Kakeibo
- Gundam Try Age SP
- My Pet Puppy 3D
- Paws & Claws: Pampered Pets Resort 3D
- Pokémon Art Academy
- Theatrhythm Final Fantasy  (log - http://pastie.org/10126152)
- Zoo Resort 3D
- Yumi's Odd Odyssey (Sayonara Umihara Kawase)

and propably more

CITRA HANGS HERE (Theatrhythm Final Fantasy):
![citra keyboard 1](https://cloud.githubusercontent.com/assets/11453507/7441925/a3692616-f0fd-11e4-980b-76fe1b77a159.JPG)

Function on-screen keyboard:
![citra keyboard 2](https://cloud.githubusercontent.com/assets/11453507/7441928/d69139de-f0fd-11e4-8e71-6c9e726018ee.JPG)

**Comment by bunnei** [comment]
This is probably the OS's built in "software keyboard". I've been meaning to implement this for a while, but didn't know of any games that were using it. Thanks for the list - I'll look into it now!

**Comment by purpasmart96** [comment]
@JohnGodgames Do you have a log?

**Comment by JohnGodgames** [comment]
Some of logs added.Search for "core\hle\service\apt\apt.cpp:Service::APT::AppletUtility"

**Comment by purpasmart96** [comment]
APT::ReplySleepQuery
APT::PrepareToStartLibraryApplet
APT::IsRegistered
APT::SendParameter
It appears these service cmd's are the bulk of the problem
@bunnei Another game that uses SVC::CreateMemoryBlock :(

**Comment by Subv** [comment]
#821 + https://github.com/Subv/citra/tree/applets should fix it.
There's currently no input handling though. As of now these patches will make the game believe that the user input "Subv" in the swkbd.
I need people to test all these games using these patches and report if the work / don't work, thanks!

**Comment by chassm** [comment]
Tomodachi Life needs an on-screen keyboard too
