### ISSUE TITLE
[Android] [Premium] light/dark mode should not be a premium feature

### ISSUE THREAD

**Issue by glitch128** [citra-emu/citra#7187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

make light/dark mode a non-premium feature

### Why would this feature be useful?

This should be a given, but dark mode should not be a premium feature. Providing a dark mode, if programmed, should be free. Now, the shaders, I understand, I'd imagine that would be difficult to implement, but a light/ dark mode toggle is easy to implement. Give me one (1) valid reason that a light/dark mode toggle should be a paid feature.

**Comment by FearlessTobi** [comment]
Dark mode is free on latest nightly builds.
