### ISSUE TITLE
Glitched Pokemon X/Y/Sun/Moon textures when playing on Vulkan on Linux + Bad performance

### ISSUE THREAD

**Issue by Readek** [citra-emu/citra#7197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2039

### Description of Issue

When playing the game on the Vulkan renderer, textures for non-chibi characters and all Pokemon will look glitched like so:

https://github.com/citra-emu/citra/assets/35299560/d073762f-5afd-4670-8224-19fd953f8888

This is not happening when dualbooting to Windows, and its also not happening on my Steam Deck. Additionally, game performance, while reaching fulltime, is barely reaching 40fps when uncapped. When using OpenGL, it easily surpasses 200fps, and on Windows Vulkan, it goes beyond 300fps.

Textures look fine when using OpenGL, but that introduces [other issues](https://github.com/citra-emu/citra/issues/7183).

### Expected Behavior

Non-glitched out textures.

### Reproduction Steps

You can see this on the first model the game throws at you, a pokeball, as well as on the professor.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13419001/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
GPU/Driver: AMD ATI Radeon RX 5700XT 
RAM: 16GB
OS: Arch Linux

**Comment by Readek** [comment]
Just checked with another Pokemon game (Moon), it seems to exhibit the exact same problems.

https://github.com/citra-emu/citra/assets/35299560/e5a306b1-1469-4930-a35a-e09c19516185

**Comment by Readek** [comment]
Going back to this testing on a new Citra version, I've generated a new log which is spamming `Render.Vulkan <Warning> video_core/renderer_vulkan/vk_texture_runtime.cpp:BlitScale:1362: Depth scale unsupported by hardware` on the times a glitched texture character appears on screen (any battle).

[citra_log.txt](https://github.com/citra-emu/citra/files/13992400/citra_log.txt)

Again, this happens on both Pokemon generations, but **not** on the Steam Deck.

**Comment by autofire372** [comment]
This might be AMD-only; I can't reproduce this on my NVIDIA machine.

**Comment by Readek** [comment]
> This might be AMD-only; I can't reproduce this on my NVIDIA machine.

Making things weirder is the fact that everything is perfectly fine with the Steam Deck, which runs AMD and, in theory, the same drivers I'm using on my Linux desktop.
