### ISSUE TITLE
Project MIRAI DX - sound of tapping button is delayed

### ISSUE THREAD

**Issue by lonelycare** [citra-emu/citra#7198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2040

### Description of Issue

the sound of tapping buttons during a song is delayed, especially noticeable in hard difficulty, which makes it difficult to play since the timing of audio cues is critical in a rhythm game

### Expected Behavior

sound should be in sync with the tap

### Reproduction Steps

1. choose Rhythm Game
2. press x to change to ButtonMode
3. start the song

when the song starts, tap a button rapidly to a tune, there will be a delay of about 1/3 of a second between the tap and the sound of tapping

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13425991/citra_log.txt)

### System Configuration

CPU: 7700HQ
GPU/Driver: 1060 6G
RAM: 16G
OS: Win10

**Comment by vitor-k** [comment]
Does this happen with audio stretching disabled?
Audio stretching adds some delay to the audio due to how it works

**Comment by lonelycare** [comment]
disabled audio stretching and the sound is working great now
thank you for the advice
