### ISSUE TITLE
[Bug/Canary] Texture Sampling Setting does not stick when exiting Citra

### ISSUE THREAD

**Issue by nickkeane** [citra-emu/citra#7205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2694

### Description of Issue

I am trying to change Texture Sampling at the global level, but the setting keeps reverting to "Game Controlled" after exiting and re-entering Citra.

### Expected Behavior

Setting should remain as I set it on app restart.

### Reproduction Steps

1. Start Citra
2. Go to Emu -> Configure -> Graphics -> Advanced -> Change Texture Sampling to Nearest Neighbor. Click OK.
3. Start a game and go to global configure menu. Setting is maintained as Nearest Neighbor and applies in game.
4. File -> Exit Citra. Start Citra. Setting is reset to Game Controlled.

### Log File

https://pastebin.com/7aT2XCAG

### System Configuration

CPU: i7 13700HX
GPU/Driver: RTX 4060 Laptop / 546.17
RAM: 32 GB
OS: Win 11 Pro

**Comment by Immersion95** [comment]
Smae thing here in global/custom config
