### ISSUE TITLE
Citra stops working after booting up games 

### ISSUE THREAD

**Issue by jethrojacinto** [citra-emu/citra#7222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly Build - 0ed909e / Canary Build - 6ed4dbd

### Description of Issue

After booting up games like Pokemon X/Y, my Citra freezes and I would get the beachball which I would then have to force quit my Citra application because it stops working altogether. Am I doing something wrong? Did I need to configure something first before starting any games?

### Expected Behavior

I would assume the Expected Behavior would be for the games to start seamlessly albeit with some hitches and lags even on the new Mac silicon chips.

### Reproduction Steps

I'm not entirely sure what to put on here or what the 'Reproduction Steps' would be to my issue.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13518629/citra_log.txt)

### System Configuration

CPU: 8-Core
GPU/Driver: 10-Core
RAM: 8GB Unified Memory
OS: Sonoma 14.1.1

**Comment by milotic** [comment]
is happening in android too
the log

[citra_log.txt](https://github.com/citra-emu/citra/files/13574257/citra_log.txt)

**Comment by Steveice10** [comment]
This should be fixed by the removal of cubeb audio from the macOS releases, when cubeb is fixed on macOS we will reintroduce it later as well.
