### ISSUE TITLE
luigi mansion coop

### ISSUE THREAD

**Issue by LITTLECHOPT8** [citra-emu/citra#7228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

citra canary 2703

### Description of Issue

on coop error has occured and in console it says unimplented feature [  61.426778] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:166: unknown / unimplemented function 'ReplySleepQuery': port='APT:A' cmd_buf={[0]=0x3e0080 (0x003E, 2, 0), [1]=0x300, [2]=0x0}

### Expected Behavior

when connecting both players should have a screen saying preparing

### Reproduction Steps

simply host a coop game and try to join it

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13537101/citra_log.txt)

### System Configuration

CPU: i7 12 gen 
GPU/Driver:
RAM:
OS: windows 11

**Comment by FearlessTobi** [comment]
The error you posted has nothing to do with multiplayer.

**Comment by LITTLECHOPT8** [comment]
well then some thing aint working in coop

**Comment by LITTLECHOPT8** [comment]
when i joined with 2nd player that appeared in the console
