### ISSUE TITLE
add directx uspport

### ISSUE THREAD

**Issue by xXxPipor333xXx** [citra-emu/citra#7229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

my pc cant handle opengl, add directx or im turning you devs all into lemondae

### Why would this feature be useful?

its good because it allows poor people to use citra

**Comment by FearlessTobi** [comment]
Damn, guess I'll turn into lemonade now ;)

**Comment by goldenx86** [comment]
Inb4 they mean D3D9.

**Comment by xXxPipor333xXx** [comment]
> Damn, guess I'll turn into lemonade now ;)

get ready to be lemonated

**Comment by xXxPipor333xXx** [comment]
> Inb4 they mean D3D9.

direct3d 7 obviously, its the most recent and supported version after all
