### ISSUE TITLE
SSB crashes on Android when rotating the screen with the vulkan api

### ISSUE THREAD

**Issue by Majora8120** [citra-emu/citra#7248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2053 Canary 2716

### Description of Issue

When rotating the screen to landscape in game it crashes. Rotating the screen before launching the game doesn't cause this. Opengl works fine

### Expected Behavior

It doesn't crash

### Reproduction Steps

Launch Super Smash Bros in portrait mode using the vulkan renderer then rotate your phone to landscape once the game starts running.

### Log File

[SSBCrashlogCanary.txt](https://github.com/citra-emu/citra/files/13687638/SSBCrashlogCanary.txt)
This log is from Canary 2716 and has the debug renderer enabled and is using turnip 24.0.0 R12 Aggressive

### System Configuration

CPU: Snapdragon 8 gen 1
GPU/Driver: Both official Qualcomm drivers and Turnip
RAM: 8GB
OS: Android

**Comment by GPUCode** [comment]
Does the crash also occur with proprietary driver?

**Comment by Majora8120** [comment]
After testing on canary 2780 this issue seems to have been fixed but i have noticed that citra will crash regardless of renderer after rotating the screen around 20-30 times but that is different then the issue i had when i made this issue report so i'm closing it as completed.
