### ISSUE TITLE
Mario kart 7 stuttering 

### ISSUE THREAD

**Issue by Cybergbx** [citra-emu/citra#7249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2719

### Description of Issue

Mario kart 7 Only in the Shell Cup in Luigi's phase does it give some aggressive stuttering at the beginning of the phase, in the other phases it's normal but only in that one that causes problems, I'm using Vulkan and OpenGL it gets worse.

### Expected Behavior

...

### Reproduction Steps

...

### Log File

missing
[   0.658314] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:344: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   0.702463] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.749060] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.791982] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.841662] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.861036] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384

### System Configuration

CPU:snapdragon 680
GPU/Driver:adreno 610
RAM:4 ram
OS:Android 13

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

Closing
