### ISSUE TITLE
Stuttering pokémon x/y, alpha saphire/ omega ruby 

### ISSUE THREAD

**Issue by Cybergbx** [citra-emu/citra#7251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2719

### Description of Issue

Pokémon games such as x and y, alpha sapphire and omega ruby have gained performance in these latest versions but are experiencing stuttering when entering battles, unlike Pokemon Sun and Moon that don't have this error

### Expected Behavior

..

### Reproduction Steps

...

### Log File

[   0.000259] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_createLogFile:561: Logging backend initialised
[   0.000343] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logUserDirectory:568: User directory path: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCitra
[   0.027537] Config <Info> main/jni/config.cpp:LoadINI:57: Successfully loaded /config/config.ini
[   0.076932] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logDeviceInfo:714: Citra Version: Canary 2718 | HEAD-35291c9
[   0.077217] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logDeviceInfo:715: Host CPU: Qualcomm Technologies, Inc SM6225
[   0.077233] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logDeviceInfo:717: Host OS: Android API level 33
[   0.413016] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.527607] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.550419] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.654027] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.658289] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:238: Secure1 KeyX missing
[   0.658306] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:248: Secure1 KeyX missing
[   0.658314] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:344: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   0.702463] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.749060] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.791982] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.841662] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.861036] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384

### System Configuration

CPU: snapdragon 680
GPU/Driver:adreno 610
RAM:4 
OS:Android 13

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

Closing
