### ISSUE TITLE
Swapdoodle save data error

### ISSUE THREAD

**Issue by milesthecreator** [citra-emu/citra#7252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2052

### Description of Issue

After going through the introductory note and configuring settings, an error message appears regarding the save data.
![Swapdoodle_17 12 23_20 22 25 618](https://github.com/citra-emu/citra/assets/45196539/26777a42-e616-4696-b453-617a24004fb9)

### Expected Behavior

The game is expected to proceed normally without errors.
(Screenshot from Nightly 2051)
![Swapdoodle_17 12 23_20 27 06 496](https://github.com/citra-emu/citra/assets/45196539/39ef8fbb-5fab-43d3-8053-3acaf007fa45)

### Reproduction Steps

1. Launch the game (Swapdoodle requires system files and enabled LLE frd.)
2. Go through introduction note and settings configuration.
3. Error happens.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13696864/citra_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.20 GHz
GPU/Driver: NVIDIA GeForce GTX 1050 Ti
RAM: 16GB RAM
OS: Windows 10

**Comment by GPUCode** [comment]
Does the game work with LLE BOSS module (View -> Debugging  -> Toggle LLE modules)
Looks like the game was regressed by the BOSS part 1 PR.

**Comment by milesthecreator** [comment]
Yeah, that got past the error. Thanks!

**Comment by milesthecreator** [comment]
Nightly 2062 got past the save data error but introduces another problem.

Do I post it here or open a new issue?

**Comment by GPUCode** [comment]
If it's completely unrelated to this one, better make a new issue
