### ISSUE TITLE
Citra on android with vulkan API closes in Pokémon ORAS,USUM And NSMB2

### ISSUE THREAD

**Issue by daeklo4** [citra-emu/citra#7253]
### Issue

Hello, greetings to all the developers of this incredible emulator, I am writing to you to know if you can help me with this problem in Citra Android. On my device all the Nintendo 3ds titles run, not so fluid but they are playable (With opengl ES) but In the case of Vulkan, the titles New Super Mario Bros 2, Pokémon Alpha Sapphire, Omega Ruby, What does not happen with OPENGL ES, please help me I send you the log file and several screenshots and a screen recording, thank you very much. It may even seem like a low-end cell phone but one point that makes me believe that this problem has a solution is that they also run Nintendo switch titles in skyline emu, I am sending you screenshots of this as well Mali GPU (MediaTek) 3GB RAM Android 10
[citra_log.txt](https://github.com/citra-emu/citra/files/13699210/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/13699211/citra_log.txt.old.txt)
![Screenshot_2023-12-17-22-05-34-579](https://github.com/citra-emu/citra/assets/109567065/f57fb2b4-38c2-466d-a7e5-c117d875f6ca)
![Screenshot_2023-12-17-22-06-18-725](https://github.com/citra-emu/citra/assets/109567065/762ebac7-ec70-4fa2-bb22-0cca0deb94ac)
![Uploading Screenshot_2023-12-17-22-06-39-710.jpg…]()

https://github.com/citra-emu/citra/assets/109567065/d624d93c-d246-476d-826b-9df8b847b686

**Comment by daeklo4** [comment]
@GPUCode 
@Steveice10 
@SachinVin 
@FearlessTobi 
@t895 
@Wunkolo 
@bunnei 
Please help me!

**Comment by SachinVin** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord or forums for support requests.

**Comment by daeklo4** [comment]
My device specifications:
![Screenshot_2023-12-17-22-06-39-710](https://github.com/citra-emu/citra/assets/109567065/30cc9552-1470-4c92-b7d8-ede22365123f)
