### ISSUE TITLE
Citra Vulkan Crash on Android 

### ISSUE THREAD

**Issue by daeklo4** [citra-emu/citra#7254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2054/Canary 2720

### Description of Issue

Hello, greetings to all the developers of this incredible emulator, I am writing to you to know if you can help me with this problem in Citra Android. On my device all the Nintendo 3ds titles run, not so fluid but they are playable (With opengl ES) but In the case of Vulkan, the titles New Super Mario Bros 2, Pokémon Alpha Sapphire, Omega Ruby, What does not happen with OPENGL ES, please help me I send you the log file and several screenshots and a screen recording, thank you very much. It may even seem like a low-end cell phone but one point that makes me believe that this problem has a solution is that they also run Nintendo switch titles in skyline emu, I am sending you screenshots of this as well Mali GPU (MediaTek) 3GB RAM Android 10
![Screenshot_2023-12-17-22-05-34-579](https://github.com/citra-emu/citra/assets/109567065/85b366ce-12a3-44c9-bcb4-c7b01f1f1928)
![Screenshot_2023-12-17-22-06-18-725](https://github.com/citra-emu/citra/assets/109567065/de4cbf9a-64d9-424f-a3f5-49b056d8f887)

https://github.com/citra-emu/citra/assets/109567065/52b449b2-bcbb-49ab-8f26-71c753da3d92

### Expected Behavior

With Vulkan, when you start the Pokémon titles, the new suoer Mario Bros 2 closes instantly

### Reproduction Steps

Execution of the title/load shaders cache/closes

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13699251/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/13699252/citra_log.txt.old.txt)

### System Configuration

CPU:MediaTek
GPU/Driver:Default system driver(Mali GPU)
RAM:3GB
OS:Android 10
![Screenshot_2023-12-17-22-06-39-710](https://github.com/citra-emu/citra/assets/109567065/b6ff72ca-dd98-44bc-9c1a-b0095a195a61)

**Comment by daeklo4** [comment]
@GPUCode 
@FearlessTobi 
@t895 
@Steveice10 
@Wunkolo 
@TGP17 

Please help me!(with vulkan I get better performance in those titles but with (Opengl Es) I don't)

**Comment by Adamillo** [comment]
Don't ping this many people, it's kinda rude to do that

**Comment by GPUCode** [comment]
Try enabling debug renderer in the settings otherwise the log won't show the crash. And yes pinging that many people is excessive

**Comment by daeklo4** [comment]
Greetings, my sincere apologies to the citra team for that, I will never do it again (I didn't know, I'm new to GITHUB), truly apologies. GpuCode I send you attached the log file with (Renderer_Debug: true), please, I reiterate my apologies, please help me. I send a new log here🙏🙏🙏
[citra_log.txt](https://github.com/citra-emu/citra/files/13703570/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/13703571/citra_log.txt.old.txt)

@GPUCode

**Comment by surlup** [comment]
upgrade your phone

**Comment by FearlessTobi** [comment]
The user has been banned from our repo.

Closing
