### ISSUE TITLE
[Android] Street fighter 4 rotation crash

### ISSUE THREAD

**Issue by KingJ2480** [citra-emu/citra#7256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 

### Description of Issue

Everytime my screen rotates, street fighter 4 just crashes.

### Expected Behavior

The game should not crash.

### Reproduction Steps

Just rotate your screen

### Log File

[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/13709708/citra_log.txt.old.txt)

### System Configuration

CPU: Snapdragon 680
GPU/Driver: Adreno 610
RAM: 8gb
OS: Android 12

**Comment by FearlessTobi** [comment]
Closing in favor of https://github.com/citra-emu/citra/issues/7290, which is more detailed.
