### ISSUE TITLE
Change upload file to apk instead of zip

### ISSUE THREAD

**Issue by topdog11ttc** [citra-emu/citra#7257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Curious as to why you chose to package citra builds zipped rather then upload apks directly.

### Why would this feature be useful?

There is a great app called [Obtanium](https://github.com/ImranR98/Obtainium) that allows you to install and update Apps directly from Github release pages and receive notifications when new releases are made available. It searches for apks so Citra being uploaded in zip format makes it unusable with Obtanium.

**Comment by TGP17** [comment]
We started to zip the APKs to reduce the download size, since the support for x86_64 Android increased the APK size.
