### ISSUE TITLE
Conveni Dream saves get corrupted and cannot load.

### ISSUE THREAD

**Issue by duckfromdiscord** [citra-emu/citra#7264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2026

### Description of Issue

At some point between March 2023 and today a breaking change was made to Citra that causes the game Conveni Dream to be unable to load its saves. This issue needs to be bisected.

### Expected Behavior

Exiting to title screen from in-game and then hitting Continue should put you back into your game, but instead a "not allowed" sound is made, but only on newer versions of Citra. On older versions the save loads.

### Reproduction Steps

The game Conveni Dream can be started by hitting start in the menu, and going through the tutorial. Exit the game by hitting the up arrow at the bottom of the screen and hitting the Title button. Then hit "Continue". A "not allowed" sound is made in Citra 2026, but not in the Vulkan test build from March 2023 (that's the earliest one I found on my computer, and it worked there).

### Log File

Logs are the same across versions

### System Configuration

CPU: Intel i5
GPU/Driver: 3050 Ti
RAM: 40GB
OS: Windows 10

**Comment by duckfromdiscord** [comment]
It seems to be working in 2056 nightly but not the installed version

**Comment by SachinVin** [comment]
> It seems to be working in 2056 nightly but not the installed version

What do you mean by "installed version" ? Installed game or installed Citra?
If it is the latter please check both the msvc version and mingw versions.

**Comment by duckfromdiscord** [comment]
The issue was not present in nightly 2020, but it was present in nightly 2021 through 2038 and was fixed in 2039 presumably with `Fix save data secure value stubs` #7191.

**Comment by duckfromdiscord** [comment]
> > It seems to be working in 2056 nightly but not the installed version
> 
> What do you mean by "installed version" ? Installed game or installed Citra? If it is the latter please check both the msvc version and mingw versions.

The reason it worked in the "installed version" was because the issue was introduced in 2021 and fixed in 2039, and I had 2026

**Comment by duckfromdiscord** [comment]
This is very important information because I was having this problem on a real system and this will help me solve that

**Comment by SachinVin** [comment]
So this is not an issue?
