### ISSUE TITLE
Can't savestate in Paper Mario Sticker Star

### ISSUE THREAD

**Issue by mcbegamerxx954** [citra-emu/citra#7287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 2726

### Description of Issue

So while testing in android this error appears only in paper Mario sticker star it seems, and it happens when you try to savestate at any point in the game:

![Screenshot_2023-12-25-10-25-45-657_org citra citra_emu canary](https://github.com/citra-emu/citra/assets/154642722/e2baedec-8f6f-40f6-b7b6-84c5924ca081)

### Expected Behavior

To savestate correctly

### Reproduction Steps

Go to citra in-game menu -> Save in any slot -> Error

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13766219/citra_log.txt)

### System Configuration

CPU: MTK Helio G80
GPU/Driver: Mali-G52 MC2
RAM: 4gb
OS: Android 13

**Comment by mcbegamerxx954** [comment]
I don't know if what I'm gonna show next deserves another issue but when you try to savestate very early after game boot you get this error instead:
![Screenshot_2023-12-25-10-37-24-489_org citra citra_emu canary](https://github.com/citra-emu/citra/assets/154642722/bdc61eef-f541-4d27-893a-236554ac0a58)

**Comment by GPUCode** [comment]
Will be fixed in next canary
