### ISSUE TITLE
update issues

### ISSUE THREAD

**Issue by porconero** [citra-emu/citra#7299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

nightly 2062

### Description of Issue

by updating citra from going to the old citra nightly with 60 fps i got 1 fps on the new updated citra nightly we found it rough for low end pc users 

### Expected Behavior

try and fix this by keeping an apart log where u can install the version that u please

### Reproduction Steps

try and fix this by keeping an apart log where u can install the version that u please

### Log File

try and fix this by keeping an apart log where u can install the version that u please

### System Configuration

CPU:adad
GPU/Driver:adad
RAM:adad
OS:adad

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests

Closing
