### ISSUE TITLE
Motion controls not working properly on landscape orientation since nightly 2060

### ISSUE THREAD

**Issue by Javiolini** [citra-emu/citra#7308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2060 - 2066

### Description of Issue

Since nightly 2060 motion controls seem to be locked to the portrait orientation, so when using landscape they are unusable. They work fine on both orientations on nightly 2059.

Video on nightly 2066:

https://github.com/citra-emu/citra/assets/12807138/247356f8-edc9-45b0-aad6-629432770c69

### Expected Behavior

Both orientations on nightly 2059:

https://github.com/citra-emu/citra/assets/12807138/5bd2e9f2-be04-4e4b-b14e-aa93613451e4

### Reproduction Steps

Use motion controls on nightly 2060 - 2066.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13814050/citra_log.txt)

### System Configuration

CPU: Snapdragon 860
GPU/Driver: System
RAM: 8 GB LPDDR4X
OS: Lineage OS 20

**Comment by Steveice10** [comment]
If it's nightly 2060 then it's probably from https://github.com/citra-emu/citra-nightly/commit/60a280af24a201895d25ee6b25f304ec8ab07076 (@jamfor352)

**Comment by Javiolini** [comment]
@jamfor352 Yup, its fixed, thanks!
