### ISSUE TITLE
Game/app hangs after calling OS Software Keyboard several times

### ISSUE THREAD

**Issue by Th3rdSergeevich** [citra-emu/citra#7315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2068

### Description of Issue

Wherever I call OS Software Keyboard to input text several times during the game session, on 5th call the keyboard does not appear and the game hangs. This behaviour is persistent across various apps and games (namely Mii Maker, Tomodachi Life and Miitopia). 

System region is US.

### Expected Behavior

Software Keyboard should be called indefinite amount of times with no issues.

### Reproduction Steps

This will work only if US System Files are present in Citra folder.

1) Launch Mii Maker
2) Select Create New Mii
3) Skip all the way to nickname entry
4) Touch either Nickname or Creator text field.
Keyboard will appear.
5) Press Cancel OR enter text and press OK.
6) Repeat steps 4-5 four times. On 5th try the issue will occur.

### Log File

[citra_log_issue.txt](https://github.com/citra-emu/citra/files/13845732/citra_log_issue.txt)

### System Configuration

CPU: MediaTek Helio G35
GPU/Driver: PowerVR GE8320
RAM: 4 GB
OS: Android 11

**Comment by Steveice10** [comment]
> [ 282.026102] Kernel <Error> core/hle/kernel/resource_limit.cpp:Reserve:45: New value 15 exceeds limit 14 for resource type 2

This is a known issue with resource limits (I think @GPUCode has the details?)

**Comment by Th3rdSergeevich** [comment]
Can confirm: the issue has been fixed.

Thanks!
