### ISSUE TITLE
Can't configure L and R in Mac OS

### ISSUE THREAD

**Issue by nvanfleet** [citra-emu/citra#7332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2071

### Description of Issue

The UI to setup L and R shoulder buttons is not present in the Mac OS version of Citra so I can't set that up.

<img width="482" alt="Screenshot 2024-01-07 at 9 00 21 PM" src="https://github.com/citra-emu/citra/assets/1486399/595a87a5-7263-4e7a-a738-8bc4730ed3cb">

### Expected Behavior

I expect to be able to do that

### Reproduction Steps

I just installed Citra fresh today and that was the case

### Log File

[   0.097941] Input <Info> input_common/udp/client.cpp:StartCommunication:206: Starting communication with UDP input server on 127.0.0.1:26760
[   0.128995] Frontend <Info> citra_qt/main.cpp:GMainWindow:237: Citra Version: Nightly 2071 | HEAD-c8c2bea
[   0.129002] Frontend <Info> citra_qt/main.cpp:GMainWindow:254: Host OS: macOS 14.2
[   0.129019] Frontend <Info> citra_qt/main.cpp:GMainWindow:257: Host RAM: 64.00 GiB
[   0.129020] Frontend <Info> citra_qt/main.cpp:GMainWindow:258: Host Swap: 0.00 GiB
[   0.158206] Render.Vulkan <Info> video_core/renderer_vulkan/vk_platform.cpp:operator():260: Candidate instance extension VK_KHR_portability_enumeration is not available
[   0.160309] Frontend <Info> citra_qt/main.cpp:CheckForUpdates:998: Update check started
[   0.618294] Frontend <Info> citra_qt/main.cpp:OnUpdateFound:1011: No updates found
[   9.543697] Service.PTM <Error> core/hle/service/ptm/ptm.cpp:ReadGameCoinData:190: Could not open the PTM SharedExtSaveData archive!

### System Configuration

CPU: Mac OS M1
GPU/Driver: 
RAM: 64GB
OS: Sonoma 14.2.1

**Comment by Steveice10** [comment]
You need to scroll down in the input configuration box.

**Comment by nvanfleet** [comment]
Sorry about that!
