### ISSUE TITLE
Resident Evil Mercenaries 3D Crash When red barrels explode

### ISSUE THREAD

**Issue by lXBloodShootXl** [citra-emu/citra#7340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly Build - 2ce0a9e

### Description of Issue

I have an Huawei p30 lite and the game works so good with Vulkan but when I shoot to red barrels the game crash. It doesn't happen if I turn off the Hardware Shader option of Depuration. The game without that setting it's too slow. 

### Expected Behavior

.

### Reproduction Steps

. 

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13895770/citra_log.txt)

### System Configuration

CPU: Kirin 710 Octa Core
GPU/Driver: Mali-G51 MP4
RAM: 6GB
OS: Android

**Comment by FearlessTobi** [comment]
Your issue report is incomplete. Please fill out the missing parts.
