### ISSUE TITLE
Graphics regression in 3DSCraft

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#735]
Commit 0e5ca080a86a6e393eab1a11075561a62a2e01f9 ("Default vertex shader attributes") introduced a shading regression in 3dscraft:

![3dscraft](http://i.imgur.com/5SYnBTf.png)

This issue is **not** fixed by #726.

cc @Subv @bunnei @neobrain

**Comment by Subv** [comment]
3dscraft sets the attribute_mask to 0xFFC for no reason, https://github.com/smealum/3dscraft/blob/852466def34e8a3c3425369941042c4db4b48967/source/main.c#L91 . This causes our code to believe that it's using default attributes when it actually isn't, so it's loading zero'd attributes and ignoring whatever was loaded with the attribute_loaders.

I believe the real hardware gives priority to the attributes loaded via attribute_loaders over the ones set to be default attributes. The only evidence I have to support this theory is that 3dscraft works fine on hardware.

Here's a patch addressing the issue, but we'll need to perform some hardware tests to make sure that this is actually the case
https://gist.github.com/Subv/077c71ed1d065943722c

**Comment by Subv** [comment]
New patch, inspired by @yuriks https://gist.github.com/Subv/077c71ed1d065943722c
