### ISSUE TITLE
[Bug] Sakura Samurai: Art of the Sword - Black Area Background

### ISSUE THREAD

**Issue by milesthecreator** [citra-emu/citra#7352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2076

### Description of Issue

In the final stage of the game, a black area can be seen in the background which is not supposed to happen. It seems to follow the enemy, defeating the enemy gets rid of the black area.
![Sakura_SamuraiArt_of_the_Sword_14 01 24_20 18 37 065](https://github.com/citra-emu/citra/assets/45196539/bc90afd9-db8d-4b8f-9526-9b4751be7622)
![Sakura_SamuraiArt_of_the_Sword_14 01 24_20 19 42 563](https://github.com/citra-emu/citra/assets/45196539/ec6bddc4-b243-4931-b8aa-f34e23313428)

### Expected Behavior

The background should not have a black area in the background. (Screenshots taken from the real console.)
![2024-01-14_21-00-01 790_top](https://github.com/citra-emu/citra/assets/45196539/5331a4ae-8a6e-484e-8c9a-15a63be692c1)
![2024-01-14_21-01-03 571_top](https://github.com/citra-emu/citra/assets/45196539/2316283e-5295-484a-b869-a40d27bb8a3c)

### Reproduction Steps

- Launch the game and select "Continue Game".
- Go to the final stage. (Titled "Dark Moon Castle")
- A black area can be seen in the background. (You may need to move around to see it, by moving the circle pad and pressing B)

Save file:
https://drive.google.com/file/d/1zsXxwDoKW38j1R0f9nTBHVj9AEB-b4uJ/view?usp=sharing

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13932435/citra_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
GPU/Driver: NVIDIA GeForce GTX 1050 Ti
RAM: 16GB
OS: Windows 10

**Comment by GPUCode** [comment]
Does this also happen when using OpenGL?

**Comment by milesthecreator** [comment]
> Does this also happen when using OpenGL?

Yes.

**Comment by GPUCode** [comment]
Can you check if linked PR fixes the issue, thanks

**Comment by milesthecreator** [comment]
> Can you check if linked PR fixes the issue, thanks

That fixed it, thanks!
