### ISSUE TITLE
[Bug] Face Raiders (New 3DS Version) Crash

### ISSUE THREAD

**Issue by milesthecreator** [citra-emu/citra#7353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2076

### Description of Issue

The emulator crashes after the preparing screen. Launching the game after that will crash the emulator immediately.

For context, Face Raiders has an old 3ds and new 3ds versions. The old 3ds version can boot the game normally, while the new 3ds version has this issue.

### Expected Behavior

The game should not crash the emulator.

### Reproduction Steps

- Launch the game. (Make sure it's from new 3DS firmware, NOT old 3ds)
- Emulator crashes.

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13932446/citra_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
GPU/Driver: NVIDIA GeForce GTX 1050 Ti
RAM: 16GB
OS: Windows 10

**Comment by PCSX1** [comment]
Same Problem On Old 3DS

https://github.com/citra-emu/citra/assets/155913442/2b70d1b2-2f46-4cb0-b09e-5efc471c2eb8

**Comment by PCSX1** [comment]
Booting Other Game From Home Menu Not appeared same problem Than Face Raiders https://github.com/citra-emu/citra/assets/155913442/44b0d8ed-b0ec-49ef-a564-e5bc4483932a

**Comment by PCSX1** [comment]
Booting Face Raiders And This Fix From Home Menu Not appeared same problem Than Face Raiders.

https://github.com/citra-emu/citra/assets/155913442/787c5944-3e3f-4cbd-a4b7-d48d536333e3
