### ISSUE TITLE
sanitize_mul is inefficient

### ISSUE THREAD

**Issue by alyssarosenzweig** [citra-emu/citra#7371]
### Issue

the current sanitize_mul does 3 isnan checks and 3 selects, to implement 0 * Inf = 0 semantics. However, there is a better implementation, used I think by DXVK:

    a * b = (b == 0 ? 0 : a) * (a == 0 ? 0 : b)

This requires only 2 compares and 2 selects, which is a significant improvement %wise given that a vertex shader can spam these multiplies a LOT and translate into real fps difference.

Furthermore, expressed in this form, Mesa drivers will optimize the entire expression to a single hardware instruction `fmulz`, which is like `fmul` but with the `0 * Inf = 0` behaviour. We cannot* optimize Citra's current expression, since the two expressions differ in how `0 * NaN` is defined: Citra will return NaN while the alternate expression will return 0. Is this intended? If not, changing to the alternate form should speed things up a lot on eligible hardware, and a little on all hardware :smile_cat:  

(If this is intended, well, sucks but that's that.)

\* Strictly, in OpenGL, all bets are off with NaNs. But fixing this in Citra would be better for all parties than working around it in Mesa.

**Comment by Steveice10** [comment]
> We cannot* optimize Citra's current expression, since the two expressions differ in how 0 * NaN is defined: Citra will return NaN while the alternate expression will return 0. Is this intended?

Yes, the 3DS GPU also has 0 * NaN = NaN

**Comment by alyssarosenzweig** [comment]
Ouch. OK, then I'm extra glad we didn't "optimize" this in Mesa! Might be worth a comment... Thanks for letting me know ^^
