### ISSUE TITLE
[Android/Mali] Lego The Hobbit: Vertex explosions

### ISSUE THREAD

**Issue by matiastulio** [citra-emu/citra#7373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary Build - d5193a7

### Description of Issue

Character vertex explosions

https://github.com/citra-emu/citra/assets/2229668/2810e7b5-6351-4e51-bc69-02e3fe7cabaa

[Device info from aida64](https://github.com/citra-emu/citra/files/13999781/report.aida64.txt)

### Expected Behavior

Without vertex explosions

### Reproduction Steps

Open the game, the main character is exploding 

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/13999704/citra_log.txt)

### System Configuration

CPU: Dimensity 1200
GPU/Driver: mali G77 MC9
RAM: 6GB
OS: Android 11

**Comment by applecuckoo** [comment]
Don't mind me, I've just transcoded the video clip so that it actually shows up on GitHub (it didn't for me):

https://github.com/citra-emu/citra/assets/113647417/2051b0c7-76c9-4329-a91d-2a81ba1871f9

**Comment by FearlessTobi** [comment]
Try to enable Accurate Multiplication please.

**Comment by matiastulio** [comment]
Damn that did the trick. My bad sir, I will close this issue then
