### ISSUE TITLE
Ridge Racer 3D crashes out nearly straight away

### ISSUE THREAD

**Issue by ScottNash042** [citra-emu/citra#7378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2081

### Description of Issue
@GPUCode 
load game and it crashes out straight away
[   4.394181] Render.Vulkan <Error> video_core/renderer_vulkan/vk_platform.cpp:DebugUtilsCallback:59: VUID-vkEndCommandBuffer-commandBuffer-00060: Validation Error: [ VUID-vkEndCommandBuffer-commandBuffer-00060 ] Object 0: handle = 0x1559ffd4e20, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4d08326d | vkEndCommandBuffer():  It is invalid to issue this call inside an active VkRenderPass 0x67eecd00000000ea[]. The Vulkan spec states: If commandBuffer is a primary command buffer, there must not be an active render pass instance (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkEndCommandBuffer-commandBuffer-00060)
[   4.394915] Render.Vulkan <Error> video_core/renderer_vulkan/vk_platform.cpp:DebugUtilsCallback:59: VUID-vkCmdEndRenderPass-renderpass: Validation Error: [ VUID-vkCmdEndRenderPass-renderpass ] Object 0: handle = 0x1559ffd73b0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x46db6f2f | vkCmdEndRenderPass():  This call must be issued inside an active render pass. The Vulkan spec states: This command must only be called inside of a render pass instance (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdEndRenderPass-renderpass)

### Expected Behavior

goes ingame

### Reproduction Steps

load game

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/14009127/citra_log.txt)

### System Configuration

OS
Windows 10

CPU
Ryzen 5 5700X

GPU
NVIDIA RTX 2060

RAM
16gb

**Comment by GPUCode** [comment]
Hm looks like the game possibly does a flush in the middle of waiting
