### ISSUE TITLE
Right analog cross hair like libretro citra git?

### ISSUE THREAD

**Issue by 007mesen** [citra-emu/citra#7382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Allowing the touchscreen to have a mouse like pointer off of joy1 right analogue 

### Why would this feature be useful?

Perfect for couch gaming on htpc with xbox controller. Already doing this with the libretro core but would rather be using standalone proper builds

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/citra-emu/citra/issues/5816.
