### ISSUE TITLE
Animal Crossing: New Leaf doesn't even boot (Android)

### ISSUE THREAD

**Issue by Le0X8** [citra-emu/citra#7401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Canary 86a52c8

### Description of Issue

I just loaded Citra on my new phone, and tried to run Animal Crossing: New Leaf. The game instantly crashed at boot.

### Expected Behavior

Not crashing. My Android Tablet runs the same release and doesn't crash.

### Reproduction Steps

- Get ACNL
- Try to run it

### Log File

[citra_log.txt](https://github.com/citra-emu/citra/files/14085997/citra_log.txt)

### System Configuration

Standard Samsung Galaxy S24

Android 14 (Kernel v6.1.43)
OneUI 6.1

**Comment by SachinVin** [comment]
Try changing the graphics API to vulkan

**Comment by Le0X8** [comment]
Fixed it.
