### ISSUE TITLE
Super Monkey Ball 3D:  Goal Gate Fadeout Fails

### ISSUE THREAD

**Issue by JMC47** [citra-emu/citra#744]
In Super Monkey Ball 3D, when you go through the goal gate, a white line goes up the gate as it fades out from bottom to top.  It looks like this on original hardware.

https://www.youtube.com/watch?feature=player_detailpage&v=8QHyE9j1mFw#t=128

![smb3dgoalgate3ds](https://cloud.githubusercontent.com/assets/6598209/7558334/d984be9a-f76f-11e4-966b-2bfa0bd274d7.jpg)

On Citra, it does not work correctly.

https://www.youtube.com/watch?feature=player_detailpage&v=t0TGSeQe1wE#t=27

![smb3dgoalgate](https://cloud.githubusercontent.com/assets/6598209/7558332/cbbfa144-f76f-11e4-9fe6-8945cd4e1884.jpg)

Note, I used timecodes for the videos, hopefully it works.

The effect on Citra shows the top half of the goal gate instantly invisible, one part of the gate partially faded out and the bottom of the gate is stuck visible.  The white line goes across the whole screen instead of being limited to the gate area as well.

**Comment by archshift** [comment]
Is this still an issue?

**Comment by JMC47** [comment]
Nope, Fixed.
