### ISSUE TITLE
Add Swap Screen to controller button option?

### ISSUE THREAD

**Issue by Xyrexus** [citra-emu/citra#7440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Sorry if I'm just being dumb and this is already possible, but is it possible to assign the Swap Screens function to a controller button? I see the default is F9, but I can only seem to change it to another keyboard key, it would be great to be able to assign it to my controller, as the way I play doesn't have me comfortably near my keyboard.

### Why would this feature be useful?

When playing a game with the second screen smaller, being able to swap screens at the touch of a button can be extremely useful. I was able to do this with DS games on another emulator, so going from that to not is very noticable to me.

**Comment by Daisouji** [comment]
https://github.com/citra-emu/citra/issues/5885

**Comment by FearlessTobi** [comment]
Closing as duplicate.
