### ISSUE TITLE
Starting a specific game with command line arguments

### ISSUE THREAD

**Issue by steve02081504** [citra-emu/citra#7450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

- Starting a specific game with command line arguments
- Right-click an item in the game list to create a shortcut on the desktop

### Why would this feature be useful?

I want to add the game to steam, but I didn't find the right command to launch the specific app in citra
![图片](https://github.com/citra-emu/citra/assets/31927825/fa257088-be4e-4546-8a6a-1d3e619689eb)
I tried starting citra with the common help parameters and didn't see any help messages either

**Comment by Daisouji** [comment]
> Starting a specific game with command line arguments

Already a feature,  citra-qt.exe "path\to\rom" 

> Right-click an item in the game list to create a shortcut on the desktop

#7423

**Comment by steve02081504** [comment]
> > Starting a specific game with command line arguments
> 
> Already a feature, citra-qt.exe "path\to\rom"
> 
> > Right-click an item in the game list to create a shortcut on the desktop
> 
> #7423

Thanks for your help but I don't quite understand what rom means, I tried starting citra like this but it just white screens for a while then crashes. Can you help me with this?
```powershell
~ >E:\Citra\nightly\citra-qt.exe D:\3DS\user
~ >cd /d/3DS/user
D:\3DS\user >copilot tree -smart
卷 游戏 的文件夹 PATH 列表
卷序列号为 63E9-FD24
D:\3DS\user
├─cheats
├─config
│  └─custom
├─gpu_drivers
├─log
├─nand
│  └─data
│      └─00000000000000000000000000000000
│          ├─extdata
│          └─sysdata
├─screenshots
├─sdmc
│  └─Nintendo 3DS
│      ├─00000000000000000000000000000000
│      │  └─00000000000000000000000000000000
│      │      ├─extdata
│      │      │  └─00000000
│      │      │      └─00000F4E
│      │      └─title
│      │          └─00040000
│      │              └─000f4e00
│      │                  ├─content
│      │                  └─data
│      │                      └─00000001
│      └─Private
│          └─00020400
├─shaders
├─states
└─sysdata
```

**Comment by Daisouji** [comment]
the rom is the game, if it's .3DS, it's the path towards that file.

**Comment by steve02081504** [comment]
> the rom is the game, if it's .3DS file, it's the path towards that file. If you are running a command-line, it's better to use .3ds.

```pwsh
D:\3DS\user >ls -Filter *.txt -Recurse

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---         2024/2/13     11:42            415 󰈙  00040000000F4E00.txt
-a---         2024/2/19      0:49           1047 󰈙  citra_log.txt
-a---         2024/2/19      0:49           5927 󰈙  citra_log.txt.old.txt
-a---         2024/2/11     19:13           2439 󰈙  aes_keys.txt

D:\3DS\user >ls -Filter *.3ds -Recurse
D:\3DS\user >
```
I didn't find any 3ds files in my citra data directory.....
I'm not sure if this right?

**Comment by Daisouji** [comment]
> > the rom is the game, if it's .3DS file, it's the path towards that file. If you are running a command-line, it's better to use .3ds.
> 
> ```powershell
> D:\3DS\user >ls -Filter *.txt -Recurse
> 
> Mode                LastWriteTime         Length Name
> ----                -------------         ------ ----
> -a---         2024/2/13     11:42            415 󰈙  00040000000F4E00.txt
> -a---         2024/2/19      0:49           1047 󰈙  citra_log.txt
> -a---         2024/2/19      0:49           5927 󰈙  citra_log.txt.old.txt
> -a---         2024/2/11     19:13           2439 󰈙  aes_keys.txt
> 
> D:\3DS\user >ls -Filter *.3ds -Recurse
> D:\3DS\user >
> ```
> 
> I didn't find any 3ds files in my citra data directory..... I'm not sure if this right?

Where are the games?

**Comment by steve02081504** [comment]
> > > the rom is the game, if it's .3DS file, it's the path towards that file. If you are running a command-line, it's better to use .3ds.
> > 
> > 
> > ```powershell
> > D:\3DS\user >ls -Filter *.txt -Recurse
> > 
> > Mode                LastWriteTime         Length Name
> > ----                -------------         ------ ----
> > -a---         2024/2/13     11:42            415 󰈙  00040000000F4E00.txt
> > -a---         2024/2/19      0:49           1047 󰈙  citra_log.txt
> > -a---         2024/2/19      0:49           5927 󰈙  citra_log.txt.old.txt
> > -a---         2024/2/11     19:13           2439 󰈙  aes_keys.txt
> > 
> > D:\3DS\user >ls -Filter *.3ds -Recurse
> > D:\3DS\user >
> > ```
> > I didn't find any 3ds files in my citra data directory..... I'm not sure if this right?
> 
> Where are the games stored?

I'm not sure, I just installed the cia file and the game became available....

**Comment by steve02081504** [comment]
```
E:\Citra\nightly\citra-qt.exe 'D:\3DS\user\sdmc\Nintendo 3DS\00000000000000000000000000000000\00000000000000000000000000000000\title\00040000\000f4e00\content\00000000.app'
```
this works! ty!
