### ISSUE TITLE
Localize loading logic improvement

### ISSUE THREAD

**Issue by steve02081504** [citra-emu/citra#7453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The existing Localize loading feature of citra uses English directly when there is no corresponding language: on my Traditional Chinese phone citra displays English, only when I set the system language to Simplified Chinese does it display Chinese
(By the way, my Android language list is set up so that Simplified Chinese is next to Traditional Chinese, and it looks like citra doesn't read the entire list but only the preferred language)
I think when it doesn't match `zh-TW` this could be improved by first iterating over any other possible `zh-*`, and then falling back to `en-US` if that doesn't find any.
It's like the following code retrieved from https://github.com/steve02081504/ps12exe/blob/89f6da0e46a248b5f8c8fa9bf1f68d132f148c52/src/LocaleLoader.ps1#L29L41:

```pwsh
&$LoadLocaleData $Localize
if (!(&$CheckLocaleData)) {
	$LocalizeList = Get-ChildItem $LocalizeDir | Where-Object { $_.Name -like '*.fbs' } | ForEach-Object { $_.BaseName }
	&$FaildLoadLocaleData $Localize
	$LocalizeHead = $Localize.Split('-')[0]
	$SimilarLocalize = $LocalizeList | Where-Object { $_.StartsWith($LocalizeHead) }
	foreach ($Localize in $SimilarLocalize) {
		&$LoadLocaleData $Localize
		if (&$CheckLocaleData) {
			break
		}
	}
	if (!(&$CheckLocaleData)) { &$LoadLocaleData 'en-UK' }
}
```

and It would be nice if citra had a language selection setting internally

### Why would this feature be useful?

idk

**Comment by FearlessTobi** [comment]
I sadly do not think this is possible on Android. Language selection is handled by the OS and not us.

However you should be able to set the language for Citra in your phone settings, if you are on Android 13 or above.
