### ISSUE TITLE
Super Monkey Ball 3D Menu Outline defects

### ISSUE THREAD

**Issue by JMC47** [citra-emu/citra#746]
Many of the menu objects in Super Monkey Ball 3D have a yellow outline texture around them to signify when they're selected.  This works fine on round objects, but on pretty much any rectangular object, there is a defect.

For example, let's see how the mode select looks on the 3DS.

![supermonkeyballboxes3ds](https://cloud.githubusercontent.com/assets/6598209/7558431/27b02b48-f772-11e4-9b12-29043fcd71e5.jpg)

Perfect.  Now, let's see how it looks on Citra.

![supermonkeyballboxescitra](https://cloud.githubusercontent.com/assets/6598209/7558432/2ec29c4a-f772-11e4-9aa4-65ddee2ed67c.jpg)

Definitely looks weird.  Other menu objects have similar defects to this one even when it's not overlapped by another menu object; so that's likely unrelated.

**Comment by JMC47** [comment]
CiTrace showing the defect.

https://dl.dropboxusercontent.com/u/484730/SuperMonkeyBall3DCiTrace.7z

**Comment by Subv** [comment]
This CiTrace currently crashes Citra due to unknown address conversions

**Comment by JMC47** [comment]
Fixed in this PR -> https://github.com/citra-emu/citra/pull/963

**Comment by yuriks** [comment]
This is reportedly fixed by #1002

**Comment by bunnei** [comment]
General note to @yuriks above comment, it's only fixed in the JIT, not in the interpreter. Another point of information: This manifested the same way in the JIT until I implemented the LOOP instruction. I have no dug into debugging this on the interpreter yet, but that suggests that it may be related to LOOP.

**Comment by JMC47** [comment]
Was this ever fixed in the interpreter?

**Comment by yuriks** [comment]
No idea, can someone retest? It might be related to the handling of nested loops, in which case I may have a fix soon.

**Comment by JMC47** [comment]
Seems fine to me.

**Comment by yuriks** [comment]
Could you do some quick bisecting to check when this was fixed? It would be good to know.
