### ISSUE TITLE
Super Monkey Ball 3D: Story Book Loses color before cutscenes + minor page corruption

### ISSUE THREAD

**Issue by JMC47** [citra-emu/citra#747]
The storybook which is normally red (even in Citra) seems to lose it's color during the final cutscene before gameplay starts.  On 3DS, it looks like this.

![supermonkeyballstorybookintro3ds](https://cloud.githubusercontent.com/assets/6598209/7558488/9bd132fa-f773-11e4-8229-783b89f6012a.jpg)

on Citra, it looks like this.  Note the weird corruption on one of the pages.

![supermonkeyballstorybookintrocitra](https://cloud.githubusercontent.com/assets/6598209/7558492/aaaecdc8-f773-11e4-9c0e-f2bfe21a0d45.jpg)

**Comment by Armonite** [comment]
The emulator is still in beta phase so it would take some time for it to render the games properly!

**Comment by yuriks** [comment]
@Armonite: Please stop making comments that don't contribute anything. I'll start deleting your posts from now on if you continue.

**Comment by Armonite** [comment]
okay!!!

**Comment by MoochMcGee** [comment]
1. More like pre-alpha
2. He knows that. He's just reporting bugs in games that work.

**Comment by yuriks** [comment]
Does this still happen? What about with #1023?

**Comment by yuriks** [comment]
Ping. Any change in master?

**Comment by JMC47** [comment]
No change.

**Comment by Subv** [comment]
Any change in master?

**Comment by JMC47** [comment]
This is still valid.

**Comment by Subv** [comment]
Could you try this with #1269 please?

**Comment by RHY3756547** [comment]
No change here.

**Comment by JMC47** [comment]
Fixed
