### ISSUE TITLE
Citra crashed whilst playing Tomodachi Life 

### ISSUE THREAD

**Issue by NikNikovsky** [citra-emu/citra#7473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

bed6a4f12

### Description of Issue

The entire emulator crashed

### Expected Behavior

It was supposed to play everything out as normal

### Reproduction Steps

I gave my Mii (NPCMALE1) a frying pan.

### Log File

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/sweet_eea/sweet:13/TKQ1.221013.002/V14.0.4.0.TKFEUOR:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2024-03-03 10:00:20.098828396+0100
Process uptime: 2532s
Cmdline: org.citra.citra_emu
pid: 27000, tid: 14355, name: GpuThread  >>> org.citra.citra_emu <<<
uid: 10540
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[   3.280234] Audio.Sink <Critical> audio_core/cubeb_sink.cpp:CubebSink:47: Error getting minimum latency'
    x0  0000000000000000  x1  0000000000003813  x2  0000000000000006  x3  00000072eef0f510
    x4  fefefefeff666d68  x5  fefefefeff666d68  x6  fefefefeff666d68  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  000000748383fcb0  x10 0000000000000001  x11 00000074838b47c8
    x12 0000000000000018  x13 0000000065e43c22  x14 003797b47e71bed7  x15 0000fd0219d3b6ce
    x16 000000748391fa80  x17 00000074838f8450  x18 00000072ee190000  x19 0000000000006978
    x20 0000000000003813  x21 00000000ffffffff  x22 00000072eef0f640  x23 ffffff80ffffffc8
    x24 0000007483922e50  x25 000000726b1d6b40  x26 0000000000000001  x27 fffffffde40600df
    x28 000000728309657b  x29 00000072eef0f590
    lr  00000074838a5748  sp  00000072eef0f4f0  pc  00000074838a5774  pst 0000000000000000
backtrace:
      #00 pc 000000000008d774  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 449f781894033dce6346794a1ee593e0)
      #01 pc 000000000004a11c  /system/lib64/libc++.so (abort_message+252) (BuildId: 1f426797e505c9b841f55cc49d32b3f4)
      #02 pc 000000000004a25c  /system/lib64/libc++.so (demangling_terminate_handler()+44) (BuildId: 1f426797e505c9b841f55cc49d32b3f4)
      #03 pc 0000000001302db8  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #04 pc 00000000013035f8  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #05 pc 000000000130359c  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #06 pc 0000000001302e80  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (__gxx_personality_v0+104) (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #07 pc 00000000000fd178  /apex/com.android.runtime/lib64/bionic/libc.so (_Unwind_RaiseException+144) (BuildId: 449f781894033dce6346794a1ee593e0)
      #08 pc 000000000004a4a8  /system/lib64/libc++.so (__cxa_throw+112) (BuildId: 1f426797e505c9b841f55cc49d32b3f4)
      #09 pc 00000000000a464c  /system/lib64/libc++.so (std::__1::__throw_system_error(int, char const*)+100) (BuildId: 1f426797e505c9b841f55cc49d32b3f4)
      #10 pc 0000000000014a2c  /system/lib64/libEGL.so (android::egl_cache_t::setBlob(void const*, long, void const*, long)+376) (BuildId: 7509d46ccf85f1a497dd943128791de4)
      #11 pc 0000000000214920  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!8b96d97b28460c2822a5897b3ff6e2!c5f0e23!+1376) (BuildId: cc1d6d65c20a3f224ef20b43fc02820a)
      #12 pc 00000000001407a0  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!5094ab766f406130e15d3aad524265!c5f0e23!+88) (BuildId: cc1d6d65c20a3f224ef20b43fc02820a)
      #13 pc 0000000000ff4b88  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (OpenGL::LoadProgram(bool, std::__ndk1::vector<unsigned int, std::__ndk1::allocator<unsigned int> > const&)+296) (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #14 pc 0000000000feb9d0  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (OpenGL::OGLProgram::Create(bool, std::__ndk1::vector<unsigned int, std::__ndk1::allocator<unsigned int> > const&)+72) (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #15 pc 0000000000fed9a8  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (OpenGL::ShaderProgramManager::ApplyTo(OpenGL::OpenGLState&)+500) (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #16 pc 0000000000fce5ac  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (OpenGL::RasterizerOpenGL::AccelerateDrawBatchInternal(bool)+312) (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #17 pc 0000000000fce010  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (OpenGL::RasterizerOpenGL::Draw(bool, bool)+3916) (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #18 pc 0000000001032d8c  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #19 pc 0000000001031c3c  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (Pica::CommandProcessor::ProcessCommandList(unsigned int, unsigned int)+268) (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #20 pc 00000000010126a4  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #21 pc 000000000101361c  /data/app/~~jHzmbD40lFyKlqB-I1cr_w==/org.citra.citra_emu-1BA0B_HYzapAHaD4-4kOQg==/split_config.arm64_v8a.apk!libmain.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (*)(VideoCore::RendererBase&, VideoCore::GPUThread::SynchState&, Core::System&), std::__ndk1::reference_wrapper<VideoCore::RendererBase>, std::__ndk1::reference_wrapper<VideoCore::GPUThread::SynchState>, std::__ndk1::reference_wrapper<Core::System> > >(void*)+48) (BuildId: 533a97b9eb6edb532611761be657229de94d8cb8)
      #22 pc 00000000000f55c8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 449f781894033dce6346794a1ee593e0)
      #23 pc 000000000008efbc  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 449f781894033dce6346794a1ee593e0)

### System Configuration

CPU: Qualcomm SM1750
GPU/Driver: Adreno 618 @ 800MHz
RAM: 6GB + 5GB w/ memory expansion
OS: Android 13

**Comment by stepsy** [comment]
The playstore version is outdated by three years.
Try nightly build.
https://github.com/citra-emu/citra-nightly/releases/tag/nightly-2103
Download the apk. Not the aab

**Comment by NikNikovsky** [comment]
Will it overwrite my already existing citra-emu folder and/or its contents?

**Comment by stepsy** [comment]
No, I don't think so.

**Comment by NikNikovsky** [comment]
It did not, but how do I get the keys required for the HOME menu to work without a 3DS?

**Comment by stepsy** [comment]
> It did not, but how do I get the keys required for the HOME menu to work without a 3DS?

You need a 3ds to get the keys. Anything else is piracy.

**Comment by NikNikovsky** [comment]
Welp, looking online it is.

**Comment by stepsy** [comment]
Is this fixed? If yes. Please close this issue.

**Comment by NikNikovsky** [comment]
yes, it got fixed.
