### ISSUE TITLE
TOTALLY UNRELATED but idk how to contact 

### ISSUE THREAD

**Issue by Emayeah** [citra-emu/citra#7477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

rip yuzu, you'll be missed, closing this as soon as I post it

### Why would this feature be useful?

o7, you had a good run...

**Comment by ExperiencersInternational** [comment]
Definitely will miss it, does anyone know whether Citra is affected since it seems to be very unclear?

I personally use Citra a lot more than Yuzu

**Comment by caimantilla** [comment]
> Definitely will miss it, does anyone know whether Citra is affected since it seems to be very unclear?
> 
> I personally use Citra a lot more than Yuzu

Things are looking grim.

![Screenshot 2024-03-04 at 14 43 10](https://github.com/citra-emu/citra/assets/103377610/c200cda7-2277-480f-89af-bce457c14eb6)

**Comment by ExperiencersInternational** [comment]
> > Definitely will miss it, does anyone know whether Citra is affected since it seems to be very unclear?
> > I personally use Citra a lot more than Yuzu
> 
> Things are looking grim.
> 
> ![Screenshot 2024-03-04 at 14 43 10](https://private-user-images.githubusercontent.com/103377610/309882750-c200cda7-2277-480f-89af-bce457c14eb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1ODI4NTYsIm5iZiI6MTcwOTU4MjU1NiwicGF0aCI6Ii8xMDMzNzc2MTAvMzA5ODgyNzUwLWMyMDBjZGE3LTIyNzctNDgwZi04OWFmLWJjZTQ1N2MxNGViNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQyMDAyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjUwMWM2ODY0YjI3YmExNjczMWZhM2RjOGU0N2M4NWYwZmU5ZTgyMzBiYmYyZTQ0Yzk1ZTFmOGNmZjgxYzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xl7kyU7b7G7jpJhhZy8mOAFUAflmOKwa4W6LCoxjeaM)

Thanks for the information and thanks Dani for asking that (doubt they'll see it but I love their work on Pretendo)

**Comment by ExperiencersInternational** [comment]
> > > Definitely will miss it, does anyone know whether Citra is affected since it seems to be very unclear?
> > > I personally use Citra a lot more than Yuzu
> > 
> > 
> > Things are looking grim.
> > ![Screenshot 2024-03-04 at 14 43 10](https://private-user-images.githubusercontent.com/103377610/309882750-c200cda7-2277-480f-89af-bce457c14eb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1ODI4NTYsIm5iZiI6MTcwOTU4MjU1NiwicGF0aCI6Ii8xMDMzNzc2MTAvMzA5ODgyNzUwLWMyMDBjZGE3LTIyNzctNDgwZi04OWFmLWJjZTQ1N2MxNGViNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQyMDAyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjUwMWM2ODY0YjI3YmExNjczMWZhM2RjOGU0N2M4NWYwZmU5ZTgyMzBiYmYyZTQ0Yzk1ZTFmOGNmZjgxYzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xl7kyU7b7G7jpJhhZy8mOAFUAflmOKwa4W6LCoxjeaM)
> 
> Thanks for the information and thanks Dani for asking that (doubt they'll see it but I love their work on Pretendo)

Not sure how long this issue thread will last but I've posted it onto fedi so people know that Citra could potentially be gone

**Comment by akatsukilevi** [comment]
Y'all, now's time to git clone before it's gone

**Comment by ExperiencersInternational** [comment]
> Y'all, now's time to git clone before it's gone

Didn't you say you were cloning Yuzu? Make sure to clone Citra too

**Comment by akatsukilevi** [comment]
> > Y'all, now's time to git clone before it's gone
> 
> Didn't you say you were cloning Yuzu? Make sure to clone Citra too

I already have a Yuzu clone at home, and now just cloned Citra as well(I'm at work and cloned into my laptop)
