### ISSUE TITLE
Transformers Prime : APT:GetAppCpuTimeLimit assert triggered

### ISSUE THREAD

**Issue by Lectem** [citra-emu/citra#771]
The game "Transformers Prime -The Game" (000400000007FE00) will trigger the assert https://github.com/citra-emu/citra/blob/master/src/core/hle/service/apt/apt.cpp#L272

**Comment by archshift** [comment]
This happens to various other games as well.

**Comment by purpasmart96** [comment]
Yeah, I'll fix it. since it was partially my fault, although it only seems to happen to 3rd party games at this point.

**Comment by purpasmart96** [comment]
Fixed

**Comment by archshift** [comment]
Fixed by #778.
