### ISSUE TITLE
Metal Gear Solid 3 heap address in a GPU command

### ISSUE THREAD

**Issue by JMC47** [citra-emu/citra#775]
Prior to Pull Request #734's merging, Metal Gear Solid 3 would load and hang on a Moflex video.

After this, The game segfaults after loading.  @pcmaker confirmed the regression as well.  It happens before the game displays any graphics whatsoever

This was bisected down to commit 28a9e4c1d55c66e99b5cf16fda00dcb75ab27fde

I'd try to get a stacktrace but for some reason Visual Studio won't attach a debugger to Citra like it does Dolphin, so I'm left here kind of useless.

**Comment by JMC47** [comment]
![giantcommandwindowhype](https://cloud.githubusercontent.com/assets/6598209/7642684/139da904-fa61-11e4-8998-418410a5d46d.png)

**Comment by Subv** [comment]
It's probably using a pointer returned by GetPointer before first checking if it's valid

**Comment by yuriks** [comment]
FWIW this will probably be fixed by properly implementing Shared Memory, so I'll tag this "unimplemented" for now.

**Comment by Armonite** [comment]
Well one would need to program it in a way that it fetches the physical addresses instead of the virtual ones where needed

**Comment by Armonite** [comment]
I'm also a programmer so if u guys need nay help do tell me

**Comment by MoochMcGee** [comment]
They don't. They really don't. People are already working on that.

**Comment by Subv** [comment]
I did some digging into this, turns out Metal Gear Solid is trying to execute a Display Transfer with VAddr 0x08084890 as the output address, however this VAddr is in the Heap, and the GPU can only be used with addresses in FCRAM or VRAM. The input address appears to be OK (FCRAM)
I wasn't able to trace where this address was coming from.

**Comment by Subv** [comment]
Returning RESULT_SUCCESS in RegisterInterruptRelayQueue instead of the current value makes it not queue the bogus display transfer and it actually boots! but that's a hack.
For some reason the game's allocator (That should be returning a valid FCRAM address), is returning an address in the heap.

**Comment by Subv** [comment]
OK, it appears that a _ton_ of games are using heap addresses for some GPU and GSP commands, thus causing errors in our Virtual <-> Physical address translation. I don't know why this happens.

**Comment by Subv** [comment]
After some more investigation, the GSP module simply sets invalid addresses to 0 when writing the GPU registers that start the display transfer, it is currently unknown what this means (Maybe the GPU ignores null addresses and just generates a PPF interrupt, maybe it uses the input address as output address)

**Comment by Leo626** [comment]
This issue is fixed with 49b1033 (#2103). May have also fixed #1763.

**Comment by wwylele** [comment]
#2103 is not an actual fix to this issue. It logs an critical error for this and bypasses it. I'll close this for now for it doesn't crash any more, but remember that we still have unknowns here. Feel free to reopen this or open a new issue if any graphical errors still occur.
