### ISSUE TITLE
Pokemon crashes the emulator

### ISSUE THREAD

**Issue by Armonite** [citra-emu/citra#777]
Hey people, I know its been stated on the website that Citra cannot emulate all the commercial games actually just not yet!
Yesterday I loaded Pokemon Alpha Sapphire rom and the emulator crashed so can you guys be working with pokemon roms so that at least we can play them at low FPS.
Thanking you people in advance!!

**Comment by archshift** [comment]
Wow, this is so helpful!

**Comment by Armonite** [comment]
so will u work on it?

**Comment by Zaneo** [comment]
I don't speak for the main contributors of the project. However the goal of the project is to make a working emulator, not one that only works for only one game. As such I do not believe anybody is currently working specifically making Pokemon work. There are much larger hurdles that need to be overcome first.

**Comment by neobrain** [comment]
@Armonite This is an issue tracker, not a request forum. Come back when you have an actual issue to report, including technical details and helpful debugging info. (no, we can't spend all of our time teaching people how to do this.)

**Comment by taisel** [comment]
It's happening! The random "pokemon pls" bug reports. I'm sure zeromus from desmume is rolling his eyes into the back of his head already upon seeing these start for citra now.
