### ISSUE TITLE
Could not read save data / corrupted data

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#784]
There is a problem with some games, specifically almost all of TEYON's games. They report a corrupted save on first boot, then delete it. From then on they report being unable to read save data.
Of note, logs for all game include:
```
<Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:75: unknown / unimplemented function 'GetFreeBytes': port=fs:USER, cmd_buff[1]=5, cmd_buff[2]=0
```
TEYON games list http://www.teyon.com/platform/3ds/

Example of some games + logs:
- 101 DinoPets 3D
- 101 Penguin Pets 3D - http://pastie.org/10192257
- 101 Pony Pets 3D 
- Bird Mania - http://pastie.org/10192270

![could not read the save data citra](https://cloud.githubusercontent.com/assets/11453507/7667384/ad590d7c-fc05-11e4-8cff-c2987cd89f6b.JPG)

**Comment by Subv** [comment]
Could you please test #1302 ?

**Comment by exhalatio** [comment]
I tested 101 Pony Pets 3D #1302, it seems fine.

**Comment by JohnGodgames** [comment]
It was fixed earlier... (forget to close)
