### ISSUE TITLE
Persona Q - Shadow of the Labyrinth Crashes at Intro / Ingame

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#786]
Game is crashing on the master or ogl at intro/ingame on the same point..I'm providing info from VS while debuging is pointing me to  src_color = Color::DecodeRGBA8(src_pixel);

LOG: http://pastie.org/10193292

![persona crash citra debug 2](https://cloud.githubusercontent.com/assets/11453507/7670701/3fa8e054-fcaf-11e4-9fd3-8bd6524b4688.JPG)

![persona crash citra debug](https://cloud.githubusercontent.com/assets/11453507/7670703/48024f88-fcaf-11e4-93a2-929a22c09ca7.JPG)

**Comment by ILOVEPIE** [comment]
can you tell me the exact number in config.input_format, if it's 6 then it may be due to unimplemented HILO8 support, in which case this could become a test case for HILO8 support.

**Comment by purpasmart96** [comment]
Control memory and other unimplemented FS stuff is likely the cause

**Comment by JohnGodgames** [comment]
already fixed...closed

**Comment by Subv** [comment]
Do you know what change fixed it?
