### ISSUE TITLE
Citra gl failed to initialize

### ISSUE THREAD

**Issue by RageShadey** [citra-emu/citra#788]
![help](https://cloud.githubusercontent.com/assets/12501211/7687513/dc126408-fd6b-11e4-80f7-32dc2556aca3.png)

So I really don't know what is wrong. I open citra but any rom i try to use gets me this error.

**Comment by archshift** [comment]
Your computer doesn't support the required version of OpenGL. Try downloading drivers, but if that doesn't work, you're out of luck. Sorry.
