### ISSUE TITLE
Won't get past loading screen without crashing

### ISSUE THREAD

**Issue by RageShadey** [citra-emu/citra#790]
Ok so this is my second post basically about the same thing. I don't know what is wrong. The only hint I had was the failure to initialize the gl functions but i used Glview utility and checked everything out myself and there was no issues. Can anyone help? It Citra is not running the rom or any of the starter roms without crashing before even starting. I assume there is something to do with it not being able to use the opengl but it is there.
![help](https://cloud.githubusercontent.com/assets/12501211/7695691/5bd02644-fdc1-11e4-8ebd-b872e2125939.png)

**Comment by yuriks** [comment]
It would eb hepful if you'd provide *any info at all* about your hardware and system.

**Comment by jroweboy** [comment]
Please understand that you are opening a second issue on the issue tracker after your first issue was closed without providing any additional information. archshift already mentioned that your graphics card doesn't support a high enough version of OpenGL to use citra right now, so if you wanted to make a new request, why not include at LEAST the version of OpenGL that your graphics card supports? Just because your card supports OpenGL doesn't mean it supports the version that citra uses. :)

**Comment by RageShadey** [comment]
Oh ok. Sorry I did not really know what kind of info to put. Yea any would have been helpful. 

![help2](https://cloud.githubusercontent.com/assets/12501211/7730988/79fa6b86-feeb-11e4-9a55-584c26f4f7a6.png)
![help3](https://cloud.githubusercontent.com/assets/12501211/7730989/79fddf46-feeb-11e4-8416-3215dcff814f.png)
![help4](https://cloud.githubusercontent.com/assets/12501211/7730990/7a04e67e-feeb-11e4-9fff-1f0d044d28c8.png)
![help5](https://cloud.githubusercontent.com/assets/12501211/7730991/7a09239c-feeb-11e4-9c14-6cbc01fa012b.png)

Thank you for any help.

**Comment by purpasmart96** [comment]
You could of just said you were using integrated graphics, But I guess that works too...

**Comment by RageShadey** [comment]
I apologize. I just wanted to be thorough.
I feel worst since I plan on going to college for computer science but most of my knowledge is extremely basic levels when it comes to programs. I know about hardware and web design.

**Comment by jroweboy** [comment]
@RageShadey just as suspected, you do not support OpenGL 3.2 (you only have OpenGL 3.1) which isn't enough to run citra right now. There is a PR in progress that may fix that https://github.com/citra-emu/citra/pull/732 but it may conflict with the upcoming hardware renderer, and that one has priority over lowering the GL version. So, yeah, you are out of luck right now, but it may change at some point in the future.

**Comment by RageShadey** [comment]
@jroweboy
Thank you. I will see about either getting a new laptop or the very unlikely possibility that I can upgrade the graphics card somehow.

**Comment by purpasmart96** [comment]
@RageShadey
Your laptop is fine for laptop, except the video card that is, I would suggest getting a desktop with a proper video card. instead of replacing your laptop.
