### ISSUE TITLE
need a bit of help 

### ISSUE THREAD

**Issue by blackdragonIV** [citra-emu/citra#791]
so i always get this when i attempt to boot a rom

![capture2](https://cloud.githubusercontent.com/assets/7633717/7713295/1f93fb54-fe77-11e4-892d-ede87c2c92ad.PNG)

my graphic card can support up to opengl 4.2 

i am attempting to boot a .3ds file is that what is wrong? do i need some conversion

**Comment by yuriks** [comment]
We do not endorse piracy.
