### ISSUE TITLE
looking for a master citra version

### ISSUE THREAD

**Issue by ravenhome** [citra-emu/citra#796]
i only made this account just for this question

after watching the emulator booting several games i found that there is an emulator version  where it have the top named master , while the nightly builds at the website have the title head , so is the master titled version runs game better i tried some homebrew games on the head version like 3ds craft but they all run very slowly as an apose to how fast Oot ran in this video

https://www.youtube.com/watch?v=Hj8sPsB5qXQ

also i have a couple of games i would like to dump to my pc to test games at better quality however after roaming the internet for guide all i can find was something known as gateway 3ds which i honestly know nothing about how to use it , also there is this video here which talks about converting files from cia to 3ds which i am not sure if it is something i must do

http://www.dailymotion.com/video/x2n74eb

can anyone help me with that my knowledge about emulation is very basic :/

**Comment by archshift** [comment]
`master`and `HEAD` are Git labels. You don't need tor worry about that on the nightly builds.

On our wiki in the sidebar, there is a page named Decryption. Use that to dump and decrypt your games.

**Comment by ravenhome** [comment]
ok thank you for the help
