### ISSUE TITLE
I test some games use the latest citra,and there are some logs and screenshots

### ISSUE THREAD

**Issue by mustfun** [citra-emu/citra#799]
I have tested three games:
1.cublic ninja
this game crash on the loading scene ,and the following is the screenshot
![qq 20150522213607](https://cloud.githubusercontent.com/assets/8612479/7773888/e127cf02-00d9-11e5-8163-512bf6d11bb7.jpg)

LOG: http://pastie.org/10202330

2.Maple story
this game crash on the scene where I want to create a character  name , you can see the following screenshot
![qq 20150522214428](https://cloud.githubusercontent.com/assets/8612479/7774081/4104c294-00db-11e5-8582-73e9806e551d.jpg)

LOG : http://pastie.org/10202364

3.Final Fantasy Explorers
this game is the same as above .this is the sceenshot
![qq 20150522215452](https://cloud.githubusercontent.com/assets/8612479/7774230/4dcab0e6-00dc-11e5-8a72-5da29c8e1384.jpg)

**Comment by archshift** [comment]
Thanks, but this isn't very helpful. First of all, please submit separate issues for each separate issue (with descriptive names and descriptions). Second of all, if they really crash Citra (hard crash, Citra closes), please get a stack trace.
