### ISSUE TITLE
Make the RasterizerOpenGL initialization lazy

### ISSUE THREAD

**Issue by linkmauve** [citra-emu/citra#807]
Currently, even when the software rasterizer is selected, RendererOpenGL::InitOpenGLObjects() will call RasterizerOpenGL::InitObjects(), which adds 8s to the startup time.

**Comment by tfarley** [comment]
The OpenGL renderer is only initialized when selected now - between that and the shader generator this shouldn't be a problem anymore.

**Comment by Zaneo** [comment]
@tfarley So this issue can be closed now?

**Comment by yuriks** [comment]
Fixed by #1272
