### ISSUE TITLE
Black textures for OoT

### ISSUE THREAD

**Issue by purpasmart96** [citra-emu/citra#808]
Related to https://github.com/citra-emu/citra/issues/775
Since Pull Request #734
OoT title screen looks like this
![title_screen](https://cloud.githubusercontent.com/assets/8182590/7786183/21ff4f0a-0170-11e5-9fae-7a8054ac2c32.PNG)
And Link looks like 
![link](https://cloud.githubusercontent.com/assets/8182590/7786187/5ec3ee6e-0170-11e5-96b8-7e597897fb6d.PNG)

**Comment by yuriks** [comment]
Fixed by #948
