### ISSUE TITLE
Failed to load ROM

### ISSUE THREAD

**Issue by cmexp** [citra-emu/citra#812]
On the latest nightly build of Citra, I get this error whenever I load a ROM:

[   4.685210] Frontend <Critical> citra_qt\main.cpp:GMainWindow::BootGame:211: Failed to load ROM!

Screenshot:

![clipboard02](https://cloud.githubusercontent.com/assets/6110397/7789358/bcf6afe2-022b-11e5-8b97-83523e72c512.jpg)

I tried Ocarina of Time 3D and Persona Q, two games I know are bootable in this emulator.

Specs are Intel core i7 5930K, GTX 980, Windows 8.1

**Comment by MoochMcGee** [comment]
Decrypt your games. This requires a real 3DS.
