### ISSUE TITLE
Multi-color Splotches in Donkey Kong Country Returns 3D

### ISSUE THREAD

**Issue by JMC47** [citra-emu/citra#813]
When playing the game, objects will be shaded really strange colors as they move around.  While some scenes look perfectly fine, it will become very apparent if you have the patience to actually get in-game that something is wrong.

![dkcr3d2](https://cloud.githubusercontent.com/assets/6598209/7789526/ac66b450-0231-11e5-82e5-190542a406da.png)

It takes about an hour and a half to get in game, so, no, I won't be doing this again until more optimizations are put in.

**Comment by purpasmart96** [comment]
Looks like save states would be really helpful.

**Comment by yuriks** [comment]
This is probably just the lack of texture filtering in the SW renderer.

**Comment by JMC47** [comment]
Here's a better image to show the weird coloring.

![dkcr3d](https://cloud.githubusercontent.com/assets/6598209/7790038/83871e40-0244-11e5-94da-37980b260898.png)

**Comment by Subv** [comment]
@JMC47 There have been a few changes that could impact this behavior, could you please verify if this is still a problem?

**Comment by JMC47** [comment]
Fixed at some point.
