### ISSUE TITLE
Hardware Renderer renders nothing in Donkey Kong Country Returns 3D

### ISSUE THREAD

**Issue by JMC47** [citra-emu/citra#814]
Simple enough: try to start up Donkey Kong Country Returns 3D in the Hardware Renderer or switch to it from SW Renderer and you will get a black screen.  Software renderer definitely renders stuff.  Proof below.

![dkcr3d](https://cloud.githubusercontent.com/assets/6598209/7789531/eba41950-0231-11e5-81fd-d7ebfbdea56b.png)

**Comment by neobrain** [comment]
Why was this closed?

**Comment by Syphurith** [comment]
835 is said to cover this issue and 829. I think that's enough expect someone "fixed in XXX".

**Comment by Subv** [comment]
This was closed by #835
