### ISSUE TITLE
OpenGL rasterizer’s fragment shader doesn’t compile on i965 on Sandy Bridge

### ISSUE THREAD

**Issue by linkmauve** [citra-emu/citra#819]
This bug is tracking the following Mesa bug: https://bugs.freedesktop.org/show_bug.cgi?id=90631

**Comment by linkmauve** [comment]
This is fixed in the next version of Mesa (see https://bugs.freedesktop.org/show_bug.cgi?id=86469#c16) and we are also dropping this mega-shader in PR #1187.

**Comment by yuriks** [comment]
We haven't merged #1187 yet, and most people don't have the updated mesa versions, so I think we should leave this unclosed for now.

**Comment by Subv** [comment]
#1187 has been merged
