### ISSUE TITLE
Crashed games on unmapped Read32 / inst_buf is full

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#824]
```
[ 0.000000] Core.ARM11 core\arm\dyncom\arm_dyncom_interpreter.cpp:AllocBuffer:1176: inst_buf is full
```
or
```
HW.Memory core\memory.cpp:Memory::Read:105: unmapped Read32
```

Some games which have the same problem + logs:

Crash Time 3D - http://pastie.org/10208961 
Girls Fashion 3D: Mezase! Top Stylist (JP) - http://pastie.org/10208969
Gundam the 3D Battle
Hamatora: Look at the Smoking World
NASCAR Unleashed
Shifting World - http://pastie.org/10208973

**Comment by yuriks** [comment]
Does the first problem go away if you change this line (shortly above the line indicated in the assert)
```
#define CACHE_BUFFER_SIZE    (64 * 1024 * 2000)
```
and increase it to `128 * 1024 * 2000`, for example?

**Comment by JohnGodgames** [comment]
increasing to (128 * 1024 * 2000) or (128 * 2024 * 4000) = without change

**Comment by yuriks** [comment]
@lioncash might want to take a look at this then

**Comment by lioncash** [comment]
Is this still an issue?

**Comment by yuriks** [comment]
No code changes were made concerning this, so I assume so.

**Comment by JohnGodgames** [comment]
Caused by bad decryption on my side...
