### ISSUE TITLE
Hardware renderer bugs - Black screens & similar issues

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#829]
It would be good that everyone knows about these problems.If I or someone else as @JMC47 will find more bugs there will be a place for them.

Update:
#### Games fixed by https://github.com/citra-emu/citra/pull/835
CRUSH 3D
Farming Simulator 14
Labyrinth no Kanata
Castle Clout 3D
Robot Rescue
Tales of the World - Reve Unitia

#### Games fixed by https://github.com/citra-emu/citra/pull/1023
Planet Crashers

# Games not fixed yet:

#### Monster 4x4 3D:
SW
![monster 4x4 sw](https://cloud.githubusercontent.com/assets/11453507/7871567/009f3f12-0591-11e5-8e5c-5d65aec7057d.PNG)

HW
![monster 4x4 hw](https://cloud.githubusercontent.com/assets/11453507/7871568/044fc41a-0591-11e5-8053-aafe14295071.PNG)

#### Rise of the Guardians:
SW
![rise of the guardians sw](https://cloud.githubusercontent.com/assets/11453507/7871602/38f3ff92-0591-11e5-9afc-76ac0179b00d.PNG)

HW
![rise of the guardians hw](https://cloud.githubusercontent.com/assets/11453507/7871604/3ca1aa18-0591-11e5-9b9e-f25ed082b63d.PNG)

#### Turbo - Super Stunt Squad:
SW
![turbo sw](https://cloud.githubusercontent.com/assets/11453507/7871615/4e49dfa6-0591-11e5-8aef-ce2e670edf54.PNG)

HW
![barbie hw](https://cloud.githubusercontent.com/assets/11453507/7871673/b527b716-0591-11e5-924b-79c9d8041e46.PNG)

#### Madagascar 3:
SW
![madagascar 3 sw](https://cloud.githubusercontent.com/assets/11453507/7900607/91656b48-0762-11e5-8c5e-b3257fbd6946.PNG)

HW
![madagascar 3 hw](https://cloud.githubusercontent.com/assets/11453507/7900608/97678bf2-0762-11e5-9f65-476cd6e32c50.PNG)

**Comment by RHY3756547** [comment]
I dunno, I think I prefer the barbie game on HW.

**Comment by JMC47** [comment]
Can confirm more games.  

New Super Mario Bros. 2 - No graphics on HW Renderer
Donkey Kong Country Returns 3D - No Graphics  on HW Renderer
Super Crush 3D - No Graphics on HW Renderer
Ace Combat: Assault Horizon Legacy - No graphics on HW Renderer

The rasterizer stays at 0 on all of these games.

**Comment by yuriks** [comment]
Can people recheck all these games on current master, #996 and #1023 and report if any are fixed, and by which PR?

**Comment by JohnGodgames** [comment]
Tested planet crashers and it was fixed by OpenGL Fix state tracking in situations with reused object handles #1023

**Comment by yuriks** [comment]
@JohnGodgames Can you file a separate issue for the Barbie glitchy meshes? I think there are a few other instances of that issue scattered around the tracker too, so maybe just merge it with one of those.
