### ISSUE TITLE
Games that use ldr:ro hang, expecting CROs to be loaded

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#834]
Aqua Moto Racing 3D - [LOG](http://pasted.co/6651e72f)

Inazuma Eleven 3 - Bomb Blast [LOG](http://pasted.co/0e7dbd34)

Inazuma Eleven 3 - Team Ogre Attacks [LOG](http://pasted.co/e6527a48)

Inazuma Eleven 3 - Lightning Bolt [LOG](http://pasted.co/59e3ea1d)

Mario & Luigi Dream Team LOG - http://pastie.org/10215191

Snoopy's Grand Adventure [LOG](http://pastebin.com/RPe1jiNT)

Super Smash Bros. - [LOG](http://pasted.co/aad99613)

**Comment by Subv** [comment]
Nope, it's trying to load a CRO, I'm working on it, but don't expect a patch anytime soon

**Comment by JohnGodgames** [comment]
Ok good to know.

**Comment by HecterL** [comment]
@Subv hows the patch coming along?

**Comment by JohnGodgames** [comment]
Mario & Luigi Dream Team loads https://www.youtube.com/watch?v=oB8NUZy5wLQ

**Comment by JohnGodgames** [comment]
@Subv ok I missed that one...so I added Snoopy's Grand Adventure to the list
`unknown / unimplemented function 'LoadExeCRO_New?': port=ldr:ro,`

**Comment by JasonSome** [comment]
This issue is too old...

**Comment by mailwl** [comment]
add YouTube, too

**Comment by JohnGodgames** [comment]
Added Super Smash Bros. (full game uses that too)

**Comment by Leo626** [comment]
CRO implementation has been merged. This needs to be closed now.

**Comment by JayFoxRox** [comment]
Sounds reasonable. Closed.
Please create new, seperate issues if the problem persists.
