### ISSUE TITLE
Hardware renderer bugs - games that have a texture cache flushing issues

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#837]
#### BlazBlue Continuum Shift II:
SW
![blaze sw](https://cloud.githubusercontent.com/assets/11453507/7871443/338328c2-0590-11e5-9f6d-6cf6952627a6.PNG)

HW
![blaze hw](https://cloud.githubusercontent.com/assets/11453507/7871448/38e96a88-0590-11e5-904f-fc271c645efc.PNG)

#### Medarot 7 - Kabuto Ver.
![meda 7 hw](https://cloud.githubusercontent.com/assets/11453507/7900771/a7cd9854-0769-11e5-83b1-a733b1a60bb4.PNG)

#### Medarot 8 - Kabuto Ver.
HW:
![meda hw](https://cloud.githubusercontent.com/assets/11453507/7900772/bca0bdce-0769-11e5-9875-e9a4890c8878.PNG)

SW:
![meda sw](https://cloud.githubusercontent.com/assets/11453507/7900773/c1f6b1ac-0769-11e5-8bc0-d30cba4dab54.PNG)

![meda 1 hw](https://cloud.githubusercontent.com/assets/11453507/7900775/d1bef40a-0769-11e5-9a71-28fc850f35ab.PNG)

#### MapleStory - The Girls Fate:
SW
![maple story sw](https://cloud.githubusercontent.com/assets/11453507/7871539/c9796c88-0590-11e5-87f5-e40670626bd6.PNG)

HW
![maple story hw](https://cloud.githubusercontent.com/assets/11453507/7871542/cfcc3aa2-0590-11e5-9e6a-70a7c5f80101.PNG)

**Comment by Subv** [comment]
Lets add Castle Conqueror to the list, the first title screen is displayed twice (instead of displaying the second title screen)

**Comment by asbel123** [comment]
because 3ds using software for 3d graphics doesnt use lot of gpu and new 3ds using cpu improvement  i tried tales of the abyss real 3ds its slow alot in the game beacuse gpu is so weak look at this websites talk about 3ds gpu compare to ps vita i got the website link is kyokojap.myweb.hinet.net/gpu_gflops/ thats why wii powerful than 3ds look at gpu flops. dont forget 3ds using differnet graphics than ps2.

thats why emulator is so hard.

**Comment by yuriks** [comment]
Can you check if #1023 fixes any of these games?

**Comment by yuriks** [comment]
Ping. Any change on these?

**Comment by JohnGodgames** [comment]
Problem still persist.

**Comment by tfarley** [comment]
Can you do a preliminary test with #1436 to see if these are fixed?

**Comment by JohnGodgames** [comment]
Fixed with #1436
