### ISSUE TITLE
MH4U: Unsupported thread processor ID

### ISSUE THREAD

**Issue by mhvuze** [citra-emu/citra#840]
Only experienced this in Monster Hunter 4 Ultimate and the demo version of the game so far, outright crashes Citra. If you let me know how I can provide more info, I'll gladly do so.

Here's the log: http://pastie.org/10216479

**Comment by Subv** [comment]
This happens because MH4U believes that Citra is a New Nintendo 3DS. This can be fixed by stubbing the APT command 0x01010000

**Comment by ignika98** [comment]
Is that something we can fix ourselves when compiling, or does it need to be done by you guys?

**Comment by yuriks** [comment]
It's fixable if you know programming, but it's not trivial. You need to add the missing function as indicated by @Subv.

**Comment by ignika98** [comment]
Oh, well I guess I'll just have to wait then.

**Comment by Zaneo** [comment]
@ignika98 If you get a chance could you try this? [Zaneo/citra/tree/apt_ptm_checknew3ds](https://github.com/Zaneo/citra/tree/apt_ptm_checknew3ds)

**Comment by ignika98** [comment]
![capture](https://cloud.githubusercontent.com/assets/2106615/8667687/b3de7f22-2a3d-11e5-9ba2-b20e3a794a6c.JPG)
It still doesn't work, but I get a different error this time. Unless I did something wrong...

**Comment by yuriks** [comment]
Apparently it's still not quite working, since it's trying to create a thread for one of the n3DS's new CPU cores.

**Comment by yuriks** [comment]
Hm, looking again at the screenshot, it doesn't look like the patch worked correctly, since it's giving unknown function error.

**Comment by ignika98** [comment]
Guess I'll just have to wait again then...

**Comment by yuriks** [comment]
Should be a matter of copying this line: https://github.com/Zaneo/citra/commit/982687f70d97a07b861b8b844c20ec4591c15fe6#diff-1534728c6bee9cbcd50cbf1ba054ab63R94
and also adding it to the table in apt_a.cpp

**Comment by ignika98** [comment]
Hmmmm, doing that gives me build errors, but I'm probably doing it wrong. How and where exactly would it be copied?

**Comment by mhvuze** [comment]
Citra still crashes but I guess that's not related to the CPU anymore, huh?
![4e2c64e225](https://cloud.githubusercontent.com/assets/4907001/8668815/45480642-2a0f-11e5-97b6-0c48d4ecea96.png)

**Comment by ignika98** [comment]
Never mind, I messed up. I cloned the wrong repo. But yeah, I get the same error as mhvuze now...
![citra](https://cloud.githubusercontent.com/assets/2106615/8669225/b876937a-2a4d-11e5-80fa-bf072dd7efb7.JPG)

**Comment by Subv** [comment]
That appears to be the same problem as #775

**Comment by yuriks** [comment]
I'm not sure if it's actually the same issue. The screenshot shows that a *virtual* linear heap address (0x14000000 onwards) is being passed to *Physical*ToVirtualAddress.

@ignika98 I'd be very interested if you could place a breakpoint on the line with that log and get a stack trace to see where it's being called from.

**Comment by mhvuze** [comment]
Like this?
![unbenannt](https://cloud.githubusercontent.com/assets/4907001/8682242/29334748-2a6c-11e5-889c-5890ea12cb4b.png)

**Comment by yuriks** [comment]
Indeed. Thanks

**Comment by internetakias** [comment]
Getting this error with New Love Plus +
![error](https://cloud.githubusercontent.com/assets/5077063/13449874/0e6769b2-e038-11e5-94ed-7f10d6896c1d.PNG)

**Comment by mailwl** [comment]
@internetakias , #1434 should help

**Comment by JamePeng** [comment]
#1520 maybe it could help to solve the 0x01010000(CheckNew3DS)

**Comment by Andrix44** [comment]
It doesn't crash anymore, but it needs geometry shaders (0x2a and 0x2b).

**Comment by JayFoxRox** [comment]
Sounds okay to me, we'll reopen if this is still a problem. Closed.
