### ISSUE TITLE
Zoo Resort 3D - Loading loop bug

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#846]
Loading loop when I want to go to the Animal Bond.This bug was caused by thread priority.So look at it @bunnei

![resort loading](https://cloud.githubusercontent.com/assets/11453507/7941647/025790c2-0959-11e5-86e3-522a8f0b02a2.PNG)

LOG - http://pastie.org/10219617

**Comment by Subv** [comment]
Does this still happen? a lot of things were fixed by recent and not-so-recent changes to our scheduling behavior

**Comment by JohnGodgames** [comment]
Still...unfortunately

**Comment by Subv** [comment]
Any changes?

**Comment by JohnGodgames** [comment]
nope...

**Comment by Subv** [comment]
#1302 ?

**Comment by JohnGodgames** [comment]
https://github.com/citra-emu/citra/pull/1302 nope...

**Comment by JohnGodgames** [comment]
Partially fixed by https://github.com/citra-emu/citra/pull/1374

**Comment by yuriks** [comment]
For what definition of "partially"? :)

**Comment by JohnGodgames** [comment]
I can go to the Animal Bond, but not to ingame (it hangs)

**Comment by JayFoxRox** [comment]
I'll consider this fixed / closed because Zoo Resort 3D is already part of meta issue https://github.com/citra-emu/citra/issues/1583 and the original "Loading loop" bug is not present anymore.
