### ISSUE TITLE
using hardware render mode break the game 

### ISSUE THREAD

**Issue by ravenhome** [citra-emu/citra#847]
the game goes completely black when switching to hardware render switching back to normal render while emulation is in progress brings the game back. i am running Oot

![console](https://cloud.githubusercontent.com/assets/12551178/7941699/4902076e-0959-11e5-9f8a-592cfa0fdd78.PNG)

![emulator](https://cloud.githubusercontent.com/assets/12551178/7941702/4d9b3a0c-0959-11e5-8f01-14f83fb6b9a6.PNG)

**Comment by purpasmart96** [comment]
This because you are using integrated graphics

**Comment by Subv** [comment]
@purpasmart96 I use citra with my CPU's integrated graphics chip without any problems. I have an HD 4600 IGP

**Comment by ravenhome** [comment]
i have the readon A10 series which features the readon hd 7660G it is not a bad gpu not a beast by any means and yes integrated card but it should be fine with citra it is a descent power gpu

**Comment by yuriks** [comment]
This is a deficiency in our HW rendering shader which causes it to break easily on various GPU drivers. It should be resolved eventually.

**Comment by ravenhome** [comment]
all right will be waiting for a new update to test :)
