### ISSUE TITLE
Static Analysis

### ISSUE THREAD

**Issue by ElfoLiNk** [citra-emu/citra#850]
I have run a static analysis on the master branch with last commit b1cb0a3f2.

The analysis was executed on Windows 8.1 x64 Build

General + Optimization Analysis: https://drive.google.com/file/d/0B296LD22NB3lQlM0VjljVWpkZ2s/view?usp=sharing

64-bit Analysis: https://drive.google.com/file/d/0B296LD22NB3ld00zN1AzbTBMTmc/view?usp=sharing

**Comment by mailwl** [comment]
Sorry, I don't know, how to report about bug in source code (and i dont' know, if it bug itself), so ask here, I think static analysis shold find this thing.
So, in file hw.cpp
https://github.com/citra-emu/citra/blob/master/src/core/hw/hw.cpp#L21
https://github.com/citra-emu/citra/blob/master/src/core/hw/hw.cpp#L35
both LCD::Write in Read and Write

**Comment by mailwl** [comment]
Another one:
https://github.com/citra-emu/citra/blob/master/src/citra_qt/debugger/callstack.cpp#L38
constant 0x10000000 valid only on main thread, right value should be
`Kernel::GetCurrentThread()->stack_top` ?

What is right way to post about such errors in source code?

**Comment by lioncash** [comment]
tell someone in the IRC or make a new issue.

**Comment by mailwl** [comment]
BTW, i check the code with PVS Studio, just one critical message:
https://github.com/citra-emu/citra/blob/master/src/common/synchronized_wrapper.h#L57 (no return result).
And alot of warnings, mostly from Qt, don't look at this yet

**Comment by neobrain** [comment]
CC @yuriks ^

**Comment by JayFoxRox** [comment]
I'll close this because most results are probably outdated by now.

We should probably re-run a static analyzer again but unless someone actually fixes the problem aftwards there is no point in doing it?
If anybody wants to do it just create a new issue for a discussion or PR.
