### ISSUE TITLE
majoras mask on loop

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#852]
so i saw that no one tried their hands on majoras mask 3D so i decided to give it a try and here is the result

so basically it starts at loading thing 

![majoras](https://cloud.githubusercontent.com/assets/12820322/8069879/c07e4dbc-0efd-11e5-9038-b34b360c03b8.PNG)

with this at the console

http://pastebin.com/kaApxK8J

after the small logo on the lower right goes away the console is stuck on a loop with this 

![console 3](https://cloud.githubusercontent.com/assets/12820322/8069987/73af020a-0efe-11e5-92f2-f373d83bcdb8.PNG)

this was tested with normal render not HW render because as i mentioned here https://github.com/citra-emu/citra/issues/847 the HW breaks the emulation for me

**Comment by bunnei** [comment]
Majora's Mask 3D works fine in latest master, I just tested to confirm! I suspect that you may have a bad dump (FWIW, there have been other users who've had the said bad dump fail at this point).

**Comment by Subv** [comment]
This doesn't seem like a bad dump, it just seems like the sw renderer is missing the combiner op 7

**Comment by MoochMcGee** [comment]
i think that's either dot3rgb, or dot3rgba

**Comment by RavenHome1** [comment]
@bunnei yes i honestly noticed that the build provided at the official website are very different from the ones you the devs are using , also i just tried the newest nightly build and it is still broken and majoras mask still wont boot

**Comment by Subv** [comment]
@RavenHome1 It does boot, it will just take a huge amount of time due to the error spam.

**Comment by RavenHome1** [comment]
@Subv yeah it dose boot but wow it takes so long it is not even worth the trouble, hopefully the issue with hardware render will be fixed soon so i can try it with HW
