### ISSUE TITLE
Labyrinth no Kanata, Unknown color combiner operation 6

### ISSUE THREAD

**Issue by polaris-** [citra-emu/citra#858]
At the very beginning once you load the ROM it spams this error message:
`[ 195.242167] HW.GPU <Error> video_core\rasterizer.cpp:Pica::Rasterizer::Process
TriangleInternal::<lambda_fd7885aff43fd2e4d041e9e368ff77a6>::operator ():561: Unknown color combiner operation 6`

The game eventually goes gets past it after a few minutes. It only seems to happen on the screens that should be black. The opening starts black and then goes into the splash screens, and then it goes black again where it then tries to initialize the save data.

Edit: For reference, this is with the latest nightly.

**Comment by OatmealDome** [comment]
Color combiner operation 6 is DOT3_RGB. PR #767 adds this missing operation.

**Comment by archshift** [comment]
Fixed by #767.
