### ISSUE TITLE
ffmpeg fails to decode a video correctly - Wrong ARMv6 emulation ?

### ISSUE THREAD

**Issue by Lectem** [citra-emu/citra#862]
I'm writing some H264/mpeg4 player, and the video decoding works fine on HW (see https://youtu.be/x1-xWt-xyAc ).
However on Citra it seems that the frames arent decoded correctly. I can sometimes see the after effect of motions, but it's as if the decoded frames were transparent (hence the green screen).
Here is a screenshot : 

![Image of decoding problem](http://lectem.fr/dl/citra-ffmpeg-problem.png)

You can download the .3dsx here [3Damnesic.zip](https://github.com/Lectem/3Damnesic/releases/download/alpha/3Damnesic.zip).
It will try to read the file test.mp4 at the root of your sdmc.
test.mp4 has to be a mpeg4 video 400*240 (do not use another resolution).

FFmpeg uses some ARMV6 asm code to optimize the decoding process, my guess is that the problem comes from this. Also note that it is NOT using y2r. It's all software based (might use some vfp though).

Source is available at https://github.com/Lectem/3Damnesic/

Edit: this post used to say h.264, but only mpeg4 caused the issue.

**Comment by Subv** [comment]
There were some fixes to the dyncom lately, @Lectem could you check if this is still a problem please? I don't have any 400 * 240 h264 video handy

**Comment by Lectem** [comment]
@Subv Same problem

**Comment by aroulin** [comment]
Can you check again ? A short video worked for me (although slow).

**Comment by Lectem** [comment]
@aroulin I wont be able to verify it soon, I have to reinstall qt and don't have a proper connection. Are you sure your video is mpeg4 and not h264?

**Comment by aroulin** [comment]
@Lectem Sorry, I did not know there was a difference. Pardon my limited knowledge of video codecs :)
I have been able to reproduce the issue, I'll try to look into it, thanks.

**Comment by Subv** [comment]
Can you try with mfloat-abi=soft? It's probably the same issue as #1218

**Comment by Lectem** [comment]
I managed to disable VFP usage and to use mfloat-abi=soft with devkitARM somehow, still the same issue.

**Comment by linkmauve** [comment]
I just reproduced using VP8 instead, I can discern the video’s features, but unlike on the 3DS there are green blocks, magenta blocks, striped blocks, and a cyan frame every few frames.

**Comment by Lectem** [comment]
Works fine thanks to #1814 !
