### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#865]
i admit, i had fun watching this, the game is Pokemon omega ruby  >;-)

so it is basically on a loop with a color show

![pokz2](https://cloud.githubusercontent.com/assets/12820322/8191569/1abff8dc-1469-11e5-88f0-deafc2e44118.PNG)

i think it will be fixed when https://github.com/citra-emu/citra/pull/849 is implemented or maybe it will not, not an expert at such things XD.

**Comment by archshift** [comment]
Thanks for reporting this, but this log doesn't give us almost any information besides the fact that it doesn't work (which we already knew).

**Comment by Alpibrine28** [comment]
So...  There is absolutely no way to emulate Pokemon ORAS?

**Comment by archshift** [comment]
Currently, no, there's absolutely no way.
