### ISSUE TITLE
Make the input-related members of Settings::Values less painful to use

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#870]
Currently, https://github.com/citra-emu/citra/blob/master/src/core/settings.h stores the key id mapped to each 3DS button/stick/.. control separately in its own variable, so we end up with different variables like `pad_a_key`, `pad_b_key`, etc. This is highly impractical because in various places we'd like to just iterate over all buttons, which currently requires duplicating the same code for each button input.

Instead, we should store all those inputs in a single array (`int input_mappings[NativeInput::NUM_INPUTS]`) and provide a single enum, e.g.

```
enum class NativeInput { A = 0, B = 1, /*...*/ };
```

to use for indexing that array. Possibly we could just re-use the enum in `Service::HID` for this purpose.

**Comment by Subv** [comment]
This was resolved with the input system rewrite.
