### ISSUE TITLE
Someone can help me?

### ISSUE THREAD

**Issue by Banido** [citra-emu/citra#872]
![image](https://cloud.githubusercontent.com/assets/12973543/8265376/0e27012a-16cf-11e5-992d-571c731e8fb3.png)
How can i fix this?

**Comment by jroweboy** [comment]
Just so you are aware, this issue tracker is not a user help forum. Please use this space only for reporting actual bugs in Citra and not for asking for help.

That aside, I would start by downloading the latest version of citra and trying to see if that works. The error message in the picture says that its looking for your config files in a location that does not exist so it fails to load the config files. Its looking for a folder at "C:\Users\Lucas\Desktop\3ds/user/config" which doesn't seem to exist.

**Comment by jroweboy** [comment]
It turns out, that those messages are harmless. Just load the game by selecting the File menu and Load File

**Comment by Banido** [comment]
Don't work, so many errors, "file not found" and in final appears only" Failed to load ROM"

**Comment by Banido** [comment]
Sorry for my english haha
but i think that you can understand.

**Comment by Banido** [comment]
![image](https://cloud.githubusercontent.com/assets/12973543/8265801/7371fe2e-16e1-11e5-98b7-42a56f53c7e5.png)

**Comment by Banido** [comment]
![image](https://cloud.githubusercontent.com/assets/12973543/8265805/8ab4104a-16e1-11e5-9e70-8460a3d0896d.png)

**Comment by archshift** [comment]
Please don't come to us with problems which stem from your attempt at using pirated games in Citra.
