### ISSUE TITLE
Audit usage of `bool` in command buffers

### ISSUE THREAD

**Issue by yuriks** [citra-emu/citra#874]
@Lectem discovered an interesting pitfall when reading `bool`-type values from service command buffers: Nintendo's implementations use the `ldrb`/`strb` instruction for reading/writing bool values, leaving the 3 unused bytes unchanged. In contrast we usually just read the entire u32 and cast it to bool. This means that if the three unused bytes have non-zero values the field will be incorrectly interpreted as `true`. This was causing spurious failures when using the Y2R service.

We should audit all of our service handling code to ensure we aren't making this mistake anywhere.

**Comment by Subv** [comment]
Here's how i did it for the AM::TitleIDListGetTotal function https://github.com/citra-emu/citra/blob/master/src/core/hle/service/am_sys.cpp#L23

**Comment by mailwl** [comment]
short values often contains garbage in hiword, too

**Comment by yuriks** [comment]
@mailwl Those aren't as much of a problem since they're usually truncated to a `u16`. Doesn't hurt to watch out for those too, though, true.

**Comment by B3n30** [comment]
looking at our ipc helpers we do that there properly. Since we  use ipc helpers now everywhere I think this can be closed...

(If I missed something feel free to reopen it again)
