### ISSUE TITLE
Final Fantasy Explorers: Deleted Save data

### ISSUE THREAD

**Issue by exhalatio** [citra-emu/citra#875]
I tried to load the save data that dump from cartridge.
They report a Delete save on first boot, then delete it. 
From then on they report being unable to read save data.
<pre><code>Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:75: unknown / unimplemented function 'GetFormatInfo': port=fs:USER, c
md_buff[1]=4, cmd_buff[2]=1, cmd_buff[3]=1, cmd_buff[4]=16386, cmd_buff[5]=26843
1000</code></pre>
Here's the log: http://pastie.org/10251202
Here's the savedata: http://www.filedropper.com/ffexsave

**Comment by Subv** [comment]
Could you please test #1302 ?

**Comment by exhalatio** [comment]
@Subv #1302 works fine. Great job.

**Comment by Subv** [comment]
The PR hasn't been merged yet
