### ISSUE TITLE
Bravely Second issues

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#879]
Please, leave this issue open, i start to dig the game, and will post here summary of investigation.

1) The game uses SaveDataCheck archive id, so, to go further, we have to use https://github.com/citra-emu/3dsutils . Easy enough.
2) After some "Unimplemented functions" errors, the game throws null poiner exception at
https://github.com/citra-emu/citra/blob/master/src/video_core/command_processor.cpp#L157
[  70.763047] HW.Memory <Error> core\memory.cpp:Memory::GetPointer:150: unknown GetPointer @ 0x940068d5

will dig further...

**Comment by Subv** [comment]
0x940068D5 looks like an invalid address returned from PhysicalToVirtual (or VirtualToPhysical), it even has 0x80000000 set (This is our "Invalid address translation" flag).
Most likely this is the same issue as #775

**Comment by mailwl** [comment]
@Subv, thanks, that's now I see it.
Ok
https://github.com/citra-emu/citra/blob/master/src/core/hle/service/gsp_gpu.cpp#L399

game checks if `params.start2` in VRam if only value is not 0, so, 0 is not real address, and in this case no need to convert with `VirtualToPhysicalAddress` to `start2` and `end2` (maybe ignore at all?)

**Comment by mailwl** [comment]
ok. got it starting (a kind of). Next stop is: 
Service.CFG <Error> core/hle/service/cfg/cfg.cpp:GetConfigInfoBlock:197: Config block 0xD0000 with flags 2 and size 4 was not found (Fatal Error)
![bs](https://cloud.githubusercontent.com/assets/629437/8331463/2ffaba9c-1a91-11e5-8002-c61df599ecfb.png)

**Comment by Subv** [comment]
@mailwl You need to place the config savefile from the CFG service in the proper folder

**Comment by mailwl** [comment]
I create entry by hand (just a hack). Now it looks like the game want to update firmware of emulator :)

**Comment by Subv** [comment]
What do you mean?

**Comment by mailwl** [comment]
it is trying to use such unimplemented functions from APT:A (description from 3dbrew):
0x0009....	1.0.0-0 - 2.0.0-2	Gamecard system update related.
0x000A....	1.0.0-0 - 2.0.0-2	Gamecard system update related.

@Subv , can you explain me, why in debug mode some games show pictures, and at release - NO, just unexpected exception and close emulator?

but my Windows notebook (which i prefer mac mini) in debug lags like a crasy, something like 1 frame per minute, hard to wait until the game actually start.

**Comment by archshift** [comment]
If the game is trying to use those commands, it may be because Citra is reporting too low of a firmware version. Try updating it [here](https://github.com/citra-emu/citra/blob/master/src/core/hle/config_mem.cpp#L33-L36).

**Comment by mailwl** [comment]
@archshift, thanks! the game requires 2.46, i think, the best way to change the version from game header.
one step ahead!
Now game almost start, even want to show intro fight, but then picture just broken - blink image from lower screen on top screen, lower screen is black
![bs1](https://cloud.githubusercontent.com/assets/629437/8339448/262c6720-1ac0-11e5-80a7-1ef9016fdc55.png)

**Comment by Subv** [comment]
@mailwl 
```quote
@Subv , can you explain me, why in debug mode some games show pictures, and at release - NO, just unexpected exception and close emulator?
```

I'm not sure what you mean by this.

**Comment by mailwl** [comment]
Now game shows good picture in intro fight, but then it goes to gameplay, i've got unimplemented GL error. BTW, what this numbers mean? seconds?
I give up :( too hard to me.

![bs2](https://cloud.githubusercontent.com/assets/629437/8360446/6b881afc-1b75-11e5-93c4-342f95660d5f.png)

**Comment by Subv** [comment]
Milliseconds, you're running at 0.05fps.

What errors are you getting?

**Comment by mailwl** [comment]
@Subv 
https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/pica_to_gl.h#L36
gl_mode = 1

**Comment by mailwl** [comment]
i commit the changes to my branch, most important part is in function on L367 (all info from 3dbrew!), there is many random changes too, but they for easy debugging in common, i don't know, which does matter
https://github.com/mailwl/citra/blob/branch-mailwl/src/core/hle/svc.cpp#L367
after this change  i saw the main menu of BS:EL

**Comment by purpasmart96** [comment]
The missing clamp mode is most likely "GL_CLAMP_TO_BORDER" although this is just speculation.

**Comment by mailwl** [comment]
@purpasmart96, Looks like true, at least picture is good with this value
![bsel](https://cloud.githubusercontent.com/assets/629437/8378067/377e463c-1c1f-11e5-830b-e7fc9e229a13.png)

About logs, yes i read the project wiki, why question?

**Comment by mailwl** [comment]
commit all stuff.

**Comment by mailwl** [comment]
May I reopen issue again?
When go out from home, we go in black night :(
Need more investigation. Drawing waste time, but it draw night
