### ISSUE TITLE
GLSL shaders fail to compile on AMD graphics card

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#882]
so i did post an issue regarding hardware render mode for me, however i noticed this error and so I decided to post it in hope it may help  someone with the issue

![render error](https://cloud.githubusercontent.com/assets/12820322/8313278/07c3bba0-19e2-11e5-9b00-e49167e4c19e.PNG)

**Comment by purpasmart96** [comment]
It actually depends on the game you are running, So which game were you running?

**Comment by RavenHome1** [comment]
@purpasmart96  this was done in OoT but i went ahead and tried with majoras mask and omega ruby and i tried the homebrew 3dscraft and they all returned the same error when loading so it is safe to say that AMD and citra are not getting along nicely

**Comment by purpasmart96** [comment]
@RavenHome1 
That's strange since I"m using a AMD card too.

**Comment by RavenHome1** [comment]
@purpasmart96 its hard to say that its on the games end since the homebrew returned the same error as well also maybe the ATI branch of AMD cards runs into this issue, not quiet sure

**Comment by OatmealDome** [comment]
Perhaps try updating your drivers? I have Catalyst Version "14.12 AMD Catalyst Omega Software", and OoT and 3dscraft run fine. (my graphics card is an AMD Radeon HD 6520G)

**Comment by RavenHome1** [comment]
my drivers are all updated i checked using the control center and it says all up to date

**Comment by RavenHome1** [comment]
ok nvm i fixed it as @OatmealDome mentioned it was a driver issue my driver was very outdated and the control center was only updating itself rather than the actual driver,so i no longer get an error and hardware render mode works now so this ends the issue
