### ISSUE TITLE
Fire Emblem If issues

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#887]
Every new game brings new problems. BS:EL successfully beaten, here new challenge - FEI.
The game shows black screen, with endless spam:

Service <Error> core/hle/service/service.cpp:SyncRequest:102: unknown / unimplemented PC = 0x00244220 function 'RecvDataIsReady': port=dsp::DSP, cmd_buff[1]=0x00000000
Service <Error> core/hle/service/service.cpp:SyncRequest:102: unknown / unimplemented PC = 0x00244434 function 'RecvData': port=dsp::DSP, cmd_buff[1]=0x00000000

cause ATM we don't care about a sound, we have to feed the game valuable data to exit from endless loop. (i suppose, silence is ok).

**Comment by mailwl** [comment]
Ah, forgot to mention!
the emulator should clean all TLS command buffer for unimplemented service functions, to avoid strange bugs, when input data used as output, which have different means (i.e. - input - pointer, output - integer)

**Comment by mailwl** [comment]
too hard to me, close for a while (maybe forever)

**Comment by exhalatio** [comment]
@mailwl I was merged your work, FE If is bootup, looks Initialization screen.
also more improves compatibility.
I had a really good you make a pull request.
![feif](https://cloud.githubusercontent.com/assets/7089513/10710294/318fac5c-7a8e-11e5-80e4-412cfc654f55.png)
