### ISSUE TITLE
Possibly Bad Warning at Compilation

### ISSUE THREAD

**Issue by zawata** [citra-emu/citra#889]
Upon Compilation in at least the MSVC this warning is spammed dozens(if not several dozen) times:
```
warning C4146: unary minus operator applied to unsigned type, result still unsigned
```
the warning refers to this line in vector_math.h(line 93):
```C++
    Vec2<decltype(-T{})> operator -() const
    {
        return MakeVec(-x,-y);
    }
```
In testing i managed to at least silence the error by removing the '-' in front of the 'T{}'

However bringing this warning to the attention of someone who knows what they're doing more than I, he showed a bit of concern over the error.

Neither of us knew what to really do about the warning so I decided to create a issue about it. I would have created a pull request for discussion but I didn't know what to change it to.

**Comment by mailwl** [comment]
it's not looks like a part of Citra, is it good idea to fix this code?

**Comment by neobrain** [comment]
@mailwl it very much is a part of Citra

@zawata VecN arithmetic follows the standard integer conversion rules, and as such the result of subtracting two unsigned number is unsigned. The fix would be to perform an explicit cast (using `.Cast<>())`) to a signed vector where necessary.

**Comment by mailwl** [comment]
@neobrain , Ah, github shows your real name, the same as in vector_math.h :)
header and code style differs from other citra code, so i thought it's from other project. Sorry for my mistake

**Comment by zawata** [comment]
@neobrain i cant find an exact line of code that throws the warning, all i found is 5 files that linked at the end of the warning
thus I dont know exactly where to apply the casts
the files are :
core\hw\gpu.cpp
video_core\renderer_opengl\gl_rasterizer.cpp
video_core\rasterizer.cpp
hw\y2r.cpp
video_core\debug_utils\debug_utils.cpp
there is a 6th time the warning is thrown but theres no file linked to it

**Comment by yuriks** [comment]
I've looked into this warning before and it happens because MSVC throws the warning when the Vec4 template is referenced, even if the operator- isn't ever invoked. I don't know of a good way of getting rid of it. Maybe using SFINAE to disable operator- for unsigned types, or just silencing the warning altogether.

**Comment by zawata** [comment]
we can always use 
```
#pragma warning(disable : 4146)
```

**Comment by lioncash** [comment]
I disagree disabling that warning entirely, because it *can* indicate definite bugs.

**Comment by yuriks** [comment]
If SFINAE to disable the function works to eliminate the warning, and operator- is not used for vectors with unsigned types (which would be kinda suspicious and would be something to look at) then that would be the best option. If that fails, for whatever reason, then I think using a fine-grained pragma around the function to disable the warning specifically inside it would be acceptable.

**Comment by neobrain** [comment]
Is there any particular reason for thinking this is not actually causing bugs in our code currently? Last time I checked, the cross product function as used in the rasterizer works purely by luck because two misuses of the subtraction operator compensate for each other. So uh, I don't fancy the idea of silencing the warning.

**Comment by yuriks** [comment]
This isn't the subtraction operator we're talking about here, but the negation operator.

**Comment by JayFoxRox** [comment]
Is this still an issue with the most recent version of MSVC?

**Comment by wwylele** [comment]
@JayFoxRox #1239 should have solved this.
