### ISSUE TITLE
Graphic problem with glsl-plus-hd

### ISSUE THREAD

**Issue by wynn1212** [citra-emu/citra#890]
Hi !
I'm trying to booting up OoT3d with glsl-plus-hd, but I have some graphics problem.

If I enabled Use Hardware Renderer,Use Hardware Vertex Shaders,Use High Resolution I can only see this.
![image](https://cloud.githubusercontent.com/assets/10562889/8393263/523b9502-1d3b-11e5-87d9-b97c13449a53.png)

But if I disabled three of them,I can't see anything!
![image](https://cloud.githubusercontent.com/assets/10562889/8393288/2b7688a4-1d3c-11e5-8ff4-5e0055afaf45.png)

If I use master version, it works fine.
![image](https://cloud.githubusercontent.com/assets/10562889/8393298/a1fec2e8-1d3c-11e5-90fa-06248b317c4b.png)

Here's the log for glsl-plus-hd
https://gist.github.com/wynn1212/d0044a839af4cfdd1e6c

**Comment by neobrain** [comment]
Don't report issues against unofficial trees.

**Comment by RavenHome1** [comment]
@neobrain i am not sure about this branch but  it runs OoT very good and at a very high speed,
however it completely crashed my graphic card driver on majoras mask
