### ISSUE TITLE
Vertex Shader optimization oportunities

### ISSUE THREAD

**Issue by Subv** [citra-emu/citra#891]
After some research, we came up with this patch that improves the VS interpreter performance by about 50% in the games that were tested (2048, Ocarina Of Time 3D)

https://gist.github.com/Subv/969b4800feacfab6669f

The change from std::stack to std::vector yielded by far the most performance improvement, it got rid of some calls to the underlying deque functions.

I'm sure there's more potential for optimization somewhere, but for now i'm posting this so others can make comments and post more ideas

Ping @bunnei

**Comment by Syphurith** [comment]
Sorry i'm just wondering how much it takes through those functions calls (GetXXX) and C++ cast.
Those are really safe. Please forget what i said, if you've already run cppcheck or Valgrind or gperf.

**Comment by Subv** [comment]
@Syphurith I'm not sure what you're asking, what GetXXX calls?

**Comment by Syphurith** [comment]
`GetIndex`, `GetRegisterType` and so on. Sorry for being a C programmer with unsafe behaviors.
Doesn't matter much, those GetXXX should not take too much time if not being executed mad. Those only cost you tiny time aren't they, when don't related to lock.
I suggest you to run some profiler tools with your debug build, which might be more helpful than me.

**Comment by Subv** [comment]
The generated code for GetRegisterType contains a bunch of conditional jumps, which are then repeated twice (because of inlining) in GetIndex, which are then repeated again in LookupSourceRegister. The changes there get rid of most of the abstraction.

Keep in mind that this code is called a _lot_, it's the current bottleneck of the emulator.

**Comment by Syphurith** [comment]
Then.. `GetSelectorSrc1` or `src2_selector_?.Value`? Indeed there could be many variables cachable.
Sorry i dislike C++ a lot and know no GL/Shader stuff. I suggest you to run those profiling tools, some of them may generates a call graph to let you see how much time it is wasted.

**Comment by Subv** [comment]
The GetSelectorSrcX functions were using a local variable to decide which selector to use, using srcX_selector_i directly allows the shifts and masks from BitField to be inlined.

**Comment by neobrain** [comment]
@Syphurith This is not the place for expressing your dislike of C++ and kind of obvious advice of using profilers. Please put that elsewhere.

**Comment by Syphurith** [comment]
@neobrain Thanks, i know. I'm just so sorry for being unable to help @Subv.

**Comment by Syphurith** [comment]
@Subv Well i forgot here:
```Patch
+            size_t swizz = swizzle.hex;
             float24 src1[4] = {
-                src1_[(int)swizzle.GetSelectorSrc1(0)],
-                src1_[(int)swizzle.GetSelectorSrc1(1)],
-                src1_[(int)swizzle.GetSelectorSrc1(2)],
-                src1_[(int)swizzle.GetSelectorSrc1(3)],
+                src1_[static_cast<int>((swizz >> 11) & 0x3)],
+                src1_[static_cast<int>((swizz >> 9) & 0x3)],
+                src1_[static_cast<int>((swizz >> 7) & 0x3)],
+                src1_[static_cast<int>((swizz >> 5) & 0x3)],
             };
+
             if (negate_src1) {
-                src1[0] = src1[0] * float24::FromFloat32(-1);
-                src1[1] = src1[1] * float24::FromFloat32(-1);
-                src1[2] = src1[2] * float24::FromFloat32(-1);
-                src1[3] = src1[3] * float24::FromFloat32(-1);
+                src1[0] = -src1[0];
+                src1[1] = -src1[1];
+                src1[2] = -src1[2];
+                src1[3] = -src1[3];
             }
```
To save time on negative paths, It could be changed to something like
```C
if (negative) {
//do and negative
} else {
//just do
}
```
And for this:
```C
             const bool negate_src1 = ((bool)swizzle.negate_src1 != false);
             const bool negate_src2 = ((bool)swizzle.negate_src2 != false);
```
Well comparing a value with false.. if the swizzle.negate_src1 is a class or a struct just forget this.
If you still thinks the performance doesn't meet your need, the actual problem maybe in somewhere else. However it is much bigger than just this issue.

BTW biggest part of the code looks well optimized, I can't help you. So sorry for troubles yesterday.
@neobrain Hope i don't break anything here. Sorry for what i did yesterday.

**Comment by RavenHome1** [comment]
@Subv not sure if it will help but there is an unofficial version of citra called glsl-hd-plus which have something of a sort related to vertex shader

**Comment by OatmealDome** [comment]
@RavenHome1 that's the fork where the vertex shaders run on the GPU... A bit different from what we're talking about here, the vertex shaders that run on the CPU.

**Comment by Subv** [comment]
This is not relevant anymore.
