### ISSUE TITLE
Unknown texture format: 6

### ISSUE THREAD

**Issue by mailwl** [citra-emu/citra#896]
HW.GPU <Error> video_core/debug_utils/debug_utils.cpp:LookupTexture:548: Unknown texture format: 6
Dead Or Alive Dimensions Demo

**Comment by neobrain** [comment]
Please don't submit minimal issue reports without actual information to reproduce the issue.

Please also read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html .

**Comment by mailwl** [comment]
I found by googling on http://florian.nouwt.com/wiki/index.php/CGFX_(File_Format)
Number 6 texture format is - is HILO8, have no idea, what is mean
