### ISSUE TITLE
Nearest-neighbor texture filtering mode not honored by OpenGL renderer

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#898]
gives off a weird blur and some weird smoothing on the grass while using hardware render on 3dscraft 

normal render

![normal sky](https://cloud.githubusercontent.com/assets/12820322/8430928/a3b82b06-1f35-11e5-98db-4a383ae741f0.PNG)

![normal ground](https://cloud.githubusercontent.com/assets/12820322/8430936/b0a49ffc-1f35-11e5-8eca-0ed6ed1f4713.PNG)

hardware render

![blur sky](https://cloud.githubusercontent.com/assets/12820322/8430941/b9977b8e-1f35-11e5-829a-78867ddc5827.PNG)

![blur ground](https://cloud.githubusercontent.com/assets/12820322/8430943/bf1ec3fa-1f35-11e5-8cba-a863d0adfd57.PNG)

**Comment by purpasmart96** [comment]
Not really an huge issue, since linear filtering is just being forced in the hw renderer.

**Comment by RavenHome1** [comment]
@purpasmart96 might become an issue in games where you are forced to look directly up or down

**Comment by yuriks** [comment]
Like @purpasmart96 said, this is just us not reading the texture filtering register and forcing bilinear filtering always. Easy to fix.

@RavenHome1 What???

**Comment by RavenHome1** [comment]
@yurkis i had this issue when directly looking up or down XD
