### ISSUE TITLE
Rune factory 4 - shared memory outside bounds

### ISSUE THREAD

**Issue by emmauss** [citra-emu/citra#900]
When starting up rune factory 4,i get an error saying address out of shared mem bounds.it only shows a black screen.citra doesnt crash though.here is the log;

http://pastie.org/10267786

if shared_font.bin isnt in sysdata , it says that shared_font .bin hasnt been loaded.

```
[ 944.688224] Kernel.SVC <Error> core\hle\service\apt\apt.cpp:Service::APT::GetSharedFont:81: called, but shared_font.bin has not been loaded!
```

**Comment by mailwl** [comment]
Hmm... At my branch was problem - no cfg block id=7001 flag=2, size=2 (leaded to break game execution),  after i add it, the game looks like working, with some bugs (no text on screen). And as usual very slowly on my old mac mini... (i don't commit changes, so actual branch will not work with this game)

![rf4](https://cloud.githubusercontent.com/assets/629437/8501545/387afad6-21af-11e5-816b-0d367de31f24.png)

**Comment by emmauss** [comment]
tried building your branch, and run into some errors,you included a "sys/mman.h" header in nccp.cpp, which isnt in msvs, and some of the code throws error in msvs,i want to test it on the fantasy life, and later when you commit these changes, rune factory. could you make the branch windows friendly, and substitute the header with a user defined one.

**Comment by mailwl** [comment]
Ah, yes, forgot to mention, it compiles now only on *nix, because i did mapping file instead reading whole ROM into memory. Windows not posix-compatible, so, it need some changes, i try to do it in near future (very long time did not programming for win)

**Comment by Syphurith** [comment]
@emmauss @mailwl There is [mmap-win32](https://github.com/witwall/mman-win32) project (seems to have similar prototypes) and you may use WinSDK functions (it is said those [VirtualAllocEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366781(v=vs.85).aspx) that could be used). Hope you do well.

**Comment by mailwl** [comment]
i think, there a lot of regression because of mapping, never tested it on windows, so, at this moment no need to use this branch, if not mac.
@Syphurith, i look at lib, thanks.

**Comment by mailwl** [comment]
very odd! i compile the very latest my commit on my mac in Release, and gave works like a charm, i even win the first fight.
But, on windows the same code even don't want to show any picture...

**Comment by emmauss** [comment]
@Syphurith i tried that, included it as a user defined header, with all files put in "sys" folder under src, it didnt throw any errors about missing header, but a pile of intellisence errors showed up, and my freshman year c++ knowledge aint enough to fix those.

**Comment by emmauss** [comment]
@mailwl will pull and build now.

**Comment by mailwl** [comment]
@emmauss , try to compile my latest commit, VS should eat it (file mapping off), but on my notebook even compiled don't show any pictures

**Comment by emmauss** [comment]
me too.just black screens.

**Comment by mailwl** [comment]
i will try to find the reason, i think, original citra may run the game, with some changes, with some changes, like this:
https://github.com/mailwl/citra/blob/branch-mailwl/src/core/hle/service/cfg/cfg.cpp#L210

**Comment by Subv** [comment]
You're missing the [config file from the Configuration Service savegame](http://3dbrew.org/wiki/Config_Savegame). You have to extract it from your 3DS
