### ISSUE TITLE
A Fanasy Life - infinite unknown service error

### ISSUE THREAD

**Issue by emmauss** [citra-emu/citra#901]
starting up fantasy life , and it goes on an infinite error log, with no crashes.shows only a black screen throughout.for first few secs of the logs;

http://pastie.org/10267811

**Comment by mailwl** [comment]
I think, you may forget about this game about 1 year at least.
Even if implement "frd:u" service, the game stuck on "am:app" service, which even not described on 3dbrew

**Comment by Subv** [comment]
Can you test this again please?

**Comment by emmauss** [comment]
tried it using latest master on jit and hw, still says services unimplemented.
http://pastie.org/10359846

**Comment by exhalatio** [comment]
I tested it using latest master. It had already been implemented frd:u service and working.

Screenshot here.
![fl](https://cloud.githubusercontent.com/assets/7089513/12069572/70abce92-b07c-11e5-98bf-9214e5442e1b.jpg)
