### ISSUE TITLE
Fire Emblem Awakening error - failed to get a handle for archive

### ISSUE THREAD

**Issue by Swinderjee** [citra-emu/citra#902]
When i just testing FE awakening, i get an error Saying that it failed to get a handle for archive, HW.memory error Kernel.SVC error

![issue 1](https://cloud.githubusercontent.com/assets/13171344/8505533/d84766f2-2223-11e5-843d-6c7aaa34483e.png)

![issue 2](https://cloud.githubusercontent.com/assets/13171344/8505537/e37663fc-2223-11e5-897d-25f6890a924f.png)

![issue 3](https://cloud.githubusercontent.com/assets/13171344/8505542/fa13d04a-2223-11e5-9846-7063694d1239.png)

and the last one....
![issue 4](https://cloud.githubusercontent.com/assets/13171344/8505544/0415fe38-2224-11e5-8727-9523dd3db8ca.png)

i try running it on Laptops using i3 processor and a Nvidia 720M graphic card
i couldn't figure out what is wrong since i only have basic experience on computer. 
i'm just hoping that giving this bug could help you

**Comment by mailwl** [comment]
i give up with FEIf, hard to drive it on

**Comment by neobrain** [comment]
Sorry, there's no point in these issue reports unless you can provide actual technical information of what's going on.

**Comment by yuriks** [comment]
Try #1097
