### ISSUE TITLE
Add alternative ncchinfo_gen to the Wiki

### ISSUE THREAD

**Issue by DeadlySystem** [citra-emu/citra#903]
Hi! I've ported the ncchinfo_gen.py script by archshift to C#: https://github.com/DeadlySystem/NCCHInfo
The [Decryption Wiki page](https://github.com/citra-emu/citra/wiki/Decryption) could be updated to mention this alternative for Windows users as it does not require a Python installation.

I could do the change myself but I do not want to make it look like I'm advertising my project in your repository. Feel free to include it if you like it.

**Comment by mailwl** [comment]
there is rxTools, which can decrypt roms on 3ds

**Comment by DeadlySystem** [comment]
Good to know. I gotta try that at some point. Then why not document that? Or at least mention it?

**Comment by mailwl** [comment]
sometimes it fails (in my case with 1832 - Lord of Magna: Maiden Heaven [U] [ENG]) don't know if xorpads will work, maybe key is too old, or my firmware 4.5

**Comment by archshift** [comment]
You don't need to make an issue for permission to edit the wiki. If you're unsure, don't hesitate to ask on IRC.
