### ISSUE TITLE
Implement svcOutputDebugString

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#91]
svcOutputDebugString is used for exactly what its name says - print a debug string. AFAIK it's implemented via a NOP on retail consoles, but it would be useful for debugging homebrew since it's the only efficient way to get debug information from within the emulated application. Additionally, maybe there are leftover calls to this function in commercial games which are useful to see.

Currently, this function is implemented in Citra, but for some reason the parameters it takes do not match the ones mentioned on 3dbrew (which specifies an additional integer to be passed as an argument).

Tentative "patch" for `src/core/hle/svc.cpp` here:

    void OutputDebugString(const char* string, int i) {
        NOTICE_LOG(SVC, "(%x): \"%s\"", i, string);
    }

This should be fixed for the sake of completeness.

**Comment by bunnei** [comment]
Done. Closed.

**Comment by Subv** [comment]
We are still ignoring the size, i think this string would fail on citra "Hello\0World"

**Comment by yuriks** [comment]
There's another issue for that.
