### ISSUE TITLE
Error/Issues in Gaist Crusher God (JP)

### ISSUE THREAD

**Issue by StephenAlexis** [citra-emu/citra#917]
https://www.youtube.com/watch?v=mxCAAX6p-QU

A YouTuber user named "John GodGames" boot up Gaist Crusher God(that,by the way,is my favorite game)!

The game works well,albeit slowly,but the problems are the following:
- Black characters
- No dialogues
- Muted color during cutscenes
- No Audio

Is there any way you can fix this?

**Comment by yuriks** [comment]
Please don't post issues that aren't about specific issues and without any technical information.
