### ISSUE TITLE
Hide version number from title bar for stable releases

### ISSUE THREAD

**Issue by neobrain** [citra-emu/citra#92]
A common argument for showing this information in a central place like the title bar is that when people submit bad bug reports we would at least still be able to see the version number from a screenshot they provide (if they provide one). While I personally find that argument ridiculous, there probably is a small point to it for nightly releases, however stable releases should be sufficiently different to each other that such a version number is not crucial for anything.

The reason for this change is that it just "feels wrong" to print the version number/git hash (which, might I add, is just a random string of gibberish to the average user anyway) in the title bar. Another argument is that virtually all other applications get along just fine without having to uglify their title bar like this (some of which definitely have a less advanced average user base than us).

Finally, both Microsoft's and Apple's human interface guidelines suggest against printing version information in title bars:
- http://msdn.microsoft.com/en-us/library/windows/desktop/bb246387%28v=vs.85%29.aspx implicitly by not including the version number in the window title to use for application main windows.
- https://developer.apple.com/library/mac/documentation/userexperience/conceptual/applehiguidelines/Menus/Menus.html very explicitly by saying "Don’t include the app version number in the name. Version information belongs in the About window."

Note that we currently have no way of marking "stable releases" in the source code, so this is mostly a TODO for the future.

**Comment by BreadFish64** [comment]
We no longer have plans for a stable release in the foreseeable future.
