### ISSUE TITLE
Teenage Mutant Ninja Turtles Danger of the Ooze hangs while saving data

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#952]
Hangs at this point while generating name / saving...image below:

![tnmt doto saving error](https://cloud.githubusercontent.com/assets/11453507/8785616/4e602cae-2f29-11e5-82e7-e70105366c39.PNG)

LOG: http://pastie.org/pastes/10302942/text

**Comment by mailwl** [comment]
can't find the rom.
i think, need rule to include rom number, when post issue about specific game

**Comment by neobrain** [comment]
(referring to the post that I just deleted: )

@mailwl Please don't be an idiot. (Put it to IRC if this is not clear enough for you.)

**Comment by Subv** [comment]
Try out #1302

**Comment by JohnGodgames** [comment]
https://github.com/citra-emu/citra/pull/1302 not helped

**Comment by JohnGodgames** [comment]
Fixed with https://github.com/MerryMage/citra **audio** branch

**Comment by JohnGodgames** [comment]
Fixed with https://github.com/citra-emu/citra/pull/1734
