### ISSUE TITLE
The Amazing Spider-Man / Save data could not be accessed

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#953]
I can go ingame with imported save...

![the amazing spiderman error](https://cloud.githubusercontent.com/assets/11453507/8787055/1da0fbd0-2f32-11e5-8b05-feb23f338133.PNG)

LOG: http://pastie.org/10303031

**Comment by Subv** [comment]
Mario Kart 7 has a similar problem (And Crashmo, and a lot of other games, though most don't just ragequit on you), i'm willing to bet this is related to BOSS (spotpass) savedata

**Comment by archshift** [comment]
Check if changed at all after #1085?

**Comment by JohnGodgames** [comment]
unfortunately #1085 not helped :(

**Comment by Subv** [comment]
Could you please test #1302 ?

**Comment by JohnGodgames** [comment]
It was fixed earlier... (forget to close), but there is a next issue that prevent to start playing a game
