### ISSUE TITLE
majoras mask break point

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#954]
previously, majoras mask will get to a point where you have to select a name to create a save slot and it wont display the keyboard to input name and will freeze at that point , now with newer release, the game will not display the keyboard and jump into creating the save slot, completely skipping the name input sequence and  creating a save slot. after my second second boot i was faced with this 

![major](https://cloud.githubusercontent.com/assets/12820322/8786980/0f9b9092-2f3a-11e5-890b-d10f6118a70b.PNG)

![capture2](https://cloud.githubusercontent.com/assets/12820322/8787009/323178e2-2f3a-11e5-86a5-84d38f0a75ff.PNG)

after hitting start it just crashes  with this

![capture](https://cloud.githubusercontent.com/assets/12820322/8787042/5d0421f0-2f3a-11e5-8f27-6fb6302b7776.PNG)

trying to use another save slot yields a repeat of the same thing

**Comment by Subv** [comment]
Alright, quick explanation for anyone working on this

1. The game is trying to open the software keyboard, our implementation currently doesn't allow for user input, so whenever the software keyboard comes up the game will think that the user entered the string "Citra", and resume execution normally.

2. The game is trying to access the infrared sensor to get some info from the Circle Pad Pro, this is not emulated at all yet so the game just crashes.

I think @bunnei is working on both of those things

**Comment by RavenHome1** [comment]
@Subv it is weird the keyboard is fully functional in OoT

![7](https://cloud.githubusercontent.com/assets/12820322/8787353/5342fbb2-2f3c-11e5-9359-85893a16bb93.PNG)

![9](https://cloud.githubusercontent.com/assets/12820322/8787370/5db7bd26-2f3c-11e5-9c39-24395d0cff59.PNG)

**Comment by yuriks** [comment]
The OoT keyboard is implemented by the game itself. It doesn't use the keyboard applet like ZMM does.

**Comment by archshift** [comment]
As it is this issue doesn't tell us anything other than the fact that MM calls ThrowFatalError.

**Comment by archshift** [comment]
If you'd like, you can make a different issue about the CirclePadPro causing an error, if that's what's being seen here.

**Comment by RavenHome1** [comment]
@archshift it seems the team is already aware of that issue so i do not see a need for a new issue, nevertheless if is needed then i will make an issue

**Comment by bunnei** [comment]
Please create a new issue and post a log! This is helpful to other people who are interesting in working on things in Citra but haven't memorized very "known" issue we have :)
