### ISSUE TITLE
Centipede Infestation - Crashing at HW renderer

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#955]
Centipede Infestation works at SW.In HW is crashes before ingame (loading) or when I switch from SW to HW ingame...

LOG: http://pastie.org/10303077

**Comment by archshift** [comment]
Can you get a stack trace of the crash by running it in a debugger?

**Comment by JohnGodgames** [comment]
In VS Debugger game isn't crashing...hmm

**Comment by JohnGodgames** [comment]
Tested today and it's not crashed...hmm strange.I'm closing this issue for now.
