### ISSUE TITLE
Dead or Alive Dimensions DEMO hangs at title screen (gyroscope)

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#956]
LOG: http://pastie.org/10303109

![doa dimension demo hang](https://cloud.githubusercontent.com/assets/11453507/8788157/bcce46a8-2f38-11e5-95de-0c128ab92308.PNG)

**Comment by Subv** [comment]
I don't see anything in the log that could make it hang, maybe it's just slow?

**Comment by JohnGodgames** [comment]
Fixed by #1549
