### ISSUE TITLE
Black Characters in certain games

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#958]
Gaist Crusher God - Citrace https://goo.gl/Q7VpO9

![geist](https://cloud.githubusercontent.com/assets/11453507/8788846/b5b7eb76-2f3d-11e5-9447-52d4ca7c64f6.PNG)

Senran Kagura - Shoujotachi no Shinei - Citrace https://goo.gl/5p1NQo

![senran kagura - shoujotachi no shinei](https://cloud.githubusercontent.com/assets/11453507/8788854/c6dcd876-2f3d-11e5-810f-5b4579fbc22a.PNG)

**Comment by yuriks** [comment]
Probably lack of frag lighting.

**Comment by JohnGodgames** [comment]
partially fixed by https://github.com/citra-emu/citra/pull/1264

**Comment by JohnGodgames** [comment]
fixed by #1264
