### ISSUE TITLE
LEGO Harry Potter Years 5 to 7 and other LEGO games crashes 

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#960]
LEGO Harry Potter Years 5 to 7

LOG: http://pastie.org/10303502

VS Debug pointed at *(float*)srcdata; 
https://gist.github.com/JohnGodgames/b2f89ebe4793626049fd

* also LEGO Pirates of the Caribbean, LEGO Star Wars III The Clone Wars...

**Comment by Subv** [comment]
This could be related to #775, perhaps GetPhysicalPointer is returning nullptr

**Comment by JohnGodgames** [comment]
All of LEGO games fixed by https://github.com/citra-emu/citra/pull/1394
Save data loop fixed by https://github.com/citra-emu/citra/pull/1302
