### ISSUE TITLE
CirclePadPro not functional causes game crashes

### ISSUE THREAD

**Issue by RavenHome1** [citra-emu/citra#965]
this is a recreation of the issue https://github.com/citra-emu/citra/issues/954 as requested by @bunnei 

in a nutshell due to not receiving info from the Circle Pad pro majora's mask game just gets confused and straight out crash itself

here is a full console log 

http://pastebin.com/PhLYUxHE

notice: it was not possible to obtain a log from start of the boot due to the fact that an error spam replaces the initial startup logs but the main errors that caused the crash are in there

**Comment by mailwl** [comment]
bug still exists? The game still throws error?
i tryed to implement CirclePadPro, but i don't have one, so, don't know, which exactly data should be return to game

**Comment by RavenHome1** [comment]
@mailwl the issue no longer exists but another issue with the game is that i can't select the "don't use" circle pad option. the game won't respond to me clicking the button and i tried all of the buttons on my keyboard and still nothing.

![capture](https://cloud.githubusercontent.com/assets/12820322/15469468/1113013e-20f3-11e6-9459-06531b92e0f8.PNG)

**Comment by RavenHome1** [comment]
an update, using bleeding 194 the "Don't use" button is now functional  and can bypass the screen, however the ZR key is still not functional
