### ISSUE TITLE
Why Legend of Zelda - Ocarina of Time 3D does not run?

### ISSUE THREAD

**Issue by davialmeida** [citra-emu/citra#967]
![screenshot_1](https://cloud.githubusercontent.com/assets/8466537/8811796/b68d3218-2fce-11e5-8469-1d746d981117.png)

**Comment by MoochMcGee** [comment]
It's not running because you didn't decrypt the game. And to do that, you
have to have the real game and a 3DS. Also, I can tell your copy is pirated.
