### ISSUE TITLE
Kingdom Hearts 3D - Dream Drop Distance Graphics Glitches

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#970]
![kh 1](https://cloud.githubusercontent.com/assets/11453507/8813699/a9d57ad0-3005-11e5-958a-c18061191932.PNG)

![kh2](https://cloud.githubusercontent.com/assets/11453507/8813704/b734c76c-3005-11e5-864f-f67e180cbbd8.PNG)

![kh3](https://cloud.githubusercontent.com/assets/11453507/8813713/bd32a576-3005-11e5-8e09-702fb5d184cc.PNG)

Citrace:  https://goo.gl/mMDgro

**Comment by yuriks** [comment]
Can you check if #963 solves these issues?

**Comment by JohnGodgames** [comment]
#963 not solved :(

**Comment by neobrain** [comment]
How does the sw renderer look?

**Comment by JohnGodgames** [comment]
I have spaming logs at sw renderer - Unknown stencil action 2.Anyway it's the same...

**Comment by MoochMcGee** [comment]
Check if #971 fixes it.

**Comment by JohnGodgames** [comment]
#971 not fixed it

**Comment by fuhuan416** [comment]
Why using the 'glsl-vertex-shaders'?

**Comment by TheSoraHD** [comment]
Fixed by #1059 
![sorarikukh3dcitra](https://cloud.githubusercontent.com/assets/8531824/9576848/021f941e-4fdc-11e5-8dfe-ce0256970cdb.png)

**Comment by yuriks** [comment]
Oh, huh, didn't see that one coming. Yay!

**Comment by HeroineChan** [comment]
Why like this? O.o
![untitled 3](https://cloud.githubusercontent.com/assets/16014270/11414237/f572ff94-942d-11e5-8c98-e992ae01469e.png)
