### ISSUE TITLE
Yu-Gi-Oh! Zexal - World Duel Carnival doesn't boot anymore

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#972]
There is a next old regression from  here https://www.youtube.com/watch?v=TaVyb0x7Ew0

LOG: http://pastie.org/10305226

**Comment by Subv** [comment]
Does this still hang?

**Comment by JohnGodgames** [comment]
Yes still...

**Comment by Subv** [comment]
How about now?

**Comment by JohnGodgames** [comment]
Still nothing...

**Comment by Subv** [comment]
Could you update the log with a newer one please?

**Comment by JohnGodgames** [comment]
Updated log: http://pasted.co/237599f0

Spams with:
```
[ 157.900365] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x00000058
[ 157.900468] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x00000058
[ 157.900668] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x00000058
[ 157.900888] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read32 @ 0x00000058
```

**Comment by Enverex** [comment]
Still an issue, spamms the console with...

`[  41.616467] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x000FFFE4
[  41.616471] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x000FFFE8
[  41.616476] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x000FFFEC
[  41.616481] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x000FFFF0
[  41.616486] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x000FFFF4
[  41.616491] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x000FFFF8
[  41.616496] HW.Memory <Error> core/memory.cpp:Read:181: unmapped Read32 @ 0x000FFFFC`

Seems seems to work its way from 0 up to 0x000FFFFC before it just stops.

**Comment by suelo50** [comment]
no boot stiil

**Comment by JohnGodgames** [comment]
Boots on https://github.com/citra-emu/citra/commit/3174bfd50c69dfa523671b96448113996a0bc42c
