### ISSUE TITLE
Frontend error

### ISSUE THREAD

**Issue by brimaster20000** [citra-emu/citra#976]
![bandicam 2015-07-21 22-28-42-532](https://cloud.githubusercontent.com/assets/13445120/8817354/f7201c22-2ff7-11e5-93a8-9e334c925ced.png)

Every game i open does this error I'm not sure how to fix it?

**Comment by archshift** [comment]
Your game is encrypted. Follow https://github.com/citra-emu/citra/wiki/Decryption to decrypt it.
