### ISSUE TITLE
Outdated wrap modes and tex filter modes in the hw renderer

### ISSUE THREAD

**Issue by Subv** [citra-emu/citra#978]
The hardware renderer is currently binding the wrap_s, wrap_t, min_filter and mag_filter values to the textures only when they're first created, this leads to graphic artifacts if a game changes these values without flushing the texture.

@yuriks suggested using OpenGL Sampler objects but those are available only in OpenGL 3.3+

Pic of the bug
HW renderer
![hw](http://i.imgur.com/5igdRI5.png)

SW renderer
![sw](http://i.imgur.com/hCkudDs.png)

**Comment by yuriks** [comment]
This can be done without Sampler Objects, but it would be an incomplete solution (in case the game binds the same texture to two different units with different settings).

I think we should just upgrade to OpenGL 3.3, which apparently has been supported on OS X for a while. (I wasn't aware of this.) We should do this after we start using libepoxy for function loading.

**Comment by hrydgard** [comment]
Our workaround for this issue in PPSSPP is to for each texture keep track of the wrap modes it was last set to, and when the texture is used check that the current global wrap modes are set such, if not, call glTexParameter etc to fix it with the texture bound. Mostly, a texture is always used with the same wrap mode set as the last time, so this results in very few glTexParameter calls.

But yes, sampler objects are indeed the "correct" solution if you target only GL 3.3+.

**Comment by RavenHome1** [comment]
my input on this may be pointless but i suggest going  for opengl 3.3+ , and if anyone to complain why emulator wont work anymore then they should know better than using a potato intel graphic cards on an emulator

**Comment by yuriks** [comment]
The intention is already to upgrade to 3.3. We're waiting on the change to libepoxy for entrypoint loading. (Not worth updating our current generated loader to 3.3 if it's going to be replaced later.)
