### ISSUE TITLE
andriod port

### ISSUE THREAD

**Issue by asbel123** [citra-emu/citra#984]
can u do andriod version because drastic ds emulator did support high reslotuion 3d today on google play store its fullspeed on my samsung galaxy s4 he did better than desume. because arm support is better than pc now. 3ds is arm cpu will be better on andriod or not. 

one game on andriod is dragon quest 8 has shaders simmaliar to 3ds on xenoblade chronicles on the characters.

**Comment by yuriks** [comment]
Citra isn't even *near* running at decent speed on powerful PCs, and won't be helped any by being on an ARM CPU, so no.

**Comment by loganpaul2018** [comment]
> can u do andriod version because drastic ds emulator did support high reslotuion 3d today on google play store its fullspeed on my samsung galaxy s4 he did better than desume. because arm support is better than pc now. 3ds is arm cpu will be better on andriod or not.
> 
> one game on andriod is dragon quest 8 has shaders simmaliar to 3ds on xenoblade chronicles on the characters.

now you can play in android if you have android 8
